### ISSUE TITLE
Add documentation for edge core modules

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#100]
This is an umbrella issue to describe how each beehive module in kubeedge works.
The expected output is a document which details the responsibilities of the module , its interfaces with other modules etc.

**Comment by m1093782566** [comment]
Reopen this issue for tracking remaining modules.

**Comment by m1093782566** [comment]
oops, reopening for tracking remaining modules, e.g. edged, devicetwin...

**Comment by m1093782566** [comment]
@sids-b @rohitsardesai83 

Can you help find a guy writing edged document?

**Comment by sids-b** [comment]
@samy2019 , Can you please help in closing this ?

**Comment by m1093782566** [comment]
Closing this issue in favor of #220
