### ISSUE TITLE
Need add a CI job to check the vender after change to go mod

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1012]
Add a  CI job to check the vender, need to check:

- go module relate files, like go.mod/go.sum

- the vender files

**Comment by subpathdev** [comment]
What do you think should the ci job do?  (@fisherxu )

**Comment by fisherxu** [comment]
@subpathdev  Can refer to the implementation in kubernetes :) [Verify-vender.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-vendor.sh)

**Comment by sids-b** [comment]
This job will be similar to the dep check job we had. We use go mod instead.
Thanks @subpathdev for taking it up :)
