### ISSUE TITLE
Sync service, endpoint, pods behind service to all nodes  is very inefficient and unnecessary

### ISSUE THREAD

**Issue by anyushun** [kubeedge/kubeedge#1013]
**What happened**:
We need sync service and pods behind it to node for service discovery and loadbalance in edgemesh, we don't know which node needs which services, so we sync service and pods behind it to all nodes. This is very inefficient and unnecessary

**What you expected to happen**:
Sync service and pods behind it to nodes that really needs the service

**How to reproduce it (as minimally and precisely as possible)**:
Design defect

**Anything else we need to know?**:

**Environment**:
- KubeEdge version: v1.0.0
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by anyushun** [comment]
How to resolve it?
**Precondition:**
1. EdgeController create CRD NodeService(means **Node** that needs access to the **Service**)
```
type NodeServiceSpec struct {
    Node   string
    Service string
}
```

**Query service and pods behind it:**
1. EdgeMesh query service and pods behind it from edgecontroller when client pod access a domain name like ```{name}.{namespace}.svc.{cluster}```
2. EdgeController create NodeService when receive query service or pods behind service
3. Response to EdgeMesh(service and pods behind it when found, NotFound type message when not found, metamanager do not save it)

**Sync service and pods behind it:**
1. EdgeController watch NodeService and cache as 
```
sync.Map{
    "service.namespace/service.name": []string{"node.name"},
}
```
2. Controller watch service and endpoint. Get all nodes from cache and then sync service and pods behind it to these nodes

**Comment by anyushun** [comment]
@qizha

**Comment by sids-b** [comment]
There maybe some problems with this approach, I had discussed with @qizha earlier,

1) If a node is offline, it will not be able to resolve the request.
2) Multiple query to cloud for resolving a single service(Since metaManager does not save the metadata). There will always be a need for edge node to query the cloud as the node doesn't know the latest endpoints/pod behind the service. This may increase a lot of traffic.

**Comment by anyushun** [comment]
Hi Sid, I updated the comment and didn't describe it clearly last time.

> 3. Response to EdgeMesh
    1. Service and pods behind it when found, meatamanager save it
    2. NotFound type message when not found, metamanager do not save it

Your questions:
1. MetaManager send query message to cloud when not found in local storage. If node is offline, There are two situations, no matter what kind of situation, it is the same as the current performance:
    1. Service and pods behind it not found in local storage, query message can not be sent to cloud, DNS resolve with failure
    2. Service and pods behind it can found in local storage(maybe the old version), use the old service and pods behind it
2. EdgeController create NodeService when first query come. EdgeController watch NodeService and cache node <-> service map in memory. On the other hand, EdgeController watch service and endpoint, sync service and pods behind it when service and endpoint changed, this will stay up to date

**Comment by sids-b** [comment]
@anyushun as per our offline discussion, If the node becomes offline before querying any service. The calls will always fail. Closing this issue for now. Please reopen for further discussion.
