### ISSUE TITLE
Compiling bluetooth failed in e2e test

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#1015]
**What happened**:
Compiling bluetooth failed in travis e2e test

**What you expected to happen**:
not failing

**How to reproduce it (as minimally and precisely as possible)**:
https://api.travis-ci.org/v3/job/569822771/log.txt
(search for: "Compiling bluetooth..." or "Failed to compile bluetooth")

**Anything else we need to know?**:
This happens in PR #856.

**Comment by sids-b** [comment]
@subpathdev , Does this issue still exist ?
