### ISSUE TITLE
Why we need 2 same deviceprofile.json in k8s configmap & devicemapper?

### ISSUE THREAD

**Issue by jwzl** [kubeedge/kubeedge#1021]
1)When Add a device into k8s cluster,  the deviceprofile.json would be stored in configmap.
2) When run a mapper in edge sides,  the deviceprofile.json file(same as step 1) is needed!

I think we should Maintain only one deviceprofile.json in edgesides(mapper), If the app needs these information, these information can be reportted  to app. 

In addition， the deviceprofile.json has a little complicated，whether we can improve a little?

**Comment by jwzl** [comment]
@sujithsimon22  @sids-b  @rohitsardesai83 @subpathdev @fisherxu @edisonxiang
I hope we can discuss this topic, thanks!

**Comment by sids-b** [comment]
@jwzl , the deviceProfile.json in mapper is the same configmap which is created when device is added. It is volume mounted in the pod.

**Comment by sujithsimon22** [comment]
@jwzl Adding on to what @sids-b said, we currently maintain only 1 copy of deviceprofile.json as a configmap on the edge, the various mapper appliations which are deployed on the edge can make use of it by volume mounting the config map into its pod

**Comment by jwzl** [comment]
@sids-b  @sujithsimon22  If the mapper in docker,  this is no problem.
But in some case,  the mapper need run anthor device  that can't  support  docker, then, the mapper's runtime is not belong to K8s cluster,  and  deviceprofile.json has 2  copy.
