### ISSUE TITLE
There is something wrong in file "cloudhub.md"

### ISSUE THREAD

**Issue by alien19880726** [kubeedge/kubeedge#1023]
**What happened**: There is something wrong in file "cloudhub.md"

**What you expected to happen**: Guide documents provide correct description to prevent learner from being misleaded.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

There is something wrong in file "cloudhub.md", I have never seen "SetReadDeadline" interface is called.
Read message from edge:
First a deadline is set for keepalive interval
Then the JSON message from connection is read
After that Message Router details are set
Message is then converted to event object for cloud internal communication
In the end the event is published to EdgeController

**Comment by soolaugust** [comment]
I agree, It seems only handle writing message now.

**Comment by sids-b** [comment]
Thanks @alien19880726 . Can I you please raise a PR to fix this issue ?
