### ISSUE TITLE
log info is self-contradictory

### ISSUE THREAD

**Issue by alien19880726** [kubeedge/kubeedge#1025]
**What happened**:
![image](https://user-images.githubusercontent.com/47560998/63003173-3ab26b80-beaa-11e9-97ec-938408fb7887.png)

**What you expected to happen**:there is nothing wrong in the log info

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by kadisi** [comment]
@alien19880726 , thank you for your issue,  we need continue this loop when we find unsupported operation. https://github.com/kubeedge/kubeedge/blob/45fb42520b3022ad53132f5140c803f03f8a8122/cloud/pkg/edgecontroller/controller/upstream.go#L571

**Comment by alien19880726** [comment]
> @alien19880726 , thank you for your issue, we need continue this loop when we find unsupported operation.
> 
> https://github.com/kubeedge/kubeedge/blob/45fb42520b3022ad53132f5140c803f03f8a8122/cloud/pkg/edgecontroller/controller/upstream.go#L571

Maybe you do not get my words, one line indicates this operation cannot be processed, while another line indicates process successfully in the following logs. I think the second line should be removed.
2019-08-06 19:48:13.574 +08:00 [0;34mINFO[0m controller/upstream.go:571 message: 0130cbc8-c97d-4fc2-8f6d-c988e40dc64a **process failure**, service operation: response unsupported
2019-08-06 19:48:13.574 +08:00 [0;34mINFO[0m controller/upstream.go:573 message: 0130cbc8-c97d-4fc2-8f6d-c988e40dc64a **process successfully**
