### ISSUE TITLE
There is sth wrong  in syncPodStatus fuction of metaManager module

### ISSUE THREAD

**Issue by alien19880726** [kubeedge/kubeedge#1029]
**What happened**: There is sth wrong  in syncPodStatus fuction of metaManager module. Pod's namespace is inevitably empty at the first time, so that its namespace will be kube-system forever while it actually is default.
![image](https://user-images.githubusercontent.com/47560998/63080324-47e75d00-bf73-11e9-820a-8bc91ebfc630.png)
![image](https://user-images.githubusercontent.com/47560998/63080353-64839500-bf73-11e9-96dd-2292dd83ecd8.png)
![image](https://user-images.githubusercontent.com/47560998/63080386-7ebd7300-bf73-11e9-890e-acde9bd6a6d6.png)
![image](https://user-images.githubusercontent.com/47560998/63080467-b88e7980-bf73-11e9-9fa1-f43d201b644f.png)
![image](https://user-images.githubusercontent.com/47560998/63080511-d8be3880-bf73-11e9-8066-f7fce262245a.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by sids-b** [comment]
@alien19880726 , can you please share steps to reproduce this issue ?

**Comment by alien19880726** [comment]
> @alien19880726 , can you please share steps to reproduce this issue ?

After I deployed KubeEdge environment, there is already such the problem
