### ISSUE TITLE
Flaky integration test:  [Fail] Event Bus Testing Publish on eventbus topics throgh MQTT internal broker [It] TC_TEST_EBUS_6: change the device status to online from eventbus 

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#103]
```
[Fail] Event Bus Testing Publish on eventbus topics throgh MQTT internal broker [It] TC_TEST_EBUS_6: change the device status to online from eventbus 
```

cc @pavan187

**Comment by m1093782566** [comment]
@pavan187 

```
[Fail] Event Bus Testing Publish on eventbus topics throgh MQTT internal broker [It] TC_TEST_EBUS_6: change the device status to online from eventbus 


------------------------------
• Failure [10.001 seconds]
Event Bus Testing
/go/src/github.com/kubeedge/kubeedge/test/integration/modules/edgecore/eventbus/eventbus_test.go:85
  Publish on eventbus topics throgh MQTT internal broker
  /go/src/github.com/kubeedge/kubeedge/test/integration/modules/edgecore/eventbus/eventbus_test.go:89
    TC_TEST_EBUS_6: change the device status to online from eventbus [It]
    /go/src/github.com/kubeedge/kubeedge/test/integration/modules/edgecore/eventbus/eventbus_test.go:152

    Expected
        <string>: unknown
    to equal
        <string>: online

    /go/src/github.com/kubeedge/kubeedge/test/integration/modules/edgecore/eventbus/eventbus_test.go:168
```

Please check https://circleci.com/gh/kubeedge/kubeedge/631 for more details.

**Comment by sids-b** [comment]
![ci fail](https://user-images.githubusercontent.com/30088497/51594637-e8642a00-1f1a-11e9-972e-636f0f1449da.png)

**Comment by m1093782566** [comment]
@sids-b 

Do you mean there is a potential deadlock?

**Comment by sids-b** [comment]
I think we are facing some issue with CI @srivatsav123 and @pavan187 can you guys co-ordinate for the same ?
cc @m1093782566 @rohitsardesai83

**Comment by sids-b** [comment]
> @sids-b
> 
> Do you mean there is a potential deadlock?

I am not sure. We had similar issue when integration tests failed once with similar timeout message. We tested on local environments and it is passing. Need to dig more on this

**Comment by sids-b** [comment]
![devicetwin](https://user-images.githubusercontent.com/30088497/51595493-da170d80-1f1c-11e9-9340-ef74f1c1872b.png)
Looks like a deadlock after running tests of dtclient, dtmodule and dtcommon. Same place it is stuck 2 times. @lidiyag @pavan187 @srivatsav123 , Please lets get it resolved quickly.

**Comment by sids-b** [comment]
https://circleci.com/gh/kubeedge/workflows/kubeedge/tree/pull%2F104
Link for your reference

**Comment by sids-b** [comment]
@m1093782566 , we have resolved the integration test issue and also identified the deadlock was because of the test file added in PR. I think we can close this now ?

**Comment by m1093782566** [comment]
Okay, let's close this issue :)
