### ISSUE TITLE
pod卡在ContainerCreating状态

### ISSUE THREAD

**Issue by qiuhui** [kubeedge/kubeedge#1030]
我按照官方文档安装好cloud端和edge端，执行kubectl get nodes看到edge的状态是ready。执行kubectl apply -f deployment.yaml后，查看pod状态一直是ContainerCreating，以下是我的编排文件和命令执行输出.
![image](https://user-images.githubusercontent.com/3477024/63081823-32743200-bf77-11e9-890a-06f303861b62.png)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 10.8.207.42:60012/library/nginx:1.9.6
        ports:
        - containerPort: 8200
          hostPort: 8200
注：镜像是提前准备好的，手动用docker run执行可以启动

**Comment by qiuhui** [comment]
edgecore的log打印很多类似信息
![image](https://user-images.githubusercontent.com/3477024/63081980-9860b980-bf77-11e9-84cb-52bdc1b638fb.png)
我的kubernetes版本是1.12.4, docker版本是18.06.1，kubeedge版本是1.0

**Comment by fisherxu** [comment]
@qiuhui Now the kubernetes version for kubeedge v1.0 is 1.15+ , maybe could have a try :)

**Comment by fisherxu** [comment]
In your log, seems the edged version is kubelet-v1.15.0-kubeedge-v1.0.0.

**Comment by sids-b** [comment]
@qiuhui , Is this issue resolved ?

**Comment by fisherxu** [comment]
Close it, if there's any question, please reopen it.
/close
