### ISSUE TITLE
[cross-compile for ARM]   use yocto sdk to build edge_core 

### ISSUE THREAD

**Issue by jwzl** [kubeedge/kubeedge#1051]
go build cmd/edge_core.go
# net
/snap/go/4289/src/net/cgo_linux.go:10:19: fatal error: netdb.h: No such file or directory
compilation terminated.
# os/user
/snap/go/4289/src/os/user/cgo_lookup_unix.go:20:20: fatal error: unistd.h: No such file or directory
compilation terminated.
# github.com/kubeedge/kubeedge/vendor/github.com/opencontainers/runc/libcontainer/system
../vendor/github.com/opencontainers/runc/libcontainer/system/sysconfig.go:6:20: fatal error: unistd.h: No such file or directory
compilation terminated.
# github.com/kubeedge/kubeedge/vendor/github.com/coreos/pkg/dlopen
../vendor/github.com/coreos/pkg/dlopen/dlopen.go:20:21: fatal error: stdlib.h: No such file or directory
// #include <stdlib.h>
                    ^
compilation terminated.
# github.com/kubeedge/kubeedge/vendor/github.com/mindprince/gonvml
../vendor/github.com/mindprince/gonvml/bindings.go:22:19: fatal error: dlfcn.h: No such file or directory
compilation terminated.
# plugin
/snap/go/4289/src/plugin/plugin_dlopen.go:11:19: fatal error: dlfcn.h: No such file or directory
compilation terminated.
# github.com/kubeedge/kubeedge/vendor/github.com/mattn/go-sqlite3
../vendor/github.com/mattn/go-sqlite3/backup.go:14:20: fatal error: stdlib.h: No such file or directory
I use the crosscompile provided by yocoto,
When I set CC=arm-poky-linux-gnueabi-gcc -march=armv7-a -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/opt/fsl-imx-x11/4.1.15-2.0.0/sysroots/cortexa9hf-neon-poky-linux-gnueabi
I guess that go  just only see CC=arm-poky-linux-gnueabi-gcc, and ignore others
@Jan Unterbrink
When cgo is enabled， how to specify sysroot ？

**Comment by jwzl** [comment]
finally, I add CGO_CFLAGS to pass sysroot to the gcc. and finished the compile
And I found the GCC version must >= 6/7
GCC 5 use collect and go compiler can't support ld and just support gold as linker.

**Comment by jan** [comment]
@jwzl I am not super sure, but you will sure figure it out!

**Comment by sids-b** [comment]
@jwzl , Is this issue resolved ?

**Comment by sids-b** [comment]
Closing this issue. Please feel free to reopen or ping on slack for further discussion.
