### ISSUE TITLE
git describe --tags show wrong information

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1055]
**What happened**:
when i exec `git describe --tags ` ：

it out ：
```
#git describe --tags
v0.3.0-beta.0-586-g4cf04771
```

**What you expected to happen**:

it should show `v1.0.0-**` tag  information

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:  v1.0.0 commit: 4cf04771e436903f31f50733e2d1cea3b10903f6
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

cc @kevin-wangzefeng @sids-b @rohitsardesai83 @fisherxu @subpathdev

**Comment by fisherxu** [comment]
@kadisi  Because the v1.0.0 tag is not from master branch before, we have update it now :) PTAL

**Comment by kadisi** [comment]
@fisherxu , thank you , after i delete my local v1.0.0 tag  and fetch again,  it works.
