### ISSUE TITLE
KubeEdge should pass the k8s conformance tests

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#1061]
**What would you like to be added/modified**:

KubeEdge should pass the k8s conformance test.

**Why is this needed**:

Passing conformance tests gives the below advantages.
1) No need to define the feature set supported by KubeEdge
2) Allows adopters/vendors to easily evaluate KubeEdge features

We can still continue to have separate api-versioning of all the features as we have modify the data flow. But in future we can try to achieve the stability of k8s to not have seperate versioning.

**Comment by sids-b** [comment]
Thoughts ? @kevin-wangzefeng @qizha @rohitsardesai83 @CindyXing @fisherxu @dims @subpathdev @edisonxiang @kadisi @chendave @Baoqiang-Zhang @anyushun

**Comment by kevin-wangzefeng** [comment]
We do need to run conformance tests, which is very helpful to identify whether any useful funcionalities from kubelet is broken in KubeEdge.

But we still need to clarify to feature set that KubeEdge offers, and tell users, adopters about our understanding on building platform for containers.

These are just twon different things, we don't need to mix them together.

**Comment by sids-b** [comment]
Anyone interested to run and share the report of conformance tests ?

**Comment by sids-b** [comment]
Thanks @fisherxu for volunteering !
