### ISSUE TITLE
Script in doc not found

### ISSUE THREAD

**Issue by gzqx** [kubeedge/kubeedge#1062]
I am not quite sure which category this issue should be labeled with and if it is a disturbance I apologize in advance

**What happened**:
When trying to install kubeEdge with minikube following [DOC](https://kubeedge.io/en/docs/getting-started-minikube/), both two provided scripts [script_1](https://raw.githubusercontent.com/Kubeedge/Kubeedge/${Kubeedge_TAG}/scripts/download.sh) and [script_2](https://raw.githubusercontent.com/Kubeedge/Kubeedge/${Kubeedge_TAG}/scripts/setup-minikube.sh) couldn't be found.
**What you expected to happen**:
Get them successfully.
**How to reproduce it (as minimally and precisely as possible)**:
By applying according to the doc:
```
export Kubeedge_TAG=v0.3.0
curl -O https://raw.githubusercontent.com/Kubeedge/Kubeedge/${Kubeedge_TAG}/scripts/setup-minikube.sh
```
**Anything else we need to know?**:

**Environment**:
- KubeEdge version:0.3.0
- Hardware configuration:
- OS (e.g. from /etc/os-release):macOS & ubuntu
- Kernel (e.g. `uname -a`):
- Others:

**Comment by subpathdev** [comment]
This website is also missing: https://kubeedge.io/docs/started/getting-started-gke/#understanding-the-deployment-process
