### ISSUE TITLE
Add a script to run kubeedge on one VM

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1077]
**What would you like to be added/modified**:
Add a script which run kubeedge on one VM, which can be used to develop test and e2e test in CI.
Xref: [the k8s local-up-cluster script](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh)

The k8s cluster can started used the [kind](https://github.com/kubernetes-sigs/kind), the kubeedge components run in the VM as process 

**Why is this needed**:
Used  for development testing.

**Comment by sids-b** [comment]
Good idea @fisherxu . I think @sujithsimon22 is doing something similar in this PR #856
