### ISSUE TITLE
edgecore issue in  ARM

### ISSUE THREAD

**Issue by jwzl** [kubeedge/kubeedge#1080]
**Environment**:
- KubeEdge version:  v1.15.0-kubeedge-v1.0.0
- Hardware configuration:  ARM imx6q soc
- OS (e.g. from /etc/os-release):  
ID="arago"
NAME="Arago"
VERSION="2019.05"
VERSION_ID="2019.05"
PRETTY_NAME="Arago 2019.05"
- Kernel (e.g. `uname -a`):   4.1.15-2.0.0

**How to reproduce it (as minimally and precisely as possible)**
When I cross compile the edgecore for arm, and run edgecore to connect the cloudcore, everything is okay.
**But when I deploy a nginx to arm sides, there are 3 issues:** 
  **1)  docker pull image is always failed, but I can run "docker pull" commandline to pull image**
      It cause that the deployment  is always in pending states.

**2)The pod  is still Terminating status ,  if I have delete the deployment object**  
and in the edge sides, I use docker ps -a :
4caddb7733da        e09f192863c9             "nginx -g 'daemon of…"   23 minutes ago      Exited (1) 21 minutes ago                       k8s_nginx_nginx-deployment-947d67f6c-bjx7c_default_2508ed6a-ca2e-11e9-9499-000babb6f874_14
57dfd39ad4b5        e09f192863c9             "nginx -g 'daemon of…"   25 minutes ago      Exited (1) 23 minutes ago                       k8s_nginx_nginx-deployment-947d67f6c-bjx7c_default_2508ed6a-ca2e-11e9-9499-000babb6f874_13
f680c21f3434        e09f192863c9             "nginx -g 'daemon of…"   2 hours ago         Up 2 hours                                      k8s_nginx_nginx-deployment-947d67f6c-bjx7c_default_2508ed6a-ca2e-11e9-9499-000babb6f874_0
88fcb1a16360        kubeedge/pause-arm:3.1   "/pause"                 2 hours ago         Up 2 hours                                      k8s_POD_nginx-deployment-947d67f6c-bjx7c_default_2508ed6a-ca2e-11e9-9499-000babb6f874_0
**But indeed, I have deleted the nginx-deployment **

**3) When pod in edge node are in error states  such as : in Terminating states;   Other deployments on this node will be blocked. If you deploy other apps to this node, it will block. until this error disappears, the deployment will be deployed normally**

Best Regards
Qing

**Comment by jwzl** [comment]
@fisherxu @kadisi @subpathdev @sids-b  Thanks!

**Comment by sids-b** [comment]
@jwzl , apologies for late response. We have tried deploying simple nginx app one RPi(ARM) all the create/delete functionality seems to work fine. Can you please try once with this deployment file ? https://github.com/kubeedge/kubeedge/blob/master/build/deployment-armv7.yaml

**Comment by jwzl** [comment]
@sids-b  I also used this same deployment file (as you described) and has these failure.

**Comment by subpathdev** [comment]
@jwzl
to your second point you could execute `kubectl delete pod <pod name> --force --grace-period 0` to remove the pod instantly from the cloud

to your first point could you please add the output of  `kubectl describe pod <pod name>, where <pod name> ist your executed nginx pod? Can you add the log file of the edgecore and the cloudcore too?

**Comment by jwzl** [comment]
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
Error from server (NotFound): pods "wordpress-69544d7b48-zfqd4" not found

**Comment by jwzl** [comment]
but in edged.go +700
`	// Restart the pod is foolish in there, it cause the  container can't  be deleted forever.
					klog.Errorf("sync loop get event container died, restart pod [%s]", pod.Name)
					key := types.NamespacedName{
						Namespace: pod.Namespace,
						Name:      pod.Name,
					}
					e.podAdditionQueue.Add(key.String())
`
When container is removed , then  this logic will restart it, It's very terrible, and you can check syncLoopIteration  in k8s implenmtion.

**Comment by subpathdev** [comment]
today I have removed a few times a container which on the described way and didn't had any problems by doing this. Yes I know this isn't the best way but when a container could not be deleted in another way we have force delete it.

> warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
Error from server (NotFound): pods "wordpress-69544d7b48-zfqd4" not found

Your error message here says, that the pod wordpress... could not be found -> it could not be removed

**Comment by subpathdev** [comment]
> bug in edged.go +700
> ` // Restart the pod is foolish in there, it cause the container can't be deleted forever. klog.Errorf("sync loop get event container died, restart pod [%s]", pod.Name) key := types.NamespacedName{ Namespace: pod.Namespace, Name: pod.Name, } e.podAdditionQueue.Add(key.String()) `
> When container is removed , then this logic will restart it, It's very terrible, and you can check syncLoopIteration in k8s implenmtion.

I have tested this issue and on my system the container is successfully removed (checked  in 2 executions) but I run into an different issue, the k8s api server didn't  register that this pod is removed and the pod hang into the terminated state.  But on a different operation system this could be handled  in a different way. (I have tested with an minikube (as cloud) and an ubuntu vm as edge).

**Comment by jwzl** [comment]
Finally， I changed the the docker to a new version(19.0.3) in arm, all is okay! Thanks very much!
And My system spec as below:
CPU:  imx6 soc
Memory: 1G
Disk Size: 8G
System OS : yocto 2.1 Linux
 
Kubeedge has been ported to imx6 soc successfully.

**Comment by sids-b** [comment]
Thanks for the information @jwzl . It would be great if you could write a small document for any system configuration changes or any kubeedge env changes you had to do to make it work.
