### ISSUE TITLE
move beehive and viaduct into kubeedge main respository

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1082]
**What would you like to be added/modified**:

i suggest to move  beehive and viaduct into kubeedge main respository.

**Why is this needed**:

now , beehive and viaduct are only imported by kubeedge main respository. If we add new features or bugfix to beehive and viaduct, it will be more difficult to merge into kubeedge main respository.  currently, beehive and viaduct are also lack of complete unit test.  there are not very good integration test with kubeedge.

so i suggest to move beehive and viaduct into kubeedge `staging/src/kubeedge.io` dir like [kubernetes](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io). and developed together with kubeedge main respository.

This will speed up the development and testing of the kubeedge project.

cc @kevin-wangzefeng @sids-b @fisherxu @rohitsardesai83 @subpathdev @CindyXing

**Comment by kadisi** [comment]
if we  don't want to sync to the[ beehive library](https://github.com/kubeedge/beehive) regularly， we can only move into kubeedge `pkg` dir.  But I don't think it's necessary to set beehive as a separate library.

**Comment by edisonxiang** [comment]
Actually it is very good suggestion.
I have ever came across this same problem.
When we need to modify some thing in beehive,
firstly we need to update beehive and then update kubeedge vendor.

**Comment by kevin-wangzefeng** [comment]
The individual repos turn out not that useful as we expected, I agree to move code into the main repo to improve developer experience.
And even if we host beehive under `pkg`, there are still ways to sync code history to a separate repo for external/downstream uses (just in case).
Let's make it during next release.

/assign

**Comment by fisherxu** [comment]
+1, that will improve developer experience and easier to test

**Comment by subpathdev** [comment]
+1

**Comment by rohitsardesai83** [comment]
+1

**Comment by sids-b** [comment]
Thanks @kadisi . It is a very good point

**Comment by kadisi** [comment]
@kevin-wangzefeng @fisherxu @rohitsardesai83 @subpathdev @edisonxiang  Do we need to move [example](https://github.com/kubeedge/examples) repo to the main repo as well ?

I suggest that the example  should try to reference the kubeedge code instead of copying it.
such as  [MsgTwin](https://github.com/kubeedge/examples/blob/ec42e72b6bcc272a4f2f50900c104d7c375f551b/led-raspberrypi/light_mapper.go#L82) 

If user simply looks at this code, the user does not know why the struct is designed like this.
if we move example to main repo, we can also  keep in sync with the features of the main repo。

**Comment by subpathdev** [comment]
I like the examples in a separate repo but I didn't have a strong opinion on this. Perhaps we can add a link to the examples in the README.md in the root directory of this repo.

**Comment by sids-b** [comment]
I think the examples repo could still continue to be a seperate repo. The examples only use kubeedge and are applications deployed or developed using kubeedge. They don't have any relation with the source code kubeedge.

**Comment by kevin-wangzefeng** [comment]
As beehive and viaduct moved intree, extra commands need to be executed after "go mod vendor", to keep the symbol links in vendor (linked to the staging repos). I will create another PR to fix this.

**Comment by fisherxu** [comment]
We have moved beehive and viaduct in-tree.
/close
