### ISSUE TITLE
Move all the compiled binary and container image to KUBEEDGE_ROOT/_output

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1086]
**What would you like to be added/modified**:
Move all the compiled binary and container image to KUBEEDGE_ROOT/_output

**Why is this needed**:
Consider improve Makefile and move all binary and container image  to a unified folder, KUBEEDGE_ROOT/_output.

**Comment by kadisi** [comment]
agree

**Comment by sids-b** [comment]
Umm, maybe we need to move the conf/ folder along with it as the binary will search for conf/ folder. Another option is to set the Goarchaius_config_path environment variable

**Comment by kadisi** [comment]
I think the configuration file can be moved to `/etc/kubeed/conf` in the future

**Comment by fisherxu** [comment]
> I think the configuration file can be moved to /etc/kubeed/conf in the future

Agree, and through a option field to find the config file instead of the Goarchaius_config_path environment variable

**Comment by sids-b** [comment]
Looks good to me

**Comment by fisherxu** [comment]
We have resolve it now.
/close
