### ISSUE TITLE
using .deb package to install KubeEdge

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#1095]
**What would you like to be added/modified**:
We can build a debian package (.deb) to install edgecore [and, or] cloudcore on debian based machines. The package could be placed by the other releases and could be installed with `dpkg -i edgecore.deb`

**Why is this needed**:
Easier way to install edgecore [and, or] cluodcore on debian based operation systems

**Comment by kadisi** [comment]
Do we need to also support the rpm package?

**Comment by subpathdev** [comment]
I didn't have any experience with the creation of rpm packages :(

**Comment by fisherxu** [comment]
Thanks! @subpathdev We need clear documentation and methods for how to install kubeedge in future :)

**Comment by bitvijays** [comment]
Pull Request https://github.com/kubeedge/kubeedge/pull/1565 should fix this.

**Comment by rzr** [comment]
As a debian maintainer I can help on this I know the procedures already

https://qa.debian.org/developer.php?login=rzr@users.sf.net

Let me cross link related issues:



https://github.com/kubeedge/kubeedge/pull/2234
