### ISSUE TITLE
Edgemesh panic 

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1097]
**What happened**:
![image](https://user-images.githubusercontent.com/28776356/64246817-1ba27900-cf40-11e9-9452-e211647afe8a.png)

**What you expected to happen**:
Judge the slice.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by arcanique** [comment]
@

> /cc @anyushun @arcanique

@fisherxu  Is not creating a service without a specified port？ The code is not judged here, there is a question. I will fix it.

**Comment by fisherxu** [comment]
> @fisherxu Is not creating a service without a specified port？ The code is not judged here, there is a question. I will fix it.

yes, I run a e2e test, and paniced, we need to fix it. Thanks @arcanique

**Comment by arcanique** [comment]
@fisherxu I submitted a fixed PR. Please review，thanks
