### ISSUE TITLE
Reuse e2e tests from upstream (K8s)

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1101]
**What would you like to be added/modified**:
Add e2e tests from upstream (K8s) to kubeedge.

**Why is this needed**:
We need  to reuse e2e tests from upstream to help check k8s releated features; and add them to the PR checks.

**Comment by sids-b** [comment]
Good idea @fisherxu . Upstream K8S has very good e2e tests for all their features.

**Comment by sids-b** [comment]
@fisherxu , is it possible for you to take this one up ?

**Comment by fisherxu** [comment]
Many upstream e2e cases rely on the logs api,  we must support logs api first.
