### ISSUE TITLE
怎么把CC2650的实时温度值上传到云端？

### ISSUE THREAD

**Issue by dhdljd** [kubeedge/kubeedge#1105]
**What would you like to be added/modified**:
通过bluetooth mappers，我现在已经可以实现在云端控制CC2650sensortag上面的灯，edge端可以正常的反馈灯的状态给云端。mappers里面同时把实时的温度值发送到mqtt服务器，但是，devicetwin里面没有对应的属性可以更新实时温度值。
我的问题是：
现在devicetwin的设计是不是只是针对可控的状态？如果我想在云端收集实时的温度值，该怎么实现？是不是需要去订阅edge端部署的mqtt服务器？
**Why is this needed**:

**Comment by Baoqiang-Zhang** [comment]
@dhdljd 你可以参考这份文档从云端获取https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/device-crd.md

**Comment by dhdljd** [comment]
> @dhdljd 你可以参考这份文档从云端获取https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/device-crd.md

@Baoqiang-Zhang 您好，非常感谢。文档我看了，但是没有理解，按照现在的设计，reported的是设备的实际值和从云端给twin设置的期望值不一样，然后把更新以后的实际值以后发送到云端，能控制的灯的状态好理解，但是实际的温度值是一个传感器只读的值，如何设置期望值？

**Comment by sids-b** [comment]
@dhdljd , is this issue resolved ? Please let us know if we can help in anyway

**Comment by dhdljd** [comment]
> @dhdljd , is this issue resolved ? Please let us know if we can help in anyway

@sids-b this issue is not resolved，by now i think the twin only update the controlled properties of devices，then mappers can compare the required and actual value of the devices，if different and then update the actual value。but if I want to update the realtime temperature of the sensor，it doesn't have any require value。i think I can use the last and current value，mappers compare there two values，if they are different，then update the twin and ayns to cloud，but adding this function is too hard for me。
