### ISSUE TITLE
Improve the env feature at edge

### ISSUE THREAD

**Issue by edisonxiang** [kubeedge/kubeedge#1106]
**What would you like to be added/modified**:

Currently the pods running at edge can not set the environment variables
by the deployment yaml and inject into the containers,
We need to support more kinds of ways to set environment variables,
including directly setting and Reading from fieldRef.
Something like read from configmap and secret and so on.

**Why is this needed**:
inject environment variables into containers for the users.

**Comment by edisonxiang** [comment]
based on https://github.com/kubeedge/kubeedge/pull/1103

**Comment by Baoqiang-Zhang** [comment]
+1

**Comment by sids-b** [comment]
@edisonxiang , is this issue fixed ?

**Comment by sids-b** [comment]
I think this issue is fixed. Please reopen if it is not.
