### ISSUE TITLE
CI enhancement

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#111]
CI while running jobs is cloning code from fork, whereas it should clone from kubeedge master and apply commits of PR in it. Also we need daily build, test jobs.
cc @m1093782566 @rohitsardesai83

**Comment by sids-b** [comment]
@srivatsav123 , please help in this

**Comment by sids-b** [comment]
![verify-fail](https://user-images.githubusercontent.com/30088497/51785956-aab60a00-2183-11e9-802f-d939ce37d459.png)
CI verify script fail issue encountered

**Comment by sujithsimon22** [comment]
Rencountered CI verify fail issue
![image](https://user-images.githubusercontent.com/35599628/51959837-44c7cc00-247c-11e9-8c5d-6bba0fc8c6d0.png)

**Comment by sujithsimon22** [comment]
Created a seperate issue for verify failure. Issue #125

**Comment by sids-b** [comment]
We have added rsync for putting only the extra commit while running CI jobs and also added daily build jobs(cron jobs). They will be triggered everyday at 7:30pm India time and 10:00 pm China time.
Thanks @srivatsav123 
cc @m1093782566 @rohitsardesai83 @skdwriting
