### ISSUE TITLE
go.mod requires github.com/kubeedge/kubeedge  but vendor/modules.txt does not include it.

### ISSUE THREAD

**Issue by noizz** [kubeedge/kubeedge#1113]
https://docs.kubeedge.io/en/latest/setup/setup.html
Run KubeEdge
Setup cloud side
Run as a binary
Build cloudcore
`
[root@kubeedge-cloud kubeedge]# pwd
/usr/local/go/src/github.com/kubeedge/kubeedge
[root@kubeedge-cloud kubeedge]# make all WHAT=cloudcore
cd cloud && make cloudcore
make[1]: Entering directory `/usr/local/go/src/github.com/kubeedge/kubeedge/cloud'
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-09-10T17:00:31Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=13a96dfbbb90be94d44e94b6fec5a4389f14a8cf -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=dirty -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.0.0-375+13a96dfbbb90be-dirty -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=0+' cmd/cloudcore/cloudcore.go
go: inconsistent vendoring in /usr/local/go/src/github.com/kubeedge/kubeedge:
        go.mod requires github.com/kubeedge/kubeedge  but vendor/modules.txt does not include it.
        run 'go mod tidy; go mod vendor' to sync
make[1]: *** [cloudcore] Error 1
make[1]: Leaving directory `/usr/local/go/src/github.com/kubeedge/kubeedge/cloud'
make: *** [all] Error 2
`
why?
I have run 'go mod tidy; go mod vendor' .

**Comment by kadisi** [comment]
Are you using the latest code? 

Have you modified the code?

please exec: `git status`

**Comment by noizz** [comment]
Thanks.  
I found some files changed .So I updated to the latest version and errors are the same.
`
[root@kubeedge-cloud kubeedge]# git fetch --all && git reset --hard origin/master && git pull
Fetching origin
HEAD is now at 37d48af Merge pull request #1059 from edisonxiang/addcsidriver
Already up-to-date.
[root@kubeedge-cloud kubeedge]# git status
# On branch master
nothing to commit, working directory clean
[root@kubeedge-cloud kubeedge]# 
[root@kubeedge-cloud kubeedge]# 
[root@kubeedge-cloud kubeedge]# pwd
/usr/local/go/src/github.com/kubeedge/kubeedge
[root@kubeedge-cloud kubeedge]# ls
build             CHANGELOG.md  CODE_OF_CONDUCT.md  CONTRIBUTING.md  edge      edgesite                go.mod  hack   LICENSE      Makefile  OWNERS  README.md     tests
CHANGELOG-1.0.md  cloud         common              docs             edgemesh  external-dependency.md  go.sum  keadm  MAINTAINERS  mappers   pkg     README_zh.md  vendor
[root@kubeedge-cloud kubeedge]# 
[root@kubeedge-cloud kubeedge]# 
[root@kubeedge-cloud kubeedge]# make all WHAT=cloudcore
cd cloud && make cloudcore
make[1]: Entering directory `/usr/local/go/src/github.com/kubeedge/kubeedge/cloud'
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-09-10T18:19:36Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=37d48af49fd7233ea71b28de8d5ccd8d0824534f -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/cloudcore/cloudcore.go
go: inconsistent vendoring in /usr/local/go/src/github.com/kubeedge/kubeedge:
        go.mod requires github.com/kubeedge/kubeedge  but vendor/modules.txt does not include it.
        run 'go mod tidy; go mod vendor' to sync
make[1]: *** [cloudcore] Error 1
make[1]: Leaving directory `/usr/local/go/src/github.com/kubeedge/kubeedge/cloud'
make: *** [all] Error 2
`

**Comment by kadisi** [comment]
@noizz can you show your go version?
`go version` and `go env`

**Comment by noizz** [comment]
[root@kubeedge-cloud ~]# go version
go version go1.13 linux/amd64
[root@kubeedge-cloud ~]# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/go/bin"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build223307592=/tmp/go-build -gno-record-gcc-switches"

**Comment by noizz** [comment]
OH,I found the reason.
The problem was solved after I changed the GOPATH to /root/go .
Thanks a lot.

**Comment by xianhongdong** [comment]
@noizz i have the same problem with you,but your solusion not suitable for me
