### ISSUE TITLE
Container-Runtime and K8S should not be in the management scope of keadm

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#1117]
**What happened**:
Currently keadm installs of Container-Runtime (Docker) and Kubernetes

**What you expected to happen**:
keadm should only be responsible for management of kubeedge components. The cloud and edge part. We should provide link of guides to setup other prerequisites like docker, containerd, cni, k8s, etc.

**Comment by sids-b** [comment]
Thoughts @kubeedge/maintainers @fisherxu @edisonxiang @chendave @kadisi @subpathdev @sujithsimon22 @lidiyag

**Comment by fisherxu** [comment]
Agreed.  In the cloud and edge side, users can install the k8s and runtime in their own way, and keadm only responsible for kubeedge components.

**Comment by kadisi** [comment]
agree

**Comment by subpathdev** [comment]
+1

**Comment by sujithsimon22** [comment]
Agreed, keadm should be primarily responsible for the setup of only KubeEdge components. But should we also think about have an optional mechanism in place to install prerequisites like Docker and Kubernetes ( This could be helpful for first time users/evaluators of KubeEdge, who might be unfamiliar with these technologies and might just be looking for an easy start-up mechanism). Just an alternate line of thought, what are your opinions on this ?

**Comment by lidiyag** [comment]
> Agreed, keadm should be primarily responsible for the setup of only KubeEdge components. But should we also think about have an optional mechanism in place to install prerequisites like Docker and Kubernetes ( This could be helpful for first time users/evaluators of KubeEdge, who might be unfamiliar with these technologies and might just be looking for an easy start-up mechanism). Just an alternate line of thought, what are your opinions on this ?

+1

**Comment by rzr** [comment]
Yes I have the same opinion, I am patching HEAD to remove installer part and rely on static binaries built from source not downloaded from random location, my longer term project is to provide working deb packages that can be installed on (any) debian system (or derived like ubuntu, raspbian etc).

Track:
https://dl.bintray.com/rzr/deb/pool/k/kubeedge/

Relate-to: https://talk.maemo.org/showthread.php?p=1558991#post1558991

**Comment by bitvijays** [comment]
@fisherxu Maybe we can close this?

**Comment by fisherxu** [comment]
Let's close it. 
/close
