### ISSUE TITLE
can not excute edge_core in the node

### ISSUE THREAD

**Issue by stormspiritzzz** [kubeedge/kubeedge#1118]
**What happened**:when i excute edge_core,it shows "-bash: ./edge_core: No such file or directory"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:excute edge_core in the node

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:v0.3.0
- Hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu16.04
- ARCH="arm"
- Kernel (e.g. `uname -a`):Linux edge3 4.4.38-tegra #1 SMP PREEMPT Thu May 17 00:15:19 PDT 2018 aarch64 aarch64 aarch64 GNU/Linux

- Others:

**Comment by stormspiritzzz** [comment]
> @stormspiritzzz Could you please try the v1.0.0?
When I try v1.0.0 in the master node,the result are as follows.There are some errors in the document.

root@master:/etc/kubeedge/cloud# pwd
/etc/kubeedge/cloud
root@master:/etc/kubeedge/cloud# ls
conf  edgecontroller
root@master:/etc/kubeedge/cloud# ./edgecontroller 
-bash: ./edgecontroller: cannot execute binary file: Exec format error
root@master:/etc/kubeedge/cloud#

**Comment by fisherxu** [comment]
> -bash: ./edgecontroller: cannot execute binary file: Exec format error

It seems that the platform and binary are not corresponding, could you please check that whether you are running the x86 binary on the arm platform or arm binary on x86 platform ? @stormspiritzzz  Thanks :)

**Comment by stormspiritzzz** [comment]
> > -bash: ./edgecontroller: cannot execute binary file: Exec format error
> 
> It seems that the platform and binary are not corresponding, could you please check that whether you are running the x86 binary on the arm platform or arm binary on x86 platform ? @stormspiritzzz Thanks :)

**Comment by stormspiritzzz** [comment]
> > -bash: ./edgecontroller: cannot execute binary file: Exec format error
> 
> It seems that the platform and binary are not corresponding, could you please check that whether you are running the x86 binary on the arm platform or arm binary on x86 platform ? @stormspiritzzz Thanks :)



> > -bash: ./edgecontroller: cannot execute binary file: Exec format error
> 
> It seems that the platform and binary are not corresponding, could you please check that whether you are running the x86 binary on the arm platform or arm binary on x86 platform ? @stormspiritzzz Thanks :)

**Comment by stormspiritzzz** [comment]
> > -bash: ./edgecontroller: cannot execute binary file: Exec format error
> 
> It seems that the platform and binary are not corresponding, could you please check that whether you are running the x86 binary on the arm platform or arm binary on x86 platform ? @stormspiritzzz Thanks :)

I try again in the edge,the results are as follows.
root@edge3:~# VERSION="v1.0.0"
root@edge3:~# OS="linux"
root@edge3:~# ARCH="arm"
root@edge3:~# curl -L "https://github.com/kubeedge/kubeedge/releases/download/${VERSION}/kubeedge-${VERSION}-${OS}-${ARCH}.tar.gz" --output kubeedge-${VERSION}-${OS}-${ARCH}.tar.gz && tar -xf kubeedge-${VERSION}-${OS}-${ARCH}.tar.gz  -C /etc  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   623    0   623    0     0    817      0 --:--:-- --:--:-- --:--:--   817
100 43.4M  100 43.4M    0     0  81472      0  0:09:18  0:09:18 --:--:-- 67993
root@edge3:~# vi /etc/kubeedge/edge/conf/edge.yaml
root@edge3:~# cd /etc/kubeedge/edge/
root@edge3:/etc/kubeedge/edge# ls
conf  edge_core
root@edge3:/etc/kubeedge/edge# ./edge_core 
-bash: ./edge_core: No such file or directory
root@edge3:/etc/kubeedge/edge# dpkg --print-architecture
arm64

**Comment by subpathdev** [comment]
@stormspiritzzz 
ARCH="arm" is not equal to "arm64"
We didn't have build binaries which could be used on arm64; you have to compile KubeEdge yourself

**Comment by sids-b** [comment]
@subpathdev , can we add a makefile job to compile a binary for arm64 just incase someone wants to cross-compile and use ?

**Comment by subpathdev** [comment]
@sids-b 
There is one :D
you can use `edge_cross_build_v8` to build the edgecore for arm64 (armv8 is in 64 bit architecture) But I didn't know if this is already present in release v1.0.0 ...

**Comment by stormspiritzzz** [comment]
> @stormspiritzzz
> ARCH="arm" is not equal to "arm64"
> We didn't have build binaries which could be used on arm64; you have to compile KubeEdge yourself

Can you give me some guidance,which document would be more reliable

> @sids-b
> There is one :D
> you can use `edge_cross_build_v8` to build the edgecore for arm64 (armv8 is in 64 bit architecture) But I didn't know if this is already present in release v1.0.0 ...

excute  the following commands in the edge(arm64)?
cd $GOPATH/src/github.com/kubeedge/kubeedge/edge
make edge_cross_build_v8

**Comment by subpathdev** [comment]
> excute the following commands in the edge(arm64)?
> cd $GOPATH/src/github.com/kubeedge/kubeedge/edge
> make edge_cross_build_v8
 
No, on the edge you can execute this: `make WHAT=edgecore`. The above command can be used to cross compile for arm64 bit. (Cross build means you build on a different architecture then you will execute the binary)

**Comment by subpathdev** [comment]
> Can you give me some guidance,which document would be more reliable

Do you want to have a setup description to build and run kubeedge yourself? https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/usage.md

@stormspiritzzz you can ping me in the kubeedge slack, if you need more guidance.

**Comment by bitvijays** [comment]
@subpathdev @fisherxu Maybe we can close this? It's been a while.
