### ISSUE TITLE
kubeedge should provide mapper programming tutorial

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1119]
**What would you like to be added/modified**:

**Why is this needed**:

device model and device instance are very good disign.  But users will be confused how to write their own device mapper. In particular, it is confusing to use several topics（eg./twin/update. /twin/get/result and so on） of mqtt, and how to correctly use the DeviceTwinUpdate structure.

We should have a detailed example and description， Although we already have a led [example](https://github.com/kubeedge/examples/tree/master/led-raspberrypi), but I think the description is not detailed enough.

/cc @kevin-wangzefeng @fisherxu @sids-b @rohitsardesai83 @subpathdev

**Comment by borlandor** [comment]
Yes, for new to kubeedge, it would be great if the document of mapper or e2e  is more detailed:
https://github.com/kubeedge/examples/tree/master/led-raspberrypi
https://github.com/kubeedge/kubeedge/blob/master/docs/mappers/bluetooth_mapper.md#bluetooth-mapper
https://github.com/kubeedge/kubeedge/blob/master/docs/guides/bluetooth_mapper_e2e_guide.md

**Comment by 12101111** [comment]
It seems that the implementation of mappers is independent of  which programming language is using.
A mapper only needs to publish mqtt messages in json format to the corresponding mqtt topic.
But there is currently no documentation for json fields of echo mqtt topic.
