### ISSUE TITLE
centosinstaller need to implement

### ISSUE THREAD

**Issue by bretagne-peiqi** [kubeedge/kubeedge#1121]
**What would you like to be added/modified**:

      I would like to implement the centosinstaller.go associated functions if it is not yet assigned.

**Why is this needed**:

       I build the keadm binary and try to install on my centos, I found centosinstaller is not implemented completely. and failed to install on my node.

**Comment by fisherxu** [comment]
Thanks! @bretagne-peiqi  Please just go ahead and implement it :)

**Comment by sids-b** [comment]
Thanks @bretagne-peiqi . It would be great if you could build on top of #721 . A few efforts have already been spent there
