### ISSUE TITLE
Question: Deploy Cloud-side services in existing managed cluster?

### ISSUE THREAD

**Issue by jtcressy** [kubeedge/kubeedge#1122]
Would it be possible to deploy the cloud-side components into an existing managed cluster like GKE or EKS? 

I may just have a hard time understanding the documentation, but It seems this is possible or was once possible by just deploying manifests into a standard cluster. 

Has anyone attempted this and had any success? I want to create a demo of kubeedge for some colleagues using a couple raspberry pi's but on the cloud side I'll need some of the simplicity that a managed cluster provides.

**Comment by kadisi** [comment]
if you have an existing cluster, you can deploy cloudcore on your cloudside, and deploy edgecore on your raspberry.

**Comment by jtcressy** [comment]
Ok, does `keadm init` work with existing clusters? i'm referring to the pdf version of the docs here: https://buildmedia.readthedocs.org/media/pdf/kubeedge/latest/kubeedge.pdf
under section 27.7.1

**Comment by subpathdev** [comment]
I run kubeedge cloud part in a gke cluster and have a issues by adding more than one edge node this cluster. (I'm still searching for a solution)

**Comment by subpathdev** [comment]
> Ok, does `keadm init` work with existing clusters? i'm referring to the pdf version of the docs here: https://buildmedia.readthedocs.org/media/pdf/kubeedge/latest/kubeedge.pdf
> under section 27.7.1
No you can't use keadm init. It will set up a kubernetes cluster. But  you can use these yaml files to set up the cloudcore. https://github.com/kubeedge/kubeedge/tree/master/build/cloud

(I think `keadm join` should still work)

**Comment by jtcressy** [comment]
@sids-b It looks like those manifests are missing the CRD's? When cloudcore starts up it cannot list v1alpha1.Device from the api server.

**Comment by jtcressy** [comment]
Nevermind, I found the CRD's in a parent directory. Trying them now.

**Comment by jtcressy** [comment]
I was able to successfully deploy cloudcore into my existing k8s cluster and expose it as a LoadBalancer service.

I am unable to test if an edge device can connect as keadm does not seem to support raspbian on the raspberry pi. If anyone has information around running edgecore on the raspberry pi with ease, let me know. It's out of the scope of this issue for now.
