### ISSUE TITLE
timeout to receive response for message

### ISSUE THREAD

**Issue by liqiangno1** [kubeedge/kubeedge#1124]
**What happened**:
when i run cloudcore and edgecore, there are some warning messages and can not register node successfully.
![image](https://user-images.githubusercontent.com/6667502/65006966-3c52d180-d937-11e9-91f7-812d3a1745ab.png)
![image](https://user-images.githubusercontent.com/6667502/65006987-4bd21a80-d937-11e9-8bc1-ab1b91f060b3.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**:
my cloud node and edge node are on the same device
**Environment**:
- KubeEdge version:  1.1.0-beta.0
- Hardware configuration:
- OS (e.g. from /etc/os-release): centos 7.5.1804
- Kernel (e.g. `uname -a`): Linux kubernetes-6 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by fisherxu** [comment]
> my cloud node and edge node are on the same device

Does the cloud node run the kubelet?  Edge node(edgecore) also run a mini-kubelet(edged), it’s best not to let them run on a machine.

Now in kubeedge we must register the edge node manually first, then the edge side will only update the nodestatus. Ref: https://github.com/kubeedge/kubeedge/blob/master/docs/setup/setup.md#deploy-the-edge-node

**Comment by fisherxu** [comment]
@liqiangno1  If you just want to have a try and run kubeedge on one VM, you can try out [this script](https://github.com/kubeedge/kubeedge/blob/master/hack/local-up-kubeedge.sh). It starts a kubedge cluster in one VM, and it uses `kind` to start a k8s cluster, then run cloudcore/edgecore in the VM.

**Comment by liqiangno1** [comment]
> > my cloud node and edge node are on the same device
> 
> Does the cloud node run the kubelet? Edge node(edgecore) also run a mini-kubelet(edged), it’s best not to let them run on a machine.
> 
> Now in kubeedge we must register the edge node manually first, then the edge side will only update the nodestatus. Ref: https://github.com/kubeedge/kubeedge/blob/master/docs/setup/setup.md#deploy-the-edge-node

sorry ,it's my fault. I do not register the edge node manually. I mistakenly thought it can register automatically. Now when I register the edge node in advance, it's running well.  Thank you so much.

**Comment by liqiangno1** [comment]
> @liqiangno1 If you just want to have a try and run kubeedge on one VM, you can try out [this script](https://github.com/kubeedge/kubeedge/blob/master/hack/local-up-kubeedge.sh). It starts a kubedge cluster in one VM, and it uses `kind` to start a k8s cluster, then run cloudcore/edgecore in the VM.
it's now running well. Thank you anyway!
