### ISSUE TITLE
New downstream controller failed with error

### ISSUE THREAD

**Issue by stormspiritzzz** [kubeedge/kubeedge#1125]
**What happened**:
# When I excute the cloudcore,there is an error.The outputs are as follows.I have the file"~/.kube/config",but the log is " no such file or directory".

root@master:~/go/src/github.com/kubeedge/kubeedge/cloud# ./cloudcore 
2019/09/17 13:20:49 RollingPolicy is empty, use default policy[size]
2019-09-17 13:20:49.572 +08:00 INFO go-archaius/archaius.go:53 Configuration files: 
2019-09-17 13:20:49.572 +08:00 WARN config-manager/configurationmanager.go:140 empty configurtion from FileSource
2019-09-17 13:20:49.572 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:FileSource
2019-09-17 13:20:49.572 +08:00 INFO go-archaius/archaius.go:112 archaius init success
2019-09-17 13:20:49.572 +08:00 WARN config-manager/configurationmanager.go:140 empty configurtion from MemorySource
2019-09-17 13:20:49.572 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:MemorySource
2019-09-17 13:20:49.573 +08:00 WARN config-manager/configurationmanager.go:140 empty configurtion from CommandlineSource
2019-09-17 13:20:49.573 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:CommandlineSource
2019-09-17 13:20:49.573 +08:00 INFO enviromentvariable-source/envconfigurationsource.go:46 enable env source
2019-09-17 13:20:49.573 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:EnvironmentSource
2019-09-17 13:20:49.573 +08:00 INFO file-source/filesource.go:354 create new watcher
2019-09-17 13:20:49.576 +08:00 INFO memory-source/memorysource.go:105 mem source callback prepared
I0917 13:20:49.577296   14384 server.go:36] Version: v1.1.0-beta.0.5+617a8d72af2309
2019-09-17 13:20:49.577 +08:00 INFO core/module.go:41 module cloudhub registered
2019-09-17 13:20:49.577 +08:00 INFO core/module.go:41 module edgecontroller registered
2019-09-17 13:20:49.577 +08:00 INFO core/module.go:41 module devicecontroller registered
2019-09-17 13:20:49.577 +08:00 INFO core/core.go:23 starting module edgecontroller
2019-09-17 13:20:49.577 +08:00 INFO core/core.go:23 starting module devicecontroller
I0917 13:20:49.577432   14384 buffer.go:64] Update controller.buffer.update-pod-status: 1024
I0917 13:20:49.577447   14384 buffer.go:71] Update controller.buffer.update-node-status: 1024
I0917 13:20:49.577452   14384 buffer.go:78] Update controller.buffer.query-configmap: 1024
I0917 13:20:49.577457   14384 buffer.go:92] Update controller.buffer.query-service: 1024
2019-09-17 13:20:49.577 +08:00 INFO core/core.go:23 starting module cloudhub
I0917 13:20:49.577461   14384 buffer.go:100] Update controller.buffer.query-endpoints: 1024
I0917 13:20:49.577465   14384 buffer.go:107] Update controller.buffer.pod-event: 1
I0917 13:20:49.577470   14384 buffer.go:114] Update controller.buffer.configmap-event: 1
I0917 13:20:49.577474   14384 buffer.go:121] Update controller.buffer.secret-event: 1
I0917 13:20:49.577478   14384 buffer.go:128] Update controller.buffer.service-event: 1
I0917 13:20:49.577482   14384 buffer.go:135] Update controller.buffer.endpoint-event: 1
I0917 13:20:49.577487   14384 buffer.go:142] Update controller.buffer.query-persistentvolume: 1024
I0917 13:20:49.577491   14384 buffer.go:149] Update controller.buffer.query-persistentvolumeclaim: 1024
I0917 13:20:49.577496   14384 buffer.go:156] Update controller.buffer.query-volumeattachment: 1024
I0917 13:20:49.577500   14384 buffer.go:163] Update controller.buffer.query-node: 1024
I0917 13:20:49.577505   14384 buffer.go:170] Update controller.buffer.update-node: 1024
I0917 13:20:49.577513   14384 context.go:29]  send module name: cloudhub
I0917 13:20:49.577517   14384 context.go:36] receive module name: edgecontroller
I0917 13:20:49.577521   14384 context.go:43] response module name: cloudhub
I0917 13:20:49.577653   14384 buffer.go:25] Update devicecontroller.buffer.update-device-status: 1024
I0917 13:20:49.577664   14384 buffer.go:32] Update devicecontroller.buffer.device-event: 1
I0917 13:20:49.577671   14384 buffer.go:39] Update devicecontroller.buffer.device-model-event: 1
I0917 13:20:49.577675   14384 context.go:29] Send module name: cloudhub
I0917 13:20:49.577679   14384 context.go:36] Receive module name: devicecontroller
I0917 13:20:49.577685   14384 context.go:43] Response module name: cloudhub
E0917 13:20:49.577696   14384 kube.go:30] Devicecontroller kube master not set
I0917 13:20:49.577702   14384 kube.go:34] Devicecontroller kube master: 
I0917 13:20:49.577711   14384 kube.go:41] Devicecontroller kube config: ~/.kube/config
I0917 13:20:49.577717   14384 kube.go:48] Devicecontroller kube namespace: 
I0917 13:20:49.577723   14384 kube.go:55] Devicecontroller kube content type: application/vnd.kubernetes.protobuf
I0917 13:20:49.577731   14384 kube.go:62] Devicecontroller kube QPS: 5.000000
I0917 13:20:49.577740   14384 kube.go:69] Devicecontroller kube burst: 10
I0917 13:20:49.577745   14384 load.go:19] Update device status workers: 1
I0917 13:20:49.577750   14384 messagelayer.go:19] Message layer: context
W0917 13:20:49.577762   14384 kubeclient.go:16] Get kube config failed with error: stat ~/.kube/config: no such file or directory
W0917 13:20:49.577776   14384 downstream.go:843] Create kube client failed with error: stat ~/.kube/config: no such file or directory
E0917 13:20:49.577782   14384 module.go:45] New downstream controller failed with error: stat ~/.kube/config: no such file or directory

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:latest
- Hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`):Linux master 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by kadisi** [comment]
@stormspiritzzz Try the absolute path ， `~/.kube/config` -> `/root/.kube/config`  , Are you running under the root user?

**Comment by liqiangno1** [comment]
I have also encountered this problem.  when modifed the path config to  absolute path, It's normal immediately. but I'm really running under the root user

**Comment by stormspiritzzz** [comment]
> @stormspiritzzz Try the absolute path ， `~/.kube/config` -> `/root/.kube/config` , Are you running under the root user?
> 
> please use this code to check:
> 
> ```
> func check(path string) {
> 	if _, err := os.Stat(path); os.IsNotExist(err) {
> 		fmt.Printf("[%s] not exist error %v\n", path, err)
> 	} else {
> 		fmt.Printf("[%s] exist ...\n", path)
> 	}
> }
> ```

root@master:/tmp# whoami
root
Where should I modify the path?  In the kubeedge\cloud\conf\controller.yaml？ And rebuild cloudcore?

**Comment by stormspiritzzz** [comment]
> > @stormspiritzzz Try the absolute path ， `~/.kube/config` -> `/root/.kube/config` , Are you running under the root user?
> > please use this code to check:
> > ```
> > func check(path string) {
> > 	if _, err := os.Stat(path); os.IsNotExist(err) {
> > 		fmt.Printf("[%s] not exist error %v\n", path, err)
> > 	} else {
> > 		fmt.Printf("[%s] exist ...\n", path)
> > 	}
> > }
> > ```
> 
> root@master:/tmp# whoami
> root
> Where should I modify the path? In the kubeedge\cloud\conf\controller.yaml？ And rebuild cloudcore?

I try it and modify 2 places. it works.

**Comment by kadisi** [comment]
@stormspiritzzz Please close this issue if it has been resolved. thanks

**Comment by shaonanzh** [comment]
I have encountered this bug too, it's still there. I think the reason is that golang "os" pakage cannot handle the path which has prefix like "~/". So there should have some preprocessing, or just config abosolute path instead.
