### ISSUE TITLE
add e2e test for device and mapper

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1126]
**What would you like to be added/modified**:

currently, kubeedge lack of e2e test about device crd and mapper. 

**Why is this needed**:

cc @kevin-wangzefeng @sids-b @fisherxu @rohitsardesai83 @subpathdev

**Comment by sids-b** [comment]
@kadisi , the e2e tests for device crd have been merged. They will run in CI once https://github.com/kubeedge/kubeedge/pull/856 this PR is merged

**Comment by sids-b** [comment]
Also the bluetooth mapper e2e tests have been merged, but it is difficult to run in CI as we need machines with bluetooth support to run them

**Comment by kadisi** [comment]
yes, but we should use at least one mapper to e2e test

**Comment by kadisi** [comment]
I also don't have a good solution.

**Comment by subpathdev** [comment]
@kadisi can you explain your bad solution?
