### ISSUE TITLE
The pod cannot be terminated

### ISSUE THREAD

**Issue by liqiangno1** [kubeedge/kubeedge#1127]
**What happened**:
I have runned the deployment demo and it's normal.  when the edgecore process is stopped , the pod is going to keep Terminating status and the cluster will start anothor pod(this pod is keeping pending status).  when the edgecore process return to normal. the pod is still keep on Terminating status.
`nginx-deployment-5f76494c55-bmj9k                     0/1     Pending            0          21m   <none>          <none>         <none>           <none>
nginx-deployment-5f76494c55-fg9fg                     1/1     Terminating        0          25m   172.17.0.3      test2          <none>           <none>
`
![image](https://user-images.githubusercontent.com/6667502/65020324-936c9c80-d95f-11e9-9728-98d6dd643140.png)

by the way, is there a qq group or other group to comunicate with others? I saw a slack url but it  has expired.
**What you expected to happen**:
the cluster delete pod automatically or return to normal when the edge process is started.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:  1.1.0-beta.0
- Hardware configuration:
- OS (e.g. from /etc/os-release): centos 7.5.1804
- Kernel (e.g. `uname -a`): Linux kubernetes-6 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by kadisi** [comment]
I have also encountered this problem.  We need to consider consistent message transmission。

cc @kevin-wangzefeng @fisherxu @sids-b

**Comment by sids-b** [comment]
This proposal once approved and implemented will solve this problem.
