### ISSUE TITLE
keadm: Default version of KubeEdge installed by the installer keadm-v1.1.0-linux-amd64.tar.gz

### ISSUE THREAD

**Issue by naveensriram** [kubeedge/kubeedge#1132]
**What happened**:
Try to install kubeedge using keadm-v1.1.0-linux-amd64.tar.gz fails "reporting '/etc/kubeedge//kubeedge/edge/edgecore': No such file or directory"

**What you expected to happen**:
Installer should use latest package of kudeedge [As of now latest is kubeedge-v1.1.0-linux-amd64.tar.gz] instead "kubeedge-v0.3.0-linux-amd64.tar.gz" when installation with default option is opted (./keadm init --kubeedge-version= --kubernetes-version= --docker-version= --kube-config=~/.kube/config) otherwise installer looks for "edgecore" file in "kubeedge-v0.3.0-linux-amd64.tar.gz" which is not present .

**How to reproduce it (as minimally and precisely as possible)**:
root@Cloud:/home/osboxes/installer/keadm-v1.1.0-linux-amd64/keadm# ./keadm init --kubeedge-version= --kubernetes-version= --docker-version= --kube-config=~/.kube/config
Same version of docker already installed in this host
Same version of kubeadm already installed in this hostExpected or Default KubeEdge version 0.3.0 is already downloaded
kubeedge/
kubeedge/edge/
kubeedge/edge/conf/
kubeedge/edge/conf/logging.yaml
kubeedge/edge/conf/modules.yaml
kubeedge/edge/conf/edge.yaml
kubeedge/edge/edge_core
kubeedge/version
kubeedge/cloud/
kubeedge/cloud/edgecontroller
kubeedge/cloud/conf/
kubeedge/cloud/conf/logging.yaml
kubeedge/cloud/conf/controller.yaml
kubeedge/cloud/conf/modules.yaml
cp: cannot stat '/etc/kubeedge//kubeedge/edge/edgecore': No such file or directory
Error: failed to run 'sh -c cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v0.3.0-linux-amd64.tar.gz && cp /etc/kubeedge//kubeedge/edge/edgecore /usr/local/bin/.' because of error : exit status 1

**Anything else we need to know?**:
Also installer code should take care of backward compatibility ie., if user opts to use kubeedge v0.3.0 installer should support "edge_core" as the executable to be used while installation.

**Environment**: 
root@Cloud:/etc/kubeedge/kubeedge/edge# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
root@Cloud:/etc/kubeedge/kubeedge/edge# 
- KubeEdge version: keadm-v1.1.0
- Hardware configuration: Nothing specific
- OS (e.g. from /etc/os-release):
root@Cloud:/etc/kubeedge/kubeedge/edge# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@Cloud:/etc/kubeedge/kubeedge/edge# 
- Kernel (e.g. `uname -a`):
root@Cloud:/etc/kubeedge/kubeedge/edge# uname -a
Linux Cloud 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@Cloud:/etc/kubeedge/kubeedge/edge# 
- Others: Nothing more specific required.
![InstallerError](https://user-images.githubusercontent.com/34940575/65178785-25b39400-da77-11e9-9fd5-2dc705916055.png)

**Comment by NoWhere-zh** [comment]
the command is cp /etc/kubeedge//kubeedge/edge/edgecore /usr/local/bin/. 
an extra '/' appears between the two 'kubeedge', maybe something is wrong when the code joined the path. let me check it.

**Comment by sids-b** [comment]
The problem over here is that in v1.1.0 the binary name is edgecore and edge_core in previous versions... I guess the issue is that the default version is v0.3.0

**Comment by sids-b** [comment]
We need an if else case in both cloud and edge installer for the binary names before and from v1.1.0

**Comment by fisherxu** [comment]
Please try latest verion of keadm v1.2.1 :)
/close
