### ISSUE TITLE
keadm: Post untar of keadm-v1.1.0-linux-amd64.tar.gz the created folder name should be kubeedge otherwise Installer will fail

### ISSUE THREAD

**Issue by naveensriram** [kubeedge/kubeedge#1134]
**What happened**:

Installer tries to find "edgecore" under specific path "/etc/kubeedge//kubeedge/edge/edgecore", usually "kubeedge" was the folder created post untar and unzip of kubeedge binary package earlier but with this package "keadm-v1.1.0-linux-amd64.tar.gz", "keadm-v1.1.0-linux-amd64" is the folder created and hence installer is not able to find the "edgecore".

**What you expected to happen**:
Package "keadm-v1.1.0-linux-amd64.tar.gz" post untar and unzip should create "kubeedge" folder instead of creating "keadm-v1.1.0-linux-amd64" folder.

**How to reproduce it (as minimally and precisely as possible)**:

First apply this work around - download manually checksum file, keep this file under /etc/kubeedge/ folder, rename this file "checksum_kubeedge-v1.1.0-linux-amd64.tar.gz.txt" to "checksum_kubeedge-v1.1.0-linux-amd64.txt".

Then issue below command 

root@Cloud:/home/osboxes/installer/keadm-v1.1.0-linux-amd64/keadm# ./keadm init --kubeedge-version=1.1.0 --kubernetes-version= --docker-version= --kube-config=~/.kube/config
Same version of docker already installed in this host
Same version of kubeadm already installed in this hostExpected or Default KubeEdge version 1.1.0 is already downloaded
kubeedge-v1.1.0-linux-amd64/
kubeedge-v1.1.0-linux-amd64/edge/
kubeedge-v1.1.0-linux-amd64/edge/conf/
kubeedge-v1.1.0-linux-amd64/edge/conf/edge.yaml
kubeedge-v1.1.0-linux-amd64/edge/conf/modules.yaml
kubeedge-v1.1.0-linux-amd64/edge/conf/logging.yaml
kubeedge-v1.1.0-linux-amd64/edge/edgecore
kubeedge-v1.1.0-linux-amd64/cloud/
kubeedge-v1.1.0-linux-amd64/cloud/csidriver/
kubeedge-v1.1.0-linux-amd64/cloud/csidriver/csidriver
kubeedge-v1.1.0-linux-amd64/cloud/admission/
kubeedge-v1.1.0-linux-amd64/cloud/admission/admission
kubeedge-v1.1.0-linux-amd64/cloud/cloudcore/
kubeedge-v1.1.0-linux-amd64/cloud/cloudcore/conf/
kubeedge-v1.1.0-linux-amd64/cloud/cloudcore/conf/controller.yaml
kubeedge-v1.1.0-linux-amd64/cloud/cloudcore/conf/modules.yaml
kubeedge-v1.1.0-linux-amd64/cloud/cloudcore/conf/logging.yaml
kubeedge-v1.1.0-linux-amd64/cloud/cloudcore/cloudcore
kubeedge-v1.1.0-linux-amd64/version
cp: cannot stat '/etc/kubeedge//kubeedge/edge/edgecore': No such file or directory
Error: failed to run 'sh -c cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v1.1.0-linux-amd64.tar.gz && cp /etc/kubeedge//kubeedge/edge/edgecore /usr/local/bin/.' because of error : exit status 1

**Anything else we need to know?**:
No

**Environment**: 
root@Cloud:/etc/kubeedge/kubeedge/edge# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
root@Cloud:/etc/kubeedge/kubeedge/edge# 
- KubeEdge version: keadm-v1.1.0
- Hardware configuration: Nothing specific
- OS (e.g. from /etc/os-release):
root@Cloud:/etc/kubeedge/kubeedge/edge# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@Cloud:/etc/kubeedge/kubeedge/edge# 
- Kernel (e.g. `uname -a`):
root@Cloud:/etc/kubeedge/kubeedge/edge# uname -a
Linux Cloud 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@Cloud:/etc/kubeedge/kubeedge/edge# 
- Others: Nothing more specific required.
![FoldernamewithinPackagerequireChange](https://user-images.githubusercontent.com/34940575/65189171-d9278300-da8d-11e9-9f7d-4c59f732bd3e.png)

**Comment by NoWhere-zh** [comment]
there are two '/' between the two 'kubeedge' here:
 cp /etc/kubeedge//kubeedge/edge/edgecore /usr/local/bin/
the path is wrong

**Comment by fisherxu** [comment]
Please try latest verion of keadm v1.2.1 :)
/close
