### ISSUE TITLE
Nodes not ready at cloud

### ISSUE THREAD

**Issue by noizz** [kubeedge/kubeedge#1138]
**What happened**:
` 
#kubectl get nodes
NAME                                   STATUS     ROLES    AGE     VERSION
fb4ebb70-2783-42b8-b3ef-63e2fd6d242e   NotReady   edge     2d23h   
`
cloudcore.log:
`
I0920 19:16:25.830539  103929 eventhandler.go:201] event received for node fb4ebb70-2783-42b8-b3ef-63e2fd6d242e id: bb05a575-b329-48af-9df8-f96a0d7f341c, parent_id: , group: meta, source: edged, resource: node/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e/default/nodestatus/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e, operation: update, content: {"UID":"38796d14-1df3-11e8-8e5a-286ed488f209","Status":{"capacity":{"cpu":"8","memory":"7802Mi","pods":"110"},"allocatable":{"cpu":"8","memory":"7702Mi","pods":"110"},"phase":"Running","conditions":[{"type":"Ready","status":"True","lastHeartbeatTime":"2019-09-20T11:16:35Z","lastTransitionTime":"2019-09-20T11:16:35Z","reason":"EdgeReady","message":"edge is posting ready status"}],"addresses":[{"type":"InternalIP","address":"192.168.36.162"},{"type":"Hostname","address":"kubeedge-edge"}],"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"3.10.0-957.27.2.el7.x86_64","osImage":"CentOS Linux 7 (Core)","containerRuntimeVersion":"remote://1.13.1","kubeletVersion":"v1.15.3-kubeedge-v1.1.0-beta.0","kubeProxyVersion":"","operatingSystem":"linux","architecture":"amd64"}},"ExtendResources":null}
I0920 19:16:25.831045  103929 upstream.go:186] dispatch message: bb05a575-b329-48af-9df8-f96a0d7f341c
I0920 19:16:25.831116  103929 util.go:88] The resource type is nodestatus, 3
I0920 19:16:25.831157  103929 upstream.go:193] message: bb05a575-b329-48af-9df8-f96a0d7f341c, resource type is: nodestatus
I0920 19:16:25.831177  103929 upstream.go:195] message: bb05a575-b329-48af-9df8-f96a0d7f341c, operation type is: update
I0920 19:16:25.831321  103929 upstream.go:341] message: bb05a575-b329-48af-9df8-f96a0d7f341c, operation is: update, and resource is node/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e/default/nodestatus/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e
I0920 19:16:25.831857  103929 util.go:113] The resource name is fb4ebb70-2783-42b8-b3ef-63e2fd6d242e, 4
W0920 19:16:25.835344  103929 upstream.go:383] message: bb05a575-b329-48af-9df8-f96a0d7f341c process failure with error: nodes "fb4ebb70-2783-42b8-b3ef-63e2fd6d242e" is forbidden: User "system:kube-controller-manager" cannot get resource "nodes" in API group "" at the cluster scope, namespaces: default name: fb4ebb70-2783-42b8-b3ef-63e2fd6d242e
I0920 19:16:31.129080  103929 eventhandler.go:98] Keepalive message received from node: fb4ebb70-2783-42b8-b3ef-63e2fd6d242e
I0920 19:16:31.129287  103929 eventhandler.go:135] Node fb4ebb70-2783-42b8-b3ef-63e2fd6d242e is still alive
`

**What you expected to happen**:
make the node ready

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
'
[root@kubeedge-cloud cmd]# go version
go version go1.13 linux/amd64
[root@kubeedge-cloud cmd]# uname -a
Linux kubeedge-cloud.lab 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@kubeedge-cloud cmd]# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="localhost,172.0.0.0/8,10.0.0.0/8,192.168.36.0/16"
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build965105845=/tmp/go-build -gno-record-gcc-switches"
'

‘
edgecore.log:

I0920 20:00:23.024217  116718 edged_status.go:163] Sync VolumesInUse: []
I0920 20:00:23.034920  116718 msg_processor.go:634] get a message {Header:{ID:f47fde65-fa70-45aa-93be-b55212c9b184 ParentID: Timestamp:1568980823024 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:8 scale:0} d:{Dec:<nil>} s:8 Format:DecimalSI} memory:{i:{value:8180989952 scale:0} d:{Dec:<nil>} s:7802Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:8 scale:0} d:{Dec:<nil>} s:8 Format:DecimalSI} memory:{i:{value:8076132352 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-09-20 20:00:23.018957447 +0800 CST m=+171288.211416608 LastTransitionTime:2019-09-20 20:00:23.018957447 +0800 CST m=+171288.211416608 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.36.162} {Type:Hostname Address:kubeedge-edge}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:3.10.0-957.27.2.el7.x86_64 OSImage:CentOS Linux 7 (Core) ContainerRuntimeVersion:remote://1.13.1 KubeletVersion:v1.15.3-kubeedge-v1.1.0-beta.0 KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I0920 20:00:23.041803  116718 metaclient.go:117] send sync message default/nodestatus/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e successed and response: {{48d627a5-1af9-4147-9116-e72f0eb27a37 f47fde65-fa70-45aa-93be-b55212c9b184 1568980823041 false} {edged meta response default/nodestatus/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e} OK}
I0920 20:00:23.563894  116718 generic.go:81] GenericLifecycle: Relisting
I0920 20:00:24.564684  116718 generic.go:81] GenericLifecycle: Relisting
I0920 20:00:25.565613  116718 generic.go:81] GenericLifecycle: Relisting
I0920 20:00:26.566465  116718 generic.go:81] GenericLifecycle: Relisting
I0920 20:00:27.567184  116718 generic.go:81] GenericLifecycle: Relisting
W0920 20:00:28.024152  116718 controller.go:208] timeout to receive response for message: {Header:{ID:48fa8c6c-2fab-486b-addc-0574d900da80 ParentID: Timestamp:1568980813000 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:8 scale:0} d:{Dec:<nil>} s:8 Format:DecimalSI} memory:{i:{value:8180989952 scale:0} d:{Dec:<nil>} s:7802Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:8 scale:0} d:{Dec:<nil>} s:8 Format:DecimalSI} memory:{i:{value:8076132352 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-09-20 20:00:12.993450442 +0800 CST m=+171278.185909621 LastTransitionTime:2019-09-20 20:00:12.993450442 +0800 CST m=+171278.185909621 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.36.162} {Type:Hostname Address:kubeedge-edge}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:3.10.0-957.27.2.el7.x86_64 OSImage:CentOS Linux 7 (Core) ContainerRuntimeVersion:remote://1.13.1 KubeletVersion:v1.15.3-kubeedge-v1.1.0-beta.0 KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I0920 20:00:28.567911  116718 generic.go:81] GenericLifecycle: Relisting

’
**Environment**:
- KubeEdge version:
github lastest

- Hardware configuration:
pc 
- OS (e.g. from /etc/os-release):
centos 7
os 
- Kernel (e.g. `uname -a`): 

- Others:

**Comment by noizz** [comment]
`
# more conf/controller.yaml
controller:
  kube:
    master:     # kube-apiserver address (such as:http://localhost:8080)
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    node_update_frequency: 10
    kubeconfig: "/etc/kubernetes/controller-manager.conf"   #Enter path to kubeconfig file to enable https connection to k8s apiserver, if master and kubeconfig are both set, master will over
ride any value in kubeconfig.
cloudhub:
  protocol_websocket: true # enable websocket protocol
  port: 10000 # open port for websocket server
  protocol_quic: true # enable quic protocol
  quic_port: 10001 # open prot for quic server
  max_incomingstreams: 10000 # the max incoming stream for quic server
  enable_uds: true # enable unix domain socket protocol
  uds_address: unix:///var/lib/kubeedge/kubeedge.sock # unix domain socket address
  address: 0.0.0.0
  ca: /etc/kubeedge/ca/rootCA.crt
  cert: /etc/kubeedge/certs/edge.crt
  key: /etc/kubeedge/certs/edge.key
  keepalive-interval: 30
  write-timeout: 30
  node-limit: 10
devicecontroller:
  kube:
    master:        # kube-apiserver address (such as:http://localhost:8080)
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    kubeconfig: "/etc/kubernetes/controller-manager.conf" #Enter path to kubeconfig file to enable https connection to k8s apiserver,if master and kubeconfig are both set, master will overrid
e any value in kubeconfig.
`
`
# more ~/.kube/config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:...==
    server: https://192.168.36.xxx:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:kube-controller-manager
  name: system:kube-controller-manager@kubernetes
current-context: system:kube-controller-manager@kubernetes
kind: Config
preferences: {}
users:
- name: system:kube-controller-manager
  user:
    client-certificate-data: ...==
    client-key-data: ...==
`

**Comment by kadisi** [comment]
> essage: bb05a575-b329-48af-9df8-f96a0d7f341c process failure with error: nodes "fb4ebb70-2783-42b8-b3ef-63e2fd6d242e" is forbidden: User "system:kube-controller-manager" cannot get resource "nodes" in API group "" at the cluster scope, namespaces: default name: fb4ebb70-2783-42b8-b3ef-63e2fd6d242e I0920 19:16:31.129080 103929 eventhandler.go:98] Keepalive message received from node: fb4ebb70-2783-42b8-b3ef-63e2fd6d242e I0920 19:16:31.129287 103929 eventhandler.go:135] Node fb4ebb70-2783-42b8-b3ef-63e2fd6d242e is still alive


@noizz This should be a permission issue。 your kubeconfig is `kubeconfig: "/etc/kubernetes/controller-manager.conf" `, Please make sure the user（system:kube-controller-manager） has sufficient permissions or change rbac。   It is recommended that you use the admin right user。

**Comment by noizz** [comment]
`
conf/edge.yaml 
mqtt:
    server: tcp://127.0.0.1:1883 # external mqtt broker url.
    internal-server: tcp://127.0.0.1:1884 # internal mqtt broker url.
    mode: 2 # 0: internal mqtt broker enable only. 1: internal and external mqtt broker enable. 2: external mqtt broker enable only.
    qos: 0 # 0: QOSAtMostOnce, 1: QOSAtLeastOnce, 2: QOSExactlyOnce.
    retain: false # if the flag set true, server will store the message and can be delivered to future subscribers.
    session-queue-size: 100 # A size of how many sessions will be handled. default to 100.

edgehub:
    websocket:
        url: wss://192.168.36.161:10000/e632aba927ea4ac2b575ec1603d56f10/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e/events
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    quic:
        url: 192.168.36.161:10001
        cafile: /etc/kubeedge/ca/rootCA.crt
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    controller:
        protocol: websocket # websocket, quic
        heartbeat: 15  # second
        project-id: e632aba927ea4ac2b575ec1603d56f10
        node-id: fb4ebb70-2783-42b8-b3ef-63e2fd6d242e

edged:
    register-node-namespace: default
    hostname-override: fb4ebb70-2783-42b8-b3ef-63e2fd6d242e
    interface-name: eth0
    edged-memory-capacity-bytes: 7852396000
    node-status-update-frequency: 10 # second
    device-plugin-enabled: false
    gpu-plugin-enabled: false
    image-gc-high-threshold: 80 # percent
    image-gc-low-threshold: 40 # percent
    maximum-dead-containers-per-container: 1
    docker-address: unix:///var/run/docker.sock
    runtime-type: docker
    remote-runtime-endpoint: unix:///var/run/dockershim.sock
    remote-image-endpoint: unix:///var/run/dockershim.sock
    runtime-request-timeout: 2
    podsandbox-image: kubeedge/pause:3.1 # kubeedge/pause:3.1 for x86 arch , kubeedge/pause-arm:3.1 for arm arch, kubeedge/pause-arm64 for arm64 arch
    image-pull-progress-deadline: 60 # second
    cgroup-driver: cgroupfs
    node-ip: ""
    cluster-dns: ""
    cluster-domain: ""

mesh:
    loadbalance:
        strategy-name: RoundRobin
~
`
I set this:
mqtt mode:2 
Is it right???
The cloud side and edge side both are in the same LAN, for test.

**Comment by kadisi** [comment]
no， you need change kubeconfig config in conf/controller.yaml。 `system:kube-controller-manager` should have no permission to change the state of the node.

**Comment by fisherxu** [comment]
> no， you need change kubeconfig config in conf/controller.yaml。 system:kube-controller-manager should have no permission to change the state of the node.

+1

And if you want to use your own mosquito,  set `mqtt mode:2` is correct :) @noizz

**Comment by noizz** [comment]
'
# more /etc/kubernetes/controller-manager.conf
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ......
    server: https://192.168.36.161:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:kube-controller-manager
  name: system:kube-controller-manager@kubernetes
current-context: system:kube-controller-manager@kubernetes
kind: Config
preferences: {}
users:
- name: system:kube-controller-manager
  user:
    client-certificate-data: ...
    client-key-data:...
'
'
# more conf/controller.yaml
controller:
  kube:
    master:     # kube-apiserver address (such as:http://localhost:8080)
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    node_update_frequency: 10
    kubeconfig: "/etc/kubernetes/controller-manager.conf"   #Enter path to kubeconfig file to enable https connection to k8s apiserver, if master and kubeconfig are both set, master will over
ride any value in kubeconfig.
cloudhub:
  protocol_websocket: true # enable websocket protocol
  port: 10000 # open port for websocket server
  protocol_quic: true # enable quic protocol
  quic_port: 10001 # open prot for quic server
  max_incomingstreams: 10000 # the max incoming stream for quic server
  enable_uds: true # enable unix domain socket protocol
  uds_address: unix:///var/lib/kubeedge/kubeedge.sock # unix domain socket address
  address: 0.0.0.0
  ca: /etc/kubeedge/ca/rootCA.crt
  cert: /etc/kubeedge/certs/edge.crt
  key: /etc/kubeedge/certs/edge.key
  keepalive-interval: 30
  write-timeout: 30
  node-limit: 10
devicecontroller:
  kube:
    master:        # kube-apiserver address (such as:http://localhost:8080)
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    kubeconfig: "/etc/kubernetes/controller-manager.conf" #Enter path to kubeconfig file to enable https connection to k8s apiserver,if master and kubeconfig are both set, master will overrid
e any value in kubeconfig.
'
Is it right?

I did as the setup document. 
https://docs.kubeedge.io/en/latest/setup/setup.html

**Comment by kadisi** [comment]
@noizz   you need change `kubeconfig: "/etc/kubernetes/controller-manager.conf"` config. because in `/etc/kubernetes/controller-manager.conf`, it is `system:kube-controller-manager` use, it  should have no permission to change the state of the node.

**Comment by sids-b** [comment]
@jparrill , can you try to use websocket protocol and see if the node comes up ? edgehub.controller.protocol: websocket

**Comment by jparrill** [comment]
I've tried with both... I'm thinking that could be something related with
K8s network, Kubeedge has any connectivity reqs to work properly?.

**Comment by subpathdev** [comment]
which protocol do you want to use for the connection between cloudhub and edgehub? you have enabled 3 protocols.

With this configuration controller configuration I've tested successfully:
[controller.yaml]
```    
  controller:
      kube:
        master: https://kubernetes.default.svc.cluster.local:443
        kubeconfig: /etc/kubeedge/cloud/kubeconfig.yaml
        namespace: ""
        content_type: "application/vnd.kubernetes.protobuf"
        qps: 5
        burst: 10
        node_update_frequency: 10
    cloudhub:
      protocol_websocket: true
      address: 0.0.0.0
      port: 10000
      ca: /etc/kubeedge/certs/rootCA.pem
      cert: /etc/kubeedge/certs/cloud.pem
      key: /etc/kubeedge/certs/cloud.key
      keepalive-interval: 30
      write-timeout: 30
      node-limit: 10
    devicecontroller:
       kube:
         master: https://kubernetes.default.svc.cluster.local:443
         namespace: ""
         content_type: "application/vnd.kubernetes.protobuf"
         qps: 5
         burst: 10
         kubeconfig: "/etc/kubeedge/cloud/kubeconfig.yaml"
```

**Comment by subpathdev** [comment]
@jparrill can you test it with the configuration above?
(I think you have to change the address of the master node, the path of the kubeconfig and the certificates definitions)

**Comment by jparrill** [comment]
I've changed Kubeconfig one, the Address is still 0.0.0.0 because I want to expose to all interfaces, the certs stays in the same way, because exists in that place. 

regards

**Comment by jparrill** [comment]
One question @subpathdev, why did you specify the `controller.kube.master` if you already has set the `controller.kube.kubeconfig`, also for `devicecontroller.kube.master` vs `devicecontroller.kube.kubeconfig`?

**Comment by subpathdev** [comment]
Good question I don't know. I copied the the configuration from [0] and had to enable the websocket_protocol:

[0] https://github.com/kubeedge/kubeedge/blob/master/build/cloud/05-configmap.yaml

**Comment by fisherxu** [comment]
@jparrill  @subpathdev  If you have specified the kubeconfig, it's no need specify the master, the master address will override the kubeconfig file

**Comment by fisherxu** [comment]
@jparrill  you can try this script :) `hack/local-up-kubeedge.sh`, which start kubeedge in one VM

**Comment by qinzhuoxing** [comment]
message: eba2e190-1b95-4740-845b-3a875d0c64ea process failure, node qzx-node01-a not found
why the node is not found, but edge and cloud can communication

**Comment by xianhongdong** [comment]
i have the same problem but i have soleve this problem by other helps. below is the edgecore logs:
I0114 14:09:17.350187   58908 upstream.go:186] dispatch message: 424e06c4-3e97-4461-88d4-9a946635a87e
W0114 14:09:17.350193   58908 upstream.go:190] parse message: 424e06c4-3e97-4461-88d4-9a946635a87e resource type with error: resource type not found
I0114 14:09:17.352586   58908 eventhandler.go:98] Keepalive message received from node: test123
I0114 14:09:17.352649   58908 eventhandler.go:201] event received for node test123 id: f5b30066-bd47-40cc-84c2-239d90c15506, parent_id: , group: resource, source: twin, resource: node/test123/membership/detail, operation: get, content: {"event_type":"group_membership_event","event_id":"123","group_id":"test123","operation":"detail","timestamp":1578982157376}
I0114 14:09:17.352681   58908 upstream.go:94] Dispatch message: f5b30066-bd47-40cc-84c2-239d90c15506
W0114 14:09:17.352686   58908 upstream.go:98] Parse message: f5b30066-bd47-40cc-84c2-239d90c15506 resource type with error: unknown resource
I0114 14:09:17.352700   58908 eventhandler.go:135] Node test123 is still alive

this is because of my docker cgroupdriver is differenct from the cgroup-driver config of conf/edge.yaml file. change the config to 'systemd' can resolov this problem. may sure that the cgroup-driver is same from /etc/docker/daemon.json file
