### ISSUE TITLE
keadm v1.10 init failed

### ISSUE THREAD

**Issue by ryanpatiency** [kubeedge/kubeedge#1139]
**What happened**:
`sudo keadm init`
`error: failed to run 'sh -c cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v0.3.0-linux-amd64.tar.gz && cp /etc/kubeedge//kubeedge/edge/edgecore /usr/local/bin/.' because of error : exit status 1
`

**Comment by NoWhere-zh** [comment]
the pull request #1137 has fixed this bug. please try.
if it does not work, please check  keadm/app/cmd/util/ubuntuinstaller.go line 490

**Comment by ryanpatiency** [comment]
Thank you

**Comment by sids-b** [comment]
@ryanpatiency , try to use the --kubeedge-version flag and set it to v1.1.0

**Comment by jahentao** [comment]
for `v1.1.0`, my fixes in #1193

**Comment by fisherxu** [comment]
Please try the latest version of KubeEdge :)
/close
