### ISSUE TITLE
Docker & Kubernetes version

### ISSUE THREAD

**Issue by liuht777** [kubeedge/kubeedge#1140]
./keadm init --docker-version=18.09.7 --kubernetes-version=1.15.4 --kubeedge-version=1.1.0 --kube-config=~/.kube/config

got error 'Expected Docker version is not available in OS repo'

What version is support for docker and Kubernetes ?

**Comment by huangy7** [comment]
@liuht777 ,is this issue solved?I am facing the issue.too

**Comment by NoWhere-zh** [comment]
my docker version is 18.09.0 and kubernetes version is 1.15.0 and kubeedge version is 1.1.0 
it works and i don't know if it matters
oh, i did not use keadm init but just start up the kubeedge with the binary file directly

**Comment by gnodli** [comment]
your environment is centos or Ubuntu？

**Comment by fisherxu** [comment]
Please try latest verion of keadm v1.2.1 :)
/close
