### ISSUE TITLE
Get kube config failed with error: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by sjw1230** [kubeedge/kubeedge#1144]
I0923 15:44:45.761653    9299 buffer.go:142] Update controller.buffer.query-persistentvolume: 1024
I0923 15:44:45.761655    9299 buffer.go:149] Update controller.buffer.query-persistentvolumeclaim: 1024
I0923 15:44:45.761658    9299 buffer.go:156] Update controller.buffer.query-volumeattachment: 1024
I0923 15:44:45.761661    9299 buffer.go:163] Update controller.buffer.query-node: 1024
I0923 15:44:45.761664    9299 buffer.go:170] Update controller.buffer.update-node: 1024
I0923 15:44:45.761667    9299 context.go:29]  send module name: cloudhub
I0923 15:44:45.761670    9299 context.go:36] receive module name: edgecontroller
I0923 15:44:45.761672    9299 context.go:43] response module name: cloudhub
I0923 15:44:45.761670    9299 buffer.go:25] Update devicecontroller.buffer.update-device-status: 1024
I0923 15:44:45.761678    9299 buffer.go:32] Update devicecontroller.buffer.device-event: 1
E0923 15:44:45.761680    9299 kube.go:30] Controller kube master not set
I0923 15:44:45.761680    9299 buffer.go:39] Update devicecontroller.buffer.device-model-event: 1
I0923 15:44:45.761683    9299 kube.go:34] Controller kube master: 
I0923 15:44:45.761684    9299 context.go:29] Send module name: cloudhub
I0923 15:44:45.761686    9299 kube.go:41] Controller kube config: /root/.kube/config
I0923 15:44:45.761687    9299 context.go:36] Receive module name: devicecontroller
I0923 15:44:45.761690    9299 kube.go:46] Controller kube namespace: 
I0923 15:44:45.761690    9299 context.go:43] Response module name: cloudhub
E0923 15:44:45.761716    9299 kube.go:30] Devicecontroller kube master not set
I0923 15:44:45.761719    9299 kube.go:34] Devicecontroller kube master: 
I0923 15:44:45.761719    9299 server.go:45] start unix domain socket server
I0923 15:44:45.761724    9299 kube.go:41] Devicecontroller kube config: /root/.kube/config
I0923 15:44:45.761727    9299 kube.go:48] Devicecontroller kube namespace: 
I0923 15:44:45.761731    9299 kube.go:55] Devicecontroller kube content type: application/vnd.kubernetes.protobuf
I0923 15:44:45.761735    9299 kube.go:62] Devicecontroller kube QPS: 5.000000
I0923 15:44:45.761740    9299 kube.go:69] Devicecontroller kube burst: 10
I0923 15:44:45.761743    9299 load.go:19] Update device status workers: 1
I0923 15:44:45.761745    9299 messagelayer.go:19] Message layer: context
I0923 15:44:45.761694    9299 kube.go:51] Controller kube content type: application/vnd.kubernetes.protobuf
E0923 15:44:45.761768    9299 uds.go:68] failed to listen addr: listen unix //var/lib/kubeedge/kubeedge.sock: bind: no such file or directory
I0923 15:44:45.761772    9299 kube.go:56] Controller kube QPS: 5.000000
I0923 15:44:45.761780    9299 kube.go:61] Controller kube burst: 10
I0923 15:44:45.761787    9299 kube.go:66] Controller kube update frequency: 10s
I0923 15:44:45.761794    9299 kube.go:72] Controller kube Node ID: 
I0923 15:44:45.761799    9299 kube.go:79] Controller kube Node Name: 
I0923 15:44:45.761805    9299 kube.go:86]  EdgeSite is false 
I0923 15:44:45.761809    9299 load.go:49] update pod status workers: 1
I0923 15:44:45.761813    9299 load.go:56] update node status workers: 1
I0923 15:44:45.761817    9299 load.go:63] query config map workers: 4
I0923 15:44:45.761822    9299 load.go:70] query secret workers: 4
I0923 15:44:45.761826    9299 load.go:77] query service workers: 4
I0923 15:44:45.761830    9299 load.go:84] query endpoints workers: 4
I0923 15:44:45.761835    9299 load.go:91] query persistentvolume workers: 4
I0923 15:44:45.761839    9299 load.go:98] query persistentvolumeclaim workers: 4
I0923 15:44:45.761844    9299 load.go:105] query volumeattachment workers: 4
W0923 15:44:45.761842    9299 kubeclient.go:16] Get kube config failed with error: invalid configuration: no configuration has been provided
I0923 15:44:45.761848    9299 load.go:112] query node workers: 4
W0923 15:44:45.761852    9299 downstream.go:843] Create kube client failed with error: invalid configuration: no configuration has been provided
I0923 15:44:45.761855    9299 load.go:119] update node workers: 4
E0923 15:44:45.761857    9299 module.go:45] New downstream controller failed with error: invalid configuration: no configuration has been provided
root@dell:/usr/local/go/gopath/src/github.com/kubeedge/kubeedge/cloud# ./cloudcore 
2019/09/23 15:44:47 RollingPolicy is empty, use default policy[size]
2019-09-23 15:44:47.267 +08:00 INFO go-archaius/archaius.go:53 Configuration files: 
2019-09-23 15:44:47.267 +08:00 WARN config-manager/configurationmanager.go:140 empty configurtion from FileSource
2019-09-23 15:44:47.267 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:FileSource
2019-09-23 15:44:47.267 +08:00 INFO go-archaius/archaius.go:112 archaius init success
2019-09-23 15:44:47.267 +08:00 WARN config-manager/configurationmanager.go:140 empty configurtion from MemorySource
2019-09-23 15:44:47.267 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:MemorySource
2019-09-23 15:44:47.267 +08:00 WARN config-manager/configurationmanager.go:140 empty configurtion from CommandlineSource
2019-09-23 15:44:47.267 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:CommandlineSource
2019-09-23 15:44:47.267 +08:00 INFO enviromentvariable-source/envconfigurationsource.go:46 enable env source
2019-09-23 15:44:47.268 +08:00 INFO file-source/filesource.go:354 create new watcher
2019-09-23 15:44:47.268 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:EnvironmentSource
2019-09-23 15:44:47.268 +08:00 INFO memory-source/memorysource.go:105 mem source callback prepared
I0923 15:44:47.272279    9335 server.go:36] Version: v1.1.0-beta.0.20+31e562bc489105
2019-09-23 15:44:47.272 +08:00 INFO core/module.go:41 module cloudhub registered
2019-09-23 15:44:47.272 +08:00 INFO core/module.go:41 module edgecontroller registered
2019-09-23 15:44:47.272 +08:00 INFO core/module.go:41 module devicecontroller registered
2019-09-23 15:44:47.272 +08:00 INFO core/core.go:23 starting module edgecontroller
2019-09-23 15:44:47.272 +08:00 INFO core/core.go:23 starting module devicecontroller
2019-09-23 15:44:47.272 +08:00 INFO core/core.go:23 starting module cloudhub
I0923 15:44:47.272475    9335 buffer.go:25] Update devicecontroller.buffer.update-device-status: 1024
I0923 15:44:47.272488    9335 buffer.go:32] Update devicecontroller.buffer.device-event: 1
I0923 15:44:47.272491    9335 buffer.go:39] Update devicecontroller.buffer.device-model-event: 1
I0923 15:44:47.272494    9335 context.go:29] Send module name: cloudhub
I0923 15:44:47.272497    9335 context.go:36] Receive module name: devicecontroller
I0923 15:44:47.272500    9335 context.go:43] Response module name: cloudhub
E0923 15:44:47.272508    9335 kube.go:30] Devicecontroller kube master not set
I0923 15:44:47.272510    9335 kube.go:34] Devicecontroller kube master: 
I0923 15:44:47.272514    9335 kube.go:41] Devicecontroller kube config: /root/.kube/config
I0923 15:44:47.272518    9335 kube.go:48] Devicecontroller kube namespace: 
I0923 15:44:47.272521    9335 kube.go:55] Devicecontroller kube content type: application/vnd.kubernetes.protobuf
I0923 15:44:47.272522    9335 server.go:45] start unix domain socket server
I0923 15:44:47.272525    9335 kube.go:62] Devicecontroller kube QPS: 5.000000
I0923 15:44:47.272532    9335 kube.go:69] Devicecontroller kube burst: 10
I0923 15:44:47.272542    9335 load.go:19] Update device status workers: 1
I0923 15:44:47.272546    9335 messagelayer.go:19] Message layer: context
E0923 15:44:47.272578    9335 uds.go:68] failed to listen addr: listen unix //var/lib/kubeedge/kubeedge.sock: bind: no such file or directory
W0923 15:44:47.272624    9335 kubeclient.go:16] Get kube config failed with error: invalid configuration: no configuration has been provided
W0923 15:44:47.272635    9335 downstream.go:843] Create kube client failed with error: invalid configuration: no configuration has been provided
E0923 15:44:47.272641    9335 module.go:45] New downstream controller failed with error: invalid configuration: no configuration has been provided

**Comment by codersdady** [comment]
I have encountered the same problem, can you send a detailed registration step?

**Comment by fisherxu** [comment]
@sjw1230 @codersdady Have you specified the kubeconfig file Path? https://github.com/kubeedge/kubeedge/blob/master/cloud/conf/controller.yaml#L9

**Comment by sjw1230** [comment]
> @sjw1230 @codersdady Have you specified the kubeconfig file Path? https://github.com/kubeedge/kubeedge/blob/master/cloud/conf/controller.yaml#L9

**Comment by fisherxu** [comment]
@sjw1230 yeah sure right, and does the `/root/.kube/config` exist in your VM?

**Comment by sjw1230** [comment]
@fisherxu  Do you have Wechat? 
yes,the /root/.kube/config exists in my VM.

**Comment by sjw1230** [comment]
![2019-09-23 17-01-40屏幕截图](https://user-images.githubusercontent.com/44339184/65413505-26a44700-de24-11e9-9360-da936bd391ed.png)

**Comment by sjw1230** [comment]
but config have nothing
![2019-09-23 17-05-12屏幕截图](https://user-images.githubusercontent.com/44339184/65413658-7f73df80-de24-11e9-9f42-0edf714ff438.png)

**Comment by fisherxu** [comment]
Yes, I think this is the problem, my Wechat is `csxufei10335` :)

**Comment by NoWhere-zh** [comment]
do u have config file in /etc/kubernetes/admin.conf ?
if the file has content, u can use it directly or copy it to /root/.kube/config
please try

**Comment by sjw1230** [comment]
@NoWhere-zh  this problem has been solved，thank you very much.

**Comment by zhangshen023** [comment]
> @NoWhere-zh this problem has been solved，thank you very much.

i meet the same problem,could you tell me how to solve,thanks

**Comment by sjw1230** [comment]
@zhangshen023  
Please specified the kubeconfig path then change the cloud controller.yaml 
or change the path in cloud controller.yaml to /etc/kubernetes/admin.conf

**Comment by NoWhere-zh** [comment]
> > @NoWhere-zh this problem has been solved，thank you very much.
> 
> i meet the same problem,could you tell me how to solve,thanks

it seems that there is no config file in your environment. please copy the /etc/kubernetes/admin.conf to $HOME/.kube/config. kubeedge will use it. please check the file ：)

**Comment by fisherxu** [comment]
Seems issue has been resolved, close it now :)
/close

**Comment by DapengLan** [comment]
hi, I also face the same issue. I don't have both files: /etc/kubernetes/admin.conf to $HOME/.kube/config.  Anyone can help?

**Comment by fisherxu** [comment]
> hi, I also face the same issue. I don't have both files: /etc/kubernetes/admin.conf and $HOME/.kube/config. Anyone can help?

How do you deploy K8s and how does your kubectl use kubeconfig?

**Comment by DapengLan** [comment]
> > hi, I also face the same issue. I don't have both files: /etc/kubernetes/admin.conf and $HOME/.kube/config. Anyone can help?
> 
> How do you deploy K8s and how does your kubectl use kubeconfig?
Here is my configuration:
# uname -a
Linux kubeedgecloud 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I install Kubernete 1.8.0 using kuberadm, following the instructions here: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

with command:
sudo apt-get update && sudo apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

**Comment by fisherxu** [comment]
Maybe you haven't created the K8s cluster. ref: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Comment by DapengLan** [comment]
> Maybe you haven't created the K8s cluster. ref: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

Hi, I fixed the issue. after I initiate the K8s cluster and copy the path from /etc/kubernetes/admin.conf to $HOME/.kube/config.

thank you.
