### ISSUE TITLE
Add ci tests for different k8s versions

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1147]
**What would you like to be added/modified**:

Add ci tests for different k8s versions.

**Why is this needed**:

Users may have different versions of k8s， we need to verify if Kubeedge support different k8s versions（eg 1.13.*, 1.14.* ,1.15.* , 1.16.* ）.  so we can give users some suggestions .

cc @kevin-wangzefeng @sids-b @fisherxu @subpathdev @rohitsardesai83

**Comment by kevin-wangzefeng** [comment]
Sounds useful to me, we can use one primary version of k8s for PR checkings, and probably make the others checked nightly etc.
