### ISSUE TITLE
cannot delete a terminated pod

### ISSUE THREAD

**Issue by NoWhere-zh** [kubeedge/kubeedge#1149]
**What happened**:
    i used kubeedge to deploy an etcd pod to an edge node. some errors occured and the pod was terminated. then i wanted to delete the terminated pod.
    but when i executed the deleting command, nothing happened after the deleting log was printed. the command was blocked. then i pressed <ctrl + c > to interrupt the command.  the pod was still there. i cannot delete it successfully.
    here are the screenshots about the process and the pod info
![Snipaste_2019-09-24_14-44-45](https://user-images.githubusercontent.com/55520097/65489445-c40f8180-dedd-11e9-95eb-a37fdd2a6290.png)
![Snipaste_2019-09-24_14-45-48](https://user-images.githubusercontent.com/55520097/65489446-c40f8180-dedd-11e9-9b1b-98a9a0f4940b.png)
![Snipaste_2019-09-24_14-46-06](https://user-images.githubusercontent.com/55520097/65489447-c4a81800-dedd-11e9-8491-f3184c1e5024.png)

**What you expected to happen**:
i expected to delete the terminated pod successfully
**How to reproduce it (as minimally and precisely as possible)**:
i just deployed an etcd pod to the edge node and failed. then delete the pod.

**Environment**:
- KubeEdge version: v1.0.0
- Kubernetes version:v.1.15.0
- OS:
Ubuntu 18.04.1 LTS in virtualbox

**Comment by subpathdev** [comment]
you can delete the pod with this command: `kubectl delete pod <pod name> --force --grace-period 0`

It is useful to add an taint on the edge node, because an etcd or an kube-proxy should not executed on the edge-node. (I have to change the node.json definition ...)

**Comment by NoWhere-zh** [comment]
> you can delete the pod with this command: `kubectl delete pod <pod name> --force --grace-period 0`
> 
> It is useful to add an taint on the edge node, because an etcd or an kube-proxy should not executed on the edge-node. (I have to change the node.json definition ...)

thank u very much. it worked.
but i wonder if it is a bug because i have to use --force to delete a terminated pod by force instead of    deleting it through normal methods.

one more thing. the edgecore on edge node is still trying to sync some infomation about a container after i have delete the etcd pod. i believe that the container has something related with the pod, which means that the cloud deletes a pod and it does not tell the edge. maybe this can be improved. 
here is the screenshot of the edge node finding the container:

**Comment by NoWhere-zh** [comment]
> you can delete the pod with this command: `kubectl delete pod <pod name> --force --grace-period 0`
> 
> It is useful to add an taint on the edge node, because an etcd or an kube-proxy should not executed on the edge-node. (I have to change the node.json definition ...)

sorry the picture is down. i will try to upload it later. glad to discuss this issue.

**Comment by qizha** [comment]
I found that a running pod can not be deleted neither
