### ISSUE TITLE
"make clean" not found to remove the binaries

### ISSUE THREAD

**Issue by sameersarkar1979** [kubeedge/kubeedge#115]
**What would you like to be added**:
Implement "make clean" in build steps

**Why is this needed**:
To remove older binaries. It helps developers to create fresh binaries. Also it can be used in automation script so that the setup always has freshly created binaries, in-case the tests need to be re-executed in current context.

**Comment by m1093782566** [comment]
@sameersarkar1979 

Shall we remove the old configurations as well?

**Comment by sameersarkar1979** [comment]
1. For re-building the code and running it again, 
                a. Stopping of edge-core process cleanly.
                b. Remove the edgecore binaries.
2. For UT (With code coverage) - Removal of generated coverage files, etc
3. For IT - a. Stopping of edge-core process cleanly.
                b. Remove the edge-core binary and all the integration test binaries created at runtime.
                c. Moving log files to a temporary location, so that they don't get over-written.
                d. Some of the configurations made in "https://github.com/kubeedge/kubeedge/blob/master/test/integration/scripts/execute.sh" can be cleaned up.

**Comment by m1093782566** [comment]
sounds like a reasonable plan @sameersarkar1979 

Please just go ahead :)

**Comment by rohitsardesai83** [comment]
@sameersarkar1979 , any updates on this ?

**Comment by sameersarkar1979** [comment]
@srivatsav123 will be working this issue

**Comment by srivatsav123** [comment]
@sameersarkar1979 @rohitsardesai83 -Please review
