### ISSUE TITLE
ERROR client/ws.go:78 dial websocket error(read tcp 202.199.13.215:36152->202.199.6.92:30030: i/o timeout), response message:

### ISSUE THREAD

**Issue by sjw1230** [kubeedge/kubeedge#1152]
**What happened**:

I0924 09:26:38.293160    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:39.293491    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:40.293860    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:41.294184    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:42.294531    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:42.819001    1625 edged_status.go:163] Sync VolumesInUse: []
I0924 09:26:42.829486    1625 msg_processor.go:634] get a message {Header:{ID:bef347dd-66f8-4b71-ada1-a57916205739 ParentID: Timestamp:1569288402819 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/edge-raspi1} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:4095737856 scale:0} d:{Dec:<nil>} s:3906Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:3990880256 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-09-24 09:26:42.750454237 +0800 CST m=+20.902870455 LastTransitionTime:2019-09-24 09:26:42.750454237 +0800 CST m=+20.902870455 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:202.199.13.215} {Type:Hostname Address:raspberrypi-1}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.19.57-v7l+ OSImage:Raspbian GNU/Linux 10 (buster) ContainerRuntimeVersion:remote://19.3.2 KubeletVersion:v1.15.3-kubeedge-v1.1.0 KubeProxyVersion: OperatingSystem:linux Architecture:arm} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I0924 09:26:42.863744    1625 metaclient.go:117] send sync message default/nodestatus/edge-raspi1 successed and response: {{cef6e854-ac59-421f-836b-70d643d918af bef347dd-66f8-4b71-ada1-a57916205739 1569288402863 false} {edged meta response default/nodestatus/edge-raspi1} OK}
I0924 09:26:43.294817    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:44.295109    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:45.295448    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:46.295799    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:47.296122    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:48.296477    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:49.296927    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:50.297298    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:51.297550    1625 generic.go:81] GenericLifecycle: Relisting
2019-09-24 09:26:52.216 +08:00 ERROR client/ws.go:78 dial websocket error(read tcp 202.199.13.215:36152->202.199.6.92:30030: i/o timeout), response message: 
E0924 09:26:52.216733    1625 websocket.go:76] Init websocket connection failed read tcp 202.199.13.215:36152->202.199.6.92:30030: i/o timeout
I0924 09:26:52.297860    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:52.933398    1625 edged_status.go:163] Sync VolumesInUse: []
I0924 09:26:52.943774    1625 msg_processor.go:634] get a message {Header:{ID:1e29154a-9f24-4118-b9e5-47438994b493 ParentID: Timestamp:1569288412933 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/edge-raspi1} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:4095737856 scale:0} d:{Dec:<nil>} s:3906Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:3990880256 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-09-24 09:26:52.864295502 +0800 CST m=+31.016711553 LastTransitionTime:2019-09-24 09:26:52.864295502 +0800 CST m=+31.016711553 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:202.199.13.215} {Type:Hostname Address:raspberrypi-1}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.19.57-v7l+ OSImage:Raspbian GNU/Linux 10 (buster) ContainerRuntimeVersion:remote://19.3.2 KubeletVersion:v1.15.3-kubeedge-v1.1.0 KubeProxyVersion: OperatingSystem:linux Architecture:arm} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I0924 09:26:52.956039    1625 metaclient.go:117] send sync message default/nodestatus/edge-raspi1 successed and response: {{1f7375e1-69f1-42ac-ad18-4978de325eac 1e29154a-9f24-4118-b9e5-47438994b493 1569288412955 false} {edged meta response default/nodestatus/edge-raspi1} OK}
I0924 09:26:53.298125    1625 generic.go:81] GenericLifecycle: Relisting
I0924 09:26:54.298417    1625 generic.go:81] GenericLifecycle: Relisting

when raspberrypi runned ./edgecore,this error happened.

**Environment**:
- KubeEdge version: v1.1
- kubernetes version: v1.15.3
- OS (e.g. from /etc/os-release): Raspbian GNU/Linux 10 (buster)
- Kernel (e.g. `uname -a`): armv7l
- Others:

**Comment by kadisi** [comment]
@sjw1230 please show your edge.yaml config.   and `telnet 202.199.6.92 30030`

**Comment by sjw1230** [comment]
@kadisi 
edge.yaml

edgehub:
    websocket:
        url: wss://202.199.6.92:30030/e632aba927ea4ac2b575ec1603d56f10/edge-raspi1/events
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    quic:
        url: 127.0.0.1:10001
        cafile: /etc/kubeedge/ca/rootCA.crt
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    controller:
        protocol: websocket # websocket, quic
        heartbeat: 15  # second
        project-id: e632aba927ea4ac2b575ec1603d56f10
        node-id: edge-raspi1

edged:
    register-node-namespace: default
    hostname-override: edge-raspi1
    interface-name: eth0
    edged-memory-capacity-bytes: 7852396000
    node-status-update-frequency: 10 # second
    device-plugin-enabled: false
    gpu-plugin-enabled: false
    image-gc-high-threshold: 80 # percent
    image-gc-low-threshold: 40 # percent
    maximum-dead-containers-per-container: 1
    docker-address: unix:///var/run/docker.sock
    runtime-type: docker
    remote-runtime-endpoint: unix:///var/run/dockershim.sock
    remote-image-endpoint: unix:///var/run/dockershim.sock
    runtime-request-timeout: 2
    podsandbox-image: kubeedge/pause:3.1 # kubeedge/pause:3.1 for x86 arch , kubeedge/pause-arm:3.1 for arm arch, kubeedge/pause-arm64 for arm64 arch
    image-pull-progress-deadline: 60 # second
    cgroup-driver: cgroupfs
    node-ip: ""
    cluster-dns: ""
    cluster-domain: ""

mesh:
    loadbalance:
        strategy-name: RoundRobin

**Comment by sjw1230** [comment]
@kadisi 
telnet 202.199.6.92 30030

root@raspberrypi-1:/etc/kubeedge/edge/conf# telnet 202.199.6.92 30030
Trying 202.199.6.92...
Connected to 202.199.6.92.
Escape character is '^]'.

**Comment by sharkwang** [comment]
same problem after upgrade openssl library to latest version.

**Comment by Penny20181222** [comment]
same problem
