### ISSUE TITLE
wrong temperature number

### ISSUE THREAD

**Issue by dhdljd** [kubeedge/kubeedge#1153]
**What happened**:
I used TI sensorTag(CC2650)+raspberry3b+kubeedge v1.0.0+CC2650example,I can read the temperature number from edge mqtt broker, but the number is wrong. For example the true number is about 25.4℃,the mapper feedback number is 32℃ or a very big big number ,and do not change.  
**What you expected to happen**:
if the temperature is 25.4℃，then the feedback number from CC2650 is cb2, its a two bytes number,in the Bluetooth mapper in the data_converter package(line 93 94 95) we use the function 'strconv.Itoa' to converte every byte to string, I think its a unsuitable method and  we will get a string as '12178',then the result will be 97 or other thing.
I think we can use the function 'hex.EncodeToString' , and the test result is right.
 initialStringValue = hex.EncodeToString(initialValue)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:v1.0.0
- Hardware configuration:raspberry3B+ TI sensorTag
- OS (e.g. from /etc/os-release):Raspbian 2018-06-17
- Kernel (e.g. `uname -a`)
- Others:

**Comment by zongke** [comment]
modbus_mapper code have some error
