### ISSUE TITLE
edgecore does not work correctly

### ISSUE THREAD

**Issue by alien19880726** [kubeedge/kubeedge#1154]
**What happened**:
2019-09-25 16:49:07.605 +08:00 ^[[0;31mERROR^[[0m client/ws.go:78 dial websocket error(x509: certificate signed by unknown authority), response message:
2019-09-25 16:49:07.605 +08:00 ^[[0;31mERROR^[[0m wsclient/websocket.go:76 Init websocket connection failed x509: certificate signed by unknown authority

**What you expected to happen**: node which edgecore process is working at is enrolled in the correct way

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

edge.yaml
edgehub:
    websocket:
        url: wss://10.162.196.246:19100/e632aba927ea4ac2b575ec1603d56f10/6cea3c2e-60d4-499e-a27d-a1c1164d2543/events
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    quic:
        url: 127.0.0.1:10001
        cafile: /etc/kubeedge/ca/rootCA.crt
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    controller:
        protocol: websocket # websocket, quic
        heartbeat: 15  # second
        project-id: e632aba927ea4ac2b575ec1603d56f10
        node-id: 6cea3c2e-60d4-499e-a27d-a1c1164d2543

**Comment by NoWhere-zh** [comment]
do u copy the correct certificate files to the edge?

**Comment by alien19880726** [comment]
> do u copy the correct certificate files to the edge?

I generated certificate files again, authentication issue is fixed, and then another error occurs, edgecore log as follows, did you deal with it before?
I0927 17:10:29.694545   10693 cpu_manager.go:155] [cpumanager] starting with none policy
I0927 17:10:29.694561   10693 cpu_manager.go:156] [cpumanager] reconciling every 0s
I0927 17:10:29.694571   10693 policy_none.go:42] [cpumanager] none policy: Start
I0927 17:10:29.695044   10693 status_manager.go:43] Starting to sync pod status with apiserver
I0927 17:10:29.695053   10693 volume_manager.go:243] Starting Kubelet Volume Manager
I0927 17:10:29.695066   10693 edged.go:765] start pod addition queue work 0
I0927 17:10:29.695074   10693 edged.go:765] start pod addition queue work 1
I0927 17:10:29.695078   10693 edged.go:765] start pod addition queue work 2
I0927 17:10:29.695082   10693 edged.go:765] start pod addition queue work 3
I0927 17:10:29.695088   10693 edged.go:765] start pod addition queue work 4
I0927 17:10:29.695120   10693 edged.go:342] starting plugin manager
W0927 17:10:29.695122   10693 container_manager_linux.go:827] CPUAccounting not enabled for pid: 30115
I0927 17:10:29.695133   10693 edged.go:345] starting syncPod
W0927 17:10:29.695135   10693 container_manager_linux.go:830] MemoryAccounting not enabled for pid: 30115
I0927 17:10:29.695125   10693 desired_state_of_world_populator.go:130] Desired state populator starts to run
I0927 17:10:29.695180   10693 generic.go:81] GenericLifecycle: Relisting
I0927 17:10:29.695214   10693 server.go:65] starting to listen on 127.0.0.1:10255
E0927 17:10:29.695246   10693 plugin_watcher.go:81] failed to traverse deprecated plugin socket path "/var/lib/edged/plugins", err: error accessing path: /var/lib/edged/plugins error: lstat /var/lib/edged/plugins: no such file or directory
I0927 17:10:29.695258   10693 plugin_manager.go:116] Starting Kubelet Plugin Manager
I0927 17:10:29.695638   10693 container_manager_linux.go:868] Found 108 PIDs in root, 108 of them are not to be moved
W0927 17:10:29.695693   10693 container_manager_linux.go:827] CPUAccounting not enabled for pid: 10693
W0927 17:10:29.695699   10693 container_manager_linux.go:830] MemoryAccounting not enabled for pid: 10693
2019-09-27 17:10:29.699 +08:00 ^[[0;34mINFO^[[0m client/ws.go:45 dial wss://10.249.159.34:10000/e632aba927ea4ac2b575ec1603d56f10/6cea3c2e-60d4-499e-a27d-a1c1164d2543/events successfully
I0927 17:10:29.699889   10693 websocket.go:79] Websocket connect to cloud access successful
2019-09-27 17:10:29.699 +08:00 ^[[0;33mWARN^[[0m context/context_channel.go:341 failed to get type channel, type(sync)
2019-09-27 17:10:29.699 +08:00 ^[[0;33mWARN^[[0m context/context_channel.go:186 bad module type (sync), do nothing
I0927 17:10:29.699970   10693 dtcontroller.go:79] DeviceTwin receive msg
I0927 17:10:29.700004   10693 dtcontroller.go:138] Send msg to the CommModule module in twin
I0927 17:10:29.700019   10693 communicate.go:35] receive msg commModule
I0927 17:10:29.700026   10693 communicate.go:90] CONNECTED EVENT
I0927 17:10:29.699990   10693 msg_processor.go:634] get a message {Header:{ID:e99617a3-304a-4d5b-bbac-d34f64cbfd42 ParentID: Timestamp:1569575429699 Sync:false} Router:{Source:edgehub Group:meta Operation:publish Resource:node/connection} Content:cloud_connected}
I0927 17:10:29.700070   10693 msg_processor.go:468] node connection event occur: cloud_connected
I0927 17:10:29.700079   10693 msg_processor.go:634] get a message {Header:{ID:991bb6a9-a262-4fcb-a4ba-ea77e028b467 ParentID: Timestamp:1569575429699 Sync:false} Router:{Source:edgehub Group:meta Operation:publish Resource:node/connection} Content:cloud_connected}
I0927 17:10:29.700112   10693 msg_processor.go:468] node connection event occur: cloud_connected
I0927 17:10:29.699972   10693 servicebus.go:57] ServiceBus receive msg
I0927 17:10:29.700088   10693 communicate.go:139] Request detail
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x277376a]

goroutine 186 [running]:
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/translator.(*MessageTranslator).protoToModel(0xc00076de60, 0xc000866190, 0xc000438300, 0x3369920, 0xc000866190) /home/edge/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/translator/message.go:21 +0x2a
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/translator.(*MessageTranslator).Decode(0xc00076de60, 0x4aaaec8, 0x0, 0x0, 0x2e722a0, 0xc000438300, 0xc000081680, 0x117e898)
/home/edge/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/translator/message.go:70 +0x13f
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/lane.(*WSLane).ReadMessage(0xc0001d0200, 0xc000438300, 0x2ece860, 0xc0003fdce0)
/home/edge/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/lane/ws.go:46 +0xa4
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).handleMessage(0xc0009ac000)
/home/edge/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn/ws.go:114 +0xa6
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).ServeConn
/home/edge/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn/ws.go:48 +0xff

**Comment by sids-b** [comment]
@alien19880726 , can try this out ? https://bugzilla.redhat.com/show_bug.cgi?id=1692131

**Comment by mumutu66** [comment]
installed with master branch 

got similar error  
```
 parse message: db478f08-82f7-4fa9-bce0-6b0edc76cdbc resource type with error: resource type not found

goroutine 2094 [running]:
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/translator.(*MessageTranslator).protoToModel(0xc002b66e60, 0xc000da8ff0, 0xc0020a7980, 0x168f3c0, 0xc000da8ff0)
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/translator/message.go:21 +0x2a
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/translator.(*MessageTranslator).Decode(0xc002b66e60, 0x22f2928, 0x0, 0x0, 0x1422420, 0xc0020a7980, 0xc000729680, 0x40c0f8)
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/translator/message.go:70 +0x13f
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/lane.(*WSLane).ReadMessage(0xc001eb05c0, 0xc0020a7980, 0x144df40, 0xc000fb5080)
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/lane/ws.go:46 +0xa4
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).handleMessage(0xc00120c1b0)
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn/ws.go:114 +0xa6
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).ServeConn
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn/ws.go:48 +0xff

```

and try to enable default Accounting from [Link](https://github.com/openshift/machine-config-operator/pull/581) but no effect

**Comment by kadisi** [comment]
> E0927 17:10:29.695246 10693 plugin_watcher.go:81] failed to traverse deprecated plugin socket path "/var/lib/edged/plugins", err: error accessing path: /var/lib/edged/plugins error: lstat /var/lib/edged/plugins: no such file or directory

i think you should create '/var/lib/edged/plugins' first.

and have you created deviceinstance  and devicemodel crd ?

**Comment by mumutu66** [comment]
solved the problem .. the doc in source code is out-of-date  cloud-core:1.1.0 is not compatible with the  newest edge-core  which is built  by the instructions [here](https://github.com/kubeedge/kubeedge/tree/master/build/edge)

**Comment by fisherxu** [comment]
> solved the problem ..

will close it .
/close
