### ISSUE TITLE
Edge node get not ready

### ISSUE THREAD

**Issue by zhangshen023** [kubeedge/kubeedge#1168]
**What happened**:
My edge node shows status not ready
![image](https://user-images.githubusercontent.com/12484497/65877146-7b643680-e3bd-11e9-93b3-d2a8dd5ba94e.png)

**What you expected to happen**:
My edge node hould be ready
**How to reproduce it (as minimally and precisely as possible)**:
   
**Anything else we need to know?**:
 I post my logs below.
cloudcore.log:
![image](https://user-images.githubusercontent.com/12484497/65877034-43f58a00-e3bd-11e9-9fe6-8bbd9ed033b0.png)
edgecode.log:
![image](https://user-images.githubusercontent.com/12484497/65877060-4e178880-e3bd-11e9-8968-5bfb2a690977.png)
and my edge config file:
![image](https://user-images.githubusercontent.com/12484497/65877130-71423800-e3bd-11e9-9133-76b7e1611553.png)

**Environment**:
- KubeEdge version: v1.1.0
- Hardware configuration: amd64
- OS (e.g. from /etc/os-release): ubuntu 16
- Kernel (e.g. `uname -a`): 
- Others:

**Comment by jparrill** [comment]
I've been dealing with the same problem from the past week: https://github.com/kubeedge/kubeedge/issues/1138#issuecomment-534560329

**Comment by subpathdev** [comment]
@jparrill, @zhangshen023 can you upload your cloudcore configuration?

**Comment by jparrill** [comment]
You got all the conf files here: https://github.com/kubeedge/kubeedge/issues/1138#issuecomment-534560329

**Comment by NoWhere-zh** [comment]
please try 
`kubectl describe node testing1`
and post the logs

**Comment by parkeunsoo** [comment]
I have same issue, so I have a question, is it necessary to commans "kubeadm join~" on edge side? I don'n know why on cloud side edge's status is NOT READY, seeing cloudcore's log , Cloudcore knows edge is alive but kubectl get nodes show me edge's status is NOTREADY

**Comment by subpathdev** [comment]
@parkeunsoo can you please upload your cloudcore log?

**Comment by NoWhere-zh** [comment]
> I have same issue, so I have a question, is it necessary to command "kubeadm join~" on edge side? I don't know why on cloud side edge's status is NOT READY, seeing cloudcore's log , Cloudcore knows edge is alive but kubectl get nodes show me edge's status is NOTREADY

no need to command "kubeadm join" because the edgecore will take control it and make the edge node join the cluster.

**Comment by subpathdev** [comment]
the command `kubeadm join` take command line flags and will create the correct configuration. You can modify the configuration by hand. After the creation kubeadm will execute the edgecore binary.

**Comment by parkeunsoo** [comment]
@subpathdev here edge node's name is edge-node
![image](https://user-images.githubusercontent.com/32799518/66357400-a1836b00-e9a9-11e9-98f5-da6f02384244.png)

**Comment by parkeunsoo** [comment]
@NoWhere-zh  Thanks! :) can I ask you two question? 

1. I post cloudcore, edgecore log above , there are communication edgecore and cloudcore , But when I command `kubectl get nodes` , there are edge-node's status is NOT READY so What I want to ask here is Regardless of 'kubectl get nodes' Is edgecore and cloudcore connected? If so, when is it like that? when I command `kubectl apply -f node.json`? when edgecore build?

2. according to your answer it is not necessary to command `kubeadm join~` on edge side. then, how do they authenticate each other ? And is that part in the source code?

**Comment by zhangshen023** [comment]
> @jparrill, @zhangshen023 can you upload your cloudcore configuration?

controller:
  kube:
    master: http://localhost:8080
    namespace: "kube-system"
    content_type: application/vnd.kubernetes.protobuf
    qps: 100
    burst: 10
    node_update_frequency: 20s
    kubeconfig: "/etc/kubeedge/config"
cloudhub:
  address: 0.0.0.0
  port: 10000
  ca: /etc/kubeedge/ca/rootCA.crt
  cert: /etc/kubeedge/certs/edge.crt
  key: /etc/kubeedge/certs/edge.key
  keepalive-interval: 30
  write-timeout: 30
  node-limit: 10
devicecontroller:
  kube:
    master: http://localhost:8080
    namespace: "kube-system"
    content_type: application/vnd.kubernetes.protobuf
    qps: 100
    burst: 10
    node_update_frequency: 0s
    kubeconfig: "/etc/kubeedge/config"

**Comment by zhangshen023** [comment]
> @jparrill, @zhangshen023 can you upload your cloudcore configuration?

controller:
  kube:
    master: http://localhost:8080
    namespace: "kube-system"
    content_type: application/vnd.kubernetes.protobuf
    qps: 100
    burst: 10
    node_update_frequency: 20s
    kubeconfig: "/etc/kubeedge/config"
cloudhub:
  address: 0.0.0.0
  port: 10000
  ca: /etc/kubeedge/ca/rootCA.crt
  cert: /etc/kubeedge/certs/edge.crt
  key: /etc/kubeedge/certs/edge.key
  keepalive-interval: 30
  write-timeout: 30
  node-limit: 10
devicecontroller:
  kube:
    master: http://localhost:8080
    namespace: "kube-system"
    content_type: application/vnd.kubernetes.protobuf
    qps: 100
    burst: 10
    node_update_frequency: 0s
    kubeconfig: "/etc/kubeedge/config"

> please try
> `kubectl describe node testing1`
> and post the logs

![image](https://user-images.githubusercontent.com/12484497/66358768-f40f5800-e9a6-11e9-9935-eb571eead82d.png)

**Comment by zhangshen023** [comment]
> please try
> `kubectl describe node testing1`
> and post the logs


Name:               testing1
Roles:              edge
Labels:             name=edge-node
                    node-role.kubernetes.io/edge=
Annotations:        node.alpha.kubernetes.io/ttl: 0
CreationTimestamp:  Mon, 30 Sep 2019 19:38:51 +0800
Taints:             node.kubernetes.io/unreachable:NoExecute
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                   Message
  ----             ------    -----------------                 ------------------                ------                   -------
  Ready            Unknown   Mon, 30 Sep 2019 19:38:51 +0800   Mon, 30 Sep 2019 19:38:54 +0800   NodeStatusNeverUpdated   Kubelet never posted node status.
  MemoryPressure   Unknown   Mon, 30 Sep 2019 19:38:51 +0800   Mon, 30 Sep 2019 19:38:54 +0800   NodeStatusNeverUpdated   Kubelet never posted node status.
  DiskPressure     Unknown   Mon, 30 Sep 2019 19:38:51 +0800   Mon, 30 Sep 2019 19:38:54 +0800   NodeStatusNeverUpdated   Kubelet never posted node status.
  PIDPressure      Unknown   Mon, 30 Sep 2019 19:38:51 +0800   Mon, 30 Sep 2019 19:38:54 +0800   NodeStatusNeverUpdated   Kubelet never posted node status.
Addresses:
System Info:
 Machine ID:                 
 System UUID:                
 Boot ID:                    
 Kernel Version:             
 OS Image:                   
 Operating System:           
 Architecture:               
 Container Runtime Version:  
 Kubelet Version:            
 Kube-Proxy Version:         
PodCIDR:                     192.169.23.0/24
Non-terminated Pods:         (0 in total)
  Namespace                  Name    CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----    ------------  ----------  ---------------  -------------  ---
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
Events:              <none>

**Comment by zhangshen023** [comment]
> please try
> `kubectl describe node testing1`
> and post the logs



![image](https://user-images.githubusercontent.com/12484497/66359190-bad7e780-e9a8-11e9-93ab-0179587f4d73.png)

**Comment by zhangshen023** [comment]
> @subpathdev Thanks :) here, edge node's name is edge-node
> 1.cloudcore
> ![image](https://user-images.githubusercontent.com/32799518/66357400-a1836b00-e9a9-11e9-98f5-da6f02384244.png)
> 2.edgecore
> ![image](https://user-images.githubusercontent.com/32799518/66357777-320e7b00-e9ab-11e9-8d63-28a966b41f89.png)
> 3.`kubectl get nodes`
> ![image](https://user-images.githubusercontent.com/32799518/66357802-48b4d200-e9ab-11e9-8570-153e2b5ff2a3.png)
> 4. `kubectl describe node edge-node`
> ![image](https://user-images.githubusercontent.com/32799518/66358732-21f89a80-e9af-11e9-9319-4f3923f00624.png)
> ![image](https://user-images.githubusercontent.com/32799518/66358753-3fc5ff80-e9af-11e9-82bd-b15a3dac379b.png)

We meet same problem! 
If you solve your problem, can you tell me?

**Comment by fisherxu** [comment]
@zhangshen023  @parkeunsoo  Could you plz upload your cloudcore config file? And please check whether the kubeconfig PATH is correct :)

**Comment by parkeunsoo** [comment]
@fisherxu Thanks :) Here
1. controller.yaml
![image](https://user-images.githubusercontent.com/32799518/66361011-1c538280-e9b8-11e9-8008-22e9bb5d6bfb.png)

2. .kube/config
![image](https://user-images.githubusercontent.com/32799518/66360955-e910f380-e9b7-11e9-8306-a192b0e1735f.png)

**Comment by zhangshen023** [comment]
> @zhangshen023 @parkeunsoo Could you plz upload your cloudcore config file? And please check whether the kubeconfig PATH is correct :)

correct,i'm sure

**Comment by NoWhere-zh** [comment]
> > @zhangshen023 @parkeunsoo Could you plz upload your cloudcore config file? And please check whether the kubeconfig PATH is correct :)
> 
> correct,i'm sure

according to your result of 'kubectl describe', it seems that the edgecore has never reported the status of the edge node to the cloudcore.
i cannot find the reason according to the current information provided. it's strange.
have you transfered the edge.key to the correct path of the edge node?
and i've compared the edge.yaml between you and me. i just change the websocket url and all the id of the edge node and no changes have been made elsewhere. i notice that you have changed somewhere else in the edge.yaml. i'm not sure if it is the reason. maybe you can try.   :)

**Comment by NoWhere-zh** [comment]
> @NoWhere-zh Thanks! :) can I ask you two question?
> 
> 1. I post cloudcore, edgecore log above. there are communication between edgecore and cloudcore , But when I command `kubectl get nodes` , there are edge-node's status is NOT READY so What I want to ask here is Regardless of 'kubectl get nodes' Is it possible to check if they are connected. If so, when is it like that? when I command `kubectl apply -f node.json`? when edgecore is built?
> 2. according to your answer it is not necessary to command `kubeadm join~` on edge side. then, how do they authenticate each other ? And is that part in the source code?

i'm not sure where is your problem. it's strange.
as for your two questions
1. it has been confirmed through 'kubectl get nodes' whether the edge node was ready. because if the node is not 'ready' according to the 'kubectl get nodes', the node will be labeled with 'not ready', and it  is an unacceptable stain for the deployments. no pod will be scheduled to a 'not ready' node.
and the edge node connects with the master when the edgecore runs.

2. when you change the websocket url of the edge.yaml, the edgecore can know where is the master node. and when you copy the edge.key to the correct path of the edge node, the edgecore can be authorized to connect with the master node.  so could you please post your edge.yaml and please check if you have copied the edge.key and edge.crt to the correct path.

**Comment by parkeunsoo** [comment]
@NoWhere-zh Thanks! :) It really helped me a lot. 
One of your comment: "because if the node is not 'ready' according to the 'kubectl get nodes', the node will be labeled with 'not ready', and it is an unacceptable stain for the deployments. no pod will be scheduled to a 'not ready' node."
I installed Kubeedge with reference to [https://docs.kubeedge.io/en/latest/setup/setup.html](url)
![image](https://user-images.githubusercontent.com/32799518/66459872-cadaee80-eab0-11e9-950a-e7299498628b.png)
I was in the process of "check status"
according to your comment Does it mean I was not in the process of "Deploy Application on cloud side"?
and
Can you see if there is anything strange about this file?
edge.yaml
![image](https://user-images.githubusercontent.com/32799518/66460258-771cd500-eab1-11e9-84dd-8fa9eb117b28.png)
![image](https://user-images.githubusercontent.com/32799518/66460293-961b6700-eab1-11e9-9088-987df3df0741.png)
cert,ca PATH (edge side)
![image](https://user-images.githubusercontent.com/32799518/66460370-bba87080-eab1-11e9-99b0-f20448e702cc.png)

**Comment by NoWhere-zh** [comment]
> @NoWhere-zh Thanks! :) It really helped me a lot.
> One of your comment: "because if the node is not 'ready' according to the 'kubectl get nodes', the node will be labeled with 'not ready', and it is an unacceptable stain for the deployments. no pod will be scheduled to a 'not ready' node."
> I installed Kubeedge with reference to [https://docs.kubeedge.io/en/latest/setup/setup.html](url)
> ![image](https://user-images.githubusercontent.com/32799518/66459872-cadaee80-eab0-11e9-950a-e7299498628b.png)
> I was in the process of "check status"
> according to your comment Does it mean I was not in the process of "Deploy Application on cloud side"?
> and
> Can you see if there is anything strange about this file?
> edge.yaml
> ![image](https://user-images.githubusercontent.com/32799518/66460258-771cd500-eab1-11e9-84dd-8fa9eb117b28.png)
> ![image](https://user-images.githubusercontent.com/32799518/66460293-961b6700-eab1-11e9-9088-987df3df0741.png)
> cert,ca PATH (edge side)
> ![image](https://user-images.githubusercontent.com/32799518/66460370-bba87080-eab1-11e9-99b0-f20448e702cc.png)
> cert,ca PATH (cloud side)
> ![image](https://user-images.githubusercontent.com/32799518/66461351-cebc4000-eab3-11e9-8558-18eee435dbee.png)
> 
> I transfered cert,ca on cloud side to edgeside

edgehub->websocket->url:  the port should be 10000 if u did not change it somewhere else.
and no need to fill the edged->node-ip. remaining "" is ok.
maybe it will help. please try
when the edge node is ready, then u can try to  "Deploy Application on cloud side".

**Comment by parkeunsoo** [comment]
@NoWhere-zh um..I tried this but to no avail.
I think may be there is a problem when I create cluster `kubeadm init` with config file
I don't know to need kubelet in process  but kubelet'log show error 
Is it related to kubelet error or kubeadm init config file?
`systemctl status -l kubelet`
![image](https://user-images.githubusercontent.com/32799518/66532546-bc411580-eb4a-11e9-91a8-be58eb53ee9f.png)
![image](https://user-images.githubusercontent.com/32799518/66532568-cebb4f00-eb4a-11e9-9cb7-768d65eb815c.png)

**Comment by fisherxu** [comment]
@parkeunsoo Have you run kubelet in edge node? It's no need to run kubelet in edgenode, because edged in edgecore is a mini-kubelet. And for the cloudside, if you deploy cloudcore as a process(not container), it has no relationship with your kubelet.

**Comment by parkeunsoo** [comment]
@fisherxu I run kubelet in cloud , I think may be it run with kubeadm init  
and Can I ask you two question? 1.Don't need kubelet on cloud? 2. After i command`kubectl describe node edge-node` message is "kubelet never posted node status" Does kubelet on the message mean edge's kubelet?

**Comment by fisherxu** [comment]
hi @parkeunsoo 
1. If you don't run application in cloud, kubelet will no need.
2. edgecore's edged is a mini-kubelet, cut some alpha features in kubelet that are not needed at the edge, in fact, it's also a kubelet. And yes, kubelet on the message mean edge's kubelet.

**Comment by parkeunsoo** [comment]
@zhangshen023  @fisherxu @NoWhere-zh I solved the problem! Thansk to guys
![image](https://user-images.githubusercontent.com/32799518/66537169-80ae4780-eb5a-11e9-9edd-1facfebddc32.png)
the problem is kubelet cgroup driver is diffrent from docker cgroup driver on edge-node 
so I modify docker cgroup driver to cgroupfs

**Comment by fisherxu** [comment]
@parkeunsoo sound good!! 
@zhangshen023  Has your issue been solved?

**Comment by zhangshen023** [comment]
yes,solved,thanks.But i don't konw why,i just follow this document https://docs.kubeedge.io/en/latest/setup/setup.html

**Comment by zhangshen023** [comment]
> @zhangshen023 @fisherxu @NoWhere-zh I solved the problem! Thansk to guys
> ![image](https://user-images.githubusercontent.com/32799518/66537169-80ae4780-eb5a-11e9-9edd-1facfebddc32.png)
> the problem is kubelet cgroup driver is diffrent from docker cgroup driver on edge-node
> so I modify docker cgroup driver to cgroupfs

Mayby,solving way to my problem is the same as yours .My vm had ben destoryed。

**Comment by Ranler** [comment]
I have same problem, k8s is v1.14.1, kubeedge is v1.1.0， cloud side is vm node， edge side is raspberrypi.

And After create a new edge node, there will create a new kube-proxy but always Pending， and edge node is always NotReady.

![图片](https://user-images.githubusercontent.com/742910/66543116-0d5f0280-eb67-11e9-83cd-0466e158464c.png)

**Comment by mumutu66** [comment]
it seems the both side docker cgroup driver should be same ?. since the cgroupfs is not recommended change both to systemd also works
