### ISSUE TITLE
Cross build failed

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1175]
**Which jobs are failing**:
Cross build

**Reason for failure**:
Travis use 16.04 as default OS, we used 14.04 as default before, and need to do some installation.

**Anything else we need to know**:

/cc @subpathdev @kadisi @chendave @sids-b

**Comment by chendave** [comment]
I am able to cross build on ubuntu16.04, 

```
# apt-get install gcc-arm-linux-gnueabi

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

# make cross_build
export GOARCH=arm \
        export GOOS="linux" \
        export GOARM=6 \
        export CGO_ENABLED=1 \
        export CC=arm-linux-gnueabi-gcc; \
        go build cmd/edgecore/edgecore.go

# ls -l edgecore
-rwxr-xr-x 1 root root 81520516 Oct  8 21:29 edgecore
```

@fisherxu  what do you mean by installation?

install "gcc-arm-linux-gnueabi" for travis?

**Comment by fisherxu** [comment]
> install "gcc-arm-linux-gnueabi" for travis?

@chendave  We have install  `gcc-arm-linux-gnueabi` for travis now, and if we change the OS to 16.04, it will have some cross build error in travis.

https://github.com/kubeedge/kubeedge/blob/master/.travis.yml#L5
dist: trusty   14.04
dist: xenial   16.04
