### ISSUE TITLE
CI available on arm

### ISSUE THREAD

**Issue by chendave** [kubeedge/kubeedge#1185]
**What would you like to be added/modified**:
CI support on arm platform

**Why is this needed**:
current travis CI only support on x86 platform, it would be great to support arm as well, so that we can find the potential issues to run/build kubeedge on arm

**Comment by chendave** [comment]
cc @fisherxu  @kevin-wangzefeng

**Comment by chendave** [comment]
https://travis-ci.com/chendave/kubeedge if you can access it.

cc @sids-b @subpathdev too.

**Comment by sids-b** [comment]
Great @chendave . We will be able to ensure ARM builds with this.

**Comment by kadisi** [comment]
great

**Comment by kevin-wangzefeng** [comment]
Cool, let's add arm testing to PR checkings, tentatively non-blocking and turn to required once we fix currently failing ones.
