### ISSUE TITLE
bluetooth-device-mapper-deployment container remain "creatingcontainer"

### ISSUE THREAD

**Issue by parkeunsoo** [kubeedge/kubeedge#1187]
**What happened**:
   bluetooth-device-mapper-deployment container remain "creatingcontainer"
**What you expected to happen**:
  bluetooth-device-mapper-deployment container remain "running"

I referenced [this](https://docs.kubeedge.io/en/latest/mappers/bluetooth_mapper.html) and tried the bluetooth mapper application deployment. But the pod state does not change in the creatingcontainer.

Can you help me?

`kubectl get pods -o name`
![image](https://user-images.githubusercontent.com/32799518/66637801-bc2a3e00-ec4e-11e9-952d-060f56c4fc5c.png)
`kubectl describe pod`
![image](https://user-images.githubusercontent.com/32799518/66637917-fa276200-ec4e-11e9-8074-7ca36bb5ab2f.png)
![image](https://user-images.githubusercontent.com/32799518/66637961-0e6b5f00-ec4f-11e9-898a-149569bde83f.png)
`kubectl logs <pod name>`
![image](https://user-images.githubusercontent.com/32799518/66637617-59d13d80-ec4e-11e9-818a-3536c4f9e058.png)
edgecore.log
![image](https://user-images.githubusercontent.com/32799518/66637740-956c0780-ec4e-11e9-9dc3-24343cb08025.png)
deployment.yaml
![image](https://user-images.githubusercontent.com/32799518/66638098-4d99b000-ec4f-11e9-8b80-0861b78041a0.png)

**Comment by parkeunsoo** [comment]
@fisherxu may be it has ens3
um.. I should try  changing ens3 to eth0
thanks :)

**Comment by sids-b** [comment]
@parkeunsoo , did changing the interface name solve the issue ?

**Comment by parkeunsoo** [comment]
@side-b I change but, it still remain creating container

**Comment by fisherxu** [comment]
@parkeunsoo  Are you free to help review the translation of Kubeegde's Korean documents? https://github.com/kubeedge/website/pull/68

**Comment by parkeunsoo** [comment]
@fisherxu Sure, Exactly what documents should be reviewed? And what should I focus on?

**Comment by fisherxu** [comment]
kubeedge/website#68 Just this PR, help check if some translation words are appropriate, you can see the deploy preview here.
![image](https://user-images.githubusercontent.com/28776356/78968767-fa3de700-7b37-11ea-9b4d-8fa9bb2e5fc6.png)

**Comment by parkeunsoo** [comment]
@fisherxu I've read it all and it seems to have been properly translated. :)

**Comment by fisherxu** [comment]
> @fisherxu I've read it all and it seems to have been properly translated. :) Whenever you need help later, ask me anytime.

Ok, thanks very much!! @parkeunsoo
