### ISSUE TITLE
compile cloudcore error

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1210]
**What happened**:

**What you expected to happen**:
```
cd  cloud
make

bash ../hack/verify-golang.sh
go detail version: go version go1.12.9 linux/amd64
go version: 1.12.9
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-10-18T03:24:49Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=52945c93c538a823c93f71bacfc8720c96d0dbb7 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.147+52945c93c538a8 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/cloudcore/cloudcore.go
# github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/common/io
pkg/cloudhub/common/io/hubio.go:37:39: cannot use d.(*"github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/model".Message) (type *"github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/model".Message) as type *"github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/vendor/github.com/kubeedge/beehive/pkg/core/model".Message in argument to io.Connection.ReadMessage
pkg/cloudhub/common/io/hubio.go:46:40: cannot use msg (type *"github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/model".Message) as type *"github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/vendor/github.com/kubeedge/beehive/pkg/core/model".Message in argument to io.Connection.WriteMessageAsync
make: *** [cloudcore] Error 2


```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

git commit:   52945c93c538a823c93f71bacfc8720c96d0dbb7

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by kadisi** [comment]
cc @kevin-wangzefeng @fisherxu

**Comment by kevin-wangzefeng** [comment]
This error only occur when you executed `hack/update-vendor.sh` and then set` GO11MODULE=off`.
Which doesn't seem to be a real world case.

**Comment by kevin-wangzefeng** [comment]
Fixes in https://github.com/kubeedge/kubeedge/pull/1211.
