### ISSUE TITLE
consider rename beehive context package name

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1214]
**What would you like to be added/modified**:

Now KubeEdge use `github.com/kubeedge/beehive/pkg/core/context` package to  pass messages in each module, I don't like the `context.Context` used in KubeEdge, but it is often confused with the [golang library context](https://golang.org/pkg/context/)  and makes the code less readable.

How about rename beehive context package name?

**Vote 1:**
change beehive package and struct name:
 
`context.Context` -> `mudulecontext.CoreContext`

**Vote 2:**
set alias for golang Context
```
import (
    gocontext 	"context" 
)
```

**Vote 3:**
set alias for  Context
```
import (
    bcontext 	"github.com/kubeedge/beehive/pkg/core/context" 
)
```

/cc @rohitsardesai83 @sids-b  @kevin-wangzefeng @subpathdev @chendave @fisherxu 
 @edisonxiang @sujithsimon22 @Baoqiang-Zhang @kexun

**Comment by kadisi** [comment]
Vote 1

**Comment by chendave** [comment]
I think the second options would be much simpler to address the concern you have.

**Comment by kevin-wangzefeng** [comment]
Either set alias for golang context or github.com/kubeedge/beehive/pkg/core/context is fine.

**Comment by sids-b** [comment]
I think Vote2 would solve the concern

**Comment by xiangxingyong** [comment]
Vote3 makes sense:)

**Comment by sujithsimon22** [comment]
Vote 3 looks better to me

**Comment by fisherxu** [comment]
> Vote3 makes sense:)

+1, Keep golang native `context`, set alias to the context in beehive and reduce misunderstanding. 
But `bcontext` seems not a good alias name, thoughts?

**Comment by sids-b** [comment]
> > Vote3 makes sense:)
> 
> +1, Keep golang native `context`, set alias to the context in beehive and reduce misunderstanding.
> But `bcontext` seems not a good alias name, thoughts?

Probably use `beehiveContext` ?

**Comment by sujithsimon22** [comment]
> > > Vote3 makes sense:)
> > 
> > 
> > +1, Keep golang native `context`, set alias to the context in beehive and reduce misunderstanding.
> > But `bcontext` seems not a good alias name, thoughts?
> 
> Probably use `beehiveContext` ? I am not quite good with names though.

+1

**Comment by fisherxu** [comment]
Now we have resolve it.
/close
