### ISSUE TITLE
suggest  put all the module name definitions under /common/constants/module.go

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1221]
**What would you like to be added/modified**:

now , The name and group name of each module is defined under its own package , but we often need to quote each other. Even a lot of local code  redefined the module name.

**Why is this needed**:

suggest  put all the module name definitions under  `/common/constants/module.go`。Use these constants in the code as long as you use module name and group.

**Comment by kadisi** [comment]
cc @kevin-wangzefeng @fisherxu @sids-b @chendave @edisonxiang

**Comment by sids-b** [comment]
+1... Thanks @kadisi

**Comment by sids-b** [comment]
/assign

I will do it along with my PR for auto-register
