### ISSUE TITLE
Info - k3s master and kubeedge-worker

### ISSUE THREAD

**Issue by Salvocll** [kubeedge/kubeedge#1226]
In the guide about the edge solution, the images show the communication between the kubeendge-worker node and the k3s master but the k8s master is used in the guide.

is it just a convention or is it possible to perform the same steps but using the k3s master and then connect to the nodes on which kubeedge-worker is installed?

During the kubecon it was said that given the use of the same API it would be possible to make them communicate.. is it possible or has not yet been implemented a solution?

Thanks in advance..

**Comment by subpathdev** [comment]
Yes you can use k3s as master as well. There are a few difference by checking resource definitions.

**Comment by fisherxu** [comment]
> Yes you can use k3s as master as well.

@Salvocll  Yes, we used the native K8s APIs, and K3s also sopport native K8s APIs.

**Comment by Salvocll** [comment]
@subpathdev @fisherxu, thanks you very much for the reply, I'll try to link them

**Comment by fisherxu** [comment]
@Salvocll Thanks for the testing, could you please share your results then? :-)

**Comment by Robinsir** [comment]
> @Salvocll Thanks for the testing, could you please share your results then? :-)
I've tried it. It works.
```
root@hecs-x-large-2-linux-20200330183426:~# kubectl get node
NAME                                  STATUS                     ROLES    AGE     VERSION
hecs-x-large-2-linux-20200330183426   Ready,SchedulingDisabled   master   4d3h    v1.17.4+k3s1
kubeedge-node2                        Ready                      edge     3h39m   v1.17.1-kubeedge-v1.2.1
kubeedge-node1                        Ready                      edge     5h3m    v1.17.1-kubeedge-v1.2.1
root@hecs-x-large-2-linux-20200330183426:~# 

```
When configuring cloudcore Notice the following,
```
vim /etc/kubeedge/config/edgecore.yaml
 kubeconfig: "/root/.kube/config" -> kubeconfig:"/etc/rancher/k3s/k3s.yaml"
```
Reference：https://docs.rancher.cn/k3s/configuration.html#_1-%E8%AE%BE%E7%BD%AEkubeconfig%E6%96%87%E4%BB%B6

Using k3s is probably the simplest Kubeedge deployment solution, and most people are barred from installing k8s.

**Comment by fisherxu** [comment]
> I've tried it. It works.

Thanks for the useful information! And I think this issue can be closed now :)

/close
