### ISSUE TITLE
kubeedge deploy always pending

### ISSUE THREAD

**Issue by wesley-fly** [kubeedge/kubeedge#1227]
**What happened**:
I have a k8s cluster, 2*master & 3*node, work fine, I want to add kubeedge to this k8s cluster, my network topology like:
k8scluster(VIP:192.168.51.9) ----- EdgeCloud(192.168.51.20) --- EdgeDevice(192.168.51.198)
I setup binary cloudcore at  EdgeCloud(192.168.51.20), edgecore at EdgeDevice(192.168.51.198)
at k8s use
[root@k8s-m1 nodes]# kubectl get node
NAME                      STATUS   ROLES       AGE   VERSION
edge-node-1           Ready    edge-node   87m   v1.15.3-kubeedge-v0.0.0-master+$Format:%h$
k8s-m1                    Ready    master      24h   v1.15.3
k8s-m2                    Ready    master      24h   v1.15.3
k8s-n1                    Ready    node        24h   v1.15.3
k8s-n2                    Ready    node        24h   v1.15.3
k8s-n3                    Ready    node        24h   v1.15.3
all seems ok
but when i kubectl create -f deploy-nginx-armv8.yaml
this pod alway pending
NAME                                    READY   STATUS    RESTARTS   AGE
pod/nginx-deployment-84c595c598-h8wnd   0/1     Pending   0          2s

describe it
[root@k8s-m1 nodes]# kubectl describe pod/nginx-deployment-84c595c598-h8wnd
Name:           nginx-deployment-84c595c598-h8wnd
Namespace:      default
Priority:       0
**Node:           edge-node-1/**
Labels:         app=nginx
                pod-template-hash=84c595c598
Annotations:    <none>
Status:         Pending
**IP:**             
Controlled By:  ReplicaSet/nginx-deployment-84c595c598
Containers:
  nginx:
    Image:        docker.io/arm64v8/nginx
    Port:         80/TCP
    Host Port:    80/TCP
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9wtp8 (ro)
Conditions:
  Type           Status
  PodScheduled   True 
Volumes:
  default-token-9wtp8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9wtp8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  name=edge-node
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  26s   default-scheduler  **Successfully assigned default/nginx-deployment-84c595c598-h8wnd to edge-node-1**

**What you expected to happen**:
the deployment will create, describe says that Successfully assigned default/nginx-deployment-84c595c598-h8wnd to edge-node-1
**How to reproduce it (as minimally and precisely as possible)**:
always in my env
**Anything else we need to know?**:
My k8s cluster's kube-proxy & calico cni use contrainer Daemonset to deploy, so edge side no cni, is this the reason? or I need to deploy cni on edge side?
And when I describe the pending pod, the Nodeand IP (Bold text show below) was none, how to deal with it?
**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
v1.1.0
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):centos7 x86_64 vm
- OS (e.g. `cat /etc/os-release`):centos7
- Kernel (e.g. `uname -a`):Linux k8s-e1 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): no
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):v1.1.0
- Hardware configuration (e.g. `lscpu`):aarch64 arm Cortex-A53
- OS (e.g. `cat /etc/os-release`):18.04.2 LTS (Bionic Beaver) ubuntu
- Kernel (e.g. `uname -a`):Linux edge-node-1 4.9.79 #4 SMP PREEMPT Fri Oct 25 11:23:33 CST 2019 aarch64 aarch64 aarch64 GNU/Linux
- Go version (e.g. `go version`): no
- Others:

**Comment by wesley-fly** [comment]
get a message {Header:{ID:0d397984-0c83-47d8-876a-6c25a1bf97a2 ParentID: Timestamp:1572085926966 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/edge-node-inspur-ucpe-1} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:642777088 scale:0} d:{Dec:<nil>} s:613Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:537919488 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-10-26 10:32:06.920487317 +0000 UTC m=+1796.225111271 LastTransitionTime:2019-10-26 10:32:06.920487317 +0000 UTC m=+1796.225111271 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.51.198} {Type:Hostname Address:edge-node-inspur-ucpe-1}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.9.79 OSImage:Ubuntu 18.04.3 LTS ContainerRuntimeVersion:remote://19.3.4 KubeletVersion:v1.15.3-kubeedge-v1.1.0-master KubeProxyVersion: OperatingSystem:linux Architecture:arm64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I1026 10:32:06.996673    3388 metaclient.go:117] send sync message default/nodestatus/edge-node-inspur-ucpe-1 successed and response: {{2d1eb85a-191e-4079-b0e4-4f1c56925689 0d397984-0c83-47d8-876a-6c25a1bf97a2 1572085926996 false} {edged meta response default/nodestatus/edge-node-1} OK}

**Comment by wesley-fly** [comment]
edgecore logs: alyways repeate
I1026 10:35:28.525755    3388 msg_processor.go:634] get a message {Header:{ID:fb4fb467-c84c-40b5-b6a2-8944d2294fa4 ParentID: Timestamp:1572086128515 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/edge-node-inspur-ucpe-1} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:642777088 scale:0} d:{Dec:<nil>} s:613Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:537919488 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-10-26 10:35:28.457547512 +0000 UTC m=+1997.762171466 LastTransitionTime:2019-10-26 10:35:28.457547512 +0000 UTC m=+1997.762171466 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.51.198} {Type:Hostname Address:edge-node-inspur-ucpe-1}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.9.79 OSImage:Ubuntu 18.04.3 LTS ContainerRuntimeVersion:remote://19.3.4 KubeletVersion:v1.15.3-kubeedge-v0.0.0-master+$Format:%h$ KubeProxyVersion: OperatingSystem:linux Architecture:arm64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I1026 10:35:28.546675    3388 metaclient.go:117] send sync message default/nodestatus/edge-node-inspur-ucpe-1 successed and response: {{5ab0bc1d-5d96-4969-be28-f4b571e6cf8c fb4fb467-c84c-40b5-b6a2-8944d2294fa4 1572086128546 false} {edged meta response default/nodestatus/edge-node-inspur-ucpe-1} OK}
I1026 10:35:28.569785    3388 controller.go:182] received msg from cloud-hub:{Header:{ID:856ab655-26d7-49b7-8e52-0093477e8371 ParentID:fb4fb467-c84c-40b5-b6a2-8944d2294fa4 Timestamp:1572086127433 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/edge-node-inspur-ucpe-1} Content:[79 75]}
2019-10-26 10:35:28.569 +00:00 WARN context/context_channel.go:157 bad anonName(fb4fb467-c84c-40b5-b6a2-8944d2294fa4), do nothing
I1026 10:35:29.330585    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:30.330899    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:31.331221    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:32.331552    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:33.331869    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:34.332180    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:35.332491    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:36.332814    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:37.333144    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:38.333465    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:38.595587    3388 edged_status.go:163] Sync VolumesInUse: []
I1026 10:35:38.605861    3388 msg_processor.go:634] get a message {Header:{ID:382b8e62-057c-472c-88a4-f431c2ffdf01 ParentID: Timestamp:1572086138595 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/edge-node-inspur-ucpe-1} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:642777088 scale:0} d:{Dec:<nil>} s:613Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:537919488 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-10-26 10:35:38.546942305 +0000 UTC m=+2007.851566300 LastTransitionTime:2019-10-26 10:35:38.546942305 +0000 UTC m=+2007.851566300 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.51.198} {Type:Hostname Address:edge-node-inspur-ucpe-1}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.9.79 OSImage:Ubuntu 18.04.3 LTS ContainerRuntimeVersion:remote://19.3.4 KubeletVersion:v1.15.3-kubeedge-v0.0.0-master+$Format:%h$ KubeProxyVersion: OperatingSystem:linux Architecture:arm64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I1026 10:35:38.626916    3388 metaclient.go:117] send sync message default/nodestatus/edge-node-inspur-ucpe-1 successed and response: {{0c70db5d-12f0-4a90-8431-8d5f140c473a 382b8e62-057c-472c-88a4-f431c2ffdf01 1572086138626 false} {edged meta response default/nodestatus/edge-node-inspur-ucpe-1} OK}
I1026 10:35:38.649709    3388 controller.go:182] received msg from cloud-hub:{Header:{ID:c2a5cc81-2311-4f9d-b9b0-9b57f6274ca7 ParentID:382b8e62-057c-472c-88a4-f431c2ffdf01 Timestamp:1572086137512 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/edge-node-inspur-ucpe-1} Content:[79 75]}
2019-10-26 10:35:38.649 +00:00 WARN context/context_channel.go:157 bad anonName(382b8e62-057c-472c-88a4-f431c2ffdf01), do nothing
I1026 10:35:39.333649    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:40.333993    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:41.334329    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:42.334741    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:43.335048    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:44.335327    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:45.335635    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:46.335959    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:47.336309    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:48.336640    3388 generic.go:81] GenericLifecycle: Relisting
I1026 10:35:48.674584    3388 edged_status.go:163] Sync VolumesInUse: []
I1026 10:35:48.684822    3388 msg_processor.go:634] get a message {Header:{ID:4936f4f7-02a2-4da4-a068-e38ca37f575b ParentID: Timestamp:1572086148674 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/edge-node-inspur-ucpe-1} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:642777088 scale:0} d:{Dec:<nil>} s:613Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:537919488 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-10-26 10:35:48.63002862 +0000 UTC m=+2017.934652574 LastTransitionTime:2019-10-26 10:35:48.63002862 +0000 UTC m=+2017.934652574 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.51.198} {Type:Hostname Address:edge-node-inspur-ucpe-1}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.9.79 OSImage:Ubuntu 18.04.3 LTS ContainerRuntimeVersion:remote://19.3.4 KubeletVersion:v1.15.3-kubeedge-v0.0.0-master+$Format:%h$ KubeProxyVersion: OperatingSystem:linux Architecture:arm64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I1026 10:35:48.705386    3388 metaclient.go:117] send sync message default/nodestatus/edge-node-inspur-ucpe-1 successed and response: {{54ed58c5-735d-456f-9ad1-27e73380656f 4936f4f7-02a2-4da4-a068-e38ca37f575b 1572086148705 false} {edged meta response default/nodestatus/edge-node-inspur-ucpe-1} OK}
I1026 10:35:48.728821    3388 controller.go:182] received msg from cloud-hub:{Header:{ID:7d10454b-7324-4971-8b07-823bf0e4ed92 ParentID:4936f4f7-02a2-4da4-a068-e38ca37f575b Timestamp:1572086147591 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/edge-node-inspur-ucpe-1} Content:[79 75]}
2019-10-26 10:35:48.728 +00:00 WARN context/context_channel.go:157 bad anonName(4936f4f7-02a2-4da4-a068-e38ca37f575b), do nothing

**Comment by fisherxu** [comment]
> but when i kubectl create -f deploy-nginx-armv8.yaml

You deploy the app to arm platform, and have you specified arm docker images(app and pause docker images)?
