### ISSUE TITLE
Does kubeedge support pv and pvc?

### ISSUE THREAD

**Issue by qiuhui** [kubeedge/kubeedge#1236]
I can not see any description about pv and pvc in kubeedge docs, anyone know about this?

**Comment by SemiLavender** [comment]
Don't support volumes of pv and pvc. I tried to use the Prometheus at the KubeEdge, which component no work

**Comment by fisherxu** [comment]
@qiuhui @SemiLavender We have a [csi support doc](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/csi.md) here,  please take a look :)

**Comment by larryck** [comment]
Support emptydir/hostpath/csi.
