### ISSUE TITLE
the pod on the edge side of kubeedge can not be managed by k8s clusters.

### ISSUE THREAD

**Issue by freekingdoms** [kubeedge/kubeedge#1239]
**What happened**:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/15769322/67939495-a6d08000-fc0c-11e9-9469-0dbd33228930.png">

i deployment a nginx service and it run well.
(please ignore knative,,I haven't deployed anything with knative yet.)
<img width="914" alt="image" src="https://user-images.githubusercontent.com/15769322/67939464-90c2bf80-fc0c-11e9-9689-74361b83d770.png">

the svc detail of ngix-service 
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/15769322/67939648-f747dd80-fc0c-11e9-8f55-3e56f9250aa4.png">

use the node1,node2 pod ip access service，is well
<img width="558" alt="image" src="https://user-images.githubusercontent.com/15769322/67939697-13e41580-fc0d-11e9-994c-b390b864a7c1.png">

use the edge cluster ip  ,is error (172.17.0.2 is the Endpoints in nginx-service svc )
<img width="453" alt="image" src="https://user-images.githubusercontent.com/15769322/67929107-81854700-fbf7-11e9-8c92-d9b61bad8ae4.png">

I can use this method to access the services deployed on the edge
the 192.168.0.18 is edge-node1 ip
<img width="597" alt="image" src="https://user-images.githubusercontent.com/15769322/67940052-d59b2600-fc0d-11e9-830a-451e53c1decd.png">

nginx.yaml
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12
        ports:
        - containerPort: 80
          hostPort: 80
```

nginx-service.yaml
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port:   32000
      targetPort: 80
```
**What you expected to happen**:
I  think the pod on the edge side of kubeedge can not be managed by k8s clusters.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
i found some warning in log ,I don't know if this has any effect tokubeedge.

> Warning MissingClusterDNS kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.

``` log

I1031 07:29:53.115653    1969 container_manager_linux.go:868] Found 147 PIDs in root, 147 of them are not to be moved
I1031 07:29:53.886652    1969 generic.go:81] GenericLifecycle: Relisting
I1031 07:29:54.900586    1969 generic.go:81] GenericLifecycle: Relisting
I1031 07:29:55.946557    1969 generic.go:81] GenericLifecycle: Relisting
I1031 07:29:56.960907    1969 generic.go:81] GenericLifecycle: Relisting
I1031 07:29:57.982146    1969 generic.go:81] GenericLifecycle: Relisting
I1031 07:29:58.011600    1969 edged_status.go:163] Sync VolumesInUse: []
I1031 07:29:58.022169    1969 msg_processor.go:634] get a message {Header:{ID:9b52b17c-c8ed-4c55-8038-36c4c51d9b04 ParentID: Timestamp:1572506998011 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/edge-node1} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:2065694720 scale:0} d:{Dec:<nil>} s:1970Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:1960837120 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-10-31 07:29:58.010188875 +0000 UTC m=+1745.490652159 LastTransitionTime:2019-10-31 07:29:58.010188875 +0000 UTC m=+1745.490652159 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.0.18} {Type:Hostname Address:u-edge1}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.15.0-66-generic OSImage:Ubuntu 18.04.3 LTS ContainerRuntimeVersion:remote://18.9.7 KubeletVersion:v1.15.3-kubeedge-v1.1.0-beta.0.176+4a75b7c2e1794e KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I1031 07:29:58.033263    1969 metaclient.go:117] send sync message default/nodestatus/edge-node1 successed and response: {{c35b3f0e-455b-439c-98b8-8a65836c7275 9b52b17c-c8ed-4c55-8038-36c4c51d9b04 1572506998033 false} {edged meta response default/nodestatus/edge-node1} OK}
I1031 07:29:58.041076    1969 controller.go:181] received msg from cloud-hub:{Header:{ID:25c3728a-c7a9-4cfb-935b-489a0c54ae6e ParentID:9b52b17c-c8ed-4c55-8038-36c4c51d9b04 Timestamp:1572506998035 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/edge-node1} Content:OK}
W1031 07:29:58.041131    1969 context_channel.go:158] Get bad anonName:9b52b17c-c8ed-4c55-8038-36c4c51d9b04 when sendresp message, do nothing
I1031 07:29:58.997533    1969 generic.go:81] GenericLifecycle: Relisting
I1031 07:30:00.017058    1969 generic.go:81] GenericLifecycle: Relisting
I1031 07:30:00.850446    1969 edged.go:775] worker [4] get pod addition item [nginx-deployment-7445b6c6f9-nkzt7]
I1031 07:30:00.850496    1969 edged.go:844] start to consume added pod [nginx-deployment-7445b6c6f9-nkzt7]
I1031 07:30:00.850656    1969 record.go:24] Warning MissingClusterDNS kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
I1031 07:30:00.850685    1969 record.go:24] Warning MissingClusterDNS pod: "nginx-deployment-7445b6c6f9-nkzt7_default(02bcb756-3e39-49f6-8130-4e0ce9641364)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
I1031 07:30:00.850734    1969 edged.go:886] consume added pod [nginx-deployment-7445b6c6f9-nkzt7] successfully
I1031 07:30:01.031326    1969 edged_volumes.go:54] Using volume plugin "kubernetes.io/empty-dir" to mount wrapped_default-token-kjfnt
I1031 07:30:01.033744    1969 generic.go:81] GenericLifecycle: Relisting

```

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
```
KubeEdge v1.1.0-beta.0.176+4a75b7c2e1794e
```

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               94
Model name:          Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
Stepping:            3
CPU MHz:             2591.998
BogoMIPS:            5183.99
Hypervisor vendor:   VMware
```
- OS (e.g. `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
```
- Kernel (e.g. `uname -a`):
```
Linux u-master 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Go version (e.g. `go version`): 
```
go version go1.12.9 linux/amd64
```
- Others:
```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```
**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
```
KubeEdge v1.1.0-beta.0.176+4a75b7c2e1794e
```
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by dwSun** [comment]
means that kubeedge only works as a container startup manager, not a part of k8s cluster?

**Comment by dwSun** [comment]
@fisherxu 
will you fix this at v1.2?
in your *KubeEdge Community Sync Meeting Notes*, I saw this:
>Support ingress at edge.
>Support managing clusters at edge from cloud (aka. EdgeSite)

**Comment by fisherxu** [comment]
@freekingdoms Edged in edgecore is a mini-kubelet which cut from kubelet, and kubeedge edgenode is part of k8s cluster. Your issue here is that you can't access the edge svc from cloud, which not means `the pod on the edge side of kubeedge can not be managed by k8s clusters.`, if not   managed by k8s clusters, we can't deploy and delete pod from cloud side.
And the edgemesh in kubeedge, we support service comunication from edge to edge, PTAL :)

@dwSun Yes, this is within out plan, and do you have a usage scenario about the `ingress at edge` and `managing clusters at edge from cloud`? Since we only managing  edge node now.

**Comment by fisherxu** [comment]
@freekingdoms  If you want to access the service in edge from cloudside, you need install the CNI plugin to edge same as in cloudside, this's not bug for kubeedge :)

**Comment by dwSun** [comment]
@fisherxu we are working on a project which will use Knative to deploy and auto-scale some services.
The problem right now is we can't use Knative to manage network traffic of pods on edge.
All our effort of trying to install CNI plugins are failed.
Is there anything special we should pay attention to when install cni plugins?
