### ISSUE TITLE
Edge node is NotReady

### ISSUE THREAD

**Issue by cwhuang29** [kubeedge/kubeedge#1243]
**What happened**: I installed KubeEdge by "Setup KubeEdge from sourcecode", but the edge side is always notReady
node status: 
```
NAME        STATUS     ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
apollo54    Ready      master   57m   v1.16.2   10.66.66.54   <none>        Ubuntu 18.04.3 LTS   4.15.0-55-generic   docker://18.6.0
edge-node   NotReady   edge     51m             <none>        <none>        <unknown>            <unknown>           <unknown>
```

**What you expected to happen**: Edge node be Ready.

**How to reproduce it (as minimally and precisely as possible)**: I follow the webpage https://docs.kubeedge.io/en/latest/setup/setup.html to install it. And k8s cluster had installed previously by following the webpage https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Anything else we need to know?**: Some error messages occur while running ./cloudcore, but the message from ./edgecore seems pretty well.

Error message:
```
E1103 18:07:23.666387   26610 channelq.go:99] rChannel for edge node edge-node is removed
I1103 18:07:23.666394   26610 channelq.go:89] fail to get dispatch channel for edge-node
...
I1103 18:07:27.178529   26610 upstream.go:186] dispatch message: f8e6589d-d0a5-4762-b5bc-b800c6334b94
W1103 18:07:27.178546   26610 upstream.go:190] parse message: f8e6589d-d0a5-4762-b5bc-b800c6334b94 resource type with error: resource type not found
```
Details are shown by screenshots below:
![cloud side](https://user-images.githubusercontent.com/49531255/68088899-9800fc00-fe9e-11e9-8a74-4e7ee5095338.png)
![edge side](https://user-images.githubusercontent.com/49531255/68088901-9a635600-fe9e-11e9-8a08-cef2c57c8a00.png)
![edge side 02](https://user-images.githubusercontent.com/49531255/68088978-49079680-fe9f-11e9-92aa-9353af25616f.png)

kubectl describe node edge-node:
```
Name:               edge-node
Roles:              edge
Labels:             name=edge-node
                    node-role.kubernetes.io/edge=
Annotations:        kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"v1","kind":"Node","metadata":{"annotations":{},"labels":{"name":"edge-node","node-role.kubernetes.io/edge":""},"name":"edge...
                    node.alpha.kubernetes.io/ttl: 0
CreationTimestamp:  Sun, 03 Nov 2019 16:09:59 +0000
Taints:             node.kubernetes.io/unreachable:NoExecute
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                   Message
  ----             ------    -----------------                 ------------------                ------                   -------
  Ready            Unknown   Sun, 03 Nov 2019 16:09:59 +0000   Sun, 03 Nov 2019 16:11:01 +0000   NodeStatusNeverUpdated   Kubelet never posted node status.
  MemoryPressure   Unknown   Sun, 03 Nov 2019 16:09:59 +0000   Sun, 03 Nov 2019 16:11:01 +0000   NodeStatusNeverUpdated   Kubelet never posted node status.
  DiskPressure     Unknown   Sun, 03 Nov 2019 16:09:59 +0000   Sun, 03 Nov 2019 16:11:01 +0000   NodeStatusNeverUpdated   Kubelet never posted node status.
  PIDPressure      Unknown   Sun, 03 Nov 2019 16:09:59 +0000   Sun, 03 Nov 2019 16:11:01 +0000   NodeStatusNeverUpdated   Kubelet never posted node status.
Addresses:
System Info:
 Machine ID:
 System UUID:
 Boot ID:
 Kernel Version:
 OS Image:
 Operating System:
 Architecture:
 Container Runtime Version:
 Kubelet Version:
 Kube-Proxy Version:
PodCIDR:                     10.244.1.0/24
PodCIDRs:                    10.244.1.0/24
Non-terminated Pods:         (0 in total)
  Namespace                  Name    CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----    ------------  ----------  ---------------  -------------  ---
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
Events:              <none>
```

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
- Kernel (e.g. `uname -a`): Linux apollo54 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): go version go1.12.7 linux/amd64

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
- Kernel (e.g. `uname -a`): Linux apollo63 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): go version go1.12.7 linux/amd64

**Comment by cwhuang29** [comment]
I've solved this problem by replacing `Cgroup Driver: systemd` with `cgroupfs`

**Comment by cwhuang29** [comment]
I've solved this problem by replacing Cgroup Driver: systemd with cgroupfs

**Comment by fisherxu** [comment]
Have the `Edge node is NotReady` been resolved now or have some other issues? @cwhuang29

**Comment by cwhuang29** [comment]
> Have the `Edge node is NotReady` been resolved now or have some other issues? @cwhuang29

I've solved it

**Comment by fisherxu** [comment]
Ok, let's close first :) If have any other issue, can reopen.

**Comment by jedyang** [comment]
I had the same problem，tks for your solution @cwhuang29 
I solved this by change the value of _edged.cgroup-driver_ to _systemd_ in edge.yaml
it workrd
```
kubectl get nodes
NAME        STATUS   ROLES    AGE    VERSION
edge-node   Ready    edge     149m   v1.15.3-kubeedge-v1.1.0-beta.0.261+ad24878db583d4
xxxx-01   Ready    master   4d2h   v1.16.3
xxxx-02   Ready    <none>   3h4m   v1.16.3

```
