### ISSUE TITLE
keadm init error, cp: -r not specified

### ISSUE THREAD

**Issue by bitosky** [kubeedge/kubeedge#1245]
**What happened**:
Use command like this:
~~~
./keadm init \
	--docker-version=19.03.4 \
	--kubernetes-version=1.16.1 \
	--kubeedge-version=1.1.0 \
	--kube-config=~/.kube/config \
	--pod-network-cidr=10.244.0.0/16 \
	--image-repository=gcr.azk8s.cn/google_containers \
~~~
Get error like this:
~~~
...
Kubeadm init successfully executed
cp: -r not specified; omitting directory '/etc/kubeedge//kubeedge/cloud/cloudcore'
in error
Error: 
...
~~~

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version 1.1.0:  

**CloudSide Environment**:
Nothing

**EdgeSide Environment**:
Nothing

**Comment by ludfun** [comment]
Same issue, did you solve it?

**Comment by bitosky** [comment]
@ludfun 

'/etc/kubeedge//kubeedge/cloud/cloudcore' should be a binary file, but it is a folder.

So I change '/etc/kubeedge//kubeedge/cloud/cloudcore'  into '/etc/kubeedge//kubeedge/cloud/cloudcore/cloudcore'.

But I failed in the end. There are some other BUGs.

Finally, I use source code installation instead.

**Comment by fisherxu** [comment]
Please try latest verion of keadm v1.2.1 :)
/close
