### ISSUE TITLE
support  service envs 

### ISSUE THREAD

**Issue by hhstu** [kubeedge/kubeedge#1254]
**What happened**:
dont have envs with kube-dns-service ,it case flannel can not start

**Comment by fisherxu** [comment]
> dont have envs with kube-dns-service ,it case flannel can not start

@hhstu You means don't have envs about service in pod?

**Comment by hhstu** [comment]
yes，i use continued。 so that  the pods  shoud  range to  apiserver just like flannel、node-exporter....

**Comment by fisherxu** [comment]
> yes，i use continued。 so that the pods shoud range to apiserver just like flannel、node-exporter can not start

Oh, If the problem has been solved, welcome raise PR to community :)
