### ISSUE TITLE
Add support charts for k8s versions of different kubeedge versions

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1255]
**What would you like to be added/modified**:
Like https://github.com/fabric8io/kubernetes-client#compatibility-matrix, add support charts for k8s versions of different kubeedge versions.

**Why is this needed**:
Make K8s version dependencies more clearer.

**Comment by kadisi** [comment]
that sounds good

**Comment by fisherxu** [comment]
Has been resolved.  https://github.com/kubeedge/kubeedge#compatibility-matrix
