### ISSUE TITLE
device event for sensor readings

### ISSUE THREAD

**Issue by xiedidan** [kubeedge/kubeedge#1256]
**What would you like to be added/modified**:
According to [device-crd#device-events](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/device-crd.md#device-events), it looks like sensor readings could NOT be watched as device events. So the readings could only be polled. So is there a way to watch these readings from k8s master/api/client?  

**Why is this needed**:
To collect sensor readings in event-driven manner, rather than polling... this saves resources and reduces collector delay.

**Comment by fisherxu** [comment]
I think the device event will be sent to MQTT broker, then send to cloud through device api(devicetwin), we can watch the device state in cloud, thoughts? @xiedidan

**Comment by xiedidan** [comment]
@fisherxu that's right, we could watch device events in the cloud...
