### ISSUE TITLE
KubeEdge install failed - "make" command won't work

### ISSUE THREAD

**Issue by BeneaAlinAndrei** [kubeedge/kubeedge#1257]
I tried to install the edge side of KubeEdge, when i run the `make` command from this part in the tutorial
`cd $GOPATH/src/github.com/kubeedge/kubeedge/edgesite
make`   i receive the message: 

`bash ../hack/verify-golang.sh
../hack/verify-golang.sh: line 26: go: command not found
go detail version: 
../hack/verify-golang.sh: line 28: go: command not found
Makefile:9: recipe for target 'verify' failed
make: *** [verify] Error 127
`
Does anyone know how i can get past this error? Thank you!

**Comment by kadisi** [comment]
you should install go package （version >1.12) 
https://golang.org/dl/

**Comment by BeneaAlinAndrei** [comment]
> you should install go package （version >1.12)
> https://golang.org/dl/

Thank you, now the command works!

**Comment by BeneaAlinAndrei** [comment]
> you should install go package （version >1.12)
> https://golang.org/dl/

P.s. After i run it again it gives me yet another error:  
`go: k8s.io/apimachinery@v0.0.0-20190612165923-1799e75a0719: invalid pseudo-version: does not match version-control timestamp (2019-06-12T20:58:21Z)
Makefile:5: recipe for target 'edge_site' failed
make: *** [edge_site] Error 1
(base) ifdstudent@kmaster:/s`

**Comment by kadisi** [comment]
export  GO111MODULE=of f

**Comment by BeneaAlinAndrei** [comment]
> export GO111MODULE=of f

Nope, dose not work.

`go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-11-12T12:43:10Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=33b972ae0589c55a3b695b4b8dad135e7ef76bfa -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.192+33b972ae0589c5 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/edgesite.go
cmd/edgesite.go:8:2: cannot find package "github.com/kubeedge/kubeedge/edgesite/cmd/app" in any of:
	/usr/lib/go-1.13/src/github.com/kubeedge/kubeedge/edgesite/cmd/app (from $GOROOT)
	/home/ifdstudent/go/src/github.com/kubeedge/kubeedge/edgesite/cmd/app (from $GOPATH)
cmd/edgesite.go:6:2: cannot find package "k8s.io/component-base/logs" in any of:
	/usr/lib/go-1.13/src/k8s.io/component-base/logs (from $GOROOT)
	/home/ifdstudent/go/src/k8s.io/component-base/logs (from $GOPATH)
Makefile:5: recipe for target 'edge_site' failed
make: *** [edge_site] Error 1
`
