### ISSUE TITLE
go: k8s.io/apimachinery@v0.0.0-20190612165923-1799e75a0719: invalid pseudo-version: does not match version-control timestamp (2019-06-12T20:58:21Z)

### ISSUE THREAD

**Issue by Ssx5** [kubeedge/kubeedge#1263]
`cd cloud && make
make[1]: Entering directory '/home/song12300560/gopath/src/github.com/kubeedge/kubeedge/cloud'
bash ../hack/verify-golang.sh
go detail version: go version go1.13.1 linux/amd64
go version: 1.13.1
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-11-14T16:44:27Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=19180d74ccb85ce900a06d09456d0d5fc25ebc5b -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.205+19180d74ccb85c -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/cloudcore/cloudcore.go
go: k8s.io/apimachinery@v0.0.0-20190612165923-1799e75a0719: invalid pseudo-version: does not match version-control timestamp (2019-06-12T20:58:21Z)
Makefile:11: recipe for target 'cloudcore' failed
make[1]: *** [cloudcore] Error 1
make[1]: Leaving directory '/home/song12300560/gopath/src/github.com/kubeedge/kubeedge/cloud'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2
`
GO111MODULE=on

**Comment by cwl233** [comment]
maybe you can use go version 1.12, and try again

**Comment by fisherxu** [comment]
> maybe you can use go version 1.12, and try again

Yes, you can use go version 1.12 and set GO111MODULE=off. @Ssx5

**Comment by Ssx5** [comment]
I use go v1.12 and set GO111MODULE=on, run success.
so the problem is go v1.13
Thanks
