### ISSUE TITLE
k8s pod network flannel deployed failed on Raspberry Pi

### ISSUE THREAD

**Issue by zhh2005757** [kubeedge/kubeedge#1268]
One of my edge node is running on a Raspberry Pi 3B+, and I have changed the kube-flannel.yml to adapt the structure of arm, but it still started failed on the edge, the edge node is always in NotReady.Then I ran the commmand "kubectl describe pod kube-flannel-ds-arm-fwnrc -n kube-system" to check out the failed started pod it shows the following:

Warning  Failed          <invalid>                      kubelet, node-1    Error: failed to start container "install-cni": Error response from daemon: cannot join network of a non running container: 7b7c119b319c81bb88e2c04fd0e58b70e7f04071b843ca9e2d6ca023cdf87e41

**Comment by kadisi** [comment]
@zhh2005757 can you show your edge.yaml ?

**Comment by zhh2005757** [comment]
.: /usr/bin/make
_: /usr/bin/make
GOARCHAIUS.CONFIG.PATH: /root/GoProj/src/github.com/kubeedge/kubeedge/edge
GOARCHAIUS_CONFIG_PATH: /root/GoProj/src/github.com/kubeedge/kubeedge/edge
GOPATH: /root/GoProj
GOPROXY: https://goproxy.io
GOROOT: /usr/local/go
HOME: /root
KUBECONFIG: /etc/kubernetes/admin.conf
LANG: zh_CN.UTF-8
LANGUAGE: zh_CN:zh
LOGNAME: root
MAIL: /var/mail/root
MAKE.TERMERR: /dev/pts/1
MAKE.TERMOUT: /dev/pts/1
MAKE_TERMERR: /dev/pts/1
MAKE_TERMOUT: /dev/pts/1
MAKEFLAGS: w
MAKELEVEL: "2"
MFLAGS: -w
OLDPWD: /root/GoProj/src/github.com/kubeedge/kubeedge
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin://root/GoProj/bin:/usr/local/go/bin://root/GoProj/bin:/usr/local/go/bin://root/GoProj/bin:/usr/local/go/bin://root/GoProj/bin
PWD: /root/GoProj/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/config
QT.QPA.PLATFORMTHEME: appmenu-qt5
QT_QPA_PLATFORMTHEME: appmenu-qt5
SHELL: /bin/bash
SHLVL: "1"
SSH.CLIENT: 192.168.137.1 59407 22
SSH.CONNECTION: 192.168.137.1 59407 192.168.137.21 22
SSH.TTY: /dev/pts/1
SSH_CLIENT: 192.168.137.1 59407 22
SSH_CONNECTION: 192.168.137.1 59407 192.168.137.21 22
SSH_TTY: /dev/pts/1
TERM: xterm
USER: root
XDG.DATA.DIRS: /usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG.RUNTIME.DIR: /run/user/0
XDG.SESSION.ID: "2"
XDG_DATA_DIRS: /usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_RUNTIME_DIR: /run/user/0
XDG_SESSION_ID: "2"
edged.cgroup-driver: cgroupfs
edged.cluster-dns: ""
edged.cluster-domain: ""
edged.device-plugin-enabled: false
edged.docker-address: unix:///var/run/docker.sock
edged.edged-memory-capacity-bytes: 7852396000
edged.gpu-plugin-enabled: false
edged.hostname-override: node-1
edged.image-gc-high-threshold: 80
edged.image-gc-low-threshold: 40
edged.image-pull-progress-deadline: 60
edged.interface-name: eth0
edged.maximum-dead-containers-per-container: 1
edged.node-ip: ""
edged.node-status-update-frequency: 10
edged.podsandbox-image: kubeedge/pause-arm:3.1
edged.register-node-namespace: default
edged.remote-image-endpoint: unix:///var/run/dockershim.sock
edged.remote-runtime-endpoint: unix:///var/run/dockershim.sock
edged.runtime-request-timeout: 2
edged.runtime-type: docker
edgehub.controller.heartbeat: 15
edgehub.controller.node-id: node-1
edgehub.controller.project-id: e632aba927ea4ac2b575ec1603d56f10
edgehub.controller.protocol: websocket
edgehub.quic.cafile: /etc/kubeedge/ca/rootCA.crt
edgehub.quic.certfile: /etc/kubeedge/certs/edge.crt
edgehub.quic.handshake-timeout: 30
edgehub.quic.keyfile: /etc/kubeedge/certs/edge.key
edgehub.quic.read-deadline: 15
edgehub.quic.url: 127.0.0.1:10001.
edgehub.quic.write-deadline: 15
edgehub.websocket.certfile: /etc/kubeedge/certs/edge.crt
edgehub.websocket.handshake-timeout: 30
edgehub.websocket.keyfile: /etc/kubeedge/certs/edge.key
edgehub.websocket.read-deadline: 15
edgehub.websocket.url: wss://192.168.137.21:10000/e632aba927ea4ac2b575ec1603d56f10/node-1/events
edgehub.websocket.write-deadline: 15
mesh.loadbalance.strategy-name: RoundRobin
modules.enabled:
- eventbus
- servicebus
- websocket
- metaManager
- edged
- twin
- dbTest
- edgemesh
mqtt.internal-server: tcp://127.0.0.1:1884
mqtt.mode: 1
mqtt.qos: 0
mqtt.retain: false
mqtt.server: tcp://127.0.0.1:1883
mqtt.session-queue-size: 100

Thanks a lot !

**Comment by zhh2005757** [comment]
And I found kube-proxy of edge node was always CrashLoopBackOff, I ran kubeclt describe kube-proxy-r9lqm and it showed the following:
Name:                 kube-proxy-r9lqm
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 node-1/192.168.137.245
Start Time:           Wed, 20 Nov 2019 22:05:49 +0800
Labels:               controller-revision-hash=6dcc9f
                      k8s-app=kube-proxy
                      pod-template-generation=1
Annotations:          <none>
Status:               Running
IP:                   192.168.137.245
IPs:                  <none>
Controlled By:        DaemonSet/kube-proxy
Containers:
  kube-proxy:
    Container ID:  docker://1eaa2294cf793612e98eaf3b2f09f997dd0c63d0f86d2725a51398721a291e5f
    Image:         registry.aliyuncs.com/google_containers/kube-proxy:v1.15.0
    Image ID:      docker-pullable://registry.aliyuncs.com/google_containers/kube-proxy@sha256:7b94921f1c64876d3663698ade724fce79b417b32f0e1053976ca68a18fc0cba
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/kube-proxy
      --config=/var/lib/kube-proxy/config.conf
      --hostname-override=$(NODE_NAME)
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      cannot join network of a non running container: 42df5603fbac1c52afed148ee919d4e5c826b7743c4368b2ec694afaba506830
      Exit Code:    128
      Started:      Wed, 20 Nov 2019 22:08:56 +0800
      Finished:     Wed, 20 Nov 2019 22:08:56 +0800
    Ready:          False
    Restart Count:  5
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-proxy-token-j4c47 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  kube-proxy-token-j4c47:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-proxy-token-j4c47
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason          Age                            From               Message
  ----     ------          ----                           ----               -------
  Normal   Scheduled       4m44s                          default-scheduler  Successfully assigned kube-system/kube-proxy-r9lqm to node-1
  Warning  Failed          <invalid>                      kubelet, node-1    Error: failed to start container "kube-proxy": Error response from daemon: cannot join network of a non running container: 4514136fa0d26d9194581eea3db77fb7037c15535254144226c5fd624b39e504
  Warning  Failed          <invalid>                      kubelet, node-1    Error: failed to start container "kube-proxy": Error response from daemon: cannot join network of a non running container: f2753b9e1982c1b5f4eb6e75b6c03462d650acbcbb3fc9c3bdf12152cc3b1a95
  Warning  Failed          <invalid>                      kubelet, node-1    Error: failed to start container "kube-proxy": Error response from daemon: cannot join network of a non running container: 10dc7c83e67a07df319448e2023b0c78fc4a5b541b6f563e57da7c6389f4431e
  Warning  BackOff         <invalid> (x7 over <invalid>)  kubelet, node-1    Back-off restarting failed container
  Normal   Created         <invalid> (x4 over <invalid>)  kubelet, node-1    Created container kube-proxy
  Normal   Pulled          <invalid> (x4 over <invalid>)  kubelet, node-1    Container image "registry.aliyuncs.com/google_containers/kube-proxy:v1.15.0" already present on machine
  Warning  Failed          <invalid>                      kubelet, node-1    Error: failed to start container "kube-proxy": Error response from daemon: cannot join network of a non running container: 865d9dcb81d6121b8f5775117e18c1abc96b9cec4f5182b38b40057b5644cbc7
  Normal   SandboxChanged  <invalid> (x6 over <invalid>)  kubelet, node-1    Pod sandbox changed, it will be killed and re-created.
