### ISSUE TITLE
No where to find the configmap

### ISSUE THREAD

**Issue by zhh2005757** [kubeedge/kubeedge#1279]
I wanna try to deploy a led-control application on the Raspberry Pi board, and I referred this guide [https://github.com/kubeedge/examples/tree/master/led-raspberrypi](url)
But when I ran the command "kubectl apply -f deployment.yaml, the pod maintained the status "ContainerCreating", and I describe the pod it said like the following:
**Warning  FailedMount  <invalid> (x6 over <invalid>)  kubelet, node-1    MountVolume.SetUp failed for volume "config-volume" : configmap "device-profile-config-node-1" not found**
I wanna know the configmap will be created by deploying the devices or manually, I didn't create configmap before, thanks!

**Comment by Sellto** [comment]
I have exactly the same issues....

**Comment by fisherxu** [comment]
@zhh2005757  @Sellto  Sorry for the dely, now in kubeedge when we create the device CRD(`device model/deviceinstance and in the device CRD there will be some configuration about the device which connected to the edgenode`), the devicecontroller will create a configmap, so when you deploy the app to edgenode, which will access the device, so it need read device configuration from configmap.

I guess you haven't created the device CRD?

**Comment by zhh2005757** [comment]
I have created the device CRD, but it still didn't work. Where should I go to check whether the configmap was created?

**Comment by fisherxu** [comment]
You can use `kubectl get cm -n NAMESPACE` to check the configmap :)

**Comment by zhh2005757** [comment]
I tried it but there still was not the configMap.
NAMESPACE     NAME                                 DATA   AGE
kube-public   cluster-info                         3      20h
kube-system   coredns                              1      20h
kube-system   extension-apiserver-authentication   6      20h
kube-system   kube-flannel-cfg                     2      10h
kube-system   kube-proxy                           2      20h
kube-system   kubeadm-config                       2      20h
kube-system   kubelet-config-1.15                  1      20h

And the following is my yaml file of the  deviceModel and device-instance

apiVersion: devices.kubeedge.io/v1alpha1
kind: DeviceModel
metadata:
 name: led-light
 namespace: default
spec:
 properties:
  - name: power-status
    description: Indicates whether the led light is ON/OFF
    type:
      string:
        accessMode: ReadWrite
        defaultValue: 'OFF'
  - name: gpio-pin-number
    description: Indicates whether the GPIO pin to which LED is connected
    type:
      int:
        accessMode: ReadOnly
        defaultValue: 18

``````````````````````````````````````````````````````````````````````

apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
  name: led-light-instance-01
  labels:
    description: LEDLight
    model: led-light
spec:
  deviceModelRef:
    name: led-light
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - node-1          #pls give your edge node name
status:
  twins:
    - propertyName: power-status
      desired:
        metadata:
          type: string
        value: 'OFF'

**Comment by luogangyi** [comment]
The configmap used by mapper is named(hard coded) as  _device-profile-config-<edge_node_name>_, you have to add configutaion like below in your mapper spec
`
    spec:
      containers:
      - name: xxx
        image: xxxx
        volumeMounts:
        - name: xxx-config-volume
          mountPath: xxxx   
      volumes:
      - name: xxx-config-volume
        configMap:
          name:  device-profile-config-<edge_node_name>
`
