### ISSUE TITLE
image gc manager remove image when process path disk usage rate reach high threshold percent

### ISSUE THREAD

**Issue by Baoqiang-Zhang** [kubeedge/kubeedge#1283]
**What happened**:image gc manager remove image when process path but not image path disk usage rate reach high threshold percent 

**What you expected to happen**: remove image when image path disk usage rate reach high threshold percent 

**How to reproduce it (as minimally and precisely as possible)**:   
1. create a vm ;  
2. mount a disk to /opt  
3. run edge_core in /opt   
4. use tool dd to full /opt disk  
5. image in /var/lib/docker will be removed  

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by Baoqiang-Zhang** [comment]
https://github.com/kubeedge/kubeedge/blob/66d2f3a194c633109bcfa799ae425972c6243486/edge/pkg/edged/images/image_gc_manager.go#L35

**Comment by daixiang0** [comment]
We can easily count the image disk usage while It is hard to count the total disk size, now we use `/`.
For docker, we can use `docker system df` to get usage, other CRIs may have similiar command i think.

In fact, it maybe more useful when you use a disk to store image rather than root disk.
WDYT @fisherxu ?
