### ISSUE TITLE
pod is pending

### ISSUE THREAD

**Issue by w-huaqiang** [kubeedge/kubeedge#1287]
version: kubeedge-v1.1.0-linux-amd64.tar

**### cloudcore:**
**[root@ansible-server cloudcore]# kubectl get pod -o wide**
NAME                                READY   STATUS    RESTARTS   AGE   IP            NODE        NOMINATED NODE   READINESS GATES
nginx-58f5559846-wl4br              1/1     Running   1          28d   10.244.41.6   node4       <none>           <none>
nginx-deployment-5969ff6c74-95zm4   0/1     Pending   0          31m   <none>        <none>      <none>           <none>
nginx-deployment-666b5b4d8f-56x7p   0/1     Pending   0          30m   <none>        edge-node   <none>           <none>
[r
[root@ansible-server cloudcore]# kubectl describe pod nginx-deployment-666b5b4d8f-56x7p
Node-Selectors:  name=edge-node
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  30m   default-scheduler  Successfully assigned default/nginx-deployment-666b5b4d8f-56x7p to edge-node

**[root@ansible-server cloudcore]# tail -f nohup.out** 
I1127 16:51:21.224525   20902 util.go:88] The resource type is nodestatus, 3
I1127 16:51:21.224541   20902 upstream.go:193] message: 975c6d76-40c9-499a-9637-2d35c70f86c5, resource type is: nodestatus
I1127 16:51:21.224547   20902 upstream.go:195] message: 975c6d76-40c9-499a-9637-2d35c70f86c5, operation type is: update
I1127 16:51:21.224557   20902 upstream.go:341] message: 975c6d76-40c9-499a-9637-2d35c70f86c5, operation is: update, and resource is node/edge-node/default/nodestatus/edge-node
I1127 16:51:21.224683   20902 util.go:113] The resource name is edge-node, 4
I1127 16:51:21.254497   20902 upstream.go:452] message: 975c6d76-40c9-499a-9637-2d35c70f86c5, update node status successfully, namespace: , name: edge-node
I1127 16:51:21.254525   20902 upstream.go:457] message: 975c6d76-40c9-499a-9637-2d35c70f86c5 process successfully
I1127 16:51:21.254675   20902 eventhandler.go:369] event to send for node edge-node, id: 1b5e95b5-208d-4a80-b388-8dfecfca6d28, parent_id: 975c6d76-40c9-499a-9637-2d35c70f86c5, group: resource, source: edgecontroller, resource: node/edge-node/default/node/edge-node, operation: response, content OK
I1127 16:51:23.746513   20902 eventhandler.go:98] Keepalive message received from node: edge-node
I1127 16:51:23.746656   20902 eventhandler.go:135] Node edge-node is still alive
I1127 16:51:31.240223   20902 eventhandler.go:201] event received for node edge-node id: 958fc6e1-5899-4965-b65b-4f13b05b50e3, parent_id: , group: meta, source: edged, resource: node/edge-node/default/nodestatus/edge-node, operation: update, content: {"UID":"38796d14-1df3-11e8-8e5a-286ed488f209","Status":{"capacity":{"cpu":"4","memory":"15885Mi","pods":"110"},"allocatable":{"cpu":"4","memory":"15785Mi","pods":"110"},"phase":"Running","conditions":[{"type":"Ready","status":"True","lastHeartbeatTime":"2019-11-27T08:51:35Z","lastTransitionTime":"2019-11-27T08:51:35Z","reason":"EdgeReady","message":"edge is posting ready status"}],"addresses":[{"type":"InternalIP","address":"1.0.11.129"},{"type":"Hostname","address":"kangpaas"}],"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"3.10.0-1062.4.1.el7.x86_64","osImage":"CentOS Linux 7 (Core)","containerRuntimeVersion":"remote://1.13.1","kubeletVersion":"v1.15.3-kubeedge-v1.1.0","kubeProxyVersion":"","operatingSystem":"linux","architecture":"amd64"}},"ExtendResources":null}
I1127 16:51:31.240331   20902 upstream.go:186] dispatch message: 958fc6e1-5899-4965-b65b-4f13b05b50e3
I1127 16:51:31.240343   20902 util.go:88] The resource type is nodestatus, 3
I1127 16:51:31.240348   20902 upstream.go:193] message: 958fc6e1-5899-4965-b65b-4f13b05b50e3, resource type is: nodestatus
I1127 16:51:31.240353   20902 upstream.go:195] message: 958fc6e1-5899-4965-b65b-4f13b05b50e3, operation type is: update
I1127 16:51:31.240368   20902 upstream.go:341] message: 958fc6e1-5899-4965-b65b-4f13b05b50e3, operation is: update, and resource is node/edge-node/default/nodestatus/edge-node
I1127 16:51:31.240496   20902 util.go:113] The resource name is edge-node, 4
**[root@ansible-server cloudcore]# cat conf/controller.yaml** 
controller:
  kube:
    master: http://192.168.100.97:8080    # kube-apiserver address (such as:http://localhost:8080)
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    node_update_frequency: 10
    kubeconfig: "/root/.kube/config"   #Enter path to kubeconfig file to enable https connection to k8s apiserver, if master and kubeconfig are both set, master will override any value in kubeconfig.
cloudhub:
  protocol_websocket: true # enable websocket protocol
  port: 10000 # open port for websocket server
  protocol_quic: true # enable quic protocol
  quic_port: 10001 # open prot for quic server
  max_incomingstreams: 10000 # the max incoming stream for quic server
  enable_uds: true # enable unix domain socket protocol
  uds_address: unix:///var/lib/kubeedge/kubeedge.sock # unix domain socket address
  address: 0.0.0.0
  ca: /etc/kubeedge/ca/rootCA.crt
  cert: /etc/kubeedge/certs/edge.crt
  key: /etc/kubeedge/certs/edge.key
  keepalive-interval: 30
  write-timeout: 30
  node-limit: 10
devicecontroller:
  kube:
    master: http://192.168.100.97:8080       # kube-apiserver address (such as:http://localhost:8080)
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    kubeconfig: "/root/.kube/config" #Enter path to kubeconfig file to enable https connection to k8s apiserver,if master and kubeconfig are both set, master will override any value in kubeconfig.

**### edgecore:**
**[root@kangpaas edge]# docker info**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-1062.4.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 15.51 GiB
Name: kangpaas
ID: MLI2:Z3FP:IJJ3:M7T5:UGIB:RVXI:OLR3:35T6:E2RZ:OBTJ:AVPX:JG6S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
**[root@kangpaas edge]# tail -f nohup.out** 
I1127 16:53:37.726596    5266 msg_processor.go:634] get a message {Header:{ID:1208b952-2ef4-4b40-bdf0-1c84a61f5d93 ParentID: Timestamp:1574844817726 Sync:false} Router:{Source:metaManager Group:resource Operation:meta-internal-sync Resource:podstatus} Content:<nil>}
I1127 16:53:37.726692    5266 msg_processor.go:481] start to sync pod status
I1127 16:53:37.726899    5266 msg_processor.go:488] list pod status, no record, skip sync
I1127 16:53:38.197361    5266 generic.go:81] GenericLifecycle: Relisting
I1127 16:53:39.197658    5266 generic.go:81] GenericLifecycle: Relisting
I1127 16:53:40.198027    5266 generic.go:81] GenericLifecycle: Relisting
I1127 16:53:41.198350    5266 generic.go:81] GenericLifecycle: Relisting
I1127 16:53:42.198648    5266 generic.go:81] GenericLifecycle: Relisting
I1127 16:53:43.199004    5266 generic.go:81] GenericLifecycle: Relisting
I1127 16:53:43.221686    5266 container_manager_linux.go:868] Found 103 PIDs in root, 103 of them are not to be moved
I1127 16:53:44.199259    5266 generic.go:81] GenericLifecycle: Relisting
I1127 16:53:45.199575    5266 generic.go:81] GenericLifecycle: Relisting
I1127 16:53:45.546761    5266 edged_status.go:163] Sync VolumesInUse: []
I1127 16:53:45.557073    5266 msg_processor.go:634] get a message {Header:{ID:9cd88a66-73bb-4e70-ab17-bab1ac78c53a ParentID: Timestamp:1574844825546 Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/edge-node} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:16656629760 scale:0} d:{Dec:<nil>} s:15885Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:16551772160 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2019-11-27 16:53:45.545409118 +0800 CST m=+4447.955077790 LastTransitionTime:2019-11-27 16:53:45.545409118 +0800 CST m=+4447.955077790 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:1.0.11.129} {Type:Hostname Address:kangpaas}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:3.10.0-1062.4.1.el7.x86_64 OSImage:CentOS Linux 7 (Core) ContainerRuntimeVersion:remote://1.13.1 KubeletVersion:v1.15.3-kubeedge-v1.1.0 KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I1127 16:53:45.560785    5266 metaclient.go:117] send sync message default/nodestatus/edge-node successed and response: {{9c7d79fa-1e00-4a05-9035-4a6de393012a 9cd88a66-73bb-4e70-ab17-bab1ac78c53a 1574844825560 false} {edged meta response default/nodestatus/edge-node} OK}
I1127 16:53:45.583406    5266 controller.go:182] received msg from cloud-hub:{Header:{ID:e60aff79-4509-4d31-84e3-9a7d843e50ee ParentID:9cd88a66-73bb-4e70-ab17-bab1ac78c53a Timestamp:1574844821467 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/edge-node} Content:[79 75]}
2019-11-27 16:53:45.583 +08:00 WARN context/context_channel.go:157 bad anonName(9cd88a66-73bb-4e70-ab17-bab1ac78c53a), do nothing
I1127 16:53:46.199899    5266 generic.go:81] GenericLifecycle: Relisting

**[root@kangpaas edge]# cat conf/edge.yaml** 
mqtt:
    server: tcp://127.0.0.1:1883 # external mqtt broker url.
    internal-server: tcp://127.0.0.1:1884 # internal mqtt broker url.
    mode: 0 # 0: internal mqtt broker enable only. 1: internal and external mqtt broker enable. 2: external mqtt broker enable only.
    qos: 0 # 0: QOSAtMostOnce, 1: QOSAtLeastOnce, 2: QOSExactlyOnce.
    retain: false # if the flag set true, server will store the message and can be delivered to future subscribers.
    session-queue-size: 100 # A size of how many sessions will be handled. default to 100.

edgehub:
    websocket:
        url: wss://119.255.249.185:10000/e632aba927ea4ac2b575ec1603d56f10/edge-node/events
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    quic:
        url: 127.0.0.1:10001
        cafile: /etc/kubeedge/ca/rootCA.crt
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    controller:
        protocol: websocket # websocket, quic
        heartbeat: 15  # second
        project-id: e632aba927ea4ac2b575ec1603d56f10
        node-id: edge-node

edged:
    register-node-namespace: default
    hostname-override: edge-node
    interface-name: ens192
    edged-memory-capacity-bytes: 7852396000
    node-status-update-frequency: 10 # second
    device-plugin-enabled: false
    gpu-plugin-enabled: false
    image-gc-high-threshold: 80 # percent
    image-gc-low-threshold: 40 # percent
    maximum-dead-containers-per-container: 1
    docker-address: unix:///var/run/docker.sock
    runtime-type: docker
    remote-runtime-endpoint: unix:///var/run/dockershim.sock
    remote-image-endpoint: unix:///var/run/dockershim.sock
    runtime-request-timeout: 2
    podsandbox-image: kubeedge/pause:3.1 # kubeedge/pause:3.1 for x86 arch , kubeedge/pause-arm:3.1 for arm arch, kubeedge/pause-arm64 for arm64 arch
    image-pull-progress-deadline: 60 # second
    cgroup-driver: cgroupfs
    node-ip: ""
    cluster-dns: ""
    cluster-domain: ""

mesh:
    loadbalance:
        strategy-name: RoundRobin

**Comment by fisherxu** [comment]
@mysteryman-huaqiang Your k8s version is 1.13？I'd suggest use 1.14/15

**Comment by mysteryman-huaqiang** [comment]
@fisherxu version is 1.15.3
[root@ansible-server ec2-user]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
[root@ansible-server ec2-user]#

**Comment by fisherxu** [comment]
Does your edgenode have been ready?

**Comment by tengzhexiao** [comment]
I have the same problem,does you settle it?

**Comment by bretagne-peiqi** [comment]
Hello @fisherxu  I have same problem.

I would like to know: How edge core react with apiserver ? like kubelet watches apiserver or it does't react with apiserver.

From your architecture diagram, It seems edge core only react with cloud core. If so,  could you please explain how is the work flow when we creating a pod. (especially after schedule to a edge node by scheduler)

**Comment by bretagne-peiqi** [comment]
in edgecore logs: bad anonName(xxxxxx-xxxxx-xxxx-xxx-xx) do nothing..

**Comment by bretagne-peiqi** [comment]
![cd9903c2696f341b5deb821c06c8e6b](https://user-images.githubusercontent.com/5621794/71611057-1c3adb80-2bd1-11ea-82da-80ed67dd21b8.png)

Here is logs for cloudcore bin..

**Comment by luogangyi** [comment]
I have digged into the warning "2019-11-27 16:53:45.583 +08:00 WARN context/context_channel.go:157 bad anonName(9cd88a66-73bb-4e70-ab17-bab1ac78c53a), do nothing"
It is becasue metamager.process.processUpdate call sendToCloud and sendToEdge both. And sendToEdge will close the anonymous(named by message parentID) which result in missing channel warning when  sendToCloud wants to write this channel.

So, this waring seems irrelevent to the problem.
