### ISSUE TITLE
Can kubeedge deal with gtp protocal? Thanks a lot

### ISSUE THREAD

**Issue by hjwoohakimwhj** [kubeedge/kubeedge#1292]
Hi, could you please tell me if kubeedge can parse gtp traffic? Thanks a lot.

**Comment by fisherxu** [comment]
Hi, could you please clarify that What will you going to do with this protocol？For edgenode access the device or edgenode access the cloud part?

**Comment by hjwoohakimwhj** [comment]
> Hi, could you please clarify that What will you going to do with this protocol？For edgenode access the device or edgenode access the cloud part?

Hi. Thanks a lot for your replay. I hope to place the edgenode behind a base which uses gtp protocal. So IoT devices can also use lte to access edgenode.

**Comment by fisherxu** [comment]
Hi, at this point we only support websocket and quic protocol for cloud and edge communication. I think you can describe your application scenario in detail, then we can have a further discussion to decide whether support in community :)

**Comment by hjwoohakimwhj** [comment]
Hi，thanks for your reply. KubeEdge documents reveal that device can use different IoT protocals to communicate with edge node. I am just wondering if these devices use 4/5G to transfer their IoT packages to edgenode through radio base, could edgenode parse this kind of  traffic which are IoT packages encapsulated by GTP-U protocal? Thanks a lot.

**Comment by kevin-wangzefeng** [comment]
Hi @hjwoohakimwhj, we have a mapper (protocal adaptor) layer to make protocals plugable: users can implement their own mapper to convert any protocal to MQTT or http, which is easier for edge application development.
