### ISSUE TITLE
make[1]: Leaving directory '/src/github.com/kubeedge/kubeedge/cloud'

### ISSUE THREAD

**Issue by vishuPPatel** [kubeedge/kubeedge#1294]
Hello Team

I follow the instruction to Setup cloud side but get the 

git clone https://github.com/kubeedge/kubeedge.git $GOPATH/src/github.com/kubeedge/kubeedge
cd $GOPATH/src/github.com/kubeedge/kubeedge

$GOPATH/src/github.com/kubeedge/kubeedge/build/tools/certgen.sh genCertAndKey edge

cd $GOPATH/src/github.com/kubeedge/kubeedge/
make all WHAT=cloudcore

root@kube-master:/src/github.com/kubeedge/kubeedge# cd $GOPATH/src/github.com/kubeedge/kubeedge/
root@kube-master:/src/github.com/kubeedge/kubeedge# make all WHAT=cloudcore
cd cloud && make cloudcore
make[1]: Entering directory '/src/github.com/kubeedge/kubeedge/cloud'
bash ../hack/verify-golang.sh
go detail version: go version go1.12.9 linux/amd64
go version: 1.12.9
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-11-29T06:18:45Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=88ed24f0e3739277f2da7ef712597e148928e428 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.259+88ed24f0e37392 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/cloudcore/cloudcore.go
make[1]: Leaving directory '/src/github.com/kubeedge/kubeedge/cloud'

I woloud like to request to team  please share the proper guide give us but there is the get the error code above show.

I change the version of different type go version of like this.1.12,1.12.1, 1.12.5 ,1.12.6,1.12.9,1.12.10. installed on my PC.

Please share the which version to working 100% fine. I will implementation for my PC. 

Thanks In Advance.

**Comment by fisherxu** [comment]
Duplicate with #1296 , close first :) 
/close
