### ISSUE TITLE
 devicecontroller.kube.master configuration key error key does not exist

### ISSUE THREAD

**Issue by hjwoohakimwhj** [kubeedge/kubeedge#1295]
**What happened**:
I follow the guides in https://docs.kubeedge.io/en/latest/setup/setup.html to install openedge. However when I run the command "systemctl start cloudcore", cloudcore fails with the following output:
Nov 29 02:45:32 ubuntu cloudcore[60496]: I1129 02:45:32.334879   60496 config.go:85] can not get devicecontroller.context.response-module key, use default value cloudhub
Nov 29 02:45:32 ubuntu cloudcore[60496]: I1129 02:45:32.334885   60496 config.go:91] can not get devicecontroller.buffer.update-device-status key, use default value 1024
Nov 29 02:45:32 ubuntu cloudcore[60496]: I1129 02:45:32.334892   60496 config.go:97] can not get devicecontroller.buffer.device-event key, use default value 1
Nov 29 02:45:32 ubuntu cloudcore[60496]: I1129 02:45:32.334897   60496 config.go:103] can not get devicecontroller.buffer.device-model-event key, use default value 1
Nov 29 02:45:32 ubuntu cloudcore[60496]: I1129 02:45:32.334903   60496 config.go:109] can not get devicecontroller.load.update-device-status-workers key, use default value 1
Nov 29 02:45:32 ubuntu cloudcore[60496]: I1129 02:45:32.334909   60496 config.go:115] can not get devicecontroller.message-layer key, use default value context
Nov 29 02:45:32 ubuntu cloudcore[60496]: E1129 02:45:32.334914   60496 config.go:119] get devicecontroller.kube.master configuration key error key does not exist
Nov 29 02:45:32 ubuntu cloudcore[60496]: E1129 02:45:32.334920   60496 config.go:121] init devicecontroller config error

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I don't change anything in controller.yaml, and the master section all are blank.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by kadisi** [comment]
#1297

**Comment by fisherxu** [comment]
Does the kubeconfig that you configed in `controller.yaml` exist? @hjwoohakimwhj

**Comment by hjwoohakimwhj** [comment]
Thanks a lot. I miss controller.yaml

**Comment by novaxiaohui** [comment]
I meet the same isuues and confused by  it for serveral days.

**Comment by qinzhuoxing** [comment]
My config file exits, but I still have the same question...how could I do???

**Comment by kadisi** [comment]
devicecontroller.kube.master  must set `“”`

**Comment by qinzhuoxing** [comment]
Thanks a lot, but now I have another question when I do ./cloudcore: read ca file  error open : no such file or directory, but the files does exits.

**Comment by qinzhuoxing** [comment]
Thanks a lot, but now I have another question when I do ./cloudcore: read ca file error open : no such file or directory, but the files does exit.

**Comment by kadisi** [comment]
@qinzhuoxing  please show your cloudcore config file , and detail error message.

**Comment by qinzhuoxing** [comment]
I have resolved my question! Some mistakes are in controller.yaml.
