### ISSUE TITLE
make[1]: Leaving directory 

### ISSUE THREAD

**Issue by vishuPPatel** [kubeedge/kubeedge#1296]
Hello Team,

I follow your given instruction, i getting the error.

How to fix It.

Thank In Advance.

root@RPCHW002:/src/github.com/kubeedge/kubeedge# cd $GOPATH/src/github.com/kubeedge/kubeedge/
root@RPCHW002:/src/github.com/kubeedge/kubeedge# make all WHAT=cloudcore
cd cloud && make cloudcore
make[1]: Entering directory '/src/github.com/kubeedge/kubeedge/cloud'
bash ../hack/verify-golang.sh
go detail version: go version go1.12.13 linux/amd64
go version: 1.12.13
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-11-29T12:32:28Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=88ed24f0e3739277f2da7ef712597e148928e428 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.259+88ed24f0e37392 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/cloudcore/cloudcore.go
make[1]: Leaving directory '/src/github.com/kubeedge/kubeedge/cloud'
root@RPCHW002:/src/github.com/kubeedge/kubeedge# make
cd cloud && make
make[1]: Entering directory '/src/github.com/kubeedge/kubeedge/cloud'
bash ../hack/verify-golang.sh
go detail version: go version go1.12.13 linux/amd64
go version: 1.12.13
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-11-29T12:34:12Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=88ed24f0e3739277f2da7ef712597e148928e428 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.259+88ed24f0e37392 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/cloudcore/cloudcore.go
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-11-29T12:34:22Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=88ed24f0e3739277f2da7ef712597e148928e428 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.259+88ed24f0e37392 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/admission/admission.go
make[1]: Leaving directory '/src/github.com/kubeedge/kubeedge/cloud'
cd edge && make
make[1]: Entering directory '/src/github.com/kubeedge/kubeedge/edge'
bash ../hack/verify-golang.sh
go detail version: go version go1.12.13 linux/amd64
go version: 1.12.13
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-11-29T12:34:32Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=88ed24f0e3739277f2da7ef712597e148928e428 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.259+88ed24f0e37392 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+'  cmd/edgecore/edgecore.go
go: downloading github.com/mattn/go-sqlite3 v1.11.0
go: downloading k8s.io/kubernetes v1.15.3
go: downloading k8s.io/cri-api v0.0.0-20190531030430-6117653b35f1
go: downloading github.com/container-storage-interface/spec v1.1.0
go: extracting github.com/container-storage-interface/spec v1.1.0
go: extracting k8s.io/cri-api v0.0.0-20190531030430-6117653b35f1
go: downloading github.com/astaxie/beego v1.12.0
go: extracting github.com/mattn/go-sqlite3 v1.11.0
go: extracting github.com/astaxie/beego v1.12.0
go: extracting k8s.io/kubernetes v1.15.3
go: downloading github.com/google/cadvisor v0.33.2-0.20190411163913-9db8c7dee20a
go: downloading google.golang.org/grpc v1.23.0
go: downloading github.com/stretchr/testify v1.3.0
go: downloading github.com/256dpi/gomqtt v0.10.4
go: downloading github.com/armon/circbuf v0.0.0-20190214190532-5111143e8da2
go: extracting github.com/armon/circbuf v0.0.0-20190214190532-5111143e8da2
go: downloading github.com/opencontainers/runc v0.0.0-20181113202123-f000fe11ece1
go: extracting github.com/256dpi/gomqtt v0.10.4
go: downloading github.com/opencontainers/selinux v1.2.2
go: extracting github.com/stretchr/testify v1.3.0
go: extracting google.golang.org/grpc v1.23.0
go: extracting github.com/opencontainers/selinux v1.2.2
go: downloading github.com/emicklei/go-restful v2.9.6+incompatible
go: extracting github.com/opencontainers/runc v0.0.0-20181113202123-f000fe11ece1
go: downloading github.com/docker/distribution v0.0.0-20190711223531-1fb7fffdb266
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: extracting github.com/emicklei/go-restful v2.9.6+incompatible
go: downloading github.com/256dpi/mercury v0.1.0
go: extracting github.com/google/cadvisor v0.33.2-0.20190411163913-9db8c7dee20a
go: downloading k8s.io/csi-translation-lib v0.0.0-20190718190424-bef8d46b95de
go: downloading github.com/coreos/go-systemd v0.0.0-20190620071333-e64a0ec8b42a
go: downloading github.com/stretchr/objx v0.2.0
go: downloading k8s.io/cloud-provider v0.0.0-20190718190308-f8e43aa19282
go: downloading github.com/mistifyio/go-zfs v2.1.1+incompatible
go: downloading k8s.io/apiextensions-apiserver v0.0.0-20190718185103-d1ef975d28ce
go: extracting github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: extracting github.com/256dpi/mercury v0.1.0
go: downloading google.golang.org/genproto v0.0.0-20190716160619-c506a9f90610
go: downloading github.com/docker/go-connections v0.4.0
go: extracting github.com/coreos/go-systemd v0.0.0-20190620071333-e64a0ec8b42a
go: downloading github.com/containerd/containerd v1.1.7
go: extracting github.com/stretchr/objx v0.2.0
go: extracting github.com/mistifyio/go-zfs v2.1.1+incompatible
go: downloading github.com/godbus/dbus v0.0.0-20181101234600-2ff6f7ffd60f
go: downloading github.com/opencontainers/runtime-spec v1.0.1
go: extracting k8s.io/cloud-provider v0.0.0-20190718190308-f8e43aa19282
go: extracting k8s.io/csi-translation-lib v0.0.0-20190718190424-bef8d46b95de
go: downloading github.com/go-chassis/go-chassis v1.7.1
go: downloading github.com/pkg/errors v0.8.1
go: extracting github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.4.0
go: extracting github.com/go-chassis/go-chassis v1.7.1
go: downloading github.com/prometheus/client_golang v1.0.0
go: extracting k8s.io/apiextensions-apiserver v0.0.0-20190718185103-d1ef975d28ce
go: extracting github.com/pkg/errors v0.8.1
go: downloading github.com/google/uuid v1.1.1
go: extracting github.com/godbus/dbus v0.0.0-20181101234600-2ff6f7ffd60f
go: downloading github.com/blang/semver v3.5.1+incompatible
go: extracting github.com/opencontainers/runtime-spec v1.0.1
go: extracting github.com/docker/go-units v0.4.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/cenkalti/backoff v2.0.0+incompatible
go: extracting github.com/google/uuid v1.1.1
go: downloading github.com/vishvananda/netlink v1.0.0
go: extracting github.com/docker/distribution v0.0.0-20190711223531-1fb7fffdb266
go: downloading github.com/patrickmn/go-cache v2.1.0+incompatible
go: extracting github.com/prometheus/client_golang v1.0.0
go: downloading k8s.io/kube-openapi v0.0.0-20190718094010-3cf2ea392886
go: extracting github.com/blang/semver v3.5.1+incompatible
go: downloading github.com/containernetworking/cni v0.6.0
go: extracting github.com/cenkalti/backoff v2.0.0+incompatible
go: extracting github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/prometheus/procfs v0.0.3
go: extracting github.com/patrickmn/go-cache v2.1.0+incompatible
go: downloading github.com/opentracing/opentracing-go v1.1.0
go: extracting github.com/vishvananda/netlink v1.0.0
go: downloading github.com/aws/aws-sdk-go v1.21.10
go: extracting github.com/containerd/containerd v1.1.7
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/prometheus/procfs v0.0.3
go: extracting github.com/containernetworking/cni v0.6.0
go: downloading github.com/coreos/pkg v0.0.0-20180108230652-97fdf19511ea
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
go: downloading github.com/prometheus/common v0.6.0
go: extracting k8s.io/kube-openapi v0.0.0-20190718094010-3cf2ea392886
go: extracting github.com/opentracing/opentracing-go v1.1.0
go: downloading cloud.google.com/go v0.43.0
go: downloading github.com/opencontainers/image-spec v1.0.1
go: extracting github.com/beorn7/perks v1.0.1
go: extracting github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/docker/spdystream v0.0.0-20181023171402-6480d4af844c
go: extracting github.com/opencontainers/go-digest v1.0.0-rc1
go: downloading github.com/morikuni/aec v0.0.0-20170113033406-39771216ff4c
go: extracting github.com/coreos/pkg v0.0.0-20180108230652-97fdf19511ea
go: downloading go.uber.org/ratelimit v0.1.0
go: extracting github.com/prometheus/common v0.6.0
go: downloading github.com/go-chassis/go-restful-swagger20 v1.0.1
go: downloading github.com/lithammer/dedent v1.1.0
go: extracting google.golang.org/genproto v0.0.0-20190716160619-c506a9f90610
go: extracting github.com/docker/spdystream v0.0.0-20181023171402-6480d4af844c
go: extracting github.com/opencontainers/image-spec v1.0.1
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/lithammer/dedent v1.1.0
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/hashicorp/go-version v1.2.0
go: extracting github.com/go-chassis/go-restful-swagger20 v1.0.1
go: downloading github.com/mattn/go-shellwords v1.0.5
go: extracting go.uber.org/ratelimit v0.1.0
go: downloading github.com/vishvananda/netns v0.0.0-20190625233234-7109fa855b0f
go: extracting github.com/morikuni/aec v0.0.0-20170113033406-39771216ff4c
go: downloading github.com/mindprince/gonvml v0.0.0-20180514031326-b364b296c732
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading gopkg.in/tomb.v2 v2.0.0-20161208151619-d5d1b5820637
go: extracting github.com/vishvananda/netns v0.0.0-20190625233234-7109fa855b0f
go: downloading github.com/sigma/go-inotify v0.0.0-20181102212354-c87b6cf5033d
go: extracting cloud.google.com/go v0.43.0
go: extracting github.com/mattn/go-shellwords v1.0.5
go: extracting github.com/hashicorp/go-version v1.2.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: extracting github.com/spf13/afero v1.2.2
go: extracting github.com/mindprince/gonvml v0.0.0-20180514031326-b364b296c732
go: downloading github.com/karrick/godirwalk v1.10.12
go: downloading github.com/containerd/console v0.0.0-20181022165439-0650fd9eeb50
go: extracting github.com/sigma/go-inotify v0.0.0-20181102212354-c87b6cf5033d
go: downloading github.com/evanphx/json-patch v4.5.0+incompatible
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/cyphar/filepath-securejoin v0.2.2
go: extracting github.com/karrick/godirwalk v1.10.12
go: downloading github.com/sirupsen/logrus v1.4.2
go: extracting github.com/containerd/console v0.0.0-20181022165439-0650fd9eeb50
go: downloading github.com/euank/go-kmsg-parser v2.0.0+incompatible
go: extracting gopkg.in/tomb.v2 v2.0.0-20161208151619-d5d1b5820637
go: downloading github.com/mrunalp/fileutils v0.0.0-20171103030105-7d4729fb3618
go: extracting github.com/evanphx/json-patch v4.5.0+incompatible
go: downloading github.com/go-chassis/foundation v0.0.0-20190621030543-c3b63f787f4c
go: extracting github.com/cyphar/filepath-securejoin v0.2.2
go: downloading github.com/syndtr/gocapability v0.0.0-20180916011248-d98352740cb2
go: extracting gopkg.in/square/go-jose.v2 v2.3.1
go: extracting github.com/euank/go-kmsg-parser v2.0.0+incompatible
go: extracting github.com/sirupsen/logrus v1.4.2
go: extracting github.com/go-chassis/foundation v0.0.0-20190621030543-c3b63f787f4c
go: extracting github.com/mrunalp/fileutils v0.0.0-20171103030105-7d4729fb3618
go: extracting github.com/syndtr/gocapability v0.0.0-20180916011248-d98352740cb2
go: extracting github.com/aws/aws-sdk-go v1.21.10
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: extracting github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: finding github.com/astaxie/beego v1.12.0
go: finding github.com/mattn/go-sqlite3 v1.11.0
go: finding google.golang.org/grpc v1.23.0
go: finding google.golang.org/genproto v0.0.0-20190716160619-c506a9f90610
go: finding github.com/container-storage-interface/spec v1.1.0
go: finding github.com/google/cadvisor v0.33.2-0.20190411163913-9db8c7dee20a
go: finding github.com/docker/go-connections v0.4.0
go: finding github.com/docker/go-units v0.4.0
go: finding github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: finding k8s.io/kube-openapi v0.0.0-20190718094010-3cf2ea392886
go: finding github.com/docker/spdystream v0.0.0-20181023171402-6480d4af844c
go: finding k8s.io/cri-api v0.0.0-20190531030430-6117653b35f1
go: finding k8s.io/kubernetes v1.15.3
go: finding k8s.io/cloud-provider v0.0.0-20190718190308-f8e43aa19282
go: finding k8s.io/apiextensions-apiserver v0.0.0-20190718185103-d1ef975d28ce
go: finding github.com/google/uuid v1.1.1
go: finding github.com/sirupsen/logrus v1.4.2
go: finding github.com/docker/distribution v0.0.0-20190711223531-1fb7fffdb266
go: finding github.com/opencontainers/go-digest v1.0.0-rc1
go: finding github.com/opencontainers/image-spec v1.0.1
go: finding github.com/mistifyio/go-zfs v2.1.1+incompatible
go: finding github.com/containerd/containerd v1.1.7
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/karrick/godirwalk v1.10.12
go: finding github.com/sigma/go-inotify v0.0.0-20181102212354-c87b6cf5033d
go: finding github.com/containerd/console v0.0.0-20181022165439-0650fd9eeb50
go: finding github.com/cyphar/filepath-securejoin v0.2.2
go: finding github.com/mrunalp/fileutils v0.0.0-20171103030105-7d4729fb3618
go: finding github.com/opencontainers/runc v0.0.0-20181113202123-f000fe11ece1
go: finding github.com/opencontainers/runtime-spec v1.0.1
go: finding github.com/godbus/dbus v0.0.0-20181101234600-2ff6f7ffd60f
go: finding github.com/coreos/go-systemd v0.0.0-20190620071333-e64a0ec8b42a
go: finding github.com/coreos/pkg v0.0.0-20180108230652-97fdf19511ea
go: finding github.com/opencontainers/selinux v1.2.2
go: finding github.com/syndtr/gocapability v0.0.0-20180916011248-d98352740cb2
go: finding github.com/vishvananda/netns v0.0.0-20190625233234-7109fa855b0f
go: finding github.com/vishvananda/netlink v1.0.0
go: finding github.com/blang/semver v3.5.1+incompatible
go: finding github.com/mattn/go-shellwords v1.0.5
go: finding github.com/mindprince/gonvml v0.0.0-20180514031326-b364b296c732
go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/prometheus/common v0.6.0
go: finding github.com/euank/go-kmsg-parser v2.0.0+incompatible
go: finding github.com/aws/aws-sdk-go v1.21.10
go: finding github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: finding cloud.google.com/go v0.43.0
go: finding github.com/spf13/afero v1.2.2
go: finding github.com/evanphx/json-patch v4.5.0+incompatible
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/stretchr/objx v0.2.0
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/beorn7/perks v1.0.1
go: finding github.com/prometheus/client_golang v1.0.0
go: finding github.com/prometheus/procfs v0.0.3
go: finding k8s.io/csi-translation-lib v0.0.0-20190718190424-bef8d46b95de
go: finding github.com/armon/circbuf v0.0.0-20190214190532-5111143e8da2
go: finding github.com/morikuni/aec v0.0.0-20170113033406-39771216ff4c
go: finding gopkg.in/square/go-jose.v2 v2.3.1
go: finding github.com/lithammer/dedent v1.1.0
go: finding github.com/containernetworking/cni v0.6.0
go: finding github.com/emicklei/go-restful v2.9.6+incompatible
go: finding github.com/256dpi/mercury v0.1.0
go: finding github.com/256dpi/gomqtt v0.10.4
go: finding github.com/eclipse/paho.mqtt.golang v1.2.0
go: finding gopkg.in/tomb.v2 v2.0.0-20161208151619-d5d1b5820637
go: finding github.com/go-chassis/go-chassis v1.7.1
go: finding github.com/go-chassis/go-restful-swagger20 v1.0.1
go: finding github.com/cenkalti/backoff v2.0.0+incompatible
go: finding github.com/go-chassis/foundation v0.0.0-20190621030543-c3b63f787f4c
go: finding github.com/hashicorp/go-version v1.2.0
go: finding github.com/patrickmn/go-cache v2.1.0+incompatible
go: finding go.uber.org/ratelimit v0.1.0
go: finding github.com/opentracing/opentracing-go v1.1.0

make[1]: Leaving directory '/src/github.com/kubeedge/kubeedge/edge'
cd keadm && make
make[1]: Entering directory '/src/github.com/kubeedge/kubeedge/keadm'
bash ../hack/verify-golang.sh
go detail version: go version go1.12.13 linux/amd64
go version: 1.12.13
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-11-29T12:40:24Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=88ed24f0e3739277f2da7ef712597e148928e428 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.259+88ed24f0e37392 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' -o keadm keadm.go
make[1]: Leaving directory '/src/github.com/kubeedge/kubeedge/keadm'
cd edgesite && make
make[1]: Entering directory '/src/github.com/kubeedge/kubeedge/edgesite'
bash ../hack/verify-golang.sh
go detail version: go version go1.12.13 linux/amd64
go version: 1.12.13
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-11-29T12:40:32Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=88ed24f0e3739277f2da7ef712597e148928e428 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.259+88ed24f0e37392 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/edgesite.go
make[1]: Leaving directory '/src/github.com/kubeedge/kubeedge/edgesite'
root@RPCHW002:/src/github.com/kubeedge/kubeedge#

**Comment by fisherxu** [comment]
Your build is right and successful, what's the problem here? :) @vishuPPatel

**Comment by vishuPPatel** [comment]
hey @fisherxu 

your point of you above show the log it's successfully build code.

I want to say that **make[1]: Leaving directory**  get the that mean what??

how to know the successfully build.

Thanks in advance.

**Comment by fisherxu** [comment]
When you use `make` cmd, it will output `make[1]: Leaving directory`. You can enter the cloud or edge dir, check the binary.
And in shell, you can check the value of `$?`, `0` is success.

**Comment by fisherxu** [comment]
Will close first :)
