### ISSUE TITLE
keadm init  show below: error: not able add the apt key due to error : exit status 2

### ISSUE THREAD

**Issue by yxzking** [kubeedge/kubeedge#1304]
root@kubeedge-cloudcore:~/go/src/github.com/kubeedge/kubeedge/keadm# ./keadm init --image-repository=registry.aliyuncs.com/google_containers --kubeedge-version=1.1.0 --kubernetes-version=1.16.3 --pod-network-cidr=10.244.0.0/16 --kube-config=/root/.kube/config
Same version of docker already installed in this host
Ubuntu distribution version is bionic
Deb suite to use: kubernetes-xenial
Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:2 http://cn.archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://cn.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://cn.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 http://cn.archive.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists...

Output failed:  exit status 2
Error: not able add the apt key due to error : exit status 2
Usage:
  keadm init [flags]

**Comment by huangdongkui** [comment]
hi how do you solution the error :Error: not able add the apt key due to error : exit status 2
