### ISSUE TITLE
kubeedge not properly installing on both ubuntu and RaspberryPi 3b

### ISSUE THREAD

**Issue by VipinKrizz** [kubeedge/kubeedge#1308]
Hi everyone,
I have been trying to install kubeedge on RaspberryPi 3b using this link.
 https://docs.kubeedge.io/en/latest/setup/installer_setup.html

But when i do the make command i'm getting error about make file. saying makefile error and go command not found. At the beginning i installed go version 1.13.x but while installing kubeedge, it specifically said that it requires go version 1.12.x itself. so i uninstalled go completely and again installed go version 1.12.x. then also it gave the same make file error.
 Later i used gobuild command to build the binary and the binary was made successfully. but when i did sudo ./keadm then it started loading something and in the end it gave an error called "**This OS version is unsupported by keadm**."
At the begining HypriotOS version 1.10.0 , so i changed version to 1.8.0 that also gave same error only and i changed version again to 1.11.2 which also produced the same. So i completely shifted to raspbian Buster lite OS and the error was same. Then i found that keadm will not work in RaspberryPi.
https://github.com/kubeedge/kubeedge/issues/883

But i saw example of kubeedge on raspberrypi and the link provided inside it also redirected to the official website(which i was already following).
Now am using Ubuntu Mate OS on raspberreyPi 3b. And followed a link online to use "gcc-arm-linux-gnueabiu" but this was not available in the apt of ubuntu. And from another set of online search i somehow able to run keadm command i when i tried to do keadm join. It gave an error saying " **Syntax error: Word unexpected (Expected ")")** " . At first i thought it was because i didnt give the cloud ip. Then later i found that it was because some cross-build. i need to solve this error and install kubeedge on RaspberryPi.

Later then i was trying to install the cloud part of kubeedge in Ubuntu 18.04(Laptop)
similar make error was there so i went on go build command and made the binary . And ran the keadm init command .
 And i got the error as 
**Error: failed to run 'sh -c swapoff -a && kubeadm init --image-repository  "k8s.gcr.io" --pod-network-cidr=100.64.0.0/10' because of error : exit status 1**

Please can any one help.
@sids-b 

**What happened**:
Error occuring while installing Kubeedge on RaspberryPi and ubuntu

**What you expected to happen**:
To create a cluster using raspberrypi with kubeedge running on it.

**How to reproduce it (as minimally and precisely as possible)**:
i followed the official website of kubeedge. (Build from source)

**Anything else we need to know?**:
I had previously installed Kubernetes in Ubuntu and completely removed that to install kubeedge on ubuntu.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  tried with both v0.3.0 and v1.0.0

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               61
Model name:          Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
Stepping:            4
CPU MHz:             1790.288
CPU max MHz:         2900.0000
CPU min MHz:         500.0000
BogoMIPS:            4589.47
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap intel_pt xsaveopt dtherm ida arat pln pts md_clear flush_l1d

- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux master-node 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Go version (e.g. `go version`): go version go1.12.13 linux/amd64

- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
RaspberryPi 3b
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM       
Model                  4
Model name:          Cortex-A53
Stepping:               r0p4
CPU max MHz:         1200.0000
CPU min MHz:         600.0000
BogoMIPS:            38.40
Flags:                 half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
- OS (e.g. `cat /etc/os-release`):
version: 18.04.2 LTS (Bionic beaver)

- Kernel (e.g. `uname -a`):
Linux worker-node 4.15.0-1032-raspi32 #34-Ubuntu SMP PREEMPT Wed Feb 6 11:50:42 UTC 2019 armv7l armv7l armv7l GNU/Linux

- Go version (e.g. `go version`): 
go version go1.12.5 linux/arm
- Others:

**Comment by VipinKrizz** [comment]
![kubeedgeerror1](https://user-images.githubusercontent.com/58075083/70233766-3aa1e880-1785-11ea-8ee5-3ecf6cdf3b17.png)
![kubeedgeerror2](https://user-images.githubusercontent.com/58075083/70233767-3aa1e880-1785-11ea-93fb-81d9eed8019d.png)
![kubeedgeerror3](https://user-images.githubusercontent.com/58075083/70233769-3aa1e880-1785-11ea-99d4-672b2cbd2206.png)

**Comment by sids-b** [comment]
cc @subpathdev @fisherxu @kadisi

**Comment by VipinKrizz** [comment]
@sids-b 
the issue is still persisting can somebody suggest any help.

**Comment by subpathdev** [comment]
Sorry for the late replay:

Addressing the first problem. ( go command not found)
This says you didn't have installed go or the binary, which called go could not be found. When you download go and unpack it to /usr/local you have to append /usr/local/go/bin in your path. This command can be used
```
export PATH=$PATH:/usr/local/go/bin
```

**Comment by subpathdev** [comment]
The tool keadm will not used the master branch. It will download the latest release and start edgecore or cloudcore from this build. If you want to use the master branch, you have to build the binaries on your own.

**Comment by subpathdev** [comment]
On which system you want to installed the package "gcc-arm-linux-gnueabiu"?

This is a used to cross compile the binary on a different architecture, to be used on the raspberry pie. You can use the normal gcc package on your raspberry pie to build the required binaries.

**Comment by subpathdev** [comment]
On your laptop can you please upload the output of the following commands `free` and `sudo kubeadm init --pod-network-cidr=10.0.0.0/10`

**Comment by VipinKrizz** [comment]
> Sorry for the late replay:
> 
> Addressing the first problem. ( go command not found)
> This says you didn't have installed go or the binary, which called go could not be found. When you download go and unpack it to /usr/local you have to append /usr/local/go/bin in your path. This command can be used
> 
> ```
> export PATH=$PATH:/usr/local/go/bin
> ```

Yes sir, My go command issue was fixed.

**Comment by VipinKrizz** [comment]
> The tool keadm will not used the master branch. It will download the latest release and start edgecore or cloudcore from this build. If you want to use the master branch, you have to build the binaries on your own.
@subpathdev 
Sir actually i want to install kubeedge on raspberrypi. After the git cloning and taring when i do the make command i am the error
![IMG_20191209_111407](https://user-images.githubusercontent.com/58075083/70410557-7c78aa80-1a75-11ea-9acb-e480158f03e7.jpg)

**Comment by VipinKrizz** [comment]
> On which system you want to installed the package "gcc-arm-linux-gnueabiu"?
> 
> This is a used to cross compile the binary on a different architecture, to be used on the raspberry pie. You can use the normal gcc package on your raspberry pie to build the required binaries.

@subpathdev 
I have installed normal gcc and it is the latest version only. But the error that i'm getting says something like
 
 #runtime/cgo
 exec: "arm-linux-gnueabi-gcc" : executable file not found in $PATH

this error am getting try to build binary using keadm.go (go build -o keadm keadm.go). This command is one which used to build the binary before and i suucessfully made the binary. But to use the 'make' command i deleted this binary and did the 'make' command, which gave the makefile error. So i planned to stick with go build command, but now i cant use the go build because it is giving this error. 

 #runtime/cgo
 exec: "arm-linux-gnueabi-gcc" : executable file not found in $PATH
Can you suggets me a solution to solve this error

**Comment by VipinKrizz** [comment]
> On your laptop can you please upload the output of the following commands `free` and `sudo kubeadm init --pod-network-cidr=10.0.0.0/10`

@subpathdev 
![gitissue](https://user-images.githubusercontent.com/58075083/70411143-6cfa6100-1a77-11ea-9b18-8503752bee6b.png)

**Comment by VipinKrizz** [comment]
@sids-b @subpathdev 
Sir i have a doubt, to install kubeedge on raspberrypi where should i follow the steps given in the below link, on RaspberryPi 3b(running Ubuntu Mate) or on my laptop(running Ubuntu 18.04LTS).
https://docs.kubeedge.io/en/latest/setup/cross-compilation.html
i tried this link on raspberrypi, but nothing new has happened.
But if i need to try this on laptop, Aftr following the above steps what should i do?

**Comment by VipinKrizz** [comment]
> > On which system you want to installed the package "gcc-arm-linux-gnueabiu"?
> > This is a used to cross compile the binary on a different architecture, to be used on the raspberry pie. You can use the normal gcc package on your raspberry pie to build the required binaries.
> 
> @subpathdev
> I have installed normal gcc and it is the latest version only. But the error that i'm getting says something like
> 
> #runtime/cgo
> exec: "arm-linux-gnueabi-gcc" : executable file not found in $PATH
> 
> this error am getting try to build binary using keadm.go (go build -o keadm keadm.go). This command is one which used to build the binary before and i suucessfully made the binary. But to use the 'make' command i deleted this binary and did the 'make' command, which gave the makefile error. So i planned to stick with go build command, but now i cant use the go build because it is giving this error.
> 
> #runtime/cgo
> exec: "arm-linux-gnueabi-gcc" : executable file not found in $PATH
> Can you suggets me a solution to solve this error

@sids-b @subpathdev 
Can you suggest me a solution for this error??

**Comment by VipinKrizz** [comment]
@sids-b I'm still nit getting any solution for my issue

**Comment by subpathdev** [comment]
@VipinKrizz you didn't have installed go or added go in your path on this system.

 Sorry for late replay I had a little time manage problem.

**Comment by subpathdev** [comment]
@VipinKrizz this isn't the 'normal' gcc. You can build all components simple but executing make. Do you have to use the arm-linux-gnueabi-gcc or a different cross build compiler if you want to build KubeEdge on your x86 machine for the raspberry pi.

**Comment by subpathdev** [comment]
@VipinKrizz ok this command shows only, that a Kubernetes cluster has daployed before executing this.

**Comment by subpathdev** [comment]
@VipinKrizz how do you set your environment variables?

**Comment by bitvijays** [comment]
@subpathdev @fisherxu Maybe we can close this. I was able to compile and run latest KubeEdge on Raspberry Pi and ubuntu machines.
