### ISSUE TITLE
edge_integration_test failed in TC_TEST_APP_DEPLOYMENT_1

### ISSUE THREAD

**Issue by tengzhexiao** [kubeedge/kubeedge#1309]
during edge_integration_test failed in TC_TEST_APP_DEPLOYMENT_1:

Test application deployment and delete deployment
  /home/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/appdeployment/application_test.go:41
    TC_TEST_APP_DEPLOYMENT_1: Test application deployment in edgecore [It]
    /home/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/appdeployment/application_test.go:52

    Timed out after 240.000s.
    Application Deployment is Unsuccessful, Pod has not come to Running State
    Expected
        <string>: 
    to equal
        <string>: Running

is that cause by my golang version1.13?

**Comment by tengzhexiao** [comment]
when I create a pod use testManager ,show :
W1206 15:37:31.545679  118189 context_channel.go:295] Failed to get channel, type:edged
W1206 15:37:31.545712  118189 context_channel.go:72] Get bad module name :edged when send message, do nothing

**Comment by tengzhexiao** [comment]
Failed to get channel is ok,but the another exception is:
"failed to read pod IP from plugin/docker: Couldn't find network status for default/redis through plugin: invalid network status for" when I try to deploy the redis pod into edge-node.

**Comment by tengzhexiao** [comment]
Why I passed some deployment test but the pod not find in k8s cluster? where dose the pods deployed?
![image](https://user-images.githubusercontent.com/23517745/70789219-8e3bb400-1dcd-11ea-8b3e-750daf22a805.png)

**Comment by fisherxu** [comment]
Now I think  we have fixed it.

/close
