### ISSUE TITLE
kubeedge 1.2 release schedule

### ISSUE THREAD

**Issue by dwSun** [kubeedge/kubeedge#1311]
According to your meeting record of Oct 16th, 2019, Kube Edge v1.2 should be released Dec 6th.

 Is there any unreleased schedule changes?

**Comment by kevin-wangzefeng** [comment]
Hi @dwSun, we are still working on release development, the latest release update will be discussed on the community meeting tomorrow.

**Comment by dwSun** [comment]
I saw your meeting record at https://docs.google.com/document/d/1Sr5QS_Z04uPfRbA7PrXr3aPwCRpx7EtsyHq7mp6CnHs/edit#

So these features below will not be supported in v1.2?
- Support K8s exec&logs API for edge application
- Support ingress at edge.
- Support managing clusters at edge from cloud (aka. EdgeSite)

**Comment by kevin-wangzefeng** [comment]
No, these features are delayed.

**Comment by kevin-wangzefeng** [comment]
Closing as v1.2.0 is released on Feb 10th.
https://github.com/kubeedge/kubeedge/releases/tag/v1.2.0

/close
