### ISSUE TITLE
can not get the response of a http request which is not a service in k8s when using edgemesh

### ISSUE THREAD

**Issue by cwl233** [kubeedge/kubeedge#1317]
**What happened**:
I am trying to use the edgemesh, following https://docs.kubeedge.io/en/latest/guides/edgemesh_test_env_guide.html .  I have run this 
`root@aa5b59cf13be:/usr/local/bin# curl http://edgemesh-example-service.default.svc.cluster:8080`
and got the response sucessfully, like this
`HOSTNAME:server-68f66dd484-mjw9l IP:172.17.0.2`

But when I trying to curl baidu.com, I can not receive the response, but a message:
```
root@aa5b59cf13be:/usr/local/bin# curl http://www.baidu.com
lb: Service length from meta db is 0
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This message is created at 
`/kubeedge/edgemesh/pkg/registry/registry.go:57`
after execute the line 57, pods is equals to nil, err is equals to "Service length from meta db is 0", because edgemesh is trying to search a service named "www.baidu.com", which doesn't exist.

I think edgemesh should try to call the real web server of "www.baidu.com" after searching in the cluster, instead return a error message only.

the stack is as follows:
```
github.com/kubeedge/kubeedge/edgemesh/pkg/registry.(*ServiceDiscovery).FindMicroServiceInstances at registry.go:58
github.com/go-chassis/go-chassis/core/loadbalancer.BuildStrategy at load_balancer.go:67
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).getEndpoint at loadbalance_handler.go:44
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).handleWithNoRetry at loadbalance_handler.go:89
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).Handle at loadbalance_handler.go:82
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next at handler_chain.go:41
github.com/kubeedge/kubeedge/edgemesh/pkg/server.process.func3 at tcp.go:97
github.com/kubeedge/kubeedge/edgemesh/pkg/resolver.(*MyResolver).Resolve at resolver.go:65
github.com/kubeedge/kubeedge/edgemesh/pkg/resolver.Resolve at resolver_chain.go:18
runtime.goexit at asm_amd64.s:1337
 - Async stack trace
github.com/kubeedge/kubeedge/edgemesh/pkg/server.process at tcp.go:108
```

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by xixi-A** [comment]
Hello,how you delployment the server.yaml? When I deploy it ,one of the  two server pod status is pending,do you have seen this question?

**Comment by cwl233** [comment]
@xixi-A 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: whatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatapp
  template:
    metadata:
      labels:
        app: whatapp
    spec:
      nodeSelector:
        name: edge-node-2
      containers:
      - name: whatapp
        image: docker.io/cloudnativelabs/whats-my-ip:latest
        ports:
        - containerPort: 8080
          hostPort: 8083

I changed the replicas from 2 to 1, beacause only one container can bind its port to 8083.

**Comment by xixi-A** [comment]
@cwl233 thanks! I will try later，and I wonder your server.yaml and client.yaml deployed on the same edgenode or two different edgenode ? thank you!

**Comment by cwl233** [comment]
@xixi-A two different edgenode.

**Comment by xixi-A** [comment]
@cwl233  Hello! I try to set the replicas from 2 to 1.Than my server and cilent pod is running.But when I  run curl http://edgemesh-example-service.default.svc.cluster:8000 ,there's error: curl: (6) Could not resolve host: edgemesh-example-service.default.svc.cluster. Besides,I try to run ctr -n k8s.io c ls , it print my container is none .And I wonder which docker image did you choose for test image? and how you test?
Here are my configmap of server and client, please help me . Thank you! 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        name: edge-node1
      containers:
      - name: client
        image: nginx:1.15.12
      initContainers:
      - args:
        - -p
        - "8000"
        - -i
        - "192.168.1.2/24,156.43.2.1/26"
        - -t
        - "12345,5432,8000"
        - -c
        - "9292"
        name: init1
        image: docker.io/kubeedge/edgemesh_init:v1.0.0
        securityContext:
          privileged: true


apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: whatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatapp
  template:
    metadata:
      labels:
        app: whatapp
    spec:
      containers:
      - name: whatapp
        image: docker.io/cloudnativelabs/whats-my-ip:latest
        ports:
        - containerPort: 8080
          hostPort: 8000
      nodeSelector:
        name: edge-node

Thank you so much!
