### ISSUE TITLE
The edge_integration_test random failed...

### ISSUE THREAD

**Issue by tengzhexiao** [kubeedge/kubeedge#1318]
In the LAN ，but the integration_test failed by random.
**Which jobs are failing**:
sometime's failed in frist step,some times failed in ohter TC_TEST_APP_DEPLOYMENT_X
**Which test(s) are failing**:
random deployment step.
**Since when has it been failing**:
Since | create the test cluster.
**Reason for failure**:

**Anything else we need to know**:

below is the log:

[testcase.log](https://github.com/kubeedge/kubeedge/files/3965894/testcase.log)

**Comment by fisherxu** [comment]
I think you'd better add your go version/kubeedge version

**Comment by tengzhexiao** [comment]
My go version is go1.12.5 linux/amd64, kubeedge version is v1.1.0-release

**Comment by FengyunPan2** [comment]
Sometimes broken at TC_TEST_APP_DEPLOYMENT_4, Sometimes broken at TC_TEST_APP_DEPLOYMENT_5...

$ go version
go version go1.12.14 linux/amd64
master kubeedge.
----
Dec 18 11:03:18.273: INFO: TestCase:TC_TEST_APP_DEPLOYMENT_5: Test application deployment delete from edgecore     Status=FAILED

• Failure [246.004 seconds]
Application deployment in edgecore Testing
/home/panfy/golang_workspace/src/github.com/kubeedge/kubeedge/edge/test/integration/appdeployment/application_test.go:39
  Test application deployment and delete deployment
  /home/panfy/golang_workspace/src/github.com/kubeedge/kubeedge/edge/test/integration/appdeployment/application_test.go:41
    TC_TEST_APP_DEPLOYMENT_5: Test application deployment delete from edgecore [It]
    /home/panfy/golang_workspace/src/github.com/kubeedge/kubeedge/edge/test/integration/appdeployment/application_test.go:100

    Timed out after 240.000s.
    Application Deployment is Unsuccessful, Pod has not come to Running State
    Expected
        <string>: Succeeded
    to equal
        <string>: Running

**Comment by FengyunPan2** [comment]
https://github.com/kubeedge/kubeedge/issues/1309

**Comment by tengzhexiao** [comment]
in the examples:
https://docs.kubeedge.io/en/latest/setup/setup.html#deploy-application-on-cloud-side :

kubectl apply -f $GOPATH/src/github.com/kubeedge/kubeedge/build/deployment.yaml

I don't understand that how could make sure the pod in edge-node ?
In cloudside the kubectl apply is just effect on kubeedge ?
The device is the same, I create a device by testManager into kubeedge-cluster, its show create success,but nothing in kubectl get device,but create by device examples file will be show. 
What is the relationship between ?
