### ISSUE TITLE
Architecture diagram “edge part”  is "edge core"

### ISSUE THREAD

**Issue by ccccbjcn** [kubeedge/kubeedge#1319]
**What would you like to be added/modified**:
Architecture diagram “edge part”  is "edge core"
https://github.com/kubeedge/kubeedge/blob/master/docs/images/kubeedge_arch.png
**Why is this needed**:
"edge core" is proper for KubeEdge.

**Comment by fisherxu** [comment]
Thanks for pointing out, will fix it soon :)
