### ISSUE TITLE
constants in project should uniform definition

### ISSUE THREAD

**Issue by du2016** [kubeedge/kubeedge#1326]
I think the following object needs to be modified,move them into /common/constants:

- [ ] module
- [ ] group
- [ ] resource
- [ ] operations
- [ ] k8s resource or other reference object (should reference from client-go,such as namespace、PV、PVC)

**Comment by du2016** [comment]
i think we should discuss some details:

1. one file or file name by kind
2. whether we should move default value define in /common/constants,or uniform define in module constants

@fisherxu @kadisi

**Comment by kadisi** [comment]
good idea,  @du2016 , I am working on the feature of kubeedge component config #1172  #1212 , and it will also involve the problem of constant definition. Welcome to discuss it together.

**Comment by du2016** [comment]
that's  great, we can define default values by component config, when the proposal approved,i can work on this if needed .
