### ISSUE TITLE
Add special characters in pattern used for validate device twin value 

### ISSUE THREAD

**Issue by robertodellapenna** [kubeedge/kubeedge#1329]
**What would you like to be added/modified**:
I would like to add some special characters in pattern used for validate Device Twin Value, in particular I'm referring to https://github.com/kubeedge/kubeedge/blob/d0bb505e42f765adad80ef2e4e22d407a9719583/edge/pkg/devicetwin/dtcommon/util.go#L55-L59
The current pattern used is **"^[a-zA-Z0-9-_.,:/@#]{1,128}$"**, I would like to add also:
- Braces: **{ }**
- Single quotes: **'**
- Empty space: 

**Why is this needed**:
In my case, I need to send more complex values through device twin value, like a dict/json, encapsulating it into a string. In general, I think that is a little bit limiting to exclude these characters and the develop cost is 0 (just add two characters into regex).

I hope you will apply this change.

Thanks

**Comment by loveplxf** [comment]
How was this problem solved in the end?

**Comment by loveplxf** [comment]
I have similar needs
