### ISSUE TITLE
Does KubeEdge now support custom message routing features like IEF? 

### ISSUE THREAD

**Issue by borlandor** [kubeedge/kubeedge#1332]
Does KubeEdge support custom message routing features like IEF? 
**What would you like to be added/modified**:
Custom message routing features similar to those in IEF should be added. The device data is sent to the custom topic of the edge node MQTT Broker. KubeEdge will forward these data to the cloud through the DIS channel. The cloud can extract these data and process and analyze the data.
**Why is this needed**:
Real-time data sending and receiving for IoT devices requires custom message routing between cloud and edge applications

**Comment by borlandor** [comment]
Added as follows:
1. Through the kubeedge cloudhub-edgehub channel , message transmission between cloud-edge can take advantage of its platform attributes, such as link security and reliability.
2. Cloud-edge message have both uplink and downlink data, and may be real-time data streams (such as telemetry, remote control, or pictures).
3, It can support customized topic routing, and can customize message routes between edge applications and between edge and cloud applications.

**Comment by openedhardware** [comment]
@borlandor 
I'd like to send a custom message from cloudhub to an edge application.

Could you provide something to achieve this?

Thanks!

**Comment by borlandor** [comment]
At present, KubeEdge cloud-edge channel only supports the control plane and simple status data reporting. You can only build the custom channel yourself, or use the cloud-edge EdgeMesh which will provided in the future version.
