### ISSUE TITLE
not able add the apt key due to error

### ISSUE THREAD

**Issue by huangdongkui** [kubeedge/kubeedge#1333]
root@hdk:~/go/src/github.com/kubeedge/kubeedge/keadm# ./keadm init --kubernetes-version=1.15.2 --kubeedge-version=1.1.0 --image-repository=registry.aliyuncs.com/google_containers
Same version of docker already installed in this host
Ubuntu distribution version is bionic
Deb suite to use: kubernetes-xenial
Hit:1 http://cn.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://cn.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://cn.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://cn.archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
Reading package lists...

Output failed:  exit status 2
Error: not able add the apt key due to error : exit status 2

**Comment by xwdreamer** [comment]
I have the same problem

**Comment by fisherxu** [comment]
Please try latest verion of keadm v1.2.1 :)
/close
