### ISSUE TITLE
too complex

### ISSUE THREAD

**Issue by acteq** [kubeedge/kubeedge#1334]
**What would you like to be added/modified**:
    simplify  the concepts, the architecture, the installation ,etc
**Why is this needed**:
   By [the document](https://docs.kubeedge.io),  instead of a cluster,  the edge part is basically a kubernetes work node.  But how to ensure the running of pods always?  nothing.  We still need a kubernetes cluster to ensure that,  so-called EdgeSite.
   So, why not removing such confusing concepts and installation, just saying we write some kubernetes applications that can easy application deployment and synchronization of metadata  between cloud and edge.

**Comment by fisherxu** [comment]
> simplify the concepts, the architecture, the installation 

+1, we need to improve the installation and the docs for the project.

> We still need a kubernetes cluster to ensure that, so-called EdgeSite.

We have two kinds of edgepart design, first is edge node, its control platform is on the cloud. The second one is edgesite, the control platform and node are all in edge side. They are two  different design.

>  why not removing such confusing concepts and installation, just saying we write some kubernetes applications that can easy application deployment and synchronization of metadata between cloud and edge.

The edge node contains the mini-kubelet, it used to manage the edge aplication schduled from cloud. And for itself it's a daemon process, not a k8s application.

**Comment by shashidharatd** [comment]
> We have two kinds of edgepart design, first is edge node, its control platform is on the cloud. The second one is edgesite, the control platform and node are all in edge side. They are two different design.
@fisherxu , so if we need application ditribution managed from cloud. But deploy some cluster services at edge cluster managed locally. can the current architecture of kubeedge support this scenario?

/cc @kevin-wangzefeng
