### ISSUE TITLE
About port mapping

### ISSUE THREAD

**Issue by umbraclet16** [kubeedge/kubeedge#1338]
According to #623 ,

> The containers running on edge node use Host network. This means:
> The containerPort and hostPort specified in the deployment should be the same

which means deploying multiple pods with one image or different images using same ports on the same node is not feasible.

Port mapping is a common requirement when using container. I don't think creating a new image and changing the port is an efficient and proper solution.

I've tried to create a service to solve this but failed. Don't know if it's because KubeEdge doesn't support creating service, or that there's no kube-proxy on the edge node.

As #769 said, containerd do support port mapping.
I wonder has such need been met? If not, is there a development schedule?

Thanks.

**Comment by arcanique** [comment]
As you described, we currently support two network pods in kubeedge. One is the host network, that is, the container shares a namespace with the host. Obviously, containers using the host network cannot have the same port number. Using hostNetworkSet by Setting spec.hostNetwork  as true . This field is false  by default.
The another is port mapping. In this way, the hostport of containers‘spec on the same edge node and other processes on the same host cannot conflict. There is nothing to do with the containerPort you specify.
Kubeedge's current deployment of some pod-related objects is basically the same as k8s.
kubeedge create service please refer to this guiide:
https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md

If you encounter specific problems in the future, we can discuss them together.

**Comment by fisherxu** [comment]
If there's any questions, please reopen it.
/close
