### ISSUE TITLE
kubeedge v1.1.0版本边缘节点最多能够支持多少容器、设备，有相关的设计规格数据或者实际测试数据吗？

### ISSUE THREAD

**Issue by illusion202** [kubeedge/kubeedge#1345]
**What would you like to be added/modified**:

**Why is this needed**:

**Comment by fisherxu** [comment]
@illusion202 

The number of pods that kubeedge edge nodes can support is the same as kubelet, but it also depends on the resources of the edge nodes.

For the maximum number of devices connected to the edge node, we need further testing, and if interested, you can participate in our testing :)

**Comment by zhanglianx111** [comment]
mark
