### ISSUE TITLE
To merge the default kube configuration for edgecontroller and devicecontroller 

### ISSUE THREAD

**Issue by kuramal** [kubeedge/kubeedge#1348]
**What would you like to be added/modified**:
To merge the default kube configuration for edgecontroller and devicecontroller
For now, the edgecontroller and devicecontroller have independent default kube config, Is it necessary to merge them?
**Why is this needed**:
edgecontroller and devicecontroller use the same kube config as default, get different configurations from the configuration file

**Comment by kevin-wangzefeng** [comment]
https://github.com/kubeedge/kubeedge/pull/1172 is the answer.

**Comment by kuramal** [comment]
ok, tks
