### ISSUE TITLE
Code Fixing need to done for isModuleEnabled() in db.go

### ISSUE THREAD

**Issue by lidiyag** [kubeedge/kubeedge#135]
The temporary change made in file db.go(pkg/common/dbm/db.go) needs to be fixed. The function isModuleEnabled() returns true in the beginning of the function.
![dbgoerror](https://user-images.githubusercontent.com/14183934/52103340-2e9c4600-260b-11e9-816e-90bae9ab1f43.png)

**Comment by sids-b** [comment]
@lidiyag can you please follow issue template here as well ??

**Comment by sids-b** [comment]
ping @lidiyag , any updates on this ?

**Comment by sids-b** [comment]
@lidiyag , still this fix is remaining ??

**Comment by m1093782566** [comment]
@lidiyag Any update on this issue?
