### ISSUE TITLE
why Cleanup function  in moudle interface is not implemented in Cloudcore registration

### ISSUE THREAD

**Issue by wangmingjunabc** [kubeedge/kubeedge#1353]
**What would you like to be added/modified**:
In kubeedge\cloud\cmd\cloudcore\app\server.go, the registerModules funciton do register cloudhub，edgecontroller and devicecontroller，but in these three funcitons， the structs passed to function core.Register are newCloudhub， newEdgeController and newDeviceController  all
of which do not implement Cleanup func of module interface in module.go。  
**Why is this needed**:
According to go syntax， all methods of interface should be implemented

**Comment by fisherxu** [comment]
@wangmingjunabc Now the Cleanup func has been deleted in module.go, please check in https://github.com/kubeedge/kubeedge/blob/master/staging/src/github.com/kubeedge/beehive/pkg/core/module.go#L17

**Comment by fisherxu** [comment]
cc @kadisi

**Comment by fisherxu** [comment]
Closed first, open again if there is still a problem :)
/close
