### ISSUE TITLE
Installation of KubeEdge 1.1.0 is failing when installed with keadm

### ISSUE THREAD

**Issue by bitvijays** [kubeedge/kubeedge#1356]
Hello Everyone, Thank you for your awesome support. While installing KubeEdge 1.1.0 using keadm (Cloud component), the below error is encountered.

**What happened**:
cp: cannot stat '/etc/kubeedge/kubeedge/edge/edgecore': No such file or directory
Error: failed to run 'sh -c cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v1.1.0-linux-amd64.tar.gz && cp /etc/kubeedge/kubeedge/edge/edgecore /usr/local/bin/.' because of error : exit status 1

**What you expected to happen**:
Successful installation of KubeEdge

**How to reproduce it (as minimally and precisely as possible)**:
keadm init --kubeedge-version=1.1.0

**Anything else we need to know?**:
This is mainly failing because when kubeedge-v1.1.0-linux-amd64.tar.gz is extracted with "tar -C /etc/kubeedge  -xvzf kubeedge-v1.1.0-linux-amd64.tar.gz" it creates a folder name "kubeedge-v1.1.0-linux-amd64" rather than "kubeedge" (which was previously in version 0.3)

**CloudSide Environment**:
Ubuntu 18.04 LTS

To Fix: (I might be wrong)

Either the zip file should be created that it creates a folder Kubeedge (as previously done in Kubeedge version 0.3) (Better and faster fix) or Keadm source file needs to be modified.

**Comment by latelee** [comment]
I had the same problem, I setup kubeedge step by step by hand, not keadm. it is ok on ubuntu 16.04 64bit.

**Comment by changtimwu** [comment]
I end up creating a symbolic link 
```
/etc/kubeedge$ sudo ln -s kubeedge-v1.1.0-linux-amd64 kubeedge
```

and then hit by another environment problem which could be easily fixed by specifying options in `--ignore-preflight-errors`. 

IMO `keadm` should be implemented as a shell script since it's just a `kubeadm` wrapper.

**Comment by fisherxu** [comment]
Please try latest verion of keadm v1.2.1 :)
/close
