### ISSUE TITLE
Proper Error Handling necessary in dtcontroller.go

### ISSUE THREAD

**Issue by lidiyag** [kubeedge/kubeedge#136]
**1. The distributeMsg() returns error as nil even if message is nil.**
![distributmsg](https://user-images.githubusercontent.com/14183934/52103656-c51d3700-260c-11e9-85cd-9d93b199ce02.png)

**2. Error handling not done in Start()**
![start](https://user-images.githubusercontent.com/14183934/52103728-1c230c00-260d-11e9-9861-414a89509c4b.png)

**Comment by sids-b** [comment]
@lidiyag , can you please follow issue template ??

**Comment by sids-b** [comment]
We don't need return here.... if we return here, device-twin will stop receiving messages.....My bad i missed it earlier.
cc @m1093782566 @rohitsardesai83
