### ISSUE TITLE
cloudcore start failed

### ISSUE THREAD

**Issue by chenjie222** [kubeedge/kubeedge#1361]
[root@k8s-master cmd]# ./cloudcore
2020/01/02 17:53:58 RollingPolicy is empty, use default policy[size]
2020-01-02 17:53:58.602 +08:00 INFO go-archaius/archaius.go:53 Configuration files: 
2020-01-02 17:53:58.602 +08:00 WARN config-manager/configurationmanager.go:140 empty configurtion from FileSource
2020-01-02 17:53:58.602 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:FileSource
2020-01-02 17:53:58.602 +08:00 INFO go-archaius/archaius.go:112 archaius init success
2020-01-02 17:53:58.602 +08:00 WARN config-manager/configurationmanager.go:140 empty configurtion from MemorySource
2020-01-02 17:53:58.602 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:MemorySource
2020-01-02 17:53:58.602 +08:00 WARN config-manager/configurationmanager.go:140 empty configurtion from CommandlineSource
2020-01-02 17:53:58.602 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:CommandlineSource
2020-01-02 17:53:58.602 +08:00 INFO enviromentvariable-source/envconfigurationsource.go:46 enable env source
2020-01-02 17:53:58.602 +08:00 INFO file-source/filesource.go:354 create new watcher
2020-01-02 17:53:58.602 +08:00 INFO memory-source/memorysource.go:105 mem source callback prepared
2020-01-02 17:53:58.602 +08:00 INFO config-manager/configurationmanager.go:117 invoke dynamic handler:EnvironmentSource
I0102 17:53:58.610427   15021 server.go:36] Version: v0.0.0-master+$Format:%h$
2020-01-02 17:53:58.610 +08:00 INFO core/module.go:41 module cloudhub registered
2020-01-02 17:53:58.610 +08:00 INFO core/module.go:41 module edgecontroller registered
2020-01-02 17:53:58.610 +08:00 INFO core/module.go:41 module devicecontroller registered
2020-01-02 17:53:58.611 +08:00 INFO core/core.go:23 starting module cloudhub
2020-01-02 17:53:58.611 +08:00 INFO core/core.go:23 starting module edgecontroller
2020-01-02 17:53:58.611 +08:00 INFO core/core.go:23 starting module devicecontroller
I0102 17:53:58.611246   15021 buffer.go:64] Update controller.buffer.update-pod-status: 1024
I0102 17:53:58.611280   15021 buffer.go:71] Update controller.buffer.update-node-status: 1024
I0102 17:53:58.611293   15021 buffer.go:78] Update controller.buffer.query-configmap: 1024
I0102 17:53:58.611306   15021 buffer.go:92] Update controller.buffer.query-service: 1024
I0102 17:53:58.611319   15021 buffer.go:100] Update controller.buffer.query-endpoints: 1024
I0102 17:53:58.611332   15021 buffer.go:107] Update controller.buffer.pod-event: 1
I0102 17:53:58.611345   15021 buffer.go:114] Update controller.buffer.configmap-event: 1
I0102 17:53:58.611358   15021 buffer.go:121] Update controller.buffer.secret-event: 1
I0102 17:53:58.611371   15021 buffer.go:128] Update controller.buffer.service-event: 1
I0102 17:53:58.611385   15021 buffer.go:135] Update controller.buffer.endpoint-event: 1
I0102 17:53:58.611400   15021 buffer.go:142] Update controller.buffer.query-persistentvolume: 1024
I0102 17:53:58.611415   15021 buffer.go:149] Update controller.buffer.query-persistentvolumeclaim: 1024
I0102 17:53:58.611430   15021 buffer.go:156] Update controller.buffer.query-volumeattachment: 1024
I0102 17:53:58.611445   15021 buffer.go:163] Update controller.buffer.query-node: 1024
I0102 17:53:58.611461   15021 buffer.go:170] Update controller.buffer.update-node: 1024
I0102 17:53:58.611480   15021 context.go:29]  send module name: cloudhub
I0102 17:53:58.611492   15021 context.go:36] receive module name: edgecontroller
I0102 17:53:58.611503   15021 context.go:43] response module name: cloudhub
I0102 17:53:58.611524   15021 kube.go:34] Controller kube master: http://127.0.0.1:6443
I0102 17:53:58.611539   15021 kube.go:41] Controller kube config: /root/.kube/config
I0102 17:53:58.611553   15021 kube.go:46] Controller kube namespace: 
I0102 17:53:58.611567   15021 kube.go:51] Controller kube content type: application/vnd.kubernetes.protobuf
I0102 17:53:58.611584   15021 kube.go:56] Controller kube QPS: 5.000000
I0102 17:53:58.611604   15021 kube.go:61] Controller kube burst: 10
I0102 17:53:58.611567   15021 server.go:45] start unix domain socket server
I0102 17:53:58.611667   15021 buffer.go:25] Update devicecontroller.buffer.update-device-status: 1024
I0102 17:53:58.611675   15021 buffer.go:32] Update devicecontroller.buffer.device-event: 1
I0102 17:53:58.611683   15021 buffer.go:39] Update devicecontroller.buffer.device-model-event: 1
I0102 17:53:58.611688   15021 context.go:29] Send module name: cloudhub
I0102 17:53:58.611694   15021 context.go:36] Receive module name: devicecontroller
I0102 17:53:58.611699   15021 context.go:43] Response module name: cloudhub
I0102 17:53:58.611710   15021 kube.go:34] Devicecontroller kube master: http://127.0.0.1:6443
I0102 17:53:58.611717   15021 kube.go:41] Devicecontroller kube config: /root/.kube/config
I0102 17:53:58.611724   15021 kube.go:48] Devicecontroller kube namespace: kube-system
I0102 17:53:58.611731   15021 kube.go:55] Devicecontroller kube content type: application/vnd.kubernetes.protobuf
I0102 17:53:58.611737   15021 kube.go:62] Devicecontroller kube QPS: 5.000000
I0102 17:53:58.611745   15021 kube.go:69] Devicecontroller kube burst: 10
I0102 17:53:58.611751   15021 load.go:19] Update device status workers: 1
I0102 17:53:58.611756   15021 messagelayer.go:19] Message layer: context
E0102 17:53:58.611767   15021 uds.go:68] failed to listen addr: listen unix //var/lib/kubeedge/kubeedge.sock: bind: no such file or directory
I0102 17:53:58.611619   15021 kube.go:66] Controller kube update frequency: 10s
I0102 17:53:58.611840   15021 kube.go:72] Controller kube Node ID: 
I0102 17:53:58.611858   15021 kube.go:79] Controller kube Node Name: 
I0102 17:53:58.611877   15021 kube.go:86]  EdgeSite is false 
I0102 17:53:58.611890   15021 load.go:49] update pod status workers: 1
I0102 17:53:58.611903   15021 load.go:56] update node status workers: 1
I0102 17:53:58.611916   15021 load.go:63] query config map workers: 4
I0102 17:53:58.611929   15021 load.go:70] query secret workers: 4
I0102 17:53:58.611942   15021 load.go:77] query service workers: 4
I0102 17:53:58.611956   15021 load.go:84] query endpoints workers: 4
I0102 17:53:58.611970   15021 load.go:91] query persistentvolume workers: 4
I0102 17:53:58.611984   15021 load.go:98] query persistentvolumeclaim workers: 4
I0102 17:53:58.611999   15021 load.go:105] query volumeattachment workers: 4
I0102 17:53:58.612014   15021 load.go:112] query node workers: 4
I0102 17:53:58.612030   15021 load.go:119] update node workers: 4
I0102 17:53:58.612042   15021 messagelayer.go:19] message layer: context
I0102 17:53:58.614386   15021 server.go:48] Start cloud hub quic server
I0102 17:53:58.616769   15021 server.go:55] Start cloud hub websocket server
I0102 17:53:58.622272   15021 upstream.go:108] start upstream controller
I0102 17:53:58.625511   15021 downstream.go:814] Start downstream devicecontroller
E0102 17:53:58.630318   15021 reflector.go:125] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:40: Failed to list *v1alpha1.Device: the server rejected our request for an unknown reason (get devices.devices.kubeedge.io)
E0102 17:53:58.630335   15021 reflector.go:125] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:40: Failed to list *v1alpha1.DeviceModel: the server rejected our request for an unknown reason (get devicemodels.devices.kubeedge.io)
W0102 17:53:58.632435   15021 controller.go:51] new downstream controller failed with error: the server rejected our request for an unknown reason (get nodes)

**Comment by fisherxu** [comment]
> Failed to list *v1alpha1.Device: the server rejected our request for an unknown reason (get

you need create the device CRD first :)

> W0102 17:53:58.632435 15021 controller.go:51] new downstream controller failed with error: the server rejected our request for an unknown reason (get nodes)

Please provide the version of the kubeedge cloudcore/edgecore, the version of k8s, thanks :)

**Comment by yzhao66** [comment]
> > Failed to list *v1alpha1.Device: the server rejected our request for an unknown reason (get
> 
> you need create the device CRD first :)
> 
> > W0102 17:53:58.632435 15021 controller.go:51] new downstream controller failed with error: the server rejected our request for an unknown reason (get nodes)
> 
> Please provide the version of the kubeedge cloudcore/edgecore, the version of k8s, thanks :)

i get same issue and create CRD 
![image](https://user-images.githubusercontent.com/44268973/72433527-75f7f400-37d4-11ea-9ad9-9e8981d1f732.png)
![image](https://user-images.githubusercontent.com/44268973/72433534-7db79880-37d4-11ea-9496-2ccc4f76a30f.png)
but it's not effect

**Comment by hanneshoettinger** [comment]
You need to set the master port in controller.yaml to 8080:
[https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/](https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/)
Default localhost port for Kubernetes is 8080. 6443 is the secure port.

As described in [https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/release_package.md](https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/release_package.md) do also set:
`vi /etc/kubernetes/manifests/kube-apiserver.yaml
# Add the following flags in spec: containers: -command section
- --insecure-port=8080
- --insecure-bind-address=0.0.0.0`

**Comment by fisherxu** [comment]
Will close this first, if there's any question, please reopen it.
/close
