### ISSUE TITLE
Edge end pods communicate with each other

### ISSUE THREAD

**Issue by zhuanghang** [kubeedge/kubeedge#1367]
How do applications communicate with each other at the edge, such as pod and database pod

**Comment by sids-b** [comment]
We can use services for pod to pod communication running on edge nodes. Current limitation is that pod to pod communication works only if nodes are in the same subnet. 
Please see test guide for reference https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md

**Comment by mumutu66** [comment]
@sids-b  how to debug the edgemesh server .. why it always binds 53 on docker0 interface and when use telnet ip 53 always receive `Connection refused`

**Comment by sids-b** [comment]
The edgemesh server is a dns server and dns servers are run on default 53 port. It resolves the service-name in the request. I am not sure about the behaviour in telnet. @arcanique maybe able to answer this

**Comment by mumutu66** [comment]
@sids-b thanks  I got it    I was using the wrong tools .  `dig` show the dns server is ok . so the real problem is the iptables 's rule .I will try to solve it.
