### ISSUE TITLE
Watch functionality for deviceTwin

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#137]
**What would you like to be added**:
Can we have a watch kind of functionality in deviceTwin? 
In current implementation of deviceTwin, if an app/user wants to get twin of a device, then a message is sent to $hw/event/device/+/twin/get topic and response is sent to $hw/event/device/+/twin/get/result topic. Similar is applicable to membership and device state.
So if an app/user needs to perform some operations based on the twin state of the device, it continuously needs to send a get message and wait for response on get/result topic.
Instead of this we can have a watch kind of functionality, which on change in twin state will publish a message on watch topic. We can have a watch topic for devices.
Following can be the flow.
1) user/app sends a message on watch topic about which devices twin/membership/state it wants to watch.(step necessary to keep count of user/apps watching on a device)
2) On update in twin/membership/state, message will be sent on watch topic.
We can maintain number of user/app watching on a device, so that if no-one is watching, updated state will not be published (will help in reducing number of messages passing in MQTT).
Example to watch topic: 
a) initialize watch topic: $hw/event/device/+/twin/watch/start
b) response watch topic: $hw/event/device/+/twin/watch/result

**Why is this needed**:
1) Reduce number of get messages flowing in mqtt broker.
2) Easy of use in performing operations based on devices.

Thoughts ?
cc @qizha @m1093782566 @rohitsardesai83 @skdwriting

**Comment by rohitsardesai83** [comment]
@sids-b , looks like a good feature to add. @qizha , please let us know if we can go ahead and prepare some kind of design document for this proposal. You can review and let us know if it's feasible to go ahead.

**Comment by m1093782566** [comment]
I think it's a reasonable feature request. WDYT @qizha

**Comment by sids-b** [comment]
While working on integration tests and debugging more inside deviceTwin, I observed that deviceTwin does publish automatically on the respective get/result topic if we change membership/twin/state. Hence no need to add extra watch topic to achieve this. get/result topic can meet the requirement.
cc @pavan187

**Comment by CindyXing** [comment]
What's the benefit of counting the number of watch? Thanks

**Comment by CindyXing** [comment]
I am thinking that we just create the onchange topic and ignore whether there is subscriber or not. Thought?
