### ISSUE TITLE
edgemesh usage support

### ISSUE THREAD

**Issue by feiyanke** [kubeedge/kubeedge#1374]
I want to setup edgemesh for the case that: two pods in the same edge node access to each other using the domain name instead of pod ip or hostPort

However, I follow the edgemesh guide, and try to change the args many times, and can not make success.
So, how exactly to do the kind of case?

**Comment by wangmingjunabc** [comment]
Maybe you need to show your args and yaml details，to find out what the problem is

**Comment by brant-ruan** [comment]
Same issue.

BTW, I follow *Edgemesh test env config guide* at 

https://kubeedge.readthedocs.io/en/latest/guides/edgemesh_test_env_guide.html#Edgemesh-end-to-end-test-guide 

to test edgemesh. The whatapp server deployment's yaml describes that it needs to use `hostPort: 8080`. However, the `edgecore` running on the slave node has been listening on port 8080 already. Therefore the whatapp server can not use host port 8080.

On edge slave:
# netstat -utlnp | grep edgecore
tcp        0      0 127.0.0.1:10255         0.0.0.0:*               LISTEN      5141/./edgecore
tcp        0      0 172.17.0.1:8080         0.0.0.0:*               LISTEN      5141/./edgecore
udp        0      0 172.17.0.1:53           0.0.0.0:*                           5141/./edgecore

Is the *Edgemesh test env config guide* out of date?

**Comment by brant-ruan** [comment]
Same issue.

BTW, I follow *Edgemesh test env config guide* at 

https://kubeedge.readthedocs.io/en/latest/guides/edgemesh_test_env_guide.html#Edgemesh-end-to-end-test-guide 

to test edgemesh. The whatapp server deployment's yaml describes that it needs to use `hostPort: 8080`. However, the `edgecore` running on the slave node has been listening on port 8080 already. Therefore the whatapp server can not use host port 8080.

On edge slave:
netstat -utlnp | grep edgecore
tcp        0      0 127.0.0.1:10255         0.0.0.0:*               LISTEN      5141/./edgecore
tcp        0      0 172.17.0.1:8080         0.0.0.0:*               LISTEN      5141/./edgecore
udp        0      0 172.17.0.1:53           0.0.0.0:*                           5141/./edgecore

Is the *Edgemesh test env config guide* out of date?

**Comment by brant-ruan** [comment]
Same issue.

BTW, I follow *Edgemesh test env config guide* at 

https://kubeedge.readthedocs.io/en/latest/guides/edgemesh_test_env_guide.html#Edgemesh-end-to-end-test-guide 

to test edgemesh. The whatapp server deployment's yaml describes that it needs to use `hostPort: 8080`. However, the `edgecore` running on the slave node has been listening on port 8080 already. Therefore the whatapp server can not use host port 8080.

On edge slave:
netstat -utlnp | grep edgecore
tcp        0      0 127.0.0.1:10255         0.0.0.0:*               LISTEN      5141/./edgecore
tcp        0      0 172.17.0.1:8080         0.0.0.0:*               LISTEN      5141/./edgecore
udp        0      0 172.17.0.1:53           0.0.0.0:*                           5141/./edgecore

Is the *Edgemesh test env config guide* out of date?
