### ISSUE TITLE
make: *** No rule to make target `edge_cross_build'.  Stop.

### ISSUE THREAD

**Issue by CC1404068613** [kubeedge/kubeedge#1381]
**What happened**:
![image](https://user-images.githubusercontent.com/44268973/72213863-21811a00-3531-11ea-814b-1732ab777585.png)
when i use command "make edge_cross_build" ,the result is "make: *** No rule to make target `edge_cross_build'.  Stop."
![image](https://user-images.githubusercontent.com/44268973/72213874-64db8880-3531-11ea-8aaa-f20eb2ccd4c0.png)

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

![image](https://user-images.githubusercontent.com/44268973/72213892-bbe15d80-3531-11ea-846f-d2a22e37175a.png)
Does it lool like cloudside is not running correctly ?
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
12.14
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
12.14
- Others:

**Comment by fisherxu** [comment]
You need to run the `make edge_cross_build` in root dir of kubeedge.
/close
