### ISSUE TITLE
How to test whether setup cloud side is correctly 

### ISSUE THREAD

**Issue by yzhao66** [kubeedge/kubeedge#1382]
**What happened**:
![image](https://user-images.githubusercontent.com/44268973/72213967-6312c480-3533-11ea-8d4d-38f2b3c3023e.png)
this command look like is ok 

![image](https://user-images.githubusercontent.com/44268973/72213972-7e7dcf80-3533-11ea-8a28-4b2f83a4f63a.png)
when run "sudo ln build/tools/cloudcore.service /etc/systemd/system/cloudcore.service"
this result is "ln: failed to access ‘build/tools/cloudcore.service’: No such file or directory"

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
12.14
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
12.14
- Others:

**Comment by fisherxu** [comment]
You can use `kubectl get node` to check the status of edge node, if it's `Ready`, which means cloudcore is running correctly. Also you can check the log of cloudcore.

**Comment by CC1404068613** [comment]
> You can use `kubectl get node` to check the status of edge node, if it's `Ready`, which means cloudcore is running correctly. Also you can check the log of cloudcore.

按照官网上的文档安装出了很多的bug

**Comment by fisherxu** [comment]
有Bug欢迎给指正 ：）如其他的问题可以直接在这里提
