### ISSUE TITLE
What's the problem with kubeedge and how to reslove this issues?

### ISSUE THREAD

**Issue by yzhao66** [kubeedge/kubeedge#1389]
**What happened**:
when i setup cloud side,there some issue as below
![image](https://user-images.githubusercontent.com/44268973/72306850-6df46300-36b3-11ea-8278-d4daa8f8eb3a.png)

![image](https://user-images.githubusercontent.com/44268973/72306672-ed356700-36b2-11ea-8950-068968676d33.png)

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
centos7
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
12.14
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
centos7
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
12.14
- Others:

**Comment by bitvijays** [comment]
@fisherxu @subpathdev We can close this issue. Document has been updated regarding this. The user didn't change directory before creating the link.
