### ISSUE TITLE
edge node is not ready

### ISSUE THREAD

**Issue by yzhao66** [kubeedge/kubeedge#1391]
**What happened**:
when i use command "./cloudcore" in cloud side
![image](https://user-images.githubusercontent.com/44268973/72311026-58d10180-36be-11ea-9824-39ff752209c6.png)

![image](https://user-images.githubusercontent.com/44268973/72311039-625a6980-36be-11ea-9253-2a0f149ce3a4.png)

when i use command "./edgecore" in edge side
![image](https://user-images.githubusercontent.com/44268973/72311150-bb2a0200-36be-11ea-9146-e14163b5a157.png)

**What you expected to happen**:
edge ndoe ready
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
centos7
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
12.14
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
centos7
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
12.14
- Others:

**Comment by kadisi** [comment]
can you show your cloudcore and edgecore config file ?

**Comment by bluefriday** [comment]
Have you ever tried configuring CNI such as weave ?

**Comment by bluefriday** [comment]
@yzhao66 
In my cases, I made socket file(just touch command) /var/lib/kubeedge/kubeedge.sock before running cloudcore.
