### ISSUE TITLE
when i reconnect a node, the cloudcore may exit unexpectedly  

### ISSUE THREAD

**Issue by NoWhere-zh** [kubeedge/kubeedge#1408]
**What happened**:
I delete a node from k8s and shutdown the edgecore. then i create the same node and restart edgecore in a short time. the cloudcore can possiblely meet an error and exit. this a serious problem.
i cannot upload the picture about the bug due to my work environment so i have to upload the log file.

**What you expected to happen**:
it is expected that the node connects successfully when the edgecore is restarted and nothing stopped.
**How to reproduce it (as minimally and precisely as possible)**:
kubectl delete node nodename
kill edgecore
kubectl create node nodename
start edgecore
that is all my operations
**Anything else we need to know?**:
here is the log :

```
E0103 17:50:15.272292   73963 messagehandler.go:354] write error, connection for node flagship-node2 will be closed, affected event id: 3dccf53f-c2ea-4ce3-a1b6-360acfa7b93a, parent_id: , group: resource, source: edgecontroller, resource: namespace/servicelist/service, operation: update, reason tls: use of closed connection
E0103 17:50:15.272346   73963 messagehandler.go:290] fail to close connection, reason: tls: use of closed connection
I0103 17:50:15.272407   73963 upstream.go:161] dispatch message ID: 00cbf3fa-d72a-46c8-8e96-6c9dfd981875
W0103 17:50:15.272441   73963 upstream.go:166] parse message: 00cbf3fa-d72a-46c8-8e96-6c9dfd981875 resource type with error: resource type not found
panic: send on closed channel

goroutine 5 [running]:
github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/channelq.(*ChannelMessageQueue).DispatchMessage(0xc0004d0000)
        /root/zhaor/IEFcode/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/channelq/channelq.go:99 +0x4d6
created by github.com/kubeedge/kubeedge/cloud/pkg/cloudhub.(*cloudHub).Start
        /root/zhaor/IEFcode/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/cloudhub.go:36 +0x59
```

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  v1.1.0

**Comment by NoWhere-zh** [comment]
i have fix this bug and i will create a pr soon. 
if someone wants to know more, please comment here.

**Comment by kadisi** [comment]
@NoWhere-zh can you format your error log use ```    ``` ?
