### ISSUE TITLE
KubeEdge on macOS?

### ISSUE THREAD

**Issue by coolbeevip** [kubeedge/kubeedge#1415]
I have installed Docker Desktop on macOS and enabled the K8S local cluster.

Can I install a standalone version of KubeEdge on macOS?

**Comment by kevin-wangzefeng** [comment]
There are some pieces of code depends on linux, so you can't run KubeEdge directly on macOS. You may need to run KubeEdge (especially edgecore) in VMs

**Comment by kevin-wangzefeng** [comment]
This is not a bug, removing the bug label.
/remove-kind bug

**Comment by coolbeevip** [comment]
Thank you
