### ISSUE TITLE
Edgecore New configuration files | Info template

### ISSUE THREAD

**Issue by bitvijays** [kubeedge/kubeedge#1422]
**What happened**:
Edgecore not running. Better output required.

**What you expected to happen**:
edgecore running

**How to reproduce it (as minimally and precisely as possible)**:
Build edgecore from the master 

**Anything else we need to know?**:
Currently, on running the edgecore with the new configuration files results in 
```
sudo ./edgecore
2020-01-21 02:04:52.445786 I | INFO: Install client plugin, protocol: rest
2020-01-21 02:04:52.446132 I | INFO: Installed service discovery plugin: edge
[TLSPrivateKeyFile: Invalid value: "/etc/kubeedge/certs/edge.key": TLSPrivateKeyFile not exist TLSCertFile: Invalid value: "/etc/kubeedge/certs/edge.crt": TLSCertFile not exist TLSCAFile: Invalid value: "/etc/kubeedge/ca/rootCA.crt": TLSCAFile not exist enable: Invalid value: false: websocket.enable and quic.enable cannot be true and false at the same time]
```
It would be suggested to have a newline between info messages. like

```
sudo ./edgecore
2020-01-21 02:04:52.445786 I | INFO: Install client plugin, protocol: rest
2020-01-21 02:04:52.446132 I | INFO: Installed service discovery plugin: edge
[
TLSPrivateKeyFile: Invalid value: "/etc/kubeedge/certs/edge.key": TLSPrivateKeyFile not exist
TLSCertFile: Invalid value: "/etc/kubeedge/certs/edge.crt": TLSCertFile not exist 
TLSCAFile: Invalid value: "/etc/kubeedge/ca/rootCA.crt": TLSCAFile not exist 
]
```
**Environment**:
Latest Master build

**Comment by kadisi** [comment]
@bitvijays  you can use `./edgecore --minconfig` to create new configfiles.

**Comment by bitvijays** [comment]
@kadisi I have created the configuration files using `./edgecore --defaultconfig`. However, if there are errors in the configuration files. It is shown in a difficult to read output. (First output) I am suggesting to add a new line, after a warning is produced (second output).

**Comment by kadisi** [comment]
@bitvijays good idea, Welcome to contribute
