### ISSUE TITLE
Cloudcore generates missing resource errors

### ISSUE THREAD

**Issue by keslerm** [kubeedge/kubeedge#1439]
**What happened**:
When cloudcore is running it constantly reports missing resources

```
E0205 14:10:37.884867   14035 reflector.go:125] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:40: Failed to list *v1alpha1.DeviceModel: the server could not find the requested res
ource (get devicemodels.devices.kubeedge.io)                                                                                                                                                                        
E0205 14:10:37.898880   14035 reflector.go:125] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:40: Failed to list *v1alpha1.Device: the server could not find the requested resource (get
 devices.devices.kubeedge.io) 
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Start cloudcore against new cluster. I've tried both, a cluster provisioned with keadm and a manually provisioned cluster.

**Anything else we need to know?**:

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): 16.04.6 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux ke-k8s-cloud 4.4.0-173-generic #203-Ubuntu SMP Wed Jan 15 02:55:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): KubeEdge v1.1.0
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): 16.04.6 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux ke-k8s-edge 4.4.0-173-generic #203-Ubuntu SMP Wed Jan 15 02:55:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): 
- Others:

**Comment by kadisi** [comment]
@keslerm you need to create DeviceModel and Device CRDs.  https://github.com/kubeedge/kubeedge/blob/master/docs/setup/setup.md

**Comment by fisherxu** [comment]
> @keslerm you need to create DeviceModel and Device CRDs. https://github.com/kubeedge/kubeedge/blob/master/docs/setup/setup.md

+1

Closed first.
/close
