### ISSUE TITLE
Integrate CRI-O as a lightweight runtime alternative 

### ISSUE THREAD

**Issue by hanneshoettinger** [kubeedge/kubeedge#1468]
**What would you like to be added/modified**:
Integrate CRI-O as a lightweight container runtime alternative.

**Why is this needed**:
Limited memory at edge device (ARM - 256MB RAM) - lightweight container runtime needed to execute containers using runc.

**Comment by chendave** [comment]
I am going to investigate k8s CIR first, them define a spec for kubeedge on the integration.

/assign

**Comment by chendave** [comment]
interface has already defined in the code base, all we need might a through validation, this include the validation against cri-o, containerd, and might be kata container as well.

**Comment by chendave** [comment]
I think we can close this now.
/close
