### ISSUE TITLE
Add option of ubuntu kubernetes apt source in keadm

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#1470]
**What would you like to be added/modified**:

Add option of ubuntu kubernetes apt source in keadm

**Why is this needed**:
Now keadm use kubernetes official apt source for downloading kubernetes, but for most China dev , it is blocked. There is issue #1333 which may be caused by this reason. it is meaningful and convenient if we can set kubernete apt source to aliyun mirror for China dev.

**Comment by latelee** [comment]
I change the source(ie, KubernetesGPGURL,KubernetesDownloadURL) to fix the problem.

**Comment by subpathdev** [comment]
@GsssC do you still facing this issue?

**Comment by GsssC** [comment]
> @GsssC do you still facing this issue?
Yes

**Comment by GsssC** [comment]
> @GsssC do you still facing this issue?

Yes

**Comment by subpathdev** [comment]
In KubeEdge version 1.2  keadm will not longer install the kubernetes cluster. I think this should resolve this issue.
\close
