### ISSUE TITLE
setup using kubeedge one click installer get the error.

### ISSUE THREAD

**Issue by vishuPPatel** [kubeedge/kubeedge#1472]
Hello kubeedge Team,

our team setup kubeedge on cloude ubuntu VM, and below steps follow as per your document.
https://kubeedge.readthedocs.io/en/latest/setup/installer_setup.html 

sudo su

wget https://github.com/kubeedge/kubeedge/releases/download/v1.2.0/keadm-v1.2.0-linux-amd64.tar.gz

tar -xvzf keadm-v1.2.0-linux-amd64.tar.gz

cd /home/keadm-v1.2.0-linux-amd64/keadm 

./keadm init --docker-version=19.03 --kubernetes-version=1.17 --kubeedge-version=1.
2.0

after getting this error what do and how to fix it.??

error: failed to run 'sh -c cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v1.2.0-linux-amd64.tar.gz && cp /etc/kubeedge/kubeedge/edge/edgecore /usr/local/bin/.' because of error : exit status 1

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) CPU @ 2.00GHz
Stepping:              3
CPU MHz:               2000.164
BogoMIPS:              4000.32
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities

- OS (e.g. `cat /etc/os-release`):

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):

Linux kubeedge 4.15.0-1052-gcp #56-Ubuntu SMP Thu Dec 19 10:54:56 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Go version (e.g. `go version`): 
- Others:

Thanks In advance.

**Comment by jay11ca39** [comment]
+1
Facing the same issue on **ubuntu 18.04**

**Comment by jay11ca39** [comment]
@sids-b ,
Any input on this issue?

**Comment by subpathdev** [comment]
/assign subpath

I thought we fixed this issue.

**Comment by kimminger** [comment]
We face the same issue also trying to install KubeEdge 1.2.0 on a Ubuntu VM 18.04 LTS
 
``` bash
failed to run 'sh -c cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v0.3.0-linux-amd64.tar.gz && cp /etc/kubeedge/kubeedge/edge/edgecore /usr/local/bin/.' because of error : exit status 1
```

seems that the cp command fails because of a wrong path.
For my understanding it should be:
```/etc/kubeedge/kubeedge/edge/edge_core```

So the correct command would be:
``` bash
failed to run 'sh -c cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v0.3.0-linux-amd64.tar.gz && cp /etc/kubeedge/kubeedge/edge/edge_core /usr/local/bin/.' because of error : exit status 1
```

**Comment by qihandeng2** [comment]
> We face the same issue also trying to install KubeEdge 1.2.0 on a Ubuntu VM 18.04 LTS
> 
> ```shell
> failed to run 'sh -c cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v0.3.0-linux-amd64.tar.gz && cp /etc/kubeedge/kubeedge/edge/edgecore /usr/local/bin/.' because of error : exit status 1
> ```
> 
> seems that the cp command fails because of a wrong path.
> For my understanding it should be:
> `/etc/kubeedge/kubeedge/edge/edge_core`
> 
> So the correct command would be:
> 
> ```shell
> sh -c cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v0.3.0-linux-amd64.tar.gz && cp /etc/kubeedge/kubeedge/edge/edge_core /usr/local/bin/.
> ```

I face the same issue with the same version of Kubeedge and Ubuntu today.
Hope this issue can be fixed soon.

**Comment by subpathdev** [comment]
Yes that the issue and we have at least 2 pr, which will close it.

**Comment by qihandeng2** [comment]
> Yes that the issue and we have at least 2 pr, which will close it.

After the code updated to the master branch, how do I get the updated one-click installer? Thanks

**Comment by fisherxu** [comment]
@qihandeng2 We will release the updated keadm in 1.2.1 this week, if you want to try it now, you can compile it from sourcecode now :)

**Comment by qihandeng2** [comment]
Many thanks.

发件人: Fei Xu <notifications@github.com>
答复: kubeedge/kubeedge <reply@reply.github.com>
日期: 2020年2月26日 星期三 下午6:35
收件人: kubeedge/kubeedge <kubeedge@noreply.github.com>
抄送: DENG Qihang <qihandeng2-c@my.cityu.edu.hk>, Mention <mention@noreply.github.com>
主题: Re: [kubeedge/kubeedge] setup using kubeedge one click installer get the error. (#1472)


@qihandeng2<https://github.com/qihandeng2> We will release the updated keadm in 1.2.1 this week, if you want to try it now, you can compile it from sourcecode now :)
