### ISSUE TITLE
storage resource fields wanted

### ISSUE THREAD

**Issue by Jack47** [kubeedge/kubeedge#1479]
**What would you like to be added/modified**:
add storage infos in edged

**Why is this needed**:
Storage usage infos in edge boxes are wanted. 

How about implement setStorageInfo just like [setMemInfo](https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edged/edged_status.go#L309-L339)? Want to know your ideas.

**Comment by fisherxu** [comment]
You want to add `ephemeral-storage` field?

**Comment by Jack47** [comment]
yes

**Comment by fisherxu** [comment]
Okey, I think that's reasonable to add it. Would you like raise a PR?
