### ISSUE TITLE
How to run e2e tests with makefile?

### ISSUE THREAD

**Issue by stacktasec** [kubeedge/kubeedge#1489]
I want to run e2e tests with the 'make e2e' using makefile, and I have already 'kind' installed in my computer, but I got an error shows that 'Kubelet should not running on edge node when running edgecore' . So I find the lines where the errors occurs in sources, it's a third library called 'go-ps' which open the '/proc' to  find the process that name match 'kubelet'.

I find that the kubelet process produced by the kind, but it's run by test scripts. 
 
So what's the correct way to run e2e test in local computer?

**Comment by fisherxu** [comment]
@stacktasec  We use this [environment variable](https://github.com/kubeedge/kubeedge/blob/master/edge/cmd/edgecore/app/server.go#L76) to control whether to check kubelet, and set it to false in [e2e start script](https://github.com/kubeedge/kubeedge/blob/master/tests/e2e/scripts/fast_test.sh#L31) .

It seems that the env variable doesn't work in your host, and are you running e2e with root user?

**Comment by stacktasec** [comment]
I found the env's reasons, and I resolved it. Thanks!

**Comment by fisherxu** [comment]
> I found the env's reasons, and I resolved it. Thanks!

Would you like share your issue before, why the env doesn't work in your host, and how to resolve it?

**Comment by fisherxu** [comment]
@stacktasec
