### ISSUE TITLE
Update README_zh.md

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#149]
**What would you like to be added**:
Update README_zh.md to be in sync with README.md

**Why is this needed**:
This is need so that chinese developers can find link to documents and mailing lists which is updated in latest README.md

**Comment by m1093782566** [comment]
cc @edisonxiang

**Comment by m1093782566** [comment]
@pavan187 

Seems ci -bot is not working now?

**Comment by pavan187** [comment]
> @pavan187
> 
> Seems ci-bot is not working now?

@m1093782566 , Assignee must be a collaborator, otherwise Github will not allow to assign
