### ISSUE TITLE
A little writing mistake in synccontroller.go:

### ISSUE THREAD

**Issue by latelee** [kubeedge/kubeedge#1490]
In `cloud/pkg/synccontroller/synccontroller.go`, L221:  
```
 klog.Errorf("Unsupported object kind： %v", sync.Spec.ObjectKind)
```
Chinese characters  `： ` need to change to `:`.

**Comment by fisherxu** [comment]
Thanks for pointing out, would you like raise a PR? :)

**Comment by latelee** [comment]
Done, see https://github.com/kubeedge/kubeedge/pull/1491

**Comment by fisherxu** [comment]
> Done, see #1491 

Thanks, could you add this `issue num` to the PR description of #1491, and in the `Fixs` field.
