### ISSUE TITLE
Synccontroller failed  to send deleteOperation msg to edge

### ISSUE THREAD

**Issue by 420691301** [kubeedge/kubeedge#1499]
**What happened**:
Synccontroller send [deleteOperation msg](https://github.com/kubeedge/kubeedge/blob/dc4f9398335c6ed02461b7e6b14f6169c9da4f24/cloud/pkg/synccontroller/objectsync.go#L24) with nil content，which can’t be send by cloudhub. Now Cloudhub can‘t tell [if msg is deleteMessge](https://github.com/kubeedge/kubeedge/blob/dc4f9398335c6ed02461b7e6b14f6169c9da4f24/cloud/pkg/cloudhub/channelq/channelq.go#L92) with [nil content](https://github.com/kubeedge/kubeedge/blob/dc4f9398335c6ed02461b7e6b14f6169c9da4f24/cloud/pkg/cloudhub/channelq/channelq.go#L356). And [edge](https://github.com/kubeedge/kubeedge/blob/dc4f9398335c6ed02461b7e6b14f6169c9da4f24/edge/pkg/edged/edged.go#L1027) can't handle deleteOperation msg with nil content.

**What you expected to happen**:
Synccontroller send deleteOperation msg successfully.

**How to reproduce it (as minimally and precisely as possible)**:
There is objectsyncs of pod A, but pod A has been deleted in kube-apiserver.

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
build from master (commit 3c441763f433096c96d39457f2b655c38377a55f)

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): centos 7
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by 420691301** [comment]
Should message with nil content be allowed by design? Or synccontroller needs to construct an object for deletion msg？

**Comment by fisherxu** [comment]
Thanks for point this out.

1. How about move L199 to above L194 in channelq.go?
2. I think we can mock a pod obj in synccontroller for deletion msg.

Would you like raise a PR? @420691301  :)

**Comment by 420691301** [comment]
yes, I will fix this. @fisherxu
