### ISSUE TITLE
Add option for the websocket connection to tunnel through an HTTP proxy

### ISSUE THREAD

**Issue by pranaypratyush** [kubeedge/kubeedge#1502]
**What would you like to be added/modified**: 
I would like to have an option `modules.edgehub.websocket.httpProxy` in `edgecore.yaml` that allows me to tunnel through an HTTP proxy. 
(Would also need `httpProxyUsername` and `httpProxyPassword` for authenticated proxies)

**Why is this needed**:
Lots of campuses (workplace, university, etc) only allow connectivity through an HTTP proxy. There's a very good reason for anyone deploying IoT in that situation to have edge server(s). So I expect that a niche would absolutely love this.

**Comment by kevin-wangzefeng** [comment]
Transparent proxy tool should help in this case.
