### ISSUE TITLE
Integration test enhancement for DeviceTwin and edged

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#151]
**What would you like to be added**:

More integration tests required for DeviceTwin and edged

**Why is this needed**:

DeviceTwin and Edged have various functionalities, and changes in one file may affect other functionality which depends on that file. Currently we do not have tests for many features/functionality of deviceTwin and edged. Only basic tests are present which do not test all the scenarios.

**Comment by naveensriram** [comment]
Need to address these as part of integration tests 

Edged scenarios
=============

-> Deploy application with restart policy: No restart
-> Deploy application with restart policy: restart on failure
-> Deploy application with restart policy: always restart
-> Deploy application with and without liveness prob
-> Deploy application with and without service probe
-> Deploy application with resource memory limit
-> Deploy application with resource CPU limit
-> Deploy application with container network configured as host
-> Deploy application with container network configured as port mapping
-> Deploy application with environment configuration for application usage
-> Deploy application which can change the device state in kubeedge node.
-> Deploy application which can add the device in kubeedge node.
-> Deploy application which can delete device in kubeedge node.


Device twin scenarios
=================

-> Add a sample device to kubeedge node
-> Add a sample device with device attributes to kubeedge node
-> Add a sample device with device twin attributes to kubeedge node
-> Add a device with tags
-> Update the existing device attributes.
-> Update the new device attributes to existing device.
-> Update the existing device twin attributes
-> Update the new devie twin attributes to existing device.
