### ISSUE TITLE
Can not find cloudcore in $GOPATH/src/github.com/kubeedge/kubeedge/cloud

### ISSUE THREAD

**Issue by majoyz** [kubeedge/kubeedge#1522]
**What happened**:kubeedge_install_source.md ask me to:
```
cd $GOPATH/src/github.com/kubeedge/kubeedge/cloud
# run cloudcore controller
# verify the configurations before running cloud(cloudcore)
mkdir ~/cmd/
cp cloudcore ~/cmd/
```
But I can't find cloudcore.

**Comment by fisherxu** [comment]
@majoyz  I have raise a PR to fix the doc, the command here should be `cp $GOPATH/src/github.com/kubeedge/kubeedge/_output/local/bin/cloudcore ~/cmd/`

**Comment by plochon** [comment]
This is a regression in releases>1.2 I think, the binary should be generated in $GOPATH/src/github.com/kubeedge/kubeedge/cloud as in previous releases.

**Comment by fisherxu** [comment]
> This is a regression in releases>1.2 I think, the binary should be generated in $GOPATH/src/github.com/kubeedge/kubeedge/cloud as in previous releases.


Yes, in releases1.2 we move all the binarys to _output, it's more centralized and easy to managed. :)
