### ISSUE TITLE
Keadm 1.2.1's  join command, I got some errors.

### ISSUE THREAD

**Issue by ytooyama** [kubeedge/kubeedge#1525]
I set up "Kubernetes 1.17.3" with "kubeadm". 
And "KubeEdge 1.2.1" with "keadm 1.2.1". 

**What happened**:
When I using the Keadm join command, I got some errors.

**What you expected to happen**:
Incorrect option?

**How to reproduce it (as minimally and precisely as possible)**:
Kubernetes 1.17.3 Setup with kubeadm.
KubeEdge 1.2.1 Setup with keadm 1.2.1.  

**Anything else we need to know?**:

```
./keadm join --cloudcoreip=172.17.28.56 --edgenodeid=esxinode7 --k8sserverip=172.17.28.56:6443 --docker-version=18.09.7
error: unknown flag: --cloudcoreip

./keadm join --cloudcore-ipport=172.17.28.56:10000 --edgenodeid=esxinode7 --k8sserverip=172.17.28.56:6443 --docker-version=18.09.7
error: unknown flag: --edgenodeid

./keadm join --cloudcore-ipport=172.17.28.56:10000 --edgenode-name=esxinode7 --k8sserverip=172.17.28.56:6443 --docker-version=18.09.7
error: unknown flag: --k8sserverip

./keadm join --cloudcore-ipport=172.17.28.56:10000 --edgenode-name=esxinode7 --docker-version=18.09.7
error: unknown flag: --docker-version

./keadm join --cloudcore-ipport=172.17.28.56:10000 --edgenode-name=esxinode7 
Works Fine!
```

The following documentation needs to be update.
https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_keadm.md

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

Cloud Side

```
root@cloud:/etc/kubeedge/kubeedge-v1.2.1-linux-amd64/cloud/cloudcore# ./cloudcore --version
KubeEdge v1.2.1
```

Edge Side

```
root@edge:/etc/kubeedge/kubeedge-v1.2.1-linux-amd64/edge# ./edgecore --version
2020-03-04 15:09:39.187193 I | INFO: Install client plugin, protocol: rest
2020-03-04 15:09:39.187540 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.2.1
```

**CloudSide Environment**:
- Hardware configuration: x86_64 Architecture
- OS: Ubuntu 18.04.4
- Kernel: 4.15.0-88-generic
- Go: Not Installed.

**EdgeSide Environment**:
- edgecore version KubeEdge v1.2.1
- Hardware configuration: x86_64 Architecture
- OS: Ubuntu 18.04.4
- Kernel: 4.15.0-88-generic
- Go: Not Installed.

**Comment by fisherxu** [comment]
@ytooyama The document https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_keadm.md has already fixed,  you can see the join command part, now there's some refactor to it. Or use `keadm --join --help` to see the help info.

**Comment by ytooyama** [comment]
Thanks fisherxu !

**Comment by fisherxu** [comment]
Np :) So I will close this first if there's no other questions :) 
/close

**Comment by ytooyama** [comment]
Will you fix this document?
https://github.com/kubeedge/kubeedge/blob/v1.2.1/docs/setup/installer_setup.md

**Comment by fisherxu** [comment]
Fixed in master branch, and the tag can't be modified now..  You can see the docs in master branch

**Comment by ytooyama** [comment]
Understand. Thanks !
