### ISSUE TITLE
There is an error in kubeedge_install_keadm.md installation document.

### ISSUE THREAD

**Issue by yxzking** [kubeedge/kubeedge#1531]
in the "Download the source code". 
url https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_keadm.md

git clone https://github.com/kubeedge/kubeedge.git $GOPATH/src/github.com/ **kubeedge/kubeedge**
multiple spaces before kubeedge

**Comment by fisherxu** [comment]
Thanks for pointing out, and would you like raise a PR? :)

**Comment by yxzking** [comment]
okay, you're welcome

**Comment by fisherxu** [comment]
Have fixed.
/close
