### ISSUE TITLE
Support VM provisioning on the edge

### ISSUE THREAD

**Issue by dingyin** [kubeedge/kubeedge#1544]
**What would you like to be added/modified**:
Add VM run time to support  VM provisioning on the edge.

**Why is this needed**:
In Telco use cases, a lot of applications are still in VM format. To support these applications, we need to support VM provisioning on the edge.

**Comment by bretagne-peiqi** [comment]
make

**Comment by bretagne-peiqi** [comment]
mark

**Comment by ugvddm** [comment]
mark
