### ISSUE TITLE
edge node does takes very long to become Ready in kubernetes if edgecore crashes and is restarted

### ISSUE THREAD

**Issue by dggonz** [kubeedge/kubeedge#1545]
**What happened**:

I launched cloudcore on the cloud, then I launched manually edgecore on the edge. Everything works fine and the node becomes 'Ready' quite fast (10-15 seconds at most).

Now if I kill edgecore, wait for the node to become 'NotReady', and then launch edgecore manually, the node will take around 4 minutes to become available again. If I stop cloudcore and then restart both cloudcore and edgecore in that order the node on the edge will become Ready in 10-15 seconds.

**What you expected to happen**:
I would expect the node to become 'Ready' within 10-15 seconds which is what it takes on a fresh cloudcore/edgecore launch

**How to reproduce it (as minimally and precisely as possible)**:
See the answer to the first question

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

cloudcore:
KubeEdge v1.2.0-beta.0.157+adcdceaf9bafbf-dirty
edgecore: 
KubeEdge v1.2.0-dirty

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): Raspberry Pi 4 4GB

Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1750.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid

- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

- Kernel (e.g. `uname -a`):
Linux kube-master.cassiopeia.local 5.3.0-1018-raspi2 #20-Ubuntu SMP Mon Feb 3 19:45:46 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

- Go version (e.g. `go version`): 
1.13
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
KubeEdge v1.2.0-dirty

- Hardware configuration (e.g. `lscpu`): Raspberry Pi 3

Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           4
Model name:                      Cortex-A53
Stepping:                        r0p4
CPU max MHz:                     1200.0000
CPU min MHz:                     600.0000
BogoMIPS:                        38.40
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid

- OS (e.g. `cat /etc/os-release`):
Yocto based custom distribution
- Kernel (e.g. `uname -a`):
Linux kube-edge.cassiopeia.local 4.19.105-v8 #1 SMP PREEMPT Wed Mar 11 13:44:07 UTC 2020 aarch64 GNU/Linux

- Go version (e.g. `go version`): 
1.13
- Others:

**Comment by zqdlove** [comment]
same  question

**Comment by fisherxu** [comment]
Now the issue has been fixed in #1670
