### ISSUE TITLE
can't deploy nginx-deployment sample succeed

### ISSUE THREAD

**Issue by latelee** [kubeedge/kubeedge#1549]
**What happened**:
When I finished setup KubeEdge, then I test the sample nginx-deployment using `kubectl apply -f $GOPATH/src/github.com/kubeedge/kubeedge/build/deployment.yaml`, the status is `Pending` (I wait for 8 min, it's still pending), then I delete it, the status is `Terminating`(I wait for a long time but it is still Terminating).  See below for more.

**What you expected to happen**:
nginx-deployment is running well.

**How to reproduce it (as minimally and precisely as possible)**:
follow the doc.

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
```
./cloudcore --version
KubeEdge v1.2.1-dirty
```

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): `Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz`
- OS (e.g. `cat /etc/os-release`): Ubuntu 16.04 LTS x86_64
- Kernel (e.g. `uname -a`): ubuntu 4.4.0-174
- Go version (e.g. `go version`): go1.12.14 linux/amd64
- Others:

EdgeSide Environment: the same as CloudSide

1. checking the system
after setup KubeEdge, the node status is:
```
# kubectl get node
NAME         STATUS   ROLES    AGE   VERSION
edge-node    Ready    edge     31m   v1.17.1-kubeedge-v1.2.0
edge-node2   Ready    edge     30m   v1.17.1-kubeedge-v1.2.0
ubuntu       Ready    master   68m   v1.17.4
```
the node is ready, and the crds is as follows: 
```
# kubectl get crds
NAME                                           CREATED AT
clusterobjectsyncs.reliablesyncs.kubeedge.io   2020-03-17T06:45:08Z
devicemodels.devices.kubeedge.io               2020-03-17T06:44:50Z
devices.devices.kubeedge.io                    2020-03-17T06:44:55Z
objectsyncs.reliablesyncs.kubeedge.io          2020-03-17T06:45:08Z
```

2. deploy nginx:
```
kubectl apply -f $GOPATH/src/github.com/kubeedge/kubeedge/build/deployment.yaml
```
but it is pending. 

3. after some time, it still pending:
```
# kubectl get pod
NAME                                           READY   STATUS        RESTARTS   AGE
nginx-deployment-77698bff7d-jdm8k              0/1     Pending       0          12m
```

4. check the information:
```
# kubectl describe pod nginx-deployment-77698bff7d-jdm8k
Name:           nginx-deployment-77698bff7d-jdm8k
Namespace:      default
Priority:       0
Node:           edge-node2/
Labels:         app=nginx
                pod-template-hash=77698bff7d
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/nginx-deployment-77698bff7d
Containers:
  nginx:
    Image:        nginx:1.15.12
    Port:         80/TCP
    Host Port:    80/TCP
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gb4kq (ro)
Conditions:
  Type           Status
  PodScheduled   True 
Volumes:
  default-token-gb4kq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gb4kq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  13m   default-scheduler  Successfully assigned default/nginx-deployment-77698bff7d-jdm8k to edge-node2
```
**The only I know from the information is the deployment is assigned to the node, nothing else.**

5. try to get the log but refused:
```
# kubectl logs nginx-deployment-77698bff7d-jdm8k
Error from server: Get https://192.168.0.153:10250/containerLogs/default/nginx-deployment-77698bff7d-jdm8k/nginx: dial tcp 192.168.0.153:10250: connect: connection refused
```

6. finaly I delete it.
```
# kubectl delete -f $GOPATH/src/github.com/kubeedge/kubeedge/build/deployment.yaml
deployment.apps "nginx-deployment" deleted
```

it is terminating: 
```
# kubectl get pod
NAME                                           READY   STATUS        RESTARTS   AGE
nginx-deployment-77698bff7d-jdm8k              0/1     Terminating   0          20m
```
the pod information:
```
# kubectl get pod nginx-deployment-77698bff7d-jdm8k -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-03-17T07:12:58Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2020-03-17T07:33:56Z"
  generateName: nginx-deployment-77698bff7d-
  labels:
    app: nginx
    pod-template-hash: 77698bff7d
  name: nginx-deployment-77698bff7d-jdm8k
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-deployment-77698bff7d
    uid: c3764762-55a3-41f4-a5b8-11706470f261
  resourceVersion: "11060"
  selfLink: /api/v1/namespaces/default/pods/nginx-deployment-77698bff7d-jdm8k
  uid: f37c9c28-d6c5-44a8-8743-f3d4fc5da89a
spec:
  containers:
  - image: nginx:1.15.12
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-gb4kq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: edge-node2
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-gb4kq
    secret:
      defaultMode: 420
      secretName: default-token-gb4kq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-17T07:12:58Z"
    status: "True"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
```

Is there sth I miss?

**Comment by fisherxu** [comment]
Your edge node is arm arch? Does the image have pulled? :) @latelee

**Comment by latelee** [comment]
@fisherxu Edge node machine is as same as Cloud side.(actually I run these machine using VMware, I copy the cloud machine for edge node),see the following output:
```
root@edge-node:~# hostname
edge-node
root@edge-node:~# uname -a
Linux edge-node 4.4.0-174-generic #204-Ubuntu SMP Wed Jan 29 06:41:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@edge-node:~# 
```
config file:
```
root@edge-node:~# cat /etc/kubeedge/config/edgecore.yaml 
# With --minconfig , you can easily used this configurations as reference.
# It's useful to users who are new to KubeEdge, and you can modify/create your own configs accordingly. 
# This configuration is suitable for beginners.

apiVersion: edgecore.config.kubeedge.io/v1alpha1
database:
  dataSource: /var/lib/kubeedge/edgecore.db
kind: EdgeCore
modules:
  edged:
    cgroupDriver: systemd
    clusterDNS: ""
    clusterDomain: ""
    devicePluginEnabled: false
    dockerAddress: unix:///var/run/docker.sock
    gpuPluginEnabled: false
    hostnameOverride: edge-node
    interfaceName: eth0
    nodeIP: 192.168.0.142
    podSandboxImage: kubeedge/pause:3.1
    remoteImageEndpoint: unix:///var/run/dockershim.sock
    remoteRuntimeEndpoint: unix:///var/run/dockershim.sock
    runtimeType: docker
  edgehub:
    heartbeat: 15
    tlsCaFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/edge.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key
    websocket:
      enable: true
      handshakeTimeout: 30
      readDeadline: 15
      server: 192.168.0.102:10000
      writeDeadline: 15
  eventbus:
    mqttMode: 2
    mqttQOS: 0
    mqttRetain: false
    mqttServerExternal: tcp://127.0.0.1:1883
    mqttServerInternal: tcp://127.0.0.1:1884
```

docker image:
```
# docker images | grep nginx
nginx                                                1.15.12             53f3fd8007f7        10 months ago       109MB
```

**Comment by latelee** [comment]
some more log (cloud side):
```
I0317 15:12:59.004429   23821 downstream.go:83] send message successfully, operation: update, resource: node/edge-node2/default/pod/nginx-deployment-77698bff7d-jdm8k
I0317 15:12:59.004480   23821 util.go:88] The resource type is pod, 3
I0317 15:12:59.004526   23821 util.go:88] The resource type is pod, 3
I0317 15:12:59.004532   23821 util.go:113] The resource name is nginx-deployment-77698bff7d-jdm8k, 4
I0317 15:12:59.004551   23821 util.go:88] The resource type is pod, 3
I0317 15:12:59.004556   23821 util.go:113] The resource name is nginx-deployment-77698bff7d-jdm8k, 4
E0317 15:12:59.004614   23821 messagehandler.go:448] write error, connection for node edge-node2 will be closed, affected event id: dba8d7ec-ffa4-4c6f-ac6e-accfa527a366, parent_id: , group: resource, source: edgecontroller, resource: default/pod/nginx-deployment-77698bff7d-jdm8k, operation: update, reason tls: use of closed connection
E0317 15:12:59.207105   23821 messagehandler.go:448] write error, connection for node edge-node2 will be closed, affected event id: de20b44c-96b9-47e7-a35c-b25949e2bb43, parent_id: , group: resource, source: edgecontroller, resource: default/pod/nginx-deployment-55677b6b95-2hvd4, operation: insert, reason tls: use of closed connection
```
it says `write error`, but I cant see the reason.

**Comment by fisherxu** [comment]
Any error logs in edgecore?

**Comment by latelee** [comment]
I checked the logs on edge side, then found the following error (matched the tmie `15:12:59` on cloud side)
```
I0317 15:12:54.408802  100838 process.go:449] node connection event occur: cloud_disconnected
I0317 15:12:54.408828  100838 eventbus.go:88] Success in pubMQTT with topic: node/connection
E0317 15:12:59.323218  100838 process.go:130] failed to send message: tls: use of closed connection
E0317 15:12:59.323255  100838 process.go:196] websocket write error: failed to send message, error: tls: use of closed connection
```
it seems the error is error: tls: use of closed connection`. 
but the connection is ok, because I see the nodes is ready.

**Comment by fisherxu** [comment]
This should be a bug, and needs to be resolved. For workaround force deleting the pod, then the new pod will be created.

**Comment by latelee** [comment]
hi @fisherxu 
I checked #1406 .
I tried deploy several time today and yesterday. My issue may be a little different. I delete pod forced, but the new pod is still pendding.
I think the actually problem my be `error: tls: use of closed connection`, ie, the cloud side can't write message to edge side, or vice versa.

**Comment by bluefriday** [comment]
I have same issue too. 
In my case, edge part is raspberry pi (3 b+).
I crossed-compile for arm architecutre. but nginx is still peding.

**Comment by latelee** [comment]
I tried to deploy edgecore on x86_64(ubuntu) and armv7l(TI board). And try the nginx and led example, but failed many times. 
But,  I haved successed deploy the pod one or two times on one node, see the following:  
```
# kubectl get pod
NAME                                 READY   STATUS    RESTARTS   AGE
nginx-deployment-747c6887f5-d759g   1/1     Running   0          15m
nginx-deployment-747c6887f5-hpx5z   0/1     Pending   0          15m
nginx-deployment-747c6887f5-zvkqg   0/1     Pending   0          15m
```
I dont know why, I cant find the answer.

**Comment by PearceDuan** [comment]
same problem hit me...

**Comment by sheep94lion** [comment]
I met the same problem.
But my edge node did not pull the Nginx docker image.

`sudo docker images` on edge node shows nothing.

Log on edgenode:

> W0427 01:15:17.329355    3304 context_channel.go:158] Get bad anonName:0e938095-5622-4ba9-be10-b96852fffb8b when sendresp message, do nothing
> I0427 01:15:21.957269    3304 process.go:622] get a message {Header:{ID:d0464390-fc11-4987-b01c-1e8ba372f3e8 ParentID: Timestamp:1587950121957 ResourceVersion: Sync:false} Router:{Source:metaManager Group:resource Operation:meta-internal-sync Resource:podstatus} Content:<nil>}
> I0427 01:15:21.957421    3304 process.go:462] start to sync pod status
> I0427 01:15:21.957765    3304 process.go:469] list pod status, no record, skip sync
> I0427 01:15:22.188632    3304 communicate.go:148] CheckConfirm
> I0427 01:15:22.188717    3304 communicate.go:151] has msg
> I0427 01:15:22.188735    3304 communicate.go:155] redo task due to no recv
> I0427 01:15:22.188759    3304 communicate.go:151] has msg
> I0427 01:15:22.188773    3304 communicate.go:155] redo task due to no recv
> I0427 01:15:22.189025    3304 dtcontext.go:69] TwinModule is healthy 1587950122
> I0427 01:15:22.189055    3304 dtcontext.go:69] DeviceModule is healthy 1587950122
> I0427 01:15:22.189067    3304 dtcontext.go:69] CommModule is healthy 1587950122
> I0427 01:15:22.189078    3304 dtcontext.go:69] MemModule is healthy 1587950122
> I0427 01:15:22.422849    3304 container_manager_linux.go:880] Found 136 PIDs in root, 136 of them are not to be moved
> I0427 01:15:27.326235    3304 edged_status.go:170] Sync VolumesInUse: []
> I0427 01:15:27.336740    3304 process.go:622] get a message {Header:{ID:2f865047-1165-44b1-8beb-07bd030bd29d ParentID: Timestamp:1587950127326 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/kubeedge-node1} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:2 scale:0} d:{Dec:<nil>} s:2 Format:DecimalSI} memory:{i:{value:2065694720 scale:0} d:{Dec:<nil>} s:1970Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:2 scale:0} d:{Dec:<nil>} s:2 Format:DecimalSI} memory:{i:{value:1960837120 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2020-04-27 01:15:27.293817444 +0000 UTC m=+1985.555364989 LastTransitionTime:2020-04-27 01:15:27.293817444 +0000 UTC m=+1985.555364989 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:172.16.61.131} {Type:Hostname Address:kubeedge-node1}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.15.0-96-generic OSImage:Ubuntu 18.04.4 LTS ContainerRuntimeVersion:remote://19.3.8 KubeletVersion:v1.17.1-kubeedge-v1.2.1 KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
> I0427 01:15:27.351066    3304 metaclient.go:114] send sync message default/nodestatus/kubeedge-node1 successed and response: {{2569c8ab-3329-421b-b10b-00c4a71e2b5e 2f865047-1165-44b1-8beb-07bd030bd29d 1587950127351  false} {edged meta response default/nodestatus/kubeedge-node1} OK}
> I0427 01:15:27.388793    3304 process.go:117] received msg from cloud-hub:{Header:{ID:ea59ccb0-d000-4537-85cd-002e10d417db ParentID:2f865047-1165-44b1-8beb-07bd030bd29d Timestamp:1587950127305 ResourceVersion:274413 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/kubeedge-node1} Content:OK}

My log on cloud side:

> I0427 09:16:55.891291   24761 util.go:113] The resource name is nginx-deployment-77698bff7d-5vzvq, 4
> I0427 09:17:00.891157   24761 util.go:88] The resource type is pod, 3
> I0427 09:17:00.891182   24761 util.go:88] The resource type is pod, 3

**Comment by bluefriday** [comment]
In my case, my edge node could not pull sandbox image (ex : kubeedge/pause:3.1).
After change to connected repository, pending and terminating issued solved.

**Comment by xwdreamer** [comment]
I have the same problem. kube-flannel-ds-arm is pending on raspberry pi,  but kube-flannel-ds-amd64 on virtual machine is ok.
I can successfully depoly nginx.

```
root@userver10:/home/xuwei# kubectl get pod --all-namespaces -owide
NAMESPACE     NAME                                READY   STATUS    RESTARTS   AGE     IP             NODE          NOMINATED NODE   READINESS GATES
default       nginx-11-69964b4687-kqbb6           1/1     Running   0          24h     172.17.0.2     userver11     <none>           <none>
default       nginx-rsap-54f6d8cf77-hsxqx         1/1     Running   0          143m    172.17.0.2     raspberrypi   <none>           <none>
kube-system   coredns-6955765f44-btq9g            1/1     Running   2          3d20h   10.244.0.7     userver10     <none>           <none>
kube-system   coredns-6955765f44-hvggl            1/1     Running   2          3d20h   10.244.0.6     userver10     <none>           <none>
kube-system   etcd-userver10                      1/1     Running   2          3d20h   192.168.1.44   userver10     <none>           <none>
kube-system   kube-apiserver-userver10            1/1     Running   2          3d20h   192.168.1.44   userver10     <none>           <none>
kube-system   kube-controller-manager-userver10   1/1     Running   2          3d20h   192.168.1.44   userver10     <none>           <none>
kube-system   kube-flannel-ds-amd64-8x6f9         1/1     Running   0          2d13h   192.168.1.47   userver11     <none>           <none>
kube-system   kube-flannel-ds-amd64-8xq86         1/1     Running   1          2d17h   192.168.1.44   userver10     <none>           <none>
kube-system   kube-flannel-ds-arm-gvfvx           0/1     Pending   0          24h     <none>         raspberrypi   <none>           <none>
kube-system   kube-proxy-g9pp6                    1/1     Running   2          3d20h   192.168.1.44   userver10     <none>           <none>
kube-system   kube-scheduler-userver10            1/1     Running   2          3d20h   192.168.1.44   userver10     <none>           <none>
root@userver10:/home/xuwei#
```

I upload the error on the slack:https://app.slack.com/client/TDZ5TGXQW/CDXVBS085/thread/CDXVBS085-1592816595.435300.

**Comment by hackers365** [comment]
I have same issue too.

**Comment by Hejianxiong** [comment]
I have the same issue, However, I was use the kuberntes 1.21.0 version, kubeedge is latest.  I switch kubernetes to 1.19, everything is ok !
