### ISSUE TITLE
Issue with update-gofmt.sh script

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#155]
**What happened**:
Running hack/update-gofmt.sh still gives gofmt warning in CI

**What you expected to happen**:
No warnings in CI

**How to reproduce it (as minimally and precisely as possible)**:
Clone the code
Run hack/update-gofmt.sh

**Comment by sids-b** [comment]
Can be seen in PR #154

**Comment by sids-b** [comment]
According to @srivatsav123 , there can be an issue with gometalinter which is not taking -w flag in gofmt

**Comment by srivatsav123** [comment]
@sids-b - Hi no issue with both update-gofmt.sh script and gometalinter ..But the version which is used to test gofmt must be  1.11 or above(go version  1.11). If its below 1.11 there may be possiblity of not formating correctly..(Possibly some bug so that some lines will not get formatted)

**Comment by srivatsav123** [comment]
@sids-b you can close the issue..

**Comment by sids-b** [comment]
We are using go version 1.11... you can check  .travis.yml for the same :)

**Comment by srivatsav123** [comment]
yes agree..But in local host ..if we use version 1.9.1..!..Then there will be missmatch in formatting..Please use go version 1.11 in local host and try..

**Comment by sids-b** [comment]
So as suggested by Manju, we need to suggest to use golang v1.11 during development
