### ISSUE TITLE
KubeEdge v1.2.1 日志无法输出到文件中

### ISSUE THREAD

**Issue by defutian** [kubeedge/kubeedge#1554]
版本：v1.2.1 
测试环境：centos 7.7 kubernetes 1.17.4
测试步骤：在启动参数中指定--log-dir、--log-file参数，举例：
 ./cloudcore --log-dir=/var/log --log-file=cloudcore.log
期望结果：日志输出到指定目录文件中
实际结果：无法产生日志文件
补充：cloudcore、edgecore具有相同的问题

**Comment by fisherxu** [comment]
试一下把这个参数`--logtostderr`设为`fasle`，这个参数默认是`true`,表示`log to standard error instead of files (default true)`

**Comment by defutian** [comment]
> 试一下把这个参数`--logtostderr`设为`fasle`，这个参数默认是`true`,表示`log to standard error instead of files (default true)`
> 可以直接这么用 `./cloudcore --logtostderr=false --log-file=/var/log/cloudcore.log`
> --log-dir 和 --log-file这两个是互斥的，不能同时使用，
> 源码：https://github.com/kubernetes/klog/blob/master/klog.go#L486

是的，经过测试--logtostderr、--log-file、--log-dir有相互排斥行为，具体为：
1、logtostderr为true时，--log-file、--log-dir同时使用或者单独使用均无效。
2、logtostderr为false时，--log-file、--log-dir同时使用，--log-dir起作用，--log-file无效、单独使用均有效。

这种情况是否符合产品预期？

**Comment by fisherxu** [comment]
这里使用的日志库是k8s上游的klog，kubeedge没有做改动，有设计问题可以到上游发起讨论 :)

**Comment by fisherxu** [comment]
Close this issue first :)
/close
