### ISSUE TITLE
close nil channel

### ISSUE THREAD

**Issue by drcwr** [kubeedge/kubeedge#1559]
**What happened**:

> W0323 11:12:01.405476   24637 messagehandler.go:174] Timeout to receive heart beat from edge node abc for project e632aba927ea4ac2b575ec1603d56f10
> panic: close of nil channel
> 
> goroutine 21532 [running]:
> github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler.(*MessageHandle).UnregisterNode(0xc0008c9420, 0x18fd040, 0xc00075a280, 0xc0007eeba0, 0x4)
> 	/root/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler/messagehandler.go:299 +0x113
> github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler.(*MessageHandle).ServeConn(0xc0008c9420, 0x18fd040, 0xc00075a280, 0xc0007eeba0)
> 	/root/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler/messagehandler.go:271 +0x289
> created by github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler.(*MessageHandle).OnRegister
> 	/root/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler/messagehandler.go:159 +0x224

```
func (mh *MessageHandle) UnregisterNode() {
	mh.nodeLocks.Delete(info.NodeID)
	mh.nodeConns.Delete(info.NodeID)
	close(mh.KeepaliveChannel[info.NodeID])
	delete(mh.KeepaliveChannel, info.NodeID)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by drcwr** [comment]
![closenilchanlog](https://user-images.githubusercontent.com/5842099/77649648-2dfc0700-6fa5-11ea-8088-fa3d3d07adbf.png)
![closenilchan](https://user-images.githubusercontent.com/5842099/77649668-33f1e800-6fa5-11ea-8d95-1a03032cf148.png)

**Comment by drcwr** [comment]
@fisherxu hi,Could you help me?I don't understand this code.

> In func (mh *MessageHandle) OnRegister(connection conn.Connection) 

```
	if _, ok := mh.KeepaliveChannel[nodeID]; !ok {
		mh.KeepaliveChannel[nodeID] = make(chan struct{}, 1)
	}
```
does it need to add return,when ok is true?
```
if ok {
return 
}
```
this is full code.
```
// OnRegister register node on first connection
func (mh *MessageHandle) OnRegister(connection conn.Connection) {
	nodeID := connection.ConnectionState().Headers.Get("node_id")
	projectID := connection.ConnectionState().Headers.Get("project_id")

	if _, ok := mh.KeepaliveChannel[nodeID]; !ok {
		mh.KeepaliveChannel[nodeID] = make(chan struct{}, 1)
	} else {
               return // need to add ?
        }

	io := &hubio.JSONIO{Connection: connection}
	go mh.ServeConn(io, &model.HubInfo{ProjectID: projectID, NodeID: nodeID})
}
```
Thank you!

**Comment by drcwr** [comment]
![the relationship between Connection and KeepaliveChan](https://user-images.githubusercontent.com/5842099/77872693-4a849180-727a-11ea-84b4-7e1b40cccf3f.png)

**Comment by GsssC** [comment]
Yes, it looks like it is going to be happened when network is bad.In a short time, MessageHandler calls twice OnRegister.For mh.KeepaliveChannel[nodeIP], idealy it should be "make close make close". But for now , it is "make 'make fails' close close", then causes the bug.

Just like #1571 shows.
