### ISSUE TITLE
HA support of CloudCore

### ISSUE THREAD

**Issue by dingyin** [kubeedge/kubeedge#1560]
**What would you like to be added/modified**:

CloudCore is not deployed as a single instance. Ideally it should be HA. So we may do it in two steps:
1. Hot standby
2. Deploy a cluster of CloudCore 

To be implemented for alpha in v1.3

- [x] Add leader election in CloudCore
- [ ] Add healthcheck method to CloudCore for integration with LB, to tell which instance is currently active
- [ ] Add LB for multiple instances

To be implemented for beta
- [ ] Make CloudCore Stateless, ref: https://github.com/kubeedge/kubeedge/issues/1444

**Why is this needed**:

**Comment by kevin-wangzefeng** [comment]
Reopening since the whole plan is not yet complete

**Comment by kevin-wangzefeng** [comment]
![image](https://user-images.githubusercontent.com/6914660/118746925-a7cb1000-b88b-11eb-9649-b10eae17cea9.png)

**Comment by kevin-wangzefeng** [comment]
![active-active-ha-for-cloudcore](https://user-images.githubusercontent.com/6914660/118747087-f4165000-b88b-11eb-8eef-0125f463468a.PNG)

**Comment by kevin-wangzefeng** [comment]
Full design proposal will be submitted in a PR.

**Comment by joker-joker-joker** [comment]
What is the difference between active-standby and active-active model? I find a article, https://blog.xuite.net/tw.nway/twblog/175386398, is this correct?

**Comment by sdghchj** [comment]
How if cloudcore runs in containers ?

**Comment by Rachel-Shao** [comment]
@fisherxu   Is there any docs about cloudcore multi-instance deployment? I can implement ha in hot-standby mode according to the relevant pr tips, but I can't implement multi-instance mode. I use keepalived. Do I need to use other LoadBalancer?
