### ISSUE TITLE
Metrics at edge 

### ISSUE THREAD

**Issue by dingyin** [kubeedge/kubeedge#1561]
**What would you like to be added/modified**:

- Support metrics-server in cloud
- Integrated cadvisor in edge
         *Need to investigate if this would make footprint increase much
- Whether to expose port in edge
         * Pros: no need to send all data to cloud
         * Need to deal with authn (and authz?)

**Why is this needed**:

**Comment by kevin-wangzefeng** [comment]
Ref: https://github.com/kubeedge/kubeedge/issues/541

**Comment by shubhamgupta2956** [comment]
Hey,
I am a sophomore at IIT Roorkee. I am willing to get mentored for this issue for the Community Bridge program. Can you please help me in getting started with it?
Thanks

**Comment by fisherxu** [comment]
@shubhamgupta2956 Could you please send a resume？

**Comment by shubhamgupta2956** [comment]
Yeah sure. Can I share it here or should I share it on slack?

**Comment by fisherxu** [comment]
Just send to my email. :)

**Comment by GsssC** [comment]
Hellow, I am a first-year graduate student of software college of zhejiang university. I'm familiar with kubeedge and am willing to get mentored for this Community Bridge program. 
Thx

**Comment by ls889** [comment]
Hey！
I am a first-year graduate student from ZJU, majoring in software engineering. I'm familiar with kubeedge and glad to get mentored for this Community Bridge program.
Thanks!

**Comment by Poor12** [comment]
Hello, I am also a first-year graduate student of software college of zhejiang university. I'm familiar with kubeedge and metrics-server.We have already realized the adaptation of metrics-server on kubeedge a little and glad to get mentored for this Community Bridge program. Thx

**Comment by fisherxu** [comment]
@GsssC @ls889 Okey, please also send the resume to my email. :)

**Comment by ls889** [comment]
@fisherxu ok!  btw,should I prepare my resume only in English?

**Comment by fisherxu** [comment]
> @fisherxu ok! btw,should I prepare my resume only in English?

Yes sure.

**Comment by benjaminhuo** [comment]
I just open a similar issue https://github.com/kubeedge/kubeedge/issues/1689 . Looks like the requirement is quite similar with this.

Glad to know if KubeEdge has any plan on this feature and I'm happy to participate in the development
