### ISSUE TITLE
edgecore 1.2.1 crashes after a few hours on pi4

### ISSUE THREAD

**Issue by xiedidan** [kubeedge/kubeedge#1571]
**What happened**:
After deploying 1.2.1 to both cloud and edge side (2 pi4s with latest raspbian), we have observed the following two kinds of failure reports from edgecore:  
```
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]: I0330 12:09:30.616069   27714 proxy.go:330] [L4 Proxy] proxy process svcs : 14 resource: namespace/servicelist/service
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]: I0330 12:09:30.616144   27714 proxy.go:339] [L4 Proxy] proxy process svc : update,nsq.queue-nsq-nsqd-exporter
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]: panic: runtime error: index out of range [1] with length 1
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]: goroutine 74 [running]:
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]: github.com/kubeedge/kubeedge/edgemesh/pkg/proxy.updateServer(0x5660800, 0x1b, 0x573fa98, 0x0, 0x2, 0x573faa0, 0x0)
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]:         /root/codes/src/github.com/kubeedge/kubeedge/edgemesh/pkg/proxy/proxy.go:457 +0x53c
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]: github.com/kubeedge/kubeedge/edgemesh/pkg/proxy.MsgProcess(0x5cfeed0, 0x24, 0x58217a0, 0x24, 0x29a151fa, 0x171, 0x5bd6780, 0x7, 0x0, 0x583ab70, ...)
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]:         /root/codes/src/github.com/kubeedge/kubeedge/edgemesh/pkg/proxy/proxy.go:359 +0x50c
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]: github.com/kubeedge/kubeedge/edgemesh/pkg.(*EdgeMesh).Start(0x57b10c0)
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]:         /root/codes/src/github.com/kubeedge/kubeedge/edgemesh/pkg/module.go:60 +0x184
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]: created by github.com/kubeedge/beehive/pkg/core.StartModules
Mar 30 12:09:30 raspberrypi-192 edgecore[27714]:         /root/codes/src/github.com/kubeedge/kubeedge/staging/src/github.com/kubeedge/beehive/pkg/core/core.go:23 +0x114
Mar 30 12:09:30 raspberrypi-192 systemd[1]: edgecore.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 30 12:09:30 raspberrypi-192 systemd[1]: edgecore.service: Failed with result 'exit-code'.
```
```
Mar 27 08:35:38 raspberrypi edgecore[24938]: I0327 08:35:38.289006   24938 metaclient.go:114] send sync message default/nodestatus/pi-ncs-2 successed and response: {{4d35afb6-4d97-41f3-b2d1-61f53ff79e9b 293c6295-6574-4d40-967d-0fd46ddd1b06 1585298138288  false} {edged meta response default/nodestatus/pi-ncs-2
Mar 27 08:35:38 raspberrypi edgecore[24938]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 27 08:35:38 raspberrypi edgecore[24938]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1fe5180]
Mar 27 08:35:38 raspberrypi edgecore[24938]: goroutine 36327 [running]:
Mar 27 08:35:38 raspberrypi edgecore[24938]: github.com/kubeedge/kubeedge/edge/pkg/edgehub/clients/wsclient.(*WebSocketClient).Send(0x506a1d0, 0x54fafc0, 0x24, 0x0, 0x0, 0x1b20fa26, 0x171, 0x0, 0x0, 0x1, ...)
Mar 27 08:35:38 raspberrypi edgecore[24938]:         /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/clients/wsclient/websocket.go:94 +0x48
Mar 27 08:35:38 raspberrypi edgecore[24938]: github.com/kubeedge/kubeedge/edge/pkg/edgehub.(*EdgeHub).sendToCloud(0x4894660, 0x54fafc0, 0x24, 0x0, 0x0, 0x1b20fa26, 0x171, 0x0, 0x0, 0x1, ...)
Mar 27 08:35:38 raspberrypi edgecore[24938]:         /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/process.go:127 +0x50
Mar 27 08:35:38 raspberrypi edgecore[24938]: github.com/kubeedge/kubeedge/edge/pkg/edgehub.(*EdgeHub).routeToCloud(0x4894660)
Mar 27 08:35:38 raspberrypi edgecore[24938]:         /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/process.go:171 +0x114
Mar 27 08:35:38 raspberrypi edgecore[24938]: created by github.com/kubeedge/kubeedge/edge/pkg/edgehub.(*EdgeHub).Start
Mar 27 08:35:38 raspberrypi edgecore[24938]:         /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/edgehub.go:86 +0x14c
```
They'll happen in a few hours after restarting edgecore.  
We are using pre-built packages from release page.  
However, x86 edgecore doesn't crash...  

Even wrose, after restarting edgecore, the task pods are automatically removed from the k8s master. We couldn't keep tasks running even with a client watchdog.  

**What you expected to happen**:
edgecore doesn't crash on pi4, just like the x86 version  

**How to reproduce it (as minimally and precisely as possible)**:
just deploy cloud to internet, start edgecore on pi4 and wait for a few hours  

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.2.1  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): 1.2.1
- Hardware configuration (e.g. `lscpu`): raspberry pi4 4GB version
- OS (e.g. `cat /etc/os-release`): PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"  
- Kernel (e.g. `uname -a`): Linux raspberrypi-192 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
- Go version (e.g. `go version`): 
- Others:

**Comment by kevin-wangzefeng** [comment]
To keep pods stay on the node (not delete from control plane), when node is disconneted, you would need to manually add toleration config to the pods with infinite tolerationSeconds, or change defaultUnreachableTolerationSeconds to infinite.

Xref:
- https://v1-17.docs.kubernetes.io/docs/concepts/configuration/taint-and-toleration/#example-use-cases

- https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#toleration-v1-core

**Comment by xiedidan** [comment]
@kevin-wangzefeng Thanks, after updating tolerationSeconds the pods stay when edgecore restarts.  
That enables us to use watchdog to keep tasks working.
