### ISSUE TITLE
cloudcore panic after running a few hours.

### ISSUE THREAD

**Issue by Toper2035** [kubeedge/kubeedge#1575]
**What happened**:
cloudcore panic and exist after running a few hours.

**What you expected to happen**:
no panic

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
cloudcore logs:
I0331 12:10:09.569375       1 upstream.go:161] dispatch message ID: c815f84b-3913-4089-97ae-ca69e7c5e36d
I0331 12:10:09.569395       1 util.go:88] The resource type is nodestatus, 3
I0331 12:10:09.569410       1 upstream.go:169] message: c815f84b-3913-4089-97ae-ca69e7c5e36d, resource type is: nodestatus
I0331 12:10:09.569423       1 upstream.go:171] message: c815f84b-3913-4089-97ae-ca69e7c5e36d, operation type is: update
I0331 12:10:09.569443       1 upstream.go:332] message: c815f84b-3913-4089-97ae-ca69e7c5e36d, operation is: update, and resource is node/edge-hw/default/nodestatus/edge-hw
I0331 12:10:09.569552       1 util.go:113] The resource name is edge-hw, 4
I0331 12:10:11.144834       1 messagehandler.go:217] event received for node edge-vm id: 03eaa465-41d6-4921-a5df-30471781095d, parent_id: 7109d392-dbc8-41a1-9deb-3a6e6d872b1a, group: meta, source: edged, resource: node/edge-vm/default/nodestatus/edge-vm, operation: update, content: map[ExtendResources:<nil> Status:map[addresses:[map[address:172.105.213.135 type:InternalIP] map[address:li1867-135.members.linode.com type:Hostname]] allocatable:map[cpu:2 memory:3689Mi pods:110] capacity:map[cpu:2 memory:3789Mi pods:110] conditions:[map[lastHeartbeatTime:2020-03-31T12:10:11Z lastTransitionTime:2020-03-31T12:10:11Z message:edge is posting ready status reason:EdgeReady status:True type:Ready]] daemonEndpoints:map[kubeletEndpoint:map[Port:%!s(float64=0)]] nodeInfo:map[architecture:amd64 bootID: containerRuntimeVersion:remote://1.13.1 kernelVersion:3.10.0-1062.el7.x86_64 kubeProxyVersion: kubeletVersion:v1.17.1-kubeedge-v1.2.1-dirty machineID: operatingSystem:linux osImage:CentOS Linux 7 (Core) systemUUID:] phase:Running] UID:38796d14-1df3-11e8-8e5a-286ed488f209]
I0331 12:10:11.145145       1 upstream.go:161] dispatch message ID: 03eaa465-41d6-4921-a5df-30471781095d
I0331 12:10:11.145179       1 util.go:88] The resource type is nodestatus, 3
I0331 12:10:11.145196       1 upstream.go:169] message: 03eaa465-41d6-4921-a5df-30471781095d, resource type is: nodestatus
I0331 12:10:11.145211       1 upstream.go:171] message: 03eaa465-41d6-4921-a5df-30471781095d, operation type is: update
I0331 12:10:11.145239       1 upstream.go:332] message: 03eaa465-41d6-4921-a5df-30471781095d, operation is: update, and resource is node/edge-vm/default/nodestatus/edge-vm
I0331 12:10:11.145385       1 util.go:113] The resource name is edge-vm, 4
I0331 12:10:16.132252       1 downstream.go:117] there are 0 nodes need to sync config map, operation: MODIFIED
I0331 12:10:18.676237       1 messagehandler.go:111] Keepalive message received from node: edge-vm
I0331 12:10:18.676314       1 messagehandler.go:159] Node edge-vm is still alive
I0331 12:10:19.174357       1 messagehandler.go:111] Keepalive message received from node: edge-hw
I0331 12:10:19.174428       1 messagehandler.go:159] Node edge-hw is still alive
I0331 12:10:19.588951       1 messagehandler.go:217] event received for node edge-hw id: 57619a24-a959-46e3-b2e7-d742d49ebc4c, parent_id: ecbbf28f-40a4-4971-b6b8-c7d6743c1ee7, group: meta, source: edged, resource: node/edge-hw/default/nodestatus/edge-hw, operation: update, content: map[ExtendResources:<nil> Status:map[addresses:[map[address:10.121.140.200 type:InternalIP] map[address:localhost.localdomain type:Hostname]] allocatable:map[cpu:4 memory:3574Mi pods:110] capacity:map[cpu:4 memory:3674Mi pods:110] conditions:[map[lastHeartbeatTime:2020-03-31T12:10:20Z lastTransitionTime:2020-03-31T12:10:20Z message:edge is posting ready status reason:EdgeReady status:True type:Ready]] daemonEndpoints:map[kubeletEndpoint:map[Port:%!s(float64=0)]] nodeInfo:map[architecture:amd64 bootID: containerRuntimeVersion:remote://1.13.1 kernelVersion:3.10.0-957.el7.x86_64 kubeProxyVersion: kubeletVersion:v1.17.1-kubeedge-v1.2.1-dirty machineID: operatingSystem:linux osImage:CentOS Linux 7 (Core) systemUUID:] phase:Running] UID:38796d14-1df3-11e8-8e5a-286ed488f209]
I0331 12:10:19.589074       1 upstream.go:161] dispatch message ID: 57619a24-a959-46e3-b2e7-d742d49ebc4c
I0331 12:10:19.589085       1 util.go:88] The resource type is nodestatus, 3
I0331 12:10:19.589092       1 upstream.go:169] message: 57619a24-a959-46e3-b2e7-d742d49ebc4c, resource type is: nodestatus
I0331 12:10:19.589102       1 upstream.go:171] message: 57619a24-a959-46e3-b2e7-d742d49ebc4c, operation type is: update
I0331 12:10:19.589120       1 upstream.go:332] message: 57619a24-a959-46e3-b2e7-d742d49ebc4c, operation is: update, and resource is node/edge-hw/default/nodestatus/edge-hw
I0331 12:10:19.589175       1 util.go:113] The resource name is edge-hw, 4
I0331 12:10:21.158191       1 messagehandler.go:217] event received for node edge-vm id: 1e9bc895-0e57-4627-88b7-d753ff61ac6a, parent_id: 7109d392-dbc8-41a1-9deb-3a6e6d872b1a, group: meta, source: edged, resource: node/edge-vm/default/nodestatus/edge-vm, operation: update, content: map[ExtendResources:<nil> Status:map[addresses:[map[address:172.105.213.135 type:InternalIP] map[address:li1867-135.members.linode.com type:Hostname]] allocatable:map[cpu:2 memory:3689Mi pods:110] capacity:map[cpu:2 memory:3789Mi pods:110] conditions:[map[lastHeartbeatTime:2020-03-31T12:10:21Z lastTransitionTime:2020-03-31T12:10:21Z message:edge is posting ready status reason:EdgeReady status:True type:Ready]] daemonEndpoints:map[kubeletEndpoint:map[Port:%!s(float64=0)]] nodeInfo:map[architecture:amd64 bootID: containerRuntimeVersion:remote://1.13.1 kernelVersion:3.10.0-1062.el7.x86_64 kubeProxyVersion: kubeletVersion:v1.17.1-kubeedge-v1.2.1-dirty machineID: operatingSystem:linux osImage:CentOS Linux 7 (Core) systemUUID:] phase:Running] UID:38796d14-1df3-11e8-8e5a-286ed488f209]
I0331 12:10:21.158436       1 upstream.go:161] dispatch message ID: 1e9bc895-0e57-4627-88b7-d753ff61ac6a
I0331 12:10:21.158462       1 util.go:88] The resource type is nodestatus, 3
I0331 12:10:21.158481       1 upstream.go:169] message: 1e9bc895-0e57-4627-88b7-d753ff61ac6a, resource type is: nodestatus
I0331 12:10:21.158498       1 upstream.go:171] message: 1e9bc895-0e57-4627-88b7-d753ff61ac6a, operation type is: update
I0331 12:10:21.158545       1 upstream.go:332] message: 1e9bc895-0e57-4627-88b7-d753ff61ac6a, operation is: update, and resource is node/edge-vm/default/nodestatus/edge-vm
I0331 12:10:21.158684       1 util.go:113] The resource name is edge-vm, 4
panic: close of closed channel

goroutine 54509 [running]:
github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler.(*MessageHandle).HandleServer(0xc0008d4620, 0xc001b6ece0, 0x185ff80, 0xc001b6eca0)
	/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler/messagehandler.go:125 +0x34a
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/mux.(*MessageMux).dispatch(0xc0001d89e0, 0xc000ebbc90, 0x185ff80, 0xc001b6eca0, 0x13f2f01, 0xc000ebbc90)
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/mux/mux.go:86 +0x15c
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/mux.(*MessageMux).ServeConn(0xc0001d89e0, 0xc000ebbc90, 0x185ff80, 0xc001b6eca0)
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/mux/mux.go:108 +0x66
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).handleMessage(0xc0008b6360)
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn/ws.go:149 +0x236
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).ServeConn
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn/ws.go:51 +0x125

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
cloudcore/edgecore --version
1.2.1

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel Core Processor (Skylake, IBRS)
Stepping:              3
CPU MHz:               2294.610
BogoMIPS:              4589.22
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 ibpb ibrs arat spec_ctrl

- OS (e.g. `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux node4 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Go version (e.g. `go version`): 
1.13

- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
1.2.1

- Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
座：                 1
NUMA 节点：         1
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              55
型号名称：        Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz
步进：              9
CPU MHz：             1332.840
CPU max MHz:           2415.7000
CPU min MHz:           1332.8000
BogoMIPS：            3993.60
虚拟化：           VT-x
L1d 缓存：          24K
L1i 缓存：          32K
L2 缓存：           1024K
NUMA 节点0 CPU：    0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer rdrand lahf_lm 3dnowprefetch epb ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat spec_ctrl intel_stibp

- OS (e.g. `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Go version (e.g. `go version`): 
1.13

- Others:

**Comment by chenjie222** [comment]
also encountered the same problem. My cloudcore is centos system, edgecore is Ububtu system,
Can you tell me how you solved it

```
I0401 21:47:30.315415    6790 messagehandler.go:217] event received for node halfbaker id: 860bd3ca-0307-4da1-9084-aa8bb46d4485, parent_id: 37670d09-f866-4cc8-9886-3e676ba8441a, group: meta, source: edged, resource: node/halfbaker/default/nodestatus/halfbaker, operation: update, content: map[ExtendResources:<nil> Status:map[addresses:[map[address:10.110.130.178 type:InternalIP] map[address:halfbaker type:Hostname]] allocatable:map[cpu:8 memory:23881Mi pods:110] capacity:map[cpu:8 memory:23981Mi pods:110] conditions:[map[lastHeartbeatTime:2020-04-01T13:45:32Z lastTransitionTime:2020-04-01T13:45:32Z message:edge is posting ready status reason:EdgeReady status:True type:Ready]] daemonEndpoints:map[kubeletEndpoint:map[Port:%!s(float64=0)]] nodeInfo:map[architecture:amd64 bootID: containerRuntimeVersion:remote://19.3.5 kernelVersion:5.3.0-45-generic kubeProxyVersion: kubeletVersion:v1.17.1-kubeedge-v0.0.0-master+$Format:%h$ machineID: operatingSystem:linux osImage:Ubuntu 18.04.4 LTS systemUUID:] phase:Running] UID:38796d14-1df3-11e8-8e5a-286ed488f209]
panic: close of closed channel

goroutine 2668 [running]:
github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler.(*MessageHandle).HandleServer(0xc000b1a000, 0xc0076d3240, 0x18ce9a0, 0xc0076d3200)
	/data/go/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler/messagehandler.go:125 +0x350
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/mux.(*MessageMux).dispatch(0xc0002a2c00, 0xc0079777e0, 0x18ce9a0, 0xc0076d3200, 0x144e701, 0xc0079777e0)
	/data/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/mux/mux.go:86 +0x16c
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/mux.(*MessageMux).ServeConn(0xc0002a2c00, 0xc0079777e0, 0x18ce9a0, 0xc0076d3200)
	/data/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/mux/mux.go:108 +0x67
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).handleMessage(0xc008d7f7a0)
	/data/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn/ws.go:149 +0x236
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).ServeConn
	/data/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/viaduct/pkg/conn/ws.go:51 +0x126
```

**Comment by chenyg0911** [comment]
same problem. +1

**Comment by drcwr** [comment]
This may be #1557
