### ISSUE TITLE
为什么edgecore会 “Failed to get host IP” 

### ISSUE THREAD

**Issue by harmful1980** [kubeedge/kubeedge#1578]
在edgecore的日志中看到如下错误信息
failed to read pod IP from plugin/docker: Couldn't find network status for default/kcs-deployment-7fbb5bb8db-gtp6q through plugin: invalid network status for

 Failed to get host IP: failed to get network interface: eth0 err:route ip+net: no such network interface
请问一下，出现这个错误的原因是什么？谢谢

**Comment by harmful1980** [comment]
忘记说了，我用的版本是1.17.1

**Comment by fisherxu** [comment]
EdgeCore配置里有`interfaceName`,默认是eth0，如果你的环境上没有eth0，换成其他的网卡就行
