### ISSUE TITLE
Scheduling Problem

### ISSUE THREAD

**Issue by SemiLavender** [kubeedge/kubeedge#1585]
# Scheduling Problem
When the edge node loses contact, K8s whether it will dispatch apps of the edge node to other edge nodes？

**Comment by fisherxu** [comment]
KubeEdge uses the k8s scheduler without any modification, Whether to dispatch apps to other edge nodes depending the strategy you configure. You can configure whether to dispatch to other nodes according to your needs.

Ref: https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#toleration-v1-core

https://v1-17.docs.kubernetes.io/docs/concepts/configuration/taint-and-toleration/#example-use-cases
