### ISSUE TITLE
Realign code structure to incorporate cloud part

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#159]
**What would you like to be added**:
The code structuring needs to be changed in order to add the cloud part modules.

**Why is this needed**:
Code modularity will help in easy maintenance once the cloud part is opensourced.
This will help reusing common framework like beehive , maintaing a common vendor package for both cloud and edge modules.

**Comment by rohitsardesai83** [comment]
we will have three modules
Proposed structure : 

kubedge
   - edge  // will contain all current kubeedge code
   - cloud // will contain all cloud components ( cloudhub , controller etc )
   - common // will contain all common code ( e.g beehive )
   - vendor // will contain all 3rd part libraries needed by above modules.

**Comment by m1093782566** [comment]
+1
