### ISSUE TITLE
Support more flexible deviceprofile config for Mapper module 

### ISSUE THREAD

**Issue by bretagne-peiqi** [kubeedge/kubeedge#1591]
**What would you like to be added/modified**:

We hope to make DeviceModels a general part, as devicemodels is bind with one kind of device, 
while deviceInstances and propertyVisitors are for a specific device of one kind.

In case of multiple deviceInstances and multiple propertyVistors, we can't figure out which propertyVistor relates to which deviceInstance for the current config format. So we need to add attribute "deviceinstanceId"  in propertyVistor part. 

![WechatIMG2](https://user-images.githubusercontent.com/5621794/79031613-91577d00-7bd2-11ea-8053-f5b672e5f756.png)

**Why is this needed**:

This consideration is from production needs. In traditional PLC data collection related issues, we consider efficiency and simplicity.

**Comment by bretagne-peiqi** [comment]
besides, we hope to add sample frequency config option for attribues, like cycle 30000

**Comment by luogangyi** [comment]
We have discuessed this topic with kubeedge team and other iiot experts serveral times.
Now, we have reach some consensus, please see the proposal.
