### ISSUE TITLE
Auto inject configmap for device mappers

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubeedge/kubeedge#1595]
**What would you like to be added/modified**:
For a device mapper, currently the configmap would be automatically generated by device controller, but users need to manually indicated the configmap name in podSpec, which doesn't make sence.

We can simply make admission controller to auto inject devicemapper relevant configmap  to podSpec.

**Why is this needed**:

Ref: https://github.com/kubeedge/kubeedge/issues/1279

**Comment by luogangyi** [comment]
@kevin-wangzefeng I don't think this would be easy to accomplish.
mapper is a normal deployment, no special property could be used to determine whether it is a mapper.
If we demand all mapper  labeled xxx-mapper, we still have to incercepts all deployments or pods first.
