### ISSUE TITLE
Expose --node-labels and --register-with-taints in EdgeCore config

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubeedge/kubeedge#1599]
**What would you like to be added/modified**:
expose `--node-labels` and `--register-with-taints` in EdgeCore Config
**Why is this needed**:
`--node-labels` and `--register-with-taints` are very useful configs when setting up a new node. We should support them in EdgeCore Config

**Comment by kevin-wangzefeng** [comment]
Part of https://github.com/kubeedge/kubeedge/issues/1171

**Comment by joshuafc** [comment]
+1, this feature is very useful. When edge device deploy, we can directly add localization, device type and role to labels. Rather than record the node name, and append these information at data center.

**Comment by larryck** [comment]
@kevin-wangzefeng hello, this feature will be greatly useful for me. What's the status of it? Will it be available by the next release?

**Comment by huapox** [comment]
/reopen
+1
