### ISSUE TITLE
nvidia-device-plugin daemonSet pod stuck in pending status

### ISSUE THREAD

**Issue by plochon** [kubeedge/kubeedge#1602]
**What happened**:

```
$ kubectl get pod -o wide --all-namespaces|grep nvidia-device-plugin
kube-system            nvidia-device-plugin-daemonset-tzrh8        0/1     Pending             0          5m42s   <none>       pl-ecs-01             <none>           <none>
```

```
$ kubectl describe pod nvidia-device-plugin-daemonset-tzrh8 --namespace=kube-system
Name:                 nvidia-device-plugin-daemonset-tzrh8
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 pl-ecs-01/
Labels:               controller-revision-hash=7854d65948
                      name=nvidia-device-plugin-ds
                      pod-template-generation=1
Annotations:          scheduler.alpha.kubernetes.io/critical-pod:
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        DaemonSet/nvidia-device-plugin-daemonset
Containers:
  nvidia-device-plugin-ctr:
    Image:        nvidia/k8s-device-plugin:1.0.0-beta4
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pjfbh (ro)
Conditions:
  Type           Status
  PodScheduled   True
Volumes:
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:
  default-token-pjfbh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pjfbh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
                 nvidia.com/gpu:NoSchedule
Events:
  Type    Reason     Age        From               Message
  ----    ------     ----       ----               -------
  Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned kube-system/nvidia-device-plugin-daemonset-tzrh8 to pl-ecs-01
```
```
$ find /var/lib/kubelet/device-plugins
/var/lib/kubelet/device-plugins
/var/lib/kubelet/device-plugins/kubelet.sock
/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint

$ find /var/run/secrets
find: ‘/var/run/secrets’: No such file or directory
```

edgecore log excerpt =
```
edged.go:1094] start update pod [nvidia-device-plugin-daemonset-tzrh8]
edged.go:695] worker [1] get pod addition item [nvidia-device-plugin-daemonset-tzrh8]
edged.go:764] start to consume added pod [nvidia-device-plugin-daemonset-tzrh8]
edged.go:1106] success update pod is &Pod{ObjectMeta:{nvidia-device-plugin-daemonset-tzrh8 nvidia-device-plugin-daemonset- kube-system /api/v1/namespaces/kube-system/pods/nvidia-device-plugin-daemonset-tzrh8
reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "device-plugin"
reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-pjfbh" 
edged_volumes.go:54] Using volume plugin "kubernetes.io/empty-dir" to mount wrapped_default-token-pjfbh
secret.go:195] Couldn't get secret kube-system/default-token-pjfbh: get secret from metaManager failed, err: timed out waiting for the condition
record.go:24] Warning FailedMount MountVolume.SetUp failed for volume "default-token-pjfbh" : get secret from metaManager failed, err: timed out waiting for the condition
edged.go:776] Unable to mount volumes for pod "nvidia-device-plugin-daemonset-tzrh8_kube-system(9a60f0e1-6e45-46c1-a8d3-a72f5d70cc78)": unmounted volumes=[default-token-pjfbh], unattached volumes=[device-plugin default-token-pjfbh]: timed out waiting for the condition; skipping pod
```
Full log =
[edgecore.log](https://github.com/kubeedge/kubeedge/files/4504877/edgecore.log)

**What you expected to happen**:
Pod in Running status

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl apply -f https://github.com/NVIDIA/k8s-device-plugin/blob/master/nvidia-device-plugin.yml
`

**Anything else we need to know?**:

**Environment**:

**CloudSide Environment**:
- arch x86_64
- Ubuntu 16.04.6 LTS
- k3s version v1.17.4+k3s1
- KubeEdge v1.2.1
- go version go1.12.17

**EdgeSide Environment**:
- arch x86_64
- Ubuntu 18.04.4 LTS
- KubeEdge v1.2.1
- go version go1.12.17
with edgecore.yaml containing 
```
devicePluginEnabled: true
gpuPluginEnabled: true
```

**Comment by bitvijays** [comment]
https://github.com/kubeedge/kubeedge/issues/1574 -- This might be provide some information.

Also, (I might be wrong). It seems that the `nvidia-device-plugin` is for Nvidia Tesla devices, where as Jetson Nano/ TX2 implement tegra.

Also, what I tried was using [Nvidia L4T-Base](ttps://ngc.nvidia.com/catalog/containers/nvidia:l4t-base) to design the application and push that as the container on the Edge / Jetson Nano/ TX2.  This was working fine.

This [k8s-dt-node-labeller](https://github.com/adaptant-labs/k8s-dt-node-labeller) might also help.

Again, the above are the rough thoughts, I did got a change to test it fully.

**Comment by plochon** [comment]
I confirm I'm trying to run nvidia-device-plugin on x86 platform with Tesla device with GPU drivers and nvidia-docker2 package properly installed (`docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi` works fine)

**Comment by kevin-wangzefeng** [comment]
Did you succeed deploying other pods to an edge node?
It seems failed syncing default token from cloud.
```log
Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: E0420 17:16:27.714485    1122 metaclient.go:118] send sync message kube-system/secret/default-token-pjfbh failed, error:timeout to get response, retries: 2
Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: E0420 17:16:27.714514    1122 secret.go:195] Couldn't get secret kube-system/default-token-pjfbh: get secret from metaManager failed, err: timed out waiting for the condition
Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: I0420 17:16:27.714534    1122 record.go:24] Warning FailedMount MountVolume.SetUp failed for volume "default-token-pjfbh" : get secret from metaManager failed, err: timed out waiting for the condition
Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: E0420 17:16:27.714570    1122 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/2c615eb8-5b87-4194-8c9b-b007635e776e-default-token-pjfbh\" (\"2c615eb8-5b87-4194-8c9b-b007635e776e\")" failed. No retries permitted until 2020-04-20 17:18:29.714545365 +0200 CEST m=+25790.947410333 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"default-token-pjfbh\" (UniqueName: \"kubernetes.io/secret/2c615eb8-5b87-4194-8c9b-b007635e776e-default-token-pjfbh\") pod \"svclb-traefik-tkftb\" (UID: \"2c615eb8-5b87-4194-8c9b-b007635e776e\") : get secret from metaManager failed, err: timed out waiting for the condition"
Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: I0420 17:16:27.714682    1122 process.go:406] ########## process get: req[{Header:{ID:0fe52bd5-0b04-47dd-a8b3-e8f1027a66ea ParentID: Timestamp:1587395667703 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:query Resource:kube-system/secret/default-token-pjfbh} Content:<nil>}], resp[{Header:{ID: ParentID: Timestamp:0 ResourceVersion: Sync:false} Router:{Source: Group: Operation: Resource:} Content:<nil>}], err[timeout to get response]
Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: E0420 17:16:27.714711    1122 process.go:408] remote query failed: timeout to get response
```

**Comment by plochon** [comment]
I succeeded in deploying nginx and a test application on an edgecore node but these applications do not use secrets. You can also see in the log the pod svclb-traefik (k3s related) which is also failing in retrieving secret.

**Comment by plochon** [comment]
Attached is the full log of edgecore, we can see that 2 pods are running fine and 2 others pods are stuck in Pending status and are not able to get secret. 
`Warning FailedMount MountVolume.SetUp failed for volume "default-token-pjfbh" : get secret from metaManager failed, err: timed out waiting for the condition`
![pods](https://user-images.githubusercontent.com/61243441/80492218-feee0200-8963-11ea-80b8-5bcfece1416b.png)
We can see that the 2 pods in Pending status are in kube-system namespace whereas the 2 pods in Running status are in default namespace. 
[edgecore.zip](https://github.com/kubeedge/kubeedge/files/4545991/edgecore.zip)

**Comment by GsssC** [comment]
> Attached is the full log of edgecore, we can see that 2 pods are running fine and 2 others pods are stuck in Pending status and are not able to get secret.
> `Warning FailedMount MountVolume.SetUp failed for volume "default-token-pjfbh" : get secret from metaManager failed, err: timed out waiting for the condition`
> ![pods](https://user-images.githubusercontent.com/61243441/80492218-feee0200-8963-11ea-80b8-5bcfece1416b.png)
> We can see that the 2 pods in Pending status are in kube-system namespace whereas the 2 pods in Running status are in default namespace.
> [edgecore.zip](https://github.com/kubeedge/kubeedge/files/4545991/edgecore.zip)
This is a bug shown in #1700 and fix by #1708 .

But for failing of getting secret from meta-manager, I guess you once deleted the edgecore.db, so cloudhub thought this secret had been successfully sent to edge, and revented this secret from being distributed, unless secret was updated. According to [reliable-message](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/reliable-message-delivery.md).

If you have not deleted, I also meet a bug and am working on figuring out the reason 
```
I0527 10:33:27.787393     660 metaclient.go:121] send sync message kube-system/configmap/kube-proxy successed and response: {{7e8c20f0-a546-4375-9223-10ce637cead9 3d2bdbb3-84a1-438d-a8fa-aa1aabd698b5 1590546807787  false} {metaManager meta response kube-system/configmap/kube-proxy} [{"data":{"config.conf":"apiVersion: kubeproxy.config.k8s.io/v1alpha1\nbindAddress: 0.0.0.0\nclientConnection:\n  acceptContentTypes: \"\"\n  burst: 0\n  contentType: \"\"\n  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf\n  qps: 0\nclusterCIDR: 192.168.0.0/16\nconfigSyncPeriod: 0s\nconntrack:\n  maxPerCore: null\n  min: null\n  tcpCloseWaitTimeout: null\n  tcpEstablishedTimeout: null\nenableProfiling: false\nhealthzBindAddress: \"\"\nhostnameOverride: \"\"\niptables:\n  masqueradeAll: false\n  masqueradeBit: null\n  minSyncPeriod: 0s\n  syncPeriod: 0s\nipvs:\n  excludeCIDRs: null\n  minSyncPeriod: 0s\n  scheduler: \"\"\n  strictARP: false\n  syncPeriod: 0s\nkind: KubeProxyConfiguration\nmetricsBindAddress: \"\"\nmode: \"\"\nnodePortAddresses: null\noomScoreAdj: null\nportRange: \"\"\nudpIdleTimeout: 0s\nwinkernel:\n  enableDSR: false\n  networkName: \"\"\n  sourceVip: \"\"","kubeconfig.conf":"apiVersion: v1\nkind: Config\nclusters:\n- cluster:\n    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n    server: https://10.10.102.78:6443\n  name: default\ncontexts:\n- context:\n    cluster: default\n    namespace: default\n    user: default\n  name: default\ncurrent-context: default\nusers:\n- name: default\n  user:\n    tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token"},"metadata":{"creationTimestamp":"2020-04-21T14:50:46Z","labels":{"app":"kube-proxy"},"name":"kube-proxy","namespace":"kube-system","resourceVersion":"193","selfLink":"/api/v1/namespaces/kube-system/configmaps/kube-proxy","uid":"5651c863-c755-4da4-8039-b251efc82470"}}]}
E0527 10:33:27.787825     660 configmap.go:249] Error creating atomic writer: stat /var/lib/edged/pods/25e6f0ea-6364-4bcc-9937-9760b6ec956a/volumes/kubernetes.io~configmap/kube-proxy: no such file or directory
W0527 10:33:27.787944     660 empty_dir.go:392] Warning: Unmount skipped because path does not exist: /var/lib/edged/pods/25e6f0ea-6364-4bcc-9937-9760b6ec956a/volumes/kubernetes.io~configmap/kube-proxy
I0527 10:33:27.787990     660 record.go:24] Warning FailedMount MountVolume.SetUp failed for volume "kube-proxy" : stat /var/lib/edged/pods/25e6f0ea-6364-4bcc-9937-9760b6ec956a/volumes/kubernetes.io~configmap/kube-proxy: no such file or directory
E0527 10:33:27.788073     660 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/configmap/25e6f0ea-6364-4bcc-9937-9760b6ec956a-kube-proxy\" (\"25e6f0ea-6364-4bcc-9937-9760b6ec956a\")" failed. No retries permitted until 2020-05-27 10:35:29.78800891 +0800 CST m=+2477.714534220 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"kube-proxy\" (UniqueName: \"kubernetes.io/configmap/25e6f0ea-6364-4bcc-9937-9760b6ec956a-kube-proxy\") pod \"kube-proxy-gbdgw\" (UID: \"25e6f0ea-6364-4bcc-9937-9760b6ec956a\") : stat /var/lib/edged/pods/25e6f0ea-6364-4bcc-9937-9760b6ec956a/volumes/kubernetes.io~configmap/kube-proxy: no such file or directory"
```

**Comment by plochon** [comment]
> If you have not deleted, I also meet a bug and am working on figuring out the reason

Do you mean you want to make some tests on my environment ?

**Comment by GsssC** [comment]
@plochon #1736 ,No~ I mean my bug is similar with you, may be the same reason.

**Comment by plochon** [comment]
@GsssC OK thank you, really interested in a fix.

**Comment by plochon** [comment]
I tried [fix using same namespace while syncPodStatus #1708](https://github.com/kubeedge/kubeedge/pull/1708/files/934d4354178e7f412faeb9bfcb1d6e153fc2cc20), backporting it to 1.2.1 code, but my issue is still occuring  ...

**Comment by plochon** [comment]
Howerver I get the same error message in cloudcore log as described in #1700 so it should be the same issue ...
> upstream.go:222] message: fb211cfb-43da-4c07-92df-30a1f2348556, pod not found, namespace: default, name: nvidia-device-plugin-daemonset-chpxl
> upstream.go:222] message: fb211cfb-43da-4c07-92df-30a1f2348556, pod not found, namespace: default, name: svclb-traefik-8cktc
>

**Comment by plochon** [comment]
@GsssC do you know if the v1.3.1 release solves this issue ? 
[kubeedge / CHANGELOG-1.3.md ](https://github.com/kubeedge/kubeedge/blob/master/CHANGELOG-1.3.md)
> • Automatically create kubeedge namespace when creating a secret. 
> • Fix using same namespace while syncPodStatus

**Comment by GsssC** [comment]
- If your bug is that pod containers are running well on the edgenode, but cloudcore still logs messages below, then I can sure the issue is resolved.
> upstream.go:222] message: fb211cfb-43da-4c07-92df-30a1f2348556, pod not found, namespace: default, name: nvidia-device-plugin-daemonset-chpxl
> upstream.go:222] message: fb211cfb-43da-4c07-92df-30a1f2348556, pod not found, namespace: default, name: svclb-traefik-8cktc

- If pod containers are not running at all, then I think may you have ever removed edgecore.db in /var/lib/kubeedge/edgecore.db. BUT not remove sync-crds(which to records whether the resource is sent to edge successfully) in k8s etcd at the same time, then cloudcore rejected the relating resource to be sent to edge.

**Comment by plochon** [comment]
@GsssC 
>    If pod containers are not running at all, then I think may you have ever removed edgecore.db in /var/lib/kubeedge/edgecore.db. BUT not remove sync-crds(which to records whether the resource is sent to edge successfully) in k8s etcd at the same time, then cloudcore rejected the relating resource to be sent to edge.

On the same edge node some pods runs fine (the "default" namespace ones), some others don't run at all (the "kube-system" ones), so do you think it could be related to crds ? we should expect issues with all pods on the node, not some of them ...

**Comment by GsssC** [comment]
@plochon ，do you upgrade to v1.3.1?

**Comment by plochon** [comment]
@GsssC  no not yet, I was also waiting for an upgrade procedure (1.2 to 1.3) on Slack but did not get any answer https://kubeedge.slack.com/archives/CKVUCM5ED/p1589978307074300
Should I stop edgecore/cloudcore, replace the binary, the restart it ? is it enough ?

**Comment by daixiang0** [comment]
@plochon hi, i test with 1.3.0 and it works:
```
kube-system          nvidia-device-plugin-daemonset-48ld8         1/1     Running   0          90s   10.244.0.5   test-control-plane   <none>           <none>
kube-system          nvidia-device-plugin-daemonset-g9sxc         1/1     Running   0          90s   172.17.0.3   edge-node            <none>           <none>
```

**Comment by zhiyxu** [comment]
> Did you succeed deploying other pods to an edge node?
> It seems failed syncing default token from cloud.
> 
> ```
> Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: E0420 17:16:27.714485    1122 metaclient.go:118] send sync message kube-system/secret/default-token-pjfbh failed, error:timeout to get response, retries: 2
> Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: E0420 17:16:27.714514    1122 secret.go:195] Couldn't get secret kube-system/default-token-pjfbh: get secret from metaManager failed, err: timed out waiting for the condition
> Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: I0420 17:16:27.714534    1122 record.go:24] Warning FailedMount MountVolume.SetUp failed for volume "default-token-pjfbh" : get secret from metaManager failed, err: timed out waiting for the condition
> Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: E0420 17:16:27.714570    1122 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/2c615eb8-5b87-4194-8c9b-b007635e776e-default-token-pjfbh\" (\"2c615eb8-5b87-4194-8c9b-b007635e776e\")" failed. No retries permitted until 2020-04-20 17:18:29.714545365 +0200 CEST m=+25790.947410333 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"default-token-pjfbh\" (UniqueName: \"kubernetes.io/secret/2c615eb8-5b87-4194-8c9b-b007635e776e-default-token-pjfbh\") pod \"svclb-traefik-tkftb\" (UID: \"2c615eb8-5b87-4194-8c9b-b007635e776e\") : get secret from metaManager failed, err: timed out waiting for the condition"
> Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: I0420 17:16:27.714682    1122 process.go:406] ########## process get: req[{Header:{ID:0fe52bd5-0b04-47dd-a8b3-e8f1027a66ea ParentID: Timestamp:1587395667703 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:query Resource:kube-system/secret/default-token-pjfbh} Content:<nil>}], resp[{Header:{ID: ParentID: Timestamp:0 ResourceVersion: Sync:false} Router:{Source: Group: Operation: Resource:} Content:<nil>}], err[timeout to get response]
> Apr 20 17:16:27 pl-ecs-01 edgecore[1122]: E0420 17:16:27.714711    1122 process.go:408] remote query failed: timeout to get response
> ```

I've got exactly the same issue in v1.4.0, any latest progress for the issue?

**Comment by daixiang0** [comment]
@zhiyxu please share reproduce steps and env details.
