### ISSUE TITLE
Custom message from CloudCore to EdgeCore

### ISSUE THREAD

**Issue by openedhardware** [kubeedge/kubeedge#1609]
**What would you like to be added/modified**:
I'd like to send a custom message from CloudCore to an edge device.

**Why is this needed**:
Sometimes we have to notice a device to do some action by sending a custom message.
Is there any way to trigger an action(send a message) on a given edge device?

**Comment by plochon** [comment]
I understand that, according to [DeviceTwin documentation page](http://docs.kubeedge.io/en/v1.2.1/modules/edge/devicetwin.html)

> **dealTwinUpdate**: dealTwinUpdate() updates the device twin information for a particular device

can be used to send information from the cloud to the device,
and
> **dealTwinSync**: dealTwinSync() syncs the device twin information to the cloud

can be used to send information from the device to the cloud.

Can anybody confirm ?

**Comment by luogangyi** [comment]
@plochon TwinUpdate/Sync is used to sync device twin property. 
If you add a String property in twin, you can send the msg through update this String propperty.
But your mapper should be able to deal with this msg.
 
Any other way is update configMap which used by mapper, this way is a bit slower to take effect

**Comment by fisherxu** [comment]
Please look at #2558
