### ISSUE TITLE
Stopping edged doesn't kill containers

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#161]
**What happened**:
Deployed an application through cloud. After stopping the edge-core process, the container was still running.

**What you expected to happen**:
After stopping edge core process, all containers managed by edged should be stopped.

**How to reproduce it (as minimally and precisely as possible)**:
1) Start edge-core
2) Deploy an application
3) Stop edge core

cc @rohitsardesai83 @m1093782566

**Comment by Baoqiang-Zhang** [comment]
@sids-b  it's a normal scenarios， stop edged would not kill container.

**Comment by sids-b** [comment]
@Baoqiang-Zhang , i was thinking if we could use something like monit of supervisord for kill pods/containers after edge_core is killed.  Maybe we can think of some design later. Closing this issue for now :)
