### ISSUE TITLE
edge node is not fully registered automatically anymore

### ISSUE THREAD

**Issue by dggonz** [kubeedge/kubeedge#1611]
**What happened**:
I updated both cloudcore and edgecore to git commit c966421. After doing that and restarting clean both cloudcore and edgecore in that order the edge node shows bu the registration is not complete. As the node is not labeled correctly and deployments don't work.

**What you expected to happen**:
I would expect the node to be fully registered as in the edgecore.yaml configuration I have set:
    registerNode: true

**How to reproduce it (as minimally and precisely as possible)**:
compiled both cloudcore and edgecore from git HEAD (commit c966421). delete the previous node from cloudcore side (kubectl delete node kube-edge.cassiopiea.local) and deployments (kubectl delete deployment temperature-mapper). Stopped cloudcore and edgecore. Started cloudcore and then edgecore. The node shows up with "kubectl get nodes". However the labels are not set. 

I manually had to run: 
kubectl  label node kube-edge.cassiopeia.local node-role.kubernetes.io/edge=""
kubectl  label node kube-edge.cassiopeia.local name="kube-edge.cassiopeia.local"

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by fisherxu** [comment]
Is this lable `name="kube-edge.cassiopeia.local"` needed in your environment?

**Comment by kevin-wangzefeng** [comment]
`name=<nodename>` is replaced with `kubernetes.io/hostname=<nodename>`
To stay align with upstream Kubernetes [built-in labels](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#built-in-node-labels)

Ref: The PR changed built-in labels https://github.com/kubeedge/kubeedge/pull/1601/files

**Comment by dggonz** [comment]
Hi,

I had to set it to be equal to the hostnameOverride field of the yaml. Otherwise deployments are not sent to the node running edgecore when I do kubectl create -f deployment.yaml

**Comment by dggonz** [comment]
BTW,

That commit also suggests that a number of labels are being set, which is not the case in my setup. There were no labels at all attached to the node when using:  kubectl get nodes --show-labels

Cheers,
Diego

**Comment by fisherxu** [comment]
![image](https://user-images.githubusercontent.com/28776356/80084986-389cc280-858a-11ea-96e9-048186320a4f.png)
In my env, the labels in nomal except the deleted `name` key. @dggonz

**Comment by dggonz** [comment]
I will give it another go, maybe I did a mistake somewhere

**Comment by dggonz** [comment]
It turns out for some reason the version of edgecore did not make it into my image so I was using an older one. I am going to close this issue assuming it is not there (I cannot say it for sure because edgecore is now crashing on start up). I am going to cut a new bug.
