### ISSUE TITLE
kubeedge fails to deploy to edge node

### ISSUE THREAD

**Issue by dggonz** [kubeedge/kubeedge#1612]
**What happened**:
I updated to version v1.3.0-alpha.0.2+c96642161db763 both the cloud and the edge components. After restarting everything the edge node registers fine, however when I try to deploy an application the pod stays in state  Pending.

**What you expected to happen**:
The pod to start running

**How to reproduce it (as minimally and precisely as possible)**:
1) stop edgecore on the edge node
2) cleanup all state on the cloud side (delete any previous deployments and nodes). 
3) Stop cloudcore on the cloud side
4) Start cloudcore
5) Start edgecore
6) The node will become ready in a few seconds, after that create the deployment. A new pod will be created. But it will remain in the pending state.

**Anything else we need to know?**:
The pod moves to running when I do:
kubectl  label node kube-edge.cassiopeia.local name="kube-edge.cassiopeia.local"
When i do this and then invoque watch kubectl get pods -owide, the Node field will switch to kube-edge.cassiopeia.local and the deployment will happen, after a few seconds the pod is in running state.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by kevin-wangzefeng** [comment]
Could you share the deployment yaml you are using?
Maybe you have some nodeSelector configuration in the yaml.

**Comment by dggonz** [comment]
Should the name: "kube-edge.cassiopeia.local" be replaced with hostname: "kube-edge.cassiopeia.local" ?

apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-mapper
  labels:
    app: temperature
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature
  template:
    metadata:
      labels:
        app: temperature
    spec:
      hostNetwork: true
      nodeSelector:
        name: "kube-edge.cassiopeia.local"
      containers:
      - name: temperature
        image: dggonz/kube-temperature:arm64-v0.0.3
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true

**Comment by fisherxu** [comment]
> nodeSelector:
name: "kube-edge.cassiopeia.local"

In your deployment yaml, you use the `name: "kube-edge.cassiopeia.local"` label, which has been removed now, please use the `kubernetes.io/hostname=EDGE-NODE` label instead.
