### ISSUE TITLE
started edgecore on armv8 error：Cgroup subsystem not mounted: [memory]

### ISSUE THREAD

**Issue by ltlf** [kubeedge/kubeedge#1613]
**What happened**:
when i started on armv8，what error happend：
![image](https://user-images.githubusercontent.com/16397723/80168616-e43f2480-8615-11ea-9603-dd427998f6f7.png)
E0424 02:24:57.679144   31694 edged.go:568] Failed to start device plugin manager system validation failed - Following Cgroup subsystem not mounted: [memory]
E0424 02:24:57.679274   31694 edged.go:262] initialize module error: system validation failed - Following Cgroup subsystem not mounted: [memory]
**What you expected to happen**:
i expected edgecore can started
**How to reproduce it (as minimally and precisely as possible)**:
you can compile and run edgecore  on armv8，then start edgecore can find this error
**Anything else we need to know?**:
**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
2020-04-24 02:30:32.497865 I | INFO: Install client plugin, protocol: rest
2020-04-24 02:30:32.498509 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.2.0-beta.0.187+f7a9374e3fa16b
- Hardware configuration (e.g. `lscpu`):
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  3
Socket(s):           2
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1800.0000
CPU min MHz:         408.0000
BogoMIPS:            48.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32

- OS (e.g. `cat /etc/os-release`):
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`):
Linux debian10.toybrick 4.4.189 #93 SMP Tue Nov 26 16:40:07 CST 2019 aarch64 GNU/Linux

- Go version (e.g. `go version`): 
go version go1.14.1 linux/amd64

- Others:

**Comment by guanzydev** [comment]
cgroupDriver is cgroupfs?

**Comment by ltlf** [comment]
yes

**Comment by ltlf** [comment]
> cgroupDriver is cgroupfs?

yes

**Comment by stacktasec** [comment]
When I use ubuntu server 20.04 for raspberry, I met this error,
so I append this line 
`cgroup_enable=memory`
to 
`/boot/firmware/cmdline.txt`

resolved this.

**Comment by lmxia** [comment]
The same promlem!  did you figure it out?

**Comment by swetabhgit** [comment]
![image](https://user-images.githubusercontent.com/43088897/159154133-87fac003-dddb-4bd4-8d36-ecdb065fe831.png)

getting above issue even adding "cgroup_enable=memory cgroup_memory=1" to /boot/cmdline.txt

I am stuck with this issue.
