### ISSUE TITLE
Unable to run cloudcore

### ISSUE THREAD

**Issue by lucklyblue** [kubeedge/kubeedge#1620]
**What happened**:
Running cloudcore，type conversion failed

` Version: v1.2.1
24866 module.go:34] Module cloudhub registered successfully
24866 module.go:34] Module edgecontroller registered successfully
24866 module.go:34] Module devicecontroller registered successfully
module.go:34] Module synccontroller registered successfully
core.go:24] Starting module cloudhub
24866 core.go:24] Starting module edgecontroller
24866 core.go:24] Starting module devicecontroller
24866 core.go:24] Starting module synccontroller
24866 upstream.go:95] start upstream controller
downstream.go:796] Start downstream devicecontroller
objectsync.go:164] The resourceVersion: 2787919 of pod in K8s is greater than in edgenode: 2343659, send the update event
objectsync.go:164] The resourceVersion: 9617492 of endpoints in K8s is greater than in edgenode: 2786974, send the update event
objectsync.go:164] The resourceVersion: 9617490 of endpoints in K8s is greater than in edgenode: 2786976, send the update event
runtime.go:78] Observed a panic: &strconv.NumError{Func:"ParseUint", Num:"", Err:(*errors.errorString)(0xc00003c1d0)} (strconv.ParseUint: parsing "": invalid syntax)
goroutine 284 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14509a0, 0xc00091e1b0)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14509a0, 0xc00091e1b0)
	/root/.gvm/gos/go1.13.4/src/runtime/panic.go:679 +0x1b2
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.CompareResourceVersion(0xc0008ca3d0, 0x7, 0x0, 0x0, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:214 +0x10d
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.sendEvents(0x0, 0x0, 0xc000422680, 0xd, 0xc0003fdc89, 0x7, 0xc0002b69c0, 0x24, 0x1620e4d, 0x3, ...)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:162 +0x85
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).managePod(0xc000247200, 0xc0000182b0)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:40 +0x1a7
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).manageObjectSync(0xc000247200, 0xc000a10400, 0x18, 0x20)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:210 +0x154
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).reconcile(0xc000247200)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:193 +0x1ea
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a0f540)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a0f540, 0x12a05f200, 0x0, 0x45ca01, 0xc000048960)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000a0f540, 0x12a05f200, 0xc000048960)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).Start
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:179 +0x510
panic: strconv.ParseUint: parsing "": invalid syntax [recovered]
	panic: strconv.ParseUint: parsing "": invalid syntax

goroutine 284 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/runtime/runtime.go:55 +0x105
panic(0x14509a0, 0xc00091e1b0)
	/root/.gvm/gos/go1.13.4/src/runtime/panic.go:679 +0x1b2
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.CompareResourceVersion(0xc0008ca3d0, 0x7, 0x0, 0x0, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:214 +0x10d
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.sendEvents(0x0, 0x0, 0xc000422680, 0xd, 0xc0003fdc89, 0x7, 0xc0002b69c0, 0x24, 0x1620e4d, 0x3, ...)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:162 +0x85
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).managePod(0xc000247200, 0xc0000182b0)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/objectsync.go:40 +0x1a7
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).manageObjectSync(0xc000247200, 0xc000a10400, 0x18, 0x20)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:210 +0x154
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).reconcile(0xc000247200)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:193 +0x1ea
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a0f540)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a0f540, 0x12a05f200, 0x0, 0x45ca01, 0xc000048960)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000a0f540, 0x12a05f200, 0xc000048960)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).Start
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:179 +0x510
`

**What you expected to happen**:
normal operation cloudcore

**How to reproduce it (as minimally and precisely as possible)**:
sudo  ./cloudcore

**Anything else we need to know?**:
my cloudcore.yaml is:
[cloudcore.txt](https://github.com/kubeedge/kubeedge/files/4550711/cloudcore.txt)

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  1.2.1

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):x86_64
- OS (e.g. `cat /etc/os-release`): CentOS Linux release 7.7.1908
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): go version go1.13.5 linux/amd64
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):x86_64
- OS (e.g. `cat /etc/os-release`):CentOS Linux release 7.7.1908
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): go version go1.13.5 linux/amd64
- Others:

**Comment by kevin-wangzefeng** [comment]
/cc @fisherxu 
This should have been fixed on master, IIRC.

**Comment by lucklyblue** [comment]
Fix panic in cloudcore #1552
