### ISSUE TITLE
Edge devices disappear from CloudCore

### ISSUE THREAD

**Issue by OuFinx** [kubeedge/kubeedge#1621]
**What happened**:

I installed CloudCore 1.2.1 on the ubuntu and connected to the EKS 

I connected my edge device to CloudCore via `keadm join`. When I did `kubectl get nodes` I see nodes from my EKS and Edge device.

But when I rebooted my edge device (or switch off and then start on) my edge device disappeared from CloudCore.

In CloudCore logs I saw just:
`862 messagehandler.go:361] Node test-device disconnected and stopped sending messages`

But when I have KubeEdge full setup (EdgeNode, Worker, Master) and my edge device was rebooted it did not disappear from the general list `kubectl get nodes` but simply went into the status of` NotReady`

**What you expected to happen**:

I expected my edge device change status from `Ready` to `NotReady` and when my device will be available the status will change to `Ready` again

**How to reproduce it (as minimally and precisely as possible)**:

1. Install CloudCore 1.2.1 (I used [This](https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_keadm.md) instruction)
2. Connect to the EKS cluster
3. Check `kubectl get nodes` you see nodes from kubernetes
4. Connect your edge device to this CloudCore instance
5. Look at `kubectl get nodes` you see your edge device with status `Ready`
6. Turn off your edge device for 5 minutes
7. Look at `kubectl get nodes` your edge device was disappeared

**Anything else we need to know?**:

I used full-stack (EdgeNode, Worker, Master) because was a problem with connecting to the EKS cluster.

When it was fixed on KubeEdge 1.2.1 - I start use it.

**Environment**:

Full-stack:
```ubuntu@master:~$ k version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
ubuntu@master:~$ cloudcore --version
KubeEdge v1.2.1
```

Just CubeEdge:

```
ubuntu@ip-192-168-68-107:~$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
ubuntu@ip-192-168-68-107:~$ cloudcore --version
KubeEdge v1.2.1
```

**CloudSide Environment**:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by kevin-wangzefeng** [comment]
> But when I have KubeEdge full setup (EdgeNode, Worker, Master) and my edge device was rebooted it did not disappear from the general list `kubectl get nodes` but simply went into the status of` NotReady`

Are you expecting the edge node stay existing or not?

**Comment by kevin-wangzefeng** [comment]
The edge node may be removed due to EKS cloud provider checking failure for instances (edge node of course doesn't have an ECS instance).
You may try with the build from master branch, or mannually label edge node with `"node-role.kubernetes.io/agent"=""`

**Comment by OuFinx** [comment]
`To keep the edge nodes stay, when disconneted, you may try with the build from master branch"`
it seemed to me that I used the master branch
```
git clone https://github.com/kubeedge/kubeedge.git $GOPATH/src/github.com/kubeedge/kubeedge
cd $GOPATH/src/github.com/kubeedge/kubeedge
make all WHAT=keadm
```

**Comment by OuFinx** [comment]
@kevin-wangzefeng I tried as you told me:
1. Build new version from master
2. Use label for edge node.

This is doesn't help. The edge device still disappear
