### ISSUE TITLE
make lint not cover all codes

### ISSUE THREAD

**Issue by daixiang0** [kubeedge/kubeedge#1623]
Now `make lint` check codes by components, it miss check codes under pkgs and tests dirs.

I think run do lint check at root directory is enough.

**Comment by kadisi** [comment]
good

**Comment by daixiang0** [comment]
Now we use script to detect components and then run test, but for docs or codes under pkgs/tests, it can not cover.
@kevin-wangzefeng shall we change the test way or add those in `ALL_COMPONENTS_AND_LINT_FUNCTIONS`?
