### ISSUE TITLE
Failed to get the latest KubeEdge release version

### ISSUE THREAD

**Issue by daixiang0** [kubeedge/kubeedge#1629]
When do not specify kubeedge version, keadm can not get latest version:
```
# ./_output/local/bin/keadm init
Failed to get the latest KubeEdge release version, will use default version 
...
```

**Comment by kevin-wangzefeng** [comment]
It's for automatially fetching latest stable release. If fetching failed, will fallback on default.

Additionally, we can expose a parameter to accept user indicated version.
