### ISSUE TITLE
Add certificate rotation for edge node

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1630]
**Why is this needed**:
At present, the edge nodes of KubeEdge only apply for certificates when they first started.
Because the certificates have a validity period, we need to automatically generate a new key and request a new certificate from the cloudcore periodically.

**Comment by SidharthBansal** [comment]
Hello @fisherxu , I am a fourth-year CSE student. I had done GSoC'18 at Public Lab(Ruby on Rails), Google Internship(Android), India and wrote two research papers in NLP(Python).
I am willing to get mentored for this issue for the Community Bridge program. Can you please help me in getting started with it and kubeedge?
Thanks

**Comment by luogangyi** [comment]
Can we just use cert-manager to do this ?
See https://cert-manager.io/docs/installation/kubernetes/

**Comment by fisherxu** [comment]
> Can we just use cert-manager to do this ?
See https://cert-manager.io/docs/installation/kubernetes/

@luogangyi  Thanks for your suggestion :) Previously, we have discussed applying for the certificate from K8s, but the edgecore's certificate request must be forwarded from cloudcore to K8s. Considering security and other issues, we finally made the certificate issuance in cloudcore, and edgecore only need to talk with cloudcore to apply the certificate.

**Comment by fisherxu** [comment]
@SidharthBansal  Sure, let's write a preliminary design document first :)

**Comment by vaniisgh** [comment]
Hey! I find this issue interesting too :) and would like to contribute to Kube Edge through Community Bridge! 
Would it be ok if I create a google doc for a basic design document for this and sent it to you over Slack?

thanks & regards
Vani

**Comment by fisherxu** [comment]
@SidharthBansal  @vaniisgh  Can you please send a resume to me?

**Comment by vaniisgh** [comment]
I sent it over to you via email :)

**Comment by XJangel** [comment]
Hi. @fisherxu I am a postgraduate student from Zhejiang University. I am also interested in this issue and would like to get mentored for this issue for the Community Bridge program. I am familiar with KubeEdge now and hope to make more contribution.
Thanks!

**Comment by fisherxu** [comment]
@XJangel   Can you also please send a resume to me?

**Comment by XJangel** [comment]
> @XJangel Can you also please send a resume to me?

Sure! I'll send it to you.

**Comment by theadityasam** [comment]
Hey @fisherxu. Unfortunately I'm a bit late to the party, would you still consider applications for the mentorship program right now? Should I mail you my resume alongwith the cover letter?

**Comment by fisherxu** [comment]
> Hey @fisherxu. Unfortunately I'm a bit late to the party, would you still consider applications for the mentorship program right now? Should I mail you my resume alongwith the cover letter?

@theadityasam  Yes, it's a bit late now :) Please follow the next round.

**Comment by theadityasam** [comment]
Okay, sure! Thanks for the update :)
