### ISSUE TITLE
Dynamic IP address in Edge side

### ISSUE THREAD

**Issue by jwang11** [kubeedge/kubeedge#1639]
Just confirm with Kubeedge team if below feature is implemented
**What would you like to be added/modified**:
IP address of Edge side is dynamic or keep changing after running a period of time. In such case, Kubeedge should handle edge node, pod and other messages correctly.

**Why is this needed**:
In our case, IP address of Edge server is actually allocated from a IP Pool, which cause dynamic IP address.

**Comment by jwang11** [comment]
Ping... Please confirm this feature is ready or not?

**Comment by fisherxu** [comment]
> In our case, IP address of Edge server is actually allocated from a IP Pool, which cause dynamic IP address.

When the  IP address changed, will the edgecore reconnecnt to cloudcore?

**Comment by jwang11** [comment]
> > In our case, IP address of Edge server is actually allocated from a IP Pool, which cause dynamic IP address.
> 
> When the IP address changed, will the edgecore reconnecnt to cloudcore?

Yes, edgecore is wrapped into a systemd service.  It keep running anyway. Just would like to confirm, when IP change, the node won't be recoginized as a new node in k8s cluster

**Comment by fisherxu** [comment]
When the ip change, if edgecore restart, edgecore will read the ip from specify interface and report ip through node status. And if edgecore don't restart, it can't aware of  ip change.

Not sure whether the ip change will have affect to logs api.

**Comment by fisherxu** [comment]
cc @kadisi

**Comment by jwang11** [comment]
> When the ip change, if edgecore restart, edgecore will read the ip from specify interface and report ip through node status. And if edgecore don't restart, it can't aware of ip change.
> 
> Not sure whether the ip change will have affect to logs api.

Thanks for clarification. So, if edgecore restart after ip change, kubeedge can handle it correctly, and won't be recoganized as a new node, right?

**Comment by fisherxu** [comment]
> if edgecore restart after ip change, kubeedge can handle it correctly, and won't be recoganized as a new node, right?

Yes, I think so. :)

**Comment by fisherxu** [comment]
Close the issue first, please let us know if have any questions. :)
/close
