### ISSUE TITLE
Pod has Pending status which installed to node

### ISSUE THREAD

**Issue by OuFinx** [kubeedge/kubeedge#1641]
**What happened**:
DaemonSet install deployment (Pod) in the node which was offline and now online and Pod stuck on the Pending status

**What you expected to happen**:
Deployment (Pod) successfully installed to the node (edge device)

**How to reproduce it (as minimally and precisely as possible)**:
1. You have 2 node. 1 online and 1 offline
2. You create DaemonSet with `nodeAffinity` (where is set these 2 nodes)
3. You apply DaemonSet and it successfully installed to the first node (which is online)
4. You turn on second node (which was offline).
5. When the second node is online, the DaemonSet install deployments and spun up Pod for this Node. But this Pod will be stuck on the `Pending` status for infinity.

Just when you force delete this stuck Pod new Pod will be successfully installed to this second node.

**Anything else we need to know?**:
On this node installed docker. And when it was Pending status - I went to the node and run `docker ps -a` and nothing to saw.
It feels like the second node (Edge device) didn't even know that DaemonSet trying to install something.

**Environment**:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
ubuntu@master:~$ cloudcore --version
KubeEdge v1.2.1
```

**CloudSide Environment**:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**EdgeSide Environment**:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by GsssC** [comment]
Is there any “write error: “ in log of cloudcore shown as #1692 ?
