### ISSUE TITLE
edgemesh 占用443端口与hostport使用443端口冲突问题

### ISSUE THREAD

**Issue by harmful1980** [kubeedge/kubeedge#1658]
问题描述：
cloudcore启动时会给kube-apiserver生成一个service
[root@w-live05 ~]# kubectl get service
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   49d
这个service被edgemesh拉到后会从虚拟设备edge0中取出一个未使用的IP来监听443端口
[root@w-live08 ~]# netstat -panl|grep 443
tcp        0      0 9.251.0.1:443           0.0.0.0:*               LISTEN      3060/edgecore

当用hostport启动一个用户应用在443端口时，docker会起监听在0.0.0.0:443,
这个时候就会与edgemesh的443端口冲突，造成用户应用无法使用hostport 443
请问
1.kube-apiserver是cloudcore上执行的，且根据kubeedge的架构图，edge是通过edge-hub和cloud-hub通讯拿到云端资源配置的，通过metamanager拿到边缘本地配置的，edgemesh为什么需要处理这个kube-apiserver的service？
2.有什么办法可以解决这个用户应用hostport 443和edgemesh处理kube-apiserver的service的443的端口冲突？

**Comment by jiaji2006** [comment]
我也有类似的情况...

**Comment by daixiang0** [comment]
使用443是方便client调用吗？

**Comment by harmful1980** [comment]
> 使用443是方便client调用吗？

443是https的默认端口，当client要访问https服务时，不需要告诉client端口，默认使用443就可以了
