### ISSUE TITLE
Telemetry data sent by edge device is not reaching cloud

### ISSUE THREAD

**Issue by chiru091096** [kubeedge/kubeedge#1660]
**What happened**:
Telemetry data sent by device doesn't go to cloud. The data read from the device is published by the scheduler to the topic "$ke/device/bluetooth-mapper/.../scheduler/result". Data isn't handled after that.

**What you expected to happen**:
Telemetry data to be sent to cloud.

**How to reproduce it (as minimally and precisely as possible)**:
Set up kubeedge 1.2.0.
Create simple device-model.yaml, device-instance.yaml and config.yaml to read the data from edge device.
Deploy the mapper and get the data from the device.

**CloudSide Environment**:
- edgecore version (e.g. `edgecore --version`):
KubeEdge v1.2.0
OS: Ubuntu 18.04

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
KubeEdge v1.2.0
OS: Ubuntu 16.04

**Comment by luogangyi** [comment]
I find this problem too. It should be another module to deal with "$ke/device/bluetooth-mapper/.../scheduler/result", but that module is not in repo.
