### ISSUE TITLE
Basic Guide to install w/o keadm

### ISSUE THREAD

**Issue by jwlai** [kubeedge/kubeedge#1665]
I was wondering if there was a quick guide to manually install KubeEdge into my Cluster (EKS in AWS). I can't seem to find basic installation instructions. After digging around I found https://github.com/kubeedge/kubeedge/blob/master/build/cloud/README.md

Are there instructions for a basic set of things to install to function (Other than architecture diagram)?

**Comment by zzxgzgz** [comment]
Check this [Development Guide](https://github.com/kubeedge/kubeedge/blob/master/docs/setup/develop_kubeedge.md) out.

**Comment by fisherxu** [comment]
> Check this Development Guide out.

Yes, this is right :)

/close
