### ISSUE TITLE
As per README.md, to run edge UT & IT, execute "make test" & "make integration_test", these commands fail

### ISSUE THREAD

**Issue by samy2019** [kubeedge/kubeedge#167]
**What happened**:
As per README.md, after executing "make test" & "make integration_test", the execution fails with error.

ubuntu@ubuntu1804VM:~/gopath/src/github.com/kubeedge/kubeedge/edge$ cd ..
ubuntu@ubuntu1804VM:~/gopath/src/github.com/kubeedge/kubeedge$ make test
make: *** No rule to make target 'test'.  Stop.

ubuntu@ubuntu1804VM:~/gopath/src/github.com/kubeedge/kubeedge$ make integration_test
make: *** No rule to make target 'integration_test'.  Stop.

**What you expected to happen**:
After execution of the command, UT & IT should had successfully run.

**How to reproduce it (as minimally and precisely as possible)**:
Simply go to ~/gopath/src/github.com/kubeedge/kubeedge path and execute "make test"
Simply go to ~/gopath/src/github.com/kubeedge/kubeedge path and execute "make integration_test"

**Anything else we need to know?**:

**Environment**:
- KubeEdge version: 0.1
- Hardware configuration: NA
- OS (e.g. from /etc/os-release): "Ubuntu 18.04.1 LTS"
- Kernel (e.g. `uname -a`): NA
- Others:

**Comment by m1093782566** [comment]
@sids-b Please take a look.

**Comment by m1093782566** [comment]
@samy2019 Thanks for reporting the issue.

A quick question, did you check out the HEAD OR just download the v0.1 release?

**Comment by samy2019** [comment]
I had checked out HEAD and not v0.1. Hence it is mistake from myside to put kubeedge version as v0.1.

**Comment by sids-b** [comment]
Just a problem in README.md
instead of make test .... we need to make it make edge_test
Similar for integration test 

Small bug in README.md , no need to make any changes in any other file.  @samy2019 can you raise PR with fix ?

**Comment by m1093782566** [comment]
Thanks for your prompt response @sids-b.
