### ISSUE TITLE
Failed to get the latest KubeEdge release version, will use default version

### ISSUE THREAD

**Issue by darunshen** [kubeedge/kubeedge#1688]
**What happened**:
sometimes print the title line sometimes not
**What you expected to happen**:
should not print this line
**How to reproduce it (as minimally and precisely as possible)**:
execute 'keadm join args' a few times
**Anything else we need to know?**:
kubeedge/keadm/cmd/keadm/app/cmd/util/common.go:

```
func GetLatestVersion() (string, error) {
	//Download the tar from repo
	versionURL := "curl -k " + latestReleaseVersionURL
	cmd := exec.Command("sh", "-c", versionURL)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	latestReleaseData, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("%v:%v", err, stderr.String())
	}
	latestRelease := &latestReleaseVersion{}
	err = json.Unmarshal(latestReleaseData, latestRelease)
	if err != nil {
		return "", err
	}
	return latestRelease.TagName, nil
}
```
 `latestRelease.TagName` will be assigned to `latestVersion` in file `kubeedge/keadm/cmd/keadm/app/cmd/edge/join.go`;
so variable 'latestVersion' may be released before used by 'len(latestVersion)'.

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): v1.3.0-dirty
- Hardware configuration (e.g. `lscpu`):aarch64
- OS (e.g. `cat /etc/os-release`):Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`):4.4.194
- Go version (e.g. `go version`): 1.14.2 linux/arm64

**Comment by daixiang0** [comment]
Duplicate with #1629.
