### ISSUE TITLE
Collecting metrics on the edge (containers and nodes) and then send  to Cloud

### ISSUE THREAD

**Issue by benjaminhuo** [kubeedge/kubeedge#1689]
I noticed key features like below was mentioned in kubeedge annual review: [Collecting metrics of containers on the edge from Cloud](https://github.com/cncf/toc/pull/440/commits/10118bc880c5a5a9423a2c4a5f2cac1f3774f248#diff-e9dc5bcb93599ba622b4e3e626fdd4eeR109)

And also noticed a feature in the latest 1.3 release notes that `Add metrics interfaces at edge`
So the edge metrics interface feature in v1.3 is part of the key feature mentioned in kubeedge annual review?

Any plan regarding feature Collecting metrics of containers on the edge from Cloud` ?

Edge node metrics is important as well as edge container metrics and it's valuable to fetch edge metrics(nodes and containers) and then send to cloud for monitoring purpose.

I'm glad to know what's KubeEdge's plan on this and I'm happy to participate in kubeedge development starting with this feature.

Thanks

Ben

**Comment by FeynmanZhou** [comment]
@kevin-wangzefeng Is there any detailed doc to elaborate on the [Collecting metrics and logs of containers on the edge from Cloud](https://github.com/cncf/toc/pull/440/commits/10118bc880c5a5a9423a2c4a5f2cac1f3774f248#diff-e9dc5bcb93599ba622b4e3e626fdd4eeR110), or when will this feature be included in community meeting? Please let us know its details.

We would like to join KubeEdge community to implement these two features together. And we plan to integrate KubeEdge in [KubeSphere](https://github.com/kubesphere/kubesphere) in the future.

**Comment by kevin-wangzefeng** [comment]
Thanks @benjaminhuo @FeynmanZhou, in KubeEdge v1.3, we added metrics interface to edgecore, and in v1.4 we have plan to offer metrics server support on cloud for collecting metrics from pods at edge.

It would be helpful if you guys could lead/join the integration work with prometheus edge.

**Comment by benjaminhuo** [comment]
@kevin-wangzefeng we're glad to participant in kubeedge development starting from this. Let's discuss this further

**Comment by GsssC** [comment]
@Poor12

**Comment by benjaminhuo** [comment]
@kevin-wangzefeng @GsssC @FeynmanZhou @rayzhou2017 , we will submit a PR to `Support metrics-server in the cloud to collecting edge nodes/pods metrics` soon. This PR will be submitted by @Ma-Dan

**Comment by Poor12** [comment]
Thanks for your effort. The community has plans to do this, and it has basically been completed. We will launch this feature soon.@benjaminhuo

**Comment by benjaminhuo** [comment]
@Poor12  looks like we made the same effort... The PR is here https://github.com/kubeedge/kubeedge/pull/1799
