### ISSUE TITLE
Can Kubeedge support a custom scheduler in the cluster just like K8s?

### ISSUE THREAD

**Issue by mixalako** [kubeedge/kubeedge#1690]
Deploying a custom scheduler is going right away at the edge from the default scheduler , which is not what is expected. 
**What would you like to be added/modified**:

**Why is this needed**:

**Comment by luogangyi** [comment]
Do you mean your  custom scheduler  is scheduled to edge node ?
You can try add a normal node in your k8s,  and use nodeSelector to force your custom scheduler pod to be run at that normal node.

**Comment by mixalako** [comment]
You want your scheduler to run on the master node in replacement of the default.
