### ISSUE TITLE
Edgecore disconnects from Cloudcore when Edgecore restarts frequently

### ISSUE THREAD

**Issue by Poor12** [kubeedge/kubeedge#1692]
**What happened**:
Edgecore disconnects from Cloudcore

**What you expected to happen**:
Cloudcore and Edgecore are connected normally

**How to reproduce it (as minimally and precisely as possible)**:
When the connection is normal, restart edgecore 5 times in a row

Anything else we need to know?**:
Logs from cloudcore:

> I0518 09:35:59.323358       1 upstream.go:166] dispatch message ID: 1e74b839-38da-44e6-b609-9959798374f7
> I0518 09:35:59.323393       1 upstream.go:174] message: 1e74b839-38da-44e6-b609-9959798374f7, resource type is: podstatus
> I0518 09:35:59.323410       1 upstream.go:176] message: 1e74b839-38da-44e6-b609-9959798374f7, operation type is: update
> I0518 09:35:59.323441       1 upstream.go:223] message: 1e74b839-38da-44e6-b609-9959798374f7, operation is: update, and resource is: node/edgenode80/kube-system/podstatus
> I0518 09:35:59.336965       1 upstream.go:300] message: 1e74b839-38da-44e6-b609-9959798374f7, update pod status successfully, namespace: kube-system, name: kube-proxy-d9499
> I0518 09:35:59.349186       1 upstream.go:300] message: 1e74b839-38da-44e6-b609-9959798374f7, update pod status successfully, namespace: kube-system, name: calico-node-mflpv
> I0518 09:35:59.359124       1 upstream.go:300] message: 1e74b839-38da-44e6-b609-9959798374f7, update pod status successfully, namespace: kube-system, name: calicoctl
> W0518 09:35:59.364040       1 upstream.go:231] message: 1e74b839-38da-44e6-b609-9959798374f7, pod not found, namespace: kube-system, name: app-6d76c4459d-fz8nq
> W0518 09:35:59.369855       1 upstream.go:231] message: 1e74b839-38da-44e6-b609-9959798374f7, pod not found, namespace: kube-system, name: app-6d76c4459d-nlhg6
> E0518 09:36:01.822025       1 messagehandler.go:450] write error, connection for node edgenode177 will be closed, affected event id: f6486574-cc72-4116-b8ce-14567f6074e4, parent_id: , group: resource, source: edgecontroller, resource: kubeedge/endpoints/cloudcorelease, operation: update, reason tls: use of closed connection
> E0518 09:36:01.822374       1 messagehandler.go:450] write error, connection for node edgenode177 will be closed, affected event id: 98d5ff5c-3868-462c-8759-8f09247badda, parent_id: , group: resource, source: edgecontroller, resource: kube-system/endpoints/kube-scheduler, operation: update, reason tls: use of closed connection
> E0518 09:36:01.822418       1 messagehandler.go:450] write error, connection for node edgenode177 will be closed, affected event id: 7aa01b05-915a-4b3a-9468-61ba3bd224cb, parent_id: , group: resource, source: edgecontroller, resource: kube-system/endpoints/kube-controller-manager, operation: update, reason tls: use of closed connection
> I0518 09:36:02.149211       1 messagehandler.go:111] Keepalive message received from node: edgenode80
> I0518 09:36:02.149317       1 messagehandler.go:162] Node edgenode80 is still alive
> I0518 09:36:02.297935       1 objectsync.go:150] pod: calico-node-scdhj has been deleted in K8s, send the delete event to edge

**Environment**:
- KubeEdge version 1.3.0 latest

**CloudSide Environment**:
- Hardware configuration : 2CPUs,Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
- OS :centos
- Kernel :x86_64 GNU/Linux
- Go version: go 1.14.1

**EdgeSide Environment**:
- Hardware configuration : 2CPUs,Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
- OS :centos
- Kernel :x86_64 GNU/Linux
- Go version :go 1.14.1

**Comment by fisherxu** [comment]
The KubeEdge version maybe wrong in the issue description :)

**Comment by Poor12** [comment]
> The KubeEdge version maybe wrong in the issue description :)

Sorry,my mistake,and sincerely my best wish for you at this important day.
