### ISSUE TITLE
Failed to unmarshal configfile /etc/kubeedge/config/edgecore.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Edged.modules.edged.volumeStatsAggPeriod of type time.Duration

### ISSUE THREAD

**Issue by yzhao66** [kubeedge/kubeedge#1706]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by fisherxu** [comment]
The issue has been fixed in #1701, for workaround you can compile a keadm from master branch.
