### ISSUE TITLE
kubectl logs failed

### ISSUE THREAD

**Issue by faicker** [kubeedge/kubeedge#1712]
**What happened**:
failed to exec kubectl logs on cloudcore.
the error is dial tcp 192.168.88.2:10350: connect: connection refused

**What you expected to happen**:
pod log showed

**How to reproduce it (as minimally and precisely as possible)**:
exec kubectl logs on cloudcore.

**Anything else we need to know?**:
on the edge node, listened at 127.0.0.1:10350

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
v1.3.0

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:
ubuntu18.04

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:
ubuntu16.04

**Comment by cody1115** [comment]
@faicker, I met the same issue. How did you fix it ? Thanks a lot~

**Comment by faicker** [comment]
see https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_source.md

**Comment by lixiangmyehk** [comment]
https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_source.md
this is invalid 。
