### ISSUE TITLE
CloudCore 1.3.0 failed to run: failed to parse EC private key: asn1: structure error: length too large

### ISSUE THREAD

**Issue by 12101111** [kubeedge/kubeedge#1714]
**What happened**:
run `keadm init` successfully but `cloudcore` failed to start
**What you expected to happen**:
`cloudcore` start successfully
**How to reproduce it (as minimally and precisely as possible)**:
`sudo keadm init --kubeedge-version=1.3.0`
**Anything else we need to know?**:
I want to test https://github.com/kubeedge/kubeedge/pull/1701
**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
```
$ cloudcore --version
KubeEdge v1.3.0
$ keadm version
version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-11+fc95119f347386", GitCommit:"fc95119f347386c8c05306e4e63cf695f5631e1f", GitTreeState:"clean", BuildDate:"2020-05-21T09:38:48Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
```
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): 
 libvirt/kvm/qemu CPU: 3 core Skylake-Client-IBRS Memory: 4G
- OS (e.g. `cat /etc/os-release`):
Ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux 5.4
- Go version (e.g. `go version`): 1.14.3
- Others:

**Comment by fisherxu** [comment]
@12101111 #1701 now has been merged, for workaround, will you have a try that compile a keadm from master branch then install 1.3?

**Comment by 12101111** [comment]
I already use keadm from master branch (test both fc95119f347386c8c05306e4e63cf695f5631e1f and 1d880504f4bf06de9bd6186e851888a66cb782ab)
And cloudcore still can't run:
```log
I0521 14:48:03.069821    7727 server.go:58] Version: v1.3.0
I0521 14:48:03.069887    7727 module.go:34] Module cloudhub registered successfully
I0521 14:48:03.069901    7727 module.go:34] Module edgecontroller registered successfully
I0521 14:48:03.069910    7727 module.go:34] Module devicecontroller registered successfully
I0521 14:48:03.071758    7727 module.go:34] Module synccontroller registered successfully
W0521 14:48:03.071774    7727 module.go:37] Module cloudStream is disabled, do not register
I0521 14:48:03.071814    7727 core.go:24] Starting module synccontroller
I0521 14:48:03.071844    7727 core.go:24] Starting module cloudhub
I0521 14:48:03.072181    7727 core.go:24] Starting module edgecontroller
I0521 14:48:03.072308    7727 core.go:24] Starting module devicecontroller
I0521 14:48:03.074381    7727 upstream.go:96] start upstream controller
I0521 14:48:03.096857    7727 downstream.go:796] Start downstream devicecontroller
I0521 14:48:03.152850    7727 downstream.go:430] start downstream controller
I0521 14:48:03.176515    7727 server.go:186] Ca and CaKey don't exist, and will be signed by cloudcore
I0521 14:48:03.182347    7727 server.go:229] TLSCertFile and TLSPrivateKeyFile don't exist, and will be signed by cloudcore
E0521 14:48:03.195246    7727 server.go:235] failed to sign a certificate, error: failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: length too large
F0521 14:48:03.195268    7727 cloudhub.go:70] failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: length too large
```

**Comment by fisherxu** [comment]
@12101111  You can delete the `kubeedge` ns and all the info under it, then have a retry.

**Comment by fisherxu** [comment]
@12101111  You can delete the `kubeedge` ns and all the info under it, then have a retry.

**Comment by luogangyi** [comment]
```
genCA() {
    openssl genrsa -des3 -out ${caPath}/rootCA.key -passout pass:kubeedge.io 4096
    openssl req -x509 -new -nodes -key ${caPath}/rootCA.key -sha256 -days 3650 \
    -subj ${subject} -passin pass:kubeedge.io -out ${caPath}/rootCA.crt
}
```
cloudconfig.go still use rsa key, I think that is the problem

**Comment by fisherxu** [comment]
> cloudconfig.go still use rsa key, I think that is the problem

no, `cloudconfig.go` just used before 1.3, in 1.3 we don't use the certGensh any more.

**Comment by 12101111** [comment]
> @12101111 You can delete the `kubeedge` ns and all the info under it in your K8s cluster, then have a retry.

Deleting `kubeedge` namespace solved this problem

**Comment by markwangC** [comment]
> > @12101111 You can delete the `kubeedge` ns and all the info under it in your K8s cluster, then have a retry.
> 
> Deleting `kubeedge` namespace solved this problem

The 'kubeedge' namespace would be re-created after running cloudcore with the same error info

**Comment by yzhao66** [comment]
> > > @12101111 You can delete the `kubeedge` ns and all the info under it in your K8s cluster, then have a retry.
> > 
> > 
> > Deleting `kubeedge` namespace solved this problem
> 
> The 'kubeedge' namespace would be re-created after running cloudcore with the same error info

i get same error too after delete ns

**Comment by Caixiaomeng** [comment]
> > > > @ 12101111您可以`kubeedge`在K8s集群中删除ns及其下的所有信息，然后重试。
> > > 
> > > 
> > > 删除`kubeedge`名称空间解决了这个问题
> > 
> > 
> > 在运行具有相同错误信息的cloudcore之后，将重新创建“ kubeedge”名称空间
> 
> 删除ns后我也遇到相同的错误

+1我也是删除了之后还是同样的问题，请问你jie

> > > > @12101111 You can delete the `kubeedge` ns and all the info under it in your K8s cluster, then have a retry.
> > > 
> > > 
> > > Deleting `kubeedge` namespace solved this problem
> > 
> > 
> > The 'kubeedge' namespace would be re-created after running cloudcore with the same error info
> 
> i get same error too after delete ns

me too.Have you solved this problem?
