### ISSUE TITLE
Redhat Support for keadm

### ISSUE THREAD

**Issue by dmosruby** [kubeedge/kubeedge#1716]
**What would you like to be added/modified**:
Redhat Support for keadm

**Why is this needed**:
Redhat is a very common OS installed in the commercial space and right now the keadm won't even run because it only supports specifically CentOS and Ubuntu.

CentOS and Redhat are very alike and I was able to get the keadm running with only a couple minor changes in code in the `keadm/cmd/keadm/app/cmd/util/common.go`

On the `func GetOSInterface()` I added a new version type `RedHatType = "rhel"` to the case statement and had it return the CentOS struct.

```go
func GetOSInterface() types.OSTypeInstaller {
	switch GetOSVersion() {
	case UbuntuOSType:
		return &UbuntuOS{}
	case CentOSType, RedHatType:
		return &CentOS{}
	default:
		panic("This OS version is currently un-supported by keadm")
	}
}
```

From there, the Redhat machine only needed the EPEL packages installed for the yum packages that you normally install for CentOS to work on Redhat.

```bash
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
subscription-manager repos --enable "rhel-*-optional-rpms" --enable "rhel-*-extras-rpms"  --enable "rhel-ha-for-rhel-*-server-rpms"
```

For other RedHat versions: https://fedoraproject.org/wiki/EPEL#Quickstart

Tested on Redhat 7.6

**Comment by daixiang0** [comment]
Would you like to have a try and file a pr?

**Comment by dmosruby** [comment]
I can give it a shot 🙂 how would you suggest handling the installation of the `epel` release package and subscription manager enable commands?

**Comment by daixiang0** [comment]
Why need epel source?

**Comment by dmosruby** [comment]
The yum commands in the centos for `epel-release` and `mosquitto` install will fail with Redhat unless the epel release for that specific version of Redhat is installed - https://github.com/kubeedge/kubeedge/blob/master/keadm/cmd/keadm/app/cmd/util/centosinstaller.go#L53

**Comment by daixiang0** [comment]
`yum install epel-release mosquitto -y` is fine, i think add redhet detect support is ok.
