### ISSUE TITLE
Service support and data communication between nodes

### ISSUE THREAD

**Issue by qizha** [kubeedge/kubeedge#172]
**What would you like to be added**:
A mechanism to support interaction between nodes. The interaction include both data transport and application calling.
There are two factors for the data transportation:
1. Define the endpoint which include data source and destination in a data transportation process
2. Define a router rule to connect the pre-defined source and destination points 
Once the router created, the data will be able to transport from the source to destination which may corss the nodes. In the data transportation, there may have a proxy in each nodes to execute the router rule.

As for the application calling, I would like to call it EdgeMesh which is similar with the Service Mesh idea. Compare to the Service Mesh, there are three factors need to be considered:
* Service discovery
We can leverage istio as the control panel, to define services in kubernetes and use istio to define the service discovery rule. The service is defined base on the deployment then we are able to know the entry point(address/port).
* Data communication
We can leverage our edgehub act like envoy to proxy the service communication. By doing that we need to add other protocol support in edgehub and find a way to let the applications know the service address. On cloud, user can use DNS or environment variable to visit another service address. But on edge, we need to consider whether we can use the same mechanism. 

**Why is this needed**:
Edge node is more and more powful to run a big distributed system. It is import to support such distribution system running cross edges

**Comment by CindyXing** [comment]
I think another benefit for this feature is performance and autonomy. With edge nodes being able to communicate each other, network latency can be reduced given it doesn't need to go through the cloud side anymore. This reduces the bandwidth load on cloud side. And enable further autonomy on edge side.  

The challenge is enable software defined network connectivity at lower level especially when there is IP overlap between nodes.

**Comment by qizha** [comment]
We can leverage some P2P techniques for the communication itself, like UDP Hole

**Comment by mryalamanchi** [comment]
@qizha I think you should checkout WAMP protocol. It's developed purely from P2P perspective.
It already supports a lot of rich features which you are trying to achieve. I can help you with it.

https://wamp-proto.org/
https://wamp-proto.org/_static/gen/wamp_latest.html
