### ISSUE TITLE
Cannot connect to cloudcore in release-1.3

### ISSUE THREAD

**Issue by varunshajimwang** [kubeedge/kubeedge#1726]
**What happened**:
Trying to configure edgecore manually to cloudcore in amazon linux 2 . 
copies across the certificates. added the ip for cloudcore in edgecore configuration
**What you expected to happen**:
expected the nodes to get registered
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: error log
I0523 13:07:11.022009   11187 server.go:35] starting to listen read-only on 127.0.0.1:10350
I0523 13:07:11.022749   11187 server.go:354] Adding debug handlers to kubelet server.
I0523 13:07:11.024285   11187 desired_state_of_world_populator.go:138] Desired state populator starts to run
I0523 13:07:11.035837   11187 edged_status.go:392] Attempting to register node ip-10-10-11-205.ap-southeast-2.compute.internal
I0523 13:07:11.224672   11187 reconciler.go:156] Reconciler: start to sync state
E0523 13:07:15.934138   11187 ws.go:79] dial websocket error(x509: cannot validate certificate for 10.10.10.85 because it doesn't contain any IP SANs), response message:
E0523 13:07:15.934169   11187 websocket.go:90] Init websocket connection failed x509: cannot validate certificate for 10.10.10.85 because it doesn't contain any IP SANs
E0523 13:07:20.939868   11187 ws.go:79] dial websocket error(x509: cannot validate certificate for 10.10.10.85 because it doesn't contain any IP SANs), response message:
E0523 13:07:20.939899   11187 websocket.go:90] Init websocket connection failed x509: cannot validate certificate for 10.10.10.85 because it doesn't contain any IP SANs
I0523 13:07:21.021149   11187 process.go:675] get a message {Header:{ID:d6974c85-269a-45fa-9f0a-5f8aa3faaf31 ParentID: Timestamp:1590239241021 ResourceVersion: Sync:false} Router:{Source:edged Group:edged Operation:query Resource:default/pod} Content:<nil>}
I0523 13:07:21.021359   11187 edged.go:1008] result content is []
E0523 13:07:25.945272   11187 ws.go:79] dial websocket error(x509: cannot validate certificate for 10.10.10.85 because it doesn't contain any IP SANs), response message:
E0523 13:07:25.945305   11187 websocket.go:90] Init websocket connection failed x509: cannot validate certificate for 10.10.10.85 because it doesn't contain any IP SANs

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:

**EdgeSide Environment**:
Both in same subnet in AWS
All the ports are accessible. tested via telnet.

**Comment by varunshajimwang** [comment]
i couldn't find in doc anywhere how i add the IP SANS to the certificate. I used the default script in 
./build/tools/certgen.sh .
I can connect using kubectl and get node status from the node.

**Comment by varunshajimwang** [comment]
kubeadm never works and says incorrect OS. hence had to do manual setup

**Comment by varunshajimwang** [comment]
If it try the approach of not adding the certs to the /etc/kubeedge/{cd,certs} then cloudcore doesn't start. It only start if I add the certs n there. the doc sin release 1.3 says not to add certs . but that way cloudcore doesn't works at all.

**Comment by varunshajimwang** [comment]
[root@ip-10-10-10-85 ec2-user]# cloudcore --version
KubeEdge v1.3.0-beta.0.35+762659a76da5c6

**Comment by varunshajimwang** [comment]
phew!! checked the code.. and found i have to remove the certs manually from k8s - [root@ip-10-10-10-85 ec2-user]# kubectl get secret -n kubeedge
NAME                  TYPE                                  DATA   AGE
casecret              Opaque                                2      3h27m
default-token-lsdp5   kubernetes.io/service-account-token   3      3h27m
tokensecret           Opaque                                1      3h27m

. now cloudcore started working.

**Comment by varunshajimwang** [comment]
got it working except the kube-flannel-ds-amd64-s65kh in the edge node is shown as failing.

**Comment by varunshajimwang** [comment]
had to remove flannel and reapply 
kubectl delete daemonset --selector=app=flannel -n kube-system
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml.
Now everything is good....

**Comment by daixiang0** [comment]
@varunshajimwang cool~

**Comment by guanzydev** [comment]
self issued certificate return error：

E0525 14:40:03.795263   29818 server.go:235] failed to sign a certificate, error: failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: length too large
F0525 14:40:03.795288   29818 cloudhub.go:70] failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: length too large

**Comment by fisherxu** [comment]
@guanzydev Ref: https://github.com/kubeedge/kubeedge/issues/1714

**Comment by fisherxu** [comment]
Seems the issue has resolved, close it now :)
/close
