### ISSUE TITLE
You must set CLOUDCOREIPS Env

### ISSUE THREAD

**Issue by CocoPapa1995** [kubeedge/kubeedge#1727]
**What happened**:
I have set the CLOUDCOREIPS env:
echo $CLOUDCOREIPS
192.168.6.200

**but when i execute this instruction：**
sudo $GOPATH/src/github.com/kubeedge/kubeedge/build/tools/certgen.sh stream
You must set CLOUDCOREIPS Env,The environment variable is set to specify the IP addresses of all cloudcore
If there are more than one IP need to be separated with space.

**Those errors happened**

**What you expected to happen**:
work successfully

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
v1.3

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by daixiang0** [comment]
I think it is a shell issue, with sudo, your environment values set by export does not pass to sudo, you can try `sudo -E` to pass the env.

**Comment by CocoPapa1995** [comment]
> I think it is a shell issue, with sudo, your environment values set by export does not pass to sudo, you can try `sudo -E` to pass the env.

thank you very much！
