### ISSUE TITLE
 Ca and CaKey don't exist, and will be signed by cloudcore，TLSCertFile and TLSPrivateKeyFile don't exist, and will be signed by cloudcore，failed to sign a certificate, error: failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: length too large， failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: length too large。

### ISSUE THREAD

**Issue by yzhao66** [kubeedge/kubeedge#1729]
**What happened**:
when i  cat /var/log/kubeedge/cloudcore.log
![image](https://user-images.githubusercontent.com/44268973/82792677-52d80200-9ea2-11ea-9ab4-85cad615c371.png)

**What you expected to happen**:
cloudcore running is healthy
**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.0
**CloudSide Environment**:1.3.0
- Hardware configuration (e.g. `lscpu`):
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
每个核的线程数：1
每个座的核数：  4
Socket(s):             4
NUMA 节点：         1
Model name:            phytium FT1500a
BogoMIPS:              3594.24
NUMA node0 CPU(s):     0-15
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux pk5 4.4.58-20180615.kylin.server.YUN+-generic #kylin SMP Tue Jul 10 14:55:31 CST 2018 aarch64 aarch64 aarch64 GNU/Linux
- Go version (e.g. `go version`): 
go version go1.13.11 linux/arm64
- Others:

**EdgeSide Environment**:1.3.0
- edgecore version (e.g. `edgecore --version`):
2020-05-25 16:15:41.480517 I | INFO: Install client plugin, protocol: rest
2020-05-25 16:15:41.480761 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.3.0-dirty
- Hardware configuration (e.g. `lscpu`):
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
每个核的线程数：1
每个座的核数：  4
Socket(s):             4
NUMA 节点：         1
Model name:            phytium FT1500a
BogoMIPS:              3594.24
NUMA node0 CPU(s):     0-15
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux pk5 4.4.58-20180615.kylin.server.YUN+-generic #kylin SMP Tue Jul 10 14:55:31 CST 2018 aarch64 aarch64 aarch64 GNU/Linux
- Go version (e.g. `go version`): 
go version go1.13.11 linux/arm64
- Others:

**Comment by fisherxu** [comment]
Ref: https://github.com/kubeedge/kubeedge/issues/1714

/close
