### ISSUE TITLE
edge: Init websocket connection failed x509: cannot validate certificate for 10.0.10.35 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by yzhao66** [kubeedge/kubeedge#1732]
**What happened**:

**What you expected to happen**:
  edge is running healthy
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.0
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Socket(s):             4
NUMA 节点：         1
Model name:            phytium FT1500a
BogoMIPS:              3594.24
NUMA node0 CPU(s):     0-15
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux pk6 4.4.58-20180615.kylin.server.YUN+-generic #kylin SMP Tue Jul 10 14:55:31 CST 2018 aarch64 aarch64 aarch64 GNU/Linux
- Go version (e.g. `go version`): 
go version go1.13.11 linux/arm64
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
1.3.0
- Hardware configuration (e.g. `lscpu`):
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Socket(s):             4
NUMA 节点：         1
Model name:            phytium FT1500a
BogoMIPS:              3594.24
NUMA node0 CPU(s):     0-15
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux pk6 4.4.58-20180615.kylin.server.YUN+-generic #kylin SMP Tue Jul 10 14:55:31 CST 2018 aarch64 aarch64 aarch64 GNU/Linux
- Go version (e.g. `go version`): 
go version go1.13.11 linux/arm64
- Others:

**Comment by yzhao66** [comment]
![image](https://user-images.githubusercontent.com/44268973/82882367-8cc50900-9f73-11ea-9634-b6a954dd8726.png)

**Comment by luogangyi** [comment]
try this
```
kubectl delete secret casecret -nkubeedge
kubectl delete secret cloudcoresecret -nkubeedge
mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak
mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
```
then restart cloudcore and edgecore

**Comment by yzhao66** [comment]
> try this
> 
> ```
> kubectl delete secret casecret -nkubeedge
> kubectl delete secret cloudcoresecret -nkubeedge
> mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak
> mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
> ```
> 
> then restart cloudcore and edgecore



> try this
> 
> ```
> kubectl delete secret casecret -nkubeedge
> kubectl delete secret cloudcoresecret -nkubeedge
> mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak
> mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
> ```
> 
> then restart cloudcore and edgecore

i hava done this process ,but still hava problems in edge .

details:
I0527 09:49:35.547777   23881 reconciler.go:156] Reconciler: start to sync state
E0527 09:49:40.233945   23881 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message: 
E0527 09:49:40.234032   23881 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
E0527 09:49:45.235023   23881 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message: 
E0527 09:49:45.235109   23881 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
I0527 09:49:45.447616   23881 process.go:675] get a message {Header:{ID:821bcb3e-b1c3-4239-8b81-8abf86a904ab ParentID: Timestamp:1590544185447 ResourceVersion: Sync:false} Router:{Source:edged Group:edged Operation:query Resource:default/pod} Content:<nil>}
I0527 09:49:45.447962   23881 edged.go:1008] result content is []
E0527 09:49:50.236086   23881 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message: 
E0527 09:49:50.236190   23881 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
E0527 09:49:55.237230   23881 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message: 
E0527 09:49:55.237322   23881 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
E0527 09:50:00.237619   23881 edgehub.go:96] connection error, try again after 60s: max retry count reached when connecting to cloud



![image](https://user-images.githubusercontent.com/44268973/82968760-a4969e80-a000-11ea-8b2c-67d3008d1e4e.png)

**Comment by luogangyi** [comment]
@yzhao66 not sure what version you are using.
recently, kubeedge team change the tls cypher from rsa to ecdsa and may cause some incompatibility.
I suggest upgrade both cloudcore and  edgecore to master branch, and try again.

**Comment by yzhao66** [comment]
> > try this
> > ```
> > kubectl delete secret casecret -nkubeedge
> > kubectl delete secret cloudcoresecret -nkubeedge
> > mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak
> > mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
> > ```
> > 
> > 
> > then restart cloudcore and edgecore
> 
> > try this
> > ```
> > kubectl delete secret casecret -nkubeedge
> > kubectl delete secret cloudcoresecret -nkubeedge
> > mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak
> > mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
> > ```
> > 
> > 
> > then restart cloudcore and edgecore
> 
> i hava done this process ,but still hava problems in edge .
> 
> details:
> I0527 09:49:35.547777 23881 reconciler.go:156] Reconciler: start to sync state
> E0527 09:49:40.233945 23881 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
> E0527 09:49:40.234032 23881 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
> E0527 09:49:45.235023 23881 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
> E0527 09:49:45.235109 23881 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
> I0527 09:49:45.447616 23881 process.go:675] get a message {Header:{ID:821bcb3e-b1c3-4239-8b81-8abf86a904ab ParentID: Timestamp:1590544185447 ResourceVersion: Sync:false} Router:{Source:edged Group:edged Operation:query Resource:default/pod} Content:}
> I0527 09:49:45.447962 23881 edged.go:1008] result content is []
> E0527 09:49:50.236086 23881 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
> E0527 09:49:50.236190 23881 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
> E0527 09:49:55.237230 23881 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
> E0527 09:49:55.237322 23881 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
> E0527 09:50:00.237619 23881 edgehub.go:96] connection error, try again after 60s: max retry count reached when connecting to cloud
> 
> ![image](https://user-images.githubusercontent.com/44268973/82968760-a4969e80-a000-11ea-8b2c-67d3008d1e4e.png)

i

**Comment by yzhao66** [comment]
> @yzhao66 not sure what version you are using.
> recently, kubeedge team change the tls cypher from rsa to ecdsa and may cause some incompatibility.
> I suggest upgrade both cloudcore and edgecore to master branch, and try again.

i set up kubeedge as kubeedge.io's documents(git clone https://github.com/kubeedge/kubeedge.git $GOPATH/src/github.com/kubeedge/kubeedge
), i think the kubeedge version i hava clone is the master.

**Comment by luogangyi** [comment]
```
openssl s_client  -connect CLOUDCOREIP:10000 -cert /etc/kubeedge/certs/server.crt -key /etc/kubeedge/certs/server.key -CAfile /etc/kubeedge/ca/rootCA.crt -state
```
please run this in edge node, and post the result.

**Comment by fisherxu** [comment]
You need to add the `advertise-address` to cloudcore, which will be add to SANs in cloud certs.
Ref:
https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_configure.md#modification-in-cloudcoreyaml
https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_keadm.md#setup-cloud-side-kubeedge-master-node

**Comment by fisherxu** [comment]
The default value of advertise-address is the Local IP at host, if the exposed ip for cloudcore is not the local IP at host, you need change it through advertise-address.

**Comment by yzhao66** [comment]
> openssl s_client  -connect CLOUDCOREIP:10000 -cert /etc/kubeedge/certs/server.crt -key /etc/kubeedge/certs/server.key -CAfile /etc/kubeedge/ca/rootCA.crt -state

edge/ca/rootCA.crt -state
CONNECTED(00000003)
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
SSL3 alert read:fatal:handshake failure
SSL_connect:error in SSLv2/v3 read server hello A
548095960864:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1590556328
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
![image](https://user-images.githubusercontent.com/44268973/82980340-c8b3a900-a01b-11ea-9ddc-8c02ed429135.png)

**Comment by yzhao66** [comment]
> https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_keadm.md#setup-cloud-side-kubeedge-master-node




> You need to add the `advertise-address` to cloudcore, which will be add to SANs in cloud certs.
> Ref:
> https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_configure.md#modification-in-cloudcoreyaml
> https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_keadm.md#setup-cloud-side-kubeedge-master-node







when i use init command in cloudside,i had add the 'advertise-address'.

kubeedge configfile as below
[configfile.zip](https://github.com/kubeedge/kubeedge/files/4686626/configfile.zip)

**Comment by luogangyi** [comment]
looks same as #1699 .
It solved by update to kubeedge and remove old certs
can you check again your version?
run
```
kubectl get nodes
cloudcore --version
edgecore --version
```

**Comment by yzhao66** [comment]
> looks same as #1699 .
> It solved by update to kubeedge and remove old certs
> can you check again your version?
> run
> 
> ```
> kubectl get nodes
> cloudcore --version
> edgecore --version
> ```

kubectl get nodes
![image](https://user-images.githubusercontent.com/44268973/82983555-e33d5080-a022-11ea-9730-8b1ab853e90d.png)

cloudcore --version
![image](https://user-images.githubusercontent.com/44268973/82983682-21d30b00-a023-11ea-9799-17c608046ac8.png)

edgecore --version
![image](https://user-images.githubusercontent.com/44268973/82983720-31eaea80-a023-11ea-9652-b3bfe2b7eda3.png)

**Comment by luogangyi** [comment]
I think it is becasue you use the updated cloudcore but v1.3.0 edgecore, they are incompatible.
you can compile edgecore manually,
see https://docs.kubeedge.io/en/latest/setup/kubeedge_install_source.html

**Comment by markwangC** [comment]
> 
> 
> I think it is becasue you use the updated cloudcore but v1.3.0 edgecore, they are incompatible.
> you can compile edgecore manually,
> see https://docs.kubeedge.io/en/latest/setup/kubeedge_install_source.html

i'm suffering the same issue here. I'm using the master codes, compiled cloudcore and edgecore manually.

**Comment by luogangyi** [comment]
@yzhao66 is it ok now?
@markwangC I have try latest code and bring up a new cluster, no error happens.
can you show this
```
kubectl get nodes
cloudcore --version
edgecore --version

kubectl delete secret casecret -nkubeedge
kubectl delete secret cloudcoresecret -nkubeedge
# both cloud and edge side
mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak 
mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
```

**Comment by markwangC** [comment]
> 
> 
> @yzhao66 is it ok now?
> @markwangC I have try latest code and bring up a new cluster, no error happens.
> can you show this
> 
> ```
> kubectl get nodes
> cloudcore --version
> edgecore --version
> 
> kubectl delete secret casecret -nkubeedge
> kubectl delete secret cloudcoresecret -nkubeedge
> # both cloud and edge side
> mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak 
> mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
> ```

root@wcl-virtual-machine-host:/etc/kubeedge# kubectl get nodes
NAME                       STATUS    ROLES                      AGE       VERSION
wcl-virtual-machine-host   Ready     controlplane,etcd,worker   17h       v1.17.5
root@wcl-virtual-machine-host:/etc/kubeedge# ~/kubeedge/cloudcore --version
KubeEdge v0.0.0-master+$Format:%h$
root@wcl-virtual-machine-host:/etc/kubeedge#
root@wcl-virtual-machine-host:/etc/kubeedge# kubectl delete secret casecret -nkubeedge
secret "casecret" deleted
root@wcl-virtual-machine-host:/etc/kubeedge# kubectl delete secret cloudcoresecret -nkubeedge
Error from server (NotFound): secrets "cloudcoresecret" not found
root@wcl-virtual-machine-host:/etc/kubeedge#
root@wcl-virtual-machine-host:/etc/kubeedge# mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
root@wcl-virtual-machine-host:/etc/kubeedge# mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak





root@edge-node:/etc/kubeedge# kubectl delete secret cloudcoresecret -nkubeedge
Error from server (NotFound): secrets "cloudcoresecret" not found
root@edge-node:/etc/kubeedge# kubectl delete secret casecret -nkubeedge
Error from server (NotFound): secrets "casecret" not found
root@edge-node:/etc/kubeedge# kubectl get node
NAME                       STATUS    ROLES                      AGE       VERSION
wcl-virtual-machine-host   Ready     controlplane,etcd,worker   9h        v1.17.5
root@edge-node:/etc/kubeedge# mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak
root@edge-node:/etc/kubeedge# mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
root@edge-node:/etc/kubeedge# ~/kubeedge/edgecore --version
2020-05-28 00:48:51.097920 I | INFO: Install client plugin, protocol: rest
2020-05-28 00:48:51.098093 I | INFO: Installed service discovery plugin: edge
KubeEdge v0.0.0-master+$Format:%h$

**Comment by yzhao66** [comment]
> @yzhao66 is it ok now?
> @markwangC I have try latest code and bring up a new cluster, no error happens.
> can you show this
> 
> ```
> kubectl get nodes
> cloudcore --version
> edgecore --version
> 
> kubectl delete secret casecret -nkubeedge
> kubectl delete secret cloudcoresecret -nkubeedge
> # both cloud and edge side
> mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak 
> mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
> ```
when i make all WHAT=edgecore

the report:
![image](https://user-images.githubusercontent.com/44268973/83094024-44bcf800-a0d3-11ea-9695-ada01b81a239.png)

**Comment by huang339** [comment]
I use the latest code and I meet the error,too

**Comment by luogangyi** [comment]
my colleague meet the same problem.
he solved this by delete ca and certs both cloud and edge side and restart .
you can try, @huang339

**Comment by huang339** [comment]
the problem could not be resolved even  ca and certs was deleted, there must be some configuration is missed, I home someone give me a detail of configuration about kubeedge1.3 .

**Comment by collinarnett** [comment]
Same issue using 1.3.1

**Comment by yeganeahmadnejad** [comment]
same issue version 1.5
please give a solution

**Comment by saraAlizadeh** [comment]
same issue on version 1.5.
tried this: https://codeleading.com/article/86244737707/
and the hints here.
need help

**Comment by koulq** [comment]
> You need to add the `advertise-address` to cloudcore, which will be add to SANs in cloud certs. Ref: https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_configure.md#modification-in-cloudcoreyaml https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_install_keadm.md#setup-cloud-side-kubeedge-master-node

@fisherxu The domain name I use also has this problem、
![image](https://user-images.githubusercontent.com/18571340/188858657-79b53121-f74d-40f1-9229-60bbd2294216.png)
