### ISSUE TITLE
edgecore can not join the cluster

### ISSUE THREAD

**Issue by CocoPapa1995** [kubeedge/kubeedge#1733]
**What happened**:

tokendata: NDg5MmZmM2Y2MmU2MTM2NWQwZTAwMTQ4MmRhMWM5NTFlYjcwN2I5YWUzZjM3YTg3ZTAzNTJmODdjM2EwNDFmYy5leUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKbGVIQWlPakUxT1RBMU56QTRNVEI5LnpPdVVKSm9rMVR0VXMxcHJjRV9jTWJtdzlqeW5YUmVsQlRRMURhWDhoRDA=

**and i use this command:**
echo NDg5MmZmM2Y2MmU2MTM2NWQwZTAwMTQ4MmRhMWM5NTFlYjcwN2I5YWUzZjM3YTg3ZTAzNTJmODdjM2EwNDFmYy5leUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKbGVIQWlPakUxT1RBMU56QTRNVEI5LnpPdVVKSm9rMVR0VXMxcHJjRV9jTWJtdzlqeW5YUmVsQlRRMURhWDhoRDA= |base64 -d

**the result is:**
4892ff3f62e61365d0e001482da1c951eb707b9ae3f37a87e0352f87c3a041fc.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTA1NzA4MTB9.zOuUJJok1TtUs1prcE_cMbmw9jynXRelBTQ1DaX8hD0

**but after i add it in the edgecore.yaml:**
edgeHub:
    token: 4892ff3f62e61365d0e001482da1c951eb707b9ae3f37a87e0352f87c3a041fc.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTA1NzA4MTB9.zOuUJJok1TtUs1prcE_cMbmw9jynXRelBTQ1DaX8hD0

**when i start edgecore, it happens:**
failed to apply for edge certificate, error: token credentials are in the wrong format

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

how can i make it work successfully？

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
v1.3.0

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by luogangyi** [comment]
try this
```
kubectl delete secret casecret -nkubeedge
kubectl delete secret cloudcoresecret -nkubeedge
mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak
mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
```
then restart cloudcore and edgecore

**Comment by ls889** [comment]
error: token credentials are in the wrong format means that the token loaded by edgecore don't have the correct format(four parts with three dots).but your token format is correct.
so maybe the token field in your edgecore has some format problems, causing edgecore read the wrong token.

try this format, keep one line.
```
 token: 4892ff3f62e61365d0e001482da1c951eb707b9ae3f37a87e0352f87c3a041fc.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTA1NzA4MTB9.zOuUJJok1TtUs1prcE_cMbmw9jynXRelBTQ1DaX8hD0
```

**Comment by CocoPapa1995** [comment]
> try this
> 
> ```
> kubectl delete secret casecret -nkubeedge
> kubectl delete secret cloudcoresecret -nkubeedge
> mv /etc/kubeedge/ca  /etc/kubeedge/ca.bak
> mv  /etc/kubeedge/certs /etc/kubeedge/certs.bak
> ```
> 
> then restart cloudcore and edgecore

i tried these step，but it still dosen‘t work

**Comment by CocoPapa1995** [comment]
> error: token credentials are in the wrong format means that the token loaded by edgecore don't have the correct format(four parts with three dots).but your token format is correct.
> so maybe the token field in your edgecore.yaml has some format problems, causing edgecore read the wrong token.
> 
> try this format, keep one line.
> 
> ```
>  token: 4892ff3f62e61365d0e001482da1c951eb707b9ae3f37a87e0352f87c3a041fc.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTA1NzA4MTB9.zOuUJJok1TtUs1prcE_cMbmw9jynXRelBTQ1DaX8hD0
> ```

i tried these step，but it still dosen‘t work

**Comment by ls889** [comment]
> > error: token credentials are in the wrong format means that the token loaded by edgecore don't have the correct format(four parts with three dots).but your token format is correct.
> > so maybe the token field in your edgecore.yaml has some format problems, causing edgecore read the wrong token.
> > try this format, keep one line.
> > ```
> >  token: 4892ff3f62e61365d0e001482da1c951eb707b9ae3f37a87e0352f87c3a041fc.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTA1NzA4MTB9.zOuUJJok1TtUs1prcE_cMbmw9jynXRelBTQ1DaX8hD0
> > ```
> 
> i tried these step，but it still dosen‘t work

Can you post edgecore.yaml?

**Comment by CocoPapa1995** [comment]
> > > error: token credentials are in the wrong format means that the token loaded by edgecore don't have the correct format(four parts with three dots).but your token format is correct.
> > > so maybe the token field in your edgecore.yaml has some format problems, causing edgecore read the wrong token.
> > > try this format, keep one line.
> > > ```
> > >  token: 4892ff3f62e61365d0e001482da1c951eb707b9ae3f37a87e0352f87c3a041fc.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTA1NzA4MTB9.zOuUJJok1TtUs1prcE_cMbmw9jynXRelBTQ1DaX8hD0
> > > ```
> > 
> > 
> > i tried these step，but it still dosen‘t work
> 
> Can you post edgecore.yaml?

i tried again and it begin working！！！
thank you very much
