### ISSUE TITLE
failed to get edge certificate from the cloudcore, error: Get https://10.10.10.16:10002/edge.crt: x509: cannot validate certificate for 10.10.10.16 because it doesn't contain any IP SANs F0527 18:23:46.255993     527 edgehub.go:76] failed to apply for edge certificate, error: failed to get edge certificate from the cloudcore, error: Get https://10.10.10.16:10002/edge.crt: x509: cannot validate certificate for 10.10.10.16 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by varunshajimwang** [kubeedge/kubeedge#1737]
Again this error came.. tried all debug approach.. edge core cannot just going.

**Comment by varunshajimwang** [comment]
recreated the token.. and it worked.

**Comment by fisherxu** [comment]
> recreated the token.. and it worked.

restart the cloudcore？

**Comment by varunshajimwang** [comment]
yeah.. but now new error
I0527 18:41:50.665377    2674 edged_status.go:392] Attempting to register node raspberrypi
E0527 18:41:54.981665    2674 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
E0527 18:41:54.981927    2674 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
E0527 18:42:00.190359    2674 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
E0527 18:42:00.190737    2674 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
I0527 18:42:00.547943    2674 process.go:675] get a message {Header:{ID:48fd9fac-0870-452f-8bbb-3efa226babca ParentID: Timestamp:1590568920547 ResourceVersion: Sync:false} Router:{Source:edged Group:edged Operation:query Resource:default/pod} Content:<nil>}
I0527 18:42:00.549192    2674 edged.go:1008] result content is []
E0527 18:42:05.429369    2674 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
E0527 18:42:05.429617    2674 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
E0527 18:42:10.689358    2674 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
E0527 18:42:10.689539    2674 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
E0527 18:42:15.689790    2674 edgehub.go:96] connection error, try again after 60s: max retry count reached when connecting to cloud
-

**Comment by varunshajimwang** [comment]
Is this relating to https://github.com/kubeedge/kubeedge/issues/1699 .
I am using release-1.3.
I got it working last day on x86 node. This tie the node is arm .. does that make a difference ?

**Comment by varunshajimwang** [comment]
root@raspberrypi:/home/pi/mwang/edgecore# edgecore --version
2020-05-27 19:35:42.631829 I | INFO: Install client plugin, protocol: rest
2020-05-27 19:35:42.632943 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.3.0-beta.0.35+762659a76da5c6-dirty

[root@ip-10-10-10-16 ec2-user]# cloudcore version
I0527 09:36:15.806068   26768 server.go:58] Version: v1.3.0-beta.0.35+762659a76da5c6

**Comment by varunshajimwang** [comment]
Just confirmed that - 
The same release in x86 server works and successfully registers the node. But in RPI (armV6) fails. And the binary created shows version as '<release tag>-dirty' . Does it mean that test for arm and hence binary get version as dirty ? I use the same release for both builds.Can i take the latest build for edge core in raspberry or should i also upgrade cloudcore ?

**Comment by varunshajimwang** [comment]
tested with latest master for edgecore in raspberry and still the same error.this time the build binary don't have the 'dirty' in the version . Still errors are the same 

> I0527 21:26:06.835507   17877 process.go:669] get a message {Header:{ID:b5f56346-089d-459f-97d3-59d18e069c96 ParentID: Timestamp:1590578766835 ResourceVersion: Sync:false} Router:{Source:edged Group:edged Operation:query Resource:default/pod} Content:<nil>}
I0527 21:26:06.836521   17877 edged.go:1006] result content is []
E0527 21:26:11.700505   17877 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
E0527 21:26:11.700667   17877 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure
E0527 21:26:17.035069   17877 ws.go:79] dial websocket error(remote error: tls: handshake failure), response message:
E0527 21:26:17.035252   17877 websocket.go:90] Init websocket connection failed remote error: tls: handshake failure

**Comment by varunshajimwang** [comment]
Using openssl command

`openssl s_client -servername masternode1 -connect 10.10.10.16:10000 -cert /etc/kubeedge/certs/server.crt -key /etc/kubeedge/certs/server.key -CAfile /etc/kubeedge/ca/rootCA.crt -state
CONNECTED(00000003)
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hell
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS read server hello
SSL_connect:TLSv1.3 read encrypted extensions
SSL_connect:SSLv3/TLS read server certificate request`

`   Start Time: 1590578964
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
SSL_connect:SSLv3/TLS read server session ticket
read R BLOCK`

Looks like no issue with certs . It certainly is a code issue.. and only happens in arm builds.

**Comment by varunshajimwang** [comment]
I moved both cloudcore and edgecore to master release - kubeedge-v1.3.0-36+b6dea75ec7ee92

cloudcore -KubeEdge v1.3.0-36+b6dea75ec7ee92-dirty .
Now it works. Better take a release or a tag , so that something stable is there to murk around with

**Comment by fisherxu** [comment]
> cloudcore -KubeEdge v1.3.0-36+b6dea75ec7ee92-dirty .
Now it works. Better take a release or a tag , so that something stable is there to murk around with

Yes, will take the `1.3.1` tag this week

**Comment by huang339** [comment]
> Again this error came.. tried all debug approach.. edge core cannot just going.

have you resoved the problem? I met the same problem,please give me some information

**Comment by magnate3** [comment]
@fisherxu  @varunshajimwang  how did you solve the proble in aarch64?

The same problem happened in my e aarch64nvironment.
root@cloud:~/cmd# grep error edgecore.log 
E0409 19:28:46.981472  205405 proxy.go:169] [EdgeMesh] failed to delete iptables chain, err: error deleting chain "EDGE-MESH": exit status 1: iptables: Too many links.
E0409 19:28:46.992042  205405 dns.go:102] [EdgeMesh] dns server listen on 172.17.0.1:53 error: listen udp 172.17.0.1:53: bind: address already in use
F0409 19:28:47.004970  205405 certmanager.go:91] Error: failed to get edge certificate from the cloudcore, error: Get "https://10.10.16.82:10002/edge.crt": x509: cannot validate certificate for 10.10.16.82 because it doesn't contain any IP SANs
github.com/eclipse/paho%2emqtt%2egolang.errorWatch(0x40005561e0)
github.com/eclipse/paho%2emqtt%2egolang.errorWatch(0x4000948000)
root@cloud:~/cmd# uname -a
Linux cloud 5.5.19-050519-generic #202004210831 SMP Tue Apr 21 08:49:56 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
