### ISSUE TITLE
Add script to install KubeEdge cloud and edge side

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1741]
## Project Description
Write a script to install KubeEdge cloud and edge with one click, including K8s, Runtime.
Note: Need more discussion.

## Difficulty
low

## Mentor
Fei Xu(@fisherxu): fisherxu1@gmail.com

## Output
- Write a script to install KubeEdge 

## Tech. Requirement
- Shell
- Kubernetes
- KubeEdge

## Related Repo
- https://github.com/kubeedge/kubeedge

**Comment by markwangC** [comment]
Could you pls considering to on click install in the restricted network ? We can download an offline package that contains all the necessary materials, then upload it to the lab which is restricted to internet.

**Comment by daixiang0** [comment]
Now we have localup script, close.
/close
