### ISSUE TITLE
Build an AI example to run AI application on KubeEdge platform

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#1743]
## Project Description
Build a sample example to run AI application on KubeEdge platform, using the device API, and ideally running inference on the edge and training on the cloud, showing cloud-edge collaboration.

## Difficulty
medium

## Mentor
Kevin Wang(@kevin-wangzefeng): kevinwzf0126@gmail.com

## Output
- Build an example to run AI application
- The device API 

## Tech. Requirement
- KubeEdge
- AI technology, such as face recognition

## Related Repo
- https://github.com/kubeedge/kubeedge
- https://github.com/kubeedge/examples

**Comment by Zhengmao-Wang** [comment]
I’m really interested in this program. I have a knowledge of golang,docker and Kubernetes  If I want to take part in this, what should I prepare?

**Comment by xixi-A** [comment]
> 我对这个程序真的很感兴趣。我对golang，docker和Kubernetes有所了解。如果我想参加，应该做些什么准备？

You can refer : 
https://github.com/kubeedge/community/blob/master/OpenSourcePromotionPlan2020/summer2020-cn.md#%E4%BB%BB%E5%8A%A1%E5%88%97%E8%A1%A8

**Comment by lzt-pro** [comment]
Hello, I want to choose this course, And I want to know more details, so that I can make my schedule. Further more, I have send an email to Mr wang.
