### ISSUE TITLE
cloudcore cannot generate certificate

### ISSUE THREAD

**Issue by coderkk** [kubeedge/kubeedge#1744]
**What happened**:
I have tried `keadm init --kubeedge-version=1.3.0  --kube-config=/root/.kube/config --advertise-address 194.55.119.121` but the cloudcore cannot generate certificate

**What you expected to happen**:
I expected it will generate cerificate in `/etc/kubeedge/ca` and `/etc/kubeedge/certs`

**Comment by XJangel** [comment]
@coderkk  In KubeEdge 1.3, the certificate won't be saved locally. It will be in the secret `cloucoresecret` of `kubeedge` namespace.

**Comment by fisherxu** [comment]
> @coderkk In KubeEdge 1.3, the certificate won't be saved locally. They will be in the secret cloudcoresecret and casecret of kubeedge namespace.

It's right, and why do you expected to generate cerificate in the host?

**Comment by fisherxu** [comment]
@coderkk

**Comment by coderkk** [comment]
Because when cloudcore start, it has error from the log

```
I0525 14:04:51.437232   26451 server.go:186] Ca and CaKey don't exist, and will be signed by cloudcore
I0525 14:04:51.458595   26451 server.go:229] TLSCertFile and TLSPrivateKeyFile don't exist, and will be signed by cloudcore
I0525 14:04:51.470908   26451 server.go:44] start unix domain socket server
I0525 14:04:51.471873   26451 server.go:62] Startting cloudhub websocket server
```

Seen like it cannot read the certificates.

**Comment by fisherxu** [comment]
The log shows that cloudcore is running well, cloudcore supports manually specify certs, and if users haven't specified, it will signed the certs automatically. @coderkk

**Comment by coderkk** [comment]
My Edgecore received this error
```
E0528 13:08:26.649837   21745 helper.go:34] Failed to unmarshal configfile /etc/kubeedge/config/edgecore.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Edged.modules.edged.volumeStatsAggPeriod of type time.Duration
F0528 13:08:26.649857   21745 server.go:64] error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Edged.modules.edged.volumeStatsAggPeriod of type time.Duration

```

**Comment by coderkk** [comment]
My cloudcore stuck at

```
I0528 13:22:54.052734   12558 server.go:186] Ca and CaKey don't exist, and will be signed by cloudcore
I0528 13:22:54.065203   12558 server.go:229] TLSCertFile and TLSPrivateKeyFile don't exist, and will be signed by cloudcore
I0528 13:22:54.099520   12558 server.go:44] start unix domain socket server
I0528 13:22:54.099764   12558 uds.go:72] listening on: //var/lib/kubeedge/kubeedge.sock
I0528 13:22:54.116767   12558 server.go:62] Startting cloudhub websocket server
I0528 13:22:55.938989   12558 upstream.go:61] Start upstream devicecontroller
```

**Comment by XJangel** [comment]
@coderkk It's normal log, not stuck.

**Comment by XJangel** [comment]
> My Edgecore received this error
> 
> ```
> E0528 13:08:26.649837   21745 helper.go:34] Failed to unmarshal configfile /etc/kubeedge/config/edgecore.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Edged.modules.edged.volumeStatsAggPeriod of type time.Duration
> F0528 13:08:26.649857   21745 server.go:64] error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Edged.modules.edged.volumeStatsAggPeriod of type time.Duration
> ```

can u show us your edgecore.yaml?

**Comment by coderkk** [comment]
I follow this document, it solve my problem https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_configure.md

Thank you.

**Comment by su600** [comment]
> I follow this document, it solve my problem https://github.com/kubeedge/kubeedge/blob/master/docs/setup/kubeedge_configure.md
> 
> Thank you.

Hi, I have same problem, could please tell me how to fix this? 
I can't find kubeedge_configure.md.

**Comment by jasha64** [comment]
> @coderkk In KubeEdge 1.3, the certificate won't be saved locally. They will be in the secret `cloudcoresecret` and `casecret` of `kubeedge` namespace.

How do we (and do we need to) extract the certificate and send it to the edge?
