### ISSUE TITLE
部署好k8s和kubeedge后发现edge的log里面有错误

### ISSUE THREAD

**Issue by hzjnet** [kubeedge/kubeedge#1745]
基本状况
1 
[root@k8s-master1 kubeedge]# kubectl get nodes
NAME          STATUS     ROLES    AGE     VERSION
k8s-master1   Ready      master   46h     v1.18.3
k8s-node1     Ready      <none>   26h     v1.18.3
k8s-node2     NotReady   edge     3h42m   v1.17.1-kubeedge-v0.0.0-master+$Format:%h$

2 
[root@k8s-master1 kubeedge]# lsof -i -P|grep LISTEN
sshd       1035   root    3u  IPv4   31690      0t0  TCP *:22 (LISTEN)
sshd       1035   root    4u  IPv6   31692      0t0  TCP *:22 (LISTEN)
dnsmasq    1325 nobody    6u  IPv4   34816      0t0  TCP k8s-master1:53 (LISTEN)
kube-cont  4826   root    5u  IPv6 2854429      0t0  TCP *:10252 (LISTEN)
kube-cont  4826   root    6u  IPv4 2854435      0t0  TCP localhost.lan:10257 (LISTEN)
kube-sche  4850   root    5u  IPv6 2854380      0t0  TCP *:10251 (LISTEN)
kube-sche  4850   root    6u  IPv4 2854386      0t0  TCP localhost.lan:10259 (LISTEN)
etcd       4889   root    3u  IPv4 2853400      0t0  TCP k8s-master1:2380 (LISTEN)
etcd       4889   root    5u  IPv4 2853404      0t0  TCP localhost.lan:2379 (LISTEN)
etcd       4889   root    6u  IPv4 2853405      0t0  TCP k8s-master1:2379 (LISTEN)
etcd       4889   root   10u  IPv4 2854424      0t0  TCP localhost.lan:2381 (LISTEN)
kube-apis  4934   root    5u  IPv6 2853439      0t0  TCP *:6443 (LISTEN)
kubelet    5305   root    9u  IPv4 2857557      0t0  TCP localhost.lan:33540 (LISTEN)
kubelet    5305   root   31u  IPv6 2858206      0t0  TCP *:10250 (LISTEN)
kubelet    5305   root   38u  IPv4 2858210      0t0  TCP localhost.lan:10248 (LISTEN)
kube-prox  5610   root   11u  IPv6 2858973      0t0  TCP *:10256 (LISTEN)
kube-prox  5610   root   13u  IPv4 2860268      0t0  TCP localhost.lan:10249 (LISTEN)
cloudcore 18567   root    6u  IPv6 6375692      0t0  TCP *:10000 (LISTEN)

3 
[root@k8s-master1 kubeedge]# cat cloudcore.log |grep fail
E0528 11:19:56.365731   18567 ws.go:122] failed to read message, error: websocket: close 1006 (abnormal closure): unexpected EOF
E0528 11:20:17.323748   18567 messagehandler.go:298] fail to close connection, reason: tls: use of closed connection
以上是master上，以下是edge的node里：
root@k8s-node2:~/kubeedge# lsof -i -P               
COMMAND    PID      USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
avahi-dae  330     avahi   12u  IPv4  14359      0t0  UDP *:5353 
avahi-dae  330     avahi   13u  IPv6  14360      0t0  UDP *:5353 
avahi-dae  330     avahi   14u  IPv4  14361      0t0  UDP *:52682 
avahi-dae  330     avahi   15u  IPv6  14362      0t0  UDP *:37093 
dhcpcd     371      root   10u  IPv4  12959      0t0  UDP *:68 
mosquitto  401 mosquitto    5u  IPv4  15922      0t0  TCP *:1883 (LISTEN)
mosquitto  401 mosquitto    6u  IPv6  15923      0t0  TCP *:1883 (LISTEN)
sshd       436      root    3u  IPv4  13920      0t0  TCP *:22 (LISTEN)
sshd       436      root    4u  IPv6  16011      0t0  TCP *:22 (LISTEN)
sshd      1440      root    3u  IPv4  20656      0t0  TCP k8s-node2:22->192.168.17.66:50200 (ESTABLISHED)

root@k8s-node2:~/kubeedge# ps -ef |grep ed
root        10     2  0 10:29 ?        00:00:03 [rcu_sched]
root       393     1  0 10:29 ?        00:00:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
pi         868     1  0 10:29 ?        00:00:00 /usr/lib/menu-cache/menu-cached /run/user/1000/menu-cached-:0

问题：
root@k8s-node2:~/kubeedge# cat edgecore.log |grep fail
W0528 11:02:02.237008    3918 container_manager_linux.go:618] [ContainerManager] Failed to ensure state of "cgroupfs": failed to find container of PID 3918: cpu and memory cgroup hierarchy not unified.  cpu: /user.slice, memory: /user.slice/user-0.slice/session-c3.scope
E0528 11:02:12.441172    3918 process.go:79] failed to send message to sync keep channel
E0528 11:02:12.441253    3918 process.go:120] failed to dispatch message, discard: failed to send message to sync keep channel
E0528 11:02:12.443282    3918 process.go:79] failed to send message to sync keep channel
E0528 11:02:12.443363    3918 process.go:120] failed to dispatch message, discard: failed to send message to sync keep channel
W0528 11:19:56.231703    3918 process.go:294] distributeMsg failed: Not found action
E0528 11:19:56.251864    3918 edged.go:857] failed to parse the Resource: Resource:  format incorrect, or Operation:  is not query/response

请教这里的failed 是什么问题？如何处理？

**Comment by luogangyi** [comment]
看上去是cgroup的问题
```
mount | grep cgroup
```
你贴一下以上命令的结果，另外，你是运行在arm上的吗？

**Comment by daixiang0** [comment]
@hzjnet seems that you build kubeedge with custom commit not a release version, right? Could you share the env and commit?

BTW, bettter to use English which support more people to help you.
