### ISSUE TITLE
Device Data repeat update to cloud sometimes

### ISSUE THREAD

**Issue by zongke** [kubeedge/kubeedge#1768]
**What happened**:
device register to cloud,and data is update to cloud from edge,but oneday or oneweek later, the divice old  data is repeat  report to cloud.
**What you expected to happen**:
device data not repeat report to cloud
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
[cloudcore-644f4fc9d-sd97q-cloudcore (2).log](https://github.com/kubeedge/kubeedge/files/4720579/cloudcore-644f4fc9d-sd97q-cloudcore.2.log)

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
release-1.0
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):  
- OS (e.g. `cat /etc/os-release`):
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.9.4
PRETTY_NAME="Alpine Linux v3.9"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

- Kernel (e.g. `uname -a`):
Linux cloudcore-644f4fc9d-sd97q 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 Linux
- Go version (e.g. `go version`): 

- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by fisherxu** [comment]
Could you plz add the kubeedge version？

**Comment by zongke** [comment]
![1](https://user-images.githubusercontent.com/12181200/83586960-63623980-a580-11ea-8282-3dd42cdea258.png)
this is out data,Every piece of data is repeated，because today the old data is repeat report to cloud

kubeedge version: release-1.0

**Comment by daixiang0** [comment]
Hi, there are lots of bugfix and optimization after release 1.0, would you like to try the latest version
?

**Comment by zongke** [comment]
ok,i will try release-1.3,but Any thoughts on this issue？

**Comment by zongke** [comment]
![2](https://user-images.githubusercontent.com/12181200/83592685-792a2b80-a58d-11ea-868a-677718df1088.png)
edge error log
