### ISSUE TITLE
Verify integration with Kata Containers

### ISSUE THREAD

**Issue by kevin-zhaoshuai** [kubeedge/kubeedge#1769]
**What would you like to be added/modified**:
Investigate the Kubeedge integration with Kata containers. 
Document to the deployment and usage

**Why is this needed**:
Kata container is the security container solution, which would benefit the edge core side runtime and security.

**Comment by fisherxu** [comment]
👍

**Comment by kevin-zhaoshuai** [comment]
working on keadm automatically install Kata containers runtime.

**Comment by kevin-zhaoshuai** [comment]
Validate the Kata-container with Containerd
Containerd 1.12.13
Kata 1.11.0-rc0, works fine on Edge Node. This document https://docs.kubeedge.io/en/latest/configuration/cri.html#kata-container has this introduction to try Kata, but this document has assumed that Kata is ready on the edge node.

Is it essential to deploy and set the configuration with Keadm @fisherxu ?

**Comment by daixiang0** [comment]
Like `kubeadm`, `keadm` should not do CRI deploy.

**Comment by daixiang0** [comment]
/close

Seems it is supported, close this.
