### ISSUE TITLE
In versions after 1.3, EdgeMesh test error

### ISSUE THREAD

**Issue by qindng** [kubeedge/kubeedge#1771]
**What happened**:
Download and build the current master branch, and run the Edgemesh example [(),](https://docs.kubeedge.io/en/latest/guides/edgemesh_test_env_guide.html) the following error occurs. However, in the same environment, version 1.3 runs the Edgemesh example normally.
` curl http://nginx-svc.default.svc.cluster:12345
curl: (52) Empty reply from server`

The log of edgecore is as follows （Related parts）：
`I0603 15:51:53.748957    5449 process.go:669] get a message {Header:{ID:10bade1d-2ec8-4808-b1da-d90276bd66fe ParentID: Timestamp:1591170713738 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/iot-edge-node2} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:8369733632 scale:0} d:{Dec:<nil>} s:7982Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:4 scale:0} d:{Dec:<nil>} s:4 Format:DecimalSI} memory:{i:{value:8264876032 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2020-06-03 15:51:53.713500198 +0800 CST m=+602.502112963 LastTransitionTime:2020-06-03 15:51:53.713500198 +0800 CST m=+602.502112963 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:9.111.141.116} {Type:Hostname Address:iot-edge-node2}] DaemonEndpoints:{KubeletEndpoint:{Port:10350}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:3.10.0-1127.8.2.el7.x86_64 OSImage:CentOS Linux 7 (Core) ContainerRuntimeVersion:remote://19.3.1 KubeletVersion:v1.17.1-kubeedge-v1.4.0-alpha.0.21+0be95b853ab879 KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I0603 15:51:53.751975    5449 metaclient.go:121] send sync message default/nodestatus/iot-edge-node2 successed and response: {{a733284e-5c87-4321-b628-b4e5b97fde24 10bade1d-2ec8-4808-b1da-d90276bd66fe 1591170713751  false} {edged meta response default/nodestatus/iot-edge-node2} OK}
I0603 15:51:54.903112    5449 process.go:669] get a message {Header:{ID:388253e9-94cc-4aa2-93d2-f4c7441866bd ParentID: Timestamp:1591170714892 ResourceVersion: Sync:true} Router:{Source:edgemesh Group:meta Operation:query Resource:default/service/nginx-svc} Content:<nil>}
I0603 15:51:54.903413    5449 metaclient.go:121] send sync message default/service/nginx-svc successed and response: {{5c1fea76-6d1f-4b29-bb4f-030b357ecf00 388253e9-94cc-4aa2-93d2-f4c7441866bd 1591170714903  false} {metaManager meta response default/service/nginx-svc} [{"metadata":{"name":"nginx-svc","namespace":"default","selfLink":"/api/v1/namespaces/default/services/nginx-svc","uid":"5ad79183-01cb-43e8-b8c2-9af142440e56","resourceVersion":"1038875","creationTimestamp":"2020-06-03T02:19:31Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"nginx-svc\",\"namespace\":\"default\"},\"spec\":{\"clusterIP\":\"None\",\"ports\":[{\"name\":\"http-0\",\"port\":12345,\"protocol\":\"TCP\",\"targetPort\":80}],\"selector\":{\"test\":\"edgemesh\"}}}\n"}},"spec":{"ports":[{"name":"http-0","protocol":"TCP","port":12345,"targetPort":80}],"selector":{"test":"edgemesh"},"clusterIP":"None","type":"ClusterIP","sessionAffinity":"None"},"status":{"loadBalancer":{}}}]}
I0603 15:51:54.903600    5449 dns.go:285] [EdgeMesh] dns server parse nginx-svc.default.svc.cluster ip 9.251.0.3
W0603 15:51:54.903710    5449 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
I0603 15:51:55.145520    5449 log.go:172] DEBUG: add [2] handlers for chain [http]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x2bb9f43]

goroutine 2927 [running]:
github.com/go-chassis/go-chassis/core/handler.(*LBHandler).Handle(0x4d41f58, 0xc0011351c0, 0xc0003770e0, 0xc0010f5540)
        /root/go-workpace/pkg/mod/github.com/go-chassis/go-chassis@v1.7.1/core/handler/loadbalance_handler.go:80 +0x43
github.com/go-chassis/go-chassis/core/handler.(*Chain).Next(0xc0011351c0, 0xc0003770e0, 0xc0010f5540)
        /root/go-workpace/pkg/mod/github.com/go-chassis/go-chassis@v1.7.1/core/handler/handler_chain.go:41 +0x73
github.com/kubeedge/kubeedge/edgemesh/pkg/protocol/http.(*HTTP).Process(0xc001135180)
        /root/go-workpace/src/github.com/kubeedge/kubeedge/edgemesh/pkg/protocol/http/http.go:69 +0x97
created by github.com/kubeedge/kubeedge/edgemesh/pkg/listener.Start
        /root/go-workpace/src/github.com/kubeedge/kubeedge/edgemesh/pkg/listener/listener.go:163 +0x256`

**What you expected to happen**:
Edgemesh example run success 
**How to reproduce it (as minimally and precisely as possible)**:
git clone master branch and make . Follow the Edgemesh test [guide(),](https://docs.kubeedge.io/en/latest/guides/edgemesh_test_env_guide.html) run 
curl http://nginx-svc.default.svc.cluster:12345
**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
cloudcore master
edgecore master(1.4.0 alpha)
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
`Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz
Stepping:              4
CPU MHz:               2299.999
BogoMIPS:              4599.99
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              16896K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp kaiser fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap xsaveopt arat md_clear flush_l1d arch_capabilities`
- OS (e.g. `cat /etc/os-release`):
`NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial`
- Kernel (e.g. `uname -a`):
`Linux iot-cloud-node 4.4.0-179-generic #209-Ubuntu SMP Fri Apr 24 17:48:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Go version (e.g. `go version`): 
`go version go1.13.3 linux/amd64`
- Others:
**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
master(1.4.0alpha)
- Hardware configuration (e.g. `lscpu`):
`Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz
Stepping:              4
CPU MHz:               2300.000
BogoMIPS:              4600.00
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              16896K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm rdseed adx smap xsaveopt arat md_clear flush_l1d arch_capabilities`
- OS (e.g. `cat /etc/os-release`):
I tried it on two machines A and B (they are both as edge node), and the same error occurred.
A :
`NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial`
B:
`NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"`
- Kernel (e.g. `uname -a`):
A:
`Linux iot-edge-node 4.4.0-179-generic #209-Ubuntu SMP Fri Apr 24 17:48:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
B:
`Linux iot-asa 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- Go version (e.g. `go version`): 
go version go1.13.4 linux/amd64
- Others:

**Comment by daixiang0** [comment]
duplicate as #1436
