### ISSUE TITLE
Trying to deploy a custom scheduler and pod is in state Error!

### ISSUE THREAD

**Issue by mixalako** [kubeedge/kubeedge#1773]
**What happened**:
Scheduler deployed pod to a node , the image was downloaded but then returned error.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
kubectl describe pod
![Screenshot from 2020-06-03 19-26-48](https://user-images.githubusercontent.com/61829876/83662877-ca0f4380-a5d0-11ea-8489-5a33bf0a9e5a.png)

my-deployment.yaml

![Screenshot from 2020-06-03 19-34-45](https://user-images.githubusercontent.com/61829876/83663282-53267a80-a5d1-11ea-8571-430ac83344b1.png)
![Screenshot from 2020-06-03 19-34-52](https://user-images.githubusercontent.com/61829876/83663289-5457a780-a5d1-11ea-84cf-581b2a972753.png)

**Environment**:
- KubeEdge version(e.g. edgecore v1.17.1-kubeedge-v1.4.0-alpha.0.21+0be95b853ab879):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by fisherxu** [comment]
Why deploy the schduler to the edge node? It's better to run it in the cloud. And now the applications runing in the edge have some issues to talk with kube-api-server directly. :) I think the schduler will connect to the apiserver directly.
