### ISSUE TITLE
Support for Openshift 4

### ISSUE THREAD

**Issue by sambr7** [kubeedge/kubeedge#1777]
**What would you like to be added/modified**:
Support for OpenShift 4
**Why is this needed**:
Ability to run small workloads in remote locations leveraging Openshift capabilities

**Comment by AndriiOmelianenko** [comment]
+1

**Comment by nstjelja** [comment]
This would be a very good feature to add.

**Comment by fisherxu** [comment]
The kubeedge cloudpart talk to the standard k8s api(kube-apiserver), so do we need any work to support openshift? Since I think openshift support the standard k8s api :)

**Comment by sambr7** [comment]
Thanks for the reply @fisherxu 
I tested KEdge 1.2.1 with OKD 4 and it didn't work properly. The pods keep in "Pending" state.

**Comment by fisherxu** [comment]
> I tested KEdge 1.2.1 with OKD 4 and it didn't work properly. The pods keep in "Pending" state.

Oh, and did the logs of cloudcore and edgecore show anything wrong?

**Comment by sambr7** [comment]
Yes, EdgeCore logs show errors like this:

I0605 16:46:14.761885   23902 process.go:622] get a message {Header:{ID:1eaf5675-8081-418a-bff5-a396ba76f859 ParentID: Timestamp:1591368374751 ResourceVersion: Sync:true} Router:{Source:edgemesh Group:meta Operation:query Resource:app/service/splk-master-01} Content:<nil>}
I0605 16:46:14.761985   23902 metaclient.go:114] send sync message app/service/splk-master-01 successed and response: {{b19e81fa-0aa1-4442-97a5-3fdb5dbc535a 1eaf5675-8081-418a-bff5-a396ba76f859 1591368374761  false} {metaManager meta response app/service/splk-master-01} []}
I0605 16:46:14.762019   23902 dns.go:276] Service splk-master-01.my.app is not found in this cluster
I0605 16:46:14.762031   23902 dns.go:117] DNS server get an resolve abnormal : get from real DNS
# Generated by NetworkManager
search mynetwork.net
nameserver x.x.x.x
nameserver x.x.x.x
nameserver x.x.x.x

**Comment by daixiang0** [comment]
Those part of edge log does not make sense, edgecore would re-send messages if failed.

**Comment by sambr7** [comment]
I'll open a proper issue detailing the problem.
Thanks for your support
