### ISSUE TITLE
Device management from cloud is required

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#178]
**What would you like to be added**:
There should be a way to manage devices from the cloud and push these updates between cloud and edge nodes. Basic CRUD operations for describing device metadata, status updates etc are needed.

**Why is this needed**:
Device management is a basic feature of an edge computing platform.

**Comment by xiaosuiba** [comment]
Any progress on this?

**Comment by sids-b** [comment]
@xiaosuiba , We are still in the design phase of this feature. This feature will be part of v0.3 release :)
