### ISSUE TITLE
Cloudcore keep received message and cloudcore cannot work properly

### ISSUE THREAD

**Issue by coderkk** [kubeedge/kubeedge#1783]
**What happened**:
My cloudcore keep received this message
```
I0606 03:15:22.394351   18576 objectsync.go:150] pod: kube-proxy-bklg8 has been deleted in K8s, send the delete event to edge
I0606 03:15:22.394427   18576 objectsync.go:150] pod: calico-node-88mld has been deleted in K8s, send the delete event to edge
I0606 03:15:22.394446   18576 objectsync.go:150] pod: calico-node-2tfnq has been deleted in K8s, send the delete event to edge
I0606 03:15:22.394539   18576 objectsync.go:150] pod: kube-proxy-lbwnl has been deleted in K8s, send the delete event to edge
I0606 03:15:27.394832   18576 objectsync.go:150] pod: calico-node-88mld has been deleted in K8s, send the delete event to edge
I0606 03:15:27.394910   18576 objectsync.go:150] pod: kube-proxy-bklg8 has been deleted in K8s, send the delete event to edge
I0606 03:15:27.394929   18576 objectsync.go:150] pod: calico-node-2tfnq has been deleted in K8s, send the delete event to edge
I0606 03:15:27.394992   18576 objectsync.go:150] pod: kube-proxy-lbwnl has been deleted in K8s, send the delete event to edge
```

**CloudSide Environment**:
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
- Kernel (e.g. `uname -a`):
Linux ke-master-1-2-1 5.3.0-1020-gcp #22~18.04.1-Ubuntu SMP Mon May 11 18:45:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fisherxu** [comment]
Have these pod already been deleted from cloud? The logs here mean the pods has been deleted in the cloud, but still exist in the edge. :)

**Comment by coderkk** [comment]
But, it non-stop display that message. Can I reset the cloudcore without reset kubernetes?

**Comment by fisherxu** [comment]
The synccontroller will compare the objects in K8s and the CRD (objectsync, which means the data sent to the edge), you can delete these CRs manually.
eg. kubectl get objectsync -A 
      kubectl delete objectsync XXX -n YOUR-NS
But the data will left at the edge side.

**Comment by coderkk** [comment]
ok, thank you

**Comment by fisherxu** [comment]
Will close it now, we can reopen it for other issue :)
/close
