### ISSUE TITLE
"false" bool value is not working

### ISSUE THREAD

**Issue by luogangyi** [kubeedge/kubeedge#1788]
**What happened**:
update IsRegisterSwap from "true" to "false" is not work.

**What you expected to happen**:
successfully update IsRegisterSwap from "true" to "false" is not work.

**How to reproduce it (as minimally and precisely as possible)**:
create a modbus intance, set IsRegisterSwap to true initially,
then update the instance,  set IsRegisterSwap to false.

or we can simply run below code
```
package main

import (
	"encoding/json"
	"fmt"
)

type SomeStruct struct {
	Value bool `json:"value,omitempty"`
}

func main() {
	// set original to true
	original := SomeStruct{Value: true}
	// update to false
	updated := SomeStruct{Value: false}
	s_updated, _ := json.Marshal(updated)
	// we see its marshal
	fmt.Println(string(s_updated))
	json.Unmarshal(s_updated, &original)
	// we see the value is not change
	fmt.Println(original.Value)

}

```

**Anything else we need to know?**:
see https://stackoverflow.com/questions/37756236/json-golang-boolean-omitempty

We should not use 
```
SomeValue bool `json:some_value,omitempty`
```
instead, we should use
```
SomeValue *bool `json:some_value,omitempty`
```

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

latest

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by daixiang0** [comment]
@luogangyi since we would call `json.Unmarshal`, this could not be an issue, see [this](https://play.golang.org/p/YSZT4TVaF9L)

**Comment by luogangyi** [comment]
@daixiang0 I don't get your point of demo code. see [demo](https://play.golang.org/p/FCaFqKoTVWi), "c2" is not updated as we expected.

Our situation is we cannot update  "true" to "false" because after Marshal and Unmarshal, the "false" value is discard. This happens when we pass value from cloud to edge which may contains serveral times Marshal and Unmarshal

**Comment by daixiang0** [comment]
After `Unmarshal`, we can get the `false` value as expected.

**Comment by luogangyi** [comment]
@daixiang0 Unmarshal to a new object, we can get what we expect. But if we Unmarshal to a existing object, false value is discard. see [demo](https://play.golang.org/p/FCaFqKoTVWi), c2 is not successfully set to false.
