### ISSUE TITLE
sh: cloudcore: command not found

### ISSUE THREAD

**Issue by Cardinalinux** [kubeedge/kubeedge#1794]
**What happened**:
keadm init not work

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
./keadm version
version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.1", GitCommit:"ae427ceeefe87c508e5ce3117fcadf66fda51c0e", GitTreeState:"clean", BuildDate:"2020-06-06T08:57:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**CloudSide Environment**:
- OS (e.g. `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:
tail /var/log/kubeedge/cloudcore.log
sh: cloudcore: command not found

but keadm downloaded all things in /etc/kubeedge

**Comment by daixiang0** [comment]
Please share the running logs here.

**Comment by niuqg** [comment]
You can check what's in your $PATH by running echo $PATH. Maybe you need to set `$PATH`.
```
export PATH=$PATH:/usr/local/bin
```
