### ISSUE TITLE
Pod running on edge has no vitural IP ? (showed <none>)

### ISSUE THREAD

**Issue by George-Chia** [kubeedge/kubeedge#1798]
> $$$$$$$$$$$ kubectl get node
 NAME                                   STATUS     ROLES    AGE   VERSION
fb4ebb70-2783-42b8-b3ef-63e2fd6d242   Ready      edge     34d   v1.15.3-kubeedge-v1.1.0
master                                 Ready      <none>   50d   v1.13.1
node1                                  NotReady   <none>   26d   v1.13.1
node2                                  NotReady   <none>   50d   v1.13.1

> $$$$$$$$$$$ kubectl get pod -o wide
NAME                            READY   cccccSTATUS        RESTARTS   AGE   IP             NODE                                   NOMINATED NODE   READINESS GATES
myapp-deploy-84b4b47c8f-22785   1/1     Running       0          6s    \<none\>         fb4ebb70-2783-42b8-b3ef-63e2fd6d242e   <none>           <none>
myapp-deploy-84b4b47c8f-4ppvw   1/1     Running       0          6s    10.244.0.140   master                                 <none>           <none>
myapp-deploy-84b4b47c8f-ttz4b   1/1     Running       0          6s    \<none\>         fb4ebb70-2783-42b8-b3ef-63e2fd6d242e   <none>           <none>
myapp-deploy1-9954f8b86-42qzr   1/1     Terminating   1          13d   10.244.1.79    node2                                  <none>           <none>

**Comment by luogangyi** [comment]
```
node1 NotReady 26d v1.13.1
node2 NotReady 50d v1.13.1
```
looks like your edge node is not OK. you should checkout edgecore status and log first.

**Comment by George-Chia** [comment]
> ```
> node1 NotReady 26d v1.13.1
> node2 NotReady 50d v1.13.1
> ```
> 
> looks like your edge node is not OK. you should checkout edgecore status and log first.

> Thanks for your reply. Node1 and node2 are nodes in k8s cluster, which is not online, so it's status is Notready. The node on the first line(fb4ebb70-2783-42b8-b3ef-63e2fd6d242) is kubeedge node. My question is that the pod running on k8s master has IP, while the one running on kubeedge does not have.

**Comment by be1be1** [comment]
> > $$$$$$$$$$$ kubectl get node
> > NAME                                   STATUS     ROLES    AGE   VERSION
> > fb4ebb70-2783-42b8-b3ef-63e2fd6d242   Ready      edge     34d   v1.15.3-kubeedge-v1.1.0
> > master                                 Ready         50d   v1.13.1
> > node1                                  NotReady      26d   v1.13.1
> > node2                                  NotReady      50d   v1.13.1
> 
> > $$$$$$$$$$$ kubectl get pod -o wide
> > NAME                            READY   cccccSTATUS        RESTARTS   AGE   IP             NODE                                   NOMINATED NODE   READINESS GATES
> > myapp-deploy-84b4b47c8f-22785   1/1     Running       0          6s    <none>         fb4ebb70-2783-42b8-b3ef-63e2fd6d242e              
> > myapp-deploy-84b4b47c8f-4ppvw   1/1     Running       0          6s    10.244.0.140   master                                            
> > myapp-deploy-84b4b47c8f-ttz4b   1/1     Running       0          6s    <none>         fb4ebb70-2783-42b8-b3ef-63e2fd6d242e              
> > myapp-deploy1-9954f8b86-42qzr   1/1     Terminating   1          13d   10.244.1.79    node2

It seems that your kubeedge is not correctly configured. Kindly change the interfaceName in `/etc/kubeedge/config/edgecore.yaml` from `eth0` to the one that you need (e.g.: `enp4s0`). For the interface, you can use `ip addr` to check it. Then, restart your edgecore.

**Comment by lmxia** [comment]
That fix my problem, thanks a lot.

**Comment by George-Chia** [comment]
myapp-deploy-84b4b47c8f-22785 1/1 Running 0 6s fb4ebb70-2783-42b8-b3ef-63e2fd6d242e

**Comment by George-Chia** [comment]
> > > $$$$$$$$$$$ kubectl get node
> > > NAME                                   STATUS     ROLES    AGE   VERSION
> > > fb4ebb70-2783-42b8-b3ef-63e2fd6d242   Ready      edge     34d   v1.15.3-kubeedge-v1.1.0
> > > master                                 Ready         50d   v1.13.1
> > > node1                                  NotReady      26d   v1.13.1
> > > node2                                  NotReady      50d   v1.13.1
> > 
> > 
> > > $$$$$$$$$$$ kubectl get pod -o wide
> > > NAME                            READY   cccccSTATUS        RESTARTS   AGE   IP             NODE                                   NOMINATED NODE   READINESS GATES
> > > myapp-deploy-84b4b47c8f-22785   1/1     Running       0          6s             fb4ebb70-2783-42b8-b3ef-63e2fd6d242e
> > > myapp-deploy-84b4b47c8f-4ppvw   1/1     Running       0          6s    10.244.0.140   master
> > > myapp-deploy-84b4b47c8f-ttz4b   1/1     Running       0          6s             fb4ebb70-2783-42b8-b3ef-63e2fd6d242e
> > > myapp-deploy1-9954f8b86-42qzr   1/1     Terminating   1          13d   10.244.1.79    node2
> 
> It seems that your kubeedge is not correctly configured. Kindly change the interfaceName in `/etc/kubeedge/config/edgecore.yaml` from `eth0` to the one that you need (e.g.: `enp4s0`). For the interface, you can use `ip addr` to check it. Then, restart your edgecore.


So where is IP address of pod running on edge b4ebb70-2783-42b8-b3ef-63e2fd6d242e?

**Comment by George-Chia** [comment]
> That fix my problem, thanks a lot.

I am still in the problem.....
