### ISSUE TITLE
Error in kubectl logs with multiple edge nodes with same IP address

### ISSUE THREAD

**Issue by Ma-Dan** [kubeedge/kubeedge#1800]
**What happened**:
CloudSide with three nodes, master 192.168.1.8, worker1: 192.168.1.7 worker2:192.168.1.10, can access by internet IP
EdgeSide1 with one node in private network 1, ip address: 192.168.1.7
EdgeSide2 with one node in private network 2, ip address: 192.168.1.7

Both edge sides registered with CloudSide sucessfully, then we have three nodes with same IP address 192.168.1.7

Deployment nginx with 5 replicas, running on each node.

kubectl logs nginx-deployment-59c9f8dff-b8vk5   OK (running on CloudSide worker 192.168.1.7)
kubectl logs nginx-deployment-59c9f8dff-tlql2     OK (running on EdgeSide1 192.168.1.7)
kubectl logs nginx-deployment-59c9f8dff-4lmr2   Error (running on EdgeSide2 192.168.1.7)

Error output is:

```
Error from server (InternalError): Internal error occurred:
```

After about 10 minutes, kubectl logs get error on both edge nodes.

**What you expected to happen**:
kubectl logs works on all edge nodes with same IP address.

**How to reproduce it (as minimally and precisely as possible)**:

Add edge nodes with same private network address to one cloud side, make one deployment with multipile replicas running on every node, then kubectl logs on each replica.

**Anything else we need to know?**:

Since edge sides run in their own private network, edge nodes with same ip address is a possible situation, and cloud site should deal with more accurate edge nodes' identities.

**Environment**:
- KubeEdge version: v1.17.1-kubeedge-v1.4.0-alpha.0.43  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): 18.04.3 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 4.15.0-99-generic
- Go version (e.g. `go version`): go1.12.5 linux/amd64
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): v1.4.0-alpha.0.43
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): 18.04.3 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 4.15.0-99-generic
- Go version (e.g. `go version`): go1.12.5 linux/amd64
- Others:

**Comment by kevin-wangzefeng** [comment]
This is not a bug, but a situation you need to take care when setting up your Kubernetes components.

Simply check the api-server argument `--kubelet-preferred-address-types`, pick hostname or internalDNS or externalDNS as primary.

**Comment by Ma-Dan** [comment]
Set --kubelet-preferred-address-types=Hostname, k8s api-server will use hostname to fetch logs, then modify hosts file inside api-server docker and add iptable entry on the hostnetwork to forward log request to CloudSteam service.
This way works, but I think there should be more elegant way to realize the hostname resolve and ipo:port forwarding.

**Comment by mixalako** [comment]
Did anyone find how to solve this ? Logs are not working no matter what,  with the same error .
