### ISSUE TITLE
Edgemesh testing failed (cannot curl from other edge node)

### ISSUE THREAD

**Issue by mipearlska** [kubeedge/kubeedge#1808]
**What happened**:
I follow the edgemesh test documentation and deploy the same like this:
![image](https://user-images.githubusercontent.com/27221815/84365553-948bdb00-ac0c-11ea-87d7-5ae6f49f358a.png)
vmedge1 is the edge node that run the service. When I curl from vmedge2, it returned:
root@ubuntu:~/go/bin# curl http://nginx-svc.default.svc.cluster:12345
curl: (7) Failed to connect to nginx-svc.default.svc.cluster port 12345: Connection refused
**What you expected to happen**:
curl nginx sucessfully
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Edgecore logs from vmedge2 after curl
I0611 01:38:53.680210   18433 dns.go:288] [EdgeMesh] dns server parse nginx-svc.default.svc.cluster ip 9.251.0.3
W0611 01:38:53.680365   18433 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  1.3.1

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 4
On-line CPU(s) list: 0-3
Thread(s) per core: 2
Core(s) per socket: 2
Socket(s): 1
NUMA node(s): 1
Vendor ID: GenuineIntel
CPU family: 6
Model: 69
Model name: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
Stepping: 1
CPU MHz: 1330.748
CPU max MHz: 2600.0000
CPU min MHz: 800.0000
BogoMIPS: 3791.25
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
L3 cache: 3072K
NUMA node0 CPU(s): 0-3
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
- OS (e.g. `cat /etc/os-release`): ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`): Linux ubuntu-desktop 4.15.0-106-generic #107-16.04.1
- Go version (e.g. `go version`): 1.14.2
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): 1.3.1
- Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Stepping:              3
CPU MHz:               3591.681
BogoMIPS:              7183.36
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt arat flush_l1d arch_capabilities
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux ubuntu 4.15.0-101-generic #102~16.04.1-Ubuntu SMP Mon May 11 11:38:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): 
go version go1.14.3 linux/amd64
- Others:

**Comment by qindng** [comment]
can you provide more edgecore logs ?

**Comment by mipearlska** [comment]
I0611 03:48:15.965108   18433 dns.go:288] [EdgeMesh] dns server parse nginx-svc.default.svc.cluster ip 9.251.0.3
W0611 03:48:15.965250   18433 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
I0611 03:48:16.314431   18433 process.go:672] get a message {Header:{ID:310f23e3-bf3e-434d-9bc5-63ced7586da4 ParentID: Timestamp:1591872496303 ResourceVersion: Sync:true} Router:{Source:edgemesh Group:meta Operation:query Resource:default/service/nginx-svc} Content:<nil>}
I0611 03:48:16.314688   18433 metaclient.go:121] send sync message default/service/nginx-svc successed and response: {{47283b3f-1cbd-4a46-bdb4-4e4eee3bc1a3 310f23e3-bf3e-434d-9bc5-63ced7586da4 1591872496314  false} {metaManager meta response default/service/nginx-svc} [{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"nginx-svc\",\"namespace\":\"default\"},\"spec\":{\"clusterIP\":\"None\",\"ports\":[{\"name\":\"http-0\",\"port\":12345,\"protocol\":\"TCP\",\"targetPort\":80}],\"selector\":{\"app\":\"nginx\"}}}\n"},"creationTimestamp":"2020-06-11T07:52:50Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:clusterIP":{},"f:ports":{".":{},"k:{\"port\":12345,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:app":{}},"f:sessionAffinity":{},"f:type":{}}},"manager":"kubectl","operation":"Update","time":"2020-06-11T07:52:50Z"}],"name":"nginx-svc","namespace":"default","resourceVersion":"5963","selfLink":"/api/v1/namespaces/default/services/nginx-svc","uid":"3d37fb6c-22e3-4894-bec7-9d913cebe5da"},"spec":{"clusterIP":"None","ports":[{"name":"http-0","port":12345,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}]}
I0611 03:48:16.314904   18433 dns.go:288] [EdgeMesh] dns server parse nginx-svc.default.svc.cluster ip 9.251.0.3
W0611 03:48:16.315096   18433 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
I0611 03:48:16.677127   18433 process.go:672] get a message {Header:{ID:804f64d2-2438-4042-9a4b-4fba7e134b66 ParentID: Timestamp:1591872496666 ResourceVersion: Sync:true} Router:{Source:edgemesh Group:meta Operation:query Resource:default/service/nginx-svc} Content:<nil>}
I0611 03:48:16.677400   18433 metaclient.go:121] send sync message default/service/nginx-svc successed and response: {{cc06d1bc-0fe7-476b-ad79-f84ce9fc7c49 804f64d2-2438-4042-9a4b-4fba7e134b66 1591872496677  false} {metaManager meta response default/service/nginx-svc} [{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"nginx-svc\",\"namespace\":\"default\"},\"spec\":{\"clusterIP\":\"None\",\"ports\":[{\"name\":\"http-0\",\"port\":12345,\"protocol\":\"TCP\",\"targetPort\":80}],\"selector\":{\"app\":\"nginx\"}}}\n"},"creationTimestamp":"2020-06-11T07:52:50Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:clusterIP":{},"f:ports":{".":{},"k:{\"port\":12345,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:app":{}},"f:sessionAffinity":{},"f:type":{}}},"manager":"kubectl","operation":"Update","time":"2020-06-11T07:52:50Z"}],"name":"nginx-svc","namespace":"default","resourceVersion":"5963","selfLink":"/api/v1/namespaces/default/services/nginx-svc","uid":"3d37fb6c-22e3-4894-bec7-9d913cebe5da"},"spec":{"clusterIP":"None","ports":[{"name":"http-0","port":12345,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}]}
I0611 03:48:16.677588   18433 dns.go:288] [EdgeMesh] dns server parse nginx-svc.default.svc.cluster ip 9.251.0.3
W0611 03:48:16.677743   18433 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
I0611 03:48:17.467058   18433 edged_status.go:186] Sync VolumesInUse: []
I0611 03:48:17.477725   18433 process.go:672] get a message {Header:{ID:f224c667-f1bb-4b69-a2cc-747320c71d29 ParentID: Timestamp:1591872497467 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/vmedge2} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:8 scale:0} d:{Dec:<nil>} s:8 Format:DecimalSI} memory:{i:{value:2065694720 scale:0} d:{Dec:<nil>} s:1970Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:8 scale:0} d:{Dec:<nil>} s:8 Format:DecimalSI} memory:{i:{value:1960837120 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2020-06-11 03:48:17.45479008 -0700 PDT m=+11379.610772294 LastTransitionTime:2020-06-11 03:48:17.45479008 -0700 PDT m=+11379.610772294 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.12.67} {Type:Hostname Address:vmedge2}] DaemonEndpoints:{KubeletEndpoint:{Port:10350}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.15.0-101-generic OSImage:Ubuntu 16.04.6 LTS ContainerRuntimeVersion:remote://19.3.9 KubeletVersion:v1.17.1-kubeedge-v1.3.1 KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I0611 03:48:17.479821   18433 metaclient.go:121] send sync message default/nodestatus/vmedge2 successed and response: {{443e3cc4-29df-4279-ad83-f9870b0c475d f224c667-f1bb-4b69-a2cc-747320c71d29 1591872497479  false} {edged meta response default/nodestatus/vmedge2} OK}
I0611 03:48:17.492846   18433 process.go:164] received msg from cloud-hub:{Header:{ID:1f04bb39-b0d9-428c-9baf-7d376d6a6035 ParentID:f224c667-f1bb-4b69-a2cc-747320c71d29 Timestamp:1591872497494 ResourceVersion:32976 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/vmedge2} Content:OK}
W0611 03:48:17.492982   18433 context_channel.go:158] Get bad anonName:f224c667-f1bb-4b69-a2cc-747320c71d29 when sendresp message, do nothing
I0611 03:48:20.798877   18433 common.go:61] start connect to mqtt server with client id: hub-client-sub-1591861118
I0611 03:48:20.798979   18433 common.go:63] client hub-client-sub-1591861118 isconnected: false
E0611 03:48:20.799245   18433 common.go:65] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
I0611 03:48:25.800078   18433 common.go:61] start connect to mqtt server with client id: hub-client-sub-1591861118
I0611 03:48:25.800166   18433 common.go:63] client hub-client-sub-1591861118 isconnected: false
E0611 03:48:25.800432   18433 common.go:65] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
I0611 03:48:27.493667   18433 edged_status.go:186] Sync VolumesInUse: []
I0611 03:48:27.504143   18433 process.go:672] get a message {Header:{ID:afadd388-9dd3-40bf-a25e-c83e0546c7bd ParentID: Timestamp:1591872507493 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/vmedge2} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:8 scale:0} d:{Dec:<nil>} s:8 Format:DecimalSI} memory:{i:{value:2065694720 scale:0} d:{Dec:<nil>} s:1970Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:8 scale:0} d:{Dec:<nil>} s:8 Format:DecimalSI} memory:{i:{value:1960837120 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2020-06-11 03:48:27.481284289 -0700 PDT m=+11389.637266505 LastTransitionTime:2020-06-11 03:48:27.481284289 -0700 PDT m=+11389.637266505 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.12.67} {Type:Hostname Address:vmedge2}] DaemonEndpoints:{KubeletEndpoint:{Port:10350}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:4.15.0-101-generic OSImage:Ubuntu 16.04.6 LTS ContainerRuntimeVersion:remote://19.3.9 KubeletVersion:v1.17.1-kubeedge-v1.3.1 KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I0611 03:48:27.506184   18433 metaclient.go:121] send sync message default/nodestatus/vmedge2 successed and response: {{02ca2679-ecb2-4778-b632-092fe47d253e afadd388-9dd3-40bf-a25e-c83e0546c7bd 1591872507506  false} {edged meta response default/nodestatus/vmedge2} OK}
I0611 03:48:27.519763   18433 process.go:164] received msg from cloud-hub:{Header:{ID:5fcaeff7-bcfa-4528-b3e2-42d969ce38aa ParentID:afadd388-9dd3-40bf-a25e-c83e0546c7bd Timestamp:1591872507521 ResourceVersion:33000 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/vmedge2} Content:OK}
W0611 03:48:27.519842   18433 context_channel.go:158] Get bad anonName:afadd388-9dd3-40bf-a25e-c83e0546c7bd when sendresp message, do nothing
`

**Comment by daixiang0** [comment]
duplicate as #1436
