### ISSUE TITLE
Edgemesh prerequisites and configuration

### ISSUE THREAD

**Issue by plochon** [kubeedge/kubeedge#1814]
What are the prerequisites and configuration to run Edgemesh ? there's a link missing on the Edgmesh page ("follow ... to deploy service" :

https://docs.kubeedge.io/en/latest/contributing/edgemesh_test_env_guide.html

![edgemesh](https://user-images.githubusercontent.com/61243441/84506353-88148a80-acbf-11ea-8585-8852012a588d.png)

**Environment**:
- KubeEdge version 1.3

**Comment by kevin-wangzefeng** [comment]
https://github.com/kubeedge/kubeedge/pull/1805/ would fix this
