### ISSUE TITLE
How to route external traffic into edge pods ?

### ISSUE THREAD

**Issue by plochon** [kubeedge/kubeedge#1815]
Could you clarify what Kubernetes methods (list below) are supported in Kubeedge to route external traffic into edge pods ?
- ClusterIP
- NodePort
- LoadBalancer
- Service
- Ingress

**Environment**:
- KubeEdge version 1.3

**Comment by fisherxu** [comment]
Now we support NodePort in edgenode to route external traffic into edge pods, and Ingress and LoadBalancer is implementing now :)

**Comment by plochon** [comment]
@fisherxu thank you, do you mean NodePort is already supported in latest release i.e. 1.3.1 ? or should we wait for 1.4 ?

**Comment by fisherxu** [comment]
> @fisherxu thank you, do you mean NodePort is already supported in latest release i.e. 1.3.1 ? or should we wait for 1.4 ?

Ohh, sorry, I think I made mistake, I mean hostport and port mapping.
