### ISSUE TITLE
Kubeedge upgrade procedure

### ISSUE THREAD

**Issue by plochon** [kubeedge/kubeedge#1816]
Could you describe the procedure to upgrade from release 1.2 to 1.3, 1.3 to 1.3.1, ... ?
Do we need to regenerate the certificates ?
Does edgecore release must match cloudcore release ?
Do we need to recreate the db file ?
...

**Environment**:
- KubeEdge version 1.3

**Comment by kevin-wangzefeng** [comment]
We should clarify this in document. /cc @daixiang0 
/kind document
/remove-kind bug
