### ISSUE TITLE
keadm download cloud side yaml from raw.githubusercontent.com failed

### ISSUE THREAD

**Issue by kevinzs2048** [kubeedge/kubeedge#1817]
**What happened**:
```
sudo ./keadm init --kube-config ~/.kube/config --kubeedge-version 1.3.1
Kubernetes version verification passed, KubeEdge installation will start...
--2020-06-14 03:18:08--  https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_device.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... failed: Connection refused.
Converted links in 0 files in 0 seconds.
Error: failed to run 'sh -c cd /etc/kubeedge/crds/devices && wget -k --no-check-certificate --progress=bar:force https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_device.yaml' because of error : exit status 4
```

If set proxy on the cmdline only, then the connection to kube-apiserver will fail.
I think we should consider use a parameter to pass the https proxy when downloading.

**What you expected to happen**:
Download success
**How to reproduce it (as minimally and precisely as possible)**:
Special in China.

**Comment by luogangyi** [comment]
@kevin-zhaoshuai ,that should be ```/assign``` , no "me" needed :)
Besides, there is two way get keadm currently, eg. build from source or download pre-built tar.
So, I think If we build from source, we can copy these yaml file into destination and If we download pre-built tar, we should put these yaml into tar instead of download them from internet.

**Comment by daixiang0** [comment]
I think https proxy is a host env indeed.

**Comment by kevin-zhaoshuai** [comment]
@luogangyi  yes, so you mean that we can just copy file first to the directory and do not need to setup the https proxy? That should be easy and do not need any code change

**Comment by kevin-zhaoshuai** [comment]
@daixiang0 yes, but the problem here is if you set the https proxy env, you can not get access to the kube-apiserver, that will make keadm fail at first.

**Comment by luogangyi** [comment]
> @luogangyi yes, so you mean that we can just copy file first to the directory and do not need to setup the https proxy? That should be easy and do not need any code change

--
yes, I think this way is less invasive and easy to accomplish

**Comment by fisherxu** [comment]
@kevin-zhaoshuai Thanks for your idea, for the download issue, we can discuss where to place the release package, then users can download without proxy, WDYT?

**Comment by kevin-zhaoshuai** [comment]
@fisherxu Thanks, that sounds good to me, and this do not need any code change, very easy to fix this problem.

**Comment by DapengLan** [comment]
I got the same issues when using Kubeedge in China. very annoying
