### ISSUE TITLE
Evaluate KubeEdge scalability

### ISSUE THREAD

**Issue by CindyXing** [kubeedge/kubeedge#182]
KubeEdge allows admin to manage large scale of edge nodes from cloud. With Edgecontroller, cloudhub/edgehub and metadata store at edge side, we are extending the potential capacity. 

To prove the advantages, this is to book an item for us evaluating the 
- latency & throughput for cloudhub/edgehub
- scalability of kubeEdge cloud side

As a result, we'll also evaluate the future improvement items.

**Comment by kevin-wangzefeng** [comment]
Reopening since #308 only addresses part of this.
