### ISSUE TITLE
kubeedge1.3 network can't expose ports.

### ISSUE THREAD

**Issue by xixi-A** [kubeedge/kubeedge#1825]
**What happened**:

1.When I assign  nignx to edgenode by:

 kubectl apply -f $GOPATH/src/github.com/kubeedge/kubeedge/build/deployment.yaml

2.Then kubectl get pod --all-namespace -owide

kubectl get pod --all-namespaces -owide
NAMESPACE     NAME                                      READ     STATU  RESTARTS AGE    IP           NODE       
default   nginx-deployment-77698bff7d-wb8pt   1/1     Running     0     8h    172.17.0.3      edgenode                  
kube-system   calico-kube-controllers-5ddf645df5-c87jj   1/1     Running 1  39h   10.217.20.68    kubeedge          
kube-system   calico-node-kftsm                          1/1     Running     1      39h   192.168.17.60   edgenode         
kube-system   calico-node-vbttt                          1/1     Running     1          39h   192.168.17.50   kubeedge    
kube-system   coredns-5644d7b6d9-jvhd2                   1/1     Running     7          10d   10.217.20.66    kubeedge   
kube-system   coredns-5644d7b6d9-snrd4                   1/1     Running     7          10d   10.217.20.67    kubeedge    
kube-system   etcd-kubeedge                              1/1     Running     4          10d   192.168.17.50   kubeedge   
kube-system   kube-apiserver-kubeedge                    1/1     Running     6          10d   192.168.17.50   kubeedge   
kube-system   kube-controller-manager-kubeedge           1/1     Running     9          10d   192.168.17.50   kubeedge    
kube-system   kube-proxy-gbt7p                           1/1     Running     4          10d   192.168.17.50   kubeedge   
kube-system   kube-scheduler-kubeedge                    1/1     Running     9          10d   192.168.17.50   kubeedge 

3. But I can't  connect  nginx at other node by : 

   curl 192.168.17.60 
   curl:(7)Failed to connect to 192.168.17.60 port 80 : refuse connection

4. Even I   "curl localhost"    on the edgenode:
   curl: (56) Recv failure: 连接被对方重设

5. Then I need do the follow cmd on edgenode:
   docker  run -d -p 80:80 nginx:1.15.2

6.  On edgenode:
    docker rm -f containerID

7.  On cloud, do this quickly! must quickly!
     kubectl apply -f $GOPATH/src/github.com/kubeedge/kubeedge/build/deployment.yaml

8. Maybe you can visit, maybe node. If not, recycle   5-7

**What you expected to happen**:

When I use : 

   kubectl apply -f  *.yaml

   I can visit the port I specify in the *.yaml.

**How to reproduce it (as minimally and precisely as possible)**:

You can install kubeedge1.3 refer to the follow blog:
   https://blog.csdn.net/qq_42484239/article/details/106738965

When you successful, you can 
  kubectl apply -f $GOPATH/src/github.com/kubeedge/kubeedge/build/deployment.yaml

Then
   curl  edgenodeIP

**Anything else we need to know?**:

Both of kubeedge1.3 and 1.1 have the network probelm, other versions are unclear. Maybe v0.3 don't have.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  v1.3.0   v1.3.1   v1.1.0

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):  intel i7      4G         40G
- OS (e.g. `cat /etc/os-release`): ubuntu16.04
- Kernel (e.g. `uname -a`): 4.15.0
- Go version (e.g. `go version`): 1.12.5
- Others:  k8s：1.16.3      docker: 18.06.3     CNI： Flannel、Calico、Canal

**EdgeSide Environment**:    the same as "CloudSide Environment"

**Comment by fisherxu** [comment]
@xixi-A  I have tried in my env, it running well. Another service have used the port 80, so I changed the host port to 8080 in deployment.yaml. The issue maybe related to your env.
```
➜  build git:(master) ✗ kubectl get pods -owide
NAME                                READY   STATUS    RESTARTS   AGE     IP           NODE        NOMINATED NODE   READINESS GATES
nginx-deployment-656567887b-6gzhm   1/1     Running   0          3m11s   172.17.0.4   edge-node   <none>           <none>
➜  build git:(master) ✗ curl 192.168.1.16:8080 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

```

**Comment by xixi-A** [comment]
@fisherxu  OK, I will try again. And I wonder which one of the OS and its version you used, and kubeedge's version. Thank you!

**Comment by fisherxu** [comment]
My host OS is ubuntu 16.04, KubeEdge version is 1.3.1  @xixi-A

**Comment by xixi-A** [comment]
@fisherxu  Which cni you used? calico or flannel?

**Comment by fisherxu** [comment]
I haven't use cni in this test env, just use the docker network, and run kubeedge in vm

**Comment by xixi-A** [comment]
@fisherxu  Thank，I'm succeed on respberry. I will try again in vm later. And I have another question, when the edge connect with the cloud successful, is there run the pod of kube-proxy automatically on the edge?

**Comment by fisherxu** [comment]
Now in the edge, we don't support kube-proxy, because kube-proxy would talk to kube-apiserver directrly, will have something wrong with the edge network. Edgemesh is our solution like kube-proxy.

**Comment by xixi-A** [comment]
OK. Thank you, I have buit a new vm and run edgecore just now, I can curl my IP.
