### ISSUE TITLE
Enable network routing between edge nodes

### ISSUE THREAD

**Issue by CindyXing** [kubeedge/kubeedge#183]
Currently to route a request from one edge node to the other, it has to go through the cloud. To enable better performance (latency, throughput), we should enable edge to edge routing.

**Comment by qizha** [comment]
I have a similar one here: https://github.com/kubeedge/kubeedge/issues/172 
please take a look. Thanks ^_^

**Comment by CindyXing** [comment]
Close this one as 172 covers the need already.
