### ISSUE TITLE
Bad coding style

### ISSUE THREAD

**Issue by sailorvii** [kubeedge/kubeedge#1830]
![image](https://user-images.githubusercontent.com/35483373/84870965-8d544980-b0b2-11ea-9917-4b32e3a70279.png)
File: bluetooth_mapper/watcher/watcher.go
**What would you like to be added/modified**:
Cut down the layers, using like this:
if Wrong {
    break
}
**Why is this needed**:
Hard to read and maintian.

**Comment by daixiang0** [comment]
@sailorvii hi, would you like to refactor them?

**Comment by sks** [comment]
@daixiang0 / @sailorvii Is this something that I can assist with ? Would like to take a stab at it.

**Comment by daixiang0** [comment]
@sks, very welcome, you can play with codes of mappers.
