### ISSUE TITLE
Network configuration for logs and metrics

### ISSUE THREAD

**Issue by Ma-Dan** [kubeedge/kubeedge#1835]
In current version of KubeEdge, if we want to use kubectl logs or kubectl top nodes/pods, we need to run apiserver/metrics-server in hostnetwork mode, then add iptables for each added edge node to forward logs/metrics request to cloudStream. If edge nodes work in hostname mode, more work should be done, adding hosts resolving to kube-apiserver/metrcis-server and assign an unconflict IP address to edge nodes.
This approach is a bit intrusive and complex:
- Handling nodes registering/unregistering
- Adding/deleting hosts entries for kube-apiserver/metrics-server
- Adding iptables entries host nodes.

**What would you like to be added/modified**:
A simple and automatic way to enable edge nodes logs and metrics

**Why is this needed**:
In practical application, edge nodes network configuration should be automcatically managed and transparent to user, modification on kube-apiserver/metrics-server network also increases the possibility of crashing it, which will cause the whole cluster malfunction.

**Comment by daixiang0** [comment]
@Ma-Dan Hi, could you have interest in completing docs about how to enable logs and metrics? It would be very helpful to users.

**Comment by lixiangmyehk** [comment]
me too

**Comment by Ma-Dan** [comment]
Currently this method contains two manual steps: (1) modify hosts file in kube-apiserver and metrics-server container, (2) modify iptables on host machine which kube-apiserver/metrics-server runs.

We planned to make this procedure automatic:
(1) Develop sidecar for kube-apiserver and metrics-server, list-watch nodes resource of k8s cluster, and sync edge nodes info, assign unconflict ip address for edge nodes, keep hosts files sync with registered edge nodes, and sync edge nodes' IP address info in etcd;
(2) Develop daemonset for iptables, running on host machine, watch sidecar maintained edge nodes' IP address info, and sync iptables to forward log/metrics requests to CloudStream service;

With these two components, hosts and iptables could be automatically maintained.

**Comment by kadisi** [comment]
@Ma-Dan for hostname mode, you can use `xip.io`

**Comment by lixiangmyehk** [comment]
iptables -t nat -A OUTPUT -p tcp  --dport 10350 -j DNAT --to 192.168.0.102:10003
是这样吗，我改过，没有效果

**Comment by Ma-Dan** [comment]
> iptables -t nat -A OUTPUT -p tcp --dport 10350 -j DNAT --to 192.168.0.102:10003
> if command is this,it was invalid .Can you explain it in more detail?Thanks

When running kubectl logs on edge pods, does kube-apiserver show logs about failing connection to https://edgenodeNameIP:10350/containerLogs/XXXXX ?

If this log is present, then add hosts in kube-apiserver container in hostname mode. (Skip this step in ip address mode)

After this in-container part is done, then run

```
iptables -t nat -A OUTPUT -d 192.168.1.14 -p tcp --dport 10350 -j DNAT --to-destination 192.168.1.4:10003
```

on host machine which kube-apiserver is running, source IP needs to be specified, otherwize this forwarding rule will affect kubectl exec on cloud side pods.

**Comment by luogangyi** [comment]
is it duplicated with #1799 and #1735 ?

**Comment by Ma-Dan** [comment]
> is it duplicated with #1799 and #1735 ?

It is not duplicated with these PRs, it covers the network configuration part (DNS for edge nodes'  hostname and iptables for CloudStream) after the function of these PRs running.

**Comment by luogangyi** [comment]
> > is it duplicated with #1799 and #1735 ?
> 
> It is not duplicated with these PRs, it covers the network configuration part (DNS for edge nodes' hostname and iptables for CloudStream) after the function of these PRs running.

Thanks for your explaination. 
Btw, "adding hosts resolving to kube-apiserver/metrcis-server and assign an unconflict IP address to edge nodes."
is it necessary? can we use dns to map all edge nodes to 127.0.0.1?

**Comment by Ma-Dan** [comment]
> > > is it duplicated with #1799 and #1735 ?
> > 
> > 
> > It is not duplicated with these PRs, it covers the network configuration part (DNS for edge nodes' hostname and iptables for CloudStream) after the function of these PRs running.
> 
> Thanks for your explaination.
> Btw, "adding hosts resolving to kube-apiserver/metrcis-server and assign an unconflict IP address to edge nodes."
> is it necessary? can we use dns to map all edge nodes to 127.0.0.1?

We are considering make this IP address a configurable parameter, using 127.0.0.1 might affect local communication on 10250/10350 ports, need to verify, we have tested that multiple edge nodes share the same IP is ok.

**Comment by benjaminhuo** [comment]
> @Ma-Dan for hostname mode, you can use `xip.io`

@kadisi xip.io works for us, we've tested it and are considering using this method to go ahead. By using xip.io, we'll needn't to "adding hosts resolving to kube-apiserver/metrcis-server" anymore which is great.

Maybe we can contribute our automation tool to KubeEdge community as well

Ben

**Comment by qby-wenzel** [comment]
Hello, is there any further progress on this topic? Maybe somewhere else than here e.g. branch/PR/issue?

We tested the logging feature weeks ago and wanted to use it now in a more complex k8s/kubeedge scenario while stumbling upon some automation challenges ;)

**Comment by benjaminhuo** [comment]
@Ma-Dan have developed a tool called EdgeWatcher for KubeEdge cloud & edge network configuration automation purpose and currently, we're making some final changes to this tool. Hopefully, we'll make it open source soon.

Ben

**Comment by qby-wenzel** [comment]
@benjaminhuo Sounds interesting, looking forward to it. And thanks for the insights! We're trying to somehow integrate things with metallb now, but this is still wip. Hope we'll all find a solution which could be adapted more generally for everybody or let's say the majority of kubeedge users :)
