### ISSUE TITLE
Edgemesh supported protocols

### ISSUE THREAD

**Issue by plochon** [kubeedge/kubeedge#1837]
According to 
https://docs.kubeedge.io/en/v1.3.1/guides/edgemesh_test_env_guide.html
> Currently we only support HTTP1.x, more protocols like HTTPS and gRPC coming later

When will other procols be supported ?

**Comment by kevin-wangzefeng** [comment]
The support of HTTP1.x here means application-layer protocal aware load balancing, for HTTPS and gRPC, you can rely on TCP L4 load-balancing now

**Comment by kevin-wangzefeng** [comment]
BTW, HTTPS and gRPC aware load balancing are advanced feature for service governance cases, I think we will add support in 2021.
