### ISSUE TITLE
keadm join时候没有指定系统架构的参数，服务端和amd64 、edge是arm64，默认每次都会改了config文件

### ISSUE THREAD

**Issue by 379763376** [kubeedge/kubeedge#1871]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by daixiang0** [comment]
Which config do you mean?

**Comment by 379763376** [comment]
/etc/kubeedge/config/edgecore.yaml

**Comment by 379763376** [comment]
边缘节点是arm64架构的  keadm join的时候  生成的config文件中image字段值应该是kubeedge/pasue-arm64:tag

keadm没有检查cpu架构？看着也没参数可以指定架构

**Comment by daixiang0** [comment]
This issue has been fixed by [this ](https://github.com/kubeedge/kubeedge/commit/a4d1c3a6)i think, which version of keadm do you use?

**Comment by 379763376** [comment]
Oh, I use v1.3.1 relaese version. The keadm installer is based on source code compilation. The kubeedge and edgesite is based on relaesed tar file.
