### ISSUE TITLE
Version error in KubeEdge cluster by using kubectl get nodes in master node.

### ISSUE THREAD

**Issue by s099064146** [kubeedge/kubeedge#1872]
**What happened**:
The version of KubeEdge which showed in command: `kubectl get nodes` (on master node).
![image](https://user-images.githubusercontent.com/40239192/85761125-0acc2980-b745-11ea-9fff-72e587c96f2e.png)
**What you expected to happen**:
It will show up something like "v1.17.1-kubeedge-v1.3.1" in the description of the version.
**How to reproduce it (as minimally and precisely as possible)**:
Just using release-1.3 branch KubeEdge to compile a keadm and build the cluster with KubeEdge release packages.
Cloud:
kubeedge-v1.3.1-linux-amd64.tar.gz
Edge:
kubeedge-v1.3.1-linux-arm64.tar.gz
**Anything else we need to know?**:
Please inform me of other information you want to know.
**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
`keadm version` + `cloudcore --version`
![image](https://user-images.githubusercontent.com/40239192/85761966-d7d66580-b745-11ea-882a-d82b00ca09d5.png)
`keadm version` + `edgecore --version`
![image](https://user-images.githubusercontent.com/40239192/85762036-e91f7200-b745-11ea-97ee-5321c2250d2c.png)
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
root@charlie--latest:/home/charlie# lscpu
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  6
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
Stepping:            10
CPU MHz:             3726.483
CPU max MHz:         4100.0000
CPU min MHz:         800.0000
BogoMIPS:            6000.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            9216K
NUMA node0 CPU(s):   0-5
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
```
- OS (e.g. `cat /etc/os-release`):
root@charlie--latest:/home/charlie# cat /etc/os-release
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
root@charlie--latest:/home/charlie# uname -a
`Linux charlie--latest 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Go version (e.g. `go version`): 
root@charlie--latest:/home/charlie# go version
`go version go1.14.4 linux/amd64`
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
root@nvidia-desktop:/home/nvidia# edgecore --version
```
2020-06-26 00:49:01.025323 I | INFO: Install client plugin, protocol: rest
2020-06-26 00:49:01.025539 I | INFO: Installed service discovery plugin: edge
KubeEdge v0.0.0-master+$Format:%h$
```
- Hardware configuration (e.g. `lscpu`):
root@nvidia-desktop:/home/nvidia# lscpu
```
Architecture:         aarch64
Byte Order:           Little Endian
CPU(s):               6
On-line CPU(s) list:  0,3-5
Off-line CPU(s) list: 1,2
Thread(s) per core:   1
Core(s) per socket:   4
Socket(s):            1
Vendor ID:            ARM
Model:                3
Model name:           Cortex-A57
Stepping:             r1p3
CPU max MHz:          2035.2000
CPU min MHz:          345.6000
BogoMIPS:             62.50
L1d cache:            32K
L1i cache:            48K
L2 cache:             2048K
Flags:                fp asimd evtstrm aes pmull sha1 sha2 crc32
```
- OS (e.g. `cat /etc/os-release`):
root@nvidia-desktop:/home/nvidia# cat /etc/os-release
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
root@nvidia-desktop:/home/nvidia# uname -a
`Linux nvidia-desktop 4.9.140-kubernetes_opt #1 SMP PREEMPT Thu Jun 25 22:08:05 CST 2020 aarch64 aarch64 aarch64 GNU/Linux`
- Go version (e.g. `go version`): 
root@nvidia-desktop:/home/nvidia# go version
`go version go1.14.4 linux/arm64`
- Others:

**Comment by daixiang0** [comment]
It is an issue for arm64 release binary, we will fix soon.

**Comment by s099064146** [comment]
@daixiang0 
Thank you for fixing this!
