### ISSUE TITLE
make lint modify images in kubeedge/docs/adopters

### ISSUE THREAD

**Issue by ls889** [kubeedge/kubeedge#1878]
**What happened**:
when run `make lint`, it will modify the images in kubeedge/docs/adopters, then the pics are broken.

**Comment by ls889** [comment]
@daixiang0 hello,  it's better to modify the images' location or modify the make lint?

**Comment by daixiang0** [comment]
@ls889 No need to move image, update `hack/lib/lint.sh` is enough.

**Comment by ls889** [comment]
@daixiang0  sure, update lint.sh and ignoring "adopters" is convenience. but png should be put in images directory.

**Comment by fisherxu** [comment]
@ls889 We specifically separate the adopters logo with the general pictures, so just  update lint.sh :)

**Comment by ls889** [comment]
@daixiang0 @fisherxu  Thanks for tips.
