### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#1882]
**What happened**:
When edgecore runs for a long time, there will be a `concurrent map writes` panic 
![image](https://user-images.githubusercontent.com/29768082/86354184-241c2b00-bc9b-11ea-9091-41a290698dfa.png)

**What you expected to happen**:
edgecore run well.
**How to reproduce it (as minimally and precisely as possible)**:
edgecore run for a long time
**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  v1.3.0

**Comment by daixiang0** [comment]
The stack is not complete, seems write map without lock.

**Comment by GsssC** [comment]
@daixiang0 ，yes，map in consumer gorutines should be locked
