### ISSUE TITLE
Redundant orphan directory

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#1888]
**What happened**:
![image](https://user-images.githubusercontent.com/29768082/86457543-68b8cc80-bd56-11ea-8acb-d6d62ac2ccd5.png)

**What you expected to happen**:
number of dir`/var/lib/edged/pods` is equal with pod number in edge-store
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  master

**Comment by ls889** [comment]
The problem has not been reproduced after many tests.
