### ISSUE TITLE
delete pvc and pv that edgecore sqlite cannot delete information

### ISSUE THREAD

**Issue by guojianyu** [kubeedge/kubeedge#1899]
**What happened**:
edgecore  sqlite3 can not clear pv and pvc of deletion information beacaus  cloudcore do not send deletion message  for  edgehub 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![ZIOKVDBBA3%W@B7UP4YF6ZH](https://user-images.githubusercontent.com/21234963/86735430-619b0280-c065-11ea-9de6-5350ea6b393f.png)

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
edgecore1.3.0
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by guojianyu** [comment]
this bug make pvc name cannot be reused,local pv pathname is first pv name all the time.

**Comment by daixiang0** [comment]
We do not support local pv at edge side.

**Comment by guojianyu** [comment]
> We do not support local pv at edge side.

it is can not support  no-provisiner local pv currently
but provisioner local pv  solved this bug   can support

**Comment by daixiang0** [comment]
Local pv may make users confused whether it is "local pv" type.

**Comment by guojianyu** [comment]
> Local pv may make users confused whether it is "local pv" type.

Get it,this description is not clear.
this loca pv points provisioner local pv
