### ISSUE TITLE
Bad naming style

### ISSUE THREAD

**Issue by sailorvii** [kubeedge/kubeedge#1905]
**What would you like to be added/modified**:
The name of functions, variables is not appropriate.
file: kubeedge/edge/pkg/devicetwin/dtmanager/membership.go
1. Function name needn't use past tense. Not only this function, but also many other function names should be refined.
Eg:
line 164
// Added add device to the edge group
func Added

2. Bad variable name. Here deviceModel -> deviceInstance. For deviceModel and deviceinstance are two definitions in device manager.
deviceExist  -> isDeviceExist.
line 	178:	deviceModel, deviceExist := context.GetDevice(device.ID)

**Why is this needed**:
Good coding style is the base.

**Comment by fisherxu** [comment]
Thanks for pointing out @sailorvii And would you like to raise some PRs to fix? :)

**Comment by kadisi** [comment]
@sailorvii Welcome to submit your PR.
