### ISSUE TITLE
get secret from metaManager failed

### ISSUE THREAD

**Issue by luotian-github** [kubeedge/kubeedge#1909]
When I try to deploy a Pod on the edge node, found mounting the secret is always failed in the log. I'm using the verion 1.2.1

[root@10 kubeedge]# kubectl get node
NAME            STATUS                     ROLES    AGE   VERSION
10.111.25.103   Ready,SchedulingDisabled   master   82d   v1.15.3
10.111.25.175   Ready                      <none>   82d   v1.15.3
10.111.25.176   Ready                      <none>   82d   v1.15.3
10.111.25.74    Ready                      edge     28h   v1.17.1-kubeedge-v1.2.1
[root@10 kubeedge]#
[root@10 kubeedge]#

On the edge node 10.111.25.74:   errors from the log:
E0708 21:14:09.003589   12834 metaclient.go:118] send sync message library/secret/default-token-s5ssb failed, error:timeout to get response, retries: 2
E0708 21:14:09.003655   12834 secret.go:195] Couldn't get secret library/default-token-s5ssb: get secret from metaManager failed, err: timed out waiting for the condition
E0708 21:14:09.003788   12834 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/0fa72210-bd66-45a7-8304-56b887b432a9-default-token-s5ssb\" (\"0fa72210-bd66-45a7-8304-56b887b432a9\")" failed. No retries permitted until 2020-07-08 21:14:09.503731934 +0800 CST m=+130.860163182 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"default-token-s5ssb\" (UniqueName: \"kubernetes.io/secret/0fa72210-bd66-45a7-8304-56b887b432a9-default-token-s5ssb\") pod \"edgenginx783-67d4c5cc58-rpngq\" (UID: \"0fa72210-bd66-45a7-8304-56b887b432a9\") : get secret from metaManager failed, err: timed out waiting for the condition"
E0708 21:14:09.004040   12834 process.go:408] remote query failed: timeout to get response
E0708 21:14:11.771284   12834 edged.go:776] Unable to mount volumes for pod "edgenginx783-67d4c5cc58-rpngq_library(0fa72210-bd66-45a7-8304-56b887b432a9)": unmounted volumes=[default-token-s5ssb], unattached volumes=[default-token-s5ssb]: timed out waiting for the condition; skipping pod
E0708 21:14:11.771392   12834 edged.go:714] worker [4] handle pod addition item [edgenginx783-67d4c5cc58-rpngq] failed: unmounted volumes=[default-token-s5ssb], unattached volumes=[default-token-s5ssb]: timed out waiting for the condition, re-add to queue

**Comment by daixiang0** [comment]
Could you please try latest version 1.3.1?

**Comment by luotian-github** [comment]
updated 1.3.1,   close this issue
