### ISSUE TITLE
Evaluate and enhance cloud/edge performance though QUIC

### ISSUE THREAD

**Issue by CindyXing** [kubeedge/kubeedge#191]
**What would you like to be added**:
QUIC is a protocol based on UDP. It is considered as the http 1.3 standard with higher security guard and better performance. QUIC also support congestion control and LTE/wifi live migration. 

The proposal here is to evaluate/design MQTT/HTTP using QUIC. Idea is to enhance security/performance and better load balancing. 

**Why is this needed**:
To enhance performance, security and agility between cloud and edge communication.

**Comment by sids-b** [comment]
cc @lidiyag 
Please keep updating your performance analysis here. Thanks :)

**Comment by rohitsardesai83** [comment]
@pavan187 , @edisonxiang  , how do we want to handle the progress of this issue ? we did perf tests and had numbers , how do we proceed  with this ? Can we create separate issue to target specific benchmarks and close this with the bechmarks we have already tested ?

**Comment by edisonxiang** [comment]
Hey @rohitsardesai83
Thanks your remind. Sorry for late.
The new issue is ok for me.
We have a plan to test quic between cloudhub and edgehub.
We can open a new issue since that is a specific test item.

**Comment by edisonxiang** [comment]
we may close this issue. what do you think about that?
@sids-b @rohitsardesai83

**Comment by edisonxiang** [comment]
The test result is published in the kubeedge google group.
https://groups.google.com/forum/#!topic/kubeedge/GjmtkxSKegk
So let's close this issue.
