### ISSUE TITLE
keadm get : Get and format the data in the output database edgecore.db

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#1918]
**What would you like to be added/modified**:
Get and format the data in the output database edgecore.db like `kubectl get`, help debug.
**Why is this needed**:
Various types of data now are stored in edge-side database **edgecore.db**(/var/lib/kubeedge/edgecore.db)  such as :
- pod
- secret
- configmap
- service
- endpoints
- node

Now, If we want to confirm whether a specific resource is successfully delivered to the edge, we need to use `sqlite3 /var/lib/kubeedge/edgecore.db` to get the data in edgecore.db, as below:
![image](https://user-images.githubusercontent.com/29768082/87122423-71118a00-c2b7-11ea-8bcc-ff2c9bc9dc83.png)

It is troublesome and messy comparing to `kubectl get`:
![image](https://user-images.githubusercontent.com/29768082/87122649-eaa97800-c2b7-11ea-9c75-f2cb65cb28d2.png)
![image](https://user-images.githubusercontent.com/29768082/87124393-4c1f1600-c2bb-11ea-8d7c-fbafe7780e03.png)

Tips:
1. How to get data in edgecore.db?
Refer to `edge\pkg\metamanager\dao\meta.go`

2. How to add a command to keadm?
Refer to `keadm\cmd\keadm\app\cmd\edge\join.go`

3. How to fomat data?
Refer to `kubectl get`

**Comment by daixiang0** [comment]
I think `kubectl get` can confirm deployment really or not, since db data is from cloudhub(it from api server), those part of data no need to implement by `keadm`.

**Comment by GsssC** [comment]
@daixiang0 I don’t think so. What you say it’s based on data have been successfully delivered to the side. In fact，reliable msg transmission is just realized in Feb this year by v1.3.0, and is gradually stable until recently a series of bug was fixed. In our test environment, there are still some data inconsistencies such as configmap, although  too rare to submit a issue. The code of connection management also have room to improve.

Beside, operation engineer at edge device may not have the permission to connection to k8s master; or the edge node is disconnected to cloudcore.

**Comment by daixiang0** [comment]
Also, `keadm` is more like `kubeadm`, is it the good choice to implement it?

**Comment by GsssC** [comment]
@daixiang0 This is indeed a problem, we originally plan to  implement it in a new binary `edgectl` like IEF do.  But for now, such a small feature is best integrated into `keadm`, may we can split later if keadm become too fat.

**Comment by fisherxu** [comment]
> @daixiang0 This is indeed a problem, we originally plan to implement it in a new binary edgectl like IEF do. But for now, such a small feature is best integrated into keadm, may we can split later if keadm become too fat.

In the short term, it's OK to do it in keadm first.
