### ISSUE TITLE
Race condition in podManager

### ISSUE THREAD

**Issue by Congrool** [kubeedge/kubeedge#1920]
Hello, I'm reading the source of kubeedge. 
I saw the following code in the file "/edge/pkg/edged/podmanager.go" starting from line 107.
```
func (pm *podManager) DeletePod(pod *v1.Pod) {
	pm.lock.RLock()
	defer pm.lock.RUnlock()
	podFullName := container.GetPodFullName(pod)
	delete(pm.podByUID, pod.UID)
	delete(pm.podByFullName, podFullName)
}
```
Should it use `Lock()` and `Unlock()` instead of `RLock()` and `RUnlock()` to avoid race condition of  `podByUID` and `podByFullName` ?

**Comment by fisherxu** [comment]
Thanks for pointing out, SGTM, would you like raise a PR? @Congrool

**Comment by Congrool** [comment]
Ok, I'd like to do so. @fisherxu
