### ISSUE TITLE
Deadline Setting Bug in WSConnection

### ISSUE THREAD

**Issue by Congrool** [kubeedge/kubeedge#1927]
Hello, I'm reading the source of KubeEdge.
I saw the following code in the file `/kubeedge/staging/src/github.com/kubeedge/viaduct/pkg/conn/ws.go ` starting from line 177.
```
func (conn *WSConnection) WriteMessageAsync(msg *model.Message) error {
	lane := lane.NewLane(api.ProtocolTypeWS, conn.wsConn)
	lane.SetReadDeadline(conn.WriteDeadline)
	msg.Header.Sync = false
	conn.locker.Lock()
	defer conn.locker.Unlock()
	return lane.WriteMessage(msg)
}
```
It looks strange to call function `SetReadDeadline` with argument `WriteDeadline`.
Does it mean `lane.SetWriteDeadline(conn.WriteDeadline)` here?

**Comment by Congrool** [comment]
@GsssC 
Hello, is it a bug?

**Comment by Congrool** [comment]
@GsssC 
Hello, is it a bug?

**Comment by GsssC** [comment]
Sure
