### ISSUE TITLE
keadm init error status 7

### ISSUE THREAD

**Issue by mxtsuper** [kubeedge/kubeedge#1930]
**What happened**:
I tried to install cloudcore on the k8s master.
I input the command of "./keadm init ".
But I got error status 7

detail:
Error: exit status 7
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.2.1  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver

Flags:
      --advertise-address string   Use this key to set SANs in certificate of cloudcore. eg: 10.10.102.78,10.10.102.79
  -h, --help                       help for init
      --kube-config string         Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string    Use this key to download and use the required KubeEdge version
      --master string              Use this key to set K8s master address, eg: http://127.0.0.1:8080

F0714 10:58:33.020176   34219 keadm.go:27] exit status 7
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0002dd200, 0xc0000c75c0, 0x39, 0x40)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:883 +0xb8
k8s.io/klog.(*loggingT).output(0x1f9cf60, 0xc000000003, 0xc00024d030, 0x1f0d095, 0x8, 0x1b, 0x0)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:834 +0x330
k8s.io/klog.(*loggingT).printDepth(0x1f9cf60, 0xc000000003, 0x1, 0xc000109f40, 0x1, 0x1)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:706 +0x129
k8s.io/klog.(*loggingT).print(...)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:697
k8s.io/klog.Fatal(...)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1264
main.main()
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0x8a

**What you expected to happen**:
I want to install the cloudcore.
I wonder what's the error status 7 means.
My PC(k8s master) can not connect to the Internet. Does it produce the error 7? 

Thanks
**How to reproduce it (as minimally and precisely as possible)**:
./keadm init
On the k8s master (to install the cloudcore) 
**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.1

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by daixiang0** [comment]
@mxtsuper you should use public ip to join cloudcore with `keadm`.
