### ISSUE TITLE
Optimize the code

### ISSUE THREAD

**Issue by dddddai** [kubeedge/kubeedge#1947]
1. Should it use `RWMutex` instead of `Mutex` to avoid the contention between readings?
https://github.com/kubeedge/kubeedge/blob/5921a88695113f45cfda304072097caea80dd117/cloud/pkg/cloudstream/tunnelserver.go#L74-L79

2. It calls `Unlock()` twice,which seems redundant.
https://github.com/kubeedge/kubeedge/blob/2ca99daa5cb247858b28957992c288250fb63507/staging/src/github.com/kubeedge/viaduct/pkg/conn/ws.go#L186-L202

**Comment by daixiang0** [comment]
It needs to dive deeper, since unlock twice would panic.

**Comment by GsssC** [comment]
@kadisi Whether the read scenario is much more than the write scenario and should we use `RWMutex`? why there are not func like `deleteSession`? : )

**Comment by GsssC** [comment]
@daixiang0 This func `WriteMessageSync` this function has never been referenced so this was not discovered before.
@dddddai thx for ur contribution, would like to submit a pr? : )

**Comment by dddddai** [comment]
> @daixiang0 This func `WriteMessageSync` has never been referenced so this was not discovered before.
> @dddddai thx for ur contribution, would like to submit a pr? : )

Thank you, I have created a PR. If it's unnecessary to use `RWMutex`,I would revert the change.

**Comment by fisherxu** [comment]
> why there are not func like deleteSession?

@dddddai @GsssC  Agreed, we need to dig that how to deleteSession
