### ISSUE TITLE
Document limitations of edge

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#195]
**What happened**:
Tried to deploy a pod with host and container port different. Found out that it was a limitation of edged.

**What you expected to happen**:
Pod to be created normally.

We need to document the limitations of edged so that users/developers can keep in mind those limitations while creating deployments.

**Comment by samy2019** [comment]
@sids-b , Please share the steps and the configurations for the pod.

**Comment by sids-b** [comment]
@samy2019 , This is the deployment which i used https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment . Consider this just an example. We need to come up with a document of what all functionalities of full kubernetes we do not support.

**Comment by nkwangleiGIT** [comment]
Hi @sids-b I'd like to work on this issue. As I tried, the limitation here is something like this:

```
Currently, for edge node, we must use hostPort in the Pod container spec to make it started normally, or the pod will be always in ContainerCreating status. And hostPort must be equal to containerPort and can not be 0.
You may also find that the Pod IP is <none> if you don't set hostNetwork to true, so set it to true if you need to get the expected Pod IP here.
```

Is it correct to add this note to the link below(under Deploy Application)?
https://docs.kubeedge.io/en/latest/setup/setup.html#deploy-application

**Comment by m1093782566** [comment]
@nkwangleiGIT

Any contributions are welcome, please go ahead and send a fix. Thanks!

**Comment by sids-b** [comment]
Sure @nkwangleiGIT . It would be great if you could contribute. Thanks :)

**Comment by sids-b** [comment]
Reopening this since we currently haven't documented all Limitations

**Comment by sids-b** [comment]
@nkwangleiGIT , will it be possible for you to take up this activity ?

**Comment by sids-b** [comment]
@edisonxiang 

Will it be possible for you to help in this one ?

**Comment by daixiang0** [comment]
/close

Now we both support containPort and hostPort.
