### ISSUE TITLE
Refactor mapper modbus

### ISSUE THREAD

**Issue by sailorvii** [kubeedge/kubeedge#1953]
**What would you like to be added/modified**:
Refactor the code of mapper modbus.

**Why is this needed**:
This module is written by JS which is not aligned with other modules. It's better to be refactored to go language.

**Comment by ttlv** [comment]
Is there any plan to refactor modbus mapper from js to golang？

**Comment by sailorvii** [comment]
Yes, it's ongoing now. The detailed design is at https://github.com/sailorvii/kubeedge/blob/mapperproposal/docs/proposals/mapper-redesign.md.

**Comment by ttlv** [comment]
> Yes, it's ongoing now. The detailed design is at https://github.com/sailorvii/kubeedge/blob/mapperproposal/docs/proposals/mapper-redesign.md.

yeap,that's great and device and devicemodel crd had been updated to v1alpha2 several days age,so it means the mappers which use v1alpha1 are useless.If we want to make it available,we must change both mappers,so,would you mind me join your group to complete modbus mapper together and I also have some requirements which are relation to modbus rtu.

**Comment by sailorvii** [comment]
It's happy that more people could join us. You could reach me by Wechat:13439114035.
