### ISSUE TITLE
The pod of the edge node is deleted,but container is not deleted. This is not necessarily appear

### ISSUE THREAD

**Issue by liabio** [kubeedge/kubeedge#1955]
**What happened**:
kubeedge version：1.3.0 
kubernetes version: 1.17.3

I create a deployment, the number of instances is 1000, and the nodeSelector is specified as hostname: 402, 102 pods were Running and 898 pods were Pending which due to 402 host resource is insufficient. So I delete deployment resource. After a while, all pods were deleted. When I executed **docker ps | grep 0721** on host 402, I saw that some containers were not deleted. Below is the screenshot.

there is a lot of  pod deleted logs by forces in cloudcore log，
![cloudcore log](https://user-images.githubusercontent.com/21979752/88023339-726a6e80-cb63-11ea-9ca0-2b9e6740ef3e.png)

Function of updatePodStatus  include deleted pod by forces，when I check egde controller （upstream controller）code.

![func of updatePodStatus in upstream controller](https://user-images.githubusercontent.com/21979752/88024086-ba3dc580-cb64-11ea-8312-3be6deb6e3a0.png)

**What you expected to happen**:
All containers of pods were cleaned..

**How to reproduce it (as minimally and precisely as possible)**:
The exact scene is complex and unknown，but I analyzed the Edged source code and Upstream source code，the analysis shows that the issue must exist. According to the message sent by pleg in the infinite loop of syncLoopIteration, call the updatePodStatus method, and set podStatus to Succeeded, and containerStatus.state.Terminated is not nil, resulting in pod deleted by func updatePodStatus in upstream controller.However func of deletePod expected when all containers were cleaned.

![set Succeeded pod status](https://user-images.githubusercontent.com/21979752/88025934-a8115680-cb67-11ea-93b4-d3cfa21a196b.png)

**Anything else we need to know?**:
This Bug is not necessarily appear. But the three types of go routines （podRemoveWorkerRun for kill container，syncLoopIteration for set podStatus，updatePodStatus in statusManager for updatePodStatus to metaManager, also cloudcore）are cooperating, so there will be timing problems. In the case, 5 podRemoveWorkerRun workers processing fast, there is generally no case that the container cannot be deleted; but analyzing the source code, the timing problem will definitely occur in large batches or other unknown scenarios. 

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
cloudcore and  egdecore based on version 1.3.0

**Comment by liabio** [comment]
The following are the modifications I thought of:

1. UpdatePodStatus in Edged does not use the podStatusRemote returned by calling CRI to determine the container status; consider modifying this, that is, not directly assign Succeeded to phase field, but set by result of podStatusRemote;
2. Considering that the Delete Pod message sent to the cloudcore from egdecore may be lost, modify the processDelete logic in metaManager. The message sent by Edged does not directly delete the sqlite pod information, but updates the sqlite pod status, and waits for cloudcore to send the delete message, then delete sqlite pod data.
3. If the delete pod message sent from the edgecore to the cloudcore is lost, rely on the 60s timer in the metaManager to query the pod status information from sqlite, synchronize it to the cloudcore, and use the updatePodStatus in the edge controller (upstream) to force delete the pod in etcd.

**Comment by liabio** [comment]
There are a few screenshots below, I think it is very helpful to analyze the bug of orphan containers：

I created 1000 pods on the g402 node at 14:23:08, 102 pods Running, and 898 pods were pending status due to insufficient resources on the g402 node;
I deleted the deployment resource at 14:25:20. After a while, all pods were deleted, but some containers were not deleted.

![pods were deleted，containers were not cleaned](https://user-images.githubusercontent.com/21979752/88299863-6f26dc80-cd35-11ea-9c46-ce035e77ad65.png)


![edgecore logs](https://user-images.githubusercontent.com/21979752/88299881-7221cd00-cd35-11ea-8a21-9c9c7044deca.png)

I log in to the node of g402 and check the edgecore log. The screenshot below only shows part of the log and is not continuous.

log："start to consume removed pod [test-0721-ng-li-85fb859975-vb4fb]" 
It means that go routine of podRemoveWorkerRun started to delete the container.

log: "consume added pod [test-0721-ng-li-85fb859975-vb4fb] successfully" 
It means go routine of podAddWorkerRun successfully created the container.

log: "consume removed pod [test-0721-ng-li-85fb859975-vb4fb] successfully" 
It means go routine of podRemoveWorkerRun successfully deleted the container.

But the result is that containers of the test-0721-ng-li-85fb859975-vb4fb related has not been deleted.

As you can see from the above, when deleting the containers, another go routine is creating the containers; so I think that when deleting test-0721-ng-li-85fb859975-vb4fb (ie podDeletionQueue include it), podAdditionQueue is not allowed Contains the key of test-0721-ng-li-85fb859975-vb4fb.



So I think these operations added to the podAdditionQueue queue must be checked, only add it when the pod DeletionTimestamp is nil.

![Code of added to podAdditionQueue](https://user-images.githubusercontent.com/21979752/88302875-f033a300-cd38-11ea-9ba1-f343c8c36d26.png)

**Comment by liabio** [comment]
@daixiang0

**Comment by daixiang0** [comment]
Thanks for analysis, it worth optimization i think.

Could you provide a stable way about how to reproduce it? Then we can reproduce it at our env too.

If you would love to contribute, i recommend post a proposal about optimization plan first then do coding.
