### ISSUE TITLE
Inconsistent status between master and node

### ISSUE THREAD

**Issue by Congrool** [kubeedge/kubeedge#1958]
**What happened**:
Master showed it that the status of node2 was `NotReady` and no pod was running.
However, the nginx was actually running in the background.
![image1-2020-07-21-21-35-40](https://user-images.githubusercontent.com/32788286/88061596-4ae2c880-cb9a-11ea-94ee-e268e2ed8dc8.png)

**What you expected to happen**:
I think it should be in one of the two situations:
1. Status of node2 is 'Ready' and there's at least one pod here. Thus, `curl` works well.
2. `curl` doesn't work.

**How to reproduce it (as minimally and precisely as possible)**:
First, I created a k8s cluster with a master and a node and made a nginx deployment. 
It woked well.
![image1-2020-07-21-20-55-27](https://user-images.githubusercontent.com/32788286/88057806-3223e400-cb95-11ea-8a47-05c33c35cb25.png)

Then, I wanted to construct a kubeedge cluster.
+ On the master
 typed the cmd
 `keadm init --advertise-address="192.168.79.101" --kubeedge-version=1.3.1`
+ On the node
typed the cmd 
`kubeadm reset`
`rm -rf ~/.kube`
`keadm join --cloudcore-ipport=192.168.79.101:10000 --interfacename=ens33 --token=SomeTokenHere`
Here, `ens33` is the interface name of master in my cluster.

Then I saw the status of node was `NotReady`, and the nginx was still running.
![image1-2020-07-21-21-13-13](https://user-images.githubusercontent.com/32788286/88059304-3fda6900-cb97-11ea-822f-92376aee9500.png)

I typed the cmd `kubectl delete deployment --all` to delete the nginx deployment and stop the pod. The deployment was deleted successfully, but the pod status was always in `Terminating`. 
![image1-2020-07-21-21-20-53](https://user-images.githubusercontent.com/32788286/88059980-2be33700-cb98-11ea-87f8-206b911e1dbd.png)

Thus, I typed the cmd `kubectl delete pod --all --force --grace-period=0`  to delete it.
Then, the pod disappeared, but it still ran in the background. 
cmd `curl 192.168.79.102` still worked.
![image1-2020-07-21-21-27-29](https://user-images.githubusercontent.com/32788286/88060729-2f2af280-cb99-11ea-995a-14944d14e8ff.png)

**Anything else we need to know?**:
It worked correctly again after recovering it to k8s cluster.
To be specific, using the following cmd.
+ On Master
` keadm reset`
+ On Node
`keadm reset`
Use cmd getting from `kubeadm token create --print-join-command` to join the node in the cluster.

Log at cloud side
![image](https://user-images.githubusercontent.com/32788286/88063835-1290b980-cb9d-11ea-9cd2-441789a3ab43.png)
It seamed that no connection request came.

Log at edge side
![image2-2020-07-21-22-02-37](https://user-images.githubusercontent.com/32788286/88064755-46b8aa00-cb9e-11ea-81fc-a77a1b5b470e.png)
It seams that someting wrong in certificatoin.
May be the node get the nginx pod from cache?

**CloudSide Environment**:
kubeedge 1.3.1
kubernetes 1.17.1
kubectl 1.16.1
kubeadm 1.16.1
kubelet 1.16.1
Linux CentOS 7

**EdgeSide Environment**:
kubeedge 1.3.1
kubernetes 1.17.1
kubeadm 1.16.1
kubelet 1.16.1
Linux CentOS 7

**Comment by Congrool** [comment]
Was it a bug here ?
Or just I used kubeedge in a wrong way?

**Comment by Congrool** [comment]
@GsssC

**Comment by GsssC** [comment]
@ls889

**Comment by daixiang0** [comment]
KubeEdge runs autonomously, which means even disconnected from cloud side(k8s master node), the pod in edge side still running.
You exec delete cmd after disconnected from cloud, i think the cmd do not reach edge side so that nginx still run as well at edge side, it is not a bug, it is what we wanted.

**Comment by GsssC** [comment]
You are facing two anomalies
1. NotReady means connection between cloudcore and edgecore is broken,  `pod delete event` can not be sent to edge. So it is better to check **edge-log ,cloud-log,status of edgecore, status of cloudcore **to figure out why edge can not connect to cloudcore.

**Comment by ls889** [comment]
hello, I see you have run `rm -rf ~/.kube`on the node, you should delete all ca and certificates in /etc/kubeedge/certs and /etc/kubeedge/ca on the edgenode
and then run 
`kubectl delete secret casecret -nkubeedge`
`kubectl delete secret cloudcoresecret -nkubeedge`
restart cloudcore and edgecore 
now keadm reset in v1.3.1 `can not` delete remaining certificates.

**Comment by Congrool** [comment]
@daixiang0 @GsssC @ls889 
Thanks. I've learned a lot.

**Comment by Congrool** [comment]
@ls889 
It connected to master successfully after using cmd as what you said.
Then, the new situation confuesd me.
![image1-2020-07-22-10-35-31](https://user-images.githubusercontent.com/32788286/88128087-c75fc080-cc07-11ea-9865-addc30e5444a.png)

The nginx is still running here.
Is it normal? How can i stop it?

**Comment by GsssC** [comment]
use `sqlite3 /var/lib/kubeedge/edgecore.db` to check if nginx pod is deleted in edge-store.

Ideally ,this pod will be delete by syncController

**Comment by Congrool** [comment]
> use `sqlite3 /var/lib/kubeedge/edgecore.db` to check if nginx pod is deleted in edge-store.
> 
> Ideally ,this pod will be delete by syncController


I checked edgecore.db, using ` select * from meta`.
I found nginx in it. Is it actually nginx run on the node? 
![image2-2020-07-22-11-28-17](https://user-images.githubusercontent.com/32788286/88136618-3515e780-cc1c-11ea-929f-9e464fd3de7d.png)

I checked the log of edgecore.
It said nginx had already been deleted successfully.
![image2-2020-07-22-12-42-50](https://user-images.githubusercontent.com/32788286/88136756-87ef9f00-cc1c-11ea-8934-cbcc4ef0309e.png)


![image2-2020-07-22-11-48-43](https://user-images.githubusercontent.com/32788286/88136816-b40b2000-cc1c-11ea-82c2-fcd01b16ca25.png)

There's something wrong on my system time. So the log date is still 0721.

**Comment by GsssC** [comment]
@Congrool ,  your picture about edgecore.db shows the information about edgenode, also shows`nginx image` is on this node.I think you should use `select key,type from meta where type = "pod"` to check if nginx pod is deleted in edgecore.db
But niginx pod not being killed normally seems like #1955, we're trying to figure out why.

**Comment by Congrool** [comment]
@GsssC 
Thank you for suggestion.
Actually, there's no pod in meta.

**Comment by GsssC** [comment]
@Congrool , so i think what you meet is bug #1955, need dig more deeper to know how to auto kill `deleted pod's container` like there
