### ISSUE TITLE
9.251.0.0/16是个公网网段，建议改成10.251（10代表10个月

### ISSUE THREAD

**Issue by shuyanzhu** [kubeedge/kubeedge#1959]
https://github.com/kubeedge/kubeedge/blob/6783e8a36a7ad42c49e4aac578dd927ed7040f94/pkg/apis/componentconfig/edgecore/v1alpha1/types.go#L30

**Comment by daixiang0** [comment]
Not sure about it, you can randomly ping ip in this range and you will get it unreachable.

**Comment by luogangyi** [comment]
see http://en.utrace.de/ip-address/9.251.0.14
It seems "9.251.0.0/16" belongs to IBM

**Comment by shuyanzhu** [comment]
> Not sure about it, you can randomly ping ip in this range and you will get it unreachable.

？？？这是一个学过计算机网络的人该说的话吗
??? Is this what a person who has studied computer networks should say

**Comment by daixiang0** [comment]
welcome pr :)
