### ISSUE TITLE
Modifying EdgeD integration tests to get pod information from MetaManager instead directly from EdgeD

### ISSUE THREAD

**Issue by samy2019** [kubeedge/kubeedge#196]
**What would you like to be added**:
EdgeD integration test cases, Instead of calling metamanager to get the pod list to verify application launch, It currently calls EdgeD provided (HTTP URL - GET). Integration tests should call metamanager to GET the pod list. This has to be modified.

**Why is this needed**:
EdgeD currently provides a way (HTTP URL - GET) which if requested GET's the Pod list. As per the architecture, the only interface or way to connect with EdgeD is via Meta Manager module. That is the control flow. Hence integration tests of edgeD should follow the same. Currently it directly calls edgeD url, which requires modification.
Also, The HTTP handle supported by EdgeD also will be removed soon.

**Comment by m1093782566** [comment]
We will decide if we will open source edge-monitor and edge-logger for GET data from edged.

Besides, if we want to implement GET for metamanager, we should do design first.

So just hold this issue for let get back to it once we have clear plan.

**Comment by rohitsardesai83** [comment]
@pavan187 , can you please check if this issue still holds true ?

**Comment by sids-b** [comment]
Closing this issue as currently no plan to change the current impl
