### ISSUE TITLE
端侧上报连续温度值数据丢失的问题

### ISSUE THREAD

**Issue by qingcai594** [kubeedge/kubeedge#1968]
1.1 端侧MQTT上报连续温度值数据，EdgeCore发生故障后恢复，故障期间的数据会丢失。主要原因是mosquitto没有对收到的数据进行缓存。测试客户端MQTT发布数据设Qos=0（最多分发一次）和Qos=1（至少分发一次）条件下mosquitto都没有缓存。
1.2 端侧MQTT上报连续温度值数据，CloudCore发生故障后恢复，故障期间数据丢失。丢失原因分析：dealSendToCloud时判断WebSocker连接状态，如果连接断开了就直接报错返回了，如下代码：
if strings.Compare(context.State, dtcommon.Disconnected) == 0 {
	klog.Infof("Disconnected with cloud, not send msg to cloud")
	return nil, nil
}
合理的做法应该是放在重传队列中等待重传。

**Comment by sailorvii** [comment]
1. In kubeedge project, the mqtt server is using memory as the storage currently. So the message will lose the messages after restarting/rebooting.
2. Yes, it's a choice to store some messages. However, discarding the old messages when losing connection is also reasonable.
