### ISSUE TITLE
重传机制存在BUG

### ISSUE THREAD

**Issue by qingcai594** [kubeedge/kubeedge#1969]
4.2.1 通过日志打印发现Edge没有执行dealConfirm函数，ConfirmMap中的元素没有移出，是因为Cloud没有发送确认消息，导致ConfirmMap没有移出已经发送的消息，重传定时器每60秒扫描ConfirmMap时，会重复发送消息。
4.2.2 存在多线程(插入线程和定时扫描线程)操作ConfirmMap，插入Map时机和定时器扫描时机碰撞，从而引起同一个消息被重复发送。
4.2.3 ConfirmMap队列中所有消息共享60秒周期定时器，存在确认消息未到来之前消息会被重传。
对于4.2.2和4.2.3的问题，解决方案为重传消息增加入队

**Comment by daixiang0** [comment]
Good catch! Welcome pr!

**Comment by qingcai594** [comment]
对于4.2.2和4.2.3的问题，为重传消息增加入队时间戳，定时器扫描时，只有当前时间戳-入队时间戳>重传周期的消息才重传。

**Comment by sailorvii** [comment]
I'd like to work on this issue: add a timestamp for each message and compare it when resending.

**Comment by zongke** [comment]
any idea for 4.2.1?
