### ISSUE TITLE
“ ./keadm gettoken”output bug

### ISSUE THREAD

**Issue by tanHeXiang** [kubeedge/kubeedge#1971]
Now, the output of the cmd "./keadm gettoken” looks like that
![bug2 PNG](https://user-images.githubusercontent.com/48286999/88379077-d8116180-cdd4-11ea-83fc-21dba8315450.jpg)
The "[root@new keadm]#"marked by red lines should begin in a new line. The output now looks strange and i think maybe we should fix it.

**Comment by fisherxu** [comment]
@tanHeXiang Thanks for pointing out, the issue has been fix by #1965, ptal :)
