### ISSUE TITLE
Wrong Container Runtime Type in Display

### ISSUE THREAD

**Issue by Congrool** [kubeedge/kubeedge#1972]
**What happened**
On cloud side, using `kubectl get node -o wide` will see the container-runtime is `remote://18.6.1` while the runtimeType in edgecore.yaml is `docker`.
![image1-2020-07-24-19-01-18](https://user-images.githubusercontent.com/32788286/88385027-2d9f3b80-cde0-11ea-883e-e323587e07f4.png)
![image2-2020-07-24-19-02-19](https://user-images.githubusercontent.com/32788286/88385124-5c1d1680-cde0-11ea-94ac-be5698305438.png)

**What do you want to see**
The container-runtime should be docker as same as it's described in edgecore.yaml.

I think it's something about the code in function `getNodeInfo` which is in `/kubeedge/kubeedge/edge/pkg/edged/edged_status.go`.
At line 264, it simply output "remote://".

```
        nodeInfo.ContainerRuntimeVersion = fmt.Sprintf("remote://%s", runtimeVersion.String())

	nodeInfo.KernelVersion = kernel
	nodeInfo.OperatingSystem = runtime.GOOS
	nodeInfo.Architecture = runtime.GOARCH
	nodeInfo.KubeletVersion = e.version
	nodeInfo.OSImage = prettyName
	//nodeInfo.ContainerRuntimeVersion = fmt.Sprintf("docker://%s", runtimeVersion.String())
```

To ensure my assumption, I used the following line ` nodeInfo.ContainerRuntimeVersion = fmt.Sprintf("docker://%s", runtimeVersion.String())` instead. And rebuild the `edgecore`, ran it on the edge side. It worked.
![image1-2020-07-24-19-13-02](https://user-images.githubusercontent.com/32788286/88385877-d5693900-cde1-11ea-8b74-951991d935e1.png)

However, I think it should not simply use "remote://" or "docker://". It should use  `containerRuntimeName` which is a member of edged and initialized as `RuntimeType`.
![edged go - kubeedge-v1 3 1-linux-amd64 - Visual Studio Code  Unsupported  2020_7_24 19_17_23](https://user-images.githubusercontent.com/32788286/88386174-70faa980-cde2-11ea-9f25-664fb332723f.png)

**Comment by Congrool** [comment]
@GsssC

**Comment by GsssC** [comment]
Could u submit a Pr to fix it ? :) thx

**Comment by Congrool** [comment]
Sure, I'd like to. :-)
