### ISSUE TITLE
Docker container not killed after `keadm reset`

### ISSUE THREAD

**Issue by ESWZY** [kubeedge/kubeedge#1973]
**What happened**:

Hi!

In sometimes, I lost the connection between cloud and edge (restart my virtual machines). So I have to rejoin to the cloud by `keadm join`, after running `keadm reset`.

After several times, I found there are some old containers still running, even if I just executed `keadm reset`:

![docker ps](https://user-images.githubusercontent.com/32200887/88386103-47da1900-cde2-11ea-8327-c592bce2436c.png)

**What you expected to happen**:

After run `keadm reset`, no related Docker container is running.

**How to reproduce it (as minimally and precisely as possible)**:

When deploy successfully, run `keadm reset` directlly, and run `docker ps`. You can see container(s) named `pause` in the list.

I also got almost the same result in cloud node. Maybe they have the same reason.

**Anything else we need to know?**:

By reading the source code, I found something related to that:

https://github.com/kubeedge/kubeedge/blob/ec23878a135bbad396ba847cc79cc9516663d712/keadm/cmd/keadm/app/cmd/reset.go#L76-L83

I want to ask **is there any plan still in progress at here?** I think maybe we can do something to avoid "zombie container", by:

```go
RunE: func(cmd *cobra.Command, args []string) error {
	// Tear down cloud node. It includes 
 	// 1. killing cloudcore process

 	// Tear down edge node. It includes 
 	// 1. killing edgecore process, but don't delete node from K8s 
	if err := TearDownKubeEdge(IsEdgeNode, reset.Kubeconfig); err != nil {
		return err
	}


	// For both cloud node and edge node:
	// 2. doing something else to cleanup
	if err2 := someCleaning(); err2 != nil {
		return err2
	}

	return nil
},
```

and

```go
// someCleaning does cleaning including kill old docker containers
func someCleaning() error {
	// TODO
	return nil
}
```

**Environment**:

Same environment for both cloud and edge nodes.

- KubeEdge version:  

```
KubeEdge v1.3.1
```

- Hardware configuration (e.g. `lscpu`):

```
[root@nginx-master-01 ~]# lscpu
Architecture:          	x86_64
CPU op-mode(s):        	32-bit, 64-bit
Byte Order:            	Little Endian
CPU(s):                	2
On-line CPU(s) list:   	0,1
Thread(s) per core:    	1
Core(s) per socket:    	1
座：                 	2
NUMA 节点：         	1
厂商 ID：           	GenuineIntel
CPU 系列：          	6
型号：              	94
型号名称：        	Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
步进：              	3
CPU MHz：             	2304.000
BogoMIPS：            	4608.00
超管理器厂商：  	VMware
虚拟化类型：     	完全
L1d 缓存：          	32K
L1i 缓存：          	32K
L2 缓存：           	256K
L3 缓存：           	6144K
NUMA 节点0 CPU：    	0,1
Flags:                 	fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt xsaveopt xsavec arat spec_ctrl intel_stibp flush_l1d arch_capabilities
```

- OS (e.g. `cat /etc/os-release`):

```
[root@nginx-master-01 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`):

```
[root@nginx-master-01 ~]# uname -a
Linux nginx-master-01 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- Go version (e.g. `go version`): 
```
[root@nginx-master-01 ~]# go version
go version go1.14.6 linux/amd64
```

**Comment by fisherxu** [comment]
I think we need to clear the containers created by edgecore, welcome the pr :) @ESWZY

**Comment by ESWZY** [comment]
Hi!

I added a mechanism to clean containers after reset action. The example is as below.

For edge node, it cleaned all containers beacuse there is no service here:

![edgenode reset](https://user-images.githubusercontent.com/32200887/88450940-6c3b0180-ce85-11ea-8bf3-5600b0eb3fdb.png)

For cloud node, it cleaned all containers. But there are still containers running because k8s service still running.

![cloudedge reset 1](https://user-images.githubusercontent.com/32200887/88450968-ad331600-ce85-11ea-9d94-48adc4d0c5e5.png)

We can cee some containers are created by k8s at once.

![cloudedge reset 2](https://user-images.githubusercontent.com/32200887/88450977-ccca3e80-ce85-11ea-9440-b20228fea8c6.png)

Note: The lines starting with `[Test]` is added for debugging.

**Comment by GsssC** [comment]
@ESWZY some of these containers are important for kubernetes cluster runing well, and will be always restarted by kubelet, also call it staticPods. For containers, we should only delete k8s-container on edgenode, and do noting when 'keadm reset` called in cloud.

**Comment by ESWZY** [comment]
> @ESWZY some of these containers are important for kubernetes cluster runing well, and will be always restarted by kubelet, also call it staticPods. For containers, we should only delete k8s-container on edgenode, and do noting when 'keadm reset` called in cloud.

It makes sence! Thank you!
