### ISSUE TITLE
An improvement when waiting for other goroutines

### ISSUE THREAD

**Issue by Congrool** [kubeedge/kubeedge#1974]
I see the following code in edgehub which used to wait other goroutines to return.
It simply uses `sleep()`  to wait other goroutines to return.
I don't think it's wise to work in this way, because which goroutine to run is up to the scheduler, and no assumption should be made in advance.
In the function `start()`, it runs 3 goroutines each loop, called `routeToEdge`, `routeToCloud` and `keepalive`.
![image](https://user-images.githubusercontent.com/32788286/88395801-37cb3500-cdf4-11ea-91e4-186e436ba0c1.png)

When some of the three goroutines fail to receive or send msg from or to cloudhub, it will unblock and continue. 
```
               // part of routeToCloud
                err = eh.sendToCloud(message)
		if err != nil {
			klog.Errorf("failed to send message to cloud: %v", err)
			eh.reconnectChan <- struct{}{}
			return
		}
```
```
                // part of routeToEdge
		message, err := eh.chClient.Receive()
		if err != nil {
			klog.Errorf("websocket read error: %v", err)
			eh.reconnectChan <- struct{}{}
			return
		}
```
```
		// part of keepalive
		err := eh.sendToCloud(*msg)
		if err != nil {
			klog.Errorf("websocket write error: %v", err)
			eh.reconnectChan <- struct{}{}
			return
		}
		time.Sleep(time.Duration(config.Config.Heartbeat) * time.Second)
``` 
Then it will execute `Uninit()` to close the connection between edgehub and cloudhub. All of the rest goroutines will come into error and return.

The problem is around `clean`.
We can see that it uses `time.Sleep(time.Duration(config.Config.Heartbeat) * time.Second * 2)` to wait for a period before reconnection and wait all of the goroutines to return as well. 

However, there's no ensurance that all goroutines have returned after the execution of sleep. Just think what will happen when `sleep` has done while some goroutines, such as `routeToEdge`, are still blocking at `receive()` without any opportunity to run or being aware of the closure of the connection. In the worst case, it will result in goroutine leak.

I guess it waits for `time.Duration(config.Config.Heartbeat) * time.Second * 2` because `keepalive` will block at most `time.Duration(config.Config.Heartbeat) * time.Second` as in the above code.

It's better to use other mechanism to ensure that all the goroutines have returned, such as a counter.
It seems no problem currently, because the period of Heartbeat is 15s. It's long enough in most cases.

**Comment by Congrool** [comment]
@GsssC

**Comment by GsssC** [comment]
👍 ，may we could pass contexts for such three functions，call context.done() if reconnecting

**Comment by GsssC** [comment]
Hey handsome guy, wolud like to submit a pr to improve it? : )

Of course, it none of ZJU summer camp.

**Comment by Congrool** [comment]
> Hey handsome guy, wolud like to submit a pr to improve it? : )
> 
> Of course, it none of ZJU summer camp.


Sure, I'd like to. But, it will take some time.

**Comment by Congrool** [comment]
>  ，may we could pass contexts for such three functions，call context.done() if reconnecting

Hello, is it better to use `WaitGroup`?

**Comment by Congrool** [comment]
> Hello, is it better to use `WaitGroup`?

Oh, I'm afraid that it's not a good idea.
Using `context` can close goroutines in a async way without wating for a uncertain time.

**Comment by GsssC** [comment]
@Congrool yes, connection break timing is not certain, context is a good way to close son gorutines(in logic).
