### ISSUE TITLE
Bug caused by v1alpha2 upgrade

### ISSUE THREAD

**Issue by MNTMDEV** [kubeedge/kubeedge#1979]
**What happened**:
Several days ago, I successfully executed "keadm init".
Yesterday,I runned "keadm init".It reports  404 error.

**What you expected to happen**:
"keadm init" should have downloaded the correct yaml file just like several days ago.

**How to reproduce it (as minimally and precisely as possible)**:
tar -zxvf keadm-v1.3.1-linux-amd64.tar.gz
cd keadm-v1.3.1-linux-amd64/keadm
mv keadm /bin/
keadm init

Result:
Kubernetes version verification passed, KubeEdge installation will start...
--2020-07-25 10:39:42--  https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_device.yaml
2020-07-25 10:39:43 错误 404：Not Found。

**Anything else we need to know?**:
We need to download devices_v1alpha2_device.yaml rather than devices_v1alpha1_device.yaml.
The reason is upgrading v1alpha2 while keadm still download v1alpha1.

**Environment**:
- keadm version:  1.3.1

**Comment by MNTMDEV** [comment]
@GsssC

**Comment by daixiang0** [comment]
Fix by https://github.com/kubeedge/kubeedge/pull/1975
