### ISSUE TITLE
Error: exit status 35

### ISSUE THREAD

**Issue by ccjjxx99** [kubeedge/kubeedge#1987]
**What happened**:
On edge node, sometimes when I use "keadm reset" and  then I use "keadm join",  the error occurred. When I search "exit status 35" in a search engine, I can not get any useful information;

**What you expected to happen**:
I want to get some useful information to tell me what should I do.

**How to reproduce it (as minimally and precisely as possible)**:
Sometimes when I use "keadm reset" and  then I use "keadm join"

**Anything else we need to know?**:
when I reboot the machine then use "keadm jion", it works.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  1.3.1

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): VMware, 2 CPUs and 2G Memory
- OS (e.g. `cat /etc/os-release`): Ubuntu Server 20.04
- Kernel (e.g. `uname -a`): Linux ubuntu 5.4.0-41-generic #45-Ubuntu SMP Fri Jul 3 10:57:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):  1.3.1
- Hardware configuration (e.g. `lscpu`): VMware, 2 CPUs and 2G Memory
- OS (e.g. `cat /etc/os-release`): Ubuntu Server 20.04
- Kernel (e.g. `uname -a`): Linux ubuntu 5.4.0-41-generic #45-Ubuntu SMP Fri Jul 3 10:57:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): 
- Others:

**Comment by BaldStrong** [comment]
+1
Facing the same issue on Centos 7

**Comment by daixiang0** [comment]
Based on exit code, it is not same issue.

Sorry that we have not a good solution about network issue, maybe you can download it with proxy.

**Comment by BaldStrong** [comment]
> Based on exit code, it is not same issue.
> 
> Sorry that we have not a good solution about network issue, maybe you can download it with proxy.

But return 404: Not Found when I visit https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_devicemodel.yaml directly.

**Comment by daixiang0** [comment]
It has been fixed by #1979, before post an issue, maybe you can search existed issues first.

**Comment by BaldStrong** [comment]
> It has been issued by #1979, before post an issue, maybe you can search existed issues first.

Thanks. I just found out that it's the version of v1alpha1.

**Comment by ccjjxx99** [comment]
Let me add some pictures
This is cloud node:
![image](https://user-images.githubusercontent.com/32434705/88453629-4ae51000-ce9b-11ea-944f-b288b6e34c9c.png)
This is edge node:
![image](https://user-images.githubusercontent.com/32434705/88453652-7ff16280-ce9b-11ea-9b51-0e65a04a904b.png)
![image](https://user-images.githubusercontent.com/32434705/88453657-8f70ab80-ce9b-11ea-8c3c-41fa431c2859.png)

It just prompts status 35, I don't know what the problem is.

**Comment by GsssC** [comment]
@daixiang0 Dose **exit status 35** means ssl handshake error?

**Comment by GsssC** [comment]
@ccjjxx99 It is hard to find a solution by **exit status 35**

Maybe u cloud check edgecore.log for more details

**Comment by daixiang0** [comment]
@ccjjxx99 i recommend that you rebase #1935 at local then do test, it would return details about error.

@GsssC based on [this doc](https://curl.haxx.se/libcurl/c/libcurl-errors.html), yes.
