### ISSUE TITLE
Enhancement: add confirmation prompt when reset

### ISSUE THREAD

**Issue by ESWZY** [kubeedge/kubeedge#1992]
**What would you like to be added/modified**:

Now, when we excute `keadm reset`, it will exit directly, without any confirmation prompt. Maybe we need a step for that.

**Why is this needed**:

To avoid a wrong input, or other reason not really want to reset, we need an intermediate step for confirmation. And it is also a best practice when we want to close or exit something.

For anyone who want to fix that, you can add something to `keadm/cmd/keadm/app/cmd/reset.go`.

**Comment by daixiang0** [comment]
Yep, also add `--force` to support without prompting.
