### ISSUE TITLE
nginx pod is always pending after creating

### ISSUE THREAD

**Issue by Exgc** [kubeedge/kubeedge#1993]
**What happened**:
- nginx pod is always pending after creating.

**What you expected to happen**:
- Nginx successfully deployed

**Anything else we need to know?**:
edgecore.yaml:

> apiVersion: edgecore.config.kubeedge.io/v1alpha1
database:
  aliasName: default
  dataSource: /var/lib/kubeedge/edgecore.db
  driverName: sqlite3
kind: EdgeCore
modules:
  dbTest:
    enable: false
  deviceTwin:
    enable: true
  edgeHub:
    enable: true
    heartbeat: 15
    httpServer: https://192.168.86.103:10002
    projectID: e632aba927ea4ac2b575ec1603d56f10
    quic:
      handshakeTimeout: 30
      readDeadline: 15
      server: 192.168.86.105:10001
      writeDeadline: 15
    tlsCaFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/server.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
    websocket:
      enable: true
      handshakeTimeout: 30
      readDeadline: 15
      server: 192.168.86.103:10000
      writeDeadline: 15
  edgeMesh:
    enable: true
    lbStrategy: RoundRobin
    listenInterface: docker0
    listenPort: 40001
    subNet: 9.251.0.0/16
  edgeStream:
    enable: false
    handshakeTimeout: 30
    readDeadline: 15
    server: 127.0.0.1:10004
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
    writeDeadline: 15
  edged:
    cgroupDriver: systemd
    cgroupRoot: ""
    cgroupsPerQOS: true
    clusterDNS: ""
    clusterDomain: ""
    cniBinDir: /opt/cni/bin
    cniCacheDirs: /var/lib/cni/cache
    cniConfDir: /etc/cni/net.d
    concurrentConsumers: 5
    devicePluginEnabled: false
    dockerAddress: unix:///var/run/docker.sock
    edgedMemoryCapacity: 7852396000
    enable: true
    enableMetrics: true
    gpuPluginEnabled: false
    hostnameOverride: edge
    imageGCHighThreshold: 80
    imageGCLowThreshold: 40
    imagePullProgressDeadline: 60
    interfaceName: ens33
    maximumDeadContainersPerPod: 1
    networkPluginMTU: 1500
    nodeIP: 192.168.86.105
    nodeStatusUpdateFrequency: 10
    podSandboxImage: kubeedge/pause:3.1
    registerNode: true
    registerNodeNamespace: default
    remoteImageEndpoint: unix:///var/run/dockershim.sock
    remoteRuntimeEndpoint: unix:///var/run/dockershim.sock
    runtimeRequestTimeout: 2
    runtimeType: docker
    volumeStatsAggPeriod: 60000000000
  eventBus:
    enable: true
    mqttMode: 2
    mqttQOS: 0
    mqttRetain: false
    mqttServerExternal: tcp://127.0.0.1:1883
    mqttServerInternal: tcp://127.0.0.1:1884
    mqttSessionQueueSize: 100
  metaManager:
    contextSendGroup: hub
    contextSendModule: websocket
    enable: true
    podStatusSyncInterval: 60
  serviceBus:
    enable: false

maybe useful in edgecore.log:

> I0718 04:21:06.522950    4773 record.go:19] Normal Pulled Successfully pulled image "nginx"
I0718 04:21:06.523043    4773 edged_pods.go:291] container: default/nginx-hostnetwork/nginx-hostnetwork podIP: "" creating hosts mount: false
I0718 04:21:06.523084    4773 edged_pods.go:373] Pod "nginx-hostnetwork_default(08e9f530-aec9-4991-bfae-6c784fbd38be)" container "nginx-hostnetwork" mount "default-token-5sc97" has propagation "PROPAGATION_HOST_TO_CONTAINER"
W0718 04:21:06.532108    4773 helpers.go:286] Unable to create pod sandbox due to conflict. Attempting to remove sandbox "5f9b05ba64a73a56e7adeaf3e6249bafeecea88de3fb9b591d0fa03741c9912e"
E0718 04:21:06.533256    4773 helpers.go:291] Failed to remove the conflicting container "5f9b05ba64a73a56e7adeaf3e6249bafeecea88de3fb9b591d0fa03741c9912e": Error response from daemon: You cannot remove a running container 5f9b05ba64a73a56e7adeaf3e6249bafeecea88de3fb9b591d0fa03741c9912e. Stop the container before attempting removal or force remove
E0718 04:21:06.533699    4773 remote_runtime.go:200] CreateContainer in sandbox "7212019f28c2f314f5673c0a6eadd94e25f0b858e2610ef5f79433de7152e382" from runtime service failed: rpc error: code = Unknown desc = Error response from daemon: Conflict. The container name "/k8s_nginx-hostnetwork_nginx-hostnetwork_default_08e9f530-aec9-4991-bfae-6c784fbd38be_0" is already in use by container "5f9b05ba64a73a56e7adeaf3e6249bafeecea88de3fb9b591d0fa03741c9912e". You have to remove (or rename) that container to be able to reuse that name.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
version-1.3.1
**CloudSide Environment**:
Linux master 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
**EdgeSide Environment**:
Linux edge 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by daixiang0** [comment]
I think it may related to dirty env, please clean all containers and data then re-test to ensure it runs well with clean env.
