### ISSUE TITLE
When I add an edge to cloud,error occurs and reports[fail to signCerts! error:unable to ParseECPrivateKey: x509: failed to parse private key (use ParsePKCS1PrivateKey instead for this key format)]

### ISSUE THREAD

**Issue by sunyuhan19981208** [kubeedge/kubeedge#1994]
**What happened**:
the edge is successfully join to the cloud by using "./keadm join --cloudcore-ipport=:10000 --token=" sentence,but error occurs when I use "edgecore" to add an edge end to the cloud end,error occurs and reports[fail to signCerts! error:unable to ParseECPrivateKey: x509: failed to parse private key (use ParsePKCS1PrivateKey instead for this key format)]

**What you expected to happen**:
it could be added to the cloud and no error occurs

**How to reproduce it (as minimally and precisely as possible)**:use./keadm join --cloudcore-ipport=<ip>:10000 --token=<token> to add the edge end while do not use keadm to create the cloud end

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  1.3.1

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):1cpu 2gram
- OS (e.g. `cat /etc/os-release`):Centos7
- Kernel (e.g. `uname -a`):Linux new 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): go1.14.1 linux/amd64
- Others:kubernates version:1.15.0

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):1.3.1
- Hardware configuration (e.g. `lscpu`):1cpu 2gram
- OS (e.g. `cat /etc/os-release`):Centos7
- Kernel (e.g. `uname -a`):Linux new 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): go version go1.14.1 linux/amd64
- Others:

**Comment by sunyuhan19981208** [comment]
if i dont use keadm,other error will happen:Error: failed to get CA certificate, err: Get https://192.168.217.102:10002/ca.crt: dial tcp 192.168.217.102:10002: connect: connection refused
but my port is open:
[root@new ~]# netstat -nlp|grep 10002
tcp6       0      0 :::10002                :::*                    LISTEN      1756/cloudcore

**Comment by GsssC** [comment]
@XJangel @ls889 May need your help :)

**Comment by GsssC** [comment]
> How to reproduce it (as minimally and precisely as possible):use./keadm join --cloudcore-ipport=:10000 --token= to add the edge end while do not use keadm to create the cloud end

When you use `keadm join` at edgenode, is cloudcore process running well, or firewall is up?

**Comment by sunyuhan19981208** [comment]
> > How to reproduce it (as minimally and precisely as possible):use./keadm join --cloudcore-ipport=:10000 --token= to add the edge end while do not use keadm to create the cloud end
> 
> When you use `keadm join` at edgenode, is cloudcore process running well, or firewall is up?

the cloudcore is running well,the fire wall is closed and i can add  an k8s node to this master node,but when it comes to add an edge node to the cloud node,error occurs , there're more other people meet this problem under this [blog](blog:https://blog.csdn.net/zhh2005757/article/details/107072717),and i just follow this blog and meet this trouble

**Comment by XJangel** [comment]
Did u run cloudcore before? I guess the esidual certificate results in this error.Delete the certificates in the node of cloudcore if there are(/etc/kubeedge/ca  /etc/kubeedge/certs). 'kubectl delete ns cloudcore', run this command then start cloudcore and edgecore again to see if eveything goes well.

**Comment by sunyuhan19981208** [comment]
> Did u run cloudcore before? I guess the esidual certificate results in this error.Delete the certificates in the node of cloudcore if there are(/etc/kubeedge/ca /etc/kubeedge/certs). 'kubectl delete ns cloudcore', run this command then start cloudcore and edgecore again to see if eveything goes well.

i did that and there are the same error,then i start a new virtual machine but i still cant use`keadm init --advertise-address="THE-EXPOSED-IP"` .Because when i run it, an ERROR comes that the resouce `https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_device.yaml` is not found,so i choose another way to build cloudcore without using  keadm---follow this  [blog](https://blog.csdn.net/weixin_44738411/article/details/107048809?fps=1&locationNum=2&utm_medium=distribute.pc_relevant.none-task-blog-baidujs-3&spm=1001.2101.3001.4242)
then i meet the same trouble.
![image](https://user-images.githubusercontent.com/50269851/88472074-06607f80-cf42-11ea-8d19-977fb29b1618.png)
![image](https://user-images.githubusercontent.com/50269851/88472081-14160500-cf42-11ea-8e4e-da78c0054d0e.png)

**Comment by GsssC** [comment]
Same as this issue #1979

**Comment by sunyuhan19981208** [comment]
> Same as this issue #1979

yes ,but i tried another way to build cloudcore and then met the errors above and i still cant use keadm to init the cloudcore now

**Comment by GsssC** [comment]
>the edge is successfully join to the cloud by using "./keadm join --cloudcore-ipport=:10000 --token=" sentence,but error occurs when I use "edgecore" to add an edge end to the cloud end,error occurs and reports[fail to signCerts! error:unable to ParseECPrivateKey: x509: failed to parse private key (use ParsePKCS1PrivateKey instead for this key format)]

> yes ,but i tried another way to build cloudcore and then met the errors above and i still cant use keadm to init the cloudcore now

It is confusing. Have you ever started cloudcore well?

**Comment by sunyuhan19981208** [comment]
> > the edge is successfully join to the cloud by using "./keadm join --cloudcore-ipport=:10000 --token=" sentence,but error occurs when I use "edgecore" to add an edge end to the cloud end,error occurs and reports[fail to signCerts! error:unable to ParseECPrivateKey: x509: failed to parse private key (use ParsePKCS1PrivateKey instead for this key format)]
> 
> > yes ,but i tried another way to build cloudcore and then met the errors above and i still cant use keadm to init the cloudcore now
> 
> It is confusing. Have you ever started cloudcore well?

i can get token by `./keadm gettoken`,and can get the version of cloudcore, and can use`./keadm join --cloudcore-ipport=<ip>:10000 --token=<token>
` to join an edgecore to the cloudcore,after i type join sentence it shows running,but when i started edgecore,the error i mentioned at first occurs,it says that there may be some wrong with my certs

**Comment by GsssC** [comment]
@sunyuhan19981208 could u contact me with **DingTalk** : )

**Comment by daixiang0** [comment]
In my env, can not reproduce, so the reproduction still need more details.

**Comment by luogangyi** [comment]
see  https://github.com/kubeedge/kubeedge/issues/1714 
I think you use x509 files generated in kubeedge-v1.2. 
you can try to remove /etc/kubeedge/ca and /etc/kubeedge/certs both cloud and edge side, delete all secreat in kubeedge ns of K8S.
Then, restart cloudcore, configure edgecore's token and restart edgecore

**Comment by sunyuhan19981208** [comment]
> In my env, can not reproduce, still need more details.

I think it is because i created ca and cert by using `bash certgen.sh` in directory "tools"

**Comment by sunyuhan19981208** [comment]
> see #1714
> I think you use x509 files generated in kubeedge-v1.2.
> you can try to remove /etc/kubeedge/ca and /etc/kubeedge/certs both cloud and edge side, delete all secreat in kubeedge ns of K8S.
> Then, restart cloudcore, configure edgecore's token and restart edgecore

thanks a lot,you are right,i start a new virtual machine and generate cloudcore without create these ca&cert directly run cloudcore,and then i successfully add an edgecore to the cloudcore
![image](https://user-images.githubusercontent.com/50269851/88508406-535f5700-d011-11ea-9f86-a0482a630ae2.png)
