### ISSUE TITLE
keadm join failed when it is interrupted last time

### ISSUE THREAD

**Issue by Exgc** [kubeedge/kubeedge#1995]
**What happened**:
- can not join when it has been interrupted before when join

**What you expected to happen**:
- Increase repeatability 

**How to reproduce it (as minimally and precisely as possible)**:
- ctrl+c when downloading from github
`keadm join`
> Created symlink from /etc/systemd/system/multi-user.target.wants/mosquitto.service to /usr/lib/systemd/system/mosquitto.service.
install MQTT service successfully.
--2020-07-25 03:05:05--  https://github.com/kubeedge/kubeedge/releases/download/v1.3.1/kubeedge-v1.3.1-linux-amd64.tar.gz
正在解析主机 github.com (github.com)... 13.229.188.59
正在连接 github.com (github.com)|13.229.188.59|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Found

- interrupte
`ctrl+c`

- rejoin again
`keadm join`
> F0725 03:16:32.409894    4225 keadm.go:27] failed to run command(cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v1.3.1-linux-amd64.tar.gz && cp /etc/kubeedge/kubeedge-v1.3.1-linux-amd64/edge/edgecore /usr/local/bin/), err:exit status 2
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0002dc100, 0xc0002e8000, 0xf7, 0x14b)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:883 +0xb8
k8s.io/klog.(*loggingT).output(0x1f9cf60, 0xc000000003, 0xc0002ca070, 0x1f0d095, 0x8, 0x1b, 0x0)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:834 +0x330
k8s.io/klog.(*loggingT).printDepth(0x1f9cf60, 0xc000000003, 0x1, 0xc0000ddf40, 0x1, 0x1)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:706 +0x129
k8s.io/klog.(*loggingT).print(...)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:697
k8s.io/klog.Fatal(...)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1264
main.main()
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0x8a

**Environment**:
- KubeEdge version(cloudcore/edgecore --1.3.1):

**Comment by coderkk** [comment]
Try go to /etc/kubeedge/ to remove the files?

**Comment by duguniu85** [comment]
m

> **What happened**:
> 
> * can not join when it has been interrupted before when join
> 
> **What you expected to happen**:
> 
> * Increase repeatability
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> * ctrl+c when downloading from github
>   `keadm join`
> 
> > Created symlink from /etc/systemd/system/multi-user.target.wants/mosquitto.service to /usr/lib/systemd/system/mosquitto.service.
> > install MQTT service successfully.
> > --2020-07-25 03:05:05--  https://github.com/kubeedge/kubeedge/releases/download/v1.3.1/kubeedge-v1.3.1-linux-amd64.tar.gz
> > 正在解析主机 github.com (github.com)... 13.229.188.59
> > 正在连接 github.com (github.com)|13.229.188.59|:443... 已连接。
> > 已发出 HTTP 请求，正在等待回应... 302 Found
> 
> * interrupte
>   `ctrl+c`
> * rejoin again
>   `keadm join`
> 
> > F0725 03:16:32.409894    4225 keadm.go:27] failed to run command(cd /etc/kubeedge/ && tar -C /etc/kubeedge/ -xvzf kubeedge-v1.3.1-linux-amd64.tar.gz && cp /etc/kubeedge/kubeedge-v1.3.1-linux-amd64/edge/edgecore /usr/local/bin/), err:exit status 2
> > goroutine 1 [running]:
> > k8s.io/klog.stacks(0xc0002dc100, 0xc0002e8000, 0xf7, 0x14b)
> > /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:883 +0xb8
> > k8s.io/klog.(*loggingT).output(0x1f9cf60, 0xc000000003, 0xc0002ca070, 0x1f0d095, 0x8, 0x1b, 0x0)
> > /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:834 +0x330
> > k8s.io/klog.(*loggingT).printDepth(0x1f9cf60, 0xc000000003, 0x1, 0xc0000ddf40, 0x1, 0x1)
> > /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:706 +0x129
> > k8s.io/klog.(*loggingT).print(...)
> > /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:697
> > k8s.io/klog.Fatal(...)
> > /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1264
> > main.main()
> > /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0x8a
> 
> **Environment**:
> 
> * KubeEdge version(cloudcore/edgecore --1.3.1):

my problem is same to you

**Comment by duguniu85** [comment]
my problem is same to you
