### ISSUE TITLE
Error: EdgeMesh listens udp IP, which is already used by edgecore

### ISSUE THREAD

**Issue by mxtsuper** [kubeedge/kubeedge#2004]
**What happened**:
Hello 

I installed the cloudcore and edgecore.
I found an error in the edge logs:
[EdgeMesh] dns server listen on 172.17.0.1:53 error: listen udp 172.17.0.1:53: bind: address already in use.

Then I got the IP was used by the edgecore.
netstat -ntulp |grep 53
udp        0      0 172.17.0.1:53           0.0.0.0:*                           34268/edgecore  

**What you expected to happen**:
Please how to deal with the error.  
Thanks
**How to reproduce it (as minimally and precisely as possible)**:
I built the cloudcore and edgecore. I installed them on tow virtual machine (centos 7.5)
**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
v1.3.1
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): 4 cpu 8G
- OS (e.g. `cat /etc/os-release`):centos7.5
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 1.14.4
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): 1.3.1
- Hardware configuration (e.g. `lscpu`): 4 cpu 8G
- OS (e.g. `cat /etc/os-release`): centos7.5
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 1.14.4
- Others:

**Comment by daixiang0** [comment]
I am sorry that it does not mean EdgeMesh use edgecore listen, please check your CentOS vm, you may find a service which listen on 53 port, that is the root cause.

**Comment by mxtsuper** [comment]
Hello daixiang0
1. I checked the port. There is only one progress.  The server is installed with centos only. 
netstat -ntulp |grep 53
udp 0 0 172.17.0.1:53 0.0.0.0:* 34268/edgecore

2. I tried to kill the 34268 progress. Then I found the websocket connection was down.
I guess some edgecore progress is using the Port 53. So there are some conflicts with EdgeMesh.

Could you please check whether there are some conflicts ?
Could you give some detail suggestions on dealing with the problem?

Thanks in advance

**Comment by daixiang0** [comment]
Use `sudo netstat -ntlp` to see which process listen this port.
