### ISSUE TITLE
arm环境node-exporter启动失败

### ISSUE THREAD

**Issue by vhuang0501** [kubeedge/kubeedge#2008]
云端是amd，edge端是arm，现在启edge端的时候状态是ready了，但是POD_node-exporter起不来，log报的"exec format error",查看镜像信息prom/node-exporter是"Architecture": "arm"，kubeedge/pause的信息"Architecture": "amd64",
这种情况应该怎么处理

**Comment by majoyz** [comment]
遇到了相同的问题，请问你是怎么处理的呀

> 云端是amd，edge端是arm，现在启edge端的时候状态是ready了，但是POD_node-exporter起不来，log报的"exec format error",查看镜像信息prom/node-exporter是"Architecture": "arm"，kubeedge/pause的信息"Architecture": "amd64",
> 这种情况应该怎么处理

**Comment by vhuang0501** [comment]
edgecore.yaml    

edged.podSandboxImage: kubeedge/pause-arm64:3.1
