### ISSUE TITLE
Single (standalone) machine support

### ISSUE THREAD

**Issue by marco-porru** [kubeedge/kubeedge#2017]
Hi team,
I know that the kubeedge architecture is ketween a k8s (or better kubeedge) server that exposes the APIs and a client (node) part.
I just have a raspberry pi and I don't have the possibility (due to the used infrastructure) to setup a server part "in the cloud".

Is there the possibility to run it standalone into the raspberry, without the server part in the cloud?
What I mean is: can I use only the raspberry to install the entire solution as standalone?
Or is it there any serverless implementation? 

Thanks in advance
Marco

**Comment by daixiang0** [comment]
See edgesite.

**Comment by GsssC** [comment]
Hi bro : )
KubeEdge is a kind of operater for k8s cluster. So it is necessary to deploy a k8s master node first for deploying KubeEdge. As far as I know, raspberry is too week to deploy a k8s master node as well as KubeEdge's cloudcore and edgecore at a same time.

I suggest that u could bug a ECS to deploy a k8s master node and cloudcore, and use raspberry as a edgenode to connected it to cloud across public network.
