### ISSUE TITLE
On edge node, again keadm join fail after keadm reset because of Kube-proxy process exists

### ISSUE THREAD

**Issue by yushanjin** [kubeedge/kubeedge#2022]
**What happened**:
On edge node, again keadm join fail after keadm reset because of Kube-proxy process exists
**What you expected to happen**:
return "Kube-proxy should not running on edge node when running edgecore" after keadm join, should not retrun "KubeEdge edgecore is running, For logs visit:  /var/log/kubeedge/edgecore.log"

**How to reproduce it (as minimally and precisely as possible)**:
keadm reset, and then keadm join

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.1
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:
![image](https://user-images.githubusercontent.com/12782056/89167252-bde23b00-d5ad-11ea-8274-e0c59fdfabac.png)

**Comment by GsssC** [comment]
use `docker rm KUBEPROXY_CONTAINER` manually.
This is because kubeproxy daemonset will auto deploy kubeproxy to edgenode.
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "3"
  creationTimestamp: "2020-04-29T06:57:40Z"
  generation: 3
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "27428980"
  selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy
  uid: d1ab4cc6-06b9-4bf5-8053-fb6f9f7d7184
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      containers:
      - command:
        - /usr/local/bin/kube-proxy
        - --config=/var/lib/kube-proxy/config.conf
        - --hostname-override=$(NODE_NAME)
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.aliyuncs.com/google_containers/kube-proxy:v1.17.1
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/os: linux

```

**Comment by yushanjin** [comment]
> use `docker rm KUBEPROXY_CONTAINER` manually.
> This is because kubeproxy daemonset will auto deploy kubeproxy to edgenode.
> 
> ```yaml
> apiVersion: apps/v1
> kind: DaemonSet
> metadata:
>   annotations:
>     deprecated.daemonset.template.generation: "3"
>   creationTimestamp: "2020-04-29T06:57:40Z"
>   generation: 3
>   labels:
>     k8s-app: kube-proxy
>   name: kube-proxy
>   namespace: kube-system
>   resourceVersion: "27428980"
>   selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy
>   uid: d1ab4cc6-06b9-4bf5-8053-fb6f9f7d7184
> spec:
>   revisionHistoryLimit: 10
>   selector:
>     matchLabels:
>       k8s-app: kube-proxy
>   template:
>     metadata:
>       creationTimestamp: null
>       labels:
>         k8s-app: kube-proxy
>     spec:
>       containers:
>       - command:
>         - /usr/local/bin/kube-proxy
>         - --config=/var/lib/kube-proxy/config.conf
>         - --hostname-override=$(NODE_NAME)
>         env:
>         - name: NODE_NAME
>           valueFrom:
>             fieldRef:
>               apiVersion: v1
>               fieldPath: spec.nodeName
>         image: registry.aliyuncs.com/google_containers/kube-proxy:v1.17.1
>         imagePullPolicy: IfNotPresent
>         name: kube-proxy
>         resources: {}
>         securityContext:
>           privileged: true
>         terminationMessagePath: /dev/termination-log
>         terminationMessagePolicy: File
>         volumeMounts:
>         - mountPath: /var/lib/kube-proxy
>           name: kube-proxy
>         - mountPath: /run/xtables.lock
>           name: xtables-lock
>         - mountPath: /lib/modules
>           name: lib-modules
>           readOnly: true
>       dnsPolicy: ClusterFirst
>       hostNetwork: true
>       nodeSelector:
>         beta.kubernetes.io/os: linux
> ```

yes, I know need to delete kube-proxy process before execute keadm join again. I know this by /var/log/kubeedge/edgecore.log, but the treminal prints are all normal. So, I think it's unresonable

**Comment by GsssC** [comment]
I also think it is confusing for users why **edgecore is crashing when keadm join shows all is ok**.

`keadm check` is under development for **checking installation enviroment**, plz wait some time : ) .

**Comment by WangYichen2000** [comment]
> 手动使用。这是因为 kubeproxy 守护进程会自动将 kubeproxy 部署到边缘节点。`docker rm KUBEPROXY_CONTAINER`
> 
> ```yaml
> apiVersion: apps/v1
> kind: DaemonSet
> metadata:
>   annotations:
>     deprecated.daemonset.template.generation: "3"
>   creationTimestamp: "2020-04-29T06:57:40Z"
>   generation: 3
>   labels:
>     k8s-app: kube-proxy
>   name: kube-proxy
>   namespace: kube-system
>   resourceVersion: "27428980"
>   selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy
>   uid: d1ab4cc6-06b9-4bf5-8053-fb6f9f7d7184
> spec:
>   revisionHistoryLimit: 10
>   selector:
>     matchLabels:
>       k8s-app: kube-proxy
>   template:
>     metadata:
>       creationTimestamp: null
>       labels:
>         k8s-app: kube-proxy
>     spec:
>       containers:
>       - command:
>         - /usr/local/bin/kube-proxy
>         - --config=/var/lib/kube-proxy/config.conf
>         - --hostname-override=$(NODE_NAME)
>         env:
>         - name: NODE_NAME
>           valueFrom:
>             fieldRef:
>               apiVersion: v1
>               fieldPath: spec.nodeName
>         image: registry.aliyuncs.com/google_containers/kube-proxy:v1.17.1
>         imagePullPolicy: IfNotPresent
>         name: kube-proxy
>         resources: {}
>         securityContext:
>           privileged: true
>         terminationMessagePath: /dev/termination-log
>         terminationMessagePolicy: File
>         volumeMounts:
>         - mountPath: /var/lib/kube-proxy
>           name: kube-proxy
>         - mountPath: /run/xtables.lock
>           name: xtables-lock
>         - mountPath: /lib/modules
>           name: lib-modules
>           readOnly: true
>       dnsPolicy: ClusterFirst
>       hostNetwork: true
>       nodeSelector:
>         beta.kubernetes.io/os: linux
> ```

没看懂啊，什么意思，我也遇到这个错误了
