### ISSUE TITLE
EdgeSite is keep failing at "register node" event

### ISSUE THREAD

**Issue by pkalincat** [kubeedge/kubeedge#2026]
**What happened**:
EdgeSite is keep failing on registration node event. After build EdgeSite from master branch I'am not able to register node in master server. 

```
I0804 11:33:39.013025    7317 edged_status.go:387] Attempting to register node cat-testsite-2
W0804 11:33:39.013197    7317 context_channel.go:295] Failed to get channel, type:websocket
E0804 11:33:39.013221    7317 edged_status.go:393] register node failed, error: bad request module name(websocket)
E0804 11:33:39.013248    7317 edged_status.go:395] response from cloud core: %!s(<nil>)
E0804 11:33:39.013259    7317 edged_status.go:423] Register node failed: bad request module name(websocket)
```

There is also problem with other modules like EdgeMesh:

```
W0804 11:33:39.000456    7317 context_channel.go:295] Failed to get channel, type:edgemesh
W0804 11:33:39.000989    7317 context_channel.go:72] Get bad module name :edgemesh when send message, do nothing
```

EdgeSite documentation page is outdated, there is reference to modify edgeSite.yaml configuration file but that file I can find in version v1.0.0, on master branch there is no such configuration files like edgeSite.yaml, logging.yaml, or modules.yaml

**What you expected to happen**:
EdgeSite will start and register new node in master node. 

**How to reproduce it (as minimally and precisely as possible)**:
- Create k8s cluster.
- Create edge cluster with edgesite, build edgesite from master and run with defaultconfig or minconfig with proper variables inside. 

**Anything else we need to know?**:
Nothing else to know. 

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
```
KubeEdge v1.4.0-alpha.0.257+094d66c0d6771b
```

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               60
Model name:          Intel Core Processor (Haswell, no TSX)
Stepping:            1
CPU MHz:             2095.082
BogoMIPS:            4190.16
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear
```
- OS (e.g. `cat /etc/os-release`):
```
18.04.4 LTS (Bionic Beaver)
```
- Kernel (e.g. `uname -a`):
```
Linux cat-testsite-1 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Go version (e.g. `go version`): 
```
go version go1.13.13 linux/amd64
```
- Others:

**EdgeSide Environment**:
Same as cloud side environment.

**Comment by antoniomuso** [comment]
Have you solved these errors? I have the same errors with `KubeEdge v1.5.0`.
