### ISSUE TITLE
创建一个名为camera的device，包含一个brightness的属性 ，mapper上报属性名为brightness的值后，没有被记录到device中

### ISSUE THREAD

**Issue by zhangru-dev** [kubeedge/kubeedge#2031]
devicemodel：
apiVersion: devices.kubeedge.io/v1alpha1
kind: DeviceModel
metadata:
  name: camera-model
  namespace: default
spec:
  properties:
    - name: brightness
      description: brightness collected from the edge device
      type:
        int:
          accessMode: ReadWrite

device：
apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
  name: camera
  labels:
    description: 'camera'
    manufacturer: 'test'
spec:
  deviceModelRef:
    name: camera-model
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - edge
status:
  twins:
    - propertyName: brightness
      desired:
        metadata:
          type: int
        value: ''

mappder程序：

func createActualUpdateMessage(actualValue string) DeviceTwinUpdate {
	var deviceTwinUpdateMessage DeviceTwinUpdate
	actualMap := map[string]*MsgTwin{"brightness": {Actual: &TwinValue{Value: &actualValue}, Metadata: &TypeMetadata{Type: "Updated"}}}
	deviceTwinUpdateMessage.Twin = actualMap
	return deviceTwinUpdateMessage
}

edgecore日志提示：

Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.220509    4524 client.go:92] OnSubMessageReceived receive msg from topic: $hw/events/device/camera/twin/update
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.220593    4524 client.go:109] received msg from mqttserver, deliver to twin with resource JGh3L2V2ZW50cy9kZXZpY2UvY2FtZXJhL3R3aW4vdXBkYXRl
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.220644    4524 process.go:291] DeviceTwin receive msg
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.220681    4524 process.go:204] classify the msg with the topic $hw/events/device/camera/twin/update
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.220714    4524 process.go:220] $hw/events/device/ /twin/update
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.220743    4524 process.go:230] Classify the msg to action TwinUpdate
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.220758    4524 process.go:67] Send msg to the TwinModule module in twin
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.220787    4524 twin.go:133] Twin Update EVENT
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.223873    4524 twin.go:159] Begin to update twin of the device camera
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.223911    4524 twin.go:166] Begin to deal device twin of the device camera
Aug  5 12:41:05 edge edgecore[4524]: E0805 12:41:05.223929    4524 twin.go:921] context:&{ edge map[CommModule:0xc0003608a0 DeviceModule:0xc0003607e0 MemModule:0xc000360660 TwinModule:0xc000360720] 0xc000360540 0xc000748450 0xc000748480 <nil> 0xc0007484b0 0xc0007484e0 0xc000054b80 connected},deviceID:camera, msgTwins:map[brightness:0xc000707080], dealType:map[brightness:0xc000707080]%!(EXTRA int=0)
Aug  5 12:41:05 edge edgecore[4524]: E0805 12:41:05.223997    4524 twin.go:937] deviceModel:&{camera camera camera   map[] map[]}
Aug  5 12:41:05 edge edgecore[4524]: E0805 12:41:05.224022    4524 twin.go:957] key:brightness, msgTwin:&{<nil> 0xc000dc3860 <nil> 0xc000dc3880 <nil> <nil>}
Aug  5 12:41:05 edge edgecore[4524]: E0805 12:41:05.224050    4524 twin.go:977] add twin:<nil>, exist:false
Aug  5 12:41:05 edge edgecore[4524]: E0805 12:41:05.224080    4524 twin.go:184] dealTwinResult:{[] [] [] map[] map[] map[] the value type is not allowed},dealType:0
Aug  5 12:41:05 edge edgecore[4524]: E0805 12:41:05.224126    4524 twin.go:188] SyncDeviceFromSqlite:{[] [] [] map[] map[] map[] the value type is not allowed}
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.224156    4524 membership.go:359] Sync device detail info from DB of device camera
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.224897    4524 twin.go:236] Deal update result of device camera: Build and send result
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.225312    4524 twin.go:256] Deal update result of device camera: send result
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.225401    4524 communicate.go:36] receive msg commModule
Aug  5 12:41:05 edge edgecore[4524]: I0805 12:41:05.225821    4524 eventbus.go:88] Success in pubMQTT with topic: $hw/events/device/camera/twin/update/result

疑问：为什么创建的device中没有显示brightness属性
Aug  5 12:41:05 edge edgecore[4524]: E0805 12:41:05.223997    4524 twin.go:937] deviceModel:&{camera camera camera   map[] map[]}

**Comment by luogangyi** [comment]
I have inspect the source code
```
// TwinProperty represents the device property for which an Expected/Actual state can be defined.
type TwinProperty struct {
	// Required: The value for this property.
	Value string `json:"value,"`
	// Additional metadata like timestamp when the value was reported etc.
	// +optional
	Metadata map[string]string `json:"metadata,omitempty"`
}
```
Its turn out that we only support String value in twin property.

So, if you want to use Int value, you can convert it to String first, and set "Int" in its metadata's type field to tell users that is a Int value.
