### ISSUE TITLE
suggest seperate mappers to independent repos

### ISSUE THREAD

**Issue by luogangyi** [kubeedge/kubeedge#2041]
**What would you like to be added/modified**:
suggest seperate mappers to independent repos according to their programming language, such as device-mappers-go, device-mappers-c and device-mappers-js.

**Why is this needed**:
- it is hard to maintain mappers when their amount grows.
- it is inconvenient for mappers' developer to follow main repo release cycle.
- it is hard to set CI for mappers coded in different programming languages.

**Comment by daixiang0** [comment]
BTW, could add docs about how to develop a new mapper and how to use it?

**Comment by luogangyi** [comment]
> BTW, could add docs about how to develop a new mapper and how to use it?

Yes, we are working on it. we are preparing a sdk like edegeX does to help developer to develop new mappers quickly.

**Comment by stanluk** [comment]
> > BTW, could add docs about how to develop a new mapper and how to use it?
> 
> Yes, we are working on it. we are preparing a sdk like edegeX does to help developer to develop new mappers quickly.

Dear @luguanglong , can You share a progress of this task? I am just starting to create my custom IoT solution with kubeedge and was thinking about making similar thing.
I assumed that my solution will have two pieces - first some general mapper library that will abstract communication over mqtt, handle twin updates and so on... second piece will be a code generator binary which will from deviceModel yaml resource generate the stub Go code with driver interface and mapper glue.
