### ISSUE TITLE
How to make EdgeCore support neo4j or mysql ?

### ISSUE THREAD

**Issue by Ranguo956** [kubeedge/kubeedge#2045]
KubeEdge needs to be used for verification in my scientific research. I need the persistent storage of edge nodes (EdgeCore) to support other databases, especially neo4j.But I don’t know how to operate to achieve the goal。

**Comment by luogangyi** [comment]
EdgeCore just stores metadata and cache twin values.
So, what data are u going to store in mysql?

**Comment by Ranguo01** [comment]
Yes, if possible, I need to enable edgecore to persist the ontology model (RDF data), which requires the use of a graph database or other databases that can store RDF.

**Comment by Ranguo01** [comment]
> EdgeCore just stores metadata and cache twin values.
> So, what data are u going to store in mysql?



> EdgeCore just stores metadata and cache twin values.
> So, what data are u going to store in mysql?

Yes, if possible, I need to enable edgecore to persist the ontology model (RDF data), which requires the use of a graph database or other databases that can store RDF.

**Comment by daixiang0** [comment]
Try CSI to store RDF, now EdgeCore support CSI volume.

**Comment by luogangyi** [comment]
> > EdgeCore just stores metadata and cache twin values.
> > So, what data are u going to store in mysql?
> 
> > EdgeCore just stores metadata and cache twin values.
> > So, what data are u going to store in mysql?
> 
> Yes, if possible, I need to enable edgecore to persist the ontology model (RDF data), which requires the use of a graph database or other databases that can store RDF.

So, how do you get RDF data? If you write your own mapper, I think you can directly store these data to your own database. There is no need to use edgecore's db.
