### ISSUE TITLE
Failed to add edgecore service to cloudcore

### ISSUE THREAD

**Issue by wknet123** [kubeedge/kubeedge#2051]
**What happened**:
When I execute `edgecore > /var/log/kubeedge/edgecore.log 2>&1` to start edge core service there has an error occurred as 
`certmanager.go:91] Error: failed to validate CA certificate. tokenCAhash: 63d2a5c4eb82fb58e5cdf251fb7bc132637fc7b99a740d01f81a203e132cf441, CAhash: 55b945018db981d8ed5148b5db20c4fc99577d2eff8908ad5a32b635915ed981`
**What you expected to happen**:
Start edgecore service successfully.
**How to reproduce it (as minimally and precisely as possible)**:
To start an edgecore service as manual. (Configure token and other items manually.)
**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.1
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): 4C
- OS (e.g. `cat /etc/os-release`): Ubuntu 18.04 for Cloud
- Kernel (e.g. `uname -a`): X86_64
- Go version (e.g. `go version`): 1.12.16
- Others: N/A

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): 1.3.1
- Hardware configuration (e.g. `lscpu`): 4C 
- OS (e.g. `cat /etc/os-release`):Ubuntu MATE 20.04
- Kernel (e.g. `uname -a`):  aarch64
- Go version (e.g. `go version`): N/A 
- Others: N/A

**Comment by fisherxu** [comment]
Maybe your token has expired, you can get a new token and have a try

**Comment by wknet123** [comment]
I misconfigured k8s apiserver url for cloudcore configuration, so was this error occurred. Fixed.

**Comment by hzozo** [comment]
> I misconfigured k8s apiserver url for cloudcore configuration, so was this error occurred. Fixed.

hey @wknet123, I have run into the same issue, could you please help me out what that misconfiguration was, how you fixed it?
