### ISSUE TITLE
edgecore doesn't register node again after cloudcore report node disconnected

### ISSUE THREAD

**Issue by Yellow-L** [kubeedge/kubeedge#2052]
**What happened**:
cloudcore disconnected the connection for some reason. logs shown as bellow:
```
{"log":"E0810 08:37:54.985282       1 messagehandler.go:383] Node 9770cd57a8c8485282d3ae5b78435655 disconnected and stopped sending messages\n","stream":"stderr","time":"2020-08-10T08:37:54.985399459Z"}
```
edgecore doesn't register node again because keepalive message just send and doesn't have a response check, so there no logic to do reregister.

**What you expected to happen**:
edgecore could reregister edge node to cloudcore.
**How to reproduce it (as minimally and precisely as possible)**:
cloudcore running 2 hours and all edge nodes status shown as notready, still don't know the reason.
**Anything else we need to know?**:
there's no logic to set edged.registrationCompleted to false, so no reregister mechanism to register node again unless restart edgecore.
**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.0

**Comment by GsssC** [comment]
It seem this bug has been fixed by 1.3.1.

**Comment by daixiang0** [comment]
@Yellow-L could you try with latest release to ensure its existence?

**Comment by Yellow-L** [comment]
@daixiang0 ok :)
