### ISSUE TITLE
Pod in edgenode has not podip 

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#2055]
**What happened**:
When use `keadm join`, Pod in edgenode has not podip, log and edgecore.yaml shows that `interfaceName` is wrong if interfaceName is not default `eth0`.

May we could add the tip of  `--interface-name` in the doucument of installation.
**What you expected to happen**:
Pod in edgenode has podip.
**How to reproduce it (as minimally and precisely as possible)**:
**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  master

**Comment by dddddai** [comment]
How about getting the valid interfaceName automatically?

**Comment by GsssC** [comment]
> How about getting the valid interfaceName automatically?

@dddddai yeah that is a question. A computer may have multiple netInterface, and may switch when edgecore is runing.

**Comment by dddddai** [comment]
> @dddddai yeah that is a question. A computer may have multiple netInterface, and may switch when edgecore is runing.

I mean perhaps we could set the default interfaceName automatically based on the host.

Now the the default interfaceName is fixed `eth0`
https://github.com/kubeedge/kubeedge/blob/78dafa025b4b9cdd79b9f6cc24ef530b66df206e/common/constants/default.go#L43

We may do like this

```go
var DefaultInterfaceName string

func init() {
	interfaces, err := net.Interfaces()
	if err != nil {
		// set DefaultInterfaceName = "eth0" or panic ?
		return
	}
	for _, itf := range interfaces {
		// get the first interface that is up and non-loopback
		if itf.Flags&net.FlagLoopback == 0 && itf.Flags&net.FlagUp != 0 {
			DefaultInterfaceName = itf.Name
			break
		}
	}
}
```
But it changes DefaultInterfaceName from constant to variable, and I'm afraid it might pollute `constants/default.go`.

**Comment by GsssC** [comment]
@dddddai 
InterfaceName will be override by config file `edgecore.yaml`, Now it is generated by `keadm join`:
https://github.com/kubeedge/kubeedge/blob/320ff99a4afaa90e39be9554fdd1f0aa316b7082/keadm/cmd/keadm/app/cmd/util/edgecoreinstaller.go#L94

May we could auto fill it with avaliable interface, rather than change DefaultInterfaceName. 

Your code is lgtm for choosing a avaliable interface. 
: )

**Comment by dddddai** [comment]
@GsssC 
It seems that `newJoinOptions` creates a default join option

```go
func NewEdgeJoin(out io.Writer, joinOptions *types.JoinOptions) *cobra.Command {
	if joinOptions == nil {
		joinOptions = newJoinOptions()
	}
	//...
}

func newJoinOptions() *types.JoinOptions {
	opts := &types.JoinOptions{}
	opts.CertPath = types.DefaultCertPath

	return opts
}
```

So may we do this ?

```go
func newJoinOptions() *types.JoinOptions {
	opts := &types.JoinOptions{}
	opts.CertPath = types.DefaultCertPath
	interfaces, err := net.Interfaces()
	if err != nil {
		return opts
	}
	for _, itf := range interfaces {
		// get the first interface that is up and non-loopback
		if itf.Flags&net.FlagLoopback == 0 && itf.Flags&net.FlagUp != 0 {
			opts.InterfaceName = itf.Name
			break
		}
	}
	return opts
}
```

**Comment by dddddai** [comment]
@GsssC
Thanks for your guidance. So may we change the interfaceName in `Add2ToolsList` ?
```go
func Add2ToolsList(toolList map[string]types.ToolsInstaller, flagData map[string]types.FlagData, joinOptions *types.JoinOptions) error {
	//...
	interfaceName := joinOptions.InterfaceName
	if interfaceName == "" {
		if interfaces, err := net.Interfaces(); err != nil {
			for _, itf := range interfaces {
				// get the first interface that is up and non-loopback
				if itf.Flags&net.FlagLoopback == 0 && itf.Flags&net.FlagUp != 0 {
					joinOptions.InterfaceName = itf.Name
					break
				}
			}
		}
	}
	toolList["KubeEdge"] = &util.KubeEdgeInstTool{
		//...
		InterfaceName: interfaceName,
		//...
	}
	//...
}
```

**Comment by GsssC** [comment]
@dddddai I think the first  is better. And may need add other judgement such as **multicast** and **lower_up**
![image](https://user-images.githubusercontent.com/29768082/90353641-50d4a800-e079-11ea-9b6f-ba8bd45ccff8.png)

**Comment by daixiang0** [comment]
@dddddai @GsssC 
It may be hard for us to choose for users, first interface is not always what users want. And it would make more confuse since it can run like a normal sucesssful running.

I perfer that we just check whether the default interface or the one users specify is valid, and return error if invalid.

**Comment by GsssC** [comment]
@daixiang0 Make sense, but k8s has no such problem, need to have a look what **kubeadm or kubelet** do

**Comment by GsssC** [comment]
@Rachel-Shao PTAL
