### ISSUE TITLE
checksum when download release source

### ISSUE THREAD

**Issue by ttlv** [kubeedge/kubeedge#2057]
**What happened**:
There is a broken kubeedge-v1.3.1-linux-amd64.tar.gz in /etc/kubeedge,when I use kubeadm to join and got some error.
**What you expected to happen**:
keadm will checksum for download file when I use keadm to install. don't skip even though kubeedge-v1.3.1-linux-amd64.tar.gz is existed.!!
**How to reproduce it (as minimally and precisely as possible)**:
put a broken  kubeedge-v1.3.1-linux-amd64.tar.gz in your path and use keadm to join 
**Anything else we need to know?**:
no
**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
both are 1.3.1
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               2194.917
BogoMIPS:              4389.83
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm 3dnowprefetch epb cat_l3 cdp_l3 fsgsbase smep cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
- OS (e.g. `cat /etc/os-release`): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux ke-node-47 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by fisherxu** [comment]
We can add an option, so users can decide whether to skip download, WDYT?

**Comment by ttlv** [comment]
well, I think beacuse of my confused description make you misunderstand my problem. I want to emphasize the importance of checksum for using keadm to join node into ke cluster.
eg:
because of bad network,I will download tar.gz file from ke official release early,maybe I will get a broken file and I don't konw I get a broken file.when I use keadm to join node,keadm will find a vaild name of .tar.gz file, and will skip it and go on,but In fact,the tar.gz file is broken so keadm will give some error abot can't join what's more,these error always make me confused.
please take a look at my pr

**Comment by GsssC** [comment]
@fisherxu ,It enables `keadm` running in closed and private network, i think it worth a new pr to skip download. 👍 
> We can add an option, so users can decide whether to skip download, WDYT?

@ttlv , agree 👍 
Broken file it is useless for installation
https://github.com/kubeedge/kubeedge/blob/8b60ae25ae9e4b1d498e6d935c775841984dc532/keadm/cmd/keadm/app/cmd/util/common.go#L352
`TODO` also suggests that it need to checksum everytime.

**Comment by daixiang0** [comment]
I post #1989 in the past since skip download is a hidden feature i think, maybe an option would be more clear.

Before adding an option, could we add this doc as a workaround?

**Comment by daixiang0** [comment]
I post #1989 in the past since skip download is a hidden feature i think, maybe an option would be more clear.

Before adding an option, could we add this doc as a workaround?

**Comment by ttlv** [comment]
yeah, I have seen the issur # 1989, it seems that the doc is about how to install ke node manually
