### ISSUE TITLE
can't deploy pod to the edge after the edge OS system reinstalled

### ISSUE THREAD

**Issue by faicker** [kubeedge/kubeedge#2059]
**What happened**:
At beginning, all works well. After reinstalled the edge OS system, I can't deploy pod to the edge. 
Delete the node is also tried.
The edge node is ready.

the edge log is as follows,
timeout to receive response for message: {Header:{ID:1d422345-429d-44d0-b478-d01299433023 ParentID: Timestamp:1597211281636 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:query Resource:kube-system/secret/kube-proxy-token-5htqv} Content:<nil>}

The network is OK, because the node is ready.
I can see the cloudcore responsed.

**What you expected to happen**:
should deploy pod OK.

**How to reproduce it (as minimally and precisely as possible)**:
reinstall the edge os.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
v1.3.1

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:
ubuntu 16.04

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:
ubuntu 16.04

**Comment by daixiang0** [comment]
What do you mean that reinstall edge OS? Reinstall edgecore or something else?

**Comment by GsssC** [comment]
it is because inconsistency of object-sync.
You need to delete relative object-sync.

**Comment by GsssC** [comment]
kubectl get objectsyncs.reliablesyncs.kubeedge.io --all-namespaces-owide|grep
EDGE_NODE_NAME|awk'{print$1,$2}'|while read line1 line2;do kubectl delete
objectsyncs.reliablesyncs.kubeedge.io -n $line1 $line2;done

**Comment by faicker** [comment]
still not OK.

error message is,
process.go:196] timeout to receive response for message: {Header:{ID:d323f9d9-ce16-45ff-8020-a3ba0038e007 ParentID: Timestamp:1597741826170 ResourceVersion: Sync:true} Router:{So
urce:edged Group:meta Operation:query Resource:default/secret/default-token-hh7md} Content:<nil>}

the token did exist in the cloudcore.
 kubectl get secrets -A
NAMESPACE         NAME                                             TYPE                                  DATA   AGE
default           default-token-hh7md                              kubernetes.io/service-account-token   3      90d

@GsssC

**Comment by faicker** [comment]
What I did is,
systemctl stop edgecore
rm -rf /var/lib/edged/
rm -rf /var/lib/kubeedge/edgecore.db
and then start edgecore.
I think this is equal to clear and reinstall the OS and edgecore.
@daixiang0

**Comment by daixiang0** [comment]
Please check edgecore log, and check edge node status, is it ready?

**Comment by GsssC** [comment]
Have you tried ?

> kubectl get objectsyncs.reliablesyncs.kubeedge.io --all-namespaces-owide|grep
> EDGE_NODE_NAME|awk'{print$1,$2}'|while read line1 line2;do kubectl delete
> objectsyncs.reliablesyncs.kubeedge.io -n $line1 $line2;done

**Comment by faicker** [comment]
it is ready. @daixiang0

**Comment by faicker** [comment]
yes, I did. @GsssC

**Comment by faicker** [comment]
It did work if I changed the hostname(hostnameoverride in edgecore.yaml) on edgecore.

**Comment by GsssC** [comment]
For detail, cloudcore will record all resources which are sent to edge, we call these records as objects-syncs. And cloudcore will stop a old reversion resource being sent to edge according these object-syncs . 

You delete resources in the edge, but not delete relative records. Make sure relative object syncs are delted, or all new query will be stoped:
https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/reliable-message-delivery.md

**Comment by GsssC** [comment]
And I suggest u upgrade to v1.4.0, In this version, we add object-sync-GC, user only need to delete node by `kubectl delete node $EdgeNodeName`, and these object will be deleted by cloud automaticly

**Comment by faicker** [comment]
Let me try 1.4.0

**Comment by faicker** [comment]
Yeah, the problem is solved in v1.4.0.
Thanks all.
