### ISSUE TITLE
Edgecore published service as 127.0.0.1:10350 which cannot be connected with cloud core endpoint

### ISSUE THREAD

**Issue by wknet123** [kubeedge/kubeedge#2068]
**What happened**:
Edge core service published with port 127.0.0.1:10350 service cannot be visited by cloud core endpoint for K8s flannel service.
```
root@ubuntu-bionic:~# kubectl get po -n kube-system
NAME                                    READY   STATUS    RESTARTS   AGE
coredns-7f9c544f75-br94t                1/1     Running   0          2m21s
coredns-7f9c544f75-gzm8k                1/1     Running   0          2m21s
etcd-ubuntu-bionic                      1/1     Running   0          2m18s
kube-apiserver-ubuntu-bionic            1/1     Running   0          2m18s
kube-controller-manager-ubuntu-bionic   1/1     Running   0          2m18s
kube-flannel-ds-amd64-zhkzg             1/1     Running   0          118s
kube-flannel-ds-arm64-ngtxj             0/1     Error     0          31s
kube-proxy-5qvbz                        1/1     Running   0          2m22s
kube-scheduler-ubuntu-bionic            1/1     Running   0          2m17s
root@ubuntu-bionic:~# docker logs -f kube-flannel-ds-arm64-ngtxj -n kube-system
unknown shorthand flag: 'n' in -n
See 'docker logs --help'.
root@ubuntu-bionic:~# kubectl logs -f kube-flannel-ds-arm64-ngtxj -n kube-system
Error from server: Get https://10.164.17.79:10350/containerLogs/kube-system/kube-flannel-ds-arm64-ngtxj/kube-flannel?follow=true: dial tcp 10.164.17.79:10350: connect: connection refused
```
`kube-flannel-ds-arm64-ngtxj` failed due to it cannot connect endpoint of edgecore service.
while at the edgecore this port is published as `127.0.0.1:10350` which cannot be visited outside this host.
```
root@board-desktop:~# netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 172.17.0.1:40001        0.0.0.0:*               LISTEN      470493/edgecore     
tcp        0      0 127.0.0.1:10350        0.0.0.0:*               LISTEN      470493/edgecore    
```
**What you expected to happen**:
How could I set to solve this problem when starting edge core service?
**How to reproduce it (as minimally and precisely as possible)**:
Normally setup K8s cluster with KubeEdge cloud core service and then connect edge core service to this server.
**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.1
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):  2C
- OS (e.g. `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`): Linux ubuntu-bionic 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`):  go version go1.12.16 linux/amd64
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by luogangyi** [comment]
did you forget setting "iptables -t nat -A OUTPUT -p tcp --dport 10350 -j DNAT --to $CLOUDCOREIPS:10003" ?

see [Enable kubectl logs Feature](https://docs.kubeedge.io/en/latest/setup/keadm.html?highlight=10350#enable-kubectl-logs-feature)

**Comment by wknet123** [comment]
Seems another error occurred by following these steps.
```
I0814 14:13:14.312701   38495 edgestream.go:107] Start a new tunnel stream connection ...
E0814 14:13:14.347846   38495 edgestream.go:119] dial wss://10.110.27.163:10003/v1/kubeedge/connect error websocket: bad handshake
E0814 14:13:14.347938   38495 edgestream.go:100] TLSClientConnect error websocket: bad handshake
```

**Comment by wknet123** [comment]
Still blocking at this issue. Help!

**Comment by daixiang0** [comment]
Please check iptables or firewall first.

**Comment by Ranguo956** [comment]
hey,I encountered the same problem as you, did you solve it, I don’t know how to solve it.

**Comment by daixiang0** [comment]
Please check the network and iptables/firewall.

**Comment by GsssC** [comment]
@ls889 @XJangel it seems like cert error, PTAL

**Comment by liuht777** [comment]
hey,I encountered the same problem as you, did you solve it, I don’t know how to solve it.

**Comment by myxland** [comment]
@wknet123 Hi~have u solve it?

**Comment by zhangyunxin1** [comment]
Have you solved your problem? I have the same problem

**Comment by hackers365** [comment]
I have the same problem

from 1.5 version Release Notes

> "Support Remote Exec to Pods on Edge From Cloud
> 
> Users are now able to use K8s exec api or kubectl exec command to connect to pods on the edge node. (#2075, @daixiang0, @kadisi)."


output:

> hackers365@k8s-master:/k8s$ kubectl exec nginx -c nginx-test -it -- /bin/sh
> Error from server: error dialing backend: dial tcp 192.168.209.213:10350: connect: connection refused
> hackers365@k8s-master: /k8s$ 

bug?

**Comment by daixiang0** [comment]
Do you miss this [doc](https://kubeedge.io/en/docs/setup/keadm/#enable-kubectl-logs-feature)?

**Comment by hackers365** [comment]
> 
> 
> Do you miss this [doc](https://kubeedge.io/en/docs/setup/keadm/#enable-kubectl-logs-feature)?

sorry, i miss this doc. recommend turn on this feature by default

**Comment by helloeverone** [comment]
hey,I encountered the same problem as you, did you solve it, I don’t know how to solve it.

**Comment by hexiaodai** [comment]
Have you solved your problem? I have the same problem.

**Comment by tianzhenabc** [comment]
Delete duplicate or incorrect items in Chain OUTPUT: 
sudo iptables -t nat -L -n --line-numbers
sudo iptables -t nat -D OUTPUT <id>
