### ISSUE TITLE
Need a method to generate ca for cloudcore behind a gateway

### ISSUE THREAD

**Issue by susu3621** [kubeedge/kubeedge#2070]
**What would you like to be added/modified**:
We use our kebeedge inside our internal network, and expose to external network.
And multiple service exposed to external through gateway，through domain proxy.
But if we use domain setting in edgecore, with ca generated by certgen.sh, edgecore will fail with the error below.

Error: failed to get edge certificate from the cloudcore, error: Get xxxx x509: certificate is not valid for any names, but wanted to match xxxx.

**Why is this needed**:
Reverse proxy is popular, and since edgecore run in external network(like with 4G connection) in most of the case, access cloudcore through domain will be helpful in many cases.

**Comment by daixiang0** [comment]
Please try `keam` with `advertise-address` option.
```
root:[kubeedge]$ _output/local/bin/keadm init -h

"keadm init" command install KubeEdge's master node (on the cloud) component.
It checks if the Kubernetes Master are installed already,
If not installed, please install the Kubernetes first.

Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.2.1  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver


Flags:
      --advertise-address string   Use this key to set SANs in certificate of cloudcore. eg: 10.10.102.78,10.10.102.79
```

**Comment by susu3621** [comment]
Hi @daixiang0 

Thanks for your reply.
We are catching up the kubeedge these days(not so familiar with go sadly), and will join the zoom meeting. 

We have no problem to setup with CA base on IP.
But I think the keadm method does't seems like solve this problem.

I checked the code. Currently, the cloudcore CA is a self generated and self signed certificated.
In K8S concept, this is a normal way, but when it open to the public network, the security mechanism should be different.

We believe in the production environment, there are 2 different case:
1. Root CA associated with domain name, and installed in kubeedge.
2. Root CA associated with domain name, but installed in the gateway.

For the 1st case,  I'm trying to use a ca generated by "Let's encrypt", and will share the test result.
From the code, I think this should work. 

But the 2nd case, the certificate is maintained by the other team, not the edge computing team.
Current design probably can't be used in this case, but it's not so important, we can discuss it later.

**Comment by daixiang0** [comment]
I see, we can discuss on the weekly meeting.

**Comment by susu3621** [comment]
Checked a little more in the code. Summarize here before the meeting.
Current design seems like this:
1. edge get CA from cloud
2. edge check ca if valid through token
3. edge request the edge crt
4. cloud will check edge's token
5. send the signed edge certification back.

Step 1-2 is act as the CA root. 
Step 3-4 is the normal usage of certification.

There are 2 cases we face the problem:
1. If the master is behind a gateway, which means the cloudcore can only be access through domain name like https://cloudcore1.kubeedge.io:10002/ca.crt
https://cloudcore2.kubeedge.io:10002/ca.crt
(cloudcore1.kubeedge.io and cloudcore2.kubeedge.io point to the same IP.)
How can we do this? When I use this, the the step 3 will fail.
Also gencerts.sh seems can't gen with dns name.

2. Consider if the CA is given by a reliable agent. Then step 1-2 is not necessary. (Means cloud is reliable). 
Still step 3 need the token to verify edge. But CA have a short lifetime, which means token can be updated.
Actually we use token as key here, update the key frequently seems a problem?
(But if cloudcore can support domain name with agent like "Let's encrypt", then issue 2 is not important.)

**Comment by susu3621** [comment]
If generate the server certificate by adding **DNS.1:<domain>**: to subjectAltName, I can connect to cloudcore through domain name now.
I referred to the following link. 
https://gist.github.com/cecilemuller/9492b848eb8fe46d462abeb26656c4f8

But in k8s cluster, **kubectl get node** is not showing the edge node.
The node registration is failed.

**Comment by GsssC** [comment]
@ls889 @XJangel PTAL

**Comment by XJangel** [comment]
Hi, @susu3621 
Thanks a lot for your work. I think we can add the term about domain name in `cloudcore.yaml` then add it to the cloudcore's certificate SubAltNames field when generating the certificate. That should works.

**Comment by susu3621** [comment]
Also, I find the current cert handshake can be hacked very easy when a self signed  domain is used.

What I need to do is like this:
1. setup a machine and get rootCA.cert from the cloudcore. (it can be  download through wget https://xxxx:10002/ca.crt --no-check-certificate)
2. Setup a **hack server** with this cert file.
3. pollute the DNS, and redirect cloudcore domain to **hack server.**
4. then wait for edge reboot
5. when edge reboot, it will not able to verify whether cloudcore is a fake or not, so it will send token to the hack server to request edge cert.
6. hack server can get the token from the request
7. we can use the token to create multiple fake edge to hack into the cluster.
