### ISSUE TITLE
断网情况下节点被删除，恢复网络后节点重新注册，但是有残留容器存在

### ISSUE THREAD

**Issue by lvfei103650** [kubeedge/kubeedge#2078]
**What happened**:  
cloudcore侧断网，节点删除，20分钟后恢复网络连接，节点重新注册拉起，但是有残留容器存在

**What you expected to happen**:  
断网情况下，节点被删除，恢复网络连接后，节点重新注册，残留容器被删除

**How to reproduce it (as minimally and precisely as possible)**: 
1. 两台虚机各起cloudcore、edgecore

2. 在cloucore侧部署一个简单测试应用
    kubectl apply -f deployment.yaml

3. 在cloudcore侧   模拟断网 iptables -t filter -A INPUT -s 10.27.22.107/32 -p tcp -m tcp --dport 10000 -j DROP

4. 在cloudcore侧   删除节点edgenode

5.  在cloudcore侧  等待10分钟，恢复网络  iptables -t filter -D INPUT -s 10.27.22.107/32 -p tcp -m tcp --dport 10000 -j DROP

6.  edgenode自动重新注册，重新启动一个新的pod和容器，但是断网前的容器镜像依然存在。如何删除历史遗留的容器？？?

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
cloudcore\edgecore --v1.3.1

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
座：                 1
NUMA 节点：         1
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              142
型号名称：        Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
步进：              12
CPU MHz：             1799.999
BogoMIPS：            3599.99
超管理器厂商：  KVM
虚拟化类型：     完全
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           256K
L3 缓存：           6144K
NUMA 节点0 CPU：    0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d arch_capabilities

- OS (e.g. `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux master 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Go version (e.g. `go version`): 
go version go1.13.11 linux/amd64

- Others:

**EdgeSide Environment**: 
- edgecore version (e.g. `edgecore --version`):
edgecore--v1.3.1

- Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
座：                 1
NUMA 节点：         1
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              142
型号名称：        Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
步进：              12
CPU MHz：             1799.999
BogoMIPS：            3599.99
超管理器厂商：  KVM
虚拟化类型：     完全
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           256K
L3 缓存：           6144K
NUMA 节点0 CPU：    0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d arch_capabilities

- OS (e.g. `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux control-plane.minikube.internal 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Go version (e.g. `go version`): 
go version go1.13.11 linux/amd64

- Others:

**Comment by daixiang0** [comment]
Why do you delete edge node when network is broken? I think it is a wrong action.

**Comment by yangchenliang** [comment]
> Why do you delete edge node when network is broken? I think it is a wrong action.

真实环境是这样的：
1、k8s部署在公有云上，用到了cloud provider

2、用的edge节点不是公有云上的虚机实例

3、当断网或弱网场景下触发edge节点Not Ready时，cloud provider的逻辑流程中回去触发delete node资源
![image](https://user-images.githubusercontent.com/24475740/90366849-6c03df80-e09a-11ea-8393-11e0e3090717.png)

4、节点被删除后，或触发deployment的pod重新调度

5、当edge节点上的edgecore重启后，pod再次重新部署到了edge节点

6、最后结果是edge节点之前的pod还在，残留了没被删除

**Comment by daixiang0** [comment]
KubeEdge has the power of Edge Autonomy, so whole logic is as we expected. We hope even disconnect to cloud, the edge sides still run.

Not sure weather the cloud provider has options to disable delete node, i think evict node is a better action.
