### ISSUE TITLE
Reduce edge-core binary size

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#208]
**What would you like to be added**:

Reduce edge-core binary size

**Why is this needed**:

edge-core's current binary file size is about 70MB, which is bigger than k3s. As less resource consuming is one of the declared advantages of kubeedge, we need to optimize the binary file size.

**Comment by sids-b** [comment]
cc @edisonxiang

**Comment by tedli** [comment]
go build option `-ldflags="-w -s -extldflags -static"` along with `CGO_ENABLED=1` (for sqlite), produce an 48M binary.

If we `upx` the built binary with flags `--best`, it gives us a 14M binary.

For now on the upxed one works well with basic cases.

But if we append ` --ultra-brute` to upx, the produced 11M binary won't run.

**Comment by m1093782566** [comment]
> If we upx the built binary with flags --best, it gives us a 14M binary.

Thanks for your advice, we will investigate it.

**Comment by sids-b** [comment]
Closed via #262
