### ISSUE TITLE
pvc in pending state when trying csi hostpath example setup

### ISSUE THREAD

**Issue by guihecheng** [kubeedge/kubeedge#2088]
**What happened**:
During the setup of csi hostpath example, it stucked at the pvc stage.
The pvc is always in pending state.

**What you expected to happen**:
The pvc should be available.

**How to reproduce it (as minimally and precisely as possible)**:
Setup csi hostpath with the files found in
> kubeedge/build/csisamples/hostpath/deploy

Do create sc, pvc using the files found in
> kubeedge/build/csisamples/hostpath/example

And the resources is in good state:
`kubectl get pods -n kubeedge`
>NAME                        READY   STATUS    RESTARTS   AGE
>csi-hostpath-controller-0   3/3     Running   0          104m
>csi-hostpath-edge-4zzln     2/2     Running   0          25m

**Anything else we need to know?**:
message from: `kubectl describe pvc`
>Name:          csi-hostpath-pvc
>Namespace:     default
>StorageClass:  csi-hostpath-sc
>Status:        Pending
>Volume:        
>Labels:        <none>
>Annotations:   kubectl.kubernetes.io/last-applied-configuration:
>                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"csi-hostpath->pvc","namespace":"default"},"spec":{"a...
>               volume.beta.kubernetes.io/storage-provisioner: csi-hostpath
>Finalizers:    [kubernetes.io/pvc-protection]
>Capacity:      
>Access Modes:  
>VolumeMode:    Filesystem
>Mounted By:    <none>
>Events:
>  Type     Reason                Age                 From                                                                         Message
>  ----     ------                ----                ----                                                                         -------
>  Normal   ExternalProvisioning  99s (x63 over 16m)  persistentvolume-controller                                                  waiting for a >volume to be created, either by external provisioner "csi-hostpath" or manually created by system administrator
>  Normal   Provisioning          89s (x11 over 16m)  csi-hostpath_csi-hostpath-controller-0_16749a01-e203-11ea-a78f->1e6f6f410214  External provisioner is provisioning volume for claim "default/csi-hostpath-pvc"
>  Warning  ProvisioningFailed    79s (x11 over 16m)  csi-hostpath_csi-hostpath-controller-0_16749a01-e203-11ea-a78f->1e6f6f410214  failed to provision volume with StorageClass "csi-hostpath-sc": rpc error: code = DeadlineExceeded desc = >context deadline exceeded

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
KubeEdge v1.4.0-beta.0.15+240cb030780864
KubeEdge v1.4.0-beta.0.15+240cb030780864

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
x86_64, CPUs = 2
- OS (e.g. `cat /etc/os-release`):
CentOS 7.6.1810
- Kernel (e.g. `uname -a`):
3.10.0-957.el7.x86_64
- Go version (e.g. `go version`): 
go1.13.11
- Others:

**EdgeSide Environment**:
- Hardware configuration (e.g. `lscpu`):
x86_64, CPUs = 2
- OS (e.g. `cat /etc/os-release`):
CentOS 7.6.1810
- Kernel (e.g. `uname -a`):
3.10.0-957.el7.x86_64
- Go version (e.g. `go version`): 
go1.13.11
- Others:

**Comment by daixiang0** [comment]
@fisherxu depend on #1834 :
```
root:[deploy]$ docker logs a96fe8661f52
W0825 06:11:35.215066       1 deprecatedflags.go:53] Warning: option connection-timeout="15s" is deprecated and has no effect
I0825 06:11:35.215114       1 feature_gate.go:226] feature gates: &{map[]}
I0825 06:11:35.215131       1 csi-provisioner.go:98] Version: v1.2.1-0-g971feacb
I0825 06:11:35.215144       1 csi-provisioner.go:112] Building kube configs for running in cluster...
F0825 06:11:35.215151       1 csi-provisioner.go:116] Failed to create config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
root:[deploy]$ docker logs 8068897776e7
I0825 06:11:35.464453       1 main.go:91] Version: v1.1.1-0-g0d83c92
E0825 06:11:35.464503       1 main.go:100] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

```

**Comment by guihecheng** [comment]
Trying to fix this myself, working in progress.

**Comment by jimmy-wei** [comment]
Hi @guihecheng , how do you make csi-hostpath-controller-0 works?  
I get the error from csi-provisioner:
`W0115 01:45:19.769193       1 deprecatedflags.go:53] Warning: option connection-timeout="15s" is deprecated and has no effect
I0115 01:45:19.769266       1 feature_gate.go:226] feature gates: &{map[]}
I0115 01:45:19.769314       1 csi-provisioner.go:98] Version: v1.2.1-0-g971feacb
I0115 01:45:19.769336       1 csi-provisioner.go:112] Building kube configs for running in cluster...
F0115 01:45:19.769355       1 csi-provisioner.go:116] Failed to create config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`
