### ISSUE TITLE
KubeEdge 1.4 compatibility for Golang 1.13

### ISSUE THREAD

**Issue by ESWZY** [kubeedge/kubeedge#2089]
**What happened**:

My golang version is 1.13.4, and the kubeedge version is as same as the repo.

When `$ make verify`, it reports:

```
bash hack/verify-vendor-licenses.sh
-mod=mod not supported (can be '', 'readonly', or 'vendor')
```

![image](https://user-images.githubusercontent.com/32200887/90603437-e0bb5300-e22d-11ea-8afb-108b973cf8a5.png)

And for golang 1.13.4, `$ go help build` says:

```
	-mod mode
		module download mode to use: readonly or vendor.
		See 'go help modules' for more.
```

![image](https://user-images.githubusercontent.com/32200887/90603069-43f8b580-e22d-11ea-961f-464e82b60b08.png)

But according to `https://docs.kubeedge.io/en/latest/contributing/contribute.html#preparation`, it supports golang1.13 version.

![image](https://user-images.githubusercontent.com/32200887/90602975-1f044280-e22d-11ea-8505-0a707e3c5663.png)

**Comment by fisherxu** [comment]
@ESWZY  In my env, the `hack/verify-vendor.sh` will also return error below,
```
➜  kubeedge git:(master) hack/verify-vendor.sh 
~/codes/src/github.com/kubeedge/kubeedge/staging/src/github.com/kubeedge/beehive ~/codes/src/github.com/kubeedge/kubeedge
running 'go mod tidy' for beehive
running 'go mod vendor' for beehive
~/codes/src/github.com/kubeedge/kubeedge
~/codes/src/github.com/kubeedge/kubeedge/staging/src/github.com/kubeedge/viaduct ~/codes/src/github.com/kubeedge/kubeedge
running 'go mod tidy' for viaduct
running 'go mod vendor' for viaduct
~/codes/src/github.com/kubeedge/kubeedge
running 'go mod tidy' for repo root
running 'go mod vendor' for repo root
FAILED: Vendor Verify failed. Please run the command to check your directories: git status
➜  kubeedge git:(master) ✗ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 376 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   vendor/modules.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

So you'd better to use go 1.14, but it can compile and run successfully with go 1.13.

**Comment by fisherxu** [comment]
And  for the ci test, it's better to use the `readonly` mod.
