### ISSUE TITLE
Suggestion: make the device configmap to be static

### ISSUE THREAD

**Issue by sailorvii** [kubeedge/kubeedge#2091]
**What would you like to be added/modified**:
Set the configmap to be static.

**Why is this needed**:
1. The process to track the change of configmap is complex. Either device twin or mapper has to deal with this configmap change. Device twin will also send many changing messages to mapper to. Mapper has to receive these messages and also the messages are not enough to get all information and will read the configmap file for more info. The process above makes the routine be complex.
2. For one node, the devices combined to it are almost stable, the change should be minor, so the device configmap is almost unchangeable. The value to deal with this change is minor.
3. Furthermore, we could process the configmap change with K8S method: restart the container which is easy and simple.

**Comment by luogangyi** [comment]
Agree, current mapper have two ways to track updates of device, one is configmap and another is twin messages. It will confuse mappers' developer.
Besides, we can provide some script to automatic restart mapper when detect configmap changes.

**Comment by sailorvii** [comment]
The new mapper has been implemented. Close it.
