### ISSUE TITLE
During installation, why must use /etc/kubeedge directory default? 

### ISSUE THREAD

**Issue by yushanjin** [kubeedge/kubeedge#2094]
**What would you like to be added/modified**:
add parameter in keadm init or keadm join, like keadm init --package-path=/home/xxxx
**Why is this needed**:
Beacuse, sometimes I have no disk space to storage in /. Now, we use DELL Edge GateWay 5000, 
![image](https://user-images.githubusercontent.com/12782056/90738742-0c5b3d80-e301-11ea-8a50-aa665716706c.png)

**Comment by GsssC** [comment]
make sense, plz feel free to submit pr to fix it.

**Comment by GsssC** [comment]
@Rachel-Shao Would u like to implement this feature? It is a good first try.
