### ISSUE TITLE
upgrade prow to cover more label

### ISSUE THREAD

**Issue by daixiang0** [kubeedge/kubeedge#2104]
**What would you like to be added/modified**:

Upgrade prow.

**Why is this needed**:

Now regression kind label miss, need to add it.

**Comment by kevin-wangzefeng** [comment]
Maybe we can check how Kubernetes Community manage prow deployment in a visible and declarative way.

**Comment by daixiang0** [comment]
Kubernetes store all configs under this repo, like [release related](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/release/release-config.yaml).

**Comment by daixiang0** [comment]
Done.

/close
