### ISSUE TITLE
Suggest support /metrics in stream server

### ISSUE THREAD

**Issue by luogangyi** [kubeedge/kubeedge#2106]
**What would you like to be added/modified**:
Add "/metric" in stream server to support pulling  "/metrics" such as node_exporter and kubelet provided.

**Why is this needed**:
We need a way to monitor edge node and integrate with Promethus.

Currently, we have metric server. But metric server is not designed for external monitoring system.

AFAK, Promethus + node-exporter + kubelet is widely used in K8S. And adding "/metric" in existing streaming server seems not very hard. 

If you also like the idea, I am happy to implement this feature.

**Comment by daixiang0** [comment]
Stream server works for connections which need api-server proxy, while `/metrics` is not, it should be implement in Edged.

Also, we can deploy node-exporter at edge side to collect node info.

**Comment by luogangyi** [comment]
> Stream server works for connections which need api-server proxy, while `/metrics` is not, it should be implement in Edged.
> 
> Also, we can deploy node-exporter at edge side to collect node info.

They are very similar, metric-server pull kubelet/edgecore through streamserver vs.  promethus pull node-exporter throuth streamserver.

"we can deploy node-exporter at edge side to collect node info." Yes, it's required. But cloud node has no direct connection to edge node, so promethus cannot pull node-exporter directly. It require a proxy connection like streamserver.

**Comment by daixiang0** [comment]
After we support CNI, it is not problem, prometheus can connect node-exporter as it's in k8s.

**Comment by luogangyi** [comment]
@daixiang0 would you provide some detail design info about CNI feature of kubeedge? I don't find it.
I wonder in current network topo, we can implement full function of CNI(may be it can work in edge mesh?)

**Comment by daixiang0** [comment]
It inlucdes two parts: #1834 #1856

**Comment by luogangyi** [comment]
> It inlucdes two parts: #1834 #1856

Thanks, It seems edgemesh has already achieve commmunication between edge nodes. But commmunication between edge and cloud is not implemented so far.
