### ISSUE TITLE
can not get pod metric data after restart edgecore service

### ISSUE THREAD

**Issue by lvchenggang** [kubeedge/kubeedge#2107]
**What happened**:
call URL: 127.0.0.1:10350/stats/summary at edge side, the pods metric data is null:
![image](https://user-images.githubusercontent.com/68538306/91393743-e556bb80-e86c-11ea-9270-974683642f5e.png)

**What you expected to happen**:
pod metric data should be displayed

**How to reproduce it (as minimally and precisely as possible)**:
restart edgecore service

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.0

**Comment by fisherxu** [comment]
Just had a try at my host, it's really a bug
