### ISSUE TITLE
codes in "context_channel_test.go" is not appropriate.

### ISSUE THREAD

**Issue by soolaugust** [kubeedge/kubeedge#211]
https://github.com/kubeedge/kubeedge/blob/a7f48c8539602a3d9c71efe864e77a32904f4518/common/beehive/pkg/core/context/context_channel_test.go#L22

should this be:

```go
msg, err := coreContext.Receive("test_dest")
fmt.Printf("receive msg: %v, error: %v\n", msg, err)
```

as `coreContext.Receive` returns `(model.Message, error)`.

**Comment by sids-b** [comment]
Thanks @soolaugust , It would be great if you could raise a PR for the same ?

**Comment by soolaugust** [comment]
I raise the PR https://github.com/kubeedge/kubeedge/pull/214, please check it
