### ISSUE TITLE
keadm init

### ISSUE THREAD

**Issue by slj211** [kubeedge/kubeedge#2117]
**What would you like to be added/modified**:
使用 keadm init 要在线下载cloudcore和edgecore，希望提供离线安装方式
**Why is this needed**:
批量部署时，每次去下载，影响部署速度。

**Comment by kevin-wangzefeng** [comment]
+1 we should add support for both offline installation and customized source.

**Comment by daixiang0** [comment]
@slj211 see #1989 as a workaround.
