### ISSUE TITLE
keadm join  fault on arm64

### ISSUE THREAD

**Issue by slj211** [kubeedge/kubeedge#2118]
利用keadm 加入集群时 提示：
MQTT is installed in this host
Expected or Default KubeEdge version 1.4.0 is already downloaded
Output failed:  exit status 127
Error: failed to run command(cd /etc/kubeedge/ && sudo wget -k --no-check-certificate https://raw.githubusercontent.com/kubeedge/kubeedge/release-1.4/build/tools/edgecore.service), err:exit status 127

**Comment by luogangyi** [comment]
Exit status 127 means Command Not Found.
You can test whether you can use "wget"

**Comment by slj211** [comment]
run manually  this command is ok

**Comment by slj211** [comment]
there no sudo on my device
