### ISSUE TITLE
the cloudcore message must be persistent  that suggest surport  cloudcores really are multiple replicas ,high availability.

### ISSUE THREAD

**Issue by guojianyu** [kubeedge/kubeedge#2123]
**What would you like to be added/modified**:
  the cloudcore message  should be persistent.
**Why is this needed**:
  kubectl edit/delete resources and the message  has been write to the channel,but edgenodes do not receive . then cloudcores restart that  the resource operation is loss. 
    the edgenode  data will do not update only  wait next the  resource operation .

**Comment by GsssC** [comment]
What's ur kubeedge-version?
Resource at edgenode which is older than cloud will be renewed by sync-controller in cloudcore ever 5 seconds.

refer to [synccontroller](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/reliable-message-delivery.md#synccontroller).

**Comment by luogangyi** [comment]
see https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/reliable-message-delivery.md
but the proposal is not fully implemented. 

I think you can do this based on previous design.

**Comment by guojianyu** [comment]
Thx，Thank you for getting back to me.
I think  message is too complex,maintain is diffcult.
I only suggest  follow  k8s design.
the current  cloudcores  is not really high availability.that support the feature cloudcore must be persistent.
cloudcores like k8s apiserver,is a controller and data centre(cloudcores depend etcd or other?)  
edgenode like k8s node or operator  is a stateless service ,edgenode save resources objects are  meaningless.
like pod start that the related resources have been buffered..
if edgenode go missing.cloudcore will control resouces schedul.edgenodes  reconnect .that cloudcore list the edgenode all resources. 

this is my foolish advice.
