### ISSUE TITLE
keadm init error

### ISSUE THREAD

**Issue by zhangyang1997** [kubeedge/kubeedge#2138]
[root@localhost bin]# ./keadm init --advertise-address="192.168.96.128"

Kubernetes version verification passed, KubeEdge installation will start...
--2020-09-06 00:55:15--  https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha2_devicemodel.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.
Converted links in 0 files in 0 seconds.

**Error: failed to run 'sh -c cd /etc/kubeedge/crds/devices && wget -k --no-check-certificate --progress=bar:force https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha2_devicemodel.yaml' because of error : exit status 4**

**Comment by zhangyang1997** [comment]
https://www.ioiox.com/archives/62.html

**Comment by w616054** [comment]
网络问题怎么解决的？  参数好像也不能指定yaml文件

**Comment by xianshun163** [comment]
if  this fix？
