### ISSUE TITLE
Use device API both on cloud and edge

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#2140]
**What would you like to be added/modified**:
Now we have defined device API in the cloud side, but the edgeside(edgecore and mapper) still don't use the API, we should refact edgeside and use same API on cloud and edge to reduce complexity.

**Comment by fisherxu** [comment]
Support list-watch from edgecore for applications is in our roadmap, xref: https://github.com/kubeedge/kubeedge/issues/1758, we need to add proxy tunnel to support list-watch from edgecore, then can call K8S api.

And now the device api in edge has no namespace, it's not k8s style.

**Comment by luogangyi** [comment]
seem great！ current device management code is too complicated and hard to maintain

**Comment by sourabhsingh282** [comment]
@fisherxu hi, I'm interested in working on this project as part of community bridge. I also applied on the website for the same. I would he happy to discuss more about the project and provide more information. Can you please help me getting started? :)

**Comment by kkBill** [comment]
Based on the discussion in previous community meetings, my tentative proposal is as follows: https://github.com/kkBill/kubeedge/blob/deviceapi%40edge/docs/proposals/deviceapi-edge-design.md, please have a look and let us discuss   @fisherxu @luogangyi
