### ISSUE TITLE
keadm reset does not stop edgecore

### ISSUE THREAD

**Issue by s099064146** [kubeedge/kubeedge#2141]
**What happened**:

Manually used `keadm reset` but the notification log is not correct:
```
KubeEdge edgecore is stopped, For logs visit:  /var/log/kubeedge/edgecore.log
```
There are two problems.
1. There is no such edgecore.log (Now it is changed to `journalctl -u edgecore.service -b`)
```
cat: /var/log/kubeedge/edgecore.log: No such file or directory
```
2. Edgecore is still running, and the log lied to me.
```
Error: EdgeCore is already running on this node, please run reset to clean up first
F0908 08:17:18.860185    3350 keadm.go:27] EdgeCore is already running on this node, please run reset to clean up first
```
![image](https://user-images.githubusercontent.com/40239192/92421672-54f17280-f1ac-11ea-8c60-13ebc64a54f6.png)

**What you expected to happen**:
Hope
``` shell
keadm reset
```
can still stop the edgecore.service correctly.

**How to reproduce it (as minimally and precisely as possible)**:

On Edgenode:
``` shell
keadm reset
cat /var/log/kubeedge/edgecore.log
keadm join --cloudcore-ipport=192.168.0.139:10000 --kubeedge-version=1.4.0 --token=<Token from Cloud node> --interfacename=wlan0
```

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

cloudcore:
![image](https://user-images.githubusercontent.com/40239192/92421957-be25b580-f1ad-11ea-93ef-313f63c1afba.png)
![image](https://user-images.githubusercontent.com/40239192/92421963-c2ea6980-f1ad-11ea-815a-a2e77ac34dbd.png)

edgecore:
edgecore --version: command not found
image
![image](https://user-images.githubusercontent.com/40239192/92421973-c847b400-f1ad-11ea-9018-d00383ccfd11.png)

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
root@charlie-latest:/home/charlie# lscpu
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 6
On-line CPU(s) list: 0-5
Thread(s) per core: 1
Core(s) per socket: 6
Socket(s): 1
NUMA node(s): 1
Vendor ID: GenuineIntel
CPU family: 6
Model: 158
Model name: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
Stepping: 10
CPU MHz: 800.071
CPU max MHz: 4100.0000
CPU min MHz: 800.0000
BogoMIPS: 6000.00
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
L3 cache: 9216K
NUMA node0 CPU(s): 0-5
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

- OS (e.g. `cat /etc/os-release`):
![image](https://user-images.githubusercontent.com/40239192/92422001-e4e3ec00-f1ad-11ea-8ecb-d9b67764de58.png)

- Kernel (e.g. `uname -a`):
![image](https://user-images.githubusercontent.com/40239192/92422002-e9100980-f1ad-11ea-82ad-8f5cf792b0b1.png)

- Go version (e.g. `go version`): 
![image](https://user-images.githubusercontent.com/40239192/92422007-edd4bd80-f1ad-11ea-87e3-368fe68e99ef.png)

- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
command not found
![image](https://user-images.githubusercontent.com/40239192/92422024-fdec9d00-f1ad-11ea-92c6-415d8af415f2.png)

- Hardware configuration (e.g. `lscpu`):
![image](https://user-images.githubusercontent.com/40239192/92422028-02b15100-f1ae-11ea-9446-cc914e3027f9.png)

- OS (e.g. `cat /etc/os-release`):
![image](https://user-images.githubusercontent.com/40239192/92422029-07760500-f1ae-11ea-8ee6-a8a5d8ef33a9.png)

- Kernel (e.g. `uname -a`):
![image](https://user-images.githubusercontent.com/40239192/92422031-0c3ab900-f1ae-11ea-84f3-94ab2869c731.png)

- Go version (e.g. `go version`): 
![image](https://user-images.githubusercontent.com/40239192/92422035-10ff6d00-f1ae-11ea-9ff4-bbf99d289ed7.png)

- Others:

@daixiang0 
Could you please give me some helps? Thank you very much in advance.

**Comment by daixiang0** [comment]
It is a bug i think, keadm uses systemd to start but not use it to stop.

**Comment by zzxgzgz** [comment]
Hi @s099064146,

Can you attach the output for executing the `keadm reset` command? I wonder if there's any error. The command should stop and delete the edgecore service but seems like it failed somehow.

**Comment by s099064146** [comment]
@daixiang0 
Thanks! Then, I need to check how to fix it.
@zzxgzgz 
May I ask where could I find this output? I thought it only gave me this since the "improvement" of missing the **edgecore** log file.

![image](https://user-images.githubusercontent.com/40239192/92531527-0c47c100-f261-11ea-8ec5-5878c6dc5e7b.png)

**Comment by zzxgzgz** [comment]
@s099064146 Thank you for your screenshot and reply. 

It seems like the command to stop edgecore executed successfully. 

Can you try this: 
1. After edgecore is started, run `keadm reset`
2. Before running `keadm join...` again, run `systemctl status edgecore` and see what is the output(and paste it here)? I wonder if the edgecore service is stopped and removed successfully. 
3. If edgecore service is still running, try to run `sudo systemctl stop edgecore.service && sudo rm /etc/systemd/system/edgecore.service && sudo systemctl daemon-reload && systemctl reset-failed` and see what is the result. If there's no error,  then the edgecore service should be deleted and you should be able to do `keadm join...` again without the error you've been facing.

**Comment by s099064146** [comment]
@zzxgzgz 
Thanks!

**Comment by SadmiB** [comment]
@zzxgzgz I got the same issue with kubeedge 1.5.0
when I run the above commands I'm getting this:
```
$ systemctl status edgecore
Unit edgecore.service could not be found.
$ sudo systemctl stop edgecore.service && sudo rm /etc/systemd/system/edgecore.service && sudo systemctl daemon-reload && systemctl reset-failed
Failed to stop edgecore.service: Unit edgecore.service not loaded. 
```

is there a way I could clean the node manually?

**Comment by zzxgzgz** [comment]
@SadmiB 

What is the version of kubeedge you're running? From the output you showed it looks like edgecore was never ran as a service, or the edgecore service was removed already(which is what we expect after `keadm reset`). 

On the cloud node, when you run `kubectl get nodes`, do you still see the edge node you're trying to remove? Can you share the outputs of this command?

**Comment by SadmiB** [comment]
I'm using `kubeedge-v1.5.0-linux-amd64` in ubuntu 18.04 with Kubernetes 1.19.0

yeah, kind I'm stuck in a loop when I try to join the node it tells that EdgeCore is already running
```
Error: EdgeCore is already running on this node, please run reset to clean up first
``` 
and when I try to reset it fails with this:

```
TearDown failed, err:failed to run command(sudo systemctl stop .service && sudo rm /etc/systemd/system/.service && sudo systemctl daemon-reload && systemctl reset-failed), err:exit status 5

```

But now after waiting some time the node joined the node successfully.

Thanks !

**Comment by zzxgzgz** [comment]
> @zzxgzgz I'm using `kubeedge-v1.5.0-linux-amd64` in ubuntu 18.04 with Kubernetes 1.19.0
> 
> yeah, kind I'm stuck in a loop when I try to join the node it tells that EdgeCore is already running
> 
> ```
> Error: EdgeCore is already running on this node, please run reset to clean up first
> ```
> 
> and when I try to reset it fails with this:
> 
> ```
> TearDown failed, err:failed to run command(sudo systemctl stop .service && sudo rm /etc/systemd/system/.service && sudo systemctl daemon-reload && systemctl reset-failed), err:exit status 5
> ```
> 
> But now after waiting some time the node joined the cluster successfully.
> 
> Thanks !

Glad to hear that the join was successful eventually.

**Comment by Cerfoglg** [comment]
I'm currently having the exact same issue above: it gets stuck telling me 

`EdgeCore is already running on this node, please run reset to clean up first` 

Even though the service isn't running. 

If I try to do a `keadm reset` I get:

`Output failed:  exit status 1
Output failed:  exit status 1
Output failed:  exit status 5
Error: TearDown failed, err:failed to run command(sudo systemctl stop .service && sudo rm /etc/systemd/system/.service && sudo systemctl daemon-reload && systemctl reset-failed), err:exit status 5`

This is on a VM running Ubuntu 18.04.5.
