### ISSUE TITLE
how to restart cloudcore and edgecore.

### ISSUE THREAD

**Issue by lmxia** [kubeedge/kubeedge#2142]
**What happened**:
I don't know how to restart cloudcore and edgecore.
**What you expected to happen**:
Modify /etc/kubeedge/config/cloudcore.yaml or /etc/kubeedge/config/edgecore.yaml of cloudcore and edgecore. 
We have to restart the cloudcore and edgecore. 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I used keadm to start cloudcore and edgecore.
**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
Version: v1.4.0
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): Version: v1.4.0
- Hardware configuration (e.g. `lscpu`): raspberry Pi 4B 
- OS (e.g. `cat /etc/os-release`):  
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by luogangyi** [comment]
normally, you can find the pid by `ps aux|grep cloudcore` and kill it `kill -9 PID`
and run it again `PATH/cloudcore &`

For test, I suggest you can run cloudcore and edgecore in systemd, see [Run cloudcore in systemd](https://github.com/kubeedge/kubeedge/pull/2139)

**Comment by lmxia** [comment]
just use cloudcore binary cmd, how to restart cloudcore? Or Run as a pod, there is no document.

**Comment by lmxia** [comment]
> normally, you can find the pid by `ps aux|grep cloudcore` and kill it `kill -9 PID`
> and run it again `PATH/cloudcore &`
> 
> For test, I suggest you can run cloudcore and edgecore in systemd, see [Run cloudcore in systemd](https://github.com/kubeedge/kubeedge/pull/2139)

Yes, I did this, then the node become notready,  i will try again, thanks.
