### ISSUE TITLE
ClusterObjectSyncSpec  field naming error

### ISSUE THREAD

**Issue by kexun** [kubeedge/kubeedge#2145]
在文档 "kubeedge/docs/proposals/reliable-message-delivery.md"中，有两个结构体字段命名拼写可能有点问题

the definition of 
// ClusterObjectSyncSpec stores the details of objects that sent to the edge.
type ClusterObjectSyncSpec struct {
    // Required: ObjectGroupVerion is the group and version of the object
    // that was successfully sent to the edge node.
    _**ObjectGroupVerion string `json:"objectGroupVerion,omitempty"`**    ObjectGroupVerion  ==》 是不是应该改成ObjectGroupVersion_ 
	// Required: ObjectKind is the type of the object
	// that was successfully sent to the edge node.
	ObjectKind string `json:"objectKind,omitempty"`
	// Required: ObjectName is the name of the object
	// that was successfully sent to the edge node.
	ObjectName string `json:"objectName,omitempty"`
}

and 

// ObjectSyncSpec stores the details of objects that sent to the edge.
type ObjectSyncSpec struct {
    // Required: ObjectGroupVerion is the group and version of the object
    // that was successfully sent to the edge node.
    _**ObjectGroupVerion string `json:"objectGroupVerion,omitempty"`**  ObjectGroupVerion  ==》是不是应该改成ObjectGroupVersion_ 
	// Required: ObjectKind is the type of the object
	// that was successfully sent to the edge node.
	ObjectKind string `json:"objectKind,omitempty"`
	// Required: ObjectName is the name of the object
	// that was successfully sent to the edge node.
	ObjectName string `json:"objectName,omitempty"`
}

**Comment by luogangyi** [comment]
I think you are right， would you like to fix this by PR ?

**Comment by kexun** [comment]
> I think you are right， would you like to fix this by PR ?

ok
