### ISSUE TITLE
go mod tidy error: looping trying to add package

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#2160]
**What happened**:
Error when devlop and use `make verify` to update vendor.
```
[root@node1 kubeedge]# make verify
bash hack/verify-golang.sh
go detail version: go version go1.14.8 linux/amd64
go version: 1.14.8
bash hack/verify-vendor.sh
~/go/src/kubeedge/kubeedge/staging/src/github.com/kubeedge/beehive ~/go/src/kubeedge/kubeedge
running 'go mod tidy' for beehive
running 'go mod vendor' for beehive
~/go/src/kubeedge/kubeedge
~/go/src/kubeedge/kubeedge/staging/src/github.com/kubeedge/viaduct ~/go/src/kubeedge/kubeedge
running 'go mod tidy' for viaduct
running 'go mod vendor' for viaduct
~/go/src/kubeedge/kubeedge
running 'go mod tidy' for repo root
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
go: finding module for package k8s.io/cluster-bootstrap/util/secrets
go: found k8s.io/api/auditregistration/v1alpha1 in k8s.io/api v0.0.0
go: found k8s.io/cluster-bootstrap/util/secrets in k8s.io/cluster-bootstrap v0.19.1
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
go: github.com/kubeedge/kubeedge/cloud/pkg/leaderelection imports
        k8s.io/client-go/kubernetes/scheme imports
        k8s.io/api/auditregistration/v1alpha1: looping trying to add package
make: *** [verify-vendor] Error 1
```

[k8s-CHANGELOD-1.19](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md) shows  The alpha DynamicAuditing feature gate and auditregistration.k8s.io/v1alpha1 API have been removed and are no longer supported. (#91502, @deads2k) [SIG API Machinery, Auth and Testing].
![image](https://user-images.githubusercontent.com/29768082/93286855-b8158180-f80a-11ea-86bf-fa93c962d433.png)

**What you expected to happen**:
make verify good
**How to reproduce it (as minimally and precisely as possible)**:
```shell
git clone https://github.com/GsssC/kubeedge.git
git checkout keReset
make verify
```
**ENV**:
Error occur at all of golang1.13 1.14 1.15

**Releated pr**:
#1976

**Comment by daixiang0** [comment]
Seems you have upgraded k8s vendor to 1.19, while we still on 1.18 :(

It would be better to be marked as question i think,

**Comment by GsssC** [comment]
Thx for ur comment.
I have found why !

Module kubeedge never rely on `k8s.io/cluster-bootstrap` before,  so `go mod tidy` will auto rely on the lasted verion `v1.19.1`, although its peer module belong to `k8s.io/` all is `v1.18.6`.

`go mod tidy` comes to ok to require `k8s.io/cluster-bootstrap v1.18.6` .

: )

**Comment by GsssC** [comment]
@daixiang0 
But it seems some error when `bash hack/verify-vendor-licenses.sh` and stderr too long to capture all , how to solve it?
![image](https://user-images.githubusercontent.com/29768082/93303684-74347380-f82e-11ea-9370-5ece94f9f39e.png)

**Comment by daixiang0** [comment]
Seems it is broken, you should use Go1.14+ version,

**Comment by GsssC** [comment]
@daixiang0 I am using Go1.14.8.

**Comment by GsssC** [comment]
@daixiang0 
To use `make verify > ~/out 2>&1`, I found the useful imformation of `Your LICENSES tree is out of date. Run hack/update-vendor-licenses.sh and commit the results.`
May we could stop the output of diff, which makes it hard to find the useful information, and too long and detail.
![image](https://user-images.githubusercontent.com/29768082/93427805-056c1e80-f8f1-11ea-923b-355f2e223125.png)

**Comment by daixiang0** [comment]
It is same as k8s does, if `verify-xxx` failed, should run `update-xxx` to fix it.

Let's do it since helpful for developers :)
