### ISSUE TITLE
Discussion: Support cloudcore to run as system service

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#2162]
**What would you like to be added/modified**:
Support CloudCore run as service :

- [x] fix some bugs of run edgecore as systemd service

- [ ] support cloudcore run as systemd service

- [ ] add option to keadm, for users to indicated whether cloudcore to be installed as a system service or deployment in K8s

- [ ] update document of [keadm.setup](https://github.com/kubeedge/kubeedge/blob/master/docs/setup/keadm.md)

**releated issues**
#2142
**Why is this needed**:
According to @luogangyi 

> I think running cloudcore in containers is easy to achieve high availability while running in systemd is easy to configure and test. They are not conflict.

For me, it support a easy way to restart cloudcore.

**Comment by daixiang0** [comment]
After we support deployment setup, systemd service would not be a good choice. Since cloudcore run at Kubernetes master nodes, why not cover it in Kubernetes?
