### ISSUE TITLE
pods stucked at Terminating status and can't delete.

### ISSUE THREAD

**Issue by Yellow-L** [kubeedge/kubeedge#2176]
**What happened**:
pods stucked at status of Terminating, can't delete by kubeedge.
**What you expected to happen**:
pod restart and running.
**How to reproduce it (as minimally and precisely as possible)**:
N/A
**Anything else we need to know?**:
restart edgecore, then edged receive all pods resource from metamanager which pod.DeletionTimestamp is not null, so edgecore can't creat or delete these pods.  error return at the following point:
```
func (e *edged) consumePodAddition(namespacedName *types.NamespacedName) error {
	podName := namespacedName.Name
	klog.Infof("start to consume added pod [%s]", podName)
	pod, ok := e.podManager.GetPodByName(namespacedName.Namespace, podName)
	if !ok || pod.DeletionTimestamp != nil {
		return apis.ErrPodNotFound    
	}
```
**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.0

**Comment by daixiang0** [comment]
Try `kubectl delete --force --grace-period=0`.

**Comment by Yellow-L** [comment]
@daixiang0 delete manually is ok, but is there a way to delete these Terminating pods automaticly for a large scale cluster?

**Comment by daixiang0** [comment]
Treminating pods mean something in process, it is hard to handle automaticly in k8s too, especially in a large cluster.

**Comment by Yellow-L** [comment]
yes, maybe volumes or cgroup deletion error encountered, or docker rpc error.
