### ISSUE TITLE
Documentation Fixes

### ISSUE THREAD

**Issue by alanisaac** [kubeedge/kubeedge#2196]
### Request
I was wondering if the maintainers of this project would be open to small enhancements from the community in documentation files to fix spelling, grammar, and other points of clarity.  Below, I've listed some examples of what I mean, though there are many more I did not list.

If the maintainers are open to it, I'd be happy to do a fuller run-through of the documentation as well to help make it more understandable.

**What would you like to be added/modified**:
Make small tweaks to the KubeEdge documentation to enhance readability and clarity.  

**Why is this needed**:
Easy to understand documentation can help users succeed with this project, and empowers them to be self-sufficient.

### Examples of Fixes

https://docs.kubeedge.io/en/latest/setup/upgrade.html

> Upgradation

Suggestion: **Upgrading**

https://docs.kubeedge.io/en/latest/governance.html

> The governance model adopted here is heavily influenced by a set of CNCF projects, especially drew reference from Kubernetes governance.

Suggestion: **drawing** reference

https://docs.kubeedge.io/en/latest/components/edge/edged.html

> It helps user to deploy containerized workloads or applications at the edge node.

Suggestion: It helps **users** to deploy

> In future other runtime support shall be added, like containerd etc.

Suggestion: In **the** future, **support for other runtimes** shall be added

> Whenever edged queries for a new secret which Metamanager doesn’t has, the request is forwared to cloud.

Suggestion: Whenever edged queries for a new secret which Metamanager doesn’t **have**, the request is **forwarded** to cloud.

**Comment by anvithks** [comment]
Hi @alanisaac Thank you for the suggestions. 
If you are comfortable using GitHub and interested in contributing, you can fork this repository and make changes to the docs located here [https://github.com/kubeedge/kubeedge/tree/master/docs](https://github.com/kubeedge/kubeedge/tree/master/docs)

I am pretty sure the maintainers will be more than happy for the contributions.

**Comment by alanisaac** [comment]
@anvithks sounds good, will do.

**Comment by GsssC** [comment]
Thx for ur contribution! could we could close this issue?

**Comment by fisherxu** [comment]
> I was wondering if the maintainers of this project would be open to small enhancements from the community in documentation files to fix spelling, grammar, and other points of clarity. 

@alanisaac  We welcome all the efforts to the project :)

**Comment by alanisaac** [comment]
@GsssC I'm continuing to look over the documentation, and will make at least 1 more PR for this issue.  There are additional fixes that I think could be made to the storage and configuration documentation pages that I am working on.

**Comment by daixiang0** [comment]
@alanisaac Hi, now we move docs to kubeedge/website repo, if you would like to continute contribution, please move there, thanks.

/close
