### ISSUE TITLE
Master branch build fails

### ISSUE THREAD

**Issue by skdwriting** [kubeedge/kubeedge#2198]
**What happened**:
Tried to build for x86 from x86 using the following commands:
git clone https://github.com/kubeedge/kubeedge.git $GOPATH/src/github.com/kubeedge/kubeedge
cd $GOPATH/src/github.com/kubeedge/kubeedge/
export GOARCH=amd64
export GOOS="linux"
export CC=gcc
make all

[Tried **make edgecore** -- failed, make clean looks like working]
]
FAILED:
root@sanildell:~/gopath/src/github.com/kubeedge/kubeedge# make all
bash hack/verify-golang.sh
go detail version: go version go1.13.9 linux/amd64
go version: 1.13.9
hack/make-rules/build.sh 
building github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
+ go build -o /root/gopath/src/github.com/kubeedge/kubeedge/_output/local/bin/cloudcore -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2020-09-26T22:44:34Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=ec7ca87d4dd63d58e99c3ec4ffa1944fe51adbf3 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.4.0-beta.0.153+ec7ca87d4dd63d -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=4+' github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
# runtime
/usr/local/go/src/runtime/map.go:65:2: bucketCntBits redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:64:18
/usr/local/go/src/runtime/map.go:66:2: bucketCnt redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:65:23
/usr/local/go/src/runtime/map.go:77:2: maxKeySize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:74:17
/usr/local/go/src/runtime/map.go:83:2: dataOffset redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:83:4
/usr/local/go/src/runtime/map.go:94:2: evacuatedX redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:91:19
/usr/local/go/src/runtime/map.go:95:2: evacuatedY redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:92:19
/usr/local/go/src/runtime/map.go:96:2: evacuatedEmpty redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:90:19
/usr/local/go/src/runtime/map.go:97:2: minTopHash redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:93:19
/usr/local/go/src/runtime/map.go:100:2: iterator redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:96:17
/usr/local/go/src/runtime/map.go:101:2: oldIterator redeclared in this block
	previous declaration at /usr/local/go/src/runtime/hashmap.go:97:17
/usr/local/go/src/runtime/map.go:101:2: too many errors
Makefile:41: recipe for target 'all' failed
make: *** [all] Error 2

**What you expected to happen**:
Build Passed.

**How to reproduce it (as minimally and precisely as possible)**:
As above

**Anything else we need to know?**:
The documentation is not very clear for building on x86

**Environment**:
- KubeEdge master branch

**CloudSide Environment**:
NA
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
NA
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**Comment by daixiang0** [comment]
@skdwriting now we use Go1.14+ to build.
