### ISSUE TITLE
Does kubeedge synchronize podstatus correctly?

### ISSUE THREAD

**Issue by KingOnTheStar** [kubeedge/kubeedge#22]
I see metaManager try to synchronize podstatus in database to cloud per minute, however it look like edged never send podstatus message to metaManager, so podstatus won't be recorded in database.
Should struct GenericLifecycle send podstatus to metaManager in function updatePodStatus(pod *v1.Pod) ?

**Comment by z00223295** [comment]
@KingOnTheStar sending podstatus message to metaManager is in status_manager.go.
https://github.com/kubeedge/kubeedge/blob/203c91dd83db08cf19a772a5bd14b06d21d21fa7/pkg/edged/status/status_manager.go#L96-L99

**Comment by KingOnTheStar** [comment]
Oh, this problem was solved 3 days ago in commit "fix pod status manager". My code is out of date.
Thanks

**Comment by m1093782566** [comment]
@KingOnTheStar Yes, we fix this issue some days ago.
