### ISSUE TITLE
pod recreate when node network interrupt for long time

### ISSUE THREAD

**Issue by sunnoy** [kubeedge/kubeedge#2214]
**What happened and what you expected to happen**:

1- node lost because network interrupt for long time ，about 10min
2- node network is ok 
3- pod runing in that node can recreated ！ 

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
1.18.3
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
1.4.0
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
1.4.0
```

</details>

**Comment by JiahuiZhao11** [comment]
kubeedge resolve this problem?
