### ISSUE TITLE
deploy cloudcore through containerization by nodePort，but  kubectl logs podname  function failure

### ISSUE THREAD

**Issue by lvfei103650** [kubeedge/kubeedge#2215]
**What happened**:
deploy cloudcore through containerization，but  kubectl logs podname function failure
**What you expected to happen**:
kubectl logs podname function success
**How to reproduce it (as minimally and precisely as possible)**:
1. kubectl create configmap cloudcore -n kubeedge --from-file=cloudcore.yaml=/etc/kubeedge/config/cloudcore.yaml
2. kubectl create configmap kubeconfig -n kubeedge --from-file=config=/root/.kube/config
3. kubectl create secret generic cloudcore -n kubeedge  --from-file=streamCA.crt=/etc/kubeedge/ca/streamCA.crt --from-file=stream.crt=/etc/kubeedge/certs/stream.crt --from-file=stream.key=/etc/kubeedge/certs/stream.key 
4. service，制作nodePort方式的service
`apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  ports:
  - port: 10000
    targetPort: 10000
    nodePort: 30000
    name: cloudhub1
  - port: 10002
    targetPort: 10002
    nodePort: 30002
    name: cloudhub2
  - port: 10003
    targetPort: 10003
    nodePort: 30003
    name: cloudhub3
  - port: 10004
    targetPort: 10004
    nodePort: 30004
    name: cloudhub4
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: NodePort`
5.  deployment,  部署
`apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
  name: cloudcore
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: cloudcore
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: cloudcore
    spec:
      nodeName: master
      containers:
      - name: cloudcore
        image: cloudcore
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: conf
          mountPath: /etc/kubeedge/config
        - name: minikube
          mountPath: /root/.minikube
        - name: kubeconfig
          mountPath: /root/.kube
        - name: certs
          mountPath: /etc/kubeedge
      restartPolicy: Always
      volumes:
      - name: minikube
        hostPath:
          path: /root/.minikube
      - name: conf
        configMap:
          name: cloudcore
      - name: kubeconfig
        configMap:
          name: kubeconfig
      - name: certs
        secret:
          secretName: cloudcore
          items:
          - key: streamCA.crt
            path: ca/streamCA.crt
          - key: stream.crt
            path: certs/stream.crt
          - key: stream.key
            path: certs/stream.key`
6. kubectl logs podname

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
# paste output here
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by daixiang0** [comment]
Please refer to this [doc](https://docs.kubeedge.io/en/latest/setup/keadm.html#enable-kubectl-logs-feature) :)

**Comment by yangchenliang** [comment]
> Please refer to this [doc](https://docs.kubeedge.io/en/latest/setup/keadm.html#enable-kubectl-logs-feature) :)
> I think you miss it.



> Please refer to this [doc](https://docs.kubeedge.io/en/latest/setup/keadm.html#enable-kubectl-logs-feature) :)
> I think you miss it.

1、cloudcore deployed in pod and expose it as hostnetwork type,  working fine.
2、if exposed cloudcore by nodePort service，kubectl logs failed when refer to that doc above. Because traffic can not be send to cloudcore deployed in  pod.
3、so when exposed cloudclore by nodePort service,  what iptables rule should be configrured？
     we try iptables rule  such  as below, unfortunately  kubectl logs failed 
     iptables -t nat -I OUTPUT  -p tcp --dport 10350   $host_ip:$nodeport_port

**Comment by daixiang0** [comment]
Try use node_ip replease with host_ip.

**Comment by yangchenliang** [comment]
it is not ok

**Comment by GsssC** [comment]
Are you sure that iptables are set at machine that has been deployed api-server

**Comment by yangchenliang** [comment]
yes, we deploy k8s with minikube in a single VM and set iptables on it
