### ISSUE TITLE
How do we actually install kubeedge into a cluster?

### ISSUE THREAD

**Issue by Geethree** [kubeedge/kubeedge#2221]
Greetings! 

So I've poked around a bit.. to me it seems that `keadm init` is meant to be ran on a node that will become apart of a k8s cluster of masters?

I attempted to install the manifests at https://github.com/kubeedge/kubeedge/tree/release-1.4/build/cloud but those resulted in not having CRDS.

Appling the crds in https://github.com/kubeedge/kubeedge/tree/release-1.4/build/crds/devices .. failed as they were not formatted correctly..

Using the CRDs from here https://docs.kubeedge.io/en/latest/troubleshooting.html#keadm-init-failed-to-download-release resulted in the device crd working, but not the device model.

Frankly, I'm super curious to try out kubeedge, but its proving difficult to figure out how to even get started? The getting started guide says to use `keadm init`  but.. AFAICT that doesn't install the cloud components into an existing cluster?

There are a few tickets floating around that express the same things over the last year or so.

Any help is _greatly appreciated._

**Comment by zzxgzgz** [comment]
What does the cloudcore's log say when you do `keadm init ...`?  Logs are available at `/var/log/kubeedge/cloudcore.log`
