### ISSUE TITLE
kubeedge plan to support other systems? for example raspberry pi OS

### ISSUE THREAD

**Issue by yushanjin** [kubeedge/kubeedge#2233]
**What happened and what you expected to happen**:
can't run keadm join on raspberry pi OS

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
1.18
```
</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
1.4
```
</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
1.4
```

</details>

keadm join:
root@raspberrypi:/etc/kubeedge# keadm join --cloudcore-ipport=xxxxx:10000 --kubeedge-version=1.4.0 --edgenode-name=raspi-edge-node --token=86b5fd84fd05b11683823ced600f0e6067a9a6e15fc799ba4b8a5ead3c8c9171.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDI1ODIwMzd9.lQN-lawrw06gT5aePeF_hfSOFE_hjx59MoWzye4T97I
This OS version is currently un-supported by keadm, debianpanic: This OS version is currently un-supported by keadm,

goroutine 1 [running]:
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/util.GetOSInterface(0x4000139c48, 0x4000217e60)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/util/common.go:190 +0x17c
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/util.(*MQTTInstTool).InstallTools(0x4000276fa0, 0x400029f170, 0x4000139c48)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/util/mqttinstaller.go:26 +0x28
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/edge.Execute(0x400029f170, 0x400029f1a0, 0x400021b500)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/edge/join.go:172 +0xb0
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/edge.NewEdgeJoin.func1(0x4000290f00, 0x400027c8c0, 0x0, 0x4, 0x0, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/edge/join.go:74 +0xb0
github.com/spf13/cobra.(*Command).execute(0x4000290f00, 0x400027c880, 0x4, 0x4, 0x4000290f00, 0x400027c880)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:826 +0x30c
github.com/spf13/cobra.(*Command).ExecuteC(0x4000290a00, 0x40000c4000, 0x10875a0, 0x40000c4008)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:914 +0x22c
github.com/spf13/cobra.(*Command).Execute(...)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:864
github.com/kubeedge/kubeedge/keadm/cmd/keadm/app.Run(0x4000054768, 0x448a4)
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/keadm.go:34 +0xdc
main.main()
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:26 +0x20
root@raspberrypi:/etc/kubeedge# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
root@raspberrypi:/etc/kubeedge# uname -a
Linux raspberrypi 5.4.42-v8+ #1319 SMP PREEMPT Wed May 20 14:18:56 BST 2020 aarch64 GNU/Linux

code limit:
![image](https://user-images.githubusercontent.com/12782056/95821460-871e6300-0d5c-11eb-90a9-c8ce0d6bc7b3.png)

**Comment by daixiang0** [comment]
Please share output with `. /etc/os-release && echo $ID`

**Comment by yushanjin** [comment]
> . /etc/os-release && echo $ID

root@raspberrypi:/etc/kubeedge# . /etc/os-release && echo $ID
debian
root@raspberrypi:/etc/kubeedge# . /etc/os-release
root@raspberrypi:/etc/kubeedge# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by yushanjin** [comment]
> Please share output with `. /etc/os-release && echo $ID`.
> 
> We support raspberry pi indeed.

yes
but the ID in not "raspbian"

the OS from: https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370
