### ISSUE TITLE
edge/pkg/devicetwin/dtmodule: import test coverage

### ISSUE THREAD

**Issue by daixiang0** [kubeedge/kubeedge#2240]
Add more tests to import test coverage. Details refer to #2110 .

/help

**Comment by daixiang0** [comment]
update

**Comment by charles-woshicai** [comment]
/assign

Is this issue still not solved? If not, I could have a try.

**Comment by daixiang0** [comment]
@charles-woshicai thanks, you can try it :)

**Comment by charles-woshicai** [comment]
I think this issue should be fixed, please confirm. @daixiang0

**Comment by daixiang0** [comment]
Please share new coverage result here.

**Comment by charles-woshicai** [comment]
> Please share new coverage result here.

➜  kubeedge git:(master) ✗ go test -coverprofile=coverprofile.cov ./edge/pkg/devicetwin/dtmodule 
ok      github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmodule       1.285s  coverage: 77.8% of statements
➜  kubeedge git:(master) ✗ go tool cover -func=coverprofile.cov                                                                            
github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmodule/dtmodule.go:18:       InitWorker      100.0%
github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmodule/dtmodule.go:64:       Start           50.0%
total:                                                                          (statements)    77.8%

Does not cover the `panic recover` statement fyi.

**Comment by charles-woshicai** [comment]
Is it enough?

**Comment by daixiang0** [comment]
90% is better, close for now.
