### ISSUE TITLE
edge/pkg/edgehub/common/http: improve test coverage

### ISSUE THREAD

**Issue by daixiang0** [kubeedge/kubeedge#2244]
Add more tests to import test coverage. Details refer to #2110 .

/help

**Comment by jmguzik** [comment]
This one was closed in https://github.com/kubeedge/kubeedge/pull/2570

**Comment by daixiang0** [comment]
@jmguzik please share UT coverage.

**Comment by jmguzik** [comment]
Ut coverage improved in edge/pkg/edgehyb/common/http/ (from ~30% to 97%)
Note: would be difficult to achieve 100% since it would require real HTTP interaction.

**Comment by daixiang0** [comment]
Above 90% is enough i think.
