### ISSUE TITLE
refactor bluetooth mapper

### ISSUE THREAD

**Issue by ttlv** [kubeedge/kubeedge#2249]
**What would you like to be added/modified**:
refactor bluetooth mapper
**Why is this needed**:
Beacuse of the new defination of device and devicemodel crd,the bluetooth mapper is broken so we need to refactor this bluetooth mapper make it to be supported by the new crd defination

**Comment by ttlv** [comment]
The modbus mapper is working in progress by sailorvii what's more there is a new proposal for mapper,I have fix the bluetooth mapper which is supported by new crd defination but not supported by the proposal,I want to know is there have a plan to restructure or somebody have worked in progress for this bluetooth mapper refactor.

**Comment by luogangyi** [comment]
maybe you can do it step by step, submit your current change first and refactor it later

**Comment by ttlv** [comment]
hey folks, new ble mapper is under testing,the repo url is https://github.com/ttlv/mappers-go/tree/ble and there will be a new pr soon. @fisherxu WDYT :)

**Comment by ttlv** [comment]
new pr is https://github.com/kubeedge/mappers-go/pull/13, welcome to review

**Comment by ttlv** [comment]
ble mapper had been merged,this issue can be closed
