### ISSUE TITLE
Need a wrapper for the current server io to support different protocol and encoding in future

### ISSUE THREAD

**Issue by qizha** [kubeedge/kubeedge#225]
**What would you like to be added*:
To provide a wrapper for the server io to support the future extension. Also, returning the transportation data size is needed for the flow control purpose.

**Why is this needed**:
The communication mechanism between cloud and edge is websocket with json encoding. However, this cloud  be change to other protocol like quic with protobuf.

**Comment by sids-b** [comment]
cc @lidiyag
