### ISSUE TITLE
The TLS config load uncorrectly When Deploy the CloudStream with Pod

### ISSUE THREAD

**Issue by Muzry** [kubeedge/kubeedge#2269]
**What happened**:

When I deploy the cloudcore with CloudStream and deploy it on Kubernetes cluster with Deployment, the error of the cloudcore pod report about  following:

```shell
W1020 11:33:55.018119       1 validation.go:153] TLSTunnelPrivateKeyFile does not exist in /etc/kubeedge/certs/server.key, will load from secret
W1020 11:33:55.018186       1 validation.go:156] TLSTunnelCertFile does not exist in /etc/kubeedge/certs/server.crt, will load from secret
W1020 11:33:55.018201       1 validation.go:159] TLSTunnelCAFile does not exist in /etc/kubeedge/ca/rootCA.crt, will load from secret
F1020 11:33:55.018290       1 server.go:55] [
  TLSStreamPrivateKeyFile: Invalid value: "/etc/kubeedge/certs/stream.key": TLSStreamPrivateKeyFile not exist
  TLSStreamCertFile: Invalid value: "/etc/kubeedge/certs/stream.crt": TLSStreamCertFile not exist
  TLSStreamCAFile: Invalid value: "/etc/kubeedge/ca/streamCA.crt": TLSStreamCAFile not exist
]
```

Then I read the code, I find the `validation.go` file will load TLS config like this:
```Go
			if errs := validation.ValidateCloudCoreConfiguration(config); len(errs) > 0 {
				klog.Fatal(util.SpliceErrors(errs.ToAggregate().Errors()))
			}
```

I also read the deployment.example file, I find the deployment.example file does not mount the secret config correctly.
https://github.com/kubeedge/kubeedge/blob/c80ffce0dc75b69e98391214a6460da6f7f2cfbf/build/cloud/ha/03-ha-deployment.yaml.example#L60

```yaml
          volumeMounts:
            - name: conf
              mountPath: /etc/kubeedge/config
          env:
            - name: CLOUDCORE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLOUDCORE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```

The log will confuse me. Because the logs show TLSTunnelPrivateKeyFile not exist and will load from secret.  I thought it will load the TLS config from the secret when the process can't found the file. But the process exit.

**What you expected to happen**:

The TLS config load correctly and the deployment.example set secret correctly. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
v1.4.0
```

</details>

**Comment by daixiang0** [comment]
The TLS files need created by hand and put them under right dir.

**Comment by Muzry** [comment]
@daixiang0 Thanks reply. Should I use `keadm init` to create TLS files? or I copy TLS files from the edge node? and I put the files to `/etc/kubeedge/` dir on the host node?

**Comment by daixiang0** [comment]
Now cloudstream in pod is still in devlop process, if you need it, please refer this [doc](https://docs.kubeedge.io/en/latest/setup/keadm.html#enable-kubectl-logs-feature).
