### ISSUE TITLE
How to build edgecore for Mac

### ISSUE THREAD

**Issue by xauthulei** [kubeedge/kubeedge#2272]
**What happened**:
make: *** [all] Error 1
**What you expected to happen**:
I want to add a mac node 
**How to reproduce it (as minimally and precisely as possible)**:
cd ${GOPATH}/src/kubeedge/kubeedge;make all WHAT=edgecore 
**Anything else we need to know?**:
go version 
go version go1.13.5 darwin/amd64

**Comment by kevin-wangzefeng** [comment]
We not yet support mac as edge node, some implementation rely on linux libs. For now you can only do cross build on mac for linux.

**Comment by xauthulei** [comment]
> We not yet support mac as edge node, some implementation rely on linux libs. For now you can only do cross build on mac for linux.

 @kevin-wangzefeng ,Thanks for your supporting,  Is there any plan to do this ? How about the windows ?

**Comment by daixiang0** [comment]
Is there any powerful reason to achieve it?

**Comment by xauthulei** [comment]
@daixiang0 , In my personal case, I want to use my laptop(Mac) instead of Raspberry Pi as a edge node  to learn the application scene of `kubeedge`. It is easy and low cost for a newer.   Thanks

**Comment by daixiang0** [comment]
I think for this case, it is more easy and almost free to use `hack/local-up-kubeedge.sh` to start a KubeEdge cluster.

**Comment by xauthulei** [comment]
@daixiang0 Thanks for your info,  It still need to build the the related binaries, such as the `edgecore`, right ?  Or it just build a all in one cluster in the VMs created the its driver `hyperkit` in MAC ?

**Comment by daixiang0** [comment]
I Have no Mac machine to test it, while Golang is cross-platform.

**Comment by xauthulei** [comment]
@daixiang0 , Well, I can try to build to it, Could I know what's the steps and specified Envs  to build the `edgecore` on your current support os.
