### ISSUE TITLE
How to monitor kubeedge using prometheus?

### ISSUE THREAD

**Issue by xuxiaoguang666** [kubeedge/kubeedge#2274]
**What happened and what you expected to happen**:
  On k8s the prometheus operator can monitor POD(such as cpu、memory ) use kubelet service and kubedge edgehost dosen't have kubelet service,How to monitor edge host and container on the edge host using prometheus? Thanks.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```

</details>

**Comment by vincent-pli** [comment]
I have similar question, Prometheus need pull metrics from `pod`, could master touch target pod on edge node directly? or need the help from `cloud hub` or `edge hub`? thanks @daixiang0

**Comment by koulq** [comment]
How come no one answered this question? metrics interfaces are provided, but no documentation is provided

**Comment by daixiang0** [comment]
@koulq @xuxiaoguang666 i think you miss [it](https://docs.kubeedge.io/en/latest/setup/keadm.html#support-metrics-server-in-cloud).
