### ISSUE TITLE
Why does the network configuration report an error when the master node of Kubeedge is configured and the slave node is added

### ISSUE THREAD

**Issue by wwwlookformetop** [kubeedge/kubeedge#2281]
![image](https://user-images.githubusercontent.com/23631902/97382387-40a53880-1906-11eb-88fd-202261691d7c.png)

**Comment by wwwlookformetop** [comment]
![image](https://user-images.githubusercontent.com/23631902/97382515-8235e380-1906-11eb-9ca3-6b864d538baf.png)

**Comment by daixiang0** [comment]
Sorry that now we do not support CNI at edge node.

**Comment by wwwlookformetop** [comment]
> Sorry that now we do not support CNI at edge node.

How does the NETWORK IP camera link to the edge nodes, only through MQTT protocol

**Comment by JINGJIEworld** [comment]
> 抱歉，现在我们在边缘节点不支持CNI。
Is there any corresponding solution for the master node to access the slave node through IP?
