### ISSUE TITLE
A device-related problem cause too many api-server request

### ISSUE THREAD

**Issue by wuqihui0317** [kubeedge/kubeedge#2286]
**What happened**:
I ran a bluetooth mapper. At the begining, there is no problem. After an hours or so, api-server's cpu became more than 300%. And kubernetes broke down because of too many api-server request. And it happens many times.

So I attempt to find the reason.

![image](https://user-images.githubusercontent.com/53106233/97656652-dece0580-1aa2-11eb-8d57-a27bca6e431f.png)
It's cloudcore's log. The function(upstream.updateDeviceStatus) is trying to patch device.status endlessly, but 3s is the report time I set in mapper. 

`upstream.go 67`
`       for i := 0; i < int(config.Config.Buffer.UpdateDeviceStatus); i++ {`
`		go uc.updateDeviceStatus()`
`	}`
![image](https://user-images.githubusercontent.com/53106233/97657090-f659be00-1aa3-11eb-8cfb-aaa3fa560063.png)
The limit of deviceStatusChan is 1024 also.

`func (uc *UpstreamController) updateDeviceStatus() {`
`	for {`
`		select {`
`		case <-beehiveContext.Done():`
`			klog.Info("Stop updateDeviceStatus")`
`			return`
`		case msg := <-uc.deviceStatusChan:`
`               ...`

the log of api-server:
![image](https://user-images.githubusercontent.com/53106233/97657298-7bdd6e00-1aa4-11eb-858c-dda81d0a65f6.png)

Above all, I think the design of device to modify device.status make too much interaction of apiserver.(when the length of deviceStatusChan arriving the limit of api-server(It might be caused by edge's network or others), the k8s broke down. ）

But cloudcore is working still, so it's easy to reach 1024. So when k8s restart, apiserver get too many requests again, and k8s broken down again, cloudcore's msg channal is increasing again... 

In this case, etcd becomes a database like mysql, dealing too many data modifactions.
![image](https://user-images.githubusercontent.com/53106233/97667510-04670900-1abb-11eb-95e4-731e0fe6de75.png)

**Comment by ttlv** [comment]
update device frequently in etcd I don't think it's a good idea.apiserver may recieve too many update requests from cloudcore and then apiserver will occupy most of memory and cpu resource.

**Comment by kkBill** [comment]
@ttlv
