### ISSUE TITLE
2020/11/04 04:29:46 Failed to patch device status &{{[{status {ON map[timestamp:1604 type:string]} {0 map[timestamp:1604 type:string]}}]}} of device counter in namespace default   error:Patch "http://127.0.0.1:8080/apis/devices.kubeedge.io/v1alpha1/namespaces/default/devices/counter": dial tcp 127.0.0.1:8080: connect: connection refused

### ISSUE THREAD

**Issue by dogfei** [kubeedge/kubeedge#2297]
**What happened and what you expected to happen**:
2020/11/04 04:29:46 Failed to patch device status &{{[{status {ON map[timestamp:1604 type:string]} {0 map[timestamp:1604 type:string]}}]}} of device counter in namespace default 
 error:Patch "http://127.0.0.1:8080/apis/devices.kubeedge.io/v1alpha1/namespaces/default/devices/counter": dial tcp 127.0.0.1:8080: connect: connection refused
**How to reproduce it (as minimally and precisely as possible)**:
# kubectl logs -f kubeedge-counter-app-6984dcb4dd-zp42q
2020/11/04 04:27:52 Get kubeConfig successfully
2020/11/04 04:27:52 Get crdClient successfully
2020/11/04 04:27:52.497 [I]  http server Running on http://:8089
2020/11/04 04:28:01 ControlTrack: ON
2020/11/04 04:28:01 Failed to patch device status &{{[{status {ON map[timestamp:1604 type:string]} {0 map[timestamp:1604 type:string]}}]}} of device counter in namespace default 
 error:Patch "http://127.0.0.1:8080/apis/devices.kubeedge.io/v1alpha1/namespaces/default/devices/counter": dial tcp 127.0.0.1:8080: connect: connection refused
2020/11/04 04:28:02 ControlTrack: ON
2020/11/04 04:28:02 Failed to patch device status &{{[{status {ON map[timestamp:1604 type:string]} {0 map[timestamp:1604 type:string]}}]}} of device counter in namespace default 
 error:Patch "http://127.0.0.1:8080/apis/devices.kubeedge.io/v1alpha1/namespaces/default/devices/counter": dial tcp 127.0.0.1:8080: connect: connection refused
2020/11/04 04:28:02 ControlTrack: ON

**Anything else we need to know?**:
# kubectl get pod -o wide
NAME                                    READY   STATUS    RESTARTS   AGE     IP            NODE           NOMINATED NODE   READINESS GATES
kubeedge-counter-app-6984dcb4dd-zp42q   1/1     Running   0          4m50s   10.20.3.112   k8s-master01   <none>           <none>
kubeedge-pi-counter-784d57c5d4-6sgvb    1/1     Running   0          4m50s   <none>        ke-edge1       <none>           <none>

# kubectl logs -f kubeedge-counter-app-6984dcb4dd-zp42q
2020/11/04 04:27:52 Get kubeConfig successfully
2020/11/04 04:27:52 Get crdClient successfully
2020/11/04 04:27:52.497 [I]  http server Running on http://:8089
2020/11/04 04:28:01 ControlTrack: ON
2020/11/04 04:28:01 Failed to patch device status &{{[{status {ON map[timestamp:1604 type:string]} {0 map[timestamp:1604 type:string]}}]}} of device counter in namespace default 
 error:Patch "http://127.0.0.1:8080/apis/devices.kubeedge.io/v1alpha1/namespaces/default/devices/counter": dial tcp 127.0.0.1:8080: connect: connection refused
2020/11/04 04:28:02 ControlTrack: ON

**Environment**:
<details><summary>Kubernets Version</summary>

```console
k8s:1.18.3
kubeedge:1.4
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
KubeEdge v1.4.0
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
2020-11-04 20:32:43.328834 I | INFO: Install client plugin, protocol: rest
2020-11-04 20:32:43.328971 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.4.0-beta.0.242+8280082f9da41b

```

</details>

**Comment by daixiang0** [comment]
Please try the latest version of it, it works at my env, if still not work, please reopen it.

/close
