### ISSUE TITLE
CloudCore shutdown

### ISSUE THREAD

**Issue by sakura41** [kubeedge/kubeedge#2299]
**What happened**:
CloudCore shutdown

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
start cloudcore by nohup cloudcore > log.txt &
but after hours, it shutdown without useful exception...

log message is below:

<code>
I1104 20:54:03.108864   27761 messagehandler.go:509] saveSuccessPoint successfully for message: node/edge-h0243m1/kube-system/endpoints/kube-controller-manager
E1104 20:54:03.152243   27761 messagehandler.go:448] write error, connection for node edge-h0315m1 will be closed, affected event id: 14df2724-519d-4749-8262-6ea09b448026, parent_id: , group: resource, source: edgecontroller, resource: default/podlist/kubernetes, operation: update, reason tls: use of closed connection
E1104 20:54:03.152275   27761 messagehandler.go:336] Node edge-h0315m1 disconnected and stopped sending messages
W1104 20:54:03.526659   27761 messagehandler.go:163] Timeout to receive heart beat from edge node edge-h0246m1 for project e632aba927ea4ac2b575ec1603d56f10
I1104 20:54:03.526716   27761 messagehandler.go:111] Keepalive message received from node: edge-h0246m1
fatal error: concurrent map read and map write

goroutine 66246 [running]:
runtime.throw(0x16e0988, 0x21)
	/root/.gvm/gos/go1.13.4/src/runtime/panic.go:774 +0x72 fp=0xc00cbc5b38 sp=0xc00cbc5b08 pc=0x42f962
runtime.mapaccess1_faststr(0x14cfc00, 0xc00110ecf0, 0xc00674b650, 0xc, 0xc00cbc5c98)
	/root/.gvm/gos/go1.13.4/src/runtime/map_faststr.go:21 +0x44f fp=0xc00cbc5ba8 sp=0xc00cbc5b38 pc=0x41433f
github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler.(*MessageHandle).HandleServer(0xc00016e0e0, 0xc00b7ee500, 0x19036c0, 0xc00b7ee4c0)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler/messagehandler.go:112 +0x4f1 fp=0xc00cbc5d78 sp=0xc00cbc5ba8 pc=0x130fc61
github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler.(*MessageHandle).HandleServer-fm(0xc00b7ee500, 0x19036c0, 0xc00b7ee4c0)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler/messagehandler.go:101 +0x48 fp=0xc00cbc5da8 sp=0xc00cbc5d78 pc=0x13148f8
github.com/kubeedge/viaduct/pkg/mux.(*MessageMux).dispatch(0xc0001fa940, 0xc00bafc3a0, 0x19036c0, 0xc00b7ee4c0, 0x1481f01, 0xc00bafc3a0)
	/root/codes/src/github.com/kubeedge/kubeedge/staging/src/github.com/kubeedge/viaduct/pkg/mux/mux.go:86 +0x15c fp=0xc00cbc5e28 sp=0xc00cbc5da8 pc=0x1306fac
github.com/kubeedge/viaduct/pkg/mux.(*MessageMux).ServeConn(0xc0001fa940, 0xc00bafc3a0, 0x19036c0, 0xc00b7ee4c0)
	/root/codes/src/github.com/kubeedge/kubeedge/staging/src/github.com/kubeedge/viaduct/pkg/mux/mux.go:108 +0x66 fp=0xc00cbc5e68 sp=0xc00cbc5e28 pc=0x1307106
github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).handleMessage(0xc00bf62240)
	/root/codes/src/github.com/kubeedge/kubeedge/staging/src/github.com/kubeedge/viaduct/pkg/conn/ws.go:149 +0x236 fp=0xc00cbc5fd8 sp=0xc00cbc5e68 pc=0x130da36
runtime.goexit()
	/root/.gvm/gos/go1.13.4/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00cbc5fe0 sp=0xc00cbc5fd8 pc=0x45cae1
created by github.com/kubeedge/viaduct/pkg/conn.(*WSConnection).ServeConn
	/root/codes/src/github.com/kubeedge/kubeedge/staging/src/github.com/kubeedge/viaduct/pkg/conn/ws.go:51 +0x125

goroutine 1 [chan receive, 83 minutes]:
github.com/kubeedge/beehive/pkg/core.GracefulShutdown()
	/root/codes/src/github.com/kubeedge/kubeedge/staging/src/github.com/kubeedge/beehive/pkg/core/core.go:34 +0x170
github.com/kubeedge/beehive/pkg/core.Run()
	/root/codes/src/github.com/kubeedge/kubeedge/staging/src/github.com/kubeedge/beehive/pkg/core/core.go:51 +0x25
github.com/kubeedge/kubeedge/cloud/cmd/cloudcore/app.NewCloudCoreCommand.func1(0xc0001fec80, 0x244ca10, 0x0, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/cmd/cloudcore/app/server.go:72 +0x2bf
github.com/spf13/cobra.(*Command).execute(0xc0001fec80, 0xc0000be190, 0x0, 0x0, 0xc0001fec80, 0xc0000be190)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001fec80, 0x43d627, 0x2397080, 0xc000000180)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/cmd/cloudcore/cloudcore.go:16 +0x68

goroutine 19 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x242f240)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1018 +0x8b
created by k8s.io/klog.init.0
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:404 +0x6c

goroutine 20 [syscall, 83 minutes]:
os/signal.signal_recv(0x0)
	/root/.gvm/gos/go1.13.4/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/root/.gvm/gos/go1.13.4/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/root/.gvm/gos/go1.13.4/src/os/signal/signal_unix.go:29 +0x41

goroutine 21 [select]:
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1771740, 0x12a05f200, 0x0, 0x1, 0xc0000ae0c0)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:164 +0x181
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88
k8s.io/apimachinery/pkg/util/wait.Forever(0x1771740, 0x12a05f200)
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:79 +0x4f
created by k8s.io/component-base/logs.InitLogs
	/root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/component-base@v0.17.1/logs/logs.go:58 +0x8a
</code>
[cloudcore.log](https://github.com/kubeedge/kubeedge/files/5491866/cloudcore.log)

**Comment by GsssC** [comment]
what is your version of cloudcore?
