### ISSUE TITLE
The problem of not being able to get Metrics -service

### ISSUE THREAD

**Issue by lgy1027** [kubeedge/kubeedge#2300]
I deployed the metrics-service according to the following connection, but I could not get the indicator information of the edge node. When I used Kubectl Top Node, I got an error error: Metrics not available yet 
https://github.com/kubeedge/kubeedge/blob/master/docs/setup/keadm.md

![image](https://user-images.githubusercontent.com/38779388/98201023-c873ee00-1f69-11eb-9ca9-49386ee823af.png)

**Comment by daixiang0** [comment]
Please share more details then we can help you as possible as we can.

**Comment by lgy1027** [comment]
> Please share more details then we can help you as possible as we can.

That's done. Thank you
