### ISSUE TITLE
microservices example

### ISSUE THREAD

**Issue by tkzkno** [kubeedge/kubeedge#2301]
Are there microservice examples on k8s using kubeedge ??

**Comment by fisherxu** [comment]
> Are there microservice examples on k8s using kubeedge ??

Can you please provide more details, what microservices do you want to run on?

**Comment by tkzkno** [comment]
Thanks comments.
I want to know how kubeedge works.

So I want to run on simple microservices.
Anything is ok.

**Comment by daixiang0** [comment]
/question

KubeEdge is designed mainly for edge computing, you can check kubeedge/example to get a demo.

If you want to know how KubeEdge works, please totally read docs, they would help you :)

**Comment by tkzkno** [comment]
I use intel NUC as edge node.  ( not raspi but intel NUC. )
Can I ran kubeedge/example in this environment ??
