### ISSUE TITLE
how to deploy edgecore with offline

### ISSUE THREAD

**Issue by myxland** [kubeedge/kubeedge#2307]
i've downloaded edgesite-v1.4.0-linux-amd64.tar.gz, kubeedge-v1.3.1-linux-amd64.tar.gz, edgecore.service to /etc/kubeedge
when use keadm join, it need to wget edgecore.service again. but the node is offline.
and what should i do to avoid download edgecore.service?

**Comment by myxland** [comment]
`	/*
		When installing edgecore, if the version is >= 1.1,
		download the edgecore.service file from the KubeEdge/build/tools/ and place it in /etc/kubeedge/ acc.
	*/
	if options.ComponentType == types.EdgeCore {
		strippedVersion := fmt.Sprintf("%d.%d", version.Major, version.Minor)

		//	No need to download if the version is less than 1.1 (or 1.1.0)
		if version.GE(semver.MustParse("1.1.0")) {
			try := 0

			edgecoreServiceFileName := "edgecore.service"

			if version.EQ(semver.MustParse("1.1.0")) {
				edgecoreServiceFileName = "edge.service"
			}`
貌似没有判断逻辑去判断是否下载了【edgecore.service】

**Comment by GsssC** [comment]
/close 

open if any other question : )
