### ISSUE TITLE
how to deploy istio with kubeedge

### ISSUE THREAD

**Issue by Yellow-L** [kubeedge/kubeedge#2314]
**What happened and what you expected to happen**:
I want to enable istio's functionality with kubeedge for application running on edge nodes. Is there any proposal or feedback on how to do that?

**Comment by zzxgzgz** [comment]
I've been trying to deploy Istio with KubeEdge, but so far it is unsuccessful. 

I somehow got Istiod pod running on edge nodes, but it is not able to talk to the cloud:
![imgpsh_mobile_save](https://user-images.githubusercontent.com/32083634/98841729-626de780-23fd-11eb-9b52-bba478cbb89a.jpg)

Can you share with me what are your current situation? Such as what part of Istio is running for you, and what part is not? 

Thank you.

**Comment by daixiang0** [comment]
Istio needs CNI and proxy which are in design and development, for now, we do not support it on the edge side.
