### ISSUE TITLE
When the configmap changes, files mounted to the pod are not updated

### ISSUE THREAD

**Issue by koulq** [kubeedge/kubeedge#2315]
**What happened**:
hello，When the configmap changes, files mounted to the pod are not updated
After the change, the configmap are as follows:
![image](https://user-images.githubusercontent.com/18571340/98795876-b4d2f680-2445-11eb-8cfc-264282e338e5.png)
deployment as follows：
![image](https://user-images.githubusercontent.com/18571340/98796012-ddf38700-2445-11eb-977c-8df55c09a233.png)
![image](https://user-images.githubusercontent.com/18571340/98796052-ea77df80-2445-11eb-8cbc-b1fa15b46d49.png)
The files generated inside the container are as follows:
![image](https://user-images.githubusercontent.com/18571340/98796124-01b6cd00-2446-11eb-92c0-2e72fb5cfa50.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
Kubernetes v1.16.2
$ kubectl version
Kubernetes v1.16.2
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
1.3.1
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
1.3.1
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
Ubuntu 18.04.6 LTS \n \l
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by koulq** [comment]
configmap最新的resourceVersion如下：
![image](https://user-images.githubusercontent.com/18571340/98799853-9f140000-244a-11eb-9843-b6b8fc5f0abf.png)
edge logs obtained are as follows:
![image](https://user-images.githubusercontent.com/18571340/98800013-cf5b9e80-244a-11eb-9c53-2ec2fd1e6526.png)

**Comment by daixiang0** [comment]
The changes for configmap is not auto-updated, it is the same behavior in Kubernetes.

**Comment by koulq** [comment]
@daixiang0 
hello，I have restarted pod, and I float pod to other nodes is no problem, our kubernets cluster is normal.

**Comment by koulq** [comment]
@daixiang0
Do kubeedge have a special configuration?

**Comment by daixiang0** [comment]
Oh, seems you miss it in the issue description, please add it.

Please try the latest version of KubeEdge and if reproduce, i will check it, thanks.

**Comment by GsssC** [comment]
may because #2119
plz wait release 1.5 these week

**Comment by koulq** [comment]
@GsssC @daixiang0 thanks , And indeed, I re-build the mirror deployment based on master, and there's no problem

**Comment by GsssC** [comment]
/close
open if any question :)
