### ISSUE TITLE
Zigbee mapper required to provide Zigbee protocol support for devices to connect to KubeEdge. 

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#232]
**What would you like to be added**:
A zigbee mapper (an application that can be used to connect and and control zigbee devices) is required to connect zigbee devices to the KubeEdge platform.

**Why is this needed**:
Many IoT devices communicate using Zigbee protocol. KubeEdge needs to provide users a away to connect their zigbee devices to the KubeEdge platform.

**Comment by mryalamanchi** [comment]
Hey @sids-b I think what you are looking at is a Zigbee Coordinator and not a mapper. A Zigbee Coordinator (C) will be able to create a PAN and allow Router (R) and End Devices (E) to connect the Coordinator. And if that's what you are looking at then how do you plan to provide access to the coordinator?

**Comment by sids-b** [comment]
@mryalamanchi , I guess we taking about the same functionality. Only the naming convention maybe different. 
Please refer to https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/mapper-design.md :)

**Comment by mryalamanchi** [comment]
Thanks for the reference @sids-b. Mapper is the right naming convention as it constitutes multiple components of which the Coordinator (Driver) is a part. So, have you guys already begun? I would like to contribute.

**Comment by sids-b** [comment]
Sure @mryalamanchi . We would love to collaborate and work. Currently we are working on the device-management from cloud design using Kubernetes CRD's. Please see #181  . After finalization of this design, we may need to modify some design of mapper post which we can work together for zigbee and other protocol support. We currently have bluetooth mapper PR in review which is also on hold till device CRD design finalization. Please see #230 . Mappers should intake device definition from CRD's. We currently plan to achieve it using config-maps. Please feel free to post your thoughts on the PR's and also to ping us on slack :)

**Comment by mryalamanchi** [comment]
@sids-b thanks for the quick update. It will be helpful to proceed further. Sure, I have some fair understanding about the protocols you are planning to integrate. I will keep a check via the Slack channels and keep myself updated. Thanks again bro :)

**Comment by rohitsardesai83** [comment]
@mryalamanchi , the device CRD feature is now available . Please feel free to try out and let us know your feedback.

**Comment by rohitsardesai83** [comment]
@mryalamanchi , did you get a chance to look at the device crd feature ?

**Comment by mryalamanchi** [comment]
@rohitsardesai83 my apologies, I have been busy for a while with my project. 
Yes, I did manage to skim through the CRD. But haven't really deep dived into the docs. Let me back to you shortly. Thanks.
