### ISSUE TITLE
Kubectl top command can not get metrics with KubeEdge 1.5.0 dynamic metrics port

### ISSUE THREAD

**Issue by Ma-Dan** [kubeedge/kubeedge#2342]
**What happened**:
kubectl top node, will trigger metrics server to read metrics from edge nodes 10250 port, on 1.5.0, due to this commit (https://github.com/kubeedge/kubeedge/commit/cdeccbef2523e6c71c0ee681871d6042390ff75c#diff-2c4a45b72ef2be00e9c3640e8402236926cba2a6593d7608eca38248f424416f), request message was send to edge node with 10250 port, so edge nodes tried to read 10250 port on their local network, which is not served by edgecore, edgecore still serve metrics on 10350, so this connection will fail.

**What you expected to happen**:
kubectl top node read metrics correctly, or provide parameter setting guide for edgecore dynamic metrics port.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl top nodes

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
v1.17.9
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
KubeEdge v1.5.0
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
KubeEdge v1.5.0
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by daixiang0** [comment]
Have you try with [guide](https://docs.kubeedge.io/en/latest/setup/keadm.html#support-metrics-server-in-cloud)?

/kind-remove bug
/help

**Comment by Ma-Dan** [comment]
Our metrics-server is v0.3.7, we will try upgrading it to v0.4.0 support kubelet port automatic identification.

**Comment by Ma-Dan** [comment]
Metrics-server v0.4.0 works well, close issue.
