### ISSUE TITLE
Documentation about missing and upcoming features

### ISSUE THREAD

**Issue by siredmar** [kubeedge/kubeedge#2344]
@daixiang0 I see several issues about the missing CNI. You answered all of them that it is currently under development. 

Proposal: the kubeedge project could provide either a roadmap (there is a not maintained one in this repo) or share a read-only version of your taskboard. A obvious link in the main Readme would allow users see what kubeedge are currently supported/not supported and what's in the pipeline.

**Comment by daixiang0** [comment]
The roadmap will update and you can see it.
