### ISSUE TITLE
empty log output when use release v1.5.0

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#2346]
**What happened**:
![image](https://user-images.githubusercontent.com/29768082/99637251-85dd0600-2a7f-11eb-9c9d-39b4bf1a41a6.png)
start cloudcore-v1.5.0, miss most basic logs.
**What you expected to happen**:
log well.

**Anything else we need to know?**:
I guess it is because we upgrade k8s to v.1.19.0, and it relay on k8s.io/klog/v2, but we still use k8s.io/klog to log as below:
![image](https://user-images.githubusercontent.com/29768082/99637410-c5a3ed80-2a7f-11eb-9dae-a48c060d5f63.png)

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
v1.5.0
$ kubectl version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by GsssC** [comment]
/cc @kevin-wangzefeng @fisherxu @daixiang0 
fatal bug, PTAL

**Comment by fisherxu** [comment]
Looks like others also meet this issue, would you like to fix it? @GsssC

**Comment by GsssC** [comment]
> Looks like others also meet this issue, would you like to fix it? @GsssC

Well : )
how about uprade all klog/v1 to v2?

**Comment by fisherxu** [comment]
> > Looks like others also meet this issue, would you like to fix it? @GsssC
> 
> Well : )
> how about uprade all klog/v1 to v2?

Well, let's follow the k8s upstream.
