### ISSUE TITLE
why i get "connection refused"

### ISSUE THREAD

**Issue by leeruibin** [kubeedge/kubeedge#235]
**Which jobs are failing**:
I am trying the KubeEdge demo, and succeed in making the edgecontroller file. I met the bug submitted in the issue #224 and fix that problem, however i can not finish the running, it report that:

E0314 13:21:01.282288    8997 reflector.go:205] github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/controller/manager/configmap.go:29: Failed to list *v1.ConfigMap: Get http://localhost:8080/api/v1/configmaps?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
E0314 13:21:01.282301    8997 reflector.go:205] github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/controller/manager/secret.go:29: Failed to list *v1.Secret: Get http://localhost:8080/api/v1/secrets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
E0314 13:21:01.286108    8997 reflector.go:205] github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/controller/manager/pod.go:93: Failed to list *v1.Pod: Get http://localhost:8080/api/v1/pods?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
E0314 13:21:01.287351    8997 reflector.go:205] github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/controller/manager/pod.go:93: Failed to list *v1.Pod: Get http://localhost:8080/api/v1/pods?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
E0314 13:21:01.287351    8997 reflector.go:205] github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/controller/manager/secret.go:29: Failed to list *v1.Secret: Get http://localhost:8080/api/v1/secrets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
E0314 13:21:01.287493    8997 reflector.go:205] github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/controller/manager/configmap.go:29: Failed to list *v1.ConfigMap: Get http://localhost:8080/api/v1/configmaps?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
^C2019-03-14 13:21:01.290 +08:00 WARN controller/controller.go:49 new downstream controller failed with error: Get http://localhost:8080/api/v1/pods: dial tcp 127.0.0.1:8080: connect: connection refused

**Which test(s) are failing**:

**Since when has it been failing**:

**Reason for failure**:

**Anything else we need to know**:
i test the project in the Raspberry Pi 3B platfor, 
the system version is "Raspbian GNU/Linux 9 \n \l", 
the architecture is "Linux han 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux", go version "go version go1.10 linux/arm", 
docker version "Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:30:52 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:26:37 2018
  OS/Arch:          linux/arm
  Experimental:     false"
i run the follow command to init the kubernete cluster "kubeadm init --kubernetes-version=v1.12.0 --feature-gates CoreDNS=false"
the running containers are as follows 
![1552543740](https://user-images.githubusercontent.com/26408630/54335164-0caece00-4663-11e9-8a88-1b94f365d34d.jpg)

**Comment by m1093782566** [comment]
cc @sids-b @edisonxiang

**Comment by sids-b** [comment]
Hi @leeruibin , Did you follow this step as well ? 
```
vi /etc/kubernetes/manifests/kube-apiserver.yaml
# Add the following flags in spec: containers: -command section
- --insecure-port=8080
- --insecure-bind-address=0.0.0.0
```
Looks like you have not opened an insecure port on apiserver.
Another way to achieve this is vial kubectl
```
kubectl proxy --port=8080 &
```

**Comment by m1093782566** [comment]
@sids-b 

Do you mean users will need to update kube-apiserver manifest and then restart kube-apiserver?


> Looks like an insecure port(8080) is not exposed by apiserver.
>Another way to achieve this is vial kubectl

> kubectl proxy --port=8080 &

If possible, I would like add this guide to README.

**Comment by sids-b** [comment]
@m1093782566 The step to update the manifest is already present in the README. As soon as there is change in manifest, apiserver will automatically restart.

**Comment by sids-b** [comment]
Also @leeruibin , if your kubernetes master is not running on the same machine as edgecontroller then IP address has to changed in conf/controller.yaml .  Change localhost to IP of the machine where your master is running 
```
controller:
  kube:
    master: http://localhost:8080
```
Please update us if you are facing any other issues :)

**Comment by m1093782566** [comment]
@sids-b 

I mean provide another way to let kube-apiserver listen on 8080 :)

```
Another way to achieve this is vial kubectl
kubectl proxy --port=8080 &
```

If possible, I would like to add this guide to README.

**Comment by sids-b** [comment]
> @sids-b
> 
> I mean provide another way to let kube-apiserver listen on 8080 :)
> 
> ```
> Another way to achieve this is vial kubectl
> kubectl proxy --port=8080 &
> ```
> If possible, I would like to add this guide to README.

Sure @m1093782566

**Comment by sids-b** [comment]
@leeruibin , can we go ahead and close this issue ??

**Comment by m1093782566** [comment]
@leeruibin 

If 

```
Another way to achieve this is vial kubectl
kubectl proxy --port=8080 &
```

works for you, would you please send a PR for this?

**Comment by leeruibin** [comment]
@sids-b i am so sorry that i forget about this issue, i will try it right away. Thanks for your advice..

**Comment by leeruibin** [comment]
@m1093782566 that method does work. I have tried both method and have solved this problem. It's true that i forget to follow the step, thanks i will go ahead and close this. @sids-b

**Comment by m1093782566** [comment]
Thanks @leeruibin for feedback.

@sids-b It's time we support accessing kube-apiserver via https?

**Comment by nkwangleiGIT** [comment]
we can help on kube-apiserver https support if needed

**Comment by sids-b** [comment]
@m1093782566 , @nkwangleiGIT We already support https connection to apiserver. I will post an example soon :) 

Thanks @leeruibin , share your experience of kubeedge with us on Slack :) Also looking forward to see your contributions to KubeEdge :)
