### ISSUE TITLE
Update tools in /hack

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#2350]
**What would you like to be added/modified**:
update tool in /hack such as `update-vendor-license.sh` to the latest version.
**Why is this needed**:

We have already upgraded k8s dep to v1.19.3, but some script logic are not synchronized with the k8s dep. It cause ci fail sometimes.
e.g.
pr #2349

**Comment by daixiang0** [comment]
In fact, we use v1.19.3
