### ISSUE TITLE
script option crash the cloudcore installation

### ISSUE THREAD

**Issue by relaxtheo** [kubeedge/kubeedge#2356]
**What happened**:
To install cloudcore in a script file, the "keadm init ...." command failed when the script has command-line options, the reported problem like:
 - . chmod: cannot access '/usr/local/bin/cloudcore': No such file or directory
      Error: failed to run 'sh -c chmod +x /usr/local/bin/cloudcore' because of error : exit status 1

 -. Error: CloudCore is already running on this node, please run reset to clean up first 

Without the option, installation is fine.

You can just add a "keadm init ..." command to a script a.sh, calling "a.sh a" will crash the installation, calling "a.sh" will complete the installation. No need to really use the option in the script

**What you expected to happen**:
Cloudcore should be installed successfully, even the script has an option. The option is used by the script, and this option should not impact the keadm init command.

**How to reproduce it (as minimally and precisely as possible)**:
Add a good keadm init command to a script file
Call the script file with any option, just like a, abc. xx, etc

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>
keadm version 1.5.0

```console
$ kubelet --version
# paste output here
$ kubectl version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by daixiang0** [comment]
Please share script to help reproduce it.

**Comment by relaxtheo** [comment]
Attach is zipped script file, you need to modify thhe IP address.

I tested it on AWS EC2 instance us-east2 region. A kubernetes master has been installed on the server.

If you call the script with an option line "ktest.sh abcd", installation will fail; if you just call "ktest.sh", installation will succeed.

[ktest.sh.zip](https://github.com/kubeedge/kubeedge/files/5612270/ktest.sh.zip)

**Comment by daixiang0** [comment]
I cannot reproduce it with `ktest.sh`, which bash version do you use？ Does AWS shell has some custom config?
