### ISSUE TITLE
I need service-bus user guide and examples

### ISSUE THREAD

**Issue by gislzhang** [kubeedge/kubeedge#2361]
**What would you like to be added/modified:**
I want a guide to use servicebus, one example is better. I can`t find guide for servicebus or example in official documents. thank you

**Why is this needed:**
one application is running on cloud, and it need to communicate with application running on edge via HTTP.

**Comment by daixiang0** [comment]
It is still under development, we will post user guide when it comes.

**Comment by daixiang0** [comment]
Duplicated with #2284 

 /close
