### ISSUE TITLE
Pod has errors, when running the modbus_mapper

### ISSUE THREAD

**Issue by mxtsuper** [kubeedge/kubeedge#2368]
**What happened and what you expected to happen**:

1. Create the deployment in the modbus_mapper.
2.  The modbus-device-mapper has an error status.
3. Check the pod logs, there are some TypeErrors,
The logs:
CONNECTOR_DPL_NAME=dpl/deviceProfile.json
CONNECTOR_MQTT_IP=127.0.0.1
CONNECTOR_MQTT_PORT=1883
[2020-11-25T08:47:29.128] [INFO] appenders - start to watch dpl config
[2020-11-25T08:47:29.139] [INFO] appenders - start to check devicetwin state
/opt/src/watchfile.js:103
    let foundVisitor = dplConfigs.propertyVisitors.findIndex((element)=>{
                                                   ^

TypeError: Cannot read property 'findIndex' of undefined
    at buildVisitorMaps (/opt/src/watchfile.js:103:52)
    at processData (/opt/src/watchfile.js:73:13)
    at /opt/src/watchfile.js:45:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

I except the modbus pod is working.

How to deal with it?

Thanks

**How to reproduce it (as minimally and precisely as possible)**:
Follows the link https://kubeedge.io/en/docs/components/mappers/modbus/.

But I did not link a real modbus device, did not create the modbus device.
Is it caused by lacking of a real modbus device ?

The edge node can not connect to the Internet.
Is it related to the pod issue ?

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
# paste output here
```
1.17.8
</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```
1.4
</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```
1.4
</details>

**Comment by mxtsuper** [comment]
Create the devicemodel, device with  modbustcp-device-instance.yaml and modbus-device-model.yaml. 
Replace the slaveIP to the edge node IP. 
Run a modbus simulator (Modbus Slave)
It outputs the same error messages.

**Comment by mxtsuper** [comment]
I will  use the modbus-go for kubeedge 1.4.0

**Comment by karthikmadupu** [comment]
Hey @mxtsuper ,
Am trying the same using modbus simulator but facing issues. Any progress or have you resolved the issue.
