### ISSUE TITLE
Keadm join command argument requirements

### ISSUE THREAD

**Issue by Ma-Dan** [kubeedge/kubeedge#2372]
**What would you like to be added/modified**:
Add more command arguments to specify more options, such as Quic port, stream port, node IP, components switches.

**Why is this needed**:
(1) CloudCore exposed port could be different from 10000 to 10004
(2) Node IP need to be set
(3) Other components (edge stream, edge mesh) switch need to be set
(4) More other options

**Comment by daixiang0** [comment]
Please add this to the agenda, then we can discuss on the next meeting.

**Comment by daixiang0** [comment]
How about add option to support specify configfile, it would be more common?

**Comment by Ma-Dan** [comment]
> How about add option to support specify configfile, it would be more common?

We added config file specification in our local build and tried, seems this method caused more manual work with configfile generation and modification, and also config file needs to be verified before applying.
We considered batch generating configfile from cloud side, currently need to verify that all settings could be generated outside the edge nodes, especially network parameters.
