### ISSUE TITLE
EdgeSite: How can I connect not master node?

### ISSUE THREAD

**Issue by antoniomuso** [kubeedge/kubeedge#2375]
How can I connect not master node?
I deploy the node Master EdgeSite Node but after that how can I connect not master node to this Master Node?
I don't know if I don't have completely understood the EdgeSite architecture.

**Comment by daixiang0** [comment]
What is your case? please see https://kubeedge.io/en/docs/components/edgesite for details.

**Comment by antoniomuso** [comment]
I have k8s, I need to deploy EdgeSite Master node in a location and the other edge nodes in the same location. But I don't understand how can communicate EdgeSite Master with Master EdgeSite Node. I have  read the documentation but I don't find it clear.

**Comment by daixiang0** [comment]
I think you misunderstand it, EdgeSite still is a worker node, see https://kubeedge.io/en/docs/components/edgesite/#deploy-edgesite-worker-node-to-k8s-cluster.

**Comment by antoniomuso** [comment]
Ok, I misunderstand it. Thanks for the clarification.
