### ISSUE TITLE
pod would restart when long time offline

### ISSUE THREAD

**Issue by JiahuiZhao11** [kubeedge/kubeedge#2385]
**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```

</details>

**Comment by shenkonghui** [comment]
Are you referring to cloud eviction or edge pod restart？

**Comment by JiahuiZhao11** [comment]
在K8s中在网络断开又恢复正常后，各资源行为如下：
- Node状态变为Ready。
- Daemonset的Pod不会recreate，旧pod状态直接变为Running。
- Deployment则是将失联Node上的Pod删除（已有新Pod在其他Node创建的情况下）或重建（无新Pod在其他节点创建）
- Statefulset的Pod会重新recreate
- Staic Pod没有重启，但是Pod的运行时间会在kubelet起来的时候置为0
想问下 Kubeedge 在网络断开重连之后对资源的处理逻辑。

**Comment by JiahuiZhao11** [comment]
> Are you referring to cloud eviction or edge pod restart？

在K8s中在网络断开又恢复正常后，各资源行为如下：

Node状态变为Ready。
Daemonset的Pod不会recreate，旧pod状态直接变为Running。
Deployment则是将失联Node上的Pod删除（已有新Pod在其他Node创建的情况下）或重建（无新Pod在其他节点创建）
Statefulset的Pod会重新recreate
Staic Pod没有重启，但是Pod的运行时间会在kubelet起来的时候置为0

想问下 Kubeedge 在网络断开重连之后对资源的处理逻辑。

**Comment by JiahuiZhao11** [comment]
> Are you referring to cloud eviction or edge pod restart？

在K8s中在网络断开又恢复正常后，各资源行为如下：

Node状态变为Ready。
Daemonset的Pod不会recreate，旧pod状态直接变为Running。
Deployment则是将失联Node上的Pod删除（已有新Pod在其他Node创建的情况下）或重建（无新Pod在其他节点创建）
Statefulset的Pod会重新recreate
Staic Pod没有重启，但是Pod的运行时间会在kubelet起来的时候置为0

想问下 Kubeedge 在网络断开重连之后对资源的处理逻辑。

**Comment by shenkonghui** [comment]
> 在K8s中在网络断开又恢复正常后，各资源行为如下：
> 
> * Node状态变为Ready。
> * Daemonset的Pod不会recreate，旧pod状态直接变为Running。
> * Deployment则是将失联Node上的Pod删除（已有新Pod在其他Node创建的情况下）或重建（无新Pod在其他节点创建）
> * Statefulset的Pod会重新recreate
> * Staic Pod没有重启，但是Pod的运行时间会在kubelet起来的时候置为0
>   想问下 Kubeedge 在网络断开重连之后对资源的处理逻辑。

这个其实和kubeedge没有关系，kubeedge基于k8s，node都是由controllerManager进行管理，node变成notready以后，由controllerManager中的nodelifecyclecontroller对异常的node上的pod进行驱逐。

是有这种问题，网络断开以后，边缘节点虽然容器还能运行，但是云端已经驱逐了。网络恢复后会让边端的pod重启。

这个我们在公司内部版本做了一定的修改，思路是边缘节点不使用nodelifecyclecontroller进行管理，自己实现控制器进行管理。如果不修改controllerManager，那么可能就要考虑自己模拟node的心跳，不让node变成notready

**Comment by JiahuiZhao11** [comment]
> > 在K8s中在网络断开又恢复正常后，各资源行为如下：
> > 
> > * Node状态变为Ready。
> > * Daemonset的Pod不会recreate，旧pod状态直接变为Running。
> > * Deployment则是将失联Node上的Pod删除（已有新Pod在其他Node创建的情况下）或重建（无新Pod在其他节点创建）
> > * Statefulset的Pod会重新recreate
> > * Staic Pod没有重启，但是Pod的运行时间会在kubelet起来的时候置为0
> >   想问下 Kubeedge 在网络断开重连之后对资源的处理逻辑。
> 
> 这个其实和kubeedge没有关系，kubeedge基于k8s，node都是由controllerManager进行管理，node变成notready以后，由controllerManager中的nodelifecyclecontroller对异常的node上的pod进行驱逐。
> 
> 是有这种问题，网络断开以后，边缘节点虽然容器还能运行，但是云端已经驱逐了。网络恢复后会让边端的pod重启。
> 
> 这个我们在公司内部版本做了一定的修改，思路是边缘节点不使用nodelifecyclecontroller进行管理，自己实现控制器进行管理。如果不修改controllerManager，那么可能就要考虑自己模拟node的心跳，不让node变成notready

明白了，十分感谢

**Comment by Abirdcfly** [comment]
> > Are you referring to cloud eviction or edge pod restart？
> 
> 在 K8s 中在网络断开又恢复正常后，各资源行为如下：
> 
> Node 状态变为 Ready。
> Daemonset 的 Pod 不会 recreate，旧 pod 状态直接变为 Running。
> Deployment 则是将失联 Node 上的 Pod 删除（已有新 Pod 在其他 Node 创建的情况下）或重建（无新 Pod 在其他节点创建）
> Statefulset 的 Pod 会重新 recreate
> Staic Pod 没有重启，但是 Pod 的运行时间会在 kubelet 起来的时候置为 0
> 
> 想问下 Kubeedge 在网络断开重连之后对资源的处理逻辑。

实质的问题是pod有没有加容忍。如果不想出现你说的这个问题。给pod加容忍就可以了。
kubeedge没有对这块处理。我的理解是kubeedge没有明确“自治”这个概念的范围。没有明确有文档提到，哪块逻辑是边缘自治处理的，哪块不是。

**Comment by kevin-wangzefeng** [comment]
The default tolerationSeconds for node unreachable taint on pod is 3000 (5min), you can change by adding custom toleration in your pod / deployment.template.

This is what you are looking for:
```yaml
tolerations:
- key: "node.kubernetes.io/unreachable"
  operator: "Exists"
  effect: "NoExecute"
  tolerationSeconds: 36000 # or even -1 for infinite time
```

You don't really need any change on the node controller in this case. And **please note** that the node controller is managing all node status, pod evictions rates etc., clusterwide, any uncareful change could make the cluster very unstable.

ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions

**Comment by daixiang0** [comment]
/retitle pod would restart when long time offline

**Comment by docooler** [comment]
> The default tolerationSeconds for node unreachable taint on pod is 3000 (5min), you can change by adding custom toleration in your pod / deployment.template.
> 
> This is what you are looking for:
> 
> ```yaml
> tolerations:
> - key: "node.kubernetes.io/unreachable"
>   operator: "Exists"
>   effect: "NoExecute"
>   tolerationSeconds: 36000 # or even -1 for infinite time
> ```
> 
> You don't really need any change on the node controller in this case. And **please note** that the node controller is managing all node status, pod evictions rates etc., clusterwide, any uncareful change could make the cluster very unstable.
> 
> ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions

 # or even -1 for infinite time 
this isn't right !
here is comments from k8s code : 
// TolerationSeconds represents the period of time the toleration (which must be
	// of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default,
	// it is not set, which means tolerate the taint forever (do not evict). Zero and
	// negative values will be treated as 0 (evict immediately) by the system.
	// +optional
	TolerationSeconds *int64
