### ISSUE TITLE
cant get edge pod

### ISSUE THREAD

**Issue by cuikevin** [kubeedge/kubeedge#2406]
my kube-edge version is 12.0 and i am a begainner,so i config it followed 

https://blog.csdn.net/Obese_Tiger/article/details/104741708?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-3.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-3.control

but when i finish it,i cant see the edge node by "kubectl get nodes" at master。
my cloud ip is 192.168.150.134
my edge ip is 192.168.150.132
both running in VM, CENTOS7.
here is my log

At the cloud :
I1207 21:24:15.226215   37028 messagehandler.go:159] Node localhost.localdomain is still alive
I1207 21:24:21.308224   37028 messagehandler.go:217] event received for node localhost.localdomain id: 64c19608-2228-44d9-b689-613fb47d2a3e, parent_id: , group: meta, source: edged, resource: node/localhost.localdomain/default/nodestatus/localhost.localdomain, operation: update, content: map[ExtendResources:<nil> Status:map[addresses:[map[address:192.168.150.132 type:InternalIP] map[address:localhost.localdomain type:Hostname]] allocatable:map[cpu:1 memory:3670Mi pods:110] capacity:map[cpu:1 memory:3770Mi pods:110] conditions:[map[lastHeartbeatTime:2020-12-07T13:24:21Z lastTransitionTime:2020-12-07T13:24:21Z message:edge is posting ready status reason:EdgeReady status:True type:Ready]] daemonEndpoints:map[kubeletEndpoint:map[Port:%!s(float64=0)]] nodeInfo:map[architecture:amd64 bootID: containerRuntimeVersion:remote://19.3.14 kernelVersion:3.10.0-1160.6.1.el7.x86_64 kubeProxyVersion: kubeletVersion:v1.17.1-kubeedge-v1.2.0 machineID: operatingSystem:linux osImage:CentOS Linux 7 (Core) systemUUID:] phase:Running] UID:38796d14-1df3-11e8-8e5a-286ed488f209]
I1207 21:24:21.308369   37028 upstream.go:161] dispatch message ID: 64c19608-2228-44d9-b689-613fb47d2a3e
I1207 21:24:21.308376   37028 util.go:88] The resource type is nodestatus, 3
I1207 21:24:21.308381   37028 upstream.go:169] message: 64c19608-2228-44d9-b689-613fb47d2a3e, resource type is: nodestatus
I1207 21:24:21.308385   37028 upstream.go:171] message: 64c19608-2228-44d9-b689-613fb47d2a3e, operation type is: update
I1207 21:24:21.308393   37028 upstream.go:332] message: 64c19608-2228-44d9-b689-613fb47d2a3e, operation is: update, and resource is node/localhost.localdomain/default/nodestatus/localhost.localdomain
I1207 21:24:21.308426   37028 util.go:113] The resource name is localhost.localdomain, 4
I1207 21:24:30.226295   37028 messagehandler.go:111] Keepalive message received from node: localhost.localdomain
I1207 21:24:30.226349   37028 messagehandler.go:159] Node localhost.localdomain is still alive
I1207 21:24:31.401773   37028 messagehandler.go:217] event received for node localhost.localdomain id: 36fae80d-626b-46bc-a31d-b5f8734fc08d, parent_id: , group: meta, source: edged, resource: node/localhost.localdomain/default/nodestatus/localhost.localdomain, operation: update, content: map[ExtendResources:<nil> Status:map[addresses:[map[address:192.168.150.132 type:InternalIP] map[address:localhost.localdomain type:Hostname]] allocatable:map[cpu:1 memory:3670Mi pods:110] capacity:map[cpu:1 memory:3770Mi pods:110] conditions:[map[lastHeartbeatTime:2020-12-07T13:24:31Z lastTransitionTime:2020-12-07T13:24:31Z message:edge is posting ready status reason:EdgeReady status:True type:Ready]] daemonEndpoints:map[kubeletEndpoint:map[Port:%!s(float64=0)]] nodeInfo:map[architecture:amd64 bootID: containerRuntimeVersion:remote://19.3.14 kernelVersion:3.10.0-1160.6.1.el7.x86_64 kubeProxyVersion: kubeletVersion:v1.17.1-kubeedge-v1.2.0 machineID: operatingSystem:linux osImage:CentOS Linux 7 (Core) systemUUID:] phase:Running] UID:38796d14-1df3-11e8-8e5a-286ed488f209]
I1207 21:24:31.401957   37028 upstream.go:161] dispatch message ID: 36fae80d-626b-46bc-a31d-b5f8734fc08d
I1207 21:24:31.401965   37028 util.go:88] The resource type is nodestatus, 3
I1207 21:24:31.401969   37028 upstream.go:169] message: 36fae80d-626b-46bc-a31d-b5f8734fc08d, resource type is: nodestatus
I1207 21:24:31.401974   37028 upstream.go:171] message: 36fae80d-626b-46bc-a31d-b5f8734fc08d, operation type is: update
I1207 21:24:31.401981   37028 upstream.go:332] message: 36fae80d-626b-46bc-a31d-b5f8734fc08d, operation is: update, and resource is node/localhost.localdomain/default/nodestatus/localhost.localdomain
I1207 21:24:31.402038   37028 util.go:113] The resource name is localhost.localdomain, 4
I1207 21:24:41.440242   37028 messagehandler.go:217] event received for node localhost.localdomain id: 4899ada8-2749-4fe4-99d3-a0abddbb50d5, parent_id: , group: meta, source: edged, resource: node/localhost.localdomain/default/nodestatus/localhost.localdomain, operation: update, content: map[ExtendResources:<nil> Status:map[addresses:[map[address:192.168.150.132 type:InternalIP] map[address:localhost.localdomain type:Hostname]] allocatable:map[cpu:1 memory:3670Mi pods:110] capacity:map[cpu:1 memory:3770Mi pods:110] conditions:[map[lastHeartbeatTime:2020-12-07T13:24:41Z lastTransitionTime:2020-12-07T13:24:41Z message:edge is posting ready status reason:EdgeReady status:True type:Ready]] daemonEndpoints:map[kubeletEndpoint:map[Port:%!s(float64=0)]] nodeInfo:map[architecture:amd64 bootID: containerRuntimeVersion:remote://19.3.14 kernelVersion:3.10.0-1160.6.1.el7.x86_64 kubeProxyVersion: kubeletVersion:v1.17.1-kubeedge-v1.2.0 machineID: operatingSystem:linux osImage:CentOS Linux 7 (Core) systemUUID:] phase:Running] UID:38796d14-1df3-11e8-8e5a-286ed488f209]
I1207 21:24:41.440373   37028 upstream.go:161] dispatch message ID: 4899ada8-2749-4fe4-99d3-a0abddbb50d5
I1207 21:24:41.440380   37028 util.go:88] The resource type is nodestatus, 3
I1207 21:24:41.440385   37028 upstream.go:169] message: 4899ada8-2749-4fe4-99d3-a0abddbb50d5, resource type is: nodestatus
I1207 21:24:41.440389   37028 upstream.go:171] message: 4899ada8-2749-4fe4-99d3-a0abddbb50d5, operation type is: update
I1207 21:24:41.440396   37028 upstream.go:332] message: 4899ada8-2749-4fe4-99d3-a0abddbb50d5, operation is: update, and resource is node/localhost.localdomain/default/nodestatus/localhost.localdomain
I1207 21:24:41.440432   37028 util.go:113] The resource name is localhost.localdomain, 4
I1207 21:24:45.226765   37028 messagehandler.go:111] Keepalive message received from node: localhost.localdomain
I1207 21:24:45.226821   37028 messagehandler.go:159] Node localhost.localdomain is still alive
I1207 21:24:51.512598   37028 messagehandler.go:217] event received for node localhost.localdomain id: ba1423a5-4423-4c02-9342-919e52db156b, parent_id: , group: meta, source: edged, resource: node/localhost.localdomain/default/nodestatus/localhost.localdomain, operation: update, content: map[ExtendResources:<nil> Status:map[addresses:[map[address:192.168.150.132 type:InternalIP] map[address:localhost.localdomain type:Hostname]] allocatable:map[cpu:1 memory:3670Mi pods:110] capacity:map[cpu:1 memory:3770Mi pods:110] conditions:[map[lastHeartbeatTime:2020-12-07T13:24:51Z lastTransitionTime:2020-12-07T13:24:51Z message:edge is posting ready status reason:EdgeReady status:True type:Ready]] daemonEndpoints:map[kubeletEndpoint:map[Port:%!s(float64=0)]] nodeInfo:map[architecture:amd64 bootID: containerRuntimeVersion:remote://19.3.14 kernelVersion:3.10.0-1160.6.1.el7.x86_64 kubeProxyVersion: kubeletVersion:v1.17.1-kubeedge-v1.2.0 machineID: operatingSystem:linux osImage:CentOS Linux 7 (Core) systemUUID:] phase:Running] UID:38796d14-1df3-11e8-8e5a-286ed488f209]
I1207 21:24:51.512745   37028 upstream.go:161] dispatch message ID: ba1423a5-4423-4c02-9342-919e52db156b
I1207 21:24:51.512756   37028 util.go:88] The resource type is nodestatus, 3
I1207 21:24:51.512761   37028 upstream.go:169] message: ba1423a5-4423-4c02-9342-919e52db156b, resource type is: nodestatus
I1207 21:24:51.512766   37028 upstream.go:171] message: ba1423a5-4423-4c02-9342-919e52db156b, operation type is: update
I1207 21:24:51.512774   37028 upstream.go:332] message: ba1423a5-4423-4c02-9342-919e52db156b, operation is: update, and resource is node/localhost.localdomain/default/nodestatus/localhost.localdomain
I1207 21:24:51.512828   37028 util.go:113] The resource name is localhost.localdomain, 4
I1207 21:25:00.226794   37028 messagehandler.go:111] Keepalive message received from node: localhost.localdomain
I1207 21:25:00.226830   37028 messagehandler.go:159] Node localhost.localdomain is still alive

At the edge ：
W1207 21:27:42.349711   26007 context_channel.go:158] Get bad anonName:fb5a43e5-5113-4df2-b135-9b360c895cdd when sendresp message, do nothing
I1207 21:27:52.348065   26007 edged_status.go:170] Sync VolumesInUse: []
I1207 21:27:52.358738   26007 process.go:622] get a message {Header:{ID:619c145d-a8bf-4acb-93f4-004b567073ed ParentID: Timestamp:1607347672348 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/localhost.localdomain} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:3953131520 scale:0} d:{Dec:<nil>} s:3770Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:3848273920 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2020-12-07 21:27:52.340608088 +0800 CST m=+1360.272767979 LastTransitionTime:2020-12-07 21:27:52.340608088 +0800 CST m=+1360.272767979 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.150.132} {Type:Hostname Address:localhost.localdomain}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:3.10.0-1160.6.1.el7.x86_64 OSImage:CentOS Linux 7 (Core) ContainerRuntimeVersion:remote://19.3.14 KubeletVersion:v1.17.1-kubeedge-v1.2.0 KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I1207 21:27:52.361979   26007 metaclient.go:114] send sync message default/nodestatus/localhost.localdomain successed and response: {{409c7cbc-eb1a-43ff-bf51-d88187511970 619c145d-a8bf-4acb-93f4-004b567073ed 1607347672361  false} {edged meta response default/nodestatus/localhost.localdomain} OK}
I1207 21:27:52.368448   26007 process.go:117] received msg from cloud-hub:{Header:{ID:0793f428-1530-4445-a729-a94e7224e5ba ParentID:619c145d-a8bf-4acb-93f4-004b567073ed Timestamp:1607347672424 ResourceVersion:31997 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/localhost.localdomain} Content:OK}
W1207 21:27:52.368485   26007 context_channel.go:158] Get bad anonName:619c145d-a8bf-4acb-93f4-004b567073ed when sendresp message, do nothing
I1207 21:28:02.370095   26007 edged_status.go:170] Sync VolumesInUse: []
I1207 21:28:02.380407   26007 process.go:622] get a message {Header:{ID:d7f9d523-7e76-4066-9c18-8e932c8d732c ParentID: Timestamp:1607347682370 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:update Resource:default/nodestatus/localhost.localdomain} Content:{UID:38796d14-1df3-11e8-8e5a-286ed488f209 Status:{Capacity:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:3953131520 scale:0} d:{Dec:<nil>} s:3770Mi Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Allocatable:map[cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} memory:{i:{value:3848273920 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:110 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}] Phase:Running Conditions:[{Type:Ready Status:True LastHeartbeatTime:2020-12-07 21:28:02.362566505 +0800 CST m=+1370.294726414 LastTransitionTime:2020-12-07 21:28:02.362566505 +0800 CST m=+1370.294726414 Reason:EdgeReady Message:edge is posting ready status}] Addresses:[{Type:InternalIP Address:192.168.150.132} {Type:Hostname Address:localhost.localdomain}] DaemonEndpoints:{KubeletEndpoint:{Port:0}} NodeInfo:{MachineID: SystemUUID: BootID: KernelVersion:3.10.0-1160.6.1.el7.x86_64 OSImage:CentOS Linux 7 (Core) ContainerRuntimeVersion:remote://19.3.14 KubeletVersion:v1.17.1-kubeedge-v1.2.0 KubeProxyVersion: OperatingSystem:linux Architecture:amd64} Images:[] VolumesInUse:[] VolumesAttached:[] Config:nil} ExtendResources:map[]}}
I1207 21:28:02.383253   26007 metaclient.go:114] send sync message default/nodestatus/localhost.localdomain successed and response: {{ccf3b0b0-93b6-449e-825f-e1d24a5164c2 d7f9d523-7e76-4066-9c18-8e932c8d732c 1607347682383  false} {edged meta response default/nodestatus/localhost.localdomain} OK}
I1207 21:28:02.391832   26007 process.go:117] received msg from cloud-hub:{Header:{ID:c77cbe15-e8df-4cf1-b3ae-0492bfa91c65 ParentID:d7f9d523-7e76-4066-9c18-8e932c8d732c Timestamp:1607347682447 ResourceVersion:32012 Sync:false} Router:{Source:edgecontroller Group:resource Operation:response Resource:default/node/localhost.localdomain} Content:OK}
W1207 21:28:02.391869   26007 context_channel.go:158] Get bad anonName:d7f9d523-7e76-4066-9c18-8e932c8d732c when sendresp message, do nothing

so can any good person help me.plz

**Comment by daixiang0** [comment]
Now we have released 1.5, could you try this version? 1.2 is too old :(

**Comment by cuikevin** [comment]
thankyou， i am trying v 1.5

**Comment by cuikevin** [comment]
i success with the version 1.5.0 ,HaHa :). thanks again for your answer.

**Comment by daixiang0** [comment]
You are welcome.

/close
