### ISSUE TITLE
build KubeEdge failed - 'go' command not found 

### ISSUE THREAD

**Issue by longyang10208** [kubeedge/kubeedge#2407]
**I have installed Go package and setuped Go environment,   but 'go' command still cat not be found  while running `make` command**
**Here goes the detail:**

**I am getting the following error when I run**  
``` 
    cd $GOPATH/src/github.com/kubeedge/kubeedge
    make all WHAT=keadm  
```

**Here is the error**
```
$ sudo make all WHAT=keadm
# hack/verify-golang.sh
# make: go: Command not found
# hack/verify-golang.sh: line 26: go: command not found
# go detail version:
# hack/verify-golang.sh: line 28: go: command not found
# Makefile:67: recipe for target 'verify-golang' failed
# make: *** [verify-golang] Error 127
``` 
**It seems I didn't install go package, but I did install go package**
```
$ go version
# go version go1.15.6 linux/amd64
```
**and the hack/verify-golang.sh  can run alone sussessfully**
```
$ ./hack/verify-golang.sh
# go detail version: go version go1.15.6 linux/amd64
# go version: 1.15.6
``` 

**Does anyone know how I can get past this error? Thank you!**

**Environment**:
<details><summary>Kubernets 1.19.4</summary>

```console
$ kubectl --version
# Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
# Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

<details><summary>KubeEdge v1.5</summary>
the latest version, get KubeEdge source code by    
`git clone https://github.com/kubeedge/kubeedge $GOPATH/src/github.com/kubeedge/kubeedge`
</details>

**Comment by daixiang0** [comment]
@longyang10208 notice that you use `sudo`, i guess the PATH value of root user does not include `go`.

**Comment by longyang10208** [comment]
> @longyang10208 notice that you use `sudo`, i guess the PATH value of root user does not include `go`.

yeh, that's exactly right, thank you very much!
