### ISSUE TITLE
Create a documentation style guide. This document will contain dos, donts and best practices for writing documentation that is compliant with ReadTheDocs.

### ISSUE THREAD

**Issue by anvithks** [kubeedge/kubeedge#241]
The KubeEdge documentation is maintained on ReadTheDocs.io . This requires our documentation markdown to follow certain guidelines. This style guide should list out the proper way of writing a document that is ReadTheDocs compliant.

**Comment by sids-b** [comment]
ping @anvithks

**Comment by sids-b** [comment]
ping @anvithks . Can we refer to some document online to find out the style guides ?

**Comment by rohitsardesai83** [comment]
@anvithks , how do we proceed with this issue ?

**Comment by rohitsardesai83** [comment]
let's take this up post 1.0 release .

**Comment by sids-b** [comment]
@anvithks , can we have this guide quickly so that we can make it easy for contirubutors ?

**Comment by sids-b** [comment]
ping @anvithks
