### ISSUE TITLE
Why edgehub keepchannel use the channel without buffer?

### ISSUE THREAD

**Issue by threestoneliu** [kubeedge/kubeedge#2411]
**What happened and what you expected to happen**:
Edgehub keepchannel init method: [init method](https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edgehub/process.go#L44)
I have test the default statement in select, if we use no buffer channel, we will have enter default statement in some times, but if we use the buffer channel, we will only enter default when all the other  case statement doesn't match.
[buffer channel](https://play.golang.org/p/sHn2oucu_e9)
[nobuffer channel](https://play.golang.org/p/QJDH9ZlP41i)

EdgeCore log: 
![edgehuberror](https://user-images.githubusercontent.com/37207968/101482827-3a3cbe80-3992-11eb-8bbd-7d252ec8031a.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```

</details>

**Comment by daixiang0** [comment]
Good catch, could you help check other codes and post a pr to fix no buffer issue?

**Comment by threestoneliu** [comment]
> Good catch, could you help check other codes and post a pr to fix no buffer issue?

ok

**Comment by threestoneliu** [comment]
@daixiang0 I have modify the code, and create a pr but ci failed! Do we really need to change the method behaivor?

**Comment by daixiang0** [comment]
@threestoneliu need dig into it, change unit test if necessary.

**Comment by fisherxu** [comment]
@RainbowMango For the unbuffered channel as example here: https://play.golang.org/p/QJDH9ZlP41i , maybe we shouldn't add the `default` code in select of send gorouting?

**Comment by RainbowMango** [comment]
It is hard to say. There is no much difference between buffered and unbuffered channel.

When sending data to an unbuffered channel, the behavior is similar to a buffered channel with the buffer is full.

**Comment by RainbowMango** [comment]
> maybe we shouldn't add the default code in select of send gorountine?

Yes, if you need to make sure send a message(not just a try). There is nothing to do with buffered or unbuffered.
