### ISSUE TITLE
Simplify the readme file to get start with KubeEdge

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeedge/kubeedge#242]
**What would you like to be added**:
For the README in the root directory, the content is some complex, and it's not easy for users to get start and have a try quickly.
I think we should put some content in separate doc file and provide most simple steps here, so users would like to have a try first 

**Why is this needed**:
Make the "get start" document as easy as possible in README file.

**Comment by m1093782566** [comment]
What about write some scripts to reduce the manual steps?

**Comment by anvithks** [comment]
Yes. This is a good idea.
We already have the documentation in different sections on https://docs.kubeedge.io.
We can reference relevant sections and provide links instead of having too much text in the Readme.

**Comment by sids-b** [comment]
Lets take this up quickly. Our Readme has become very big and is not in sync with docs.kubeedge.io.
cc @naveensriram to help find a guy to close this quickly

**Comment by sids-b** [comment]
This issue is fixed by @edisonxiang in #391. Thanks
