### ISSUE TITLE
add flag to skip download checksum

### ISSUE THREAD

**Issue by Abirdcfly** [kubeedge/kubeedge#2420]
**What would you like to be added/modified**:
after v1.5.0 when install wget checksum and sha512sum is added.It make offline install more Complicated. I think we should add a flag to skip this Steps for offline install. 
**Why is this needed**:
offline or can not connnect to github.com Environment

**Comment by daixiang0** [comment]
It is not a good choice, checksum is for security.  Also, we will download service files and crds files.

What you want is whole offline deployment indeed, which is under development.

Besides, we will add other release sources to reduce network issue.

**Comment by Abirdcfly** [comment]
👌 🙏
