### ISSUE TITLE
Failed to patch device status

### ISSUE THREAD

**Issue by bluntWu** [kubeedge/kubeedge#2423]
Error running kubeedge-counter-demo

The content of the error report is：“Failed to patch device status &{{[{status {ON map[timestamp:1607 type:string]} {0 map[timestamp:1607 type:string]}}]}} of device counter in namespace default， error:the server could not find the requested resource (patch devices.devices.kubeedge.io counter)”

$ k8s version ：1.19
$ kubeedge version :1.15

**Comment by daixiang0** [comment]
see https://github.com/kubeedge/examples/pull/57

**Comment by swartz-k** [comment]
create clusterrole && serviceaccount and use `rest.InClusterConfig` to get conf
