### ISSUE TITLE
keadm init fail

### ISSUE THREAD

**Issue by gjmzj** [kubeedge/kubeedge#2424]
**What happened**:
following tips: https://github.com/kubeedge/kubeedge/blob/master/docs/troubleshooting.md

still got error:
```
 tree /etc/kubeedge/
/etc/kubeedge/
├── crds
│   ├── devices
│   │   ├── devices_v1alpha2_devicemodel.yaml
│   │   └── devices_v1alpha2_device.yaml
│   └── reliablesyncs
│       ├── cluster_objectsync_v1alpha1.yaml
│       └── objectsync_v1alpha1.yaml
└── kubeedge-v1.5.0-linux-amd64.tar.gz

./keadm init --advertise-address="114.*.*.*" --kubeedge-version 1.5.0
Kubernetes version verification passed, KubeEdge installation will start...
W1211 20:13:08.239798   25232 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1211 20:13:08.246187   25232 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1211 20:13:08.250493   25232 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1211 20:13:08.254758   25232 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Expected or Default KubeEdge version 1.5.0 is already downloaded and will checksum for it.
kubeedge-v1.5.0-linux-amd64.tar.gz checksum:
checksum_kubeedge-v1.5.0-linux-amd64.tar.gz.txt content:
[Run as service] start to download service file for cloudcore
Output failed:  exit status 4
Error: fail to download service file,error:{failed to run command(cd /etc/kubeedge/ && sudo -E wget -t 5 -k --no-check-certificate https://raw.githubusercontent.com/kubeedge/kubeedge/release-1.5/build/tools/cloudcore.service), err:exit status 4}
```

**What you expected to happen**:
keadm init success

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
# paste output here
kubelet --version
Kubernetes v1.19.4

$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by zzxgzgz** [comment]
can you try to manually download the cloudcore.service file using the following command?
`sudo -E wget -t 5 -k --no-check-certificate https://raw.githubusercontent.com/kubeedge/kubeedge/release-1.5/build/tools/cloudcore.service`

If it fails then it is the network issue.

**Comment by gjmzj** [comment]
yes, it is the network issue; can we have a workaround like https://github.com/kubeedge/kubeedge/blob/master/docs/troubleshooting.md

**Comment by zzxgzgz** [comment]
> yes, it is the network issue; can we have a workaround like https://github.com/kubeedge/kubeedge/blob/master/docs/troubleshooting.md

I think this problem was solved by this PR already:
https://github.com/kubeedge/kubeedge/pull/2170

Are you using the latest version 1.5 of KubeEdge? Can you try to use it, and also place the cloudcore.service file at its desired path then try again?
