### ISSUE TITLE
can KubeEdge use runc

### ISSUE THREAD

**Issue by DongxinWang** [kubeedge/kubeedge#2429]
使用kubeedge过程中，遇到一个问题，kubeedge边缘节点资源受限（68M内存），尝试使用podman但发现podman消耗内存很大，所以kubeedge是否能直接对接runc？来缓解这一问题。

**Comment by kevin-wangzefeng** [comment]
KubeEdge provides support to OCI conformant container runtime through CRI.
The community verified runtimes are docker, containerd, CRI-O and kata containers.
In resource limited cases, you can use cri-o, which takes only 30MB memory.
