### ISSUE TITLE
Will kubeedge support docker network plugins in the future version

### ISSUE THREAD

**Issue by touchuyht** [kubeedge/kubeedge#2432]
**What happened**:
edgecore can't use docker cnm plugins. 
what you expected to happen:
The docker option **--network** is supported. Either it can be assigned in the edgecore.yaml or in the pod annotations.

**Comment by fisherxu** [comment]
> **What happened**:
> edgecore can't use docker cnm plugins.
> what you expected to happen:
> The docker option **--network** is supported. Either it can be assigned in the edgecore.yaml or in the pod annotations.

Does k8s support the docker cnm plugins?

**Comment by touchuyht** [comment]
> > **What happened**:
> > edgecore can't use docker cnm plugins.
> > what you expected to happen:
> > The docker option **--network** is supported. Either it can be assigned in the edgecore.yaml or in the pod annotations.
> 
> Does k8s support the docker cnm plugins?

No, but k8s support cni plugins. My team's project need a network solution in the edge nodes to enable communications between edge nodes, either it be cni plugins which can be running when the edge nodes are disconnected from cloud or docker cnm solutions.

**Comment by daixiang0** [comment]
If you want to enable communications between edge nodes, try [EdgeMesh](https://kubeedge.io/en/docs/developer/edgemesh_guide/).
