### ISSUE TITLE
树莓派4 安装kubeedge v1.5后， kube-flannel，kube-proxy运行错误 

### ISSUE THREAD

**Issue by skyearthfeng** [kubeedge/kubeedge#2434]
**What happened**:
树莓派的pod  kube-flannel 日志如下：

ERROR: logging before flag.Parse: I1215 09:59:54.001818       1 main.go:519] Determining IP address of default interface
ERROR: logging before flag.Parse: I1215 09:59:54.004045       1 main.go:532] Using interface with name wlan0 and address 192.168.8.116
ERROR: logging before flag.Parse: I1215 09:59:54.004159       1 main.go:549] Defaulting external address to interface address (192.168.8.116)
W1215 09:59:54.004264       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1215 09:59:54.004391       1 client_config.go:613] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
ERROR: logging before flag.Parse: E1215 09:59:54.097252       1 main.go:250] Failed to create SubnetManager: fail to create kubernetes config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

树莓派的pod  kube-proxy日志如下：

standard_init_linux.go:219: exec user process caused: exec format error

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
Kubernetes v1.19.4
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by daixiang0** [comment]
/remove-kind bug

CNI support is under development, it is normal 
/close

**Comment by DreamEagle0** [comment]
So kubeEdge still doesn't  support flannel?
