### ISSUE TITLE
Treat master as a edge node

### ISSUE THREAD

**Issue by qizha** [kubeedge/kubeedge#244]
**What happened**:
There is an error in the log:
`ERROR channelq/channelq.go:101 rChannel for edge node family-nc02u is removed`
As @sids-b mentioned in slack:

> The reason for this log is that edgecontroller is assuming family-nc02u is also one of the edge nodes and trying to send a message to the node via cloudhub. Cloudhub doesnt have a channel/websocket connection with the master node amd hence logging this error.

**What you expected to happen**:
Give a edge role to edgenode and do not treat a node with master role as a edge node. In this way, we can do some management to edge node particular especially when there is one K8S master managing node located on both cloud and edge.

**How to reproduce it (as minimally and precisely as possible)**:
Always

**Comment by sids-b** [comment]
cc @maurya-anuj
