### ISSUE TITLE
Why does the device information in ConfigMap still exist after the device is removed

### ISSUE THREAD

**Issue by wzq12345678** [kubeedge/kubeedge#2455]
**What happened and what you expected to happen**:
Why does the device information in ConfigMap still exist after the device is removed

**How to reproduce it (as minimally and precisely as possible)**:
After I created a device, when I wanted to change the properties inside the device, I deleted the device and reedited it, but the old information from configMap always existed.

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```

</details>

**Comment by sailorvii** [comment]
Which version do you use? If it's 1.4, there's an issue and has been fixed, please update to 1.5 and check it again.
