### ISSUE TITLE
keadm reset too slow

### ISSUE THREAD

**Issue by gitlijian** [kubeedge/kubeedge#2475]
![image](https://user-images.githubusercontent.com/15320599/103253894-fe5bae80-49bd-11eb-9b56-1f6f9e0695af.png)

**What would you like to be added/modified**:

**Why is this needed**:

**Comment by daixiang0** [comment]
Please use English.

Fixed by  #2035

**Comment by zhangyunxin1** [comment]
楼主安装成功没
