### ISSUE TITLE
containerd Runtime with KubeEdge | How to get edgecore running with containerd without installing docker

### ISSUE THREAD

**Issue by bitvijays** [kubeedge/kubeedge#2483]
As per the [KubeEdge runtime configuration](https://github.com/kubeedge/kubeedge/blob/master/docs/configuration/cri.md#containerd), KubeEdge can be executed using `containerd` as a container runtime.

Currently, it is mentioned that "when docker is installed, `containerd` is installed by default". Now, when this happens `container network interface` is already setup ? i.e.
```
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:e2:31:f1:0d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```
is already present and `edgecore` works fine?

However, in the case where we are installing the `containerd` without `docker` using `apt-get install containerd`. We also need to setup `container network interface`. 

Now, I followed the [Step1](https://github.com/kubeedge/kubeedge/blob/master/docs/configuration/cri.md#steps) of CNI installation (Download CNI plugin release and extract it) and configuring CNI plugin (adding the configuration in `/etc/cni/net.d` folder).

However, when `containerd` is restarted, it doesn't start the network defined in the `cni` because of which the `edgecore` stops working because of the segmentation fault.

```
Dec 30 08:37:49 kenode-0002 edgecore[2162]: E1230 08:37:49.359382    2162 config.go:33] [EdgeMesh] get listen ip err: route ip+net: no such network interface
Dec 30 08:37:49 kenode-0002 edgecore[2162]: E1230 08:37:49.364455    2162 csi_plugin.go:226] kubernetes.io/csi: CSIDriverLister not found on KubeletVolumeHost
Dec 30 08:37:49 kenode-0002 edgecore[2162]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 30 08:37:49 kenode-0002 edgecore[2162]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x299c480]
Dec 30 08:37:49 kenode-0002 edgecore[2162]: goroutine 85 [running]:
Dec 30 08:37:49 kenode-0002 edgecore[2162]: net.(*TCPListener).Addr(...)
Dec 30 08:37:49 kenode-0002 edgecore[2162]:         /root/.gvm/gos/go1.15/src/net/tcpsock.go:283
Dec 30 08:37:49 kenode-0002 edgecore[2162]: github.com/kubeedge/kubeedge/edgemesh/pkg/proxy.Init()
Dec 30 08:37:49 kenode-0002 edgecore[2162]:         /root/codes/src/github.com/kubeedge/kubeedge/edgemesh/pkg/proxy/proxy.go:45 +0x60
Dec 30 08:37:49 kenode-0002 edgecore[2162]: github.com/kubeedge/kubeedge/edgemesh/pkg.(*EdgeMesh).Start(0x40008c27f0)
Dec 30 08:37:49 kenode-0002 edgecore[2162]:         /root/codes/src/github.com/kubeedge/kubeedge/edgemesh/pkg/module.go:51 +0x30
Dec 30 08:37:49 kenode-0002 edgecore[2162]: created by github.com/kubeedge/beehive/pkg/core.StartModules
Dec 30 08:37:49 kenode-0002 edgecore[2162]:         /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:23 +0x13c
Dec 30 08:37:49 kenode-0002 systemd[1]: edgecore.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

Could we provide more details on how to setup `containerd` from start without assuming `docker` is installed? or more info on running `containerd` / creating network using `cni` and ensuring `edgecore` works fine without `docker` installed?

**Comment by bitvijays** [comment]
Similar question here https://discuss.kubernetes.io/t/cni-not-starting-after-switching-from-docker-to-containerd/12092

**Comment by drawdy** [comment]
same question

**Comment by Abirdcfly** [comment]
https://kubeedge.io/en/docs/advanced/cri/#containerd the doc is helpful, And It can be running. Do you change edgecore config?I need more information.😂
