### ISSUE TITLE
how to update stream certs when add edge nodes

### ISSUE THREAD

**Issue by zhiyxu** [kubeedge/kubeedge#2484]
**What happened and what you expected to happen**:
当前环境中cloudcore运行在pod中，在云端集群访问边缘节点上的pod日志时报错如下：
```
# kubectl logs nginx-deployment-77698bff7d-wmqfx
Error from server: Get https://node4:10350/containerLogs/default/nginx-deployment-77698bff7d-zf5c6/nginx: x509: certificate is not valid for any names, but wanted to match node4
```
此时需要在生成stream证书时在`$SUBJECTALTNAME`中添加`DNS:node4`，重启cloudcore后，即可正常访问

当前的问题是：
如果存在新的边缘节点加入集群，需要重新生成stream证书、重启cloudcore重新加载证书后，才能对新边缘节点上的pod进行`kubectl logs`访问，但频繁重启cloudcore太过暴力，是否存在更好的办法？
重新生成stream证书后，是否能够不重启cloudcore，动态加载证书？

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```

</details>

**Comment by daixiang0** [comment]
/question
/retitle how to update stream certs when add edge nodes

**Comment by huapox** [comment]
+1

**Comment by huapox** [comment]
with k3s 1.20; kedge 1.10.3; kedge binary installed(without keadm)

- cloudStream certs: with tlsSAN: `export CLOUDCORE_DOMAINS="xxx-node62,DNS:*.kedge"`
- have to set node's ip-hostname mapping to k3s's /etc/hosts
- then exec/logs ok
- switch with metircs-server v045, then got err:

```bash
[root@(?.|default:kube-system) kube-system]$ kc logs -f metrics-server-6bd975677b-6rmql
# unable to fetch metrics from node node193.kedge: Get "https://172.25.23.193:10351/stats/summary?only_cpu_and_memory=true": x509: certificate is valid for 127.0.0.1, 172.25.23.194, not 172.25.23.193, unable to fully scrape metrics from node xxx-node62: unable to fetch metrics from node xxx-node62: Get "https://172.25.21.62:10351/stats/summary?only_cpu_and_memory=true": x509: certificate is valid for 127.0.0.1, 172.25.23.194, not 172.25.21.62
```

**Comment by huapox** [comment]
resolv with kedge v1.10.3, for kedge v1.12.1 ref: #4414 
---
just use nodeIP: 172.0.0.1; and add `172.0.0.1` to cloudStream's certs

`export CLOUDCOREIPS="172.25.23.194,IP.3:172.0.0.1"` (172, not 127)
