### ISSUE TITLE
build kubeadm failed with kubeedge 1.5

### ISSUE THREAD

**Issue by leofang94** [kubeedge/kubeedge#2485]
**What happened and what you expected to happen**:
when exec "root@leo-VirtualBox:~/go/src/github.com/kubeedge/kubeedge# make all WHAT=keadm", which failed as below:
hack/verify-golang.sh
go detail version: go version go1.15.6 linux/amd64
go version: 1.15.6
hack/make-rules/build.sh keadm
building github.com/kubeedge/kubeedge/keadm/cmd/keadm
+ go build -o /root/go/src/github.com/kubeedge/kubeedge/_output/local/bin/keadm -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2021-01-02T02:32:30Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=2eecccdd45868ced3a9c12f2e44cbcb8947ad85c -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.5.0-beta.0.175+2eecccdd45868c -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=5+' github.com/kubeedge/kubeedge/keadm/cmd/keadm
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
Makefile:47: recipe for target 'all' failed
make: *** [all] Error 1
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
root@leo-VirtualBox:~/go/src/github.com/kubeedge/kubeedge# gcc --version 
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 Copyright (C) 2017 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@leo-VirtualBox:~/go/src/github.com/kubeedge/kubeedge# make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

root@leo-VirtualBox:/go/src/github.com/kubeedge/kubeedge# uname -a
Linux leo-VirtualBox 5.4.0-59-generic #6518.04.1-Ubuntu SMP Mon Dec 14 15:59:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
<details><summary>Kubernets Version</summary>
```console
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```

</details>

**Comment by daixiang0** [comment]
It is your env issue, please try upgrade `git` then do test. Also, you can run it with `golang:1.15` image.

**Comment by leofang94** [comment]
I try as your suggestion, but it failed as the same.
root@ke-cloud:~/go/src/github.com/kubeedge/kubeedge# make WHAT=keadm
hack/verify-golang.sh
go detail version: go version go1.15.6 linux/amd64
go version: 1.15.6
hack/make-rules/build.sh keadm
building github.com/kubeedge/kubeedge/keadm/cmd/keadm
+ go build -o /root/go/src/github.com/kubeedge/kubeedge/_output/local/bin/keadm -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2021-01-04T01:12:19Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=2eecccdd45868ced3a9c12f2e44cbcb8947ad85c -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.5.0-beta.0.175+2eecccdd45868c -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=5+' github.com/kubeedge/kubeedge/keadm/cmd/keadm
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
Makefile:47: recipe for target 'all' failed
make: *** [all] Error 1

root@ke-cloud:~/go/src/github.com/kubeedge/kubeedge# apt upgrade git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.17.1-1ubuntu0.7).
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libck-connector0
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by daixiang0** [comment]
Try in container, you can post the issue in golang community, they are experts in this field.

**Comment by leofang94** [comment]
> Try in container, you can post the issue in golang community, they are experts in this field.

ok, thanks

**Comment by Abirdcfly** [comment]
One possible reason is that your virtualbox's memory is small. 😂 https://forum.golangbridge.org/t/go-build-exits-with-signal-killed/513/2
