### ISSUE TITLE
failed to run kubectl logs edge node pod

### ISSUE THREAD

**Issue by zhangru-dev** [kubeedge/kubeedge#2492]
![image](https://user-images.githubusercontent.com/64136514/104005526-3ba31600-51e0-11eb-9d62-d71c9972fd30.png)

edgecore 日志
![image](https://user-images.githubusercontent.com/64136514/104005588-4fe71300-51e0-11eb-88d3-dd40bf0b4e7c.png)

**Comment by daixiang0** [comment]
It seems docker issue indeed, please google it for help first. If confirm not, share more details about this, only error log does not help.

/remove-kind bug
/question

**Comment by Abirdcfly** [comment]
I think you should add more error log, maybe cloudcore log.
"docker can't reopen log error" does not lead to "kubectl log edge node pod error",at least in my case.😜

**Comment by daixiang0** [comment]
/retitle failed to run kubectl logs edge node pod
