### ISSUE TITLE
edge device use containerd failed

### ISSUE THREAD

**Issue by hechengjie** [kubeedge/kubeedge#2498]
Edge device side use docker is worked. 
I try to use containerd for edge device.
I modifiy the mini edgecore.yaml. 
But it always failed!.

> apiVersion: edgecore.config.kubeedge.io/v1alpha1
> database:
>   dataSource: /var/lib/kubeedge/edgecore.db
> kind: EdgeCore
> modules:
>   edgeHub:
>     heartbeat: 15
>     httpServer: https://172.16.192.25:10002
>     tlsCaFile: /etc/kubeedge/ca/rootCA.crt
>     tlsCertFile: /etc/kubeedge/certs/server.crt
>     tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
>     token: b1346a1f1a2a321ecd29dc519dc66ce9ea216e131da7ca1e594cceda4f037c00.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTA0NzIzNzZ9.DK8A5G0lfP0t_FXxX9nC-S-tMd0ch3p-TlzpY0JuxIc
>     websocket:
>       enable: true
>       handshakeTimeout: 30
>       readDeadline: 15
>       server: 172.16.192.25:10000
>       writeDeadline: 15
>   edged:
>     cgroupDriver: systemd
>     cgroupRoot: ""
>     cgroupsPerQOS: true
>     clusterDNS: ""
>     clusterDomain: ""
>     devicePluginEnabled: false
>     gpuPluginEnabled: false
>     hostnameOverride: containerdedge
>     nodeIP: 192.168.137.140
>     runtimeRequestTimeout: 2
>     podSandboxImage: k8s.gcr.io/pause:3.2
>     remoteImageEndpoint: unix:///var/run/containerd/containerd.sock
>     remoteRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
>     runtimeType: remote
>   eventBus:
>     mqttMode: 2
>     mqttQOS: 0
>     mqttRetain: false
>     mqttServerExternal: tcp://127.0.0.1:1883
>     mqttServerInternal: tcp://127.0.0.1:1884

> ./edgecore --config edgecore.yaml
> 2021-01-12 03:19:28.221296 I | INFO: Install client plugin, protocol: rest
> 2021-01-12 03:19:28.221467 I | INFO: Installed service discovery plugin: edge
> I0112 03:19:28.242535   20469 remote_runtime.go:59] parsed scheme: ""
> I0112 03:19:28.242561   20469 remote_runtime.go:59] scheme "" not registered, fallback to default scheme
> I0112 03:19:28.242610   20469 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
> I0112 03:19:28.242631   20469 clientconn.go:948] ClientConn switching balancer to "pick_first"
> I0112 03:19:28.242681   20469 remote_image.go:50] parsed scheme: ""
> I0112 03:19:28.242698   20469 remote_image.go:50] scheme "" not registered, fallback to default scheme
> I0112 03:19:28.242718   20469 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
> I0112 03:19:28.242733   20469 clientconn.go:948] ClientConn switching balancer to "pick_first"
> W0112 03:19:33.253309   20469 nvidia.go:61] NVIDIA GPU metrics will not be available: no NVIDIA devices found
> E0112 03:19:33.277444   20469 remote_runtime.go:83] Version from runtime service failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
> E0112 03:19:33.277501   20469 kuberuntime_manager.go:200] Get runtime version failed: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
> E0112 03:19:33.277514   20469 edged.go:262] init new edged error, New generic runtime manager failed, err: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService

**Comment by ChAnYaNG97** [comment]
Same issue here. Have you solved the problem yet?
