### ISSUE TITLE
fix golint warnings

### ISSUE THREAD

**Issue by islinwb** [kubeedge/kubeedge#25]
Currently code in many directories (excluding `vendor`, `docs`, etc.) fails to pass the `golint`.

Contributors are very welcome to take part in this work. Just leave the directory you want to fix in this issue.

How to do it?  
A simple way is 
```shell
cd ${GOPATH}/src/github.com/kubeedge/kubeedge
# get gometalinter(https://github.com/alecthomas/gometalinter)
curl -L https://git.io/vp6lP | sh
export PATH=${PATH}:${GOPATH}/src/github.com/kubeedge/kubeedge/bin
gometalinter --disable-all --enable=golint --include=<Directory-You-Want-To-Fix> ./...
```
Then you'll see warnings if any. Just fix them accordingly.

/cc @m1093782566 @Lion-Wei @stewart-yu

**Comment by m1093782566** [comment]
Sounds like a good plan.

**Comment by stewart-yu** [comment]
IMO, first, fixing all in one PR is OK; secondary, can we add `gometalinter` in vendor? no need to get it every time we run CI

**Comment by m1093782566** [comment]
>  secondary, can we add gometalinter in vendor? no need to get it every time we run CI

@stewart-yu I think we may need to discuss what should be in vendor? files which are referenced by other codes OR files which are used during building, checking or testing?

**Comment by sids-b** [comment]
@maurya-anuj can you please help with this ?

**Comment by m1093782566** [comment]
ping @sids-b @maurya-anuj

Any updates?

**Comment by sids-b** [comment]
> ping @sids-b @maurya-anuj
> 
> Any updates?

@m1093782566 , PR will be raised by @maurya-anuj for pkg folder next week. After which we can also add golint in CI
