### ISSUE TITLE
Containerize edge core so docker can manage the lifecycle and simplify the deployment

### ISSUE THREAD

**Issue by tedli** [kubeedge/kubeedge#250]
**What would you like to be added**:

Dockerfile and scripts to run edge core as a container.

**Why is this needed**:

Simplify edge side deployment.

**Comment by m1093782566** [comment]
cc @qizha @Baoqiang-Zhang

**Comment by m1093782566** [comment]
@tedli 

I notice you are active in KubeEdge and provided some constructive feedback. Do you want to join as an external collaborator of KubeEdge?

**Comment by tedli** [comment]
> @tedli
> 
> I notice you are active in KubeEdge and provided some constructive feedback. Do you want to join as an external collaborator of KubeEde? If you want, I will send you an invite link.

cc @nkwangleiGIT

**Comment by nkwangleiGIT** [comment]
@m1093782566 yes, we'd like to join, can you send us the invitation link? thanks!
