### ISSUE TITLE
DCO is missing for the KubeEdge project

### ISSUE THREAD

**Issue by idvoretskyi** [kubeedge/kubeedge#2509]
Greetings, project maintainers.

CNCF's IP policy (https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy) requires all projects to use either CLA (Contributor License Agreements) or DCO (Developer Certificate of Origin). Unless there's a strong necessity to use CLA, we encourage projects to use DCO as it's easier to setup and use.

During the audit, we've noticed that your project doesn't have DCO enabled. Please enable DCO for all repositories in your GitHub organization. You may find more details here - https://github.com/apps/dco.

Thanks

**Comment by idvoretskyi** [comment]
Ref: https://github.com/cncf/foundation/issues/130

**Comment by fisherxu** [comment]
> Please enable DCO for all repositories in your GitHub organization. 

@idvoretskyi Thanks for the reminder, we have enabled DCO for all repos.

**Comment by idvoretskyi** [comment]
@fisherxu awesome, thanks. It works.
