### ISSUE TITLE
Modbus go mapper

### ISSUE THREAD

**Issue by beyondyinjl2** [kubeedge/kubeedge#2512]
cd $GOPATH/src/github.com/kubeedge/kubeedge/mappers/modbus-go
exe docker build . -t kubeedge/kubeedge-modbus:v1.0.0
error:
Step 3/6 : COPY ./modbus kubeedge/
COPY failed: stat /var/lib/docker/tmp/docker-builder757785432/modbus: no such file or directory
not modbus dir

**Comment by daixiang0** [comment]
We have moved modbus go to kubeedge/mappers-go, so move this issue here.

/close
