### ISSUE TITLE
What's the difference between edgecore & edgesite ?

### ISSUE THREAD

**Issue by hechengjie** [kubeedge/kubeedge#2521]
Edgesite only for offline mode ? Edgecore for online mode? 
If work node turn into offline mode from online mode, how to tran work pods ？

**Comment by YuxiJin-tobeyjin** [comment]
+1 , I‘m also confused, can edgesite and edgecore be deployed at the same , so we can manage edge node from the cloud as well as from local site(using local cluster manager)

**Comment by qizha** [comment]
well, we are considering to refactor the edge-site to make it more clearly. In general, the edge-site will be built to support the offline management mode, which means a K8S master will be running on edge and be able to be managed on Cloud.
