### ISSUE TITLE
Unable to get secret in edge node

### ISSUE THREAD

**Issue by SadmiB** [kubeedge/kubeedge#2524]
**What happened**:

**What you expected to happen**:
I defined database credentials as Kubernetes secrets and I'm getting them from my python code as environment variables(this works with native Kubernetes).
![image](https://user-images.githubusercontent.com/26244234/105382093-03ec9300-5c10-11eb-86df-8c7cdd2569eb.png)

Passing secrets as environment variables:
```
   envFrom:
     - secretRef:
          name: db-cred
```

**How to reproduce it (as minimally and precisely as possible)**:
Define a Kubernetes secret.
Pass it as environment variable in your yaml file.
Handle the environment variable in your code.

![image](https://user-images.githubusercontent.com/26244234/105382459-6180df80-5c10-11eb-94a1-1e50e246cdee.png)

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
Kubernetes v1.18.1
# paste output here
$ kubectl version
v1.18.1
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
KubeEdge v1.5.0

# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
KubeEdge v1.5.0
# paste output here
```

</details>

**Comment by daixiang0** [comment]
Fix by #2230
