### ISSUE TITLE
Can not compile the edge_core in the Raspberry Pi 3B

### ISSUE THREAD

**Issue by leeruibin** [kubeedge/kubeedge#253]
**What would you like to be added**:
Is there a release version of edge_core on arm architecture go version 1.10 linux/arm. 
**Why is this needed**:
I just try to compile the edge_core on my Raspberry Pi 3B, unfortunately i can not finish the compilation process. I have been spending about two hours in waiting it, however i just stuck in the line "go build cmd/edge_core.go", 
the total memory of the Raspberry Pi is about 800M, 
the system architecture is "Linux han 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux"
the go version is "1.10 linux/arm"

i can finish compiling edgecontroller, however the compilation process of the edge_core can not finish.

**Comment by sids-b** [comment]
@sujithsimon22 , can you please help here. I remember we were also facing something similar.

**Comment by sujithsimon22** [comment]
Hi @leeruibin ,

Have u tried to cross-compile and send the binary over to the raspberry-Pi ? 
You could execute the following command from within the KubeEdge directory (Pls ensure that the $GOPATH is set before executing):
 $ make edge_cross_build
You could also refer to https://github.com/kubeedge/kubeedge/blob/master/docs/setup/cross-compilation.md

**Comment by sujithsimon22** [comment]
It is advisable to cross-compile and transfer the binary along with the configurations to the edge node.
We will try to give release version of edge_core for arm architecture in the future releases.

**Comment by m1093782566** [comment]
> It is advisable to cross-compile and transfer the binary along with the configurations to the edge node.
We will try to give release version of edge_core for arm architecture in the future releases.

We should provide an arm architecture release. @sids-b Can we update the release v0.2 to support arm architecture? We do not need to wait till v0.3.

**Comment by sids-b** [comment]
Sure @m1093782566

**Comment by leeruibin** [comment]
@sujithsimon22 Thanks, i am trying to cross-compile but when i run "sudo apt-get install gcc-arm-linux-gnueabi" but i get 
"The following packages have unmet dependencies:
 gcc-arm-linux-gnueabi : Depends: gcc-5-arm-linux-gnueabi (>= 5.3.1-3~)
E: Unable to correct problems, you have held broken packages.
" 
i didn't use this before, is there any solution?
Also  i check the Makefile, the command may be "make cross_build" rather than "make edge_cross_build"

**Comment by nkwangleiGIT** [comment]
You can also do this inside docker container if you're familiar with docker, here is the base image:
https://hub.docker.com/_/golang

**Comment by sujithsimon22** [comment]
@leeruibin if u are using the makefile which is present inside the edge folder of KubeEdge then u have to give: $make cross_build  (as u have said),
I was talking about the makefile present in the KubeEdge folder, in which case u have to use: $make edge_cross_build

**Comment by tedli** [comment]
> @sujithsimon22 Thanks, i am trying to cross-compile but when i run "sudo apt-get install gcc-arm-linux-gnueabi" but i get
> "The following packages have unmet dependencies:
> gcc-arm-linux-gnueabi : Depends: gcc-5-arm-linux-gnueabi (>= 5.3.1-3~)
> E: Unable to correct problems, you have held broken packages.
> "
> i didn't use this before, is there any solution?
> Also i check the Makefile, the command may be "make cross_build" rather than "make edge_cross_build"

I suggest you to write a helloworld like program in pure C, to test your cross compiler works as expect.

**Comment by sujithsimon22** [comment]
We will 

> @sujithsimon22 Thanks, i am trying to cross-compile but when i run "sudo apt-get install gcc-arm-linux-gnueabi" but i get
> "The following packages have unmet dependencies:
> gcc-arm-linux-gnueabi : Depends: gcc-5-arm-linux-gnueabi (>= 5.3.1-3~)
> E: Unable to correct problems, you have held broken packages.
> "
> i didn't use this before, is there any solution?
> Also i check the Makefile, the command may be "make cross_build" rather than "make edge_cross_build"

 We will be providing a release package for the current version of KubeEdge (v0.2) for arm architecture, any time now. You could make use the binary within the release package :)

**Comment by sids-b** [comment]
@leeruibin , please find the link for the arm release package. https://github.com/kubeedge/kubeedge/releases/download/v0.2/kubeedge-v0.2-linux-arm.tar.gz 

Thanks @sujithsimon22 for the package :)

**Comment by leeruibin** [comment]
!! cool !! Thanks, you make my day. :) @sids-b @sujithsimon22  And thanks for your advice I will try what you say!!! @m1093782566 @nkwangleiGIT
