### ISSUE TITLE
how to use virtlet with kubeedge

### ISSUE THREAD

**Issue by yangchenliang** [kubeedge/kubeedge#2532]
**What happened and what you expected to happen**:
In kubeedge docs, seems to do not know how to use virtlet.
Is need to install criproxy and config runtimeType of edgecore.yaml 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```

</details>

**Comment by daixiang0** [comment]
See https://kubeedge.io/en/docs/advanced/cri/#virtlet

/close

**Comment by yangchenliang** [comment]
> See https://kubeedge.io/en/docs/advanced/cri/#virtlet
> 
> /close

I`ve looked up the link above and followed the steps.But there are a few questeions.
1.Whether edgecore.yaml configuration file  need to be modified
2.Whether to install criproxy and modify runtimeType in edgecore.yaml.
3.Can provides some use casese of virtlet

According to the document of virtlet, you need to deploy criproxy and modify the runtimeType to remote and criproxy.sock. and need to deploy additional dockershim.

Confused by the above questions, I am looking for you reply.
