### ISSUE TITLE
Can not display container logs when using contained as container runtime

### ISSUE THREAD

**Issue by Ma-Dan** [kubeedge/kubeedge#2536]
**What happened**:
"crictl logs <containerId>" can not display running container logs on edge nodes.

**What you expected to happen**:
"crictl logs <containerId>" and "kubectl logs" display logs correctly like docker runtime.

**How to reproduce it (as minimally and precisely as possible)**:
Prepare a K8s cluster with contained runtime, install cloucore v1.5.0, prepare an edge node with containerd runtime, configure edgecore using contained runtime and join.
Schedule a workload with multiple replicas on both cloud side nodes and edge nodes.
"crictl logs" can display container log on cloud side nodes, but not on edge nodes.

**Anything else we need to know?**:
Container runtime is configured following https://github.com/kubeedge/kubeedge/blob/master/docs/configuration/cri.md

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
Kubernetes v1.17.9
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
KubeEdge v1.5.0
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
KubeEdge v1.5.0
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by daixiang0** [comment]
The `logs` feature means `kubectl logs`, and `docker logs` would fail if you check edge logs.

**Comment by Ma-Dan** [comment]
kubectl logs also displays nothing, kubectl exec and kubectl top can work well on edge nodes.

**Comment by daixiang0** [comment]
If so, I think there are no logs for it, since we do not edit any logic for `crictl`.

Or you can check edgecore log to see any error about logs.

**Comment by Ma-Dan** [comment]
First "kubectl logs" displays nothing, then we debugged using "curl localhost:10350/containerLogs/default/nginx-deployment-545c56ccf9-nmmfz/nginx" on edge node, then use "crictl logs". I think containerd log is the root cause.
Also tried "crictl inspect", log config is below:
```
"io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
        "containerPath": "/dev/termination-log",
    "logPath": "/var/log/pods/default_nginx-deployment-7759576c7-6cgph_1568d21b-df10-4cd2-be8f-507490bd4600/nginx/0.log"
          "container_path": "/dev/termination-log",
        "io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
      "log_path": "nginx/0.log",
          "destination": "/dev/termination-log",
```
Exec into container, and then cat mapped file on host, no content in log files.

**Comment by Ma-Dan** [comment]
Same workload with same containerd on cloude side nodes can display log correctly, both on "kubectl logs" and "crictl logs".

**Comment by daixiang0** [comment]
You need run it at edge side, compare with cloud is meaningless.

**Comment by Ma-Dan** [comment]
> Please start a container then see `crictl logs` can work or not, if not, it is not KubeEdge issue indeed.

Start a pod and container with "crtctl startp/create/start" can run a container and get log correctly on the same node. But need some special configuration on pod "log_directory" and container "log_path" parameters.
We will compare the difference on manual started pod/container and edgecore scheduled ones to find out what happened to log output.

**Comment by Ma-Dan** [comment]
Kubeedge scheduled contaier log is written into mounted file (eg. /var/log/pods/default_nginx-deployment-???/nginx/0.log), but this file will be automatically cleaned in 10 seconds. We can only see kubectl log in this short time window.

**Comment by Ma-Dan** [comment]
We are using KubeEdge v1.5.0, https://github.com/kubeedge/kubeedge/blob/v1.5.0/edge/pkg/edged/edged.go#L582 container log rotation is set very small size, and only 2 log files is reserved, but this seems not affect docker runtime. I noticed that this size is increased in new version.

**Comment by daixiang0** [comment]
It is updated, see https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edged/edged.go#L583.

You can try with master HEAD code.
