### ISSUE TITLE
Edge_core crashing while doing stress test

### ISSUE THREAD

**Issue by srivatsav123** [kubeedge/kubeedge#254]
**What happened**:
When iterating 100 times, to add the device,toggle the device state from unknown to online and from online to unknown.Edgecore was crashing for 15/7 iterations etc......
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.Go to edge/test/integration/device/device.test.go
2.combine 6th and 7th testcase and make it one, put the code to iterate 100 times(for loop inside IT)
3.Put the logic to create device id and device into the for loop and remove the logic from device_suite_test.go
4.compile--  bash -x ./compile device
5.append the testManager module into the array in file edge/conf/modules.yaml
6 start edge core
7..run test case bash -x ./fast_test
8.. observe whether it crashes or not

![Screenshot from 2019-03-18 12-34-31](https://user-images.githubusercontent.com/39593583/54524186-4bac8e80-4997-11e9-83ee-5fcb7deb25e4.png)

**Anything else we need to know?**:
No 
**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by sids-b** [comment]
This is the same issue we resolved for flacky integration tests. Closing this :)
cc @srivatsav123
