### ISSUE TITLE
Support multi-instance high availability cloudcore for large-scale cluster

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#2543]
**What would you like to be added/modified**:
Support multi-instance high availability cloudcore in cloudside, so we can spport large-scale cluster.

**Why is this needed**:
Cloudcore is the core component of kubeegde in cloud, which is responsible for sending resources of cloud to the edge. Now the cloudcore is running in leader/follower mode, only one instance can run at the same time. For the more larger scale cluster, we need to support multi-instance high availability for cloudcore.

**Comment by akdanwlf** [comment]
Hello @fisherxu, I came across this issue listed as an LFX Mentorship Project. I am trying to join the kubeedge Slack channel, but it looks like the invitation present in CONTRIBUTING.md is expired. Can I find the link to join elsewhere?

**Comment by fisherxu** [comment]
> Hello @fisherxu, I came across this issue listed as an LFX Mentorship Project. I am trying to join the kubeedge Slack channel, but it looks like the invitation present in CONTRIBUTING.md is expired. Can I find the link to join elsewhere?

@akdanwlf Please try this one :) https://join.slack.com/t/kubeedge/shared_invite/enQtNjc0MTg2NTg2MTk0LWJmOTBmOGRkZWNhMTVkNGU1ZjkwNDY4MTY4YTAwNDAyMjRkMjdlMjIzYmMxODY1NGZjYzc4MWM5YmIxZjU1ZDI

**Comment by kevin-wangzefeng** [comment]
Previous disscussion https://github.com/kubeedge/kubeedge/issues/1444
