### ISSUE TITLE
can't get container log from cloud

### ISSUE THREAD

**Issue by nbet** [kubeedge/kubeedge#2564]
**What happened**:
after configure logs, 

**What you expected to happen**:
hope to get container log from cloud

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/15992450/107003920-7e004880-67c8-11eb-9c66-aaa0b744b73b.png">

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/15992450/107004035-a25c2500-67c8-11eb-90e3-116b44d0761e.png">

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
v1.17.9
$ kubectl version
v1.17.9
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
KubeEdge v1.5.0
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
2021-02-05 07:36:03.229823 I | INFO: Install client plugin, protocol: rest
2021-02-05 07:36:03.229933 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.5.0
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
root@ip-172-32-0-89:~/manifest# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:            7
CPU MHz:             3099.979
BogoMIPS:            4999.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
root@ip-172-32-0-89:~/manifest# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
root@ip-172-32-0-89:~/manifest# uname -a
Linux ip-172-32-0-89 4.15.0-1063-aws #67-Ubuntu SMP Mon Mar 2 07:24:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
root@ip-172-32-0-74:~# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:            7
CPU MHz:             3105.176
BogoMIPS:            4999.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
root@ip-172-32-0-74:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
Linux ip-172-32-0-74 4.15.0-1063-aws #67-Ubuntu SMP Mon Mar 2 07:24:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>
root@ip-172-32-0-74:/etc/kubeedge# docker info
Client:
 Debug Mode: false

Server:
 Containers: 551
  Running: 3
  Paused: 0
  Stopped: 548
 Images: 5
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1063-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.583GiB
 Name: ip-172-32-0-74
 ID: CQJ2:YC43:4SED:QXFY:OWLU:BSL2:ISZH:AGYV:7MM7:FASZ:T3TK:E2L3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
<details><summary>Others</summary>
</details>

**Comment by nbet** [comment]
hope you can help me

**Comment by hackers365** [comment]
https://kubeedge.io/en/docs/setup/keadm/#enable-kubectl-logs-feature

**Comment by nbet** [comment]
thanks @hackers365
but after review this doc, kubectl log still failed.

**Comment by hackers365** [comment]
> 
> 
> thanks @hackers365
> but after review this doc, kubectl log still failed.

`iptables -t nat -A OUTPUT -p tcp --dport 10350 -j DNAT --to $CLOUDCOREIPS:10003`

I guess this step is not correct

**Comment by nbet** [comment]
> > thanks @hackers365
> > but after review this doc, kubectl log still failed.
> 
> `iptables -t nat -A OUTPUT -p tcp --dport 10350 -j DNAT --to $CLOUDCOREIPS:10003`
> 
> I guess this step is not correct

how to check if this step is correct? thanks
