### ISSUE TITLE
CloudStream cannot be enable when in the cloudcore HA deployment pattern

### ISSUE THREAD

**Issue by Jw-Jm** [kubeedge/kubeedge#2565]
**What happened**:
CloudStream cannot be enable when in the cloudcore HA deployment pattern
docker logs：
[root@master-1 ha]# docker logs 027c4f14fe69
TLSTunnelPrivateKeyFile does not exist in /etc/kubeedge/certs/server.key, will load from secret
TLSTunnelCertFile does not exist in /etc/kubeedge/certs/server.crt, will load from secret
TLSTunnelCAFile does not exist in /etc/kubeedge/ca/rootCA.crt, will load from secret

**What you expected to happen**:
CloudStream can be enable when in the cloudcore HA deployment pattern

**How to reproduce it (as minimally and precisely as possible)**:
1.Follow this document(https://github.com/kubeedge/kubeedge/blob/master/build/cloud/ha/README.md) to deploy cloudcore HA
2.enable cloudStream in 02-ha-configmap.yaml.example

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
Kubernetes v1.18.0

$ kubectl version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by Jw-Jm** [comment]
I'll try to fix this bug

**Comment by metadeng** [comment]
> I'll try to fix this bug

any comment on this now?
