### ISSUE TITLE
failed to dispatch message, discard: failed to send message to sync keep channel

### ISSUE THREAD

**Issue by shiwenjuan123** [kubeedge/kubeedge#2569]
**What happened**:
Failure of irregular node connecting to cloud

**What you expected to happen**:
Nodes connected to the cloud continue to work normally

**How to reproduce it (as minimally and precisely as possible)**:
This problem occurs from time to time, and the test environment cannot be reproduced. The test environment and the formal environment are the same except for the network environment

**Anything else we need to know?**:
![微信图片_20210209170200](https://user-images.githubusercontent.com/78789343/107340368-a2c22c00-6af8-11eb-8b54-39acf240b219.png)
failed to dispatch message, discard: failed to send message to sync keep channel

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by shiwenjuan123** [comment]
Environment:

Kubernetes version (use kubectl version):
-----V1.18.6
KubeEdge version(e.g. cloudcore --version and edgecore --version):
-----cloudcore version------V1.5
-----edgecore version------V1.5

Cloud nodes Environment:
Hardware configuration (e.g. lscpu):
-----Hi1616 64 core
OS (e.g. cat /etc/os-release): 
-----centos7.6
Go version (e.g. go version):
----1.14.9

**Comment by shiwenjuan123** [comment]
Feb  5 03:02:51 tx2-shiyunxing edgecore[7420]: E0205 03:02:51.641893    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  5 03:02:55 tx2-shiyunxing edgecore[7420]: E0205 03:02:55.700541    7420 dns.go:290] [EdgeMesh] service router2.teamviewer.com is not found in this cluster
Feb  5 03:02:56 tx2-shiyunxing edgecore[7420]: E0205 03:02:56.646909    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  5 03:02:56 tx2-shiyunxing edgecore[7420]: E0205 03:02:56.669030    7420 dns.go:290] [EdgeMesh] service 1.pool.ntp.org is not found in this cluster
Feb  5 03:02:57 tx2-shiyunxing edgecore[7420]: E0205 03:02:57.812507    7420 process.go:77] failed to send message to sync keep channel
Feb  5 03:02:57 tx2-shiyunxing edgecore[7420]: E0205 03:02:57.812606    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  5 03:03:01 tx2-shiyunxing edgecore[7420]: E0205 03:03:01.649834    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  5 03:03:06 tx2-shiyunxing edgecore[7420]: E0205 03:03:06.652260    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  5 03:03:06 tx2-shiyunxing edgecore[7420]: E0205 03:03:06.676385    7420 dns.go:290] [EdgeMesh] service 1.pool.ntp.org is not found in this cluster
Feb  5 03:03:06 tx2-shiyunxing edgecore[7420]: E0205 03:03:06.716412    7420 dns.go:290] [EdgeMesh] service router16.teamviewer.com is not found in this cluster
Feb  5 03:03:11 tx2-shiyunxing edgecore[7420]: E0205 03:03:11.659964    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  5 03:03:15 tx2-shiyunxing edgecore[7420]: E0205 03:03:15.473969    7420 dns.go:290] [EdgeMesh] service quay.io is not found in this cluster
Feb  5 03:03:16 tx2-shiyunxing edgecore[7420]: E0205 03:03:16.663267    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  5 03:03:16 tx2-shiyunxing edgecore[7420]: E0205 03:03:16.699903    7420 dns.go:290] [EdgeMesh] service 0.fr.pool.ntp.org is not found in this cluster
Feb  5 03:03:16 tx2-shiyunxing edgecore[7420]: E0205 03:03:16.728337    7420 dns.go:290] [EdgeMesh] service router16.teamviewer.com is not found in this cluster

**Comment by shiwenjuan123** [comment]
Feb  6 00:53:54 tx2-shiyunxing edgecore[7420]: E0206 00:53:54.032021    7420 dns.go:290] [EdgeMesh] service k8s.gcr.io is not found in this cluster
Feb  6 00:53:58 tx2-shiyunxing edgecore[7420]: E0206 00:53:58.956521    7420 dns.go:290] [EdgeMesh] service 0.pool.ntp.org is not found in this cluster
Feb  6 00:53:59 tx2-shiyunxing edgecore[7420]: E0206 00:53:59.006874    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  6 00:53:59 tx2-shiyunxing edgecore[7420]: E0206 00:53:59.762810    7420 process.go:77] failed to send message to sync keep channel
Feb  6 00:53:59 tx2-shiyunxing edgecore[7420]: E0206 00:53:59.764016    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  6 00:54:04 tx2-shiyunxing edgecore[7420]: E0206 00:54:04.007798    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  6 00:54:04 tx2-shiyunxing edgecore[7420]: E0206 00:54:04.763525    7420 process.go:77] failed to send message to sync keep channel
Feb  6 00:54:04 tx2-shiyunxing edgecore[7420]: E0206 00:54:04.763652    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  6 00:54:09 tx2-shiyunxing edgecore[7420]: E0206 00:54:09.009308    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  6 00:54:09 tx2-shiyunxing edgecore[7420]: E0206 00:54:09.762984    7420 process.go:77] failed to send message to sync keep channel
Feb  6 00:54:09 tx2-shiyunxing edgecore[7420]: E0206 00:54:09.763321    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  6 00:54:14 tx2-shiyunxing edgecore[7420]: E0206 00:54:14.011330    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  6 00:54:14 tx2-shiyunxing edgecore[7420]: E0206 00:54:14.763712    7420 process.go:77] failed to send message to sync keep channel
Feb  6 00:54:14 tx2-shiyunxing edgecore[7420]: E0206 00:54:14.764688    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  6 00:54:19 tx2-shiyunxing edgecore[7420]: E0206 00:54:19.012359    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  6 00:54:19 tx2-shiyunxing dockerd[6301]: time="2021-02-06T00:54:19.021269728+08:00" level=warning msg="Error getting v2 registry: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
Feb  6 00:54:19 tx2-shiyunxing dockerd[6301]: time="2021-02-06T00:54:19.021474048+08:00" level=info msg="Attempting next endpoint for pull after error: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
Feb  6 00:54:19 tx2-shiyunxing dockerd[6301]: time="2021-02-06T00:54:19.021628032+08:00" level=error msg="Handler for POST /v1.40/images/create returned error: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
Feb  6 00:54:19 tx2-shiyunxing edgecore[7420]: E0206 00:54:19.025020    7420 remote_image.go:113] PullImage "k8s.gcr.io/kube-proxy:v1.18.6" from image service failed: rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Feb  6 00:54:19 tx2-shiyunxing edgecore[7420]: E0206 00:54:19.025907    7420 kuberuntime_image.go:51] Pull image "k8s.gcr.io/kube-proxy:v1.18.6" failed: rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Feb  6 00:54:19 tx2-shiyunxing edgecore[7420]: E0206 00:54:19.026476    7420 kuberuntime_manager.go:804] container &Container{Name:kube-proxy,Image:k8s.gcr.io/kube-proxy:v1.18.6,Command:[/usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf

**Comment by shiwenjuan123** [comment]
Feb  7 00:05:36 tx2-shiyunxing anacron[1510]: Job `cron.daily' terminated
Feb  7 00:05:36 tx2-shiyunxing anacron[1510]: Normal exit (1 job run)
Feb  7 00:05:37 tx2-shiyunxing edgecore[7420]: E0207 00:05:37.968831    7420 process.go:77] failed to send message to sync keep channel
Feb  7 00:05:37 tx2-shiyunxing edgecore[7420]: E0207 00:05:37.971105    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  7 00:05:38 tx2-shiyunxing edgecore[7420]: E0207 00:05:38.550517    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  7 00:05:42 tx2-shiyunxing edgecore[7420]: E0207 00:05:42.968803    7420 process.go:77] failed to send message to sync keep channel
Feb  7 00:05:42 tx2-shiyunxing edgecore[7420]: E0207 00:05:42.968853    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  7 00:05:43 tx2-shiyunxing edgecore[7420]: E0207 00:05:43.553062    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  7 00:05:47 tx2-shiyunxing edgecore[7420]: E0207 00:05:47.968892    7420 process.go:77] failed to send message to sync keep channel
Feb  7 00:05:47 tx2-shiyunxing edgecore[7420]: E0207 00:05:47.968932    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  7 00:05:48 tx2-shiyunxing edgecore[7420]: E0207 00:05:48.555323    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  7 00:05:50 tx2-shiyunxing edgecore[7420]: W0207 00:05:50.070794    7420 sysinfo.go:203] Nodes topology is not available, providing CPU topology
Feb  7 00:05:52 tx2-shiyunxing edgecore[7420]: E0207 00:05:52.969535    7420 process.go:77] failed to send message to sync keep channel
Feb  7 00:05:52 tx2-shiyunxing edgecore[7420]: E0207 00:05:52.970833    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  7 00:05:53 tx2-shiyunxing edgecore[7420]: E0207 00:05:53.563754    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  7 00:05:57 tx2-shiyunxing edgecore[7420]: E0207 00:05:57.969426    7420 process.go:77] failed to send message to sync keep channel
Feb  7 00:05:57 tx2-shiyunxing edgecore[7420]: E0207 00:05:57.969478    7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel
Feb  7 00:05:58 tx2-shiyunxing edgecore[7420]: E0207 00:05:58.566385    7420 common.go:100] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Feb  7 00:06:00 tx2-shiyunxing dockerd[6301]: time="2021-02-07T00:06:00.304551648+08:00" level=warning msg="Error getting v2 registry: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

**Comment by mengmaren** [comment]
[
[2021-02.zip](https://github.com/kubeedge/kubeedge/files/5950398/2021-02.zip)

](url)

**Comment by mengmaren** [comment]
Upload the edge node system log.

**Comment by kubeeeee** [comment]
Thanks for pointing out, will take a look later.

**Comment by fisherxu** [comment]
Will have a look later

**Comment by fisherxu** [comment]
> connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused

this is because the mqtt server haven't run in the edgenode, will you use the mqtt?

**Comment by mengmaren** [comment]
We don't use the MQTT, so you can ignore that error message. 
Please take care about the following errors:
Feb 7 00:05:57 tx2-shiyunxing edgecore[7420]: E0207 00:05:57.969426 7420 process.go:77] failed to send message to sync keep channel
Feb 7 00:05:57 tx2-shiyunxing edgecore[7420]: E0207 00:05:57.969478 7420 process.go:126] failed to dispatch message, discard: failed to send message to sync keep channel

**Comment by shiwenjuan123** [comment]
@fisherxu 
What causes this problem? When can it be repaired?

**Comment by fisherxu** [comment]
@shiwenjuan123  Please take a look of #2614

**Comment by hackers365** [comment]
> 
> 
> @shiwenjuan123 Please take a look of #2614

Can you explain a little bit the cause of this problem?
