### ISSUE TITLE
Support for armv6 / arm6hf (Raspberry Pi 1 / Raspberry Pi Zero)

### ISSUE THREAD

**Issue by haukepribnow** [kubeedge/kubeedge#2571]
_(I'm using a combination of the Bug Report and the Enhancement Request template for this issue.)_

**What happened**:
When launching `edgecore` on a Raspberry Pi 1 B, it fails with message `Illegal instruction` and exit code `132`.

**What you expected to happen / What would you like to be added/modified**:
`edgecore` should work on the armv6 architecture and preferrably also support VFP in armv6 architectures ("armv6hf") like provided by the Raspberry Pi 1 and Raspberry Pi Zero.

**How to reproduce it (as minimally and precisely as possible)**:
1. From `kubeedge-v1.5.0-linux-arm.tar.gz`, upload `kubeedge-v1.5.0-linux-arm/edge/edgecore` to a Raspberry Pi 1 B.
2. `chmod +x edgecore` (if the file mode gets lost during extraction or upload).
3. `./edgecore` (currently prints `Illegal instruction`)
4. `echo $?` (currently prints `132`, i.e. exit because of signal 4 / SIGILL)

**Anything else we need to know? / Why is this needed**:
Even though the Raspberry PI 1 may somewhat have started to age, the release of the Raspberry Pi Zero has "revitalized" the armv6hf architecture. Consequently, this architecture remains an important one. (See https://www.engadget.com/raspberry-pi-ventilators-covid-19-163729140.html as an example for this importance: Ventilator manufacturers have started adding the Raspberry PI Zero to their products so that they can react to the increased ventilator demand from the healthcare industry because of COVID-19.)

**Environment**:
Kubernetes version (use `kubectl version`): _[not relevant to this ticket]_

KubeEdge version (e.g. `cloudcore --version` and `edgecore --version`): I downloaded the v1.5.0 release.

Cloud nodes Environment: _[not relevant to this ticket]_

<details><summary>Edge nodes Environment:</summary>

Hardware configuration (`lscpu`):
```
Architecture:          armv6l
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Model:                 7
Model name:            ARMv6-compatible processor rev 7 (v6l)
CPU max MHz:           700.0000
CPU min MHz:           700.0000
BogoMIPS:              697.95
Flags:                 half thumb fastmult vfp edsp java tls
```

OS (`cat /etc/os-release`):
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

Kernel  `uname -a`):
```
Linux raspberrypi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux
```

Go version (`go version`): 
```
-bash: go: command not found
```
_(Note: I don't have go installed on my Raspberry Pi because I don't want to compile anything on it. I only want to run `edgecore` there.)_
  </details>

**Comment by haukepribnow** [comment]
And to add to this: I've seen PR #992 that - from the looks of it - would add a release script that builds for armv6 . However, the PR was never merged.

**Comment by jmguzik** [comment]
@haukepribnow  I am not a member nor maintainer, so while you wait for a proper response from a project member, I can only say that it seems arm32 architecture is not supported on master as well as by releases at the moment. These binaries are for arm64, that's why you get such error.
You can still try to make use of it by cloning the branch from PR you mentioned or cherry-picking this change to the current master. Maybe it will work.
I do not know why there is an issue with merging this one.
