### ISSUE TITLE
In cloud,  edge's rules is none, but edgecore is running in edge.

### ISSUE THREAD

**Issue by Xxllj834738992** [kubeedge/kubeedge#2576]
**What happened and what you expected to happen**:
In cloud,  edge's rules is none, but edgecore is running in edge.
It is expected that edge's rules is agent and edge
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15.2
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.5.0
![微信截图_20210218233837](https://user-images.githubusercontent.com/50351971/108381090-7027da00-7242-11eb-824d-c89212ac5294.png)
![微信截图_20210218233926](https://user-images.githubusercontent.com/50351971/108381205-8a61b800-7242-11eb-999d-17b25cb771e1.png)

**Comment by fisherxu** [comment]
> In cloud, edge's rules is none, but edgecore is running in edge.
It is expected that edge's rules is agent and edge

Looks like you had installed kubelet in the edge node, that's wrong. You only need to install edgecore to the edgenode. @Xxllj834738992

**Comment by Xxllj834738992** [comment]
> > In cloud, edge's rules is none, but edgecore is running in edge.
> > It is expected that edge's rules is agent and edge
> 
> Looks like you had installed kubelet in the edge node, that's wrong. You only need to install edgecore to the edgenode. @Xxllj834738992

Thanks, I'll try it.
