### ISSUE TITLE
panic: x509: cannot parse IP address of length 0

### ISSUE THREAD

**Issue by markbgrdt** [kubeedge/kubeedge#2577]
**What happened**:
I installed Kubeedge on my cloud node by using keadm init --advertise-address=1.2.3.4 (my public ip). The first attempt failed with "Error: failed to run 'sh -c chmod +x /usr/local/bin/cloudcore' because of error : exit status 1". However, after running the installer a second time the installation was successful and keadm stated that cloudcore is running. /usr/local/bin/cloudcore is there.

I took a quick look into the logs at /var/log/kubeedge/cloudcore.log and saw that there was a panic "F0219 09:08:54.781302   37895 server.go:56] x509: cannot parse IP address of length 0 panic: x509: cannot parse IP address of length 0"

Cloudcore is not running (checked by ps -aux), ports are not open (just to be sure, checked by netstat -tpln).  

**What you expected to happen**:
I expected a running cloudcore and ports 10000 and 10002 open.

**How to reproduce it (as minimally and precisely as possible)**:
Grab a fresh installation of Ubuntu 20.04 LTS, install Kubernetes 1.19, download keadm-v1.5.0-linux-amd64.tar.gz, extract it and run keadm init --advertise-address=1.2.3.4 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): KubeEdge v1.5.0
- <details><summary>Cloud nodes Environment:</summary>
There is only a untainted master node running for test purposes with Calico installed.

  - Hardware configuration (e.g. `lscpu`): 
  
  Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   42 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6278C CPU @ 2.60GHz
Stepping:                        7
CPU MHz:                         2600.000
BogoMIPS:                        5200.00
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        1 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology 
                                 nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3
                                 dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushop
                                 t clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni md_clear flush_l1d arch_capabilities

  - OS (e.g. `cat /etc/os-release`): VERSION="20.04.1 LTS (Focal Fossa)"
  - Kernel (e.g. `uname -a`): Linux edge-test 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>
No installed yet as cloudcore is not runnign.
  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`): go version go1.13.8 linux/amd64
  - Others:

  </details>

**Comment by hackers365** [comment]
try

> kubectl delete secret casecret cloudcoresecret -n kubeedge

**Comment by mhh12121** [comment]
@hackers365  Damn! I was stuck at this shit half a day! Thank you very much! But I wonder why this works ?
And now I use helm to install cloudcore v1.11, i still met this issue :sweat:
