### ISSUE TITLE
There is no edge when kubectl get node

### ISSUE THREAD

**Issue by Xxllj834738992** [kubeedge/kubeedge#2579]
**What happened and what you expected to happen**:
There is no edge when kubectl get node, but both cloudcore and edgecore are runing. 
It is expected that edge should  be added in when kubectl get node.
![微信截图_20210220153942](https://user-images.githubusercontent.com/50351971/108588026-01599680-7392-11eb-97a6-a903f3d6c841.png)
![微信截图_20210220153956](https://user-images.githubusercontent.com/50351971/108588030-04ed1d80-7392-11eb-8c94-74e5854575fe.png)
![微信截图_20210220153834](https://user-images.githubusercontent.com/50351971/108588033-0880a480-7392-11eb-8b90-52350bc5f425.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15.2
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.15.2

**Comment by Abirdcfly** [comment]
may be you should add some log in you issue,.

**Comment by Xxllj834738992** [comment]
Here is edgecore's log.
2月 25 10:47:49 edge edgecore[26011]: table `device_attr` already exists, skip
2月 25 10:47:49 edge edgecore[26011]: table `device_twin` already exists, skip
2月 25 10:47:49 edge edgecore[26011]: table `meta` already exists, skip
2月 25 10:47:49 edge edgecore[26011]: E0225 10:47:49.319361   26011 csi_plugin.go:226] kubernetes.io/csi: CSIDriverLister not found on KubeletVolumeHost
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.319462   26011 log.go:181] DEBUG: Installed strategy plugin: [RoundRobin].
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.319483   26011 log.go:181] DEBUG: ConfigurationFactory Initiated
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.319492   26011 log.go:181] INFO: Configuration files: []
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.319571   26011 log.go:181] WARN: empty configurtion from [FileSource]
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.319581   26011 log.go:181] INFO: invoke dynamic handler:FileSource
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.319600   26011 log.go:181] INFO: archaius init success
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.319720   26011 log.go:181] INFO: create new watcher
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.319991   26011 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.320117   26011 client.go:87] parsed scheme: "unix"
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.320128   26011 client.go:87] scheme "unix" not registered, fallback to default scheme
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.322132   26011 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
2月 25 10:47:49 edge edgecore[26011]: I0225 10:47:49.322147   26011 clientconn.go:948] ClientConn switching balancer to "pick_first"
2月 25 10:47:49 edge edgecore[26011]: F0225 10:47:49.322625   26011 certmanager.go:91] Error: failed to get CA certificate, err: Get "https://192.168.3.145:10002/ca.crt": dial tcp 192.168.3.145:10002: connect: connection refused
2月 25 10:47:49 edge edgecore[26011]: goroutine 94 [running]:
2月 25 10:47:49 edge edgecore[26011]: k8s.io/klog.stacks(0xc000623300, 0xc0001341e0, 0xbf, 0x1cf)
2月 25 10:47:49 edge edgecore[26011]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:883 +0xb9
2月 25 10:47:49 edge edgecore[26011]: k8s.io/klog.(*loggingT).output(0x4b36bc0, 0xc000000003, 0xc00036e070, 0x482b13a, 0xe, 0x5b, 0x0)
2月 25 10:47:49 edge edgecore[26011]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:834 +0x35f
2月 25 10:47:49 edge edgecore[26011]: k8s.io/klog.(*loggingT).printf(0x4b36bc0, 0x3, 0x346c1b6, 0x9, 0xc000a93e10, 0x1, 0x1)
2月 25 10:47:49 edge edgecore[26011]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:715 +0x153
2月 25 10:47:49 edge edgecore[26011]: k8s.io/klog.Fatalf(...)
2月 25 10:47:49 edge edgecore[26011]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:1284
2月 25 10:47:49 edge edgecore[26011]: github.com/kubeedge/kubeedge/edge/pkg/edgehub/certificate.(*CertManager).Start(0xc0001f24e0)
2月 25 10:47:49 edge edgecore[26011]: /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/certificate/certmanager.go:91 +0xd5
2月 25 10:47:49 edge edgecore[26011]: github.com/kubeedge/kubeedge/edge/pkg/edgehub.(*EdgeHub).Start(0xc0001f24e0)
2月 25 10:47:49 edge edgecore[26011]: /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/edgehub.go:68 +0x425
2月 25 10:47:49 edge edgecore[26011]: created by github.com/kubeedge/beehive/pkg/core.StartModules
2月 25 10:47:49 edge edgecore[26011]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:23 +0x15a
2月 25 10:47:49 edge systemd[1]: edgecore.service: main process exited, code=exited, status=255/n/a
2月 25 10:47:49 edge systemd[1]: Unit edgecore.service entered failed state.
2月 25 10:47:49 edge systemd[1]: edgecore.service failed.
2月 25 10:47:59 edge systemd[1]: edgecore.service holdoff time over, scheduling restart.
2月 25 10:47:59 edge systemd[1]: Stopped edgecore.service.
2月 25 10:47:59 edge systemd[1]: Started edgecore.service.
2月 25 10:47:59 edge edgecore[26062]: INFO: Install client plugin, protocol: rest
2月 25 10:47:59 edge edgecore[26062]: INFO: Installed service discovery plugin: edge
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.808551   26062 client.go:77] Connecting to docker on unix:///var/run/docker.sock
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.808610   26062 client.go:94] Start docker client with request timeout=0s
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.811303   26062 docker_service.go:241] Hairpin mode set to "hairpin-veth"
2月 25 10:47:59 edge edgecore[26062]: W0225 10:47:59.811419   26062 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
2月 25 10:47:59 edge edgecore[26062]: W0225 10:47:59.817831   26062 hostport_manager.go:71] The binary conntrack is not installed, this can cause failures in network connection cleanup.
2月 25 10:47:59 edge edgecore[26062]: W0225 10:47:59.817854   26062 hostport_manager.go:71] The binary conntrack is not installed, this can cause failures in network connection cleanup.
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.820799   26062 docker_service.go:256] Docker cri networking managed by kubernetes.io/no-op
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.847618   26062 docker_service.go:261] Docker Info: &{ID:FVAC:LSH6:IS7P:ODSD:D7Z3:UOJB:7VLO:BPOW:A7BW:LPLR:IWJG:D2VV Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Im
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.847717   26062 docker_service.go:274] Setting cgroupDriver to systemd
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.864416   26062 remote_runtime.go:59] parsed scheme: ""
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.864449   26062 remote_runtime.go:59] scheme "" not registered, fallback to default scheme
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.864482   26062 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/dockershim.sock  <nil> 0 <nil>}] <nil> <nil>}
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.864493   26062 clientconn.go:948] ClientConn switching balancer to "pick_first"
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.864562   26062 remote_image.go:50] parsed scheme: ""
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.864573   26062 remote_image.go:50] scheme "" not registered, fallback to default scheme
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.864584   26062 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/dockershim.sock  <nil> 0 <nil>}] <nil> <nil>}
2月 25 10:47:59 edge edgecore[26062]: I0225 10:47:59.864589   26062 clientconn.go:948] ClientConn switching balancer to "pick_first"
2月 25 10:48:04 edge edgecore[26062]: W0225 10:48:04.877715   26062 nvidia.go:61] NVIDIA GPU metrics will not be available: no NVIDIA devices found
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.884515   26062 kuberuntime_manager.go:214] Container runtime docker initialized, version: 18.09.7, apiVersion: 1.39.0
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.911481   26062 container_manager_linux.go:276] container manager verified user specified cgroup-root exists: []
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.911521   26062 container_manager_linux.go:281] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker Cgr
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.911653   26062 topology_manager.go:126] [topologymanager] Creating topology manager with none policy
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.911761   26062 container_manager_linux.go:311] [topologymanager] Initializing Topology Manager with none policy
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.911775   26062 container_manager_linux.go:316] Creating device plugin manager: false
2月 25 10:48:04 edge edgecore[26062]: table `device` already exists, skip
2月 25 10:48:04 edge edgecore[26062]: table `device_attr` already exists, skip
2月 25 10:48:04 edge edgecore[26062]: table `device_twin` already exists, skip
2月 25 10:48:04 edge edgecore[26062]: table `meta` already exists, skip
2月 25 10:48:04 edge edgecore[26062]: E0225 10:48:04.914840   26062 csi_plugin.go:226] kubernetes.io/csi: CSIDriverLister not found on KubeletVolumeHost
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.914944   26062 log.go:181] DEBUG: Installed strategy plugin: [RoundRobin].
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.914969   26062 log.go:181] DEBUG: ConfigurationFactory Initiated
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.914980   26062 log.go:181] INFO: Configuration files: []
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.915198   26062 log.go:181] WARN: empty configurtion from [FileSource]
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.915213   26062 log.go:181] INFO: invoke dynamic handler:FileSource
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.915236   26062 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.915242   26062 log.go:181] INFO: archaius init success
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.915383   26062 client.go:87] parsed scheme: "unix"
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.915395   26062 client.go:87] scheme "unix" not registered, fallback to default scheme
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.915464   26062 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.915475   26062 clientconn.go:948] ClientConn switching balancer to "pick_first"
2月 25 10:48:04 edge edgecore[26062]: I0225 10:48:04.915492   26062 log.go:181] INFO: create new watcher
2月 25 10:48:04 edge edgecore[26062]: F0225 10:48:04.916217   26062 certmanager.go:91] Error: failed to get CA certificate, err: Get "https://192.168.3.145:10002/ca.crt": dial tcp 192.168.3.145:10002: connect: connection refused
2月 25 10:48:04 edge edgecore[26062]: goroutine 63 [running]:
2月 25 10:48:04 edge edgecore[26062]: k8s.io/klog.stacks(0xc000990c00, 0xc000a4a000, 0xbf, 0xc6)
2月 25 10:48:04 edge edgecore[26062]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:883 +0xb9
2月 25 10:48:04 edge edgecore[26062]: k8s.io/klog.(*loggingT).output(0x4b36bc0, 0xc000000003, 0xc000794000, 0x482b13a, 0xe, 0x5b, 0x0)
2月 25 10:48:04 edge edgecore[26062]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:834 +0x35f
2月 25 10:48:04 edge edgecore[26062]: k8s.io/klog.(*loggingT).printf(0x4b36bc0, 0x3, 0x346c1b6, 0x9, 0xc000cf1e10, 0x1, 0x1)
2月 25 10:48:04 edge edgecore[26062]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:715 +0x153
2月 25 10:48:04 edge systemd[1]: edgecore.service: main process exited, code=exited, status=255/n/a
2月 25 10:48:04 edge edgecore[26062]: k8s.io/klog.Fatalf(...)
2月 25 10:48:04 edge edgecore[26062]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:1284
2月 25 10:48:04 edge edgecore[26062]: github.com/kubeedge/kubeedge/edge/pkg/edgehub/certificate.(*CertManager).Start(0xc000ad2d00)
2月 25 10:48:04 edge edgecore[26062]: /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/certificate/certmanager.go:91 +0xd5
2月 25 10:48:04 edge edgecore[26062]: github.com/kubeedge/kubeedge/edge/pkg/edgehub.(*EdgeHub).Start(0xc000ad2d00)
2月 25 10:48:04 edge edgecore[26062]: /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/edgehub.go:68 +0x425
2月 25 10:48:04 edge edgecore[26062]: created by github.com/kubeedge/beehive/pkg/core.StartModules
2月 25 10:48:04 edge edgecore[26062]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:23 +0x15a
2月 25 10:48:04 edge systemd[1]: Unit edgecore.service entered failed state.
2月 25 10:48:04 edge systemd[1]: edgecore.service failed.

**Comment by Xxllj834738992** [comment]
Here is kubelet's log in 10.
[root@cloud kubelet.service.d]#  journalctl -u kubelet -n 10
-- Logs begin at 六 2021-02-20 22:01:42 CST, end at 四 2021-02-25 10:48:15 CST. --
2月 25 10:48:01 cloud kubelet[824]: E0225 10:48:01.354838     824 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.
2月 25 10:48:01 cloud kubelet[824]: E0225 10:48:01.355032     824 pod_workers.go:190] Error syncing pod cb34274a-05d6-42da-8cc6-c0ba52e046de ("coredns-bccdc95cf-fllp2_kube-system(cb
2月 25 10:48:05 cloud kubelet[824]: E0225 10:48:05.356980     824 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.
2月 25 10:48:06 cloud kubelet[824]: E0225 10:48:06.195292     824 summary_sys_containers.go:47] Failed to get system container stats for "/system.slice/docker.service": failed to ge
2月 25 10:48:11 cloud kubelet[824]: E0225 10:48:11.354304     824 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.
2月 25 10:48:11 cloud kubelet[824]: E0225 10:48:11.354662     824 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.
2月 25 10:48:11 cloud kubelet[824]: E0225 10:48:11.354784     824 pod_workers.go:190] Error syncing pod a9b95909-9b11-42fa-8745-fba403aa581a ("coredns-bccdc95cf-qrbsm_kube-system(a9
2月 25 10:48:15 cloud kubelet[824]: E0225 10:48:15.354407     824 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.
2月 25 10:48:15 cloud kubelet[824]: E0225 10:48:15.354442     824 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.
2月 25 10:48:15 cloud kubelet[824]: E0225 10:48:15.354553     824 pod_workers.go:190] Error syncing pod cb34274a-05d6-42da-8cc6-c0ba52e046de ("coredns-bccdc95cf-fllp2_kube-system(cb
lines 1-11/11 (END)

**Comment by Xxllj834738992** [comment]
> may be you should add some log in you issue,.

Thanks. Please check it. I hope you can help. It have made me upset for a long time.

**Comment by Abirdcfly** [comment]
> 2 月 25 10:48:04 edge edgecore [26062]: F0225 10:48:04.916217 26062 certmanager.go:91] Error: failed to get CA certificate, err: Get "https://192.168.3.145:10002/ca.crt": dial tcp 192.168.3.145:10002: connect: connection refused

the log show edgecore cant connect to cloudcore.

**Comment by Xxllj834738992** [comment]
> > 2 月 25 10:48:04 edge edgecore [26062]: F0225 10:48:04.916217 26062 certmanager.go:91] Error: failed to get CA certificate, err: Get "https://192.168.3.145:10002/ca.crt": dial tcp 192.168.3.145:10002: connect: connection refused
> 
> the log show edgecore cant connect to cloudcore.

Yes, but I don't know how to fix it. I have closed the firewall. But it still be "connect refuse".

**Comment by Abirdcfly** [comment]
Just `curl -v -k https://192.168.3.145:10002/ca.crt` in you edgecore node， if you can get  some result. may be error occurs in edge. otherwise. cloudcore is not running correctly.

**Comment by Xxllj834738992** [comment]
> Just `curl -v -k https://192.168.3.145:10002/ca.crt` in you edgecore node， if you can get some result. may be error occurs in edge. otherwise. cloudcore is not running correctly.

Thank you. I'll try it.

**Comment by sunkai-XDD** [comment]
@Xxllj834738992  how about your question？，and have you solved it？

**Comment by KyanWang** [comment]
@Xxllj834738992  I have the same issue. How did you fix it?

**Comment by Xxllj834738992** [comment]
> @Xxllj834738992 I have the same issue. How did you fix it?

Reinstall the system....

**Comment by Watle-fan** [comment]
> > @Xxllj834738992 I have the same issue. How did you fix it?
> 
> Reinstall the system....


May I ask if you have also installed the following version after reinstalling the system?

Kubernetes version (use kubectl version):1.15.2
KubeEdge version(e.g. cloudcore --version and edgecore --version):1.15.2
