### ISSUE TITLE
Failed to get CA certificate

### ISSUE THREAD

**Issue by Xxllj834738992** [kubeedge/kubeedge#2580]
**What happened and what you expected to happen**:
In the edge node log，it shows：
Failed to get CA certificate, err: Get "https://192.168.3.145:10002/ca.crt": dial tcp 192.168.3.145:10002: connect: connection refused.
And in the kubelet log, it shows:
2月 20 23:21:22 cloud kubelet[824]: E0220 23:21:22.607334     824 summary_sys_containers.go:47] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.5.2
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.5.0

**Comment by hackers365** [comment]
"dial tcp 192.168.3.145:10002: connect: connection refused"

Check whether the cloudcore instance is alive or  firewall opens port 10002

**Comment by KyanWang** [comment]
@Xxllj834738992 how did you fixed the issue?  Thank you

**Comment by Xxllj834738992** [comment]
> @Xxllj834738992 how did you fixed the issue? Thank you

Reinstall the system......
