### ISSUE TITLE
edge_core report error even the master node report edge node ready

### ISSUE THREAD

**Issue by leeruibin** [kubeedge/kubeedge#259]
**Which jobs are failing**:
Run edge_core, but get the error as follow:
**Which test(s) are failing**:

I meet another problem, i run the command "kubectl apply -f $GOPATH/src/github.com/kubeedge/kubeedge/build/deployment.yaml" and get the error "DockerManager EnsureImageExists failed, msg:Back-off pulling image "k8s.gcr.io/kube-proxy:v1.13.2", ImagePullBackOff
"
"edged/edged.go:485 worker [0] handle pod addition item [kube-proxy-8rqhx] failed: consume added pod [kube-proxy-8rqhx] ensure image exist failed, ImagePullBackOff, re-add to queue" ""
Also " edged/edged.go:545 Unable to mount volumes for pod "kube-proxy-g6gcx_kube-system(254be5dc-49f6-11e9-b7ae-7c2a31c2de13)": timeout expired waiting for volumes to attach or mount for pod "kube-system"/"kube-proxy-g6gcx". list of unmounted volumes=[kube-proxy]. list of unattached volumes=[kube-proxy xtables-lock lib-modules kube-proxy-token-cn5wd]; skipping pod"
" edged/edged.go:485 worker [4] handle pod addition item [kube-proxy-g6gcx] failed: timeout expired waiting for volumes to attach or mount for pod "kube-system"/"kube-proxy-g6gcx". list of unmounted volumes=[kube-proxy]. list of unattached volumes=[kube-proxy xtables-lock lib-modules kube-proxy-token-cn5wd], re-add to queue
"
since the gfw in china so that i can not pull the image kube-proxy directly, i pull another image and change the tag to the k8s.gcr.io/kube-proxy in the local, but it still show this error message..

**Since when has it been failing**:

**Reason for failure**:

**Anything else we need to know**:

**Comment by faicker** [comment]
How did this solved?
