### ISSUE TITLE
A query on mosquitto

### ISSUE THREAD

**Issue by AlexanderChiyun** [kubeedge/kubeedge#2596]
As far as I know, the current edgecore has built-in mosquitto by default. Will it support decoupling or other brokers? Tks

**Comment by fisherxu** [comment]
> As far as I know, the current edgecore has built-in mosquitto by default. Will it support decoupling or other brokers? Tks

Now the mqtt is the default  broker that devices access to edgecore. With the built-in mqtt that users can use it directly without installing.

Looking forward to the ideas that support other brokers. :)
