### ISSUE TITLE
If edge core didn't handle pod delete event from cloud, pod remains with status Terminating

### ISSUE THREAD

**Issue by tedli** [kubeedge/kubeedge#260]
**What happened**:

Pod (running at edge) remain with status Terminating.

![image](https://user-images.githubusercontent.com/3324663/54588464-0a32e680-4a5e-11e9-899f-6da4c0f02e2e.png)

For temporary go over this problem, I have to delete meta entry of the pod in edge.db and delete the pod object in etcd manully.

**What you expected to happen**:

Pod should be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy pod to edge, after pod up and running, kill edge core, delete the pod, again start the edge core.

Then the pod we intend to delete get never deleted, ramains with status Terminating.

**Anything else we need to know?**:

The downstream controller (response for trigger event to edge side) just try to notice edge once, and if failed did nothing but log an error.

https://github.com/kubeedge/kubeedge/blob/6878d86b9ec33ca716933575b93ef70663504ba5/cloud/edgecontroller/pkg/controller/controller/downstream.go#L51-L67

**Environment**:
- KubeEdge version: v0.2
- Hardware configuration: irrelevant
- OS (e.g. from /etc/os-release): irrelevant
- Kernel (e.g. `uname -a`): irrelevant
- Others: irrelevant

**Comment by sids-b** [comment]
cc @Baoqiang-Zhang

**Comment by Baoqiang-Zhang** [comment]
There are no message cache in edgecontroller&cloudhub right now, maybe we can add cache to send message reliable.

**Comment by tedli** [comment]
I don't think cache at controller side is a good idea. If controller be killed or downed for some reasons, the cache also gone.

I think we may group pods by nodes, and sync this pods to each node, and edge side could determine which pod should exist which should be deleted.

**Comment by tedli** [comment]
I found that metamanager periodically sync pod status from cloud. But only unmarshaling message content to `interface{}`, didn't check fields of the pod status object (the interface{}).

So I think we can add some conditions here to work out this case:

https://github.com/kubeedge/kubeedge/blob/6878d86b9ec33ca716933575b93ef70663504ba5/edge/pkg/metamanager/msg_processor.go#L328-L339

If no disagreements, I'm glad to fix this issue.

**Comment by m1093782566** [comment]
@tedli 

I am happy to see the PR.

**Comment by sids-b** [comment]
@tedli Please go ahead and fix this issue :) We are very open to contributions from community.

**Comment by tedli** [comment]
I'm working on this issue, I plan to handle this by adding some condition in cloud controller, at where controller handles pod statuses syncing from meta manager, then cloud side could list pods using k8s client, and filter out which pod should be delete and still exist at edge side, by filtering out these pods, cloud can trigger delete event again, to let edge delete the pod.

But, it depends on #268, the #268 should be fixed first.

**Comment by CindyXing** [comment]
I echo what Tedli called out about the issue by adding a cache. 
@tedli, please go ahead and share the PR. I commented #268. 

Yes, we had thought about "I think we may group pods by nodes, and sync this pods to each node, and edge side could determine which pod should exist which should be deleted.". Would love to hear more of your thoughts.

**Comment by tedli** [comment]
Whether to implement a cache or other mechanisms to solve this issue, a way of event ACK is needed. Also because of all the actions were taken in an async way, a situation that edge side is handling the event just didn't response to cloud in time, the cloud may think that edge side didn't get the event handled at all, so cloud side may resend the event. If so, should edge just ignore the duplicated event or response something to cloud to indicate event is duplicated (the previous event the not duplicated one should response in the normal way)

**Comment by CindyXing** [comment]
Considering edge can connect/disconnect, I think we can't (can't easily) prevent duplicate event sent from cloud. Rather we should make sure customers' intention/events are sent reliably from cloud to edge. 

We probably need to evaluate what kinds of events sent from cloud to edge; whether there is any side effect for edgecore to process the event twice. 

So far we are sending deployment actions from cloud to edge. It seems benign for edgecore to process the event twice. Let me know if you think differently.

**Comment by rohitsardesai83** [comment]
@tedli , what can we do about this issue ?

**Comment by tedli** [comment]
@rohitsardesai83 
My solution of syncing all pods every time edge connect to cloud indeed lacks of consideration, and according to the discussion above, I agree with introducing cache mechanism. However by doing so things turns complicated. I think it should be considered at  architecture level of edge-cloud communication. It's a big topic at code level. (AFAIK edgecontroller cannot run with replicas to achieve HA for now on)
CC @shouhong @nkwangleiGIT

**Comment by sids-b** [comment]
@tedli , I think this issue can be fixed with #725 ?

**Comment by tedli** [comment]
Glad to know the progress about this. I will close this issue, and #725 take this over.
