### ISSUE TITLE
v1.6 cloudcore logs "failed to get obj(gvr:/, Resource=endpoints,namespace:kube-system,name:kube-scheduler), the server could not find the requested resource"

### ISSUE THREAD

**Issue by hackers365** [kubeedge/kubeedge#2602]
**What happened**:
v1.6
cloudcore logs

> E0304 17:13:54.797595 3429407 objectsync.go:38] failed to get obj(gvr:/, Resource=endpoints,namespace:kube-system,name:kube-scheduler), the server could not find the requested resource
E0304 17:13:54.812465 3429407 objectsync.go:38] failed to get obj(gvr:/, Resource=service,namespace:monitoring,name:prometheus), the server could not find the requested resource
E0304 17:13:54.814542 3429407 objectsync.go:38] failed to get obj(gvr:/, Resource=endpoints,namespace:kube-system,name:kube-controller-manager), the server could not find the requested resource
E0304 17:13:54.832725 3429407 objectsync.go:38] failed to get obj(gvr:/, Resource=configmap,namespace:default,name:openresty-upgrade-configmap), the server could not find the requested resource
E0304 17:13:54.847473 3429407 objectsync.go:38] failed to get obj(gvr:/, Resource=endpoints,namespace:monitoring,name:prometheus), the server could not find the requested resource
E0304 17:13:54.852698 3429407 objectsync.go:38] failed to get obj(gvr:/, Resource=endpoints,namespace:kube-system,name:kube-scheduler), the server could not find the requested resource
E0304 17:13:54.855790 3429407 objectsync.go:38] failed to get obj(gvr:/, Resource=endpoints,namespace:kube-system,name:kube-controller-manager), the server could not find the requested resource
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by majoyz** [comment]
Same problem, used cloudcore image.

**Comment by bluzioo** [comment]
I delete all objectsyncs.reliablesyncs.kubeedge.io and restart cloudcore. Then it runs without the error log. I don't figure out that the GVR disappear in the objectsyncs resources after upgrade from v1.5 to v1.6.
