### ISSUE TITLE
Does KubeEdge support other vendors' Device Plugin ?

### ISSUE THREAD

**Issue by cist** [kubeedge/kubeedge#2612]
**What happened and what you expected to happen**:

I used other device plugin like Ascend devcie plugin in Huawei, I can view and allocate devices in the cloud, but I don't see Edgecore calling the allocate function of the device-plugin. Does KubeEdge support other vendors' Device Plugin like K8S ?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- 1.17.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- 1.2.1

**Comment by cist** [comment]
hi, I find in realse1.6 have a change [pr 2317](https://github.com/kubeedge/kubeedge/pull/2317/files) , but I do not find UpdatePluginResources in edged.go except addPod function. So if i shoud add  UpdatePluginResources  in function consumePodAddition ? thanks. If I do this, I will be able to call the List&Watch and allocate functions of the other device plugins and mount the devices correctly.

**Comment by threestoneliu** [comment]
[pr 2317](https://github.com/kubeedge/kubeedge/pull/2317/files) just make container can use device. It's a part of to use device plugin. [pr 2353](https://github.com/kubeedge/kubeedge/pull/2353) will enable allocateResourceAdmitHandler which will call deviceplugin rpc method. But pr 2353 will cause the edgecore run unstable. If you are insterested , you can create a new pr to fix this problem.

**Comment by cist** [comment]
> [pr 2317](https://github.com/kubeedge/kubeedge/pull/2317/files) just make container can use device. It's a part of to use device plugin. [pr 2353](https://github.com/kubeedge/kubeedge/pull/2353) will enable allocateResourceAdmitHandler which will call deviceplugin rpc method. But pr 2353 will cause the edgecore run unstable. If you are insterested , you can create a new pr to add the new feature.

Thank you very much for your answer. I am very interested in this problem. But I'm a little confused. Why does this change cause the edgecore to be unstable? Thank you.
