### ISSUE TITLE
keadm join | edgecore binary location and default config location

### ISSUE THREAD

**Issue by bitvijays** [kubeedge/kubeedge#2618]
**What happened**:
- keadm installs the `edgecore` binary in `/etc/kubeedge/` folder. It should also copy the `edgecore` binary in `/usr/local/bin/`
- `edgecore` by default doesn't take the configuration file location as `/etc/kubeedge/config/edgecore.yaml`. When edgecore is executed using `./edgecore` or `service edgecore start`, it fails as the binary doesn't take the location of config file by default.

**What you expected to happen**:

- edgecore binary to be copied to `/usr/local/bin`
- edgecore should by default take the location of config file as  `/etc/kubeedge/config/edgecore.yaml`

**How to reproduce it (as minimally and precisely as possible)**:

Join a worker node using keadm

**Anything else we need to know?**:

**Environment**:
KubeEdge v1.6

**Comment by fisherxu** [comment]
Thanks for pointing out, and we already have a merged PR to fix this issue, ref: #2603 , and a patch release will be out this week.

**Comment by bitvijays** [comment]
Hey @fisherxu Thank you :). That sounds great!

Quick Question, Have we also fixed the config issue too?:

- edgecore should by default take the location of config file as `/etc/kubeedge/config/edgecore.yaml`

Asking, because currently the `edgecore.service` files contains

```
[Unit]
Description=edgecore.service

[Service]
Type=simple
ExecStart=/usr/local/bin/edgecore
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

and running `service edgecore start` fails as it doesn't take the config file location by default.

The other way to fix it is to change the `edgecore.service` and include
```
ExecStart=/usr/local/bin/edgecore --config /etc/kubeedge/config/edgecore.yaml
```

**Comment by swartz-k** [comment]
edgecore default config path is `/etc/kubeedge/config/edgecore.yaml`
check that by `edgecore --help`

**Comment by bitvijays** [comment]
@swartz-k Hope you are doing well. I am aware that's the default path of config file. I wanted to say

When we execute `./edgecore` does it automatically takes the config file `/etc/kubeedge/config/edgecore.yaml` or we have to execute the edgecore like `./edgecore --config /etc/kubeedge/config/edgecore.yaml`

We tried running edgecore like `./edgecore` and it fails, we had to run it like `./edgecore --config /etc/kubeedge/config/edgecore.yaml`
