### ISSUE TITLE
Kubeedge namespace was stuck in terminating when running keadm reset

### ISSUE THREAD

**Issue by JackZxj** [kubeedge/kubeedge#2619]
**What happened**:
Kubeedge namespace was stuck in terminating when running keadm reset

**What you expected to happen**:
Delete namespace `kubeedge` when running keadm reset

**How to reproduce it (as minimally and precisely as possible)**:
I don't know exactly.  I just run `keadm reset`

**Anything else we need to know?**:
I am using keadm v1.5.0 and have successfully installed kubeedge v1.5.0. Now I want to upgrade to kubeedge 1.6.0, so I run `keadm reset` to reset and then re-install. Since one installation failure, I found that the namespace kubeedge was stuck in the terminated state, so I manually deleted it‘s `finalizers` and then reinstalled it. After that, every time I execute `keadm reset` will find that the namespace kubeedge is terminating and cannot be deleted automatically.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): keadm v1.5.0; cloudcore v1.6.0; edgecore v1.6.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`): x86_64
  - OS (e.g. `cat /etc/os-release`): CentOS Linux release 7.6.1810 (Core)
  - Kernel (e.g. `uname -a`): 3.10.0-957.el7.x86_64
  - Go version (e.g. `go version`): 
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): v1.6.0
  - Hardware configuration (e.g. `lscpu`): x86_64
  - OS (e.g. `cat /etc/os-release`): CentOS Linux release 7.8.2003 (Core)
  - Kernel (e.g. `uname -a`): 3.10.0-1127.el7.x86_64
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by zc2638** [comment]
`keadm reset 'cleans up the cloud environment. Deleting the `kubeedge` namespace involves deleting the resources under the namespace. You need to wait for the cleanup to complete. The waiting time depends on kubernetes.
@JackZxj

**Comment by JackZxj** [comment]
> `keadm reset` cleans up the cloud environment. Deleting the `kubeedge` namespace involves deleting the resources under the namespace. You need to wait for the cleanup to complete. The waiting time depends on kubernetes.
> @JackZxj

Fine, thanks. I also think it may be the k8s problem, so I am here to confirm it.
