### ISSUE TITLE
test: Edgehub Config Unit test failed

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#263]
**Which jobs are failing**:
https://travis-ci.org/kubeedge/kubeedge/jobs/508213930

**Which test(s) are failing**:
edgehub config unit test.

**Since when has it been failing**:

**Reason for failure**:
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
2019/03/19 04:52:10 DEBUG: watch file error:%!(EXTRA []interface {}=[<nil>])
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData/edge.yaml REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData/edge.yaml": REMOVE], continue
2019/03/19 04:52:10 DEBUG: file event [/tmp/kubeedge/testData REMOVE], operation is %!d(MISSING). reload it.
2019/03/19 04:52:10 WARN: the file change mode: ["/tmp/kubeedge/testData": REMOVE], continue
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x73f8d3]
goroutine 83 [running]:
github.com/kubeedge/kubeedge/vendor/github.com/ServiceComb/go-archaius/sources/file-source.(*watch).startWatchPool(0xc0003729c0)
	/home/travis/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/ServiceComb/go-archaius/sources/file-source/yamlconfigurationsource.go:384 +0x73
created by github.com/kubeedge/kubeedge/vendor/github.com/ServiceComb/go-archaius/sources/file-source.(*yamlConfigurationSource).DynamicConfigHandler
	/home/travis/gopath/src/github.com/kubeedge/kubeedge/vendor/github.com/ServiceComb/go-archaius/sources/file-source/yamlconfigurationsource.go:361 +0x91
FAIL	github.com/kubeedge/kubeedge/edge/pkg/edgehub/config	0.019s
ok  	github.com/kubeedge/kubeedge/edge/pkg/edgehub	(cached)
ok  	github.com/kubeedge/kubeedge/edge/pkg/edgehub/clients	0.006s
ok  	github.com/kubeedge/kubeedge/edge/pkg/edgehub/clients/wsclient	300.117s
ok  	github.com/kubeedge/kubeedge/edge/pkg/eventbus/common/util	0.018s
ok  	github.com/kubeedge/kubeedge/edge/pkg/metamanager/dao	0.007s
ok  	github.com/kubeedge/kubeedge/edge/pkg/metamanager	64.101s

**Anything else we need to know**:

**Comment by rohitsardesai83** [comment]
@sujithsimon22 , can you please check ?

**Comment by sujithsimon22** [comment]
The issue seems to have been caused when the configuration file mentioned within the test is trying to be loaded before the successful creation of the config file. This issue was occurring randomly since, in the normal execution scenario the file is created pretty quickly and hence this panic is not observed. This can be solved by ensuring that the file is loaded only after providing sufficient time for its creation.
