### ISSUE TITLE
edge is notready after restarting master

### ISSUE THREAD

**Issue by fysd** [kubeedge/kubeedge#2632]
**What happened**:
edge is notready after restarting master, journal mention that" Init websocket connection failed dial tcp 192.168.100.235:10000: connect: connection refused"

**What you expected to happen**:
After restarting master,edge should be ready automatically.
**How to reproduce it (as minimally and precisely as possible)**:
When both master and edge are ready ,restart master
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.20.1
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.6.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):raspberry-pi 4b ram:8G
  - OS (e.g. `cat /etc/os-release`):ubuntu20.10
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):1.15.6
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):1.6.0
  - Hardware configuration (e.g. `lscpu`):raspberry-pi 4b ram:2G
  - OS (e.g. `cat /etc/os-release`):ubuntu20.10
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):1.12.5
  - Others:

  </details>

**Comment by gccio** [comment]
`restarting master` means restart the machine?
is the cloudcore still running on 192.168.100.235:10000 after restart your master?

**Comment by fisherxu** [comment]
> `restarting master` means restart the machine?
> is the cloudcore still running on 192.168.100.235:10000 after restart your master?

+1, Please add more descriptions @fysd 

And does it `connection refused` every time restarted, or just occasionally?

**Comment by fysd** [comment]
> `restarting master` means restart the machine?
> is the cloudcore still running on 192.168.100.235:10000 after restart your master?

yes,everytime I restart machine. And I can't find 192.168.100.235:10000 when I use command "netstat -ap", which maybe means that cloudcore are not  running on 192.168.100.235:10000 after restart machine.

**Comment by fysd** [comment]
> > `restarting master` means restart the machine?
> > is the cloudcore still running on 192.168.100.235:10000 after restart your master?
> 
> +1, Please add more descriptions @fysd
> 
> And does it `connection refused` every time restarted, or just occasionally?

yes,maybe something is wrong with cloudcore, but I don't know how to find it.

**Comment by fisherxu** [comment]
> > `restarting master` means restart the machine?
> > is the cloudcore still running on 192.168.100.235:10000 after restart your master?
> 
> yes,everytime I restart machine. And I can't find 192.168.100.235:10000 when I use command "netstat -ap", which maybe means that cloudcore are not running on 192.168.100.235:10000 after restart machine.

Maybe cloudcore isn't started after you restart the machine, please have a check  :)

**Comment by fysd** [comment]
> > > `restarting master` means restart the machine?
> > > is the cloudcore still running on 192.168.100.235:10000 after restart your master?
> > 
> > 
> > yes,everytime I restart machine. And I can't find 192.168.100.235:10000 when I use command "netstat -ap", which maybe means that cloudcore are not running on 192.168.100.235:10000 after restart machine.
> 
> Maybe cloudcore isn't started after you restart the machine, please have a check :)

how to start cloudcore without using keadm init ?

**Comment by gccio** [comment]
try with command `systemctl start cloudcore` to start it.

**Comment by fysd** [comment]
> try with command `systemctl start cloudcore` to start it.

This command isn't work with  " Unit cloudcore.service not found"

**Comment by fysd** [comment]
> > try with command `systemctl start cloudcore` to start it.
> 
> This command isn't work with " Unit cloudcore.service not found"
But cloudcore is in the process

**Comment by fysd** [comment]
> > > `restarting master` means restart the machine?
> > > is the cloudcore still running on 192.168.100.235:10000 after restart your master?
> > 
> > 
> > yes,everytime I restart machine. And I can't find 192.168.100.235:10000 when I use command "netstat -ap", which maybe means that cloudcore are not running on 192.168.100.235:10000 after restart machine.
> 
> Maybe cloudcore isn't started after you restart the machine, please have a check :)

Thank you！ Finally I slove the problem！
I found cloudcore.service is not in /etc/systemd/system, then I created the file ：

[Unit]
Description=cloudcore.service

[Service]
Type=simple
ExecStart=/usr/local/bin/cloudcore            (make sure it's your cloudcore path)        

[Install]
WantedBy=multi-user.target

Then  "systemctl daemon-reload" ,and  "systemctl restart cloudcore.service"  worked.
Last, kubectl get node, 
node1 is ready.
