### ISSUE TITLE
Create data routing mechanism between edge and cloud

### ISSUE THREAD

**Issue by qizha** [kubeedge/kubeedge#265]
**What would you like to be added**:
We need to add the data routing mechanism to control the data flow between edge and cloud. The first step is to support mqtt and rest.

**Why is this needed**:
So that the user can reuse the data channel built by the KubeEdge to do data communication between applications.

**Comment by sids-b** [comment]
I think I can achieve this before v0.3

**Comment by rohitsardesai83** [comment]
the issue mentions support for mqtt and rest . service bus supports rest only right ?
are we targeting mqtt in future release ?

**Comment by naveensriram** [comment]
@qizha , can you specify the scope w.r.t v1.0.0 ie., only we can cover pod to pod communication within same node.
