### ISSUE TITLE
Parse message: 15d32e13-1f6a-4aa9-b654-5811351ca33f resource type with error: unknown resource

### ISSUE THREAD

**Issue by xauthulei** [kubeedge/kubeedge#2665]
**What happened**:
I am try to deploy a pod to the edge cluster, However, its pod is pending 
**What you expected to happen**:
The pod can be run on the node
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):KubeEdge v1.6.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`): x86_64
  - OS (e.g. `cat /etc/os-release`):Ubuntu
  - Kernel (e.g. `uname -a`):Ubuntu 18.04.5
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):KubeEdge v1.6.0
  - Hardware configuration (e.g. `lscpu`): x86_64
  - OS (e.g. `cat /etc/os-release`): Ubuntu
  - Kernel (e.g. `uname -a`):Ubuntu 18.04.5 
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by xauthulei** [comment]
`cloudcore` log: 
0318 22:46:24.072807   22209 upstream.go:88] Dispatch message: 15d32e13-1f6a-4aa9-b654-5811351ca33f
W0318 22:46:24.072912   22209 upstream.go:92] Parse message: 15d32e13-1f6a-4aa9-b654-5811351ca33f resource type with error: unknown resource
How to define what  the `15d32e13-1f6a-4aa9-b654-5811351ca33f ` is ? Thanks

**Comment by fisherxu** [comment]
@xauthulei Thanks for pointint out the issue, this line of log is meaningless, can omit it, and is a known issue and will be fixed soon, ref: #https://github.com/kubeedge/kubeedge/pull/2644

**Comment by xauthulei** [comment]
@fisherxu , Thanks for your supporting. Meanwhile, If my pod status is pending, how to debug what happened here? from the edgecore log ?  Is there any Doc or process ? Thanks

**Comment by ChAnYaNG97** [comment]
same problem here
