### ISSUE TITLE
Refactor model.Message to embed node_id and project_id

### ISSUE THREAD

**Issue by tedli** [kubeedge/kubeedge#267]
**What would you like to be added**:

In struct `model.Message`, no fields to store where the message comes from.

**Why is this needed**:

A module may need to know where this message comes from when handling the message. Like when syncing pod status from edge to cloud, at cloud side, it's better to list all pods on a specific node, in this way, cloud side could diff out which pod should be delete again (on pod delete event, the edge side may not handled the event because network off or power off or other reasons), and then send delete event to edge again.

#260

**Comment by sids-b** [comment]
When cloudhub receives a message, It appends the nodeid to the resource.Please see line 103
https://github.com/kubeedge/kubeedge/blob/master/cloud/edgecontroller/pkg/cloudhub/wsserver/server.go#L87-L117
