### ISSUE TITLE
Multi-tenancy support for KubeEdge

### ISSUE THREAD

**Issue by tedli** [kubeedge/kubeedge#268]
**What happened**:

Pod in different namespaces, didn't get status updated. (through meta syncing operation)

**What you expected to happen**:

Pod status updated properly.

**How to reproduce it (as minimally and precisely as possible)**:

Create pod in different namespaces, only one got updated.

**Anything else we need to know?**:

The meta manager syncs pod status periodically, but use the first namespace found in sqlite db: (line 311)

https://github.com/kubeedge/kubeedge/blob/6878d86b9ec33ca716933575b93ef70663504ba5/edge/pkg/metamanager/msg_processor.go#L296-L314

**Environment**:
- KubeEdge version: v0.2
- Hardware configuration: irrelevant
- OS (e.g. from /etc/os-release): irrelevant
- Kernel (e.g. `uname -a`): irrelevant
- Others: irrelevant

**Comment by CindyXing** [comment]
Yes, we assume a registered edge node belongs to a single namespace (tenant/user/project). Can you share the potential customer scenario which requires multiple namespace at each edge node? Thanks

**Comment by nkwangleiGIT** [comment]
@CindyXing is the 'namespace' you mentioned here is K8S namespace?
in our design, can we deploy multiple pods from different K8S namespaces to a single edge node?

**Comment by CindyXing** [comment]
Yes, k8s namespace is what I meant. Currently we do not support multiple k8s namespace on a single edge node. 

If there is such need, I'd like to understand the customer scenario.

**Comment by nkwangleiGIT** [comment]
@CindyXing thanks for your response.
if we have this limitation, edge node is not a common K8S worker any more :-) and this is the design from the beginning? 
For a simple scenario, we have multiple tenants/projects(K8s namespace) that want to deploy services to edge nodes, then we have to prepare two edge nodes for each tenant?

**Comment by CindyXing** [comment]
@nkwangleiGIT , please don't get me wrong... For the kubeEdge cluster itself, it still supports multi namespaces. The assumption here is that a single edge node won't be shared by different tenant/project. 

From KubeEdge infra. perspective, edgecontroller watches changes against all namesapces and then send down through the cloudhub/edgehub channel. So we can/are supporting multiple namespaces on a single edge node. The above lines of code or related might not be. 

I am validating with you all on the assumption.

**Comment by nkwangleiGIT** [comment]
@CindyXing so the tenant/project here is NOT the same as K8S namespace in KubeEdge? where can I find some docs to introduce tenant/project concept of KubeEdge?

If so, the code above is probably not working as expected...

**Comment by CindyXing** [comment]
@nkwangleiGIT , currently K8s itself is still defining the multi-tenancy story. It is the same situation for KubeEdge. 

K8s uses namespace to differentiate tenant and project. 

Not sure what you mean by not working as expected. Can you help me to understand your points? Which part not working as expected? 

We are assuming one Edge node will belong to the same tenant based on edge/iot customer scenarios. As such, we only support one namespace. 

Fundamentally we could support multiple namespaces on a single edge node. But I need to know your scenarios and we can just enable if they are valid. 

For a K8s at cloud, there can be clusters dedicated for a single tenant.

**Comment by tedli** [comment]
@CindyXing What we want to express is that a k8s node (while edge core also act as a node) is a cluster scope resource. Without a customized k8s scheduler, pod in other namespaces are also able to be scheduled to an edge node which the pod's namespace doesn't belong to.

So current implementation of KubeEdge (v0.2) could be found that pod in different namespaces co exist on one edge node. And meanwhile there are codes only get the first pod's namespace listed from edge.db (metamanager) as the namespace of all pods on the edge node.

If one edge node only belongs to one namespace, there should be extra efforts to limit pods in other namespaces get scheduled to that edge node.

Or we may allow edge belongs to multi namespaces. So a use case may like this, company A owned an edge node which equiped at production line A with many devices connected, and there are two teams, a manager/supervisor team, a QA team. Both the two teams want to deploy edge apps to the edge node, collecting data from different devices connected. So the two kinds of apps (manager/QA) may want to deploy into different namespaces, one in manager, other in qa to the same edge node.

**Comment by CindyXing** [comment]
@tedli agree with you on the scheduling part. 

Looking at the controller code (https://github.com/kubeedge/kubeedge/blob/master/cloud/edgecontroller/pkg/controller/config/kube.go), we are supporting a single namesapce as a whole. So, my bad if some of the upper comments made any confusion. KubeEdge 0.2 E2E works fine. 

Your scenario is valid. Though running containers for different tenants on the same edge node needs to have security guard. Currently we run regular docker container considering the resource constraint on edge. 

As said, K8s doesn't have a solid multi-tenancy solution. Namespace can't address the security isolation against tenants. Projects among same tenant probably is ok. 

Please go ahead raise a new issue for supporting multi-tenancy. Thanks much!

**Comment by CindyXing** [comment]
Or just update the title for this issue. Thx.

**Comment by nkwangleiGIT** [comment]
ok, so it'll work as expected if we specify a namespace of the edgecontroller, and we can also deploy multiple edgecontroller for different namespaces if needed.
I think we can change the title to "Multi-tenancy support for KubeEdge".  @tedli

**Comment by ryan-esty** [comment]
This might be a a little late but if you have a edge_controller for each customer does that really scale well if you are using name spaces per customer? If there are a bunch of customers with only a couple of devices you won't be able to share an edge_controller and you will only have a couple of devices per edge controller. I'm not sure how big the edge_controller is but it seems wasteful to have only a couple of devices tied to each one.

**Comment by ryan-esty** [comment]
As pointed out to me on the message boards it seems my concern for the edgeController is not necessary it seems the edgeController can watch in all namespaces which means the cloud portion can easily scale.
