### ISSUE TITLE
Create 0.1 release

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#27]
1. create a new `make quick-release` command in Makefile to auto compile and make release tarball.

2. upload the release tarball and write a release note file.

cc @islinwb @Lion-Wei

**Comment by sids-b** [comment]
@m1093782566 , Can close this one ?

**Comment by m1093782566** [comment]
Sure. I think we can start to plan v0.2 now :)

**Comment by m1093782566** [comment]
But we still need a `make quick-release command in Makefile to auto compile and make release tarball.`
