### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by wzshiming** [kubeedge/kubeedge#2721]
**What happened**:
Test fails
**How to reproduce it (as minimally and precisely as possible)**:
Test passd
**What you expected to happen**:
https://github.com/kubeedge/kubeedge/blob/9123e993dc970446c849a754e000d4e87d72870c/pkg/metaserver/key_test.go#L73
This test fails, should I fix the test or fix the code?

**Anything else we need to know?**:
https://github.com/kubeedge/kubeedge/pull/2722/checks?check_run_id=2182946157#step:6:73
**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by wzshiming** [comment]
1.  fix the test or fix the code 
2. add CI #2722

**Comment by fisherxu** [comment]
@wzshiming Thanks for pointing out the issue, Ithink let's fix the test first, because the function  code now haven't the e2e test.
