### ISSUE TITLE
Allow customer deploy K8s service that it can be further proxied/lb to an endpoint

### ISSUE THREAD

**Issue by CindyXing** [kubeedge/kubeedge#273]
**What would you like to be added**:
1. Support K8s service type
2. Be able to route/lb service to endpoints behind

**Why is this needed**:
Allow customer to deploy micro-service using K8s Service type like what they do in data center

**Comment by CindyXing** [comment]
This can be an action item of [#172](https://github.com/kubeedge/kubeedge/issues/172)

**Comment by sids-b** [comment]
Similar to #700 . Closing this issue.
