### ISSUE TITLE
DNS support on kubeedge 1.6

### ISSUE THREAD

**Issue by chuan9** [kubeedge/kubeedge#2736]
**What happened and what you expected to happen**:
I saw [release log of kubeedge 1.6.0](https://github.com/kubeedge/kubeedge/blob/master/CHANGELOG/CHANGELOG-1.6.md), it support third party CNI like flannel, do this version support dns? i.e, service discovery like edgemesh?
**How to reproduce it (as minimally and precisely as possible)**:
k8s+kubeedge(disable edgeMesh)+containerd
**Anything else we need to know?**:

**Environment**:Centos8
- Kubernetes version (use `kubectl version`):None
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.6.0/1.6.1

**Comment by chuan9** [comment]
PTAL, thanks~

**Comment by fisherxu** [comment]
@chuan9 This feature of v1.6 still in alpha phase, had been disabled by default. If you would like to use it, please refer to: #2677
