### ISSUE TITLE
List of pros vs cons of using KubeEdge on website / docs 

### ISSUE THREAD

**Issue by anvithks** [kubeedge/kubeedge#274]
Main benefits to using kubeedge over a standard Kubernetes deployment from a user perspective.
Should you use Kubeedge or a  generic single node cluster.

From here : [refer tweet](https://twitter.com/cjimti/status/1108472662777434113?s=19)

**Comment by wrannaman** [comment]
@anvithks How are you currently going about updating and managing system health on all your edge nodes using a single node cluster? (E.G. pod x on edge node y keeps restarting every 2 minutes for some unknown reason)

Practically speaking when you have 100s (1000s) of edge nodes, management is a sizeable pain in the a$$.

**Comment by anvithks** [comment]
@sids-b could you shed some light on this?
cc @rohitsardesai83

**Comment by m1093782566** [comment]
@anvithks You can check https://github.com/kubeedge/kubeedge#advantages first.

**Comment by sids-b** [comment]
Closing this issue now. We can add points in #291 about use-cases or create a seperate issue if required in the website repository.
