### ISSUE TITLE
symbolic link volume mount handling allows arbitrary file access in host filesystem

### ISSUE THREAD

**Issue by longwanbin** [kubeedge/kubeedge#2754]
**What happened**:
This vulnerability allows containers using symbolic link volume mounts to access files/directories outside of the volume, including the host’s filesystem.
Vulnerable versions:
- kubeedge-1.2
- kubeedge-1.3
- kubeedge-1.4
- kubeedge-1.5
- kubeedge-1.6

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
For example:
1. Container A mount host path /home as /container/home/, then enter the container and create a symbolic point to root directories (cd /container/home/ && ln -sf / abc)
2. Create container b and mount /home/abc to container b. Because /home/abc is a symbolic file, container b parses the directory to the real path. In this case, the actual mounting path of b is the root directory(/), which cause container escape.

**Environment**:
- Kubernetes version (use `kubectl version`): kubernetes v1.17.1
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by fisherxu** [comment]
@longwanbin Thanks for pointing out the issue, does this bug exist in native K8s?

**Comment by luo-ru** [comment]
yes, this bug exist in native K8s?
