### ISSUE TITLE
Refactor the cloudStream to pass-through the request instead of parsing the web path

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#2756]
**What would you like to be added/modified**:
Edgestream is used to handle the request from apiserver, then forward the request to edged through tunnel. Now in edgestream, we parse the url path as here:  https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/cloudstream/streamserver.go#L52

We need to find a way to pass-through the request, through the hijack stuff, instead of parsing the web path manually.

**Comment by rajibmitra** [comment]
could you please assign this to me @fisherxu

**Comment by charles-woshicai** [comment]
/assign

Let me try.

**Comment by charles-woshicai** [comment]
Latest status: not work with this but might be free to try in the next month. So keep it unstale.
