### ISSUE TITLE
Something wrong in my cloud， but I don‘t know why.This is the log.

### ISSUE THREAD

**Issue by Xxllj834738992** [kubeedge/kubeedge#2759]
I0407 15:55:21.600718   17858 server.go:64] Version: v1.6.0
I0407 15:55:21.602530   17858 config.go:45] Succeed in loading CA certificate from local directory
I0407 15:55:21.602570   17858 config.go:52] Succeed in loading CA key from local directory
I0407 15:55:21.602607   17858 module.go:34] Module cloudhub registered successfully
I0407 15:55:21.613023   17858 module.go:34] Module edgecontroller registered successfully
I0407 15:55:21.613089   17858 module.go:34] Module devicecontroller registered successfully
I0407 15:55:21.613133   17858 module.go:34] Module synccontroller registered successfully
W0407 15:55:21.613188   17858 module.go:37] Module cloudStream is disabled, do not register
W0407 15:55:21.613193   17858 module.go:37] Module router is disabled, do not register
W0407 15:55:21.613197   17858 module.go:37] Module dynamiccontroller is disabled, do not register
I0407 15:55:21.613225   17858 core.go:24] Starting module cloudhub
I0407 15:55:21.613387   17858 core.go:24] Starting module edgecontroller
I0407 15:55:21.613410   17858 core.go:24] Starting module devicecontroller
I0407 15:55:21.613429   17858 core.go:24] Starting module synccontroller
I0407 15:55:21.613541   17858 upstream.go:110] start upstream controller
I0407 15:55:21.614501   17858 downstream.go:870] Start downstream devicecontroller
I0407 15:55:21.614526   17858 downstream.go:550] start downstream controller
E0407 15:55:21.623931   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
E0407 15:55:21.626248   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
W0407 15:55:21.714704   17858 channelq.go:294] nodeQueue for edge node edge not found and created now
W0407 15:55:21.714747   17858 channelq.go:322] nodeStore for edge node edge not found and created now
W0407 15:55:21.714774   17858 channelq.go:308] nodeListQueue for edge node edge not found and created now
W0407 15:55:21.714782   17858 channelq.go:336] nodeListStore for edge node edge not found and created now
I0407 15:55:21.722423   17858 server.go:317] CloudCoreCert and key don't exist in local directory, and will read from the secret
I0407 15:55:21.730908   17858 signcerts.go:98] Succeed to creating token
I0407 15:55:21.730955   17858 server.go:44] start unix domain socket server
I0407 15:55:21.731075   17858 uds.go:72] listening on: //var/lib/kubeedge/kubeedge.sock
I0407 15:55:21.737864   17858 server.go:63] Starting cloudhub websocket server
E0407 15:55:22.554620   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
W0407 15:55:22.615630   17858 downstream.go:373] Device doesn't support valid protocol
E0407 15:55:22.767899   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
I0407 15:55:23.617095   17858 upstream.go:63] Start upstream devicecontroller
E0407 15:55:24.768382   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
E0407 15:55:24.880325   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
E0407 15:55:28.990794   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
E0407 15:55:29.470193   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
E0407 15:55:37.268438   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
E0407 15:55:40.221295   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
E0407 15:55:52.870286   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
E0407 15:55:55.625867   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
E0407 15:56:27.711277   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
E0407 15:56:35.837283   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
E0407 15:57:14.635878   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
E0407 15:57:23.589647   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
E0407 15:57:53.552652   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
E0407 15:58:16.172518   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
E0407 15:58:29.752153   17858 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
I0407 15:58:49.364172   17858 core.go:35] Get os signal interrupt
I0407 15:58:49.364345   17858 core.go:40] Cleanup module edgecontroller
W0407 15:58:49.364385   17858 upstream.go:667] stop queryPersistentVolume
I0407 15:58:49.364410   17858 upstream.go:110] Stop updateDeviceStatus
W0407 15:58:49.364411   17858 downstream.go:376] Stop edgecontroller downstream syncEndpoints loop
I0407 15:58:49.364421   17858 upstream.go:110] Stop updateDeviceStatus
I0407 15:58:49.364442   17858 upstream.go:110] Stop updateDeviceStatus
I0407 15:58:49.364453   17858 upstream.go:110] Stop updateDeviceStatus
I0407 15:58:49.364464   17858 upstream.go:110] Stop updateDeviceStatus
I0407 15:58:49.364479   17858 upstream.go:110] Stop updateDeviceStatus
I0407 15:58:49.364489   17858 upstream.go:110] Stop updateDeviceStatus

**Comment by GsssC** [comment]
It seems that you have not apply crds.yaml at [here](https://github.com/kubeedge/kubeedge/tree/master/build/crds/router)

**Comment by Xxllj834738992** [comment]
> It seems that you have not apply crds.yaml at [here](https://github.com/kubeedge/kubeedge/tree/master/build/crds/router)
Sorry, I don't know how to do it. Could you please help me?

**Comment by GsssC** [comment]
@Xxllj834738992 just
```go
kubectl apply -f router_v1_rule.yaml
kubectl apply -f router_v1_ruleEndpoint.yaml
```

**Comment by Xxllj834738992** [comment]
> @Xxllj834738992 just
> 
> ```go
> kubectl apply -f router_v1_rule.yaml
> kubectl apply -f router_v1_ruleEndpoint.yaml
> ```

Thanks a lot!
