### ISSUE TITLE
cloudcore starts fail

### ISSUE THREAD

**Issue by magnate3** [kubeedge/kubeedge#2761]
**What happened**:
I0408 11:44:02.145000   45555 server.go:64] Version: v1.6.0-beta.0.168+853c367496baac
I0408 11:44:02.149064   45555 config.go:45] Succeed in loading CA certificate from local directory
I0408 11:44:02.149153   45555 config.go:52] Succeed in loading CA key from local directory
I0408 11:44:02.149204   45555 module.go:34] Module cloudhub registered successfully
I0408 11:44:02.173996   45555 module.go:34] Module edgecontroller registered successfully
I0408 11:44:02.174091   45555 module.go:34] Module devicecontroller registered successfully
I0408 11:44:02.174129   45555 module.go:34] Module synccontroller registered successfully
W0408 11:44:02.174238   45555 module.go:37] Module cloudStream is disabled, do not register
W0408 11:44:02.174253   45555 module.go:37] Module router is disabled, do not register
W0408 11:44:02.174266   45555 module.go:37] Module dynamiccontroller is disabled, do not register
I0408 11:44:02.174347   45555 core.go:24] Starting module cloudhub
I0408 11:44:02.174390   45555 core.go:24] Starting module edgecontroller
I0408 11:44:02.174667   45555 core.go:24] Starting module devicecontroller
I0408 11:44:02.174797   45555 upstream.go:111] start upstream controller
I0408 11:44:02.174850   45555 core.go:24] Starting module synccontroller
I0408 11:44:02.174848   45555 downstream.go:870] Start downstream devicecontroller
I0408 11:44:02.177399   45555 downstream.go:566] start downstream controller
I0408 11:44:02.285445   45555 server.go:311] CloudCoreCert and key don't exist in local directory, and will read from the secret
I0408 11:44:02.287008   45555 server.go:315] CloudCoreCert and key don't exist in the secret, and will be signed by CA
E0408 11:44:02.309357   45555 server.go:318] failed to sign a certificate, error: failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: tags don't match (16 vs {class:1 tag:0 length:64 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} ecPrivateKey @2
F0408 11:44:02.309387   45555 cloudhub.go:74] failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: tags don't match (16 vs {class:1 tag:0 length:64 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} ecPrivateKey @2
goroutine 115 [running]:
 

**Environment**:
- Kubernetes version (use `kubectl version`):
root@ubuntu:~/cmd# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
root@ubuntu:~/cmd#
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
root@ubuntu:~/cmd# ./cloudcore --version
KubeEdge v1.6.0-beta.0.168+853c367496baac
 
 root@ubuntu:~/cmd# go version
go version go1.14.6 linux/arm64
root@ubuntu:~/cmd# uname -a
Linux ubuntu 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:10:24 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
root@ubuntu:~/cmd# lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           2
NUMA node(s):        4
Vendor ID:           ARM
Model:               2
Model name:          Cortex-A72
Stepping:            r0p2
BogoMIPS:            100.00
L1d cache:           32K
L1i cache:           48K
L2 cache:            1024K
L3 cache:            16384K
NUMA node0 CPU(s):   0-15
NUMA node1 CPU(s):   16-31
NUMA node2 CPU(s):   32-47
NUMA node3 CPU(s):   48-63
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
 
 

  </details>

**Comment by GsssC** [comment]
try **kubectl delete namespaces kubeedge**, it will delete certifications. 
And cloudcore will re-create these certifications when restart.

**Comment by magnate3** [comment]
@GsssC  after  try kubectl delete namespaces kubeedge, restart cloudcore and the error is 
W0408 15:48:20.115527   40713 upstream.go:186] parse message:  resource type with error: resource type not found
W0408 15:48:20.135651   40713 upstream.go:92] Parse message:  resource type with error: unknown resource

**Comment by gege-pro** [comment]
Have you solved this problem? I have the same problem as you

**Comment by gege-pro** [comment]
Have you solved this problem? I have the same problem as you
