### ISSUE TITLE
edgecore starts fail 

### ISSUE THREAD

**Issue by magnate3** [kubeedge/kubeedge#2762]
What happened:
 
 certmanager.go:91] Error: failed to get edge certificate from the cloudcore, error: Get "https://10.10.16.82:10002/edge.crt": x509: cannot validate certificate for 10.0.6.82 because it doesn't contain any IP SANs
Environment:

Kubernetes version (use kubectl version):
root@ubuntu:/cmd# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
root@ubuntu:/cmd#
KubeEdge version(e.g. cloudcore --version and edgecore --version):
root@ubuntu:~/cmd# ./cloudcore --version
KubeEdge v1.6.0-beta.0.168+853c367496baac
root@ubuntu:/cmd# go version
go version go1.14.6 linux/arm64
root@ubuntu:/cmd# uname -a
Linux ubuntu 5.0.0-23-generic #2418.04.1-Ubuntu SMP Mon Jul 29 16:10:24 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
root@ubuntu:/cmd# lscpu
Architecture: aarch64
Byte Order: Little Endian
CPU(s): 64
On-line CPU(s) list: 0-63
Thread(s) per core: 1
Core(s) per socket: 32
Socket(s): 2
NUMA node(s): 4
Vendor ID: ARM
Model: 2
Model name: Cortex-A72
Stepping: r0p2
BogoMIPS: 100.00
L1d cache: 32K
L1i cache: 48K
L2 cache: 1024K
L3 cache: 16384K
NUMA node0 CPU(s): 0-15
NUMA node1 CPU(s): 16-31
NUMA node2 CPU(s): 32-47
NUMA node3 CPU(s): 48-63
Flags: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

**Comment by Rachel-Shao** [comment]
I encountered this problem once, but it was not resolved at the time. Here are some possible reasons:
#2220 (same problem)

Now I give a little bit of my thoughts：
It is obviously a certificate issue, so I generally choose to regenerate the certificate (I suggest to delete the `kubeedge` 
namespace directly, and then restart `cloudcore`)

When edgenode joins the cluster, pay attention to the process of obtaining the certificate, the relevant explanation is in #2791

Hope it can help you :)
