### ISSUE TITLE
Device Controller doesn't accept `nodeSelector.nodeSelectorTerms[0].matchExpressions.operator: Exists`

### ISSUE THREAD

**Issue by esakat** [kubeedge/kubeedge#2763]
**What happened**:

I tried to run [kubeedge-counter-demo](https://github.com/kubeedge/examples/tree/master/kubeedge-counter-demo).  
and I changed manifest to suit for my environment.

i.e.

I changed like following.
https://github.com/kubeedge/examples/blob/master/kubeedge-counter-demo/crds/kubeedge-counter-instance.yaml

```diff
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
-        operator: In
-        values:
-        - edge-node
+      - operator: Exists
+        key: 'node-role.kubernetes.io/edge'
```

I open [Webpage](https://github.com/kubeedge/examples/tree/master/kubeedge-counter-demo#control-counter-by-visiting-web-app-page) and change state, then
cloudcore process is down with following log message

```
panic: runtime error: index out of range [0] with length 0

goroutine 269 [running]:
github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/controller.(*DownstreamController).deviceUpdated(0xc000149c40, 0xc0001e4fc0)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/controller/downstream.go:629 +0xbb8
github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/controller.(*DownstreamController).syncDevice(0xc000149c40)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/controller/downstream.go:167 +0x29f
created by github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/controller.(*DownstreamController).Start
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/controller/downstream.go:877 +0xe7
```

I noticed that to make ConfigMap, device controller use `NodeSelector.NodeSelectorTerms[0].MatchExpressions[0].Values[0]`.
https://github.com/kubeedge/kubeedge/blob/v1.6.1/cloud/pkg/devicecontroller/controller/downstream.go#L186

I didn't realize that, but I hope I can use `nodeSelector.nodeSelectorTerms[0].matchExpressions.operator: Exists`. 
so it should accept other `nodeSelector.nodeSelectorTerms[0].matchExpressions.operator`.

**What you expected to happen**:

No Error, if i use `nodeSelector.nodeSelectorTerms[0].matchExpressions.operator: Exists`

**How to reproduce it (as minimally and precisely as possible)**:

1. Create `Kind: Device` with `nodeSelector.nodeSelectorTerms[0].matchExpressions.operator: Exists`
2. Do something to occur `(dc *DownstreamController) addToConfigMap(device *v1alpha2.Device) `

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):  `v1.6.1`
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by GsssC** [comment]
@ttlv PTAL : )

**Comment by ttlv** [comment]
@esakat well,I don't think it's a bug because the field of values must be filled, if null we will get a fatal error(index out of range ). You will find the coupling relationship between node and device(in counter example we don't have any device,I mean mapper) in other words device belongs to nodeA and can't belong to  nodeB at the same time. WDYT :)

**Comment by esakat** [comment]
@ttlv thank you. you perfectly right.

> in other words device belongs to nodeA and can't belong to nodeB at the same time.

to achieve this. the node selected by nodeSelector should be unique.  
I understood this is not bug.


----
sorry following is my opinion.

but I was little confused by this specification.
`nodeSelector` looks it should be set `nodename` as `Value`.

I tried following

```bash
$ kubectl label nodes <nodename> nodetype=edge-node-A
```

and apply this Device manifest.

```yml
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: 'nodetype'
        operator: In
        values:
        - edge-node-A
```

There wasn't  error in cloudcore log.  
but this changes didn't publish to Mosquitto.  
So I change manifest again.


```diff
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
-      - key: 'nodetype'
+      - key: ''
        operator: In
        values:
-        - edge-node-A
+        - <nodename>
```

I succeeded [kubeedge-counter-demo](https://github.com/kubeedge/examples/tree/master/kubeedge-counter-demo).  
it looks.. this value uses in MQTT topic name.

I noticed `nodeSelector` should be set `<nodename>` as Value.  but to do this, `nodeSelector` is too flexible.  
if prepare custom attribute for this, it will be more clearly.

**Comment by ttlv** [comment]
@esakat You are right, if you read the source code of the devicecontroller you will find the values(it must be nodename now) which you set in the device yaml is very important and your suggestion is good to me, I am goging to talk about this problem with other community‘s  members, welcome to join us :)
