### ISSUE TITLE
customize node labels can't be seen when I add labels in edgecorefile and restart edgecore

### ISSUE THREAD

**Issue by ttlv** [kubeedge/kubeedge#2764]
**What happened**:
 Kubeedge supports customize node labels  after version 1.6.0,I tryed today but it did't work when I restart edgecore,I can't see any customize node labels when I use ```kubectl get node --show-labels``` command  but when I delete edge node and rejoin,the customize node labels which I add into edgecore's yaml can be showed
**How to reproduce it (as minimally and precisely as possible)**:
just add some customize node labels in edgecore config yaml and then restart edgecore bin
**Environment**:
- Kubernetes version : 1.19.7
- KubeEdge version: cloudcore 1.6.1, edgecore 1.6.1

**Comment by felix0080** [comment]
有更多的细节提供吗？

**Comment by ttlv** [comment]
customsized labels  is meanningful when edgenode first join and if we want to add or update the labels for node, we can use kubectl label command to make it rather than use the configyaml of edgecore, priority of the cloud is top1. so I think it's better  to make keadm to support.

**Comment by fisherxu** [comment]
With this patch #2827, if we restart edgecore, maybe the label will still missing?

**Comment by ttlv** [comment]
> With this patch #2827, if we restart edgecore, maybe the label will still missing?

If we use kubectl label command to add new label for edge node and should we synchronize the new label in the edgecore's config file ?

**Comment by fisherxu** [comment]
>  If we use kubectl label command to add new label for edge node in the cloud and should we synchronize the new label in the edgecore's config file ?

No, I think the edgenode should patch the node spec, if labels in config changed, the labels of edgenode should be patched. @ttlv
