### ISSUE TITLE
Should edgenode crash be considered in autonomy scenario?

### ISSUE THREAD

**Issue by DreamEagle0** [kubeedge/kubeedge#2776]
When cloud nodes cannot connect to a edge node, there are 2 scenarios:
1. network disconnection
2. edge node crashes

Consider the second scenario. When a edge node crashes, the pod in the edge node will not be evicted. In this case, the service of the pod will keep unavailable? Is there any way to fix this?

**Comment by fisherxu** [comment]
@DreamEagle0 Now we haven't done the detection for edge node for the scenario of network disconnection or crash. 

There are some ideas to make edge nodes detect each other, but when the network of other nodes is also disconnected(use the same gateway), there is still no way to know whether the network is disconnected or crashed.

But I think we can add some detections api for users, who can decide whether to detect from some "special edge nodes".
