### ISSUE TITLE
Refactoring Device Module: use k8s v1alpha2.Device CRD structure, instead of self-defined device or twin property structure, to communicate between cloud and edge, between edge and device.

### ISSUE THREAD

**Issue by gy95** [kubeedge/kubeedge#2778]
### devicetwin module refactoring key points：

1、One general principle is that all of messages between cloud and edge, or between edge and device, all apply for K8s device CRD structure as follows:

```go
// Device is the Schema for the devices API
// +k8s:openapi-gen=true
type Device struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DeviceSpec   `json:"spec,omitempty"`
	Status DeviceStatus `json:"status,omitempty"`
}
```

and so all related content arising out of changing message content structure should be modified accordingly. and we will not use the following structure or other similar self-defined structures any more.

```go
// Device the struct of device
type Device struct {
	ID          string              `json:"id,omitempty"`
	Name        string              `json:"name,omitempty"`
	Description string              `json:"description,omitempty"`
	State       string              `json:"state,omitempty"`
	LastOnline  string              `json:"last_online,omitempty"`
	Attributes  map[string]*MsgAttr `json:"attributes,omitempty"`
	Twin        map[string]*MsgTwin `json:"twin,omitempty"`
}
```

2、edge and device should also support namespace property, so we will use `namespace + "/" + name` as device unique key, but not only use `name` as unique key

#### cloud modifications:

1、`deviceAdded` and `deviceDeleted ` function will use two deferent resource type `membership/added` and `membership/deleted` to send messages to edge. will not use the same resource type `membership` to represent both added device and deleted device.

2、`DeviceProfile` also uses structure `v1alpha2.Device` to store devices.

```go
// DeviceProfile is structure to store in configMap. These types would be consumed by mappers to marshal / unmarshal the device profile json
type DeviceProfile struct {
	// DeviceInstances is used to store list of all devices.
	DeviceInstances []*v1alpha2.Device `json:"deviceInstances,omitempty"`
	// DeviceModels is used to store list of all DeviceModels referenced by DeviceInstances
	DeviceModels []*DeviceModel `json:"deviceModels,omitempty"`
	// TODO: protocols is repeated in DeviceInstance, consider to remove it
	// Protocols is list of all protocols used by DeviceInstances
	Protocols []*Protocol `json:"protocols,omitempty"`
}
```

#### edge modifications:

1、modifications about database: we change table `device` and `device_twin` structures and delete not-used table `device_attr`.

 table `device` and `device_twin` structures are as follows: and we will use `namespace+name` as table `device` unique key, `device_name + device_namespace + property_name` as table `device_twin` unique key

```go
//Device the struct of device
type Device struct {
	ID          int64 `orm:"column(id); size(64); auto; pk"`
	Name        string `orm:"column(name); null; type(text); unique"`
	Namespace   string `orm:"column(namespace); null; type(text); unique"`
}
```

```go
//DeviceTwin the struct of device twin
type DeviceTwin struct {
	ID              int64  `orm:"column(id);size(64);auto;pk"`
	DeviceName      string `orm:"column(device_name); null; type(text); unique"`
	DeviceNamespace string `orm:"column(device_namespace);null;type(text); unique"`
	PropertyName    string `orm:"column(property_name);null;type(text); unique"`
	Expected        string `orm:"column(expected);null;type(text)"`
	Actual          string `orm:"column(actual);null;type(text)"`
	ExpectedMeta    string `orm:"column(expected_meta);null;type(text)"`
	ActualMeta      string `orm:"column(actual_meta);null;type(text)"`
}
```

2、remove or modify some message processing functions:

(1) delete two message processing functions about device state and device attribute (`dealDeviceAttrUpdate`、`dealDeviceStateUpdate`), delete `dealDeviceAttrUpdate` due to removing device attribute, delete `dealDeviceStateUpdate` because edge side only stores device online/offline state in database but cloud don't react to device state change

(2) delete membership manager not-used function `dealMembershipDetail`, because i don't find where to use this function or how to trigger this function

(3) divide function `dealMembershipUpdate` into two independent functions `dealMembershipAdd`、`dealMembershipDelete` just like what the cloud side did

3、device twin processing function `DealDeviceTwin` has a major modification

(1) not considering the version factor anymore

(2) the result of dealing twin `DealTwinResult` structure removes not-used document and Result fields, the structure becomes this:

```go
//DealTwinResult the result of dealing twin
type DealTwinResult struct {
   Add        []dtclient.DeviceTwin
   Delete     []dtclient.DeviceTwinPrimaryKey
   Update     []dtclient.DeviceTwinUpdate
   SyncResult v1alpha2.Device
   Err        error
}
```

the structure before modifications is as follows:

```go
//DealTwinResult the result of dealing twin
type DealTwinResult struct {
	Add        []dtclient.DeviceTwin
	Delete     []dtclient.DeviceDelete
	Update     []dtclient.DeviceTwinUpdate
	Result     map[string]*MsgTwin
	SyncResult map[string]*MsgTwin
	Document   map[string]*TwinDoc
	Err        error
}
```

#### device modifications:

1、due to message content structures changed to `v1alpha2.Device`, so the relating mapper also needs to be modified synchronously.

2、topics published to MQTT or subscribed need also contain `namespace + name` field

because we moved all mappers to kubeedge/mapper-go repo, so then i will open another PR to the new repo again

**Comment by GsssC** [comment]
@ttlv PTAL
