### ISSUE TITLE
keadm gettoken validity issue

### ISSUE THREAD

**Issue by beyondyinjl2** [kubeedge/kubeedge#2779]
1 What is the validity period of keadm gettoken?
2 keadm gettoken can modify the validity period of the token, or produce a new token?

**Comment by GsssC** [comment]
1. 12h according to https://github.com/kubeedge/kubeedge/blob/f01eeff7f4cc870ebcc5eff290071e8aabc8e36d/cloud/pkg/cloudhub/servers/httpserver/signcerts.go#L88-L87
2. both not. `keadm gettoken` just read token stored in etcd and print out. you could also get by `kubectl get secret -nkubeedge tokensecret`

**Comment by beyondyinjl2** [comment]
@GsssC  keadm gettoken gets token, is there any other way to get token? Is there kubeedge api document to get it, or k8s api to get it?

**Comment by GsssC** [comment]
kubectl get secret -nkubeedge tokensecret

you could get token by this.
