### ISSUE TITLE
How about  change  the api verision of the crds to a stable version?

### ISSUE THREAD

**Issue by zhu733756** [kubeedge/kubeedge#2780]
**What happened and what you expected to happen**:
Currently, the crds are in different version. How about change the api version of the crds to apiextensions.k8s.io/v1 ?  It would help me a lot to manage these crds. Thanks.

**Comment by fisherxu** [comment]
Sure, we sould use tools like kubebuilder to generate the crd.

**Comment by zhu733756** [comment]
Great. Thanks you again.
