### ISSUE TITLE
Edgecode has pod residue

### ISSUE THREAD

**Issue by jackgege90** [kubeedge/kubeedge#2782]
When the state of the edge node is out of sync with the cloud, can it be reset remotely? For example, I create a batch of micro services in the cloud and distribute them to node1, but I don't know why, when I delete them in the cloudcore, there is still a service running on node1. Due to port mapping, I can't create the service normally after republishing the micro service. Besides manual deletion, is there any other remote operation method?

**Environment**:
- Kubernetes version (use `kubectl version`):1.19.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.6.0

**Comment by GsssC** [comment]
Sorry, now the only sync method is **"deleting node" , "keadm reset" and re"keadm join"**, same as "kubelet is wrong".
It is better to figure out why edgecore is out of sync.
