### ISSUE TITLE
Does custom cni plugin like calico support on edge node?

### ISSUE THREAD

**Issue by vickiyan** [kubeedge/kubeedge#2788]
**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
**What happened and what you expected to happen**:
calico cni plugin doesn't work on edge node but works on k8s node.  Are k8s cni plugins like calico or other custom cni plugins supported on edge node? If yes, any document to deploy step-by-step as an example？
 
**How to reproduce it (as minimally and precisely as possible)**:
1.modify the edgecore.yaml as below:
1).close edgemesh "modules.edgemesh.enable: false"
2).add a new field "modules.edged.networkPluginName: cni" 
2 restart edgecore
3. run calico.yaml
4. kubectl apply -f  deployment.yaml  to edge node, the pod cannot start with no IP assigned, its status is stuck at "containercreating".

**Anything else we need to know?**:
I'm wondering if edgemesh is disabled, could service discovering and routing will be affected for edge node? 
**Environment**:
- Kubernetes version (use `kubectl version`):
- 1.13.9
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
1.5
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by vickiyan** [comment]
I resolved this issue via modifying the Calico daemonset yaml file , need to specify environment variable KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT for each container , because Pod running on edge cannot get In Cluster Config like those running on K8s cluster node.   Now calico cni plugin is working fine on both k8s and kubedge ,all pods running between cluster node and egde node could access each other just like single k8s cluster.  
Also, Close edgemesh module seems not necessary.

**Comment by CooperLi** [comment]
> I resolved this issue via modifying the Calico daemonset yaml file , need to specify environment variable KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT for each container , because Pod running on edge cannot get In Cluster Config like those running on K8s cluster node. Now calico cni plugin is working fine on both k8s and kubedge ,all pods running between cluster node and egde node could access each other just like single k8s cluster.
> Also, Close edgemesh module seems not necessary.

Hi there, I met the same issue and change the daemon set yaml file like you said, however, the outcome still not correct, could you please put your Calico daemonset yaml file? Thanks a lot!

**Comment by jidalong** [comment]
> > I resolved this issue via modifying the Calico daemonset yaml file , need to specify environment variable KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT for each container , because Pod running on edge cannot get In Cluster Config like those running on K8s cluster node. Now calico cni plugin is working fine on both k8s and kubedge ,all pods running between cluster node and egde node could access each other just like single k8s cluster.
> > Also, Close edgemesh module seems not necessary.
> 
> Hi there, I met the same issue and change the daemon set yaml file like you said, however, the outcome still not correct, could you please put your Calico daemonset yaml file? Thanks a lot!
> 
> Here is my error log:
> 
> ```shell
> 2021-08-28 13:19:38.619 [INFO][1] ipam_plugin.go 75: migrating from host-local to calico-ipam...
> 2021-08-28 13:19:38.619 [FATAL][1] ipam_plugin.go 93: failed to initialize api client node="edge.kubeedge"
> ```

@CooperLi hello， I meet the same issue, have you solved this problem.

**Comment by CooperLi** [comment]
> > > I resolved this issue via modifying the Calico daemonset yaml file , need to specify environment variable KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT for each container , because Pod running on edge cannot get In Cluster Config like those running on K8s cluster node. Now calico cni plugin is working fine on both k8s and kubedge ,all pods running between cluster node and egde node could access each other just like single k8s cluster.
> > > Also, Close edgemesh module seems not necessary.
> > 
> > 
> > Hi there, I met the same issue and change the daemon set yaml file like you said, however, the outcome still not correct, could you please put your Calico daemonset yaml file? Thanks a lot!
> > Here is my error log:
> > ```shell
> > 2021-08-28 13:19:38.619 [INFO][1] ipam_plugin.go 75: migrating from host-local to calico-ipam...
> > 2021-08-28 13:19:38.619 [FATAL][1] ipam_plugin.go 93: failed to initialize api client node="edge.kubeedge"
> > ```
> 
> @CooperLi hello， I meet the same issue, have you solved this problem.

not yet, used `flannel` instead
