### ISSUE TITLE
Facing issue while Setting-up  KubeEdge from sourcecode

### ISSUE THREAD

**Issue by milindw96** [kubeedge/kubeedge#2789]
Hello 
i am trying to   setup  KubeEdge from sourcecode
but getting these error and unable to solve it can anyone please help me with it 
----------------------------------------------------------------
followed doc https://kubeedge-docs.readthedocs.io/en/latest/setup/setup.html
Additional info:
[admin@localvm kubeedge]$ gcc --version
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[admin@localvm kubeedge]$ uname -r
5.11.11-200.fc33.x86_64

========================================================================
error:
[admin@localvm kubeedge]$ make all WHAT=cloudcore
hack/verify-golang.sh
go detail version: go version go1.15.8 linux/amd64
go version: 1.15.8
KUBEEDGE_OUTPUT_SUBPATH=_output/local hack/make-rules/build.sh cloudcore
building github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
+ go build -o /src/github.com/kubeedge/kubeedge/_output/local/bin/cloudcore -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2021-04-18T08:59:49Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=ceadc730fdacdc831450abdd75d944e2c3d7a22a -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.6.0-beta.0.178+ceadc730fdacdc -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=6+' github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:125322:10: warning: function may return address of local variable [-Wreturn-local-addr]
125322 |   return pNew;
       |          ^~~~
sqlite3-binding.c:125282:10: note: declared here
125282 |   Select standin;
       |          ^~~~~~~
go build github.com/kubeedge/kubeedge/cloud/cmd/cloudcore: copying /tmp/go-build340273276/b001/exe/a.out: open /src/github.com/kubeedge/kubeedge/_output/local/bin/cloudcore: permission denied
make: *** [Makefile:47: all] Error 1
------------------------------------------------------------------

Thanks in advance

**Comment by sunkai-XDD** [comment]
maybe it's the permissions problem,you can checkout root prv

**Comment by milindw96** [comment]
looks like it's not an issue of root prv 
```[admin@localvm kubeedge]$ sudo make all WHAT=cloudcore
hack/verify-golang.sh
go detail version: go version go1.15.8 linux/amd64
go version: 1.15.8
KUBEEDGE_OUTPUT_SUBPATH=_output/local hack/make-rules/build.sh cloudcore
building github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
+ go build -o /src/github.com/kubeedge/kubeedge/_output/local/bin/cloudcore -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2021-04-19T09:05:06Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=beed66d71625f53a3aaf08a868247ad2a755a6cb -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.6.0-beta.0.182+beed66d71625f5 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=6+' github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:125322:10: warning: function may return address of local variable [-Wreturn-local-addr]
125322 |   return pNew;
       |          ^~~~
sqlite3-binding.c:125282:10: note: declared here
125282 |   Select standin;
       |          ^~~~~~~
+ set +x
[admin@localvm kubeedge]$ 
```

**Comment by fisherxu** [comment]
@milindw96 Looks like the cloudcore has been compiled successfully, please goto `_output/local/bin` to checkout.

**Comment by fisherxu** [comment]
> @fisherxu yup looks like its compiled
> 
> [admin@localvm bin]$ ll
> total 35708
> -rwxr-xr-x. 1 root root 36564160 Apr 19 14:35 cloudcore
> [admin@localvm bin]$ pwd
> /src/github.com/kubeedge/kubeedge/_output/local/bin
> 
> but can u please explain to me why it is giving me a warning there might be some reason for that right?

I'm not sure why there's that warning, and in my host, have no warning.. @milindw96 
```shell
➜  kubeedge git:(master) make all WHAT=cloudcore                  
hack/verify-golang.sh
go detail version: go version go1.15.8 linux/amd64
go version: 1.15.8
KUBEEDGE_OUTPUT_SUBPATH=_output/local hack/make-rules/build.sh cloudcore
building github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
+ go build -o /root/codes/src/github.com/kubeedge/kubeedge/_output/local/bin/cloudcore -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2021-04-20T04:12:39Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=beed66d71625f53a3aaf08a868247ad2a755a6cb -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.6.0-beta.0.182+beed66d71625f5 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=6+' github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
+ set +x
```

**Comment by milindw96** [comment]
Cool might be I did some mistake while following steps 
Thanks for the help :-)

**Comment by fisherxu** [comment]
> Cool might be I did some mistake while following steps
> Thanks for the help :-)

welcome :) So I will close the issue, free to reopen if have other issue.
