### ISSUE TITLE
Keadm gettoken failed error

### ISSUE THREAD

**Issue by younes199511** [kubeedge/kubeedge#2792]
**What happened**:

Hello,
I'm new with kubeedge and i'm facing an issue with the deployment.
The command keadm gettoken returns the error below
![image](https://user-images.githubusercontent.com/44032734/115270634-cd55e400-a13c-11eb-9382-018217d5d85a.png)

I was able to deploy CloudCore successfully but i coudn't get the token to deploy the EdgeCore node.

**What you expected to happen**:

I expect to get a token key 
`# keadm gettoken
27a37ef16159f7d3be8fae95d588b79b3adaaf92727b72659eb89758c66ffda2.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTAyMTYwNzd9.JBj8LLYWXwbbvHKffJBpPd5CyxqapRQYDIXtFZErgYE`

**How to reproduce it (as minimally and precisely as possible)**:

I followed the setup with keadm instructions in the documentations 
https://kubeedge.io/en/docs/setup/keadm/
 
**Anything else we need to know?**:

Using the _kubectl -n kubeedge describe secrets_ i'm getting this : 

![image](https://user-images.githubusercontent.com/44032734/115271703-e7dc8d00-a13d-11eb-8c03-a98ffbed7186.png)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.6.1

  - Hardware configuration (e.g. `lscpu`):  x86, 64 bits, Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  - OS (e.g. `cat /etc/os-release`): Ubuntu VM (virtualbox)
  - Kernel (e.g. `uname -a`): Linux x86_64
  - Go version (e.g. `go version`): 1.16.1

**Comment by GsssC** [comment]
@Rachel-Shao PTAL

**Comment by Rachel-Shao** [comment]
It seems that you are not running cloudcore normally. Generally, there should be four secrets in the kubeedge namespace. 
Like this ↓
![image](https://user-images.githubusercontent.com/34911960/115341946-085b2480-a1dc-11eb-95b2-5273c2d892bf.png)


 I think you can try to delete the existing casecret or delete the kubeedge namespace directly (because these old secrets may come from the cloudcore you installed earlier), and then restart cloudcore. It will regenerate these secrets.

**Comment by younes199511** [comment]
Hello @Rachel-Shao 
Thank's so much. It's working now.

I have just another question please: is there a simple way to test that the deployement of kubeedge (both cloud and edge cores) was successfull and everything works fine ?

Best regards

**Comment by Rachel-Shao** [comment]
Are there any specific error messages with `[F0421]` flags?
If you can’t find it, you can `systemctl stop edgecore`  first, then run your edgecore binary file directly.
If no accident, it will pause and output a lot of logs, you can definitely find the error message.
