### ISSUE TITLE
Add hardware requirements for kubeedge

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#28]
Memory >=256MB

CPU  >=1VCPU

xref: https://support.huaweicloud.com/usermanual-ief/ief_01_0003.html

**Comment by warmchang** [comment]
Would you consider supporting a lightweight operating system (Alpine or BusyBox)?
> 
OS | Ubuntu 16.04 LTS (Xenial Xerus)、Ubuntu 18.04 LTS (Bionic Beaver) 、CentOS 7和RHEL 7
-- | --

**Comment by m1093782566** [comment]
> Would you consider supporting a lightweight operating system (Alpine or BusyBox)?

Definitely!

cc @skdwriting @sids-b @rohitsardesai83

**Comment by Baoqiang-Zhang** [comment]
@warmchang OS in requirements is only  a suggestion since IEF service team have verified on these general OS, you can use kubeedge code to build a binary to run on any OS that you need.

**Comment by warmchang** [comment]
Got it, thanks. :+1:
