### ISSUE TITLE
kubeedge为什么不支持nodePort；

### ISSUE THREAD

**Issue by feiluojiang** [kubeedge/kubeedge#2807]
问下大佬们，kubeedge为什么不支持nodePort；

**Comment by fisherxu** [comment]
In most usage scenarios, the edge node is located in the private network, and have no public IP, so in the initial design, edgemesh doesn't support nodeport.

But now we have supported to install kube-proxy in edgenode, so you can use nodeport through kube-proxy.

**Comment by fisherxu** [comment]
Close the issue now, please reopen it if has any other issues :)
/close
