### ISSUE TITLE
Edge request API server , when cloudhub create objectsync for node or namespace resources which do not have namesapce, cloudhub report an error

### ISSUE THREAD

**Issue by jidalong** [kubeedge/kubeedge#2810]
**What happened**:
Edge request API server , when cloudhub create objectsync for node or namespace resources which do not have namesapce, cloudhub report an error
**Edge:**
curl 192.168.93.191:10550/api/v1/nodes
**cloud:**
![image](https://user-images.githubusercontent.com/53475708/115979605-70818000-a5b9-11eb-9f84-7000adc38cdc.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Rachel-Shao** [comment]
Is there any error message returned when you execute `curl 192.168.93.191:10550/api/v1/nodes` ?

**Comment by jidalong** [comment]
> Is there any error message returned when you execute `curl 192.168.93.191:10550/api/v1/nodes` ?
After curl 10550/api/v1/nodes，edge can print the expected result whitout any errors，but cloud may print some error log in cloudhub like the picture above. Although cloudhub output the error logs, cloudcore and edgecore can still run.

**Comment by Rachel-Shao** [comment]
@jidalong   When Cloudhub processes messages, it first starts `ObjectSyncController`. `ObjectSyncController` is the controller of custom CRD objects `ObjectSync` and `ClusterObjectSync`. KubeEdge uses K8s CRD to store the latest resourceVersion of resources that have been successfully sent to Edge.

**`ClusterObjectSync` is used to store cluster-wide objects, and `ObjectSync` is used to store namespace-wide objects. 
`node` belongs to the cluster-scoped object, and it has no `namespace`.**

But the current version of `ClusterObjectSync` is not currently in use and is waiting to be expanded, so all resources will be stored in `ObjectSync` for the time being, so there is an error that namespace is null (`node` shouldn't be in `ObjectSync`).

As a temporary solution, you can set it to "" if the namespace is null before creatObjectSync.
The above is just my personal understanding:)  [more detail](http://www.sel.zju.edu.cn/blog/2020/12/21/kubeedge%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90%E7%B3%BB%E5%88%97%E4%BA%8Ccloudhub/)
