### ISSUE TITLE
Unable to connect to the cloud after edge switch from wired network to wireless network

### ISSUE THREAD

**Issue by luoqian1999** [kubeedge/kubeedge#2814]
**What happened and what you expected to happen**:
Through the installation of Keadm, the edge was successfully added to KubeEdge using a wired network.
![image](https://user-images.githubusercontent.com/67575704/116026622-adb34400-a685-11eb-9a14-65bc904a8637.png)
At this point, switch the edge network to the wireless network, and the edge will always be in the NotReady state.
![image](https://user-images.githubusercontent.com/67575704/116026648-b60b7f00-a685-11eb-9fd1-74ed1527fc19.png)
I hope that the edge can switch between different networks freely after joining KubeEdge, without affecting the connection with the cloud.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Wired network card information：
![image](https://user-images.githubusercontent.com/67575704/116026681-c3286e00-a685-11eb-8817-be30d49e6183.png)
Wireless card information：
![image](https://user-images.githubusercontent.com/67575704/116026697-c91e4f00-a685-11eb-9925-1679a1104f40.png)
**Environment**:
- Kubernetes version (use `kubectl version`):
![image](https://user-images.githubusercontent.com/67575704/116026857-1ac6d980-a686-11eb-9cf8-fb61a4513fdd.png)

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
![image](https://user-images.githubusercontent.com/67575704/116026869-22867e00-a686-11eb-829c-3f24395415be.png)
![image](https://user-images.githubusercontent.com/67575704/116026878-27e3c880-a686-11eb-96f9-4120bb630523.png)

**Comment by GsssC** [comment]
Sorry we have not supported multi-network-interface now. Welcome to add this feature! :)
Edgecore will only try to use network interface recorded in here:
https://github.com/kubeedge/kubeedge/blob/5daf35a3a9f68340ba3bbb70f84d4e6230501221/pkg/apis/componentconfig/edgecore/v1alpha1/types.go#L173-L176

**Comment by GsssC** [comment]
Sorry we have not supported multi-network-interface now. Welcome to add this feature! :)

**Comment by luoqian1999** [comment]
> Sorry we have not supported multi-network-interface now. Welcome to add this feature! :)

Thanks for your response,I've been aware of the problem.

**Comment by fisherxu** [comment]
Has any error logs when edge node can't connect to cloud node after switch to wireless?
