### ISSUE TITLE
 error: failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: length too large

### ISSUE THREAD

**Issue by magnate3** [kubeedge/kubeedge#2816]
0427 15:15:12.522322   40945 server.go:324] failed to sign a certificate, error: failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: length too large
F0427 15:15:12.522342   40945 cloudhub.go:74] failed to parse ECPrivateKey, err: x509: failed to parse EC private key: asn1: structure error: length too large
 
root@ubuntu:~/cmd# ./cloudcore --version
KubeEdge v1.6.1

root@ubuntu:~/cmd# uname -a
Linux ubuntu 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:10:24 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
-

root@ubuntu:~/cmd# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}

**Comment by fisherxu** [comment]
Have you used your own certs? @magnate3

**Comment by magnate3** [comment]
@fisherxu  all  certs produced by build/tools/certgen.sh

 
root@ubuntu:~/cmd# ls /etc/kubeedge/ca/
rootCA.crt  rootCA.key  rootCA.srl  streamCA.crt
root@ubuntu:~/cmd# ls /etc/kubeedge/certs/
edge.crt  edge.csr  edge.key  stream.crt  stream.csr  stream.key
