### ISSUE TITLE
E0428 05:20:04.019583   10210 objectsync.go:38] failed to get obj(gvr:/v1, Resource=pods,namespace:kube-system,name:kube-proxy-bp4h2), pods "kube-proxy-bp4h2" not found

### ISSUE THREAD

**Issue by Justin-Young** [kubeedge/kubeedge#2819]
**What happened and what you expected to happen**:
When the edge node was not ready, I deleted a pod on that node. But the pod couldn't be deleted and was in a state of terminating, so I forcedly restarted the edge node because restarting edgecore.service didn't seem to work  -_-. After that, the pod was deleted, but the cloudcore always generates an error message like `E0428 05:20:04.019583   10210 objectsync.go:38] failed to get obj(gvr:/v1, Resource=pods,namespace:kube-system,name:kube-proxy-bp4h2), pods "kube-proxy-bp4h2" not found`. I wanna know how to make this error message disappear without resetting. Could you help me please?
**How to reproduce it (as minimally and precisely as possible)**:
[https://kubeedge.io/en/docs/setup/keadm/](https://kubeedge.io/en/docs/setup/keadm/)#enable kubectl logs feature
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.6.1

**Comment by GsssC** [comment]
@Rachel-Shao PTAL

**Comment by Rachel-Shao** [comment]
@Justin-Young   When you delete a pod normally, CloudHub will receive a msg whose operation is delete. Then the corresponding ObjectSync will be deleted.
But you used some inelegant deletion methods, which caused the pod to be deleted but the ObjectSync may still there. Therefore, the SyncController detects the ObjectSync when processing synchronization but finds that there is no corresponding pod, so an error is reported. 

The solution may have been proposed by #2812 , but now I think you can only choose to ignore it.

**Comment by Justin-Young** [comment]
Okay, thank you very much! ^_^
