### ISSUE TITLE
how to build connection with cloud and edge 

### ISSUE THREAD

**Issue by RocMe** [kubeedge/kubeedge#282]
**Which jobs are failing**:run kubeedge 

**Which test(s) are failing**:1."ERROR config/kube.go:41 kube config not set" ,sorry,I am not clear about how to set kube.go this file ,could you help me 
2.I am not sure how to use edge.crt  edge.key
3. "ERROR:wsclient/websocket.go:76 error when init websocket connection: dial tcp 0.0.0.0:10000: connect: connection refused"

**Since when has it been failing**:when I start to build ./edgecontroller  ./edge_core 

**Reason for failure**: not sure 

**Anything else we need to know**: no

**Comment by m1093782566** [comment]
@RocMe 

I would suggest you take a look at the README and follow the instructions step by step.

**Comment by m1093782566** [comment]
> 1."ERROR config/kube.go:41 kube config not set"

@sids-b When can we add instructions on connect kube-apiserver with https/tls?

**Comment by sids-b** [comment]
Hi @RocMe , Please have a look at this issue https://github.com/kubeedge/kubeedge/issues/235 and this PR https://github.com/kubeedge/kubeedge/pull/275 for better clarity. Please feel free to ping me(Siddharth Bhadri) on KubeEdge Slack for any other issue you face :)

**Comment by RocMe** [comment]
> feel free



> @RocMe
> 
> I would suggest you take a look at the README and follow the instructions step by step.
thank you .I will see

**Comment by RocMe** [comment]
> Hi @RocMe , Please have a look at this issue #235 and this PR #275 for better clarity. Please feel free to ping me(Siddharth Bhadri) on KubeEdge Slack for any other issue you face :)

Thank you for your kind reply. I will read it .

**Comment by sids-b** [comment]
I am closing this issue. Please ping us on slack for further queries. Thanks @RocMe
