### ISSUE TITLE
How to deploy Python program on kubeedge?

### ISSUE THREAD

**Issue by Xxllj834738992** [kubeedge/kubeedge#2826]
I need to do such a scenario: model training and prediction in the cloud, data acquisition, preprocessing, feature extraction and other data processing in the edge.
Any help and discussion are welcome！
Thanks a lot！！

**Comment by bensch98** [comment]
I have a similiar use-case. Is it possible to use heterogeneous edge-devices, e.g. like some Raspberry Pi's and also some devices running Windows?

**Comment by Xxllj834738992** [comment]
> I have a similiar use-case. Is it possible to use heterogeneous edge-devices, e.g. like some Raspberry Pi's and also some devices running Windows?

Yes, i have a Raspberry Pi's, please give me some advise. In addition, I hope to see your source code. Thanks a lot!
