### ISSUE TITLE
edge.crt": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by magnate3** [kubeedge/kubeedge#2837]
certmanager.go:91] Error: failed to get edge certificate from the cloudcore, error: Get "https://10.10.14.82:10002/edge.crt": x509: certificate signed by unknown authority
goroutine 108 [running]:
Environment:

Kubernetes version (use kubectl version):
root@ubuntu:/cmd# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm64"}
root@ubuntu:/cmd#
KubeEdge version(e.g. cloudcore --version and edgecore --version):
 

root@ubuntu:~/cmd#  ./cloudcore --version
KubeEdge v1.6.1

edgecore --version
2021-05-10 11:36:06.885673 I | INFO: Install client plugin, protocol: rest
2021-05-10 11:36:06.889706 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.6.1-dirty  

root@ubuntu:/cmd# go version
go version go1.14.6 linux/arm64
root@ubuntu:/cmd# uname -a
Linux ubuntu 5.0.0-23-generic #2418.04.1-Ubuntu SMP Mon Jul 29 16:10:24 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
root@ubuntu:/cmd# lscpu
Architecture: aarch64
Byte Order: Little Endian
CPU(s): 64
On-line CPU(s) list: 0-63
Thread(s) per core: 1
Core(s) per socket: 32
Socket(s): 2
NUMA node(s): 4
Vendor ID: ARM
Model: 2
Model name: Cortex-A72
Stepping: r0p2
BogoMIPS: 100.00
L1d cache: 32K
L1i cache: 48K
L2 cache: 1024K
L3 cache: 16384K
NUMA node0 CPU(s): 0-15
NUMA node1 CPU(s): 16-31
NUMA node2 CPU(s): 32-47
NUMA node3 CPU(s): 48-63
Flags: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

**Comment by Jeaniowang** [comment]
hi，we meet the same problem,did you solve it?

**Comment by Jeaniowang** [comment]
We have a similar problem and solved by this issue, You can see if it works for you
[https://github.com/kubeedge/kubeedge/issues/2844](url)
