### ISSUE TITLE
[Init websocket connection failed x509: certificate is not valid for any names, but wanted to match xxx

### ISSUE THREAD

**Issue by Jeaniowang** [kubeedge/kubeedge#2844]
**What happened and what you expected to happen**:
Hi, we use kubeedge 1.6.1, when we conntect the Cloudcore by dns, the server option config as this "server: wss://KubeEdge:10000" in the edgecore.yaml, we met the error as follow picture,

![image](https://user-images.githubusercontent.com/19906335/118091684-b170f580-b3fd-11eb-829b-ddab2e249257.png)

 have someone meet this problem? 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/arm64"}
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): KubeEdge v1.6.1

**Comment by MiaoZhou** [comment]
same problem

**Comment by Jeaniowang** [comment]
we solved this problem, help from this issue: [https://github.com/kubeedge/kubeedge/issues/2070](url)

![image](https://user-images.githubusercontent.com/19906335/118104041-357ea980-b40d-11eb-910f-6efdf4dbf100.png)

or see keadm help doc, add the --domainname config on the Cloud:
[https://github.com/kubeedge/kubeedge/blob/v1.6.1/docs/setup/keadm.md](url)

![image](https://user-images.githubusercontent.com/19906335/118104370-a2923f00-b40d-11eb-83f8-db9fdfebc68a.png)

before restart the edgecore to connect the Cloud, don't forget to delete the old cert file, because in the edgecore core, if the old cert is exist, it does not to re generate the new cert!
