### ISSUE TITLE
edgecore Init websocket connection failed websocket: bad handshake

### ISSUE THREAD

**Issue by qdj0226** [kubeedge/kubeedge#2849]
**What happened**:
Hi guys,
When I tried to join the edge device, I failed to register cloudcore. The journalctl reported: bad handshake.
Does anyone know how to fix this?

`5月 18 15:40:48 k8s-node1 edgecore[27641]: E0518 15:40:48.036303   27641 edged_status.go:400] register node failed, error: timeout to send message
5月 18 15:40:48 k8s-node1 edgecore[27641]: E0518 15:40:48.036324   27641 edged_status.go:402] response from cloud core: <nil>
5月 18 15:40:48 k8s-node1 edgecore[27641]: E0518 15:40:48.036338   27641 edged_status.go:430] Register node failed: timeout to send message
5月 18 15:40:58 k8s-node1 edgecore[27641]: I0518 15:40:58.049142   27641 edged_status.go:388] Attempting to register node edge-node-2
5月 18 15:41:11 k8s-node1 edgecore[27641]: I0518 15:41:11.242134   27641 websocket.go:51] Websocket start to connect Access
5月 18 15:41:11 k8s-node1 edgecore[27641]: E0518 15:41:11.264011   27641 ws.go:78] dial websocket error(websocket: bad handshake), response message: response code: 404, response body: 404 page not found
5月 18 15:41:11 k8s-node1 edgecore[27641]: E0518 15:41:11.264025   27641 websocket.go:90] Init websocket connection failed websocket: bad handshake
5月 18 15:41:16 k8s-node1 edgecore[27641]: E0518 15:41:16.284683   27641 ws.go:78] dial websocket error(websocket: bad handshake), response message: response code: 404, response body: 404 page not found
5月 18 15:41:16 k8s-node1 edgecore[27641]: E0518 15:41:16.284701   27641 websocket.go:90] Init websocket connection failed websocket: bad handshake
5月 18 15:41:21 k8s-node1 edgecore[27641]: E0518 15:41:21.304477   27641 ws.go:78] dial websocket error(websocket: bad handshake), response message: response code: 404, response body: 404 page not found
5月 18 15:41:21 k8s-node1 edgecore[27641]: E0518 15:41:21.304492   27641 websocket.go:90] Init websocket connection failed websocket: bad handshake
5月 18 15:41:25 k8s-node1 edgecore[27641]: I0518 15:41:25.492848   27641 process.go:525] start to sync pod status in edge-store to cloud
5月 18 15:41:25 k8s-node1 edgecore[27641]: I0518 15:41:25.492961   27641 process.go:532] list pod status, no record, skip sync
5月 18 15:41:26 k8s-node1 edgecore[27641]: E0518 15:41:26.323141   27641 ws.go:78] dial websocket error(websocket: bad handshake), response message: response code: 404, response body: 404 page not found
5月 18 15:41:26 k8s-node1 edgecore[27641]: E0518 15:41:26.323163   27641 websocket.go:90] Init websocket connection failed websocket: bad handshake
5月 18 15:41:31 k8s-node1 edgecore[27641]: E0518 15:41:31.344313   27641 ws.go:78] dial websocket error(websocket: bad handshake), response message: response code: 404, response body: 404 page not found
5月 18 15:41:31 k8s-node1 edgecore[27641]: E0518 15:41:31.344338   27641 websocket.go:90] Init websocket connection failed websocket: bad handshake
5月 18 15:41:36 k8s-node1 edgecore[27641]: E0518 15:41:36.344490   27641 edgehub.go:89] connection failed: max retry count reached when connecting to cloud, will reconnect after 30s`

**What you expected to happen**:
Register to cloudcore
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.1
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):  1.6.1
-  Master: centos-release-7-6.1810.2.el7.centos.x86_64
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by ttlv** [comment]
Please make sure the cloudcore is running normally in the cloud
