### ISSUE TITLE
kubeedge1.6 deploy nginx failed for 'Get ServiceAccount Token unsupported'

### ISSUE THREAD

**Issue by ccc7574** [kubeedge/kubeedge#2850]
**After kube edge cluster been init, I copy the deployment yaml from kubedge code repo**:
The nginx pod hang for the status "ContainerCreating",
then I checked the edgecore log and got below info, and I also checked the ca and cert file :

5月 18 18:06:39 banmaserver02 edgecore[121507]: E0518 18:06:39.702672  121507 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/projected/99d48a0c-a472-4b79-8b71-6626d945e77f-kube-api-access-qvp9r podName:99d48a0c-a472-4b79-8b71-6626d945e77f nodeName:}" failed. No retries permitted until 2021-05-18 18:08:41.702620104 +0800 CST m=+6485.992849244 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"kube-api-access-qvp9r\" (UniqueName: \"kubernetes.io/projected/99d48a0c-a472-4b79-8b71-6626d945e77f-kube-api-access-qvp9r\") pod \"nginx-deployment-66c7f7b68c-vrvdt\" (UID: \"99d48a0c-a472-4b79-8b71-6626d945e77f\") : GetServiceAccountToken unsupported"
5月 18 18:06:43 edgecore[121507]: I0518 18:06:43.962271  121507 edged_status.go:196] Sync VolumesInUse: []
5月 18 18:06:53 edgecore[121507]: I0518 18:06:53.989860  121507 edged_status.go:196] Sync VolumesInUse: []
5月 18 18:07:04 edgecore[121507]: I0518 18:07:04.017362  121507 edged_status.go:196] Sync VolumesInUse: []
5月 18 18:07:14 edgecore[121507]: I0518 18:07:14.044580  121507 edged_status.go:196] Sync VolumesInUse: []
5月 18 18:07:24 edgecore[121507]: I0518 18:07:24.072245  121507 edged_status.go:196] Sync VolumesInUse: []
5月 18 18:07:31 edgecore[121507]: I0518 18:07:31.341386  121507 edged.go:881] worker [3] get pod addition item [nginx-deployment-66c7f7b68c-vrvdt]
5月 18 18:07:31 edgecore[121507]: I0518 18:07:31.341434  121507 edged.go:949] start to consume added pod [nginx-deployment-66c7f7b68c-vrvdt]
5月 18 18:07:34 edgecore[121507]: I0518 18:07:34.099660  121507 edged_status.go:196] Sync VolumesInUse: []
5月 18 18:07:36 edgecore[121507]: I0518 18:07:36.164782  121507 process.go:525] start to sync pod status in edge-store to cloud
5月 18 18:07:37 edgecore[121507]: I0518 18:07:37.231082  121507 edged_volumes.go:54] Using volume plugin "kubernetes.io/empty-dir" to mount wrapped_kube-api-access-4kcc8
5月 18 18:07:37 edgecore[121507]: E0518 18:07:37.241700  121507 projected.go:201] Error preparing data for projected volume kube-api-access-4kcc8 for pod kubeedge/kubeedge-counter-app-59d94d964c-cprxm: GetServiceAccountToken unsupported
5月 18 18:07:37 edgecore[121507]: I0518 18:07:37.241759  121507 record.go:24] Warning FailedMount MountVolume.SetUp failed for volume "kube-api-access-4kcc8" : **GetServiceAccountToken unsupported**

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f deployment.yaml

**Environment**:
- Kubernetes version (v1.21.0):
- KubeEdge version(v1.6.1):

**Comment by ttlv** [comment]
Cloud you please tell me what's your OS

**Comment by champels** [comment]
I have the same issue. I'm executing from an Ubuntu 20.04.2 LTS in a MacOS virtual machine orchestrated with Multipass.

**Comment by ccc7574** [comment]
> Cloud you please tell me what's your OS

My OS  is CentOS 7.9

**Comment by champels** [comment]
@ccc7574, I have been able to solve it by myself. I discovered in the [compatibility matrix](https://github.com/kubeedge/kubeedge#kubernetes-compatibility) does not include Kubernetes 1.21. I installed a 1.19 version and is not longer producing this error.

**Comment by xiehaoina** [comment]
Anyone would like to make kubeedge compatible to higher kubernernes ?

**Comment by fisherxu** [comment]
> Anyone would like to make kubeedge compatible to higher kubernernes ?


The latest version of K8s has been supported in KubeEdge v1.7.2 :) @all
