### ISSUE TITLE
web app demo can not receive track info based on Kubeedge 1.6.1 build on Aliyun

### ISSUE THREAD

**Issue by flixgithub** [kubeedge/kubeedge#2855]
**What happened**:
1. the edge node show ready state in the cluster but not receive messge from topic "$hw/events/device/speaker-01/twin/update/document"
2. edgecore and mqtt and cloud core all are in the normal running state

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Kubernetes version (use kubectl version):
-----V1.18.8
KubeEdge version(e.g. cloudcore --version and edgecore --version):
-----cloudcore version------V1.6.1
-----edgecore version------V1.6.1

Cloud nodes Environment:
Hardware configuration (e.g. lscpu):
----- edge node   arm64  4core  1.5G
----- cloud node  x86_64 16core 2.4G
OS (e.g. cat /etc/os-release):
-----edge node   Ubuntu 20.04.2 LTS
----- cloud node  CentOS Linux release 7.6.1810 (Core)
Go version (e.g. go version):
----1.13

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

1. mqtt log show the topic is listened:
![image](https://user-images.githubusercontent.com/6768036/118988298-a7c62f80-b9b3-11eb-9517-1671db5f5625.png)
2. pi-player-app is running and can not receive the correct message:
![image](https://user-images.githubusercontent.com/6768036/118988403-bdd3f000-b9b3-11eb-93df-f15df463dfd1.png)
3. cloud side trigger several play requests to the edge side but no track will be played:
![image](https://user-images.githubusercontent.com/6768036/118988634-f2e04280-b9b3-11eb-855e-f4bbfc4eac88.png)

**Comment by wwwlookformetop** [comment]
I also have this problem, and it is preliminarily judged that it is because of MQTT. As long as the topic with $sign, it cannot subscribe to publish

**Comment by wwwlookformetop** [comment]
Who can give us a hand ？

**Comment by wwwlookformetop** [comment]
I have already solved the problem, when you deploy related equipment, if your kubeedge version upgrade, your old equipment, it will not be able to update, causing the $/ hw/events/device/counter twin/update theme don't get the message

**Comment by wwwlookformetop** [comment]
![Uploading image.png…]()

**Comment by wwwlookformetop** [comment]
![image](https://user-images.githubusercontent.com/23631902/119622682-f4898a80-be39-11eb-87e6-c29a672c9dfa.png)

**Comment by flixgithub** [comment]
> I have already solved the problem, when you deploy related equipment, if your kubeedge version upgrade, your old equipment, it will not be able to update, causing the $/ hw/events/device/counter twin/update theme don't get the message

After i tried to change the kubeedge to 1.5.0 version(before is 1.6.1 ), i can receive the request and respsonse then them demo works, i think this will be some issues in the 1.6.x version between edge side and cloud side when communicate by the MQTT topic
