### ISSUE TITLE
metamanager can't catch the default/secret/default-token-XXXXX. How is this resource synchronized to the edge?

### ISSUE THREAD

**Issue by yz271544** [kubeedge/kubeedge#2862]
**What happened and what you expected to happen**:

May 20 15:13:04 ke-edge2 edgecore[4828]: E0520 15:13:04.027940    4828 metaclient.go:125] send sync message default/secret/default-token-r8tgw failed, error:timeout to get response, retries: 1
May 20 15:13:04 ke-edge2 edgecore[4828]: I0520 15:13:04.028193    4828 process.go:469] ########## process get: req[{Header:{ID:212af154-bfcc-40ee-b8f5-de5b313a106b ParentID: Timestamp:1621494724017 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:query Resource:default/secret/default-token-r8tgw} Content:<nil>}], resp[{Header:{ID: ParentID: Timestamp:0 ResourceVersion: Sync:false} Router:{Source: Group: Operation: Resource:} Content:<nil>}], err[timeout to get response]
May 20 15:13:04 ke-edge2 edgecore[4828]: E0520 15:13:04.028209    4828 process.go:471] remote query failed: timeout to get response

**How to reproduce it (as minimally and precisely as possible)**:
1. ../tools/certgen.sh buildSecret | tee ./06-secret.yaml;
2. update 05-config.yaml, add the following:
```yaml
dynamicController:
  enable: true
```
3. update 03-clusterrole.yaml, add the following:
```yaml
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules", "serviceentries", "gateways"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```
4. Execute these YAML files in turn to make CloudCore run in the cloud pod and expose a NodePort;

5. Config the edgecore.yaml on the edge node, for edgemesh of daemonset.
```yaml
...
  edgeMesh:
    enable: false
...
metaManager:
...
  metaServer:
    enable: true
...
```
Of course, config `httpServer`, `quic/server`, `websocket/server` ip and port, and the token.
6. Start edge by the `systemctl start edgecore` on the edge nodes;
7. Start the edgemesh use daemonset. 
```shell
$ kubectl apply -f 03-configmap.yaml 
configmap/edgemesh-gateway-cfg created
$ kubectl apply -f 04-deployment.yaml 
deployment.apps/edgemesh-gateway created
```
8. Any pod that runs at the edge is arbitrarily pulled up and is in a `Pending` state. You can see this log in the journalctl of edgecore.

**Anything else we need to know?**:
1. 按照以上整个部署过程，直接一次性部署edgemesh为daemonset，就会出现以上报错。
2. 而先部署好整个kubeedge，拉起应用测试完，再修改为独立的edgemesh，此刻default/secret/default-token-xxxxx已经被同步到边缘sqlite中，这样情况测试则是没有问题的。

报错在https://github.com/kubeedge/kubeedge/blob/aa3ea9e69718f11ada33dc08a014e790a70d3bc7/edge/pkg/metamanager/process.go#L469，

```go
		resp, err := beehiveContext.SendSync(
			string(metaManagerConfig.Config.ContextSendModule),  // socket ==> edgehub
			message,
			time.Duration(metaManagerConfig.Config.RemoteQueryTimeout)*time.Second)
		klog.Infof("########## process get: req[%+v], resp[%+v], err[%+v]", message, resp, err)
```

 Router:{
          Source:edged 
          Group:meta 
          Operation:query 
          Resource:default/secret/default-token-r8tgw
        } 
我并没有在edgehub找到处理该消息的相关代码。
但如果先部署好整个kubeedge，再修改为edgemesh的方式，是可以的。所以想知道这个secret在哪里进行了同步操作？为什么直接使用edgemesh的daemonset就没有成功呢？

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by k-9527** [comment]
The issue has been resolved yet? I also got this with version 1.5.0
