### ISSUE TITLE
For `NegotiateTunnelPort`(cloud/cmd/cloudcore/app/server.go)  method in version 1.7.0

### ISSUE THREAD

**Issue by insrat** [kubeedge/kubeedge#2884]
Please do code review.

When the ConfigMaps exists and localIP value in `IPTunnelPort` map, no valid value is returned.

**Comment by fisherxu** [comment]
We have merged a pr https://github.com/kubeedge/kubeedge/pull/2876, please take a look that whether it resolve this issue:)
