### ISSUE TITLE
[PROPOSAL] More programmer friendly beehive framework

### ISSUE THREAD

**Issue by tedli** [kubeedge/kubeedge#289]
**What would you like to be added**:

Please refer to this demo:
https://github.com/tenxcloud/serviced/blob/master/example/main.go

``` golang
type EdgeCore interface {
	CreatePod(pod Pod) (result PodCreationResult)
	// ...... other methods
}

type EdgeD interface {
	CreatePod(pod Pod) (status PodStatus)
	// ...... other methods
}

type edgeCoreImpl struct {
	EdgeDModule EdgeD  // can be injected
	// ...... other dependencies
}

func (eci edgeCoreImpl) CreatePod(pod Pod) (result PodCreationResult) {
	status := eci.EdgeDModule.CreatePod(pod)
	result := status.ToResult()
	return
}

// at edgecontroller side

edgeCore := kernel.ResolveService(new(EdgeCore))

// resolves out a transparent proxy which convert method call to message then send
// through websocket or other transport object.
result := edgeCore.CreatePod(theNewCreatePodFromEvent)
```

**Why is this needed**:

beehive framework now has points that now good enough:

1. Hard for one who new to kubeedge code to understand interactions between modules (without accurate sequence diagram);
2. Hard to debug (nor do unit test);
3. Easy to make a mistake;
4. A module can 'Receive' messages which should not be received by this module.

**Comment by m1093782566** [comment]
@tedli 

We just create a independent repository for beehive, please check: https://github.com/kubeedge/beehive. You can move the issue to the beehive repo. FYI :)
