### ISSUE TITLE
altas500上是否支持使用keadm安装edgecore

### ISSUE THREAD

**Issue by 1597583589** [kubeedge/kubeedge#2891]
**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by ttlv** [comment]
Euler OS is not supported by keadm so you can't install edgecore by keadm
