### ISSUE TITLE
In router module how set a wildcard topic for a RuleEndpoint

### ISSUE THREAD

**Issue by Imy123** [kubeedge/kubeedge#2892]
**What happened and what you expected to happen**:In router module, I want to set a wildcard topic for RuleEndpoint 
**How to reproduce it (as minimally and precisely as possible)**:
apiVersion: rules.kubeedge.io/v1
kind: RuleEndpoint
metadata:
  name: my-rest
  labels:
    description: test
spec:
  ruleEndpointType: "rest"
  properties: {}

---
apiVersion: rules.kubeedge.io/v1
kind: RuleEndpoint
metadata:
  name: my-eventbus
  labels:
    description: test
spec:
  ruleEndpointType: "eventbus"
  properties: {}

---
apiVersion: rules.kubeedge.io/v1
kind: Rule
metadata:
  name: my-rule-eventbus-rest
  labels:
    description: test
spec:
  source: "my-eventbus"
  #default/$ke/events/+/device/data/update
  sourceResource: {"topic": "$ke/events/device/+/data/update","node_name": "edgenode-dzag"}
  target: "my-rest"
  targetResource: {"resource": "http://192.168.5.118:8080/device"}

in this file, I want to set a wildcard topic '$ke/events/device/+/data/update', but it works not meet expectations
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by liufen90** [comment]
router didn't support wildcard topic, maybe we can support this later, if you are interested in this feature, you can join us to support this feature.

**Comment by liufen90** [comment]
cc @WintonChan

**Comment by Imy123** [comment]
> Router didn't support wildcard topic, maybe we can support this later, if you are interested in this feature, you can join us to support this feature.

ok, how to join your team

**Comment by WintonChan** [comment]
@Imy123 I found the router does not support wildcard topic  because messages send to cloud with the real topic need exact match. The res of message  from eventbus need support wildcard match.
