### ISSUE TITLE
cannot apploy ief

### ISSUE THREAD

**Issue by u2takey** [kubeedge/kubeedge#29]
cannot press apply button on https://account.huaweicloud.com/usercenter/#/applyBeta?serviceCodeP=ief, open console found 400 error for https://account.huaweicloud.com/usercenter/rest/v1.0/6bf99a32f49a4dfebfdf1544a2ab9e54/tracker

**Comment by m1093782566** [comment]
@u2takey Are you able to login and have you ever done real-name authentication?

cc @Baoqiang-Zhang

**Comment by u2takey** [comment]
@m1093782566 tks, solved, its real-name-authentication issue.

**Comment by m1093782566** [comment]
no problem, @u2takey :)
