### ISSUE TITLE
 dial websocket error(x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "KubeEdge"))

### ISSUE THREAD

**Issue by 1597583589** [kubeedge/kubeedge#2903]
**Which jobs are failing**:

**Which test(s) are failing**:

**Since when has it been failing**:

**Reason for failure**:

**Anything else we need to know**:

**Comment by Rachel-Shao** [comment]
There is a problem with the certificate, please try the method mentioned in this issue #1736
