### ISSUE TITLE
How to use flannel and kube-proxy on kubeedge

### ISSUE THREAD

**Issue by blackdobb** [kubeedge/kubeedge#2911]
**What happened and what you expected to happen**:
I want to use flannel and kube-proxy on kubeedge, but here comes to the problem, the flannel on my edge side always be like error:
```
[root@master-7-1 ~]# kubectl logs kube-flannel-ds-nrxdv -n kube-system
ERROR: logging before flag.Parse: I0617 02:30:16.305152       1 main.go:519] Determining IP address of default interface
ERROR: logging before flag.Parse: I0617 02:30:16.306139       1 main.go:532] Using interface with name eth0 and address 172.30.48.21
ERROR: logging before flag.Parse: I0617 02:30:16.306211       1 main.go:549] Defaulting external address to interface address (172.30.48.21)
W0617 02:30:16.306279       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ERROR: logging before flag.Parse: E0617 02:30:16.512708       1 main.go:250] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-nrxdv': Get "https://10.109.192.219:9336/api/v1/namespaces/kube-system/pods/kube-flannel-ds-nrxdv": dial tcp 10.109.192.219:9336: connect: no route to host
```
**How to reproduce it (as minimally and precisely as possible)**:
I wish i it turns to running.
**Anything else we need to know?**:
I  modified kube-flannel daemonset about the affinity of the flannel part, also i added KUBERNETES_SERVICE_HOST, KUBERNETES_SERVICE_PORT environment variables.
**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by ZBoIsHere** [comment]
kubeedge v1.6.0 support list-watch on edge node, you can try reinstall flannel and kube-proxy at your edgenode.
