### ISSUE TITLE
question about the  Collaboration between cloud and edge

### ISSUE THREAD

**Issue by wd900309jay** [kubeedge/kubeedge#2917]
**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by fisherxu** [comment]
What's your question? :) @wd900309jay

**Comment by wd900309jay** [comment]
> What's your question? :) @wd900309jay

Sorry, my English is pool!
My question is that I have a scene should be realizing.it is that when the connection of edge between cloud is disconnect, how can I manage the edge node by kubeedge go through the K8S Api on edge node.

我的问题是，当云端和边缘端的连接断开以后，边缘端如何通过kubeedge的特性，去管理该边缘节点，包括原本在云端实现的，由k8s api支持的应用部署、节点管理等操作。
如果kubeedge支持这种特性，边缘端会自动接管这些原本属于云端的操作权限么？
谢谢您！
