### ISSUE TITLE
The subresource Status of the routing module crd resource Rule failed to update

### ISSUE THREAD

**Issue by xujiaja** [kubeedge/kubeedge#2920]
**What happened**:
When I am testing custom sending messages，I found that the number of times the message was forwarded was always 0，The resource field is Status.SuccessMessages
**What you expected to happen**:
When I send a message, the Rule.Status.SuccessMessages increases
**How to reproduce it (as minimally and precisely as possible)**:
Follow this [tutorial，](https://kubeedge.io/en/docs/developer/custom_message_deliver/#how-to-deliver-custom-messages)
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.1
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.7.1

Read the source code to find the cause of this [upstream.go-updateRuleStatus](https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/edgecontroller/controller/upstream.go)
```go
rule, err = uc.crdClient.RulesV1().Rules(namespace).Get(context.Background(), ruleID, metaV1.GetOptions{})
			if err != nil {
				klog.Warningf("message: %s process failure, get rule with error: %s, namespaces: %s name: %s", msg.GetID(), err, namespace, ruleID)
				continue
			}
			content, ok := msg.Content.(routerrule.ExecResult)
			if !ok {
				klog.Warningf("message: %s process failure, get rule content with error: %s, namespaces: %s name: %s", msg.GetID(), err, namespace, ruleID)
				continue
			}
			if content.Status == "SUCCESS" {
				rule.Status.SuccessMessages++
			}
			if content.Status == "FAIL" {
				rule.Status.FailMessages++
				errSlice := make([]string, 0)
				rule.Status.Errors = append(errSlice, content.Error.Detail)
			}
			newStatus := &rulesv1.RuleStatus{}
			body, err := json.Marshal(newStatus)
			if err != nil {
				klog.Warningf("message: %s process failure, content marshal err: %s", msg.GetID(), err)
				continue
			}
			var data []byte = []byte(body)
			_, err = uc.crdClient.RulesV1().Rules(namespace).Patch(context.Background(), ruleID, controller.MergePatchType, data, metaV1.PatchOptions{})
			if err != nil {
				klog.Warningf("message: %s process failure, update ruleStatus failed with error: %s, namespace: %s, name: %s", msg.GetID(), err, namespace, ruleID)
			} else {
				klog.Infof("UpdateRulestatus successfully!")
			}

```
There are two problems here. A newStatus is only initialized. Second, Rule.Status is a sub-resource and needs to be enabled in crd yaml

**Comment by xujiaja** [comment]
The same problem exists in resource Device.Dtatus, I have fixed this bug. Can I submit a merge request?

**Comment by algebra2k** [comment]
I think this pr makes sense, I had a similar problem.
