### ISSUE TITLE
timeout to get  secrets or configmap  response 

### ISSUE THREAD

**Issue by qugq0228** [kubeedge/kubeedge#2929]
**What happened**:

send sync message kubeedge/secret/modbus-map-secret failed, error:timeout to get response, retries: 2
Couldn't get secret kubeedge/secret/modbus-map-secret: get secret from metaManager failed, err: timed out waiting for the condition

**What you expected to happen**:
can get response 

**How to reproduce it (as minimally and precisely as possible)**:
when the node is first node connected to the cloud，or the cloud and the edge network is unhealthy .

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
    1.6.1
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by qugq0228** [comment]
there check if the msg resourceVersion <= ObjectResourceVersion，but sometime，if the network is unhealty，edge is possible to re request the same resource https://github.com/kubeedge/kubeedge/blob/a9ca6911539569ba961097448480fe89f7df9696/cloud/pkg/cloudhub/channelq/channelq.go#L115-L125

**Comment by vcozzolino** [comment]
I have a similar issue. I'm trying to deploy a fluentd DaemonSet and the pods on the edge nodes remain forever in a pending state due to this error:

`
send sync message kube-logging-0/secret/fluentd-token-rmpd6 failed, error:timeout to get response, retries: 1
`
