### ISSUE TITLE
Support PV\PVC on edge

### ISSUE THREAD

**Issue by qizha** [kubeedge/kubeedge#293]
**What would you like to be added**:
Add PC/PVC support on edge

**Why is this needed**:
There are some user scenarios need the local shared storage:
1. In a system to do video data collection and analysis, one application may beed to store the video data into a NAS device and another application read the data to do analysis.
2. In a big computing task flow execution, each tasks interactive the big data with the shared storage.
So we need to support such scenarios especially share data with a NAS device. So maybe NFS support is good start.

**Comment by sids-b** [comment]
This issue is same as #272 . 
cc @CindyXing @m1093782566

**Comment by CindyXing** [comment]
Yes, this is a dup of #272. I am closing this one and assign Baoqiang to #272. Thanks.
