### ISSUE TITLE
cloudcore as system service，fialed to restart!

### ISSUE THREAD

**Issue by MoXinQian** [kubeedge/kubeedge#2947]
kubeedge1.7.0：
execute：sudo ln /etc/kubeedge/cloudcore.service /etc/systemd/system/cloudcore.service
errorinfo:
![image](https://user-images.githubusercontent.com/82023054/124893184-18c9b100-e00d-11eb-8fda-ba412730ae3b.png)

**Comment by gccio** [comment]
maybe you need to paste the log to us.
