### ISSUE TITLE
Is Mapper an application or a driver?

### ISSUE THREAD

**Issue by Imy123** [kubeedge/kubeedge#2949]
I want to know, mapper is a application or a driver

**Comment by ttlv** [comment]
well good question, on the one hand mapper is a application which run in kubeedge and one the other hand mapper is a driver for the physical device.

**Comment by Imy123** [comment]
> well good question, on the one hand mapper is an application which run in kubeedge and one the other hand mapper is a driver for the physical device.

thinks, I have another question, Is the relationship between mapper and device one-to-one or one-to-many

**Comment by ttlv** [comment]
> > well good question, on the one hand mapper is an application which run in kubeedge and one the other hand mapper is a driver for the physical device.
> 
> thinks, I have another question, Is the relationship between mapper and device one-to-one or one-to-many
one to many is better.

**Comment by Imy123** [comment]
> > > well good question, on the one hand mapper is an application which run in kubeedge and one the other hand mapper is a driver for the physical device.
> > 
> > 
> > thinks, I have another question, Is the relationship between mapper and device one-to-one or one-to-many
> > one to many is better.

thinks
