### ISSUE TITLE
edge controller dropped the responses from edge (response of adding, deleting, modifying pod)

### ISSUE THREAD

**Issue by tedli** [kubeedge/kubeedge#296]
**What happened**:

When handling add, delete, modify event at edge core side, in code there are logics like

```
Send2Cloud()
```

to response that the event had been handled. But controller side just dropped the response.

**What you expected to happen**:

The response not be dropped, or if edge side should not response, we can remove `Send2Cloud` lines.

**How to reproduce it (as minimally and precisely as possible)**:

Default settings will reproduce stable. (but without any error or warning)

**Anything else we need to know?**:

The response message looks like this:

![image](https://user-images.githubusercontent.com/3324663/54969895-0867a680-4fbb-11e9-87ee-49e597105b2f.png)

At the end of a event handling method, called Send2Group to response:

https://github.com/kubeedge/kubeedge/blob/8f4ceaee09e09fe3cd575db325e32df98b65391a/edge/pkg/metamanager/msg_processor.go#L204-L216

But at edge controller side:

https://github.com/kubeedge/kubeedge/blob/8f4ceaee09e09fe3cd575db325e32df98b65391a/cloud/edgecontroller/pkg/controller/controller/upstream.go#L124-L160

The `resourceType ` is `pod`, so the switch/case goes to default, assign err a expressive detail, however next iteration of the outer for scope, at line 132, the err was reassigned, so the err of previous iteration (unsupported resource type) is ignored, and the response message was dropped.

**Environment**:
- KubeEdge version: v0.2
- Hardware configuration: irrelevant
- OS (e.g. from /etc/os-release): irrelevant
- Kernel (e.g. `uname -a`): irrelevant
- Others: irrelevant

**Comment by tedli** [comment]
The #260  wants an `ack` of an event handling. Whether to implement a cache or other mechanisms to solve #260 , the response is significant.

**Comment by sids-b** [comment]
@tedli , does this issue still persists in the latest releases ?

**Comment by tedli** [comment]
@sids-b 
Sorry for late reply. I haven't follow with new commits these days, and didn't confirm whether this issue still persists. Feel free to close this one. I will report new issue if I find something not as expect.
