### ISSUE TITLE
EdgeHub has a bug when Client init

### ISSUE THREAD

**Issue by Jeaniowang** [kubeedge/kubeedge#2965]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):edgecore ---v1.6.1
  - 
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - 
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
we the cloudcore reboot, we met edgecore coredump in function wsc.connection.SetWriteDeadline
![image](https://user-images.githubusercontent.com/19906335/126329747-c57e2bea-4054-4d15-9a97-bd71d4eb313b.png)

the panic log as follows:
![image](https://user-images.githubusercontent.com/19906335/126333108-794ebadb-5e34-4df2-b764-c23532880704.png)

 After we analyze the Start function in edgehub.go,  there is a process risk. when the websocket 
disconnected, it will call eh.initial() to init eh.chClient, at this time, the goroutinee  eh.routeToCloud() send the message to Cloud, But eh.chClient.Init() mybe called, wsc.connection is nil pointer, cause coredump. 
![image](https://user-images.githubusercontent.com/19906335/126332974-05e1805a-6d46-458f-a651-ada19f8e0238.png)

the err := eh.initial() function should be call before for loop to Guarantee eh.chClient is not nil, and the  eh.chClient just need to init onece, not need to init again when websocket disconnet.
 
We tried to restart the CloudCore service many times, and this problem reproduced many times.

**Comment by gccio** [comment]
`eh.initial()` can not move out of the loop.
before reconnect to cloudhub, `eh.chClient.UnInit()` will close the websocket connection. the connection can not reopen once close.

**Comment by Jeaniowang** [comment]
> `eh.initial()` can not move out of the loop.
> before reconnect to cloudhub, `eh.chClient.UnInit()` will close the websocket connection. the connection can not reopen once close.
hi gccio, eh.initial() just instantiation eh.chClient,  eh.chClient.UnInit() close the eh.chClient.connection, when next time connection, eh.chClient.Init() will init eh.chClient.connection again.  it's a new connection

**Comment by Jeaniowang** [comment]
报告收到
