### ISSUE TITLE
unable to load in-cluster configuration

### ISSUE THREAD

**Issue by tiezhuoyu** [kubeedge/kubeedge#2968]
**What happened and what you expected to happen**:
Some pods like flannel and kubevirt-operator ran well on those nodes with kubelet, but failed on nodes with edged. The logs  report error 'unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined.' 

When creating a pod with kubelet, a function 'getServiceEnvVarMap(ns string, enableServiceLinks bool) (map[string]string, error' will be executed to  acquire env from services, including KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT. However, this part is missing in edged.  
I have two questions here:
1. Is there any reason why edged does not get env from services?
2. For those pods requiring in-cluster configuration, I have to add KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT into thier yaml file manually. Is there a better way to make them get env of service automatically?

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f kube-flannel.yaml

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
cloudcore --version
KubeEdge v1.7.1
edgecore --version
2021-07-21 11:18:37.668319 I | INFO: Install client plugin, protocol: rest
2021-07-21 11:18:37.668426 I | INFO: Installed service discovery plugin: edge

**Comment by zhuyaguang** [comment]
有进展吗 目前边缘节点的普罗米修斯运行失败 因为获取不到这两个环境变量
