### ISSUE TITLE
Make token TTL consistent

### ISSUE THREAD

**Issue by stingshen** [kubeedge/kubeedge#2969]
**What would you like to be added/modified**:

Make token TTL consistent. Everytime, the TTL of token returned by `keadm gettoken` should be consistent. I expected the TTL isn't related to the time point when the token is got.

Currently, the TTL of token returned by `keadm gettoken` isn't consistent and is related to refresh point.

**Why is this needed**:

The TTL of token generated by `kubeadm` is consistent and can be specified by `--ttl` argument. The current keadm gettoken behavior is not parity with `kubeadm`.

**Comment by huapox** [comment]
+1 sugest provide --static-token for `cloudcore`?

**Comment by huapox** [comment]
got `tokenRefreshDuration: 12 ` existed (v1.13.0)

ref: https://github.com/kubeedge/kubeedge/pull/2796
