### ISSUE TITLE
TC_Test_EBUS_14 Add a new twin attribute to existing device, Test case randomly failing in Travis Env

### ISSUE THREAD

**Issue by srivatsav123** [kubeedge/kubeedge#297]
<!-- Please only use this template for submitting reports about failing tests in KubeEdge CI jobs 
![Screenshot from 2019-03-20 16-02-12](https://user-images.githubusercontent.com/39593583/54985207-66ee4e00-4fd6-11e9-942e-20a5511cb2f5.png)

**Which jobs are failing**:
edge_integration jobs 
**Which test(s) are failing**:
TC_Test_EBUS_14 Add a new twin attribute to existing device
**Since when has it been failing**:
It will fail randomly
**Reason for failure**:
Edge core is crashing, thats why Handle delete pods is panicking and also MQtt client connection refused
**Anything else we need to know**:

**Comment by m1093782566** [comment]
@srivatsav123 Can confirm if the flaky test really exists?
