### ISSUE TITLE
TC_TEST_EBUS_14 Add a new attribute to existing device, testcase is failing in Travis CI randomly

### ISSUE THREAD

**Issue by srivatsav123** [kubeedge/kubeedge#298]
![Screenshot from 2019-03-20 16-02-12](https://user-images.githubusercontent.com/39593583/54986317-6b1b6b00-4fd8-11e9-9e58-4174923f1ede.png)
**Which jobs are failing**:
edge_integration_test is failing
**Which test(s) are failing**:
TC_TEST_EBUS_14 Add a new attribute to existing device testcase is failing
**Since when has it been failing**:
It fails randomly in CI
**Reason for failure**:
Might be edge core have been crashed due to which handle pod delete panicked and MQTT client connection refused.
**Anything else we need to know**:

**Comment by sids-b** [comment]
Is this issue also solved @srivatsav123 @pavan187 with the fix you guys provided ??

**Comment by m1093782566** [comment]
Is this issue fixed or not now?

**Comment by sids-b** [comment]
By looking at the code I think this issue is not valid now as we are not connecting/disconnecting in each test case. Hence client.Connect() will not be called in Test 14
