### ISSUE TITLE
keadm document link does not exist

### ISSUE THREAD

**Issue by jeffzhu503** [kubeedge/kubeedge#2982]
I am trying to install KubeEdge on the edge side.  The link to keadm does not work and get 404.  
https://github.com/kubeedge/kubeedge/blob/master/docs/setup/keadm.md.

**Comment by llhuii** [comment]
see [keadm-v1.7.1-linux-amd64.tar.gz](https://github.com/kubeedge/kubeedge/releases/download/v1.7.1/keadm-v1.7.1-linux-amd64.tar.gz) in kubeedge [releases](https://github.com/kubeedge/kubeedge/releases).

**Comment by gy95** [comment]
> https://github.com/kubeedge/kubeedge/blob/master/docs/setup/keadm.md

ref : https://kubeedge.io/en/docs/setup/keadm/
