### ISSUE TITLE
Configuration for CloudStream and EdgeStream module don't work

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#2994]
**What happened**:
When I run `hack\local-up-kubeedge.sh` to start a local cluster, the CloudStream and EdgeStream in config file have been enabled, but after cloudcore/edgecore started, the CloudStream and EdgeStream is disabled.

Looks like the config file does't work after v1.7. And it works in v1.6.

/assign @gy95 

**What you expected to happen**:

Make the configuration file work as expected.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by fisherxu** [comment]
cc @gy95 plal :)

**Comment by gy95** [comment]
> cc @gy95 plal :)

ok

**Comment by gy95** [comment]
https://github.com/kubeedge/kubeedge/blob/fb51c63c0d2de502c0f4ee017e4078e6d02e9dbb/hack/local-up-kubeedge.sh#L103
