### ISSUE TITLE
wrong port  for metrics interface of edgenode  in version 1.7.1

### ISSUE THREAD

**Issue by snstaberah** [kubeedge/kubeedge#2996]
**What happened**:
when deploy  cloudcore in HA mode of version 1.7.1，I found that edgenode kubeletendpoint port in APIServer is modified like 10351、10352，and iptables is set 
![image](https://user-images.githubusercontent.com/8952747/127977888-3b3b0a7e-3817-4e6f-aa00-d42a90197861.png)
but when i try to access  https://nodeip:10351/metrics ,the request is received by cloudcore,but the response  is never return;
edgecore log show that  this request is send to 127.0.0.1:10351
![image](https://user-images.githubusercontent.com/8952747/127978845-15a05057-3df0-4cf3-a25c-37e95157041b.png)

**What you expected to happen**:
success to get response https://nodeip:10351/metrics from edgenode
**How to reproduce it (as minimally and precisely as possible)**:
just curl --ca  --cert  --key   https://nodeip:10351/metrics
**Anything else we need to know?**:
I look up the code and find something different for logs and metrics, is this a bug or not?
![image](https://user-images.githubusercontent.com/8952747/127978674-24437236-4e0f-4d59-9677-c4d819a264ec.png)
![image](https://user-images.githubusercontent.com/8952747/127978697-fede3ad3-69b2-485b-b98b-ad4a7819ba57.png)

**Environment**:
- KubeEdge version 1.7.1, cloudcore use new active-active HA mode

**Comment by sdghchj** [comment]
Sure it's a bug
