### ISSUE TITLE
Cross build kubeedge

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#30]
We should be able to cross build kubeedge in different OS X platforms, e.g. {linux, windows, macos} X {amd, arm, ppcp...}

- [x] cross build for arm #160
- [ ] cross build for macos

**Comment by sujithsimon22** [comment]
Created a sub issue for cross compiling kubeedge for ARM based processors

**Comment by GsssC** [comment]
This issue should be closed @sids-b

**Comment by daixiang0** [comment]
@fisherxu could close this?
