### ISSUE TITLE
Kubernetes Cluster requirements in order to deploy KubeEdge using Keadm

### ISSUE THREAD

**Issue by jeffzhu503** [kubeedge/kubeedge#3000]
I am trying to deploy KubeEdge in Google Cloud.  I have a few questions here: 

1. I will first create a Kubernetes cluster for both Cloud and Edge side.  However, what is the requirement for the Kubernetes cluster?  Do we have any? 
2. One of the limitations based on the document site is "
Currently, support of keadm is available for Ubuntu and CentOS OS. RaspberryPi supports is in-progress."  Why shall we care about the VM OS behind Kubernetes cluster?  
3. Where shall we run "keadm init --advertise-address="THE-EXPOSED-IP"?  It seems to be KubeEdge Master Node, is it correct?

**Comment by llhuii** [comment]
1. Yes, see [this link](https://github.com/kubeedge/kubeedge#kubernetes-compatibility) for k8s requirement.
2. keadm has two subcommands:
   - `init`: should be executed in the machine in which you want to run [cloudcore](https://github.com/kubeedge/kubeedge#architecture)(cloud part of kubeedge).
   - `join`: should be executed in the machine in which you want to run [edgecore](https://github.com/kubeedge/kubeedge#architecture)(edge part of kubeedge).
   So `Ubuntu and CentOS OS` is the requirement of `kubeedge`.
3. `THE-EXPOSED-IP` is the bind ip of cloudcore, which ip edgecore connects.

**Comment by jeffzhu503** [comment]
To give you an example how Kubeflow writes its deployment steps: https://www.kubeflow.org/docs/distributions/gke/deploy/deploy-cli/ .  You can read the detail on the site.  Here is the layout of the deployment doc: 
Prerequisites: how to set up the k8s cluster?  what kind of credentials? etc. 
Install the required tools: how to install keadm.  

For my particular question, how do I set up the Kubernetes to meet Kubeedeg requirements? How do I get the-exposed-ip?

**Comment by llhuii** [comment]
Yes, It is better to add more docs about setting up prerequisites, @fisherxu @kevin-wangzefeng 

For your questions:
1. From [the k8s requirements for kubeedge](https://github.com/kubeedge/kubeedge#kubernetes-compatibility), k8s 1.19 would be good. For about how to set up the k8s, you can search the k8s official docs to install this specified version.
2. Once you have choose the cloud and edge side, you can set the-exposed-ip in cloud side for that edge side can be able to access. How to get the ip? Depending on your environments, just run the shell `ip addr` command in cloud side, or get elastic ip of cloud side.

**Comment by bensch98** [comment]
@llhuii I don't think it's necessary to set up a separate Kubernetes cluster on the edge node. I always just create the cluster on my master node using `kubeadm init`. Then setup cloudcore with `keadm init` and join it via `keadm join` on the edge device.

@jeffzhu503 Install docker, docker-compose, kubelet, kubectl, kubeadm, keadm on your master node. Create the cluster with:
```bash
sudo kubeadm init --apiserver-advertise-address MASTER_IP --pod-network-cidr POD_NETWORK
```
You probably have to execute these steps but instructions are printed out to the terminal.
```bash
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```
Then run `keadm init --advertise-address MASTER_IP`
The token is printed out to the terminal, or get it via `keadm gettoken`.
Switch to edge device. 
Install docker, docker-compose, keadm on edge device and join with: `keadm join --cloudcore-ipport MASTER_IP:10000 --token TOKEN`

If a command doesn't work, try it with sudo and specifiying `--kube-config flag`.

I use both Ubuntu 20.04 VMs and Raspberry Pis. Note that you might have to change the --cgroupdriver flag for `keadm join` depending on your device.

I for myself created quite a bit of markdown files for documentation and bash scripts so I don't have to repeat all the steps over and over again. If it's needed I can submit a PR.

**Comment by llhuii** [comment]
> @llhuii I don't think it's necessary to set up a separate Kubernetes cluster on the edge node. I always just create the cluster on my master node using `kubeadm init`. Then setup cloudcore with `keadm init` and join it via `keadm join` on the edge device.

I meant the k8s cluster requirement was the cluster created by `kubeadm init` that you said.

**Comment by jeffzhu503** [comment]
@bensch98  With the help from @llhuii ,  I  successfully set up Cloudcore and Edgecore in GCP initially a few weeks ago.  But it stopped working after a weekend.  Then I had the problem to re-enable or re-join the edge nodes.  
Btw, I found the document from Sedna: https://sedna2.readthedocs.io/en/latest/.  This is a good format that KubeEdge project shall also adopt!
