### ISSUE TITLE
edgecore bug--v1.7.1

### ISSUE THREAD

**Issue by MoXinQian** [kubeedge/kubeedge#3001]
Sudden interruption of edge node！

![image](https://user-images.githubusercontent.com/82023054/128285024-c57390f0-7652-4fa7-b706-f51adcef23d9.png)

8月 04 20:15:21 hw-node01 edgecore[937]: E0804 20:15:21.780142     937 imitator.go:89] failed to access database:sql: transaction has already been committed or rolled back
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.780614     937 process.go:282] DeviceTwin receive msg
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.780751     937 process.go:66] Send msg to the TwinModule module in twin
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.780879     937 eventbus.go:90] Success in pubMQTT with topic: $hw/events/device/watcher1/twin/update/document
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.782637     937 twin.go:285] Deal document of device watcher1: build and send document
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.782768     937 twin.go:288] Deal document of device watcher1: send document
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.782891     937 twin.go:92] Twin Sync EVENT
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.783319     937 twin.go:110] Begin to update twin of the device watcher1
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.783430     937 twin.go:169] Begin to deal device twin of the device watcher1
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.783543     937 twin.go:533] dealtwincompare
8月 04 20:15:21 hw-node01 edgecore[937]: E0804 20:15:21.783967     937 imitator.go:89] failed to access database:sql: transaction has already been committed or rolled back
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.784310     937 eventbus.go:90] Success in pubMQTT with topic: $hw/events/device/watcher1/twin/update/document
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.787834     937 twin.go:285] Deal document of device watcher1: build and send document
8月 04 20:15:21 hw-node01 edgecore[937]: I0804 20:15:21.787963     937 twin.go:288] Deal document of device watcher1: send document
8月 04 20:15:21 hw-node01 edgecore[937]: E0804 20:15:21.788265     937 imitator.go:89] failed to access database:sql: transaction has already been committed or rolled back
8月 04 20:15:21 hw-node01 edgecore[937]: panic: failed to access database after 3 times try
8月 04 20:15:21 hw-node01 edgecore[937]: goroutine 128 [running]:
8月 04 20:15:21 hw-node01 edgecore[937]: k8s.io/apimachinery/pkg/util/runtime.Must(...)
8月 04 20:15:21 hw-node01 edgecore[937]:         /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
8月 04 20:15:21 hw-node01 edgecore[937]: github.com/kubeedge/kubeedge/edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator.(*imitator).Inject(0xc000a798c0, 0xc001463740, 0x24, 0x0, 0x0, 0x17b1116f29d, 0xc0013d7278, 0x7
8月 04 20:15:21 hw-node01 edgecore[937]:         /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go:48 +0x425
8月 04 20:15:21 hw-node01 edgecore[937]: github.com/kubeedge/kubeedge/edge/pkg/metamanager.(*metaManager).processUpdate(0xc000972080, 0xc001463740, 0x24, 0x0, 0x0, 0x17b1116f29d, 0xc0013d7278, 0x7, 0x0, 0xc0013d72a0, ...)
8月 04 20:15:21 hw-node01 edgecore[937]:         /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/metamanager/process.go:222 +0xf5
8月 04 20:15:21 hw-node01 edgecore[937]: github.com/kubeedge/kubeedge/edge/pkg/metamanager.(*metaManager).process(0xc000972080, 0xc001463740, 0x24, 0x0, 0x0, 0x17b1116f29d, 0xc0013d7278, 0x7, 0x0, 0xc0013d72a0, ...)
8月 04 20:15:21 hw-node01 edgecore[937]:         /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/metamanager/process.go:646 +0x218
8月 04 20:15:21 hw-node01 edgecore[937]: github.com/kubeedge/kubeedge/edge/pkg/metamanager.(*metaManager).runMetaManager.func1(0xc000972080)
8月 04 20:15:21 hw-node01 edgecore[937]:         /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/metamanager/process.go:680 +0x318
8月 04 20:15:21 hw-node01 edgecore[937]: created by github.com/kubeedge/kubeedge/edge/pkg/metamanager.(*metaManager).runMetaManager
8月 04 20:15:21 hw-node01 edgecore[937]:         /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/metamanager/process.go:670 +0x3f
8月 04 20:15:21 hw-node01 systemd[1]: edgecore.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
8月 04 20:15:21 hw-node01 systemd[1]: edgecore.service: Failed with result 'exit-code'.

**Comment by PearceDuan** [comment]
I meet same problem now, is this solved or not?

**Comment by PearceDuan** [comment]
> I meet same problem now, is this solved or not?

although i don't know  the root cause, but it seems temporary work for me after add time.Sleep() in Retry loop

vim ./edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go

near line 90, add `time.Sleep(1*time.Second)` in the Retry loop


```golang
	var maxRetryTimes = 3
	for i := 1; err != nil; i++ {
		time.Sleep(1*time.Second)
		klog.Errorf("failed to access database:%v", err)
		if i == maxRetryTimes {
			return fmt.Errorf("failed to access database after %v times try", i)
		}
		_, err = dbm.DBAccess.Raw("INSERT OR REPLACE INTO meta_v2 (key, groupversionresource, namespace,name,resourceversion,value) VALUES (?,?,?,?,?,?)", m.Key, m.GroupVersionResource, m.Namespace, m.Name, m.ResourceVersion, m.Value).Exec()
	}
```
