### ISSUE TITLE
KubeEdge Support K8s v1.21

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#3002]
**What would you like to be added/modified**:

Now when we use version v1.21 of K8s master, the application schduled to the edgenode can't run normally. Maybe need some adaption work in edgecontroller.

cc @gy95 
**Why is this needed**:
Support  K8s v1.21.

**Comment by fisherxu** [comment]
We can use local-up to test.

**Comment by gy95** [comment]
ok
/assign
