### ISSUE TITLE
not surport nodeSelector feature（v1.7.1）

### ISSUE THREAD

**Issue by MoXinQian** [kubeedge/kubeedge#3004]
I want the pod to be scheduled to certain nodes， I set bolew：
```bash
nodeSelector:
   app: hahaha
```
But only one node is scheduled

**Comment by fisherxu** [comment]
Thanks for pointing out the issue. And can you provide more details? The schedule work is done by k8s's scheduler in master, so do the pods all schduledsuccessfully?

**Comment by bensch98** [comment]
nodeSelector works just fine. Label your node:
```bash
kubectl label node NODENAME "app=hahaha"
```
Afterwards the Pods will only be scheduled there. I assume you mean only one of your pods is being scheduled after applying your deployment? Maybe you try to deploy multiple Pods using the same Port on the same node? That won't work and only one Pod will be running.
@MoXinQian Please provide your Pod/Deployment yaml files.

**Comment by siredmar** [comment]
@MoXinQian this depends on how you are defining your workload. If you are using the kind "Deployment" with replica set to 1 it only gets deployed to one matching node. If you are using "DaemonSet" your workload will be scheduled on every matching node. 
If you are the kind "Pod" than you should share your manifest yaml files as something else is strange. Did you label all your wanted nodes to match your labelSelector?

**Comment by MoXinQian** [comment]
> @MoXinQian this depends on how you are defining your workload. If you are using the kind "Deployment" with replica set to 1 it only gets deployed to one matching node. If you are using "DaemonSet" your workload will be scheduled on every matching node.
> If you are the kind "Pod" than you should share your manifest yaml files as something else is strange. Did you label all your wanted nodes to match your labelSelector?

thanks

**Comment by siredmar** [comment]
Did this fix your problems? Can this issue get closed then?

**Comment by MoXinQian** [comment]
yes

**Comment by MoXinQian** [comment]
> Did this fix your problems? Can this issue get closed then?
thanks，you can.
