### ISSUE TITLE
The environment to run keadm

### ISSUE THREAD

**Issue by jeffzhu503** [kubeedge/kubeedge#3005]
It is not exactly clear to me where to run this command: " keadm init --advertise-address="THE-EXPOSED-IP" 

I would expect something like the following: 
1. Shall I create a VM in the cloud or use my laptop?  
2. OS Ubuntu is required and has been tested. Mac may work but it is not tested. 
3. What kind of credential in order to run this keadm? 
4. Can I run from one of pods in the Kubernetes cluster? 
5. Download keadm from the link, and unzip to the following directory.

**Comment by mehulhirpara** [comment]
Answering some of the questions

You need a k8s cluster before starting on KubeEdge. You can create a VM on your laptop and setup k8s cluster first and download keadm from [keadm v1.7.1](https://github.com/kubeedge/kubeedge/releases/download/v1.7.1/keadm-v1.7.1-linux-amd64.tar.gz)

```
$ wget https://github.com/kubeedge/kubeedge/releases/download/v1.7.1/keadm-v1.7.1-linux-amd64.tar.gz
$ tar -xvf keadm-v1.7.1-linux-amd64.tar.gz
$ cd keadm
$ sudo ./keadm init --advertise-address=<THE-EXPOSED-IP> --kube-config=<ABSOLUTE-PATH-TO>/.kube/config
```

**Comment by ZBoIsHere** [comment]
this blog may help you
[KubeEdge在centos8.0下的安装部署详解](https://mp.weixin.qq.com/s?search_click_id=8336705840306415996-1628507703106-740319&sub=&__biz=MzIzNzU5NTYzMA==&mid=2247490514&idx=1&sn=66e8500384a5c2a36c1de23ea3b32f93&chksm=e8c76553dfb0ec458e1fd89dc5b506e2f47277553b564537de017b88103e793a017b41e36ccf&scene=3&subscene=10000&clicktime=1628507703&enterid=1628507703&ascene=0&devicetype=android-29&version=2800093b&nettype=WIFI&abtest_cookie=AAACAA%3D%3D&lang=zh_CN&exportkey=ASqKN4QWA8wMMvUa%2B0bx1f0%3D&pass_ticket=1EpYoHipQ3rxuVT0lY9l4VSM22UXsT4OAvXxoWBm%2B%2Bdlewg%2F%2BalUT%2B7QT1tXKv8S&wx_header=1)

**Comment by jeffzhu503** [comment]
We set up another VM to install Cloudcore using keadm which connects a K8s standard cluster in GCP.   This scenario is verified.
