### ISSUE TITLE
failing to get token

### ISSUE THREAD

**Issue by mehulhirpara** [kubeedge/kubeedge#3009]
**What happened**: Trying to setup cloudcore using keadm. Completed cloudcore successfully, but failing to get token using command metioned below:

```
$ ./keadm gettoken --kube-config <path-to-config>
failed to get token
Error: secrets "tokensecret" not found
Usage:
  keadm gettoken [flags]

Examples:

keadm gettoken --kube-config /root/.kube/config
- kube-config is the absolute path of kubeconfig which used to build secure connectivity between keadm and kube-apiserver
to get the token.


Flags:
  -h, --help                 help for gettoken
      --kube-config string   Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")

F0806 15:02:11.798017 3428747 keadm.go:27] secrets "tokensecret" not found
```

**What you expected to happen**: Expected to receive a token which I can use to join worker/edge node

**How to reproduce it (as minimally and precisely as possible)**: Just by running command "keadm gettoken"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.7.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by bensch98** [comment]
Is the Kubernetes cluster already running? Did you check if the config is really located at your specified path?
My config is always in $HOME/.kube/config

**Comment by mehulhirpara** [comment]
Yes, k8s is running and config file location is at $HOME/.kube/config

**Comment by mehulhirpara** [comment]
Tried manually and found that default token is created and in the description there is "token" field instead of "tokensecret"

```
$ kubectl get secrets
NAME                  TYPE                                  DATA   AGE
default-token-ltv8k   kubernetes.io/service-account-token   3      10d

$ kubectl describe secrets/default-token-ltv8k
Name:         default-token-ltv8k
Namespace:    default
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: default
              kubernetes.io/service-account.uid: 06550015-3d9a-4e00-b638-3c3c2cf06d95

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1066 bytes
namespace:  7 bytes
token:      <encoded data>

$ kubectl get secret default-token-ltv8k -o=jsonpath='{.data.token}' | base64 -d
```

**Comment by gy95** [comment]
just need to run `keadm gettoken` without specified configuration
