### ISSUE TITLE
kube-flannel and kube-proxy of work nodes is pending 

### ISSUE THREAD

**Issue by slomo28** [kubeedge/kubeedge#3012]
**What happened and what you expected to happen**:
The master node works properly, but the Kube-flannel and Kube-proxy of all work nodes are pending.
**How to reproduce it (as minimally and precisely as possible)**:
The work node is faulty after being added to the cluster
**Anything else we need to know?**:
Edgecore has been installed on the work node and all the images under "kubeadm config images List" have been downloaded
**Environment**:Ubuntu 21.4
- Kubernetes version (use `kubectl version`):v1.21.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.7.1

**Comment by ZBoIsHere** [comment]
so far, kube-flannel and kube-proxy can be installed in the cloudnode, if you want to install CNI and kube-proxy in the edgenode, you can reference to https://github.com/kubeedge/kubeedge/issues/2677; if you just want access service in the edgenode, you can try install[ edgemesh](https://github.com/kubeedge/edgemesh) in your edgenode.

**Comment by ZBoIsHere** [comment]
In addition, edgemesh and kube-proxy can't not installed in the same host.

**Comment by slomo28** [comment]
Thank for your help!

**Comment by slomo28** [comment]
> In addition, edgemesh and kube-proxy can't not installed in the same host.
Should I delete kube-flannel and kube-proxy on the work node?I want to run 'kubeedge-counter-demo', but 'Kubeedge -pi-counter' is pending, is that because of the above problem?

**Comment by slomo28** [comment]
> In addition, edgemesh and kube-proxy can't not installed in the same host.
Should I delete kube-flannel and kube-proxy on the work node?I want to run 'kubeedge-counter-demo', but 'Kubeedge -pi-counter' is pending, is that because of the above problem?

**Comment by ZBoIsHere** [comment]
edgemesh and kube-proxy will be able to install in the same host in the next version of kubeedge. 
If kube-proxy is running in the edgenode, the edgecore will be failed, so in the edgenode, you can first close the kube-flannel and kube-proxy and restart the edgecore, then watch the counter-demo healthy or not.
