### ISSUE TITLE
Install KubeEdge in GCP err: no Auth Provider found for name "gcp" goroutine 1 [running]:

### ISSUE THREAD

**Issue by jeffzhu503** [kubeedge/kubeedge#3013]
We created a Kubernetes cluster in GCP and run Keadm init using the following config file.  
- name: gke_devops-267820_us-central1-c_kubeedge-cloud-std
  user:
    auth-provider:
      config:
        access-token: ya29.c.Ko8BCwhw6UPe28gOegdTmUSohwmUVLNHcAi-eSNPsv9cKICzl_redgu5Bf9wj-SrVCPSEidzW-ZYUIZgcn1PgUj8lkVK21VIfsKXvlvv4o110YZOBkfj-5_XKY-xMudxazGy05rKmAP6SF0pSN3mW0IydEzPeaiAwonrDthm-WK_oCh9ZbPc5Unjywu1wOGtG64.........................
.........................................................................................................................................................................................................................................................
.........................................................................................................................................................................................................................................................
.........................................................................................................................................................................................................................................................
................
        cmd-args: config config-helper --format=json
        cmd-path: /snap/google-cloud-sdk/190/bin/gcloud
        expiry: "2021-08-09T08:29:17Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

**Comment by jeffzhu503** [comment]
Found a previous bug: https://github.com/kubeedge/kubeedge/issues/2427.  
We need to confirm if we support all three major public cloud providers.

**Comment by llhuii** [comment]
patch `https://github.com/kubeedge/kubeedge/blob/master/keadm/cmd/keadm/app/cmd/util/common.go` and run `make WHAT=keadm` to recompile keadm can solve this issue.
```diff
diff --git a/keadm/cmd/keadm/app/cmd/util/common.go b/keadm/cmd/keadm/app/cmd/util/common.go
index c54918e6..27ca9811 100644
--- a/keadm/cmd/keadm/app/cmd/util/common.go
+++ b/keadm/cmd/keadm/app/cmd/util/common.go
@@ -33,6 +33,7 @@ import (
        "github.com/spf13/pflag"
        "k8s.io/apimachinery/pkg/version"
        "k8s.io/client-go/discovery"
+       _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
        "k8s.io/client-go/rest"
        "k8s.io/client-go/tools/clientcmd"
        "k8s.io/klog/v2"
```

**Comment by llhuii** [comment]
`cloudcore`
```diff
diff --git a/cloud/pkg/common/client/client.go b/cloud/pkg/common/client/client.go
index 8029b693..bb335165 100644
--- a/cloud/pkg/common/client/client.go+++ b/cloud/pkg/common/client/client.go
@@ -23,6 +23,7 @@ import (        "k8s.io/apimachinery/pkg/runtime"
        "k8s.io/client-go/dynamic"        "k8s.io/client-go/kubernetes"
+       _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
        "k8s.io/client-go/rest"
        "k8s.io/client-go/tools/clientcmd"
        "k8s.io/klog/v2"
```
