### ISSUE TITLE
Deadlock occurs using beehiveContext.SendSync

### ISSUE THREAD

**Issue by shmilyhome** [kubeedge/kubeedge#3016]
**What happened**:
Deadlock occurs using beehiveContext.SendSync，Have a small probability
**What you expected to happen**:
Resolve deadlock
**How to reproduce it (as minimally and precisely as possible)**:
using beehiveContext.SendSync，But the cloudcore response time is just the critical point of the timeout time
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.20.4
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):v1.7.1
- 
**solution**:
Problem code block：github.com/kubeedge/beehive/pkg/core/context/context_channel.go

```go
 func (ctx *ChannelContext) SendResp(message model.Message) {
 	anonName := getAnonChannelName(message.GetParentID())
 
 	ctx.anonChsLock.RLock()
 	defer ctx.anonChsLock.RUnlock()
 	if channel, exist := ctx.anonChannels[anonName]; exist {
 		channel <- message
 		return
 	}
 
 	klog.V(4).Infof("Get bad anonName:%s when sendresp message, do nothing", anonName)
 }
```
Personal solution：
```go
 func (ctx *ChannelContext) SendResp(message model.Message) {
 	anonName := getAnonChannelName(message.GetParentID())
 	respTimer := time.NewTimer(MessageTimeoutDefault)
 	ctx.anonChsLock.RLock()
 	defer ctx.anonChsLock.RUnlock()
 	if channel, exist := ctx.anonChannels[anonName]; exist {
 		select {
		case channel <- message:
 		case <- respTimer.C:
 			klog.Warningf("the messages ParentID:%s return resp timeout", anonName)
 		}
 		return
 	}
 
 	klog.V(4).Infof("Get bad anonName:%s when sendresp message, do nothing", anonName)
}
```

**Comment by sdghchj** [comment]
Kind to remind you of stopping the ticker when you no longer use it.
More and more tickers not stopped will exhaust your CPU resource.

**Comment by ankitrgadiya** [comment]
The chances of reproducing this issue are lower but it does happen.

This is the code from SendSync function which sends the message to the Module. Only after sending the message does it allocate a new channel. If it so happens that the module calls SendResp before the channel is added in the map then it will not send the message and the above issue will happen. This can be artificially simulated by adding a time.Sleep(time.Nanosecond * 500) right before allocating the channel.

```go
	sendTimer := time.NewTimer(timeout)
	select {
	case reqChannel <- message:
	case <-sendTimer.C:
		return model.Message{}, errors.New("timeout to send message")
	}
	sendTimer.Stop()

	// new anonymous channel for response
	anonChan := make(chan model.Message)
	anonName := getAnonChannelName(message.GetID())
	ctx.anonChsLock.Lock()
	ctx.anonChannels[anonName] = anonChan
	ctx.anonChsLock.Unlock()
	defer func() {
		ctx.anonChsLock.Lock()
		delete(ctx.anonChannels, anonName)
		close(anonChan)
		ctx.anonChsLock.Unlock()
	}()

	var resp model.Message
	respTimer := time.NewTimer(time.Until(deadline))
	select {
	case resp = <-anonChan:
	case <-respTimer.C:
		return model.Message{}, errors.New("timeout to get response")
	}
	respTimer.Stop()
```

A better fix than adding a timeout will be to allocate the channel before actually sending the messsage. I'll raise a PR for the fix.
