### ISSUE TITLE
Can't get configmap when the pod in the edgenode

### ISSUE THREAD

**Issue by xianshun163** [kubeedge/kubeedge#3020]
**What happened and what you expected to happen**:
I create a deployment , the deployment use a  configmapRef  like below:
 envFrom:
        - configMapRef:
            name:  config-env
when the deployment is run in the cloud node , it  can get the configmap, but when it run in the edge node, It can't get the config map. 
**How to reproduce it (as minimally and precisely as possible)**:
Deploy the kubeedge  as the doc  https://kubeedge.io/zh/docs/setup/keadm/.
And then create a configmap, and create a deployment to use the configmap, and  add a nodeSelector to let  it  run in the edge node.
**Anything else we need to know?**:
I deploy the kubeedge  use the keadm,  and deploy the kubernets use the kubeadm. and use the calico  as the CNI
**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3  and   1.16.0   hase the same  issue
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.7.1

**Comment by haoheipi** [comment]
I got into trouble with the same problem and when I viewed the code it was because the method makeEnvironmentVariables  in that loading configuration from envFrom was removed .
I don't know why it was removed in this [pr](https://github.com/kubeedge/kubeedge/pull/1104) . If necessary, I am willing to submit my PR for this issue.  @fisherxu

**Comment by fisherxu** [comment]
> I got into trouble with the same problem and when I viewed the code it was because the method makeEnvironmentVariables in that loading configuration from envFrom was removed .
> I don't know why it was removed in this [pr](https://github.com/kubeedge/kubeedge/pull/1104) . If necessary, I am willing to submit my PR for this issue. @fisherxu

Please goahead, and welcome the PR! @haoheipi
