### ISSUE TITLE
Edgecore logs are flooded by EDGE_Metrics_CONNECTOR after update to 1.7.1

### ISSUE THREAD

**Issue by rorosen** [kubeedge/kubeedge#3023]
**What happened**:
Since an update from version 1.5.1 to version 1.7.1 (edgecore and cloudcore), the edgecore logs are permanently flooded by the EDGE_Metrics_CONNECTOR with "write metrics data" events. 

A small section of the messages:
```
...
Aug 11 15:14:22 ... edgecore[15642]: I0811 15:14:22.586416   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70593 write metrics data # HELP machine_nvm_capacity NVM capacity value labeled by NVM mode (memory mode or app direct mode).
Aug 11 15:14:22 ... edgecore[15642]: I0811 15:14:22.586486   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70593 write metrics data # TYPE machine_nvm_capacity gauge
Aug 11 15:14:22 ... edgecore[15642]: I0811 15:14:22.586566   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70593 write metrics data machine_nvm_capacity{boot_id="5081b4de-70fa-4c5a-a2f6-bc2269e6ba0c",machine_id="af5b530e30b642678998e03bba486435",mode="app_direct_mode",system_uuid="c9d2a4f4-7dec-11ea-af6f-58d43daa0900"} 0 1628693611994
Aug 11 15:14:22 ... edgecore[15642]: I0811 15:14:22.586635   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70593 write metrics data machine_nvm_capacity{boot_id="5081b4de-70fa-4c5a-a2f6-bc2269e6ba0c",machine_id="af5b530e30b642678998e03bba486435",mode="memory_mode",system_uuid="c9d2a4f4-7dec-11ea-af6f-58d43daa0900"} 0 1628693611994
Aug 11 15:14:22 ... edgecore[15642]: I0811 15:14:22.586706   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70593 write metrics data # HELP machine_scrape_error 1 if there was an error while getting machine metrics, 0 otherwise.
Aug 11 15:14:22 ... edgecore[15642]: I0811 15:14:22.586774   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70593 write metrics data # TYPE machine_scrape_error gauge
Aug 11 15:14:22 ... edgecore[15642]: I0811 15:14:22.586840   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70593 write metrics data machine_scrape_error 0
...
```

Usually, it prints several hundreds lines and stops at some point with the message:
```
Aug 11 15:14:22 ... edgecore[15642]: I0811 15:14:22.586972   15642 edgedmetricsconnection.go:119] receive stop single, so stop metrics scan ...
```

However, a few seconds later it starts flooding the log once again for no reason:
```
...
Aug 11 15:15:12 ... edgecore[15642]: I0811 15:15:12.379877   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70602 write metrics data # HELP apiserver_audit_event_total [ALPHA] Counter of audit events generated and sent to the audit backend.
Aug 11 15:15:12 ... edgecore[15642]: I0811 15:15:12.380344   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70602 write metrics data # TYPE apiserver_audit_event_total counter
Aug 11 15:15:12 ... edgecore[15642]: I0811 15:15:12.380760   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70602 write metrics data apiserver_audit_event_total 0
Aug 11 15:15:12 ... edgecore[15642]: I0811 15:15:12.381181   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70602 write metrics data # HELP apiserver_audit_requests_rejected_total [ALPHA] Counter of apiserver requests rejected due to an error in audit logging backend.
Aug 11 15:15:12 ... edgecore[15642]: I0811 15:15:12.381592   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70602 write metrics data # TYPE apiserver_audit_requests_rejected_total counter
Aug 11 15:15:12 ... edgecore[15642]: I0811 15:15:12.382022   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70602 write metrics data apiserver_audit_requests_rejected_total 0
Aug 11 15:15:12 ... edgecore[15642]: I0811 15:15:12.382441   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70602 write metrics data # HELP apiserver_client_certificate_expiration_seconds [ALPHA] Distribution of the remaining lifetime on the certificate used to authenticate a request.
Aug 11 15:15:12 ... edgecore[15642]: I0811 15:15:12.383018   15642 edgedmetricsconnection.go:114] EDGE_Metrics_CONNECTOR Message MessageID 70602 write metrics data # TYPE apiserver_client_certificate_expiration_seconds histogram
...
```

**How to reproduce it (as minimally and precisely as possible)**:
Update from version 1.5.1 to version 1.7.1 without major changes to cloudcore and edgecore configuration. Maybe even a fresh 1.7.1 setup suffers this issue?

**Anything else we need to know?**:
I do not need metrics anyway and tried to disable them already in the edgecore config:
```
edged:
  enableMetrics: false
```
This does weirdly not change anything, the log is still spammed by EDGE_Metrics_CONNECTOR. I am deploying edgecore via a systemd service and retrieving the logs with `journalctl -u edgecore.service`.

My question is: How to get rid of the EDGE_Metrics_CONNECTOR logs? Is this even expected? I wonder about not seeing other issues complaining about the amount of logs.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.12
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): KubeEdge v1.7.1 (cloudcore and edgecore)
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): KubeEdge v1.7.1
  - Hardware configuration (e.g. `lscpu`): 
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           55
Model name:                      Intel(R) Atom(TM) CPU  E3825  @ 1.33GHz
Stepping:                        9
CPU MHz:                         533.331
CPU max MHz:                     1333.0000
CPU min MHz:                     533.2000
BogoMIPS:                        2666.66
Virtualization:                  VT-x
L1d cache:                       48 KiB
L1i cache:                       64 KiB
L2 cache:                        1 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arc
                                 h_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx1
                                 6 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb pti ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid tsc_
                                 adjust smep erms dtherm arat md_clear
  - OS (e.g. `cat /etc/os-release`):
NAME="openSUSE MicroOS"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20210706"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20210706"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo"
  - Kernel (e.g. `uname -a`):
`Linux ... 5.13.0-1-default #1 SMP Fri Jul 2 05:54:32 UTC 2021 (aa40472) x86_64 x86_64 x86_64 GNU/Linux`
  - Go version (e.g. `go version`): compiled with go1.14

  </details>

**Comment by elrosar** [comment]
I just noticed that this is also happening in a cluster running cloudcore v.1.7.1 and edgecore v.1.5.0. This is critical because edgecore v1.5.0 writes its log to `/tmp` where the info log will take up all the place until there is nothing left to write. This will lead to edgecore failing repeatedly because `no space left on device` errors.

Hence, this all is initiated by the update of the cloudcore version. Could you point me to the change in cloudcore that is responsible for this behaviour? Is there anything I can change in the cloudcore configuration so this is not happening anymore?

**Comment by first-sight12** [comment]
Upgrade edgecore version from  v.1.5.0.  to v.1.7.1

**Comment by first-sight12** [comment]
> I just noticed that this is also happening in a cluster running cloudcore v.1.7.1 and edgecore v.1.5.0. This is critical because edgecore v1.5.0 writes its log to `/tmp` where the info log will take up all the place until there is nothing left to write. This will lead to edgecore failing repeatedly because `no space left on device` errors.
> 
> Hence, this all is initiated by the update of the cloudcore version. Could you point me to the change in cloudcore that is responsible for this behaviour? Is there anything I can change in the cloudcore configuration so this is not happening anymore?



> I just noticed that this is also happening in a cluster running cloudcore v.1.7.1 and edgecore v.1.5.0. This is critical because edgecore v1.5.0 writes its log to `/tmp` where the info log will take up all the place until there is nothing left to write. This will lead to edgecore failing repeatedly because `no space left on device` errors.
> 
> Hence, this all is initiated by the update of the cloudcore version. Could you point me to the change in cloudcore that is responsible for this behaviour? Is there anything I can change in the cloudcore configuration so this is not happening anymore?



> I just noticed that this is also happening in a cluster running cloudcore v.1.7.1 and edgecore v.1.5.0. This is critical because edgecore v1.5.0 writes its log to `/tmp` where the info log will take up all the place until there is nothing left to write. This will lead to edgecore failing repeatedly because `no space left on device` errors.
> 
> Hence, this all is initiated by the update of the cloudcore version. Could you point me to the change in cloudcore that is responsible for this behaviour? Is there anything I can change in the cloudcore configuration so this is not happening anymore?

Upgrade edgecore version from v.1.5.0 to v.1.7.1

**Comment by gy95** [comment]
these logs are from this, we could modify this log level from `Info` to `Debug`
https://github.com/kubeedge/kubeedge/blob/611e5d820b92d89f2be0df23bf7d5ef20fd09a72/pkg/stream/edgedmetricsconnection.go#L114
And one question, do you enable module `edgestream`? @elrosar

**Comment by elrosar** [comment]
@gy95 yes, `edgestream` is enabled as we need logs and exec for the nodes. So it is no option for us to disable `edgestream` completely. I do not completely understand why these are logs from `edgestream` although the message says "metrics data", is this intended?

Changing the log level in the relevant line in `edgemetricsconnection.go` seems like a quick fix to hide these lines in the logs, but would not address the root cause of this issue no? Is it possible that other problems may remain, when the log level is changed? Let me know if I can support you anyhow, I would be happy to debug this further with you.
