### ISSUE TITLE
The Raspberry PI node cannot join the cluster.

### ISSUE THREAD

**Issue by slomo28** [kubeedge/kubeedge#3040]
**What happened and what you expected to happen**:
Raspberry PI failed to join the cluster.
**How to reproduce it (as minimally and precisely as possible)**:
After keadm join is executed on the raspberry PI node, edgecore is successfully run, but raspberry PI is not added to the cluster on the master node.
**Anything else we need to know?**:
Log display:
" Failed to start container manager, err: system validation failed - Following Cgroup subsystem not mounted: [memory]"
"initialize module error: system validation failed - Following Cgroup subsystem not mounted: [memory]"
Edgecore. service restarts repeatedly.
**Environment**:
- Kubernetes version (use `kubectl version`):1.19.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.7.2

**Comment by slomo28** [comment]
I have solved this problem by editing the cmdline.txt file under /boot/firmware, append "cgroup_memory=1 cgroup_enable=memory", and restart the raspberry PI.

**Comment by fisherxu** [comment]
@slomo28  Thanks for sharing the experience :) It's an issue related to raspi.

**Comment by bensch98** [comment]
Had the same issue in the past. This is only necessary for kernel versions 5.x.x and above. As @fisherxu said, it's an issue related to the Pi and not the Image. Note that the `cmdline.txt` file can be located in slightly different directories depending on which OS you are running on the Pi.

**Comment by fisherxu** [comment]
I think we can close this issue, feel free to reopen it for any other problem.

/close
