### ISSUE TITLE
list-watch: cannot update secret resource

### ISSUE THREAD

**Issue by Poorunga** [kubeedge/kubeedge#3041]
**What happened**:

I used the list-watch capability provided by edgecore. And when I try to update the secret, I receive an error log:
```
W0819 02:46:03.954397       1 tunnel.go:42] Set peer addr info to secret err: Update secret &Secret{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,} err: the body of the request was in an unknown format - accepted media types include: application/json, application/yaml
```

My code:
```
func (c *TunnelAgentController) SetPeerAddrInfo(nodeName string, info *peer.AddrInfo) error {
	peerAddrINfoBytes, err := info.MarshalJSON()
	if err != nil {
		return fmt.Errorf("Marshal node %s peer info err: %v", nodeName, err)
	}

	secret, err := c.secretLister.Secrets(constants.SecretNamespace).Get(constants.SecretName)
	if err != nil {
		return fmt.Errorf("Get secret %s in %s failed: %v", constants.SecretName, constants.SecretNamespace, err)
	}

	if secret.Data == nil {
		secret.Data = make(map[string][]byte)
	} else if bytes.Equal(secret.Data[nodeName], peerAddrINfoBytes) {
		return nil
	}

	secret.Data[nodeName] = peerAddrINfoBytes
	secret, err = c.secretOperator.Update(context.Background(), secret, metav1.UpdateOptions{})
	if err != nil {
		return fmt.Errorf("Update secret %v err: %v", secret, err)
	}
	return nil
}
```

You can also see these codes in https://github.com/kubeedge/edgemesh/blob/main/agent/pkg/tunnel/controller/controller.go

**What you expected to happen**:

I hope the secret update can be successful

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.20
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.7.2
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Poorunga** [comment]
I solved this problem by modifying the ContentType, like:
```
return &KubeAPIConfig{
		Master:      "http://127.0.0.1:10550",
		//ContentType: "application/vnd.kubernetes.protobuf",
		ContentType: "application/json",
		QPS:         100.0,
		Burst:       200,
		KubeConfig:  "",
	}
```
Change ContentType from `application/vnd.kubernetes.protobuf` to `application/json`

**Comment by fisherxu** [comment]
Yes, now we only support json ContentType, and the client-go use json by default.
