### ISSUE TITLE
Start edgecore error: Failed to start container manager, err: failed to initialize top level QOS containers: root container [kubepods] doesn't exist

### ISSUE THREAD

**Issue by beyondyinjl2** [kubeedge/kubeedge#3042]
uname -a
Linux davinci-mini 4.19.95+ #1 SMP Wed Feb 24 17:32:53 CST 2021 aarch64 aarch64 aarch64 GNU/Linux

mosquitto -v
1629354086: mosquitto version 1.4.15 (build date Tue, 18 Jun 2019 11:42:22 -0300) starting
1629354086: Using default config.
1629354086: Opening ipv4 listen socket on port 1883.
1629354086: Error: Address already in use

docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:37 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:46 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

/usr/local/bin/edgecore
Start edgecore error:
I0819 06:24:29.014685   18609 websocket.go:93] Websocket connect to cloud access successful
I0819 06:24:29.014808   18609 process.go:512] node connection event occur: cloud_connected
I0819 06:24:29.014950   18609 process.go:512] node connection event occur: cloud_connected
I0819 06:24:29.014988   18609 process.go:282] DeviceTwin receive msg
W0819 06:24:29.015315   18609 eventbus.go:145] Action not found
I0819 06:24:29.015386   18609 process.go:66] Send msg to the CommModule module in twin
W0819 06:24:29.018039   18609 manager.go:949] Error getting perf_event cgroup path: "could not find path for resource \"perf_event\" for container \"/\""
W0819 06:24:29.025614   18609 manager.go:949] Error getting perf_event cgroup path: "could not find path for resource \"perf_event\" for container \"/system.slice/docker.service\""
W0819 06:24:29.026826   18609 manager.go:949] Error getting perf_event cgroup path: "could not find path for resource \"perf_event\" for container \"/kubepods.slice\""
I0819 06:24:29.029802   18609 proxy.go:119] [EdgeMesh] dnat rule -p tcp -j DNAT --to-destination 172.17.0.1:40001 not exists
W0819 06:24:29.030119   18609 proxy.go:64] [EdgeMesh] add route err: file exists
I0819 06:24:29.116518   18609 cpu_manager.go:184] [cpumanager] starting with none policy
I0819 06:24:29.116567   18609 cpu_manager.go:185] [cpumanager] reconciling every 0s
I0819 06:24:29.116624   18609 state_mem.go:36] [cpumanager] initializing new in-memory state store
I0819 06:24:29.117152   18609 state_mem.go:88] [cpumanager] updated default cpuset: ""
I0819 06:24:29.117192   18609 state_mem.go:96] [cpumanager] updated cpuset assignments: "map[]"
I0819 06:24:29.117229   18609 policy_none.go:43] [cpumanager] none policy: Start
E0819 06:24:29.131285   18609 cgroup_manager_linux.go:674] cgroup update failed failed to set supported cgroup subsystems for cgroup [kubepods]: failed to find subsystem mount for required subsystem: pids
E0819 06:24:29.131434   18609 edged.go:742] Failed to start container manager, err: failed to initialize top level QOS containers: root container [kubepods] doesn't exist
E0819 06:24:29.131461   18609 edged.go:293] initialize module error: failed to initialize top level QOS containers: root container [kubepods] doesn't exist

**Comment by lonelyCZ** [comment]
I also encounter this problem.  Do you find the solution of this issue?

**Comment by lonelyCZ** [comment]
I find a way to this problem that change config params in source code. Then recompile the edged.go code. 

https://github.com/kubeedge/kubeedge/blob/d2cbad777ae00a444e193a18a3cbbc00a7317d33/vendor/k8s.io/kubernetes/pkg/features/kube_features.go#L683-L684

**Set this two params default params are false**
- SupportPodPidsLimit=false
- SupportNodePidsLimit=false

**then recompile the edged.go code**

Could I set these parmas by edgecore config file like kubelet? @fisherxu

**Comment by beyondyinjl2** [comment]
@lonelyCZ Which branch or tag did you modify on? After I modified it, the compilation was successful, and the same error was reported after running.

**Comment by beyondyinjl2** [comment]
Compiled with the master branch, another error is reported:
E1118 11:58:41.010155 32283 node_container_manager_linux.go:57] "Failed to create cgroup" err="Unit kubepods.slice already exists." cgroupName=[kubepods]
E1118 11:58:41.010207 32283 edged.go:810] Failed to start container manager, err: Unit kubepods.slice already exists.
E1118 11:58:41.010235 32283 edged.go:301] initialize module error: Unit kubepods.slice already exists.

**Comment by lonelyCZ** [comment]
> @lonelyCZ Which branch or tag did you modify on? After I modified it, the compilation was successful, and the same error was reported after running.

It should be v1.7.2 at that time.
