### ISSUE TITLE
Pods remain in state "Pending" when added while node is offline in v1.7.x

### ISSUE THREAD

**Issue by rorosen** [kubeedge/kubeedge#3045]
**What happened**: All pods that are deployed while the respective edge node is offline remain in state "Pending", in v1.7.1 (Cloudcore and Edgecore). Re-deploying the pods in question while the edge node is online succeeds. 

**What you expected to happen**: Pods should be running as soon as the edge node gets online.

**How to reproduce it (as minimally and precisely as possible)**:
* Stop edgecore
* Deploy a pod on the respective node
* Start edgecore
* -> The pod remains in state "Pending"

**Anything else we need to know?**: Comparing the cloudcore logs of v1.6.1 and v1.7.1 (edgecore version is always v1.7.1), there is one deviating line that appears only with v1.7.1:

```text
W0819 08:43:43.234425       1 upstream.go:789] message: 7aead20a-bb32-426c-99a2-94592d268fa2 process failure, update node failed with error: nodes "<nodename>" is forbidden: User "system:serviceaccount:kubeedge:cloudcore" cannot patch resource "nodes" in API group "" at the cluster scope, namespace: , name: <nodename>
```

That message is kind of expected, since "patch" is not specified in `clusterrole.yaml`. However, adding "patch" to the clusterrole only results in:

```text
W0819 09:12:07.219506       1 upstream.go:789] message: 27fb7366-37f1-473c-949f-6f8bd7f42b1f process failure, update node failed with error: Operation cannot be fulfilled on nodes " <nodename>": the object has been modified; please apply your changes to the latest version and try again, namespace: , name:  <nodename>
``` 

The pod does not start running whether "patch" is added to the clusterrole or not. I tried also Cloudcore version v1.7.2, but the problem remains.

If Cloudcore is restarted after the deployment and the respective edge node is online, the pod will start running on the edge node.

I am not sure if and how this is related to the line that appears only in the logs of v1.7.x. Is this is a general problem with v1.7.x or needs the setup to be adjusted for v1.7.x?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.12
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): KubeEdge v1.7.1 (Cloudcore and Edgecore)

**Comment by stingshen** [comment]
This commit may mitigate the issue:

https://github.com/kubeedge/kubeedge/commit/bd19593fee28bc4d5cc788cc656c0b59c1a39574#diff-435879603c8c2c6b20c971bd976216fe2e635ca24de924ef494f888a910b4b64L223
