### ISSUE TITLE
websocket.go:90] Init websocket connection failed dial tcp 192.168.18.130:10000: connect: connection refused

### ISSUE THREAD

**Issue by assdddddff** [kubeedge/kubeedge#3048]
**What ``happened**:[root@kubeedge edge]# edgecore 
2021-08-23 16:50:52.160874 I | INFO: Install client plugin, protocol: rest
2021-08-23 16:50:52.160985 I | INFO: Installed service discovery plugin: edge
I0823 16:50:52.163632    9623 server.go:72] Version: v1.7.0
I0823 16:50:52.166394    9623 sql.go:21] Begin to register twin db model
I0823 16:50:52.166529    9623 module.go:34] Module twin registered successfully
I0823 16:50:52.184889    9623 client.go:77] Connecting to docker on unix:///var/run/docker.sock
I0823 16:50:52.184922    9623 client.go:94] Start docker client with request timeout=0s
I0823 16:50:52.207298    9623 docker_service.go:242] Hairpin mode set to "hairpin-veth"
W0823 16:50:52.207423    9623 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
I0823 16:50:52.214128    9623 docker_service.go:257] Docker cri networking managed by kubernetes.io/no-op
I0823 16:50:52.224298    9623 docker_service.go:264] Docker Info: &{ID:2A2I:KZHX:3JVM:GAKK:BGFX:XRCT:HXHM:ZVTT:IX5V:SPUF:5KVX:ZPZD Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:0 Driver:overlay2 DriverStatus:[[Backing Filesystem xfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:[] Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:[] Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:true KernelMemoryTCP:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6tables:true Debug:false NFd:24 OomKillDisable:true NGoroutines:33 SystemTime:2021-08-23T16:50:52.214917653+08:00 LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:0 KernelVersion:3.10.0-1160.36.2.el7.x86_64 OperatingSystem:CentOS Linux 7 (Core) OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:0xc0005d9e30 NCPU:2 MemTotal:1907732480 GenericResources:[] DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:kubeedge Labels:[] ExperimentalBuild:false ServerVersion:20.10.8 ClusterStore: ClusterAdvertise: Runtimes:map[io.containerd.runc.v2:{Path:runc Args:[]} io.containerd.runtime.v1.linux:{Path:runc Args:[]} runc:{Path:runc Args:[]}] DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:[] Nodes:0 Managers:0 Cluster:<nil> Warnings:[]} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:e25210fe30a0a703442421b0f60afac609f950a3 Expected:e25210fe30a0a703442421b0f60afac609f950a3} RuncCommit:{ID:v1.0.1-0-g4144b63 Expected:v1.0.1-0-g4144b63} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=default] ProductLicense: Warnings:[]}
I0823 16:50:52.224369    9623 docker_service.go:277] Setting cgroupDriver to cgroupfs
I0823 16:50:52.224436    9623 edged.go:536] RemoteRuntimeEndpoint: "unix:///var/run/dockershim.sock", remoteImageEndpoint: "unix:///var/run/dockershim.sock"
I0823 16:50:52.224448    9623 edged.go:539] Starting the GRPC server for the docker CRI shim.
I0823 16:50:52.239483    9623 remote_runtime.go:59] parsed scheme: ""
I0823 16:50:52.239499    9623 remote_runtime.go:59] scheme "" not registered, fallback to default scheme
I0823 16:50:52.239522    9623 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/dockershim.sock  <nil> 0 <nil>}] <nil> <nil>}
I0823 16:50:52.239530    9623 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0823 16:50:52.239570    9623 remote_image.go:50] parsed scheme: ""
I0823 16:50:52.239574    9623 remote_image.go:50] scheme "" not registered, fallback to default scheme
I0823 16:50:52.239579    9623 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/dockershim.sock  <nil> 0 <nil>}] <nil> <nil>}
I0823 16:50:52.239583    9623 clientconn.go:948] ClientConn switching balancer to "pick_first"
W0823 16:50:52.239685    9623 container_manager_linux.go:942] CPUAccounting not enabled for pid: 9623
W0823 16:50:52.239692    9623 container_manager_linux.go:945] MemoryAccounting not enabled for pid: 9623
I0823 16:50:52.317101    9623 kuberuntime_manager.go:214] Container runtime docker initialized, version: 20.10.8, apiVersion: 1.41.0
I0823 16:50:52.317133    9623 edged.go:638] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
I0823 16:50:52.327083    9623 container_manager_linux.go:268] container manager verified user specified cgroup-root exists: []
I0823 16:50:52.327100    9623 container_manager_linux.go:273] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/edged ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:0s ExperimentalPodPidsLimit:0 EnforceCPULimits:false CPUCFSQuotaPeriod:0s ExperimentalTopologyManagerPolicy:none}
I0823 16:50:52.327137    9623 topology_manager.go:126] [topologymanager] Creating topology manager with none policy
I0823 16:50:52.327143    9623 container_manager_linux.go:303] [topologymanager] Initializing Topology Manager with none policy
I0823 16:50:52.327147    9623 container_manager_linux.go:308] Creating device plugin manager: false
I0823 16:50:52.327217    9623 module.go:34] Module edged registered successfully
I0823 16:50:52.327225    9623 module.go:34] Module websocket registered successfully
I0823 16:50:52.327229    9623 module.go:34] Module eventbus registered successfully
I0823 16:50:52.327725    9623 module.go:34] Module edgemesh registered successfully
I0823 16:50:52.327742    9623 metamanager.go:45] Begin to register metaManager db model
I0823 16:50:52.327779    9623 module.go:34] Module metaManager registered successfully
W0823 16:50:52.327785    9623 module.go:37] Module servicebus is disabled, do not register
W0823 16:50:52.327791    9623 module.go:37] Module edgestream is disabled, do not register
W0823 16:50:52.327794    9623 module.go:37] Module testManager is disabled, do not register
table `device` already exists, skip
table `device_attr` already exists, skip
table `device_twin` already exists, skip
table `sub_topics` already exists, skip
table `meta` already exists, skip
table `meta_v2` already exists, skip
I0823 16:50:52.329519    9623 core.go:24] Starting module twin
I0823 16:50:52.329537    9623 core.go:24] Starting module edged
I0823 16:50:52.329560    9623 process.go:113] Begin to sync sqlite 
I0823 16:50:52.329591    9623 core.go:24] Starting module websocket
I0823 16:50:52.329605    9623 core.go:24] Starting module eventbus
I0823 16:50:52.329616    9623 core.go:24] Starting module edgemesh
I0823 16:50:52.329631    9623 core.go:24] Starting module metaManager
I0823 16:50:52.330064    9623 common.go:96] start connect to mqtt server with client id: hub-client-sub-1629708652
I0823 16:50:52.330072    9623 log.go:181] DEBUG: Installed strategy plugin: [RoundRobin].
I0823 16:50:52.330119    9623 log.go:181] DEBUG: ConfigurationFactory Initiated
I0823 16:50:52.330126    9623 log.go:181] INFO: Configuration files: []
I0823 16:50:52.330137    9623 log.go:181] WARN: empty configurtion from [FileSource]
I0823 16:50:52.330141    9623 log.go:181] INFO: invoke dynamic handler:FileSource
I0823 16:50:52.330153    9623 common.go:98] client hub-client-sub-1629708652 isconnected: false
I0823 16:50:52.330159    9623 log.go:181] INFO: archaius init success
I0823 16:50:52.330296    9623 edged.go:290] Starting edged...
E0823 16:50:52.330438    9623 csi_plugin.go:226] kubernetes.io/csi: CSIDriverLister not found on KubeletVolumeHost
I0823 16:50:52.330461    9623 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
I0823 16:50:52.330621    9623 log.go:181] INFO: create new watcher
I0823 16:50:52.331077    9623 client.go:150] finish hub-client sub
I0823 16:50:52.331099    9623 common.go:96] start connect to mqtt server with client id: hub-client-pub-1629708652
I0823 16:50:52.331103    9623 common.go:98] client hub-client-pub-1629708652 isconnected: false
I0823 16:50:52.331817    9623 client.go:166] finish hub-client pub
I0823 16:50:52.331873    9623 eventbus.go:63] Init Sub And Pub Client for externel mqtt broker tcp://127.0.0.1:1883 successfully
I0823 16:50:52.331972    9623 client.go:91] edge-hub-cli subscribe topic to $hw/events/upload/#
I0823 16:50:52.332732    9623 client.go:91] edge-hub-cli subscribe topic to $hw/events/device/+/state/update
I0823 16:50:52.332821    9623 client.go:91] edge-hub-cli subscribe topic to $hw/events/device/+/twin/+
I0823 16:50:52.332880    9623 client.go:91] edge-hub-cli subscribe topic to $hw/events/node/+/membership/get
I0823 16:50:52.332928    9623 client.go:91] edge-hub-cli subscribe topic to SYS/dis/upload_records
I0823 16:50:52.332973    9623 client.go:91] edge-hub-cli subscribe topic to +/user/#
I0823 16:50:52.333137    9623 client.go:99] list edge-hub-cli-topics status, no record, skip sync
I0823 16:50:52.338510    9623 certmanager.go:159] Certificate rotation is enabled.
I0823 16:50:52.338548    9623 websocket.go:51] Websocket start to connect Access
E0823 16:50:52.341776    9623 ws.go:78] dial websocket error(dial tcp 192.168.18.130:10000: connect: connection refused), response message: 
E0823 16:50:52.341805    9623 websocket.go:90] Init websocket connection failed dial tcp 192.168.18.130:10000: connect: connection refused
I0823 16:50:52.352459    9623 listener.go:138] [EdgeMesh] get listener default.kubernetes from edge db: 9.251.0.1
I0823 16:50:52.354534    9623 client.go:86] parsed scheme: "unix"
I0823 16:50:52.354550    9623 client.go:86] scheme "unix" not registered, fallback to default scheme
I0823 16:50:52.354566    9623 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
I0823 16:50:52.354572    9623 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0823 16:50:52.363632    9623 listener.go:138] [EdgeMesh] get listener kube-system.kube-dns from edge db: 9.251.0.2
E0823 16:50:52.366154    9623 proxy.go:143] [EdgeMesh] open file /run/edgemesh-iptables err: open /run/edgemesh-iptables: no such file or directory
I0823 16:50:52.369950    9623 proxy.go:95] [EdgeMesh] chain EDGE-MESH not exists
I0823 16:50:52.382031    9623 proxy.go:103] [EdgeMesh] inbound rule -p tcp -d 9.251.0.0/16 -i docker0 -j EDGE-MESH not exists
I0823 16:50:52.383908    9623 proxy.go:111] [EdgeMesh] outbound rule -p tcp -d 9.251.0.0/16 -o docker0 -j EDGE-MESH not exists
I0823 16:50:52.391286    9623 proxy.go:119] [EdgeMesh] dnat rule -p tcp -j DNAT --to-destination 172.17.0.1:40001 not exists
I0823 16:50:52.422124    9623 cpu_manager.go:184] [cpumanager] starting with none policy
I0823 16:50:52.422137    9623 cpu_manager.go:185] [cpumanager] reconciling every 0s
I0823 16:50:52.422152    9623 state_mem.go:36] [cpumanager] initializing new in-memory state store
I0823 16:50:52.422665    9623 state_mem.go:88] [cpumanager] updated default cpuset: ""
I0823 16:50:52.422674    9623 state_mem.go:96] [cpumanager] updated cpuset assignments: "map[]"
I0823 16:50:52.422684    9623 policy_none.go:43] [cpumanager] none policy: Start
I0823 16:50:52.448411    9623 record.go:19] Normal NodeAllocatableEnforced Updated Node Allocatable limit across pods
I0823 16:50:52.448419    9623 volume_manager.go:265] Starting Kubelet Volume Manager
W0823 16:50:52.448775    9623 container_manager_linux.go:942] CPUAccounting not enabled for pid: 9623
W0823 16:50:52.448792    9623 container_manager_linux.go:945] MemoryAccounting not enabled for pid: 9623
I0823 16:50:52.448826    9623 desired_state_of_world_populator.go:139] Desired state populator starts to run
E0823 16:50:52.458846    9623 imitator.go:222] failed to unmarshal message content to unstructured obj: Object 'Kind' is missing in '{"metadata":{"name":"kubeedge","creationTimestamp":null,"labels":{"kubernetes.io/arch":"amd64","kubernetes.io/hostname":"kubeedge","kubernetes.io/os":"linux","node-role.kubernetes.io/agent":"","node-role.kubernetes.io/edge":""}},"spec":{},"status":{"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"","osImage":"","containerRuntimeVersion":"","kubeletVersion":"","kubeProxyVersion":"","operatingSystem":"","architecture":""}}}'
I0823 16:50:52.459644    9623 edged_status.go:390] Attempting to register node kubeedge
I0823 16:50:52.460858    9623 status_manager.go:53] Starting to sync pod status with apiserver
I0823 16:50:52.460877    9623 edged.go:890] start pod addition queue work 0
I0823 16:50:52.460880    9623 edged.go:890] start pod addition queue work 1
I0823 16:50:52.460883    9623 edged.go:890] start pod addition queue work 2
I0823 16:50:52.460885    9623 edged.go:890] start pod addition queue work 3
I0823 16:50:52.460888    9623 edged.go:890] start pod addition queue work 4
I0823 16:50:52.460906    9623 edged.go:356] starting plugin manager
I0823 16:50:52.461027    9623 server.go:35] starting to listen read-only on 127.0.0.1:10350
I0823 16:50:52.461818    9623 server.go:425] Adding debug handlers to kubelet server.
I0823 16:50:52.462480    9623 plugin_manager.go:114] Starting Kubelet Plugin Manager
I0823 16:50:52.465545    9623 cpu_manager.go:184] [cpumanager] starting with none policy
I0823 16:50:52.465568    9623 cpu_manager.go:185] [cpumanager] reconciling every 1s
I0823 16:50:52.465593    9623 state_mem.go:36] [cpumanager] initializing new in-memory state store
I0823 16:50:52.465673    9623 state_mem.go:88] [cpumanager] updated default cpuset: ""
I0823 16:50:52.465678    9623 state_mem.go:96] [cpumanager] updated cpuset assignments: "map[]"
I0823 16:50:52.465686    9623 policy_none.go:43] [cpumanager] none policy: Start
I0823 16:50:52.465706    9623 edged.go:368] starting syncPod
E0823 16:50:57.342998    9623 ws.go:78] dial websocket error(dial tcp 192.168.18.130:10000: connect: connection refused), response message: 
E0823 16:50:57.343034    9623 websocket.go:90] Init websocket connection failed dial tcp 192.168.18.130:10000: connect: connection refused
E0823 16:51:02.343959    9623 ws.go:78] dial websocket error(dial tcp 192.168.18.130:10000: connect: connection refused), response message: 
E0823 16:51:02.343984    9623 websocket.go:90] Init websocket connection failed dial tcp 192.168.18.130:10000: connect: connection refused
I0823 16:51:02.466644    9623 edged.go:1084] result content is []
I0823 16:51:02.589096    9623 reconciler.go:157] Reconciler: start to sync state
E0823 16:51:07.345101    9623 ws.go:78] dial websocket error(dial tcp 192.168.18.130:10000: connect: connection refused), response message: 
E0823 16:51:07.345138    9623 websocket.go:90] Init websocket connection failed dial tcp 192.168.18.130:10000: connect: connection refused
E0823 16:51:12.345954    9623 ws.go:78] dial websocket error(dial tcp 192.168.18.130:10000: connect: connection refused), response message: 
E0823 16:51:12.346001    9623 websocket.go:90] Init websocket connection failed dial tcp 192.168.18.130:10000: connect: connection refused
E0823 16:51:17.346940    9623 edgehub.go:89] connection failed: max retry count reached when connecting to cloud, will reconnect after 30s
qI0823 16:51:47.347077    9623 websocket.go:51] Websocket start to connect Access
E0823 16:51:47.348254    9623 ws.go:78] dial websocket error(dial tcp 192.168.18.130:10000: connect: connection refused), response message: 
E0823 16:51:47.348296    9623 websocket.go:90] Init websocket connection failed dial tcp 192.168.18.130:10000: connect: connection refused
:^H^CI0823 16:51:52.052602    9623 core.go:34] Get os signal interrupt
`
./keadm join --cloudcore-ipport=192.168.18.130:10000 --edgenode-name=kubeedge --kubeedge-version=1.7.0 --token=83f348b63e722353ec6e4c7463b75a3f0488e6af744ca32cd766447ecedf9968.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjg2NTE2MzR9.wWTgQaEzsLjzQDoKR-IanArnv3IRXUFAl6PRmG9wciU
[root@kubeedge keadm]# journalctl -u edgecore.service -b
8月 23 17:12:13 kubeedge systemd[1]: Started edgecore.service.
8月 23 17:12:13 kubeedge systemd[1]: edgecore.service: main process exited, code=exited, status=203/EXEC
8月 23 17:12:13 kubeedge systemd[1]: Unit edgecore.service entered failed state.
8月 23 17:12:13 kubeedge systemd[1]: edgecore.service failed.
8月 23 17:12:23 kubeedge systemd[1]: edgecore.service holdoff time over, scheduling restart.
8月 23 17:12:23 kubeedge systemd[1]: Stopped edgecore.service.
8月 23 17:12:23 kubeedge systemd[1]: Started edgecore.service.
8月 23 17:12:23 kubeedge systemd[1]: edgecore.service: main process exited, code=exited, status=203/EXEC
8月 23 17:12:23 kubeedge systemd[1]: Unit edgecore.service entered failed state.
8月 23 17:12:23 kubeedge systemd[1]: edgecore.service failed.
8月 23 17:12:33 kubeedge systemd[1]: edgecore.service holdoff time over, scheduling restart.

**What you expected to happen**:
**edgecore can run correctly**
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.18.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
edgecore:v1.7.0
cloudcore: v1.7.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
座：                 2
NUMA 节点：         1
厂商 ID：           AuthenticAMD

  - OS (e.g. `cat /etc/os-release`):centos7
  - Kernel (e.g. `uname -a`):Linux kubeedge 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):KubeEdge v1.7.0
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):go version go1.15.3 linux/amd64
  - Others:

  </details>

**Comment by assdddddff** [comment]
how to deal with it?

**Comment by fisherxu** [comment]
Can the edge node access to the `192.168.18.130:10000`? And is this the host's ip of cloudcore?

**Comment by assdddddff** [comment]
> 
> 
> Can the edge node access to the `192.168.18.130:10000`? And is this the host's ip of cloudcore?

can't and the host's ip of cloudcore is 192.168.18.130. at previously it was possible to connect to the cloud using the above statement, But it doesn't work now.

**Comment by fisherxu** [comment]
Oh, is the cloudcore still running now?

**Comment by assdddddff** [comment]
> 
> 
> Oh, is the cloudcore still running now?

 I reboot the cloudcore,the following are some codes.
`[root@kubecloud ~]# keadm init --advertise-address=192.168.18.130 --kubeedge-version=1.7.0
Kubernetes version verification passed, KubeEdge installation will start...
kubeedge-v1.7.0-linux-amd64.tar.gz checksum: 
checksum_kubeedge-v1.7.0-linux-amd64.tar.gz.txt content: 
[Run as service] service file already exisits in /etc/kubeedge//cloudcore.service, skip download
kubeedge-v1.7.0-linux-amd64/
kubeedge-v1.7.0-linux-amd64/edge/
kubeedge-v1.7.0-linux-amd64/edge/edgecore
kubeedge-v1.7.0-linux-amd64/cloud/
kubeedge-v1.7.0-linux-amd64/cloud/csidriver/
kubeedge-v1.7.0-linux-amd64/cloud/csidriver/csidriver
kubeedge-v1.7.0-linux-amd64/cloud/admission/
kubeedge-v1.7.0-linux-amd64/cloud/admission/admission
kubeedge-v1.7.0-linux-amd64/cloud/cloudcore/
kubeedge-v1.7.0-linux-amd64/cloud/cloudcore/cloudcore
kubeedge-v1.7.0-linux-amd64/version

KubeEdge cloudcore is running, For logs visit:  /var/log/kubeedge/cloudcore.log
CloudCore started
[root@kubecloud ~]#  cat /var/log/kubeedge/cloudcore.log
I0823 23:20:45.982339   34298 server.go:73] Version: v1.7.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15df708]

goroutine 1 [running]:
github.com/kubeedge/kubeedge/cloud/cmd/cloudcore/app.NewCloudCoreCommand.func1(0xc00044fb80, 0x28be118, 0x0, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/cmd/cloudcore/app/server.go:84 +0x2e8
github.com/spf13/cobra.(*Command).execute(0xc00044fb80, 0xc000110190, 0x0, 0x0, 0xc00044fb80, 0xc000110190)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00044fb80, 0xc000100058, 0x0, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/root/codes/src/github.com/kubeedge/kubeedge/cloud/cmd/cloudcore/cloudcore.go:16 +0x65
`

**Comment by assdddddff** [comment]
> 
> 
> Oh, is the cloudcore still running now?

The cloud doesn't seem to be working

**Comment by fisherxu** [comment]
> > Oh, is the cloudcore still running now?
> 
> The cloud doesn't seem to be working

You'd better to try the v1.7.2, there's a panic bug in 1.7.0

**Comment by assdddddff** [comment]
> 
> 
> > > Oh, is the cloudcore still running now?
> > 
> > 
> > The cloud doesn't seem to be working
> 
> You'd better to try the v1.7.2, there's a panic bug in 1.7.0

ok
