### ISSUE TITLE
Failed to join AWS edge node to a GCP cloudcore.

### ISSUE THREAD

**Issue by jeffzhu503** [kubeedge/kubeedge#3050]
**What happened**:
We set up the Cloudcore in GCP and tried to have several edge nodes in the same or different public cloud providers join the same Cloudcore.  However we could not successfully do it. 

Here are some error logs we collected from AWS:
oot@ip-172-31-46-190:/data/gopath/src/github.com/kubeedge/kubeedge# ps -ef |grep -i edgecore
root      9479     1  2 17:14 ?        00:00:00 /usr/local/bin/edgecore
 
But it is not really running after I check the status of edgecore using systemctl command.
 
root@ip-172-31-46-190:/data/gopath/src/github.com/kubeedge/kubeedge# systemctl status edgecore
● edgecore.service
   Loaded: loaded (/etc/systemd/system/edgecore.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-08-23 17:13:38 UTC; 4s ago
  Process: 9021 ExecStart=/usr/local/bin/edgecore (code=exited, status=255)
Main PID: 9021 (code=exited, status=255)
 
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]:         /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/google/cadvisor/manager/manager.go:323 +0x53b
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]: goroutine 375 [select]:
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000937070, 0x3b2e440, 0xc00094e2d0, 0xc001290f01, 0xc0001000c0)
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]:         /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000937070, 0x45d964b800, 0x0, 0xc001290f01, 0xc0001000c0)
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]:         /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]: k8s.io/apimachinery/pkg/util/wait.Until(0xc000937070, 0x45d964b800, 0xc0001000c0)
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]:         /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]: created by k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).Start
Aug 23 17:13:38 ip-172-31-46-190 edgecore[9021]:         /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go:649
 
Then I use the command ‘journalctl -u edgecore.service -b’ to see real root cause.
 
Aug 21 16:24:30 ip-172-31-46-190 edgecore[9136]: E0821 16:24:30.770633    9136 dns.go:290] [EdgeMesh] service ec2messages.us-west-2.amazonaws.com is not found in this clust
Aug 21 16:24:30 ip-172-31-46-190 edgecore[9136]: W0821 16:24:30.770671    9136 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Aug 21 16:24:30 ip-172-31-46-190 edgecore[9136]: W0821 16:24:30.770691    9136 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Aug 21 16:24:40 ip-172-31-46-190 edgecore[9136]: F0821 16:24:40.890696    9136 certmanager.go:92] Error: failed to get CA certificate, err: Get "https://34.70.181.71:10002/
 
Using another command ‘tail -f /var/log/syslog’, I can see the same error:
 
root@ip-172-31-46-190:/data/gopath/src/github.com/kubeedge/kubeedge# tail -4 /var/log/syslog
Aug 23 17:20:44 ip-172-31-46-190 edgecore[11547]: I0823 17:20:44.630400   11547 reconciler.go:157] Reconciler: start to sync state
Aug 23 17:20:45 ip-172-31-46-190 edgecore[11547]: E0823 17:20:45.410060   11547 dns.go:290] [EdgeMesh] service ec2messages.us-west-2.amazonaws.com is not found in this cluster
Aug 23 17:20:45 ip-172-31-46-190 edgecore[11547]: W0823 17:20:45.410548   11547 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Aug 23 17:20:45 ip-172-31-46-190 edgecore[11547]: W0823 17:20:45.410683   11547 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns

Does KubeEdge support this kind of use case: Can edge nodes from different cloud providers can join the cluster(Heterogeneous is not working for Kubeedge)?

**Comment by jeffzhu503** [comment]
It was open when we installed cloudcore.

**Comment by zc2638** [comment]
```
Aug 21 16:24:40 ip-172-31-46-190 edgecore[9136]: F0821 16:24:40.890696 9136 certmanager.go:92] Error: failed to get CA certificate, err: Get "https://34.70.181.71:10002/
```
Can you paste this information intact?

**Comment by jeffzhu503** [comment]
@zc2638 I can't find the error message anymore.  Could you please confirm if you have tested this kind of scenario: the setup of KubeEdge in two different public clouds or networks?

**Comment by zc2638** [comment]
This is related to your public cloud network configuration.
Could you tell me your cloud network situation?
For example, there is a layer of gateway proxy or VIP.

And could you please post the content of `/etc/kubeedge/config/edgecore.yaml` ?

**Comment by jeffzhu503** [comment]
I decided to recreate a new Kubernetes master node using kubeadm in GCP.  After it is completed, here is what I get.
 kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY   STATUS    RESTARTS       AGE
kube-system   calico-kube-controllers-74b8fbdb46-cq2rr   1/1     Running   0              5h43m
kube-system   calico-node-dm4cf                          1/1     Running   1 (108m ago)   5h43m
kube-system   coredns-78fcd69978-8dsf4                   1/1     Running   0              22h
kube-system   coredns-78fcd69978-fhgv7                   1/1     Running   0              22h
kube-system   etcd-ke-cloudcore                          1/1     Running   0              22h
kube-system   kube-apiserver-ke-cloudcore                1/1     Running   1              22h
kube-system   kube-controller-manager-ke-cloudcore       1/1     Running   1              22h
kube-system   kube-proxy-mf5lp                           1/1     Running   0              22h
kube-system   kube-scheduler-ke-cloudcore                1/1     Running   1              22h

**Comment by jeffzhu503** [comment]
Now, I am running keadm init --kube-config=$HOME/.kube/config --advertise-address=35.193.86.243.  Here is the new error I am seeing: 
9145 keadm.go:27] the server could not find the requested resource
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00012c001, 0xc000320160, 0x5c, 0xb0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x3d78bc0, 0xc000000003, 0x0, 0x0, 0xc00047e0e0, 0x3a3b201, 0x8, 0x1b, 0xe4e400)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:970 +0x19b
k8s.io/klog/v2.(*loggingT).printDepth(0x3d78bc0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000647060, 0x1, 0x1)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:733 +0x16f
k8s.io/klog/v2.(*loggingT).print(...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:715
k8s.io/klog/v2.Fatal(...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1489
main.main()
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0xdf
goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x3d78bc0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:418 +0xdf
goroutine 29 [IO wait]:
internal/poll.runtime_pollWait(0x7fbafc22b378, 0x72, 0x2cdc3a0)
        /root/.gvm/gos/go1.15/src/runtime/netpoll.go:220 +0x55

**Comment by jeffzhu503** [comment]
What is the requested resource missing here?

**Comment by zc2638** [comment]
Could you paste all the exception information?
It help locate the exception location.
@jeffzhu503

**Comment by jeffzhu503** [comment]
F0929 19:25:00.911123   28403 keadm.go:27] the server could not find the requested resource
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00012c001, 0xc00032a2c0, 0x5c, 0xb0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x3d78bc0, 0xc000000003, 0x0, 0x0, 0xc0003af030, 0x3a3b201, 0x8, 0x1b, 0xe4e4
00)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:970 +0x19b
k8s.io/klog/v2.(*loggingT).printDepth(0x3d78bc0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0006425e0, 0x1, 0x1)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:733 +0x16f
k8s.io/klog/v2.(*loggingT).print(...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:715
k8s.io/klog/v2.Fatal(...)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1489
main.main()
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0xdf
goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x3d78bc0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:418 +0xdf
goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0x7f470d42ec78, 0x72, 0x2cdc3a0)
        /root/.gvm/gos/go1.15/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc00042ac18, 0x72, 0xc0001b0d00, 0x8e8, 0x8e8)
        /root/.gvm/gos/go1.15/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /root/.gvm/gos/go1.15/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00042ac00, 0xc0001b0d00, 0x8e8, 0x8e8, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.15/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc00042ac00, 0xc0001b0d00, 0x8e8, 0x8e8, 0x203000, 0x11d2f1b, 0xc00061d9e0)
        /root/.gvm/gos/go1.15/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000242aa0, 0xc0001b0d00, 0x8e8, 0x8e8, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.15/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc00000f1e0, 0xc0001b0d00, 0x8e8, 0x8e8, 0x1e, 0x8e3, 0xc000739710)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc00061db00, 0x2cd8420, 0xc00000f1e0, 0xe4b825, 0x28241c0, 0x2a02660)
        /root/.gvm/gos/go1.15/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00061d880, 0x2cda100, 0xc000242aa0, 0x5, 0xc000242aa0, 0xd)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00061d880, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc00061d880, 0xc000524000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.15/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0004ad9e0, 0xc000620578, 0x9, 0x9, 0xc000524009, 0x3d79c60, 0x7f473589c108)
        /root/.gvm/gos/go1.15/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x2cd8280, 0xc0004ad9e0, 0xc000620578, 0x9, 0x9, 0x9, 0xc000739d38, 0x138617c, 0x29108e0)
        /root/.gvm/gos/go1.15/src/io/io.go:314 +0x87
io.ReadFull(...)
/root/.gvm/gos/go1.15/src/io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc000620578, 0x9, 0x9, 0x2cd8280, 0xc0004ad9e0, 0x0, 0x0, 0xc000739dd0,
 0xc000426350)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000620540, 0xc0003fc800, 0x0, 0x0, 0x0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000739fa8, 0x0, 0x0)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000426300)
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5

**Comment by jeffzhu503** [comment]
That is all I got from the screen. The top of the error message is the server could not find the requested resource
goroutine 1 [running].  And I have the second one in the team who received the same error message.
