### ISSUE TITLE
Make edge failed in Mac OS

### ISSUE THREAD

**Issue by zhanghongtong** [kubeedge/kubeedge#309]
**What happened**:
Make edge failed

**What you expected to happen**:
Make edge success

**How to reproduce it (as minimally and precisely as possible)**:
```
$ git clone https://github.com/kubeedge/kubeedge.git $GOPATH/src/github.com/kubeedge/kubeedge
$ cd $GOPATH/src/github.com/kubeedge/kubeedge/edge
$ make
go build cmd/edge_core.go
# github.com/kubeedge/kubeedge/edge/pkg/edged/containers
pkg/edged/containers/helpers.go:114:33: undefined: ContainerManager
pkg/edged/containers/helpers.go:129:10: undefined: containerManager
make: *** [edge_core] Error 2
```

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration: MacBook Pro
- OS (e.g. from /etc/os-release): macOS Mojave 10.14.3
- Kernel (e.g. `uname -a`):
- Others: go version go1.11.5 darwin/amd64

**Comment by m1093782566** [comment]
dup #292?

**Comment by zhanghongtong** [comment]
@m1093782566  Yes, but I will also report an error when performing cross compilation.
```
$ make cross_build
export GOARCH=arm
export GOOS="linux"
export GOARM=6
export CGO_ENABLED=1
export CC=arm-linux-gnueabi-gcc
go build cmd/edge_core.go
# github.com/kubeedge/kubeedge/edge/pkg/edged/containers
pkg/edged/containers/helpers.go:114:33: undefined: ContainerManager
pkg/edged/containers/helpers.go:129:10: undefined: containerManager
make: *** [cross_build] Error 2
```

**Comment by m1093782566** [comment]
Yes because cross_build does not support darwin yet.

**Comment by zhanghongtong** [comment]
OK, I know, do you have plans to fix this?

**Comment by m1093782566** [comment]
Yeah, I think it will be a good community contribution :)

**Comment by sids-b** [comment]
@zhanghongtong , If possible please do contribute with this fix :)

**Comment by m1093782566** [comment]
Closing this in favor of decrease issues.
