### ISSUE TITLE
Sort out kubeedge message topics

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#31]
The communication between components of kubeedge is based on message. There are some message topics and we need to sort them out in document for the sake of helping contributors/developers understanding kubeedge well.

**Comment by m1093782566** [comment]
@sids-b @rohitsardesai83 

I think we very need such kind of document. Could you help it out?

**Comment by sids-b** [comment]
> @sids-b @rohitsardesai83
> 
> I think we very need such kind of document. Could you help it out?

Sure @m1093782566
