### ISSUE TITLE
edgemesh agent always pending

### ISSUE THREAD

**Issue by first-sight12** [kubeedge/kubeedge#3108]
**What happened**:
When edgemesh is deployed, edgemesh agent is always in pending state

```shell
[root@k8s-master edgemesh-agent]# kubectl get po -n kubeedge
NAME                               READY   STATUS    RESTARTS   AGE
edgemesh-agent-cloud-fgw8c         1/1     Running   0          80m
edgemesh-agent-cloud-nmbcb         1/1     Running   0          80m
edgemesh-agent-edge-4pbpd          0/1     Pending   0          63m
edgemesh-agent-edge-69gpr          0/1     Pending   0          63m
edgemesh-server-5f4d8b8b5b-fv9bj   1/1     Running   0          6h53m
```

Edge node to view edgecore status
![image](https://user-images.githubusercontent.com/88825053/131803622-be604c9a-1423-4366-9cb7-22e875842c6d.png)

![image](https://user-images.githubusercontent.com/88825053/131803569-a1af20fa-43f9-4c3e-a0cb-b2f69818a7e5.png)

**What you expected to happen**:

I hope to solve the above problems

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- EdgeMesh version: edgemesh：v1.8

- Kubernetes version (use `kubectl version`):v1.19.3

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):kubeedge-v1.7.2

- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - Architecture:          x86_64
    CPU op-mode(s):        32-bit, 64-bit
    Byte Order:            Little Endian
    CPU(s):                4
    On-line CPU(s) list:   0-3
    Thread(s) per core:    1
    Core(s) per socket:    1
    Socket(s):             4
    NUMA node(s):          1
    Vendor ID:             GenuineIntel
    CPU family:            6
    Model:                 61
    Model name:            Intel Core Processor (Broadwell, IBRS)
    Stepping:              2
    CPU MHz:               2095.148
    BogoMIPS:              4190.29
    Hypervisor vendor:     KVM
    Virtualization type:   full
    L1d cache:             32K
    L1i cache:             32K
    L2 cache:              4096K
    NUMA node0 CPU(s):     0-3
    Flags:                 fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm 3dnowprefetch ssbd ibrs ibpb fsgsbase bmi1 hle avx2 smep bmi2 erms rtm rdseed adx smap xsaveopt md_clear spec_ctrl

  - OS (e.g. `cat /etc/os-release`):
  - NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):

  Linux k8s-master 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Go version (e.g. `go version`):

- Others:

  </details>

- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): v1.7.2
  - Hardware configuration (e.g. `lscpu`):
  - Architecture:          x86_64
    CPU op-mode(s):        32-bit, 64-bit
    Byte Order:            Little Endian
    CPU(s):                4
    On-line CPU(s) list:   0-3
    Thread(s) per core:    1
    Core(s) per socket:    1
    Socket(s):             4
    NUMA node(s):          1
    Vendor ID:             GenuineIntel
    CPU family:            6
    Model:                 61
    Model name:            Intel Core Processor (Broadwell, IBRS)
    Stepping:              2
    CPU MHz:               2095.148
    BogoMIPS:              4190.29
    Hypervisor vendor:     KVM
    Virtualization type:   full
    L1d cache:             32K
    L1i cache:             32K
    L2 cache:              4096K
    NUMA node0 CPU(s):     0-3
    Flags:                 fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm 3dnowprefetch ssbd ibrs ibpb fsgsbase bmi1 hle avx2 smep bmi2 erms rtm rdseed adx smap xsaveopt md_clear spec_ctrl

  - OS (e.g. `cat /etc/os-release`):
  - NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):

  Linux ke-edge1 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Go version (e.g. `go version`):

- Others:

  </details>

**Comment by stingshen** [comment]
The issue should mitigate after this commit: https://github.com/kubeedge/kubeedge/commit/bd19593fee28bc4d5cc788cc656c0b59c1a39574#diff-435879603c8c2c6b20c971bd976216fe2e635ca24de924ef494f888a910b4b64

Root cause: before the commit, node location cache would be updated only after the node ready condition shows up. But some times, k8s scheduler assigns the pod to node right before the node ready condition shows up, and the pod would be ignored if the node is not in node location cache:

![Screenshot from 2021-11-16 15-15-52](https://user-images.githubusercontent.com/6214067/141938479-16a7e4d1-eb74-47ca-b433-28fe4c19e61e.png)

**Comment by gy95** [comment]
@stingshen  do you mean that we should revert https://github.com/kubeedge/kubeedge/pull/3229? :)

**Comment by stingshen** [comment]
> 

No. Actually, #3229 fixes the issue from my observation.
