### ISSUE TITLE
Maintain Feature/API version.

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#312]
**What would you like to be added**:
Each feature/api (including configurations) should have versioning which can make it easy to maintain. Also API's/features can have an alpha/beta/stable tag similar to Kubernetes. Need to define a feature/api graduation process as well.

**Why is this needed**:
This is help in maintaining API/feature backward compatibility. Management becomes easy and can help in review process of enhancement designs.

Thoughts @m1093782566 @kevin-wangzefeng @rohitsardesai83 ??

**Comment by m1093782566** [comment]
+1

**Comment by sids-b** [comment]
Kubernetes api-versioning for example: https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-versioning

**Comment by kevin-wangzefeng** [comment]
We do need to clarify the critiera of graduation by feature level.
Different features may have different critiera on alpha/beta/stable.
For the API versioning, I think we may just distinguish unstable vs. stable at API object level. Kubernetes also doesn't have a good mechanism for unstable features that relavent to some fields in an already stable API object.

**Comment by rohitsardesai83** [comment]
@kevin-wangzefeng , how do we go about this ? Do we need to have a document in place which describes this ?

**Comment by kevin-wangzefeng** [comment]
Yes, we need a document for this. Currently I'm working on the versioning doc, not yet started the API convention and general graduation / deprecation guide.

**Comment by sids-b** [comment]
This issue is fixed by #850
