### ISSUE TITLE
KubeEdge Playground on Katacoda

### ISSUE THREAD

**Issue by ansjin** [kubeedge/kubeedge#3142]
Hi,

I created a playground for KubeEdge deployment on Katacoda for `one cloud node and one edge node`. It has the following :

- Deployment of K8s using kubeadm
- Deployment of KubeEdge using Keadm
- Enabling Logs, and flannel
- Deployment of Sedna 

Please check it out: https://www.katacoda.com/ansjin/scenarios/getting-started-with-kubeedge-sedna

**Comment by llhuii** [comment]
Hi, I have created all-in-one playground for Sedna with one liner:
- A Kubernetes v1.21 cluster
- KubeEdge v1.8 with two edge nodes

The one line script requires you:
- 2 CPUs or more
- 2GB free memory
- 10GB of free disk space
- Internet connection(docker hub, github etc.)
- Linux platform, such as ubuntu/centos
- Docker 17.06+

You can play it here https://www.katacoda.com/kubeedge-sedna/scenarios/all-in-one
