### ISSUE TITLE
How do we partition a config map containing different device instances , models

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#315]
**What would you like to be added**:
The current device crd design proposal https://github.com/kubeedge/kubeedge/pull/181 introduces config maps to store device models and instances for all devices belonging to an edge node. We need a way to segregate the configs by device models / protocols etc.

**Why is this needed**:
Considering the [1mb size limitation in etcd](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/limit.md) , we may hit a cap if we attempt to store all device models and devices in  a single config map. What should be the best way to partition a monolithic config map into smaller config maps ? Should the partitioning be based on the protocol type or based on device model ?

**Comment by rohitsardesai83** [comment]
@kevin-wangzefeng , @qizha , @CindyXing , thoughts ?

**Comment by CindyXing** [comment]
An easy way is to define configmapGroups.

**Comment by rohitsardesai83** [comment]
> An easy way is to define configmapGroups.

I am sorry I did not understand what you meant by configmapGroups. Could you please explain a bit in detail.

**Comment by CindyXing** [comment]
Thanks Rohit. What I meant is that we can create a new type called ConfigMapGroup where device configs can be stored and relation to device (configmap name). After the meta data flow down to edge data store, edged can handle the configMapGroup and restructure the configmap for each device. 

This way, for a group of devices, only one copy of meta data can be saved. 

Thought?

**Comment by rohitsardesai83** [comment]
> Thanks Rohit. What I meant is that we can create a new type called ConfigMapGroup where device configs can be stored and relation to device (configmap name). After the meta data flow down to edge data store, edged can handle the configMapGroup and restructure the configmap for each device.
> 
> This way, for a group of devices, only one copy of meta data can be saved.
> 
> Thought?

Sorry for the delayed response , I will think more about this . Do you mean to say ConfigMapGroup is a new CRD ?
