### ISSUE TITLE
New issue/PR template

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#32]
We need a formal issue/PR template for people whom are going to create an issue/PR for KubeEdge.

xref: https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE

https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by daijiale** [comment]
Maybe we need a standardized KubeEdge contribution guide, not only involved issue/PR, but also for code specification and development environment report , if you want, I am willing to help making a demo for you

**Comment by daijiale** [comment]
> We need a formal issue/PR template for people whom are going to create an issue/PR for KubeEdge.
> 
> xref: https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE
> 
> https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Maybe we need a standardized KubeEdge contribution guide, not only involved issue/PR, but also for code specification and development environment report , if you want, I am willing to help making a demo for you

**Comment by m1093782566** [comment]
@daijiale Sure, would love to see your contributions. So, please show me :)
