### ISSUE TITLE
Whether KubeEdge supports master node migration

### ISSUE THREAD

**Issue by farawaychen** [kubeedge/kubeedge#3206]
**What happened and what you expected to happen**:
I have created a Kubeedge cluster now, whether KubeEdge supports switching k8S master node.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.19.15
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.8

**Comment by fisherxu** [comment]
What's the meaning of  `switching k8S master node`?

**Comment by farawaychen** [comment]
Change the master of the K8S cluster to another device.IP is different.

**Comment by fisherxu** [comment]
> Change the master of the K8S cluster to another device.IP is different.

Ohh, you need to migration all kubeedge related object to the related cluster.

**Comment by farawaychen** [comment]
How to related object?
1. On the new Master node, do I need to redeploy Cloudcore and generate a new token?  
2. On the Edge node, do I need to execute "keadm reset" to join in the new k8s master node?
