### ISSUE TITLE
CloudHub supports other module subscribe the message from edge

### ISSUE THREAD

**Issue by todayisgood** [kubeedge/kubeedge#323]
**What would you like to be added**:
 supports other modules to subscribe the message from edge

**Why is this needed**:
I want to extend a module to handle the message from the edge. But I
found the message from the edge only  be send to the controller module and the custom module  will not be able to process the message.  Can it support send the message to other modules?

the  code in github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub/wsserver/server.go
```GO
// EventReadLoop processes all read requests
func (eh *EventHandle) EventReadLoop(hi hubio.CloudHubIO, info *emodel.HubInfo, stop chan ExitCode) {
	for {
		var msg model.Message
		// set the read timeout as the keepalive interval so that we can disconnect when heart beat is lost
		err := hi.SetReadDeadline(time.Now().Add(time.Duration(eh.KeepaliveInterval) * time.Second))
		if err != nil {
			bhLog.LOGGER.Errorf("SetReadDeadline error, %s", err.Error())
			stop <- webSocketReadFail
			return
		}
		_, err = hi.ReadData(&msg)
		if err != nil {
			bhLog.LOGGER.Errorf("read error, connection for node %s will be closed, reason: %s", info.NodeID, err.Error())
			stop <- webSocketReadFail
			return
		}
		msg.SetResourceOperation(fmt.Sprintf("node/%s/%s", info.NodeID, msg.GetResource()), msg.GetOperation())

		event := emodel.MessageToEvent(&msg)
		bhLog.LOGGER.Infof("event received for node %s %s, content: %s", info.NodeID, dumpEventMetadata(&event), event.Content)
		if event.IsFromEdge() {
			err := eh.EventQueue.Publish(info, &event)
			if err != nil {
				// content is not logged since it may contain sensitive information
				bhLog.LOGGER.Errorf("fail to publish event for node %s, %s, reason: %s",
					info.NodeID, dumpEventMetadata(&event), err.Error())
				stop <- eventQueueDisconnect
				return
			}
		}
	}
}


```

```GO
// Publish sends message via the rchannel to Edge Controller
func (q *ChannelEventQueue) Publish(info *model.HubInfo, event *model.Event) error {
	msg := model.EventToMessage(event)
	q.ctx.Send("controller", msg)
	return nil
}
```

**Comment by sids-b** [comment]
@todayisgood , Nice Catch !! We will soon be having other modules in cloud(device-controller, router), etc. We will soon be changing this logic.

**Comment by sids-b** [comment]
But if you have urgent requirement, a quick fix would be to use 
```go
q.ctx.Send2Group("controller", msg)
``` 
and add the custom module in controller group.

**Comment by todayisgood** [comment]
> But if you have urgent requirement, a quick fix would be to use
> 
> ```go
> q.ctx.Send2Group("controller", msg)
> ```
> 
> and add the custom module in controller group.

Thank you very much. When will it be released?

**Comment by sids-b** [comment]
> > But if you have urgent requirement, a quick fix would be to use
> > ```go
> > q.ctx.Send2Group("controller", msg)
> > ```
> > 
> > 
> > and add the custom module in controller group.
> 
> Thank you very much. When will it be released?

Release is Due by May 31, 2019

**Comment by todayisgood** [comment]
> > > But if you have urgent requirement, a quick fix would be to use
> > > ```go
> > > q.ctx.Send2Group("controller", msg)
> > > ```
> > > 
> > > 
> > > and add the custom module in controller group.
> > 
> > 
> > Thank you very much. When will it be released?
> 
> Release is Due by May 31, 2019, but we might have the changes in master branch before release

Nice!

> > > But if you have urgent requirement, a quick fix would be to use
> > > ```go
> > > q.ctx.Send2Group("controller", msg)
> > > ```
> > > 
> > > 
> > > and add the custom module in controller group.
> > 
> > 
> > Thank you very much. When will it be released?
> 
> Release is Due by May 31, 2019, but we might have the changes in master branch before release



> > > But if you have urgent requirement, a quick fix would be to use
> > > ```go
> > > q.ctx.Send2Group("controller", msg)
> > > ```
> > > 
> > > 
> > > and add the custom module in controller group.
> > 
> > 
> > Thank you very much. When will it be released?
> 
> Release is Due by May 31, 2019, but we might have the changes in master branch before release

Nice!

**Comment by sids-b** [comment]
@todayisgood , we also used send2group to send the message to another module than edgeController which is device controller.
I am closing this issue now

**Comment by m1093782566** [comment]
Thanks @sids-b 

@todayisgood Would you please check it?

**Comment by todayisgood** [comment]
Thanks @sids-b  @m1093782566 
It's good
