### ISSUE TITLE
Error: CustomResourceDefinition.apiextensions.k8s.io "devices.devices.kubeedge.io" is invalid: spec.versions: Invalid value: []

### ISSUE THREAD

**Issue by yookacn** [kubeedge/kubeedge#3237]
**What happened**:
root@kubeedge-cloud: keadm init 
Kubernetes version verification passed, KubeEdge installation will start...
Error: CustomResourceDefinition.apiextensions.k8s.io "devices.devices.kubeedge.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha2", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc007c4b438), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.5.0  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver

Flags:
      --advertise-address string   Use this key to set IPs in cloudcore's certificate SubAltNames field. eg: 10.10.102.78,10.10.102.79
      --domainname string          Use this key to set domain names in cloudcore's certificate SubAltNames field. eg: www.cloudcore.cn,www.kubeedge.cn
  -h, --help                       help for init
      --kube-config string         Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string    Use this key to download and use the required KubeEdge version
      --master string              Use this key to set K8s master address, eg: http://127.0.0.1:8080
      --tarballpath string         Use this key to set the temp directory path for KubeEdge tarball, if not exist, download it

F1018 20:19:54.438694    2984 keadm.go:27] CustomResourceDefinition.apiextensions.k8s.io "devices.devices.kubeedge.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha2", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc007c4b438), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc0009e6000, 0x263, 0x2b7)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2c93380, 0xc000000003, 0x0, 0x0, 0xc0002400e0, 0x29b2f22, 0x8, 0x1b, 0x1e39a00)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printDepth(0x2c93380, 0xc000000003, 0x0, 0x0, 0x1, 0xc000a9ff68, 0x1, 0x1)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:718 +0x165
k8s.io/klog/v2.(*loggingT).print(...)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:703
k8s.io/klog/v2.Fatal(...)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1436
main.main()
        /data/gopath/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0xa5

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x2c93380)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 15 [IO wait]:
internal/poll.runtime_pollWait(0x7f9e388f2138, 0x72, 0x1e3b8e0)
        /usr/local/go/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc00063e218, 0x72, 0xc000180900, 0x8b4, 0x8b4)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00063e200, 0xc000180900, 0x8b4, 0x8b4, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc00063e200, 0xc000180900, 0x8b4, 0x8b4, 0x203000, 0x78d55b, 0xc0001de4e0)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010028, 0xc000180900, 0x8b4, 0x8b4, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc00034c140, 0xc000180900, 0x8b4, 0x8b4, 0x558, 0x884, 0xc00066d710)
        /usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc0001de600, 0x1e38460, 0xc00034c140, 0x419225, 0x1a39040, 0x1bb4360)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc0001de380, 0x1e3a100, 0xc000010028, 0x5, 0xc000010028, 0x547)
        /usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0001de380, 0x0, 0x0, 0xc00066dd18)
        /usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc0001de380, 0xc000132000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0004c3e00, 0xc0008d4118, 0x9, 0x9, 0xc00066dd18, 0x1cfd200, 0x93aa8b)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1e382c0, 0xc0004c3e00, 0xc0008d4118, 0x9, 0x9, 0x9, 0xc00007c040, 0x0, 0x1e386a0)
        /usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc0008d4118, 0x9, 0x9, 0x1e382c0, 0xc0004c3e00, 0x0, 0x0, 0xc00066ddd0, 0x475645)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0008d40e0, 0xc0004f8210, 0x0, 0x0, 0x0)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00066dfa8, 0x0, 0x0)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000602600)
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /data/gopath/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5

**What you expected to happen**:
keadm init success.

**How to reproduce it (as minimally and precisely as possible)**:
git clone https://github.com/kubeedge/kubeedge
cd kubeedge
git checkout -b v1.7 origin/release-1.7
make all WHAT=keadm
make all WHAT=cloudcore && make all WHAT=edgecore
cp _output/local/bin/* /usr/local/bin/
keadm init

**Anything else we need to know?**:

**Environment**: 

- Kubernetes version (use `kubectl version`): 
`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
`
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`): ubuntu18.04  
  - Kernel (e.g. `uname -a`): x86_64 GNU/Linux
  - Go version (e.g. `go version`): go1.15 linux/amd64
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Rachel-Shao** [comment]
There are some problems with version 1.7, please use version 1.7.1 or 1.8 to see if there are similar problems #3030
