### ISSUE TITLE
Add installer for kubeedge

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#324]
**What would you like to be added**:

Many users complained that kubeedge installation is too complicated and it may prevent people from trying kubeedge.

**Why is this needed**:

Add installer for simplified the installation of kubeedge. e.g. 

```
$ kubeedge init cloud # install k8s master and cloud components 

$ kubeedge join <node> # install edge-core and register it to cloud
```

**Comment by m1093782566** [comment]
cc @CindyXing @qizha @kevin-wangzefeng @sids-b @rohitsardesai83

**Comment by sids-b** [comment]
Sounds good. Need to come up with a design for this so that it can be extended further for devices, etc.
For eg: 1 change i would suggest is
```
$ kubeedge join <cloud-ip>  <node> # install edge-core and register to correct cloud
```
Still think above command will have complications(like generating correct certificates,etc) while actual implementation. 
Indeed a very important and valuable feature.

**Comment by rohitsardesai83** [comment]
:+1:

**Comment by rohitsardesai83** [comment]
I feel can we keep k8s installation out of this ? 
The pre-requisite for installing kubeedge can be a kubernetes cluster installed using tools of user choice.

The kubeedge install should care about installing kubeedge cloud / edge side components.

Also , this installer need not be extended to manage devices.  
Device management can be done using kubectl commands since devices are CRDs. 

The scope of the installer could be to install cloud , join edge node , unbind edge node , uninstall cloud for now. we can see the scope of how kubeadm does things.

**Comment by m1093782566** [comment]
> I feel can we keep k8s installation out of this ?
> The pre-requisite for installing kubeedge can be a kubernetes cluster installed using tools of user choice.

Actually I want to reduce the work of installing k8s cluster for uers.

> Device management can be done using kubectl commands since devices are CRDs.

Make sense.

> we can see the scope of how kubeadm does things.

I think we should learn k3s instead of kubeadm. Kubeadm even ask users to install kubelet by themselves!

**Comment by rohitsardesai83** [comment]
agree on k3s study ! I still feel we should not complicate our edge installer by introducing k8s control components as well. 

one more question : 
what is the target audience for this installer ?

1. users who want to try running some apps on top of kubeedge .
2. developers who want to setup a 1-node edge cluster and then update binaries or docker images after changing code ?

**Comment by m1093782566** [comment]
I think we mainly focus on fresh users, so 1) if we can only choose one. For 2) I think it's more about upgrade stuff and developers may do some hacks themselves.

**Comment by sids-b** [comment]
We can have something like PreFlight checks in Kubeadm. kubeedge init cloud will check if docker already installed(install if not exists and check version compatibility), same for k8s and other prerequisites. Makes sense ?

**Comment by samy2019** [comment]
I am proposing the following commands for kubeedge installation process.

There are primarily 2 components (cloud and node [edge])

**Cloud commands will be**:
1. kubeedge cloud init
2. kubeedge cloud reset

**Edge commands will be**:
1. kubeedge node init
2. kubeedge node reset
3. kubeedge node join

**NOTE**: GO will NOT be installed with any of the commands or processes below. User himself needs to do the same in the environment. Also it is understood and assumed that user has already build edge-controller and edge_core using the steps.

**Explaining the commands in detail**

_Cloud commands_:
1. kubeedge cloud init - 
   What is it? - This command will be responsible to bring up kubeedge cloud components like edge-controller and K8S (using kubeadm)
   What it will do? - 
   i. Check version of OS and install subsequently the required pre-requisites using supported steps. 
       Currently we will support ONLY (Ubuntu & CentOS)
   ii. Check and install all the pre-requisites before executing edge-controller, which are
           a. docker (currently 18.06.0~ce~3-0~ubuntu) and check is service is up.
	   b. kubelet, kubeadm & kubectl (latest version)
	   c. openssl (latest available in OS repos)
 iii. Generate certificates using openssl and save the certs in a predefined static path. 
      It will also compress the folder and display on the terminal so that user can pick it up and transfer it to edge node VM/host.
  iv. It will update the certificate information in controller.yaml
   v. Start "kubeadm init". 
      **NOTE**: If any issues or error reported from "kubeadm init", "kubeedge cloud init" command is not responsible, as it may occur due to the environment. User has to resolve it. We are taking up this activity to have 1 click install approach for kubeedge and not kubeadm.
  vi. Update /etc/kubernetes/manifests/kube-apiserver.yaml with below information
      _- --insecure-port=8080
      - --insecure-bind-address=0.0.0.0_ 
 vii. start edge-controller
   
2. kubeedge cloud reset - 
   What is it? - This command will be responsible to bring down kubeedge cloud components edge-controller and call kubeadm reset (to stop K8S)
   What it will do? -
    i. It shall get the nodes and execute "kubectl drain <node id> --force". 
   ii. Kill edge-controller process
  iii. Execute "kubeadm reset"

Edge commands:
1. kubeedge node init - 
   What is it? - This command will be responsible to install pre-requisites kubeedge edge component (edge_core)
   What it will do? - 
   i. Check version of OS and install subsequently the required pre-requisites using supported steps. Currently we will support ONLY (Ubuntu & CentOS)
  ii. Check and install all the pre-requisites before executing edge-controller, which are
           a. docker (currently 18.06.0~ce~3-0~ubuntu) and check is service is up.
	   b. mosquitto (latest available in OS repos) and check if running.
	   c. kubelet
 iii. This command will take --certPath (string type) as mandatory option which will the certificates path in where the certs were transfered from cloud. It will modify $GOPATH/src/github.com/kubeedge/kubeedge/edge/conf/edge.yaml, edgehub.websocket.certfile and edgehub.websocket.keyfile field.   
  iv. Modify $GOPATH/src/github.com/kubeedge/kubeedge/build/node.json and apply it using kubectl command to api-server	   
	  **NOTE**: you can use the -s or --server flags to specify the address and port of the Kubernetes API server. Refer "https://kubernetes.io/docs/reference/kubectl/overview/"
	   
2. kubeedge node join -
   What is it? - This command will be responsible to make pre-requisite modifications and start kubeedge edge component (edge_core)
   What it will do? - 
   i. This command will take mandatory "-s" or "--server" flag to specify the address and port of the Kubernetes API server
 ii. Modify $GOPATH/src/github.com/kubeedge/kubeedge/edge/conf/edge.yaml
       a. Update the IP address of the master in the websocket.url field. 
	   b. Replace fb4ebb70-2783-42b8-b3ef-63e2fd6d242eq with edge node ip in edge.yaml for the fields: controller:node-id, edged:hostname-override
	   c. In websocket:URL, replace 0.0.0.0 with server ip from "-s" option.
  iii. Register or add node to master, Using Flag "-s" or "--server" mandatory field, it will connect with the master (api-server).  Modify $GOPATH/src/github.com/kubeedge/kubeedge/build/node.json and apply it using kubectl command to api-server	   
**NOTE**: you can use the -s or --server flags to specify the address and port of the Kubernetes API server. Refer "https://kubernetes.io/docs/reference/kubectl/overview/"
  iv. start edge_core
   
3. kubeedge node reset - 
   What is it? - This command will be responsible to bring down kubeedge edge component (edge_core)
   What it will do? -
   i. Remove node.
  ii. Kill edge_core process

**Comment by m1093782566** [comment]
@samy2019 Thanks for your input.

I think it's worth for writing a formal proposal?
