### ISSUE TITLE
ApiServer IP should be masked

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#327]
**What happened**:
APIServer IP is visible.

**What you expected to happen**:
APIServer IP should not be visible to anyone.

If the IP of apiserver is visible, anyone can play around with apiserver resulting in our test cases getting failed. Need to find a way to mask it.

**Comment by m1093782566** [comment]
@sids-b Would you please provide more context?

**Comment by sids-b** [comment]
Opps forgot to post line number.
https://github.com/kubeedge/kubeedge/blob/master/tests/e2e/scripts/execute.sh#L56
In our e2e test cases source code, we have exposed the ApiServer public IP address. Anyone can delete our deployments, add more deployments and play around with ApiServer which will result in our e2e test case failure. Need to think of some way to mask it.

**Comment by m1093782566** [comment]
Oops!

**Comment by sids-b** [comment]
@pavan187 , I think we should spend some time on this one now.

**Comment by sids-b** [comment]
This issue will be fixed once #856 is merged
