### ISSUE TITLE
Problem creating Cloudcore

### ISSUE THREAD

**Issue by allenleu** [kubeedge/kubeedge#3273]
During the deployment of version 1.8, I used ha-deployme.yaml to create deployment, and the number of deployments READY was 0. I noticed that there was a label in the ha-deployme.yaml.example file, readinessGates:

- conditionType: "kubeedge.io/CloudCoreIsLeader"

When I delete it and create deployment again, the number of READY is normal. Should I keep this label in the YAML file? What does it do?

**Comment by QeelinDarly** [comment]
Maybe you should remove your labels, try again.

**Comment by allenleu** [comment]
> Maybe you should remove your labels, try again.

Yes, I removed the label and Cloudcore is working fine. I just don't know if this label is left over from the historical version. I see that there is no code for this label in version 1.7 or later. And, when I remove this label, is my deployed environment highly available?

**Comment by Rachel-Shao** [comment]
This is the description of `readinessGates`:  https://zhuanlan.zhihu.com/p/158664888
And there is also a description of the meaning of `conditionType: "kubeedge.io/CloudCoreIsLeader"` in `kubeedge/docs/proposals/cloudcore-ha-design.md`, which mentions: "_It means traffic is not forward to the back cloudcore until we Patch the status of "kubeedge.io/CloudCoreIsLeader" from "False" to "True" after this cloudcore becoming leader._"
I think the use of `kubeedge.io/CloudCoreIsLeader` ensures that the pod will work only when the current `cloudcore` is the leader, otherwise it will cause some problems such as...the `cloudcore` that is not the leader but are running pod.
hopes it can help u  (*￣︶￣)

**Comment by allenleu** [comment]
> This is the description of `readinessGates`: https://zhuanlan.zhihu.com/p/158664888 And there is also a description of the meaning of `conditionType: "kubeedge.io/CloudCoreIsLeader"` in `kubeedge/docs/proposals/cloudcore-ha-design.md`, which mentions: "_It means traffic is not forward to the back cloudcore until we Patch the status of "kubeedge.io/CloudCoreIsLeader" from "False" to "True" after this cloudcore becoming leader._" I think the use of `kubeedge.io/CloudCoreIsLeader` ensures that the pod will work only when the current `cloudcore` is the leader, otherwise it will cause some problems such as...the `cloudcore` that is not the leader but are running pod. hopes it can help u (*￣︶￣)

**Comment by allenleu** [comment]
> > This is the description of `readinessGates`: https://zhuanlan.zhihu.com/p/158664888 And there is also a description of the meaning of `conditionType: "kubeedge.io/CloudCoreIsLeader"` in `kubeedge/docs/proposals/cloudcore-ha-design.md`, which mentions: "_It means traffic is not forward to the back cloudcore until we Patch the status of "kubeedge.io/CloudCoreIsLeader" from "False" to "True" after this cloudcore becoming leader._" I think the use of `kubeedge.io/CloudCoreIsLeader` ensures that the pod will work only when the current `cloudcore` is the leader, otherwise it will cause some problems such as...the `cloudcore` that is not the leader but are running pod. hopes it can help u (*￣︶￣)

Thank you for your reply. I've already seen this article, I have a question, the value of conditionType (kubeedge. IO/CloudCoreIsLeader) is defined in where? I can't find it in the 1.8 version of the code.

**Comment by allenleu** [comment]
> > > This is the description of `readinessGates`: https://zhuanlan.zhihu.com/p/158664888 And there is also a description of the meaning of `conditionType: "kubeedge.io/CloudCoreIsLeader"` in `kubeedge/docs/proposals/cloudcore-ha-design.md`, which mentions: "_It means traffic is not forward to the back cloudcore until we Patch the status of "kubeedge.io/CloudCoreIsLeader" from "False" to "True" after this cloudcore becoming leader._" I think the use of `kubeedge.io/CloudCoreIsLeader` ensures that the pod will work only when the current `cloudcore` is the leader, otherwise it will cause some problems such as...the `cloudcore` that is not the leader but are running pod. hopes it can help u (*￣︶￣)
> 
> Thank you for your reply. I've already seen this article, I have a question, the value of conditionType (kubeedge. IO/CloudCoreIsLeader) is defined in where? I can't find it in the 1.8 version of the code.

Thank you for your reply. I've already seen this article, I have a question, the value of conditionType (kubeedge. IO/CloudCoreIsLeader) is defined in where? I can't find it in the 1.8 version of the code.

**Comment by allenleu** [comment]
> This is the description of `readinessGates`: https://zhuanlan.zhihu.com/p/158664888 And there is also a description of the meaning of `conditionType: "kubeedge.io/CloudCoreIsLeader"` in `kubeedge/docs/proposals/cloudcore-ha-design.md`, which mentions: "_It means traffic is not forward to the back cloudcore until we Patch the status of "kubeedge.io/CloudCoreIsLeader" from "False" to "True" after this cloudcore becoming leader._" I think the use of `kubeedge.io/CloudCoreIsLeader` ensures that the pod will work only when the current `cloudcore` is the leader, otherwise it will cause some problems such as...the `cloudcore` that is not the leader but are running pod. hopes it can help u (*￣︶￣)

Thank you for your reply. I've already seen this article, I have a question, the value of conditionType (kubeedge. IO/CloudCoreIsLeader) is defined in where? I can't find it in the 1.8 version of the code.

**Comment by Rachel-Shao** [comment]
The current code does not seem to update the value of `CloudCoreIsLeader`, but I found a pr in the past #1650, which contains content to modify the value of `CloudCoreIsLeader`. 
This part of code has been deleted. This may be related to the future plan of cloudcore HA?  You may need to ask @fisherxu

**Comment by allenleu** [comment]
> @allenleu The current code does not seem to update the value of `CloudCoreIsLeader`, but I found a pr in the past #1650, which contains content to modify the value of `CloudCoreIsLeader`. This part of code has been deleted. This may be related to the future plan of cloudcore HA? You may need to ask @fisherxu

OK，thanks. @fisherxu Can you help me out with this question？
