### ISSUE TITLE
dial websocket error(x509: cannot validate certificate for 192.168.204.138 because it doesn't contain any IP SANs)

### ISSUE THREAD

**Issue by liyinxin** [kubeedge/kubeedge#3298]
**What happened**:
dial websocket error(x509: cannot validate certificate for 192.168.204.138 because it doesn't contain any IP SANs)
**What you expected to happen**:
My edgecore can connect to the cloudcore
**How to reproduce it (as minimally and precisely as possible)**:
Just cloudcore use keadm init, then edgecore join. The edgecore.service must dead,  I generate the CA CERT files with the certgen.sh, and I copy these files to the edgecore /etc/kubeedge. Then the edgecore.service is running. And the error is occured:
`dial websocket error(x509: cannot validate certificate for 192.168.204.138 because it doesn't contain any IP SANs)`
**Anything else we need to know?**:
nothing
**Environment**:
- Kubernetes version (use `kubectl version`):v1.21.6
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):cloudcore,edgecore 1.8.2
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
       NAME="Ubuntu"
       VERSION="20.04.2 LTS (Focal Fossa)"
       ID=ubuntu
       ID_LIKE=debian
       PRETTY_NAME="Ubuntu 20.04.2 LTS"
  - Kernel (e.g. `uname -a`):Linux ubuntu 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  - Go version (e.g. `go version`):go version go1.17.3 linux/amd64
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):v1.8.2
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
       NAME="Ubuntu"
       VERSION="20.04.2 LTS (Focal Fossa)"
       ID=ubuntu
       ID_LIKE=debian
       PRETTY_NAME="Ubuntu 20.04.2 LTS"
  - Kernel (e.g. `uname -a`):5.4.0-77-generic
  - Go version (e.g. `go version`):go version go1.17.3 linux/amd64
  - Others:

  </details>

**Comment by gy95** [comment]
no need to generate CAs by yourself, you only need to execute this below command in shell
```
keadm init --advertise-address="THE-EXPOSED-IP"
keadm join --cloudcore-ipport=192.168.20.50:10000 --token=27a37ef16159f7d3be8fae95d588b79b3adaaf92727b72659eb89758c66ffda2.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTAyMTYwNzd9.JBj8LLYWXwbbvHKffJBpPd5CyxqapRQYDIXtFZErgYE
```

ref: https://kubeedge.io/en/docs/setup/keadm/

**Comment by liyinxin** [comment]
@gy95 yes, I did these:
```keadm init --advertise-address="THE-EXPOSED-IP"
keadm join --cloudcore-ipport=192.168.20.50:10000 --token=27a37ef16159f7d3be8fae95d588b79b3adaaf92727b72659eb89758c66ffda2.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTAyMTYwNzd9.JBj8LLYWXwbbvHKffJBpPd5CyxqapRQYDIXtFZErgYE
```
But the edgecore.service must dead, So I generate the CA and CERT the edgecore becoming running.

**Comment by Rachel-Shao** [comment]
There have been many replies to this type of issue, such as #2762 #2905. You can search and try the solutions they mentioned:)
