### ISSUE TITLE
Improve the test cases of getCloudHubUrl() in controller_test.go

### ISSUE THREAD

**Issue by sujithsimon22** [kubeedge/kubeedge#330]
**What happened**:
All test cases of TestGetCloudHubUrl() mentioned in edgehub/controller_test.go appear to be testing the same case i.e. when the placement field in the configuration file is set to false. Looks like the test cases were changed due to source code change when the cloud code added.

**What you expected to happen**:
We should be testing cases in which the placement field is set to true as well, also we need to ensure that the code coverage in this particular function is improved.

**Comment by m1093782566** [comment]
Nice catch!

**Comment by sids-b** [comment]
Thanks @sujithsimon22 . Lets add more test cases to check the placement: false scenarios
