### ISSUE TITLE
Unit kubepods.slice already exists

### ISSUE THREAD

**Issue by beyondyinjl2** [kubeedge/kubeedge#3303]
kubeedge-v1.8.2  /usr/local/bin/edgecore start error:
I1117 11:37:49.465879   15393 websocket.go:93] Websocket connect to cloud access successful
I1117 11:37:49.467793   15393 process.go:317] node connection event occur: cloud_connected
I1117 11:37:49.467863   15393 process.go:282] DeviceTwin receive msg
I1117 11:37:49.467924   15393 process.go:66] Send msg to the CommModule module in twin
I1117 11:37:49.468232   15393 process.go:317] node connection event occur: cloud_connected
W1117 11:37:49.468281   15393 eventbus.go:148] Action not found
I1117 11:37:49.515302   15393 cpu_manager.go:199] "Starting CPU manager" policy="none"
I1117 11:37:49.515365   15393 cpu_manager.go:200] "Reconciling" reconcilePeriod="0s"
I1117 11:37:49.515419   15393 state_mem.go:36] "Initialized new in-memory state store"
I1117 11:37:49.515969   15393 state_mem.go:88] "Updated default CPUSet" cpuSet=""
I1117 11:37:49.516035   15393 state_mem.go:96] "Updated CPUSet assignments" assignments=map[]
I1117 11:37:49.516065   15393 policy_none.go:44] "None policy: Start"
E1117 11:37:49.522298   15393 node_container_manager_linux.go:57] "Failed to create cgroup" err="Unit kubepods.slice already exists." cgroupName=[kubepods]
E1117 11:37:49.522338   15393 edged.go:806] Failed to start container manager, err: Unit kubepods.slice already exists.
E1117 11:37:49.522362   15393 edged.go:298] initialize module error: Unit kubepods.slice already exists.

**Comment by QeelinDarly** [comment]
Has kubelet been installed on your system? Edgecore cannot run in an environment with kubelet.

**Comment by beyondyinjl2** [comment]
No kubelet installed
