### ISSUE TITLE
Supports automatic deletion of edge containers if their pods do not exist in the cloud.

### ISSUE THREAD

**Issue by todayisgood** [kubeedge/kubeedge#332]
**What would you like to be added**:

Supports automatic deletion of edge containers if their pods do not exist in the cloud.

**Why is this needed**:

When we delete pods in the cloud, if the network is disconnected, the containers on the edge will not be deleted.This will lead to inconsistencies between the cloud and the edge, even if the network is connected.That will create a series of problems, such as the inability to  update the services in the cloud before logging in  edge nodes to remove the old containers.

So I think it's necessary to support the ability to automatically delete edge containers when pod not found in the cloud.

the code in github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/controller/controller

```GO
func (uc *UpstreamController) updatePodStatus(stop chan struct{}) {
	running := true
	for running {
		select {
		case msg := <-uc.podStatusChan:
			log.LOGGER.Infof("message: %s, operation is: %s, and resource is: %s", msg.GetID(), msg.GetOperation(), msg.GetResource())

			namespace, podStatuses := uc.unmarshalPodStatusMessage(msg)
			switch msg.GetOperation() {
			case model.UpdateOperation:
				for _, podStatus := range podStatuses {
					getPod, err := uc.kubeClient.CoreV1().Pods(namespace).Get(podStatus.Name, metaV1.GetOptions{})
					if errors.IsNotFound(err) {
						log.LOGGER.Warnf("message: %s, pod not found, namespace: %s, name: %s", msg.GetID(), namespace, podStatus.Name)
						continue
					}
					if err != nil {
						log.LOGGER.Warnf("message: %s, pod is nil, namespace: %s, name: %s, error: %s", msg.GetID(), namespace, podStatus.Name, err)
						continue
					}
          
          //……
}
```

**Comment by sids-b** [comment]
@todayisgood , I think we already support deletion of Container is it not a Pod on the edge node. Please see function at line https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edged/containers/container_manager.go#L1051 
and 
https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edged/containers/container_manager.go#L1104

This is part of edged. Does this solve your concern ??

**Comment by todayisgood** [comment]
> @todayisgood , I think we already support deletion of Container if it not a Pod on the edge node. Please see function at line https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edged/containers/container_manager.go#L1051
> and
> https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edged/containers/container_manager.go#L1104
> 
> This is part of edged. Does this solve your concern ??

Can't solve because the container in the edge is running, but the pod not found in the cloud. 

The function detectContainers will update the last usage time of this container when listing running containers and it will never be deleted.

the part of edge: 
https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edged/containers/container_manager.go#L1181

the part of cloud:
https://github.com/kubeedge/kubeedge/blob/master/cloud/edgecontroller/pkg/controller/controller/upstream.go#L175

**Comment by sids-b** [comment]
@kexun @Baoqiang-Zhang , can you please have a look at this ?

**Comment by sids-b** [comment]
@todayisgood , can you please try these step ?
1) Run a container manually on your edge node.
2) Start edge_core.
I think edge_core will delete that container

**Comment by todayisgood** [comment]
> @todayisgood , can you please try these step ?
> 
> 1. Run a container manually on your edge node.
> 2. Start edge_core.
>    I think edge_core will delete that container

I'll try it later. But why? Can you show me the code?

**Comment by sids-b** [comment]
The same container gc code i referenced above. edge_core is also killing k8s core components if run on same node as they are not pods managed by edge_core. Pleaase see #278

**Comment by todayisgood** [comment]
If the container is  managed by edge_core and it's pod not found in the cloud, it will not be deleted.

**Comment by sids-b** [comment]
ohh.....I think what we need here to solve the issue is reliable message delivery from cloud to edge.
Since applications can be deployed and deleted only from the cloud, so if the application deletion message reaches the edge, there will no pod which is not found in the cloud.

**Comment by todayisgood** [comment]
Yeah.When we delete pods in the cloud, if the connection between the cloud and the edge is disconnected, the containers on the edge will not be deleted.

So I think  one way to solve this problem is  to resend the deletion message to the edge when the edgecontroller couldn't find the pod in the cloud.But now the edgecontroller doesn't do anything, except to report warning. 

Please see function at line 
[https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/controller/controller/upstream.go#L175](url)
@sids-b
