### ISSUE TITLE
no route to host

### ISSUE THREAD

**Issue by 359859461** [kubeedge/kubeedge#3321]
**What happened**:
**after execute** 
"./keadm join --cloudcore-ipport=10.1.28.172:10000 --edgenode-name=edge1 --kubeedge-version=1.8.0 --token=3a0a30db83552cf96e195027aa84a34602ee41db9913dcde09ad2235d295b49e.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTMwMTgxMDZ9.UaGcyIeTvzQ7vnJEhhZuimG_u_OXtKkitfZSctH74nU"
**i check the log** 
"journalctl -u edgecore.service -f"
**found**
Nov 19 15:19:16 host-10-19-28-172 systemd[1]: edgecore.service holdoff time over, scheduling restart.
Nov 19 15:19:16 host-10-19-28-172 systemd[1]: Stopped edgecore.service.
Nov 19 15:19:16 host-10-19-28-172 systemd[1]: Started edgecore.service.
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.157383    2704 server.go:70] Version: v1.8.0
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.169971    2704 sql.go:21] Begin to register twin db model
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.170388    2704 module.go:34] Module twin registered successfully
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.182468    2704 client.go:78] "Connecting to docker on the dockerEndpoint" endpoint="unix:///var/run/docker.sock"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.183368    2704 client.go:97] "Start docker client with request timeout" timeout="0s"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.188318    2704 docker_service.go:242] "Hairpin mode is set" hairpinMode=hairpin-veth
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.188590    2704 cni.go:239] "Unable to update cni config" err="no networks found in /etc/cni/net.d"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.202610    2704 docker_service.go:257] "Docker cri networking managed by the network plugin" networkPluginName="kubernetes.io/no-op"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.225314    2704 docker_service.go:264] "Docker Info" dockerInfo=&{ID:DLUQ:A7AT:QDFL:E3Q3:5MWM:E2IS:NK35:2TSX:V25C:NKWF:2UYT:7IXQ Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:0 Driver:overlay2 DriverStatus:[[Backing Filesystem xfs] [Supports d_type true] [Native Overlay Diff true]] SystemStatus:[] Plugins:{Volume:[local] Network:[bridge host macvlan null overlay] Authorization:[] Log:[]} MemoryLimit:true SwapLimit:true KernelMemory:true KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:false IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6tables:true Debug:false NFd:14 OomKillDisable:true NGoroutines:21 SystemTime:2021-11-19T15:19:16.204204328+08:00 LoggingDriver:journald CgroupDriver:systemd CgroupVersion: NEventsListener:0 KernelVersion:3.10.0-1160.45.1.el7.x86_64 OperatingSystem:CentOS Linux 7 (Core) OSVersion: OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:0xc000236a10 NCPU:8 MemTotal:16824741888 GenericResources:[] DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:host-10-19-28-172 Labels:[] ExperimentalBuild:false ServerVersion:1.13.1 ClusterStore: ClusterAdvertise: Runtimes:map[docker-runc:{Path:/usr/libexec/docker/docker-runc-current Args:[] Shim:<nil>} runc:{Path:docker-runc Args:[] Shim:<nil>}] DefaultRuntime:docker-runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:[] Nodes:0 Managers:0 Cluster:0xc0000e3ce0 Warnings:[]} LiveRestoreEnabled:false Isolation: InitBinary:/usr/libexec/docker/docker-init-current ContainerdCommit:{ID: Expected:aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1} RuncCommit:{ID:66aedde759f33c190954815fb765eedc1d782dd9 Expected:9df8b306d01f59d3a8029be411de015b7304dd8f} InitCommit:{ID:fec3683b971d9c3ef73f284f176672c44b448662 Expected:949e6facb77383876aeff8a6944dde66b3089574} SecurityOptions:[name=seccomp,profile=/etc/docker/seccomp.json name=selinux] ProductLicense: DefaultAddressPools:[] Warnings:[]}
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.225468    2704 docker_service.go:277] "Setting cgroupDriver" cgroupDriver="systemd"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.225645    2704 edged.go:690] RemoteRuntimeEndpoint: "unix:///var/run/dockershim.sock", remoteImageEndpoint: "unix:///var/run/dockershim.sock"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.225668    2704 edged.go:693] Starting the GRPC server for the docker CRI shim.
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.247711    2704 remote_runtime.go:62] parsed scheme: ""
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.247755    2704 remote_runtime.go:62] scheme "" not registered, fallback to default scheme
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.247826    2704 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/dockershim.sock  <nil> 0 <nil>}] <nil> <nil>}
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.247867    2704 clientconn.go:948] ClientConn switching balancer to "pick_first"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.247987    2704 remote_image.go:50] parsed scheme: ""
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.248005    2704 remote_image.go:50] scheme "" not registered, fallback to default scheme
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.248031    2704 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/dockershim.sock  <nil> 0 <nil>}] <nil> <nil>}
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.248050    2704 clientconn.go:948] ClientConn switching balancer to "pick_first"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.248646    2704 container_manager_linux.go:991] "CPUAccounting not enabled for process" pid=2704
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.248673    2704 container_manager_linux.go:994] "MemoryAccounting not enabled for process" pid=2704
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.248821    2704 container_manager_linux.go:991] "CPUAccounting not enabled for process" pid=3121
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.248845    2704 container_manager_linux.go:994] "MemoryAccounting not enabled for process" pid=3121
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.325628    2704 kuberuntime_manager.go:222] "Container runtime initialized" containerRuntime="docker" version="1.13.1" apiVersion="1.26.0"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.326010    2704 edged.go:575] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339121    2704 container_manager_linux.go:278] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339285    2704 container_manager_linux.go:283] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:systemd KubeletRootDir:/var/lib/edged ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:0s ExperimentalMemoryManagerPolicy: ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:0 EnforceCPULimits:false CPUCFSQuotaPeriod:0s ExperimentalTopologyManagerPolicy:none}
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339338    2704 topology_manager.go:120] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339370    2704 container_manager_linux.go:314] "Initializing Topology Manager" policy="none" scope="container"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339392    2704 container_manager_linux.go:319] "Creating device plugin manager" devicePluginEnabled=false
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339676    2704 module.go:34] Module edged registered successfully
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339705    2704 module.go:34] Module websocket registered successfully
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339792    2704 module.go:34] Module eventbus registered successfully
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339871    2704 metamanager.go:45] Begin to register metaManager db model
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.339981    2704 module.go:34] Module metaManager registered successfully
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: W1119 15:19:16.340003    2704 module.go:37] Module servicebus is disabled, do not register
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: W1119 15:19:16.340029    2704 module.go:37] Module edgestream is disabled, do not register
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: W1119 15:19:16.340040    2704 module.go:37] Module testManager is disabled, do not register
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: table `device` already exists, skip
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: table `device_attr` already exists, skip
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: table `device_twin` already exists, skip
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: table `sub_topics` already exists, skip
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: table `meta` already exists, skip
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: table `meta_v2` already exists, skip
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.343378    2704 core.go:24] Starting module edged
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.343446    2704 core.go:24] Starting module websocket
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.343491    2704 edged.go:294] Starting edged...
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.343498    2704 core.go:24] Starting module eventbus
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.343608    2704 core.go:24] Starting module metaManager
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.343671    2704 core.go:24] Starting module twin
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: E1119 15:19:16.343809    2704 csi_plugin.go:224] kubernetes.io/csi: CSIDriverLister not found on KubeletVolumeHost
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.343887    2704 common.go:96] start connect to mqtt server with client id: hub-client-sub-1637306356
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.343915    2704 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.344024    2704 process.go:113] Begin to sync sqlite
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.343921    2704 common.go:98] client hub-client-sub-1637306356 isconnected: false
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.345966    2704 http.go:40] tlsConfig InsecureSkipVerify true
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.345969    2704 client.go:150] finish hub-client sub
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.346143    2704 common.go:96] start connect to mqtt server with client id: hub-client-pub-1637306356
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.346166    2704 common.go:98] client hub-client-pub-1637306356 isconnected: false
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.346386    2704 client.go:91] edge-hub-cli subscribe topic to $hw/events/upload/#
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.346758    2704 client.go:91] edge-hub-cli subscribe topic to $hw/events/device/+/state/update
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.346801    2704 client.go:166] finish hub-client pub
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.346823    2704 eventbus.go:63] Init Sub And Pub Client for externel mqtt broker tcp://127.0.0.1:31183 successfully
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.347010    2704 client.go:91] edge-hub-cli subscribe topic to $hw/events/device/+/twin/+
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: I1119 15:19:16.347512    2704 client.go:91] edge-hub-cli subscribe topic to $hw/events/node/+/membership/get
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: F1119 15:19:16.347813    2704 certmanager.go:93] Error: failed to get CA certificate, err: Get "https://10.19.28.176:10002/ca.crt": dial tcp 10.19.28.176:10002: connect: no route to host
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: goroutine 129 [running]:
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: k8s.io/klog/v2.stacks(0xc000010001, 0xc00017c700, 0xbb, 0x1b9)

**What you expected to happen**:
register to cloud successful 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- [root@host-10-19-28-176 kubeedge]# ./cloudcore --version
KubeEdge v1.8.2

[root@host-10-19-28-172 home]# cd /etc/kubeedge/
[root@host-10-19-28-172 kubeedge]# ls
config  edgecore  edgecore.service  kubeedge-v1.8.0-linux-amd64  kubeedge-v1.8.0-linux-amd64.tar.gz
[root@host-10-19-28-172 kubeedge]# ./edgecore --version
KubeEdge v1.8.2

- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - [root@host-10-19-28-176 kubeedge]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel Xeon Processor (Skylake, IBRS)
Stepping:              4
CPU MHz:               2299.996
BogoMIPS:              4599.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat pku ospke spec_ctrl intel_stibp

  - OS (e.g. `cat /etc/os-release`):
  - [root@host-10-19-28-176 kubeedge]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@host-10-19-28-176 kubeedge]#

  - Kernel (e.g. `uname -a`):
  - [root@host-10-19-28-176 kubeedge]# uname -a
Linux host-10-19-28-176 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

  - Go version (e.g. `go version`):
  - [root@host-10-19-28-176 kubeedge]# go version
go version go1.17.2 linux/amd64

  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - same as cloud
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by gy95** [comment]
Nov 19 15:19:16 host-10-19-28-172 edgecore[2704]: F1119 15:19:16.347813 2704 certmanager.go:93] Error: failed to get CA certificate, err: Get "https://10.19.28.176:10002/ca.crt": dial tcp 10.19.28.176:10002: connect: no route to host

**Comment by gy95** [comment]
Are both IP and port correct? If true, please confirm the IP and port can be reached.

**Comment by 359859461** [comment]
@gy95 thanks for the remind。because of iptables 。after i clear up all the rules，edge register to cloud successfully！
