### ISSUE TITLE
Csi driver report error: "illegal base64 data at input byte 0"

### ISSUE THREAD

**Issue by lvchenggang** [kubeedge/kubeedge#3336]
Step1: Use Dockerfile exist in build/csidriver to build csidriver image used in cloud at project root directory.
![image](https://user-images.githubusercontent.com/68538306/142959573-a706ba05-e55f-4668-92c8-4290e6157d1e.png)
......
![image](https://user-images.githubusercontent.com/68538306/142959587-3c84cce0-db3f-4679-a6aa-05d0552ee4c0.png)

Step2: Use YAML build/csisamples/hostpath/deploy/csicontroller.yaml to create sts in cloud. Meanwhile replace the csi-driver container's image to above new build image: kubeedge/csidriver:v1.1.1.
![image](https://user-images.githubusercontent.com/68538306/142959852-2eeb60aa-a0ec-49f0-8312-2077dead7c7f.png)

Step3: Create Storageclass and PVC:
![image](https://user-images.githubusercontent.com/68538306/142959937-e80a27b8-2609-437a-a394-b6e99d2f9950.png)
![image](https://user-images.githubusercontent.com/68538306/142959956-1ac11da0-9907-4cb6-9bed-5b3956a64e1a.png)
![image](https://user-images.githubusercontent.com/68538306/142959977-392d4d1b-e20f-4f45-b49f-32aa2c086133.png)

Step4: Watch the log of csicontroller's csi-driver container, found error log:
![image](https://user-images.githubusercontent.com/68538306/142960065-bb2309d2-db6b-4d52-8d8f-13edbf45191d.png)

Phenomenon analysis:
It seems that the uds communication between csidriver and cloudhub's udsserver not encrypted by base64 algorithm.

Impact Analysis:
The error will affect the response chan about csidriver->provisioner->k8s apiserver.

**Comment by lvchenggang** [comment]
It seems that the uds communication between csidriver and cloudhub's udsserver not encrypted by base64 algorithm

**Comment by moolen** [comment]
Hey @lvchenggang, i found a couple of more issues with the CSI integration:
1. cloudhub/channelq drops messages towards edgecore that do not contain a resourceVersion [see here](https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/cloudhub/channelq/channelq.go#L91)
2. edged: the `content` passed to `handleVolume()` is a json-escaped string that has to be unmarshaled twice [see here](https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edged/edged.go#L1177) 
3. the csidriver docker image was last built for `kubeedge v1.3` ~2 years ago, it would be great to push a image for every release
4. there's a lot of duplication in `csidriver/controllerserver.go` that should be refactored to streamline the encode/decode process 

I got fixes and tests for 1, 2 and 4. And i did manual tests to ensure the csi integration works as documented in the [csi proposal](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/csi.md).

I would like to open separate PRs for those on top of #3343, would that work for you?

**Comment by lvchenggang** [comment]
> 



> Hey @lvchenggang, i found a couple of more issues with the CSI integration:
> 
> 1. cloudhub/channelq drops volume related messages because they do not contain a resourceVersion [see here](https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/cloudhub/channelq/channelq.go#L91)
> 2. edged: the `content` passed to `handleVolume()` is a json-escaped string that has to be unmarshaled twice [see here](https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edged/edged.go#L1177)
> 3. the csidriver docker image was last built for `kubeedge v1.3` ~2 years ago, it would be great to push a image for every release
> 4. there's a lot of duplication in `csidriver/controllerserver.go` that should be refactored to streamline the encode/decode process
> 
> I got fixes and tests for 1, 2 and 4. And i did manual tests to ensure the csi integration works as documented in the [csi proposal](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/csi.md).
> 
> I would like to open separate PRs for those on top of #3343, would that work for you?

Aggree. I also found some other problems:
5. edge side fixed csi driver as csi-hostpath in code, which can not use other csi plugin. This problem fixed in #3326 
6. csi driver handle response message error, that is current issue's content, this fixed in #3343 
7. edged module lack necessary code which csi storage need.
8. currently the edge node is write in csinode.yaml, this leads to cloud could only interact with one edge node, but cannot manage multiple edge node.

I will integrate 7 and 8 into new PR.

**Comment by moolen** [comment]
Just for the record: I've been working on the csi-driver ([my branch](https://github.com/moolen/kubeedge/tree/exp/topo-impl)) to support multiple edge nodes by making it topology-aware in combination with `volumeBindingMode=WaitForFirstConsumer`. What's missing is to autocreate a `Kind=CSINode` for every edge node. I'll upstream it bit by bit once legal stuff is out of the way.
@lvchenggang I think that's issue 8 from above.

**Comment by shumintao** [comment]
Recently I use csidriver , I meet same problems. I see your branch,but don’t work
