### ISSUE TITLE
keadm get nodes -A print namespace while node resource whithout namespace actually

### ISSUE THREAD

**Issue by jidalong** [kubeedge/kubeedge#3345]
**What happened**:
When I excute “keadm get nodes/node -A/--all-namespaces ”，keadm may print the namespace with null while in original k8s， the resource of node does not have any namespaces.
![image](https://user-images.githubusercontent.com/53475708/142982281-cb7d5107-1a54-4313-ae4d-6d81e231feee.png)
The following is **kubectl** get nodes -A in original k8s cluster:
![image](https://user-images.githubusercontent.com/53475708/142982331-76e16f16-fce1-47b7-b94a-4989c62981c0.png)

**What you expected to happen**:
“keadm get nodes/node -A/--all-namespaces ” may print without namespaces

**Comment by gy95** [comment]
after PR #3346 , what does  command `keadm get nodes/node -A/--all-namespaces ` print

**Comment by jidalong** [comment]
> after PR #3346 , what does command `keadm get nodes/node -A/--all-namespaces ` print look like? 😄

@gy95 after PR #3346 , command keadm get nodes/node -A/--all-namespaces print like the following which is consistent with original k8s print:
![image](https://user-images.githubusercontent.com/53475708/142986820-5a18f181-204b-40b1-9135-eadac106a25e.png)

**Comment by gy95** [comment]
oh, yes, not print NAMESPACE column anymore 👍
