### ISSUE TITLE
keadm init fail :　per-version schemas may not all be set to identical values

### ISSUE THREAD

**Issue by yenhsunli** [kubeedge/kubeedge#3365]
**What happened**:
franklee@franklee-noteBook:~/keadm-v1.8.0-linux-amd64/keadm$ sudo ./keadm init --kubeedge-version=1.8.0  --kube-config=/home/franklee/.kube/config
Kubernetes version verification passed, KubeEdge installation will start...
Error: CustomResourceDefinition.apiextensions.k8s.io "devices.devices.kubeedge.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha2", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc00843f008), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.5.0  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver

Flags:
      --advertise-address string   Use this key to set IPs in cloudcore's certificate SubAltNames field. eg: 10.10.102.78,10.10.102.79
      --domainname string          Use this key to set domain names in cloudcore's certificate SubAltNames field. eg: www.cloudcore.cn,www.kubeedge.cn
  -h, --help                       help for init
      --kube-config string         Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string    Use this key to download and use the required KubeEdge version
      --master string              Use this key to set K8s master address, eg: http://127.0.0.1:8080
      --tarballpath string         Use this key to set the temp directory path for KubeEdge tarball, if not exist, download it

F1125 00:17:12.274762   23736 keadm.go:27] CustomResourceDefinition.apiextensions.k8s.io "devices.devices.kubeedge.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha2", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc00843f008), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc0008f82c0, 0x263, 0x2b7)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x3d78bc0, 0xc000000003, 0x0, 0x0, 0xc0004f81c0, 0x3a3b201, 0x8, 0x1b, 0xe4e400)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:970 +0x19b
k8s.io/klog/v2.(*loggingT).printDepth(0x3d78bc0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0008ec250, 0x1, 0x1)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:733 +0x16f
k8s.io/klog/v2.(*loggingT).print(...)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:715
k8s.io/klog/v2.Fatal(...)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1489
main.main()
	/root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0xdf

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x3d78bc0)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:418 +0xdf

goroutine 52 [IO wait]:
internal/poll.runtime_pollWait(0x7f6035a988f8, 0x72, 0x2cdc3a0)
	/root/.gvm/gos/go1.15/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc000561b18, 0x72, 0xc000776400, 0x8c1, 0x8c1)
	/root/.gvm/gos/go1.15/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/root/.gvm/gos/go1.15/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000561b00, 0xc000776400, 0x8c1, 0x8c1, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.15/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc000561b00, 0xc000776400, 0x8c1, 0x8c1, 0x203000, 0x11d2f1b, 0xc0007732e0)
	/root/.gvm/gos/go1.15/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0003c8738, 0xc000776400, 0x8c1, 0x8c1, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.15/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0007f48c0, 0xc000776400, 0x8c1, 0x8c1, 0x558, 0x8bc, 0xc0001b7710)
	/root/.gvm/gos/go1.15/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc000773400, 0x2cd8420, 0xc0007f48c0, 0xe4b825, 0x28241c0, 0x2a02660)
	/root/.gvm/gos/go1.15/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000773180, 0x2cda100, 0xc0003c8738, 0x5, 0xc0003c8738, 0x547)
	/root/.gvm/gos/go1.15/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000773180, 0x0, 0x0, 0xc0001b7d18)
	/root/.gvm/gos/go1.15/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
	/root/.gvm/gos/go1.15/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc000773180, 0xc0001c6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.15/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc00071b560, 0xc0008d6118, 0x9, 0x9, 0xc0001b7d18, 0x2b6d700, 0x139714b)
	/root/.gvm/gos/go1.15/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x2cd8280, 0xc00071b560, 0xc0008d6118, 0x9, 0x9, 0x9, 0xc00007a040, 0x0, 0x2cd85e0)
	/root/.gvm/gos/go1.15/src/io/io.go:314 +0x87
io.ReadFull(...)
	/root/.gvm/gos/go1.15/src/io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc0008d6118, 0x9, 0x9, 0x2cd8280, 0xc00071b560, 0x0, 0x0, 0xc0001b7dd0, 0xea89a5)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0008d60e0, 0xc000747680, 0x0, 0x0, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0001b7fa8, 0x0, 0x0)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc00018b080)
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/root/codes/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5

**What you expected to happen**:
keadm init success.

**How to reproduce it (as minimally and precisely as possible)**:
wget https://github.com/kubeedge/kubeedge/releases/download/v1.8.0/keadm-v1.8.0-linux-arm.tar.gz
tar xzvf keadm-v1.8.0-linux-amd64.tar.gz
cd /keadm-v1.8.0-linux-amd64/keadm
sudo ./keadm init --advertise-address=192.168.0.3 --kube-config=/home/frank/.kube/config

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- -Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:58:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):　Ubuntu 18.04.6 LTS
  - Kernel (e.g. `uname -a`):  x86_64 GNU/Linux
  - Go version (e.g. `go version`):　go1.16.6 linux/amd64
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by QeelinDarly** [comment]
Maybe you can update your golang version to 1.17

**Comment by windghoul** [comment]
i have the same problem
