### ISSUE TITLE
Add community charter

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#337]
**What would you like to be added**:

Per weekly meeting, we need to add community charter.

**Why is this needed**:

**Comment by skdwriting** [comment]
Some of the docs we need to add:
1. Overall charter of the project and its vision (could be on readme? or a kubeedge_chater.md(better?))
2. Roadmap - kubeedge_roadmap.md -- This will be updated as and when needed. (This can also have future view of future 2 releases. (Next - more clear, NextNext-start adding fluid ideas)
3. Community Meeting - KubeEdgeCommunityBiWeeklyMeeting.md -- agenda and MoM
4. Community Operation - KubeEdgeCommunityOperation.md - we detail how the community operation happens. where to look for certain info etc.
5. KubeEdgeJoining.md
6. KubeEdgeContributionGuide.md
7. KubeEdgeStylingGuide.md
Our Readme.md can have the links to all the above documents and it will be easy for any developer or user of KubeEdge

If you are ok, I can start putting the initial docs....

**Comment by m1093782566** [comment]
I just initialized the charter, please check: #336 and give your comments there.

For other items, I think you need to check with team one by one as some has been done.

**Comment by sids-b** [comment]
@kevin-wangzefeng @fisherxu @rohitsardesai83 @chendave @edisonxiang  @kadisi @subpathdev 

What are your thoughts on this one ? Do we create a project charter or form small SIG and they charter.

**Comment by daixiang0** [comment]
ping @kevin-wangzefeng @fisherxu
