### ISSUE TITLE
build: Running `make` builds only edge_core.

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#338]
**What happened**:
When I run "make" from the root folder i.e kubedge/kubedge , it only  compiles edge_core.

**What you expected to happen**:
When I run make, it should first build cloud , followed by edge code.

**How to reproduce it (as minimally and precisely as possible)**:
```sh
$cd src/github.com/kubeedge/kubeedge
$make
cd edge && make
make[1]: Entering directory '/home/root1/go/src/github.com/kubeedge/kubeedge/edge'
go build cmd/edge_core.go
make[1]: Leaving directory '/home/root1/go/src/github.com/kubeedge/kubeedge/edge'
```

**Anything else we need to know?**:
NA

**Environment**: Ubuntu 16.04 LTS
- KubeEdge version: HEAD

**Comment by rohitsardesai83** [comment]
@srivatsav123 , can you please take a look at this ?

**Comment by srivatsav123** [comment]
ok

**Comment by srivatsav123** [comment]
@rohitsardesai83 -Pr is merged .I will close this issue...
