### ISSUE TITLE
Support Windows Container 

### ISSUE THREAD

**Issue by CindyXing** [kubeedge/kubeedge#339]
**What would you like to be added**:
Here is to ask KubeEdge support running windows container(s) on a windows edge node. 

**Why is this needed**:
There is good market need for windows platform. With azuresphere, customers can also benefit from secure windows device + os.

**Comment by chenqiangzhishen** [comment]
We have the same and strong requirement for running kubeedge on windows, would reopen it and any plan for it? thx.
