### ISSUE TITLE
边缘节点跨网络join问题解决

### ISSUE THREAD

**Issue by zhaosonghai** [kubeedge/kubeedge#3402]
cloud端:192.168.173.77（资源池1）
edge:198.132.7.13（资源池2）
中转网：173.16.253.196 （资源池1）【业务网】  [承载网为166.7.18.152]
cloud端和edge网络无法直通，需要使用中转网(173.16.253.196)中转，即192.168.177.77（业务网）----->173.16.253.196（业务网）--->198.132.7.13(业务网),但是 173.16.253.196连接 198.132.7.13 是通过承载网173.16.253.196的承载网(166.7.18.152)进行连接，现在192.168.173.77和173.16.253.196  网络是全通，173.16.253.196 [承载网为166.7.18.152] 与198.132.7.13开通了10000到10500，20000到20500端口范围的策略，但是edge在join cloud 时，INTERNAL-IP 显示有问题，在edge.yaml里配置nodeIP为173.16.253.196时，192.168.173.77会直接连接 173.16.253.196:10351,网络不通，但是nodeIP通过配置域名edeg-node(173.16.253.196)时，在INTERNAL-IP 显示为 <nil> ，连接端口探测也是Error from server: Get https://<nil>:10351/containerLogs/kube-system/kube-proxy-lp8hg/kube-proxy?follow=true: dial tcp: lookup <nil>: no such host，请帮忙看看怎么配置

**Comment by khalid-jobs** [comment]
如果可以提供一个直观点的网路拓扑图，会容易理解一些。另外你的INTERNAL-IP 是指什么? edge 在join的时候，具体报错信息可以贴全一些。
