### ISSUE TITLE
UT is missing in cloud part

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#341]
**What would you like to be added**:

Add UTs for cloud part and run them in the CI.

**Why is this needed**:

UT is very basic tests.

**Comment by m1093782566** [comment]
cc @lidiyag @pavan187 @naveensriram

**Comment by m1093782566** [comment]
Also what can we do for integration tests?

**Comment by pavan187** [comment]
@m1093782566 , Integration is not required for this, as the cloud part test already covering in E2E framework tests. we do not need have cloud part seperately.

To do only cloud part integration test we need to mock K8s API-Server, which is difficult to handle as we need to study entire k8s API-server code. so we decided to handle the cloud part tests along with E2E tests.
cc @sids-b @rohitsardesai83

**Comment by woshiyezitang** [comment]
膜拜大佬

**Comment by rohitsardesai83** [comment]
we need to see how kubernetes handles such tests and try to attempt and write whatever we can .
