### ISSUE TITLE
It took over a minute for a pod to terminate /pod sutcked at Terminating status and cannot be deleted automatically

### ISSUE THREAD

**Issue by davedavedavid** [kubeedge/kubeedge#3410]
**What happened**:
![image](https://user-images.githubusercontent.com/87642892/143975516-95a2dd6c-79f3-4f8c-b616-2794ab9e655f.png)
yolo-v5-train-t9w2r is running on edgenode, it took over a minute to terminate since job is deleted.
Sometime it just stucks at Terminating status and cannot be deleted automatically, like yolo-v5-train-hnts4
**What you expected to happen**:
pod can be deleted properly
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.21.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.8.2
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):1.8.2
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):euler
  - Kernel (e.g. `uname -a`):Linux a500-124 4.19.36-vhulk1907.1.0.h1017.eulerosv2r8.aarch64 #1 SMP Sat Mar 27 10:04:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by QeelinDarly** [comment]
You can try to use `kubectl delete yolo-v5-train-t9w2r --force --grace-period=0` to delete your pod.

**Comment by davedavedavid** [comment]
> You can try to use `kubectl delete yolo-v5-train-t9w2r --force --grace-period=0` to delete your pod.

delete manually is functional , but is there any problem with kubeedge cloud-edge communication and status synchronization

**Comment by QeelinDarly** [comment]
> > You can try to use `kubectl delete yolo-v5-train-t9w2r --force --grace-period=0` to delete your pod.
> 
> delete manually is functional , but is there any problem with kubeedge cloud-edge communication and status synchronization

Can you say more about _How to reproduce it_?

**Comment by davedavedavid** [comment]
> Can you say more about _How to reproduce it_?
i just create job to create the pod,  runing my bunisess , then delete the job, nothing special.
the problem occurs occasionally.
