### ISSUE TITLE
Refactor out deprecated io/ioutil 

### ISSUE THREAD

**Issue by mjlshen** [kubeedge/kubeedge#3411]
**What happened**:
In Go 1.16, all of `io/ioutil`'s functionality has been moved to other packages https://go.dev/doc/go1.16#ioutil, https://github.com/kubeedge/kubeedge/pull/3409#discussion_r758871055

We should refactor out the rest of them:
```bash
grep -r '"io/ioutil"' . | grep -v vendor | cut -f 1 -d ':' | cut -d '/' -f 1-3 | sort | uniq -c | sort
```
```
   1 ./edgesite/cmd
   1 ./pkg/stream
   1 ./pkg/util
   1 ./tests/performance
   2 ./tests/stubs
   3 ./keadm/cmd
   3 ./staging/src
   4 ./edge/test
   5 ./pkg/apis
   5 ./tests/e2e
  10 ./edge/pkg
  16 ./cloud/pkg
```

**Comment by mjlshen** [comment]
I'll work on getting a PR ready

**Comment by gy95** [comment]
there's already a PR https://github.com/kubeedge/kubeedge/pull/3222

**Comment by gy95** [comment]
hold for waiting request for golang 1.16
:)

**Comment by mjlshen** [comment]
Ah, go.mod is already on Go 1.16, so I assumed it was already ready. Good thing you already got the PR ready!

**Comment by fisherxu** [comment]
The pr has merged, so close this now :)
/close
