### ISSUE TITLE
servicebus test

### ISSUE THREAD

**Issue by RocMe** [kubeedge/kubeedge#343]
**What would you like to be added**:
I want a guide to do servicebus test,thank you.
**Why is this needed**:
 I want to communicate with application running on edge via HTTP. Thank you.

**Comment by rohitsardesai83** [comment]
servicebus development is under progress .

**Comment by RocMe** [comment]
> servicebus development is under progress .
OK. Thank you.

**Comment by sids-b** [comment]
@RocMe please have a look at the Router design. Once the feature is in place, you can use servicebus https://github.com/kubeedge/kubeedge/pull/314

**Comment by RocMe** [comment]
> @RocMe please have a look at the Router design. Once the feature is in place, you can use servicebus #314

great. Thank you.
