### ISSUE TITLE
KubeEdge CRI containerd error

### ISSUE THREAD

**Issue by MoXinQian** [kubeedge/kubeedge#3440]
According to officail documention：[here](https://kubeedge.io/en/docs/advanced/cri/#containerd)
but when i started edgecore，it's error as flollow:
> dgecore.service
   Loaded: loaded (/etc/systemd/system/edgecore.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-12-07 17:28:11 CST; 7s ago
  Process: 27756 ExecStart=/usr/local/bin/edgecore (code=exited, status=1/FAILURE)
 Main PID: 27756 (code=exited, status=1/FAILURE)

when i used `journalctl  -u edgecore.service  -f`,it's error info as follow:
>  12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.613494    8011 server.go:70] Version: v1.8.2
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.619430    8011 sql.go:21] Begin to register twin db model
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.619728    8011 module.go:34] Module twin registered successfully
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.627110    8011 remote_runtime.go:62] parsed scheme: ""
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.627411    8011 remote_runtime.go:62] scheme "" not registered, fallback to default scheme
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.628153    8011 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.628270    8011 clientconn.go:948] ClientConn switching balancer to "pick_first"
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.628435    8011 remote_image.go:50] parsed scheme: ""
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.628543    8011 remote_image.go:50] scheme "" not registered, fallback to default scheme
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.628739    8011 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
12月 08 10:04:29 node02 edgecore[8011]: I1208 10:04:29.628863    8011 clientconn.go:948] ClientConn switching balancer to "pick_first"
12月 08 10:04:29 node02 edgecore[8011]: E1208 10:04:29.665635    8011 remote_runtime.go:86] "Version from runtime service failed" err="rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
12月 08 10:04:29 node02 edgecore[8011]: E1208 10:04:29.665661    8011 kuberuntime_manager.go:208] "Get runtime version failed" err="get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
12月 08 10:04:29 node02 edgecore[8011]: E1208 10:04:29.665667    8011 edged.go:269] init new edged error, New generic runtime manager failed, err: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService

who can help me，i'm very anxious?thanks

**Comment by gy95** [comment]
look at logs: /var/log/kubeedge/edgecore.log

**Comment by MoXinQian** [comment]
> look at logs: /var/log/kubeedge/edgecore.log

when i open the `/var/log/kubeedge/`，but it's error as follow:
> root@node02:/etc/kubeedge/config# cd /var/log/kubeedge/
-bash: cd: /var/log/kubeedge/: No such file or directory

**Comment by MoXinQian** [comment]
> look at logs: /var/log/kubeedge/edgecore.log

I have updated the comment,can you help me to see again?

**Comment by gy95** [comment]
not quite sure, which container runtime do you use? and what's the version.

**Comment by MoXinQian** [comment]
> not quite sure, which container runtime do you use? and what's the version.

thanks for you!
I have resovled this problem by using another machine that only installed containerd。
