### ISSUE TITLE
keadm 1.9.0 failed to init with `--kubeedge-version=1.9.0`

### ISSUE THREAD

**Issue by llhuii** [kubeedge/kubeedge#3448]
**What happened**:

``` 
root@sedna-mini-control-plane:~# keadm init --kubeedge-version=1.9.0 --advertise-address=172.18.0.3
Kubernetes version verification passed, KubeEdge installation will start...
W1208 07:19:27.984998   19817 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, u
navailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition                       
Error: CustomResourceDefinition.apiextensions.k8s.io "devices.devices.kubeedge.io" is invalid: spec.versions: Invalid value: [
]apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha2", Served:true, Sto
rage:true, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(0xc00f008cc0)
, Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)   
Usage:                                                                                                                        
  keadm init [flags]    
```
**What you expected to happen**:
keadm init normally

**How to reproduce it (as minimally and precisely as possible)**:
just run `keadm init --kubeedge-version=1.9.0`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by gy95** [comment]
what's k8s version? :)

**Comment by llhuii** [comment]
The bug is here:
https://github.com/kubeedge/kubeedge/blob/4ff2d99da342e3623141665696f23ca85e12d675/keadm/cmd/keadm/app/cmd/util/k8sinstaller.go#L149-L153

`build/crds/devices/devices_v1alpha2_device.yaml` in [release 1.9](https://github.com/kubeedge/kubeedge/blob/release-1.9/build/crds/devices/devices_v1alpha2_device.yaml) is `apiextensions.k8s.io/v1`, in [release 1.8](https://github.com/kubeedge/kubeedge/blob/release-1.8/build/crds/devices/devices_v1alpha2_device.yaml) is `apiextensions.k8s.io/v1beta1`

**Comment by llhuii** [comment]
Other crds(`reliablesyncs/cluster_objectsync_v1alpha1.yaml`, `reliablesyncs/objectsync_v1alpha1.yaml`) are `apiextensions.k8s.io/v1`.
So we just remove the `else` branch? https://github.com/kubeedge/kubeedge/blob/4ff2d99da342e3623141665696f23ca85e12d675/keadm/cmd/keadm/app/cmd/util/k8sinstaller.go#L149-L153

**Comment by fisherxu** [comment]
#3444 is trying to fix this bug.

**Comment by llhuii** [comment]
OK

**Comment by gy95** [comment]
> OK

can you try applying for the patch https://github.com/kubeedge/kubeedge/pull/3444
build keadm from source codes and use it to check whether it fix the problem

**Comment by llhuii** [comment]
keadm need to be able to install lower version kubeedge, e.g. 1.8.0

> > OK
> 
> can you try applying for the patch #3444 build keadm from source codes and use it to check whether it fix the problem

**Comment by fisherxu** [comment]
Will release the v1.9.1 to fix this bug :)

**Comment by llhuii** [comment]
#3444 has been merged
/close
