### ISSUE TITLE
Remove the remote request for the default version in `keadm`.

### ISSUE THREAD

**Issue by zc2638** [kubeedge/kubeedge#3454]
**What would you like to be added/modified**:

Remove the remote request for the default version in `keadm`.

**Why is this needed**:

We don’t need to pass an extra place to ensure the default version.
We can completely rely on the constant `DefaultKubeEdgeVersion` in package `keadm/cmd/keadm/app/cmd/common/constant.go`
In any case, what is used in CICD should be the associated version of the current commit, not the final version.

```golang
if kubeVer == "" {
	var latestVersion string
	for i := 0; i < util.RetryTimes; i++ {
		version, err := util.GetLatestVersion()
		if err != nil {
			fmt.Println("Failed to get the latest KubeEdge release version, error: ", err)
			continue
		}
		if len(version) > 0 {
			kubeVer = strings.TrimPrefix(version, "v")
			latestVersion = version
			break
		}
	}
	if len(latestVersion) == 0 {
		kubeVer = types.DefaultKubeEdgeVersion
		fmt.Println("Failed to get the latest KubeEdge release version, will use default version: ", kubeVer)
	}
}
```

**Comment by fisherxu** [comment]
If we want to publish a new release, we need to modify the code of DefaultKubeEdgeVersion first, but now we still haven't the related release, so the latest release can't be tested? We can have to look how k8s/kubeadm deal with this issue.

**Comment by zc2638** [comment]
submit the hash according to the current code to build the version, and confirm according to the tag when releasing.
1. build the main components according to the code (e.g. cloudcore, edgecore)
2. build a tar archive
3. start an API server to download local static (tar.gz) files
4. build keadm and test.
5. ...

We should use the currently submitted code to carry out the correct test.
WDYT? @fisherxu

**Comment by zc2638** [comment]
Just like `kubeadm` can customize the image registry, should `keadm` specify a custom download address?

**Comment by gy95** [comment]
seems that should support `make release` cmd?

**Comment by zc2638** [comment]
Yes, maybe we need a command to build release to test.
@gy95

**Comment by zc2638** [comment]
will refactor keadm in #3475.
/close
