### ISSUE TITLE
status of pod is still pending when node online again

### ISSUE THREAD

**Issue by SmileCaoJ** [kubeedge/kubeedge#3465]
**What happened**:
1.  stop edgecore on node
2. create a pod   (status of node is still Ready)
3. status of pod is pending
4. setup edgecore on node, status of node is ready
5. status of pod is still pending

**What you expected to happen**:
1. status of pod is running

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):   v1.17
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):   cloudcore  1.8.1   edgecore  1.9.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):  amd64
  - OS (e.g. `cat /etc/os-release`):    ubuntu 18.04
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by stingshen** [comment]
This may be related. https://github.com/kubeedge/kubeedge/issues/3108#issuecomment-969943066

In conclusion, the issue should be resolved on v1.9.0.
