### ISSUE TITLE
Maintain proposal/design in Issues

### ISSUE THREAD

**Issue by yongwww** [kubeedge/kubeedge#347]
**What would you like to be added**:
Suggest to maintain proposal in Issues, or in a separate repo like kubeedge/rfc

**Why is this needed**:
No need to introduce unnecessary commits and docs in kubeedge code base, since proposal needs more discussion usually, there is no final version of this kind of stuff even the code get merged. 

For example, some successful projects like Pytorch/MXNet/TVM, design/proposal/rfc are maintained in Issues, guys from community could join the discussion.  In Tensorflow, proposal/design/rfc was maintained in a separate repo tensorflow/community.

**Comment by yongwww** [comment]
cc @CindyXing @m1093782566 @sids-b

**Comment by CindyXing** [comment]
Sounds good to me. Yes, we should separate code and doc checkins. It can save merging efforts too.

**Comment by sids-b** [comment]
Thanks @yongwww , we have a similar issue here #288 . We will move the docs soon :)
