### ISSUE TITLE
About edgenode log collection issues

### ISSUE THREAD

**Issue by lgy1027** [kubeedge/kubeedge#3477]
Currently we use loki as the log collection component, but after deploying kubeedge, the container logs deployed by the edge node cannot be collected normally. May I ask, do you have any thoughts on the collection of container logs by kubeedge?

**Comment by lgy1027** [comment]
What if a k8S resource needs to be called inside a container deployed on an edge node

**Comment by gy95** [comment]
you mean using `kubectl logs` command to get pod logs on the edge node?
you can ref: https://kubeedge.io/en/docs/advanced/debug/

**Comment by lgy1027** [comment]
> 
What I mean is to collect the logs of edge nodes, just like ELK is deployed in a cluster, and you can pull the logs of each node.

**Comment by zhu733756** [comment]
You may need a log agent deployed in edge nodes, like fluent-bit daemon agents,  grafana/agent or promtail, opentelemetry-collector? You can have a try.

**Comment by lgy1027** [comment]
> 

Yes, what I use now is to deploy pormtail, but promtail will call k8s API to get data and do some log label processing, which is not available at edge nodes

**Comment by zhu733756** [comment]
> > 
> 
> Yes, what I use now is to deploy pormtail, but promtail will call k8s API to get data and do some log label processing, which is not available at edge nodes

Promtail will collect logs on edge nodes and always send them to Loki. If you want to call k8s API, and the logs are so larger, you may need to build your own client by using kubeconfig.   Actually, I don't know your scene, you can collects docker logs from edges and forwards them to the center logging component. See https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460

**Comment by lgy1027** [comment]
> > > 
> > 
> > 
> > Yes, what I use now is to deploy pormtail, but promtail will call k8s API to get data and do some log label processing, which is not available at edge nodes
> 
> Promtail will collect logs on edge nodes and always send them to Loki. If you want to call k8s API, and the logs are so larger, you may need to build your own client by using kubeconfig. Actually, I don't know your scene, you can collects docker logs from edges and forwards them to the center logging component. See https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460

We now use loki+promtail as the log collector. Promtail is deployed on all nodes, but after promtail is deployed on edge nodes, label information cannot be processed, because this involves obtaining node information from the cluster and pod information deployed in the current node

**Comment by zc2638** [comment]
You can try to connect to metaServer on the edge side, which is the apiServer that exposes k8s resources on the edge side. I don’t know if it can meet the demand.
@lgy1027

**Comment by lgy1027** [comment]
> 

The address of the edge link is 127.0.0.1:13350 to get the metadata, but I deployed it to the edge node container through k8s. This does not seem to work. In fact, in some scenarios, the container application deployed to the edge node needs to call apiserver to get the cluster. Related information, but is there a better way

**Comment by zc2638** [comment]
> > 
> 
> The address of the edge link is 127.0.0.1:13350 to get the metadata, but I deployed it to the edge node container through k8s. This does not seem to work. In fact, in some scenarios, the container application deployed to the edge node needs to call apiserver to get the cluster. Related information, but is there a better way

Consider `hostNetwork` ?

**Comment by lgy1027** [comment]
> 



> > > 
> > 
> > 
> > The address of the edge link is 127.0.0.1:13350 to get the metadata, but I deployed it to the edge node container through k8s. This does not seem to work. In fact, in some scenarios, the container application deployed to the edge node needs to call apiserver to get the cluster. Related information, but is there a better way
> 
> Consider `hostNetwork` ?

I was wrong. I can get the data by accessing curl -s http://127.0.0.1:10550/api/v1/pods on the edge node. If my edge node is deployed using keadm, can I set up hostnetwork? Are there any encapsulated APIs that can be used by container applications deployed on edge nodes?

**Comment by zhu733756** [comment]
As far as I know, you may need a monitoring agent deployed on edges like [here](https://github.com/kubeedge/edgemesh/blob/main/docs/proposal/observability-support-proposal.md).  The agent would scape the edge metrics and send them to the central cloud.  BTW, grafana/agent can do this also. Then, you can query it through promtheus query API for everywhere. Do you mean this solution?
