### ISSUE TITLE
Avoid/remove all unnecessary commits like "Merge pull request #*** from ***"

### ISSUE THREAD

**Issue by yongwww** [kubeedge/kubeedge#348]
**What would you like to be added**:
I saw a lot of unnecessary commits in code base like "Merge pull request #346 from brant4test/patch-1", make no sense to maintain this kind of commits. 

**Why is this needed**:
Obviously, need to keep code base/commit log clean and meaningful

**Comment by yongwww** [comment]
cc @CindyXing @m1093782566 @sids-b

**Comment by yongwww** [comment]
And need to squash all commits in a pr to merge into code base ("Squash and Merge"). For example in this pr #181, a bunch of unnecessary commits were introduced into code base.

**Comment by m1093782566** [comment]
Agree!

**Comment by m1093782566** [comment]
We will ask contributors to squash commits before merging PRs.

Also cc @qizha @rohitsardesai83.

**Comment by sids-b** [comment]
Thanks @yongwww . We will be careful now onwards :)

**Comment by yongwww** [comment]
Thank you guys! @m1093782566 @sids-b will close the issue soon, leave it open for a while in case other guys has different thoughts
