### ISSUE TITLE
How to deploy binary programs from the cloud to the edge？

### ISSUE THREAD

**Issue by lirui79** [kubeedge/kubeedge#3484]
If the edge cannot support the operation of docker containers, can you deploy binary programs from the cloud to the edge and control their startup, operation, and exit, and upgrades?

**Environment**:
- Kubernetes version (v1.23.0):
- KubeEdge version(e.g. `cloudcore --v1.9.0` and `edgecore --v1.9.0`):

**Comment by zhu733756** [comment]
Let's join #3475 to talk about it.

**Comment by lirui79** [comment]
very sorry! I am not asking about KubeEdge system component deployment. What I want to know is that I have an application that needs to be deployed on the edge, but the edge cannot run docker containers. Can I deploy this application binary program to the edge through the cloud? Can the KubeEdge system be used to control the start, run, stop and update of applications on the edge?

**Comment by zhu733756** [comment]
> very sorry! I am not asking about KubeEdge system component deployment. What I want to know is that I have an application that needs to be deployed on the edge, but the edge cannot run docker containers. Can I deploy this application binary program to the edge through the cloud? Can the KubeEdge system be used to control the start, run, stop and update of applications on the edge?

Does the kubelet support it? you could think edgecore as a simple kubelet but not all.

**Comment by fisherxu** [comment]
KubeEdge now only support containerization application @lirui79 What's your usage scenario, embedded device management?

**Comment by lirui79** [comment]
Our application scenario is relatively simple. The edge node may be a set-top box, and its resources are very limited. I am afraid that it cannot run docker containers.
