### ISSUE TITLE
Will the edge update the docker image file be sent from the cloud to the edge or the edge downloads it from the docker image library website?

### ISSUE THREAD

**Issue by lirui79** [kubeedge/kubeedge#3485]
**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by zc2638** [comment]
The edge directly pulls the image from the image registry
