### ISSUE TITLE
cloud container be scheduled to the edge node

### ISSUE THREAD

**Issue by yz271544** [kubeedge/kubeedge#3489]
**What happened**:
this is my cluster info, it work on kubeedge in v1.8.2 version.
![1 normal-first](https://user-images.githubusercontent.com/16499075/146874982-16a92c14-fde3-4e6e-9fa0-49d9d8b683d4.png)

#### Testing process #3293 
1. prepare
`systemctl stop edgecore` on all of the edgenode.
and clean all of the config on the edgenode
```shell
rm -f ca/*
rm -f certs/*
rm -fr edgemesh/
rm -f /var/lib/kubeedge/edgecore.db
```
and remove the `reliablesyncs.kubeedge.io` and it's children node from etcd
![1 1 remove-reliablesyncs-kubeedge-io](https://user-images.githubusercontent.com/16499075/146876237-196eab8a-e59b-4fbf-84b4-c0065301d6fe.png)

and clean cloudimage on cloud node
`docker rmi kubeedge/cloudcore:v1.8.2`

2. modify these two files according to 3293
modify the `cloud/pkg/dynamiccontroller/application/listener.go` and `pkg/metaserver/util/util.go` 
In order to find the problem easier, I modified the `edged.go` file and added the print content:
```go
// klog.Infof("result content is %s", result.Content)
klog.Infof("result content is %s, resource: %s, group: %s, source: %s, operation: %s", result.Content, result.GetResource(), result.GetGroup(), result.GetSource(), result.GetOperation())
```
then rebuild the cloudimage and edgecore binary
```shell
make cloudimage
make all WHAT=edgecore
```
3. restart the cloudcore and add edgecore
![2 add-edgenode](https://user-images.githubusercontent.com/16499075/146877321-ed3a5de8-8bf0-4806-adde-31fc4c507c92.png)
exec the `kubectl get pod -owide -nkubeedge -w` on the cloud

4. start the edgemesh-server and edgemesh-agent
At this moment, there is a problem that various cloud containers are scheduled to edge nodes.
It is found that containers such as `cloudcore` and `edgemesh` are also failing and restarting continuously;
![3 watch-pod-status](https://user-images.githubusercontent.com/16499075/146877464-95fc217a-badf-49b3-a72e-d371cb732b9a.png)
The container being pulled up can be seen on the edge node: `docker ps -a`
![4 docker-pa-a-on-edgenode](https://user-images.githubusercontent.com/16499075/146877571-4d092418-6431-4bbe-a9e9-22edbc006e6b.png)

5. I keep the journal log files on the edge node
[edge-container-list.log](https://github.com/kubeedge/kubeedge/files/7749877/edge-container-list.log)
[edge-journal-3293.log](https://github.com/kubeedge/kubeedge/files/7749881/edge-journal-3293.log)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
I have tested a lot of this, and it has nothing to do with the number of edge nodes. The current positioning is the problem caused by fix #3293; because I don't know much about `synccontroller` and `dynamiccontroller`, I sent the log for answers;
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.17.17

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
v1.8.2 + #3293 

- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by yz271544** [comment]
It is preliminarily determined from the log that it is related to the message sent by the `dynamiccontroller`;

**Comment by yz271544** [comment]
I just communicated with @Poorunga ; and did not start edgemesh on the edge side, direct called edgemesh's listwatch API on the edge side, which also triggered this bug.
```shell
curl http://127.0.0.1:10550/api/v1/pods?watch=yes
```

![2](https://user-images.githubusercontent.com/16499075/146923604-bd926848-5099-4039-8256-52ed038d25e8.png)

**Comment by yz271544** [comment]
I am directly on v1.8.2, modify according to #3293, ignore other fixes, and then start cloudcore and edgecore respectively, and curl listwatch api on the edge node
```shell
curl http://127.0.0.1:10550/api/v1/pods?watch=yes
```

![5 only-3293-on-v1 8 2](https://user-images.githubusercontent.com/16499075/146927544-f12a096e-f0b1-4c51-9d4f-a3c871af5910.png)

This time there is no edgemesh influence, but cloudcore don’t keep trying to transfer to edgenode.
Other containers in the cloud are not transferred to edge nodes.

[only3293-fixon-v1.8.2-edgelistwatch.log](https://github.com/kubeedge/kubeedge/files/7755198/only3293-fixon-v1.8.2-edgelistwatch.log)

**Comment by Rachel-Shao** [comment]
It seems that dynamicController does not filter non-edge pod resources, will fix soon

**Comment by fisherxu** [comment]
👍  Other components running in edge will may list pods through metaServer, so we indeed need the filter for edged.
