### ISSUE TITLE
An error occurred when starting 100 pods at the edge node

### ISSUE THREAD

**Issue by allenleu** [kubeedge/kubeedge#3497]
Start 100 pods at the edge node, and finally about 50 can be started. Checking the status of the edge node container, about 110 containers were started. At present, the maximum number of containers tested in the up state can reach 114. Containers exceeding this number are in the created state and cannot be forced to start.

**Comment by allenleu** [comment]
The following is a screenshot of the log：
![内网通截图20211223152733](https://user-images.githubusercontent.com/79303312/147210053-7673e902-3232-491d-a6f3-31b477046493.jpg)

**Comment by gy95** [comment]
feel that the core error log is `failed to get fd for socket:xxxx, ........  too many open files`, it seems that it's due to docker restriction. not sure.

**Comment by gy95** [comment]
i guess it's related to docker or linux restriction:  https://stackoverflow.com/questions/29403185/docker-error-too-many-open-files

**Comment by allenleu** [comment]
> i guess it's related to containerd or linux restriction: search in the browser : containerd too many open files
Yes, but I checked the information related to it and modified some configurations, but it didn't work.

**Comment by allenleu** [comment]
> i guess it's related to containerd or linux restriction: search in the browser : containerd too many open files

Yes, but I checked the information related to it and modified some configurations, but it didn't work.

**Comment by fisherxu** [comment]
This issue have been fixed? @allenleu

**Comment by allenleu** [comment]
> This issue have been fixed? @allenleu

yes，I changed some of the docker configuration and it worked

**Comment by fisherxu** [comment]
OKey, let's close the issue, please reopen it if there's any other issue :)
/close
