### ISSUE TITLE
Identify session by node name instead of ip

### ISSUE THREAD

**Issue by stingshen** [kubeedge/kubeedge#3498]
**What would you like to be added/modified**:

Identify session by node name instead of ip. Currently, session is identified by node ip when exec and get metrics. It breaks if two edge nodes with the same internal ip are added to the cluster. https://github.com/kubeedge/kubeedge/pull/3136 fixes the behavior on logs. Maybe exec and get metrics could be fixed similarly.

**Why is this needed**:

It is possible that two edge nodes have the same ip in kubeedge cluster. When it is the case, `kubectl logs` and `kubectl top` break because the duplicated internal ip is used to get the session.

Kubesphere uses a sophisticated IPAM to solve the issue: <https://segmentfault.com/a/1190000040467814>. However, I think this issue should be fixed on kubeedge side.

**Comment by sdghchj** [comment]
The blog article you mentioned is a sulotion given by my team in China mobile Co.
We used kubesphere 1.3 which integrated kubeedge 1.6  half a year ago and ran into the edge ip conflict issue, so we posted that alternative sulotion to kubeSphere. I am not sure whether kubesphere adopted the sugested solution in their new version.
But, that solution removes the real ip of edge node, which will break the functions of edgemesh, although in our product, we didn't need edgemesh.
Finally, kubeedge fixed it in 1.8.1 in another way, identifying a node session with the unique node name. This solution keeps the real ip of edge node.
