### ISSUE TITLE
[ProjectOrganization] Issue Labels Update

### ISSUE THREAD

**Issue by skdwriting** [kubeedge/kubeedge#350]
**What would you like to be added**:
Issue labels can be updated:
Some are with kind/<>, some are without kind/
Better we simply add the lables like enhancement, feature, bug etc... (no need to put kind/ -- unless we need it for any processing). It should be enough and clean to understand the issue type.

**Why is this needed**:
Consistency and Simplicity.

**Comment by m1093782566** [comment]
cc @sids-b

**Comment by sids-b** [comment]
I think kind is a keyword to redirect ci-bot towards labels. A future processing possibility I see is that the bot automatically requesting review/ assigning the issue/Pr to a correct person.
For eg: kind/bug issue can be assigned to the person who commited in the file. kind/feature can be assigned to one of the maintainers. kind/documentation can be assigned to the person maintaining docs.

Actually the prefixing will help the ci-bot logic later when traffic is more. Some of the popular prefixing is area/ , sig/
For eg: area/devicetwin, area/cloudhub. sig/networking, sig/devicemanagement.

Offcourse with some extra some we can manage by removing the prefix.

**Comment by sids-b** [comment]
But definitely we can remove duplicate labels foreg: we have bug and kind/bug both.

**Comment by skdwriting** [comment]
looping Rohit @rohitsardesai83

**Comment by skdwriting** [comment]
please check and make it consistent.

**Comment by sids-b** [comment]
Thanks @skdwriting , I have removed all duplicate labels and also made the description consistent.
