### ISSUE TITLE
Can I deploy deep learning algorithms such as cnn or rnn?

### ISSUE THREAD

**Issue by chenzhen1994** [kubeedge/kubeedge#352]
**What would you like to be added**:

Question:

I didn't see how to develop my own application in the development documentation. The three program examples are written in go language. Can I deploy deep learning algorithms such as cnn or rnn?

**Why is this needed**:

**Comment by m1093782566** [comment]
@chenzhen1994 

Would you please describe your need in English though I can read Chinese as well :)

The English speakers in our team may unable to help you if you write down issues in Chinese.

**Comment by m1093782566** [comment]
To your question, kubeedge can run any containered application(no matter what language is) without modifing one piece of code.

**Comment by chenzhen1994** [comment]
> @chenzhen1994
> 
> Would you please describe your need in English though I can read Chinese as well :)
> 
> The English speakers in our team are unable to help you if you write down issues in Chinese.
Ok, I am really sorry.

**Comment by m1093782566** [comment]
@chenzhen1994 

No worries, welcome to try kubeedge and please feel free to contact us if you have any quesitons :)
