### ISSUE TITLE
安装KubeEdge  coreDns无法启动 

### ISSUE THREAD

**Issue by MrHanLei** [kubeedge/kubeedge#3550]
查看日志journalctl -u edgecore.service -b -f

![微信图片_20220112180453](https://user-images.githubusercontent.com/50442900/149123295-3cb4d037-2727-4dc7-b3bd-18c91251ff5d.png)

发现coreDns报错，查看容器日志
![微信图片_20220112182548](https://user-images.githubusercontent.com/50442900/149123518-9951faf8-197c-479d-8b02-b5c66e74d5f1.png)

**Comment by MrHanLei** [comment]
请问这个是啥原因，怎么解决呢？

**Comment by khalid-jobs** [comment]
coredns需要连接apiserver，看输出，你的coredns是被调度到边侧了。在边侧的话，你需要把kubeedge Autonomic Kube-API Endpoint feature 开启，然后把apiserver的地址换为边侧的，也就是http://127.0.0.1:10550
你在边侧部署coreDNS的目的是什么

**Comment by MrHanLei** [comment]
谢谢回复，coredns和calico是在安装边缘节点时，集群自动安装的，请问如果我想让集群正常，应该做哪些操作呢？
keadm join --cloudcore-ipport=192.168.20.50:10000 --token=27a37ef16159f7d3be8fae95d588b79b3adaa
![image](https://user-images.githubusercontent.com/50442900/149158095-932af558-2bab-42c7-8e83-fcae044f02b7.png)


> coredns需要连接API服务器，看输出，你的coredns是被调度到边侧了。在边侧的话，你需要把kubeedge自主库贝-API终点功能开启，然后把API服务器的地址换为边侧的，也就是[HTTP ://127.0.0.1:10550](http://127.0.0.1:10550) 你在边侧部署coreDNS的目的是什么

**Comment by khalid-jobs** [comment]
参考 https://github.com/kubeedge/kubeedge/issues/2677

主要就是加入如下的亲和性
```
# kubectl edit ds -n kube-system kube-flannel-ds
...
spec:
  ...
  template:
    ...
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: node-role.kubernetes.io/agent
                operator: DoesNotExist
```

**Comment by khalid-jobs** [comment]
报错信息是什么？有试着用连接所给的配置试试吗？是否可行

**Comment by MrHanLei** [comment]
> 尝试用所给的配置尝试吗？
您好，目前集群看上去正常了，但是在边缘节点上部署了一个pod，却无法通过service对这个pod进行访问。 请问这个是kubeedge正确的使用方式吗？是否需要通过其它方式进行访问呢？
![1642387775(1)](https://user-images.githubusercontent.com/50442900/149700696-53a0a472-1d5c-4327-9ac2-e96bc2219335.png)
