### ISSUE TITLE
It is possible to install KuberEdge on Edge device that blocked from access to Internet

### ISSUE THREAD

**Issue by baoquach14** [kubeedge/kubeedge#3556]
Hi KubeEdge Support 

Can you please let me know, if it is possible to install KuberEdge on Edge device that blocked from access to Internet, but allow access to local network or intranet. 
Our customers environment such as on Premsie or Edge devces do NOT have access to internet or GiT version control.               

**- Kubernetes version (use `kubectl version`):**
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79
03a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersio
6.10", Compiler:"gc", Platform:"linux/amd64"}

**- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):**
- cloudcore --version output > KubeEdge v1.8.2 on the master node
 -edgecore  --version  KubeEdge v1.9.1 on edge device

Thank you for your help and support

Regards, Bao

**Comment by fisherxu** [comment]
KubeEdge edgenode need to connect to the cloudside, so you only need to make sure the edge nodes can access to the cloudnode/cloudcore :)
