### ISSUE TITLE
Can you advise for Production environment what the minium Kubernetes master nodes need to setup to manage 1000 KubeEdges on Edge devices   

### ISSUE THREAD

**Issue by baoquach14** [kubeedge/kubeedge#3564]
Hi KubeEdge Team

Can you advise for Production environment what the minium Kubernetes master nodes and worker nodes need to setup to manage 1000 KubeEdges on Edge devices , PostregSQL, Prometheus and Alert Manager Prometheus.  

**Environment**:
- Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79
03a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersio
6.10", Compiler:"gc", Platform:"linux/amd64"}

- KubeEdge version(e.g. cloudcore --version and edgecore --version):

cloudcore --version output > KubeEdge v1.8.2 on the master node
-edgecore --version KubeEdge v1.9.1 on edge device

Thank you for your help and support

Regards, Bao

**Comment by fisherxu** [comment]
What's the meaning of ` 1000 KubeEdges on Edge devices , PostregSQL, Prometheus and Alert Manager Prometheus.`?

**Comment by baoquach14** [comment]
What's the meaning of 1000 KubeEdges on Edge devices , PostregSQL, Prometheus and Alert Manager Prometheus.?
means:
 1000 instances on KubeEdges  running  on 1000  Edge devices (edge computers)
One instance PostregSQL running on a Worker node
One instance Prometheus  running on a Worker node
One instance Alert Manager Prometheus  running on a Worker node

Regards, Bao

**Comment by fisherxu** [comment]
You'd better to deploy 3 k8s masters and 2~3 cloudcores to manage 1000 edge nodes.
