### ISSUE TITLE
After the edge node is powered off, the application cannot be restored when it is powered on again one day later

### ISSUE THREAD

**Issue by suwu** [kubeedge/kubeedge#3579]
**What happened**:
An application is deployed on the edge node. After shutting down for a period of time, many records of the application in terminating status will appear on the cloud, and the application cannot return to normal after the edge node is powered on.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by fisherxu** [comment]
> An application is deployed on the edge node
> many records of the application in terminating status will appear on the cloud, 

This is because the pod eviction?
