### ISSUE TITLE
metaServer cannot return k8s version information

### ISSUE THREAD

**Issue by Poorunga** [kubeedge/kubeedge#3580]
**What happened**:
Now, metaServer cannot return k8s version information, like:
```
$ curl 127.0.0.1:10550/version
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Internal error occurred: not a resource req",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "not a resource req"
      }
    ]
  },
  "code": 500
}
```

**What you expected to happen**:
I hope metaServer can return k8s version information correctly, like:
```
$ curl 127.0.0.1:10550/version
{
  "major": "1",
  "minor": "21",
  "gitVersion": "v1.21.8",
  "gitCommit": "4a3b558c52eb6995b3c5c1db5e54111bd0645a64",
  "gitTreeState": "clean",
  "buildDate": "2021-12-15T14:46:22Z",
  "goVersion": "go1.16.12",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.8
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.8.2
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by fujitatomoya** [comment]
@Poorunga we probably want to reopen this issue?
