### ISSUE TITLE
type.**k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1.ContainerPreferredAllocationRequest: dwarf: definition of unknown kind 0

### ISSUE THREAD

**Issue by dafanshu** [kubeedge/kubeedge#3586]
**What happened**:
compile error in raspberry pi 3B+:
`ubuntu@ubuntu:~/kubeedge-1.8.2$ CGO_ENABLED=1 GOARM=7 GOOS=linux GOARCH=arm go build -o ./_out ./edge/cmd/edgecore
# github.com/kubeedge/kubeedge/edge/cmd/edgecore
type.**k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1.ContainerPreferredAllocationRequest: dwarf: definition of unknown kind 0
panic: runtime error: slice bounds out of range [40:36]

goroutine 1 [running]:
cmd/link/internal/ld.decodetypeIfaceMethodCount(0x415f80, {0x91735251, 0x24, 0x24})
        /usr/local/go/src/cmd/link/internal/ld/decodesym.go:92 +0x84
cmd/link/internal/ld.(*dwctxt).newtype(0x4c8d51c, 0x11cba7)
        /usr/local/go/src/cmd/link/internal/ld/dwarf.go:637 +0x390
cmd/link/internal/ld.(*dwctxt).defgotype(0x4c8d51c, 0x11cba7)
        /usr/local/go/src/cmd/link/internal/ld/dwarf.go:536 +0x10c
cmd/link/internal/ld.(*dwctxt).dwarfVisitFunction(0x4c8d51c, 0x75561, 0x21022a0)
        /usr/local/go/src/cmd/link/internal/ld/dwarf.go:1709 +0x524
cmd/link/internal/ld.dwarfGenerateDebugInfo(0x10ec000)
        /usr/local/go/src/cmd/link/internal/ld/dwarf.go:1875 +0x1544
cmd/link/internal/ld.Main(0x415f80, {0x4, 0x8, 0x1, 0xd, 0xe, 0x1c00000, {0x0, 0x0}, {0x295198, ...}, ...})
        /usr/local/go/src/cmd/link/internal/ld/main.go:265 +0x128c
main.main()
        /usr/local/go/src/cmd/link/main.go:69 +0xbb0
`
 
**What you expected to happen**:
just compile edgecore module

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): 
1.8.2
  - Hardware configuration (e.g. `lscpu`):
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1400.0000
CPU min MHz:         600.0000
BogoMIPS:            89.60
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

  - OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

  - Kernel (e.g. `uname -a`):
Linux ubuntu 5.4.0-1042-raspi #46-Ubuntu SMP PREEMPT Fri Jul 30 00:36:54 UTC 2021 armv7l armv7l armv7l GNU/Linux
  - Go version (e.g. `go version`):
go version go1.17.6 linux/arm
  - Others:

  </details>

**Comment by gy95** [comment]
you can just try to run `make all WHAT=edgecore` on your raspberry pi 3B+ machine.
the print error seems not to belong to compile errors.

**Comment by dafanshu** [comment]
I got the result below，when execute：make all WHAT=edgecore
`root@ubuntu:/home/ubuntu/pkg/kubeedge# make all WHAT=edgecore
hack/verify-golang.sh
go detail version: go version go1.17.6 linux/arm
go version: 1.17.6
KUBEEDGE_OUTPUT_SUBPATH=_output/local hack/make-rules/build.sh edgecore
building github.com/kubeedge/kubeedge/edge/cmd/edgecore
+ go build -o /home/ubuntu/pkg/kubeedge/_output/local/bin/edgecore -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2022-01-25T06:09:12Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=14457d2c33e242a64c4238cce2c4c3b6394f8cf6 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.9.0-beta.0.6+14457d2c33e242 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=9+' github.com/kubeedge/kubeedge/edge/cmd/edgecore
# github.com/kubeedge/kubeedge/edge/cmd/edgecore
panic: runtime error: index out of range [960768] with length 15

goroutine 1 [running]:
cmd/link/internal/loader.(*Loader).resolve(0x966000, 0x1bdc700, {0xea90                                                                                                                                     0, 0x0})
        /usr/local/go/src/cmd/link/internal/loader/loader.go:668 +0x200
cmd/link/internal/loader.Reloc.Sym({0x8b84de6c, 0x1bdc700, 0x966000})
        /usr/local/go/src/cmd/link/internal/loader/loader.go:59 +0x68
cmd/link/internal/ld.(*deadcodePass).flood(0x88d5bc)
        /usr/local/go/src/cmd/link/internal/ld/deadcode.go:199 +0x7a0
cmd/link/internal/ld.deadcode(0x930000)
        /usr/local/go/src/cmd/link/internal/ld/deadcode.go:330 +0x4c
cmd/link/internal/ld.Main(0x415f80, {0x4, 0x8, 0x1, 0xd, 0xe, 0x1c00000                                                                                                                                     , {0x0, 0x0}, {0x295198, ...}, ...})
        /usr/local/go/src/cmd/link/internal/ld/main.go:252 +0x11d0
main.main()
        /usr/local/go/src/cmd/link/main.go:69 +0xbb0
make: *** [Makefile:49: all] Error 2
`

**Comment by fisherxu** [comment]
Maybe because the memory of  the 3B is not enough, the memory is 1GB?

**Comment by gy95** [comment]
```
root@ubuntu:/home/ubuntu/pkg/kubeedge# make all WHAT=edgecore
hack/verify-golang.sh
go detail version: go version go1.17.6 linux/arm
go version: 1.17.6
KUBEEDGE_OUTPUT_SUBPATH=_output/local hack/make-rules/build.sh edgecore
building github.com/kubeedge/kubeedge/edge/cmd/edgecore

go build -o /home/ubuntu/pkg/kubeedge/_output/local/bin/edgecore -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2022-01-25T06:09:12Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=14457d2c33e242a64c4238cce2c4c3b6394f8cf6 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.9.0-beta.0.6+14457d2c33e242 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=9+' github.com/kubeedge/kubeedge/edge/cmd/edgecore
github.com/kubeedge/kubeedge/edge/cmd/edgecore
panic: runtime error: index out of range [960768] with length 15

goroutine 1 [running]:
cmd/link/internal/loader.(*Loader).resolve(0x966000, 0x1bdc700, {0xea90 0, 0x0})
/usr/local/go/src/cmd/link/internal/loader/loader.go:668 +0x200
cmd/link/internal/loader.Reloc.Sym({0x8b84de6c, 0x1bdc700, 0x966000})
/usr/local/go/src/cmd/link/internal/loader/loader.go:59 +0x68
cmd/link/internal/ld.(*deadcodePass).flood(0x88d5bc)
/usr/local/go/src/cmd/link/internal/ld/deadcode.go:199 +0x7a0
cmd/link/internal/ld.deadcode(0x930000)
/usr/local/go/src/cmd/link/internal/ld/deadcode.go:330 +0x4c
cmd/link/internal/ld.Main(0x415f80, {0x4, 0x8, 0x1, 0xd, 0xe, 0x1c00000 , {0x0, 0x0}, {0x295198, ...}, ...})
/usr/local/go/src/cmd/link/internal/ld/main.go:252 +0x11d0
main.main()
/usr/local/go/src/cmd/link/main.go:69 +0xbb0
make: *** [Makefile:49: all] Error 2
```


not sure, what's your arch, please run `uname -a` and what's the output?

**Comment by gy95** [comment]
you can try golang1.16 or 1.17 lower version to check whether it's related to go version.

**Comment by dafanshu** [comment]
> 
Linux ubuntu 5.4.0-1042-raspi #46-Ubuntu SMP PREEMPT Fri Jul 30 00:36:54 UTC 2021 armv7l armv7l armv7l GNU/Linux

**Comment by dafanshu** [comment]
> ```
> root@ubuntu:/home/ubuntu/pkg/kubeedge# make all WHAT=edgecore
> hack/verify-golang.sh
> go detail version: go version go1.17.6 linux/arm
> go version: 1.17.6
> KUBEEDGE_OUTPUT_SUBPATH=_output/local hack/make-rules/build.sh edgecore
> building github.com/kubeedge/kubeedge/edge/cmd/edgecore
> 
> go build -o /home/ubuntu/pkg/kubeedge/_output/local/bin/edgecore -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2022-01-25T06:09:12Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=14457d2c33e242a64c4238cce2c4c3b6394f8cf6 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.9.0-beta.0.6+14457d2c33e242 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=9+' github.com/kubeedge/kubeedge/edge/cmd/edgecore
> github.com/kubeedge/kubeedge/edge/cmd/edgecore
> panic: runtime error: index out of range [960768] with length 15
> 
> goroutine 1 [running]:
> cmd/link/internal/loader.(*Loader).resolve(0x966000, 0x1bdc700, {0xea90 0, 0x0})
> /usr/local/go/src/cmd/link/internal/loader/loader.go:668 +0x200
> cmd/link/internal/loader.Reloc.Sym({0x8b84de6c, 0x1bdc700, 0x966000})
> /usr/local/go/src/cmd/link/internal/loader/loader.go:59 +0x68
> cmd/link/internal/ld.(*deadcodePass).flood(0x88d5bc)
> /usr/local/go/src/cmd/link/internal/ld/deadcode.go:199 +0x7a0
> cmd/link/internal/ld.deadcode(0x930000)
> /usr/local/go/src/cmd/link/internal/ld/deadcode.go:330 +0x4c
> cmd/link/internal/ld.Main(0x415f80, {0x4, 0x8, 0x1, 0xd, 0xe, 0x1c00000 , {0x0, 0x0}, {0x295198, ...}, ...})
> /usr/local/go/src/cmd/link/internal/ld/main.go:252 +0x11d0
> main.main()
> /usr/local/go/src/cmd/link/main.go:69 +0xbb0
> make: *** [Makefile:49: all] Error 2
> ```
> 
> not sure, what's your arch, please run `uname -a` and what's the output?

Linux ubuntu 5.4.0-1042-raspi #46-Ubuntu SMP PREEMPT Fri Jul 30 00:36:54 UTC 2021 armv7l armv7l armv7l GNU/Linux

**Comment by dafanshu** [comment]
> 



> Maybe because the memory of the 3B is not enough, the memory is 1GB?

yes ,but i swap 1GB

**Comment by dafanshu** [comment]
I am trying to complie in another ubuntu amd64 node , use comond :
`make crossbuild WHAT=edgecore GOARM=GOARM7`
It work well , but raspberry pi 3B+ can not recognize it
`
ubuntu@ubuntu:~$ sh edgecore

edgecore: 1: Syntax error: word unexpected (expecting ")")

`
help~~~

**Comment by gy95** [comment]
> I am trying to complie in another ubuntu amd64 node , use comond : `make crossbuild WHAT=edgecore GOARM=GOARM7` It work well , but raspberry pi 3B+ can not recognize it ` ubuntu@ubuntu:~$ sh edgecore
> 
> edgecore: 1: Syntax error: word unexpected (expecting ")")
> 
> ` help~~~

just run ./edgecore

**Comment by dafanshu** [comment]
> 



> > I am trying to complie in another ubuntu amd64 node , use comond : `make crossbuild WHAT=edgecore GOARM=GOARM7` It work well , but raspberry pi 3B+ can not recognize it ` ubuntu@ubuntu:~$ sh edgecore
> > edgecore: 1: Syntax error: word unexpected (expecting ")")
> > ` help~~~
> 
> just run ./edgecore

can‘t work too
`ubuntu@ubuntu:~$ ./edgecore`
`-bash: ./edgecore: No such file or directory`

**Comment by gy95** [comment]
you should run `./edgecore` in the directory where binary `edgecore` is located. you can run `ls` to ensure that you've already cd in the right directory.

**Comment by dafanshu** [comment]
> 



> you should run `./edgecore` in the directory where binary `edgecore` is located. you can run `ls` to ensure that you've already cd in the right directory.

the directory is right， raspberry pi 3B+ can not recognize the binary edgecore …… so print No such file-_-

**Comment by dafanshu** [comment]
> 



> Could you please have a try? In your amd64 host, run(mainly set the `CGO_ENABLED` to 0):
> 
> ```
> export GOARCH=arm
> export GOOS=linux
> export GOARM=7
> export CGO_ENABLED=0
> export CC=arm-linux-gnueabi-gcc
> 
> then crossbuild the edgecore
> go build -o ./_output/local/bin/edgecore  edge/cmd/edgecore
> ```
> 
> Then copy the edgecore to rasp to have a test. @dafanshu

try many times, I can't compile in rastberry pi 3B+,
but at last, I find this param is work :  CC=arm-linux-gnueabi**hf**-gcc, when i use crossbuild：
`export CC=arm-linux-gnueabihf-gcc`
every thing is ok，

 “arm-linux-gnueabi-gcc” is not work well.

**Comment by gy95** [comment]
try set GOARM variables:
https://github.com/golang/go/wiki/MinimumRequirements#arm

**Comment by dafanshu** [comment]
thx
