### ISSUE TITLE
Can we add a node by a single command?

### ISSUE THREAD

**Issue by YuPengZTE** [kubeedge/kubeedge#360]
**What would you like to be added**:
Can we add a node by a single command like “k3s agent -s ${SERVER_URL} -t ${NODE_TOKEN} ” in k3s, or “docker swarm join-token ${NODE_TOKEN}” in docker swarm?
**Why is this needed**:
The operation is simple and common.

**Comment by m1093782566** [comment]
Make sense. Actually we are developing the kubeedge installer to launch kubeedge cluster easily, please check: https://github.com/kubeedge/kubeedge/pull/342

**Comment by YuPengZTE** [comment]
@m1093782566 Good news!
It is better to add the way of adding nodes by token in [run-edge](https://github.com/kubeedge/kubeedge/blob/master/README.md#run-edge)

**Comment by m1093782566** [comment]
@YuPengZTE 

I wish you can join this effort :)

**Comment by YuPengZTE** [comment]
@m1093782566 Thanks for your invitation, I would like to participate in it.

**Comment by sids-b** [comment]
Thanks @YuPengZTE 

@samy2019 @srivatsav123 you guys can collaborate with @YuPengZTE on this effort :)

**Comment by YuPengZTE** [comment]
In my practice, I found some points are not easy to understand, in [inscope](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/kubeedgeadm-scope.md#inscope):
1. The nodes are included cloud nodes and edge nodes, so it is better to change kubeedge node into kubeedge edge.
2. Since kubeedge edge had edge used twice and didn't sound nice, and kubeedge and kubedge are confused, we can change kubeedge into "kec"(K8s in/for/.. edge computing) or other words. So kubeedge edge is changed with kec edge.
@m1093782566 @sids-b @samy2019 @srivatsav123

**Comment by rohitsardesai83** [comment]
@samy2019 , @srivatsav123 , please coordinate with @YuPengZTE on this effort. 
@YuPengZTE , please feel free to discuss on slack and take up some tasks . Thanks !
