### ISSUE TITLE
0 por [Jack-Rogers](https://github.com/D3VL/L3MON/issues?q=is%3Aissue+author%3AJack-Rogers) foi fechadoon 23 Dec 2020

### ISSUE THREAD

**Issue by Cleyhilton-Nascimento** [kubeedge/kubeedge#3612]
#150 por [Jack-Rogers](https://github.com/D3VL/L3MON/issues?q=is%3Aissue+author%3AJack-Rogers) foi fechadoon 23 Dec 2020

**Comment by fisherxu** [comment]
What's meaning of the issue? I'll close it now, feel free to reopen it if there's any other question.
/close
