### ISSUE TITLE
Modify configmap when edge is offline

### ISSUE THREAD

**Issue by allenleu** [kubeedge/kubeedge#3638]
**What happened**:
If the configmap is modified when the edge is offline, the value in the pod is not updated after the network is restored.
**What you expected to happen**:
The content of the configmap updated during offline is synchronized with the pod after the network is restored.
**How to reproduce it (as minimally and precisely as possible)**:
Create a deploy mount configmap and schedule it to the edge node, the pod runs normally, then disconnect the network, wait 5-10 minutes, modify the value of the configmap, then connect to the network, enter the pod to view the value of the configmap in the mount directory, and find that the value is not renew.
**Environment**:
- Kubernetes version (use `kubectl version`):1.20.10
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.8.1

**Comment by vincentgoat** [comment]
Hi @allenleu we solved this issue by this PR #3578

**Comment by vincentgoat** [comment]
Hi @allenleu, What is the query result of the kubectl command for pod status after network restore?  Terminating or something else? I reproduced the same problem and the pod status is Terminating.

**Comment by allenleu** [comment]
> 嗨@allenleu，kubectl命令对网络恢复后pod状态的查询结果是什么？终止还是其他？我重现了同样的问题，并且 pod 状态为 Terminating。

**Comment by allenleu** [comment]
> Hi @allenleu, What is the query result of the kubectl command for pod status after network restore? Terminating or something else? I reproduced the same problem and the pod status is Terminating.

Modifying configMap alone does not change the POD state, but mounting configMap while offline, or any other action that causes the POD to restart, changes the POD to the terminating state.
