### ISSUE TITLE
deployment is running but hit "connect: connection refused" error message

### ISSUE THREAD

**Issue by chendave** [kubeedge/kubeedge#365]
**What happened**:
Follow the guide here: https://github.com/kubeedge/kubeedge, I can set up an kubeedge cluster with one controller and one edge node, the deployment canbe created and the status is running, but the logs in the pod tell me there is "connect: connection refused" error.

```bash
$ kubectl get pods
NAME                               READY   STATUS        RESTARTS   AGE
nginx-deployment-b444b6b8b-ctp8h   1/1     Running       0          4m45s

$ kubectl logs nginx-deployment-b444b6b8b-ctp8h 
Error from server: Get https://10.169.41.219:10250/containerLogs/default/nginx-deployment-74f447756b-dq7t6/nginx: dial tcp 10.169.41.219:10250: connect: connection refused
```

And I cannot access nginx service with curl anyway.

In case the pod is scheduled on the controller node, everything works fine (I don't think schedule the workload to controller node make sense here.)

Looks like the 10250 is used by kubelet,  have checked there is no such port open on the edge node.

**What you expected to happen**:
should not see such error message, service could be accessed correctly, and not sure the reaching of port here "10250" is correct or not.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the guide https://github.com/kubeedge/kubeedge, create a deployment like this,
```kubectl apply -f $GOPATH/src/github.com/kubeedge/kubeedge/build/deployment.yaml```

and then check the logs from the pod,
```$ kubectl logs nginx-deployment-b444b6b8b-ctp8h ```

**Anything else we need to know?**:

**Environment**:
- KubeEdge version: latest
- Hardware configuration: amd64
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Others:

**Comment by m1093782566** [comment]
@chendave Please check: #261

If this is an necessary feature, we can start the design in community.

**Comment by chendave** [comment]
okay, thanks for the info, close it now.

**Comment by yangbin1212** [comment]
> okay, thanks for the info, close it now.
Hello, I have encountered this problem. How do you solve it? Look at another issue, I don’t understand it. Is it not supported?

**Comment by sids-b** [comment]
@yangbin1212 , yess logs and exec is not supported as it seems edged doesn't expose any port for that.

**Comment by yangbin1212** [comment]
> @yangbin1212 , yess logs and exec is not supported as it seems edged doesn't expose any port for that.

What I want to ask is how do I confirm that my application has been deployed successfully? Because I didn't see the page I could eventually access.

**Comment by sids-b** [comment]
We are have ing a eature in pipeline called EdgeMesh in pipeline. Once it is implemented, we can access the application running on edgeNode . Please see the design here https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/edgemesh-design.md
