### ISSUE TITLE
Any plans to link KubeEdge and BlockChain?

### ISSUE THREAD

**Issue by pidb** [kubeedge/kubeedge#3653]
**What happened and what you expected to happen**:
Any plans to link KubeEdge and BlockChain? such as Hyperledger Fabric?

**Comment by fisherxu** [comment]
> Any plans to link KubeEdge and BlockChain? such as Hyperledger Fabric?

No clear plan so far, but if there's any user scenarios, we can do some discussion. @7bytes Has any ideas?
