### ISSUE TITLE
edgemesh's pod can't work on the edge 

### ISSUE THREAD

**Issue by zz952332446** [kubeedge/kubeedge#3677]
### master
* network: public server with public ip
* k8s:1.21.0 ( installed with kubeadm)
* keadm: 1.8.2
```
keadm init --advertise-address=public ip --kubeedge-version=1.8.2
```
* kubeedge: 1.8.2

* edgemesh: installed with HELM :
```
helm install edgemesh --set server.nodeName=**  --set server.publicIP=*** https://raw.githubusercontent.com/kubeedge/edgemesh/main/build/helm/edgemesh.tgz
```
I config edgemesh according to [EdgeMesh](https://edgemesh.netlify.app/zh/guide/getting-started.html)

### agent
* net: Campus Network
* keadm: 1.8.2
* kubeedge: 1.8.2

### question
edgemesh's pod can work on the master, but on the edge can't work mostly, even restart again and again!

this is ·`kubectl get no`
![](https://gitee.com/hhyyzzzzz/image/raw/master/image/image-20220310203551329.png)

this is `kubectl get pod -A`, you can see the pod:edgemesh-agent is pending. 
![](https://gitee.com/hhyyzzzzz/image/raw/master/image/image-20220310204523774.png)

On the agent, it doesn't have any container about edgemesh-agent

Or, it has containers about edgemesh-agent, but they can't work
![image-20220310200914407](https://gitee.com/hhyyzzzzz/image/raw/master/image/image-20220310200914407.png)

### error log
I can't get logs helpful according to `systemctl status edgecore` or `journalctl -u edgecore.service -b`

Through `systemctl status docker`: it seems that docker was stuck in something??
![image-20220310202646605](https://gitee.com/hhyyzzzzz/image/raw/master/image/image-20220310202646605.png)

**Comment by Poorunga** [comment]
@zz952332446 please move this issue to https://github.com/kubeedge/edgemesh/issues

**Comment by zz952332446** [comment]
> ok，done

**Comment by zz952332446** [comment]
> @zz952332446 please move this issue to https://github.com/kubeedge/edgemesh/issues

ok，done

**Comment by fisherxu** [comment]
I'll close this one :)
