### ISSUE TITLE
Can we install kubeedge in PHICOMM N1

### ISSUE THREAD

**Issue by YuPengZTE** [kubeedge/kubeedge#372]
**What would you like to be added**:
A user story of large-scale, low-power container cluster in edge computing with kubeedge like k3s.
**Why is this needed**:
For users, if kubeedge can be installed on N1 simply and quickly, and running smoothly, then kubeedge can run in most EC scenarios.

P.S.
[Introduction of phicomm n1](https://www.cnx-software.com/2019/03/11/phicomm-n1-tv-box-linux-distributions/)

[N1 deployment containerized server k3s server](https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=506438). 
I just found the chinese document, sorry.

**Comment by m1093782566** [comment]
The KubeEdge agent(edge-core) is much light-weight than k3s agent and edge-core can run on both amd and arm Linux platform.

We have not tested running edge-core in PHICOMM N1 but I guess there should be no big issues. Why not have a try?

**Comment by YuPengZTE** [comment]
Although I have not tried it, I think there should be no big problem running the kubeedge agent on N1. The question may be whether the kubeedge cloud can be run on N1. In other words, can we run the kubeedge cloud in the form of k3s deployment on N1, similar to [Deploy the cloud part into a k8s cluster](https://github.com/kubeedge/kubeedge/blob/master/build/cloud/README.md), or the kubeedge cloud is directly ported to the k3s master based on the changes of the kubernetes master, similar to [run-as-a-binary](https://github.com/kubeedge/kubeedge/blob/master/README.md#run-as-a-binary)

**Comment by m1093782566** [comment]
> In other words, can we run the kubeedge cloud in the form of k3s deployment on N1, similar to Deploy the cloud part into a k8s cluster, or the kubeedge cloud is directly ported to the k3s master based on the changes of the kubernetes master, similar to run-as-a-binary

Interesting point. I think we have discussed it before. You may want to check: https://github.com/kubeedge/kubeedge/pull/316

**Comment by m1093782566** [comment]
cc @CindyXing @qizha

**Comment by YuPengZTE** [comment]
Thanks for your reminder. @m1093782566 
I will close this issue when I have run the kubeedge cloud in the form of k3s deployment.

**Comment by m1093782566** [comment]
Great! Looking forward to your further feedback :)

**Comment by CindyXing** [comment]
KubeEdge is branded as an architecture to run control plane at cloud; and worker nodes at edge location. For scenarios where a whole lightweight cluster is to be installed/run at edge, the idea is EdgeSite. Here it is to propose running K3s master together with kubeedge agent; and benefit from both.

**Comment by sids-b** [comment]
ping @YuPengZTE , any update ?

**Comment by sids-b** [comment]
Closing this issue. Please feel free to reopen or ping on slack for further discussions :)
