### ISSUE TITLE
Networking: error dialing backend

### ISSUE THREAD

**Issue by Berndinox** [kubeedge/kubeedge#3749]
**What happened and what you expected to happen**:
I dont know if this is a normal behaviour, but networking does not seem to work.
```
kubectl exec -it -n=test1 nginx1-996c49d8f-nsxhd -- bash
Error from server: error dialing backend: dial tcp: lookup edge-2: Try again
```
I also can not curl any service (NodePort as well as ClusterIP)
when i schedule pods on the master (from which i made the test) i can curl and exec into the pods/services.
when i schedule the pods on the edge nodes, everything seems fine, but not for the networking part.
```
kubectl get all -n=test1 -o wide
NAME                         READY   STATUS    RESTARTS   AGE    IP           NODE     NOMINATED NODE   READINESS GATES
pod/nginx1-996c49d8f-qtt9k   1/1     Running   0          151m   172.17.0.2   edge-1   <none>           <none>
pod/nginx1-996c49d8f-ks2lp   1/1     Running   0          151m   172.17.0.3   edge-1   <none>           <none>
pod/nginx1-996c49d8f-q6zs4   1/1     Running   0          151m   172.17.0.3   edge-2   <none>           <none>
pod/nginx1-996c49d8f-nsxhd   1/1     Running   0          151m   172.17.0.2   edge-2   <none>           <none>

NAME                 TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE    SELECTOR
service/nginx1-svc   NodePort   10.43.124.167   <none>        8000:30007/TCP   151m   app=nginx1

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS   IMAGES             SELECTOR
deployment.apps/nginx1   4/4     4            4           151m   nginx1       nginxdemos/hello   app=nginx1,version=v1
```

The deployment used is verified and did work on another cluster.

I did use:
- K3s on the Master
- Docker on the Edge nodes

Followed the installation routine from the docs (keadm ctl)
Scheduling Pods, creating ressources seems to work.

I also tried: https://kubeedge.io/en/docs/advanced/edgemesh/ without success.

Then i found this: https://edgemesh.netlify.app/guide/getting-started.html#step3
i run through the steps, however the option: edgeMesh: enable to the edge nodes does not exist.
curl 127.0.0.1:10550/api/v1/services - does not work, even all steps run through successfully.

I then switched to kubeadm, resulting in a similar issue.
Error when curl to the service: 
`curl: (7) Failed to connect to 10.100.232.90 port 8000: No route to host`

Is there any consitent documentation?
I do really miss the network part.

BR Bernd

**Comment by linuswagner** [comment]
@Berndinox did you find a solution for your problem? If so, could you share it?
