### ISSUE TITLE
update TLS default version in streamserver ? 

### ISSUE THREAD

**Issue by snstaberah** [kubeedge/kubeedge#3753]
I found that in cloudstream  streamserver use default tlsconfig to launch httpserver,  and tunnelserver  used  TLS1.2 as minversion，why not use 1.2 as  default tls version in streamserver？ 

**What would you like to be added/modified**:
add MinVersion:   tls.VersionTLS12, in streamserver
**Why is this needed**:
this can improve security of cloudcore，and pass some security test

**Comment by fisherxu** [comment]
@snstaberah Thanks for pointing out it, and would you like to open a pr to fix it?
