### ISSUE TITLE
What will happen if edge node ip changed?

### ISSUE THREAD

**Issue by wfchair** [kubeedge/kubeedge#3763]
**What happened and what you expected to happen**:

kubeedge edgecore was deployed onto an edge node whose ip was dhcp allocated.
the edge node ip changed by some reason.

1) Can I fix the potential problem ( problem of edgemesh etc. components included) 
by change /etc/kubeedge/config/edgecore.yaml as per real ip?

2) What will happen if no action was taken for ip change? 
Do I have to modify edgecore.yaml as per real ip?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by vincentgoat** [comment]
@wfchair it may cause some error for streaming and DNS function, you can set CustomInterfaceName on edged to avoid IP change problem, FYI [https://github.com/kubeedge/kubeedge/blob/master/edge/cmd/edgecore/app/server.go#L93](url)

**Comment by mhh12121** [comment]
@vincentgoat Let's assume the edgenode is exposed in Public Internet environment(WAN). Is it necessary to consider the net provider may provide it with a different IP in different time ?

**Comment by vincentgoat** [comment]
Most of the time, no.
The NodeIP may be mattered if there is a need for service traffic.

**Comment by mhh12121** [comment]
> Most of the time, no. The NodeIP may be mattered if there is a need for service traffic.

That's what I'm concerned about. If I need to ensure the traffic between edge and master node but under a low quality network environment( the kubeege may reconnect at anytime). Once the edge node's ip changed, the master would no longer reconnect to the edge node?
