### ISSUE TITLE
Is there some gui tools good for kubeedge?

### ISSUE THREAD

**Issue by alongL** [kubeedge/kubeedge#3799]
I want to view status of edge nodes  and controll it .
Is the some gui tools works  for kubeedge?
I have tried Kubesphere, but I think it's very hard to use with little document.
Greatly increase our work.

Can some other web gui application can be used to  monitor kubeedge and edge node?

**Comment by fisherxu** [comment]
@alongL Now we aleady have the plan to design a dashboard for kubeedge. Now dashbord of k8s can used to monitor kubeedge and edge node. Ref: https://github.com/kubernetes/dashboard

**Comment by alongL** [comment]
dashboard seems good. 

![image](https://user-images.githubusercontent.com/5533883/163748473-f3a2b6f5-1cfd-4dc4-a63b-7da40741a3ca.png)

**Comment by fisherxu** [comment]
> dashboard seems good.

OKey, I'll close this issue, please reopen it if there's any issue.
/close
