### ISSUE TITLE
bump ginkgo from v1 to v2

### ISSUE THREAD

**Issue by Congrool** [kubeedge/kubeedge#3829]
**What would you like to be added/modified**:

Bump ginkgo to v2.
Currently, kubeedge is using `ginkgo v1.14.0`, I think we need to bump it to `ginkgo v2.1.4` which is the latest released version.

**Why is this needed**:
There're two reasons for this bump.
1. As described in the [official doc of ginkgo](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#:~:text=With%20the%20release%20of%20Ginkgo%202.0%20the%201.x%20version%20is%20formally%20deprecated%20and%20no%20longer%20supported.%20All%20future%20development%20will%20occur%20on%20version%202.), v1 is deprecated and all new features will be added to v2.
2. We need the [Serial Decorator feature](https://onsi.github.io/ginkgo/#serial-specs) of v2, and I'll explain the scenario why we need it.

In summary, we need a way to mark the specific e2e tests as serial to avoid running them in parallel, which may cause race condition. For v1, we cannot mark the e2e test as serial within code. 
For example, and it's also the problem I encountered when writing e2e tests for the nodegroup crd: one node can only belong to one nodegroup at a time, if this node has already belonged to nodegroup A, it cannot belong to nodegroup B until nodegroup A has removed this node. Thus, if we run serval tests in parallel, only the first one can successfully select the node.

I notice that kubernetes solves this problem using `[Serial]` tag in `Describe` statement, and specify the ginkgo option `-focus` and `-skip` to select tests of which label to run or not run. When needing to run tests of `[Serial]` label, additional `-nodes` option should be set to specify the parallelism. It's a bit complicated. 
Also, kubernetes seems to migrate its ginkgo version from v1 to v2, see kubernetes/kubernetes#109111, so I think it's time for kubeedge.

**Comment by Congrool** [comment]
And if we actually need to do this, I'd like to take over this work.

**Comment by fisherxu** [comment]
@Congrool Sounds good, go ahead.

**Comment by gy95** [comment]
>  We need the [Serial Decorator feature](https://onsi.github.io/ginkgo/#serial-specs) of v2, and I'll explain the scenario why we need it.

Do you mean that we can run e2e parallelly? @Congrool

**Comment by Congrool** [comment]
I originally mean that we need a way to mark some tests to run in serial. It's the new feature of ginkgo v2 called [Serial Decorator](https://onsi.github.io/ginkgo/#serial-specs). 

Currently, e2e tests of KubeEdge seem not run in parallel as ginkgo is not provided with the option `-p` in [fast_test.sh](https://github.com/kubeedge/kubeedge/blob/d187efbddff22ba51db2e7fb77678a0ba05b762f/tests/e2e/scripts/fast_test.sh#L31-L49).

I'm not sure if our tests are ready to run in parallel, you know, some cannot run in parallel such as the scenario I discribed above. So, before running them in parallel, we need to check the existing tests first. If someone cannot run in parallel, we need to mark it as serial.

**Comment by gy95** [comment]
yes, can continue work about marking tests to run in serial, so that we can fasten the e2e if we run test in parallel with option `-p`.   :)
