### ISSUE TITLE
[Feature] To support edge nodes running on OpenHarmony

### ISSUE THREAD

**Issue by huanwei** [kubeedge/kubeedge#3839]
**What would you like to be added/modified**:
To support edge nodes running on OpenHarmony.

**Why is this needed**:
At present, most edge computing frameworks in the industry only discuss GPOS scenarios. While the future of edge computing will definitely extend to scenarios that require more real-time and lower power consumption. Therefore, it is very challenging and meaningful to realize the support of edge computing for lightweight operating systems such as OpenHarmony and embedded RTOS.

**Comment by Shelley-BaoYue** [comment]
[Implementation of the KubeedgeOnOpenHarmony](https://github.com/kubeedge/community/pull/111)
