### ISSUE TITLE
CI is stuck for all new PR's

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#385]
**Which jobs are failing**:
CI is stuck for all the new PR's

**Anything else we need to know**:
Do we have a problem with our travis.yml or there is some problem with travis(looks doubtful)

**Comment by sids-b** [comment]
This is the last PR merged in travis.yml
https://github.com/kubeedge/kubeedge/pull/378

**Comment by edisonxiang** [comment]
https://travis-ci.org/kubeedge/kubeedge/requests?requestId=160130513
It seems the problem is related with .travis.yml
`Could not parse kubeedge/kubeedge/.travis.yml`

**Comment by m1093782566** [comment]
@u5surf thoughts?

**Comment by u5surf** [comment]
Sorry, I couldn't tried it ,because travis-ci was stacked when I pushed the branch which was commited fixed #371

**Comment by m1093782566** [comment]
No worries, the travis ci error is fixed by #386 now.
