### ISSUE TITLE
The "Edge access cloud" test case does not work

### ISSUE THREAD

**Issue by Aix6** [kubeedge/kubeedge#3853]
**What happened**:
Using the following test case:
https://edgemesh.netlify.app/guide/test-case.html#cross-edge-cloud
When I deploy the "Cloud access edge " test case, they are scheduled correctly. But when I try using the "Edge access cloud" test case, I get the error "telnet: bad address 'tcp-echo-cloud-svc.cloudzone'". 
**What you expected to happen**:
The service on the edge side can access the service on the cloud, and the service can be accessed between edge and edge side.
**How to reproduce it (as minimally and precisely as possible)**:
Refer to [Getting Started](https://edgemesh.netlify.app/guide/getting-started.html) to deploy EdgeMesh, and test the "Cross-Edge-Cloud" case.
**Anything else we need to know?**:

the log from the edge agent:
[INFO] 172.17.0.2:59781 - 2 "AAAA IN tcp-echo-cloud-svc.cloudzone. udp 46 false 512" NXDOMAIN qr,rd,ra 46 0.011376754s
[INFO] 172.17.0.2:45856 - 3 "AAAA IN tcp-echo-cloud-svc.cloudzone.edgezone.svc.cluster.local. udp 73 false 512" SERVFAIL qr,aa,rd 166 0.00017384s
[INFO] 172.17.0.2:55856 - 4 "AAAA IN tcp-echo-cloud-svc.cloudzone.svc.cluster.local. udp 64 false 512" SERVFAIL qr,aa,rd 157 0.000176988s
[INFO] 172.17.0.2:48115 - 5 "AAAA IN tcp-echo-cloud-svc.cloudzone.cluster.local. udp 60 false 512" SERVFAIL qr,aa,rd 153 0.000101509s
[INFO] 172.17.0.2:59521 - 6 "AAAA IN tcp-echo-cloud-svc.cloudzone. udp 46 false 512" NXDOMAIN qr,rd,ra 46 0.012526947s
[INFO] 172.17.0.2:43397 - 7 "AAAA IN tcp-echo-cloud-svc.cloudzone.edgezone.svc.cluster.local. udp 73 false 512" SERVFAIL qr,aa,rd 166 0.000090932s
[INFO] 172.17.0.2:42690 - 8 "AAAA IN tcp-echo-cloud-svc.cloudzone.svc.cluster.local. udp 64 false 512" SERVFAIL qr,aa,rd 157 0.00005627s
[INFO] 172.17.0.2:52825 - 9 "AAAA IN tcp-echo-cloud-svc.cloudzone.cluster.local. udp 60 false 512" SERVFAIL qr,aa,rd 153 0.000055028s
[INFO] 172.17.0.2:58870 - 10 "AAAA IN tcp-echo-cloud-svc.cloudzone. udp 46 false 512" NXDOMAIN qr,rd,ra 46 0.010677519s
[INFO] 172.17.0.2:49946 - 11 "AAAA IN tcp-echo-cloud-svc.cloudzone.edgezone.svc.cluster.local. udp 73 false 512" SERVFAIL qr,aa,rd 166 0.000089105s
[INFO] 172.17.0.2:48067 - 12 "AAAA IN tcp-echo-cloud-svc.cloudzone.svc.cluster.local. udp 64 false 512" SERVFAIL qr,aa,rd 157 0.000129666s
[INFO] 172.17.0.2:44724 - 13 "AAAA IN tcp-echo-cloud-svc.cloudzone.cluster.local. udp 60 false 512" SERVFAIL qr,aa,rd 153 0.00009314s
[INFO] 172.17.0.2:55959 - 14 "A IN tcp-echo-cloud-svc.cloudzone. udp 46 false 512" NXDOMAIN qr,rd,ra 46 0.013949858s
[INFO] 172.17.0.2:38798 - 15 "A IN tcp-echo-cloud-svc.cloudzone.edgezone.svc.cluster.local. udp 73 false 512" SERVFAIL qr,aa,rd 166 0.000161544s
[INFO] 172.17.0.2:59545 - 16 "A IN tcp-echo-cloud-svc.cloudzone.svc.cluster.local. udp 64 false 512" SERVFAIL qr,aa,rd 157 0.000137076s
[INFO] 172.17.0.2:41051 - 17 "A IN tcp-echo-cloud-svc.cloudzone.cluster.local. udp 60 false 512" SERVFAIL qr,aa,rd 153 0.000135414s
[INFO] 172.17.0.2:44841 - 18 "A IN tcp-echo-cloud-svc.cloudzone. udp 46 false 512" NXDOMAIN qr,rd,ra 46 0.010543393s
[INFO] 172.17.0.2:57659 - 19 "A IN tcp-echo-cloud-svc.cloudzone.edgezone.svc.cluster.local. udp 73 false 512" SERVFAIL qr,aa,rd 166 0.000086273s
[INFO] 172.17.0.2:56533 - 20 "A IN tcp-echo-cloud-svc.cloudzone.svc.cluster.local. udp 64 false 512" SERVFAIL qr,aa,rd 157 0.000078826s
[INFO] 172.17.0.2:48386 - 21 "A IN tcp-echo-cloud-svc.cloudzone.cluster.local. udp 60 false 512" SERVFAIL qr,aa,rd 153 0.00006085s
[INFO] 172.17.0.2:42190 - 22 "A IN tcp-echo-cloud-svc.cloudzone. udp 46 false 512" NXDOMAIN qr,rd,ra 46 0.015018106s
[INFO] 172.17.0.2:36478 - 23 "A IN tcp-echo-cloud-svc.cloudzone.edgezone.svc.cluster.local. udp 73 false 512" SERVFAIL qr,aa,rd 166 0.00006208s
[INFO] 172.17.0.2:39979 - 24 "A IN tcp-echo-cloud-svc.cloudzone.svc.cluster.local. udp 64 false 512" SERVFAIL qr,aa,rd 157 0.000035293s
[INFO] 172.17.0.2:33445 - 25 "A IN tcp-echo-cloud-svc.cloudzone.cluster.local. udp 60 false 512" SERVFAIL qr,aa,rd 153 0.000033415s

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.7.2
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`): virtual machine
  - OS (e.g. `cat /etc/os-release`): ubuntu 18.0.4 
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): 1.7.2
  - Hardware configuration (e.g. `lscpu`): virtual machine
  - OS (e.g. `cat /etc/os-release`): ubuntu 18.0.4 
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by abhinavjha126** [comment]
@Aix6 Can u please let me know how you achieved this test case successfully....i am also getting same error

**Comment by Aix6** [comment]
> @Aix6 Can u please let me know how you completed this test case successfully....i am also getting same error

View the agent log. In my case, the ClusterRole  have no "list" rule in apiGroup "namespaces".

**Comment by jjj960** [comment]
> > @Aix6 Can u please let me know how you completed this test case successfully....i am also getting same error
> 
> View the agent log. In my case, the ClusterRole have no "list" rule in apiGroup "namespaces".

Can you say more in detail, I do not quite understand.

**Comment by kinglong08** [comment]
我遇到了相同情况，希望大佬可以详细描述一下解决过程

**Comment by Piwriw** [comment]
> 我遇到了相同情况，希望大佬可以详细描述一下解决过程
你可以详细的描述一下你的安装测试过程吗？

**Comment by walking98** [comment]
I get this error:
# telnet tcp-echo-cloud-svc.cloudzone 2701
telnet: can't connect to remote host (10.233.52.244): Connection refused

edgemesh dns has resolved the svc, but the host refused to connect, why ?

**Comment by walking98** [comment]
> I get this error:
> 
> $ telnet tcp-echo-cloud-svc.cloudzone 2701
> 
> telnet: can't connect to remote host (10.233.52.244): Connection refused
> 
> edgemesh dns has resolved the svc, but the host refused to connect, why ?

![image](https://github.com/kubeedge/kubeedge/assets/19318111/f3a2dcb3-5766-4aa7-b4ba-bc24201699c8)
Got reason for my case, there are two useless pods keep terminating! it works after I force delete them.
