### ISSUE TITLE
no error when run `keadm beta join` failed

### ISSUE THREAD

**Issue by zirain** [kubeedge/kubeedge#3874]
**What happened**:

no error report when run ` /usr/local/bin/keadm beta join --token= --cloudcore-ipport=x.x.x.x:8080` failed

```console
I0525 16:04:07.755483   32452 command.go:849] 1. Check KubeEdge edgecore process status
I0525 16:04:07.762016   32452 command.go:849] 2. Check if the management directory is clean
F0525 16:04:07.762071   32452 joinbeta.go:91] The management directory /etc/kubeedge/ is not clean, please remove it first
```

**What you expected to happen**:

exit code should not be 0 in this scenario。

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by gy95** [comment]
The management directory /etc/kubeedge/ is not clean, please remove it first 
should rm /etc/kubeedge dir

**Comment by zirain** [comment]
I think we should return error when prerun failed, not only run failed.

**Comment by gy95** [comment]
yes, we can refactor function to fix this: `PreRun` to `PreRunE`, `Run` to `RunE`
https://github.com/kubeedge/kubeedge/blob/88f708e75ca1365baacf78c4b9ce95d1b304fe02/keadm/cmd/keadm/app/cmd/edge/joinbeta.go#L67
https://github.com/kubeedge/kubeedge/blob/88f708e75ca1365baacf78c4b9ce95d1b304fe02/keadm/cmd/keadm/app/cmd/edge/joinbeta.go#L92

**Comment by gy95** [comment]
```
_output/local/bin/keadm beta join --cloudcore-ipport 127.0.0.1:10002
I0525 16:34:15.977806  601913 command.go:845] 1. Check KubeEdge edgecore process status
I0525 16:34:15.985817  601913 command.go:845] 2. Check if the management directory is clean
Error: The management directory /etc/kubeedge/ is not clean, please remove it first
execute keadm command failed:  The management directory /etc/kubeedge/ is not clean, please remove it first
```
I just change PreRun to PreRunE, Is this OK? @zirain

**Comment by zirain** [comment]
I think that would be better
