### ISSUE TITLE
Are environment variable for gpu set correctly?

### ISSUE THREAD

**Issue by KingOnTheStar** [kubeedge/kubeedge#39]
Is this a bug report?
I have tried to allocate one gpu to a container by device-plugin, and found the  container get all the gpus every time. At the same time, the allocatable resource number for "nvidia.com/gpu" in database didn't change. 
In file /kubeedge/pkg/edged/containers/container_manager.go, in line 624. When kubeedge gets the opts, I guess kubeedge should set opts.Env to container.Env

**Comment by Baoqiang-Zhang** [comment]
@KingOnTheStar allocatable resource "nvidia.com/gpu" will not change like cpu/mem, kube-scheduler will check if the node's resource is available to schedule.
scheduler will set pod annotation **huawei.com/gpu-decision: '{"container-0":{"nvidia0":263}}'**, and edged will allocate nvidia0 for the container.

**Comment by KingOnTheStar** [comment]
I try to set pod annotation huawei.com/gpu-decision: '{"container-0":{"nvidia0":263}}', but it has no use.
And I find this annotation only has definition but isn't be used anywhere in kubeedge.

**Comment by sids-b** [comment]
ping @KingOnTheStar , the cloud part is available now. Can you check if the problem still exists ? It will be very easy to debug with cloud part.

**Comment by sids-b** [comment]
Closing this issue.
