### ISSUE TITLE
Change model message and its content to protobuf based

### ISSUE THREAD

**Issue by CindyXing** [kubeedge/kubeedge#399]
**What would you like to be added**:

Currently, in beehive framework, model message is defined and serialized/deserialized using json format. With it, for parsing the message, each field index is hardcoded (see https://github.com/kubeedge/beehive/blob/master/pkg/common/util/parse_resource.go). 

**Why is this needed**:
This adds a strong limit on how the message will look like and prevent any future extension. For example, we want to add clusterID info., etc. 

On the other hand, protobuf is extensible with field type/name defined. 
Plus the json serialization/deserialization performance is slower than protobuf

**Comment by kadisi** [comment]
seem feeling. Agree with @CindyXing .

**Comment by kadisi** [comment]
@CindyXing please assign to me

**Comment by kadisi** [comment]
@CindyXing @sids-b  PTAL

**Comment by kadisi** [comment]
@rohitsardesai83  @sids-b @kevin-wangzefeng  @CindyXing there are things we need to be done:

### General
- [ ] [Docs] [add change model message to protobuf message design](https://github.com/kubeedge/kubeedge/pull/891)

### Test in the downstream library

- [ ] [github.com/kadisi/beehive:protobuf_based] change message to protobuf based and deal with message resource hardcode problem  
- [ ] [github.com/kadisi/viaduct:protobuf_based]  no need `translator.NewTran().Encode()`, delete protobuf define.
- [ ] [github.com/kadisi/kubeedge:code_message_protobuf] import new version of beehive and viaduct,  Modify the corresponding code ，Mainly process `Resource` problem。

### after test successfully , submit new pr

- [ ] [github.com/kadisi/beehive:protobuf_based] pull request to  github.com/kubeedge/beehive
- [ ] [github.com/kadisi/viaduct:protobuf_based] pull request to  github.com/kubeedge/viaduct
- [ ] [github.com/kadisi/kubeedge:code_message_protobuf]  pull request to 
 github.com/kubeedge/kubeedge

**Comment by rohitsardesai83** [comment]
> @rohitsardesai83 @sids-b @kevin-wangzefeng @CindyXing there are things we need to be done:
> ### General
> 
>     * [x]  [Docs] [add change model message to protobuf message design](https://github.com/kubeedge/kubeedge/pull/891)
> 
> 
> ### Test in the downstream library
> 
>     * [x]  [[github.com/kadisi/beehive](https://github.com/kadisi/beehive):protobuf_based] change message to protobuf based and deal with message resource hardcode problem
> 
>     * [ ]  [[github.com/kadisi/viaduct](https://github.com/kadisi/viaduct):protobuf_based]  no need `translator.NewTran().Encode()`, delete protobuf define. TBD
> 
>     * [ ]  [[github.com/kadisi/kubeedge](https://github.com/kadisi/kubeedge):code_message_protobuf] import new version of beehive and viaduct,  Modify the corresponding code ，Mainly process `Resource` problem, TBD。
> 
> 
> ### after test successfully , submit new pr
> 
>     * [ ]  [[github.com/kadisi/beehive](https://github.com/kadisi/beehive):protobuf_based] pull request to  github.com/kubeedge/beehive, TBD
> 
>     * [ ]  [[github.com/kadisi/viaduct](https://github.com/kadisi/viaduct):protobuf_based] pull request to  github.com/kubeedge/viaduct,TBD
> 
>     * [ ]  [[github.com/kadisi/kubeedge](https://github.com/kadisi/kubeedge):code_message_protobuf]  pull request to
>       github.com/kubeedge/kubeedge ,TBD

Can we give the beehive completed task ?
