### ISSUE TITLE
Device CRD design/implementation known issues/requires enhancements

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#405]
**What would you like to be added**:
We will have as an umbrella issue for tracking all issues/bugs/possible enhancements required in device CRD v1alpha1 design/implementation.

**Why is this needed**:
For improving device CRD design/implementation

**Comment by rohitsardesai83** [comment]
- [ ] How to handle config map updates if device model is updated e.g some property is deleted.

- [ ] Allow deletion of device model if no devices are referring to it.

- [ ] ??

- [ ] ??

**Comment by rohitsardesai83** [comment]
we can add all known issues like above ? or we create separate sub-issues and link to this as parent issue ?

**Comment by m1093782566** [comment]
I agree.

**Comment by sids-b** [comment]
In general I feel we need to have strong api-validation in place. need to come up with a design.

**Comment by rohitsardesai83** [comment]
we need to identify which issues we can finish in v0.3 timeframe and then take up the rest of the issues in 1.0. @sids-b , please create separate issues for things we can't do in 0.3 release.

**Comment by rohitsardesai83** [comment]
moving this to backlog as we can have minimal validation for 1.0 release. let's create separate issues for each of the items , else its difficult to track them.
for 1.0 , I will add a specific issue for validation.

**Comment by rohitsardesai83** [comment]
Created #631 to target limited set of validations for 1.0.0.

**Comment by chendave** [comment]
#845
