### ISSUE TITLE
Does cloudcore need to be always running, if so, how to set self-start？

### ISSUE THREAD

**Issue by Justin-Young** [kubeedge/kubeedge#4065]
**What happened and what you expected to happen**:
if the cloudcore is not running,  the edge node becomes not ready and edgecore.service reports an error：
`Jul 25 22:28:49 raspberrypi edgecore[391]: E0725 22:28:49.658810     391 ws.go:78] dial websocket error(dial tcp 192.168.1.100:10000: connect: connection refused), response message:
Jul 25 22:28:49 raspberrypi edgecore[391]: E0725 22:28:49.658961     391 websocket.go:90] Init websocket connection failed dial tcp 192.168.1.100:10000: connect: connection refused`
I want to know how to make edge node be ready. In addition, how to use systemctl to run cloudcore and enable self-start?
when I ran the command `systemctl start cloudcore`, I got an error message : `Failed to start cloudcore.service: Unit cloudcore.service not found.`

**How to reproduce it (as minimally and precisely as possible)**:
after keadm join, reboot master or stop cloudcore.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.22.4
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.10.2
- master: ubuntu   edge: raspberrypi
![image](https://user-images.githubusercontent.com/53030626/180808556-e58fd239-9853-4e62-8b59-33e28fb21f6a.png)
![image](https://user-images.githubusercontent.com/53030626/180808929-511425ce-4758-4598-8eab-9a4c516348fd.png)
![image](https://user-images.githubusercontent.com/53030626/180809182-6ffa2db3-449f-40c3-accd-35444c150793.png)

**Comment by wackxu** [comment]
the first question, we need cloudcore running always,  second, In cloud, we prefer to use k8s deployment to deploy cloudcore, so if the cloudcore container exit, the k8s will restart it.

**Comment by Justin-Young** [comment]
> the first question, yes! we need cloudcore running always, second, In cloud, we prefer to use k8s deployment to deploy cloudcore, so if the cloudcore container exit, the k8s will restart it.

Thank you for your reply, I have another question: it seems that k8s does not restart the cloudcore on my machine, why is this, is there something wrong with my cluster configuration? How can I make k8s restart cloudcore automatically？

**Comment by wackxu** [comment]
Do you use k8s deployment to deploy cloudcore?  the restarPolicy in deployment is `always` by default, that means if the container is exitd, the kubelet will restart a new container.

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec

**Comment by DrewZt** [comment]
![image](https://user-images.githubusercontent.com/37324084/181140952-922c5f1a-62b1-4bee-af93-8aba0add19b5.png)
copy to /etc/systemd/system/
then systemctl enable cloudcore

**Comment by Justin-Young** [comment]
Thank you very much! I will use systemd to control cloudcore to start automatically for now, if necessary, I will try to deploy it to k8s.
