### ISSUE TITLE
logManager of edged should not start when docker log not use json-file

### ISSUE THREAD

**Issue by LRaito** [kubeedge/kubeedge#4115]
**What happened**:
when I set docker's log-driver to syslog, edged reports errors always like below:
`
Aug 15 14:50:40 linaro-alip edgecore[390]: E0815 14:50:40.564050     390 remote_runtime.go:580] "ReopenContainerLog from runtime service failed" err="rpc error: code = Unknown desc = docker does not support reopening container log files" containerID="8dd1106bf0bb9f4b58871cd38a3685a8367a1f0346c58469d438b582fa75b06a"
Aug 15 14:50:40 linaro-alip edgecore[390]: E0815 14:50:40.565575     390 container_log_manager.go:244] "Container log doesn't exist, reopen container log failed" err="rpc error: code = Unknown desc = docker does not support reopening container log files" containerID="8dd1106bf0bb9f4b58871cd38a3685a8367a1f0346c58469d438b582fa75b06a" path="/var/log/pods/xxx-rfmz8_5f105b52-cd00-4d3e-ab49-2a2260dc2c45/xxx/4.log"
`

**What you expected to happen**:
support config to close logManager or it will be cloesd automatically

**How to reproduce it (as minimally and precisely as possible)**:
set docker log-driver to syslog, then see the log of edgecore

**Environment**:
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
v1.9.2

**Comment by wackxu** [comment]
ref https://github.com/kubeedge/kubeedge/pull/3885

**Comment by wackxu** [comment]
This has been fixed
/close
