### ISSUE TITLE
Experience with Prometheus, Best way to install?

### ISSUE THREAD

**Issue by tobiasbbb** [kubeedge/kubeedge#4131]
Hello, 

I would like to monitor my cluster using Prometheus and have currently the following setup:

**Current Setup**
- 1 Master Node, Ubuntu 20.04, running on Macbook
- 1 Edge Node, Ubuntu 20.04, Raspberry Pi

Metrics server, kubectl logs and deploying Pods on the Edge Node are working fine.

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: v1.24.4
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): KubeEdge v1.10.0, KubeEdge v1.11.1

I tried to install Prometheus via the community helm chart.
```
helm install stable prometheus-community/kube-prometheus-stack --namespace monitoring --set nodeSelector.nodename=kubeedge-cloud 
```

The problem that occurs during installation is the startup of the 'kube-state-metrics' pod on the edge node. It exits with the following output:
```
docker logs -f e7abc0d137de
I0823 13:43:41.550902       1 server.go:100] Using resources certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
I0823 13:43:41.551271       1 types.go:136] Using all namespace
I0823 13:43:41.551321       1 server.go:122] Metric allow-denylisting: Excluding the following lists that were on denylist: 
W0823 13:43:41.551429       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0823 13:43:41.551459       1 client_config.go:622] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
F0823 13:43:41.552137       1 main.go:65] Failed to run kube-state-metrics: failed to create client: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
I am not sure why it does not find a valid config, also tried to pass the kubeconfig via a flag but the error stays the same.

Is there any example or a best practise about how to install prometheus and KubeEdge? 

Thanks!

**Comment by vincentgoat** [comment]
Hi, @tobiasbbb How's it going? Did you deploy the `prometheus` pod on the edge node?

**Comment by tobiasbbb** [comment]
Hi  @vincentgoat , I deployed ```prometheus```on the cloud node.

**Comment by vincentgoat** [comment]
If so, I think the way deploying `prometheus` is the same with K8s cluster. 
Please check the location of your serviceAccountToken/CA cert file or kubeconfig file.

**Comment by tobiasbbb** [comment]
Thank you for the reply! 
I managed to deploy Prometheus successfully by manually creating the Prometheus Configs and Deployments instead of the Helm Chart.

**Comment by abhinavjha126** [comment]
@tburchardt Can u please share the Promrtheus and Grafana files/ github link for kubeedge
