### ISSUE TITLE
Support OPC-UA Mapper

### ISSUE THREAD

**Issue by venergiac** [kubeedge/kubeedge#416]
**What would you like to be added**: Event Bus for OPC-UA

**Why is this needed**: OPC-UA is a popular standard protocol for industrial sector. As MQTT and ModBUS there are Publisher to convert from OPC-UA to MQTT to Mosquitto (https://github.com/OPCFoundation/UA-.NETStandard/tree/prototyping-mqtt/Mqtt), but we lose performance. Driver for OPC-UA is already available https://github.com/gopcua/opcua.

**Comment by m1093782566** [comment]
@venergiac Thanks for reporting. We do have a plan to support OPC-UA in the near future!

cc @qizha @zhenghaibo1008 @rohitsardesai83 @sids-b

**Comment by sids-b** [comment]
@venergiac , we plan to support OPC-UA as a mapper. Please see devicecrd design https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/device-crd.md and mapper design https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/mapper-design.md

**Comment by m1093782566** [comment]
Yes and I think Driver for OPC-UA https://github.com/gopcua/opcua should be a good repository to learn.

**Comment by venergiac** [comment]
cool !! thanks! I contributed to develop the OPC-UA gateway for my company and I can test the edge on real field, if you want.

below my suggestions

### Specs

OPC-UA can support two way to trigger data **DataChange** and **Polling**. 

On **Polling**, ....it is polling. 

On **DataChange** the client is notified on "data change"; on real case we need to define the **deadband** to avoid to be notified every millisecond by "signal's noise". Normally is about +/- 2%. It means that if the signal doesn't change + or - 2% of the last sample, it will NOT sent. Deadband can be also absolute eg. +/- 10 DegCelsius. Deadbands are not supported by all clients. Deadbands are just a data filter.
![Slide1](https://user-images.githubusercontent.com/9880255/56848627-8df8b200-68eb-11e9-8498-2597d4266e84.png)


The second most important feature is the **Browsing**; Browsing allows to get the list of published measures from OPC-UA Server. Normally, it is used only during configuration and you can skip it in the first release.

OPC-UA supports also **writing**, but due to cybersecurity restriction in the industry is not applied.

**Multiple server connection** is another important feature, but I think we need to scale over multiple containers.

**Discovery server** is a way of OPC-UA to discover server in the same network. We can avoid to implement it in the first release.

Finally, **cybersecurity**: unfortunately all the Encryption and Authentication mechanisms are required from the beginning. 

### Test

- An

 official Demo server is there https://opcfoundation.org/products/view/free-opc-ua-demo-servers or https://www.prosysopc.com/products/opc-ua-simulation-server/
 
- Certified SDK  https://opcfoundation.org/products/view/opc-ua-c-server-development-toolkits-for-windows

- UI client: 

https://github.com/FreeOpcUa/opcua-client-gui (python, open source) or 
![Slide3](https://user-images.githubusercontent.com/9880255/56848648-b84a6f80-68eb-11e9-89e1-52a1712718d8.png)

https://www.prosysopc.com/products/opc-ua-client/ (prosys, commercial)
![Slide2](https://user-images.githubusercontent.com/9880255/56848637-a668cc80-68eb-11e9-9ebe-8b504e918ce6.png)

but a simple client/server based on NodeJS is there https://node-opcua.github.io/
AWS Greengrass and Nodered use it. It supports all features.

Sorry guys very long mail.... Let me know if I can help.

**Comment by sids-b** [comment]
Thanks @venergiac . That's very impresive !!! It would be great if you could contribute in the development of OPC-UA mapper for kubeedge.

**Comment by zongke** [comment]
Ask, when OPCUA go online?

**Comment by dazer-chen** [comment]
hi, guys, How is the opc-ua mapper support going?
