### ISSUE TITLE
imitator.go:224] failed to unmarshal message content to unstructured obj: Object 'Kind' is missing

### ISSUE THREAD

**Issue by xiezg** [kubeedge/kubeedge#4164]
**What happened**:
E0906 15:47:41.951356   22688 imitator.go:224] failed to unmarshal message content to unstructured obj: Object 'Kind' is missing in '{"metadata":{"name":"172-16-244-175.aibee.cn","creationTimestamp":null,"labels":{"kubernetes.io/arch":"amd64","kubernetes.io/hostname":"172-16-244-175.aibee.cn","kubernetes.io/os":"linux","node-role.kubernetes.io/agent":"","node-role.kubernetes.io/edge":""}},"spec":{},"status":{"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"","osImage":"","containerRuntimeVersion":"","kubeletVersion":"","kubeProxyVersion":"","operatingSystem":"","architecture":""}}}'
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
必现
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.12
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 
- <details><summary>Cloud nodes Environment:</summary>
  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):master branch :commit 2599118b2ef919b3a91cf7bbbbbc4d508c631ea8
  
- Hardware configuration (e.g. `lscpu`):
  Architecture:        x86_64
  CPU op-mode(s):      32-bit, 64-bit
  - OS (e.g. `cat /etc/os-release`):VERSION="18.04.1 LTS (Bionic Beaver)"
  - Kernel (e.g. `uname -a`):4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  - Go version (e.g. `go version`): go version go1.19 linux/amd64
  - Others:
  - 

  </details>

**Comment by RyanZhaoXB** [comment]
hello. what operation do you take before this error happened? could you please provide more information?

**Comment by da-sha** [comment]
我在"Ubuntu 20.04.4 LTS也存在这样的问题，
怎么办？
> I1107 09:42:03.155684   13446 kubelet_node_status.go:69] "Attempting to register node" node="lilei-vm"
E1107 09:42:03.167800   13446 imitator.go:235] failed to unmarshal message content to unstructured obj: Object 'Kind' is missing in '{"metadata":{"name":"lilei-vm","creationTimestamp":null,"labels":{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"lilei-vm","kubernetes.io/os":"linux","node-role.kubernetes.io/agent":"","node-role.kubernetes.io/edge":""},"annotations":{"volumes.kubernetes.io/controller-managed-attach-detach":"true"}},"spec":{},"status":{"capacity":{"cpu":"2","ephemeral-storage":"19688064Ki","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"3994704Ki","pods":"110"},"allocatable":{"cpu":"2","ephemeral-storage":"18144519753","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"3892304Ki","pods":"110"},"conditions":[{"type":"MemoryPressure","status":"False","lastHeartbeatTime":"2022-11-07T09:42:03Z","lastTransitionTime":"2022-11-07T09:42:03Z","reason":"KubeletHasSufficientMemory","message":"kubelet has sufficient memory available"},{"type":"DiskPressure","status":"False","lastHeartbeatTime":"2022-11-07T09:42:03Z","lastTransitionTime":"2022-11-07T09:42:03Z","reason":"KubeletHasNoDiskPressure","message":"kubelet has no disk pressure"},{"type":"PIDPressure","status":"False","lastHeartbeatTime":"2022-11-07T09:42:03Z","lastTransitionTime":"2022-11-07T09:42:03Z","reason":"KubeletHasSufficientPID","message":"kubelet has sufficient PID available"},{"type":"Ready","status":"False","lastHeartbeatTime":"2022-11-07T09:42:03Z","lastTransitionTime":"2022-11-07T09:42:03Z","reason":"KubeletNotReady","message":"PLEG is not healthy: pleg has yet to be successful"}],"addresses":[{"type":"InternalIP","address":"192.168.111.128"},{"type":"Hostname","address":"lilei-vm"}],"daemonEndpoints":{"kubeletEndpoint":{"Port":10250}},"nodeInfo":{"machineID":"eac89b74f70d432abc5639bc8163ac5e","systemUUID":"69d34d56-1f88-0f0a-4f15-399d6238ae3c","bootID":"f3fe6f27-1108-4263-ad62-74a16fab15ab","kernelVersion":"5.4.0-131-generic","osImage":"Ubuntu 20.04.4 LTS","containerRuntimeVersion":"docker://20.10.17","kubeletVersion":"v1.22.6-kubeedge-v1.12.0","kubeProxyVersion":"v0.0.0-master+$Format:%H$","operatingSystem":"linux","architecture":"amd64"},"images":[{"names":["sub-center-monitor:0.1"],"sizeBytes":1016184143},{"names":["province-center-monitor:0.1"],"sizeBytes":957447053},{"names":["hub-lande.ruitong369.com:30443/plateform/mpush-alloc@sha256:864ef62d94c554348b3aef7622d672c0e4aa5e0739d14f0a55be8309eadf491c","hub.ruitong369.com:5443/plateform/mpush-alloc@sha256:864ef62d94c554348b3aef7622d672c0e4aa5e0739d14f0a55be8309eadf491c","hub-lande.ruitong369.com:30443/plateform/mpush-alloc:0.8.2.3","hub-zns.ruitong369.com:5443/plateform/mpush-alloc:0.8.2.3","hub.ruitong369.com:30443/plateform/mpush-alloc:0.8.2.3"],"sizeBytes":530466614},{"names":["hub-video.ruitong369.com:30443/plateform/mpush@sha256:5cbc1a5ea39a0fa1b826ad0f1e77b1fac0c0732f12733f1f58a5831cb9c91d80","hub-video.ruitong369.com:30443/plateform/mpush:0.8.1.2"],"sizeBytes":530053262},{"names":["tomcat9:0.1"],"sizeBytes":502327455},{"names":["hub.ruitong369.com:30443/mysql@sha256:ca4a69d21836099c0aa2b4bb49ee32d2f1e2055576105ea2930206387a9e7291","hub.ruitong369.com:30443/mysql:5.7.33"],"sizeBytes":448699122},{"names":["kubeedge/installation-package@sha256:18184d21dbb5a12b7d070c40d12c55e8ac7c61b5a22563c3c808db25f10d5112","kubeedge/installation-package:v1.12.0"],"sizeBytes":201075498},{"names":["hub.ruitong369.com:30443/nginx@sha256:9dc6c65944f0970ffd6ffc3c80e4c4d5e01e683e8acf75a2b4ee0350fb62fc76","hub.ruitong369.com:30443/nginx:1.20"],"sizeBytes":133108138},{"names":["hub.ruitong369.com:30443/debian@sha256:a5edb9fa5b2a8d6665ed911466827734795ef10d2b3985a46b7e9c7f0161a6b3","hub.ruitong369.com:30443/debian:buster"],"sizeBytes":114075536},{"names":["swr.cn-east-2.myhuaweicloud.com/kuboard-dependency/metrics-server@sha256:56eee05d743d86466f6e2d9dbe34904229e2ac263774cccb367e8ec8f7a2064a","swr.cn-east-2.myhuaweicloud.com/kuboard-dependency/metrics-server:v0.5.0"],"sizeBytes":63517663},{"names":["hub.ruitong369.com:30443/ubuntu@sha256:a7fa45fb43d471f4e66c5b53b1b9b0e02f7f1d37a889a41bbe1601fac70cb54e","hub.ruitong369.com:30443/ubuntu:18.04"],"sizeBytes":63252300},{"names":["eclipse-mosquitto@sha256:67bd20abe9644b6cde7d98c732ade04bae55775bdaa9ee22adb46d1abbb253e2","eclipse-mosquitto:1.6.15"],"sizeBytes":11564549},{"names":["kubeedge/pause@sha256:d22591b61e9c2b52aecbf07106d5db313c4f178e404d660b32517b18fcbf0144","kubeedge/pause:3.1"],"sizeBytes":742472}]}}'
I1107 09:42:03.181810   13446 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv6
I1107 09:42:03.181863   13446 status_manager.go:158] "Starting to sync pod status with apiserver"
I1107 09:42:03.181879   13446 kubelet.go:1807] "Starting kubelet main sync loop"
E1107 09:42:03.181918   13446 kubelet.go:1831] "Skipping pod synchronization" err="PLEG is not healthy: pleg has yet to be successful"
E1107 09:42:07.916363   13446 ws.go:78] dial websocket error(tls: first record does not look like a TLS handshake), response message:

**Comment by da-sha** [comment]
我也遇到了同样的问题，后来经过调查发现：
默认cloudcore会被任意调度的一个节点上，并且开hostport，这个导致可能与你期望的server.advertiseAddress服务器不一致，导致他连接不上，我修改调度策略，指定调度到期望节点后，一切恢复正常了！
希望对你有用！

**Comment by huapox** [comment]
+1

**Comment by huapox** [comment]
> 我也遇到了同样的问题，后来经过调查发现： 默认cloudcore会被任意调度的一个节点上，并且开hostport，这个导致可能与你期望的server.advertiseAddress服务器不一致，导致他连接不上，我修改调度策略，指定调度到期望节点后，一切恢复正常了！ 希望对你有用！

---
这个是正确的

**Comment by huapox** [comment]
kedge v1.13.0 with k3s-1.22.17

```bash
E0201 16:24:30.454946      82 imitator.go:235] failed to unmarshal message content to unstructured obj: Object 'Kind' is missing in '{"metadata":{"name":"ten-vm1-172-70-0-14-81fe9.kedge","creationTimestamp":null,"labels":{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","customize.author":"sam11","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"ten-vm1-172-70-0-14-81fe9.kedge","kubernetes.io/os":"linux","node-role.kubernetes.io/agent":"","node-role.kubernetes.io/edge":""},"annotations":{"volumes.kubernetes.io/controller-managed-attach-detach":"true"}},"spec":{},"status":{"capacity":{"cpu":"1","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"1877060Ki","pods":"110"},"allocatable":{"cpu":"1","hugepages-1Gi":"0","hugepages-2Mi":"0","memory":"1774660Ki","pods":"110"},"conditions":[{"type":"MemoryPressure","status":"False","lastHeartbeatTime":"2023-02-01T16:24:30Z","lastTransitionTime":"2023-02-01T16:24:30Z","reason":"KubeletHasSufficientMemory","message":"kubelet has sufficient memory available"},{"type":"DiskPressure","status":"False","lastHeartbeatTime":"2023-02-01T16:24:30Z","lastTransitionTime":"2023-02-01T16:24:30Z","reason":"KubeletHasNoDiskPressure","message":"kubelet has no disk pressure"},{"type":"PIDPressure","status":"False","lastHeartbeatTime":"2023-02-01T16:24:30Z","lastTransitionTime":"2023-02-01T16:24:30Z","reason":"KubeletHasSufficientPID","message":"kubelet has sufficient PID available"},{"type":"Ready","status":"False","lastHeartbeatTime":"2023-02-01T16:24:30Z","lastTransitionTime":"2023-02-01T16:24:30Z","reason":"KubeletNotReady","message":"[container runtime status check may not have completed yet, missing node capacity for resources: ephemeral-storage]"}],"addresses":[{"type":"InternalIP","address":"172.0.0.1"},{"type":"Hostname","address":"ten-vm1-172-70-0-14-81fe9.kedge"}],"daemonEndpoints":{"kubeletEndpoint":{"Port":10350}},"nodeInfo":{"machineID":"61a2db38159943f4932a5ff62e33b01b","systemUUID":"07ece4dc-336f-456f-8b5d-2fb03acecf4b","bootID":"c52e5ae3-9c94-434f-b10d-60ea2c8dd87a","kernelVersion":"4.15.0-118-generic","osImage":"Ubuntu 20.04.5 LTS","containerRuntimeVersion":"containerd://1.6.15","kubeletVersion":"v1.23.15-kubeedge-v1.13.0","kubeProxyVersion":"v0.0.0-master+$Format:%H$","operatingSystem":"linux","architecture":"amd64"},"images":[{"names":["infrasync/kubeedge-edgemesh-agent@sha256:bba9441e7293749714a63918afa1a282c895ff21e4942c375a1292363e01cc6a","infrasync/kubeedge-edgemesh-agent:v1.13.0"],"sizeBytes":23944989},{"names":["infrasync/alpine@sha256:a875c6f8216ca12a4dbb312162d877f7fd90539f0c6c8a8dd13f6150f292648c","infrasync/alpine:3.14.8"],"sizeBytes":2830033},{"names":["infrasync/rancher-pause@sha256:554175924e0fe5a7870dca31291a735db81922118a74ae026a91a2eaa1ae42e0","infrasync/rancher-pause:3.2"],"sizeBytes":298573}]}}'
```
