### ISSUE TITLE
Restarting Edge Node

### ISSUE THREAD

**Issue by bensch98** [kubeedge/kubeedge#4169]
I have a general purpose question:
If I need to restart my Edge Node for whatever reason, what is the best practice to automatically reconnect it to the cluster after the reboot. So far I was thinking of running a Linux Service that will run `keadm join` again to join the cluster. Is there a best practice for this case. I assume this is sth almost everybody has to deal with.

**Comment by vincentgoat** [comment]
Hi @bensch98 ,  after your first `keadm join`, I think edgecore.service will restart and reconnect to the cluster automatically when rebooting.
Is this not working on your machine?

edgecore.service:
```
[Unit]
Description=edgecore.service

[Service]
Type=simple
ExecStart=/usr/local/bin/edgecore
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**Comment by bensch98** [comment]
Hi @vincentgoat,
I just upgraded to Kubeedge 1.11.1. The edge node reconnects, and the pods also restart, however the information of the pods status is updated on the master node only after like 5min. I tracked the pods running in my cluster via `watch kubectl get pods -A` while rebooting my edge node. That's also why I thought before, that it doesn't work at all, cause I didnt't wait long enough. Is there a way to make this faster by setting the frequency the edge node communicates with the master node?

**Comment by vincentgoat** [comment]
Hi @bensch98,
I tried on my local edge node, after the edge node restart, the information of the pods status is updated on the master node immediately. Can you check if your edge node reboot process may take a delay?

**Comment by bensch98** [comment]
Hi @vincentgoat,
I tested it now extensively and it works like a charm after installing edgemesh server and agent. Didn't know that this is mandatory. Until kubeedge v1.6 I never deployed it and everything was immediately deployed nonetheless.
The behavior of my cluster is now probably as it should be. When rebooting, the edge node almost immediately reconnects via edgecore.service and all pods are scheduled again. When disconnecting the edge node, its pods keep running and are getting synced once the connection to the master nodes is established again.
My services on the edge node are available very fast. The nodes status is getting synced after approx. 30s ~ 60s. I guess this is the default interval how the edgenode syncs with the control-plane.
