### ISSUE TITLE
网页的文档还更新么

### ISSUE THREAD

**Issue by mahmut-Abi** [kubeedge/kubeedge#4216]
![image](https://user-images.githubusercontent.com/96514873/191652526-648b6983-bf1e-4e53-99e0-0368977850c0.png)
这都没有新版本的文档

**Comment by ABottleofWater7** [comment]
+1 I need the latest docs!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
