### ISSUE TITLE
why edgehub and cloudhub do not use grpc?

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#425]
**What would you like to be added**:
if found that edgehub and cloudhub use websocket, but why not choose grpc?

**Why is this needed**:

**Comment by tedli** [comment]
@kadisi

**Comment by sids-b** [comment]
Thanks @kadisi . One of our contributor @kexun is proposing QUIC- a UDP based protocol for evaluation/enhancement of websocket. @CindyXing has proposed to convert beehive message to protobuf #399 . We would like to hear your thoughts on grpc.

**Comment by kadisi** [comment]
@sids-b @tedli  thank you, please let me have a look first

**Comment by rohitsardesai83** [comment]
A suggested read : https://www.infoq.com/articles/websocket-and-http2-coexist
