### ISSUE TITLE
How to use nodeLabels in edgecore config

### ISSUE THREAD

**Issue by mretallack** [kubeedge/kubeedge#4280]
**What happened and what you expected to happen**:

I have added nodeLabels to the edgecore config:

    edged:

      nodeLabels:
        nodetype: edgeDevice
           
However, when I list labels using:

   kubectl get nodes --show-labels

I cannot see the nodetype label, have I added nodeLabels into the correct bit?

**How to reproduce it (as minimally and precisely as possible)**:

Add nodeLabels into edgecore config

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

Latest from github head.

**Comment by vincentgoat** [comment]
I found `nodeLabels` won't convert to `kubeletflags` in function `ConvertConfigEdgedFlagToConfigKubeletFlag`.
cc @Shelley-BaoYue

**Comment by Shelley-BaoYue** [comment]
Exactly. I think I have missed nodelabels convertion. I'll fix it right away
