### ISSUE TITLE
DTWorker interface has PreDeal /Deal /PostDeal methods which have empty implementations.

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#43]
DTWorker interface (pkg/devicetwin/dtmanager/dtworker.go ) has PreDeal /Deal /PostDeal methods. 
The below go files have an empty implementation of these interface methods.

- pkg\devicetwin\dtmanager\device.go
- pkg\devicetwin\dtmanager\communicate.go
- pkg\devicetwin\dtmanager\membership.go
- pkg\devicetwin\dtmanager\twin.go

Are these methods required or can be removed ?

**Comment by m1093782566** [comment]
Can you provide the links?

**Comment by rohitsardesai83** [comment]
https://github.com/kubeedge/kubeedge/blob/master/pkg/devicetwin/dtmanager/dtworker.go

https://github.com/kubeedge/kubeedge/blob/master/pkg/devicetwin/dtmanager/communicate.go

https://github.com/kubeedge/kubeedge/blob/master/pkg/devicetwin/dtmanager/membership.go

https://github.com/kubeedge/kubeedge/blob/master/pkg/devicetwin/dtmanager/twin.go

**Comment by m1093782566** [comment]
Is there any chance to remove the unused codes?
