### ISSUE TITLE
Where is the souce code of kubeedge/pause:3.1?

### ISSUE THREAD

**Issue by wyanping** [kubeedge/kubeedge#4303]
I want to  build image which is kubeedge/pause:3.1, but I don't find the souce code and dockerfile about it. Can you help me?

**Comment by wackxu** [comment]
you can pull it from the dockerhub

**Comment by wyanping** [comment]
> you can pull it from the dockerhub

Yes, but I want to konw the souce code about it in order to compare with k8s's pause. Thank you.

**Comment by wackxu** [comment]
> > you can pull it from the dockerhub
> 
> Yes, but I want to konw the souce code about it in order to compare with k8s's pause. Thank you.
 

we do not change the source code and just rename the image tag and push it to the docker hub

**Comment by wackxu** [comment]
please see https://github.com/kubeedge/kubeedge/pull/3114

**Comment by wyanping** [comment]
> please see #3114
thanks for your help.
