### ISSUE TITLE
can edge node auto register into k8s cluster ?

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#431]
**What would you like to be added**:
in your install usage: https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/usage.md#run-kubeedge

when we run edge node, we first create k8s node use `kubectl apply -f node.json`

can we skip this step, use edge node auto register to cloud?

**Why is this needed**:

This will make installation easier

**Comment by m1093782566** [comment]
xref: #419

**Comment by sids-b** [comment]
@kadisi , I dont think it would be correct if edge_core directly connects to k8s master. We are working on kubeedge installer which will create cloud and edge in 2 simple commands

**Comment by CindyXing** [comment]
Correct. Different from nodes at data center, we assume customers need to manually register the edge node from cloud. This includes configuring the relevant info. (e.g. node label, network config. etc.). Also considering the network reliability between edge and cloud, registering the edge nodes at cloud first and then update the node status is a more general solution.

**Comment by kadisi** [comment]
@sids-b @CindyXing  That sounds reasonable， thank you

**Comment by sids-b** [comment]
@kadisi , we have released the installed with v0.3.0-beta.0 , please try it out :)
