### ISSUE TITLE
docker images有没有国内的镜像加速

### ISSUE THREAD

**Issue by SakuraWh** [kubeedge/kubeedge#4343]
**问题：docker images有没有国内的镜像加速仓库**:
**Question：Does docker images have a Chinese mirror acceleration hub?**

常用的阿里云华为云好像没有kubeedge的镜像，直接从docker hub上pull有一点点慢
The commonly used Alibaba Cloud and Huawei Cloud do not seem to have kubeedge images, so pulling directly from the docker hub is a little slow.

**Comment by wuxs** [comment]
可以试试这个 https://dockerproxy.com/docs

**Comment by SakuraWh** [comment]
> 

谢谢

**Comment by SakuraWh** [comment]
谢谢

**Comment by SakuraWh** [comment]
> 可以试试这个 https://dockerproxy.com/docs

谢谢
