### ISSUE TITLE
Please calculate SHA512 checksum of KubeEdge tgz files and release it along with every release

### ISSUE THREAD

**Issue by samy2019** [kubeedge/kubeedge#437]
**What would you like to be added**:
With every software/tool release, it is mandatory to generate checksum and release it as well with the release artifacts.
It should be a separate text file, just containing the generated checksum string.
Either SHA256 or SHA512 checksum can be generated.
It is as simple as below sample 

$ sha256sum node.json
224a9293996c248d41647e9862674d8855cf82cdda4d9c4a7c759ab69e6a2b28  node.json
$ 
$ sha512sum node.json
6f4d54b538dc2c1c21f39d47b9057f0bf556773d2df2167fa1edbc81fd58d349ca231e902fc8e026c7a4cfe04b62542fbaca0e1f197144cb1efb63ce71432679  node.json
$ 

Just take the response string and put in a text file. 
Please do it for all the artifacts required to be released.
Name it checksum_<artifactname>.txt and along with tgz's release it.

It should immediately started from next release

**Why is this needed**:
It is used to verify if the download of the artifacts were fully complete or partial.

**Comment by sids-b** [comment]
Thanks @samy2019 , we have release the checkum files along with v0.3.0-beta-0. Please check it out :)
