### ISSUE TITLE
Hello, I want to use keadm to deploy kubeedge in an offline environment. Do you have any related documents?

### ISSUE THREAD

**Issue by WVenus** [kubeedge/kubeedge#4390]
**What happened and what you expected to happen**:
Hello, I want to use keadm to deploy kubeedge in an offline environment. Do you have any related documents?

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/39941928/200571979-8a038b97-5b0b-40cd-a247-7d5bb2b60c99.png)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23.4
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.12.1

**Comment by vincentgoat** [comment]
Same issue with https://github.com/kubeedge/kubeedge/issues/4380
