### ISSUE TITLE
docs: Improve README documentation

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#441]
**What would you like to be added**:
Suggested improvements in documentation  : 

- [ ] Move https://github.com/kubeedge/kubeedge#roadmap below https://github.com/kubeedge/kubeedge#usage

- [ ] Introduce a section in the https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/usage.md#usage which can show how to download a kubeedge release ( e.g v0.2) and run.
Users might just want to try running kubeedge without building from source.

- [ ] Running the cloud [ https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/usage.md#run-cloud ] should first show how to run as a binary and then how to run using K8S deployments. Similarly for edge.

- [ ]  Explicitly specify to run edge component as root user #440 

**Why is this needed**:
To make it easier for community to get started with KubeEdge.

**Comment by rohitsardesai83** [comment]
Suggestions are welcome , we can create separate issues for each of the items and track them.

**Comment by anvithks** [comment]
@rohitsardesai83 since the documentation section is still undergoing overhauls I would not recommend this being a Good First Issue.

**Comment by rohitsardesai83** [comment]
> @rohitsardesai83 since the documentation section is still undergoing overhauls I would not recommend this being a Good First Issue.

thanks anvith.

**Comment by rohitsardesai83** [comment]
Opened #495 to track item 2.
