### ISSUE TITLE
to get edge certificate from the cloudcore, error: Get "https://10.121.134.115:10002/edge.crt": x509: cannot validate certificate for 10.121.134.11 5 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by zmk1173411140** [kubeedge/kubeedge#4418]
I1117 14:53:34.745668   42621 client.go:91] edge-hub-cli subscribe topic to SYS/dis/upload_records
I1117 14:53:34.745853   42621 client.go:91] edge-hub-cli subscribe topic to +/user/#
I1117 14:53:34.745929   42621 client.go:99] list edge-hub-cli-topics status, no record, skip sync
F1117 14:53:34.766874   42621 certmanager.go:92] Error: failed to get edge certificate from the cloudcore, error: Get "https://10.121.134.115:10002/edge.crt": x509: cannot validate certificate for 10.121.134.11
5 because it doesn't contain any IP SANs

希望能告知 cloudcore证书生成的依据，以及他的加载过程（从什么文件夹下加载，什么时候生成，pod部署）
为什么边端总是出错
这个问题困扰我很久了，

如果是用kuadm部署的话这个证书更具哪个文件生成，
生成的结果是什么，token嘛？

拜托大佬讲的详细一点

**Comment by wackxu** [comment]
If you do not specify certificate for cloudcore, it will self-generated certificate using the adviterseAddress. The generated certificate will be stored in the configmap and used for all cloudcore instance.

**Comment by wackxu** [comment]
The problem for you is that you do not specify adviterseAddress correctlly, so  validate certificate failed

**Comment by wackxu** [comment]
please refer https://github.com/kubeedge/website/pull/272
