### ISSUE TITLE
docs: Received 404 when Setup or any other link is clicked in getting-started.md

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#442]
**What happened**:
Go to https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/getting-started.md
Click on any of the links e.g Setup . Page is not found ( 404  error )

**What you expected to happen**:
The setup page opens up correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Go to https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/getting-started.md
Click on any of the links e.g Setup .

**Anything else we need to know?**:
NA

**Comment by sids-b** [comment]
This issue is getting discussed here #288 .
