### ISSUE TITLE
support `kubectl attach` in KubeEdge

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#4424]
**What would you like to be added/modified**:

Support `kubectl attach` in KubeEdge

**Why is this needed**:

We have already support `kubectl logs/exec`, we want to add support `kubectl attach` in future version. Users can attach to the main process running in the container.

**Comment by Shelley-BaoYue** [comment]
welcome 😃

**Comment by Shelley-BaoYue** [comment]
Hi, @carlory , how's it going so far?  if there are any progress, welcome to keep communication here plz.

**Comment by Shelley-BaoYue** [comment]
Hi, @carlory, is there any progress with `kubectl attach`?

**Comment by Shelley-BaoYue** [comment]
Proposal of kubectl exec/attach/logs: #4690 
Also I have completed part of code of kubectl attach, including the whole framework. There are some functions need to be completed. Anyone interested can refer to my commit or continue the work beased on my commit:  https://github.com/Shelley-BaoYue/kubeedge/commit/7cee5b0a6bb808575cbe4885a5d65ec2c0dbe717

**Comment by wenchajun** [comment]
I am very interested in this and can assign it to me

**Comment by zhengwjie** [comment]
I am very interested in this but I am a novice, how to start it?

**Comment by Shelley-BaoYue** [comment]
> I am very interested in this and can assign it to me

Welcome！ Feel free to talk to me if there are any questions. 😄

**Comment by wenchajun** [comment]
@Shelley-BaoYue Hi, I have a question, is this part of the feature that I added after the pr merge you submitted?

**Comment by wenchajun** [comment]
> @Shelley-BaoYue Hi, I have a question, is this part of the feature that I added after the pr merge you submitted?

https://github.com/Shelley-BaoYue/kubeedge/commit/7cee5b0a6bb808575cbe4885a5d65ec2c0dbe717
My understanding is that I am developing based on that commit, so should I wait for that commit to be committed and merged?

**Comment by Shelley-BaoYue** [comment]
https://github.com/kubeedge/kubeedge/pull/4690 is the pr of proposal. You need to create another pr with the code implementation.
You can cherry-pick my commit(https://github.com/Shelley-BaoYue/kubeedge/commit/7cee5b0a6bb808575cbe4885a5d65ec2c0dbe717 )  and continue coding with your commit. Therefore, the pr you pushed can include commits of both of us. 
Of course, my commit is just a reference, you can also write it all yourself..

**Comment by Shelley-BaoYue** [comment]
> > @Shelley-BaoYue Hi, I have a question, is this part of the feature that I added after the pr merge you submitted?
> 
> [Shelley-BaoYue@7cee5b0](https://github.com/Shelley-BaoYue/kubeedge/commit/7cee5b0a6bb808575cbe4885a5d65ec2c0dbe717) My understanding is that I am developing based on that commit, so should I wait for that commit to be committed and merged?

No, just cherry-pick it.

**Comment by wenchajun** [comment]
> 

I got it, thanks.

**Comment by Shelley-BaoYue** [comment]
@wenchajun How is everything going？If you have any progress or questions, please feel free to contact me. 😃

**Comment by wenchajun** [comment]
> @wenchajun How is everything going？If you have any progress or questions, please feel free to contact me. 😃

I have written the code as requested and it is currently in testing and seems to be a bit problematic.

**Comment by Shelley-BaoYue** [comment]
It sounds great! Feel free to contact me when you need help, or you can submit some code and review it together.

**Comment by wenchajun** [comment]
> It sounds great! Feel free to contact me when you need help, or you can submit some code and review it together.

Ok, I will submit the code in the next day or two, please advise.
