### ISSUE TITLE
fuzz issue

### ISSUE THREAD

**Issue by gy95** [kubeedge/kubeedge#4426]
**What happened**:

**What you expected to happen**:
https://github.com/kubeedge/kubeedge/actions/runs/3502764411/jobs/5867374097
```
Running go-fuzz -tags gofuzz -func FuzzdealTwinActions -o fuzz_deal_twin_actions.a github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/syscall.go:83:28: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/syscall_linux.go:2256:21: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/syscall_unix.go:118:19: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/sysvshm_unix.go:33:19: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
2022/11/19 08:34:18 failed to build packages:exit status 2
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by vincentgoat** [comment]
Related issue: https://github.com/google/oss-fuzz/issues/9022

**Comment by vincentgoat** [comment]
We also can bump K8s version and golang version to fix this issue. cc @gy95 @fisherxu

**Comment by AdamKorcz** [comment]
Fixed in https://github.com/google/oss-fuzz/pull/9067
