### ISSUE TITLE
docs: Incorrect instruction to build edge docker image

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#443]
**What happened**:
The command `make edgeimage` failed if we follow the instructions here : https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/README.md#deploy-the-edge-part-into-a-k8s-cluster

**What you expected to happen**:
The edge image to be built successfully.

**How to reproduce it (as minimally and precisely as possible)**:
```sh
/go/src/github.com/kubeedge/kubeedge$ sudo make edgeimage
docker build -t kubeedge/edgecore:v0.2.1-94-gd2ebe11 -f build/edge/Dockerfile .
Sending build context to Docker daemon  141.1MB
Step 1/16 : ARG BUILD_FROM=golang:1.12-alpine3.9
Step 2/16 : ARG RUN_FROM=docker
Step 3/16 : FROM ${BUILD_FROM} AS builder
 ---> b97a72b8e97d
Step 4/16 : ARG QEMU_ARCH=x86_64
 ---> Using cache
 ---> 39bf2c3cd053
Step 5/16 : COPY ./build/edge/tmp/qemu-${QEMU_ARCH}-static /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder651840803/build/edge/tmp/qemu-x86_64-static: no such file or directory
Makefile:59: recipe for target 'edgeimage' failed
```
**Anything else we need to know?**:
The documentation to build the image should be corrected to use the edge/build/run_daemon.sh script to build the docker image.
```sh
cd build/edge
./run_daemon.sh build 
```
OR the documentation should point to https://github.com/kubeedge/kubeedge/blob/master/build/edge/README.md#deploy-kubeedges-edge-nodes-using-containers where there is a step to build the image.

**Comment by kadisi** [comment]
if use `ARG` in dockerfile, need docker >=17.05, ( [https://github.com/moby/moby/issues/32457](url) )   my docker version is 13.1, when exec `make edgeimage`, it will output error:
```
make edgeimage
docker build -t kubeedge/edgecore:v0.3.0-beta.0 -f build/edge/Dockerfile .
Sending build context to Docker daemon 109.2 MB
Step 1/16 : ARG BUILD_FROM=golang:1.12-alpine3.9
Please provide a source image with `from` prior to commit
make: *** [edgeimage] Error 1
``` 

we need check docker version before docker build

**Comment by chendave** [comment]
Actually, I didn't get the point of using qemu-*-static here, since it is used for cross-build, but obviously, the dockerfile here don't have any clue with cross build. 

The below doc mention this, but it looks like a different for deployment. 
https://github.com/kubeedge/kubeedge/blob/master/build/edge/README.md#deploy-kubeedges-edge-nodes-using-containers

BTW, I am on this.
