### ISSUE TITLE
KubeEdge latest version is not correct

### ISSUE THREAD

**Issue by vincentgoat** [kubeedge/kubeedge#4455]
**What happened**:
The latest version is not correct when we try to get it from https://kubeedge.io/latestversion

/help

**What you expected to happen**:
It should be v1.12.1

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by gy95** [comment]
/good first issue
please reference https://github.com/kubeedge/website/pull/262 to open one PR in [website ](https://github.com/kubeedge/website)repository to fix this.

**Comment by gy95** [comment]
/close 
https://github.com/kubeedge/website/pull/275 merged
