### ISSUE TITLE
NodeIP is empty, kubelet should not running on edge node when running edgecore

### ISSUE THREAD

**Issue by OyamingO** [kubeedge/kubeedge#4458]
**$ keadm join --cloudcore-ipport=master-IP:10000 --token=XXX**

$ journalctl -u edgecore.service -xe
-- The job identifier is 1473.
Nov 30 15:22:57 ecs-9b72 edgecore[24240]: W1130 15:22:57.130225   24240 validation.go:71] **NodeIP is empty , use default ip which can connect to cloud.**
Nov 30 15:22:57 ecs-9b72 edgecore[24240]: I1130 15:22:57.130276   24240 server.go:74] Version: v1.12.0
Nov 30 15:22:57 ecs-9b72 edgecore[24240]: F1130 15:22:57.132424   24240 server.go:85] **failed to check the running environment: kubelet should not running on edge node when running edgecore**
Nov 30 15:22:57 ecs-9b72 systemd[1]: edgecore.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit edgecore.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Nov 30 15:22:57 ecs-9b72 systemd[1]: edgecore.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit edgecore.service has entered the 'failed' state with result 'exit-code'.

**How do I stop kubelet running?**

Environment:
2CPU and 4G memory
system: ubuntu20.04
k8s: 1.22.15
keadm: 1.12.1

**Comment by gy95** [comment]
kubelet and kube-proxy cannot be deployed to edgecore nodes,
if you want to install edgecore on cloudcore node, you should set an env `export CHECK_EDGECORE_ENVIRONMENT="false"`
for systemd, you should add this env to systemd service file
https://kubeedge.io/en/docs/setup/local/#run-1

**Comment by OyamingO** [comment]
> kubelet and kube-proxy cannot be deployed to edgecore nodes, if you want to install edgecore on cloudcore node, you should set an env `export CHECK_EDGECORE_ENVIRONMENT="false"` for systemd, you should add this env to systemd service file https://kubeedge.io/en/docs/setup/local/#run-1

Very thanks for your reply.
