### ISSUE TITLE
Can i do keadm join with domain-name+port instead of ip+port

### ISSUE THREAD

**Issue by keyword1983** [kubeedge/kubeedge#4500]
Can i do keadm join with domain-name+port instead of ip+port??
like below:
keadm join --cloudcore-ipport=mycloudcore.xx.xx.local:10000 --edgenode-name=edge-node-01 --token=MYTOKEFROMCLOUDCORE

**What happened and what you expected to happen**:
join successful
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.12.1

**Comment by wackxu** [comment]
yes, We support this,  when you install cloudcore, you need add the dnsNames config, for example

```
keadm init --advertise-address=10.0.0.235 --kube-config=/var/run/kubernetes/admin.kubeconfig --profile cloudCore.modules.cloudHub.dnsNames=mycloudcore.xx.xx.local ...
```

**Comment by wackxu** [comment]
Then you can join the node use the command

keadm join --cloudcore-ipport=mycloudcore.xx.xx.local:10000 --edgenode-name=edge-node-01 --token=MYTOKEFROMCLOUDCORE

**Comment by wackxu** [comment]
Also, you should make sure the dns names can be resolve by the edge node

**Comment by keyword1983** [comment]
> Then you can join the node use the command
> 
> keadm join --cloudcore-ipport=mycloudcore.xx.xx.local:10000 --edgenode-name=edge-node-01 --token=MYTOKEFROMCLOUDCORE

@wackxu thx for reply
is it also support https url?

**Comment by wackxu** [comment]
the config `--cloudcore-ipport=` is the cloudcore address that expose to edge node, so the cloudcore-ipport could be a domain address or a ip address with port
