### ISSUE TITLE
Move mappers out of kubeedge/kubeedge repo

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#451]
**What would you like to be added**:
Move mappers out of kubeedge/kubeedge repo to a new `kubeedge/mappers` repo.

**Why is this needed**:
Currently mappers are part of kubeedge repo : https://github.com/kubeedge/kubeedge/tree/master/device. As mappers are applications sitting in between the edge_core process and devices to which they are connected, they should be not part of the core platform repo code. They should be moved out to a separate `kubeedge/mappers` repo.

**Comment by rohitsardesai83** [comment]
@sujithsimon22 , could you please take a look at this  ?

**Comment by sujithsimon22** [comment]
sure @rohitsardesai83 I can take this up. I will need a little help, from someone who had repo creation access within kubeedge, to create the repo kubedge/mappers.

**Comment by sujithsimon22** [comment]
@sids-b could you pls help out with repo creation ?

**Comment by m1093782566** [comment]
Please keep in mind that mapper will be required in kubeedge release package.

cc @kevin-wangzefeng @CindyXing

**Comment by kevin-wangzefeng** [comment]
I don't think it's a good time to move mapper out of tree now.
The mappers are now required part of device management functionality.
We can have out-of-tree mappers later on if there are more and more mappers.

**Comment by sujithsimon22** [comment]
> I don't think it's a good time to move mapper out of tree now.
> The mappers are now required part of device management functionality.
> We can have out-of-tree mappers later on if there are more and more mappers.

I guess this is a valid point. so we can probably put this activity on hold for now and take this up at a later point in time when there are more mappers and we feel its better to have the mappers out of the tree.

**Comment by kevin-wangzefeng** [comment]
Yes.
I'm going to move this out of v0.3.

**Comment by sids-b** [comment]
Thanks, lets keep this in backlog and we will take it up at right time.
