### ISSUE TITLE
边缘云节点安装后无法登入主机

### ISSUE THREAD

**Issue by cc20110101** [kubeedge/kubeedge#4538]
**What happened**:
1、根据官网部署方式(文档写的差劲，小学生写的吧)安装后，边端连接不了云端，云端svc方式根本就没放开端口，边端连接不了，手工改的边端配置文件端口
2、边端部署后，虚机登入不了，在输入用户界面卡住，永远在输入用户界面
![950cf1cc532ea696c20a12704724a81](https://user-images.githubusercontent.com/12064991/210536125-70a45961-4afd-403c-92c1-3e4c25e6ffd1.png)

3、边端机器，reboot、shutdown命令用不了了
![image](https://user-images.githubusercontent.com/12064991/210536184-ca11f00f-d735-49c2-b496-ac17d7aeefd7.png)

**Environment**:
k8s version: 1.23.5
kubeedge version :1.12.1
os: ubuntu-20.04.2
![image](https://user-images.githubusercontent.com/12064991/210536258-9badffaa-3a17-47d7-96e8-684ee89965a0.png)
![image](https://user-images.githubusercontent.com/12064991/210536298-53da2497-9ab0-468e-8dfc-5f5e8c25f709.png)

**Comment by vincentgoat** [comment]
Hi, @cc20110101 Thanks for the feedback. To better solve the issues you've met, please provide specific information on the following questions.

> 1、边端连接不了云端，云端svc方式根本就没放开端口，边端连接不了，手工改的边端配置文件端口

Which port did you manually modify?

> 边端部署后，虚机登入不了，在输入用户界面卡住，永远在输入用户界面

Generally, the kubeedge process will not affect device login and logout. You can stop the edgecore process and try again to rule out the problem of kubeedge.

> 边端机器，reboot、shutdown命令用不了了

Ditto

The log info shows the error information of the MQTT connection and didn't matter with this issue.
Please contact me if you have any other questions.

**Comment by vincentgoat** [comment]
As we discussed, KubeEdge integrates with containerd works fine. The ssh login issue would be the sshd config problem, let's check the operating system logs when the issues happen again.
With the advice above, I'll close this issue and feel free to reopen it if you think there are other issues that still need to be addressed.
