### ISSUE TITLE
边缘端edgecore段错误

### ISSUE THREAD

**Issue by cc20110101** [kubeedge/kubeedge#4539]
Environment:
k8s version: 1.23.5
kubeedge version :1.11.2
os: ubuntu-20.04.2-live-server-amd64.iso
![5dfe046152a405c481c0ba2de8b1313](https://user-images.githubusercontent.com/12064991/210701479-087b3aa5-578a-41bb-8edb-573c2fe9c275.png)
![9e8f3143b75d8980ed5fc1d3f9c2b64](https://user-images.githubusercontent.com/12064991/210701519-0453ebd4-a97d-4108-ab0c-950743fcb84a.png)

**Comment by vincentgoat** [comment]
The kubeedge/installation-package image id is correct and it works fine on other machines. I suggest checking the VM system when the error occurred.
So close this issue and feel free to contact me if you have any questions later.
