### ISSUE TITLE
[Question] How to verify device CRD works as expected?

### ISSUE THREAD

**Issue by chendave** [kubeedge/kubeedge#456]
**What happened**:
I saw device CRD is a new feature in 0.3-beta, and I could create an instance of device, but I cannot see there is any logs information / callback function implemented anywhere to see what's happened.

where is `c.events` is used?  
https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/devicecontroller/manager/common.go#L26

**What you expected to happen**:

There should be some message from cloud side that show what has been done and the result of the creation/deletion etc.

And I am unable to find where is the `event` got used anywhere. 

**How to reproduce it (as minimally and precisely as possible)**:
- create device model and device
- create instance
- check the logs from controller side.

**Anything else we need to know?**:

**Environment**:
- KubeEdge version: 0.3-beta
- Hardware configuration: X86-64
- OS (e.g. from /etc/os-release): UBUNTU16.04
- Kernel (e.g. `uname -a`):
- Others:

**Comment by sids-b** [comment]
Hi @chendave , after applying CRDs, we have given crd-samples in build folder.
1) Create a Kubeedge setup with cloud and edge.
2) apply model yaml from samples
2) change the node selector to node of your edge node instance yaml in samples.
3) apply instance yaml

You will see the following things happened.
1) device might have been created on edge. check sqlite edge.db. in device and device_twin table
2) config map with device profile will be create.
3) if you changed actual state of device from edge, it will get reflected in cloud as desired state. Do kubectl get device <device name> to verify,

**Comment by chendave** [comment]
@sids-b thanks!

Could you pls let me know what's the username/password of the edge.db? where it's defined?

**Comment by sids-b** [comment]
edge.db will be created at the directory from where edge_core is run. There will be no username or password. It is sqlite3 version.

**Comment by chendave** [comment]
Seems there is something goes wrong here, where can I get started on this?

``` bash
# kubectl get device
NAME                     AGE
sensor-tag-instance-01   12s

sqlite> .tables
device       device_attr  device_twin  meta

sqlite> .schema device
CREATE TABLE `device` (
    `id` varchar(64) NOT NULL PRIMARY KEY,
    `name` text,
    `description` text,
    `state` text,
    `last_online` text
);

sqlite> select count(*) from device;
0
```

**Comment by chendave** [comment]
sorry, I forgot to update nodeSelector

sqlite> select * from device;
sensor-tag-instance-01|sensor-tag-instance-01|TISimplelinkSensorTag||

**Comment by chendave** [comment]
one more question, 

> if you changed actual state of device from edge, it will get reflected in cloud as desired state. Do kubectl get device to verify

Do you mean the status from `kubectl describe device` will reflect the change?

**Comment by sids-b** [comment]
@chendave yess, you can change the actual state of the device from edge and it will be reflected at cloud. You can verify with kubectl describe device as well :)

**Comment by chendave** [comment]
@sids-b , could you tell me how to change the actual status of device? the device I created is based on the sample template, it is a fake device, so how do I simulate the change on the device?
