### ISSUE TITLE
dashboard install KubeEdge

### ISSUE THREAD

**Issue by RuningITway** [kubeedge/kubeedge#4616]
**What would you like to be added/modified**:

**Why is this needed**:
1. 希望增强功能
例如 ： 安装KubeEdge，有个控制台界面dashboard，一键选择安装套件包，然后点击 【一键安装】按钮，
则后台自动执行安装脚本，打印log，直到安装finish

**Comment by huapox** [comment]
不错，想得美

**Comment by vincentgoat** [comment]
Tracked by https://github.com/kubeedge/dashboard/issues/1 and close this issue.
Feel free to comment on https://github.com/kubeedge/dashboard/issues/1 if you have any other UI suggestions.
