### ISSUE TITLE
 Failed to check the running environment: Kubelet should not running on edge node when running edgecore

### ISSUE THREAD

**Issue by Yi-hash1** [kubeedge/kubeedge#4625]
when join 出现问题edgecore.service没起来

**Comment by RyanZhaoXB** [comment]
just as the log said, `kubelet should not running on edge noe when running edgecore`. please stop the `kubelet service` on the node using `systemctl stop kubelet`. or you can set the environment `CHECK_EDGECORE_ENVIRONMENT` to `false` to skip the environment checking.

**Comment by vincentgoat** [comment]
Please feel free to reopen if you have any questions about this issue.

**Comment by duanmengkk** [comment]
![image](https://github.com/kubeedge/kubeedge/assets/17697155/decb4f41-cd27-4346-95fd-daccfbfe452b)
The kubelet is not running on my machine,but the error is also occured
