### ISSUE TITLE
After restarting the edge node, the pod's restartCount is set to 0

### ISSUE THREAD

**Issue by yeqiugt** [kubeedge/kubeedge#4627]
**What happened**:
After restarting the edge node,  the pod's restartCount is set to 0。
![微信图片_20230228103417](https://user-images.githubusercontent.com/37202250/221738812-24ae8de0-e148-4967-91f6-eff4ad41ef96.jpg)
Through the wait command, i notice that the pod's restartCount +1 at first， but quickly changed to 0.
By audit log, i found cloudcore has a patch action that set pod's restartCount  to 0.
![微信图片_20230228103426](https://user-images.githubusercontent.com/37202250/221738878-847e385a-1a19-4580-bd0c-f4910e1589ce.jpg)
![微信图片_20230228103431](https://user-images.githubusercontent.com/37202250/221738895-ff721fe0-3f8d-426d-8d2e-7067fa9c78d1.jpg)

Is this a bug? or by design。

**What you expected to happen**:
In a normal k8s cluster, it should be 1 or the original restartCount  + 1。

**How to reproduce it (as minimally and precisely as possible)**:
Reboot edge node , and wait.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.10
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.12.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Shelley-BaoYue** [comment]
It doesn't matter. 😄   I will close this pr for v1.12.2 has fixed this problem.
