### ISSUE TITLE
同一个edge 反复注册及reset操作后，不能下发k8s部署文件

### ISSUE THREAD

**Issue by shenguangfu0906** [kubeedge/kubeedge#4629]
在一个edge上执行注册，并reset。多次重复操作后，无法下发k8s部署文件到edge端，cloud端日志提示 edge已经删除。
可能和缓存有关

**Comment by Shelley-BaoYue** [comment]
Before deploying, we need to use `kubectl get no` to make sure the edge-node has registed successfully. Therefore, we need to find why edge-node registration fails. Cloud you provide more detailed operation steps and edgecore error logs.
