### ISSUE TITLE
Update KubeEdge architecture picture to complete the missing device controller

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#463]
**What happened**:

The device controller is missing in the KubeEdge architecture picture.

**What you expected to happen**:

We should update KubeEdge architecture picture to complete the missing part.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by sids-b** [comment]
Nice Catch @m1093782566 . Will fix this soon :)
