### ISSUE TITLE
Bug about "INTERNAL-IP" messages

### ISSUE THREAD

**Issue by Piwriw** [kubeedge/kubeedge#4638]
**What happened**:
When I change the ip of edgecore ,the cloud message("INTERNAL-IP" ) is not right.When I `kubetcl get node -owide`
**What you expected to happen**:
Maybe it can changes at same time.This still seems to make the state ready, though
**How to reproduce it (as minimally and precisely as possible)**:
From using static addresses to changing dncp

**Anything else we need to know?**:
My edgecore is use VM,maybe it is a problem
**Environment**:
- Kubernetes version (use `kubectl version`):v1.22.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):v1.11.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):centeros7.6
  - Kernel (e.g. `uname -a`):5.19.0-1.el7.elrepo.x86_64
  - Go version (e.g. `go version`):1.17
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):v1.11.1
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7
  - Kernel (e.g. `uname -a`):3.10.0-1160.el7.x86_64
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Shelley-BaoYue** [comment]
Do you mean that you changed the `nodeIP` In `edgecore.yaml` or you changed the IP of VM?  No matter which operation you did, you need to restart edgecore to make the modification taking effect.
btw, v1.11.2 is better than v1.11.1.  You are advised to use the latest patch version.

**Comment by Piwriw** [comment]
> Do you mean that you changed the `nodeIP` In `edgecore.yaml` or you changed the IP of VM? No matter which operation you did, you need to restart edgecore to make the modification taking effect. btw, v1.11.2 is better than v1.11.1. You are advised to use the latest patch version.

Yes，I changed the `changed the IP of VM`. But it is  very strange that it still displays the original ip on the cloud. Although I know the relaunch will be updated. Maybe it is can be improved.

**Comment by Shelley-BaoYue** [comment]
#4641 may help.

**Comment by Piwriw** [comment]
> pr #4641 may help. If you use v1.12.2 or v1.13.0, you can just cherry-pick this pr and test in your environment.
Thanks，I will close the issues now.
