### ISSUE TITLE
edge cloud not  send message  to  cloud  by servicebus ???

### ISSUE THREAD

**Issue by shenguangfu0906** [kubeedge/kubeedge#4639]
![image](https://user-images.githubusercontent.com/33505599/223000371-c90c1338-bf4d-4740-bbc5-845faeb142d0.png)

**Comment by RyanZhaoXB** [comment]
edge could also send message to cloud by servicebus. you can check the KubeEdge Course https://www.bilibili.com/video/BV1RY411Y7rN?t=6157.0 to get more.

**Comment by shenguangfu0906** [comment]
i have seen this https://www.bilibili.com/video/BV1RY411Y7rN?t=6157.0  ,but there only introduced the code。no document how write the  rule  of  edge to cloud servicebus
