### ISSUE TITLE
How to deploy the edge part into a k8s cluster

### ISSUE THREAD

**Issue by zhanghongtong** [kubeedge/kubeedge#464]
**Which jobs are failing**:
I tried to deploy edgecore according to the [documentation](https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/README.md), but it didn't work.

**Which test(s) are failing**:
I tried to deploy edgecore according to the document. When I finished, the edge node is still in the state of NotReady. If I see the pods, I can see that the pod containing edgecore is in the pending state.

Just think about the following (my edgenode's name is "172.31.23.166")
```
$ kubectl get nodes
NAME               STATUS     ROLES    AGE   VERSION
172.31.23.166      NotReady   <none>   15s
ip-172-31-27-157   Ready      master   17h   v1.14.1

$ kubectl get pods -n kubeedge
NAME                              READY   STATUS    RESTARTS   AGE
172.31.23.166-7464f44944-nlbj2    0/2     Pending   0          9s
edgecontroller-5464c96d6c-tmqfs   1/1     Running   0          42s

$ kubectl describe pods 172.31.23.166-7464f44944-nlbj2 -n kubeedge
Name:               172.31.23.166-7464f44944-nlbj2
Namespace:          kubeedge
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             k8s-app=kubeedge
                    kubeedge=edgenode
                    pod-template-hash=7464f44944
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      ReplicaSet/172.31.23.166-7464f44944
Containers:
  edgenode:
    Image:      kubeedge/edgecore:latest
    Port:       <none>
    Host Port:  <none>
    Limits:
      cpu:     200m
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  512Mi
    Environment:
      DOCKER_HOST:  tcp://localhost:2375
    Mounts:
      /etc/kubeedge/certs from certs (rw)
      /etc/kubeedge/edge/conf from conf (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lpftk (ro)
  dind-daemon:
    Image:      docker:dind
    Port:       <none>
    Host Port:  <none>
    Requests:
      cpu:        20m
      memory:     512Mi
    Environment:  <none>
    Mounts:
      /var/lib/docker from docker-graph-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lpftk (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubeedge/certs
    HostPathType:
  conf:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      edgenodeconf
    Optional:  false
  docker-graph-storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-lpftk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lpftk
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  46s (x2 over 46s)  default-scheduler  0/2 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 1 Insufficient pods, 1 node(s) had taints that the pod didn't tolerate.
```

**Since when has it been failing**:

**Reason for failure**:

**Anything else we need to know**:
1. I set a taint on the primary node: `node-role.kubernetes.io/master=:NoSchedule`, which makes the master node unable to deploy any pods, I am not sure if this is correct
2. The edge node does not do anything other than pulling the edgecore image and copying the edge certs file into the `/etc/kubeedge/certs` folder. Is there anything I missed?
3. The [edge deploy file](https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/04-deployment-edgenode.yaml) has no information about the node select. When there are multiple edgenodes, how is it deployed to the correct node?
4. Have you completed the function of connecting edge from cloud? Otherwise, how does cloud deploy pods to edge?

**Comment by zhanghongtong** [comment]
I deployed the mqtt broker on the edgenode, then modified [mqtt.server in 03-configmap-edgenodeconf.yaml](https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/03-configmap-edgenodeconf.yaml#L12), and the edge core's pods are still in the pending state.

**Comment by edisonxiang** [comment]
Hey @zhanghongtong 
Thanks you reply.
are you using the latest code to build edge image?
https://github.com/kubeedge/kubeedge/tree/master/build/edge/kubernetes
I guess you need to change this line with your KubeEdge EdgeController ip and port
https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/03-configmap-edgenodeconf.yaml#L20

Actually we need to expose the KubEdge EdgeController as a service like clusterip or nodeport or LB, so we can connect the service ip and port by websocket.
Another way is to use hostNetwork here.
https://github.com/kubeedge/kubeedge/blob/master/build/cloud/07-deployment.yaml#L49
and also expose the web socket server ip and port:)

**Comment by zhanghongtong** [comment]
@edisonxiang Thanks you reply.
I did use the latest code, and I have modified [edgehub. websocket.url in 03-configmap-edgenodeconf.yaml](https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/03-configmap-edgenodeconf.yaml#L20), I deployed the KubEdge EdgeController as a NodePort Service for direct access on the edgenode, but my issue still exists.

**Comment by edisonxiang** [comment]
@zhanghongtong Oh..... It seems like your edge node pod is not scheduled.

> Warning  FailedScheduling  46s (x2 over 46s)  default-scheduler  0/2 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 1 Insufficient pods, 1 node(s) had taints that the pod didn't tolerate

**Comment by zhanghongtong** [comment]
@edisonxiang This is also my doubt, my edgenode is AWS EC2 t2.
T2.xlarge, its configuration is 4 core 16G memory, there should be no shortage of computing power, I suspect that the edgenode has been in the state of NotReady, which led to this Warning, how should I troubleshoot it?

**Comment by edisonxiang** [comment]
@zhanghongtong  perhaps you can use `free` and `top` or other commands in your AWS EC2 t2 so that you can get the real time cpu and memory information in that ec2:)

**Comment by zhanghongtong** [comment]
@edisonxiang I have checked that my CPU and memory are almost idle.
```
$ free
              total        used        free      shared  buff/cache   available
Mem:       16424488      323308    13653168         776     2448012    15770200
Swap:             0           0           0

$top
top - 03:41:25 up 19:01,  1 user,  load average: 0.00, 0.00, 0.00
Tasks: 118 total,   1 running,  73 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16424488 total, 13653028 free,   323448 used,  2448012 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 15770060 avail Mem
```

**Comment by zhanghongtong** [comment]
I can't correctly display the resources of edgenode when I use kubectl to view edgenode on the cloud node.
```
$ kubectl describe nodes 172.31.23.166
Name:               172.31.23.166
Roles:              <none>
Labels:             name=edge-node
Annotations:        node.alpha.kubernetes.io/ttl: 0
CreationTimestamp:  Wed, 08 May 2019 01:57:39 +0000
Taints:             node.kubernetes.io/unreachable:NoExecute
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                   Message
  ----             ------    -----------------                 ------------------                ------                   -------
  Ready            Unknown   Wed, 08 May 2019 01:57:39 +0000   Wed, 08 May 2019 01:57:41 +0000   NodeStatusNeverUpdated   Kubelet never posted node status.
  MemoryPressure   Unknown   Wed, 08 May 2019 01:57:39 +0000   Wed, 08 May 2019 01:57:41 +0000   NodeStatusNeverUpdated   Kubelet never posted node status.
  DiskPressure     Unknown   Wed, 08 May 2019 01:57:39 +0000   Wed, 08 May 2019 01:57:41 +0000   NodeStatusNeverUpdated   Kubelet never posted node status.
  PIDPressure      Unknown   Wed, 08 May 2019 01:57:39 +0000   Wed, 08 May 2019 01:57:41 +0000   NodeStatusNeverUpdated   Kubelet never posted node status.
Addresses:
System Info:
 Machine ID:
 System UUID:
 Boot ID:
 Kernel Version:
 OS Image:
 Operating System:
 Architecture:
 Container Runtime Version:
 Kubelet Version:
 Kube-Proxy Version:
PodCIDR:                     10.244.1.0/24
Non-terminated Pods:         (0 in total)
  Namespace                  Name    CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----    ------------  ----------  ---------------  -------------  ---
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
Events:              <none>
```

**Comment by edisonxiang** [comment]
yep. since the edge node is not ready:(
This root cause of this issue is because the edge node pod is not scheduled.
Could you try to clear the taint in your master and try to deploy edge noe pod in your master?

**Comment by zhanghongtong** [comment]
Yes, I removed the taint on the cloud node and redeployed the pod. Now the edgecore pod has been running, but the edgenode is still NotReady.
```
$ kubectl taint nodes ip-172-31-27-157  node-role.kubernetes.io/master:NoSchedule-
node/ip-172-31-27-157 untainted

$ kubectl create -f 04-deployment-edgenode.yaml
deployment.apps/172.31.23.166 created

$ kubectl get pods -n kubeedge -o wide
NAME                              READY   STATUS    RESTARTS   AGE     IP            NODE               NOMINATED NODE   READINESS GATES
172.31.23.166-7464f44944-9tmlp    2/2     Running   0          3m30s   10.244.0.16   ip-172-31-27-157   <none>           <none>
edgecontroller-5464c96d6c-tmqfs   1/1     Running   0          3h58m   10.244.0.14   ip-172-31-27-157   <none>           <none>

$ kubectl get nodes
NAME               STATUS     ROLES    AGE     VERSION
172.31.23.166      NotReady   <none>   3h55m
ip-172-31-27-157   Ready      master   21h     v1.14.1
```

**Comment by edisonxiang** [comment]
Okay. could you get edge_core container's log?
It is useful to find the problem.
By the way, 
since you are using `172.31.23.166` as an edge node name,
did you modify the edge node name like this readme describes?
https://github.com/kubeedge/kubeedge/tree/master/build/edge/kubernetes

**Comment by zhanghongtong** [comment]
Oh, I know what's going on, I wrote the wrong edgehub.websocket.url in 03-configmap-edgenodeconf.yaml, this is a stupid mistake.I fixed it and can work now. So edgecore pods are to be deployed to the cloud node, is that correct?

**Comment by zhanghongtong** [comment]
I have a new problem now. I modified `kubeedge/build/deployment.yaml` and deployed it to edgenode. The state of pods is now running, but there is no docker container on edgenode, and it can't be linked using curl. What happened?

On the cloud node
```
$ git diff deployment.yaml
diff --git a/build/deployment.yaml b/build/deployment.yaml
index 29dbd3a..ae5e0a2 100644
--- a/build/deployment.yaml
+++ b/build/deployment.yaml
@@ -14,6 +14,7 @@ spec:
       labels:
         app: nginx
     spec:
+      nodeName: 172.31.23.166
       containers:
       - name: nginx
         image: nginx:1.15.12

$ kubectl apply -f deployment.yaml
deployment.apps/nginx-deployment created

$ kubectl get pods -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP       NODE            NOMINATED NODE   READINESS GATES
nginx-deployment-68cf9b6795-r4w49   1/1     Running   0          21s   <none>   172.31.23.166   <none>           <none>

$ curl 172.31.23.166
curl: (7) Failed to connect to 172.31.23.166 port 80: Connection refused
```

On the edge node
```
$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by edisonxiang** [comment]
@zhanghongtong OKay.
In your k8s cluster, there is one vm for master, one vm for node. Right?
I guess your k8s node have came across some problem.
Perhaps you can retart it and try again.
Actually this is only related with k8s self scheduler.

**Comment by zhanghongtong** [comment]
I still don't understand it, but I am going to clear the environment and redeploy it again. Before that, I want to confirm two problems:
1. edgecore pods are to be deployed to the cloud node, is that correct? or it does not matter which node the edgecore is deployed to. It only needs to be handed over to the k8s scheduler.
2. The documentation does not mention the need to install the mqtt broker on the edgenode, so I have not installed any mqtt broker. Is this correct?

**Comment by edisonxiang** [comment]
@zhanghongtong 
About 1. It does not matter.
About 2, since the edge node is running in the pod.  so do you mean if we need to setup mqtt in the docker images

Actually there is no difference with this original architecture
https://github.com/kubeedge/kubeedge#architecture

Just we need to a real k8s cluster including master and node.
We will deploy the edgecontroller and edgecore by pods.
and edgecore pod connects to edgecontroller(nodeport) 
and edgecontroller list watch k8s api server.

**Comment by zhanghongtong** [comment]
@edisonxiang Thanks you reply. 
> About 2, since the edge node is running in the pod. so do you mean if we need to setup mqtt in the docker images

We don't need to set mqtt in the docker image, we only need to add an mqtt proxy container to the edgecore pod, because the document does not mention the contents of the mqtt proxy, so I want to know if the mqtt proxy is still necessary, if so, then Is it feasible to deploy the mqtt agent to the edgecore pod, or does the mqtt agent have to run on the edgenode?

**Comment by edisonxiang** [comment]
@zhanghongtong yep. mqtt  is necessary for communication between edge node and devices (mapper). Feel free to add it:). Thanks very much.

**Comment by zhanghongtong** [comment]
I redeployed `edgecontroller` and `edgecoer`, now they all run on the cloud node, edgenode is also Ready, now I deploy `kubeedge/build/deployment.yaml ` to the edgenode, see that the edgenode node still has no running docker container, and can't pass Curl access to the `nginx-deployment pod`

```
$ kubectl get pods -n  kubeedge
NAME                              READY   STATUS    RESTARTS   AGE
172.31.23.166-8475859745-9fbwp    3/3     Running   0          81m
edgecontroller-5464c96d6c-tmqfs   1/1     Running   0          7h28m

$ kubectl get nodes
NAME               STATUS   ROLES    AGE     VERSION
172.31.23.166      Ready    <none>   7h45m   2.0.0
ip-172-31-27-157   Ready    master   24h     v1.14.1

$ kubectl get pods -o wide
NAME                               READY   STATUS    RESTARTS   AGE   IP       NODE            NOMINATED NODE   READINESS GATES
nginx-deployment-d86dfb797-8cspw   1/1     Running   0          26m   <none>   172.31.23.166   <none>           <none>

$ curl 172.31.23.166
curl: (7) Failed to connect to 172.31.23.166 port 80: Connection refused
```

I think this is a problem. Edgecore runs on the cloud node. How does it deploy the pod on the docker in dockeredge node?

**Comment by edisonxiang** [comment]
@zhanghongtong Currently you have a very good progress about deploying kubeedge cloud and edge in k8s cluster:) In your environment, edge node is ready and nginx-deployment is running, right?

https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/04-deployment-edgenode.yaml#L41

Actually the nginx process will be exist in this container `dind-daemon`.
I think this is the reason you got nothing from `curl 172.31.23.166`

**Comment by zhanghongtong** [comment]
Yes, I found nginx-deployment in the dind-deamon, but the nginx-deployment is still running on the cloud node, because the dind-deamon is also running on the cloud node, how to distribute it to the edge node?

**Comment by edisonxiang** [comment]
@zhanghongtong we can use node selector to specify nginx-deployment to edge node, right?

**Comment by zhanghongtong** [comment]
@edisonxiang Sorry to reply so late, I use the node selector to specify nginx-deployment to the edge node, but, nginx-deployment is still deployed in the container of the ded-deamon in the pod of the edgenode. The pod of the edgenode is running on the cloud node, so the nginx-deployment is not deployed on the edge node host.

**Comment by edisonxiang** [comment]
@zhanghongtong perhaps I have some misunderstandings with the `edgenode` which you were talking about.  Actually the `edgenode` is not a vm in this kind of deployment. the `edgenode` is a pod which will connect with the `edgecontroller` in the pod. so in this kind of deployment, actually 
it is not neccessary to distinguish the cloud and the edge:)

**Comment by zhanghongtong** [comment]
I feel that I need to re-describe my problem to avoid meaningless misunderstandings.

First we define several concepts

- cloud node : cloud physical machine
- edge node : edge physical machine
- edge controller pod : edge controller deployed via k8s
- edge core pod : edge core deployed by k8s

Currently I am trying to use a cloud node and an edge node to form a cluster by k8s deployment. I did the following

1. Deploy edge controller pods via kubectl, just like https://github.com/kubeedge/kubeedge/blob/master/build/cloud/README.md, edge controller pods are deployed on top of the cloud node.
2. Deploy edge core pods via kubectl, just like https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/README.md, edge core pods are deployed on top of the cloud node.
3. Using kubectl create -f kubeedge/build/deployment.yaml to deploy nginx-deplyment, you can see that nginx-deployment was successfully deployed in the dind-deamon container in the edge core pod.

My question:

1. I think edge core pods should be deployed on the edge node, but before the edge core pods are deployed successfully, the edge node is always in the NotReady state. Only after the edge core pods state becomes running, the edge node becomes Ready
2. nginx-deployment is deployed in the dind-deamon container in the edge core pod, so it is actually on the cloud node, I think it should be on the edge node
3. The edge node has no containers or pods deployed on it so far, it feels that this physical machine is useless.

**Comment by zhanghongtong** [comment]
Anything update?

**Comment by rohitsardesai83** [comment]
@edisonxiang , can you please check ?

**Comment by googlebabaio** [comment]
> I feel that I need to re-describe my problem to avoid meaningless misunderstandings.
> 
> First we define several concepts
> 
> * cloud node : cloud physical machine
> * edge node : edge physical machine
> * edge controller pod : edge controller deployed via k8s
> * edge core pod : edge core deployed by k8s
> 
> Currently I am trying to use a cloud node and an edge node to form a cluster by k8s deployment. I did the following
> 
> 1. Deploy edge controller pods via kubectl, just like https://github.com/kubeedge/kubeedge/blob/master/build/cloud/README.md, edge controller pods are deployed on top of the cloud node.
> 2. Deploy edge core pods via kubectl, just like https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/README.md, edge core pods are deployed on top of the cloud node.
> 3. Using kubectl create -f kubeedge/build/deployment.yaml to deploy nginx-deplyment, you can see that nginx-deployment was successfully deployed in the dind-deamon container in the edge core pod.
> 
> My question:
> 
> 1. I think edge core pods should be deployed on the edge node, but before the edge core pods are deployed successfully, the edge node is always in the NotReady state. Only after the edge core pods state becomes running, the edge node becomes Ready
> 2. nginx-deployment is deployed in the dind-deamon container in the edge core pod, so it is actually on the cloud node, I think it should be on the edge node
> 3. The edge node has no containers or pods deployed on it so far, it feels that this physical machine is useless.

1. Programs of `edge_core` should be running on edge node ,It can be binary or image.
2.Want to see the edge node's status is `ready`, edge node needs to start the  `edge_core` program. If it's running as image, start it with `docker run`  ,not deploy in k8s.
3. the purpose for start edge_core is:
(1) Start the client of websocket on edge node
(2) Connect the web socker server provided by Cloud-Edge cotroller according to the configuration in `edge.yaml`
(3) The way kubeedge connects between cloud and edge is websocket.
4. If you want to deploy a `deployment.yaml` to an edge node, you can use `node selector`, and you also need to ensure that the edge node is `ready`

**Comment by zhanghongtong** [comment]
@googlebabaio Oh, I know, thx.
Bug if the edge core cannot be deployed through k8s, why does [this document](https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/README.md) exist?

**Comment by googlebabaio** [comment]
> @googlebabaio Oh, I know, thx.
> Bug if the edge core cannot be deployed through k8s, why does [this document](https://github.com/kubeedge/kubeedge/blob/master/build/edge/kubernetes/README.md) exist?

@zhanghongtong  Yes,I think  u r right! 

I just run edge_core contaniner by docker-compose. [Deploy kubeedge's edge nodes using containers](https://github.com/kubeedge/kubeedge/tree/master/build/edge)

I do not deploy the edge part into a k8s cluster.. I think this is a chicken and egg problem.hhh..

**Comment by zhanghongtong** [comment]
@googlebabaio Yes, the analogy of chicken and egg is very appropriate, hhh...
So this is a ubiquitous problem. Do you have a plan to solve it? Do we need to reassign the labels and milestones of this issue?

**Comment by edisonxiang** [comment]
@zhanghongtong @googlebabaio 
sorry for late.
I think your conversations are reasonable.
Actually the key point is that we should deploy edge_core pod on the `edge node vm`
but in your test case, the edge-core pod is running on the `cloud node vm`

Perhaps you have the question about that
since the edge node is added into k8s cluster,
why do we need to run one ore more edge_core pods on this edge node.
As you know, the edge_core pods are working with edge_controller by websocket or quic.
so the edge_core is vitural edge node. we can simulate one or more vitural edge nodes on one actual `edge node vm`. So there is no chicken and egg problem.

In our original ideas, these solution can be used simulate lots of vitural edge nodes in one vm.

**Comment by zhanghongtong** [comment]
@edisonxiang Thank you for your answer, so deploying edge core with k8s is not suitable for deployment on physical edge nodes, right?

**Comment by edisonxiang** [comment]
@zhanghongtong you are welcome. 
since the edge node vm is already added into k8s cluster.
so it is not neccessary to add the edge node again by kubeedge.
yep. Perhaps we can find some actual user scenarios about this in some day.
and today we can use it as a test or some experiments.
since we can deploy edge_controller and edge_core in pods which are running in one ore more vms, like you had deployed. Once we find some user cases, we can try to improve it or give another kind of solution. Currently this solution is very useful for us. Actually it is a little like `kubemark` in kubernetes.

**Comment by zhanghongtong** [comment]
@edisonxiang Ok, I understand, I will close this issue, thank you for your reply.

**Comment by edisonxiang** [comment]
@zhanghongtong Thanks. Your feedback is always useful for the team.
