### ISSUE TITLE
When the edge node is connected, a failed cni plug-in pod will be deployed

### ISSUE THREAD

**Issue by JiaweiGithub** [kubeedge/kubeedge#4653]
**What happened**:
When the edge node is connected, a failed cni plug-in pod will be deployed
**What you expected to happen**:
Access edge nodes, do not deploy these failed cni plugin pods

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/8078735/224209447-a30e02e5-0f35-4522-9579-f62f44e9f617.png">

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Shelley-BaoYue** [comment]
You can set toleration or taints to make calico not schedule on edge nodes.

**Comment by JiaweiGithub** [comment]
> You can set toleration or taints to make calico not schedule on edge nodes.

ok,thanks
