### ISSUE TITLE
Can‘t pull the image of kubeedge/cloud-iptables-manager 1.13.0 when execute "keadm init" command

### ISSUE THREAD

**Issue by NicoleLeeuu** [kubeedge/kubeedge#4657]
**What happened**:
Can‘t pull the image of kubeedge/cloud-iptables-manager 1.13.0 when execute "keadm init" command. Dockerhub hasn't the image of kubeedge/cloud-iptables-manager 1.13.0.
**What you expected to happen**:
Add the image of kubeedge/cloud-iptables-manager 1.13.0.
**How to reproduce it (as minimally and precisely as possible)**:
Deploy kubeedge v1.13.0
**Anything else we need to know?**:
None.
**Environment**:
- Kubernetes version (use `kubectl version`): v1.23.8
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.13.0
- <details><summary>Cloud nodes Environment:</summary> 

  - Hardware configuration (e.g. `lscpu`): 
  - OS (e.g. `cat /etc/os-release`): 
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by RyanZhaoXB** [comment]
hello, the name of `iptables-manager` is wrong in this version and the fix PR https://github.com/kubeedge/kubeedge/pull/4620  has been waiting to be merged. you can find the images of `1.13.0` here https://hub.docker.com/r/kubeedge/iptablesmanager/tags

**Comment by NicoleLeeuu** [comment]
get it
