### ISSUE TITLE
edge节点断网离线，云侧deployment不断启动新的pod

### ISSUE THREAD

**Issue by ledrsnet** [kubeedge/kubeedge#4659]
edge节点断网离线，云侧deployment不断启动新的pod，pod是硬调度到节点的，如果节点离线，deployment控制器自动删除旧的pod拉起新的pod一直拉不起新的，删不掉旧的，导致pod数量一直增多。
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/31727281/224705173-2f3a4fa4-c633-4932-9ce3-5daff91d84ef.png">

```bash
示例yaml如下:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
  labels:
    app: nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      nodeName: sealos-2
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 80
```

**Comment by Shelley-BaoYue** [comment]
fyi: https://github.com/kubeedge/kubeedge/issues/3736

**Comment by ledrsnet** [comment]
@Shelley-BaoYue 3Q!

**Comment by HusenHuang** [comment]
kubbedge version 1.18 这个又复现了

**Comment by HusenHuang** [comment]
![image](https://github.com/user-attachments/assets/0dabf0a0-7035-47fc-b83a-3bdd76d5feaa)


![image](https://github.com/user-attachments/assets/a730034d-04ec-4e80-95dc-849b2a1cb6af)

![image](https://github.com/user-attachments/assets/05e3ebd1-0ee5-4a18-a287-7c35584233db)
