### ISSUE TITLE
No space left on the device on the edge node  if we redirect log to some file

### ISSUE THREAD

**Issue by srivatsav123** [kubeedge/kubeedge#469]
**What happened**:
After installation of kubeedge using keadm installer(kubeedge installer)..Edge node got evicted due to no space left on the device
Reason:Since edge_core.logs are been redirected in /etc/kubeedge/kubeedge/edge/edge_core.log
**What you expected to happen**:
Edge node must tar the files and keep(ex:logrotate mechanism) or donot redirect logs
**How to reproduce it (as minimally and precisely as possible)**:
install kubeedge using kubeedge installer..Keep for 1 day..Lots of log will be accumulated
**Anything else we need to know?**:
![nodeevicted](https://user-images.githubusercontent.com/39593583/57352774-04b36c00-7184-11e9-98b4-5133da88ddf7.png)

As seen in above image 93 gb was used by edge_core.log

**

**Comment by sids-b** [comment]
Looks a reasonable feature to add.

**Comment by rohitsardesai83** [comment]
@srivatsav123 , looks like we need to have log rotation. We can target this after 1.0 release ?
Moving to backlog now. Please get back if it needs to go in 1.0.

**Comment by sids-b** [comment]
I see a PR in beehive https://github.com/kubeedge/beehive/pull/27 to support log rotate. But since we have moved to klog, not sure if the PR is still valid.
