### ISSUE TITLE
pod on edge not deleted when call with --force

### ISSUE THREAD

**Issue by neiba** [kubeedge/kubeedge#4692]
**What happened**:
1. create deployment with 5 replicas, schedule 5 nginx pod to edge node
2. kubectl delete pod -l app=nginx --force

some pod on edge node not be deleted.

**What you expected to happen**:
All pod be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

1. edgecontroller send pod delete msg to cloudhub
2. synccontroller reconcile and found pod was deleted, and send pod delete msg to cloudhub too, this msg does not contain spec.nodename
3. edged handlePod with filterPodByNodeName filter, so the message just pass.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.13
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Shelley-BaoYue** [comment]
This pr may help: https://github.com/kubeedge/kubeedge/pull/4596 .   It haven't be merged into 1.13 version. You can cherry-pick it or use 1.12.2 version.

**Comment by neiba** [comment]
Thanks!
