### ISSUE TITLE
Memory leaks caused by devicetwin module when the device mapper is deployed

### ISSUE THREAD

**Issue by geassXX** [kubeedge/kubeedge#4700]
**What happened**:
Now when I try to deploy deivce mapper pods ，I find  that the edgecore process is consuming more and more memory , so I suspect a memory leak caused by improper devicetwin module code.

**How to reproduce it (as minimally and precisely as possible)**:
Just deploy the device mapper in any kubeedge environment.

**Anything else we need to know?**:
After I try to understand the device twin code and edgehub code , It is basically confirmed that the problem is caused by the error of confusing the relationship between synchronous asynchro and response when the two modules send acknowledgement messages using the beehave framework.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.8
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.21.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`): NAME="Ubuntu" VERSION="18.04.5 LTS (Bionic Beaver)"
  - Kernel (e.g. `uname -a`):Linux controller01 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
  - Go version (e.g. `go version`):go version go1.18 linux/amd64
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):v1.21.1
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`): NAME="Ubuntu" VERSION="18.04.5 LTS (Bionic Beaver)"
  - Kernel (e.g. `uname -a`):Linux edge-line-01 4.19.90+ #1 SMP Sat Jan 29 00:19:13 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
  - Go version (e.g. `go version`):go version go1.18.5 linux/arm64
  - Others: This problem also occurs on the edge of euleros systems.

  </details>

**Comment by RyanZhaoXB** [comment]
Hello! this bug has been fixed in https://github.com/kubeedge/kubeedge/issues/4701. please cherry-pick the PR and try it. Thanks.

**Comment by geassXX** [comment]
devicecontroller upstream module on the cloud also seems to have some problems handling DeviceStateUpdate response messages.In detail, In line 91 of upstream.go, the resource type determination did not process the state/update message.
