### ISSUE TITLE
move some definition into  common package for cloud and edge

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#471]
**What would you like to be added**:
when i read code of kubeedge, i found some definition are shared between cloud and edge. do we need move them into common package?

such as `ResourceSep               = "/"` in `cloud/pkg/controller/constants/service.go` file.

in edge, we only use `"/"`, but in cloud  somewhere use `ResourceSep` and somewhere use `"/"`

```
cloud/pkg/devicecontroller/messagelayer/util.go

// GetDeviceID returns the ID of the device
func GetDeviceID(resource string) (string, error) {
	res := strings.Split(resource, "/")
	if len(res) >= constants.ResourceDeviceIDIndex+1 && res[constants.ResourceDeviceIndex] == constants.ResourceDevice {
		return res[constants.ResourceDeviceIDIndex], nil
	}
	return "", errors.New("failed to get device id")
}
```

**Why is this needed**:

**Comment by rohitsardesai83** [comment]
@kadisi , its good that we can have common constants defined in the common package. 
Is this list of duplicate constants big or small ? If small , we can live with it for now. Else we move to common.

**Comment by rohitsardesai83** [comment]
@kadisi , any update on this ?

**Comment by kadisi** [comment]
@rohitsardesai83 PTAL
