### ISSUE TITLE
边缘节点的flannel的pod报错： Error from server: Get "https://192.168.50.3:10350/containerLogs/kube-flannel/kube-flannel-ds-q5gh9/kube-flannel": dial tcp XXXXX:10350: connect: connection refused

### ISSUE THREAD

**Issue by luomengY** [kubeedge/kubeedge#4759]
边缘节点的flannel的pod报错如下，pod状态为CrashLoopBackOff
Error from server: Get "https://192.168.50.3:10350/containerLogs/kube-flannel/kube-flannel-ds-q5gh9/kube-flannel": dial tcp XXXXX:10350: connect: connection refused
详细报错如下：
Defaulted container "kube-flannel" out of: kube-flannel, install-cni-plugin (init), install-cni (init)
Error from server: Get "https://43.139.161.85:10350/containerLogs/kube-flannel/kube-flannel-ds-xkgc7/kube-flannel": dial tcp 43.139.161.85:10350: connect: connection refused

**Comment by Piwriw** [comment]
You can try manually pulling the image of the flannel first

**Comment by luomengY** [comment]
> 

这跟手动拉镜像没关系吧，kubectl logs日志是：
Error from server: Get "https://192.168.159.106:10350/containerLogs/kube-system/kube-flannel-edge-ds-8hcj9/kube-flannel": dial tcp 192.168.159.106:10350: connect: connection refused
手动拉取镜像也是一样的

**Comment by RyanZhaoXB** [comment]
hello @luomengY . You cannot use `kubectl logs` to get the log when your pod crashed. 

You can check https://github.com/kubeedge/kubeedge/issues/2677 and install flannel at edge correctly.

**Comment by luomengY** [comment]
> hello @luomengY . You cannot use `kubectl logs` to get the log when your pod crashed.
> 
> You can check #2677 and install flannel at edge correctly.

日志是可以看到的：
Error from server: Get "https://192.168.159.106:10350/containerLogs/kube-system/kube-flannel-edge-ds-pnvqm/kube-flannel": dial tcp 192.168.159.106:10350: connect: connection refused
我用的isulad作为容器引擎，边缘节点192.168.159.106的10350端口lsof如下：
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
edgecore 39787 root   17u  IPv4 144039      0t0  TCP localhost:10350 (LISTEN)
这个端口好像没有对外开放访问呢，会不会是因为这个原因导致cloud node访问边缘节点的10350端口访问不了而被拒绝

**Comment by univwang** [comment]
借楼，开启metaserver后，flannel在边缘节点是READY状态，配置了EdgeCore的cni后，没有按照想象的那样创建一个cni0网桥，只有flannel.1，创建的pod的ip依旧是172网段的，怀疑并没有正常运行cni插件，如果配置？如何调试？

**Comment by qyd159** [comment]
> > hello @luomengY . You cannot use `kubectl logs` to get the log when your pod crashed.
> > You can check #2677 and install flannel at edge correctly.
> 
> 日志是可以看到的： Error from server: Get "https://192.168.159.106:10350/containerLogs/kube-system/kube-flannel-edge-ds-pnvqm/kube-flannel": dial tcp 192.168.159.106:10350: connect: connection refused 我用的isulad作为容器引擎，边缘节点192.168.159.106的10350端口lsof如下： COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME edgecore 39787 root 17u IPv4 144039 0t0 TCP localhost:10350 (LISTEN) 这个端口好像没有对外开放访问呢，会不会是因为这个原因导致cloud node访问边缘节点的10350端口访问不了而被拒绝

遇到相同的问题，有解决办法了吗

**Comment by RingTsui** [comment]
> 借楼，开启metaserver后，flannel在边缘节点是READY状态，配置了EdgeCore的cni后，没有按照想象的那样创建一个cni0网桥，只有flannel.1，创建的pod的ip依旧是172网段的，怀疑并没有正常运行cni插件，如果配置？如何调试？

请问您解决了这个问题吗？
