### ISSUE TITLE
Make DeviceModel CRD optional

### ISSUE THREAD

**Issue by cl2017** [kubeedge/kubeedge#4777]
**What would you like to be added/modified**:
Make DeviceModel CRD optional and it can be mount into Device just like configmap.
Users can write properties into DeviceModel based on their requirements. DeviceModel is not forced to use.

**Why is this needed**:
The same property is described in both Device and DeviceModel, but the content of the property is different, which makes users feel difficult to understand, and they do not know how to use it.
The code is complex, and there are problems in the order of Device and DeviceModel delivery

**Comment by vincentgoat** [comment]
+1 Nice consideration.

**Comment by fisherxu** [comment]
The device model is still needed :)
/close
