### ISSUE TITLE
 certmanager.go:94] Error: failed to get CA certificate, err: Get "https://192.168.200.128:10002/ca.crt": dial tcp 192.168.200.128:10002: connect: connection refuse

### ISSUE THREAD

**Issue by Albertchamberlain** [kubeedge/kubeedge#4796]
**What happened**:
failed to get CA certificate
![image](https://github.com/kubeedge/kubeedge/assets/47343901/d67f52bf-48d1-4188-a8cd-76208a3aba81)

**What you expected to happen**:
get the CA
**How treproduce it (as minimally and precisely as possible)**:
run “ keadm join --cloudcore-ipport=192.168.200.128:10000 --token=5c6c3d4967647b6d26262990d2feb205f9b70fee33253df7115f546f” in Edge device
**Anything else we need to know?**:
ping 192.168.200.128 is ok
![image](https://github.com/kubeedge/kubeedge/assets/47343901/ed503960-9693-473a-93fa-acad6a4235d1)

**Environment**:
- Kubernetes version (use `kubectl version`):v1.22.7
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):v1.12.2
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            25
Model:                 80
Model name:            AMD Ryzen 7 5800H with Radeon Graphics
Stepping:              0
CPU MHz:               3193.882
BogoMIPS:              6387.76
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext pdpe1gb rdtscp lm constant_tsc art rep_good nopl tsc_reliable nonstop_tsc extd_apicid eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cr8_legacy abm sse4a misalignsse osvw topoext rsb_ctxsw ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero arat umip vaes vpclmulqdq overflow_recov succor
  - OS (e.g. `cat /etc/os-release`):  NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
  - Kernel (e.g. `uname -a`): Linux edge.kubeedge 3.10.0-1160.90.1.el7.x86_64  SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linu
  - Go version (e.g. `go version`):go version go1.12.9 linux/amd64
  - Others:

  </details>

- <details><summary>Edge nodes Environment:</summary>
  - edgecore version (e.g. `edgecore --version`):v1.12.2
  - Hardware configuration (e.g. `lscpu`):same  with  cloud core
  - OS (e.g. `cat /etc/os-release`): same with  cloud core
  - Kernel (e.g. `uname -a`): same with  cloud core
  - Go version (e.g. `go version`): same with  cloud core
  - Others:
  </details>

**Comment by Shelley-BaoYue** [comment]
Ports 10000-10004 must be open to edge nodes.

**Comment by Albertchamberlain** [comment]
> Ports 10000-10004 must be open to edge nodes.端口10000-10004必须对边缘节点开放。

![image](https://github.com/kubeedge/kubeedge/assets/47343901/9765b6f8-886e-498d-88d5-a186cbfb0386)
![image](https://github.com/kubeedge/kubeedge/assets/47343901/79d4dda9-810f-4c52-9e49-83d8be8d8622)

cloud core 在运行，却没有端口

**Comment by Shelley-BaoYue** [comment]
Is `192.168. 200.128` your device ip? Because your cloudcore is deployed as a container in the cluster, you should use the nodeip of the master to access the edge.

**Comment by Albertchamberlain** [comment]
yes，i see，thanks you！192.168. 200.128 is the  k8s master ip，and there is two nodes 192.168.200.129 and 192.168.200.130，at beginning，the three machine in one k8s cluster。at last，edgecore  running in edge machine，it's ip is 192.168.200.131, i wanna use keadm let the edge machine to  join the k8s cluster。

**Comment by Albertchamberlain** [comment]
Another error happen

as you say，172.30.219.64 is the container nodeip。
so，crt error solved，but failed to read data from checkpoint

after run “keadm join --cloudcore-ipport=172.30.219.64:10000 --token=5c6c3d4967647b6d26262990d2feb205f9b70fee33253df7115f546”


![image](https://github.com/kubeedge/kubeedge/assets/47343901/0d6d1efb-efa9-4996-ba6f-e5929a0a3180)

**Comment by Albertchamberlain** [comment]
So，can't get the edgecore node status  on  k8s  master（running cloudcore） 
![image](https://github.com/kubeedge/kubeedge/assets/47343901/3a244559-a011-42c7-adae-07a987752e4e)

**Comment by Albertchamberlain** [comment]
![image](https://github.com/kubeedge/kubeedge/assets/47343901/4fb2dc9c-21e6-4a2c-aa44-fc83e2142fdf)

**Comment by yike21** [comment]
> Is `192.168. 200.128` your device ip? Because your cloudcore is deployed as a container in the cluster, you should use the nodeip of the master to access the edge.

Hi! @Shelley-BaoYue  I recently ran into some similar questions when trying to deploy a kubeedge cluster.

When `cloudcore` is deployed as a container, the `cloudcore svc` is accessed by way of the **clusterIP**.  May I ask how the edge node `edgecore` is accessing the ports `10000-10004` of `cloudcore` and registering to the cluster?

If I need to expose `cloudcore svc` using nodePort, and the default range of kubernetes for nodePort is 30000-32767. Does this mean that I need to first change the `cloudcore svc` to **nodePort** in the cloud, and then modify 
corresponding configurations such as `modules.edgeHub.httpServer` in `/etc/kubeedge/ config/edgecore.yaml` and restart `edgecore` on the edge?

I would appreciate your help in answering my questions!
