### ISSUE TITLE
边缘端pod用不了新建的configmap

### ISSUE THREAD

**Issue by ljjzhka** [kubeedge/kubeedge#4806]
**What happened**:
我创建了新的comfigmap，但是边缘的pod找不到。我看之前的issues出现过这个问题，但是1.13.0版本也存在。希望能修复

**Environment**:
- Kubernetes version (use `kubectl version`):   K8s版本为1.25.9
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):    Kubeedge版本为1.13.0

**Comment by vincentgoat** [comment]
Hi,
Can you provide more info about the pod yaml and the edgecore.log?

**Comment by ljjzhka** [comment]
> Hi, Can you provide more info about the pod yaml and the edgecore.log?

只需要创建新的comfigmap，然后pod使用它，就能复现这个问题。
我目前的解决方式是删除cloudcore容器让它重启，并重新将边缘加入集群，这样它才能同步到comfigmap资源。

**Comment by ljjzhka** [comment]
> Hi, Can you provide more info about the pod yaml and the edgecore.log?

如果可以的话也请帮我关注一下 #4782 ，它目前对我很重要

**Comment by vincentgoat** [comment]
I tried as below and it works fine, seems not a problem.
```
    ...
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
    ...

```
