### ISSUE TITLE
Cleanup edge modules.yaml from default configuration for unused modules.

### ISSUE THREAD

**Issue by trilokgm** [kubeedge/kubeedge#482]
**What happened**:

Default modules configuration in edge.yaml has dbTest which is not required unless a testcase being run.

**What you expected to happen**:

dbTest should not be enabled by default.

**Comment by CindyXing** [comment]
Agree with this request. Our test dependency shouldn't be in product. 

When first setting up KubeEdge, one would be asked to ensure c++ compiler installed. I assume it was due to dbtest.

**Comment by sids-b** [comment]
+1 
@CindyXing , gcc is required for setting up sqlite3.

**Comment by rohitsardesai83** [comment]
@trilokgm , any updates on this ?

**Comment by sids-b** [comment]
ping @trilokgm
