### ISSUE TITLE
For precious wireless bandwidth between cloud and edge，how often the EdgeHUB syncing cloud-side resource updates to the edge, and reporting edge-side host and device status changes to the cloud. It send only after changes, or periodically?  If periodically，Can the sending cycle be configured?

### ISSUE THREAD

**Issue by borlandor** [kubeedge/kubeedge#4824]
**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by Shelley-BaoYue** [comment]
The messages from cloud to edge are sent only after there are changes in cluster.  And the messages reported from edge to cloud contain both periodic messages and change-generated messages.  The reporting period can be configured by edgecore parameters, such as nodeStatusReportFrequency, syncFrequency, etc.

**Comment by borlandor** [comment]
Thanks a lot
