### ISSUE TITLE
Enable bootstrap and automatic (over-the-air) selfupgrade

### ISSUE THREAD

**Issue by CindyXing** [kubeedge/kubeedge#483]
**What would you like to be added**:
While we are releasing new versions of KubeEdge, we need to have a story to upgrade system components for existing customers. 

For new customers, we need to have a bootstrap mechanism for automatic installation (i.e. over-the-air) of KubeEdge components at the edge side. 
**Why is this needed**:
1. We need to have a bootstrap mechanism for installing the edgecore. The automation is especially valuable when we are considering large scale of edge nodes
2. We need to support upgrade the KubeEdge system component automatically. It is critical when we find security issue that the patch needs to be automatic upon large scale of edge nodes. For the upgrade, it is required to have no impact for any running customer applications. For example, customer applications using devicetwin or mqtt.

**Comment by sids-b** [comment]
This looks like a very valuable and must have feature.

**Comment by rohitsardesai83** [comment]
Pushing to backlog as it can't be done in 1.0 timeframe.
