### ISSUE TITLE
Enable health monitoring and automatic Edgesite patching/installation

### ISSUE THREAD

**Issue by CindyXing** [kubeedge/kubeedge#484]
**What would you like to be added**:
With the edgesite feature, we need to ensure health monitoring of each site. In case of issues, KubeEdge edgesite components can be patched/fixed reliably according some SLA.  

**Why is this needed**:
We need to ensure service quality for Edgesites.

**Comment by rohitsardesai83** [comment]
Is this achievable in 1.0 ? I think we can move this to backlog and address after 1.0
