### ISSUE TITLE
Randomly deployment application pod on KubeEdge node are not getting deleted

### ISSUE THREAD

**Issue by pavan187** [kubeedge/kubeedge#488]
**What happened**:
Application pod deployed in kubeedge node are not getting deleted.
**What you expected to happen**:
Application pod should be deleted when the deployment deleted
**How to reproduce it (as minimally and precisely as possible)**:
1. Setup KubeEdge Env
2. Created multiple deployments on to KubeEdge Node
3. Wait untill all pods come into Running state.
4. Delete all the deployements created on KubeEdge node.
5. Check all the pods deleted from KubeEdge Node.

**Anything else we need to know?**:
Issue is Random, Need to do the same test multiple times to reproduce the issue.
**Environment**:
- KubeEdge version: **v0.3.0-beta.0**
- Hardware configuration: NA
- OS (e.g. from /etc/os-release):Ubuntu 16.04
- Kernel (e.g. `uname -a`):NA
- Others:NA

![image](https://user-images.githubusercontent.com/45059377/57453631-82f73780-7284-11e9-8d44-77fa1ba01082.png)

**Comment by rohitsardesai83** [comment]
@sids-b , we need to check this soon.

**Comment by sids-b** [comment]
I think this will solve the problem https://github.com/kubeedge/beehive/pull/8 
cc @edisonxiang

**Comment by rohitsardesai83** [comment]
@m1093782566 , we need to merge https://github.com/kubeedge/beehive/pull/8 and upgrade beehive in vendor and verify this issue is fixed .

**Comment by sids-b** [comment]
@pavan187 , does this issue still persist ??
