### ISSUE TITLE
Failed to restart cloudcore

### ISSUE THREAD

**Issue by AXHMFHNP** [kubeedge/kubeedge#4912]
**What happened**:
After restarting cloudcore, it throws an error.
```
panic: interface conversion: interface {} is *v1alpha1.ObjectSync, not *v1alpha1.ClusterObjectSync

goroutine 582 [running]:
github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1.(*clusterObjectSyncLister).List.func1({0x189d4c0, 0x40036b0810})
	/go/src/github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go:53 +0xf8
github.com/kubeedge/kubeedge/vendor/k8s.io/client-go/tools/cache.ListAll({0x1bcd028, 0x40005ac9d8}, {0x1bc96e0, 0x400159ae10}, 0x4000812d38)
	/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/client-go/tools/cache/listers.go:40 +0xb8
github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1.(*clusterObjectSyncLister).List(0x40009c1140, {0x1bc96e0, 0x400159ae10})
	/go/src/github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go:52 +0x8c
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).deleteClusterObjectSyncs(0x4000805a00)
	/go/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:167 +0x64
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).Start(0x4000805a00)
	/go/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:109 +0x84
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.moduleKeeper({0x18e5c3e, 0xe}, 0x4000990990, {{0x18e5c3e, 0xe}, {0x18ddcda, 0x7}, {0x0, {0x0, 0x0}}})
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:77 +0xf0
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.StartModules
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:45 +0x428
```

**What you expected to happen**:
After restarting cloudcore, it can run correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Restarting cloudcore with clusterobjectsyncs resource present.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.24.13
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.14.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by AXHMFHNP** [comment]
I think the issue might be caused by saving the data obtained from the List operation by ClusterObjectSyncInformer as ObjectSync type.
https://github.com/kubeedge/kubeedge/blob/f23a1900d65efbe6002d410792ef11a3bad51621/pkg/apis/reliablesyncs/v1alpha1/type.go#L74-L83
https://github.com/kubeedge/kubeedge/blob/f23a1900d65efbe6002d410792ef11a3bad51621/pkg/client/informers/externalversions/reliablesyncs/v1alpha1/clusterobjectsync.go#L57-L77
So, the conversion to ClusterObjectSync type failed while calling the List method of clusterObjectSyncLister.
https://github.com/kubeedge/kubeedge/blob/f23a1900d65efbe6002d410792ef11a3bad51621/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go#L51-L56

**Comment by ZhengXinwei-F** [comment]
> I think the issue might be caused by saving the data obtained from the List operation by ClusterObjectSyncInformer as ObjectSync type.
> 
> https://github.com/kubeedge/kubeedge/blob/f23a1900d65efbe6002d410792ef11a3bad51621/pkg/apis/reliablesyncs/v1alpha1/type.go#L43-L52
> 
> 
> https://github.com/kubeedge/kubeedge/blob/f23a1900d65efbe6002d410792ef11a3bad51621/pkg/client/informers/externalversions/reliablesyncs/v1alpha1/clusterobjectsync.go#L57-L77
> 
> 
> So, the conversion to ClusterObjectSync type failed while calling the List method of clusterObjectSyncLister.
> https://github.com/kubeedge/kubeedge/blob/f23a1900d65efbe6002d410792ef11a3bad51621/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go#L51-L56

I submitted a PR to fix this problem. Could you review and confirm it?

**Comment by AXHMFHNP** [comment]
> > I think the issue might be caused by saving the data obtained from the List operation by ClusterObjectSyncInformer as ObjectSync type.
> > https://github.com/kubeedge/kubeedge/blob/f23a1900d65efbe6002d410792ef11a3bad51621/pkg/apis/reliablesyncs/v1alpha1/type.go#L43-L52
> > 
> > https://github.com/kubeedge/kubeedge/blob/f23a1900d65efbe6002d410792ef11a3bad51621/pkg/client/informers/externalversions/reliablesyncs/v1alpha1/clusterobjectsync.go#L57-L77
> > 
> > So, the conversion to ClusterObjectSync type failed while calling the List method of clusterObjectSyncLister.
> > https://github.com/kubeedge/kubeedge/blob/f23a1900d65efbe6002d410792ef11a3bad51621/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go#L51-L56
> 
> I submitted a PR to fix this issue. Could you please review and verify it? #4915

I have verified that cloudcore can restart correctly.
