### ISSUE TITLE
upgrade golang version

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#4930]
**What would you like to be added/modified**:

upgrade golang version 

**Why is this needed**:

Now KubeEdge dependence golang version is 1.17.  When we want to upgrade other dependent libs version, for example, bump k8s version to 1.26, we encounter compilation failures because k8s relies on golang v1.19. Therefore we need to upgrade golang version. 

We need to decide which version to upgrade to. @fisherxu  I recomment aligning with k8s v1.26 and upgrading golang version to 1.19

**Comment by fisherxu** [comment]
lgtm, let's follow the golang version of  k8s.

**Comment by saudch007** [comment]
Can I contrbute to this project?

**Comment by Shelley-BaoYue** [comment]
@saudch007  Sorry, I have already working for this issue. Thank you for your participation. You're welcome to review my pr or contribute with other issues. 😄
