### ISSUE TITLE
Web server support

### ISSUE THREAD

**Issue by alb12393** [kubeedge/kubeedge#4931]
**What happened and what you expected to happen**:
I am interested in deploying web services and exposing them on the Edge. Is this supported or a part of KubeEdge’s intentional features? If so, how can these services be exposed and accessed by users connected to the Edge without relying on resources present on the cloud?
I've found an example in your documentation where you deploy a nginx container on the Edge, but it doesn't show a way for the nginx server to be exposed externally from the Edge.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: v1.27.3

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
v1.12.1

**Comment by ZhengXinwei-F** [comment]
This is determined by your client's location. If the client can connect directly with the edge, it can take advantage of kubernetes' native service capability. If the client is in the cloud side,[**edgemesh** ](https://github.com/kubeedge/edgemesh)can be used for cloud-edge communication.

**Comment by alb12393** [comment]
Wouldn't using Kubernetes' services require a connection to the cluster and therefore the cloud? The edge doesn't have any innate Kubernetes components on it right?
Additionally based on your answer, is the basis of KubeEdge to maintain a constant connection between the cloud and edge or does it support the edge being disconnected and isolated?

**Comment by ZhengXinwei-F** [comment]
> Wouldn't using Kubernetes' services require a connection to the cluster and therefore the cloud? The edge doesn't have any innate Kubernetes components on it right? Additionally based on your answer, is KubeEdge designed with a constant connection between the cloud and edge in mind? Is the Edge designed to be a self-sustaining node if connection to the cloud is temporarily broken? If not, what are the actual intended use cases (can you give an example)?

Kubernetes svc simply provides a service discovery feature. kube-proxy will retrieve service and endpoint information and generate rules on the node. (Edgecore contains a data cache that can be utilized as an apiserver service when the connection to the cloud edge is lost.)

When your client is another in-cluster service located on the cloud side, or you expose this svc outside the cluster via ingress and lb, with the ingress controller or lb commonly located on the cloud side. The cloud-edge communication capabilities are required. #edgemesh

If your client is on an out-of-cluster node that can communicate directly with the edge node. Use nodeport directly and connect to it through edge-node-ip:nodeport-port.

**Comment by alb12393** [comment]
I understand now. Thanks for your replies!
