### ISSUE TITLE
kubeedge v1.13.1 删除了边缘节点配置中的 nodeip，作用是什么呢

### ISSUE THREAD

**Issue by wuxs** [kubeedge/kubeedge#4933]
**What happened and what you expected to happen**:

@Shelley-BaoYue 请问这个 commit https://github.com/kubeedge/kubeedge/commit/78eeb2e45ac4ca15c0f8100c75d6d9d06875ae6e 的作用是什么，为什么要将NodeIP删掉呢

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by ZhengXinwei-F** [comment]
This commit is to fix this issue #4638

**Comment by wuxs** [comment]
谢谢，了解了

**Comment by ZhengXinwei-F** [comment]
Thank you for your continued support of the kubeedge community.  : )
