### ISSUE TITLE
Should I create the cloudcore service manually next?

### ISSUE THREAD

**Issue by yike21** [kubeedge/kubeedge#4941]
**What happened and what you expected to happen**:
When I use keadm version 1.14.1 to initialize cloudcore, it seems that the cloudcore service is no longer created, which is differetn from [doc](https://kubeedge.io/docs/setup/install-with-keadm#keadm-init). I wonder know if I should create the `service` for cloudcore manually next.

**How to reproduce it (as minimally and precisely as possible)**:
```shell
keadm init --advertise-address=${CLOUDCORE_IP} --profile version=1.14.1 --kube-config=/root/.kube/config
```

**Anything else we need to know?**:
When I execute `kubectl get all -n kubeedge`, it shows that:
![image](https://github.com/kubeedge/kubeedge/assets/48058415/5fc9a596-3193-495d-adaf-24c9d7c00226)

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.4
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.14.1

**Comment by ZhengXinwei-F** [comment]
You can connect with cloudcore directly using its IP address. Service is not required because cloudcore is a hostnetwork container. 

Actually, edgecore cannot connect to the cluster using the ClusterIP service, because the edge node lacks the ability to forward clusterIP to podIP before connecting to the cluster.

**Comment by yike21** [comment]
> You can connect with cloudcore directly using its IP address. The Service is not necessary because cloudcore is a hostnetwork container.
> 
> Actually, edgecore cannot connect to the cluster using the ClusterIP service, because the edge node lacks the ability to forward clusterIP to podIP before connecting to the cluster.

I get it, thank you for clarification!

**Comment by ZhengXinwei-F** [comment]
> > You can connect with cloudcore directly using its IP address. The Service is not necessary because cloudcore is a hostnetwork container.
> > Actually, edgecore cannot connect to the cluster using the ClusterIP service, because the edge node lacks the ability to forward clusterIP to podIP before connecting to the cluster.
> 
> I get it, thank you for clarification!

:-)

**Comment by yike21** [comment]
OK, I will pay attention to this scene. 🚀
