### ISSUE TITLE
how change join token？

### ISSUE THREAD

**Issue by sunnoy** [kubeedge/kubeedge#4986]
**What happened and what you expected to happen**:

How to replace the token, to prevent token leakage of malicious registration node scenarios

Isn't it by way of the following

```bash
k delete secrets -n kubeedge tokensecret
k delete pod -n kubeedge cloudcore-6655556b49-clprc
keadm gettoken
```

Tested to work.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.14.1

**Comment by ZhengXinwei-F** [comment]
Hello and thank you for joining the kubeedge community conversation.
Do you wish to reissue a new token and revoke the feasibility of the current token?

**Comment by sunnoy** [comment]
> 

yes Fear of token leakage resulting in malicious registrations

**Comment by WillardHu** [comment]
The token refresh every 12 hours by default, you can configure `modules.cloudHub.tokenRefreshDuration` to modify schedule time in `cloudcore.yaml`. If you want to actively refresh the token, you can refer to the logic of code `cloud/pkg/cloudhub/servers/httpserver/signcerts.go L91-100` to update the secret `tokensecret` and refresh the token.
