### ISSUE TITLE
Deploy the devicemodel and device first, and then start the mapper. The mapper will remain stuck.

### ISSUE THREAD

**Issue by luomengY** [kubeedge/kubeedge#5021]
**What happened**:
I found that if you deploy devicemodel and device first and then start mapper, it will always get stuck here:
start grpc server
Insecure communication,skiping server......
However, deploying mapper first and then deploying devicemodel and device is normal.

**What you expected to happen**:
Deploying devicemodel and device and mapper should not be done regardless of the deployment order
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.21.2
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.14.0

**Comment by wbc6080** [comment]
The current way mapper manages devices is that the user submits a creation command in the cloud. After submitting the device model and instance information, the corresponding data is sent to the mapper through DMI. Therefore, if the model and instance information are submitted first, the mapper will not be able to obtain the corresponding information. We will try to fix this problem in the future. At the same time, you can also try to modify it if you like. Thank you for your contribution.

**Comment by luomengY** [comment]
> The current way mapper manages devices is that the user submits a creation command in the cloud. After submitting the device model and instance information, the corresponding data is sent to the mapper through DMI. Therefore, if the model and instance information are submitted first, the mapper will not be able to obtain the corresponding information. We will try to fix this problem in the future. At the same time, you can also try to modify it if you like. Thank you for your contribution.
Okay, I have resolved it and submitted the PR: https://github.com/kubeedge/kubeedge/pull/5036 .

**Comment by luomengY** [comment]
> The current way mapper manages devices is that the user submits a creation command in the cloud. After submitting the device model and instance information, the corresponding data is sent to the mapper through DMI. Therefore, if the model and instance information are submitted first, the mapper will not be able to obtain the corresponding information. We will try to fix this problem in the future. At the same time, you can also try to modify it if you like. Thank you for your contribution.

Okay, I have resolved it and submitted the PR: https://github.com/kubeedge/kubeedge/pull/5036 .
