### ISSUE TITLE
Change astaxie/beego to beego/beego

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#5024]
Now the go framework `beego` has been migrated to `github.com/beego/beego` from `github.com/astaxie/beego`,  and we still use the  `github.com/astaxie/beego`, let's change to `beego/beego`!

**Comment by MeenuyD** [comment]
Hello, @fisherxu should I need change all files?

**Comment by fisherxu** [comment]
And let's use `v1.12.2` of beego instead :)

**Comment by yeqiugt** [comment]
/assign 

Does it have to be version v1.12.2?
The latest version of v1 is v1.12.12, and the v2 version has also been released.

**Comment by fisherxu** [comment]
> The latest version of v1 is v1.12.12, and the v2 version has also been released.

**Comment by fisherxu** [comment]
> The latest version of v1 is v1.12.12, and the v2 version has also been released.

OK, v1.12.12 shoud be fine, I think I should mean 1.12.12 above, not sure what's the difference of v2 and v1, and the compatibility of them :) @yeqiugt
