### ISSUE TITLE
 Failed to unmarshal configfile /etc/kubeedge/config/edgecore.yaml

### ISSUE THREAD

**Issue by Sergiossrr** [kubeedge/kubeedge#5032]
**What happened**:
when i install edgemesh, to test if it works.but pods'status on edgenode is like this
**NAME                                  READY   STATUS        RESTARTS   AGE     IP       NODE        NOMINATED NODE   READINESS GATES
busybox-sleep-edge-675c5b84f8-q8hc2   0/1     Pending       0          62m     <none>   <none>      <none>           <none>
tcp-echo-edge-95649b6d8-7tdl9         0/1     Pending       0          62m     <none>   <none>      <none>           <none>**

so i check isula,kubelet,edgecore,then i find some errors using `journalctl -xe edgecore`,error inf is like this
**Failed to unmarshal configfile /etc/kubeedge/config/edgecore.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field Edged.modules.edged.clusterDNS of type string.**
**What you expected to happen**:
edgemesh pods on edgenode work
**Environment**:
- Kubernetes version (use `kubectl version`):1.20.2
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.8
- <details><summary>Cloud nodes Environment:</summary>

  
  - OS (e.g. `cat /etc/os-release`): OpenEuler 22.03 LTS
  - Kernel (e.g. `uname -a`):Linux

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):KubeEdge v1.8.0
  - OS (e.g. `cat /etc/os-release`):OpenEuler 22.03 LTS
  - Kernel (e.g. `uname -a`):Linux

  </details>

**Comment by Shelley-BaoYue** [comment]
It seems that the keadm version does not match the edgecore version. In addition, v1.8 is no longer maintained. You are advised to upgrade to a later version.

**Comment by Sergiossrr** [comment]
Done. Old kubeedge can't surpport ‘-’  , and i set clusterDNS "- 169.xx.xx.xx".After setting "169.xx.xx.xx" it is solved.
