### ISSUE TITLE
Error "namespaces \"null\" not found" in Message Dispatcher

### ISSUE THREAD

**Issue by Windrow14** [kubeedge/kubeedge#5042]
**What happened**:

When cloud side `dynamiccontroller`, and edge side `metaserver`, `servicebus` are enabled, if an edge side application wants to get a resource not related to `namespace`, such as `node`, `namespace` or some custom resources, the error in title exists.

`(*SelectorListener).sendObj` in `kubeedge/cloud/pkg/dynamiccontroller/application/listener.go` add "null" for namespace if namespace is not specified in the received object:
```
	namespace := accessor.GetNamespace()
	if namespace == "" {
		namespace = v2.NullNamespace
	}
```

Then, when the message comes to `(.messageDispatcher).enqueueAckMessage` in `kubeedge/cloud/pkg/cloudhub/dispatcher/message_dispatcher.go`, "null" is considered as a namespace name string:
```
	resourceNamespace, _ := messagelayer.GetNamespace(*msg)
...
	objectSync, err := md.objectSyncLister.ObjectSyncs(resourceNamespace).Get(objectSyncName)
```

I added some prints in that function. As you can see, when `node` is requested, the `resource` is:  
`MessageRoute.Resource: node/pc-k8s-192-168-0-121/null/node/pc-k8s-192-168-0-121`.

Then this error is reported before the return of the function:  
`"Failed to create objectSync" err="namespaces \"null\" not found" objectSyncName="pc-k8s-192-168-0-121.2da196e2-4f80-4fdb-bdc4-34c98687aed5" resourceNamespace="null" resourceName="pc-k8s-192-168-0-121"`.

Other resources also have the same problem.  
`namespace`:  
`node/pc-k8s-192-168-0-121/null/namespace/kubeedge`.  
Custom resource `ciliumidentity`:  
`node/pc-k8s-192-168-0-121/null/ciliumidentity/14444`.  

**What you expected to happen**:

Maybe we can use something does not bring confusion, such as "-". 

By the way, why `ObjectSyncs` was designed based on `namespace` at first? Maybe we should handle resources not related to `namespace` separately?

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable `metaserver` and `servicebus` on edge side and `dynamiccontroller` on cloud side.

2. Get some resource without specifying `namespace`.

**Anything else we need to know?**:

Other places use "null" for `NullNamespace` should also be modified.

A basic reason is, we do be able to create a `namespace` called "null" in a Kubernetes cluster:
```
windrow@k8s-node:~$ kubectl create namespace null
namespace/null created
windrow@k8s-node:~$ kubectl get namespace
NAME			STATUS		AGE
default			Active		56m
kube-node-lease		Active		56m
kube-public		Active		56m
kube-system		Active		56m
kubeedge		Active		51m
null			Active		18s
```

**Environment**:
- Kubernetes version: 1.22.16
- KubeEdge version: commit 669cef39bb40fc7ddd5b3fd61f9588542690ef25 (HEAD -> release-1.12, tag: v1.12.4, origin/release-1.12)
- OS: Ubuntu 20.04

**Comment by Shelley-BaoYue** [comment]
It seems has been solved in v1.14 with PR https://github.com/kubeedge/kubeedge/pull/4758.

**Comment by Windrow14** [comment]
> It seems has been solved in v1.14 with PR #4758.

@Shelley-BaoYue Oh, that's nice, I'm having a try.

By the way, I see v1.14 updating Kubernetes to 1.24, does it still support earlier usage with docker-shim? I just encountered some related problems when joining an edge node.

**Comment by Shelley-BaoYue** [comment]
https://github.com/kubeedge/kubeedge/issues/4843

**Comment by fujitatomoya** [comment]
@Windrow14 once you verify the behavior, please close this issue since this has been addressed.

@Shelley-BaoYue thanks 👍 really appreciate your information.

**Comment by fujitatomoya** [comment]
@Shelley-BaoYue can we close this in favor of https://github.com/kubeedge/kubeedge/pull/4758?
CC: @wujunyi792

**Comment by Shelley-BaoYue** [comment]
> @Shelley-BaoYue can we close this in favor of #4758? CC: @wujunyi792

Of course, if you have verified  😄

**Comment by fujitatomoya** [comment]
Sorry i missed @Windrow14 , this has been tested. so we can go ahead to close this?
