### ISSUE TITLE
Edge node retains logs during upgrade process

### ISSUE THREAD

**Issue by wlq1212** [kubeedge/kubeedge#5051]
**What happened**:

If the keadm upgrade fails, logs cannot be viewed, and troubleshooting is difficult

**What you expected to happen**:

Retain relevant logs during keadm upgrade process to facilitate troubleshooting

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by ZhengXinwei-F** [comment]
The reason for keadm's abnormal interruption cannot be displayed in nodeUpgradeJobs. 

To aid troubleshooting, the log of keadm's active exit should  be logged in nodeUpgradeJob.
