### ISSUE TITLE
边缘节点在断网情况下重启，使用了localpath PV卷的pod无法自动启动

### ISSUE THREAD

**Issue by youthantennalemon** [kubeedge/kubeedge#5060]
问题：边缘节点在断网情况下重启，使用了localpath PV卷的pod无法自动启动
希望的结果：边缘节点在断网情况下重启，使用了localpath PV卷的pod可以自动被edgecore拉起

复现过程
1. 安装local-path-provisioner作为localPV卷的提供者
2. 在边缘节点启动一个使用deployment控制器控制并且使用localPV卷的应用
3. 断开边缘节点的网络连接（拔掉网线，模拟边缘节点离线情况）
4. 重启边缘节点服务器后发现使用localPV卷的应用pod无法自动启动，其他不带PV卷的pod可以自动启动

查看边缘节点上edgecore的日志发现edgecore需要与云端的API server通信获取PV卷的什么信息，导致无法拉起pod
edgecore[1680]: E1009 11:26:12.084523    1680 pod_workers.go:915] "Error syncing pod, skipping" err="unmounted volumes=[database], unattached volumes=[database kube-api-access-j7vqd protocol-conf]: error processing PVC gw-test-01/elinker-database: failed to fetch PV pvc-3c4b66d1-86a1-4084-aef3-ebabd683e125 from API server: persistentvolume length from meta db is 0" pod="gw-test-01/edge-gw-5f48d56fd6-g8lpn" podUID=9a9d3349-48c4-4183-bb18-5dfb4cfad395

有没有办法让边缘节点在离线情况下重启后能自动拉起使用了localpath PV卷的pod？

版本信息
- Kubernetes version  v1.22.12
- KubeEdge version v1.12.1

**Comment by Shelley-BaoYue** [comment]
It seems the edge DB doesn't save the persistentvolume data, so edged cannot get persistentvolume date when offline.  I checked the code of edged that metemanager does save the persistentvolume data in edge DB.  
Could you please repeat your step 1&2? Raise the log level and after deploying the pod successfully, using `sqlite3 /var/lib/kubeedge/edgecore.db` to see if persistentvolume data has been stored in edge DB.

**Comment by youthantennalemon** [comment]
在启动了带有PV卷的pod后，在/var/lib/kubeedge/edgecore.db的meta表里面可以看到一条关于pvc的信息

**Comment by youthantennalemon** [comment]
在边缘节点启动了带有PV卷的pod后可以在/var/lib/kubeedge/edgecore.db的meta表里面发现一条关于pvc的记录，数据如下，但是没有发现pv相关信息的记录


![image](https://github.com/kubeedge/kubeedge/assets/125952990/6e7ac024-dcd9-4dbf-9fe0-55dcc218f57b)

gw-test-01/persistentvolumeclaim/elinker-database	persistentvolumeclaim	{"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"[kubectl.kubernetes.io/last-applied-configuration](http://kubectl.kubernetes.io/last-applied-configuration)":"{\"apiVersion\":\"v1\",\"kind\":\"PersistentVolumeClaim\",\"metadata\":{\"annotations\":{},\"name\":\"elinker-database\",\"namespace\":\"gw-test-01\"},\"spec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"10Gi\"}},\"storageClassName\":\"local-path\",\"volumeMode\":\"Filesystem\"}}\n","...

**Comment by Shelley-BaoYue** [comment]
It's so strange that pod status is running but pv data is not found in edge DB. Could you please raise the edgecore log level to ensure if there are any error log, especially in metamanager module(process.go)?

**Comment by youthantennalemon** [comment]
给edgecore加上--v=4启动参数，在边缘节点在线的情况下重启，记录edgecore的启动日志如下，直到使用了localPV卷的pod自动启动，没有发现process.go相关的报错
[edgecore.log](https://github.com/kubeedge/kubeedge/files/12855846/edgecore.log)
应用使用的pv的名称为“pvc-3c4b66d1-86a1-4084-aef3-ebabd683e125”
<img width="1279" alt="image" src="https://github.com/kubeedge/kubeedge/assets/125952990/a37c7203-854d-4df8-9c1d-c5dc796bcc5d">

**Comment by Shelley-BaoYue** [comment]
Hi, @youthantennalemon   I did reproduce this problem in my environment. Metamanager receives a deletion message for PV which the message source is edgecontroller, causing PV data cannot found in edge DB.  I'm still search for the actual reason, which may take some time. If you're interested, you can locate the problem based on the current phenomenon. 😄

**Comment by youthantennalemon** [comment]
@Shelley-BaoYue many thanks，我发现使用hostpath是一个替代pv卷作为边缘节点上pod持久化数据的办法，使用hostpath将数据放到节点上，即使边缘节点和cloudcore网络断开，重启边缘节点对应的pod也可以自动启动，我去定位上面的问题可能有点困难就不去深究了😂
