### ISSUE TITLE
Kubeedge v1.12.1 setup questions regarding rk3588

### ISSUE THREAD

**Issue by victorming666** [kubeedge/kubeedge#5062]
**What happened and what you expected to happen**:
Kubeedge v1.12.1 setup on Cloud-Edge-Cluster:
1. After installing docker+kubernetes+kubeedge on both 3 nodes(see following hardware), should the edge node(rk3588) run the command: "kubeadm join cloud_server_host:6443 ...." to join the kubernetes cluster? Not mentioned this in the setup docs.
2. Both Cloud Server and Edge Server all running normally, except the edge_node(rk3588), followings are the logs of edgecore on the edge node:

> Oct 09 17:17:16 GW3588 edgecore[41006]: W1009 17:17:16.276115   41006 context_channel.go:164] Get bad anonName: when sendresp message, do nothing
Oct 09 17:17:16 GW3588 edgecore[41006]: E1009 17:17:16.272223   41006 metaclient.go:117] send sync message kube-system/configmap/kubernetes-services-endpoint failed, error:timeout to get response for message 49931e0b-9b7c-4e54-9684-21e95f5b1a0c, retries: 1
Oct 09 17:18:16 GW3588 edgecore[41006]: E1009 17:18:16.278356   41006 metaclient.go:117] send sync message kube-system/configmap/kubernetes-services-endpoint failed, error:timeout to get response for message 49931e0b-9b7c-4e54-9684-21e95f5b1a0c, retries: 2
Oct 09 17:18:16 GW3588 edgecore[41006]: E1009 17:18:16.278923   41006 process.go:422] remote query failed, req[msgID[fb07546f-7ad5-4a5c-b505-5fa6c3a83772] resource[kube-system/configmap/kubernetes-services-endpoint]], err: timeout to get response for message fb07546f-7ad5-4a5c-b505-5fa6c3a83772
Oct 09 17:18:16 GW3588 edgecore[41006]: W1009 17:18:16.279063   41006 context_channel.go:164] Get bad anonName: when sendresp message, do nothing
Oct 09 17:18:16 GW3588 edgecore[41006]: E1009 17:18:16.279131   41006 kuberuntime_manager.go:898] init container &Container{Name:upgrade-ipam,Image:docker.io/calico/cni:v3.26.1,Command:[/opt/cni/bin/calico-ipam -upgrade],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{EnvVar{Name:KUBERNETES_NODE_NAME,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:spec.nodeName,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:CALICO_NETWORKING_BACKEND,Value:,ValueFrom:&EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:&ConfigMapKeySelector{LocalObjectReference:LocalObjectReference{Name:calico-config,},Key:calico_backend,Optional:nil,},SecretKeyRef:nil,},},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:host-local-net-dir,ReadOnly:false,MountPath:/var/lib/cni/networks,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:cni-bin-dir,ReadOnly:false,MountPath:/host/opt/cni/bin,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:kube-api-access-9wn29,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{EnvFromSource{Prefix:,ConfigMapRef:&ConfigMapEnvSource{LocalObjectReference:LocalObjectReference{Name:kubernetes-services-endpoint,},Optional:*true,},SecretRef:nil,},},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod calico-node-fhsrk_kube-system(212a0715-5bba-4bae-a476-bacc4fe39e97): CreateContainerConfigError: get configmap from metaManager failed, err: timed out waiting for the condition
Oct 09 17:18:16 GW3588 edgecore[41006]: E1009 17:18:16.279453   41006 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"upgrade-ipam\" with CreateContainerConfigError: \"get configmap from metaManager failed, err: timed out waiting for the condition\"" pod="kube-system/calico-node-fhsrk" podUID=212a0715-5bba-4bae-a476-bacc4fe39e97
Oct 09 17:19:16 GW3588 edgecore[41006]: E1009 17:19:16.696581   41006 process.go:422] remote query failed, req[msgID[43936217-5b72-4658-b0bf-1bffb3f74256] resource[kube-system/configmap/kubernetes-services-endpoint]], err: timeout to get response for message 43936217-5b72-4658-b0bf-1bffb3f74256
Oct 09 17:19:16 GW3588 edgecore[41006]: E1009 17:19:16.696794   41006 metaclient.go:117] send sync message kube-system/configmap/kubernetes-services-endpoint failed, error:timeout to get response for message e06e2b96-40da-4967-ab11-9ad47181638d, retries: 1
Oct 09 17:19:16 GW3588 edgecore[41006]: W1009 17:19:16.696949   41006 context_channel.go:164] Get bad anonName: when sendresp message, do nothing

The above shows the "calico-node-fhsrk" pod on edgenode failed, I want to know if it's caused as calico is not supported by Kubeedge, or simply since the edge node not joined the k8s cluster. Any helps will be appreciated!

**Environment**:
- Hardware: 3 nodes: amd64 GPU server as Cloud Server + amd64 CPU server as Edge Server + RK3588 as Edge Node 
- Kubernetes: v1.22.16-00
- Kubeedge: v1.12.1
- Docker: 24.0.5
- OS: Ubuntu 20.04

**Comment by Shelley-BaoYue** [comment]
1. no need to use 'kubeadm join',  using `keadm join` is enough to join edgecore to cluster. 
2. Has edgecore connected to cloud successfully? Using `kubectl get node` to see if edge node is ready.
3. calico is not required at edge. if you need to use calico, you need to enable metaserver and dynamiccontroller.

**Comment by victorming666** [comment]
Thanks! @Shelley-BaoYue. `kubectl get nodes` shows the edge node is ready:
![image](https://github.com/kubeedge/kubeedge/assets/44672506/29c7ed50-4d8c-40ce-bb62-6b3105b82fc5)
however, `kubectl get pods --all-namespaces` shows the calico pod failed to start:
![image](https://github.com/kubeedge/kubeedge/assets/44672506/aefcef9d-4481-4c9e-8b82-b2bb32ff1fc7)
If calico is not required at edge, how does the cloud server communicate with the edge node?

**Comment by Shelley-BaoYue** [comment]
kubectl get pods --all-namespaces shows the calico pod failed to start: 
-->  enable  dynamiccontroller in cloudcore config and enable metaserver in edgecore config

If calico is not required at edge, how does the cloud server communicate with the edge node? 
--> the subproject https://github.com/kubeedge/edgemesh of KubeEdge is responsible for it.

**Comment by victorming666** [comment]
OK，I will check the docs to see how to enable dynamiccontroller and metaserver. Thanks @Shelley-BaoYue .
