### ISSUE TITLE
ConatinerName should be given as a flag in run_daemon.sh

### ISSUE THREAD

**Issue by lidiyag** [kubeedge/kubeedge#507]
**What would you like to be added**:
![IssueContainerName](https://user-images.githubusercontent.com/14183934/57671116-f0fa8080-762f-11e9-9936-d0ffe6a7b4f1.png)
Here by default the name of container is always edgecore(github.com/kubeedge/kubeedge/build/edge/run_daemon.sh). The script should be able to take container name as a flag

**Why is this needed**:
This is required to run multiple containerized edgcores in a single host.

**Comment by lidiyag** [comment]
cc @rohitsardesai83  @sids-b  @edisonxiang  @pavan187

**Comment by sids-b** [comment]
Sounds Fair @lidiyag
