### ISSUE TITLE
What is the placement-url and how to modify it?

### ISSUE THREAD

**Issue by anna2018** [kubeedge/kubeedge#51]
I want to know what is placement-url: https://10.154.193.32:7444/v1/placement_external/message_queue in /conf/edge.yaml  ? If I want to modify it, what do I need to do?

**Comment by m1093782566** [comment]
@anna2018 

placement in kubeedge is used for finding the proper cloud controller(we may have more than one cloud controllers). Currently, users will not need to know much about placement-url as cloud controller is part of Huawei Cloud IEF service. Once cloud part of kubeedge is open-sourced, users will need to know more about placement.

For how to update the kubeedge config file(including placement-url), please check: https://github.com/kubeedge/kubeedge#integrate-with-huaweicloud-intelligent-edgefabric-ief
