### ISSUE TITLE
Upgrade Kubernetes dependency 

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#5117]
**What would you like to be added/modified**:

Now when we use version v1.26.7 of Kubernetes in v1.15.0， we need to upgrade it to newer version in release-1.16.

And in Kubernetes v1.26.7, there are two security issues when using Windows node, we need to upgrade it in KubeEdge release-1.15.

Ref: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.26.md#changelog-since-v1267

**Comment by Shelley-BaoYue** [comment]
For stability and version update frequency, we decided to upgrade Kubernetes deoendency to 1.27 in release 1.16

**Comment by Shiva953** [comment]
@Shelley-BaoYue could you elaborate more on this? which version(s) need to be changed, if any

**Comment by Shelley-BaoYue** [comment]
> @Shelley-BaoYue could you elaborate more on this? which version(s) need to be changed, if any

I have completed this work with PR https://github.com/kubeedge/kubeedge/pull/5121. But it relies on the go version upgrade, so I'll have to wait for you to complete the go version upgrade.
