### ISSUE TITLE
bump golang version to 1.20 

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#5122]
**What would you like to be added/modified**: 

bump golang version to 1.20 

**Why is this needed**:

Kubernetes v1.27 is developed based on go v1.20, and the minimum Go version must be 1.20. Before we bump kubernetes to 1.27, we need to upgrade go version first.

**Comment by Shiva953** [comment]
I would like taking this up

**Comment by Shelley-BaoYue** [comment]
Hi, @Shiva953 , welcome to contributing KubeEdge. I have submitted a PR #5123  to update the Go version in the build tool. You can complete this issue based on the PR. Also, you can refer to the PR https://github.com/kubeedge/kubeedge/pull/4938 that I bump go version to 1.19,

**Comment by Shiva953** [comment]
> Hi, @Shiva953 , welcome to contributing KubeEdge. I have submitted a PR #5123  to update the Go version in the build tool. You can complete this issue based on the PR. Also, you can refer to the PR https://github.com/kubeedge/kubeedge/pull/4938 that I bump go version to 1.19,

So I open a new PR with the same changes? Or some extra ones

**Comment by Shelley-BaoYue** [comment]
> > Hi, @Shiva953 , welcome to contributing KubeEdge. I have submitted a PR #5123  to update the Go version in the build tool. You can complete this issue based on the PR. Also, you can refer to the PR #4938 that I bump go version to 1.19,
> 
> So I open a new PR with the same changes? Or some extra ones

You need to do some extra ones, like PR #4938

**Comment by Shiva953** [comment]
@Shelley-BaoYue should I update the Alpine version to 3.18?

**Comment by Shelley-BaoYue** [comment]
No need in this issue, thank you. 😄

**Comment by Shelley-BaoYue** [comment]
@Shiva953  Hi, how is everything going?

**Comment by Shelley-BaoYue** [comment]
Sorry, @Shiva953  I have completed this issue with PR #5146 by myself, becasue the work upgrading kubernetes version is blocked. Still thank you for your participation, and you are welcome to participate in other work in the community.
