### ISSUE TITLE
Kubeedge and edgemesh installation doubt related to K8s cluster CNI

### ISSUE THREAD

**Issue by ravaga** [kubeedge/kubeedge#5153]
### Discussed in https://github.com/kubeedge/kubeedge/discussions/5145

<div type='discussions-op-text'>

<sup>Originally posted by **ravaga** November  6, 2023</sup>
Hello, I have a question regarding Kubeedge and edgemesh installation, more related to the interaction with the K8s cluster CNI.

Right now, I use as starting point a K8s cluster (v1.24.17) with a single node (the master node), in which I'm installing Flannel or Cilium as the cluster CNI.
Then, I install the cloud side of Kubeedge in the K8s cluster using _keadm_:

`keadm init --advertise-address="192.168.250.208" --profile version=v1.15.0 --kube-config=/root/.kube/config`

Once the cloud side is installed, I go to a VM running Ubuntu 22.04.3 LTS, in which I've previously installed _containerd_ as container runtime, and I join this edge node to the Kubeedge cluster using _keadm_:

`keadm join --cloudcore-ipport=192.168.250.208:10000 --token=<token> --kubeedge-version=v1.15.0 --cgroupdriver=systemd --runtimetype=remote
`

Now, the node has been registered in the K8s cluster and Kubeedge is working. Then, I follow the [Edgemesh instructions to install](https://edgemesh.netlify.app/guide/#install) it in the Kubeedge cluster and everything seems to be working properly.

However, the pod of the Flannel daemonset intended to be deployed in the edge node has always an _Error_ status.
`kube-flannel   kube-flannel-ds-lfqwl                          0/1     Error              937 (5m9s ago)    3d6h    192.168.250.241   kubeedge-faredge     <none>           <none>
`
![image](https://github.com/kubeedge/kubeedge/assets/19761628/227cb063-4211-4604-a359-208fd097d571)

So I have the following questions:

- Is this the expected working mode? 
- Am I installing properly Kubeedge and Edgemesh? 
- It is needed to not deploy the CNI related pods in the edge nodes? (e.g. in Cilium it can be done) 
- Should I try to install another CNI in the cluster (I tried Flannel, Calico and Cilium)

</div>

**Comment by Shelley-BaoYue** [comment]
Other CNI, like Flannel, Calico and Cilium are not needed.  You can check whether each agent of the edgemesh is running properly and use the edgemesh capability according to the document of edgemesh.

**Comment by ravaga** [comment]
Understood, an _edgemesh-agent_ pod is running properly in each node.

Just for clarification: when I install the K8s cluster before installing _Kubeedge_, is it not necessary to install a CNI (Flannel, Calico, Cilium...) if I install _Edgemesh_ ? Otherwise, if it's needed a CNI only for the K8s cluster nodes (not _Kubeedge_ nodes), need I to not deploy this CNI related pods in the  _Kubeedge_ nodes ?

Thanks for your help.

**Comment by sajiduni** [comment]
> ### Discussed in #5145
> Originally posted by **ravaga** November 6, 2023 Hello, I have a question regarding Kubeedge and edgemesh installation, more related to the interaction with the K8s cluster CNI.
> 
> Right now, I use as starting point a K8s cluster (v1.24.17) with a single node (the master node), in which I'm installing Flannel or Cilium as the cluster CNI. Then, I install the cloud side of Kubeedge in the K8s cluster using _keadm_:
> 
> `keadm init --advertise-address="192.168.250.208" --profile version=v1.15.0 --kube-config=/root/.kube/config`
> 
> Once the cloud side is installed, I go to a VM running Ubuntu 22.04.3 LTS, in which I've previously installed _containerd_ as container runtime, and I join this edge node to the Kubeedge cluster using _keadm_:
> 
> `keadm join --cloudcore-ipport=192.168.250.208:10000 --token=<token> --kubeedge-version=v1.15.0 --cgroupdriver=systemd --runtimetype=remote `
> 
> Now, the node has been registered in the K8s cluster and Kubeedge is working. Then, I follow the [Edgemesh instructions to install](https://edgemesh.netlify.app/guide/#install) it in the Kubeedge cluster and everything seems to be working properly.
> 
> However, the pod of the Flannel daemonset intended to be deployed in the edge node has always an _Error_ status. `kube-flannel kube-flannel-ds-lfqwl 0/1 Error 937 (5m9s ago) 3d6h 192.168.250.241 kubeedge-faredge <none> <none> ` ![image](https://user-images.githubusercontent.com/19761628/280778766-227cb063-4211-4604-a359-208fd097d571.png)
> 
> So I have the following questions:
> 
> * Is this the expected working mode?
> * Am I installing properly Kubeedge and Edgemesh?
> * It is needed to not deploy the CNI related pods in the edge nodes? (e.g. in Cilium it can be done)
> * Should I try to install another CNI in the cluster (I tried Flannel, Calico and Cilium)

I can't even install on Ubuntu 22.04

**Comment by ravaga** [comment]
Sorry @Shelley-BaoYue, can you please answer my last question in order to close the issue? Thanks in advance.

> Understood, an _edgemesh-agent_ pod is running properly in each node.
> 
> Just for clarification: when I install the K8s cluster before installing _Kubeedge_, is it not necessary to install a CNI (Flannel, Calico, Cilium...) if I install _Edgemesh_ ? Otherwise, if it's needed a CNI only for the K8s cluster nodes (not _Kubeedge_ nodes), need I to not deploy this CNI related pods in the _Kubeedge_ nodes ?
> 
> Thanks for your help.

**Comment by ravaga** [comment]
Closing the issue as I found a solution, which is explained in the original discussion thread #5145
