### ISSUE TITLE
边缘节点加入成功了，但是 启动容器无法正常启动，一直处于ContainerCreating

### ISSUE THREAD

**Issue by ithinkeng** [kubeedge/kubeedge#5158]
Windows  server  2019 

edgecore 版本 1.15.0

[kubeedge-v1.15.0-windows-amd64.tar.gz](https://github.com/kubeedge/kubeedge/releases/download/v1.15.0/kubeedge-v1.15.0-windows-amd64.tar.gz)

边缘节点加入成功了，但是 启动容器无法正常启动，一直处于ContainerCreating

配置文件：
`
edged:
    containerRuntime: remote
    enable: true
    ..........
    podSandboxImage: kubeedge/pause:3.6
   ............

`

将  ctr  images tag  mcr.microsoft.com/oss/kubernetes/pause:3.8   registry.k8s.io/pause:3.8  后依然报错

报错信息如下：

E1109 19:08:51.254666    3432 common.go:101] connect error: Network Error : dial tcp 127.0.0.1:1883: connectex: No connection could be made because the target machine actively refused it.
E1109 19:08:53.731318    3432 cri_stats_provider_windows.go:55] "Failed to fetch current HNS endpoints" err="failed during hnsCallRawResponse: hnsCall failed in Win32: Class not registered (0x80040154)"
E1109 19:08:53.731437    3432 eviction_manager.go:261] "Eviction manager: failed to get summary stats" err="failed to list pod stats: failed to list container network stats: failed during hnsCallRawResponse: hnsCall failed in Win32: Class not registered (0x80040154)"
E1109 19:08:53.885473    3432 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to get sandbox image \"registry.k8s.io/pause:3.8\": failed to pull image \"registry.k8s.io/pause:3.8\": failed to pull and unpack image \"registry.k8s.io/pause:3.8\": failed to resolve reference \"registry.k8s.io/pause:3.8\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.8\": dial tcp 74.125.204.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
E1109 19:08:53.885473    3432 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to get sandbox image \"registry.k8s.io/pause:3.8\": failed to pull image \"registry.k8s.io/pause:3.8\": failed to pull and unpack image \"registry.k8s.io/pause:3.8\": failed to resolve reference \"registry.k8s.io/pause:3.8\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.8\": dial tcp 74.125.204.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." pod="kubeedge/edgemesh-agent-9zhq8"
E1109 19:08:53.889615    3432 kuberuntime_manager.go:775] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to get sandbox image \"registry.k8s.io/pause:3.8\": failed to pull image \"registry.k8s.io/pause:3.8\": failed to pull and unpack image \"registry.k8s.io/pause:3.8\": failed to resolve reference \"registry.k8s.io/pause:3.8\": failed to do request: Head \"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.8\": dial tcp 74.125.204.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." pod="kubeedge/edgemesh-agent-9zhq8"
E1109 19:08:53.890657    3432 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"edgemesh-agent-9zhq8_kubeedge(24fc6b52-f760-41dd-90f5-a55a0feada3c)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"edgemesh-agent-9zhq8_kubeedge(24fc6b52-f760-41dd-90f5-a55a0feada3c)\\\": rpc error: code = Unknown desc = failed to get sandbox image \\\"registry.k8s.io/pause:3.8\\\": failed to pull image \\\"registry.k8s.io/pause:3.8\\\": failed to pull and unpack image \\\"registry.k8s.io/pause:3.8\\\": failed to resolve reference \\\"registry.k8s.io/pause:3.8\\\": failed to do request: Head \\\"https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.8\\\": dial tcp 74.125.204.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\"" pod="kubeedge/edgemesh-agent-9zhq8" podUID=24fc6b52-f760-41dd-90f5-a55a0feada3c

**Comment by Shelley-BaoYue** [comment]
将 ctr images tag mcr.microsoft.com/oss/kubernetes/pause:3.8 registry.k8s.io/pause:3.8 后依然报错 

> how about using `ctr -n k8s.io images tag` because kubelet uses k8s.io ns.   

And I'm not sure if edgemesh can run properly on Windows OS.

**Comment by ithinkeng** [comment]
> 将 ctr images tag mcr.microsoft.com/oss/kubernetes/pause:3.8 registry.k8s.io/pause:3.8 后依然报错
> 
> > how about using `ctr -n k8s.io images tag` because kubelet uses k8s.io ns.
> 
> And I'm not sure if edgemesh can run properly on Windows OS.

k8s  版本  1.26.7

windows 镜像的容器也跑不起来，registry.k8s.io/pause:3.8，config/edgecore.yaml  中是kubeedge/pause:3.6 
  ,   registry.k8s.io/pause:3.8  是在哪里配置的，回去拉取这个进行

**Comment by Shelley-BaoYue** [comment]
This is configured by the runtime you install. You can change it through the runtime configurations, like /etc/containerd/config.toml, /etc/crio/crio.config, which is up to your runtime type.

**Comment by ithinkeng** [comment]
> This is configured by the runtime you install. You can change it through the runtime configurations, like /etc/containerd/config.toml, /etc/crio/crio.config, which is up to your runtime type.

解决了，谢谢
