### ISSUE TITLE
docs: Add guidance for submitting changes to github and get accepted

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubeedge/kubeedge#517]
**What would you like to be added**:
Describe the workflow that we apply for checking-in changes.

**Why is this needed**:
Useful to new contributors.
ref: https://github.com/kubeedge/kubeedge/pull/506#issuecomment-492476244

**Comment by sids-b** [comment]
cc @rohitsardesai83 @naveensriram , we need to take this one up.
