### ISSUE TITLE
Lint is not being performed over for all the folders in repo

### ISSUE THREAD

**Issue by samy2019** [kubeedge/kubeedge#518]
**What happened**:
Lint is not being performed in all the folders in the repo. Hence the PR which has lint issues don't get detected and pass the lint test

**What you expected to happen**:
Lint should be performed over all the folders.
Code from Makefile

-------------------------------------------
.PHONY: edge_verify
edge_verify:
	cd edge && $(MAKE) verify
-------------------------------------------

It shouldn't change to "edge" folder and then execute verify.sh, it should run on root folder

**How to reproduce it (as minimally and precisely as possible)**:
Execute "make verify"

**Anything else we need to know?**:
NA

**Environment**:
- KubeEdge version: 0.2.1, 0.3.0-beta.0
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by sids-b** [comment]
Closing this issue as the scope is covered in #847
