### ISSUE TITLE
Keadm join reported error: 'failed to setup network for sandbox "d1c1700a789248876d60bc7581859394550bcb050820f3ee19784de67bf3d5f5": cni plugin not initialized'.

### ISSUE THREAD

**Issue by luomengY** [kubeedge/kubeedge#5195]
**What happened**:

When keadm joins, theoretically there is no need to install CNI plugins before edge nodes join the cluster. The installation of CNI plugins is usually done through kubectl apply - f kube flannel.yaml after installing them on the edge of the cloud (lite kubelet). The error is now reported as follows:
![cni](https://github.com/kubeedge/kubeedge/assets/110345347/99ea134d-cca6-450d-a830-6918551935b9)
**What you expected to happen**:
Users do not need to manually install CNI plugins on edge nodes before joining with keadm.
**How to reproduce it (as minimally and precisely as possible)**:
Step 1: remove the CNI plugin
Step 2: keadm join XXX
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.21.2
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):v1.15.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):v1.15.0
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by WeiguangYoung** [comment]
do you solve this preoblem?

**Comment by luomengY** [comment]
> do you solve this preoblem?

yes，https://github.com/kubeedge/kubeedge/pull/5196

**Comment by WeiguangYoung** [comment]
I see #5196 ，but i don't what I shoud do. Do I use keadm with the lastest version to retry?

**Comment by luomengY** [comment]
> I see #5196 ，but i don't what I shoud do. Do I use keadm with the lastest version to retry?

This PR has not been merged into the main branch yet. If you need to test, you can git clone this PR, then compile keadm, and then verify with the compiled keadm.

**Comment by WeiguangYoung** [comment]
okay. Thank you!

**Comment by WeiguangYoung** [comment]
I installed cni anyway by https://release-1-15.docs.kubeedge.io/docs/setup/prerequisites/runtime#virtlet.

**Comment by Shelley-BaoYue** [comment]
Hi，@luomengY， Can we discuss this issue further at tomorrow's community meeting for more in-depth conversation?

**Comment by luomengY** [comment]
> Hi，@luomengY， Can we discuss this issue further at tomorrow's community meeting for more in-depth conversation?

ok
