### ISSUE TITLE
Fix: node status of nodeGroup is wrong

### ISSUE THREAD

**Issue by Onion-of-dreamed** [kubeedge/kubeedge#5197]
**What happened**:
When adding a node that is already in a node group to a new node group, the failure reason prompts an error
ex:
i have put node test-1041he52cldd to the nodeGroup shanghai
<img width="476" alt="image" src="https://github.com/kubeedge/kubeedge/assets/42525411/8ab1670e-6eae-47b6-beb2-364c77c520f1">

then i select the node in another nodeGroup, the result
<img width="770" alt="image" src="https://github.com/kubeedge/kubeedge/assets/42525411/ebf9ac33-51ec-4a2c-9d7b-31e00bda9370">

It is obvious that the reason for the prompt is wrong.

**What you expected to happen**:

I hope he can display normal information to users
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.12.5
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Onion-of-dreamed** [comment]
sry, it's been fixed in #5107, hope it can be cherry pick to 1.12.5+ release

**Comment by Shelley-BaoYue** [comment]
> sry, it's been fixed in #5107, hope it can be cherry pick to 1.12.5+ release

Hi, @Onion-of-dreamed, Could you please help cherry-pick #5107 to 1.12 and other releases?

**Comment by fisherxu** [comment]
Seems we have picked to all the releases, can it be closed? @Onion-of-dreamed

**Comment by zhiyingfang2022** [comment]
Completed.
