### ISSUE TITLE
Device controller not copying data correctly to config map in the case of bluetooth

### ISSUE THREAD

**Issue by sujithsimon22** [kubeedge/kubeedge#521]
**What happened**:
Device controller not copying the data to the config map correctly in case of bluetooth devices in  the data write section of visitor config.

**What you expected to happen**:
The values given through the input files should not be modified
![image](https://user-images.githubusercontent.com/35599628/57766620-4c5a6a80-7725-11e9-999d-15d39803d18d.png)

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply the CC2650 device model and device instance placed at: https://github.com/kubeedge/kubeedge/tree/master/build/crd-samples/devices
2. Check the contents of the config map generated.

![image](https://user-images.githubusercontent.com/35599628/57766191-9000a480-7724-11e9-9d31-f97a5980e1a0.png)

**Anything else we need to know?**:
NA

**Environment**:
- KubeEdge version: v0.3
- Hardware configuration: 16GB/500 GB
- OS (e.g. from /etc/os-release): Ubuntu 18.04

**Comment by sujithsimon22** [comment]
@sids-b Can u pls take a look at this issue ?

**Comment by sids-b** [comment]
![propertyvisitor](https://user-images.githubusercontent.com/30088497/57771867-a19c7900-7731-11e9-95d8-d99e9631873f.png)
We just directly copy the full structure as is.

**Comment by sujithsimon22** [comment]
> ![propertyvisitor](https://user-images.githubusercontent.com/30088497/57771867-a19c7900-7731-11e9-95d8-d99e9631873f.png)
> We just directly copy the full structure as is.

@sids-b Actually the problem is not here. It looks to me like the data has come

**Comment by sujithsimon22** [comment]
@rohitsardesai83 @sids-b This issue seems to have been raised in the github repo of golang.  For your reference: https://github.com/golang/go/issues/16815

**Comment by rohitsardesai83** [comment]
I think we can change the value to an int instead of []byte , and then convert the int to a byte array in the code :  https://www.socketloop.com/tutorials/golang-convert-int-to-byte-array-byte

**Comment by sujithsimon22** [comment]
> I think we can change the value to an int instead of []byte , and then convert the int to a byte array in the code : https://www.socketloop.com/tutorials/golang-convert-int-to-byte-array-byte

@rohitsardesai83 if we convert int to byte array the value we expect will change. For example if we use the value 1 as integer we will get []byte value as [49] but we are expecting value as [1]

**Comment by sids-b** [comment]
@sujithsimon22 try this. It is working for me
```go
package main

import (
        "fmt"
	"encoding/binary"
)

func main() {
	bs := make([]byte, 4)
	binary.LittleEndian.PutUint32(bs, 1)
	fmt.Println(bs)
}
```

**Comment by sids-b** [comment]
1 thing to learn here is that we need priority labels. For eg: priority/low , priority/medium , priority/high

This way high priority issues can be identified easily and taken-up

**Comment by sids-b** [comment]
BTW, The package has many functions for Uint16, Uint8.... We can use whichever is suitable.

**Comment by sujithsimon22** [comment]
> @sujithsimon22 try this. It is working for me
> 
> ```go
> package main
> 
> import (
>         "fmt"
> 	"encoding/binary"
> )
> 
> func main() {
> 	bs := make([]byte, 4)
> 	binary.LittleEndian.PutUint32(bs, 1)
> 	fmt.Println(bs)
> }
> ```
@sids-b this method looks to be working, I guess we can go ahead with changing the value to int instead of []byte

**Comment by sujithsimon22** [comment]
@sids-b , @rohitsardesai83 I will change the implementation of bluetooth mapper according to this change, maybe either of you could take up changing []byte to int for device CRD ?? Thanks :)

**Comment by m1093782566** [comment]
I don't get the point of changing []byte to int for device CRD.

Can't we convert the string `configMap.Data[DeviceProfileJSON]` back to []byte and then Unmarshal the []byte to structed data? I just did a simple test, please check: https://play.golang.org/p/cEPY7QkTTUW

**Comment by sujithsimon22** [comment]
> I don't get the point of changing []byte to int for device CRD.
> 
> Can't we convert the string `configMap.Data[DeviceProfileJSON]` back to []byte and then Unmarshal the []byte to structed data? I just did a simple test, please check: https://play.golang.org/p/cEPY7QkTTUW
> 
> Am I missing something?

@m1093782566 While storing the data into config map doesn't it have to be in string format ? When we convert the marshalled data to string the []byte does not get stored in the manner we expect

**Comment by m1093782566** [comment]
> @m1093782566 While storing the data into config map doesn't it have to be in string format ? When we convert the marshalled data to string the []byte does not get stored in the manner we expect

Sorry I still don't understand. Can you please tell what you except for data store manner?

Struct -> []byte -> string(stored in configmap) -> []byte -> struct.

Does the dataflow works for you?

**Comment by sids-b** [comment]
+1 to @m1093782566 , I think the dataflow should not have any problem. 
1) Initial structure
2)  array of bytes when marshaled
3)  string(bytes)
4) string received at edge
5) Converted string back to bytes
6) Unmarshal back to structure

(3,4) , (2,5) , (1,6) should be same. At which point are they not same ?

**Comment by sids-b** [comment]
> > I don't get the point of changing []byte to int for device CRD.
> > Can't we convert the string `configMap.Data[DeviceProfileJSON]` back to []byte and then Unmarshal the []byte to structed data in the mapper? I just did a simple test, please check: https://play.golang.org/p/cEPY7QkTTUW
> > Am I missing something?
> 
> @m1093782566 While storing the data into config map doesn't it have to be in string format ? When we convert the marshalled data to string the []byte does not get stored in the manner we expect

the data field in v1.ConfigMap structure is of type map[string]string so it has to be string

**Comment by sujithsimon22** [comment]
> > @m1093782566 While storing the data into config map doesn't it have to be in string format ? When we convert the marshalled data to string the []byte does not get stored in the manner we expect
> 
> Sorry I still don't understand. Can you please tell what you except for data store manner?
> 
> I proposed:
> 
> Struct -> []byte -> string(stored in configmap, for base64 encoding or not, all depend on you) -> []byte -> struct.
> 
> Does the dataflow work for you?

looks like you are right @m1093782566 . Since the mapper converts the string --> []byte --> struct it will get the right values. Also since the only consumer of the config map is going to be the mapper, it does not make a difference whether the data stored in the configmap is in human readable form .

Hence closing this issue

**Comment by mg9** [comment]
Hi there, 
I have problems for generating configmaps.
After I applied the CC2650 device model and device instances any configmap hasn't been generated and when I do "kubectl get cm -o yaml" the only result returning is the information of edgecontroller configmap created at previous building cloud steps.
Is there something I should do after applying .yaml files to generate configmaps?

Thanks for your help,

> **What happened**:
> Device controller not copying the data to the config map correctly in case of bluetooth devices in the data write section of visitor config.
> 
> **What you expected to happen**:
> The values given through the input files should not be modified
> ![image](https://user-images.githubusercontent.com/35599628/57766620-4c5a6a80-7725-11e9-999d-15d39803d18d.png)
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> 1. Apply the CC2650 device model and device instance placed at: https://github.com/kubeedge/kubeedge/tree/master/build/crd-samples/devices
> 2. Check the contents of the config map generated.
> 
> ![image](https://user-images.githubusercontent.com/35599628/57766191-9000a480-7724-11e9-9d31-f97a5980e1a0.png)
> 
> **Anything else we need to know?**:
> NA
> 
> **Environment**:
> 
> * KubeEdge version: v0.3
> * Hardware configuration: 16GB/500 GB
> * OS (e.g. from /etc/os-release): Ubuntu 18.04
