### ISSUE TITLE
KubeEdge Installer: Add configurable parameters for all the required fields in controller.yaml and edge.yaml

### ISSUE THREAD

**Issue by samy2019** [kubeedge/kubeedge#522]
**What would you like to be added**:
Adding configurable parameters to KubeEdge init and join, so that it can be used to populate the required fields in controller.yaml and edge.yaml.

**Why is this needed**:
It gives more and better user experience to run own efficient KubeEdge environment and deployment.

**Comment by sids-b** [comment]
@kadisi do you plan to take this one up ? I see a PR was opened and closed to resolve this issue.

**Comment by sids-b** [comment]
ping @kadisi

**Comment by kadisi** [comment]
@sids-b  please assign to me ,  I am working on kubeedge configuration。
