### ISSUE TITLE
Simplify the pushmethod field in device instance CRD

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/kubeedge#5237]
**What would you like to be added/modified**:
We can create a new CRD to define the **pushmethod** field in device instance CRD, to make it simpler

**Why is this needed**:
The definition of the pushmethod field in the current device CRD is complicated, making the yaml file too long, like in #5064, so we can simplify it by referencing the new pushmethod CRD.

**Comment by fisherxu** [comment]
Now the DB config is for every property, I think it's necessary to add a global config for all properties in device spec if users only use one DB, how do you think? cc @WillardHu @luomengY @cl2017 @wbc6080

**Comment by WillardHu** [comment]
My main concern is that with more and more pushMethods, the lines of code defining the pushMethods will exceed the device itself, but using two CRDs will indeed be more expensive for use and development.

**Comment by wbc6080** [comment]
We had a preliminary discussion on this issue in the last regular device IoT meeting. There are two main options:
1. Create an additional pushmethod crd and let the device instance reference pushmethod crd.
2. Modify the mapper-framework and open the database push part of the dmi data plane， which users can implement the database push code by themselves. We may be able to delete the dbmethod field later and only place examples in mappers-go.

**Comment by wbc6080** [comment]
At the latest regular community meeting, we discussed and decided to transfer the common content of the dbmethod field to the spec field of device-instance, and also allow users to configure such as bucket, table and other contents of the database in the device properties. In this way, part of the content can be reused when pushing data and the length of the file can be reduced. I will implement a demo as an example as soon as possible for further discussion.

**Comment by wbc6080** [comment]
I integrated the parameter fields of the three current databases. We can fill in the common parameters in the spec field, and fill in the parameters with different attributes in the property field. The demo is as follows

**Comment by wbc6080** [comment]
influx database:
![influx](https://github.com/kubeedge/kubeedge/assets/48212997/2d36e303-eb20-433c-9fc4-593a851f126f)

**Comment by wbc6080** [comment]
redis database:
![redis](https://github.com/kubeedge/kubeedge/assets/48212997/49816abe-f192-424f-8bbf-d72084e859b9)

**Comment by wbc6080** [comment]
Please see if it can be defined like this
@WillardHu @fisherxu @luomengY @cl2017

**Comment by WillardHu** [comment]
I offer another way of thinking:
- The mapper framework provides an sdk for how to push data to the target source, like gorm;
- The configuration of the target source follows the Mapper framework, e.g.: config.yaml;
- Device properties set the unique identity of the data source in the config.yaml configuration file;

The collection of data to the push of the target source can be considered using the observer design.

**Comment by luomengY** [comment]
If I define multiple data sources, is it in the following format? @wbc6080 
![image](https://github.com/kubeedge/kubeedge/assets/110345347/da3cd9c2-2a78-489e-9840-523e7d766ac3)

**Comment by wbc6080** [comment]
After discussions at several community meetings, we believe that the current `pushmethod` field is only complicated in the crd definition, because all built-in database fields must be included here. But at the user level, you may only need to define one of the databases, so the device instance yaml file is not too complicated for users. We plan to maintain the status, and if there are better solutions or other needs later, we will reopen it.
