### ISSUE TITLE
Error "cni plugin not initialized" occured when executing "keadm join"

### ISSUE THREAD

**Issue by bluven** [kubeedge/kubeedge#5256]
**What happened**:
When I executed 'keadm join', this error happened:
```
I1204 07:37:24.155013    4423 command.go:901] 1. Check KubeEdge edgecore process status
I1204 07:37:24.165609    4423 command.go:901] 2. Check if the management directory is clean
I1204 07:37:24.165979    4423 join.go:107] 3. Create the necessary directories
I1204 07:37:24.181502    4423 join.go:184] 4. Pull Images
Pulling docker.io/library/eclipse-mosquitto:1.6.15 ...
Successfully pulled docker.io/library/eclipse-mosquitto:1.6.15
Pulling docker.io/kubeedge/installation-package:v1.15.1 ...
Successfully pulled docker.io/kubeedge/installation-package:v1.15.1
Pulling docker.io/kubeedge/pause:3.6 ...
Successfully pulled docker.io/kubeedge/pause:3.6
I1204 07:37:24.184935    4423 join.go:184] 5. Copy resources from the image to the management directory
E1204 07:37:24.304578    4423 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"23a26df6b2472c6cf2de78b9a2971dea3ed9dc811c1df1775446064f76232259\": cni plugin not initialized"
Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to setup network for sandbox "23a26df6b2472c6cf2de78b9a2971dea3ed9dc811c1df1775446064f76232259": cni plugin not initialized
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to setup network for sandbox "23a26df6b2472c6cf2de78b9a2971dea3ed9dc811c1df1775446064f76232259": cni plugin not initialized
```

**What you expected to happen**:

'keadm join' succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy contaienrd 
2. execute 'keadm join':
```
keadm join \
	--cloudcore-ipport=10.22.53.101:10000 \
	--token=0e0ca70c6fd090a086ef77e1ca44d92b2dcfeffff56fb332e3aeb0a27e2a1088.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDE3NTcxNTd9.lY8CbYZ57hnLJx0LYEQ4_y34Jf0-JDDWfz5G-ILQqyU \
	--kubeedge-version=v1.15.1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.15.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Shelley-BaoYue** [comment]
Some modification work is still in process such as PR #5196, but we still suggest to install cni-plugin .

**Comment by bluven** [comment]
There is still error happened even if I install cni and configured cni config:
```
I1205 06:08:58.489374   12784 command.go:901] 1. Check KubeEdge edgecore process status
I1205 06:08:58.506624   12784 command.go:901] 2. Check if the management directory is clean
I1205 06:08:58.506835   12784 join.go:107] 3. Create the necessary directories
I1205 06:08:58.549120   12784 join.go:184] 4. Pull Images
Pulling docker.io/kubeedge/installation-package:v1.15.1 ...
Successfully pulled docker.io/kubeedge/installation-package:v1.15.1
Pulling docker.io/library/eclipse-mosquitto:1.6.15 ...
Successfully pulled docker.io/library/eclipse-mosquitto:1.6.15
Pulling docker.io/kubeedge/pause:3.6 ...
Successfully pulled docker.io/kubeedge/pause:3.6
I1205 06:08:58.556135   12784 join.go:184] 5. Copy resources from the image to the management directory
E1205 06:08:58.562314   12784 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to reserve sandbox name \"edgecore_kubeedge__0\": name \"edgecore_kubeedge__0\" is reserved for \"23a26df6b2472c6cf2de78b9a2971dea3ed9dc811c1df1775446064f76232259\""
Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "23a26df6b2472c6cf2de78b9a2971dea3ed9dc811c1df1775446064f76232259"
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "23a26df6b2472c6cf2de78b9a2971dea3ed9dc811c1df1775446064f76232259"
```

**Comment by bluven** [comment]
> If you use `containerd` as runtime, you need to install runc and cni plugin as described in https://github.com/containerd/containerd/blob/main/docs/getting-started.md#installing-containerd



> I1205 06:08:58.556135   12784 join.go:184] 5. Copy resources from the image to the management directory

This happened because there was still a container which should be cleared by keadm, after delete it manually and restart containerd, problem resolved.

**Comment by bluven** [comment]
> There is still error even if I install cni and configured cni config:
> 
> ```
> I1205 06:08:58.489374   12784 command.go:901] 1. Check KubeEdge edgecore process status
> I1205 06:08:58.506624   12784 command.go:901] 2. Check if the management directory is clean
> I1205 06:08:58.506835   12784 join.go:107] 3. Create the necessary directories
> I1205 06:08:58.549120   12784 join.go:184] 4. Pull Images
> Pulling docker.io/kubeedge/installation-package:v1.15.1 ...
> Successfully pulled docker.io/kubeedge/installation-package:v1.15.1
> Pulling docker.io/library/eclipse-mosquitto:1.6.15 ...
> Successfully pulled docker.io/library/eclipse-mosquitto:1.6.15
> Pulling docker.io/kubeedge/pause:3.6 ...
> Successfully pulled docker.io/kubeedge/pause:3.6
> I1205 06:08:58.556135   12784 join.go:184] 5. Copy resources from the image to the management directory
> E1205 06:08:58.562314   12784 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to reserve sandbox name \"edgecore_kubeedge__0\": name \"edgecore_kubeedge__0\" is reserved for \"23a26df6b2472c6cf2de78b9a2971dea3ed9dc811c1df1775446064f76232259\""
> Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "23a26df6b2472c6cf2de78b9a2971dea3ed9dc811c1df1775446064f76232259"
> execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "23a26df6b2472c6cf2de78b9a2971dea3ed9dc811c1df1775446064f76232259"
> ```

This happened because there was still a container which should be cleared by keadm, after delete it manually and restart containerd, problem resolved.

**Comment by shawn-robusoft** [comment]
Have you successed?

**Comment by bluven** [comment]
@shawn-robusoft yes.

**Comment by shawn-robusoft** [comment]
> @shawn-robusoft yes.

how to  intall the cni ?
