### ISSUE TITLE
keadm used containerd.sock even if I set --remote-runtime-endpoint to another socket file

### ISSUE THREAD

**Issue by bluven** [kubeedge/kubeedge#5258]
**What happened**:
I installed docker and cri-dockerd on edge node and executed `keadm join` like this:
```
keadm join \
	--cloudcore-ipport=10.22.53.101:10000 \
	--token=0e0ca70c6fd090a086ef77e1ca44d92b2dcfeffff56fb332e3aeb0a27e2a1088.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDE3NTcxNTd9.lY8CbYZ57hnLJx0LYEQ4_y34Jf0-JDDWfz5G-ILQqyU \
	--remote-runtime-endpoint=unix:///run/cri-dockerd.sock \
	--kubeedge-version=v1.15.1
```
but got error:
```
I1204 09:01:30.277529   24238 command.go:901] 1. Check KubeEdge edgecore process status
I1204 09:01:30.288286   24238 command.go:901] 2. Check if the management directory is clean
I1204 09:01:30.288658   24238 join.go:107] 3. Create the necessary directories
I1204 09:01:30.311288   24238 join.go:184] 4. Pull Images
Pulling docker.io/kubeedge/installation-package:v1.15.1 ...
E1204 09:01:30.315057   24238 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = Error response from daemon: error creating temporary lease: connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\": unavailable" image="docker.io/kubeedge/installation-package:v1.15.1"
Error: edge node join failed: pull Images failed: rpc error: code = Unknown desc = Error response from daemon: error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout": unavailable
execute keadm command failed:  edge node join failed: pull Images failed: rpc error: code = Unknown desc = Error response from daemon: error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout": unavailable
```

**What you expected to happen**:

At lease some error related to docker or cri-docker.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install docker and [cri-dockerd](https://github.com/Mirantis/cri-dockerd)
2. Execute keadm join
```
keadm join \
	--cloudcore-ipport=10.22.53.101:10000 \
	--token=0e0ca70c6fd090a086ef77e1ca44d92b2dcfeffff56fb332e3aeb0a27e2a1088.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDE3NTcxNTd9.lY8CbYZ57hnLJx0LYEQ4_y34Jf0-JDDWfz5G-ILQqyU \
	--remote-runtime-endpoint=unix:///run/cri-dockerd.sock \
	--kubeedge-version=v1.15.1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.15.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by luomengY** [comment]
Do you compile your own keadm and then use the compiled keadm join to join edge nodes?

**Comment by luomengY** [comment]
The code for the master branch has been modified in this area. If you are compiling keadm using the latest master branch code, you need to compile both keadm and edgecore, and remake and replace the edgecore image to avoid this problem.

**Comment by hernando-garcia** [comment]
I am getting the same error as @bluven and although I do not use keadm (kubeadm) when debugging the problem with pulling images, it seems it is docker related:

```docker pull foo.bar.org/projectk8s/kube-apiserver:v1.28.2
Error response from daemon: error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout": unavailable```

Here are the versions: 

`k8s 1.28.2`
`cri-dockerd 0.3.7.20231027185657.170103f2-0.el8.x86_64`
`docker-ce 24.0.7-1.el8.x86_64`

**Comment by Shelley-BaoYue** [comment]
> I am getting the same error as @bluven and although I do not use keadm (kubeadm) when debugging the problem with pulling images, it seems it is docker related:
> 
> ```
> docker pull foo.bar.org/projectk8s/kube-apiserver:v1.28.2
> Error response from daemon: error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout": unavailable
> ```
> 
> Here are the versions:
> 
> ```
> k8s 1.28.2
> cri-dockerd 0.3.7.20231027185657.170103f2-0.el8.x86_64
> docker-ce 24.0.7-1.el8.x86_64
> ```

Thank you for your assistance. Maybe we can take a look at the installation status of cri-dockerd, or we can open an issue in the cri-dockerd community for further consultation.

**Comment by bluven** [comment]
> Do you compile your own keadm and then use the compiled keadm join to join edge nodes?

No, I didn't. But laster I used a keadm I compiled to debug and find out this might caused by containerd which I shut down accidentally. After I reboot containerd, the problem is gone.

I just don't understand why it still used the containerd.sock, it's confusing.

**Comment by bluven** [comment]
@Shelley-BaoYue This might occured as I shutdown containerd accidentally. 

I think this issue can be closed.
