### ISSUE TITLE
Why doesn't edge reference dockershim to support multiple container runtimes？

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#526]
**What would you like to be added**:

**Why is this needed**:
when i want let edge support multiple container runtime . i found that edge do not reference dockershim , and only use dockerclient to operator container directly。
```
edge/pkg/edged/dockertools/docker_manager.go
//CreateContainer creates container and returns ID
func (dm *DockerManager) CreateContainer(config *cri.ContainerConfig) (string, error) {
	ctx, cancel := dm.getTimeoutContext()
	defer cancel()
	dockerNetwork := &network.NetworkingConfig{}
	createResp, err := dm.client.ContainerCreate(ctx, config.Config, config.HostConfig, dockerNetwork, config.Name)
	if ctxErr := contextError(ctx); ctxErr != nil {
		return "", ctxErr
	}
	if err != nil {
		return "", err
	}
	return createResp.ID, nil
}
```
and if we only support docker, it is ok.

but if we support multiple container runtime, There will be a lot of trouble。 We lack a consistent cri implementation like kubelet。  if we do not use dockershime , We're going to change too much code to support multiple container runtimes.

**Comment by m1093782566** [comment]
@kadisi 

Yes, correct and CRI support is in our v1.0 roadmap.

**Comment by kadisi** [comment]
@m1093782566 can i let it support dockershim first ?

**Comment by m1093782566** [comment]
I think it's OK but let's discuss with @naveensriram and @gpinaik before starting the project.

**Comment by kadisi** [comment]
#295
