### ISSUE TITLE
Pod Deployment failed when EdgeCore re-initialized to use Quic from websocket

### ISSUE THREAD

**Issue by pavan187** [kubeedge/kubeedge#528]
**What happened**:
Pod Deployment is failing when re-initializing edgecore to use QUIC protocol from Websocket protocol.

**What you expected to happen**:
Pod deployment should be successful.
**How to reproduce it (as minimally and precisely as possible)**:
1. Setup Kubeedge Env
2. Register EdgeNode to K8s Master
2. Do the cloudcore deployment.
3. Do the Edgecore deployment with protocol: websocket (in edge.yaml)
4. Check is node is Ready.
5. Chnage the config(configMap) to  protocol:quic (node name should be same)
6. delete edgecore pod(not deployment), pod should be deleted and new pod should bring-up by k8s deployment object.
7. check node is in Ready state
8. do the application deployment on kubeedge edgenode.
9.Check the deployment is success and pod is in Running state.
10. Repeat steps 6 - 9 again 
11. check application deployment is successfull 2nd time.
**Actual result:**
2nd Application deployment is not success.
**Expected result:**
Application deployment should be successfull for all the time.

**Anything else we need to know?**:
This tests are performed by deploying cloudcore and edgecores as k8s deployment.

**Environment**:
- KubeEdge version: v0.3.0-beta.0
- Hardware configuration:NA
- OS (e.g. from /etc/os-release):Ubuntu16.04
- Kernel (e.g. `uname -a`):NA
- Others:NA

**Comment by pavan187** [comment]
[edge_core.logs.zip](https://github.com/kubeedge/kubeedge/files/3185730/edge_core.logs.zip)

**Comment by sids-b** [comment]
@pavan187 , Can you please verify once again ? We can reopen if the issue persists

**Comment by pavan187** [comment]
Thanks @shouhong @kexun , Issue is fixed now and it works fine.
