### ISSUE TITLE
Remove `--runtimetype` in keadm join in release 1.16 

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#5285]
**What would you like to be added/modified**: 

Remove `--runtimetype` in keadm join command 

**Why is this needed**:

Kubernetes v1.27 has removed `ContainerRuntime` flag for kubelet  -->  In KubeEdge next version, v1.16, the `--runtimetype` will no longer have any effect, and therefore it can be removed.

And from Kubernetes v1.24, the only valid value of `ContainerRuntime` is `remote`.  -->  From KubeEdge v1.14, due to the upgrade of Kubernetes dependency to version 1.24, the `--runtimetype` can only be configured as "remote."

I have evaluated the impact of the removal, the following observations have been made:
- Since the v1.14 version, we have already provided a notification that the runtimetype will be removed in v1.16.
- Following community standards, keadm needs to be compatible with the current version and the two previous versions. In other words, the v1.16 keadm needs to be compatible with v1.14 and v1.15. As mentioned earlier, the runtimetype only supports the "remote" from v1.14. Therefore, remove `--runtimetype` will not affect compatibility with older versions.

![image](https://github.com/kubeedge/kubeedge/assets/48788150/c677afbb-5dc2-4445-aac7-f2b881150371)

cc @fisherxu @WillardHu

**Comment by WillardHu** [comment]
+1 I think it's okey.
