### ISSUE TITLE
Build mapper image fail

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/kubeedge#5287]
**What happened**:
When we use mapper-framework to generate a mapper project, an error will occur if we directly build the mapper image.
![docker](https://github.com/kubeedge/kubeedge/assets/48212997/e20f26d0-9d82-4689-8a82-7764a1848497)

**What you expected to happen**:
Successfully built mapper image
**How to reproduce it (as minimally and precisely as possible)**:
Execute the make generate command in mapper-framework to generate the mapper project, and then docker build the image in the mapper project
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.15.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by niconiconi1234** [comment]
try `go mod tidy` before build?

**Comment by wbc6080** [comment]
> try `go mod tidy` before build?

Yes, this is a solution to the bug. I have proposed it in the PR #5288 . After using mapper-framework to generate the mapper project, execute the command `go mod tidy` to re-import the dependencies.
