### ISSUE TITLE
Stresstest : Randomly pod is taking long time to Delete/Create on KubeEdge node

### ISSUE THREAD

**Issue by pavan187** [kubeedge/kubeedge#529]
**What happened**:
Application deployed on KubeEdge node taking long time to comes into Running state/Deleting from EdgeNode.
**What you expected to happen**:
1. Ideally when the image exist in the KubeEdge node, application deployed on Edgenode should not take longtime. Same applies for delete pod , delete Pod should not take long time.

**Pod Creation logs:**
![image](https://user-images.githubusercontent.com/45059377/57856389-92d5c500-780a-11e9-9026-ea551d4e6dd6.png)

**Pod Deletion Logs:**
![image](https://user-images.githubusercontent.com/45059377/57856486-cc0e3500-780a-11e9-8354-dfda2cb2edc6.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup KubeEdge env
2. Check all KubeEdge node are Ready
3. Make sure application Image exist in the Edgenode
3.Create 100 deployments deployement object, and check application pods are coming into Running state in sometime.
4. Once all pods are Running, Delete the deployments.
5. Check the Pods are deleted from KubeEdge Nodes in sometime.
6. Repeat steps 3 to 5, for 4 to 5 times and check all the time pod creation and deletion happening proper time ?

Expected Result:
Pods should create and delete within sometime, should not take long time.
**Anything else we need to know?**:

**Environment**:
- KubeEdge version:v0.3.0-beta.0
- Hardware configuration:NA
- OS (e.g. from /etc/os-release):Ubuntu16.04
- Kernel (e.g. `uname -a`):Linux ubuntu-27 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others:NA

**Comment by sids-b** [comment]
Glad to see that we are finding issues with Performance testing. Thanks @edisonxiang and @pavan187 .

**Comment by ugvddm** [comment]
Hi @pavan187 , how many edge nodes in your test environment? was it spent time in schedule phase? how about the  resource usage of kube-apiserver/edge-controller and other component?  please post more information, thx.

**Comment by pavan187** [comment]
> urce usage of kube-apiserver/edge-controller and
@ugvddm , currently i tested with 20 EdgeNodes,  no delay in scheduling, issue is in pod creation and deletion on EdgeNodes, as it is observed that taking more time to create/delete.

Coming to resource utilization, currently im working on that, will post the info once it is done.
Thanks.

**Comment by ugvddm** [comment]
It's kind of weird, need more test

**Comment by sids-b** [comment]
@pavan187 @ugvddm ,I think it is because we are miss reliable message delivery and also because of resource limiting of edgecontroller container

**Comment by ugvddm** [comment]
That is a really problem, any plan?

**Comment by sids-b** [comment]
Not sure exactly. Need to think. Do you have a suggestion? @ugvddm

**Comment by ugvddm** [comment]
@sids-b , I have a simple idea to address it,  First of all, Edge core,  periodically, sends a full amount of information（e.g, pod, configmap） to the cloud side,  edgecontroller compare of it  that has been cached, and if it is inconsistent, sends a difference of section to the edge side,  edge side will be consistent with cloud side finally, thoughts?

**Comment by sids-b** [comment]
Yess, This PR does something similar. It checks if pod exists in cloud and if not, it will send delete message to edge core. https://github.com/kubeedge/kubeedge/pull/537

**Comment by ugvddm** [comment]
It's some different, All of operation will be cached in edge controller, include create/update/delete. when sync full info from edge side, we'll know that which message is missed, then resend it.

**Comment by sids-b** [comment]
@ugvddm Sounds like a plan. Can you raise a PR for this solution ?

**Comment by ugvddm** [comment]
yes ，but we need more discuss, @qizha  thoughts?

**Comment by pavan187** [comment]
@ugvddm @sids-b 
I have retested with simple application deployment (hello-world), i could see the application creation in edgenode itself is taking long time. for example i did a deployment of 100 applications into 1 Edgenode.
even though the image is exist in the EdgeNode the POD creation on EdgeNode is taking too long.

Please see the blow screenshots for reference
**Application contianers on EdgeNodes**
![image](https://user-images.githubusercontent.com/45059377/58021042-8497e980-7b27-11e9-883a-c385dc895d45.png)

i could see the first container came up  6min ago, overall around some 20 PODs came into Running after7min, and still edgenode is trying to bringup other continers as well..

i feel Its not really about reliable message delivery from edge to cloud, it is about edged bringing up the pods on Edgenode is having some issue.

**Comment by rohitsardesai83** [comment]
this issue needs to be fixed asap. This affects our performance numbers badly.

**Comment by sids-b** [comment]
I think this issue was reported fixed after increasing the value of qps, burst and then testing.

Closing this issue. Please reopen if this issue still persists.
