### ISSUE TITLE
No 'CONTRIBUTING.md' was found.

### ISSUE THREAD

**Issue by lubinsz** [kubeedge/kubeedge#53]
Hi all,
I'm from Arm.
My boss and legal department want to check the inbound&outbound license of this project.

Can you add the files of 'CONTRIBUTING.md'  ?

In general, the inbound license should be 'Developer Certificate of Origin, version 1.1'.
The outbound license should be 'Apache License 2.0'
And the legal information of inbound license should be in CONTRIBUTING.md.
The legal information of outbound license should be in LICENSE.md.

Please see the links as reference:
https://github.com/opencontainers/runc/blob/master/CONTRIBUTING.md
https://github.com/opencontainers/runc/blob/master/LICENSE
Thanks.

**Comment by m1093782566** [comment]
Nice catch! @lubinsz 

cc @kevin-wangzefeng

**Comment by m1093782566** [comment]
Please check out https://github.com/kubeedge/kubeedge/blob/master/CONTRIBUTING.md

**Comment by m1093782566** [comment]
I am going to close this issue as it's already there.
