### ISSUE TITLE
e2e test failing randomly

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#530]
**Which jobs are failing**:
e2e test job is failing

**Reason for failure**:
I suspect IP is not reachable sometimes.

**Comment by sids-b** [comment]
Lets try to make an alternative setup if the IP is not reachable. Many PR's CI is failing.

**Comment by pavan187** [comment]
> /assign @pavan187

Seems like environment issue api server response is getting timeout, redeployed the e2e env..now tests are passing.

**Comment by sids-b** [comment]
Thanks @pavan187 , I am closing the issue then.
