### ISSUE TITLE
failed to read message, error: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by vectornguyen76** [kubeedge/kubeedge#5304]
**What happened**:
CloudCore Logs:
```
I1212 09:41:03.251965       1 message_handler.go:122] edge node ip-10-0-0-114 for project e632aba927ea4ac2b575ec1603d56f10 connected
I1212 09:41:03.252036       1 node_session.go:136] Start session for edge node ip-10-0-0-114
I1212 09:41:03.256249       1 upstream.go:89] Dispatch message: 48c13d49-4754-4d5b-b24c-74fab2c28610
I1212 09:41:03.256319       1 upstream.go:96] Message: 48c13d49-4754-4d5b-b24c-74fab2c28610, resource type is: membership/detail
E1212 09:41:03.406176       1 ws.go:107] failed to read message, error: websocket: close 1006 (abnormal closure): unexpected EOF
E1212 09:41:03.406294       1 message_handler.go:166] projectID e632aba927ea4ac2b575ec1603d56f10 node ip-10-0-0-114 read message err
I1212 09:41:03.406331       1 message_handler.go:139] edge node ip-10-0-0-114 for project e632aba927ea4ac2b575ec1603d56f10 disConnected
W1212 09:41:03.406391       1 upstream.go:217] parse message: 7bacd8cc-e23f-4632-9a64-43fced3eae27 resource type with error, message resource: node/ip-10-0-0-114, err: resource type not found
```

Help me fix this error 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.28
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.12.6
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`): ubuntu 20.04
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`): 
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by mengjinmm** [comment]
How did you solve it? @vectornguyen76

**Comment by vectornguyen76** [comment]
@mengjinmm I have not yet resolved it. It's quite hard with me.

**Comment by vofr** [comment]
> [@mengjinmm](https://github.com/mengjinmm) I have not yet resolved it. It's quite hard with me.

Any news?
