### ISSUE TITLE
When use v1.15.1 , the version of device/devicemodel crd is old (v1alpha2), not v1beta1, which will cause the device can not been assign to node correctly. 

### ISSUE THREAD

**Issue by shawn-robusoft** [kubeedge/kubeedge#5306]
**What happened**: the device/device model crds version is older ones.

**What you expected to happen**:  version should be v1beta1

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.26.7
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.15.1
- <details><summary>Cloud nodes Environment:</summary> Public Cloud VM.

  - Hardware configuration (e.g. `lscpu`): intel
  - OS (e.g. `cat /etc/os-release`): CentOS7.9
  - Kernel (e.g. `uname -a`): /
  - Go version (e.g. `go version`): /
  - Others: /

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): /
  - Hardware configuration (e.g. `lscpu`): intel
  - OS (e.g. `cat /etc/os-release`):CentOS7.9
  - Kernel (e.g. `uname -a`):/
  - Go version (e.g. `go version`):/
  - Others:/

  </details>

I installed v1.15.1 kubeedge in k8s 1.26.7, when I use the python demo script  to subscribe to the device-node relationship topic of mqtt broker , I find the node has no devices even if I have created the device model and the device instance using v1alpha2  and the instance's node has been specified to the kubeedge node.
After deleted the old version  v1alpha2  crds and created with the version v1beta1 , the problem can be fixed.
I used the install command as bellow before:
docker run --rm kubeedge/installation-package:v1.15.1 cat /usr/local/bin/keadm > /usr/local/bin/keadm && chmod +x /usr/local/bin/keadm 
keadm init --advertise-address="172.16.0.100" --profile version=v1.15.1 --kube-config=/etc/kubernetes/admin.conf

**Comment by wbc6080** [comment]
I followed the same steps and tested multiple times locally, but no similar errors occurred. According to PR #5097 , similar problems should have been fixed, right? @luomengY

**Comment by wbc6080** [comment]
After discussions at our community meetings, it is believed that this problem has been fixed in v1.15.1. You can check whether the keadm version is the latest v1.15.1 and rebuild the cluster. Or was your cluster upgraded from a previous version? Maybe it’s because the crd of the previous version has not been deleted.
