### ISSUE TITLE
The join node, tip pull kubeedge/pause:3.1. The image is not actually used

### ISSUE THREAD

**Issue by wlq1212** [kubeedge/kubeedge#5309]
**What happened**:
The join node, tip pull kubeedge/pause:3.1. The image is not actually used

**What you expected to happen**:
pull “kubeedge/pause: 3.1”. The image is not actually used. advised to delete the pull“kubeedge/pause: 3.1” step

**How to reproduce it (as minimally and precisely as possible)**:
1. Use the keadm join node

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by ZhengXinwei-F** [comment]
Thanks for your contribution, this issue needs to be fixed.
