### ISSUE TITLE
Keadm Join Failed  Using V1.13.1 in k8s 1.26.7

### ISSUE THREAD

**Issue by shawn-robusoft** [kubeedge/kubeedge#5311]
**What happened**: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups 

**How to reproduce it (as minimally and precisely as possible)**: v1.26.7 K8S , v1.13.1 Kubeedge, K8S using containerd instead of docker, but docker is also been installed to use the "docker run --rm kubeedge/installation-package:v1.13.1 cat /usr/local/bin/keadm > /usr/local/bin/keadm && chmod +x /usr/local/bin/keadm" command.

**Anything else we need to know?**:

export hostname=`hostname`
keadm join --cloudcore-ipport=172.16.0.29:10000 --kubeedge-version=v1.13.1 --cgroupdriver=systemd -i $hostname --token=9cb1cd4df3fea2016b1417596c01c231515f8d7b992a9d6324ff22c8419890bc.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI1NjYzODN9.GoSrY5lkkCBgJ-rTid5OxnsbnwPCBXx7uN4MzSuheFo

I1214 09:16:50.827239   13185 command.go:845] 1. Check KubeEdge edgecore process status
I1214 09:16:50.832627   13185 command.go:845] 2. Check if the management directory is clean
I1214 09:16:50.832667   13185 join.go:107] 3. Create the necessary directories
I1214 09:16:50.836323   13185 join.go:184] 4. Pull Images
Pulling kubeedge/installation-package:v1.13.1 ...
Successfully pulled kubeedge/installation-package:v1.13.1
Pulling eclipse-mosquitto:1.6.15 ...
Successfully pulled eclipse-mosquitto:1.6.15
Pulling kubeedge/pause:3.6 ...
Successfully pulled kubeedge/pause:3.6
I1214 09:16:50.837272   13185 join.go:184] 5. Copy resources from the image to the management directory
E1214 09:16:50.936680   13185 remote_runtime.go:198] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format \"slice:prefix:name\" for systemd cgroups, got \"/k8s.io/98e4e4e4ca3c53084d5ab603e91e81b9f424f4ab3565e997ac5ab17941a8621f\" instead: unknown"
Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups, got "/k8s.io/98e4e4e4ca3c53084d5ab603e91e81b9f424f4ab3565e997ac5ab17941a8621f" instead: unknown
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups, got "/k8s.io/98e4e4e4ca3c53084d5ab603e91e81b9f424f4ab3565e997ac5ab17941a8621f" instead: unknown

<img width="1430" alt="image" src="https://github.com/kubeedge/kubeedge/assets/88022252/5b69a6d0-030d-4e02-9419-2e6821728828">

**Comment by shawn-robusoft** [comment]
Same issue but not fixed in v1.13.1?
https://github.com/kubeedge/kubeedge/issues/4969
Do we have any workarounds?

**Comment by Shelley-BaoYue** [comment]
Please use the newest patch version v1.13.4 of release 1.13.  More details in https://github.com/kubeedge/kubeedge/blob/master/CHANGELOG/CHANGELOG-1.13.md

**Comment by shawn-robusoft** [comment]
> Please use the newest patch version v1.13.4 of release 1.13. More details in https://github.com/kubeedge/kubeedge/blob/master/CHANGELOG/CHANGELOG-1.13.md

Thanks.It works.
