### ISSUE TITLE
run Kubernetes conformance tests in release CI 

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#5314]
**What would you like to be added/modified**: 

Add a job to run Kubernetes conformance tests in [main.yaml](https://github.com/kubeedge/kubeedge/blob/master/.github/workflows/main.yaml). When we add a new PR, we can run the Full-scale conformance tests.

Kubernetes conformance tests has been integrated in https://github.com/kubeedge/kubeedge/tree/master/build/conformance, we can achieve the job based on it. 

Now there are about 223 conformance test cases and it takes one and a half hours to run all the cases. We hope shorten the time with concurrency in CI

**Why is this needed**:

KubeEdge is built upon the native Kubernetes, so we need to ensure we can run Kubernetes conformance tests successfully. When we draft beta releases, we need to run the tests and solve the problem.

**Comment by jaydee029** [comment]
Hi , I would like to work on this. @Shelley-BaoYue

**Comment by Shelley-BaoYue** [comment]
Welcome! feel free to communicate here at any time.

**Comment by Shelley-BaoYue** [comment]
@jaydee029 Welcome! feel free to communicate here at any time.

**Comment by jaydee029** [comment]
Hey, @Shelley-BaoYue can you fill me up on how are we running them until now, any supported documentation?
Thanks.

**Comment by Shelley-BaoYue** [comment]
@jaydee029  Apologies for the delayed response. I hope this PR https://github.com/kubeedge/community/pull/144 can be helpful to you.

**Comment by jaydee029** [comment]
Thanks

**Comment by Shelley-BaoYue** [comment]
Sorry, due to a lack of progress for an extended period of time, /unassign @jaydee029

**Comment by jaydee029** [comment]
Hi @Shelley-BaoYue this issue got lost in my mails, apologies

**Comment by liyuerich** [comment]
got it. thanks.

**Comment by liyuerich** [comment]
Add a job to run Kubernetes conformance tests in [release.yml](https://github.com/kubeedge/kubeedge/blob/master/.github/workflows/release.yml). When we draft a new release, we can run the Full-scale conformance tests.

Besides run conformance tests before release, we also need to run conformance tests per PR. Then we need to run conformance tests in main.yml ?
