### ISSUE TITLE
Enhance the installation tool keadm

### ISSUE THREAD

**Issue by WillardHu** [kubeedge/kubeedge#5317]
**What would you like to be added/modified**:

1. [x] Refactor the implementation code for the cloud init command, use the gofile `keadm/cmd/keadm/app/cmd/helm/cloudcore.go` func `Install(..)` to complete the install logic.  https://github.com/kubeedge/kubeedge/pull/5461
2. [x] Change the print helm chart resources YAML command name`keadm generate` to `keadm manifest`. https://github.com/kubeedge/kubeedge/pull/5462
3. [x] Refactor the command `reset` to third-level commands, like: `keamd reset cloud` and `keadm reset edge`. If uses `keadm rest`, both the cloud and the edge will be reset. https://github.com/kubeedge/kubeedge/pull/5463
4. [x] Add a parent flag `--log-level` to the keadm and make it hidden for debug. https://github.com/kubeedge/kubeedge/pull/5547
5. [x] Add some custom image repository flags to `keadm init` and `keadm upgrade`. https://github.com/kubeedge/kubeedge/pull/5540
6. [x] Add a flag `--set` to edge command `keadm join` makes the edgecore to modify the configuration file `/etc/kubeedge/config/edgecore.yaml` before startup.  @HT0403
7. [ ] ~~Runtime-endpoint is automatically discrovered when the upgrade and reset commands are executed.~~

**Why is this needed**:

**Comment by Shelley-BaoYue** [comment]
“Add a flag --set to edge command keadm join makes the edgecore to modify the configuration file /etc/kubeedge/config/edgecore.yaml before startup.”

> I completely agree with this point. Could we discuss in community meeting whether to support modifying config using `--set` or allowing users to directly use the local edgecore.yaml?

**Comment by WillardHu** [comment]
> I completely agree with this point. Could we discuss in community meeting whether to support modifying config using `--set` or allowing users to directly use the local edgecore.yaml?

This can be discussed at community meeting.

**Comment by luomengY** [comment]
Add a flag --set to edge command keadm join makes the edgecore to modify the configuration file /etc/kubeedge/config/edgecore.yaml before startup.

**Comment by WillardHu** [comment]
Add a task: Runtime-endpoint is automatically discrovered when the upgrade and reset commands are executed.

**Comment by 528548004** [comment]
```
 Runtime-endpoint is automatically discrovered when the upgrade and reset commands are executed.
```

**Comment by 528548004** [comment]
> Runtime-endpoint is automatically discrovered when the upgrade and reset commands are executed.
When the runtime-endpoint assignment is empty, I get this value from the configuration file and give it to it. Am I understanding it correctly?
```
// updated runtime-endpoint
if reset.Endpoint == "" {
// Benchmarking v1.17
reset.Endpoint = config.Modules.Edged.TailoredKubeletConfig.ContainerRuntimeEndpoint
}
```

**Comment by WillardHu** [comment]
> > Runtime-endpoint is automatically discrovered when the upgrade and reset commands are executed.
> 
> ```
> // updated runtime-endpoint
> if reset.Endpoint == "" {
> // Benchmarking v1.17
> reset.Endpoint = config.Modules.Edged.TailoredKubeletConfig.ContainerRuntimeEndpoint
> }
> ```
> 
> When the runtime-endpoint assignment is empty, I get this value from the configuration file and give it to it. Am I understanding it correctly?

Yes, but it's only used to remove the static pod of mqtt, and we have used a DaemonSet to maintain the mqtt since v1.16.
So this flag `runtime-endpoint` may not be matter in the future...
