### ISSUE TITLE
handlePodListFromEdgeController don't work

### ISSUE THREAD

**Issue by lzx258** [kubeedge/kubeedge#532]
**What happened**:
```
func (e *edged) handlePodListFromEdgeController(content []byte) (err error) {
	var lists []v1.Pod
// lists is empty, why for...
	for _, list := range lists {
		err = json.Unmarshal(content, &list)
		if err != nil {
			return err
		}
		e.addPod(&list)
	}

	return nil
}
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by m1093782566** [comment]
cc @sids-b

**Comment by sids-b** [comment]
@lzx258 , can you please describe the issue more precisely ? Please answer these questions
1) What happened ?
2) What you expected to happen ?
3) How to reproduce it ?

**Comment by sids-b** [comment]
Ohh, I get it now @lzx258 , Thats a nice catch.
I think the solution would be to move UnMarshall above the for loop
```go
func (e *edged) handlePodListFromEdgeController(content []byte) (err error) {
	var lists []v1.Pod
	err = json.Unmarshal(content, &list)
	if err != nil {
		return err
	}
	for _, list := range lists {
		e.addPod(&list)
	}
	return nil
}
``` 

Can please verify the solution and raise PR with the fix? There is also a handlePodListFromMetaManager function just above this function for reference if the above solution causes some problem :)

**Comment by lzx258** [comment]
ok, I raise PR for this bug see https://github.com/kubeedge/kubeedge/pull/534 
pls review

thinks
