### ISSUE TITLE
Refine document description

### ISSUE THREAD

**Issue by yangbin1212** [kubeedge/kubeedge#533]
**What would you like to be added**:

Before running ./edgecontroller and Edge_core, is there any other need to modify this configuration file in addition to the configuration on the documentation?
edge.yaml (edge) inside the edged: **interface name: eth0**, this eth0 should be changed to the edge node's interface name, this I have changed，If not modified, edgenode will prompt an error and cannot find the network port.
controller.yaml (cloud) this controller:  **kubectl: kubeconfig: "" #Enter path to kubeconfig file to enable https connection to k8s apiserver** whether we need to modify, this is not very sure?

**Why is this needed**:

Because I am not sure if this is needed, I need it from the configuration file, but the operation documentation does not mention this too deliberately.

**Comment by m1093782566** [comment]
cc @srivatsav123
