### ISSUE TITLE
Maintain configuration folder in edge for new installation

### ISSUE THREAD

**Issue by ravaga** [kubeedge/kubeedge#5344]
**What happened and what you expected to happen**:
After a uninstalltion process in an edge node (removing the node from the cluster and using `keadm reset` command), I want to reinstall Kubeedge in the same machine (using the `keadm join` command) but maintaining the configuration folder (_/etc/kubeedge/config/_). However, I always receive the error message indicating that the Kubeedge folder is not empty.

Is there a way to do it? Can I install _Kubeedge edgecore_ running the `keadm join` command without removing the _/etc/kubeedge/config/edgecore.yaml_ file?

**Environment**:
- Kubernetes version: v1.24.17
- KubeEdge version: v1.15.1

**Comment by Shelley-BaoYue** [comment]
The original edgecore.yaml file is not supported currently. We do plan to achieve it in future release. You are welcome to participate in the discussion under the issue https://github.com/kubeedge/kubeedge/issues/5317 or feature development.

**Comment by ravaga** [comment]
Thanks for you response, I'll take a look to the discussion as it's an interesting feature.
