### ISSUE TITLE
StressTest :EdgeController is not updating node ready status to K8s Master

### ISSUE THREAD

**Issue by pavan187** [kubeedge/kubeedge#538]
**What happened**:
Deployed 50 EdgeNode through K8s Deployment.
Kubeedge node pods came up and Running in 30s of time, and nodestatus event being send to cloud. But KubeEdge Nodes ready status is not deing updated to k8s master by EdgeController.

**What you expected to happen**:
EdgeController should update the node ready status to k8s master as on when the event is received from EdgeNode.
*
**How to reproduce it (as minimally and precisely as possible)**:
1. Create KubeEdge Env.
2. Deploy Cloud as k8s deployment 
3. Deploy 50 KubeEdge nodes as  k8s deployment
4. wait untill all kubeEdge node pod comes into Running state
5. Do the kubectl get nodes from the k8s Master and check all EdgeNodes are in Ready state ?

Actual Result:
EdgeNode status is ""NotReady in K8s Master.

Expected Result:
EdgeNode status Must be in Ready

**Anything else we need to know?**:
This is tests are done by deploying Cloud and Edge nodes as k8s deployments.

**Environment**: ** Google Clouod Platform**
- KubeEdge version:v0.3.0-beta.0
- Hardware configuration:NA
- OS (e.g. from /etc/os-release):Ubuntu 16.04
- Kernel (e.g. `uname -a`):NA
- Others:NA

**Logs**:
![image](https://user-images.githubusercontent.com/45059377/57930875-b36a5180-78d4-11e9-875a-c3c942958bf9.png)

**Comment by sids-b** [comment]
@pavan187 , check the PR #536 . One cause for this could be the limiting of resources for edgecontroller. Since edge controller is a cloud component, we may not have resource constraint environment. That PR solves the issue. After the pr merge, we can verify this issue again.

**Comment by pavan187** [comment]
@sids-b , EdgeNodes are coming into running state after 3 to 4 minutes of time, i dont think the resource limit will solve the issue, issue is delay in updating the staus to master by edgecontroller

**Comment by sids-b** [comment]
Lets put some extra logs in this function https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/controller/controller/upstream.go#L244 and see at which point we are hitting error condition. The updateStatus function call has to executed successfully to update the node status in apiserver. The call is on line https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/controller/controller/upstream.go#L330

**Comment by rohitsardesai83** [comment]
This issue needs to be worked on asap. This is affecting our performance numbers.

**Comment by srivatsav123** [comment]
@pavan187 I was able to reproduce the issue..
One thing i noticed in the log is ,IT failed to update the node status which is clearly visible in the logs as attachd below..
![error](https://user-images.githubusercontent.com/39593583/59198421-5438ed80-8bb1-11e9-8e7d-242c34aee05b.png)
![code](https://user-images.githubusercontent.com/39593583/59200794-a4ff1500-8bb6-11e9-950a-3f8c6932d353.png)

As per the above error i was able to find some blogs 
![sol1](https://user-images.githubusercontent.com/39593583/59200366-ac71ee80-8bb5-11e9-9120-5a32dcbe4e43.png)
![sol2](https://user-images.githubusercontent.com/39593583/59200718-76813a00-8bb6-11e9-8370-e8fcc920bd5f.png)



https://github.com/kubernetes/kubernetes/issues/28149

https://github.com/kubeflow/kubeflow/issues/980

**Comment by edisonxiang** [comment]
Hi @pavan187 @srivatsav123 @sids-b @rohitsardesai83 
I tested in my environment.
I found the updatenodestatus function in the upstream.go may cost 400ms once.
and the message will stuck at this function.
As the message numbers are increased, this nodestatus will not be updated.
I tested 200 edge nodes, some node status will be firstly become Ready,
and then become NotReady. The node status is not stable.

I tried to modify the qps and burst of API here.
https://github.com/kubeedge/kubeedge/blob/master/cloud/conf/controller.yaml#L6-L7
change them into:
```
    qps: 200
    burst: 400
```
It seems like it works.
I tried 200 edge nodes in my env.
It is OK under the configrations `qps: 200` and `burst: 400`

I am not sure whether changing qps and burst configration can solve the issues #529 and #488

Could you help to verify it in your environment?
Thanks very much.

**Comment by pavan187** [comment]
@edisonxiang , Thanks for your input, Yes, with theese configurations we do the test again in our env for #538, @529, #488

**Comment by srivatsav123** [comment]
@edisonxiang 100 nodes are coming up in 55 secs after changing qps: 200
    burst: 400..
Thanks for your analysis and solution..

**Comment by edisonxiang** [comment]
@pavan187 @srivatsav123 great. Thanks your feedback.

**Comment by pavan187** [comment]
Closing after verification
