### ISSUE TITLE
pod 'ImagePullBackOff' error for local docker image

### ISSUE THREAD

**Issue by fatmanurozdemir** [kubeedge/kubeedge#5389]
I connected my ubuntu machine with Jetson Nano through a switch. I initiated a cluster on ubuntu machine and started cloudcore using keadm(v1.15.1). I joined jetson nano into the cluster successfully using `keadm join`. I can deploy simple nginx pod into Jetson Nano. When I want to deploy a model that uses the local docker image in the jetson nano, it gives 'ErrImagePull' error and then 'ImagePullBackOff' after many pulling attempts. I checked the jetson nano and the docker image exists.

**What you expected to happen**:
The deployment to pull the local image and run the model

**Environment**:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:42:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

keadm version(both master node and edge node): v1.15.1

**Comment by WillardHu** [comment]
This issue may be related to CRI. Normally, we need to use cri-dockerd uds `unix:///run/cri-dockerd.sock`.

**Comment by fatmanurozdemir** [comment]
@WillardHu yes it is.
#4843
