### ISSUE TITLE
Pulling docker.io/kubeedge/installation-package fail

### ISSUE THREAD

**Issue by zhangshuo32** [kubeedge/kubeedge#5395]
**keadm join fail when pulling docker.io/kubeedge/installation-package:v1.15.1**:

![image](https://github.com/kubeedge/kubeedge/assets/64187883/f954e220-7f97-44f5-8fbb-6dbf0f69e2bf)

I use docker to pull kubeedge/installation-package:v1.15.1 fist then try again, it returns the same issue

![image](https://github.com/kubeedge/kubeedge/assets/64187883/b18c8cab-44d4-4aca-b767-4513bc39ec2b)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27.1
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.15.1
- docker version 24.0.2
- containerd version 1.6.21
- ubuntu 18.04

/etc/containerd/config.toml

![image](https://github.com/kubeedge/kubeedge/assets/64187883/7d9771de-6315-4071-9b4c-b7655bc78585)

daemo.json

![image](https://github.com/kubeedge/kubeedge/assets/64187883/138eda1c-222c-477b-b9d3-93b6c0bd7e0d)

**Comment by Shelley-BaoYue** [comment]
You can use `ctr -n k8s.io pull {image}` to pull the installation image for you use `containerd` runtime in keadm join

**Comment by zhangshuo32** [comment]
problem solved， network issue， thanks！
