### ISSUE TITLE
boolean validation error.

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#54]
https://github.com/kubeedge/kubeedge/blob/3d599fea0b7e0823839043854beb7fdd1495d342/pkg/devicetwin/dtcommon/util.go#L33

the condition should be 
if strings.Compare(value, "true") != 0 && strings.Compare(value, "false") != 0 {

**Comment by m1093782566** [comment]
@sids-b I am shocked about that.

This kind bug is one of the reason that we should add more unit test codes for this project...

**Comment by m1093782566** [comment]
cc @Baoqiang-Zhang

**Comment by sids-b** [comment]
> @sids-b I am shocked about that.
> 
> This kind bug is one of the reasons that we should add more unit test codes for this project...

@m1093782566 Found this issue while writing UT for this package

**Comment by sids-b** [comment]
Issue addressed in pull request #59
