### ISSUE TITLE
Nameserver in /etc/resolv.conf of Edge Side Pod Is Always 127.0.0.53

### ISSUE THREAD

**Issue by Windrow14** [kubeedge/kubeedge#5400]
**What happened and what you expected to happen**:

1. I create a `busybox` `DaemonSet`. In pod created on cloud side, I can do `nslookup` normally, while it returns `nslookup: write to '127.0.0.53': Connection refused` in pod on edge side. By default, `dnsPolicy` is `ClusterFirst`, so the expected name server should be `10.96.0.10`, not `127.0.0.53`.

2. I set `dnsPolicy` to `ClusterFirst`, `ClusterFirstWithHostNet`, `Default` for the `busybox` `DaemonSet`, and check `/etc/resolv.conf` of the pod on edge side, it is always `nameserver 127.0.0.53    options edns0 trust-ad`. Not only this `busybox` pod, but all the other pods have the same `/etc/resolv.conf` file.

**How to reproduce it (as minimally and precisely as possible)**:

Just create a `KubeEdge` cluster, and check `/etc/resolv.conf` from edge side `kube-proxy` and cloud side `kube-proxy`. You can see the difference.
```
windrow@windrow-PC:~$ kubectl exec -it -n kube-system kube-proxy-bwj94 -- cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0 trust-ad
windrow@windrow-PC:~$ 
windrow@windrow-PC:~$ kubectl exec -it -n kube-system kube-proxy-xjf4d -- cat /etc/resolv.conf
nameserver 123.45.67.89
nameserver 123.45.67.90
```

**Anything else we need to know?**:

Is this expected behavior? Is there any module need to be enabled for edge side pod to DNS?

**Environment**:
- Kubernetes version: v1.26.7
- KubeEdge version: v1.15.1

**Comment by Windrow14** [comment]
In `containerd`, host's `/etc/resolv.conf` is used if `DNSConfig` passed from `cri-api` is empty.
```
        // Set DNS options. Maintain a resolv.conf for the sandbox.
        var err error
        resolvContent := ""
        if dnsConfig := config.GetDnsConfig(); dnsConfig != nil {
                resolvContent, err = parseDNSOptions(dnsConfig.Servers, dnsConfig.Searches, dnsConfig.Options)
                if err != nil {
                        return fmt.Errorf("failed to parse sandbox DNSConfig %+v: %w", dnsConfig, err)
                }
        }
        resolvPath := c.getResolvPath(id)
        if resolvContent == "" {
                // copy host's resolv.conf to resolvPath
                err = c.os.CopyFile(resolvConfPath, resolvPath, 0644)
```

**Comment by Windrow14** [comment]
We can add `clusterDNS` into `modules.edged.tailoredKubeletConfig` of `/etc/kubeedge/config/edgecore.yaml` on edge node to make `/etc/resolv.conf` in our pods to use `10.96.0.10` as nameserver instead of `127.0.0.53`.
```
      clusterDNS:
      - 10.96.0.10
```

**Comment by fujitatomoya** [comment]
@Windrow14 i guess this is intentional expected behavior to fetch the host system configuration instead of cluster IP address assigned by k8s? i think kubeedge edgecore is meant to be in the edge network, and expecting the fragile connectivity to the cloud via internet. so it intentionally avoids the configuration to access the cloud components.

as kubeedge community, it seems that edgemesh is responsible for this use case. see https://github.com/kubeedge/edgemesh/blob/main/README.md#why-edgemesh

**Comment by fujitatomoya** [comment]
> We can add clusterDNS into modules.edged.tailoredKubeletConfig of /etc/kubeedge/config/edgecore.yaml on edge node to make /etc/resolv.conf in our pods to use 10.96.0.10 as nameserver instead of 127.0.0.53.

KubeEdge support `TailoredKubeletConfiguration` that said we can set whatever kubelet can be configured. this could be work-around for us. `10.96.0.10` is assigned by IPM of cluster, after the cluster is ready, we need to update all edgecore configuration to join the cluster?

**Comment by ZhengXinwei-F** [comment]
It appears that [the kubelet configuration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) (resolvConf) has taken effect. The edge node's resolv configuration is used. And `127.0.0.53` is the systemd-resolved stub resolver in Ubuntu.

```
 root@kubeedge-dev-linux-0005  cat /etc/kubeedge/config/edgecore.yaml | grep resol          
      resolvConf: /etc/resolv.conf
```

```
resolvConf    resolvConf is the resolver configuration file used as the basis for the container DNS resolution configuration. If set to the empty string, will override the default and effectively disable DNS lookups. Default: "/etc/resolv.conf"
```

**Comment by ZhengXinwei-F** [comment]
You could try changing resolvConf to "" and specifying clusterDNS as a DNS address that edge pods can access. @Windrow14

**Comment by ZhengXinwei-F** [comment]
Like:
```
 ⚡  Mon 19 Feb - 15:24  /home/code/src/github.com/kubeedge/kubeedge   v1.16.0 1⚙ 1● 
 root@kubeedge-dev-linux-0005  cat /etc/kubeedge/config/edgecore.yaml | grep -A 3 resol 
      resolvConf: ""
      clusterDNS:
      - 8.8.8.8
      runtimeRequestTimeout: 2m0s

 ⚡  Mon 19 Feb - 15:25  /home/code/src/github.com/kubeedge/kubeedge   v1.16.0 1⚙ 1● 
 root@kubeedge-dev-linux-0005  crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
ddfb9bf5803ae       e4720093a3c13       26 seconds ago      Running             nginx               0                   a1ace9c50b1b7

 ⚡  Mon 19 Feb - 15:25  /home/code/src/github.com/kubeedge/kubeedge   v1.16.0 1⚙ 1● 
 root@kubeedge-dev-linux-0005  crictl exec -it ddfb9bf5803ae cat /etc/resolv.conf      
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 8.8.8.8
options ndots:5

 ⚡  Mon 19 Feb - 15:25  /home/code/src/github.com/kubeedge/kubeedge   v1.16.0 1⚙ 1● 
 root@kubeedge-dev-linux-0005  

```

**Comment by Windrow14** [comment]
I see your point.

By the way, `kubeadm` started using `/run/systemd/resolve/resolv.conf` for `resolvConf` since 2020, while most other tools are still using `/etc/resolv.conf`.

**Comment by ZhengXinwei-F** [comment]
> I see your point. Thanks for your answer and solution.
> 
> By the way, it seems `kubeadm` started using `/run/systemd/resolve/resolv.conf` for `resolvConf` since 2020, while most other tools are still using `/etc/resolv.conf`.

Maybe we could modify the default configuration.

**Comment by fujitatomoya** [comment]
@Windrow14 changing `resolv.conf` on edge devices seem to be a half-measure for me, does that really scale to hundreds devices on edge environment?

**Comment by ZhengXinwei-F** [comment]
> @Windrow14 changing `resolv.conf` on edge devices seem to be a half-measure for me, does that really scale to hundreds devices on edge environment?

The resolvConf configuration in Kubelet has the highest priority. It must be set to "" for other resolv to take effect. We plan to finish the remote configuration update capabilities of edge nodes by the first half of 2024. This feature could solve this issue.

**Comment by fujitatomoya** [comment]
@Windrow14 @ZhengXinwei-F thanks.

do we need to reopen this to track?

> It must be set to "" for other resolv to take effect. We plan to finish the remote configuration update capabilities of edge nodes

(if you have already) if possible could you elaborate the feature or idea a bit? i do not quite understand the capability of this feature.
