### ISSUE TITLE
suggest add metrics api on edged

### ISSUE THREAD

**Issue by googlebabaio** [kubeedge/kubeedge#541]
**What would you like to be added**:
add  metrics api on edged

**Why is this needed**:
such like metrics api on kubelet , can docking prometheus.

**Comment by sids-b** [comment]
@googlebabaio would you like to take this up ? Maybe share some of the detailed thoughts on what exactly you want to be added and how it can be achieved ?

**Comment by benjaminhuo** [comment]
https://github.com/kubeedge/kubeedge/pull/1573 I can see this PR has been merged
and the related issue https://github.com/kubeedge/kubeedge/issues/1561 has been added to v1.3 milestone.
