### ISSUE TITLE
Upgrade Kubernetes dependency to v1.28 

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#5411]
**What would you like to be added/modified**:

upgrade kubernetes dependency version to 1.28.

**Comment by mrks-g** [comment]
Does this mean kubeedge is compatible with v1.28.x (and newer versions)? The Docs do not include this info yet fyi. 
<img width="839" alt="image" src="https://github.com/kubeedge/kubeedge/assets/144018508/33894a66-c8c7-4dc5-8d07-3876f4ac105f">

**Comment by Shelley-BaoYue** [comment]
> Does this mean kubeedge is compatible with v1.28.x (and newer versions)? The Docs do not include this info yet fyi. <img alt="image" width="839" src="https://private-user-images.githubusercontent.com/144018508/304675479-33894a66-c8c7-4dc5-8d07-3876f4ac105f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDAxMjEsIm5iZiI6MTcwODIzOTgyMSwicGF0aCI6Ii8xNDQwMTg1MDgvMzA0Njc1NDc5LTMzODk0YTY2LWM4YzctNGRjNS04ZDA3LTM4NzZmNGFjMTA1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQwNzAzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWYwNDM3YWQ3ZTM0OTkyZDVjYWRlOTJkYTViZTBlZjcxYWE2OWNkM2I5ODIwZjdkNTRlYjZhOWUxYTM5NTQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mB_bc_1htTAsGdi-udRJiTIGKhvNapqYqrL_am77h_E">

This issue is still worl in progress. The master branch and the newest version 1.16 is compatible with v1.27
