### ISSUE TITLE
Add edge nodes in batches

### ISSUE THREAD

**Issue by ZhengXinwei-F** [kubeedge/kubeedge#5426]
**What would you like to be added/modified**:
I think it would be more elegant to accomplish this feature through documentation. Some modifications can also be made to the kubeedge code.

**Dynamic node addition**
- [ ]  If the node is newly created from the resource pool, we may consider using cloudinit to install edgecore.
- [ ]  Guide users to produce ISO images.

**Static node addition**

- [ ] Provide node adding scripts and usage instructions. 
- [ ] Ensure that the node to be added is in the same network area. Furthermore, the script must be performed on an execution computer that has SSH access to all of the nodes being added.
- [ ] Provide password and ssh-key login options.
- [ ] Consider using a remote ssh tool such as sshpass.

**Why is this needed**:

Currently, adding edge nodes requires users to log in to each node individually and manage them. Perhaps we can introduce node capabilities in batches.

**Comment by ZhengXinwei-F** [comment]
@Windrow14  Hi, are you interested in this feature?

**Comment by fisherxu** [comment]
We can consider to integrate the ansible tool

**Comment by luomengY** [comment]
I have a question. If edge nodes are added in batches on the cloud, the prerequisite is to ensure that the cloud can access the edges. However, in many cases, the cloud and edges cannot be directly connected through IP. Even with the Ansible tool, cloud to edge connectivity is still required.

**Comment by ZhengXinwei-F** [comment]
> I have a question. If edge nodes are added in batches on the cloud, the prerequisite is to ensure that the cloud can access the edges. However, in many cases, the cloud and edges cannot be directly connected through IP. Even with the Ansible tool, cloud to edge connectivity is still required.

Ensure that all nodes to be added are on the same network plane. Each node has a network foundation that connects to cloudcore.

**Comment by Windrow14** [comment]
@ZhengXinwei-F Is this the feature you mentioned here https://github.com/kubeedge/kubeedge/issues/5400#issuecomment-1955793837?

**Comment by XmchxUp** [comment]
@Shelley-BaoYue hi, does this feature support it?

> @ZhengXinwei-F Is this the feature you mentioned here [#5400 (comment)](https://github.com/kubeedge/kubeedge/issues/5400#issuecomment-1955793837)?
