### ISSUE TITLE
connectivity between edge side and cloud side

### ISSUE THREAD

**Issue by SherlockShemol** [kubeedge/kubeedge#5429]
When the edge side runs `keadm join` , how does the edge side find the cloud? Do they need to be on the same network? Or does the token contain network information?

**Comment by wbc6080** [comment]
According to my understanding，when executing `keadm join`, the IP address of the cloud node will be entered like `keadm join --cloudcore-ipport="THE-EXPOSED-IP":10000`. If edge node can curl the 10000 port of cloud node, this edge node can be added to the cluster

**Comment by SherlockShemol** [comment]
Thank you very much.
I ignored the ip parameter and it's clear that the ip address is the key point.
What a stupid question. Thank you again. 
And it makes sense why I can't keadm join because I didn't set the right ip address.

**Comment by SherlockShemol** [comment]
> According to my understanding，when executing `keadm join`, the IP address of the cloud node will be entered like `keadm join --cloudcore-ipport="THE-EXPOSED-IP":10000`. If edge node can curl the 10000 port of cloud node, this edge node can be added to the cluster

Thank you very much.
I ignored the ip parameter and it's clear that the ip address is the key point.
What a stupid question. Thank you again.
And it makes sense why I can't keadm join because I didn't set the right ip address.
