### ISSUE TITLE
keadm join failed.

### ISSUE THREAD

**Issue by LiShuang-codes** [kubeedge/kubeedge#5440]
**What happened and what you expected to happen**:  Command "keadm join" cannot exec successfully. The full cammand is 
`keadm join --cloudcore-ipport=192.168.107.10:10000 --edgenode-name=node01 --kubeedge-version=1.16.0 --token=133b7c3ef38528097ad0011f37278ef277a908e46bd9d88d2e1f1d62ca48b8d2.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDkxOTI2NDN9.Psvalt6A6eMf1NgliSuXFhQ6awYTnaANjSkWY15XugI --remote-runtime-endpoint=unix:///var/run/cri-dockerd.sock
`
The output is:
`
I0228 18:43:10.932798 4193367 command.go:901] 1. Check KubeEdge edgecore process status
I0228 18:43:11.182971 4193367 command.go:901] 2. Check if the management directory is clean
I0228 18:43:11.183700 4193367 join.go:94] 3. Create the necessary directories
I0228 18:43:11.235397 4193367 join_others.go:183] 4. Pull Images
Pulling kubeedge/installation-package:v1.16.0 ...
Successfully pulled kubeedge/installation-package:v1.16.0
I0228 18:43:11.257999 4193367 join_others.go:183] 5. Copy resources from the image to the management directory
E0228 18:43:14.005504 4193367 remote_runtime.go:326] "StartContainer from runtime service failed" err="rpc error: code = Unknown desc = failed to start container \"511c2e0ee8417da5a5a94e1bb61e7781a1ff0a49a055b69d6c9b6b946677f9c6\": Error response from daemon: cannot join network of a non running container: 6f6a3f5922c45a14fe25961c2e1a4413252c25619e43267f4ce8e135536b33de" containerID="511c2e0ee8417da5a5a94e1bb61e7781a1ff0a49a055b69d6c9b6b946677f9c6"
Error: edge node join failed: copy resources failed: start container failed: rpc error: code = Unknown desc = failed to start container "511c2e0ee8417da5a5a94e1bb61e7781a1ff0a49a055b69d6c9b6b946677f9c6": Error response from daemon: cannot join network of a non running container: 6f6a3f5922c45a14fe25961c2e1a4413252c25619e43267f4ce8e135536b33de
execute keadm command failed:  edge node join failed: copy resources failed: start container failed: rpc error: code = Unknown desc = failed to start container "511c2e0ee8417da5a5a94e1bb61e7781a1ff0a49a055b69d6c9b6b946677f9c6": Error response from daemon: cannot join network of a non running container: 6f6a3f5922c45a14fe25961c2e1a4413252c25619e43267f4ce8e135536b33de
`
I can be sure that the docker is in cgroupfs mode and "unix:///var/run/cri-dockerd.sock" works properly. 
**How to reproduce it (as minimally and precisely as possible)**: I think that reproduce is unecessarily. You may givesome tips about this problem.

**Anything else we need to know?**: Nothing.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.26.9
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.16..0
- System: Ubuntu 20.04 LTS
- Docker version: 24.0.7

**Comment by LiShuang-codes** [comment]
The problem solved. The cloudcore listrning on port 2349 and 2350, not 10000. Idont know why, and I want an official answer.

**Comment by WillardHu** [comment]
This error occurs when running container copy resources, possibly related to the sendbox image pause:3.6.

By default, the cloudcore websocket listens to port 10000. Ports 2349, 2350 and more {port}+1 are used for the iptables routing to the stream port 10003.

**Comment by LiShuang-codes** [comment]
> This error occurs when running container copy resources, possibly related to the sendbox image pause:3.6.
> 
> By default, the cloudcore websocket listens to port 10000. Ports 2349, 2350 and more {port}+1 are used for the iptables routing to the stream port 10003 (For proxy kubelet port).

You are right. but why does my 'cloudcore websocket' not listens to port 10000? see problem #5442 . Now i cannot reproduce the problem, because after  reset the cloudcore and i cannot start it.

**Comment by WillardHu** [comment]
> You are right. but why does my 'cloudcore websocket' not listens to port 10000? see problem #5442 . Now i cannot reproduce the problem, because after reset the cloudcore and i cannot start it.

I commeneted on the issue #5442. For the websocket port, we can see the code:
https://github.com/kubeedge/kubeedge/blob/487b3687bb380a0ef9dd6ecec92d039bf88e47c9/cloud/pkg/cloudhub/servers/server.go#L63
It just uses the property `modules.cloudHub.websocket.prot` in cloudcore.yaml
