### ISSUE TITLE
EdgeCore.service持续显示connect error

### ISSUE THREAD

**Issue by LiShuang-codes** [kubeedge/kubeedge#5446]
**What happened and what you expected to happen**:
执行`journalctl -u edgecore.service -xb`，下面的错误log重复出现
```
Mar 02 16:52:06 node01 edgecore[15277]: I0302 16:52:06.666115   15277 common.go:97] start connect to mqtt server with client id: hub-client-sub-1709351484
Mar 02 16:52:06 node01 edgecore[15277]: I0302 16:52:06.666466   15277 common.go:99] client hub-client-sub-1709351484 isconnected: false
Mar 02 16:52:06 node01 edgecore[15277]: E0302 16:52:06.668784   15277 common.go:101] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Mar 02 16:52:07 node01 edgecore[15277]: I0302 16:52:07.182320   15277 scope.go:115] "RemoveContainer" containerID="bd7394fce2568ad3f65c72fc5ec9ea6093917abae60b79e1670761f13115535a"
Mar 02 16:52:07 node01 edgecore[15277]: E0302 16:52:07.187748   15277 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=kube-flannel pod=kube-flannel-ds-qbv5r_kube-flannel(1d7151a0-2228-4b64-9333-3fd720d9ae54)\"" pod="kube-flannel/kube-flannel-ds-qbv5r" podUID=1d7151a0-2228-4b64-9333-3fd720d9ae54
Mar 02 16:52:11 node01 edgecore[15277]: I0302 16:52:11.669656   15277 common.go:97] start connect to mqtt server with client id: hub-client-sub-1709351484
Mar 02 16:52:11 node01 edgecore[15277]: I0302 16:52:11.669963   15277 common.go:99] client hub-client-sub-1709351484 isconnected: false
Mar 02 16:52:11 node01 edgecore[15277]: E0302 16:52:11.672028   15277 common.go:101] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
Mar 02 16:52:15 node01 edgecore[15277]: E0302 16:52:15.077085   15277 cri_stats_provider.go:455] "Failed to get the info of the filesystem with mountpoint" err="cannot find filesystem info for device \"/dev/sda5\"" mountpoint="/var/lib/docker"
...重复上面的内容...
```
**How to reproduce it (as minimally and precisely as possible)**:
正常安装edgecore，而且edge正常加入cloudcore，kubectl get nodes也显示edge是ready的，如果使用后续有问题还会更新
**Anything else we need to know?**:
没有
**Environment**:
- Kubernetes version (use `kubectl version`):1.26.7
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.15.2

**Comment by Piwriw** [comment]
你是指“connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused”吗？，这是因为你并没有安装mqtt Broker

**Comment by LiShuang-codes** [comment]
> 你是指“connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused”吗？，这是因为你并没有安装mqtt Broker

请问这个mqtt Broker是cloudcore和edgecore都要安装吗？我忘了之前在哪里看到的，说安装kubeedge自带mqtt，安装的mqtt要卸载，否则会占用kubeedge的1883端口，所以我才没有安装

**Comment by Piwriw** [comment]
> > 你是指“connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused”吗？，这是因为你并没有安装mqtt Broker
> 
> 请问这个mqtt Broker是cloudcore和edgecore都要安装吗？我忘了之前在哪里看到的，说安装kubeedge自带mqtt，安装的mqtt要卸载，否则会占用kubeedge的1883端口，所以我才没有安装
你应该在`keadm join`的时候使用with-mqtt=true加入，在之后版本中会使用ds管理，具体的PR在https://github.com/kubeedge/kubeedge/issues/5233

**Comment by LiShuang-codes** [comment]
> > > 你是指“connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused”吗？，这是因为你并没有安装mqtt Broker
> > 
> > 
> > 请问这个mqtt Broker是cloudcore和edgecore都要安装吗？我忘了之前在哪里看到的，说安装kubeedge自带mqtt，安装的mqtt要卸载，否则会占用kubeedge的1883端口，所以我才没有安装
> > 你应该在`keadm join`的时候使用with-mqtt=true加入，在之后版本中会使用ds管理，具体的PR在#5233

在添加这个参数后，keadm join又加不了集群了。详细信息如下：
```
root@node01:~# keadm join --cloudcore-ipport=192.168.107.10:10000 --edgenode-name=node01 --kubeedge-version=1.15.2 --token=63ee5b45f79fb2941ac7c341f3fdf7dd3d1bd23444a489723dd334c40d7243b3.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDk2MDA1NzV9.bPBmxhPuehLPvWj1JezTX0ITAdhEwmTQqDW876qfU4A --remote-runtime-endpoint=unix:///var/run/cri-dockerd.sock --with-mqtt
I0304 13:17:12.632920  237615 command.go:901] 1. Check KubeEdge edgecore process status
I0304 13:17:12.865669  237615 command.go:901] 2. Check if the management directory is clean
I0304 13:17:12.867233  237615 join.go:107] 3. Create the necessary directories
I0304 13:17:13.035934  237615 join.go:184] 4. Pull Images
Pulling docker.io/kubeedge/installation-package:v1.15.2 ...
Successfully pulled docker.io/kubeedge/installation-package:v1.15.2
Pulling docker.io/library/eclipse-mosquitto:1.6.15 ...
Successfully pulled docker.io/library/eclipse-mosquitto:1.6.15
Pulling docker.io/kubeedge/pause:3.6 ...
Successfully pulled docker.io/kubeedge/pause:3.6
I0304 13:17:13.114456  237615 join.go:184] 5. Copy resources from the image to the management directory
E0304 13:17:33.135397  237615 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
Error: edge node join failed: copy resources failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Comment by Watle-fan** [comment]
最后你成功解决了吗？with-mqtt=true带参数还是解决不了一开始的问题吗

**Comment by LiShuang-codes** [comment]
抱歉，这个问题我后来没有跟进。我已经转用kubesphere部署了，暂时没有发现问题。kubeedge也锁定在1.13版本。



---原始邮件---
发件人: "zhou ***@***.***&gt;
发送时间: 2024年5月22日(周三) 中午11:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [kubeedge/kubeedge] EdgeCore.service持续显示connect error (Issue #5446)




 
最后你成功解决了吗？with-mqtt=true带参数还是解决不了一开始的问题吗

**Comment by Watle-fan** [comment]
> 抱歉，这个问题我后来没有跟进。我已经转用kubesphere部署了，暂时没有发现问题。kubeedge也锁定在1.13版本。
> […](#)
> ---原始邮件--- 发件人: "zhou ***@***.***&gt; 发送时间: 2024年5月22日(周三) 中午11:37 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [kubeedge/kubeedge] EdgeCore.service持续显示connect error (Issue #5446) 最后你成功解决了吗？with-mqtt=true带参数还是解决不了一开始的问题吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好的，感谢

**Comment by xichengliudui** [comment]
> 最后你成功解决了吗？with-mqtt=true带参数还是解决不了一开始的问题吗

请问哥们你有解决吗？
我在安装 1.21.0 版本，在 cloud 使用 daemonset 部署的 mosquitto，并且在 edge 节点 telnet 127.0.0.1 1883 也是可以的，但是 edgecore 仍然会跑出这个日志，并且 mosquitto pod 隔几分钟还会重启
