### ISSUE TITLE
Nobody can deploy KubeEdge successfully. It's really a RUBBISH!

### ISSUE THREAD

**Issue by victorming666** [kubeedge/kubeedge#5449]
**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by victorming666** [comment]
We spent almost 3 months to deploy this project on a K8s cluster with some rk3588 edge nodes, but failed. Too many issues!! I never saw an inferior stuff like this project.

**Comment by asker9527** [comment]
I agree it.
