### ISSUE TITLE
Action not performing as expected in Bluetooth Mapper

### ISSUE THREAD

**Issue by lidiyag** [kubeedge/kubeedge#545]
**What happened**:
While using bluetooth mapper with CC2650-sensortag , it is observed that the Action Manager is not performing action as specified in the config file. 

**What you expected to happen**:
It is expected to perform action as specified in the config file. 

**How to reproduce it (as minimally and precisely as possible)**:
Run bluetooth mapper and test using CC3650-SensorTag

**Anything else we need to know?**:
It was observed that the struct "Action" was not getting proper values upon running the mapper.

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by lidiyag** [comment]
@sujithsimon22 please have a look. Thanks

**Comment by sujithsimon22** [comment]
Thanks @lidiyag I will take a look at it :)
