### ISSUE TITLE
regarding 16.0 image prepull 

### ISSUE THREAD

**Issue by nanyi545** [kubeedge/kubeedge#5453]
**What happened and what you expected to happen**:

I have a 3-node cluster 
1 control-plane
1 worker node
1 edgenode

I applied below ImagePrePullJob but i do not see images gets downloaded in edge node.

apiVersion: operations.kubeedge.io/v1alpha1
kind: ImagePrePullJob
metadata:
  name: imageprepull-example
  labels:
    description: ImagePrePullLabel
spec:
  imagePrePullTemplate:
    images:
    - busybox:1.35.0
    - nginx:1.24.0
    nodeNames:
    - e1

I use below commands to find images on e1 edge node , but i can not see them. 

ctr -n k8s.io image ls | grep busy 
ctr -n k8s.io image ls | grep nginx

how do i find the real cause here? is there a way to check prepull logging status ?  Thanks in advance !!

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version :  1.26
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):  1.16.0

**Comment by Shelley-BaoYue** [comment]
What‘s the status of this ImagePrePullJob?

**Comment by nanyi545** [comment]
ImagePrePullJob yaml file

`apiVersion: operations.kubeedge.io/v1alpha1
kind: ImagePrePullJob
metadata:
  name: imageprepull-example2
  labels:
    description: ImagePrePullLabel
spec:
  imagePrePullTemplate:
    images:
      - nginx:latest
    nodeNames:
      - e1
      - e2
    checkItems:
      - "disk"
    failureTolerate: "0.3"
    concurrency: 2
    timeoutSeconds: 180
    retryTimes: 1`

**Comment by nanyi545** [comment]
strangely, there is no status field from describe command?


`
Name:         imageprepull-example2
Namespace:    
Labels:       description=ImagePrePullLabel
Annotations:  <none>
API Version:  operations.kubeedge.io/v1alpha1
Kind:         ImagePrePullJob
Metadata:
  Creation Timestamp:  2024-03-07T07:07:22Z
  Generation:          1
  Managed Fields:
    API Version:  operations.kubeedge.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:description:
      f:spec:
        .:
        f:imagePrePullTemplate:
          .:
          f:checkItems:
          f:concurrency:
          f:failureTolerate:
          f:images:
          f:nodeNames:
          f:retryTimes:
          f:timeoutSeconds:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2024-03-07T07:07:22Z
  Resource Version:  7724
  UID:               e5a45aa0-76f4-462e-8d84-a55c62cfc870
Spec:
  Image Pre Pull Template:
    Check Items:
      disk
    Concurrency:       2
    Failure Tolerate:  0.3
    Images:
      nginx:latest
    Node Names:
      e1
      e2
    Retry Times:      1
    Timeout Seconds:  180
Events:               <none>
`

`
apiVersion: operations.kubeedge.io/v1alpha1
kind: ImagePrePullJob
metadata:
  name: imageprepull-example2
  labels:
    description: ImagePrePullLabel
spec:
  imagePrePullTemplate:
    images:
      - nginx:latest
    nodeNames:
      - e1
      - e2
    checkItems:
      - "disk"
    failureTolerate: "0.3"
    concurrency: 2
    timeoutSeconds: 180
    retryTimes: 1
`

**Comment by Shelley-BaoYue** [comment]
You can check the error logs in CloudCore and EdgeCore logs.

**Comment by nanyi545** [comment]
the thing is i just could not find any relavent information in  CloudCore and EdgeCore logs.

**Comment by Shelley-BaoYue** [comment]
Has you ever enable the TaskManager in cloudcore config?

**Comment by nanyi545** [comment]
> Have you ever enable the TaskManager in cloudcore config?

oops, I never knew it is disabled by default   :(      thanks very much !!!
