### ISSUE TITLE
P2P communication using KCP protocol

### ISSUE THREAD

**Issue by SherlockShemol** [kubeedge/kubeedge#5459]
When conducting P2P communication between nodes, is it necessary to use the kcp protocol?
https://github.com/paralin/go-libp2p-kcp

**Comment by wbc6080** [comment]
I don’t quite understand the description of this problem. Do you want kubeedge nodes to communicate using the kcp protocol? Maybe you can get a better answer by asking this question under [edgemesh](https://github.com/kubeedge/edgemesh/issues).

**Comment by SherlockShemol** [comment]
Thanks.Then I will close the issue.
