### ISSUE TITLE
安装部署k8s1.27版本安装kubeedge1.15版本，无法添加edge节点

### ISSUE THREAD

**Issue by sawchen** [kubeedge/kubeedge#5470]
**Environment**:
- Kubernetes version (use `kubectl version`):1.27.6
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.15.1

预制环境k8s使用containerd作为容器运行时
边缘节点已经安装containerd，版本
 containerd -v
containerd github.com/containerd/containerd v1.6.27

k8s节点使用如下命令初始化成功
./keadm init --advertise-address="192.168.33.33" --kubeedge-version=1.15.1
kubectl get all -n kubeedge
NAME                             READY   STATUS    RESTARTS   AGE
pod/cloudcore-5ff67dd45f-42vxz   1/1     Running   0          6h41m

NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/edge-eclipse-mosquitto   0         0         0       0            0           <none>          6h41m

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cloudcore   1/1     1            1           6h41m

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/cloudcore-5ff67dd45f   1         1         1       6h41m

边缘节点加入命令，提示失败
./keadm join --cloudcore-ipport=192.168.33.33 --kubeedge-version=1.15.1 --token=XXXXX
I0315 16:14:09.864001    3427 command.go:901] 1. Check KubeEdge edgecore process status
I0315 16:14:09.869885    3427 command.go:901] 2. Check if the management directory is clean
I0315 16:14:10.296976    3427 join.go:94] 3. Create the necessary directories
I0315 16:14:10.300905    3427 join_others.go:183] 4. Pull Images
Pulling kubeedge/installation-package:v1.15.1 ...
Successfully pulled kubeedge/installation-package:v1.15.1
I0315 16:14:10.301773    3427 join_others.go:183] 5. Copy resources from the image to the management directory
E0315 16:14:10.338820    3427 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format \"slice:prefix:name\" for systemd cgroups, got \"/k8s.io/e0f2c8f48bc13d478c858bdfb348d76f02517727370af44201373a6d5b2737a1\" instead: unknown"
Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups, got "/k8s.io/e0f2c8f48bc13d478c858bdfb348d76f02517727370af44201373a6d5b2737a1" instead: unknown
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups, got "/k8s.io/e0f2c8f48bc13d478c858bdfb348d76f02517727370af44201373a6d5b2737a1" instead: unknown

**Comment by wbc6080** [comment]
This problem is very similar to #5311 . You can refer to the processing method in #5311 and use the latest v1.15.2 patch version of kubeedge.

**Comment by sawchen** [comment]
我解决了这个问题了。
边缘节点添加，应该带上--cgroupdriver=systemd才可以
如下是正确的使用
./keadm join --cloudcore-ipport=192.168.33.33:10000 --cgroupdriver=systemd -kubeedge-version=1.15.1 --token=XXXX

**Comment by mkisantal** [comment]
> 我解决了这个问题了。
> 边缘节点添加，应该带上--cgroupdriver=systemd才可以
> 如下是正确的使用

Thanks for posting this @sawchen, adding the `--cgroupdriver=systemd` as you suggested worked (and was needed) in my case as well, with v1.16.2
