### ISSUE TITLE
为什么在cloud侧看不到调度到edge的pod的日志呢？是不是我需要执行什么特殊的操作？

### ISSUE THREAD

**Issue by LiShuang-codes** [kubeedge/kubeedge#5473]
**What happened and what you expected to happen**:
Internal Server Error
Get "https://192.168.137.233:10350/containerLogs/default/mypod/mypod?tailLines=1000&timestamps=true": dial tcp 192.168.137.233:10350: connect: connection refused
**How to reproduce it (as minimally and precisely as possible)**:
这个情况应该很普遍
**Anything else we need to know?**:
没有
**Environment**:
- Kubernetes version (use `kubectl version`):1.23.17
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.13

**Comment by Piwriw** [comment]
Please Update Kubeedge Version  & follow the steps
https://release-1-15.docs.kubeedge.io/docs/advanced/debug/
