### ISSUE TITLE
Kubeedge communication arch problem

### ISSUE THREAD

**Issue by SherlockShemol** [kubeedge/kubeedge#5476]
为了表达清楚我的问题，我先用中文陈述一遍。
按照[这里](https://github.com/kubeedge/kubeedge/issues/5447)所说的，实际上我建立了一个使用EdgeMesh作为CNI的KubeEdge云边通信方式。此时如果我在Cloudhub只启动QUIC server,请问是不是quic包是按照下图的路径传输的（打叉的地方因为没有安装CNI plugin所以没办法通过）？
![image](https://github.com/kubeedge/kubeedge/assets/87739402/8ce06197-b577-42a3-9e23-c66005aae42d)

这是Sedna的架构图。
![image](https://github.com/kubeedge/kubeedge/assets/87739402/4ebdb794-87f0-4c73-85f6-04462a2f38f1)
Sedna中提到其提供EdgeMesh的跨边缘-云微服务发现和数据平面流量治理功能。请问图中的Messaging over Kubeedge是通过EdgeMesh实现的吗？[源代码](https://github.com/kubeedge/sedna/tree/main/pkg/globalmanager/messagelayer)的这部分好像直接用websocket实现了，没有用到edgemesh？（抱歉代码水平有限）
关于Sedna的问题我是否应该在Sedna下提问？不过如果您知道的话能顺便告诉我吗？
还请您不吝赐教。

As stated [here](https://github.com/kubeedge/kubeedge/issues/5447), I actually built a KubeEdge cloud-edge communication method using EdgeMesh as CNI. At this time, if I only start the QUIC server in Cloudhub, is the quic package transmitted according to the path in the figure below (the crossed area cannot be passed because the CNI plugin is not installed)?
![image](https://github.com/kubeedge/kubeedge/assets/87739402/8ce06197-b577-42a3-9e23-c66005aae42d)

This is the architecture diagram of Sedna.
![image](https://github.com/kubeedge/kubeedge/assets/87739402/4ebdb794-87f0-4c73-85f6-04462a2f38f1)
Sedna mentioned that it provides EdgeMesh's cross-edge-cloud microservice discovery and data plane traffic management functions. Is the Messaging over Kubeedge in the picture implemented through EdgeMesh? This part of [source code](https://github.com/kubeedge/sedna/tree/main/pkg/globalmanager/messagelayer) seems to be implemented directly using websocket without using edgemesh? (Sorry for the limited code level)
Questions about Sedna Should I ask under Sedna? But if you know, can you tell me by the way?
Please feel free to give me some advice.

**Comment by Shelley-BaoYue** [comment]
Raise an issue under subproject Sedna is more approciate : )

**Comment by SherlockShemol** [comment]
Ok thank you :smiley_cat: 
I will put the first half under EdgeMesh and the second half under Sedna
