### ISSUE TITLE
Device data supports storage to prometheus

### ISSUE THREAD

**Issue by JiaweiGithub** [kubeedge/kubeedge#5478]
**What would you like to be added/modified**:
Our current business scenario is that there is a Prometheus service that supports rest api（http://xxxxxx/api/v1/write） writing, and we hope to store device data in it.

**Why is this needed**:

**Comment by wbc6080** [comment]
Do you want to output the edge device data collected by mapper to the prometheus application? Maybe you can describe the scenario in detail at the afternoon community meeting :)

**Comment by JiaweiGithub** [comment]
> Do you want to output the edge device data collected by mapper to the prometheus application? Maybe you can describe the scenario in detail at the afternoon community meeting :)

ok,thanks

**Comment by forsaken628** [comment]
Prometheus is pull based. It is not suitable for replacing the ingestion via scraping and turning Prometheus into a push-based metrics collection system. [official documents](https://prometheus.io/docs/prometheus/latest/querying/api/#remote-write-receiver)

But you can configure Prometheus as a receiver for the OTLP Metrics protocol.
[official documents](https://prometheus.io/docs/prometheus/latest/querying/api/#otlp-receiver)

Support for sending device data via OTLP Metrics protocol is more reasonable.
