### ISSUE TITLE
about keadm  cloudcore version

### ISSUE THREAD

**Issue by xingcici** [kubeedge/kubeedge#5496]
Hi there! I'm using keadm 1.16.0 to install cloudcore, but I noticed that there's no taskmanager configuration in the default settings. Does this mean that the cloudcore installed by keadm is not the latest version of 1.16.0? 
Can I specify the installation of cloudcore 1.16.0?

**Comment by wbc6080** [comment]
You can follow this command to install version 1.16 of kubeedge  `keadm init --advertise-address="THE-EXPOSED-IP" --profile version=v1.16.0 --kube-config=/root/.kube/config` as shown in [document](https://release-1-15.docs.kubeedge.io/docs/setup/install-with-keadm)

**Comment by xingcici** [comment]
> You can follow this command to install version 1.16 of kubeedge `keadm init --advertise-address="THE-EXPOSED-IP" --profile version=v1.16.0 --kube-config=/root/.kube/config` as shown in [document](https://release-1-15.docs.kubeedge.io/docs/setup/install-with-keadm)

😂 I didn't notice that there is a big difference between the Chinese documentation and the English documentation. Thank you.
