### ISSUE TITLE
Context deadline exceeded when execute keadm init

### ISSUE THREAD

**Issue by zhkmxx9302013** [kubeedge/kubeedge#5521]
Execute the following command:
` keadm init --advertise-address=192.168.31.10 --kubeedge-version=1.16.1
`

The Error is:

Kubernetes version verification passed, KubeEdge installation will start...
Error: context deadline exceeded
Usage:
  keadm init [flags]

Examples:

keadm init
- This command will render and install the Charts for Kubeedge cloud component

keadm init --advertise-address=127.0.0.1 --profile version=v1.15.1 --kube-config=/root/.kube/config
  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver
	- a list of helm style set flags like "--set key=value" can be implemented, ref: https://github.com/kubeedge/kubeedge/tree/master/manifests/charts/cloudcore/README.md

Flags:
      --advertise-address string    Use this key to set IPs in cloudcore's certificate SubAltNames field. eg: 10.10.102.78,10.10.102.79
  -d, --dry-run                     Print the generated k8s resources on the stdout, not actual execute. Always use in debug mode
      --external-helm-root string   Add external helm root path to keadm.
  -f, --files string                Allow appending file directories of k8s resources to keadm, separated by commas
      --force                       Forced installing the cloud components without waiting.
  -h, --help                        help for init
      --kube-config string          Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string     Use this key to set the default image tag
      --manifests string            Allow appending file directories of k8s resources to keadm, separated by commas
      --profile string              Set profile on the command line (iptablesMgrMode=external or version=v1.15.1)
      --set stringArray             Set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)

execute keadm command failed:  context deadline exceeded

**Comment by Shelley-BaoYue** [comment]
Try executing `kubectl get ns` and `kubectl get po -nkubeedge` to see the result

**Comment by zhkmxx9302013** [comment]
> Try executing `kubectl get ns` and `kubectl get po -nkubeedge` to see the result

oh thanks, I find the solution.
[cloudcore in pending status](https://kubeedge.io/docs/faq/setup/#cloudcore-in-pending-status)

**Comment by zhkmxx9302013** [comment]
done
