### ISSUE TITLE
1.16.1 join err 

### ISSUE THREAD

**Issue by thinkeng** [kubeedge/kubeedge#5529]
k8s   v1.27.2  + docker  v24.0.7 + cri-docker v0.3.10

kubeedge  v1.16.1 + dokcer  v26.0.0 + cri-docker v0.3.12

```
systemctl status cri-docker.socket
● cri-docker.socket - CRI Docker Socket for the API
     Loaded: loaded (/etc/systemd/system/cri-docker.socket; enabled; vendor preset: enabled)
     Active: active (listening) since Wed 2024-04-10 19:38:20 CST; 12min ago
   Triggers: ● cri-docker.service
     Listen: /run/cri-dockerd.sock (Stream)
      Tasks: 0 (limit: 18731)
     Memory: 0B
        CPU: 1ms
     CGroup: /system.slice/cri-docker.socket

4月 10 19:38:20 rootk systemd[1]: Starting CRI Docker Socket for the API...
4月 10 19:38:20 rootk systemd[1]: Listening on CRI Docker Socket for the API.
```

加入命令
```
keadm join \
--cloudcore-ipport=192.168.1.158:10000 \
--with-mqtt=false \
--kubeedge-version=1.16.1 \
--edgenode-name=edge-01 \
--token=xxxxx
```

加入时报如下错误
```
I0410 19:40:28.749010  826266 command.go:901] 1. Check KubeEdge edgecore process status
I0410 19:40:28.760203  826266 command.go:901] 2. Check if the management directory is clean
I0410 19:40:28.760306  826266 join.go:94] 3. Create the necessary directories
Error: edge node join failed: validate service connection: validate CRI v1 image API for endpoint "unix:///run/containerd/containerd.sock": rpc error: code = Unimplemented desc = unknown service runtime.v1.ImageService
execute keadm command failed:  edge node join failed: validate service connection: validate CRI v1 image API for endpoint "unix:///run/containerd/containerd.sock": rpc error: code = Unimplemented desc = unknown service runtime.v1.ImageService
```

**Comment by Shelley-BaoYue** [comment]
add --remote-runtime-endpoint=unix:///var/run/cri-dockerd.sock

**Comment by thinkeng** [comment]
> 添加 --remote-runtime-endpoint=unix:///var/run/cri-dockerd.sock

`I0410 19:58:32.759022  875478 command.go:901] 1. Check KubeEdge edgecore process status
I0410 19:58:32.772668  875478 command.go:901] 2. Check if the management directory is clean
I0410 19:58:32.772759  875478 join.go:94] 3. Create the necessary directories
I0410 19:58:32.861311  875478 join_others.go:183] 4. Pull Images
Pulling kubeedge/installation-package:v1.16.1 ...
Successfully pulled kubeedge/installation-package:v1.16.1
I0410 19:59:22.256568  875478 join_others.go:183] 5. Copy resources from the image to the management directory
E0410 19:59:42.276078  875478 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
Error: edge node join failed: copy resources failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded`

**Comment by thinkeng** [comment]
> add --remote-runtime-endpoint=unix:///var/run/cri-dockerd.sock

需求添加其他配置文件么？

**Comment by Shelley-BaoYue** [comment]
I guess the status of cr-dockerd need to be active(running)

**Comment by thinkeng** [comment]
> I guess the status of cri-dockerd need to be active(running)

cri-docker.service 的配置增加
`ExecStart=/usr/bin/cri-dockerd --network-plugin=cni --pod-infra-container-image=registry.aliyuncs.com/google_containers/pause:3.7`

journalctl -u edgecore.service -xe

看到日志
`"Starting to sync pod status with apiserver"
44] "Starting kubelet main sync loop"
68] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
status.go:68] "Attempting to register node" node="barry-edge-01"
66] failed to unmarshal message content to unstructured obj: Object 'Kind' is missing in '{"metadata":{"name":"barry-edge-01","creationTimestamp":null,"labels":{"beta.>
8] process remote failed, req[msgID[c1178973-2eaf-4f93-b725-52a9d6c59acb] resource[default/node/barry-edge-01]], err: not connected
el.go:164] Get bad anonName: when sendresp message, do nothing
o:214] "Starting CPU manager" policy="none"
o:215] "Reconciling" reconcilePeriod="10s"
36] "Initialized new in-memory state store"
88] "Updated default CPUSet" cpuSet=""
96] "Updated CPUSet assignments" assignments={}
o:49] "None policy: Start"
r.go:169] "Starting memorymanager" policy="None"
35] "Initializing new in-memory state store"
75] "Updated machine memory state"
1] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
r.go:118] "Starting Kubelet Plugin Manager"
ger.go:262] "Eviction manager: failed to get summary stats" err="failed to get node info: node length from meta db is 0"
:295] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: node length from meta db is 0
:295] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: node length from meta db is 0
:295] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: node length from meta db is 0
:295] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: node length from meta db is 0
 start connect to mqtt server with client id: hub-client-sub-1712802162
 client hub-client-sub-1712802162 isconnected: false
] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
:295] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: node length from meta db is 0`

**Comment by thinkeng** [comment]
这是个bug，还是环境配置的问题？

**Comment by Shelley-BaoYue** [comment]
make sure if edge node can curl cloudcore or if there is any err log in cloudcore.log 
![image](https://github.com/kubeedge/kubeedge/assets/48788150/20afb809-cc68-45c9-879e-2c73dcf2d5c2)

**Comment by thinkeng** [comment]
> make sure if edge node can curl cloudcore or if there is any err log in cloudcore.log ![image](https://private-user-images.githubusercontent.com/48788150/321531618-20afb809-cc68-45c9-879e-2c73dcf2d5c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjEzODMsIm5iZiI6MTcxMjgyMTA4MywicGF0aCI6Ii80ODc4ODE1MC8zMjE1MzE2MTgtMjBhZmI4MDktY2M2OC00NWM5LTg3OWUtMmM3M2RjZjJkNWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZWRhMTYyNWYzOTgyMDAyYWNlNGU4MTg1YWExMzRkOGQyMGM4ODQ3ZWIyZWU1NmFlNjc4OGI5NTYwZmY1YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lGU3UbIDoq47_tavOJ6U1eGDVMx1H2j1tjCkHGbNwCk)
9091 端口需要往外暴露么，这个端口是干什么的

**Comment by thinkeng** [comment]
> > make sure if edge node can curl cloudcore or if there is any err log in cloudcore.log ![image](https://private-user-images.githubusercontent.com/48788150/321531618-20afb809-cc68-45c9-879e-2c73dcf2d5c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjEzODMsIm5iZiI6MTcxMjgyMTA4MywicGF0aCI6Ii80ODc4ODE1MC8zMjE1MzE2MTgtMjBhZmI4MDktY2M2OC00NWM5LTg3OWUtMmM3M2RjZjJkNWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZWRhMTYyNWYzOTgyMDAyYWNlNGU4MTg1YWExMzRkOGQyMGM4ODQ3ZWIyZWU1NmFlNjc4OGI5NTYwZmY1YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lGU3UbIDoq47_tavOJ6U1eGDVMx1H2j1tjCkHGbNwCk)
> > 9091 端口需要往外暴露么，这个端口是干什么的

可以了谢谢

**Comment by thinkeng** [comment]
再问一下，9091 端口需要往外暴露么? 这个端口是干什么的

**Comment by Shelley-BaoYue** [comment]
> 再问一下，9091 端口需要往外暴露么? 这个端口是干什么的

https://github.com/kubeedge/kubeedge/blob/master/pkg/apis/componentconfig/cloudcore/v1alpha1/types.go#L54

**Comment by thinkeng** [comment]
节点加入成功后  pod 一直 ContainerCreating
报错
`4月 11 19:35:56 rootk edgecore[1864043]: E0411 19:35:56.965075 1864043 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"edge-node-exporter-g72hr_monitoring(ecf3a3ef-bee0-412d-8a6c-84d8cdb8c055)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"edge-node-exporter-g72hr_monitoring(ecf3a3ef-bee0-412d-8a6c-84d8cdb8c055)\\\": rpc error: code = Unknown desc = failed to create a sandbox for pod \\\"edge-node-exporter-g72hr\\\": Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as \\\"xxx.slice\\\"\"" pod="monitoring/edge-node-exporter-g72hr" podUID="ecf3a3ef-bee0-412d-8a6c-84d8cdb8c055"`


docker 配置 
/etc/docker/daemon.json
{
  "registry-mirrors":["https://bycacelf.mirror.aliyuncs.com"],
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}

**Comment by Shelley-BaoYue** [comment]
https://kubeedge.io/docs/setup/prerequisites/runtime#configure-the-runtime-for-edgecore-using-keadm-2

**Comment by thinkeng** [comment]
> https://kubeedge.io/docs/setup/prerequisites/runtime#configure-the-runtime-for-edgecore-using-keadm-2

可以了，谢谢谢谢

**Comment by cosmosiwi** [comment]
> > https://kubeedge.io/docs/setup/prerequisites/runtime#configure-the-runtime-for-edgecore-using-keadm-2
> 
> 可以了，谢谢谢谢

can I know how you configure the cri-dockerd and the platform you boot k8s ?

**Comment by thinkeng** [comment]
> > > https://kubeedge.io/docs/setup/prerequisites/runtime#configure-the-runtime-for-edgecore-using-keadm-2
> > 
> > 
> > 可以了，谢谢谢谢
> 
> can I know how you configure the cri-dockerd and the platform you boot k8s ?

用kubekey  安装的 https://github.com/kubesphere/kubekey
