### ISSUE TITLE
Separate network communication channel between control plane and data plane

### ISSUE THREAD

**Issue by CindyXing** [kubeedge/kubeedge#556]
**What would you like to be added**:
Currently we are using the same websocket channel between cloudhub & edgehub for both system level communication as well as application level one (e.g. device twin data)

**Why is this needed**:
From both security and network bandwidth's perspective, we should separate them. The QOS level and business charge would be different too.

**Comment by CindyXing** [comment]
For edgemesh, we are creating router for micro-services communicate each other. Here we should purposely make sure routing in data plane is separate from control plane

**Comment by qizha** [comment]
can we leverage quic's multiple stream to achieve that?

**Comment by chenleji** [comment]
suggest gRPC for administration, origin channels for business.

**Comment by sids-b** [comment]
@chenleji apologies for late response. Can you share your thoughts on how we can use gRPC to resolve this issue ?
