### ISSUE TITLE
Router Manager Support HA

### ISSUE THREAD

**Issue by JiaweiGithub** [kubeedge/kubeedge#5561]
**What would you like to be added/modified**:
Router Manager Support HA

**Why is this needed**:
Users need to communicate between the cloud and the edge. For example, the cloud calls the rest interface of the edge service. In this case, the routing management function of kubeedge can be used. Currently, Kubeedge's routing management function has some problems in the case of multiple cloudcore copies. The main problem is that when there are multiple copies of cloudcore, whether the cloud sends messages to the edge or reports the message to the cloud, it is not known which cloudcore is sent to it for processing, and there is confusion in message management in the cloud.

**Comment by h4l0gen** [comment]
Hii @JiaweiGithub this project idea sounds exciting. Can you elaborate me this idea, I like to work on it. I am looking forward to take part in LFX term2 with kubeedge.

**Comment by 2008sahil** [comment]
Hi @JiaweiGithub  ,

I'm Sahil Gupta and I'm currently on my journey to explore Golang and Kubernetes, and this project seems like an excellent opportunity for me to deepen my understanding in these areas while contributing to a meaningful project. I'm excited about the challenge of optimizing the router manager to support multi-CloudCore scenarios.

Could you please provide some guidance and resources to help me navigate my contribution to this project?

Looking forward to your advice.

Best regards,
Sahil Gupta
