### ISSUE TITLE
keadm init failed with `--profile version=v1.17.0`

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/kubeedge#5601]
**What happened**:

When using `keadm init --profile version=v1.17.0` to deploy cloudcore,  it will failed with error like: 

![image](https://github.com/kubeedge/kubeedge/assets/48788150/fe97ce69-cc82-46df-beb2-33a5c4c12d82)

**What you expected to happen**: 

deploy cloudcore successfully

**How to reproduce it (as minimally and precisely as possible)**:

execute `keadm init --advertise-address=xxx --profile version=v1.17.0`

**Anything else we need to know?**:

Using keadm --kubeedge-version=v1.17.0 can deploy cloudcore successfully

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): cloudcore v1.17.0   keadm version: v1.17.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Shelley-BaoYue** [comment]
cc @luomengY

**Comment by luomengY** [comment]
> cc @luomengY

Keam init has restructured its architecture on v1.17, and now only supports internal profiles/version.yaml for profiles. If you want to specify a version, it is recommended to use `--kubeedge-version` directly. The `--profile` parameter only supports version.

**Comment by luomengY** [comment]
> > cc @luomengY
> 
> Keam init has restructured its architecture on v1.17, and now only supports internal `profiles/version.yaml` for profiles. If you want to specify a version, it is recommended to use `--kubeedge-version` directly. The `--profile` parameter only supports version.

**Comment by Shelley-BaoYue** [comment]
`The --profile parameter only supports version.`
--> but now I cannot using `--profile version` to specify cloudcore version. 

The setup documentation in KubeEdge website still recommend users using `--profile version`: https://kubeedge.io/docs/setup/install-with-keadm#keadm-init. If we no longer support it, we need to modify the documentation.  

I think this change affects user behavior and needs a deprecated phase.  Release changelog also should declare it. cc @fisherxu  @WillardHu @wbc6080

**Comment by WillardHu** [comment]
We can update how to use the command keadm init in the documentation station(website). 
We can also add a compatibility processing.
```golang
if strings.split(profileValue, "=") == 2 {
    // override the kubeedge version to version.yaml
} else {
    ....
}
```
But I don't know whether this flag `--profile version=<version>` is commonly used, it is the same as the flag `--kubeedge-version=<version>` from a technical point of view. 

Would you like to make these contributions? @luomengY

**Comment by luomengY** [comment]
> We can update how to use the command keadm init in the documentation station(website). We can also add a compatibility processing.
> 
> ```go
> if strings.split(profileValue, "=") == 2 {
>     // override the kubeedge version to version.yaml
> } else {
>     ....
> }
> ```
> 
> But I don't know whether this flag `--profile version=<version>` is commonly used, it is the same as the flag `--kubeedge-version=<version>` from a technical point of view.
> 
> Would you like to make these contributions? @luomengY

Here, the functions of `profile` and `kubedge version` appear to be the same. Is there any other use of `profile' here`? If not, I think it can be directly made compatible in the code by assigning the value of `profile` to `kubedge version`. What do you think?  @fisherxu  @Shelley-BaoYue  @WillardHu

**Comment by WillardHu** [comment]
> Here, the functions of profile and kubedge-version appear to be the same. Is there any other use of profile here? If not, I think it can be directly made compatible in the code by assigning the value of profile to kubedge-version. What do you think? @fisherxu @Shelley-BaoYue @WillardHu

If this flag `--profile version=<version>` is not commonly used, I think it is ok.

**Comment by Shelley-BaoYue** [comment]
CloudCore installation only supports the `--profile version` initially, and with the guidance of the official website, I think it's commonly used. If we want to incorporate it into kubeedge-version in the future, we need to make a statement in the keadm introduction and website documentation to gradually deprecate it.

**Comment by wbc6080** [comment]
> CloudCore installation only supports the `--profile version` initially, and with the guidance of the official website, I think it's commonly used. If we want to incorporate it into kubeedge-version in the future, we need to make a statement in the keadm introduction and website documentation to gradually deprecate it.

+1, I just read the [document](https://kubeedge.io/docs/setup/install-with-keadm) and found that when the cloud node executes `keadm init`, `--profile version `is used, but when the edge node executes `keadm join`, `--kubeedge-version` is used. I think whether we can combine the two ways into one expression in the future.

**Comment by luomengY** [comment]
> CloudCore installation only supports the `--profile version` initially, and with the guidance of the official website, I think it's commonly used. If we want to incorporate it into kubeedge-version in the future, we need to make a statement in the keadm introduction and website documentation to gradually deprecate it.

ok, can we ensure compatibility at the code level and assign the value of `profile` to `kubedge-version` now?

**Comment by luomengY** [comment]
> I just read the [document](https://kubeedge.io/docs/setup/install-with-keadm) and found that when the cloud node executes `keadm init`, `--profile version `is used, but when the edge node executes `keadm join`, `--kubeedge-version` is used. I think whether we can combine the two ways into one expression in the future.

Yes, if there are no other uses for `profile`, we can gradually discard it.
