### ISSUE TITLE
keadm upgrade cloud  Error

### ISSUE THREAD

**Issue by thinkeng** [kubeedge/kubeedge#5605]
k8s  version v1.27.2
kubeedge   v1.16.1

keadm  v1.17.0

想从1.16.1  升级到 v.1.17.0  

升级报错如下

```
keadm upgrade cloud --advertise-address=192.168.1.150 --kubeedge-version=v1.17.0
Kubernetes version verification passed, KubeEdge upgradation will start...
Error: failed to upgrade release cloudcore, err: context deadline exceeded
Usage:
  keadm upgrade cloud [flags]

Flags:
      --advertise-address string    Please set the same value as when you installed it, this value is only used to generate the configuration and does not regenerate the certificate. eg: 10.10.102.78,10.10.102.79
  -d, --dry-run                     Print the generated k8s resources on the stdout, not actual execute. Always use in debug mode
      --external-helm-root string   Add external helm root path to keadm
      --force                       Forced upgrading the cloud components without waiting
  -h, --help                        help for cloud
      --image-repository string     Choose a container image repository to pull the image of the kubedge component.
      --kube-config string          Use this key to update kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string     Use this key to set the upgrade image tag
      --print-final-values          Print the final values configuration for debuging
      --profile string              Sets profile on the command line. If '--values' is specified, this is ignored
      --reuse-values                reuse the last release's values and merge in any overrides from the command line via --set and -f.
      --set stringArray             Sets values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --values stringArray          specify values in a YAML file (can specify multiple)

execute keadm command failed:  failed to upgrade release cloudcore, err: context deadline exceeded
```

有没有详细一点的升级文档

**Comment by Shelley-BaoYue** [comment]
How about set `--toVersion=v1.17.0`? Using `keadm upgrade -h` to get more info about upgrade.

**Comment by thinkeng** [comment]
> How about set `--toVersion=v1.17.0`? Using `keadm upgrade -h` to get more info about upgrade.



> How about set `--toVersion=v1.17.0`? Using `keadm upgrade -h` to get more info about upgrade.

旧的pod 没有自动删除，删除后新版本的pod 可以是正常启动的

**Comment by WillardHu** [comment]
This issue may be that due to port conflicts caused by Cloudcore using the hostnetwork, You can try adding a flag `--set cloudCore.strategy.type=Recreate` to execute command `keadm upgrade`.

**Comment by Mengxue12** [comment]
> k8s version v1.27.2 kubeedge v1.16.1
> 
> keadm v1.17.0
> 
> 想从1.16.1 升级到 v.1.17.0
> 
> 升级报错如下
> 
> ```
> keadm upgrade cloud --advertise-address=192.168.1.150 --kubeedge-version=v1.17.0
> Kubernetes version verification passed, KubeEdge upgradation will start...
> Error: failed to upgrade release cloudcore, err: context deadline exceeded
> Usage:
>   keadm upgrade cloud [flags]
> 
> Flags:
>       --advertise-address string    Please set the same value as when you installed it, this value is only used to generate the configuration and does not regenerate the certificate. eg: 10.10.102.78,10.10.102.79
>   -d, --dry-run                     Print the generated k8s resources on the stdout, not actual execute. Always use in debug mode
>       --external-helm-root string   Add external helm root path to keadm
>       --force                       Forced upgrading the cloud components without waiting
>   -h, --help                        help for cloud
>       --image-repository string     Choose a container image repository to pull the image of the kubedge component.
>       --kube-config string          Use this key to update kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
>       --kubeedge-version string     Use this key to set the upgrade image tag
>       --print-final-values          Print the final values configuration for debuging
>       --profile string              Sets profile on the command line. If '--values' is specified, this is ignored
>       --reuse-values                reuse the last release's values and merge in any overrides from the command line via --set and -f.
>       --set stringArray             Sets values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
>       --values stringArray          specify values in a YAML file (can specify multiple)
> 
> execute keadm command failed:  failed to upgrade release cloudcore, err: context deadline exceeded
> ```
> 
> 有没有详细一点的升级文档

我也是这个问题，请问最后是怎样升级的呢
