### ISSUE TITLE
Edgecore error message

### ISSUE THREAD

**Issue by peakforever** [kubeedge/kubeedge#5611]
****edgecore error** **:
edgecore[832]: E0514 12:28:04.113409     832 cri_stats_provider.go:455] "Failed to get the info of the filesystem with mount
point" err="cannot find filesystem info for device \"/dev/mapper/openeuler-root\"" mountpoint="/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs"
the edgecore log:
[edgecore.log](https://github.com/kubeedge/kubeedge/files/15304827/edgecore.log)
**Anything else we need to know?**:
My edgenode is a vmware virtual machine :arch:x86_64, os openeuler22.03,containerd is the container runtime. containerd starts sucessfully , the edgecore is deployed by keadm 1.15.2.
**Environment**:
- Kubernetes version (use `kubectl version`):1.26.15
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.15.2

**Comment by Shelley-BaoYue** [comment]
This error log can be ignored because we don't support cadvisor at edge temporarily  : )    Is the edge node status running?

**Comment by peakforever** [comment]
thank you for your responding so fast. yes, the edge node is running. and I can deploy a demo app on this edge node, and the app container runs successfully.
