### ISSUE TITLE
keadm init shows success, but the cloudcore process cannot be found

### ISSUE THREAD

**Issue by Watle-fan** [kubeedge/kubeedge#5612]
**What happened and what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
-
keadm init shows success, but the cloudcore process cannot be found, and the corresponding file is not generated in the corresponding /etc/kubeedge folder. I used isuald instead of docker. Will this replacement container affect keadm init? Modify the relevant configuration files so that keadm init can initialize successfully? kubernets version: 1.24, kubeedge version: 1.15, isulad version: 2.1.5
<img width="659" alt="add58cd7a183eacee73aa55cd2feb5a" src="https://github.com/kubeedge/kubeedge/assets/78351235/78a4a6d1-deb4-4e67-a888-536da6247ae3">
Before executing the above keadm init command, I have executed the following command for taint tolerance. I uploaded the kubeedge-v1.15.0-linux-amd64.tar.gz and checksum_kubeedge-v1.15.0-linux-amd64.tar.gz.txt files in the etc/kubeedge/ directory, but after executing the keadm init command, the above problem occurred, and there are no task files in the etc/kubeedge/ folder, including the files I uploaded myself.

kubectl describe nodes cloud | grep Taints
kubectl taint nodes cloud node-role.kubernetes.io/control-plane:NoSchedule-

**Comment by thinkeng** [comment]
kubectl  get  pod -n kubeedge

**Comment by Watle-fan** [comment]
> Do you want to view cloudcore logs? Because cloudcore has two methods: binary deployment and keadm deployment. Binary deployment can check the log through cloudcore.service, but keadm deployment deploys cloudcore in the form of pod. You can refer to https://kubeedge.io/docs/faq/setup#how-to-check-cloudcore-logs
However, my logs still show some errors：
<img width="1136" alt="ad82be8a68375f9a2eb5553efcb28ac" src="https://github.com/kubeedge/kubeedge/assets/78351235/6baef555-ac29-48d8-9432-8ac9cbda7ced">
<img width="1133" alt="20d530192b95d781063e12cb72ccac5" src="https://github.com/kubeedge/kubeedge/assets/78351235/8efd25a9-73c8-406c-8faa-de708ca37c97">

**Comment by Shelley-BaoYue** [comment]
using v1.15.2 but not v1.15.0 to fix the error log

**Comment by Watle-fan** [comment]
This issue has been resolved, mainly because since v1.10, CloudCore is running in container mode instead of process mode, and you can see the CloudCore image by looking at docker images。
<img width="734" alt="c89291ae8102deeca79bd8f0ba3e37a" src="https://github.com/kubeedge/kubeedge/assets/78351235/8bb78201-29a0-4505-82f6-8115862518f1">
