### ISSUE TITLE
BlueToothMapper:Error handling required in scheduler when invalid actionname is given

### ISSUE THREAD

**Issue by lidiyag** [kubeedge/kubeedge#562]
**What would you like to be added**:
Proper error handling required when invalid value is given

**Comment by lidiyag** [comment]
@sujithsimon22 please have a look

**Comment by sujithsimon22** [comment]
> @sujithsimon22 please have a look

Thanks @lidiyag. Could you please edit the issue name to mention explicitly what is meant by invalid value ex: "invalid action name". It will help other users understand what this issue is about
