### ISSUE TITLE
kubectl get nodes don't show edge nodes

### ISSUE THREAD

**Issue by Watle-fan** [kubeedge/kubeedge#5624]
I have successfully added edge1 to cloud, but the edge1 node is not displayed when I run the `kubectl get nodes` command on cloud, why is this? I tried the kubeedgev1.15.2 version but it didn't work, because the cloud node had a time out command error when executing the` keadm init` command, and the following command ：
```
kubectl describe nodes cloud | grep Taints
kubectl taint nodes cloud node-role.kubernetes.io/control-plane:NoSchedule-
```
<img width="772" alt="a7baa4e66d9d9bacc691d5ff7c283c0" src="https://github.com/kubeedge/kubeedge/assets/78351235/ce77d39a-d4d2-44f2-82f0-4b49d8b1dd93">
<img width="1097" alt="b797fbf6ae1f5e14df46fdd3c9da768" src="https://github.com/kubeedge/kubeedge/assets/78351235/68043b98-0f29-48a8-9e2e-fe9ec3fafdcd">

<img width="637" alt="44ae0287aea5a3c9559103d647ebe2a" src="https://github.com/kubeedge/kubeedge/assets/78351235/34117601-6f65-41fd-a509-1b4758f28cee">

<img width="312" alt="3997976152f08364705a7d851353714" src="https://github.com/kubeedge/kubeedge/assets/78351235/d3b1dcec-458e-47ff-9dc9-b4f1c4a76a1a">

was executed to solve the problem and successfully carried out `keadm init`, does this have an impact?

**Environment**:
- Kubernetes version (v1.24.0):
- KubeEdge version(v1.14.5)。

**Comment by Watle-fan** [comment]
This issue is fixed by modifying port number 10350 in /etc/kubeedge/config/edgecore.yaml to 10351 and running the following command: 
```
sudo systemctl daemon-reload
 sudo systemctl restart edgecore.service
```

**Comment by Piwriw** [comment]
edgecore  is not running，The edge node is not registered with the cluster. Please stop `10350` and you will get edgenodes in master. Also u change to 10351 is OK.
