### ISSUE TITLE
which version k8s is more recommend for kubeedge 1.16.2 ? latest 1.27.x or 1.27.7 ?

### ISSUE THREAD

**Issue by xingcici** [kubeedge/kubeedge#5636]
Hi, We are considering deploying kubeedge in a formal environment.
Which version k8s is more recommend for kubeedge 1.16.2 ? latest 1.27.x or 1.27.7 (in the doc) ?
Is it risky to use the latest version of 1.27.x ？

**Comment by Shelley-BaoYue** [comment]
refer to https://github.com/kubeedge/kubeedge?tab=readme-ov-file#kubernetes-compatibility. I think it won't has any probelm with using the latest patch release of 1.27.x

**Comment by xingcici** [comment]
> refer to https://github.com/kubeedge/kubeedge?tab=readme-ov-file#kubernetes-compatibility. I think it won't has any probelm with using the latest patch release of 1.27.x

Thank you for your reply ！
