### ISSUE TITLE
kubect logs show  host not found in upstream "xxxx" in /etc/nginx/conf.d/nginx.80.conf:11

### ISSUE THREAD

**Issue by Watle-fan** [kubeedge/kubeedge#5639]
When I deployed my e3edge application, I got an error in the container(host not found in upstream "svc-user-center-v3" in /etc/nginx/conf.d/nginx.80.conf:11), and the corresponding log is as follows: For this error, I tried to add "svc-user-center-v3" to the /etc/hosts file, but I still get this error. Is there any other workable solution?
<img width="770" alt="df12cb33745afebfd222e9214fcd450" src="https://github.com/kubeedge/kubeedge/assets/78351235/350fbf43-a81c-45f9-847c-cdb32fb3137c">
<img width="745" alt="0c67e5c4ca0c5471b179c984b15aa0e" src="https://github.com/kubeedge/kubeedge/assets/78351235/f8e63305-d891-4cad-9447-6e248e72c258">
<img width="721" alt="3182aea145ec40ec658bccd7f308a07" src="https://github.com/kubeedge/kubeedge/assets/78351235/c4843fe0-4590-4c34-ac4c-e9fb86891c77">

The nginx.80.conf file reads as follows: `
server {
    listen       80;

    location / {
        root   /usr/share/nginx/html;
        index  landing.html index.html index.htm;
        expires  1d;
    }

    location /uc-api/ {
        proxy_pass http://svc-user-center-v3:8080/;
        proxy_http_version 1.1;
        proxy_pass_header Authorization;
        gzip on;
        expires -1;
    }

    error_page   404 500 502 503 504  /404.html;
    location /50x.html {
        root   /usr/share/nginx/html;
    }

    location /404.html {
        root   /usr/share/nginx/html;
    }
}
`

**Comment by WillardHu** [comment]
This issue looks the same as #5638, you can close one and track it with an issue.

You execute ping <service name> in the cloud, and coredns is active in the cloud, you can try to execute ping <service name> in the nginx container(kubectl/docker/nerdctl exec -it), it will not work.

You can use [EdgeMesh](https://github.com/kubeedge/edgemesh) or https://github.com/kubeedge/kubeedge/issues/2677) enable pods to access pods using a service name in the edge node.
