### ISSUE TITLE
Cloudcore runs in containers

### ISSUE THREAD

**Issue by Watle-fan** [kubeedge/kubeedge#5641]
Cloudcore shows that it is running as a container, and I don't see the cloudcore configuration file under /etc/kubeedge/config, so how can I get its configuration file and modify the configuration file in it?

`keadm init --advertise-address=172.18.186.131 --kubeedge-version=1.14.5`
<img width="503" alt="0f32c6b58d24609f2ad53b3e238c4f5" src="https://github.com/kubeedge/kubeedge/assets/78351235/b71c096e-31bb-431b-ab8f-452e89f5d5aa">

**Environment**:
- Kubernetes version (use `v1.24`):
- KubeEdge version(`v1.14.5`):

**Comment by WillardHu** [comment]
You can modify the configmap cloudcore in the namespace kubeedge, and restart the deployment cloudcore
