### ISSUE TITLE
Mapper supports device data writing

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/kubeedge#5657]
**What would you like to be added/modified**:

Added device writing feature in Mapper Framework

**Why is this needed**:

Now the Mapper Framework has realized the ability to collect and report edge device data, but it cannot well support the scenario of device data writing. In actual use, users may need to write data to certain registers of the managed device to achieve the purpose of device control.

**Comment by EraKin575** [comment]
@wbc6080 can I work on this issue?
