### ISSUE TITLE
Create a common inside cloud/pkg to place common/types

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#566]
**What happened**:
common/types contains code which is only used by cloud.

**What you expected to happen**:
common should have code which is used by both cloud and edge

1) common in root directory should have common code used by both cloud and edge
2) common in cloud/pkg should have common code used by different cloud modules
3) common in edge/pkg should have common code  used by different edge modules (already exists in source code)

Thoughts ?

**Comment by sids-b** [comment]
cc @m1093782566 @shouhong

**Comment by shouhong** [comment]
@sids-b Which code in common/types is only used by cloud? 
The new added KubeInfo struct is used by both cloud and edgesite.

**Comment by sids-b** [comment]
@shouhong , edgesite code will soon refer to controller from cloud. We plan to have only cmd/ and conf/ in edgesite. we already have an issue for that #531. Along with that or post that we can resolve this issue. @samy2019 is working on #531

**Comment by shouhong** [comment]
> @shouhong , edgesite code will soon refer to controller from cloud. We plan to have only cmd/ and conf/ in edgesite. we already have an issue for that #531. Along with that or post that we can resolve this issue. @samy2019 is working on #531

@sids-b I see. Thanks!

**Comment by rohitsardesai83** [comment]
#531 is resolved now. Can we proceed with this ?
