### ISSUE TITLE
Broken links in the testing user guide

### ISSUE THREAD

**Issue by Jaanki** [kubeedge/kubeedge#567]
**What happened**:
The links to example tests in testing user guide is broken.

**What you expected to happen**:
Correct links to point to example tests.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by sids-b** [comment]
Hi @Jaanki , We are discussing the same in #288 . Please take a look and share your thoughts. We want to resolve the issue soon. Thanks :)
