### ISSUE TITLE
加入边缘节点时，创建podsandpox报错：已存在同名pod，如何删除该pod？

### ISSUE THREAD

**Issue by DeJeune** [kubeedge/kubeedge#5686]
**What happened and what you expected to happen**:
```
keadm join --cloudcore-ipport=10.211.11.5:10000 --kubeedge-version=v1.17.0 --token=** 
--image-repository="docker.io/jeuneastre" --remote-runtime-endpoint=unix:///var/run/isulad.sock
```
报错：
```
 "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = Conflict. The name 
\"k8s_POD_edgecore_kubeedge__0\" is already in use by sandbox 
f4344dd861c7193bbf089bed8cd006290e44aaf4fabf6da2c4d72f7bb12718be. You have to remove that sandbox to be able to reuse that name."
Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = Conflict. The name 
"k8s_POD_edgecore_kubeedge__0" is already in use by sandbox 
f4344dd861c7193bbf089bed8cd006290e44aaf4fabf6da2c4d72f7bb12718be. You have to remove that sandbox to be able to reuse that 
name.
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = Conflict. The name 
"k8s_POD_edgecore_kubeedge__0" is already in use by sandbox 
f4344dd861c7193bbf089bed8cd006290e44aaf4fabf6da2c4d72f7bb12718be. You have to remove that sandbox to be able to reuse that 
name.
```
查询边缘节点的pod：
```
crictl --runtime-endpoint=unix:///var/run/isulad.sock --image-endpoint=unix:///var/run/isulad.sock pods
POD ID              CREATED             STATE               NAME                NAMESPACE           ATTEMPT             RUNTIME
f4344dd861c71       About an hour ago   NotReady            edgecore            kubeedge            0                   (default)
```
尝试删除该pod时报错：
```
crictl --runtime-endpoint=unix:///var/run/isulad.sock --image-endpoint=unix:///var/run/isulad.sock rmp -f f4344dd861c71
getting sandbox status of pod "f4344dd861c71": metadata.Name, metadata.Namespace or metadata.Uid is not in metadata 
"&PodSandboxMetadata{Name:edgecore,Uid:,Namespace:kubeedge,Attempt:0,}"
```
通过查询发现是k8s的设计[kubernetes/issues/119692](https://github.com/kubernetes/kubernetes/issues/119692)
应该如何删除该pod
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
之所以会导致该pod会出现，是当我第一次加入边缘节点时，keadm报错
不能在$PATH找到pause exectuable，但实际上，已经成功编译好了适用于RISCV的[pause](https://github.com/kubernetes-csi/driver-registrar)，于是重新加入边缘节点，此时出现了上述的一系列问题
**Environment**:
- System Information:
OS: OpenEuler23.09 preview
Architecure: RISCV
Container Runtime: iSulad 
iSulad Client Version:	2.1.5
iSulad Server Version:	2.1.5
OCI config Version:	1.0.1
iSulad已启用cri v1 api

- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.30.1
Server Version: v1.30.1
```
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 
v1.17.0

**Comment by Shelley-BaoYue** [comment]
https://kubeedge.io/docs/faq/setup#failed-to-reserve-sandbox-name

**Comment by DeJeune** [comment]
> https://kubeedge.io/docs/faq/setup#failed-to-reserve-sandbox-name

请问我容器引擎使用的是isula，可以使用ctr工具来删除吗？

**Comment by Shelley-BaoYue** [comment]
> > https://kubeedge.io/docs/faq/setup#failed-to-reserve-sandbox-name
> 
> 请问我容器引擎使用的是isula，可以使用ctr工具来删除吗？

Sorry, I didn't notice it was `isulad`, but I think you can try to solve it in a similar way

**Comment by luomengY** [comment]
> > https://kubeedge.io/docs/faq/setup#failed-to-reserve-sandbox-name
> 
> 请问我容器引擎使用的是isula，可以使用ctr工具来删除吗？

isula rm -f contianerid

**Comment by luomengY** [comment]
> > > https://kubeedge.io/docs/faq/setup#failed-to-reserve-sandbox-name
> > 
> > 
> > 请问我容器引擎使用的是isula，可以使用ctr工具来删除吗？
> 
> isula rm -f containerId

**Comment by DeJeune** [comment]
> > > https://kubeedge.io/docs/faq/setup#failed-to-reserve-sandbox-name
> > 
> > 
> > 请问我容器引擎使用的是isula，可以使用ctr工具来删除吗？
> 
> Sorry, I didn't notice it was `isulad`, but I think you can try to solve it in a similar way

感谢，问题已解决
