### ISSUE TITLE
Support long-term offline edge node, the status of pod could be running but not terminating after the edge node is ready? 

### ISSUE THREAD

**Issue by todayisgood** [kubeedge/kubeedge#572]
**What would you like to be added**:
The status of the pod should be running but not terminating after the edge node is ready, if the container is running normally at the edge node.
**Why is this needed**:
One pod is running on a edge node. After the edge node is not ready, the status of the pod will be on "Unknown".  And after the edge node is read, the status of the pod will be on "Terminating" even if the container is still running normally at the edge node. It's the same as kubelet. That will not support long-term offline edge nodes.

**Comment by sids-b** [comment]
@todayisgood Maybe this can help ?

https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#taint-based-evictions

**Comment by larryck** [comment]
Do we have any updates on this issue?  I agree edge system need to tolerate long-term offline.
