### ISSUE TITLE
add device twin fault when using device apiversion v1beta1

### ISSUE THREAD

**Issue by hollow2003** [kubeedge/kubeedge#5758]
**What happened and what you expected to happen**:
I'd like to add a device to my edge node,this is my device model and device config
![image](https://github.com/user-attachments/assets/839930d1-ac4a-4552-9f50-a06178be1c26)
![image](https://github.com/user-attachments/assets/15956998-f613-42c5-868a-ee13dc8e73c6)
After that I want to use mqtt to update my device twin status,however I get the below response
![image](https://github.com/user-attachments/assets/a0e62184-2ff6-47d7-8655-b31a612448a5)
First time I update the twin, it would be possible to see the content of twin in response.However after that every response twins is {}.So I check the edge node's output. It's said that add device error because can't get the dmi client of mqtt.To be honest I don't know what dmi is and whether is already installed in kubeedge,or is it fatal to not config dmi?Besides,compared to v1alpha2,the device config about twin does not have the "desire" key anymore,is it equal to config it in the properties in spec?And how could I get it through mqtt?

**Environment**:
- Kubernetes version (use `kubectl version`):
![image](https://github.com/user-attachments/assets/23041664-128f-427c-a587-87b7b3bb5324)

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
1.17

**Comment by wbc6080** [comment]
DMI is the unified interface for device management in kubeedge and is the communication bridge between mapper and edgecore. Now kubeedge uses the mapper device management plugin to manage devices. Updating devicetwin need to be completed through mapper. Here are some documentation https://kubeedge.io/docs/developer/dmi https://kubeedge.io/docs/concept/device/mapper https://kubeedge.io/docs/developer/mapper-framework. You need to define a mapper for your device to manage and report devicetwin messages.

**Comment by wbc6080** [comment]
In addition, there is `desire` field in device crd. You can refer to https://kubeedge.io/docs/concept/device/device_crds#device-instance-sample

**Comment by hollow2003** [comment]
I'm appreciated to know that.I do have my own mapper adapted to my device.It update device status through publish MQTT messeage in /evets/device/+/twin/updated.
![image](https://github.com/user-attachments/assets/ecd916bb-1bb9-44dd-8ba7-238ccab9344a)
![image](https://github.com/user-attachments/assets/1b1b5a24-3510-4d07-aa62-e54adde86158)

After I use this method to update my device twin,I check out the database in the edge.It seems that my device twin do exist.However,most of the values are null.At the same time,I found that the field name of the twin such as expectedValue do not match the "desired" in device config.
![image](https://github.com/user-attachments/assets/fc4a4457-f61e-43ee-9d1a-0f3d4c6cbd11)
I'm still confused that whether I should set up the device twin in my device instance config or not.The "status","twins" field still can be recongenized,but it appears that it doesn't work at all.Or maybe it's just the format of my MQTT message is wrong?
BTW，I find that the MQTT topics isn't match in eventbus of version 1.17 and the definition.The definition refer to .
![image](https://github.com/user-attachments/assets/9e13743d-bc9b-4e22-8803-225a943c27c7)
https://github.com/kubeedge/kubeedge/blob/f4471e15c89ce9cf383054c02ccd724e1ad4e7a9/edge/pkg/eventbus/mqtt/client.go.
When I use the topic that this link defined,It can't be recongenized by eventbus.Due to that,I change my kubeedge version to v1.15.3.However,every problems I have do not be solved.Only I can confirm that MQTT topics match in this version.

**Comment by wbc6080** [comment]
After DMI is implemented, kubeedge will only accept device update information reported by DMI, and users cannot implement mqtt topic to report devicetwin as the previous way. mapper reports devicetwin through the ReportDeviceStatus function in the DMI grpc interface https://github.com/kubeedge/kubeedge/blob/master/staging/src/github.com/kubeedge/mapper-framework/_template/mapper/device/devicetwin.go#L63

**Comment by hollow2003** [comment]
I check out the code dealing with device twin.https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/devicetwin/dtmanager/twin.go
And I figure out how it valiate the MQTT message.So I adapte my MQTT message format to it.Here is my MQTT message.
![image](https://github.com/user-attachments/assets/21055ba5-a402-4ef5-b1e7-dd4f31d89e52)
After that it can be possible to change device status including expected(desired) and actual(reported) value through MQTT and synchronized to the cloud.
