### ISSUE TITLE
How can i get device messages which eventhub send to deviceT

### ISSUE THREAD

**Issue by chuanyezaici** [kubeedge/kubeedge#576]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by sids-b** [comment]
This is a dup of #577 closing this issue.
