### ISSUE TITLE
edgecore error Error: failed to get CA certificate, err: Get "https://xx/ca.crt": remote error: tls: bad certificate

### ISSUE THREAD

**Issue by niyelail** [kubeedge/kubeedge#5766]
# cloudcore 
```
I0730 10:17:07.223355       1 log.go:194] http: TLS handshake error from 114.241.82.90:1391: tls: client didn't provide a certificate
```

# edgecore
```
F0730 02:15:34.218333 3441209 certmanager.go:96] Error: failed to get CA certificate, err: Get "https://101.200.139.87:10002/ca.crt": remote error: tls: bad certificate
```
# other
1. Without CA and Certs, aren't they automatically generated?
2. edgecore.yaml The token is correct

**Comment by WillardHu** [comment]
Which version of KubeEdge?

**Comment by WillardHu** [comment]
Cloud-edge logs appear to occur at different times

**Comment by niyelail** [comment]
Version: kubernetes v1.26.3
edge and cloud core is v1.16.3

- edge log:
F0730 11:52:12.041431 3493387 certmanager.go:96] Error: failed to get CA certificate, err: Get "https://101.200.139.87:10002/ca.crt": remote error: tls: bad certificate

- cloud log
I0730 11:52:11.950628       1 log.go:194] http: TLS handshake error from 114.241.82.90:2727: tls: client didn't provide a certificate

**Comment by niyelail** [comment]
> Cloud-edge logs appear to occur at different times

Version: kubernetes v1.26.3
edge and cloud core is v1.16.3

edge log:
F0730 11:52:12.041431 3493387 certmanager.go:96] Error: failed to get CA certificate, err: Get "https://101.200.139.87:10002/ca.crt": remote error: tls: bad certificate

cloud log
I0730 11:52:11.950628 1 log.go:194] http: TLS handshake error from 114.241.82.90:2727: tls: client didn't provide a certificate

**Comment by WillardHu** [comment]
It may be caused by the difference between the cloud and the edge time zone, and the timeliness of the token is only 12 hours by default.

**Comment by niyelail** [comment]
> It may be caused by the difference between the cloud and the edge time zone, and the timeliness of the token is only 12 hours by default.

After adjusting the time on the edge and rechecking the token, the above error still occurred

**Comment by niyelail** [comment]
> It may be caused by the difference between the cloud and the edge time zone, and the timeliness of the token is only 12 hours by default.

Cloud: 
I0730 13:26:15.378125       1 log.go:194] http: TLS handshake error from 114.241.82.90:1787: tls: client didn't provide a certificate

Edge:
F0730 13:26:15.387639    4721 certmanager.go:96] Error: failed to get CA certificate, err: Get "https://101.200.139.87:10002/ca.crt": remote error: tls: bad certificate

**Comment by WillardHu** [comment]
You can check whether the token in the /etc/kubeedge/bootstrap-edgecore.conf file is correct.

**Comment by niyelail** [comment]
I rechecked and they are consistent
/etc/kubeedge/bootstrap-edgecore.conf and /etc/kubeedge/config/edgecore.yaml

**Comment by niyelail** [comment]
> 您可以检查 /etc/kubeedge/bootstrap-edgecore.conf 文件中的 token 是否正确。
I rechecked and they are consistent
/etc/kubeedge/config/edgecore.yaml and /etc/kubeedge/bootstrap-edgecore.conf

**Comment by niyelail** [comment]
> You can check whether the token in the /etc/kubeedge/bootstrap-edgecore.conf file is correct.

I rechecked and they are consistent
/etc/kubeedge/config/edgecore.yaml and /etc/kubeedge/bootstrap-edgecore.conf

**Comment by WillardHu** [comment]
https://github.com/kubeedge/kubeedge/blob/release-1.16/edge/pkg/edgehub/common/http/http.go#L42
When edgecore gets the certificate, the http client skips the tls verification, and this issue is basically caused by the token.

**Comment by niyelail** [comment]
Edgecore did not obtain the certificate, and the CA and Certs under/etc/kubeedge have not been created

The startup information for Edgecore is as follows：

<details>
W0730 14:22:56.102019   43344 validation.go:71] NodeIP is empty , use default ip which can connect to cloud.
I0730 14:22:56.102046   43344 server.go:102] Version: v1.16.3
I0730 14:22:56.133500   43344 sql.go:21] Begin to register twin db model
I0730 14:22:56.133597   43344 module.go:52] Module twin registered successfully
I0730 14:22:56.134891   43344 module.go:52] Module edged registered successfully
I0730 14:22:56.134905   43344 module.go:52] Module websocket registered successfully
I0730 14:22:56.134909   43344 module.go:52] Module eventbus registered successfully
I0730 14:22:56.134924   43344 metamanager.go:41] Begin to register metamanager db model
I0730 14:22:56.134960   43344 module.go:52] Module metamanager registered successfully
W0730 14:22:56.134967   43344 module.go:55] Module servicebus is disabled, do not register
W0730 14:22:56.134982   43344 module.go:55] Module edgestream is disabled, do not register
W0730 14:22:56.134988   43344 module.go:55] Module testManager is disabled, do not register
table `device` already exists, skip
table `device_attr` already exists, skip
table `device_twin` already exists, skip
table `sub_topics` already exists, skip
table `meta` already exists, skip
table `meta_v2` already exists, skip
table `target_urls` already exists, skip
I0730 14:22:56.135672   43344 core.go:46] starting module twin
I0730 14:22:56.135686   43344 core.go:46] starting module edged
I0730 14:22:56.135698   43344 core.go:46] starting module websocket
I0730 14:22:56.135709   43344 core.go:46] starting module eventbus
I0730 14:22:56.135724   43344 core.go:46] starting module metamanager
I0730 14:22:56.135756   43344 edged.go:122] Starting edged...
I0730 14:22:56.135862   43344 http.go:42] tlsConfig InsecureSkipVerify true
I0730 14:22:56.135927   43344 server.go:370] "Kubelet version" kubeletVersion="v0.0.0-master+$Format:%H$"
I0730 14:22:56.135948   43344 server.go:372] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0730 14:22:56.135961   43344 common.go:97] start connect to mqtt server with client id: hub-client-sub-1722320576
I0730 14:22:56.135975   43344 common.go:99] client hub-client-sub-1722320576 isconnected: false
I0730 14:22:56.136047   43344 process.go:119] Begin to sync sqlite 
E0730 14:22:56.136124   43344 common.go:101] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
I0730 14:22:56.136206   43344 dmiworker.go:68] dmi worker start
I0730 14:22:56.136289   43344 dmiworker.go:219] success to init device model info from db
I0730 14:22:56.136326   43344 dmiworker.go:240] success to init device info from db
I0730 14:22:56.136359   43344 dmiworker.go:260] success to init device mapper info from db
I0730 14:22:56.136375   43344 server_others.go:13] init uds socket: /etc/kubeedge/dmi.sock
I0730 14:22:56.136384   43344 server.go:495] "Failed to get the kubelet's cgroup. Kubelet system container metrics may be missing." err="cpu and memory cgroup hierarchy not unified.  cpu: /user.slice, memory: /user.slice/user-0.slice/session-3.scope"
I0730 14:22:56.139405   43344 server.go:421] "No api server defined - no events will be sent to API server"
I0730 14:22:56.139419   43344 server.go:523] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
I0730 14:22:56.139713   43344 container_manager_linux.go:265] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
I0730 14:22:56.139926   43344 container_manager_linux.go:270] "Creating Container Manager object based on Node Config" nodeConfig={"RuntimeCgroupsName":"","SystemCgroupsName":"","KubeletCgroupsName":"","KubeletOOMScoreAdj":-999,"ContainerRuntime":"","CgroupsPerQOS":true,"CgroupRoot":"/","CgroupDriver":"systemd","KubeletRootDir":"/var/lib/edged","ProtectKernelDefaults":false,"KubeReservedCgroupName":"","SystemReservedCgroupName":"","ReservedSystemCPUs":{},"EnforceNodeAllocatable":{"pods":{}},"KubeReserved":null,"SystemReserved":null,"HardEvictionThresholds":[{"Signal":"memory.available","Operator":"LessThan","Value":{"Quantity":"100Mi","Percentage":0},"GracePeriod":0,"MinReclaim":null},{"Signal":"nodefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.1},"GracePeriod":0,"MinReclaim":null},{"Signal":"nodefs.inodesFree","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05},"GracePeriod":0,"MinReclaim":null},{"Signal":"imagefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.15},"GracePeriod":0,"MinReclaim":null}],"QOSReserved":{},"CPUManagerPolicy":"none","CPUManagerPolicyOptions":null,"TopologyManagerScope":"container","CPUManagerReconcilePeriod":10000000000,"ExperimentalMemoryManagerPolicy":"None","ExperimentalMemoryManagerReservedMemory":null,"PodPidsLimit":-1,"EnforceCPULimits":true,"CPUCFSQuotaPeriod":100000000,"TopologyManagerPolicy":"none","ExperimentalTopologyManagerPolicyOptions":null}
I0730 14:22:56.139963   43344 topology_manager.go:136] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
I0730 14:22:56.139978   43344 container_manager_linux.go:301] "Creating device plugin manager"
I0730 14:22:56.140008   43344 state_mem.go:36] "Initialized new in-memory state store"
I0730 14:22:56.142903   43344 kubelet.go:272] "Adding static pod path" path="/etc/kubeedge/manifests"
I0730 14:22:56.143206   43344 kuberuntime_manager.go:256] "Container runtime initialized" containerRuntime="docker" version="25.0.4" apiVersion="v1"
I0730 14:22:56.143577   43344 server.go:767] "Started kubelet"
I0730 14:22:56.144175   43344 server.go:189] "Starting to listen read-only" address="127.0.0.1" port=10350
I0730 14:22:56.144575   43344 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
E0730 14:22:56.144781   43344 cri_stats_provider.go:455] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/docker"
E0730 14:22:56.144812   43344 kubelet.go:1297] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
I0730 14:22:56.144920   43344 volume_manager.go:284] "Starting Kubelet Volume Manager"
I0730 14:22:56.145167   43344 server.go:430] "Adding debug handlers to kubelet server"
I0730 14:22:56.145308   43344 desired_state_of_world_populator.go:145] "Desired state populator starts to run"
I0730 14:22:56.153741   43344 kubelet_network_linux.go:63] "Initialized iptables rules." protocol="IPv4"
I0730 14:22:56.155377   43344 kubelet_network_linux.go:63] "Initialized iptables rules." protocol="IPv6"
I0730 14:22:56.155399   43344 status_manager.go:207] "Starting to sync pod status with apiserver"
I0730 14:22:56.155426   43344 kubelet.go:2144] "Starting kubelet main sync loop"
E0730 14:22:56.155504   43344 kubelet.go:2168] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
F0730 14:22:56.168923   43344 certmanager.go:96] Error: failed to get CA certificate, err: Get "https://101.200.139.87:10002/ca.crt": remote error: tls: bad certificate
</details>

**Comment by niyelail** [comment]
> https://github.com/kubeedge/kubeedge/blob/release-1.16/edge/pkg/edgehub/common/http/http.go#L42 When edgecore gets the certificate, the http client skips the tls verification, and this issue is basically caused by the token.

Edgecore did not obtain the certificate, and the CA and Certs under/etc/kubeedge have not been created

The startup information for Edgecore is as follows：
<details>
W0730 14:22:56.102019 43344 validation.go:71] NodeIP is empty , use default ip which can connect to cloud. I0730 14:22:56.102046 43344 server.go:102] Version: v1.16.3 I0730 14:22:56.133500 43344 sql.go:21] Begin to register twin db model I0730 14:22:56.133597 43344 module.go:52] Module twin registered successfully I0730 14:22:56.134891 43344 module.go:52] Module edged registered successfully I0730 14:22:56.134905 43344 module.go:52] Module websocket registered successfully I0730 14:22:56.134909 43344 module.go:52] Module eventbus registered successfully I0730 14:22:56.134924 43344 metamanager.go:41] Begin to register metamanager db model I0730 14:22:56.134960 43344 module.go:52] Module metamanager registered successfully W0730 14:22:56.134967 43344 module.go:55] Module servicebus is disabled, do not register W0730 14:22:56.134982 43344 module.go:55] Module edgestream is disabled, do not register W0730 14:22:56.134988 43344 module.go:55] Module testManager is disabled, do not register table `device` already exists, skip table `device_attr` already exists, skip table `device_twin` already exists, skip table `sub_topics` already exists, skip table `meta` already exists, skip table `meta_v2` already exists, skip table `target_urls` already exists, skip I0730 14:22:56.135672 43344 core.go:46] starting module twin I0730 14:22:56.135686 43344 core.go:46] starting module edged I0730 14:22:56.135698 43344 core.go:46] starting module websocket I0730 14:22:56.135709 43344 core.go:46] starting module eventbus I0730 14:22:56.135724 43344 core.go:46] starting module metamanager I0730 14:22:56.135756 43344 edged.go:122] Starting edged... I0730 14:22:56.135862 43344 http.go:42] tlsConfig InsecureSkipVerify true I0730 14:22:56.135927 43344 server.go:370] "Kubelet version" kubeletVersion="v0.0.0-master+$Format:%H$" I0730 14:22:56.135948 43344 server.go:372] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK="" I0730 14:22:56.135961 43344 common.go:97] start connect to mqtt server with client id: hub-client-sub-1722320576 I0730 14:22:56.135975 43344 common.go:99] client hub-client-sub-1722320576 isconnected: false I0730 14:22:56.136047 43344 process.go:119] Begin to sync sqlite E0730 14:22:56.136124 43344 common.go:101] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused I0730 14:22:56.136206 43344 dmiworker.go:68] dmi worker start I0730 14:22:56.136289 43344 dmiworker.go:219] success to init device model info from db I0730 14:22:56.136326 43344 dmiworker.go:240] success to init device info from db I0730 14:22:56.136359 43344 dmiworker.go:260] success to init device mapper info from db I0730 14:22:56.136375 43344 server_others.go:13] init uds socket: /etc/kubeedge/dmi.sock I0730 14:22:56.136384 43344 server.go:495] "Failed to get the kubelet's cgroup. Kubelet system container metrics may be missing." err="cpu and memory cgroup hierarchy not unified. cpu: /user.slice, memory: /user.slice/user-0.slice/session-3.scope" I0730 14:22:56.139405 43344 server.go:421] "No api server defined - no events will be sent to API server" I0730 14:22:56.139419 43344 server.go:523] "--cgroups-per-qos enabled, but --cgroup-root was not specified. defaulting to /" I0730 14:22:56.139713 43344 container_manager_linux.go:265] "Container manager verified user specified cgroup-root exists" cgroupRoot=[] I0730 14:22:56.139926 43344 container_manager_linux.go:270] "Creating Container Manager object based on Node Config" nodeConfig={"RuntimeCgroupsName":"","SystemCgroupsName":"","KubeletCgroupsName":"","KubeletOOMScoreAdj":-999,"ContainerRuntime":"","CgroupsPerQOS":true,"CgroupRoot":"/","CgroupDriver":"systemd","KubeletRootDir":"/var/lib/edged","ProtectKernelDefaults":false,"KubeReservedCgroupName":"","SystemReservedCgroupName":"","ReservedSystemCPUs":{},"EnforceNodeAllocatable":{"pods":{}},"KubeReserved":null,"SystemReserved":null,"HardEvictionThresholds":[{"Signal":"memory.available","Operator":"LessThan","Value":{"Quantity":"100Mi","Percentage":0},"GracePeriod":0,"MinReclaim":null},{"Signal":"nodefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.1},"GracePeriod":0,"MinReclaim":null},{"Signal":"nodefs.inodesFree","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05},"GracePeriod":0,"MinReclaim":null},{"Signal":"imagefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.15},"GracePeriod":0,"MinReclaim":null}],"QOSReserved":{},"CPUManagerPolicy":"none","CPUManagerPolicyOptions":null,"TopologyManagerScope":"container","CPUManagerReconcilePeriod":10000000000,"ExperimentalMemoryManagerPolicy":"None","ExperimentalMemoryManagerReservedMemory":null,"PodPidsLimit":-1,"EnforceCPULimits":true,"CPUCFSQuotaPeriod":100000000,"TopologyManagerPolicy":"none","ExperimentalTopologyManagerPolicyOptions":null} I0730 14:22:56.139963 43344 topology_manager.go:136] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container" I0730 14:22:56.139978 43344 container_manager_linux.go:301] "Creating device plugin manager" I0730 14:22:56.140008 43344 state_mem.go:36] "Initialized new in-memory state store" I0730 14:22:56.142903 43344 kubelet.go:272] "Adding static pod path" path="/etc/kubeedge/manifests" I0730 14:22:56.143206 43344 kuberuntime_manager.go:256] "Container runtime initialized" containerRuntime="docker" version="25.0.4" apiVersion="v1" I0730 14:22:56.143577 43344 server.go:767] "Started kubelet" I0730 14:22:56.144175 43344 server.go:189] "Starting to listen read-only" address="127.0.0.1" port=10350 I0730 14:22:56.144575 43344 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer" E0730 14:22:56.144781 43344 cri_stats_provider.go:455] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/docker" E0730 14:22:56.144812 43344 kubelet.go:1297] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem" I0730 14:22:56.144920 43344 volume_manager.go:284] "Starting Kubelet Volume Manager" I0730 14:22:56.145167 43344 server.go:430] "Adding debug handlers to kubelet server" I0730 14:22:56.145308 43344 desired_state_of_world_populator.go:145] "Desired state populator starts to run" I0730 14:22:56.153741 43344 kubelet_network_linux.go:63] "Initialized iptables rules." protocol="IPv4" I0730 14:22:56.155377 43344 kubelet_network_linux.go:63] "Initialized iptables rules." protocol="IPv6" I0730 14:22:56.155399 43344 status_manager.go:207] "Starting to sync pod status with apiserver" I0730 14:22:56.155426 43344 kubelet.go:2144] "Starting kubelet main sync loop" E0730 14:22:56.155504 43344 kubelet.go:2168] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]" F0730 14:22:56.168923 43344 certmanager.go:96] Error: failed to get CA certificate, err: Get "https://101.200.139.87:10002/ca.crt": remote error: tls: bad certificate
</details>

**Comment by niyelail** [comment]
> https://github.com/kubeedge/kubeedge/blob/release-1.16/edge/pkg/edgehub/common/http/http.go#L42 When edgecore gets the certificate, the http client skips the tls verification, and this issue is basically caused by the token.

Edgecore did not obtain the certificate, and the CA and Certs under/etc/kubeedge have not been created

The startup information for Edgecore is as follows：
<details>
W0730 14:22:56.102019   43344 validation.go:71] NodeIP is empty , use default ip which can connect to cloud.
I0730 14:22:56.102046   43344 server.go:102] Version: v1.16.3
I0730 14:22:56.133500   43344 sql.go:21] Begin to register twin db model
I0730 14:22:56.133597   43344 module.go:52] Module twin registered successfully
I0730 14:22:56.134891   43344 module.go:52] Module edged registered successfully
I0730 14:22:56.134905   43344 module.go:52] Module websocket registered successfully
I0730 14:22:56.134909   43344 module.go:52] Module eventbus registered successfully
I0730 14:22:56.134924   43344 metamanager.go:41] Begin to register metamanager db model
I0730 14:22:56.134960   43344 module.go:52] Module metamanager registered successfully
W0730 14:22:56.134967   43344 module.go:55] Module servicebus is disabled, do not register
W0730 14:22:56.134982   43344 module.go:55] Module edgestream is disabled, do not register
W0730 14:22:56.134988   43344 module.go:55] Module testManager is disabled, do not register
table `device` already exists, skip
table `device_attr` already exists, skip
table `device_twin` already exists, skip
table `sub_topics` already exists, skip
table `meta` already exists, skip
table `meta_v2` already exists, skip
table `target_urls` already exists, skip
I0730 14:22:56.135672   43344 core.go:46] starting module twin
I0730 14:22:56.135686   43344 core.go:46] starting module edged
I0730 14:22:56.135698   43344 core.go:46] starting module websocket
I0730 14:22:56.135709   43344 core.go:46] starting module eventbus
I0730 14:22:56.135724   43344 core.go:46] starting module metamanager
I0730 14:22:56.135756   43344 edged.go:122] Starting edged...
I0730 14:22:56.135862   43344 http.go:42] tlsConfig InsecureSkipVerify true
I0730 14:22:56.135927   43344 server.go:370] "Kubelet version" kubeletVersion="v0.0.0-master+$Format:%H$"
I0730 14:22:56.135948   43344 server.go:372] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0730 14:22:56.135961   43344 common.go:97] start connect to mqtt server with client id: hub-client-sub-1722320576
I0730 14:22:56.135975   43344 common.go:99] client hub-client-sub-1722320576 isconnected: false
I0730 14:22:56.136047   43344 process.go:119] Begin to sync sqlite 
E0730 14:22:56.136124   43344 common.go:101] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
I0730 14:22:56.136206   43344 dmiworker.go:68] dmi worker start
I0730 14:22:56.136289   43344 dmiworker.go:219] success to init device model info from db
I0730 14:22:56.136326   43344 dmiworker.go:240] success to init device info from db
I0730 14:22:56.136359   43344 dmiworker.go:260] success to init device mapper info from db
I0730 14:22:56.136375   43344 server_others.go:13] init uds socket: /etc/kubeedge/dmi.sock
I0730 14:22:56.136384   43344 server.go:495] "Failed to get the kubelet's cgroup. Kubelet system container metrics may be missing." err="cpu and memory cgroup hierarchy not unified.  cpu: /user.slice, memory: /user.slice/user-0.slice/session-3.scope"
I0730 14:22:56.139405   43344 server.go:421] "No api server defined - no events will be sent to API server"
I0730 14:22:56.139419   43344 server.go:523] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
I0730 14:22:56.139713   43344 container_manager_linux.go:265] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
I0730 14:22:56.139926   43344 container_manager_linux.go:270] "Creating Container Manager object based on Node Config" nodeConfig={"RuntimeCgroupsName":"","SystemCgroupsName":"","KubeletCgroupsName":"","KubeletOOMScoreAdj":-999,"ContainerRuntime":"","CgroupsPerQOS":true,"CgroupRoot":"/","CgroupDriver":"systemd","KubeletRootDir":"/var/lib/edged","ProtectKernelDefaults":false,"KubeReservedCgroupName":"","SystemReservedCgroupName":"","ReservedSystemCPUs":{},"EnforceNodeAllocatable":{"pods":{}},"KubeReserved":null,"SystemReserved":null,"HardEvictionThresholds":[{"Signal":"memory.available","Operator":"LessThan","Value":{"Quantity":"100Mi","Percentage":0},"GracePeriod":0,"MinReclaim":null},{"Signal":"nodefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.1},"GracePeriod":0,"MinReclaim":null},{"Signal":"nodefs.inodesFree","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05},"GracePeriod":0,"MinReclaim":null},{"Signal":"imagefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.15},"GracePeriod":0,"MinReclaim":null}],"QOSReserved":{},"CPUManagerPolicy":"none","CPUManagerPolicyOptions":null,"TopologyManagerScope":"container","CPUManagerReconcilePeriod":10000000000,"ExperimentalMemoryManagerPolicy":"None","ExperimentalMemoryManagerReservedMemory":null,"PodPidsLimit":-1,"EnforceCPULimits":true,"CPUCFSQuotaPeriod":100000000,"TopologyManagerPolicy":"none","ExperimentalTopologyManagerPolicyOptions":null}
I0730 14:22:56.139963   43344 topology_manager.go:136] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
I0730 14:22:56.139978   43344 container_manager_linux.go:301] "Creating device plugin manager"
I0730 14:22:56.140008   43344 state_mem.go:36] "Initialized new in-memory state store"
I0730 14:22:56.142903   43344 kubelet.go:272] "Adding static pod path" path="/etc/kubeedge/manifests"
I0730 14:22:56.143206   43344 kuberuntime_manager.go:256] "Container runtime initialized" containerRuntime="docker" version="25.0.4" apiVersion="v1"
I0730 14:22:56.143577   43344 server.go:767] "Started kubelet"
I0730 14:22:56.144175   43344 server.go:189] "Starting to listen read-only" address="127.0.0.1" port=10350
I0730 14:22:56.144575   43344 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
E0730 14:22:56.144781   43344 cri_stats_provider.go:455] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/docker"
E0730 14:22:56.144812   43344 kubelet.go:1297] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
I0730 14:22:56.144920   43344 volume_manager.go:284] "Starting Kubelet Volume Manager"
I0730 14:22:56.145167   43344 server.go:430] "Adding debug handlers to kubelet server"
I0730 14:22:56.145308   43344 desired_state_of_world_populator.go:145] "Desired state populator starts to run"
I0730 14:22:56.153741   43344 kubelet_network_linux.go:63] "Initialized iptables rules." protocol="IPv4"
I0730 14:22:56.155377   43344 kubelet_network_linux.go:63] "Initialized iptables rules." protocol="IPv6"
I0730 14:22:56.155399   43344 status_manager.go:207] "Starting to sync pod status with apiserver"
I0730 14:22:56.155426   43344 kubelet.go:2144] "Starting kubelet main sync loop"
E0730 14:22:56.155504   43344 kubelet.go:2168] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
F0730 14:22:56.168923   43344 certmanager.go:96] Error: failed to get CA certificate, err: Get "https://101.200.139.87:10002/ca.crt": remote error: tls: bad certificate
</details>

**Comment by niyelail** [comment]
> https://github.com/kubeedge/kubeedge/blob/release-1.16/edge/pkg/edgehub/common/http/http.go#L42 When edgecore gets the certificate, the http client skips the tls verification, and this issue is basically caused by the token.

Edgecore did not obtain the certificate, and the CA and Certs under/etc/kubeedge have not been created

The startup information for Edgecore is as follows：
![image](https://github.com/user-attachments/assets/88ec360c-5ccc-4ef4-8e9e-b41289a718b5)

**Comment by WillardHu** [comment]
Please try `curl -k https://101.200.139.87:10002/ca.crt` to check whether the certificate can be obtained. The token is not required to get the ca.

**Comment by niyelail** [comment]
> Please try to check whether the certificate can be obtained. The token is not required to get the ca.`curl -k https://101.200.139.87:10002/ca.crt`

The running result is as follows：
curl: (56) OpenSSL SSL_read: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate, errno 0

**Comment by WillardHu** [comment]
Does this IP 101.200.139.87 belong to the k8s node? It looks like a proxy service.

**Comment by WillardHu** [comment]
Maybe the certificate verification from your load balancer

**Comment by niyelail** [comment]
> Maybe the certificate verification from your load balancer

This load balancer does not have validation rules. Edgecore can receive requests after startup and printed the following error:
![image](https://github.com/user-attachments/assets/c5adab4b-cdbd-4d04-9c4e-4549eb28c255)

**Comment by WillardHu** [comment]
You can try `curl -k https://<cloudcore ip>:10002/ca.crt` without the load balancer

**Comment by niyelail** [comment]
> 您可以尝试不使用负载均衡器`curl -k https://<cloudcore ip>:10002/ca.crt`

Is it related to the K8S of the AWS cloud service I use.

**Comment by niyelail** [comment]
> You can try `curl -k https://<cloudcore ip>:10002/ca.crt` without the load balancer
Is it related to the K8S of the AWS cloud service I use.

**Comment by niyelail** [comment]
> You can try `curl -k https://<cloudcore ip>:10002/ca.crt` without the load balancer

The file /etc/kubeedge/ca and certs in cloudcore does not have this file either

**Comment by WillardHu** [comment]
It's possible. Mybe you need to do a certificate conversion

edgecore --- [lb certs]  ---> lb server --- [cloudcore certs] ---> cloudcore

**Comment by niyelail** [comment]
> You can try `curl -k https://<cloudcore ip>:10002/ca.crt` without the load balancer

CloudCore don't have these files
    tlsCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsCAKeyFile: /etc/kubeedge/ca/rootCA.key
    tlsCertFile: /etc/kubeedge/certs/edge.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key

**Comment by niyelail** [comment]
> It's possible. Mybe you need to do a certificate conversion
> 
> edgecore --- [lb certs] ---> lb server --- [cloudcore certs] ---> cloudcore

You are correct. I exposed the service type in CloudCore by changing it to NodePort, and EdgeCore was added correctly. Thank you for your help
