### ISSUE TITLE
eventhub

### ISSUE THREAD

**Issue by chuanyezaici** [kubeedge/kubeedge#577]
**How can i get the device message which eventhub send to deviceTwin？**:

**i want to find the message that eventhub subscribe on mosquitte server**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by sids-b** [comment]
Please see this devicetwin documentation http://docs.kubeedge.io/en/latest/modules/edge/eventbus.html
Also tryout led demo https://github.com/kubeedge/examples/tree/master/led-raspberrypi

**Comment by sids-b** [comment]
@chuanyezaici , can we close this issue ?

**Comment by sids-b** [comment]
closing this issue. @chuanyezaici , please feel free to reach out to us via slack or reopen this issue for further discussions :)
