### ISSUE TITLE
 Edge节点加入后云端一直显示其状态Unavailable 

### ISSUE THREAD

**Issue by GuilingQiyu** [kubeedge/kubeedge#5779]
KubeEdge 
> 版本: v1.29.5-kubeedge-v1.18.0  
> 操作系统: Ubuntu 22.04.4 LTS  
> 容器运行时: containerd://1.7.12

云端K8s
> 版本: v1.28.6+k3s2  
> 操作系统: SUSE Linux Enterprise Server 15 SP5  
> 容器运行时: containerd://1.7.11-k3s2

云端使用
`keadm init --advertise-address="192.168.224.131" --profile version=v1.18.0`
部署了CloudCore。

边端使用
`keadm join --cloudcore-ipport=192.168.224.131:10000 --token={token} --kubeedge-version=1.18.0 --with-mqtt=true`
部署了EdgeCore。

均提示安装成功

节点情况概览：
![image](https://github.com/user-attachments/assets/ab7fb154-b3d8-4be3-804d-4544a3db775e)

可见Edge节点运行不正常

通过`journalctl -u edgecore.service -xe`查看边端日志，循环提示
> Aug 04 06:38:22 edge edgecore[871]: I0804 06:38:22.893315     871 common.go:97] start connect to mqtt server with client id: hub-client-sub-1722751558
> Aug 04 06:38:22 edge edgecore[871]: I0804 06:38:22.893385     871 common.go:99] client hub-client-sub-1722751558 isconnected: false
> Aug 04 06:38:22 edge edgecore[871]: E0804 06:38:22.893636     871 common.go:101] connect error: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
> Aug 04 06:38:23 edge edgecore[871]: E0804 06:38:23.081160     871 kubelet.go:2765] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
> 

通过云端控制台查看Edge节点情况，如下：
![image](https://github.com/user-attachments/assets/1a9c99c9-0e72-4412-95d2-2ce78c454f4e)

**Comment by wbc6080** [comment]
https://kubeedge.io/docs/faq/setup/#cni-plugin-not-initializedcni-config-uninitialized

**Comment by GuilingQiyu** [comment]
管用，谢谢
