### ISSUE TITLE
使用keadm正常安装CloudCore和EdgeCore后使用keadm reset卸载CloudCore换另一个advertise-address再次init CloudCore，出现问题

### ISSUE THREAD

**Issue by GuilingQiyu** [kubeedge/kubeedge#5794]
> 版本: v1.28.6+k3s2
> 操作系统: SUSE Linux Enterprise Server 15 SP5
> 容器运行时: containerd://1.7.11-k3s2

使用keadm正常安装CloudCore和EdgeCore后，边缘节点正常显示，可以正常部署Deployment。
此时使用keadm reset重置CloudCore，**手动删除边缘节点**
**换用另一个advertise-address**再次init CloudCore，
CloudCore的Pod无法成功初始化。
初步分析日志显示未找到证书

![图片](https://github.com/user-attachments/assets/62fd7635-5140-45c9-8894-3dd28d1b0421)

Pod日志信息如下
[cloudcore-5b87fc6678-sc7p9_cloudcore.log](https://github.com/user-attachments/files/16568936/cloudcore-5b87fc6678-sc7p9_cloudcore.log)

**Comment by Shelley-BaoYue** [comment]
What's the version of keadm and cloudcore?

**Comment by WillardHu** [comment]
These warns do not affect the startup of cloudcore. You need to search for other logs.

**Comment by GuilingQiyu** [comment]
> What's the version of keadm and cloudcore? 

v1.18.0
