### ISSUE TITLE
Any quick path of delpoy KubeEdge for development and bug reproduction?

### ISSUE THREAD

**Issue by magichan** [kubeedge/kubeedge#5828]
Hello everyone, I am very interested in the KubeEdge project and would like to participate in it.

Currently, I plan to check the Issues on a daily basis to see if there are any Bugs I can fix or Features I can contribute to.

The above work requires frequent construction of different versions of the KubeEdge environment, therefore, I would like to know what tools and solutions the community members use to help themselves quickly build a reproduction environment.

Don't worry about the computational resources for me; I have an idle ARM architecture physical machine with enough ample resources.

**Comment by wbc6080** [comment]
You can use local-up script automatically deploy a kubeedge cluster https://deploy-preview-600--competent-hypatia-4195b7.netlify.app/docs/developer/local_up_kubeedge

**Comment by magichan** [comment]
@wbc6080 Thank you, I will try it after work, and if it goes smoothly, I will close this issue myself.

**Comment by magichan** [comment]
After check, it work.

close the issue, thx!

I add a little pr  https://github.com/kubeedge/kubeedge/pull/5832 to enhance the script,  hope @wbc6080  can help me review it.

**Comment by magichan** [comment]
After check, it work.

close the issue, thx!

I add a little pr https://github.com/kubeedge/kubeedge/pull/5832 to enhance the script, hope @wbc6080 can help me review it.
