### ISSUE TITLE
the meaning of lastversion shown in https://kubeedge.io/latestversion

### ISSUE THREAD

**Issue by magichan** [kubeedge/kubeedge#5851]
**What happened and what you expected to happen**:

While reading the code, I found that the result of https://kubeedge.io/latestversion is v1.15.1, but the latest version of KubeEdge is v1.18.0.

Could v1.15.1 be a different manifest version, such as the Helm package for KubeEdge?

**How to reproduce it (as minimally and precisely as possible)**:
```sh
wget https://kubeedge.io/latestversion
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by magichan** [comment]
@Shelley-BaoYue  
If you agree that this is a bug,
could you please help me change the label from kind/question to kind/bug?

**Comment by Shelley-BaoYue** [comment]
You can help update version here https://github.com/kubeedge/website/blob/master/functions/latestversion.js#L3
