### ISSUE TITLE
keadm  join里涉及到一些yum操作，在无网的环境下怎么办？

### ISSUE THREAD

**Issue by liangkun16** [kubeedge/kubeedge#5852]
如题，节点机器是不通公网的。

**Comment by Shelley-BaoYue** [comment]
Currently, there is no official offline installation document in KubeEdge community, but there are some developers are participating in the feature. You can search for other unofficial offline deployment installation for reference.

**Comment by magichan** [comment]
@liangkun16   Under the default configuration, during the addition of the edge node using keadm join, I only observed external dependencies for the images `registry.k8s.io/pause` and `kubeedge/installation-package`.

Would you mind providing the configuration under which yum operations are required?

**Comment by liangkun16** [comment]
> @liangkun16 Under the default configuration, during the addition of the edge node using keadm join, I only observed external dependencies for the images `registry.k8s.io/pause` and `kubeedge/installation-package`.
> 
> Would you mind providing the configuration under which yum operations are required?

不单单是yum操作，还有校验k8s版本，包括 keadm init 有一些helm操作都依赖网络，我这边因为是基地环境，访问外网没那么自由，所以想问下是否有离线的部署kubeedge方式.

**Comment by magichan** [comment]
@liangkun16  I'm currently organizing the steps for the offline deployment. I'll submit a MR on the WebSite Repo within one to two weeks, and I will @ you to review it at that time

**Comment by liangkun16** [comment]
那能不能给个提示，就是关于easzlab/pause:3.9 镜像，keadm始终会去docker.io/easzlab/pause:3.9去pull，我本地节点的机器导入了image也不行，如何能让keadm去我指定的仓库下载Image

**Comment by liangkun16** [comment]
E0913 17:37:46.290953   78716 remote_runtime.go:177] "RunPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox image \"easzlab/pause:3.9\": failed to pull image \"easzlab/pause:3.9\": failed to pull and unpack image \"docker.io/easzlab/pause:3.9\": failed to resolve reference \"docker.io/easzlab/pause:3.9\": failed to do request: context deadline exceeded"

**Comment by liangkun16** [comment]
> @liangkun16
> 
> Hi, the base content of offline install by keadm is ready in [kubeedge/website#639](https://github.com/kubeedge/website/pull/639).
> 
> you may want to check it.

感谢帮忙解决，但是我尝试了一下 edgecore还是无法安装
![image](https://github.com/user-attachments/assets/50353654-9b22-4bdf-aed0-1f346909fe80)

**Comment by magichan** [comment]
@liangkun16  
containerd has namespace concepts, 

you may need to load the image into the `k8s.io` namespace and try again.

**Comment by liangkun16** [comment]
请问下这个证书问题我该怎么解决，我也是按照那个文档部署得 iptables也设置了，certgen.sh 脚本也执行了。配置文件里改打开都打开了。
![image](https://github.com/user-attachments/assets/4ba55c98-fd86-42b9-be02-a8c374f83f44)

**Comment by magichan** [comment]
@liangkun16 This is beyond my knowledge and the scope of this issue, maybe you can open a new issue to ask about this.

**Comment by liangkun16** [comment]
> @liangkun16 This is beyond my knowledge and the scope of this issue, maybe you can open a new issue to ask about this.

[https://github.com/kubeedge/kubeedge/issues/5852#issuecomment-2381071652](url)
