### ISSUE TITLE
What does Controller Manager Deployment do?

### ISSUE THREAD

**Issue by magichan** [kubeedge/kubeedge#5862]
I note the exsit of `deployment_controllermanager.yaml` in mainfest and  controllerManager setting(default value is false) in the `value.yaml`, that means the the service is part of kubeedge deployment. 

But in the latest documentation, I didn't see any relevant introduction.  Has this service been deprecated?

**Environment**:
- Kubernetes version (use `kubectl version`):
None
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):\
V1.18.0

**Comment by Shelley-BaoYue** [comment]
Controller manager is used for nodegroup feature. https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/node-group-management.md#architecture
