### ISSUE TITLE
Get a DeviceList through the API provided by MetaServer on the edge. The Kind field in the return information is incorrect.

### ISSUE THREAD

**Issue by dcdc831** [kubeedge/kubeedge#5890]
**What happened**:

When I get `*v1beta1.DeviceList` using the `clientSet` provided by kubeedge:
```go
	deviceList, err := versionedClient.DevicesV1beta1().Devices(deviceRequest.Namespace).List(ctx, metaV1.ListOptions{
		LabelSelector: deviceRequest.LabelSelector,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list devices: %v", err)
	}
```
an error occurs:
![error](https://github.com/user-attachments/assets/950fbefb-7cfc-42fd-966c-7296d1e21607)

Then I call MetaServer API directly: 
```shell
curl 'http://127.0.0.1:10550/apis/devices.kubeedge.io/v1beta1/namespaces/default/devices'
```
The Kind field in the return information is `DevicList` :
![image](https://github.com/user-attachments/assets/4e01d3bb-d88b-4ede-9c8a-60c77c4e9396)

**What you expected to happen**:

The Kind field in the return information is `DeviceList`.

**Anything else we need to know?**:

This bug might be related to suffix handling.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.28.14
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.18.0
(I also found this bug in kubeedge1.17)

**Comment by wbc6080** [comment]
This problem is similar to #4471 . It is caused by the inaccuracy of the singular and plural conversion of English words when metaserver parses resource types, such as changing devices to devic, or changing namespaces to namespac.

![image](https://github.com/user-attachments/assets/9ce4de7a-3d57-4608-b524-ccb650327210)

/assign
