### ISSUE TITLE
Does KubeEdge has plan to support common CNI such as Cilium?

### ISSUE THREAD

**Issue by FengGaoCSC** [kubeedge/kubeedge#5911]
**What happened and what you expected to happen**:
I notice there is a [blog](https://release-1-18.docs.kubeedge.io/blog/enable-cilium) that enable the Cilium CNI with KubeEdge but need manually configured. 

Does KubeEdge has plan to support common CNI plugin including but not limited to Cilium or just has plan by using EdgeMesh?

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by Shelley-BaoYue** [comment]
Most CNI plugins depend on the edge list-watch capability. You can enable the `dynamiccontroller` in cloudcore and `metaserver` in edgecore of KubeEdge. Some operaters may need to be modified like the cilium. You are welcome to discuss or contribute in the community.

**Comment by FengGaoCSC** [comment]
> Most CNI plugins depend on the edge list-watch capability. You can enable the `dynamiccontroller` in cloudcore and `metaserver` in edgecore of KubeEdge. Some operaters may need to be modified like the cilium. You are welcome to discuss or contribute in the community.

@Shelley-BaoYue 

thanks for your answer. As my understanding, there isn't plan to support common CNI but in theory, `enable the dynamiccontroller in cloudcore and metaserver in edgecore of KubeEdge` could be ok when to support some CNI but maybe some modified on CNI either, so if we want to support some CNI, we will be happy to discuss and contribute in the community. 

thanks & regards

**Comment by Shelley-BaoYue** [comment]
@FengGaoCSC  Feel free to ask any questions or provide your idea here. If there are optimization or fix needed by common CNI plugins, we will plan to enhance those. 😄

**Comment by FengGaoCSC** [comment]
@Shelley-BaoYue 

Thanks very much

**Comment by fujitatomoya** [comment]
@Shelley-BaoYue thanks for openness!

@FengGaoCSC this issue likes like a question but issue, should we close this once. and then come up with concrete design or idea?

**Comment by FengGaoCSC** [comment]
@fujitatomoya 
yes, sound reasonable.
