### ISSUE TITLE
Your Quay.io registry is not accessible to the public.

### ISSUE THREAD

**Issue by wartih** [kubeedge/kubeedge#5936]
**What happened**:
I can't pull image from your public registry.
crictl pull quay.io/kubeedge/cloudcore:v1.17.3
E1029 15:12:50.451994    4234 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = reading manifest v1.17.3 in quay.io/kubeedge/cloudcore: unauthorized: access to the requested resource is not authorized" image="quay.io/kubeedge/cloudcore:v1.17.3"
FATA[0005] pulling image: reading manifest v1.17.3 in quay.io/kubeedge/cloudcore: unauthorized: access to the requested resource is not authorized

**What you expected to happen**:
Successfully pulling images.
**How to reproduce it (as minimally and precisely as possible)**:
keadm init
**Anything else we need to know?**:
The Quay.io registry is also inaccessible through the web, displaying a '403: Unauthorized' error, which suggests that the issue is not related to my network.
**Environment**:
- Kubernetes version (use `kubectl version`): 
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): any version
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:
no matter
  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Shelley-BaoYue** [comment]
All KubeEdge offcial images are pushed to docker.io/kubeedge registry but not Quay.io, please check your contained configure.
