### ISSUE TITLE
Add CI for ARM64 CPU architecture

### ISSUE THREAD

**Issue by martin-g** [kubeedge/kubeedge#5951]
**What would you like to be added/modified**:

I'd like to propose extending the CI workflows to run the jobs on Linux ARM64 runners. 

**Why is this needed**:

https://github.com/kubeedge/kubeedge/issues?q=arm64 shows that there are/were issues related to ARM64/aarch64 and having ARM64 CI runner would be helpful to prevent regressions.

I experimented at my fork (https://github.com/martin-g/kubeedge/pull/1) and overall everything looks good! There is one [issue](https://github.com/martin-g/kubeedge/actions/runs/11739723880/job/32705322479?pr=1) that I need to debug!

I am a member of the [openEuler](https://www.openeuler.org/) team and we are working together with the CNCF Infra team to setup self-hosted ARM64 runners (CC @krook @jeefy) for all CNCF projects. 

What do you think ?
Would you be interested ?

**Comment by wbc6080** [comment]
Looks great!

**Comment by wbc6080** [comment]
Hi @martin-g,  ARM's CI has been unable to pass recently https://github.com/kubeedge/kubeedge/actions/runs/11949831426/job/33310353018. By checking the logs, it seems that some files in the directory `/home/runner/actions-runner/_work/kubeedge/kubeedge/_output/local/_go/cache` cannot be deleted. Can you help log in to the ARM machine to see why there are these files can't be deleted?

**Comment by martin-g** [comment]
Looking !
