### ISSUE TITLE
keadm join failed when use crio runtime：cannot generate pod name without uid in metadata

### ISSUE THREAD

**Issue by shyer** [kubeedge/kubeedge#5955]
**What happened**:
Edge:
./keadm join --cloudcore-ipport=192.168.203.110:10000 --token $TOKEN --cgroupdriver systemd --kubeedge-version v1.19.0 --remote-runtime-endpoint unix:///run/crio/crio.sock

> E1111 05:07:07.595468    1247 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = setting pod sandbox name and id: cannot generate pod name without uid in metadata"

![image](https://github.com/user-attachments/assets/fc6c50c9-6ce3-47d0-a560-4822c635291e)

**What you expected to happen**:
can use crio runtime ok

**How to reproduce it (as minimally and precisely as possible)**:
Cloud:
install-with-keadm: https://kubeedge.io/zh/docs/setup/install-with-keadm

Edge:
1. install crio: https://[cri-o](https://cri-o.io/).io/
2. keadm join：https://kubeedge.io/zh/docs/setup/install-with-keadm#%E8%AE%BE%E7%BD%AE%E8%BE%B9%E7%BC%98%E7%AB%AFkubeedge-%E5%B7%A5%E4%BD%9C%E8%8A%82%E7%82%B9

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.31.2
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.19.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by wbc6080** [comment]
This problem seems to be related with `crio` runtime. Maybe you can refer to the [issue](https://github.com/cri-o/cri-o/issues/3618) and try to upgrade the `crio` version.

**Comment by shyer** [comment]
old version `crio` not require uid, new version `crio` require uid

after crio v1.29，require uid
https://github.com/cri-o/cri-o/blob/release-1.29/internal/factory/sandbox/sandbox.go#L111
![image](https://github.com/user-attachments/assets/059f159e-f021-419b-a204-dc05db07c27a)

before crio v1.28，not require uid
https://github.com/cri-o/cri-o/blob/release-1.28/internal/factory/sandbox/sandbox.go#L107
![image](https://github.com/user-attachments/assets/f7201549-d778-4cdc-934f-0d24c54bbfed)


in that issue https://github.com/cri-o/cri-o/issues/3618 uid is require after 2023
![image](https://github.com/user-attachments/assets/d6af82c1-b484-4572-82ab-a73847752e54)

**Comment by wbc6080** [comment]
OK, I see. There are some steps to configure cri-o runtime in the document https://kubeedge.io/docs/setup/prerequisites/runtime#cri-o  https://kubeedge.io/docs/faq/setup#runtime-related-issues. You can see whether this problem can be solved. If not, you may need to check the cri-o log to see if there is any prompt message.

**Comment by Shelley-BaoYue** [comment]
I tested this issue in PR https://github.com/kubeedge/kubeedge/pull/5960 and the CI with cri-o v1.29.0 succeed to install KubeEdge https://github.com/kubeedge/kubeedge/actions/runs/11829549109/job/32961536211?pr=5960. What's the version of `keadm` in your environment?

**Comment by shyer** [comment]
kubeadm：v1.31.2
crio：v1.29.10
keadm：v1.19.0
