### ISSUE TITLE
Dynamic NameServer configuration based on the CNI availability

### ISSUE THREAD

**Issue by fujitatomoya** [kubeedge/kubeedge#5982]
Revised from https://github.com/kubeedge/kubeedge/issues/5400

**What would you like to be added/modified**:

After [enabling CIlium CNI on KubeEdge](https://kubeedge.io/blog/enable-cilium/), we have Cilium CNI (`cilium-agent` pod) running on the edge nodes as well with edgecore. as https://github.com/kubeedge/kubeedge/issues/5400 points out, with edgecore, NameServer in `/etc/resolv.conf` will be always bound to host system configuration. Originally this should be fine, since the expectation of KubeEdge is that pods at edge nodes use host network interfaces only.
But this comes to the problem for the configuration enabled with Cilium CNI, since edge pods cannot resolve cluster DNS.

https://github.com/kubeedge/kubeedge/issues/5400 also introduces that we can always modify `edgecore.yaml` to reconfigure the DNS as we like. But it would be really much better that, if the edge nodes can be aware of the CNI availability and configure the DNS setting dynamically.

**Why is this needed**:

Eventually better user-experience in terms of KubeEdge supports CNIs.
Updating and modifying the `edgecore.yaml` is user operation burden, and this can be concealed by implementation.

**Implementation Consideration**:

- (Not ideal) CLI option for `keadm join` to specify if the DNS should be set in the cluster access or not. This is easier to add but not exactly solving `user operation burden` in dynamic ways. after all, i would not recommend this approach.
- Implementation in `edgecore` specifically in `MakeKubeClientBridge`. according to `kubelet`, has some check if the CNI is ready to the node that it going to deploy the pods. (the following is to make sure that it only allows the request to start the container with host network interfaces if no CNI is running.) https://github.com/kubernetes/kubernetes/blob/591c75e40b0c861b35e69d4818dffb75f9668402/pkg/kubelet/kubelet.go#L1918-L1922 Probably same mechanism can be implemented in `MakeKubeClientBridge`. with this approach, user can be agnostic from CNI configuration, and no downsides as far as i can see.

**Comment by XmchxUp** [comment]
@fujitatomoya 

### DNS Issue in KubeEdge

### Part 1: KubeEdge EdgeCore Host-DNS Logic source codeAnalysis
<details>
<summary>detail</summary>

##### In KubeEdge, the `edgecore` component initializes the `ResolverConfig` parameter with the default value `/etc/resolv.conf`, and `ClusterDNS` is set to `nil` by default.

```go 
kubeedge/vendor/github.com/kubeedge/api/apis/componentconfig/edgecore/v1alpha2/types.go:391

// ClusterDNS is a list of IP addresses for the cluster DNS server. 
// If set, edged will configure all containers to use this for DNS resolution
// instead of the host's DNS servers.
// Default: nil
// +optional
ClusterDNS []string `json:"clusterDNS,omitempty"`

// ResolverConfig is the resolver configuration file used as the basis
// for the container DNS resolution configuration.
// If set to the empty string, it will override the default and effectively disable DNS lookups.
// Default: "/etc/resolv.conf"
// +optional
ResolverConfig *string `json:"resolvConf,omitempty"`

```

##### Entrypoint: The core logic runs a Kubelet service under the hood.

```go
kubeedge/edge/pkg/edged/edged.go:123

// DefaultRunLiteKubelet will only be changed when EdgeMark is enabled
var DefaultRunLiteKubelet RunLiteKubelet = kubeletserver.Run

func (e *edged) Start() {
    ...
    kubeletErrChan := make(chan error, 1)
    go func() {
        err := DefaultRunLiteKubelet(e.context, e.KubeletServer, e.KubeletDeps, e.FeatureGate)
        if err != nil {
            if !kefeatures.DefaultFeatureGate.Enabled(kefeatures.ModuleRestart) {
                klog.Errorf("Start edged failed, err: %v", err)
                os.Exit(1)
            }
            kubeletErrChan <- err
        }
    }()
    
    kubeletReadyChan := make(chan struct{}, 1)
    go kubeletHealthCheck(e.KubeletServer.ReadOnlyPort, kubeletReadyChan)
    ...
}

```

##### Passing DNS Parameters to Kubelet

- When using the Kubelet service, parameters such as `ClusterDNS` and `ResolverConfig` are passed for use by the `dnsConfigurer`.

```go
kubernetes/pkg/kubelet/kubelet.go:445

clusterDNS := make([]net.IP, 0, len(kubeCfg.ClusterDNS))
for _, ipEntry := range kubeCfg.ClusterDNS {
    ip := netutils.ParseIPSloppy(ipEntry)
    if ip == nil {
        klog.InfoS("Invalid clusterDNS IP", "IP", ipEntry)
    } else {
        clusterDNS = append(clusterDNS, ip)
    }
}
...
&Kubelet{
    ...
    dnsConfigurer: dns.NewConfigurer(kubeDeps.Recorder, nodeRef, nodeIPs, clusterDNS, kubeCfg.ClusterDomain, kubeCfg.ResolverConfig),
}


```

- The Kubelet implements a RuntimeHelper interface, and one key function is `GetPodDNS`, which retrieves the DNS settings for a given Pod.
- So when a pod is created and needs to set up DNS, this interface is called.

```go
kubelet/kubelet_network.go:56

// GetPodDNS returns DNS settings for the pod.
// This function is defined in kubecontainer.RuntimeHelper interface so we
// have to implement it.
func (kl *Kubelet) GetPodDNS(pod *v1.Pod) (*runtimeapi.DNSConfig, error) {
      return kl.dnsConfigurer.GetPodDNS(pod)
}


// RuntimeHelper wraps kubelet to make container runtime
// able to get necessary informations like the RunContainerOptions, DNS settings, Host IP.
type RuntimeHelper interface {
      GenerateRunContainerOptions(ctx context.Context, pod *v1.Pod, container *v1.Container, podIP string, podIPs []string) (contOpts *RunContainerOptions, cleanupAction func(), err error)
      GetPodDNS(pod *v1.Pod) (dnsConfig *runtimeapi.DNSConfig, err error)
      // GetPodCgroupParent returns the CgroupName identifier, and its literal cgroupfs form on the host
      // of a pod.
      GetPodCgroupParent(pod *v1.Pod) string
      GetPodDir(podUID types.UID) string
      GeneratePodHostNameAndDomain(pod *v1.Pod) (hostname string, hostDomain string, err error)
      // GetExtraSupplementalGroupsForPod returns a list of the extra
      // supplemental groups for the Pod. These extra supplemental groups come
      // from annotations on persistent volumes that the pod depends on.
      GetExtraSupplementalGroupsForPod(pod *v1.Pod) []int64

      // GetOrCreateUserNamespaceMappings returns the configuration for the sandbox user namespace
      GetOrCreateUserNamespaceMappings(pod *v1.Pod) (*runtimeapi.UserNamespace, error)

      // PrepareDynamicResources prepares resources for a pod.
      PrepareDynamicResources(pod *v1.Pod) error

      // UnprepareDynamicResources unprepares resources for a a pod.
      UnprepareDynamicResources(pod *v1.Pod) error
}

```

##### Default DNS Behavior in EdgeCore

- **Defaults**:
    - `ClusterDNS`: `nil`
    - `ResolverConfig`: `/etc/resolv.conf`
    - Pod `DNSPolicy`: `ClusterFirst`
    - Pod `HostNetwork`: `false`

```go 
k8s.io/api/core/v1/types.go:3538

      // Set DNS policy for the pod.
      // Defaults to "ClusterFirst".
      // Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'.
      // DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy.
      // To have DNS options set along with hostNetwork, you have to specify DNS policy
      // explicitly to 'ClusterFirstWithHostNet'.
      // +optional
      DNSPolicy DNSPolicy `json:"dnsPolicy,omitempty" protobuf:"bytes,6,opt,name=dnsPolicy,casttype=DNSPolicy"`

      // Host networking requested for this pod. Use the host's network namespace.
      // If this option is set, the ports that will be used must be specified.
      // Default to false.
      // +k8s:conversion-gen=false
      // +optional
      HostNetwork bool `json:"hostNetwork,omitempty" protobuf:"varint,11,opt,name=hostNetwork"`
```

##### DNS Logic

- 1. **DNSPolicy Evaluation**:
    - `DNSPolicy` is checked in `getPodDNSType`. By default:
        - `ClusterFirst` is used if the Pod does not enable `HostNetwork`.
        - Otherwise, it falls back to `Host` DNS configuration.
- 2. **`GetPodDNS` Behavior**:
    - If the Pod's DNS type is `podDNSCluster` and `clusterDNS` is not empty, it uses `clusterDNS`.
    - Otherwise, it falls back to the `podDNSHost` logic:
        - If `ResolverConfig` is empty, it defaults to `127.0.0.1`.
        - Otherwise, it uses the specified `ResolverConfig`.

- Thus, `edgecore` ensures that Kubelet uses the specified `ResolverConfig`. To use the cluster's DNS (e.g., `10.96.0.10`), you need to explicitly set `ClusterDNS`.

```go
k8s.io/kubernetes/pkg/kubelet/network/dns/dns.go:303

// IsHostNetworkPod returns whether the host networking requested for the given Pod.
// Pod must not be nil.
func IsHostNetworkPod(pod *v1.Pod) bool {
      return pod.Spec.HostNetwork
}


func getPodDNSType(pod *v1.Pod) (podDNSType, error) {
      dnsPolicy := pod.Spec.DNSPolicy
      switch dnsPolicy {
      case v1.DNSNone:
            return podDNSNone, nil
      case v1.DNSClusterFirstWithHostNet:
            return podDNSCluster, nil
      case v1.DNSClusterFirst:
            if !kubecontainer.IsHostNetworkPod(pod) {
                  return podDNSCluster, nil
            }
            // Fallback to DNSDefault for pod on hostnetwork.
            fallthrough
      case v1.DNSDefault:
            return podDNSHost, nil
      }
      // This should not happen as kube-apiserver should have rejected
      // invalid dnsPolicy.
      return podDNSCluster, fmt.Errorf("invalid DNSPolicy=%v", dnsPolicy)
}


// GetPodDNS returns DNS settings for the pod.
func (c *Configurer) GetPodDNS(pod *v1.Pod) (*runtimeapi.DNSConfig, error) {
      dnsConfig, err := c.getHostDNSConfig(c.ResolverConfig)
      if err != nil {
            return nil, err
      }

      dnsType, err := getPodDNSType(pod)
      if err != nil {
            klog.ErrorS(err, "Failed to get DNS type for pod. Falling back to DNSClusterFirst policy.", "pod", klog.KObj(pod))
            dnsType = podDNSCluster
      }
      switch dnsType {
      case podDNSNone:
            // DNSNone should use empty DNS settings as the base.
            dnsConfig = &runtimeapi.DNSConfig{}
      case podDNSCluster:
            if len(c.clusterDNS) != 0 {
                  // For a pod with DNSClusterFirst policy, the cluster DNS server is
                  // the only nameserver configured for the pod. The cluster DNS server
                  // itself will forward queries to other nameservers that is configured
                  // to use, in case the cluster DNS server cannot resolve the DNS query
                  // itself.
                  dnsConfig.Servers = []string{}
                  for _, ip := range c.clusterDNS {
                        dnsConfig.Servers = append(dnsConfig.Servers, ip.String())
                  }
                  dnsConfig.Searches = c.generateSearchesForDNSClusterFirst(dnsConfig.Searches, pod)
                  dnsConfig.Options = defaultDNSOptions
                  break
            }
            // clusterDNS is not known. Pod with ClusterDNSFirst Policy cannot be created.
            nodeErrorMsg := fmt.Sprintf("kubelet does not have ClusterDNS IP configured and cannot create Pod using %q policy. Falling back to %q policy.", v1.DNSClusterFirst, v1.DNSDefault)
            c.recorder.Eventf(c.nodeRef, v1.EventTypeWarning, "MissingClusterDNS", nodeErrorMsg)
            c.recorder.Eventf(pod, v1.EventTypeWarning, "MissingClusterDNS", "pod: %q. %s", format.Pod(pod), nodeErrorMsg)
            // Fallback to DNSDefault.
            fallthrough
      case podDNSHost:
            // When the kubelet --resolv-conf flag is set to the empty string, use
            // DNS settings that override the docker default (which is to use
            // /etc/resolv.conf) and effectively disable DNS lookups. According to
            // the bind documentation, the behavior of the DNS client library when
            // "nameservers" are not specified is to "use the nameserver on the
            // local machine". A nameserver setting of localhost is equivalent to
            // this documented behavior.
            if c.ResolverConfig == "" {
                  for _, nodeIP := range c.nodeIPs {
                        if utilnet.IsIPv6(nodeIP) {
                              dnsConfig.Servers = append(dnsConfig.Servers, "::1")
                        } else {
                              dnsConfig.Servers = append(dnsConfig.Servers, "127.0.0.1")
                        }
                  }
                  if len(dnsConfig.Servers) == 0 {
                        dnsConfig.Servers = append(dnsConfig.Servers, "127.0.0.1")
                  }
                  dnsConfig.Searches = []string{"."}
            }
      }

      if pod.Spec.DNSConfig != nil {
            dnsConfig = appendDNSConfig(dnsConfig, pod.Spec.DNSConfig)
      }
      return c.formDNSConfigFitsLimits(dnsConfig, pod), nil
}


```

##### The kubelet actively calls the CRI `Status` interface via gRPC to detect whether there is a NetworkReady state.

```go
kubelet/kubelet.go:2743

// updateRuntimeUp calls the container runtime status callback, initializing
// the runtime dependent modules when the container runtime first comes up,
// and returns an error if the status check fails.  If the status check is OK,
// update the container runtime uptime in the kubelet runtimeState.
func (kl *Kubelet) updateRuntimeUp() {
      kl.updateRuntimeMux.Lock()
      defer kl.updateRuntimeMux.Unlock()
      ctx := context.Background()

      s, err := kl.containerRuntime.Status(ctx)
      if err != nil {
            klog.ErrorS(err, "Container runtime sanity check failed")
            return
      }
      if s == nil {
            klog.ErrorS(nil, "Container runtime status is nil")
            return
      }
      // Periodically log the whole runtime status for debugging.
      klog.V(4).InfoS("Container runtime status", "status", s)
      klogErrorS := klog.ErrorS
      if !kl.containerRuntimeReadyExpected {
            klogErrorS = klog.V(4).ErrorS
      }
      networkReady := s.GetRuntimeCondition(kubecontainer.NetworkReady)

const (
      // RuntimeReady means the runtime is up and ready to accept basic containers.
      RuntimeReady RuntimeConditionType = "RuntimeReady"
      // NetworkReady means the runtime network is up and ready to accept containers which require network.
      NetworkReady RuntimeConditionType = "NetworkReady"
)
```
</details>

### Summary of the DNS logic in EdgeCore

1. **Kubelet Configuration Limitations**:
    - Kubelet does not provide runtime configuration updates for `ClusterDNS` or `ResolverConfig`. These parameters are set during initialization.
    - Since `edged` directly starts Kubelet without generating a configuration file, modifying these settings requires restarting Kubelet.
2. **Kubeadm**:
    - Unlike `kubeadm`, which sets `ClusterDNS` by default (`10.96.0.10`), `edgecore`'s default `ResolverConfig` results in Kubelet using the host's DNS.

```sh
> sudo kubeadm init
> cat /var/lib/kubelet/config.yaml | grep -C 2 clusterDNS                         
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
```

### Part 2: Trial: Automatic CNI Status Check Integration
<details>
<summary>detail</summary>
##### **Logic Overview**

The main idea is to check whether the `NetworkReady` condition is set, similar to the way `kubelet` checks this status during the pod synchronization process. The key implementation involves using the `Container Runtime Interface (CRI)` to call the `Status` API and verify the presence of the `NetworkReady` indicator.

##### **Check code**

- In `kubelet.go`, the logic for verifying the `NetworkReady` condition is shown below:

kubelet.go:2763

```go
      // Periodically log the whole runtime status for debugging.
      klog.V(4).InfoS("Container runtime status", "status", s)
      klogErrorS := klog.ErrorS
      if !kl.containerRuntimeReadyExpected {
            klogErrorS = klog.V(4).ErrorS
      }
      networkReady := s.GetRuntimeCondition(kubecontainer.NetworkReady)
      if networkReady == nil || !networkReady.Status {
            klogErrorS(nil, "Container runtime network not ready", "networkReady", networkReady)
            kl.runtimeState.setNetworkState(fmt.Errorf("container runtime network not ready: %v", networkReady))
      } else {
            // Set nil if the container runtime network is ready.
            kl.runtimeState.setNetworkState(nil)
      }

```


- `edged` acts as a simplified wrapper around `kubelet`. However, for `kubelet` to handle runtime services properly, it must be fully initialized via the `PreInitRuntimeService` function.

- The relevant `kubelet.go` function is as follows:

```go
// PreInitRuntimeService will init runtime service before RunKubelet.
func PreInitRuntimeService(kubeCfg *kubeletconfiginternal.KubeletConfiguration, kubeDeps *Dependencies) error {
      remoteImageEndpoint := kubeCfg.ImageServiceEndpoint
      if remoteImageEndpoint == "" && kubeCfg.ContainerRuntimeEndpoint != "" {
            remoteImageEndpoint = kubeCfg.ContainerRuntimeEndpoint
      }
      var err error
      if kubeDeps.RemoteRuntimeService, err = remote.NewRemoteRuntimeService(kubeCfg.ContainerRuntimeEndpoint, kubeCfg.RuntimeRequestTimeout.Duration, kubeDeps.TracerProvider); err != nil {
            return err
      }
      if kubeDeps.RemoteImageService, err = remote.NewRemoteImageService(remoteImageEndpoint, kubeCfg.RuntimeRequestTimeout.Duration, kubeDeps.TracerProvider); err != nil {
            return err
      }

      kubeDeps.useLegacyCadvisorStats = cadvisor.UsingLegacyCadvisorStats(kubeCfg.ContainerRuntimeEndpoint)

      return nil
}
```

- Adding logic in `MakeKubeClientBridge` is not feasible because this function is only invoked during the `newEdged` process. The `newEdged` function merely creates a configuration struct instance and doesn't actually start `kubelet`.

- We need to initialize `RemoteRuntimeService` in order to use.

##### **Issue with above trial**

- `kubelet` startup is tightly coupled with the availability of the CNI (Container Network Interface).

- if the CNI configuration files under `/etc/cni/net.d/` are deleted on an edge node, `kubelet` fails to start, logging the following error:
```
`node1 edgecore[10445]: E1203 15:33:59.549983 10445 kubelet.go:2765] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"`
```
</details>

####  **Summary**  

 > Currently, when using the cri runtime, you need to install the cni plugin and configure the cni config before executing keadm join. You can follow the steps below as a reference:
[ref](https://kubeedge.io/docs/faq/setup#cni-plugin-not-initializedcni-config-uninitialized)
 
  -  The file `10-containerd-net.conflist` is located in `/etc/cni/net.d`. At this point, if you check the network status using `kl.runtimeService.GetStatus()`, it will always return the `NetWorkReady` status. so just using status `NetWorkReady` to judge if there is another CNI plugin(e.g Cilium/flannel) installed or not isn't enough.
  
```sh
sudo ls /etc/cni/net.d/
10-containerd-net.conflist

cat /etc/cni/net.d/10-containerd-net.conflist 
{
  "cniVersion": "1.0.0",
  "name": "containerd-net",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cni0",
      "isGateway": true,
      "ipMasq": true,
      "promiscMode": true,
      "ipam": {
        "type": "host-local",
        "ranges": [
          [{
            "subnet": "10.88.0.0/16"
          }],
          [{
            "subnet": "2001:db8:4860::/64"
          }]
        ],
        "routes": [
          { "dst": "0.0.0.0/0" },
          { "dst": "::/0" }
        ]
      }
    },
    {
      "type": "portmap",
      "capabilities": {"portMappings": true},
      "externalSetMarkChain": "KUBE-MARK-MASQ"
    }
  ]
}
```

### Conclusion

- Enhancing keadm to support DNS configuration aligns with Kubernetes best practices.

Does anyone have any other ideas?

**Comment by fujitatomoya** [comment]
@XmchxUp thanks for posting the detailed information, it was too early to jump on the dynamic solution, but it looks pretty hard to do so. and we might as well keep the consistent behavior with k8s.

IMO, there are a few ways to achieve what we want here,

- we should avoid adding the extra options to `keadm`? i think that is the original intention why https://github.com/kubeedge/kubeedge/pull/5946 introduced and taken. if the user specific configuration needs to be applied, we can use this hook on post-init, to apply `--cluster-dns` information.
- Can `KUBELET_EXTRA_ARGS` based approach used with edgecore? this is also useful for the user to specify the static configuration applied to edgecore (kubelet components) during initialization? I am not sure if this is supported with edgecore either.

any thouoghts?

**Comment by XmchxUp** [comment]
@fujitatomoya In the latest version of keadm, the set parameter is supported and can be used as shown below. 
` sudo keadm join --set modules.edged.tailoredKubeletConfig.clusterDNS={10.96.0.10}`

**Comment by fujitatomoya** [comment]
According to @XmchxUp description and suggestion, after all we can just use `keadm join --set modules.edged.tailoredKubeletConfig.clusterDNS={10.96.0.10}` for edge nodes based on the requirements for the pods running on edgecore. i will go ahead to close this one.
