### ISSUE TITLE
边缘端的 deploy 类型的 pod 里面无法访问 其他主机的ip

### ISSUE THREAD

**Issue by thinkeng** [kubeedge/kubeedge#6035]
边缘端的 deploy 类型的 pod 里面无法访问 其他主机的ip，例如：MySQL 服务 191.168.1.123: 3306 ,边缘节点中 pod 中无法连接

**Comment by wbc6080** [comment]
Communication between edge application pods requires edgemesh. https://github.com/kubeedge/edgemesh

**Comment by thinkeng** [comment]
> Communication between edge application pods requires edgemesh. https://github.com/kubeedge/edgemesh

通过svc 访问pod 没有问题是通的，集群外的服务，比如另一台单独部署 MySQL  （MySQL 没有部署到 到  k8s 集群中）服务，然后再pod 中 链接用ip 加端口链接MySQL 服务，网络不通

**Comment by bimoQi** [comment]
> > Communication between edge application pods requires edgemesh. https://github.com/kubeedge/edgemesh
> 
> 通过svc 访问pod 没有问题是通的，集群外的服务，比如另一台单独部署 MySQL （MySQL 没有部署到 到 k8s 集群中）服务，然后再pod 中 用ip 加端口连接 MySQL 服务，网络不通

请问下您是怎么解决的 我现在遇到这个问题了， 排查不出来原因
