### ISSUE TITLE
Make release via script

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#613]
**What would you like to be added**:

Make release via script in Makefile, e.g. make quick-release.

**Why is this needed**:

**Comment by m1093782566** [comment]
cc @sids-b @rohitsardesai83

**Comment by sids-b** [comment]
+1 to @m1093782566 , This is very important. For 1st version we can target generation of the binaries, run all the integration and e2e test cases on the binaries, create release tar's and their checksum's. This tar's and checksum's can then be manually uploaded by one of the Maintainers for now.

**Comment by m1093782566** [comment]
We also need to reach agreement on what will be included in the release package.

**Comment by sids-b** [comment]
@m1093782566 , yess.... currently we have 3 tars in release asset and their respective checksum's.
1) kubeedge amd64
2) kubeedge arm
3) installer amd64

We may need to add 2more in the future releases which are
4) EdgeSite amd64
5) EdgeSite arm

Need to discuss on this more.

**Comment by rohitsardesai83** [comment]
can we take this up in the next community meeting ?

**Comment by m1093782566** [comment]
> can we take this up in the next community meeting ?

+1
