### ISSUE TITLE
Request Existing Organization Members to enable two-factor authentication

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#627]
As per the latest KubeEdge Community Membership document and to keep KubeEdge github organization secure, one of the requirement for being a member is to enable two-factor authentication. The organization settings currently don't enforce this but we will soon be enforcing to meet the membership guidelines. So I request the existing members to enable two-factor authentication for their github account and respond here. Below is the list of members who have not enabled two-factor authentication

- [x] @chendave 

- [x] @CindyXing 

- [x] @dingyin 

- [x] @kadisi 

- [ ] @qizha 

- [x] @rohitsardesai83 

- [x] @shouhong 

- [x] @skdwriting

**Comment by kadisi** [comment]
done

**Comment by chendave** [comment]
done too

**Comment by rohitsardesai83** [comment]
done

**Comment by kevin-wangzefeng** [comment]
removing assignees that have turned on 2FA.
/unassign @kadisi @chendave

**Comment by shouhong** [comment]
done

**Comment by skdwriting** [comment]
done

**Comment by sids-b** [comment]
ping @CindyXing @qizha @dingyin

**Comment by sids-b** [comment]
@CindyXing and @dingyin have also enabled 2FA

/unassign @CindyXing @dingyin

**Comment by sids-b** [comment]
Thanks @qizha for enabling 2FA
