### ISSUE TITLE
Enahance the Performance framework for Benchmark the Resource Consumption SLO's

### ISSUE THREAD

**Issue by pavan187** [kubeedge/kubeedge#630]
**What would you like to be added**:
Enhance the performance framework for Benchmarking Resource consumtion SLO's

**Why is this needed**:
This is helps in measuring the resource consumption(Memory and CPU) of a KubeEdge Node when user deploy various no.of application Pod's.Which will help in validating the KubeEdge node performance based on application load.

**Comment by rohitsardesai83** [comment]
@pavan187 , are we targeting this for 1.0 ?
