### ISSUE TITLE
Create OWNERS file for proper review and approval process

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#638]
**What would you like to be added**:
We should have OWNERS file with reviewers and approvers entry for proper review of a PR

**Why is this needed**:
A PR needs to be reviewed buy members who have worked or have knowledge in the the are where changes will be made. This will help in proper review of all PRs and will also distribute work load.

Currently we may not add OWNERS file in all packages. We can have them at a higher level based on features. For eg: deviceController may have 1 OWNERS file, edged may have 1 OWNERS file,etc

Thoughts ??

**Comment by sids-b** [comment]
cc @kevin-wangzefeng @m1093782566 @rohitsardesai83 @shouhong @kadisi @chendave @subpathdev

**Comment by m1093782566** [comment]
+1

**Comment by kadisi** [comment]
+1

**Comment by shouhong** [comment]
+1

**Comment by chendave** [comment]
Good idea, +1.

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by sids-b** [comment]
looks like we may have consensus. First let us start creating OWNERS file one by one for packages. Later review and approve permissions can be enforced by the bot.

**Comment by sids-b** [comment]
Closing this issue now. We have owners file in place for most of the modules
