### ISSUE TITLE
how to send msg sync from cloud module to edge module?

### ISSUE THREAD

**Issue by dsxing** [kubeedge/kubeedge#639]
**how to send msg sync from cloud module to edge module?**:

**Why is this needed**:

**Comment by sids-b** [comment]
@dsxing , can you please give little more details about what you would like to know ?

**Comment by dsxing** [comment]
> @dsxing , can you please give little more details about what you would like to know ?

I want to Send messages synchronously from the cloud to the edge，for example：I want to send messages from the 'devicecontroller' module to the 'servicebus'  module， I use the 'send' method in the 'devicecontroller' module , and then the 'servicebus'  module will receive the message asynchronously by 'Beehive framework' , I want to know how can I make this process synchronous.
i want to  get the response from 'servicebus' module.

Fake code：
     devicecontroller ：
                remsg , err := dc.messageLayer.SendSync("servicebus",  *msg,  30*time.Second)
     servicebus
                if msg, ok := ac.context.Receive("servicebus"); ok == nil{
			//to do something 
                        resp := msg.NewRespByMessage(&msg, "response msg: OK")
			ac.context.SendResp(*resp)
                }

**Comment by sids-b** [comment]
@dsxing , apologies for delayed response. I think the code which you have written is correct. We have similar implementations for sync message in metamanager as well;
https://github.com/kubeedge/kubeedge/blob/767620a85d8d66a4319e6dae3c00101276a40bd9/edge/pkg/metamanager/msg_processor.go#L415-L457

**Comment by sids-b** [comment]
Closing this issue. Please reach out to us via slack or reopen the issue for further discussion :)
