### ISSUE TITLE
race condition @ DTContext.Lock / DTContext.Unlock

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#640]
**What happened**:
We have a potential race @ locking / unlocking the device mutex. (https://github.com/kubeedge/kubeedge/blob/0ddc4b3f7752fb527c73bec4d5d2adbe5f3635f2/edge/pkg/devicetwin/dtcontext/dtcontext.go#L107-L128)

EXAMPLE CASE:
- 2 messages from the same device
- start handling first message
  - run dtc.Lock('xyz')
      - success on dtc.Mutex.Lock()
      - success on deviceMutex.Lock()
      - success on dtc.Mutex.Unlock()
- start handling second message
   - run dtc.Lock('xyz')
      - success on dtc.Mutex.Lock()
      - bounded waiting on deviceMutex.Lock() # beause the first message has this mutex
- continue handling first message
  - run dtc.Unlock('xyz')
     - bounded waiting on dtc.Mutex.Unlock() # because the second message has the mutex

**What you expected to happen**:
no race condition

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
not relevant

**Comment by m1093782566** [comment]
Oh, nice catch! @subpathdev

**Comment by subpathdev** [comment]
Do we really need dtc.Mutex.Lock() / dtc.Mutex.Unlock() in this context?

**Comment by sids-b** [comment]
Thats a nice catch @subpathdev . But the lock function is called only once at the beginning of the deviceTwin module in a synchronous for loop.
https://github.com/kubeedge/kubeedge/blob/be4d5e34012d41246919296ee378c1834b9ec097/edge/pkg/devicetwin/dtcontroller.go#L185-L204

The SyncDeviceFromSqlite then calls the lock function. 

The main reason for dtc.Mutex.Lock is to guard against race condition in case of dealMembershipDetail from cloud. Cloud sends an array of added, removed devices. So dealMembershipDetailfunction calls these function to get a lock on full context.
https://github.com/kubeedge/kubeedge/blob/be4d5e34012d41246919296ee378c1834b9ec097/edge/pkg/devicetwin/dtcontext/dtcontext.go#L131-L138

So we need dtc.Mutex.Lock()

**Comment by sids-b** [comment]
But yess, the lock function can cause a deadlock as it can be called for same devices for 2 different messages as explained by you. But I think removing dtc.Mutex.Lock won't be a correct solution.

**Comment by sids-b** [comment]
I was thinking a solution could be removing dtc.Mutex.Lock() only from the Unlock function. Would it be a correct solution though ?
cc @m1093782566 @rohitsardesai83 @subpathdev

**Comment by subpathdev** [comment]
The actual state doesn't provide the described functionality in all states. Here is an example of what can go wrong:

we receive a message of a device:
-> lock dtc.Mutex
-> lock device mutex
-> unlock dtc.Mutex

now running dealMembershipDetail
-> lock dtc.Mutex

at this point we can modify the device twin without locking the dtc.Mutex.
( I hate race conditions )

I think we should lock the device in the functions and not the list of all devices. (critical sections should be as small as possible)

**Comment by sids-b** [comment]
@subpathdev , I think there is one more step here

now running dealMembershipDetail
-> lock dtc.Mutex
-> lock deviceMutex

We may get stuck in a deadlock here as device message has not yet unlocked dtc.Mutex is in lock state.

How about make dtc.Mutex a RWMutex. We can use readlock in Lock and Unlock functions and then not have deadlock. Thoughts ?

**Comment by subpathdev** [comment]
Yes I think that is the right way. Thank you @sids-b .

**Comment by subpathdev** [comment]
I would use the lock dtc.Mutex in the dtc.Lock function and unlock it in the dtc.Unlock() function. (like the commit above) Thoughts?
