### ISSUE TITLE
E2E Testing: Even though actually the tests have failed the report shows it has passed

### ISSUE THREAD

**Issue by samy2019** [kubeedge/kubeedge#657]
**What happened**:
Executed e2e tests and it due to some reason all the tests failed. but the report still showed all the test passed. Below is the output.

Ran 7 of 0 Specs in 66.631 seconds
FAIL! -- 0 Passed | 7 Failed | 0 Pending | 0 Skipped
Running Suite: kubeedge App Deploymet Suite
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 0 Skipped
Integration Test Final Summary Report
===============================================
Total Number of Test cases = 7
Number of Test cases PASSED = 7
Number of Test cases FAILED = 0
==================Result Summary=======================
Integration suite successfully passed all the tests !!

**What you expected to happen**:
It should show all tests as failed.

**How to reproduce it (as minimally and precisely as possible)**:
Pre-req: Make API-server unreachable to cloud contoller.
1. As non root, execute "make e2e_test"
2. The node addition and consecutively all the tests would fail.

**Anything else we need to know?**:

**Environment**:
- KubeEdge version: master
- Hardware configuration: NA
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): NA
- Others: NA

**Comment by rohitsardesai83** [comment]
@pavan187 , can you please check this issue ?

**Comment by sids-b** [comment]
Closing this issue. Didn't observe similar behaviour
