### ISSUE TITLE
can not build cloud in ubuntu16.04

### ISSUE THREAD

**Issue by stormspiritzzz** [kubeedge/kubeedge#660]
**What happened**:fail to build cloud

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:Release 0.3
- Hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu16.04
- Kernel (e.g. `uname -a`):Linux master 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Others:
root@master:~/work/src/github.com/kubeedge/kubeedge#  make all WHAT=cloud
cd cloud && make
make[1]: Entering directory '/root/work/src/github.com/kubeedge/kubeedge/cloud'
go build cmd/edgecontroller.go
../vendor/github.com/ServiceComb/paas-lager/rotate/logrotate.go:19:2: cannot find package "archive/zip" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/archive/zip (vendor tree)
	/root/go/src/archive/zip (from $GOROOT)
	/root/work/src/archive/zip (from $GOPATH)
../vendor/github.com/gorilla/websocket/conn.go:8:2: cannot find package "bufio" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/bufio (vendor tree)
	/root/go/src/bufio (from $GOROOT)
	/root/work/src/bufio (from $GOPATH)
../vendor/github.com/fsnotify/fsnotify/fsnotify.go:11:2: cannot find package "bytes" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/bytes (vendor tree)
	/root/go/src/bytes (from $GOROOT)
	/root/work/src/bytes (from $GOPATH)
../vendor/github.com/gorilla/websocket/compression.go:8:2: cannot find package "compress/flate" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/compress/flate (vendor tree)
	/root/go/src/compress/flate (from $GOROOT)
	/root/work/src/compress/flate (from $GOPATH)
../vendor/golang.org/x/net/http2/transport.go:12:2: cannot find package "compress/gzip" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/compress/gzip (vendor tree)
	/root/go/src/compress/gzip (from $GOROOT)
	/root/work/src/compress/gzip (from $GOPATH)
../vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_compression.go:6:2: cannot find package "compress/zlib" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/compress/zlib (vendor tree)
	/root/go/src/compress/zlib (from $GOROOT)
	/root/work/src/compress/zlib (from $GOPATH)
../vendor/k8s.io/client-go/tools/cache/heap.go:22:2: cannot find package "container/heap" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/container/heap (vendor tree)
	/root/go/src/container/heap (from $GOROOT)
	/root/work/src/container/heap (from $GOPATH)
../vendor/github.com/hashicorp/golang-lru/simplelru/lru.go:4:2: cannot find package "container/list" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/container/list (vendor tree)
	/root/go/src/container/list (from $GOROOT)
	/root/work/src/container/list (from $GOPATH)
../vendor/github.com/gorilla/websocket/client.go:9:2: cannot find package "context" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/context (vendor tree)
	/root/go/src/context (from $GOROOT)
	/root/work/src/context (from $GOPATH)
../vendor/github.com/lucas-clemente/quic-go/mint_utils.go:4:2: cannot find package "crypto" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto (vendor tree)
	/root/go/src/crypto (from $GOROOT)
	/root/work/src/crypto (from $GOPATH)
../vendor/github.com/bifurcation/mint/cookie-protector.go:4:2: cannot find package "crypto/aes" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/aes (vendor tree)
	/root/go/src/crypto/aes (from $GOROOT)
	/root/work/src/crypto/aes (from $GOPATH)
../vendor/github.com/bifurcation/mint/cookie-protector.go:5:2: cannot find package "crypto/cipher" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/cipher (vendor tree)
	/root/go/src/crypto/cipher (from $GOROOT)
	/root/work/src/crypto/cipher (from $GOPATH)
../vendor/github.com/bifurcation/mint/crypto.go:8:2: cannot find package "crypto/ecdsa" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/ecdsa (vendor tree)
	/root/go/src/crypto/ecdsa (from $GOROOT)
	/root/work/src/crypto/ecdsa (from $GOPATH)
../vendor/github.com/bifurcation/mint/crypto.go:9:2: cannot find package "crypto/elliptic" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/elliptic (vendor tree)
	/root/go/src/crypto/elliptic (from $GOROOT)
	/root/work/src/crypto/elliptic (from $GOPATH)
../vendor/github.com/bifurcation/mint/crypto.go:10:2: cannot find package "crypto/hmac" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/hmac (vendor tree)
	/root/go/src/crypto/hmac (from $GOROOT)
	/root/work/src/crypto/hmac (from $GOPATH)
../vendor/github.com/satori/go.uuid/generator.go:25:2: cannot find package "crypto/md5" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/md5 (vendor tree)
	/root/go/src/crypto/md5 (from $GOROOT)
	/root/work/src/crypto/md5 (from $GOPATH)
../vendor/github.com/satori/go.uuid/generator.go:26:2: cannot find package "crypto/rand" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/rand (vendor tree)
	/root/go/src/crypto/rand (from $GOROOT)
	/root/work/src/crypto/rand (from $GOPATH)
../vendor/github.com/bifurcation/mint/crypto.go:12:2: cannot find package "crypto/rsa" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/rsa (vendor tree)
	/root/go/src/crypto/rsa (from $GOROOT)
	/root/work/src/crypto/rsa (from $GOPATH)
../vendor/github.com/satori/go.uuid/generator.go:27:2: cannot find package "crypto/sha1" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/sha1 (vendor tree)
	/root/go/src/crypto/sha1 (from $GOROOT)
	/root/work/src/crypto/sha1 (from $GOPATH)
../vendor/github.com/bifurcation/mint/cookie-protector.go:7:2: cannot find package "crypto/sha256" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/sha256 (vendor tree)
	/root/go/src/crypto/sha256 (from $GOROOT)
	/root/work/src/crypto/sha256 (from $GOPATH)
../vendor/github.com/bifurcation/mint/crypto.go:25:2: cannot find package "crypto/sha512" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/sha512 (vendor tree)
	/root/go/src/crypto/sha512 (from $GOROOT)
	/root/work/src/crypto/sha512 (from $GOPATH)
../vendor/github.com/lucas-clemente/aes12/aes_gcm.go:9:8: cannot find package "crypto/subtle" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/subtle (vendor tree)
	/root/go/src/crypto/subtle (from $GOROOT)
	/root/work/src/crypto/subtle (from $GOPATH)
../vendor/github.com/gorilla/websocket/client.go:10:2: cannot find package "crypto/tls" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/tls (vendor tree)
	/root/go/src/crypto/tls (from $GOROOT)
	/root/work/src/crypto/tls (from $GOPATH)
../vendor/github.com/kubeedge/viaduct/pkg/conn/conn.go:4:2: cannot find package "crypto/x509" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/x509 (vendor tree)
	/root/go/src/crypto/x509 (from $GOROOT)
	/root/work/src/crypto/x509 (from $GOPATH)
../vendor/github.com/bifurcation/mint/crypto.go:14:2: cannot find package "crypto/x509/pkix" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/crypto/x509/pkix (vendor tree)
	/root/go/src/crypto/x509/pkix (from $GOROOT)
	/root/work/src/crypto/x509/pkix (from $GOPATH)
../vendor/github.com/satori/go.uuid/sql.go:25:2: cannot find package "database/sql/driver" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/database/sql/driver (vendor tree)
	/root/go/src/database/sql/driver (from $GOROOT)
	/root/work/src/database/sql/driver (from $GOPATH)
../vendor/gopkg.in/yaml.v2/decode.go:4:2: cannot find package "encoding" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/encoding (vendor tree)
	/root/go/src/encoding (from $GOROOT)
	/root/work/src/encoding (from $GOPATH)
../vendor/github.com/bifurcation/mint/crypto.go:15:2: cannot find package "encoding/asn1" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/encoding/asn1 (vendor tree)
	/root/go/src/encoding/asn1 (from $GOROOT)
	/root/work/src/encoding/asn1 (from $GOPATH)
../vendor/gopkg.in/yaml.v2/decode.go:5:2: cannot find package "encoding/base64" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/encoding/base64 (vendor tree)
	/root/go/src/encoding/base64 (from $GOROOT)
	/root/work/src/encoding/base64 (from $GOPATH)
../vendor/github.com/satori/go.uuid/generator.go:28:2: cannot find package "encoding/binary" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/encoding/binary (vendor tree)
	/root/go/src/encoding/binary (from $GOROOT)
	/root/work/src/encoding/binary (from $GOPATH)
../vendor/github.com/spf13/pflag/string_slice.go:5:2: cannot find package "encoding/csv" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/encoding/csv (vendor tree)
	/root/go/src/encoding/csv (from $GOROOT)
	/root/work/src/encoding/csv (from $GOPATH)
../vendor/github.com/satori/go.uuid/codec.go:26:2: cannot find package "encoding/hex" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/encoding/hex (vendor tree)
	/root/go/src/encoding/hex (from $GOROOT)
	/root/work/src/encoding/hex (from $GOPATH)
../vendor/github.com/spf13/cast/caste.go:9:2: cannot find package "encoding/json" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/encoding/json (vendor tree)
	/root/go/src/encoding/json (from $GOROOT)
	/root/work/src/encoding/json (from $GOPATH)
../vendor/k8s.io/client-go/util/cert/cert.go:27:2: cannot find package "encoding/pem" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/encoding/pem (vendor tree)
	/root/go/src/encoding/pem (from $GOROOT)
	/root/work/src/encoding/pem (from $GOPATH)
../vendor/github.com/ServiceComb/go-archaius/configurationfactory.go:25:2: cannot find package "errors" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/errors (vendor tree)
	/root/go/src/errors (from $GOROOT)
	/root/work/src/errors (from $GOPATH)
../vendor/github.com/spf13/pflag/flag.go:104:2: cannot find package "flag" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/flag (vendor tree)
	/root/go/src/flag (from $GOROOT)
	/root/work/src/flag (from $GOPATH)
../vendor/github.com/kubeedge/beehive/pkg/common/config/config.go:4:2: cannot find package "fmt" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/fmt (vendor tree)
	/root/go/src/fmt (from $GOROOT)
	/root/work/src/fmt (from $GOPATH)
../vendor/k8s.io/apimachinery/pkg/runtime/swagger_doc_generator.go:22:2: cannot find package "go/ast" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/go/ast (vendor tree)
	/root/go/src/go/ast (from $GOROOT)
	/root/work/src/go/ast (from $GOPATH)
../vendor/k8s.io/apimachinery/pkg/runtime/swagger_doc_generator.go:23:2: cannot find package "go/doc" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/go/doc (vendor tree)
	/root/go/src/go/doc (from $GOROOT)
	/root/work/src/go/doc (from $GOPATH)
../vendor/k8s.io/apimachinery/pkg/runtime/swagger_doc_generator.go:24:2: cannot find package "go/parser" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/go/parser (vendor tree)
	/root/go/src/go/parser (from $GOROOT)
	/root/work/src/go/parser (from $GOPATH)
../vendor/k8s.io/apimachinery/pkg/runtime/swagger_doc_generator.go:25:2: cannot find package "go/token" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/go/token (vendor tree)
	/root/go/src/go/token (from $GOROOT)
	/root/work/src/go/token (from $GOPATH)
../vendor/github.com/satori/go.uuid/generator.go:29:2: cannot find package "hash" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/hash (vendor tree)
	/root/go/src/hash (from $GOROOT)
	/root/work/src/hash (from $GOPATH)
../vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_cache.go:5:2: cannot find package "hash/fnv" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/hash/fnv (vendor tree)
	/root/go/src/hash/fnv (from $GOROOT)
	/root/work/src/hash/fnv (from $GOPATH)
../vendor/github.com/spf13/cast/caste.go:12:2: cannot find package "html/template" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/html/template (vendor tree)
	/root/go/src/html/template (from $GOROOT)
	/root/work/src/html/template (from $GOPATH)
../vendor/github.com/fsnotify/fsnotify/inotify.go:12:2: cannot find package "io" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/io (vendor tree)
	/root/go/src/io (from $GOROOT)
	/root/work/src/io (from $GOPATH)
../vendor/github.com/go-chassis/go-archaius/sources/file-source/yamlconfigurationsource.go:23:2: cannot find package "io/ioutil" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/io/ioutil (vendor tree)
	/root/go/src/io/ioutil (from $GOROOT)
	/root/work/src/io/ioutil (from $GOPATH)
../vendor/github.com/go-mesh/openlogging/log.go:4:2: cannot find package "log" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/log (vendor tree)
	/root/go/src/log (from $GOROOT)
	/root/work/src/log (from $GOPATH)
../vendor/gopkg.in/yaml.v2/decode.go:8:2: cannot find package "math" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/math (vendor tree)
	/root/go/src/math (from $GOROOT)
	/root/work/src/math (from $GOPATH)
../vendor/github.com/bifurcation/mint/crypto.go:17:2: cannot find package "math/big" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/math/big (vendor tree)
	/root/go/src/math/big (from $GOROOT)
	/root/work/src/math/big (from $GOPATH)
../vendor/github.com/gorilla/websocket/conn.go:13:2: cannot find package "math/rand" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/math/rand (vendor tree)
	/root/go/src/math/rand (from $GOROOT)
	/root/work/src/math/rand (from $GOPATH)
../vendor/k8s.io/client-go/rest/client.go:21:2: cannot find package "mime" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/mime (vendor tree)
	/root/go/src/mime (from $GOROOT)
	/root/work/src/mime (from $GOPATH)
../vendor/github.com/satori/go.uuid/generator.go:30:2: cannot find package "net" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/net (vendor tree)
	/root/go/src/net (from $GOROOT)
	/root/work/src/net (from $GOPATH)
../vendor/github.com/gorilla/context/context.go:8:2: cannot find package "net/http" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/net/http (vendor tree)
	/root/go/src/net/http (from $GOROOT)
	/root/work/src/net/http (from $GOPATH)
../vendor/github.com/gorilla/websocket/client.go:16:2: cannot find package "net/http/httptrace" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/net/http/httptrace (vendor tree)
	/root/go/src/net/http/httptrace (from $GOROOT)
	/root/work/src/net/http/httptrace (from $GOPATH)
../vendor/golang.org/x/net/http/httpguts/guts.go:13:2: cannot find package "net/textproto" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/net/textproto (vendor tree)
	/root/go/src/net/textproto (from $GOROOT)
	/root/work/src/net/textproto (from $GOPATH)
../vendor/github.com/gorilla/mux/regexp.go:11:2: cannot find package "net/url" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/net/url (vendor tree)
	/root/go/src/net/url (from $GOROOT)
	/root/work/src/net/url (from $GOPATH)
../vendor/github.com/fsnotify/fsnotify/inotify.go:13:2: cannot find package "os" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/os (vendor tree)
	/root/go/src/os (from $GOROOT)
	/root/work/src/os (from $GOPATH)
../vendor/github.com/googleapis/gnostic/compiler/extension-handler.go:20:2: cannot find package "os/exec" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/os/exec (vendor tree)
	/root/go/src/os/exec (from $GOROOT)
	/root/work/src/os/exec (from $GOPATH)
../vendor/github.com/kubeedge/beehive/pkg/core/core.go:5:2: cannot find package "os/signal" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/os/signal (vendor tree)
	/root/go/src/os/signal (from $GOROOT)
	/root/work/src/os/signal (from $GOPATH)
../vendor/github.com/golang/glog/glog_file.go:26:2: cannot find package "os/user" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/os/user (vendor tree)
	/root/go/src/os/user (from $GOROOT)
	/root/work/src/os/user (from $GOPATH)
../vendor/github.com/kubeedge/beehive/pkg/common/config/config.go:6:2: cannot find package "path" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/path (vendor tree)
	/root/go/src/path (from $GOROOT)
	/root/work/src/path (from $GOPATH)
../vendor/github.com/fsnotify/fsnotify/inotify.go:14:2: cannot find package "path/filepath" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/path/filepath (vendor tree)
	/root/go/src/path/filepath (from $GOROOT)
	/root/work/src/path/filepath (from $GOPATH)
../vendor/github.com/spf13/cast/caste.go:13:2: cannot find package "reflect" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/reflect (vendor tree)
	/root/go/src/reflect (from $GOROOT)
	/root/work/src/reflect (from $GOPATH)
../vendor/gopkg.in/yaml.v2/encode.go:8:2: cannot find package "regexp" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/regexp (vendor tree)
	/root/go/src/regexp (from $GOROOT)
	/root/work/src/regexp (from $GOPATH)
package main
	imports runtime: cannot find package "runtime" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/runtime (vendor tree)
	/root/go/src/runtime (from $GOROOT)
	/root/work/src/runtime (from $GOPATH)
../vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go:23:2: cannot find package "runtime/debug" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/runtime/debug (vendor tree)
	/root/go/src/runtime/debug (from $GOROOT)
	/root/work/src/runtime/debug (from $GOPATH)
../vendor/golang.org/x/sys/unix/syscall_unix.go:12:2: cannot find package "sort" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/sort (vendor tree)
	/root/go/src/sort (from $GOROOT)
	/root/work/src/sort (from $GOPATH)
../vendor/github.com/spf13/cast/caste.go:14:2: cannot find package "strconv" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/strconv (vendor tree)
	/root/go/src/strconv (from $GOROOT)
	/root/work/src/strconv (from $GOPATH)
../vendor/github.com/spf13/cast/caste.go:15:2: cannot find package "strings" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/strings (vendor tree)
	/root/go/src/strings (from $GOROOT)
	/root/work/src/strings (from $GOPATH)
../vendor/golang.org/x/sys/unix/syscall_unix.go:13:2: cannot find package "sync" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/sync (vendor tree)
	/root/go/src/sync (from $GOROOT)
	/root/work/src/sync (from $GOPATH)
../vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/logger.go:9:2: cannot find package "sync/atomic" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/sync/atomic (vendor tree)
	/root/go/src/sync/atomic (from $GOROOT)
	/root/work/src/sync/atomic (from $GOPATH)
../vendor/golang.org/x/sys/unix/dirent.go:9:8: cannot find package "syscall" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/syscall (vendor tree)
	/root/go/src/syscall (from $GOROOT)
	/root/work/src/syscall (from $GOPATH)
../vendor/k8s.io/apimachinery/pkg/util/diff/diff.go:26:2: cannot find package "text/tabwriter" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/text/tabwriter (vendor tree)
	/root/go/src/text/tabwriter (from $GOROOT)
	/root/work/src/text/tabwriter (from $GOPATH)
../vendor/github.com/spf13/cast/cast.go:9:8: cannot find package "time" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/time (vendor tree)
	/root/go/src/time (from $GOROOT)
	/root/work/src/time (from $GOPATH)
../vendor/gopkg.in/yaml.v2/sorter.go:5:2: cannot find package "unicode" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/unicode (vendor tree)
	/root/go/src/unicode (from $GOROOT)
	/root/work/src/unicode (from $GOPATH)
../vendor/github.com/json-iterator/go/iter_str.go:5:2: cannot find package "unicode/utf16" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/unicode/utf16 (vendor tree)
	/root/go/src/unicode/utf16 (from $GOROOT)
	/root/work/src/unicode/utf16 (from $GOPATH)
../vendor/gopkg.in/yaml.v2/encode.go:13:2: cannot find package "unicode/utf8" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/unicode/utf8 (vendor tree)
	/root/go/src/unicode/utf8 (from $GOROOT)
	/root/work/src/unicode/utf8 (from $GOPATH)
../vendor/golang.org/x/sys/unix/affinity_linux.go:10:2: cannot find package "unsafe" in any of:
	/root/work/src/github.com/kubeedge/kubeedge/vendor/unsafe (vendor tree)
	/root/go/src/unsafe (from $GOROOT)
	/root/work/src/unsafe (from $GOPATH)
Makefile:5: recipe for target 'edgecontroller' failed
make[1]: *** [edgecontroller] Error 1
make[1]: Leaving directory '/root/work/src/github.com/kubeedge/kubeedge/cloud'
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by subpathdev** [comment]
Which go version do you use?

**Comment by stormspiritzzz** [comment]
> Which go version do you use?

go version go1.6.2 linux/amd64

**Comment by subpathdev** [comment]
you have to use a newer version of go; we are testing with go1.11

**Comment by stormspiritzzz** [comment]
> you have to use a newer version of go; we are testing with go1.11

it works,thank you

**Comment by sids-b** [comment]
Thanks @subpathdev :)
