### ISSUE TITLE
Installing kubeedge manually using release package fails

### ISSUE THREAD

**Issue by vizero1** [kubeedge/kubeedge#661]
**What happened**:
Running ./edgecontroller on my cloud vm fails.
**What you expected to happen**:
That edgecontroller starts and I can afterwards setup my edge vm
**How to reproduce it (as minimally and precisely as possible)**:
Replicating the steps from the documentation for "Setting up Kubeedge using release package".
https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/release_package.md

**Anything else we need to know?**:
Would like to set it up manually using the release packages and afterwards improve the documentation so other people with not so much experience ( e.g. me) will not face the problems. Would like to use that ticket to express the problems I get during my installation process.

**Environment**:
- KubeEdge version: 0.30
- Hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`):

I followed every step from "Setting up Kubeedge using release package". 
I created a k8s cluster(used canico as network add on) with one master node in the google cloud, exposed 8080, generated the certificates and created device model and device CRDs.
After that i start the edgecontroller script and can see following error in the logs:

```

> 2019-06-06 14:30:50.871 +00:00 INFO controller/downstream.go:726 Start downstream controller
> 2019-06-06 14:30:50.873 +00:00 INFO wsserver/server.go:413 Start cloud hub service
> 2019-06-06 14:30:50.881 +00:00 INFO controller/downstream.go:170 start downstream controller
> 2019-06-06 14:30:50.881 +00:00 INFO controller/downstream.go:66 send message successfully, operation: insert, resource: node/instance-1/kube-system/pod/calico-node-fwkfd
> 2019-06-06 14:30:50.881 +00:00 ERROR channelq/channelq.go:103 rChannel for edge node instance-1 is removed
> 2019-06-06 14:30:50.881 +00:00 INFO channelq/channelq.go:89 fail to get dispatch channel for instance-1
> 2019-06-06 14:30:50.882 +00:00 INFO controller/downstream.go:132 there are 0 nodes need to sync secret, operation: ADDED
> 2019-06-06 14:30:50.882 +00:00 INFO controller/downstream.go:132 there are 0 nodes need to sync secret, operation: ADDED
> 2019-06-06 14:30:50.883 +00:00 INFO controller/downstream.go:132 there are 0 nodes need to sync secret, operation: ADDED
> 2019-06-06 14:30:50.883 +00:00 INFO controller/downstream.go:132 there are 0 nodes need to sync secret, operation: ADDED
> 2019-06-06 14:30:50.883 +00:00 INFO controller/downstream.go:132 there are 0 nodes need to sync secret, operation: ADDED
> 2019-06-06 14:30:50.883 +00:00 INFO controller/downstream.go:132 there are 1 nodes need to sync secret, operation: ADDED
> 2019-06-06 14:30:50.883 +00:00 INFO controller/downstream.go:158 send message successfully, operation: update, resource: node/instance-1/kube-system/secret/coredns-token-msf6w
> 2019-06-06 14:30:50.883 +00:00 ERROR channelq/channelq.go:103 rChannel for edge node instance-1 is removed
> 2019-06-06 14:30:50.883 +00:00 INFO channelq/channelq.go:89 fail to get dispatch channel for instance-1
> 2019-06-06 14:30:50.883 +00:00 INFO controller/downstream.go:132 there are 1 nodes need to sync secret, operation: ADDED
> 2019-06-06 14:30:50.883 +00:00 INFO controller/downstream.go:158 send message successfully, operation: update, resource: node/instance-1/kube-system/secret/calico-node-token-fq78l
> 2019-06-06 14:30:50.883 +00:00 INFO controller/downstream.go:132 there are 0 nodes need to sync secret, operation: ADDED
> 2019-06-06 14:30:50.884 +00:00 INFO controller/downstream.go:132 there are 0 nodes need to sync secret, operation: ADDED
> 2019-06-06 14:30:50.884 +00:00 ERROR channelq/channelq.go:103 rChannel for edge node instance-1 is removed
> 2019-06-06 14:30:50.884 +00:00 INFO channelq/channelq.go:89 fail to get dispatch channel for instance-1

```

What exactly is the rChannel and why is it removed for my master node instance-1? Can somebody explain me that? 
Another question is related to the certificates. After generating them in the default directory, do I need to change  in /etc/kubeedge/cloud/conf/controller.yaml the defined path for cloudhub certificates?

My controller configuration is now:

```
controller:
  kube:
    master: http://localhost:8080
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    node_update_frequency: 10
    kubeconfig: ""   #Enter path to kubeconfig file to enable https connection to k8s apiserver
cloudhub:
  address: 0.0.0.0
  port: 10000
  ca: /etc/kubeedge/ca/rootCA.crt
  cert: /etc/kubeedge/certs/edge.crt
  key: /etc/kubeedge/certs/edge.key
  keepalive-interval: 30
  write-timeout: 30
  node-limit: 10
devicecontroller:
  kube:
    master: http://localhost:8080
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    kubeconfig: ""
```

**Comment by sids-b** [comment]
@vizero1 , please take a look at #244 . We have resolved the issue in master branch :)

**Comment by vizero1** [comment]
@sids-b thanks. Could set up kubeedge by compiling the master branch :)
Can find in the logs a lot of time warnings, e.g.
On the edge site logs:
```
2019-06-07 13:46:04.382 +02:00 INFO edgehub/controller.go:198 received msg from cloud-hub:{Header:{ID:639cbae5-4d2a-431c-ade5-68835828ea2f ParentID:ad9bbd0c-49bd-4a10-a9fd-8e08bc0965ed Timestamp:1559907964285 Sync:false} Router:{Source:controller Group:resource Operation:response Resource:default/node/ubuntu-x86} Content:OK}
2019-06-07 13:46:04.382 +02:00 WARN context/context_channel.go:157 bad anonName(ad9bbd0c-49bd-4a10-a9fd-8e08bc0965ed), do nothing
2019-06-07 13:46:05.053 +02:00 INFO pleg/generic.go:47 GenericLifecycle: Relisting
```
On the cloud site logs:
```
2019-06-07 11:46:04.276 +00:00 INFO controller/upstream.go:94 Dispatch message: ad9bbd0c-49bd-4a10-a9fd-8e08bc0965ed
2019-06-07 11:46:04.276 +00:00 WARN controller/upstream.go:98 Parse message: ad9bbd0c-49bd-4a10-a9fd-8e08bc0965ed resource type with error: unknown resource
2019-06-07 11:46:04.276 +00:00 INFO controller/upstream.go:137 dispatch message: ad9bbd0c-49bd-4a10-a9fd-8e08bc0965ed
2019-06-07 11:46:04.276 +00:00 INFO messagelayer/util.go:87 The resource type is nodestatus, 3
```

Why is it showing this warning? I dont have any deployment and beehive module defined for the communication. That is shown between the edge node and master communication.

**Comment by rohitsardesai83** [comment]
@vizero1 , 

What exactly is the rChannel and why is it removed for my master node instance-1? Can somebody explain me that?

every edge node is connected to the cloud node via a dedicated receiver channel i.e rChannel. 
since the master node is not an edge node , you see messages indicating the channel is removed .
This was fixed as part of https://github.com/kubeedge/kubeedge/pull/294

Another question is related to the certificates. After generating them in the default directory, do I need to change in /etc/kubeedge/cloud/conf/controller.yaml the defined path for cloudhub certificates? 

If the certificates are generated in /etc/kubeedge , then the yaml path need not be changed,

**Comment by sids-b** [comment]
ping @vizero1 , was your issue solved ?

**Comment by vizero1** [comment]
@sids-b Yes, thanks to the new release I could install kubeedge.
@rohitsardesai83 Thanks.

**Comment by sids-b** [comment]
Great. Thanks @vizero1
