### ISSUE TITLE
adding type support

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#681]
**What would you like to be added**:
 The type of value of a device should not only by string.

As you can see we are setting the type static to string. ([cloud/pkg/devicecontroller/downstream.go Line 417](https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/devicecontroller/controller/downstream.go#L417) OR [cloud/pkg/devicecontroller/downstream.go Line 648](https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/devicecontroller/controller/downstream.go#L648)) 

**Why is this needed**:
We say, that we are supporting string and int64 ...

**Comment by rohitsardesai83** [comment]
:+1: , let's target this post 1.0 release ?

**Comment by subpathdev** [comment]
@rohitsardesai83 Yes, can you put this in the backlog?

**Comment by subpathdev** [comment]
thanks

**Comment by subpathdev** [comment]
is fixed by pr #712

**Comment by subpathdev** [comment]
The type will be overwritten somewhere => reopening issue

**Comment by subpathdev** [comment]
OK I think this is only a documentation problem. By creating a new device we have to set the value and the type in the desired field and not in the reported field. (The reported field will be ignored)

Also the ValueType which is set by the DeviceModel.yaml, will be ignored.

**Comment by sids-b** [comment]
@subpathdev , does this issue still persists ?

**Comment by subpathdev** [comment]
no -> I am closing this issue
