### ISSUE TITLE
a problem on installing kubeedge in centos

### ISSUE THREAD

**Issue by xiayanshangda** [kubeedge/kubeedge#691]
i install kubeedge in centos,when execute this step
![image](https://user-images.githubusercontent.com/39492112/59351634-70739080-8d51-11e9-9a0a-2fab19c9439c.png)

a error is reported:

[root@lab01 keadm]# kubeedge init
Expected Docker version is not available in OS repo
Expected kubeadm version is not available in OS repo
InstallKubeEdge called
open /etc/kubeedge/certgen.sh: no such file or directory
[root@lab01 keadm]#

how to solve this problem

**Comment by subpathdev** [comment]
to install docker on centos: https://docs.docker.com/install/linux/docker-ce/centos/
to install kubernetes on centos: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by subpathdev** [comment]
cc @kevin-wangzefeng @samy2019

**Comment by xiayanshangda** [comment]
@subpathdev i have already installed docker and k8s, but the version is not the default version of kubeedge

**Comment by xiayanshangda** [comment]
@subpathdev i have tried this method yesterday,but not successful
![image](https://user-images.githubusercontent.com/39492112/59399773-da2e8180-8dc7-11e9-9ef0-f9c77e44b8cf.png)
how to know the version of kubernetes

**Comment by rohitsardesai83** [comment]
@xiayanshangda , please see this: https://github.com/kubeedge/kubeedge/tree/master/keadm#limitation

**Comment by xiayanshangda** [comment]
@rohitsardesai83  I followed the installation instructions,but failed in this step
![image](https://user-images.githubusercontent.com/39492112/59406039-4799dc80-8ddf-11e9-9eb9-9a8671028734.png)

**Comment by sids-b** [comment]
@xiayanshangda Currently kubeedge installer doesn't support CentOS. Please see #454

**Comment by xiayanshangda** [comment]
@sids-b thank you, I have found this problem

**Comment by sids-b** [comment]
Thanks @xiayanshangda . I am closing this issue :) If possible do contribute the centOS installer :)

**Comment by xiayanshangda** [comment]
@sids-b haha ,I believe in you.
