### ISSUE TITLE
keadm should not ignore errors

### ISSUE THREAD

**Issue by yamt** [kubeedge/kubeedge#698]
**What happened**:

in many cases, keadm ignores errors and continues.

**What you expected to happen**:

it should stop processing and prompt the user.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version: 0.3.0
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by rohitsardesai83** [comment]
@yamt , do you have a plan to address the problems step by step ? it would be good if we can have work items for solving the ignored errors.

**Comment by sids-b** [comment]
ping @yamt

**Comment by fisherxu** [comment]
I think #844 have fixed this issue  :)
/close
