### ISSUE TITLE
updating device values

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#709]
**What happened**:
```sh
controller/upstream.go:169 Failed to patch device status &{{[{CPU_Temperatur { map[]} {161 map[timestamp:1560756072724 type:string]}} {cpu_id { map[]} {0 map[timestamp:1560756072724 type:string]}}]}} of device cpu-sensor-tag01 in namespace default
```

the concrete problem seems to be this: 
```sh
status.twins.desired.value in body is required
```

I've create an minimal example to understand this problem: https://play.golang.org/p/JepBWmp_YxD
I think the problem is this:
 - json.Marshal doesn't remove the desired field

An possible solution is could the Usage of Struct-Pointer as TwinValues. 

**What you expected to happen**:
Updating the values of a device in the kuberentes API should run successfully

**How to reproduce it (as minimally and precisely as possible)**:
1. setting up kuberenetes api-server
2. kubectl apply -f build/crd.samples/devices/led-light-device-model.yaml
3. kubectl apply -f build/crd.samples/devices/led-light-device-instance.yaml
4. kubectl edit device led-light-instance-01 
   a. adding desired: {} to power-status

**Anything else we need to know?**:

**Environment**:
- KubeEdge version: git commit hash: 1a0d4e230e23036fc584991a95f06c968422e268
- OS (e.g. from /etc/os-release): not relevant
- kubectl version:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by subpathdev** [comment]
also an valid solution could be this one:
diff --git a/cloud/pkg/devicecontroller/apis/devices/v1alpha1/device_instance_types.go b/cloud/pkg/devicecontroller/apis/devices/v1alpha1/device_instance_types.go
index d7f91bc..d2a3c82 100644
--- a/cloud/pkg/devicecontroller/apis/devices/v1alpha1/device_instance_types.go
+++ b/cloud/pkg/devicecontroller/apis/devices/v1alpha1/device_instance_types.go
@@ -139,7 +139,7 @@ type Twin struct {
 // TwinProperty represents the device property for which an Expected/Actual state can be defined.
 type TwinProperty struct {
        // Required: The value for this property.
-       Value string `json:"value,omitempty"`
+       Value string `json:"value,"`
        // Additional metadata like timestamp when the value was reported etc.
        // +optional
        Metadata map[string]string `json:"metadata,omitempty"`

**Comment by subpathdev** [comment]
I like the second solution. Thoughts?

**Comment by rohitsardesai83** [comment]
> I like the second solution. Thoughts?

thanks @subpathdev for raising the issue. Just wanted to check if you have applied the new yamls for the device model and device instance crds : https://github.com/kubeedge/kubeedge/pull/669

this PR enforces some required fields in the schema. Have you applied the schema with these validations ?

**Comment by subpathdev** [comment]
Yes I've used the new yamls.
