### ISSUE TITLE
Device Type Metadata getting overwritten to "string" type

### ISSUE THREAD

**Issue by sujithsimon22** [kubeedge/kubeedge#711]
**What happened**:
Device instance Metadata gets overwritten to "string" value even if it is created with "int" value

**What you expected to happen**:
The metadata type given by user should be retained instead of overwriting it

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup kubeedge cloud and edge
2. Create device model and a device instance with desired metadata type as int
3. Check the device value at edge using MQTT (it would have converted the metadata value to string)

**Environment**:
- KubeEdge version: 0.3

**Comment by sids-b** [comment]
I think the problem is in these 2 lines

**Comment by subpathdev** [comment]
Compare to issue #681
