### ISSUE TITLE
using “fieldPath: spec.nodeName” Error.

### ISSUE THREAD

**Issue by zhanglu0704** [kubeedge/kubeedge#718]
**What happened**:
    When I apply daemonset in kubeedge ，I used the "valueFrom: fieldRef:  fieldPath: spec.nodeName" to set node name as env value.
    But I fand the pod's status is false, and got the ERROR log:"F0617 11:47:36.114866       1 main.go:65] MY_NODE_NAME environment variable not set". 
    I check the env value in the container —— is empty， But I check the pod's info as "kubectl get pod <podname> -o yaml |grep fieldPath " is natural.

**What you expected to happen**:
I need to set each pod's environment variable as the node's host name at deployment time

**How to reproduce it (as minimally and precisely as possible)**:
'''
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
'''

**Environment**:         k8s master(1.11.6)
- KubeEdge version:  .0.0.2
- Hardware configuration:  arm64
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`): master :4.4.0-141-generic
- Others:

**Comment by rohitsardesai83** [comment]
@zhanglu0704 , currently edged doesn't support environment variables.
@gpinaik , can you please take a look ?

**Comment by sids-b** [comment]
@zhanglu0704 , Environment variables support has been merged in the master branch. Please let us know if you still face the issue. Closing this issue for now
