### ISSUE TITLE
pod use hostname to communicates

### ISSUE THREAD

**Issue by zhanglu0704** [kubeedge/kubeedge#719]
**What would you like to be added**:

I found that edge nodes were only allowed to use hostport,But we need to deploy an application that communicates with each pods  via hostname.

**Comment by rohitsardesai83** [comment]
@qizha , @sids-b , @anyushun

**Comment by sids-b** [comment]
Can you try out edgemesh feature ? Service name can be used to communicate between pods https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md

**Comment by zhanglu0704** [comment]
> Can you try out edgemesh feature ? Service name can be used to communicate between pods https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md

ok，I'll try what follow your advice,thank you.

**Comment by zhanglu0704** [comment]
> Can you try out edgemesh feature ? Service name can be used to communicate between pods https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md

I deploied edged on devices using ARM64 architecture, So I'm trying to compil CNI on the ARM64 device. I encountered such a mistake when I build host-local.
'''
Building API
Building reference CLI
Building plugins
   flannel
   tuning
   bridge
   ipvlan
   loopback
   macvlan
   ptp
   dhcp
# github.com/appc/cni/vendor/golang.org/x/sys/unix
gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t
gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14: undefined: Ucred
gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:27: undefined: Ucred
gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42: undefined: Cmsghdr
'''
   Could you please give me some more help?

**Comment by zhanglu0704** [comment]
> > Can you try out edgemesh feature ? Service name can be used to communicate between pods https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md
> 
> I deploied edged on devices using ARM64 architecture, So I'm trying to compil CNI on the ARM64 device. I encountered such a mistake when I build host-local.
> ```
> Building API
> Building reference CLI
> Building plugins
> flannel
> tuning
> bridge
> ipvlan
> loopback
> macvlan
> ptp
> dhcp
> 
> # github.com/appc/cni/vendor/golang.org/x/sys/unix
> gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t
> gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14: undefined: Ucred
> gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:27: undefined: Ucred
> gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42: undefined: Cmsghdr
> ```
> Could you please give me some more help?

I find that ,the version 0.2 don't have types_linux_arm64.go in vendor/golang.org/x/sys/unix/, it means version 0.2 doesn't support  arm64 for packeg unix .But I tried to use version 0.7 , it is supported.

**Comment by arcanique** [comment]
> > > Can you try out edgemesh feature ? Service name can be used to communicate between pods https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md
> > 
> > 
> > I deploied edged on devices using ARM64 architecture, So I'm trying to compil CNI on the ARM64 device. I encountered such a mistake when I build host-local.
> > ```
> > Building API
> > Building reference CLI
> > Building plugins
> > flannel
> > tuning
> > bridge
> > ipvlan
> > loopback
> > macvlan
> > ptp
> > dhcp
> > 
> > # github.com/appc/cni/vendor/golang.org/x/sys/unix
> > gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t
> > gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14: undefined: Ucred
> > gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:27: undefined: Ucred
> > gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42: undefined: Cmsghdr
> > ```
> > 
> > 
> > Could you please give me some more help?
> 
> I find that ,the version 0.2 don't have types_linux_arm64.go in vendor/golang.org/x/sys/unix/, it means version 0.2 doesn't support arm64 for packeg unix .But I tried to use version 0.7 , it is supported.

yess, This is the compilation information on my environment.
`[root@kwephicprd01496 plugins-0.2.0]# ./build
Building API
Building reference CLI
Building plugins
   flannel
   tuning
   bridge
   ipvlan
   loopback
   macvlan
   ptp
   dhcp
github.com/appc/cni/vendor/golang.org/x/sys/unix
gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/flock.go:18:42: undefined: Flock_t
gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14:29: undefined: Ucred
gopath/src/github.com/appc/cni/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42:9: undefined: Cmsghdr

[root@kwephicprd01496 plugins-0.2.0]# cd bin

[root@kwephicprd01496 bin]# ls

**bridge  cnitool  flannel  ipvlan  loopback  macvlan  ptp  tuning**
`
Only the dhcp and host-local components are not compiled, we are not currently using these two components. You can ignore this problem, copy the successfully compiled components to the /opt/cni/bin directory, follow the instructions to configure and I think it will be worked

**Comment by sids-b** [comment]
@zhanglu0704 , is the feature working for you ?

**Comment by sids-b** [comment]
Closing this issue. Please feel free to reopen or ping us on slack for further discussion :)
