### ISSUE TITLE
Reliable message delivery from cloud to edge

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#725]
**What would you like to be added**:
Create a mechanism to make sure each message is delivered reliably to edge.

**Why is this needed**:
In offline scenarios, when there is an update in pods or device, the message is not send to edge and it is lost. So the edgeNode is not aware of the changes.

**Comment by sids-b** [comment]
cc @kadisi @shouhong @chendave @subpathdev

**Comment by kadisi** [comment]
please assign to me

**Comment by rohitsardesai83** [comment]
Let's come up with some kind of design first as to how can we achieve this.

**Comment by kadisi** [comment]
@rohitsardesai83 ok

**Comment by kadisi** [comment]
> In offline scenarios, when there is an update in pods or device, the message is not send to edge and it is lost. So the edgeNode is not aware of the changes.

@rohitsardesai83 @sids-b 

take websocket as an example , we need to deal with  two things.  

one is write message error , we need to judge whether this error is ErrCloseSent.
https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/cloudhub/handler/eventhandler.goL255
```
		err = eh.hubIoWrite(hi, info.NodeID, &msg)
		if err != nil {
			bhLog.LOGGER.Errorf("write error, connection for node %s will be closed, affected event %s, reason %s",
				info.NodeID, dumpEventMetadata(event), err.Error())
			stop <- hubioWriteFail
			return
		}
```

add the following judgement:
```
if err == websocket.ErrCloseSent {

}
```
if we found this is `ErrCloseSent`, we need cache this msg. so this is the second thing which we need deal with.

we need change the field `channelPool` in `ChannelEventQueue` struct.  `channelPool` is a map of channel,  we should change it to a map of queue.

the queue struct like this:   refer to `k8s.io/client-go/util/workqueue/queue.go`
```
type EventQueue struct {
	queue []*Event
	lock  sync.RWMutex
}

// Get the first element of the queue, but do not pop it
// You must call Done with item when you have finished processing it.
func (this *EventQueue) Get() *Event {
	return nil
}

// Pop the first element of the queue
func (this *EventQueue) Done() {
}
// add new element to the queue
func (this *EventQueue) Add(e *Event) {
}
```
then , we can call `Get()` to get Event from this queue, and use  websocket to WriteMessage, if WriteMessage success, we Need call `Done()` to pop this useless event, if we judge `ErrCloseSent`, we need send something to stop channel, and if it output other error, we need log it , and also call `Done()` .

**Comment by rohitsardesai83** [comment]
@kadisi , the idea sounds good to use work queue, we need to think more about : 

1. what happens if we get an event from the queue and for some reason can't process the event. since it is not marked done, the other events in the queue will be blocked or starved?
2. what happens if there are some events in the queue and the edge controller crashes ? 

I would suggest we create a design proposal for this and start fleshing out the details.

**Comment by kadisi** [comment]
@rohitsardesai83 ok

**Comment by sids-b** [comment]
@kadisi , Also we need to be careful with in-memory queue. An edgeNode may be offline for a long period of time. In this case it will consume a lot of memory.
Also we can think of few mechanisms to save B/W for eg:
If there are 2 pod update messages when edgenode is offline, we only send the last one...

Thoughts ?

**Comment by kadisi** [comment]
@sids-b yes, i am thinking about it.

**Comment by kadisi** [comment]
@sids-b @rohitsardesai83  I think we should deal with issue #339 (pr:  https://github.com/kubeedge/beehive/pull/21)  .  Data transmission format should be resolved first and then reliable message delivery.
