### ISSUE TITLE
dependencies version incorrect

### ISSUE THREAD

**Issue by anyushun** [kubeedge/kubeedge#726]
**What happened**:some dependencies version is behind, get CI failed when create pull request to kubeedge

**What you expected to happen**:
all dependencies version keep correct

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by rohitsardesai83** [comment]
@anyushun , can we close this ?
