### ISSUE TITLE
a problem about keadm init when installing kubeedge

### ISSUE THREAD

**Issue by xiayanshangda** [kubeedge/kubeedge#729]
I use ubuntu 16.04.5 LTS. when I install kubeedge, the first time execute "keadm init", the result is
![image](https://user-images.githubusercontent.com/39492112/59823172-dcf91b80-935f-11e9-8374-bba6b0881ca0.png)

then, I execute  "keadm init" again, the result is
![image](https://user-images.githubusercontent.com/39492112/59823210-09ad3300-9360-11e9-92e6-f2d576e9832c.png)

how to solve this problem

**Comment by xiayanshangda** [comment]
@samy2019 @srivatsav123

**Comment by xiayanshangda** [comment]
@sids-b @rohitsardesai83

**Comment by rohitsardesai83** [comment]
can you try from a clean state again ? looks like there were problems downloading the tar balls.

**Comment by sids-b** [comment]
closing this issue. Please feel free to reach to us via slack or reopen this issue for further discussion
