### ISSUE TITLE
Change to use gomod to manage the dependencies

### ISSUE THREAD

**Issue by qizha** [kubeedge/kubeedge#748]
**What would you like to be added**:
Use gomod to manage the dependies and remove the vendor from the project

**Why is this needed**:
To manage the dependiences more efficient

**Comment by rohitsardesai83** [comment]
:+1:

**Comment by subpathdev** [comment]
@qizha do you have started with this issue?

**Comment by qizha** [comment]
@subpathdev not yet, please go ahead. thanks

**Comment by subpathdev** [comment]
I get the following error: go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"

As you can see on the github.com/docker/docker dependencies they are using github.com/Sirupsen/logrus

I think the problem can be found in the usage of the caps in Sirupsen. If anybody knows a solution feel free to contribute. (currently you can find the actual state on https://github.com/subpathdev/kubeedge/tree/gomod)

**Comment by subpathdev** [comment]
If we use another version of github.com/docker/docker the problem, which I described above should be solved. I will focus this later.

**Comment by sids-b** [comment]
@subpathdev ,which version of docker you used to solve the problem ?

**Comment by subpathdev** [comment]
We have also to increase the version of k8s.io/[kubernetes,api,...]. The kubernetes package include docker and I run into the same sirupsen error. 

Currently I use ``gotip`` instead of ```go```.  Gotip shows the include path, so we can identify the package which make problems. As an example:
```
$go mod vendor
go: finding github.com/docker/docker/api/types/network latest
go: finding github.com/docker/docker/client latest
go: finding github.com/docker/docker/api/types/filters latest
go: finding github.com/docker/docker/api/types/strslice latest
go: finding github.com/docker/docker/api/types/container latest
go: finding github.com/docker/docker/api/types latest
go: finding github.com/docker/docker/api/types/image latest
go: finding github.com/docker/docker/api latest
go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements
```

vs 
```
$ gotip mod vendor
go: github.com/kubeedge/kubeedge/edge/pkg/edged imports
    k8s.io/kubernetes/pkg/kubelet/kuberuntime imports
    github.com/docker/docker/pkg/sysinfo imports
    github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
```

**Comment by subpathdev** [comment]
@sids-b If I knew the required version, I will write the required versions here.

**Comment by sids-b** [comment]
@subpathdev , can we try something like this  ??https://stackoverflow.com/questions/55537287/unexpected-module-path-github-com-sirupsen-logrus

**Comment by sids-b** [comment]
Some similar discussions are happening here as well https://github.com/golang/go/issues/28489

**Comment by subpathdev** [comment]
> @subpathdev , can we try something like this ??https://stackoverflow.com/questions/55537287/unexpected-module-path-github-com-sirupsen-logrus

Thank you this seems to work to solve the sirupsen bug.

**Comment by sids-b** [comment]
@subpathdev , is there any update on this one ?

**Comment by subpathdev** [comment]
I am struggling with cadvisor:
```
make[1]: Entering directory '/home/subpath/data/git/arbeit/kubeedge/edge'
go build cmd/edge_core.go
# github.com/google/cadvisor/http
../../../../go/pkg/mod/github.com/google/cadvisor@v0.29.2/http/handlers.go:101:33: too many arguments in call to prometheus.NewProcessCollector
	have (int, string)
	want (prometheus.ProcessCollectorOpts)
make[1]: *** [Makefile:5: edge_core] Error 2
```
uthe problems could be referenced to github.com/prometheus/client_golang. I have to read the documentation about a way to solve this issue;

**Comment by edisonxiang** [comment]
hey @subpathdev
Thanks your efforts.
I am working on #806 
perhaps we can work together.
We need to update some codes if we want to use k8s 1.15.

**Comment by subpathdev** [comment]
@edisonxiang Yes I think that is a good idea.
