### ISSUE TITLE
keadm init error

### ISSUE THREAD

**Issue by liangyuanpeng** [kubeedge/kubeedge#753]
i am trying to keadm init
```
sudo keadm init --docker-version=18.09.6 --kubernetes-version=v1.14.3
```

and i got some err:
```
I0622 13:59:12.485568  122121 version.go:97] falling back to the local client version: v1.14.3
[init] Using Kubernetes version: v1.14.3
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Port-6443]: Port 6443 is in use
        [ERROR Port-10251]: Port 10251 is in use
        [ERROR Port-10252]: Port 10252 is in use
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
        [ERROR Port-10250]: Port 10250 is in use
        [ERROR Port-2379]: Port 2379 is in use
        [ERROR Port-2380]: Port 2380 is in use
        [ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...
```

OS:ubuntu16

so what should i do?

**Comment by gilles537** [comment]
It looks like you already have a cluster running. Keadm init creates a cluster for you.

**Comment by sids-b** [comment]
@liangyuanpeng , is this issue solved ?

**Comment by liangyuanpeng** [comment]
@sids-b 
not yet,i have run ``kubeadm reset`` and `keadm init --docker-version=18.06.3(or 18.06.3-ce) --kubernetes-version=1.14.3` but i got some error 
``error: Expected Docker version is not available in OS repo``

my docker version:
```
[root@node1 keadm]# docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by sids-b** [comment]
@samy2019 @srivatsav123 @naveensriram , can you take a look at this ?

**Comment by sids-b** [comment]
@liangyuanpeng , are you still facing this issue ?

**Comment by huangy7** [comment]
is this issue solved ? I have also encountered this issue：`error:Expected Docker version is not available in OS repo`

**Comment by huangy7** [comment]
@liangyuanpeng is this issue solved ? I am facing the same issue. I have run `keadm init`, then I got some error `error: Expected Docker version is not available in OS repo`

**Comment by huangy7** [comment]
@sids-b, is this issue solved?

**Comment by huangy7** [comment]
@sids-b ,I am facing the issue, what should I do? thanks!

**Comment by sids-b** [comment]
@huangy7 , can you run kubeadm reset and then run keadm init ? I guess it should work

**Comment by huangy7** [comment]
@sids-b I did as you said, but it still not didn't work, here are my actions and logs
`[root@master keadm]# kubeadm reset
[reset] Reading configuration from the cluster...
[reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[reset] WARNING: Changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] Are you sure you want to proceed? [y/N]: y
[preflight] Running pre-flight checks
[reset] Removing info for node "master" from the ConfigMap "kubeadm-config" in the "kube-system" Namespace
[reset] WARNING: Changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] Are you sure you want to proceed? [y/N]: y
[preflight] Running pre-flight checks
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]

The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually.
For example:
iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.

The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
[root@master keadm]# 
[root@master keadm]# 
[root@master keadm]# ./keadm init
Error: Expected Docker version is not available in OS repo
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of pre-requisites and KubeEdge

keadm init --kubeedge-version=0.2.1 --kubernetes-version=1.14.1 --docker-version=18.06.3 --kube-config=~/.kube/config

  - In case, any flag is used in a format like "--docker-version" or "--docker-version=" (without a value)
    then default versions shown in help will be chosen. 
    The versions for "--docker-version", "--kubernetes-version" and "--kubeedge-version" flags should be in the
    format "18.06.3", "1.14.0" and "0.2.1" respectively
  - kube-config is the path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver


Flags:
      --docker-version string[="18.06.0"]           Use this key to download and use the required Docker version (default "18.06.0")
  -h, --help                                        help for init
      --image-repository string[="k8s.gcr.io"]      Use this key to set the Kubernetes docker image repository (default "k8s.gcr.io")
      --kube-config string                          Use this key to set kube-config path, eg: $HOME/.kube/config
      --kubeedge-version string[="0.3.0"]           Use this key to download and use the required KubeEdge version (default "0.3.0")
      --kubernetes-version string[="1.14.1"]        Use this key to download and use the required Kubernetes version (default "1.14.1")
      --pod-network-cidr string[="100.64.0.0/10"]   Use this key to set the Kubernetes pod Network cidr  (default "100.64.0.0/10")

error: Expected Docker version is not available in OS repo
`

**Comment by huangy7** [comment]
```
fdsaf
sdfasd
dsfasdf
```

**Comment by huangy7** [comment]
I did as you said, but it still not didn't work, here are my actions and logs
```
[root@master keadm]# kubeadm reset
[reset] Reading configuration from the cluster...
[reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[reset] WARNING: Changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] Are you sure you want to proceed? [y/N]: y
[preflight] Running pre-flight checks
[reset] Removing info for node "master" from the ConfigMap "kubeadm-config" in the "kube-system" Namespace
[reset] WARNING: Changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] Are you sure you want to proceed? [y/N]: y
[preflight] Running pre-flight checks
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]

The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually.
For example:
iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.

The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
[root@master keadm]# 
[root@master keadm]# 
[root@master keadm]# ./keadm init
Error: Expected Docker version is not available in OS repo
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of pre-requisites and KubeEdge

keadm init --kubeedge-version=0.2.1 --kubernetes-version=1.14.1 --docker-version=18.06.3 --kube-config=~/.kube/config

  - In case, any flag is used in a format like "--docker-version" or "--docker-version=" (without a value)
    then default versions shown in help will be chosen. 
    The versions for "--docker-version", "--kubernetes-version" and "--kubeedge-version" flags should be in the
    format "18.06.3", "1.14.0" and "0.2.1" respectively
  - kube-config is the path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver


Flags:
      --docker-version string[="18.06.0"]           Use this key to download and use the required Docker version (default "18.06.0")
  -h, --help                                        help for init
      --image-repository string[="k8s.gcr.io"]      Use this key to set the Kubernetes docker image repository (default "k8s.gcr.io")
      --kube-config string                          Use this key to set kube-config path, eg: $HOME/.kube/config
      --kubeedge-version string[="0.3.0"]           Use this key to download and use the required KubeEdge version (default "0.3.0")
      --kubernetes-version string[="1.14.1"]        Use this key to download and use the required Kubernetes version (default "1.14.1")
      --pod-network-cidr string[="100.64.0.0/10"]   Use this key to set the Kubernetes pod Network cidr  (default "100.64.0.0/10")

error: Expected Docker version is not available in OS repo

```

**Comment by huangy7** [comment]
@sids-b here are versions of my docker and kubernetes
```
[root@master keadm]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[root@master keadm]# 
[root@master keadm]# docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by huangy7** [comment]
@sids-b , even though I added some optional flags to specify the version, it still didn't work.
```
[root@master keadm]# git branch
  master
  release-1.0
* release-1.1
[root@master keadm]# ./keadm init --kubeedge-version=1.1.0 --kubernetes-version=1.15.0 --docker-version=18.06.3-ce --kube-config=~/.kube/config
Error: Expected Docker version is not available in OS repo
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of pre-requisites and KubeEdge

keadm init --kubeedge-version=0.2.1 --kubernetes-version=1.14.1 --docker-version=18.06.3 --kube-config=~/.kube/config

  - In case, any flag is used in a format like "--docker-version" or "--docker-version=" (without a value)
    then default versions shown in help will be chosen. 
    The versions for "--docker-version", "--kubernetes-version" and "--kubeedge-version" flags should be in the
    format "18.06.3", "1.14.0" and "0.2.1" respectively
  - kube-config is the path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver


Flags:
      --docker-version string[="18.06.0"]           Use this key to download and use the required Docker version (default "18.06.0")
  -h, --help                                        help for init
      --image-repository string[="k8s.gcr.io"]      Use this key to set the Kubernetes docker image repository (default "k8s.gcr.io")
      --kube-config string                          Use this key to set kube-config path, eg: $HOME/.kube/config
      --kubeedge-version string[="0.3.0"]           Use this key to download and use the required KubeEdge version (default "0.3.0")
      --kubernetes-version string[="1.14.1"]        Use this key to download and use the required Kubernetes version (default "1.14.1")
      --pod-network-cidr string[="100.64.0.0/10"]   Use this key to set the Kubernetes pod Network cidr  (default "100.64.0.0/10")

error: Expected Docker version is not available in OS repo

```

**Comment by sids-b** [comment]
can you change the value of --docker-version to just 18.06.3 and try ? if you don't use this flag while running the command, it will install the default version

**Comment by xueyahui1** [comment]
我也出现了此问题，请问应该如何解决?

**Comment by huangy7** [comment]
> 我也出现了此问题，请问应该如何解决?

[我最后没有通过这个方式部署，运行二进制部署或者容器部署，可以参考下这篇文章
[KubeEdge 详解](http://huangy.top/2019/10/28/KubeEdge%E8%AF%A6%E8%A7%A3/)

**Comment by VipinKrizz** [comment]
@sids-b When i was running keadm init in my Ubuntu machine (version 18.04 LTS) i am getting this error.
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-10250]: Port 10250 is in use
	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
Error: failed to run 'sh -c swapoff -a && kubeadm init --image-repository  "k8s.gcr.io" --pod-network-cidr=100.64.0.0/10' because of error : exit status 1

**NOTES**
kubernetes version: v1.14.9
docker version: 18.06.0
kubeedge version: 0.3.0
also i tried with kubeedge version v1.1.0 also both gave the same error.

**Comment by Hades32** [comment]
> It looks like you already have a cluster running. Keadm init creates a cluster for you.

Is it possible to have it install its components into my already existing cluster?

**Comment by fisherxu** [comment]
Please try the latest keadm v1.2.1 :)
/close
