### ISSUE TITLE
Containerd does not support port mapping

### ISSUE THREAD

**Issue by anyushun** [kubeedge/kubeedge#769]
**What happened**:create a deployment with hostPort, it not work

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:release-1.0
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by sids-b** [comment]
@anyushun , Is this a problem with containerd or with our CRI implementation ?

**Comment by kadisi** [comment]
@sids-b 

containerd support port mapping.

@anyushun you need change your cni configfile in `/etc/cni/net.d/`

such as
```
{
    "name": "mynet",
    "plugins": [
      {
        "type": "portmap",
        "capabilities": {"portMappings": true}
      }
    ]
}


```

**Comment by sids-b** [comment]
@kadisi , can you please change the edgemesh test guide so that we can close this issue ??

**Comment by sids-b** [comment]
@arcanique , we can try this soultion to see if it solves the issue

**Comment by arcanique** [comment]
@sids-b @kadisi Thank you very much, this change is OK. And I will do an e2e verification.

**Comment by fisherxu** [comment]
Containerd support port mapping, will close this first.
/close
