### ISSUE TITLE
docs: bug of release_package.md, urls were wrong

### ISSUE THREAD

**Issue by HeathKang** [kubeedge/kubeedge#803]
Just a little urls location bug when I following the steps to run kubeedge. The contents of  `kubeedge/docs/getting-started/release_package.md`:

>## Generate Certificates
>```
>wget -L https://github.com/kubeedge/kubeedge/blob/master/build/tools/certgen.sh
># make script executable
>chmod +x certgen.sh
>bash -x ./certgen.sh genCertAndKey edge
>```

>- Create device model and device CRDs
>```
>wget -L https://github.com/kubeedge/kubeedge/blob/master/build/crds/devices/devices_v1alpha1_devicemodel.yaml
># make script executable
>chmod +x devices_v1alpha1_devicemodel.yaml
>kubectl create -f devices_v1alpha1_devicemodel.yaml
>wget -L https://github.com/kubeedge/kubeedge/blob/master/build/crds/devices/devices_v1alpha1_device.yaml
># make script executable
>chmod +x devices_v1alpha1_device.yaml
>kubectl create -f devices_v1alpha1_device.yaml
>```

I think URLS were wrong since I used the commands just got HTML file. And the right urls are below:
## Generate Certificates
```
wget -L https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/tools/certgen.sh
# make script executable
chmod +x certgen.sh
bash -x ./certgen.sh genCertAndKey edge
```
- Create device model and device CRDs
```
wget -L https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_devicemodel.yaml
# make script executable
chmod +x devices_v1alpha1_devicemodel.yaml
kubectl create -f devices_v1alpha1_devicemodel.yaml
wget -L https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_device.yaml
# make script executable
chmod +x devices_v1alpha1_device.yaml
kubectl create -f devices_v1alpha1_device.yaml
```

**Comment by rohitsardesai83** [comment]
@HeathKang , thanks for pointing this out , can you please raise a PR with this fix ?

**Comment by rohitsardesai83** [comment]
@srivatsav123 , just fyi.

**Comment by HeathKang** [comment]
@rohitsardesai83 sure
