### ISSUE TITLE
edgemesh: Support  edge-cloud communication

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#807]
**What would you like to be added**:
Support communication of applications between cloud and edge.

**Why is this needed**:
Currently, pod to pod communication between edge nodes in the same network is supported. Edge to cloud communication is required.

**Comment by RocMe** [comment]
Hello,I want to know how to achieve "pod to pod communication"  in kubeedge .Can you offer the network design? Thanks.

**Comment by sids-b** [comment]
Hi @RocMe , try this try this out https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md

The design proposal is here https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/edgemesh-design.md

**Comment by RocMe** [comment]
> Hi @RocMe , try this try this out https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md
> 
> The design proposal is here https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/edgemesh-design.md

Thanks.
