### ISSUE TITLE
 Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)

### ISSUE THREAD

**Issue by Warok21** [kubeedge/kubeedge#816]
**What happened**: When checking the  `edg econtroller.log`  

> Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)

**What you expected to happen**:Controller working correctly

**How to reproduce it (as minimally and precisely as possible)**:`/keadm init`
Installing calico :https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
adding the following line 
```
- --insecure-port=8080
- --insecure-bind-address=0.0.0.0
```
and changed `address: 0.0.0.0` to `address: <your IPv4 address>` in controller.yaml
and to be sure `sudo swapoff -a`
**Anything else we need to know?**:
```
sudo kubectl create -f devices_v1alpha1_devicemodel.yaml
Error from server (AlreadyExists): error when creating "devices_v1alpha1_devicemodel.yaml": customresourcedefinitions.apiextensions.k8s.io "devicemodels.devices.kubeedge.io" already exists
sudo kubectl create -f devices_v1alp ha1_device.yaml
Error from server (AlreadyExists): error when creating "devices_v1alpha1_device.yaml": customresourcedefinitions.apiextensions.k8s.io "devices.devices.kubeedge.io" already exists
```
**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by rohitsardesai83** [comment]
@Warok21 , what is the current problem you are facing ? Is the edge controller up and running , and the error logs related to device crds are still showing up even after applying the crd yamls ?

Can you check which kubernetes cluster you are connected to ?

```sh
kubectl config current-context
```

**Comment by Warok21** [comment]
`sudo systemctl status kubelet.service` say :  active (running).
I run the

>  sudo ./keadm init, no error message, but If i check the log, I've got this error

**Comment by sids-b** [comment]
@Warok21 , use this command of see if yaml's re applied
```
sudo kubectl create -f devices_v1alpha1_devicemodel.yaml -s 86.119.28.207
```

**Comment by Warok21** [comment]
> Unable to connect to the server: dial tcp 86.119.28.207:80: i/o timeout

**Comment by sids-b** [comment]
And restart the edgecontroller after this

**Comment by Warok21** [comment]
Still the same error in the log after, `keadm reset`, and then `keadm init`

**Comment by Warok21** [comment]
Btw, in :"

> src/github.com/kubeedge/kubeedge/cloud/conf/controller.yaml"
Under "controller, kube, kubeconfig" it's empty, should I change it?

**Comment by rohitsardesai83** [comment]
> Btw, in :"
> 
> > src/github.com/kubeedge/kubeedge/cloud/conf/controller.yaml"
> 
> Under "controller, kube, kubeconfig" it's empty, should I change it?

If the api server is running in secure mode , then you can pass the location of the kubeconfig file.
If not , then this can be left empty.

**Comment by jwzl** [comment]
No permmition for list  device by your serviceaccount?
or, may be you have not create a device

**Comment by rohitsardesai83** [comment]
@Warok21 , any updates on this issue ?

**Comment by sids-b** [comment]
closing this issue. please feel free to reach out to us via slack or reopen this issue for further discussions :)
