### ISSUE TITLE
devicecrd : device model property type can be only string or int64. Other types are not supported.

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#823]
**What would you like to be added**:
When creating a device model , we need to validate if the property type is one of [ int64 , string ].

**Why is this needed**:
Validation of crds is needed for ensuring valid metadata is persisted for use by mappers / platform.

**Comment by chendave** [comment]
per the comments from https://github.com/kubeedge/kubeedge/issues/826, I feel we can close this issue.

**Comment by sids-b** [comment]
Agree with @chendave. Closing this issue.
