### ISSUE TITLE
device crd: Reject property visitors  other than bluetooth, modbus and opcua protocol.

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#824]
**What would you like to be added**:
When creating a device model, add validation to support Property visitors for bluetooth, modbus and opcua protocols only. Other protocol visitors are not supported.

**Why is this needed**:
Validation of crds is needed for ensuring valid metadata is persisted for use by mappers / platform.

**Comment by sids-b** [comment]
cc @chendave . Thoughts ??

**Comment by chendave** [comment]
Let's close this, I don't think we really need to do this.
