### ISSUE TITLE
Unable to deploy local image as pod

### ISSUE THREAD

**Issue by lucifercr07** [kubeedge/kubeedge#825]
**What happened**:
Tried to deploy a local docker image to edge node. The status of pod is always in `Container creating` state. Even set the `imagePullPolicy` in yaml file which seems to not being adhered while deployment.

root@ubuntu:~# kubectl describe pod liota-pod-6f5585cc59-xtzg7
Name:               liota-pod-6f5585cc59-xtzg7
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               pulse-iotc-agent-cluster/
Start Time:         Fri, 28 Jun 2019 22:58:43 +0530
Labels:             pod-template-hash=6f5585cc59
                    run=liota-pod
Annotations:        <none>
Status:             Unknown
IP:                 
Controlled By:      ReplicaSet/liota-pod-6f5585cc59
Containers:
  liota-pod:
    Image:        liota_docker_image:1.0.0
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f4qzf (ro)
Conditions:
  Type    Status
  Ready   False 
Volumes:
  default-token-f4qzf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-f4qzf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  51m   default-scheduler  Successfully assigned default/liota-pod-6f5585cc59-xtzg7 to pulse-iotc-agent-cluster

**What you expected to happen**:
Successful deployment.
**How to reproduce it (as minimally and precisely as possible)**:
Try to deploy a local image to edge.

**Environment**:
- KubeEdge version: default 
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): x86_64

**Comment by rohitsardesai83** [comment]
@lucifercr07 , can you start edge_core with log level of ERROR and share the edge_core log  ?

**Comment by Baoqiang-Zhang** [comment]
@lucifercr07 Did you set `imagePullPolicy` as `IfNotPresent` ?

**Comment by lucifercr07** [comment]
@Baoqiang-Zhang yes have tried that

**Comment by sids-b** [comment]
@lucifercr07 , can you please share the error loags ?

**Comment by sids-b** [comment]
Closing this issue. Please feel free to reopen or reach out via slack for further discussion,
