### ISSUE TITLE
devicecrd: Reject protocol configs for protocols other than OPC UA , Modbus and Bluetooth.

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#826]
**What would you like to be added**:
While creating a device instance, protocol configs are optional, but if provided, they can be one of [OPC UA, Modbus, and Bluetooth]. Other protocol configs are not supported.

**Why is this needed**:
Validation of CRDs is needed for ensuring valid metadata is persisted for use by mappers/platform.

**Comment by kevin-wangzefeng** [comment]
We should not reject protocols that is not predefined in-tree, which will prevent people adding their own protocol/mapper implementations.
For protocols already defined in-tree, we can check if all the fields are filled correctly.

**Comment by sids-b** [comment]
cc @chendave . Thoughts ?

**Comment by chendave** [comment]
@sids-b , I agree with Kevin's comments, so the patch there has been updated (https://github.com/kubeedge/kubeedge/pull/1075) to only allow one protocol, and reject unknown protocols.
