### ISSUE TITLE
cross build kubeedge edge failed(ARM64)

### ISSUE THREAD

**Issue by OlympusHo** [kubeedge/kubeedge#839]
**What happened**:
cross build kubeedge edge failed(ARM64)
**What you expected to happen**:
cross build kubeedge edge success(ARM64)!
**How to reproduce it (as minimally and precisely as possible)**:
cd $GOPATH/src/github.com/kubeedge/kubeedge/edge
sudo apt-get install gcc-arm-linux-gnueabi
export GOARCH=arm64
export GOOS="linux"
export GOARM=7                             
export CGO_ENABLED=1
export CC=arm-linux-gnueabi-gcc
make edge_core
**Environment**:
- KubeEdge version:
master
- Hardware configuration:
arm64
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux olympusedge 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- compile log
root@olympusedge:~/go/src/github.com/kubeedge/kubeedge/edge# make
go build cmd/edge_core.go
runtime/cgo
In file included from _cgo_export.c:3:0:
cgo-gcc-export-header-prolog:25:14: error: size of array ‘_check_for_64_bit_pointer_matching_GoInt’ is negative
Makefile:5: recipe for target 'edge_core' failed
make: *** [edge_core] Error 2

**Comment by subpathdev** [comment]
can you please try this command:
```
export GOARCH=arm64
export GOOS=linux
export GOARM=7
cd $GOPATH/src/github.com/kubeedge/kubeedge/edge
make edge_core
```

**Comment by OlympusHo** [comment]
> can you please try this command:
> 
> ```
> export GOARCH=arm64
> export GOOS=linux
> export GOARM=7
> cd $GOPATH/src/github.com/kubeedge/kubeedge/edge
> make edge_core
> ```

Thanks for your reply!
cross compile success as your reply,but the edge can't  run up, error infos as below:

root@c05c2f13d4f75373a39f60b27d8d4cb9:/home/olympus/kubeedge/edge# ./edge_core 
2019/07/02 00:43:04 WARN: empty configurtion from [CommandlineSource]
2019/07/02 00:43:04 WARN: empty configurtion from [MemorySource]
New file source added for configuration: /home/olympus/kubeedge/edge/conf/edge.yamlNew file source added for configuration: /home/olympus/kubeedge/edge/conf/logging.yamlNew file source added for configuration: /home/olympus/kubeedge/edge/conf/modules.yaml/home/olympus/kubeedge/edge/conf/logging.yamllogConfig:&{DEBUG  [stdout] true false  }
2019-07-02 00:43:04.234 +00:00 DEBUG :0 init logger...
[ORM]2019/07/02 00:43:04 register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
2019-07-02 00:43:04.235 +00:00 FATAL dbm/db.go:61 Failed to register db: register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
panic: 2019-07-02 00:43:04.235 +00:00 FATAL dbm/db.go:61 Failed to register db: register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
github.com/kubeedge/kubeedge/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager.(*logger).logs(0x442007c540, 0x4420039450, 0x1, 0x1, 0x4, 0x442010c240, 0x8c, 0x0, 0x0, 0x0)
        /root/go/src/github.com/kubeedge/kubeedge/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/logger.go:182 +0x710
github.com/kubeedge/kubeedge/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager.(*logger).logf(0x442007c540, 0x4, 0x143db62, 0x19, 0x4420039440, 0x1, 0x1)
        /root/go/src/github.com/kubeedge/kubeedge/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/logger.go:212 +0xb0
github.com/kubeedge/kubeedge/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager.(*logger).Fatalf(0x442007c540, 0x143db62, 0x19, 0x4420039440, 0x1, 0x1)
        /root/go/src/github.com/kubeedge/kubeedge/vendor/github.com/go-chassis/paas-lager/third_party/forked/cloudfoundry/lager/logger.go:232 +0x50
github.com/kubeedge/kubeedge/edge/pkg/common/dbm.init.0()
        /root/go/src/github.com/kubeedge/kubeedge/edge/pkg/common/dbm/db.go:61 +0x420

**Comment by OlympusHo** [comment]
change the CC=arm-linux-gnueabi-gcc to CC=aarch64-linux-gnu-gcc，compile success!
