### ISSUE TITLE
devicecrd: Handle device model updates

### ISSUE THREAD

**Issue by rohitsardesai83** [kubeedge/kubeedge#843]
**What would you like to be added**:
1. We create a device model, device instance referring to the model.
2. The mapper consumes the config map generated after creating the device instance, connects to the device and starts doing read/write operations on the device.
3. Now say we want to update a device property or a visitor in the model or delete a device property from the model.

| Update Type                    | Expected Behaviour                                       |
|-------------------------------|----------------------------------------------                 |
|Rename a property in devicemodel       |  Rename the device twin in the device instance. The config map is updated. The mapper needs to stop watching on old property and start watching on new property ie refresh its state                                           |
|Change the propery type in devicemodel             | Change the device twin property type. The config map is updated . The mapper consuming the map needs to refresh its in-memory state with the new property type settings.|
|Change a property visitor in devicemodel | The config map is updated. The mapper needs to refresh to start read/write operations based on the changes in the visitor settings.|
|Delete a property in devicemodel | Delete the device twin corresponding to the property in the device instance. The config map is updated. The mapper consuming the config map needs to be refreshed.|
|Delete a property visitor in device model          |  The config map is updated. The mapper needs to stop read/write operations using the deleted property visitor.|

**Why is this needed**:
To ensure proper functioning of mappers.

**Comment by sids-b** [comment]
cc @chendave . Thoughts ?
