### ISSUE TITLE
creation of DeviceModel should fail if there is any misconfiguration

### ISSUE THREAD

**Issue by chendave** [kubeedge/kubeedge#845]
**What would you like to be added**:

``` bash
git diff crd-samples/devices/CC2650-device-model.yaml
diff --git a/build/crd-samples/devices/CC2650-device-model.yaml b/build/crd-samples/devices/CC2650-device-model.yaml
index c8e6473..29dfc18 100644
--- a/build/crd-samples/devices/CC2650-device-model.yaml
+++ b/build/crd-samples/devices/CC2650-device-model.yaml
@@ -8,9 +8,9 @@ spec:
   - name: temperature
     description: temperature in degree celsius
     type:
-     int:
-      accessMode: ReadOnly
-      maximum: 100
+     test:
+      access: ReadOnly
+      max: 100
       unit: degree celsius
   - name: temperature-enable
     description: enable data collection of temperature sensor
```

$ kubectl create -f crd-samples/devices/CC2650-device-model.yaml
devicemodel.devices.kubeedge.io/cc2650-sensortag created

**Why is this needed**:

The configuration doesn't follow crd schema validation, there should be a way to reject the creation.  It would be nice to have some other approach beside crd validation exposed by the updating of the yaml  template only.

`external admission webhooks` might be helpful in this case.

**Comment by chendave** [comment]
cc @rohitsardesai83 @sids-b

**Comment by sids-b** [comment]
+1

**Comment by chendave** [comment]
should be under the umbrella of #405 as well.

**Comment by chendave** [comment]
After apply the webhook, below error message will expected with the malformed configuration.

# kubectl create -f CC2650-device-model-malformed.yaml
Error from server: error when creating "CC2650-device-model-malformed.yaml": admission webhook "validation-devices.kubeedge.io" denied the request: Either Int or String must be set
