### ISSUE TITLE
Add golint&govet check to all the component

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#847]
**What would you like to be added**:
Add golint&govet check to all the components, and fix all the lint/vet issue exist now.

**Why is this needed**:
Make the code more standardized.

**Comment by sids-b** [comment]
Closing #518 as this issue covers the scope

**Comment by sids-b** [comment]
@fisherxu , does this issue still persists ?

**Comment by fisherxu** [comment]
now we have checked all the components now, let's close this.
/close
