### ISSUE TITLE
Unit test failing in CI

### ISSUE THREAD

**Issue by sujithsimon22** [kubeedge/kubeedge#85]
- The init() present in : kubeedge/pkg/edgehub/config/config.go, will panic if "kubeedge/pkg/edgehub/config" is imported. 

- This is due to the fact that the binaries are built & run at a temporary location where the config files are not present.

- Thus, it will cause the unit tests to fail before it even has a chance to execute

**Comment by sujithsimon22** [comment]
![image](https://user-images.githubusercontent.com/35599628/51108000-acdca800-1816-11e9-83ae-364e4a434d5a.png)

**Comment by sids-b** [comment]
@srivatsav123 can you please help with this ?
