### ISSUE TITLE
CI using a static K8s setup for e2e tests

### ISSUE THREAD

**Issue by sujithsimon22** [kubeedge/kubeedge#855]
**What would you like to be added**:
CI is using a static K8s setup for running e2e tests. So parallel builds triggered for PRs  will cause problems while creating/deleting the kubernetes resource for device and device model in e2e tests for device management. Each build should use its own K8s setup

**Why is this needed**:
Parallel builds triggered for PRs  will cause problems while creating/deleting the kubernetes resource for device and device model in the shared K8s setup in the e2e tests for device management. Each build should use its own K8s setup

**Comment by fisherxu** [comment]
now we have used kind to start the static K8s.
/close
