### ISSUE TITLE
question:how edgesite  communicate with cloud

### ISSUE THREAD

**Issue by RocMe** [kubeedge/kubeedge#857]
**What would you like to be added**:
Hello.I want to know how edge site  communicate with the cloud. If I use the edgesite , does it mean giving up edge_core? 
**Why is this needed**:
When the cloud sends messages, how does edgesite handle it?

**Comment by sids-b** [comment]
@RocMe , edgesite is for scenarios where the k8s master is available in the edge network. So we have only removed the cloudhub-edgehub websocket communication. The controller directly sends pod/secret/configmap messages to metaManager. 

You don't have to giveup edge_core, all modules of edge_core as well as edgecontroller will be part of edgesite except for edgehub. Curently edgesite only support application deployment and management. Device scenarios are yet to be added

**Comment by RocMe** [comment]
> @RocMe , edgesite is for scenarios where the k8s master is available in the edge network. So we have only removed the cloudhub-edgehub websocket communication. The controller directly sends pod/secret/configmap messages to metaManager.
> 
> You don't have to giveup edge_core, all modules of edge_core as well as edgecontroller will be part of edgesite except for edgehub. Curently edgesite only support application deployment and management. Device scenarios are yet to be added

Thanks. The k8s master is at the edge for edgesite but k8s master is at the cloud for edge_core. If I want to send some message from cloud to edgesite part , what should I do?

**Comment by sids-b** [comment]
@RocMe , the edgecontroller module in edgesite watches on k8s master and all the updates are absorbed.  EdgeSite is for scenarios where there is no cloud and all components are at edge.

**Comment by jwzl** [comment]
@sids-b 
 Maybe, this is also a   scenarios where cloud cluster to manager the edge cluster.  If it can be support in our kubeedge project?

**Comment by sids-b** [comment]
@jwzl , the architecture of kubeedge supports managing edge nodes from cloud. EdgeSite is just a variant of kubeedge architecture which supports both k8s and nodes in the edge network :)

**Comment by sids-b** [comment]
Closing this issue. Please feel free to reopen or ping on slack for further discussion :)

**Comment by fei922** [comment]
> @jwzl , the architecture of kubeedge supports managing edge nodes from cloud. EdgeSite is just a variant of kubeedge architecture which supports both k8s and nodes in the edge network :)

@sids-b Could you tell me what “both k8s and nodes in the edge network” means? 
Thanks.
