### ISSUE TITLE
Kubeedge compatibility with LoadBalancer/ Ingress Controllers

### ISSUE THREAD

**Issue by vizero1** [kubeedge/kubeedge#860]
Hi guys, 

I have a kubeedge cluster running with my master in Google Cloud and my node locally.
KubeEdge version is 1.0.0
I deployed a container (with a nodejs webserver) as a pod to my node and read in the documentation about the limitation to set hostPort and contaienrPort. With setting hostPort my application is now accessible from outside the cluster. But I would rather like to use a service and an ingress controller to make my webserver accessible outside of my cluster.
Tried to deploy a nginx ingress controller to my cluster but failed.
So my question is if KubeEdge is currently supporting LoadBalancer or ingress controller to make an application accessible outside of a cluster(with the IP address of the host machine) or is hostPort the only possible way now?
Before I investigate more time on making my application accessible outside the cluster, I would like to know if there are currently any limitations. Could not find anything in the documentation.
Btw. in the documentation is a slack channel linked but that link is now invalid.
"This invite link is no longer active." Is there a possibility to contact you via another way than creating a github issue?
Thanks in advance.

**Comment by sids-b** [comment]
Thanks @vizero1 for pointing out regarding the slack link. We will fix it soon. 
You can also reach out to us via our mailing list which can be found here https://github.com/kubeedge/kubeedge#contact

You can use service to access your pods. Please see an example guide here. https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md
Currently there is an issue with port mapping but we will fix the issue soon.
The ingress support at Edge is currently in the TODO list.

**Comment by sids-b** [comment]
@vizero1 It would be great if you could join the development effort of ingress support at edge.

**Comment by vizero1** [comment]
@sids-b Thanks for the clarification.Is the edgemesh beta version released in kubeedge 1.0.0. At least it is mentioned in the Roadmap notes. Or do I need to build kubeedge by source( master branch) to test edgemesh?
Are there any notes or information how ingress support should be implemented in kubeedge? In the proposals directory I could not find anything.

**Comment by sids-b** [comment]
@vizero1 , you can try with v1.0.0 release packages as well. 

Currently there is no proposal, the effort for ingress support at edge is yet to start. We will create an issue for that soon.
