### ISSUE TITLE
Stuck at ContainerCreating

### ISSUE THREAD

**Issue by Warok21** [kubeedge/kubeedge#861]
**What happened**: the pod is not deployed

**What you expected to happen**:pod deployed

**How to reproduce it (as minimally and precisely as possible)**: my deployement fails, 
**Anything else we need to know?**:

```
ubuntu@kubernetesmaster:~/docker$ sudo kubectl get pods
NAME         READY   STATUS              RESTARTS   AGE
nvf2-h9kpr   0/1     ContainerCreating   0          4m50s
nvf2-xx2xj   0/1     ContainerCreating   0          4m50s
```

```
 sudo kubectl logs nvf2-h9kpr
Error from server: Get https://160.98.34.223:10250/containerLogs/default/nvf2-h9kpr/nvf2: dial tcp 160.98.34.223:10250: i/o timeout
```
 ```sudo kubectl describe pod nvf2-h9kpr
sudo kubectl describe pod nvf2-h9kpr
Name:               nvf2-h9kpr
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               node2/
Start Time:         Thu, 04 Jul 2019 19:43:48 +0200
Labels:             app=nvf2
                    controller-revision-hash=d597fc9f7
                    pod-template-generation=3
Annotations:        <none>
Status:             Unknown
IP:
Controlled By:      DaemonSet/nvf2
Containers:
  nvf2:
    Image:        8e467b093efc
    Port:         4000/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8mxcw (ro)
Conditions:
  Type    Status
  Ready   False
Volumes:
  default-token-8mxcw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8mxcw
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  name=edge-node
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  5m12s  default-scheduler  Successfully assigned default/nvf2-h9kpr to node2
```
If you want, here is my [deployement.yaml](https://pastebin.com/V848zWeg) 
**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by subpathdev** [comment]
can you attach the logfile from edge_core of node2?

**Comment by Warok21** [comment]
Here it is :https://pastebin.com/uy1xTcWi
Btw, I precise that my cluster seems to be OK:
```
ubuntu@kubernetesmaster:~$ sudo kubectl get nodes
NAME               STATUS   ROLES    AGE     VERSION
kubernetesmaster   Ready    master   7d16h   v1.14.1
node1              Ready    edge     67m     v1.10.9-kubeedge-0.3.0
node2              Ready    edge     14h     v1.10.9-kubeedge-0.3.0
```

**Comment by subpathdev** [comment]
yes I think I know the problem but I have to check the log file.

**Comment by subpathdev** [comment]
please have a look on line 24 of your log file
I think you have a problem with the name of your network interface

**Comment by subpathdev** [comment]
you can get the name of your network interface by using ```ip a``` and you have to add this in your edge configuration

**Comment by Warok21** [comment]
The file to modify, is 

> ~/src/github.com/kubeedge/kubeedge/edge/conf/edge.yaml

Cause I still have the same issue

**Comment by Warok21** [comment]
Nope, it's still doesn't work with the same error :
`2019-07-05 10:07:40.942 +02:00 ERROR containers/container_manager.go:936 Cannot get host IP: failed to get network interface: eth0 err:route ip+net: no such network interface
`

**Comment by subpathdev** [comment]
do you have restarted the edge?

**Comment by subpathdev** [comment]
show ```ip a s eth0``` an ip address?

**Comment by Warok21** [comment]
with :`sudo systemctl restart kubelet.service`?

**Comment by Warok21** [comment]
> show ip a s eth0 an ip address?
 Nope

**Comment by subpathdev** [comment]
kubelet service is from kuberenetes

you can stop edge_core with the kill command and the process id (to get the process id you can use ``` ps ax | grep edge_core```

**Comment by Warok21** [comment]
Just to be sure, to restart the service, wich command should i use? 
`sudo ./keadm join --` ?

**Comment by rohitsardesai83** [comment]
> Just to be sure, to restart the service, wich command should i use?
> `sudo ./keadm join --` ?

there are no systemd services configured for edge_core. You need to manually kill the edge_core process like how @subpathdev described in the previous comment.

**Comment by Warok21** [comment]
But the service start automatically?
Cause now I just have 
```
: sudo ps ax | grep edge_core
 28621 pts/18   S+     0:00 grep --color=auto edge_core
```

**Comment by subpathdev** [comment]
I think ```keadm join``` should work to start the edge_core.

**Comment by Warok21** [comment]
This will not override the changes that I've made?

**Comment by Warok21** [comment]
Apparently, this erase the changes that i've made in `/etc/kubeedge/kubeedge/edge/conf/edge.yaml
`

**Comment by subpathdev** [comment]
sorry my fault

I though the edge core would only start. You can start this via your shell:
 ```cd /etc/kubeedge/; ./edge_core```

**Comment by Warok21** [comment]
Yeah, it worked fine. Thanks 👍

**Comment by kkBill** [comment]
> show `ip a s eth0` an ip address?
# ip a s eth0
Device "eth0" does not exist.
I have the same question. And it shows above. What should I do next?

**Comment by FirasSECA** [comment]
I have the same issue when working on the deployment of the counter demo. while deploying the edge part the pod status is always stuck on  containerCreating

**Comment by Piwriw** [comment]
> I have the same issue when working on the deployment of the counter demo. while deploying the edge part the pod status is always stuck on containerCreating

Maybe you should check for your Pod logs. Counter demo is still working when I use it in February

**Comment by FirasSECA** [comment]
@Piwriw yeah yeah I had an error where the edge node couldn't pull the image but I changed it to my own repo with docker tag and it works fine
