### ISSUE TITLE
add keadm only start edge_core

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#867]
**What would you like to be added**:
it should be possible to start the edge_core via keadm

**Why is this needed**:
people only know keadm so they should use that tool to start the edge_core

**Comment by sids-b** [comment]
@subpathdev can you share a little more details ?
keadm join starts edge_core

**Comment by subpathdev** [comment]
yes but it doesn't check if you have already a configuration. It will every time create a new configuration and overwrite your changes.

**Comment by sids-b** [comment]
got it... +1

**Comment by sids-b** [comment]
@subpathdev will it be possible for you to take this one up ?

**Comment by subpathdev** [comment]
yes
/assign @subpathdev

**Comment by subpathdev** [comment]
yes of course; I will do both in the pr, which fix this issue
