### ISSUE TITLE
keadm join network interface

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#868]
**What would you like to be added**:
we should add an flag to specify the network interface or auto detection of the used network interface.

**Why is this needed**:
eth0 is not the standard network interface, so we should be able to set or autodetect them

**Comment by sids-b** [comment]
@subpathdev will it possible for you to take up this issue after the gomod change ?

**Comment by subpathdev** [comment]
Yes I will take up.
/assign subpathdev
