### ISSUE TITLE
EdgeHub Unit Tests randomly failing

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#874]
**Which jobs are failing**:
Edge Unit Test 

**Which test(s) are failing**:
EdgeHub tests in folder edgehub/ and edgehub/config

**Reason for failure**:
To test different possible configurations, the configurations in the config file are overwritten, but sometimes it take time for archaius to detect the change and load them again and test fails.

**Comment by lidiyag** [comment]
I also faced this issue. Sharing logs below:
![UTFailure](https://user-images.githubusercontent.com/14183934/61703273-e14d9580-ad5e-11e9-97f4-7ae832729e42.png)
