### ISSUE TITLE
Edge node not coming to ready state

### ISSUE THREAD

**Issue by sujithsimon22** [kubeedge/kubeedge#880]
**What happened**:
While deploying cloud core and edgecore as deployments, the following errors are observed in edgecore logs 
![image](https://user-images.githubusercontent.com/35599628/60860573-c7776300-a234-11e9-854b-82069d7915c6.png)
But the same logs show that the connection to the cloud was established

Due to this the edge node does not come to ready state

**What you expected to happen**:
The cloud and edge should connect normally and edge node should come to ready state

**How to reproduce it (as minimally and precisely as possible)**:

1. Build cloudcore and edgecore images using the docker file provided
2. Register the node with API server using node.json
3. Attach the certificates and config files as volumes and deploy the cloud core
4. Create a node port service to connect to cloud core.
5. Attach the certificates and config files as volumes and deploy edge core

The above steps are performed in the e2e test mentioned in PR #856

Cloud core and edge core pods come to running state but node does not come to ready state

**Comment by sujithsimon22** [comment]
@shouhong @kexun Could you please help me with this ?

**Comment by rohitsardesai83** [comment]
the logs mention use of closed connection. I guess #870 tries to fix this issue. 
@shouhong , can you confirm ?

**Comment by shouhong** [comment]
@rohitsardesai83 PR #870 is for bug #866 which happens when stop and then start edge node within keepalive interval.  The reproducing steps of this problem does not include stopping the edge node. It seems the reason of this problem is different from #866. 

@sujithsimon22 Does this problem only happen when deploying with K8S deployment? How about directly run the edgecontroller and  edge_core as Linux process?

**Comment by sids-b** [comment]
@sujithsimon22 ,can you please check if this issue still persists ?

**Comment by sujithsimon22** [comment]
closing this issue for the time being as it is not currently not observed. This issue can be reopened if this issue pops up again in the future
