### ISSUE TITLE
Create and register node from edge part

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#881]
**What would you like to be added**:
Now when install kubeedge, after install the cloud part, if user want to add a edge node, must create node object by user self. 
Consider create and register node all by edge part, like kubelet done in native k8s.

**Why is this needed**:
User only install edge part, no need create node manually.

**Comment by kadisi** [comment]
@fisherxu   ref #431

**Comment by kadisi** [comment]
@sids-b  @CindyXing  should we discuss it again?

**Comment by sids-b** [comment]
Would anyone like to take this one up ?
