### ISSUE TITLE
Unmarshal update request body failed, Please check the request

### ISSUE THREAD

**Issue by jwzl** [kubeedge/kubeedge#890]
When I enable the devicetwin,   the error messege from edge " Unmarshal update request body failed, Please check the request"

**Comment by sids-b** [comment]
I think #889 is a same issue.... 
cc @sujithsimon22

**Comment by jwzl** [comment]
Yes, we are same issue.
the edge sides  call dttype.UnmarshalDeviceTwinUpdate(content) to unmarshall the content.
But in the cloude sides don't call any marshall action.

**Comment by sujithsimon22** [comment]
@jwzl Yeah I think you are right, I feel maybe this might be the problem: 
![image](https://user-images.githubusercontent.com/35599628/61043556-35b65400-a3f4-11e9-92af-4b4c03cbc914.png)

@shouhong could this be the reason for the unmarshal issue we are facing ? I see that the previous code was marshalling the incoming message and sending and i see that in the current implementation we are sending the message without marshalling, maybe this is causing a problem in unmarshalling in device twin membership ?

**Comment by shouhong** [comment]
@sujithsimon22 Previously the WebSocket and Quic prototols have different WriteData() function implementions. The WebSocket implementation directly uses WebSocket interface and Quic implementation uses unified Viaduct interface. So we selected Quic implementation as the unified one for both protocols. 

I have two doubts for the above guess:
1. If the problem lies here, it means this feature does not work for Quic protocol from the beginning. Is this true?
2. In WriteData(), it marshalled the whole Message struct. But UnmarshalDeviceTwinUpdate() only unmarshalled Message.Content part. This does not match.

**Comment by jwzl** [comment]
"In WriteData(), it marshalled the whole Message struct. But UnmarshalDeviceTwinUpdate() only unmarshalled Message.Content part. This does not match."
Yes, this is the problem!@shouhong

**Comment by jwzl** [comment]
@sujithsimon22  Indeed, WriteData() finally call websocket send(), and  this method will translator.NewTran().Encode(rawData, msg)  to encode the msg, and reciver sides will call translator.NewTran().Decode(rawData, msg) to Decode the messge.  that is , message in websocket  layer should be okay.

In cloud sides, msg.content dosen't decode the msg.content,  but in edge side, devicetwin call    UnmarshalDeviceTwinUpdate() to encode the msg.content,  then device twin print the err msg:
"Unmarshal update request body failed, Please check the request"

**Comment by sujithsimon22** [comment]
@jwzl @shouhong On converting the contentData variable (the one that the code tries to unmarshal) to string and  printing it, i get the following result 
![image](https://user-images.githubusercontent.com/35599628/61102255-c475b000-a48a-11e9-9e32-2f4c73d1d908.png)
It looks to me that the content of the message is encoded

**Comment by sujithsimon22** [comment]
If we see the device controller implementation (as shown below) the structure is stored as such in the content part of the message, without any encoding. This makes me think that problem lies somewhere between sending of the message from device controller and its reception in the membership module of devicetwin
![image](https://user-images.githubusercontent.com/35599628/61102545-e9b6ee00-a48b-11e9-9ca5-b74ec9c7fbf5.png)

**Comment by jwzl** [comment]
@sujithsimon22   Finally, I found this problem is that : we call the json.Marshal(message.Msg.Content)  in github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtcontroller.go: 
`func classifyMsg(message *dttype.DTMessage) bool {
  .....
 } else if strings.Contains(message.Msg.Router.Resource, "twin/cloud_updated") {
			message.Action = dtcommon.TwinCloudSync
			content, err := json.Marshal(message.Msg.Content)
			if err != nil {
				return false
			}
			resources := strings.Split(message.Msg.Router.Resource, "/")
			message.Identity = resources[1]
			message.Msg.Content = content
			return true
		} 
}`

**But ,  this call will cause the error** since the msg.content  has been Marshaled in github.com/kubeedge/viaduct/pkg/translator/message.go when the msg send:
`func (t *MessageTranslator) Encode(msg interface{}) ([]byte, error) {
	modelMessage, ok := msg.(*model.Message)
	if !ok {
		return nil, fmt.Errorf("bad msg type")
	}

	protoMessage := message.Message{
		Header: &message.MessageHeader{},
		Router: &message.MessageRouter{},
	}

	err := t.modelToProto(modelMessage, &protoMessage)
	if err != nil {
		log.LOGGER.Errorf("failed to copy message")
		return nil, err
	}

	msgBytes, err := proto.Marshal(&protoMessage)
	if err != nil {
		log.LOGGER.Errorf("failed to marshal message")
		return nil, err
	}

	return msgBytes, nil
}
func (t *MessageTranslator) modelToProto(src *model.Message, dst *message.Message) error {
	dst.Header.ID = src.GetID()
	dst.Header.ParentID = src.GetParentID()
	dst.Header.Timestamp = int64(src.GetTimestamp())
	dst.Header.Sync = src.IsSync()
	dst.Router.Source = src.GetSource()
	dst.Router.Group = src.GetGroup()
	dst.Router.Resouce = src.GetResource()
	dst.Router.Operaion = src.GetOperation()
	if content := src.GetContent(); content != nil {
		switch content.(type) {
		case []byte:
			dst.Content = content.([]byte)
		case string:
			dst.Content = []byte(content.(string))
		default:
			bytes, err := json.Marshal(content)
			if err != nil {
				log.LOGGER.Errorf("failed to marshal")
				return err
			}
			dst.Content = bytes
		}
	}
	return nil
}
`
the msg.content will be Marshalled when send from cloud.
**But, msg.content will not be unMarshalled when recieved from edge sides**, let's show you:
`func (t *MessageTranslator) Decode(raw []byte, msg interface{}) error {
	modelMessage, ok := msg.(*model.Message)
	if !ok {
		return fmt.Errorf("bad msg type")
	}

	protoMessage := message.Message{}
	err := proto.Unmarshal(raw, &protoMessage)
	if err != nil {
		log.LOGGER.Errorf("failed to unmarshal payload")
		return err
	}
	t.protoToModel(&protoMessage, modelMessage)
	return nil
}
func (t *MessageTranslator) protoToModel(src *message.Message, dst *model.Message) error {
	dst.BuildHeader(src.Header.ID, src.Header.ParentID, int64(src.Header.Timestamp)).
		BuildRouter(src.Router.Source, src.Router.Group, src.Router.Resouce, src.Router.Operaion).
		**FillBody(src.Content)**

	// TODO:
	dst.Header.Sync = src.Header.Sync

	return nil
}

`
This is not be unmarshaled since protoMessage.content is a type of []byte.
So, the viaduct will not  unmarshal  the msg.content,  So recall the  json.Marshal(message.Msg.Content)  in github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtcontroller.go will cause this problem.

We should mask all  json.Marshal() in  github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtcontroller.go: classifyMsg().

**Comment by jwzl** [comment]
var   s=[]byte{123, 34, 101, 118, 101, 110, 116, 95, 105, 100, 34, 58, 34, 100,98,98, 49,56, 53, 53, 48, 45, 100, 48, 97, 49, 45, 52, 51, 100, 51, 45, 97, 99, 52, 98, 45, 56, 99, 102, 102, 101, 57, 59, 54, 100, 102, 49, 51, 34, 44, 34, 116, 105, 109, 101, 115, 116, 97, 109, 112, 34, 58, 49, 53, 54, 50, 57, 49, 53, 56, 55, 53, 51, 53, 56, 44, 34, 116, 119, 105, 110, 34, 58, 123, 34, 116, 101, 109, 112, 101, 114, 97, 116, 117， 114， 101， 34， 58， 123， 34， 101， 120， 112， 101， 99， 116， 101， 100， 34， 58， 123， 34， 118， 97， 108， 117， 101， 34， 58， 34， 52， 52， 34， 44， 34， 109， 101， 116， 97， 100， 97， 116， 97， 34， 58， 123， 34， 116， 105， 109， 101， 115， 116， 97， 109， 112， 34， 58， 49， 53， 54， 50， 57， 49， 53， 56， 55， 53， 51， 53， 56， 125， 125， 44， 34， 111， 112， 116， 105， 111， 110， 97， 108， 34， 58， 102， 97， 108， 115， 101， 44， 34， 109， 101， 116， 97， 100， 97， 116， 97， 34， 58， 123， 34， 116， 121， 112， 101， 34， 58， 34， 115， 116， 114， 105， 110， 103， 34， 125， 44， 34， 101， 120， 112， 101， 99， 116， 101， 100， 95， 118， 101， 114， 115， 105， 111， 110， 34， 58， 123， 34， 99， 108， 111， 117， 100， 34， 58， 51， 54， 48， 54， 57， 54， 50， 44， 34， 101， 100， 103， 101， 34， 58， 48， 125， 125， 125， 125}

print as string, then show :
{"event_id":"dbb18550-d0a1-43d3-ac4b-8cffe9;6df13","timestamp":1562915875358,"twin":{"temperature":{"expected":{"value":"44","metadata":{"timestamp":1562915875358}},"optional":false,"metadata":{"type":"string"},"expected_version":{"cloud":3606962,"edge":0}}}}

**Comment by sujithsimon22** [comment]
> @sujithsimon22 Finally, I found this problem is that : we call the json.Marshal(message.Msg.Content) in github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtcontroller.go:
> func classifyMsg(message *dttype.DTMessage) bool {
> ![classifyMsg](https://user-images.githubusercontent.com/10529845/61117803-5d91d000-a465-11e9-9417-336a2c1676cc.png)
> 
> **But , this call will cause the error** since the msg.content has been Marshaled in github.com/kubeedge/viaduct/pkg/translator/message.go when the msg send:
> ![encode](https://user-images.githubusercontent.com/10529845/61117620-e2c8b500-a464-11e9-8e8a-5e6c1d47e9d3.png)
> ![topro](https://user-images.githubusercontent.com/10529845/61117626-e65c3c00-a464-11e9-84f5-9ea33d6d3b3b.png)
> 
> the msg.content will be Marshalled when send from cloud.
> **But, msg.content will not be unMarshalled when recieved from edge sides**, let's show you:
> ![decode](https://user-images.githubusercontent.com/10529845/61117720-228f9c80-a465-11e9-8510-bfe23b4b7281.png)
> ![proto](https://user-images.githubusercontent.com/10529845/61117725-26232380-a465-11e9-9134-8cd5b23c3049.png)
> 
> This is not be unmarshaled since protoMessage.content is a type of []byte.
> So, the viaduct will not unmarshal the msg.content, So recall the json.Marshal(message.Msg.Content) in github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtcontroller.go will cause this problem.
> 
> We should mask all json.Marshal() in github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtcontroller.go: classifyMsg().

That is a great observation @jwzl . I found a similar issue in the updation of device information from edge to cloud #908

**Comment by rohitsardesai83** [comment]
@jwzl , do you want to submit a PR with a fix you described ?

**Comment by jwzl** [comment]
Yes, If I can

**Comment by kexun** [comment]
> @jwzl , do you want to submit a PR with a fix you described ?

@rohitsardesai83 @jwzl i have fixed the bug, i will push this PR later.

**Comment by sids-b** [comment]
@jwzl , @shouhong @sujithsimon22 , can you guys review #936 ? Thanks
