### ISSUE TITLE
Evaluate GRPC implementation between cloudHub and edgeHub

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#898]
**What would you like to be added**:
GRPC communication between cloudhub and edgehub

**Why is this needed**:
Currently default communication protocol between cloudHub and edgeHub is websocket. An alternate protocol QUIC was introduced to see if better performance results can be achieved. But the performance results indicated that websocket gives better performance. 

gRPC is a modern open source high performance RPC framework that can run in any environment. It can efficiently connect services in and across data centers with pluggable support for load balancing, tracing, health checking and authentication. GRPC is currently incubated in CNCF

We can evaluate the performance by using GRPC bidirectional streaming.

**Comment by kadisi** [comment]
agree,  at the seem time,  we can change model message to protobuf message.

**Comment by Baoqiang-Zhang** [comment]
+1

**Comment by subpathdev** [comment]
+1, @kadisi I think it does not depend on protobuf messages . So we can apply protobuf messages before adding GRPC or vice versa.

**Comment by sujithsimon22** [comment]
+1

**Comment by kadisi** [comment]
@subpathdev yes

**Comment by lzx258** [comment]
+1

**Comment by sids-b** [comment]
https://drive.google.com/file/d/1Qd_m0CTo5V0eVn3-k-ooXUDhssvi8hZy/view?usp=sharing 

Here are a few results of the GRPC evaluation. Currently Websocket looks to be better performing,

**Comment by sids-b** [comment]
We are having better performance results in Websocket than GRPC as seen in the doc. Should we close this issue ?
@subpathdev @fisherxu @edisonxiang @kadisi @subpathdev

**Comment by subpathdev** [comment]
can we close this now?
