### ISSUE TITLE
support Active/standby mode on edge

### ISSUE THREAD

**Issue by Baoqiang-Zhang** [kubeedge/kubeedge#900]
**What would you like to be added**: we want implement active/standby mode on edge nodes, it will help eedge node and application(service) with high availability.

**Why is this needed**:
use case:  
1.user have two edge node and register to kubeedge by active/standby mode;
2.user create application on kubeedge and it will run on active node;
3.in case of active node down, standby node will change to active node and setup the application.
it will help eedge node and application(service) with high availability.

**Comment by jwzl** [comment]
+1

**Comment by sids-b** [comment]
@Baoqiang-Zhang will it be possible for you to take this one up ?
