### ISSUE TITLE
keadm init crash

### ISSUE THREAD

**Issue by luguanglong** [kubeedge/kubeedge#901]
**What happened**:
A crash happend when execute "keadm init" on not supportted systems(eg:debian). 

**What you expected to happen**:
I know now only support ubuntu.  But it should not crash directly. It should exit  with some errors.

**How to reproduce it (as minimally and precisely as possible)**:
Execute "keadm init" on systems other than ubuntu and centos.

**Anything else we need to know?**:
The crash happens because the function GetOSInterface() returns nil on not supported systems and its callers does not check it's return value.

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
debian 10 (buster)
- Kernel (e.g. `uname -a`):
- Others:

**Comment by subpathdev** [comment]
@luguanglong could you raise a pr to this bug?

After debian buster is stable we can think about adding debian buster to the list of supported os
