### ISSUE TITLE
store device values (mind term) on the edge

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#906]
**What would you like to be added**:
Add influxdb or timescale db to store device values on the edge

**Why is this needed**:
In the current state we store the value of an device until a new value has arrived. I think it's a nice feature to store values over a longer time and I think a time serious db is the best way to do this. After a specific time the values should be deleted automatically. (I think 2 weeks are a good default value for this)

Thoughts?

**Comment by rohitsardesai83** [comment]
@subpathdev , this is a valid requirement for data processing/storage at the edge.
we need to consider the resource constraints at the edge while selecting the database to use.
Data ingested into the edge via the event bus can be in varied formats like images, text , video frames etc.
Do we support storing all such data formats at the edge ?
We need deeper analysis on this. Can we start documenting and have further discussions ?

**Comment by subpathdev** [comment]
I think we should support storing all data types. If we don't support these we are making restrictions on the usage of kubeedge.

Where do you like to have these documentation and discussion? I think an issue is an good first place.
(We can discuss further points of this on the meeting in 3 weeks (next week I have a training :( )

**Comment by jwzl** [comment]
+1
I agree @subpathdev , We should support storing all data types.
