### ISSUE TITLE
integration/e2e tests are required for edged

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/kubeedge#91]
Currently we are manually running integration/e2e tests for edged, xref: https://github.com/kubeedge/kubeedge/tree/master/test. I think we should automated all these procedures and write some test cases.

**Comment by m1093782566** [comment]
cc @sids-b

**Comment by sids-b** [comment]
@pavan187 can own this.

**Comment by pavan187** [comment]
@m1093782566 , Yes, i'm already working on this task. currently designing the test cases, will update the test to kubeedge as soon as possible.

**Comment by m1093782566** [comment]
@pavan187 

Can we close this issue now?

**Comment by sids-b** [comment]
We have some integration/e2e test cases for edged in place already. We will always keep improving/adding more test cases.
