### ISSUE TITLE
Unifying logging library to klog

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#913]
The `beehive logger` ["github.com/kubeedge/beehive/pkg/common/log"]("github.com/kubeedge/beehive/pkg/common/log")
E.g. `log.LOGGER.Infof("ServiceBus receive msg")`

and glog ["github.com/golang/glog"]("github.com/golang/glog")
E.g. `glog.V(8).Infof(format, data)`

Today both of these logging libraries are used in edge_core, which is expensive to maintain and confusing to end users.
As we are going to upgrade edged base to k8s-v1.15, we'd better get this fixed first.
And choosing glog seems an easier way to stay align with upstream kubernetes.

The pros are:
1. logging liberary widely used by upstream kubernetes and subprojects
2. support numeric log level
3. already used in bluetooth_mapper, edged, integration test, e2e test and performance test

Any comments?

/cc @rohitsardesai83 @sids-b @qizha @kevin-wangzefeng @subpathdev @chendave @kadisi @edisonxiang @sujithsimon22 @Baoqiang-Zhang @kexun 

----

### 2019.07.17 Updates:
Kubernetes has moved to klog, we should move to klog directly instead of glog.

----
### 2019.08
Ongoing Pull Requests:
- [x] beehive : https://github.com/kubeedge/kubeedge/pull/1164
- [x] viaduct : https://github.com/kubeedge/viaduct/pull/20
- [x] kubeedge:  https://github.com/kubeedge/kubeedge/pull/1019

**Comment by kevin-wangzefeng** [comment]
Agreed, this useful.

**Comment by chendave** [comment]
sound good to me.

**Comment by kadisi** [comment]
agree

**Comment by edisonxiang** [comment]
Hey @fisherxu, +1
I saw that lots of external kubernetes projects has using "k8s.io/klog" instead of glog.
What about klog?

**Comment by fisherxu** [comment]
@edisonxiang `klog` is fine, actually `klog` is forked from `glog`, and we can use the `klog`. ref: [https://github.com/kubernetes/klog](https://github.com/kubernetes/klog)

**Comment by sujithsimon22** [comment]
Agreed, this would help in avoiding confusion among new contributors regarding which logging libraries to use

**Comment by kadisi** [comment]
That makes sense， I'm interested in this.

**Comment by kevin-wangzefeng** [comment]
Just went through a few relevant upstream issues (xref: https://github.com/kubernetes/kubernetes/issues/70264), and double checked K8s v1.15.0 code, glog has been replaced with klog, so let's move to klog as well.

**Comment by kevin-wangzefeng** [comment]
Revised issue title and description to reflect discussion updates.

**Comment by fisherxu** [comment]
> We should first replace the log of beehive with klog, and then let kubeedge use beehive klog.

@kadisi How about let's kubeedge and beehive use klog directly, and init klog in kubeedge components

**Comment by kadisi** [comment]
@fisherxu , good idea.   do we need to create new branch for kubeedge, beehive and viaduct to implement this feature  ?  and make a track task.

**Comment by kadisi** [comment]
@fisherxu @rohitsardesai83 @kevin-wangzefeng @chendave @edisonxiang 

this is track task:

- [ ] beehive : [unifying loging library to klog ](https://github.com/kubeedge/beehive/pull/26)
- [ ] viaduct : [unifying loging library to klog](https://github.com/kubeedge/viaduct/pull/20)
- [ ] kubeedge:  TODO

**Comment by fisherxu** [comment]
@kadisi Does this issue have been resolved? Or we can close it.

**Comment by kadisi** [comment]
@fisherxu yes, resolved
