### ISSUE TITLE
Pod not coming up when edge and cloud runs on single machine

### ISSUE THREAD

**Issue by lidiyag** [kubeedge/kubeedge#923]
**What happened**:
While trying to deploy an application with edge and cloud running on same machine, the pod coming up fails and gives message as "ConatinerCannotRun".
![PodCreationStatus](https://user-images.githubusercontent.com/14183934/61365780-ee254180-a8a5-11e9-907c-2464f22deec4.png)
Sharing the edge core logs below:
![PodStartFailedError](https://user-images.githubusercontent.com/14183934/61365814-0006e480-a8a6-11e9-8919-e26dc9061513.png)

**What you expected to happen**:
Pod should come to "Running" status

**How to reproduce it (as minimally and precisely as possible)**:
Clone latest code
Run cloud and edge on same machine
Deploy application and see whether pod is running

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by fisherxu** [comment]
Seems some error about network, does docker run can start the Container?

**Comment by sids-b** [comment]
I think both and cloud are not supposed to run on the same machine. Kubelet will keep killing the edged spawned containers and edged will kill the kubelet containers.

**Comment by rohitsardesai83** [comment]
@lidiyag , can we close this issue ?

**Comment by sids-b** [comment]
Closing this issue

**Comment by sids-b** [comment]
Also @lidiyag , you need to delete the existing pause and nginx containers which might not have been deleted as per the error logs shown in edged.... without deleting them, new containers won't come up even if the cloud components are run on a seperate node.
