### ISSUE TITLE
Unused function "Confirm(msg ID string,content interface{}) error" in dtcontext.go

### ISSUE THREAD

**Issue by lidiyag** [kubeedge/kubeedge#94]
Unused code in the file dtcontext.go(pkg/devicetwin/dtcontext)

![confirmfunction](https://user-images.githubusercontent.com/14183934/51365258-66809500-1b05-11e9-9c1b-bfa9a7695ef4.png)

**Comment by m1093782566** [comment]
@lidiyag 

We can associated this issue in PR by typing `Fixes #94` in PR description content.

FYI.
