### ISSUE TITLE
optimization / refactor e2e

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#951]
**What would you like to be added/modified**:
- optimize / refactor our e2e tests so that we avoid running tests like repeated creation / deletion of pods
- remove tests which do much more than check e2e 

**Why is this needed**:
- speed up ci

**Comment by subpathdev** [comment]
please make the e2e more stable

**Comment by sids-b** [comment]
+1

**Comment by sids-b** [comment]
@subpathdev , is is possible for you to take this one up ?
