### ISSUE TITLE
Edgemesh Test Env Problem 

### ISSUE THREAD

**Issue by liyongxian** [kubeedge/kubeedge#956]
When docker  pull docker.io/ytsobd/edgemesh_init:v1.0, the image does not exist.

![1111111](https://user-images.githubusercontent.com/18571576/61774085-b3cd1e80-ae28-11e9-94cb-d647d84c4e68.jpg)

I can not build the image in kubeedge code,beause edgemesh module does not contain Dockerfile. 
Thanks.
@CindyXing

**Comment by liyongxian** [comment]
@sids-b Please check it.
Thanks.

**Comment by sids-b** [comment]
This is the init container Dockerfile
https://github.com/kubeedge/kubeedge/blob/master/edgemesh/tools/initContainer/deb/Dockerfile

**Comment by sids-b** [comment]
Let me give it a try to pull the image and I will get back to you

**Comment by liyongxian** [comment]
@sids-b  OK.Thanks.I got it.
In Edgemesh test env config guide,EdgeMesh relies on Containerd,I am confused.Why Not Docker.
Thanks.

**Comment by sids-b** [comment]
@liyongxian the document has been updated to use docker as well. Please let us know if it works out for you. Also the image has been pushed to kubeedge dockerhub repo.

Closing this issue
