### ISSUE TITLE
kubeedge ci add Codecov

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#959]
**What would you like to be added/modified**:

kubeedge ci need add codecov

**Why is this needed**:

for improve kubeedge code review workflow and quality, i suggest add codecov for ci.

like : [Codecov](https://codecov.io/)

**Comment by edisonxiang** [comment]
Thanks @kadisi Good idea:) Currently are these some projects which are using Codecov

**Comment by kadisi** [comment]
@edisonxiang such as [containerd](https://github.com/containerd/containerd)
