### ISSUE TITLE
Use cobra command and Remove init to use explicit call

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#971]
Now in some components like cloud/edge core, all used init to load config and register sub modules. And even if we want to only print the version of component, the init func still be called and print lots of logs, so we need to `Remove init to use explicit call` and `Use cobra command`.

The task lists:

- [x] Use cobra command and Remove init in cloud part #988 
- [ ] Use cobra command and Remove init in edge core
- [ ] Use cobra command and Remove init in edgesite
- [ ] TBD

/cc @rohitsardesai83 @sids-b @kevin-wangzefeng @qizha @edisonxiang @Baoqiang-Zhang @kadisi @chendave @subpathdev

**Comment by chendave** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1, this is important, we should do it.

**Comment by kexun** [comment]
+1， i will do it.

**Comment by fisherxu** [comment]
@kexun Sure, please just go ahead.

**Comment by rohitsardesai83** [comment]
:+1:
