### ISSUE TITLE
replace gometalinter with golangci-lint 

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#978]
**What would you like to be added/modified**:
to verify the edge code we are using gometalinter. This repo has been marked as deprecated so we didn't should use it. (https://github.com/alecthomas/gometalinter)

**Why is this needed**:
We didn't should use deprecated tools to check our code.

**Comment by subpathdev** [comment]
you can simple replace gometalinter with golangci-lint run

**Comment by fisherxu** [comment]
+1

**Comment by kadisi** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Agreed, golangci-lint is also recommanded by gometalinter

**Comment by ziyi-yan** [comment]
Hi, I'd like to handle this issue and start being familiar with the project. Could I have it assigned to me?
