### ISSUE TITLE
Consider rename the edgecontroller

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/kubeedge#980]
Now the cloud part component under cloud/cmd called edgecontroller, under cloud/pkg/ contains 3 modules cloudhub/controller/devicecontroller.

![image](https://user-images.githubusercontent.com/28776356/62112096-a90d0080-b2e4-11e9-81be-bc7bb2a1c519.png)

While `controller` under cloud/pkg is not clear, how about rename it to edgecontroller?

**Vote 1:** `controller` under cloud/pkg 
i. **Still called controller**
ii. **edgecontroller**  // clarify interaction with the edge
iii. **Any suggestions**？

If rename `controller` under cloud/pkg to `edgecontroller`, cloud part component under cloud/cmd also can be renamed.

**Vote 2:** cloud part under cloud/cmd
i. **Still called edgecontroller**
ii. **edge-operator** // more cloud native, clarify that operate thing on cloud 
iii. **cloud-core**  // corresponding to edge edge-core, maybe not friendly to new component added to cloud
iv. **Any suggestions**？

/cc @rohitsardesai83 @sids-b @qizha @kevin-wangzefeng @subpathdev @chendave @kadisi @edisonxiang @sujithsimon22 @Baoqiang-Zhang @kexun

----

### 2019.08.01 Updates:

Will named cloud-core to cloudcore 

The task list:

- [ ] change the code and directory
- [ ] change the deploy&install part
- [ ] change the docs and diagram

**Comment by edisonxiang** [comment]
Vote 1: controller under cloud/pkg
ii. edgecontroller

Vote 2: cloud part under cloud/cmd
iii. cloud-core

Just one vote:)

**Comment by chendave** [comment]
same voting as Edison, 

Vote 1: controller under cloud/pkg
ii. edgecontroller

Vote 2: cloud part under cloud/cmd
iii. cloud-core  //The code structure looks more clear.

**Comment by sids-b** [comment]
+1 to edison

**Comment by sujithsimon22** [comment]
+1 to  Edison
Vote 1: controller under cloud/pkg
ii. edgecontroller

Vote 2: cloud part under cloud/cmd
iii. cloud-core

**Comment by jwzl** [comment]
Vote 1: controller under cloud/pkg
ii. edgecontroller

Vote 2: cloud part under cloud/cmd
iii. cloud-core is more better.

And some other proposal:
kedge-cloud?      the cloud side of kubeedge

**Comment by kadisi** [comment]
@edisonxiang  +1

**Comment by kevin-wangzefeng** [comment]
Vote 1: controller under cloud/pkg
- [ ] keep the name controller
- [x] edgecontroller // clarify interaction with the edge

Vote 2: cloud part under cloud/cmd
- [ ] keep the name edgecontroller
- [x] edge-operator // more cloud native, operator can be a collection of multiple controllers, just like it as now. And it's compatible either we keep cloudhub inside or later on make cloudhub an individual component.
- [ ]  cloud-core // symmetric to edge-core at edge, but not quite self-explaining, people may have no idea what it contains.

**Comment by subpathdev** [comment]
+1 to edison

**Comment by kexun** [comment]
Vote 1: controller under cloud/pkg
ii. edgecontroller

Vote 2: cloud part under cloud/cmd
iii. cloud-core

**Comment by Baoqiang-Zhang** [comment]
Vote 1: controller under cloud/pkg
ii. edgecontroller

Vote 2: cloud part under cloud/cmd
iii. cloud-core

**Comment by glenn-lg** [comment]
+1 to Edison

Vote 1: controller under cloud/pkg
ii. edgecontroller

Vote 2: cloud part under cloud/cmd
iii. cloud-core

**Comment by fisherxu** [comment]
Thanks all your suggestions. :)  Seems most of ours support changing to that:
`controller` under `cloud/pkg` to `edgecontroller`, cloud part under `cloud/cmd` to `cloud-core`.

So let's just do it, will add a task list to issue description.

**Comment by kevin-wangzefeng** [comment]
#988 Accepted, and we need to document this change in v1.1 release note.

**Comment by fisherxu** [comment]
> #988 Accepted, and we need to document this change in v1.1 release note.

Sure.

**Comment by sids-b** [comment]
Closing this issue as we have merged the PR

**Comment by sids-b** [comment]
Thanks @fisherxu
